### ISSUE TITLE
Destination routing to incorrect Pod IPs

### ISSUE THREAD

**Issue by styler** [linkerd/linkerd2#10003]
### What is the issue?

We are seeing routing issues between LinkerD containers. (essentially a mismatch between the Kubernetes EndpointSlice and LinkerD Routes)

The discrepancy occurs after an error:
<img width="946" alt="example" src="https://user-images.githubusercontent.com/10061593/207413753-674f5ce7-75ac-4366-a037-fb52fa440fda.png">
> time="2022-12-13T10:26:31Z" level=error msg="Unable to create new address:unable to fetch pod production/gatekeeper-789c7d94bf-bz67w: pod \"gatekeeper-789c7d94bf-bz67w\" not found" addr="8086' component=service-publisher ns=production port=80 svc=gatekeeper

As shown in the graph above, the misalignment occurs exactly when the error messages happen.

We have also manually checked the difference with `kubectl describe endpointslice -l app=gatekeeper` & `linkerd diagnostics endpoints gatekeeper.production.svc.cluster.local:80`

```
Running for svc: gatekeeper...

K8S EndpointSlice (gatekeeper-z24b8)
count: 15
ips: [10.12.0.101 10.12.14.49 10.12.27.134 10.12.5.7 10.12.37.11 10.12.39.183 10.12.8.59 10.12.18.209 10.12.3.11 10.12.43.4 10.12.51.222 10.12.10.15 10.12.2.148 10.12.28.67 10.12.32.94]

Linkerd
count: 16
ips: [10.12.27.134 10.12.51.222 10.12.19.29 10.12.0.101 10.12.14.49 10.12.32.94 10.12.5.7 10.12.43.4 10.12.2.148 10.12.28.67 10.12.18.209 10.12.10.15 10.12.39.183 10.12.8.59 10.12.37.11 10.12.3.11]


Mismatch?
count: 1
ips: [10.12.19.29]
```

At this point, the `gatekeeper` service gets out of sync, and some proxies try to route traffic to this pod.

<img width="1920" alt="Screenshot 2022-12-13 at 19 34 17" src="https://user-images.githubusercontent.com/10061593/207416826-590554dd-4254-4cbd-a6e5-c1f00695b5df.png">

**Example screenshot from Grafana Loki showing the increased amount of proxy errors.**

> {"timestamp":"[597593.988456s]","level":"WARN","fields":{"message":"Failed to connect","error":"connect timed out after 1s"},"target":"linkerd_reconnect","spans":[{"name":"outbound"},{"addr":"10.20.3.149:80","name":"proxy"}],"threadId":"ThreadId(1)"}

Related links
- https://github.com/linkerd/linkerd2/blob/main/controller/api/destination/watcher/endpoints_watcher.go#L841
- https://github.com/linkerd/linkerd2/blob/main/controller/api/destination/watcher/endpoints_watcher.go#L748

### How can it be reproduced?

Unknown at this stage.

### Logs, error output, etc

```
{"message":"Failed to connect","error":"connect timed out after 1s"}
{"message":"Failed to connect","error":"connect timed out after 1s"}
{"message":"Failed to connect","error":"connect timed out after 1s"}
{"message":"Failed to connect","error":"connect timed out after 1s"}
{"message":"Failed to connect","error":"connect timed out after 1s"}
```

### output of `linkerd check -o short`

```text
❯ linkerd check -o short
Linkerd core checks
===================

linkerd-identity
----------------
‼ issuer cert is valid for at least 60 days
    issuer certificate will expire on 2022-12-15T15:16:33Z
    see https://linkerd.io/2.12/checks/#l5d-identity-issuer-cert-not-expiring-soon for hints

Linkerd extensions checks
=========================

linkerd-viz
-----------
‼ prometheus is installed and configured correctly
    missing ClusterRoles: linkerd-linkerd-viz-prometheus
    see https://linkerd.io/2.12/checks/#l5d-viz-prometheus for hints

Status check results are √
```

### Environment

- Kubernetes Version: 1.24.5-gke.600
- Cluster Environment: GKE
- Host OS: Container-Optimized OS with containerd (cos_containerd)
- LinkerD Version: 2.12.3
- Certs are managed via cert-manager (And rotate every 48 hours)

Installed via HELM

### Possible solution

K8s has cleaned up the pod, and the pod no longer exists in the endpoint slice; however, it remains in the linkerd route table and never gets fixed.
It seems to be a race condition between the k8s API and the linkerd watcher.  Linkerd is responding to events on the endpointslice; however, by the time linkerd goes to fetch information about the pod being removed, it's already too late, and the pod is gone, generating the error message.

### Would you like to work on fixing this bug?

None

**Comment by dwilliams782** [comment]
I reported the same a while back but it got closed as we couldn't find distinct repro steps: https://github.com/linkerd/linkerd2/issues/8956

We're also GKE, that is very unlikely to be a coincidence. We only ever saw the error with one daemonset and couldn't repro with any other workload. You can workaround it by using endpoints rather than slices by setting `-enable-endpoint-slices=false`, though it shouldn't be required. I'm glad it's not just us! 

@kleimkuhler you may be interested that it's been reproduced as you were involved in my thread.

**Comment by styler** [comment]
@dwilliams782 Disabling endpointSlices is indeed helping the problem. 👏

**Comment by kleimkuhler** [comment]
As mentioned in #8956 I agree this is an issue, but it's been unfortunately hard to reproduce. I'd really like to figure out what's going on here, but I was unable to after some manual churning of Pods/Nodes that I explained in #8956 [here](https://github.com/linkerd/linkerd2/issues/8956#issuecomment-1212427347). @styler is there anything else you can add that you may not have mentioned here, or that did come up in discussion with @dwilliams782 on #8956?

Does it seem to be related to Nodes spinning down, Pods getting deleted for some other reason, happening with certain cluster events, or anything else that comes to mind?

Obviously turning off EndpointSlice support is not ideal so figuring out a fix for this is important. Getting something that we can reproduce would be super helpful.

**Comment by scott-haines-se** [comment]
@kleimkuhler I am a colleague of @styler and have been debugging along side him.

While we cannot pinpoint exactly how to reproduce the issue, we have noticed that it seems to be related to an aggressively scaling HPA.  The workload being shown as an example in this thread has an HPA which will scale up & down very rapidly.  Not every scaling activity causes the de-sync, however, we suspect (unproven) that it could be a scale up & scale down in short succession which results in the de-sync manifesting.

We are willing to do live troubleshooting sessions to help understand and fix this issue.  We understand that it's difficult to reproduce.
