### ISSUE TITLE
Add Block Chomping Indicator to Strip Trailing New Lines in Config Map

### ISSUE THREAD

**Issue by avdicl** [linkerd/linkerd2#10012]
### What problem are you trying to solve?

When importing and decrypting a cert using azure key vault plugin and argo, a trailing new line is added and can't be removed, causing linkerd control plane to crash upon deployment.

When using ArgoCD and Azure Key Vault Plugin to manage Linkerd via Helm, the `identityTrustAnchorsPEM` value gets passed from Azure Key Vault with a trailing new line. This trailing new line makes its way into the config map `linkerd-identity-trust-roots` causing Linkerd control plane to crash upon deployment.

### How should the problem be solved?

Add a block chomping indicator to strip trailing new lines in the config map. 

`ca-bundle.crt: |{{.Values.identityTrustAnchorsPEM | trim | nindent 4}}` -> `ca-bundle.crt: |-{{.Values.identityTrustAnchorsPEM | trim | nindent 4}}`

### Any alternatives you've considered?

There aren't any other alternatives when using Azure Key Vault due to how multi-line secrets are created. Azure forces this trailing new line. 

### Would you like to work on this feature?

yes

**Comment by avdicl** [comment]
Forgot to mention the suggested change is in this file: 
https://github.com/linkerd/linkerd2/blob/main/charts/linkerd-control-plane/templates/identity.yaml

**Comment by kleimkuhler** [comment]
Stripping trailing newlines at the end of the value sounds good. I wasn't too familiar with YAML multiline formatting but [this](https://yaml-multiline.info) was helpful.
