### ISSUE TITLE
Make Cache Sync Timeout Configurable

### ISSUE THREAD

**Issue by steve-gray** [linkerd/linkerd2#10036]
### What problem are you trying to solve?

Cache Sync timeout in control plane is currently 60 seconds hard-coded. There's a potential scenario where if something starts taking longer than this, things end up in a death spiral.

https://github.com/linkerd/linkerd2/blob/4dbb027f48fb1bf87c518e3a8bf90a87f5e5bf5d/controller/k8s/k8s.go#L23

### How should the problem be solved?

Make configuration adjustable for this value.

### Any alternatives you've considered?

Looked at some other options/potential causes of the cache sync timeout being hit in this Slack thread on #linkerd2 - but nothing leaps out.

https://linkerd.slack.com/archives/C89RTCWJF/p1671605753397439

### How would users interact with this feature?

Helm values.yaml or configmap option.

### Would you like to work on this feature?

None

**Comment by gkarthiks** [comment]
I would love to patch this if the maintainers agree on that.

**Comment by olix0r** [comment]
I'm -1 on adding configuration here. Why do we need a hard timeout at all? It seems like we should keep the existing timeout but, when it elapses, start logging warnings and let things continue until they can complete.

**Comment by olix0r** [comment]
Though, we'll need to take care that the admin server starts serving liveness probes before we start syncing caches and that readiness probes only succeed when caches have synced.
