### ISSUE TITLE
jaeger and viz helm charts install resources in default namespace

### ISSUE THREAD

**Issue by joebowbeer** [linkerd/linkerd2#10043]
### What is the issue?

1️⃣ The jaeger helm chart creates four resources without a namespace:

https://github.com/linkerd/linkerd2/blob/main/jaeger/charts/linkerd-jaeger/templates/namespace-metadata-rbac.yaml

Resources:
* ServiceAccount namespace-metadata
* Role namespace-metadata
* RoleBinding namespace-metadata

https://github.com/linkerd/linkerd2/blob/main/jaeger/charts/linkerd-jaeger/templates/namespace-metadata.yaml

Resource:
* Job namespace-metadata

2️⃣ The viz helm chart creates four resources without a namespace:

https://github.com/linkerd/linkerd2/blob/main/viz/charts/linkerd-jaeger/templates/namespace-metadata-rbac.yaml

Resources:
* ServiceAccount namespace-metadata
* Role namespace-metadata
* RoleBinding namespace-metadata

https://github.com/linkerd/linkerd2/blob/main/viz/charts/linkerd-jaeger/templates/namespace-metadata.yaml

Resource:
* Job namespace-metadata

3️⃣ ditto for multicluster charts

### How can it be reproduced?

It's obvious from looking at the template source.

I discovered this by trying to install linkerd-jaeger and having my no-default-namespace admission policy deny my request.

### Logs, error output, etc

policy disallow-default-namespace -> resource default/ServiceAccount/namespace-metadata failed: 
1. validate-namespace: validation error: Using 'default' namespace is not allowed. rule validate-namespace failed at path /metadata/namespace/ 

policy disallow-default-namespace -> resource default/Job/namespace-metadata failed: 
1. validate-podcontroller-namespace: validation error: Using 'default' namespace is not allowed for pod controllers. rule validate-podcontroller-namespace failed at path /metadata/namespace/

Note: The Role and RoleBinding are also missing a namespace

### output of `linkerd check -o short`

```text
N/A
```

### Environment

N/A

### Possible solution

Add `namespace: {{ .Release.Namespace }}` to the four resources where it is missing.

### Additional context

I think this was a regression that happened in #6635

### Would you like to work on fixing this bug?

yes

**Comment by joebowbeer** [comment]
@alpeb I am templating the chart (v30.4.5) so that it can be kustomized and installed by ArgoCD:

```bash
helm template linkerd ./v30.4.5 -n linkerd-jaeger
```

What I see in the jaeger and viz charts source, is that _every_ resource is namespaced _except_ these four, but  `helm template -n` is not supplying a namespace for these four resources.

I didn't realize there might be a difference between `install` and `template` with respect to namespace injection, but given that ever other resource in the charts is namespaced, I suggest adding it both for consistency and for `template` correctness.

**Comment by alpeb** [comment]
Good point :100: , I had forgotten about that `linkerd template` gotcha!
