### ISSUE TITLE
Expose `terminationGracePeriodSeconds` for configuration via Linkerd Helm Charts

### ISSUE THREAD

**Issue by deusxanima** [linkerd/linkerd2#10058]
### What problem are you trying to solve?

Configuring `proxy.waitBeforeExitSeconds` on the linkerd control-plane helm charts applies the setting to Linkerd control plane proxies as well as data plane proxies. This can result in errors when the default k8s `terminationGracePeriod` is set lower than the `proxy.waitBeforeExitSeconds` value such as the following:

```
Exec lifecycle hook ([/bin/sleep 40]) for Container "linkerd-proxy" in Pod "linkerd-destination-9559586c5-g9jns_linkerd(e33e8d02-66ca-42fa-9a7c-0ea45bda814a)" failed - error: command '/bin/sleep 40' exited with 137: , message: ""
```

For instances like this it would be useful to override the `terminationGracePeriodSeconds` to a higher value to allow time for the linkerd proxy preStop hook to complete, however, there's not currently an easy way to override this for the Linkerd control plane pods.

### How should the problem be solved?

Expose `terminationGracePeriodSeconds` for configuration via Linkerd Helm Charts.

### Any alternatives you've considered?

Expose an option to NOT apply the "proxy.waitBeforeExitSeconds" to the Linkerd control plane proxies.

### How would users interact with this feature?

Helm Charts

### Would you like to work on this feature?

None

**Comment by kleimkuhler** [comment]
The alternative solution of not applying the `proxy.waitBeforeExitSeconds` to control plane workloads feels like the right path forward here. We know that those workloads should be able to terminate within the `terminationGracePeriod`, so if we can solve that issue without adding more configuration then that would be great.

@deusxanima if you're interested in working on this please feel free to ask any questions that you may have!

**Comment by deusxanima** [comment]
I'd feel more comfortable having a Linkerd maintainer work on it to make sure nothing gets missed/it's tightly scoped, but open to an initial draft PR if it would help ensure we get it into the upcoming release.

**Comment by kleimkuhler** [comment]
Sure let's touch base off GH and figure out a plan for working on this!
