### ISSUE TITLE
Cannot monitor cluster filesystem usage on Linode. Grafana dashboard has broken regex. 

### ISSUE THREAD

**Issue by nodox** [linkerd/linkerd2#10057]
### What is the issue?

On Linode, the main device drive is `/dev/sda`.  The panel found here is broken because the regex does not find a match.

Dashboard
> http://localhost:50750/grafana/d/k8s/kubernetes-cluster-monitoring-via-prometheus?orgId=1&refresh=1m&editPanel=7 

Source code can be found here

> https://github.com/linkerd/linkerd2/blob/main/grafana/dashboards/kubernetes.json#L453

### How can it be reproduced?

Steps

```
linkerd viz dashboard

# open link in browser
http://localhost:50750/grafana/d/k8s/kubernetes-cluster-monitoring-via-prometheus?orgId=1&refresh=1m&editPanel=7
```

### Logs, error output, etc

N/A

### output of `linkerd check -o short`

Status check results are √

### Environment

k3s on Linode

### Possible solution

The proper regex should match when there is not a number present at this location in a [source](https://github.com/linkerd/linkerd2/blob/main/grafana/dashboards/kubernetes.json#L453). Add a question mark to make the matching of numbers optional.

```
# GOOD
^/dev/[sv]d[a-z][1-9]?$

# BAD
^/dev/[sv]d[a-z][1-9]$ 
```

### Would you like to work on fixing this bug?

Sure

**Comment by alpeb** [comment]
Thanks for the report @nodox , the proposed solution looks good to me :+1:  Would you like to issue a PR with it? Also, this particular dashboard was sourced from the Grafana community, so it might make sense to port the fix upstream, or check if they have an update (if it's still maintained). But we need to figure first _where_ is that located...
