### ISSUE TITLE
Expose configuration for outbound proxy cache eviction timeout

### ISSUE THREAD

**Issue by jeremychase** [linkerd/linkerd2#10078]
Configuration for [LINKERD2_PROXY_OUTBOUND_DISCOVERY_IDLE_TIMEOUT](https://github.com/linkerd/linkerd2-proxy/blob/e8fca296797da76e7ccbb3ce60828f2ac883167c/linkerd/app/src/env.rs#L272) should be via Kubernetes annotation.

This issue is intended to replicate the [ver.slow-outbound-evict.b88228fa](https://github.com/users/olix0r/packages/container/l2-proxy/58451015?tag=ver.slow-outbound-evict.b88228fa) package, but with user configuration.

**Comment by risingspiral** [comment]
https://www.notion.so/buoyantio/Cache-configuration-discovery-ba4a465ae3b74d4aab2c228c77cc8822

**Comment by mateiidavid** [comment]
First PR to configure them at install time merged. One left to go.

**Comment by risingspiral** [comment]
This was released in 2.13.4
