### ISSUE TITLE
known-http-port option as alternative to skip or opaque ports

### ISSUE THREAD

**Issue by kellybirr** [linkerd/linkerd2#10146]
### What problem are you trying to solve?

Rather than resolving protocol detection timeouts by skip or opaque ports, I'd like to just specify what I know is an http port and skip detection.

I get these all the time:

```
New configuration alert for Production-1 / ingress-nginx / ingress-nginx-controller
Inbound protocol detection timeout on port 8080
```

This is an HTTP port, It looks like the client is just being lazy or it's a weak DOS attack where it's opening and not sending.

NOTE: I specifically use 8080 and 44300 on the pod to avoid running ingress controllers as privileged/root.  The LoadBalancer service exposes these as 80 and 443.

### How should the problem be solved?

a new annotation

### Any alternatives you've considered?

a possible alternative, specific to external facing service ports to deal with bad client behavior.

### How would users interact with this feature?

annotate Nginx ingress pods to specify 8080 and 44300 as http ports.

### Would you like to work on this feature?

no

**Comment by kellybirr** [comment]
Normally I'm happy to contribute.  However, I don't code in Rust (yet) so this is outside my current skillset.  This doesn't seem like something that anyone would want a Rust novice modifying.

**Comment by mateiidavid** [comment]
Hey @kellybirr if you're on a recent version of Linkerd, you can actually skip the inbound protocol detection by using a `Server` for that port. The `Server` resources contains a `proxyProtocol` field, that when set to anything other than `unknown` will skip protocol detection on the inbound side. We support `opaque`, `http`, `grpc` and `http2`. Would this do the trick?

https://linkerd.io/2.12/reference/authorization-policy/#server-spec -- docs in case you want to read more on the topic.

**Comment by kellybirr** [comment]
It does sound like that would solve my issue.
