### ISSUE TITLE
user-reported security scan finding

### ISSUE THREAD

**Issue by wmorgan** [linkerd/linkerd2#10164]
### What is the issue?

A user reported a security scan finding for Linkerd's controller image in 2.12.3:

```
| PRISMA-2022-0227 | high     | 7.50 | github.com/emicklei/go-restful/v3 | v3.8.0  | fixed in v3.10.0        | > 6 months | < 1 hour   | github.com/emicklei/go-restful/v3 | 
```

This issue has to do with [how go-restful handles certain URLs](https://github.com/emicklei/go-restful/issues/497) that allows REST authentication to be bypassed.

Since Linkerd does not use REST authentication I believe this does not present a real issue for us. However, for hygiene reasons we may want to upgrade go-restful at some point.

### How can it be reproduced?

Run the security scan software.

### Logs, error output, etc

See above

### output of `linkerd check -o short`

Unknown

### Environment

Unknown

### Would you like to work on fixing this bug?

None

**Comment by olix0r** [comment]
No idea why dependabot hasn't flagged this -- and there are no open dependency security alerts on this repo...

FWIW, Linkerd isn't using this library's authentication logic, so this isn't a "real" issue, but we should try to fix it if there aren't major blockers.
