### ISSUE TITLE
Excessive RBAC permissions needed for linkerd viz operations on a multitenant cluster

### ISSUE THREAD

**Issue by danibaeyens** [linkerd/linkerd2#10207]
### What problem are you trying to solve?

We run multitenant clusters where different teams own a single namespace. These clusters have lots of verbs and resources restricted out of their own namespaces (i.e. don't allow get/list/watch secrets on other namespaces).

If I want to allow teams to run `linkerd viz tap` on their own resources, the operation fails because they need elevated privileges for some operations (i.e. list namespaces, get clusterroles, etc)
Inspecting the code, we've seen that for a `linkerd viz tap` command, it runs under the hood the same checks as `linkerd viz check` (see https://github.com/linkerd/linkerd2/blob/0bd3f732e68b9bc0345b801ca541fad36a8dd824/viz/pkg/healthcheck/healthcheck.go#L72). This means that it will even need checking the tap certificate (which means get/list/watch on secrets for other namespaces than their own).

As a namespace user, I don't think they need all those permissions, but just
```
- apiGroups:
  - tap.linkerd.io
  resources:
  - '*'
  verbs:
  - watch
```
as the `tap-admin` role states.

### How should the problem be solved?

I'd either reduce the surface of the checks for some `viz` commands. 

We've tried to manually remove the check line (https://github.com/linkerd/linkerd2/blob/0bd3f732e68b9bc0345b801ca541fad36a8dd824/viz/cmd/tap.go#L210) and build the CLI again, and the `tap` command works with restricted permissions.
We have a ClusterRole with:
```
- apiGroups:
  - tap.linkerd.io
  resources:
  - '*'
  verbs:
  - watch
```
and a RoleBinding which uses it on a certain namespace.

### Any alternatives you've considered?

Consider removing all checks on commands which can be run on isolated namespaces, as a single user does not need to check `linkerd viz` health on every command run.

### How would users interact with this feature?

It's quite specific to multitenant scenarios with restricted permissions, but it's a deal breaker. With the checks in place, no users can run
- edges
- routes
- tap
if they don't have elevated privileges.

### Would you like to work on this feature?

yes

**Comment by adleong** [comment]
Hi @danibaeyens!

The reason why commands like `linkerd viz tap` run a full suite of checks is so that we can ensure that the control plane is in a healthy state and give the user a helpful error message if we know the command cannot succeed because the control plane is unhealthy.  With that said, I agree with you that these permission requirements are too strict and unnecessary.  

I'd be in favor of removing these checks from `linkerd viz tap` etc.  We should, however, verify that we can still give as helpful a message as possible when these commands fail due to an unhealthy or unavailable control plane.

**Comment by danibaeyens** [comment]
As said, most of the checks would not work if the user does not have elevated permissions in the cluster. Therefore, they cannot do much even if the control plane or viz is not working.

Though, I see `"tap API service is running"` is the valid summary check and the one that a user in a multitenant cluster would care the most.

What about detecting if the user has access to the viz namespace, and if not, just check for a successful API service access and print that further checks can be run by a cluster administrator?

I guess that a successful tap API service implies that pods are running and certs are valid, am I right?
