### ISSUE TITLE
In the Destination controller, Server subscribers shouldn't be keyed off of the entire pod

### ISSUE THREAD

**Issue by alpeb** [linkerd/linkerd2#10205]
Followup to #10201

It's not necessary and even wasteful to have the Server subscriptions in `server_watcher.go` be keyed off of the entire Pod. We require the pods labels and ContainerPorts, which we can pack in a new struct.

**Comment by olix0r** [comment]
But even if we only care about a pod's labels... I'd expect that belongs in the map _value_ and not the map's key? The uniquely identifiable info of a server is either ip:port or _namespace/pod:port_, right?
