### ISSUE TITLE
linkerd multicluster checks using confusing language

### ISSUE THREAD

**Issue by whiskeysierra** [linkerd/linkerd2#10212]
### What is the issue?

When running `linkerd multicluster check`, the output mentions "gateway mirrors", where it probably means to say "service mirrors".

### How can it be reproduced?

```
❯ linkerd multicluster check
```

### Logs, error output, etc

See linkerd check output below.

### output of `linkerd check -o short`

```
linkerd-multicluster
--------------------
√ Link CRD exists
√ Link resources are valid
	* echo-alpha
√ remote cluster access credentials are valid
	* echo-alpha
√ clusters share trust anchors
	* echo-alpha
√ service mirror controller has required permissions
	* echo-alpha
√ service mirror controllers are running
	* echo-alpha
× all gateway mirrors are healthy
        liveness checks failed for echo-alpha
    see https://linkerd.io/2.12/checks/#l5d-multicluster-gateways-endpoints for hints
√ multicluster extension proxies are healthy
√ multicluster extension proxies are up-to-date
√ multicluster extension proxies and cli versions match

Status check results are ×
```

### Environment

- Linkerd version: stable-2.12.3

### Possible solution

Change it here

https://github.com/linkerd/linkerd2/blob/2e8ff818d3e75ced83f06e7ed76094f5d139bd0b/multicluster/cmd/check.go#L203-L208

### Would you like to work on fixing this bug?

maybe

**Comment by Jehan-h20220012** [comment]
I want to work on this issue. Please assign me

**Comment by whiskeysierra** [comment]
I can't rule out that I'm misunderstanding something though. In fact it's very likely even.

**Comment by mateiidavid** [comment]
> all gateway mirrors are healthy

This should refer to the `Service` created in a local cluster after linking with a remote target. Assuming two clusters: east and west, if we link them (and east is our source/local cluster), we would expect a "gateway mirror" `Service` object created in east.

This `Service` object serves as a target for our service-mirror probe. Each service-mirror instance is configured to probe its gateway (through the `Service`, ofc). I see why the naming is confusing, but I believe changing this to `gateway` will be even more confusing. For example, if we run the check command in a cluster that has both a gateway, and a gateway mirror (it receives and sends multicluster traffic), what would we expect the check to surface when both are healthy? What if only one is down? If we say the gateway is down (when in fact only the mirror is) would people assume that the cluster cannot receive any traffic?

We're open to suggestions here of course, but not sure if changing the naming here will make it less confusing. Perhaps something like:

`all gateway mirrors (probe services) are healthy` might give it more context?

https://github.com/linkerd/linkerd2/blob/main/multicluster/charts/linkerd-multicluster-link/templates/gateway-mirror.yaml

^ gateway mirror service.

**Comment by whiskeysierra** [comment]
> `all gateway mirrors (probe services) are healthy` might give it more context?

Yes, I think that would be clearer.

**Comment by stevej** [comment]
We think clarifying the message to something like "Probe service able/unable to communicate with gateway mirrors" would help but would like feedback on that.
