### ISSUE TITLE
Add dynamic profiling to Linkerd Rust controllers

### ISSUE THREAD

**Issue by risingspiral** [linkerd/linkerd2#10227]
### What problem are you trying to solve?

Enable users to dynamically profile the running application can aid significantly in debugging and diagnostics. 

### How should the problem be solved?

With [pprof](https://github.com/tikv/pprof-rs/blob/master/README.md) or something similar

### Any alternatives you've considered?

Not at the moment. 

### How would users interact with this feature?

Network connection

### Would you like to work on this feature?

maybe

**Comment by amit-62** [comment]
This enhancement looks interesting to me, so I would love to be a LFX mentee for this project. Please help me to get started with this issue.

**Comment by mateiidavid** [comment]
@amit-62, I'd start by looking at how this is handled for our controllers written in Go.

https://github.com/linkerd/linkerd2/blob/ae46678b0e976d61830a4b6e1f0d6b174ecd9ecb/pkg/admin/admin.go#L34-L51

https://github.com/linkerd/linkerd2/blob/ae46678b0e976d61830a4b6e1f0d6b174ecd9ecb/controller/cmd/destination/main.go#L34

Each controller takes a CLI argument that enables pprof. How would we do this in Rust? What would the expected end-to-end flow look like? Would it similar to Go?

Also, in Go, pprof is (if I'm not wrong) exported by the http package. What would we use in Rust? Have a look at the post carefully, read through the problem statement, and come up with a thorough implementation plan. Make sure to let us know how users would interact with this feature (i.e UX) and how you would go about implementing in.

**Comment by amit-62** [comment]
Thank you @mateiidavid. I will start working on it.

**Comment by brancz** [comment]
I want to highlight a parallel effort that is on-going, which is to build binaries with DWARF debuginfos, which would allow profilers like `perf` and Parca to profile linkerd without any code modifications needed, and more importantly without using `SIGPROF` which can change program execution (in very high-performance use cases we've observed this to be an actual problem).

cc @stevej @olix0r

**Comment by stevej** [comment]
@brancz Thank you for chiming in! I caught up with oliver and he let me know that we've been putting `debug_info` into the proxy release since the end of december although I'm not sure this is DWARF format or not. If this doesn't work in your pipeline, we can improve it.

debug-info was included with this commit: https://github.com/linkerd/linkerd2-proxy/commit/adf06c492d303beda83cef990b98a3fa86a6ebe1#diff-deb9bb56fb122db0b605aa5b63f95a4665c905b18dd670e1fa6c877576a94ff1R114-R121

I took a quick look at a recent release from github: https://github.com/linkerd/linkerd2-proxy/releases/tag/release%2Fv2.189.0

```% file *
LICENSE:            ASCII text
bin:                directory
linkerd2-proxy:     ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=7feb197a9e27026f754f3d3dbe56375dced0dacc, for GNU/Linux 3.2.0, stripped
linkerd2-proxy.dbg: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter *empty*, BuildID[sha1]=7feb197a9e27026f754f3d3dbe56375dced0dacc, for GNU/Linux 3.2.0, with debug_info, not stripped
```

**Comment by brancz** [comment]
Awesome! I’ll try it!

**Comment by fool1280** [comment]
Hi, I'm interested in this issue, and I learned about it through LFX. I messed up the wrong date and submited my cover letter late for 5 hours. I understand it can be a big thing to ask, but if possible, I'd like to still be considered to become a mentee for this issue. Please let me know! Thank you.
