### ISSUE TITLE
[cli] `linkerd inject` show "skipped" for a Namespace

### ISSUE THREAD

**Issue by brsolomon-deloitte** [linkerd/linkerd2#10231]
### What is the issue?

Running `kubectl get ns <namespace> -o yaml | linkerd inject -` shows `namespace "<namespace>" skipped` on stderr. However, it does appear that the annotation gets applied and spit out as YAML as expected.

The linkerd [docs](https://linkerd.io/2.12/tasks/adding-your-service/#meshing-a-service-with-annotations) note that you can apply the `linkerd.io/inject: enabled` annotation to a `Namespace`. (Yes, I realize this could be done using `kubectl annotate`, but the `linkerd inject` route seems more stable and explicit.)

Is `linkerd inject` meant to be used on `Namespace` YAML, or only directly on Deployment/StatefulSet/Pod resources?

### How can it be reproduced?

```
kubectl get ns <namespace> -o yaml | linkerd inject -
```

### Logs, error output, etc

```
$ kubectl get ns airflow -o yaml | linkerd inject -

...

namespace "airflow" skipped
```

### output of `linkerd check -o short`

```
$ linkerd check -o short
Status check results are √
```

### Environment

- Amazon EKS 1.24

### Would you like to work on fixing this bug?

no

**Comment by scotran** [comment]
I'd like to take this issue: I've narrowed down the issue and will be creating a pull request soon. (Disclaimer: I'm a student at the University of Texas at Austin taking a Virtualization course)

**Comment by douglaslim** [comment]
Hi, is this issue still open?
