### ISSUE TITLE
[charts/linkerd-viz] Add `Ingress` template for Helm chart

### ISSUE THREAD

**Issue by brsolomon-deloitte** [linkerd/linkerd2#10230]
### What problem are you trying to solve?

The `linkerd-viz` Helm chart does not include an `Ingress` template in [`web.yaml`](https://github.com/linkerd/linkerd2/blob/main/viz/charts/linkerd-viz/templates/web.yaml) and users are forced to roll their own. The lack of an Ingress is noticeable as many charts include one by default for web app UIs.

### How should the problem be solved?

Add an [`ingress:`](https://github.com/bitnami/charts/blob/main/bitnami/spark/values.yaml#L818) section in values.yaml and a corresponding `Ingress` template.

### Any alternatives you've considered?

No.

However, currently the docs show usage of `linkerd viz dashboard &`. Looking at this command, it runs a simple `port-forward`. If this is the _only_ recommended way to access the linkerd-viz dashboard, then that could be stated in the documentation. Otherwise, a dedicated Ingress resource seems useful to be able to access the app.

### Would you like to work on this feature?

maybe

**Comment by stevej** [comment]
We suspect the docs cover your use case, please let us know if that's not the case: https://linkerd.io/2.12/tasks/exposing-dashboard/

**Comment by brsolomon-deloitte** [comment]
My suggestion here is to add a Helm chart [`Ingress` template](https://github.com/bitnami/charts/blob/main/bitnami/apache/templates/ingress.yaml) as part of the official `linkerd-viz` Helm chart. In my own opinion, documenting examples of hardcoded Ingress manifests in the docs isn't a replacement for that.

**Comment by whiskeysierra** [comment]
An `Ingress` is a tricky resource to provide a default for, because:

1. TLS: Some users want TLS, some might not. Those who do might use `cert-manager` to aquire the certificate/key, some might not.
2. Authentication: How should the ingress be secured? Basic auth? OIDC? None of those is a first-class construct in the Ingress API.
3. Ingress controller specific annotations: Most of the time you'll need to set some controller-specific annotations to get your desired result, e.g. authentication related configuration.

I think it's reasonable to expect that pretty much all users of the helm chart would need to kustomize/patch the Ingress resource to add those pieces.
At which point they may just create the whole resource themselves to begin with.

**Comment by brsolomon-deloitte** [comment]
> I think it's reasonable to expect that pretty much all users of the helm chart would need to kustomize/patch the Ingress resource to add those pieces.

This is the entire purpose of Helm :) Provide a base template, and let users customize it.

TLS: this one's easy. See [numerous examples](https://github.com/bitnami/charts/tree/main/bitnami/spark) of how `values.yaml` and Helm helpers can optionally template-out the `tls` section based on user inputs. `cert-manager` requires a single annotation and can use the existing ingress hostname.

Authentication and ingress controller: this is also what `ingress.annotations` is for. Set it empty and let user customize it.

Virtually every production helm chart offers an `Ingress` template. The Helm chart author's job is not to ensure that the template works with zero overrides for every user scenario. It's to provide a useful base for multiple scenarios. There is nothing particularly different about `linkerd-viz` that would discourage its use with Helm. Here are just a few more examples.

- https://github.com/prometheus-community/helm-charts/blob/2c3113586607a53252fdb3d2583bb3e44e107121/charts/kube-prometheus-stack/values.yaml#L253
- https://github.com/grafana/helm-charts/blob/main/charts/grafana/templates/ingress.yaml

**Comment by itsCheithanya** [comment]
I would love to work on this issue

**Comment by Laakso** [comment]
Yeah I agree what brsolomon just said. I came here to file an github issue about ingress as well.

**Comment by johnjeffers** [comment]
I agree that having a customizable ingress as part of the viz helm chart would be welcome. Right now, I have to manage the ingress for viz separately, which is fine, but I'd love it if all the pieces of viz were wrapped into the same deployment.

Here's an example of a helm chart that does what I think people are asking for:

https://github.com/jfrog/charts/blob/master/stable/artifactory/values.yaml#L103
https://github.com/jfrog/charts/blob/master/stable/artifactory/templates/ingress.yaml
