### ISSUE TITLE
Namespace Settings Also Applied To Services

### ISSUE THREAD

**Issue by lupusllc** [linkerd/linkerd2#10261]
### What problem are you trying to solve?

When adding namespace level opaque ports, this is added to pods automatically but not to their related services. When doing a linkerd check --proxy we see warnings about this and the following documentation says that's it needed.

https://linkerd.io/2.12/tasks/troubleshooting/#linkerd-opaque-ports-definition

```
linkerd-data-plane
------------------
√ data plane namespace exists
√ data plane proxies are ready
√ data plane is up-to-date
√ data plane and cli versions match
√ data plane pod labels are configured correctly
√ data plane service labels are configured correctly
√ data plane service annotations are configured correctly
‼ opaque ports are properly annotated
        * service ingress-ingress-nginx-controller targets the opaque port https through 443; add 443 to its config.linkerd.io/opaque-ports annotation
        * service ingress-ingress-nginx-controller targets the opaque port https through 443; add 443 to its config.linkerd.io/opaque-ports annotation
    see https://linkerd.io/2.12/checks/#linkerd-opaque-ports-definition for hints
```

### How should the problem be solved?

Appropriate namespace configurations for Linkerd should be applied also to the services

### Any alternatives you've considered?

I don't know how adding some of these values actually effect the service and the way Linkerd operates. If possible, maybe Linkerd just automatically assumes to use pod settings on the service, without the need to annotate the service. Then the linkerd check can be updated to not give these warnings.

Plus the warnings themselves are confusing, when it says the "opaque ports are properly annotated" it should say "opaque ports are **not** properly annotated". Otherwise, it looks like a false negative.

### Would you like to work on this feature?

no

**Comment by mateiidavid** [comment]
@lupusllc services (unlike pods) are generally immutable. Not sure if this would be very helpful in the long run. A service may pass through the injector only when it is first created (and this still enforces a dependency on the control plane existing). It's easier to have them treated separately imo and it eliminates doubts and assumptions.

> Plus the warnings themselves are confusing, when it says the "opaque ports are properly annotated" it should say "opaque ports are not properly annotated". Otherwise, it looks like a false negative.

That's the check's name, not the check's result. As you can see in the output you've posted, a pair of exclamation marks show up next to the check. Other (successful) checks have a tick.

**Comment by lupusllc** [comment]
For services, are linkerd annotations only honored at their creation?
Would there be a reason a service would ever not want to have the same annotations that the pods would have for opaque ports?
