### ISSUE TITLE
Consider signing digests instead of tags in cosign sign step.

### ISSUE THREAD

**Issue by vaikas** [linkerd/linkerd2#10277]
### What problem are you trying to solve?

Currently looks like the actions (one example here):
https://github.com/linkerd/linkerd2/actions/runs/3913727139/jobs/6689964753

And in particular `Run cosign sign...` action complains about sining a tag 
```
Generating ephemeral keys...
Retrieving signed certificate...

        Note that there may be personally identifiable information associated with this signed artifact.
        This may include the email address associated with the account with which you authenticate.
        This information will be used for signing this artifact and will be stored in public transparency logs and cannot be removed later.
Successfully verified SCT...
WARNING: Image reference ghcr.io/linkerd/controller:edge-23.1.1 uses a tag, not a digest, to identify the image to sign.

This can lead you to sign a different image than the intended one. Please use a
digest (example.com/ubuntu@sha256:abc[12](https://github.com/linkerd/linkerd2/actions/runs/3913727139/jobs/6689964753#step:6:13)3...) rather than tag
(example.com/ubuntu:latest) for the input to cosign. The ability to refer to
images by tag will be removed in a future release.
tlog entry created with index: 11107890
Pushing signature to: ghcr.io/linkerd/controller
```

### How should the problem be solved?

Probably grab the digest from a previous step and sign that instead of the tag.

### Any alternatives you've considered?

I think it will continue to work for now, but at some point it won't, so might as well get ahead of it :) 

### Would you like to work on this feature?

yes

**Comment by risingspiral** [comment]
Hey @vaikas! Yes, we'd welcome a PR for this since you indicated you'd like to work on this feature.

**Comment by vaikas** [comment]
Just a quick update on this. Haven't forgotten and started to look into it and it's a bit more complex given how the current release process works and I'm trying to find the place where one could 'grab the digest' :) in a surgical way and I must have misplaced it somehow, cause I can't find it :)

Anyways, not ignoring!
