### ISSUE TITLE
Add a readiness probe during `conduit inject` that indicates when proxy is ready

### ISSUE THREAD

**Issue by briansmith** [linkerd/linkerd2#1029]
In a configuration where every proxy instance assumes every other proxy instance can do TLS, a proxy cannot send requests to another proxy unless/until the proxy is ready to accept TLS connections. In particular that proxy must have its certificate and private key, which it gets from the CA. The CA issues certificates asynchronously with pod creation so there will be gaps where the pod has been created but the CA hasn't issued it a certificate. And/or the CA may fail to issue the certificate due to operational failure, e.g. because the RBAC configuration is messed up. During the time when the pod is unable to do TLS then it should respond "nope" to the readiness probe so that Kubernetes directs the traffic to other pods for the same service (if any).

/cc @olix0r

**Comment by hawkw** [comment]
Here's my understanding of potential readiness criteria for a proxy:

A proxy is ready if the following are true:
- inbound & outbound listeners are open
- has successfully connected to the `Destination` service
- has successfully loaded its TLS cert and private key

@briansmith and @olix0r, does that sound correct to you?

**Comment by briansmith** [comment]
> inbound & outbound listeners are open
Yes.
> has successfully connected to the Destination service
I'm not sure this is necessary. In particular, some applications never make any outgoing requests and thus the Destination service isn't needed.
> has successfully loaded its TLS cert and private key
Yes, if/when TLS is enabled.

**Comment by hawkw** [comment]
> I'm not sure this is necessary. In particular, some applications never make any outgoing requests and thus the Destination service isn't needed.

That's true. I suppose a readiness probe would only care that the proxy is ready to _receive_ requests, not that it's ready to route outbound requests. 

In light of that we might also only care if the inbound listener is open, and not the outbound listener?

**Comment by olix0r** [comment]
I don't think the proxy should be considered ready until all of its ports are bound. Let's keep it simple.

**Comment by briansmith** [comment]
@hawkw What you described here is true for the initial iteration, but there will be an following iteration where the original plan will be implemented. In particular, the fallback-to-non-secure-connection logic will be removed after the TLS implementation's reliability has been validated. Similarly, we probably will predicate the readiness probe on TLS being available once we're satisfied with the reliability of the TLS implementation.

**Comment by hawkw** [comment]
I opened  #1084 to track the fall-back-to-plaintext behaviour.
