### ISSUE TITLE
Add tests for proxy rebinding endpoints on metadata changes

### ISSUE THREAD

**Issue by hawkw** [linkerd/linkerd2#1031]
See also https://github.com/runconduit/conduit/pull/1006#pullrequestreview-123564862.

PR #1006 modified the proxy's `destination` module so that when the metadata associated with an endpoint changes, the endpoint is re-bound and the load balancer is updated with the newly-bound service, rather than changing the metadata in place, as was done previously.

We should, if possible, add one or more tests in order to ensure that this is done correctly.

**Comment by briansmith** [comment]
The test server listens on a port for connections and requests on those connections. A request sent after a rebind wouldn't be on the same connection as a request sent before the rebind, and I think we can use that as a basis for the test. The trick is to make sure there aren't any false positives, i.e. ensure that the connection doesn't get closed during the test except during the rebind. WDYT?
