### ISSUE TITLE
Add metrics for all long-lived data structures in all controllers

### ISSUE THREAD

**Issue by jeremychase** [linkerd/linkerd2#10325]
Debugging memory usage requires profiling if we do not export metrics for our long-lived data-structures.

Similar to the work performed in #10213, we want to first identify all long-lived data structures and then ensure each has a corresponding metric associated with it.

For the purposes of this issue, long-lived means a val that that remains in memory and has a lifecycle similar to the controller that contains it. The data-structure may be a `map`, slice, or anything else that can vary in size.

**Comment by stevej** [comment]
We tried this technique at one company I worked at with Oliver and William but we found that it was easy to forget to add alerting on the metrics. Lots of people felt we were putting more pressure on the timeseries service without enough benefit.

This might be served with a new go lint, though. a lint rule could check that any map or slice with an assignment needs to have a delete somewhere.

**Comment by adleong** [comment]
This is further complicated by the fact that many controllers will pull in long-lived data structures through libraries such as client-go, for example.
