### ISSUE TITLE
Metric not display on linkerd viz ( use external prometheus)

### ISSUE THREAD

**Issue by sureenart** [linkerd/linkerd2#10329]
### What is the issue?

Metric not display on linkerd viz ( use external prometheus)

![image](https://user-images.githubusercontent.com/125337032/218643369-10ee36c2-0c19-4e1d-b5a8-cedc4ec5ae29.png)
![image](https://user-images.githubusercontent.com/125337032/218643412-e3a892cc-9412-4280-a5dd-1f468a3f603d.png)

### How can it be reproduced?

![image](https://user-images.githubusercontent.com/125337032/218643436-9c8b5995-e55f-47a4-82b5-4821a49db750.png)

### Logs, error output, etc

![image](https://user-images.githubusercontent.com/125337032/218643430-a8dba33e-2dba-4fc7-b02f-5e838b973505.png)

### output of `linkerd check -o short`

Linkerd core checks
===================

linkerd-version
---------------
‼ cli is up-to-date
    is running version 2.12.3 but the latest stable version is 2.12.4
    see https://linkerd.io/2.12/checks/#l5d-version-cli for hints

control-plane-version
---------------------
‼ control plane is up-to-date
    is running version 2.12.3 but the latest stable version is 2.12.4
    see https://linkerd.io/2.12/checks/#l5d-version-control for hints

linkerd-control-plane-proxy
---------------------------
‼ control plane proxies are up-to-date
    some proxies are not running the current version:
	* linkerd-destination-78f89f49c6-jtm7r (stable-2.12.3)
	* linkerd-identity-7588c6579b-lnplr (stable-2.12.3)
	* linkerd-proxy-injector-7c7658d894-mpvnl (stable-2.12.3)
    see https://linkerd.io/2.12/checks/#l5d-cp-proxy-version for hints

Linkerd extensions checks
=========================

linkerd-viz
-----------
‼ viz extension proxies are up-to-date
    some proxies are not running the current version:
	* metrics-api-7bb6cf684f-rjc7k (stable-2.12.3)
	* tap-7f8785bd5d-bfdv5 (stable-2.12.3)
	* tap-injector-86d64dbc8f-tccfm (stable-2.12.3)
	* web-746476d77b-wcqg8 (stable-2.12.3)
    see https://linkerd.io/2.12/checks/#l5d-viz-proxy-cp-version for hints

Status check results are √

### Environment

 - kubernetes version v1.26.1
 - linkerd version
Client version: stable-2.12.3
Server version: stable-2.12.3

### Would you like to work on fixing this bug?

None

**Comment by mateiidavid** [comment]
@sureenart is it possible your external prometheus link is bad? Can you post it here?

Also, can you look at the logs for `metrics-api` and `web` in `linkerd-viz`? They will indicate whether something has happened or if they cannot connect to a service.

**Comment by sureenart** [comment]
Thanks @mateiidavid  now we change to build-in prometheus it's work but data on services not display .  could you guild on this ? 
![image](https://user-images.githubusercontent.com/125337032/219318846-71826fa2-d2cb-48d5-9fdd-cf980eebf8c4.png)

**Comment by mateiidavid** [comment]
@sureenart would love to help but we need a few more details. A screenshot alone won't help us identify the problem. I'd suggest going through the steps I recommended above :)

* Check logs for `web` in the viz namespace (for both proxy, and web container)
* Check logs for `metrics-api` in the viz namespace (same as above)
* Ensure you have set up your scrapes correctly as suggested in our docs.

If you want to use an external prometheus instance, have a read through our docs (https://linkerd.io/2.12/tasks/external-prometheus/), perhaps you'll find what you're missing in there.
