### ISSUE TITLE
Repeat: linkerd-cni logs are flooded on some pods

### ISSUE THREAD

**Issue by relu** [linkerd/linkerd2#10375]
### What is the issue?

This is an exact repeat of #9916

### How can it be reproduced?

It started to happen on some of our clusters where we recently did a rolling update of the nodes. Still trying to understand how this problem gets triggered

### Logs, error output, etc

```
Created CNI config /host/etc/cni/net.d/05-cilium.conflist
Detected change in /host/etc/cni/net.d/: CREATE 01-linkerd-cni.conf
sha256sum: /host/etc/cni/net.d/01-linkerd-cni.conf: No such file or directory
New file [01-linkerd-cni.conf] detected; re-installing in "chained" mode
Using CNI config template from CNI_NETWORK_CONFIG environment variable. 
      "k8s_api_root": "https://__KUBERNETES_SERVICE_HOST__:__KUBERNETES_SERVICE_PORT__",
      "k8s_api_root": "https://172.20.0.1:__KUBERNETES_SERVICE_PORT__", 
CNI config: {    
  "name": "linkerd-cni",                                       
  "type": "linkerd-cni",
  "log_level": "info",
  "policy": {                   
      "type": "k8s",            
      "k8s_api_root": "https://172.20.0.1:443",
      "k8s_auth_token": "__SERVICEACCOUNT_TOKEN__"
  },                                           
  "kubernetes": {                                     
      "kubeconfig": "/etc/cni/net.d/ZZZ-linkerd-cni-kubeconfig"
  },                      
  "linkerd": {
    "incoming-proxy-port": 4143,
    "outgoing-proxy-port": 4140,                                                                                                              
    "proxy-uid": 2102,                                    
    "ports-to-redirect": [],                                       
    "inbound-ports-to-ignore": ["4191","4190"],                   
    "outbound-ports-to-ignore": ["8125","8126","443"],            
    "simulate": false,                                                                                                                        
    "use-wait-flag": false                                                                                                                    
  }                                                                                                                                           
}                                                                                                                                             
mv: setting attribute 'security.selinux' for 'security.selinux': Permission denied
Created CNI config /host/etc/cni/net.d/01-linkerd-cni.conf
Detected change in /host/etc/cni/net.d/: DELETE 01-linkerd-cni.conf
Detected change in /host/etc/cni/net.d/: DELETE 05-cilium.conflist
Detected change in /host/etc/cni/net.d/: CREATE 05-cilium.conflist
New file [05-cilium.conflist] detected; re-installing in "chained" mode 
Using CNI config template from CNI_NETWORK_CONFIG environment variable. 
      "k8s_api_root": "https://__KUBERNETES_SERVICE_HOST__:__KUBERNETES_SERVICE_PORT__",
      "k8s_api_root": "https://172.20.0.1:__KUBERNETES_SERVICE_PORT__", 
CNI config: {
  "name": "linkerd-cni",
  "type": "linkerd-cni",
  "log_level": "info",
  "policy": {
      "type": "k8s",
      "k8s_api_root": "https://172.20.0.1:443",
      "k8s_auth_token": "__SERVICEACCOUNT_TOKEN__"
  },
  "kubernetes": {
      "kubeconfig": "/etc/cni/net.d/ZZZ-linkerd-cni-kubeconfig"
  },
  "linkerd": {
    "incoming-proxy-port": 4143,
    "outgoing-proxy-port": 4140,
    "proxy-uid": 2102,
    "ports-to-redirect": [],
    "inbound-ports-to-ignore": ["4191","4190"],
    "outbound-ports-to-ignore": ["8125","8126","443"],
    "simulate": false,
    "use-wait-flag": false
  }
}
Removing Linkerd's configuration file: /host/etc/cni/net.d/01-linkerd-cni.conf
mv: setting attribute 'security.selinux' for 'security.selinux': Permission denied
```

### output of `linkerd check -o short`

```
Status check results are √
```

### Environment

- Kubernetes v1.24
- EKS
- Bottlerocket OS 1.12.0
- Linkerd v2.12.4
- Cilium v1.12.4

### Possible solution

Restarting the linkerd-cni DaemonSet does solve the problem, however, I'm not sure how long it lasts before they start misbehaving again (if that is the case).

### Would you like to work on fixing this bug?

yes

**Comment by relu** [comment]
I figured out how to reproduce this even outside of Kubernetes:
```sh
cat > /tmp/05-cilium.conf << EOF
{
  "cniVersion": "0.3.1",
  "name": "cilium",
  "type": "cilium-cni",
  "enable-debug": true,
  "log-file": "/dev/stdout"
}
EOF
touch /tmp/empty
mkdir -p /tmp/cni/{bin,net.d}
cp /tmp/05-cilium.conf /tmp/cni/net.d/
docker run -ti -v /tmp/cni/net.d:/host/etc/cni/net.d -v /tmp/cni/bin:/host/opt/cni/bin -v /tmp/empty:/var/run/secrets/kubernetes.io/serviceaccount/token -e KUBERNETES_SERVICE_HOST=localhost -e KUBERNETES_SERVICE_PORT=80 -e TLS_CFG= -e CNI_NETWORK_CONFIG='{"test":"__KUBERNETES_SERVICE_HOST__.__KUBERNETES_SERVICE_PORT__.__KUBERNETES_NODE_NAME__.__KUBECONFIG_FILENAME__.__CNI_MTU__.__KUBECONFIG_FILEPATH__.__SERVICEACCOUNT_TOKEN__"}' ghcr.io/linkerd/cni-plugin:stable-2.12.4
# Wait for the container to start and then do this a few times repeatedly:
rm -f /tmp/cni/net.d/{05-cilium.conflist,ZZZ-linkerd-cni-kubeconfig} && cp /tmp/05-cilium.conf /tmp/cni/net.d/
```

I was able to reproduce this very quickly.

What I noticed was that likely because there's a few microseconds delay between deleting the `.conflist` file and re-creating it the plugin will start to take the path of installing in interface mode which breaks the cycle and starts the endless loop of detecting and removing the `01-linkerd-cni.conf` file over and over.

```
Detected change in /host/etc/cni/net.d/: DELETE 05-cilium.conflist                                                                                                                                                                                                                          
No active CNI configuration file found after DELETE event; re-installing in "interface" mode
Created CNI config /host/etc/cni/net.d/01-linkerd-cni.conf                                                                                                                                                                                                                                  
Detected change in /host/etc/cni/net.d/: CREATE 05-cilium.conf
New file [05-cilium.conf] detected; re-installing in "chained" mode
Renaming /host/etc/cni/net.d/05-cilium.conf extension to .conflist                                                                                                                                                                                                                          
Removing Linkerd's configuration file: /host/etc/cni/net.d/01-linkerd-cni.conf                                                                                                                                                                                                              
Removing unwanted .conf file                                                                                                                                                                                                                                                                
Created CNI config /host/etc/cni/net.d/05-cilium.conflist                                                                                                                                                                                                                                   
Detected change in /host/etc/cni/net.d/: CREATE 01-linkerd-cni.conf
sha256sum: /host/etc/cni/net.d/01-linkerd-cni.conf: No such file or directory                                                                                                                                                                                                               
New file [01-linkerd-cni.conf] detected; re-installing in "chained" mode
Created CNI config /host/etc/cni/net.d/01-linkerd-cni.conf
Detected change in /host/etc/cni/net.d/: DELETE 01-linkerd-cni.conf
Detected change in /host/etc/cni/net.d/: CREATE 05-cilium.conflist
New file [05-cilium.conflist] detected; re-installing in "chained" mode
...
```
(removed some of the more verbose log messages for brevity)

**Comment by mateiidavid** [comment]
@relu thanks! I was trying to reproduce this today. Your explanation seems very plausible. Without too much thought, I think an easy (and correct) way out of this would be to run the CNI plugin in interface or standalone mode and stop trying to do both. In all honesty, I struggle to find a reason as to why we would want to install `linkerd-cni` in standalone mode to begin with; we don't do any IPAM, or any other networking heavy lifting. 

Having a "standalone" mode implies that `linkerd-cni` _can_ live as the only CNI plugin, and I'm not sure that's completely true. Without an actual CNI backend (Calico, Cilium, Flannel, etc), pods won't be able to start anyone. Perhaps down the line it'd be wiser to completely remove this and attach ourselves to any configuration file that's in there. Not sure what all of these changes imply as far as changes go, but it's currently where I'm at right now.

Curious as a CNI production user what your thoughts are.

cc: @stevej

**Comment by relu** [comment]
I think your proposal makes a lot of sense @mateiidavid, having the ability to set, through configuration, a single mode of operation that is expected for the plugin to run in sounds like the right call to me. For example, Cilium uses an environment variable to decide its mode of operation ([see here](https://github.com/cilium/cilium/blob/master/plugins/cilium-cni/cni-install.sh#L7)) and that will apply to the agent for the entire lifecycle of the pod.

As for having the "standalone" mode available, I also think that makes sense considering linkerd-cni lacks core CNI feature requirements such as IPAM and likely will never need to.

**Comment by relu** [comment]
I've created my own version of the cni-plugin image removing the standalone installation from the install script and I can confirm my problem is solved now. Here's a gist with the modifications if anyone else might find it helpful: https://gist.github.com/relu/e81a9fc2ee1f4e53ca4ddce35ecbdaa3

**Comment by relu** [comment]
This issue is still relevant and quite critical to fix IMO.

**Comment by mateiidavid** [comment]
Hey @relu, we pushed a change to only allow the CNI plugin to run in interface mode. It's the solution we described above. Plugin should now wait for the existence of other config files before appending itself. Does that fix your problems? I believe it's been released in a recent edge version.

**Comment by relu** [comment]
I found this [commit](https://github.com/linkerd/linkerd2/commit/040481cd800481b38a315ea1809ddd7eee1bf9bb#diff-bd0f7a739b50f00dea0bb4a8cf1be72e835c635069a97115060ad2288ddac103) which seems to be relevant, but I don't see any changes to the install script in there that would enable the described behavior. The [install script on main](https://github.com/linkerd/linkerd2/blob/main/cni-plugin/deployment/scripts/install-cni.sh) has not changed since 8 months ago. Maybe I'm not looking in the right place?

**Comment by risingspiral** [comment]
@relu the relevant commit is here: https://github.com/linkerd/linkerd2-proxy-init/commit/c0da952385f6212844c320f9d98ad4d1804dd4e4 the CNI plugin code was ported to the linkerd2-proxy-init repo earlier this year. What you see on the main branch of linkerd2 is no loger used. The improvement was released as part of https://github.com/linkerd/linkerd2/releases/tag/edge-23.6.1
