### ISSUE TITLE
Presence of thousands of pods causes cluster reliability issues

### ISSUE THREAD

**Issue by nagaland88** [linkerd/linkerd2#10386]
### What is the issue?

With the presence of 3k+ pods, linkerd-proxy-injector is not happy and is getting OOMkilled constantly. I only noticed this issue when 3k pods were already created, but might already happen if we exceed the 1.5k mark. 

The memory consumption of linkerd-proxy-injector grows with the number of pods in the system, instead of streaming through the list of pods to process ...

ReplicaSets were created with issues, and no pods were created by it. The following error was provided:

Error creating: Internal error occurred: failed calling webhook "linkerd-proxy-injector.linkerd.io": failed to call webhook: Post "https://linkerd-proxy-injector.linkerd.svc:443/?timeout=10s": no endpoints available for service "linkerd-proxy-injector"

```- containerID: containerd://db5b6ce9e1c710d89a1ba12398ad12c4d0084c36970adefe8168901a509081b9
    image: cr.l5d.io/linkerd/controller:stable-2.12.2
    imageID: cr.l5d.io/linkerd/controller@sha256:c2c7324027cad22602197dbaa8d5ce3bd90b350f82b9969cd313f09877d917f3
    lastState:
      terminated:
        containerID: containerd://db5b6ce9e1c710d89a1ba12398ad12c4d0084c36970adefe8168901a509081b9
        exitCode: 137
        finishedAt: "2023-01-04T13:30:27Z"
        reason: OOMKilled
        startedAt: "2023-01-04T13:30:20Z"
    name: proxy-injector
    ready: false
    restartCount: 7
    started: false
    state:
      waiting:
        message: back-off 5m0s restarting failed container=proxy-injector pod=linkerd-proxy-injector-8b4fd48c5-65zh2_linkerd(3d354d5d-4184-45df-a6e4-745f9e426ca4)
        reason: CrashLoopBackOff
```

### How can it be reproduced?

Create a reasonably high amount of pods 1.5k+ 

Inspect the memory consumption of `linkerd-proxy-injector`

### Logs, error output, etc

Error creating: Internal error occurred: failed calling webhook "linkerd-proxy-injector.linkerd.io": failed to call webhook: Post "https://linkerd-proxy-injector.linkerd.svc:443/?timeout=10s": no endpoints available for service "linkerd-proxy-injector"

### output of `linkerd check -o short`

```
Linkerd core checks
===================

linkerd-version
---------------
‼ cli is up-to-date
    is running version 2.12.2 but the latest stable version is 2.12.4
    see https://linkerd.io/2.12/checks/#l5d-version-cli for hints

control-plane-version
---------------------
‼ control plane is up-to-date
    is running version 2.12.3 but the latest stable version is 2.12.4
    see https://linkerd.io/2.12/checks/#l5d-version-control for hints
‼ control plane and cli versions match
    control plane running stable-2.12.3 but cli running stable-2.12.2
    see https://linkerd.io/2.12/checks/#l5d-version-control for hints

linkerd-control-plane-proxy
---------------------------
‼ control plane proxies are up-to-date
    some proxies are not running the current version:
	* linkerd-destination-758f589976-285vf (stable-2.12.3)
	* linkerd-destination-758f589976-h7sgq (stable-2.12.3)
	* linkerd-destination-758f589976-jsjcl (stable-2.12.3)
	* linkerd-identity-6b64848bb4-5jhfh (stable-2.12.3)
	* linkerd-identity-6b64848bb4-72xkc (stable-2.12.3)
	* linkerd-identity-6b64848bb4-ndj8n (stable-2.12.3)
	* linkerd-proxy-injector-5f99969cc8-mxxtj (stable-2.12.3)
	* linkerd-proxy-injector-5f99969cc8-nz24g (stable-2.12.3)
	* linkerd-proxy-injector-5f99969cc8-rgs2m (stable-2.12.3)
    see https://linkerd.io/2.12/checks/#l5d-cp-proxy-version for hints
‼ control plane proxies and cli versions match
    linkerd-destination-758f589976-285vf running stable-2.12.3 but cli running stable-2.12.2
    see https://linkerd.io/2.12/checks/#l5d-cp-proxy-cli-version for hints

Linkerd extensions checks
=========================

linkerd-jaeger
--------------
‼ jaeger extension proxies are up-to-date
    some proxies are not running the current version:
	* collector-bd67f7f8-jb885 (stable-2.12.3)
	* jaeger-7bcbcf9899-kc5nb (stable-2.12.3)
	* jaeger-injector-5566f9698d-xgxbl (stable-2.12.3)
    see https://linkerd.io/2.12/checks/#l5d-jaeger-proxy-cp-version for hints
‼ jaeger extension proxies and cli versions match
    collector-bd67f7f8-jb885 running stable-2.12.3 but cli running stable-2.12.2
    see https://linkerd.io/2.12/checks/#l5d-jaeger-proxy-cli-version for hints

Linkerd extensions checks
=========================

linkerd-viz
-----------
‼ viz extension proxies are up-to-date
    some proxies are not running the current version:
	* metrics-api-6748fb9548-gnqlc (stable-2.12.3)
	* prometheus-596568b6f6-5xrzr (stable-2.12.3)
	* tap-84d9687fd5-nzpq7 (stable-2.12.3)
	* tap-injector-7bc8d69fb7-r5dkd (stable-2.12.3)
	* web-56896f9dbc-nh6q9 (stable-2.12.3)
    see https://linkerd.io/2.12/checks/#l5d-viz-proxy-cp-version for hints
‼ viz extension proxies and cli versions match
    metrics-api-6748fb9548-gnqlc running stable-2.12.3 but cli running stable-2.12.2
    see https://linkerd.io/2.12/checks/#l5d-viz-proxy-cli-version for hints

Status check results are √
```

### Environment

- Kubernetes version: 1.23
- Cluster: AWS EKS
- Linkerd version: 2.12.2

### Would you like to work on fixing this bug?

None

**Comment by mateiidavid** [comment]
Thanks for raising this @nagaland88!

Are you experiencing this when you create _1.5k pods at the same time_, or do you observe it when you have that many pods in your cluster? Most Kubernetes controllers establish watches on certain resources, the caches in the watches and the api client alone can take up a lot of memory.

I don't this is necessarily a problem; it's a huge load. Have you perhaps given any thought to running Linkerd in `HA` (High Availability`) mode? If you have more replicas you might experience less reliability problems.

Have a l[ook at our docs](https://linkerd.io/2.12/features/ha/) on this topic.

**Comment by nagaland88** [comment]
Hello, @mateiidavid, we already run Linkerd in HA. 

We reached 1.5k pods by creating them through a CI  workflow at approximately 1 pod every 3 seconds. 

Those pods where not linkerd `injected` nevertheless, the linkerd-proxy-injector memory grew with the number of pods in the cluster, instead of streaming through the list of pods to process

**Comment by olix0r** [comment]
> Every admission controller receives a request from the apiserver for the resources it subscribes to. This is all dictated by the webhook. Regardless of the outcome (injected or not), the injector has to process all of these requests and presumably it has to buffer the payload and ensure the pods cannot be processed (by looking at the inject value). What I mean by this is that the injector won't receive a subset of the pods from the apiserver, it will receive all pods that are created.

If I understand correctly, it may be possible to alter the webhook configuration so that webhook requests can be more selective. There's some more discussion about this in https://github.com/linkerd/linkerd2/issues/5022.
