### ISSUE TITLE
dtrace exposes a query API that allows you to dynamically instrument program text in a running binary, to provide tracing information. 

### ISSUE THREAD

**Issue by parmishh** [linkerd/linkerd2#10397]
### What problem are you trying to solve?

dtrace exposes a query API that allows you to dynamically instrument program text in a running binary, to provide tracing information. 

It would be nice if linkerd2 provided the networking equivalent, exposing a query API that allowed you to dynamic attach a probe to the control plane that provides information about a distributed trace. 

I think this is useful because at scale it is useful to have principled ways of reasoning about an entire request rather than an aggregate metric. The ability of linkerd to introspect on a request over multiple RPC hops could be a critical step in this process.

ad hoc distributed tracing. I want the ability to understand the lifecycle of a request, beginning to end, dynamically.

### How should the problem be solved?

Presumably with a query API that allows you to dynamically attach queries to the control plane. This could be dtrace-like, or ~relational, ReactiveX, or something else. It is worth considering exposing it as an SDK in a real language so that you can write queries that are like "tell pagerduty if query with x properties occurs".

### Any alternatives you've considered?

There are distributed tracing systems out there, but they have the disadvantage that in many cases your code needs to emit metrics. So, if you're posting the wrong events, you have to change them and re-deploy the app.
Being able to dynamically instrument a global RPC control plane would be very convenient because it requires no changes to code.

### How would users interact with this feature?

Users write a query somehow (e.g., through a CLI, in a text file), which is given linkerd2 to service.   @adleong @olix0r @alpeb 

### Would you like to work on this feature?

None

**Comment by alpeb** [comment]
We currently don't have something like that you can query like you suggest, but I encourage you to take a look at `linkerd viz tap` that might expose those events you're interested in, and then you could build something on top of that. Tap doesn't require changes in the services code. Also note we also offer distributed tracing through the Jaeger extension, but as you point out, that kind of solution does require services to post spans.
