### ISSUE TITLE
Proxy stuck in reconnecting to stale ip address

### ISSUE THREAD

**Issue by pBiczysko** [linkerd/linkerd2#10406]
### What is the issue?

Linkerd-proxy gets into a state where it keeps trying to connect to stale pod IP address of another service. It seems to be happening more often on pods that have hardly any traffic. Once the pod gets into that state it will stay in the reconnecting loop, unable to correctly handle any outbound traffic until the pod is restarted. Depending on whether the stale pod IP is unassigned or already taken over by another pod it will keep returning `HTTP Balancer service in fail-fast` or `gRPC Unimplemented: unknown service` error.  

The observed behavior timeline for one of the affected pods goes as follows: 
1. Presumably the Issue starts at `2023-02-24 14:17:14` a request is made to pod of `service-tracking-widget`.
2. The request fails because of the inability of the `service-tracking-widget` to connect to dependency service due to `Service failed channel closed` error. 
3. `2023-02-24 14:17:14` - `2023-02-24 14:17:17` We can observe 10 logs of:
```
connect timed out after 1s
```
4. Before entering fail-fast mode:
`Request failed: HTTP Balancer service in fail-fast`
5. Due to application level retry we see the next 10 logs of: 
```
Request failed: HTTP Balancer service in fail-fast
```
6. From `2023-02-24 14:17:17` we start to see a looping behavior of reconnect even though there is no more traffic or retries: 
```
Failed to connect: connect timed out after 1s
```
7. That logs would continue until the pod is restarted and would fail every incoming request. 
8. At `2023-02-24 14:28:41` on the affected pod we set log level `warn,linkerd=debug,linkerd_dns=trace,linkerd_proxy_dns_resolve=trace,linkerd_proxy_resolve=trace,linkerd_reconnect=trace` we attach the logs in the next section. 

Additionally around that time we noticed that: 
1. `linkerd-destination` pods have been failing readiness probes as well as restarting due to failed liveness probes. 
2. Two days before we noticed `Dropping resolution due to watchdog` log on the same pod that was later affected. 

### How can it be reproduced?

Unfortunately we do not have a clear way of reproducing the issue. It has been happening on our stage environment at least once per week on different services/pods for a while now. Stage environment was scaling a lot during that times and it is running on preemptive nodes. When it comes to production the issue happened couple of times during the past 6 months.  

### Logs, error output, etc

Logs with default level of when the issue occurred: 
https://gist.github.com/pBiczysko/0b7d694b92bc49ae6d6436fd15945060

Logs with trace level of already present issue: 
https://gist.github.com/pBiczysko/982671c2f17ab2b4e5056da8e547a957

### output of `linkerd check -o short`

```
Linkerd extensions checks
=========================

linkerd-viz
-----------
‼ prometheus is installed and configured correctly
    missing ClusterRoles: linkerd-linkerd-viz-prometheus
    see https://linkerd.io/2.12/checks/#l5d-viz-prometheus for hints

Status check results are √
```

### Environment

* Kubernetes Version: 1.23.14-gke.1800
* Cluster Environment: GKE with kube-proxy
* Linkerd version: stable-2.12.4

### Would you like to work on fixing this bug?

None

**Comment by alpeb** [comment]
Thanks for the detailed write up. Having linkerd-destination pods fail sounds like the source of the problem; if data-plane pods aren't provided up-to-date service info from linkerd-destination, they'll act on cache data that'll become stale, resulting in the issues you see. So it'd be great to see some logs from linkerd-destination (both destination and proxy containers) from around the time leading to failing probes. Please provide them in single line unformatted fashion so it's easier to consume :-)

**Comment by mateiidavid** [comment]
@pBiczysko are you able to try out our new edge version and see if the problem is fixed for you? We fixed a couple of similar issues in the past few weeks and it'd be helpful to know if you see the problems go away on a newer build.
