### ISSUE TITLE
linkerd-control-plane chart modifies destination and proxy-injector deployment template on every helm upgrade

### ISSUE THREAD

**Issue by tkazmierczak-tt** [linkerd/linkerd2#10416]
### What is the issue?

Currently the destination and proxy-injector deployment definitions contain the following annotation `linkerd.io/helm-release-version: {{.Release.Revision | quote}}` which implies a new Deployment rollout on every Helm Release upgrade.

Was that made on purpose? I did not expect such behavior, it breaks idempotency of manifests within the Release.

### How can it be reproduced?

Every helm release upgrade.

### Logs, error output, etc

irrelevant

### output of `linkerd check -o short`

irrelevant

### Environment

irrelevant

### Possible solution

If it's possible remove the mentioned annotations.

### Would you like to work on fixing this bug?

None

**Comment by alpeb** [comment]
This is a great point. We had in the 2.11 branch an annotation `checksum/config` whose value was computed with the injector's RBAC/Webhook config file, but apparently got lost when the charts got split for 2.12. We should bring that back into `main`.

**Comment by jeremychase** [comment]
We want to remove the `linkerd.io/helm-release-version: {{.Release.Revision | quote}}` annotation and add `checksum/config`, based on [helm documentation](https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments).
