### ISSUE TITLE
What is just-cargo

### ISSUE THREAD

**Issue by daixiang0** [linkerd/linkerd2#10458]
### What is the issue?

```
[root linkerd2-proxy]# just fetch
sh: just-cargo: command not found
error: Backtick failed with exit code 127
    |
139 | _objcopy := 'llvm-objcopy-' + `just-cargo --evaluate _llvm-version`
    |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

As https://github.com/linkerd/linkerd2-proxy#building-the-project says, we need only `just` and `cargo`, docs do not say anything about `just-cargo`

### How can it be reproduced?

```
git clone https://github.com/linkerd/linkerd2-proxy.git
cd linker2-proxy
# install just and cargo
just fetch
```

### Logs, error output, etc

```
[root linkerd2-proxy]# just fetch
sh: just-cargo: command not found
error: Backtick failed with exit code 127
    |
139 | _objcopy := 'llvm-objcopy-' + `just-cargo --evaluate _llvm-version`
    |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

### output of `linkerd check -o short`

N/A

### Environment

For a long time

### Would you like to work on fixing this bug?

yes

**Comment by daixiang0** [comment]
@mateiidavid thanks for quick and careful response!

I create https://github.com/linkerd/linkerd2-proxy/pull/2292 to improve doc, please review!

**Comment by mateiidavid** [comment]
Awesome, thanks for the contribution. I'll be closing this now :)
