### ISSUE TITLE
Proxy tries to connect to stale endpoints after rollout deployments

### ISSUE THREAD

**Issue by someone-stole-my-name** [linkerd/linkerd2#10491]
### What is the issue?

After rollout deployments of big un-meshed fleets, the proxies keep trying to connect to stale (no longer existing) endpoints. When that happens, the destination pods get completely out of sync with whats in the cluster and the only solution is to restart the control plane.

### How can it be reproduced?

Not sure if it is the same bug in both versions, but the outcome is the same: the proxy keeps trying to connect to stale IPs, restarting doesn't help, and the only fix is to restart the destination pods.

#### To reproduce it in 2.12:

- Create a vanilla EKS cluster
- Add Linkerd 2.12
```
linkerd install --crds | kubectl apply -f -
linkerd install --set proxyInit.runAsRoot=true --ha | kubectl apply -f -
```
- Add our custom [coredns config](https://gist.github.com/someone-stole-my-name/dd0f83b5b7ce1144c8d1811d2e04a58a#file-coredns-yaml) and a [probe](https://gist.github.com/someone-stole-my-name/dd0f83b5b7ce1144c8d1811d2e04a58a#file-probe-yaml) that does queries through the proxy using TCP.
- Scale coredns to 180 pods:
```
kubectl scale deployment/coredns --replicas=180 -n kube-system
```
- Do a rollout and watch for errors in the probe:
```
kubectl rollout restart deployment/coredns -n kube-system
```

If that doesn't trigger the bug, scale coredns to 100 again, wait until there are only 100 pods and then repeat the above steps from the scale up.

#### To reproduce it in 2.11.5:

- Create a vanilla EKS cluster
- Add Linkerd 2.11
```
linkerd install --set proxyInit.runAsRoot=true --ha | kubectl apply -f -
```
- Add our custom [coredns config](https://gist.github.com/someone-stole-my-name/dd0f83b5b7ce1144c8d1811d2e04a58a#file-coredns-yaml) and a [probe](https://gist.github.com/someone-stole-my-name/dd0f83b5b7ce1144c8d1811d2e04a58a#file-probe-yaml) that does queries through the proxy using TCP.
- Do a rollout and watch for errors in the probe:
```
kubectl rollout restart deployment/coredns -n kube-system
```

### Logs, error output, etc

[2.11.5](https://gist.github.com/someone-stole-my-name/2b75cdd26910587feeb3c109ae637c87)
[2.12.4](https://gist.github.com/someone-stole-my-name/fd66c597b23946ba6c36e330ffab063c)

### output of `linkerd check -o short`

```
Linkerd core checks
===================

linkerd-existence
-----------------
‼ cluster networks can be verified
    the following nodes do not expose a podCIDR:
        ip-10-0-10-5.ec2.internal
        ip-10-0-10-62.ec2.internal
        ip-10-0-14-76.ec2.internal
        ip-10-0-16-201.ec2.internal
        ip-10-0-17-156.ec2.internal
        ip-10-0-20-116.ec2.internal
        ip-10-0-20-213.ec2.internal
        ip-10-0-22-211.ec2.internal
        ip-10-0-27-246.ec2.internal
        ip-10-0-29-183.ec2.internal
        ip-10-0-3-86.ec2.internal
        ip-10-0-30-184.ec2.internal
        ip-10-0-31-127.ec2.internal
        ip-10-0-33-64.ec2.internal
        ip-10-0-37-131.ec2.internal
        ip-10-0-37-224.ec2.internal
        ip-10-0-37-235.ec2.internal
        ip-10-0-42-33.ec2.internal
        ip-10-0-46-27.ec2.internal
        ip-10-0-5-13.ec2.internal
        ip-10-0-6-117.ec2.internal
    see https://linkerd.io/2.11/checks/#l5d-cluster-networks-verified for hints

linkerd-identity
----------------
‼ issuer cert is valid for at least 60 days
    issuer certificate will expire on 2023-04-13T07:53:45Z
    see https://linkerd.io/2.11/checks/#l5d-identity-issuer-cert-not-expiring-soon for hints

linkerd-webhooks-and-apisvc-tls
-------------------------------
‼ proxy-injector cert is valid for at least 60 days
    certificate will expire on 2023-04-13T07:53:45Z
    see https://linkerd.io/2.11/checks/#l5d-proxy-injector-webhook-cert-not-expiring-soon for hints
‼ sp-validator cert is valid for at least 60 days
    certificate will expire on 2023-04-13T07:53:45Z
    see https://linkerd.io/2.11/checks/#l5d-sp-validator-webhook-cert-not-expiring-soon for hints
‼ policy-validator cert is valid for at least 60 days
    certificate will expire on 2023-04-13T07:53:44Z
    see https://linkerd.io/2.11/checks/#l5d-policy-validator-webhook-cert-not-expiring-soon for hints

linkerd-version
---------------
‼ cli is up-to-date
    is running version 2.11.5 but the latest stable version is 2.12.4
    see https://linkerd.io/2.11/checks/#l5d-version-cli for hints

control-plane-version
---------------------
‼ control plane is up-to-date
    is running version 2.11.5 but the latest stable version is 2.12.4
    see https://linkerd.io/2.11/checks/#l5d-version-control for hints

linkerd-control-plane-proxy
---------------------------
‼ control plane proxies are up-to-date
    some proxies are not running the current version:
        * linkerd-destination-76bb49dc48-6q9g6 (stable-2.11.5)
        * linkerd-destination-76bb49dc48-s78jc (stable-2.11.5)
        * linkerd-destination-76bb49dc48-tp4th (stable-2.11.5)
        * linkerd-identity-55548fcf68-c8nfv (stable-2.11.5)
        * linkerd-identity-55548fcf68-nbp8s (stable-2.11.5)
        * linkerd-identity-55548fcf68-sldpr (stable-2.11.5)
        * linkerd-proxy-injector-6f64f6b4cb-87wf6 (stable-2.11.5)
        * linkerd-proxy-injector-6f64f6b4cb-m5p6q (stable-2.11.5)
        * linkerd-proxy-injector-6f64f6b4cb-tm8dj (stable-2.11.5)
    see https://linkerd.io/2.11/checks/#l5d-cp-proxy-version for hints

Linkerd extensions checks
=========================

linkerd-viz
-----------
‼ tap API server cert is valid for at least 60 days
    certificate will expire on 2023-04-13T07:53:45Z
    see https://linkerd.io/2.11/checks/#l5d-tap-cert-not-expiring-soon for hints
‼ viz extension proxies are up-to-date
    some proxies are not running the current version:
        * metrics-api-5c85fb4497-hpjlk (stable-2.11.5)
        * tap-88ff86dbf-4bcbk (stable-2.11.5)
        * tap-88ff86dbf-blrmg (stable-2.11.5)
        * tap-88ff86dbf-gbrmw (stable-2.11.5)
        * tap-injector-658bcfccc-92pww (stable-2.11.5)
        * web-66bfcf75-sxg54 (stable-2.11.5)
    see https://linkerd.io/2.11/checks/#l5d-viz-proxy-cp-version for hints
‼ prometheus is installed and configured correctly
    missing ClusterRoles: linkerd-linkerd-viz-prometheus
    see https://linkerd.io/2.11/checks/#l5d-viz-prometheus for hints

Status check results are √
```

### Environment

- Kubernetes Version: 1.24
- Cluster Environment: EKS
- Linkerd Version: Reproduced in 2.11.5 and 2.12.4

### Additional context

Using CoreDNS to reproduce the issue because that's the deployment where we first saw this behavior, but maybe it is not related to DNS at all and could also affect other services.

While trying to reproduce it in 2.12.4, I've noticed that even when the proxy doesn't break completely, some requests are still routed to the wrong endpoints during the rollout.

### Would you like to work on fixing this bug?

no

**Comment by olix0r** [comment]
@someone-stole-my-name This sounds like an issue that was recently fixed (https://github.com/linkerd/linkerd2/pull/10370). Are you able to test last week's edge release?

**Comment by someone-stole-my-name** [comment]
It seems that https://github.com/linkerd/linkerd2/pull/10370 fixed the original issue, I couldn't break the proxy while using `edge-23.3.1`. 

Even though the proxy didn't break completely, I can still see some requests going to wrong endpoints during a rollout, causing timeouts in the application. Eventually it fixes itself, but I'm not sure what is causing this behavior since all target pods are waiting up to 60s to die, and have a failing `readinessProbe`.

**Comment by mateiidavid** [comment]
@someone-stole-my-name hey, thanks for posting! It's helpful to know that the fix worked for you.

It sounds to me like what you're experiencing now is related more to how shutdowns are being handled, as opposed to a discovery (or stale endpoints) problem. I think it'd be helpful for us to get a new issue with your problem description; handling shutdowns correctly in Kubernetes is non-trivial and it's something we want to improve on in future versions.

If you could please open up an issue with the problem description and maybe some repro steps, that'd be great. Once that's done, I can close this one.
