### ISSUE TITLE
Support config custom resource type

### ISSUE THREAD

**Issue by daixiang0** [linkerd/linkerd2#10568]
### What problem are you trying to solve?

As [doc](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers) says, now Kubernetes supports many resource types.

But in linkerd2, we only support 3 types as https://github.com/linkerd/linkerd2/blob/904a8fc1921350fe32614a58d84f5cf41fd34816/pkg/charts/linkerd2/values.go#L218-L222 

I want linkerd2 become more flexibly.

### How should the problem be solved?

Add `CustomResource ` struct as below:
```
	CustomResource struct {
		Name  string      `json:",name"`
		Value Constraints `json:",inline"`
	}
	Resources struct {
		CPU              Constraints `json:"cpu"`
		Memory           Constraints `json:"memory"`
		EphemeralStorage Constraints `json:"ephemeral-storage"`
		CustomResources []CustomResource `json:",inline"`
	}
```

### Any alternatives you've considered?

Support users edit sidecar config by `kubectl`, while I do not find how to do it.

### How would users interact with this feature?

For scalability and flexibility.

### Would you like to work on this feature?

yes

**Comment by adleong** [comment]
Hi @daixiang0!  This issue is a little bit vague. Can you provide some specifics about your use-case or how a user might use this feature?  What problem are you trying to solve?

**Comment by daixiang0** [comment]
Now many hardware provide accelerators by k8s device plugin, if linkerd wants to use it, must specify resources.

**Comment by daixiang0** [comment]
@adleong ping

**Comment by alpeb** [comment]
Can you give an example of how would that custom resources look like in an injected pod manifest?
