### ISSUE TITLE
Change the behaviour of `NoEndpoints` events when using `EndpointSlice`s

### ISSUE THREAD

**Issue by mateiidavid** [linkerd/linkerd2#10580]
When an `EndpointSlice` object is deleted, we drain all of the addresses from the listener, and send a `NoEndpoints=false` event that signals the Service itself no longer exists. This comes after in #10370 we fixed an issue where `NoEndpoints` events would be sent to listeners when multiple `EndpointSlice` objects were in use (but only a subset deleted).

Although this is not breaking anything at the moment, we should think through what the correct behaviour is here. We had a first pass at this in #10460, however, the solution wasn't quite correct either. We should think through what should happen in this case; processing `EndpointSlice` objects in the same way as `Endpoints` does not seem to work well here.

**Comment by adleong** [comment]
Linkerd's model of service discovery has evolved over time and so has the semantics of this field.  One question that I would like to investigate is if the `NoEndpoints` field is used by the proxy and if so, what exactly does it control.  Understanding this better will inform what the proper behavior is for the control plane.
