### ISSUE TITLE
unable to create linkerd destination pod 

### ISSUE THREAD

**Issue by kvk24680** [linkerd/linkerd2#10581]
### What is the issue?

Hi guys, 

I am using a contabo machine with CentOS7. When I try to deploy linkerd in kubeadm using normal installation method, I find that the linkerd destination pods are stuck in pending state. 

I found I had containers with init errors, but after switching around a few things such as ditching the CNI and using ipvs Kubelet services mode, couldn’t get past the sandbox errors.

### How can it be reproduced?

By installing linkerd in centos 7 using kubeadm cluster. 

### Logs, error output, etc

**Logs of linkerd destination, identity and proxy injector pod**

Defaulted container "linkerd-proxy" out of: linkerd-proxy, destination, sp-validator, policy, linkerd-init (init)
Error from server (BadRequest): container "linkerd-proxy" in pod "linkerd-destination-8bcfd68d8-rr7zl" is waiting to start: PodInitializing

### output of `linkerd check -o short`

Linkerd core checks
===================

linkerd-existence
-----------------
- No running pods for "linkerd-destination" 

### Environment

- Host OS : CentOS7
- Kubernetes cluster : kubeadm
- Linkerd Version : 2.12 

### Additional context

This bug is related to [#8235](https://github.com/linkerd/linkerd2/issues/8235)

### Would you like to work on fixing this bug?

None

**Comment by adleong** [comment]
Hi @kvk24680 

Are you able to determine why the linkerd-destination-8bcfd68d8-rr7zl pod is stuck in PodInitializing state?  Kubernetes provides a number of ways to investigate this kind of thing.  Looking at the output of `kubectl describe -n linkerd po` would be a good start.
