### ISSUE TITLE
Latency Based Routing

### ISSUE THREAD

**Issue by boedy** [linkerd/linkerd2#10591]
### What problem are you trying to solve?

[Based on question asked in slack](https://linkerd.slack.com/archives/C89RTCWJF/p1679045285611849).

When running a stretched cluster spanning multiple datacenters or availability zones we would want to have Linkerd route pods to the closest available pod. Currently I believe linkerd (with the weighted routing algorithm) will in general route to the best performing pods, but some request will occasionally still go to distant pods. Depending how stretched the cluster is, this could add some considerable latency to the request, whilst there might be a pod running on the same host or DC that could have handled it.

### How should the problem be solved?

Linkerd could actively monitor latency between gateway and pod or inter-pod connections. When routing a request, the latency between source and destination could be a factor to decide which pod should be on the receiving end. How much weight should be assigned to latency might be configurable by the user.

### Any alternatives you've considered?

I have developed a creative workaround to make this workable using traffic splits: I’ve developed an operator that assigns the `http://topology.kubernetes.io/region` and `topology.kubernetes.io/zone` node labels to all pods running on those nodes. This allows me to target only pods running in a certain region using a dedicated  service per zone (e.g. `service-west` , `service-east`). Then by using TrafficSplits I can route workloads to the right pods in its zone, with a failover in place in case the pods aren't reachable.

It works.. but I have to jump through a few hoops make it work. Having some latency restrictions would make this a lot easier.

### Would you like to work on this feature?

None

**Comment by adleong** [comment]
Hi @boedy 

> Linkerd could actively monitor latency between gateway and pod or inter-pod connections. When routing a request, the latency between source and destination could be a factor to decide which pod should be on the receiving end. 

This is already how Linkerd's load balancing works.  You can read more about it at: https://linkerd.io/2.12/features/load-balancing/

It is true that some requests will occasionally still go to distant pods.  This is necessary in order to measure the latency, but the amount of traffic that goes to those distant pods will be weighted based on their latency.

**Comment by boedy** [comment]
Hey @adleong

Thank for the follow up. In a usual cluster (one dc) the current load balancing implementation is great, because the internode latency is basically zero. Problems start when a cluster gets stretched across multiple datacenters. A use-case could be deploying one globally stretched cluster used for edge workloads. Noted that there a more challenges here when running such a cluster, but the linkerd load balancer algorithm can be improve so it would work on both.

My suggestion would be that each proxy maintains a hash-tabel to each pod in the cluster measuring its latency. This could be a simple ping. Let's call this latency the **NetworkLatency** and the processing of the request by the pod we shall call the **ProcessingLatency**. The **TotalLatency** = NetworkLatency + ProcessingLatency.

For typical deployments the NetworkLatency would only be a few ms at best. So only the ProcessingLatency would be relevant. This is how Linkerd currently operates.

---

**Let me share an detailed example to better explain the use-case:**

Imagine we have a globally stretched Kubernetes cluster deployed across three datacenters: one in North America (NA), one in Europe (EU), and one in Asia-Pacific (APAC). Each datacenter has a set of pods running the same application, and we're using Linkerd to manage traffic between these pods. The edge workloads are designed to serve clients with low latency, which is crucial for providing a good user experience.

In this scenario, a client in Europe makes a request to the application. Ideally, we would want the request to be served by a pod located in the EU datacenter to minimize latency. However, with the current load balancing implementation, some requests might still be routed to pods in the NA or APAC datacenters, adding considerable latency to the response time. This could negatively impact the user experience for clients in Europe.

By implementing the suggested solution, each proxy would maintain a hash table measuring the NetworkLatency to each pod in the cluster. In our example, let's say that the typical ProcessingLatency for the application is 50ms. The proxies would be aware of the NetworkLatency between datacenters, which we can assume to be as follows:

- NA to EU: 80ms
- NA to APAC: 120ms
- EU to APAC: 100ms

Given this information, when a client in Europe makes a request, the proxy would first consider the NetworkLatency to determine which pods are viable candidates to handle the request. In this case, since the NetworkLatency from EU to NA and APAC is 80ms and 100ms respectively, and both are greater than the typical ProcessingLatency of 50ms, the proxy would prioritize pods within the EU datacenter to handle the request. This is because the TotalLatency (NetworkLatency + ProcessingLatency) would be significantly lower for pods in the EU datacenter compared to those in NA or APAC.

Only if the ProcessingLatency within the EU datacenter increases beyond a certain threshold, say to 100ms, would the proxy consider routing requests to pods in the NA or APAC datacenters as viable alternatives.

By taking into account both the NetworkLatency and ProcessingLatency, the modified load balancing algorithm would help ensure that requests are served by the closest available pods, minimizing latency and providing a better user experience for clients in a globally stretched cluster.

---

Hope this long reply makes sense.  All in all I this could be an optional feature which could be toggled, because as I mentioned in the beginning, most clusters reside within one availability zone.

**Comment by adleong** [comment]
I'll just clarify that Linkerd does client-side load balancing and uses latency as measured by the client to inform load-balancing decisions.  This includes both network latency processing latency (in fact, the client can't even tell the difference).

I'd also recommend taking a look at [Topology Aware Hints](https://kubernetes.io/docs/concepts/services-networking/topology-aware-hints/) which Linkerd supports and may satisfy your use-case.

**Comment by adleong** [comment]
Having Linkerd do out-of-band pings to determine latency is a pretty big architectural change from the way that Linkerd works today and probably not something we'd pursue at this time.
