### ISSUE TITLE
linkerd-multicluster extension installs with duplicate authorizationpolicies

### ISSUE THREAD

**Issue by klingerf** [linkerd/linkerd2#10612]
### What is the issue?

When the `linkerd-multicluster` extension is installed with a gateway, it includes policy resources for the gateway. As far as I can tell, it provides two authorizationpolicies that are named differently but are actually identical.

Here's the spec for the `linkerd-gateway` authorizationpolicy:

https://github.com/linkerd/linkerd2/blob/24adbb6beac2dc0a3cde8f5038d08f2202fa35df/multicluster/charts/linkerd-multicluster/templates/gateway-policy.yaml#L31-L44

And here's the spec for the `linkerd-gateway-probe` authorizationpolicy:

https://github.com/linkerd/linkerd2/blob/24adbb6beac2dc0a3cde8f5038d08f2202fa35df/multicluster/charts/linkerd-multicluster/templates/gateway-policy.yaml#L91-L105

The only difference that I can see between those two specs is this comment:

> allows probes from outside the cluster, as long as they have an identity

And from looking at the spec itself, I'm not sure that comment is correct.

### How can it be reproduced?

View gateway policy objects here: https://github.com/linkerd/linkerd2/blob/main/multicluster/charts/linkerd-multicluster/templates/gateway-policy.yaml

### Logs, error output, etc

View of configured policy for the `linkerd-proxy` server in [Buoyant Cloud](https://buoyant.io/cloud):

![image](https://user-images.githubusercontent.com/9226/227309680-24102759-5244-40d7-a07e-061550332c6d.png)

### output of `linkerd check -o short`

N/A

### Environment

N/A

### Possible solution

Remove one of the authorizationpolicies, or modify the `linkerd-gateway-probe` authorizationpolicy to actually allow probes from outside the cluster.

### Would you like to work on fixing this bug?

no

**Comment by adleong** [comment]
Good find, @klingerf.  This changed in https://github.com/linkerd/linkerd2/pull/10079 but I need to do a bit more investigation to determine what the correct resolution is here
