### ISSUE TITLE
install dashboard missing ClusterRoles

### ISSUE THREAD

**Issue by spring-bu** [linkerd/linkerd2#10641]
### What is the issue?

I install dashboard with this command:

```
linkerd viz install | kubectl apply -f 
```

and then `linkerd viz check` , the result say `missing ClusterRoles: linkerd-linkerd-metrics-api, linkerd-linkerd-tap, linkerd-linkerd-tap-admi`

### How can it be reproduced?

```
linkerd viz install | kubectl apply -f 

linkerd viz check
```

### Logs, error output, etc

```text
linkerd-viz
-----------
√ linkerd-viz Namespace exists
× linkerd-viz ClusterRoles exist
    missing ClusterRoles: linkerd-linkerd-metrics-api, linkerd-linkerd-tap, linkerd-linkerd-tap-admin
    see https://linkerd.io/2.12/checks/#l5d-viz-cr-exists for hints

Status check results are ×
```

### output of `linkerd check -o short`

```text
Linkerd extensions checks
=========================

linkerd-viz
-----------
× linkerd-viz ClusterRoles exist
    missing ClusterRoles: linkerd-linkerd-metrics-api, linkerd-linkerd-tap, linkerd-linkerd-tap-admin
    see https://linkerd.io/2.12/checks/#l5d-viz-cr-exists for hints

Linkerd extensions checks
=========================

linkerd-viz
-----------
× linkerd-viz ClusterRoles exist
    missing ClusterRoles: linkerd-linkerd-metrics-api, linkerd-linkerd-tap, linkerd-linkerd-tap-admin
    see https://linkerd.io/2.12/checks/#l5d-viz-cr-exists for hints

Status check results are ×
```

### Environment

- kubernetes version:  v1.24.8
- OS: ubuntu 22.04
- linkerd version: stable-2.12.4

### Additional context

<img width="852" alt="WeChatWorkScreenshot_6c4cd71f-5bdc-4140-b9af-42c1d3b658c3" src="https://user-images.githubusercontent.com/37682426/228442634-c71b1032-efac-446e-9e17-672a98968961.png">

### Would you like to work on fixing this bug?

None

**Comment by alpeb** [comment]
Can you confirm your CLI version is also stable-2.12.4 (`linkerd version`)?
Also can you paste here the yaml for your linkerd-viz namespace? I could be missing a label.

**Comment by alpeb** [comment]
The label `linkerd.io/extension=viz` is what the `linkerd viz check` tool uses to determine under which namespace is viz installed. You have it set fine in `linkerd-viz`. Maybe you have it by mistake in the `linkerd` namespace as well?

**Comment by spring-bu** [comment]
> The label `linkerd.io/extension=viz` is what the `linkerd viz check` tool uses to determine under which namespace is viz installed. You have it set fine in `linkerd-viz`. Maybe you have it by mistake in the `linkerd` namespace as well?

It was my mistake, the reason is: I installed it once using the helm method and then switched to a command line binary installation, so I left an  extra labele on the linkerd namespace, and after removing the extra label `linkerd.io/extension=viz` on linkerd namespace, the problem was solved,  Thank you very much for your reply and help.
