### ISSUE TITLE
linkerd-cni broken in EKS with the latest AWS CNI addon `1.12.6-eksbuild.1`

### ISSUE THREAD

**Issue by alpeb** [linkerd/linkerd2#10669]
## The Problem

When installing linkerd in ESK using the AWS CNI add-on (enabled by default), the linkerd pods are unable to acquire networking:

```bash
$ k -n linkerd describe po linkerd-identity-6fd8646bbc-46kwq
...
Events:
  Type     Reason                  Age                    From     Message
  ----     ------                  ----                   ----     -------
  Warning  FailedCreatePodSandBox  2m58s (x432 over 96m)  kubelet  (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "ff832e29fc050fc8900ee1c59c0a9ad561b73a7bacc097ccfc9a47f43e104d7a": plugin type="aws-cni" name="aws-cni" failed (add): add cmd: Error received from AddNetwork gRPC call: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:50051: connect: connection refused"
```

## Logs and Output

These are the logs from linkerd-cni:
```bash
$ k -n linkerd-cni logs -f linkerd-cni-7xw74
Wrote linkerd CNI binaries to /host/opt/cni/bin
Installing CNI configuration in "chained" mode for /host/etc/cni/net.d/10-aws.conflist
Using CNI config template from CNI_NETWORK_CONFIG environment variable.
      "k8s_api_root": "https://__KUBERNETES_SERVICE_HOST__:__KUBERNETES_SERVICE_PORT__",
      "k8s_api_root": "https://10.100.0.1:__KUBERNETES_SERVICE_PORT__",
CNI config: {... (OMITTED).. }
Created CNI config /host/etc/cni/net.d/10-aws.conflist
Setting up watches.
Watches established.
```
So our plugin is detecting the presence of AWS CNI's config `10-aws.conflist` and should be adding its config in, but that turns out not to be the case:

```bash
$ k debug node/ip-172-31-43-182.us-east-2.compute.internal  -it --image=ubuntu
$ cat /host/etc/cni/net.d/10-aws.conflist
root@ip-172-31-43-182:/host/etc/cni/net.d# cat 10-aws.conflist
{
  "cniVersion": "0.4.0",
  "name": "aws-cni",
  "disableCheck": true,
  "plugins": [
    {
      "name": "aws-cni",
      "type": "aws-cni",
      "vethPrefix": "eni",
      "mtu": "9001",
      "podSGEnforcingMode": "strict",
      "pluginLogFile": "/var/log/aws-routed-eni/plugin.log",
      "pluginLogLevel": "DEBUG"
    },
    {
      "name": "egress-v4-cni",
      "type": "egress-v4-cni",
      "mtu": "9001",
      "enabled": "false",
      "randomizeSNAT": "prng",
      "nodeIP": "172.31.43.182",
      "ipam": {
         "type": "host-local",
         "ranges": [[{"subnet": "169.254.172.0/22"}]],
         "routes": [{"dst": "0.0.0.0/0"}],
         "dataDir": "/run/cni/v6pd/egress-v4-ipam"
      },
      "pluginLogFile": "/var/log/aws-routed-eni/egress-v4-plugin.log",
      "pluginLogLevel": "DEBUG"
    },
    {
      "type": "portmap",
      "capabilities": {"portMappings": true},
      "snat": true
    }
  ]
}
```

## Affected Versions

Currently when creating an EKS cluster the default AWS CNI addon version is `1.12.2-eksbuild.1`, which is not affected by this issue. But the latest version available, `v1.12.6-eskbuild.1`, is affected.

## Possible Diagnose

Linkerd-cni currently only reacts to the `create` and `delete` events under the `/etc/cni/net.d` directory. 

A user has reported that adding the `moved_to` event fixed the issue, but this hasn't been tested yet.
Also I don't understand how the first `10-aws.conflist` file is first detected and updated by linkerd, and then gets overwritten.
The user provided this link pointing to AWS CNI changes:
https://github.com/aws/amazon-vpc-cni-k8s/commit/261af6c4b388747e17a8ecf16dbd6f2843d3cfde

**Comment by frimik** [comment]
https://github.com/aws/amazon-vpc-cni-k8s/commit/261af6c4b388747e17a8ecf16dbd6f2843d3cfde#diff-39b019ff3ec19f41366d38c83ad4eae0e7f2f4862426fc6d3fbd146c69296c1dR48

The issue is this new `CopyFile` method which now performs a rename which makes the “watch” phase of the linkerd-cni script not work.

**Comment by mateiidavid** [comment]
https://github.com/linkerd/linkerd2/issues/10738 might be a duplicate of this.

**Comment by frimik** [comment]
My method of consuming upstream helm chart with local patch override:
https://github.com/cloud-destroyer/linkerd2-libsonnet

**Comment by alpeb** [comment]
Thanks again for the fixup @frimik :+1: 
I couldn't repro again the exact issue depicted in this issue, but I think it must have been a manifestation of #10738. So closing this in favor of that one, for which I've pushed linkerd/linker2-proxy-init#230. Thanks @frimik for the fix!
