### ISSUE TITLE
Print CLI extension version information with `linkerd version` command

### ISSUE THREAD

**Issue by risingspiral** [linkerd/linkerd2#10671]
### What problem are you trying to solve?

With https://github.com/linkerd/linkerd2/pull/10588 there is the new concept of CLI-based checks being introduced into Linkerd.

We want to enable a way for these checks to signal their version information to users when running the `linkerd version` command.

### How should the problem be solved?

The proposal is to extend the _extension-metadata object to include a "version" property with a string that communicates version information to the user. Example:

```
$ linkerd-foo _extension-metadata
{
  "name": "linkerd-foo",
  "checks": "always",
  "version": "Linkerd Foo version v0.1.117"
}
```

The Linkerd CLI machinery discovers this information and when present includes it in the `linkerd version` output:

```
$ linkerd version
Linkerd Foo version: v0.1.117
Client Linkerd version: edge-23.3.3
Server Linkerd version: edge-23.3.3
```

### Any alternatives you've considered?

Prepending or appending doesn't really matter. It might be useful to require this information so that the commands being discovered and run are explicitly listed.

### How would users interact with this feature?

Via the linkerd version output as mentioned previously.

### Would you like to work on this feature?

None

**Comment by adleong** [comment]
a few questions that jump to mind:

How does this interact with existing extensions which don't currently expose a version number?  If some extension versions are showing up in the output of `linkerd version` I think that users would expect that this is a full list of all installed (or available?) extensions.

Is it worth using semver or some approximation of it here?  It may be useful to be able to compare two versions and know which one is newer e.g. to know if a user is attempting an upgrade or a downgrade

Linkerd and Kubernetes both have a notion of client version vs server version.  This would give us client version but no server version which could lead to confusion if `linkerd version` prints one version for an extension but actually a different version is installed on the cluster.

**Comment by olix0r** [comment]
> Linkerd and Kubernetes both have a notion of client version vs server version. This would give us client version but no server version which could lead to confusion if linkerd version prints one version for an extension but actually a different version is installed on the cluster.

I think this is a good point.

If running `linkerd version` with the SMI extension installed, for instance, I'd expect to see both the client-side and server-side versions.

**Comment by olix0r** [comment]
Though, it appears that `linkerd-smi` doesn't share server versions yet, anyway. Perhaps a path forward is to support explicit `client_version` and `cluster_version` (or something like that) so extensions can specify what version they are providing.
