### ISSUE TITLE
linkerd-viz and linkerd-jaeger charts do not support nodeAffinity

### ISSUE THREAD

**Issue by volver-13** [linkerd/linkerd2#10680]
### What is the issue?

In contrast to [linkerd-control-plane](https://github.com/linkerd/linkerd2/blob/main/charts/linkerd-control-plane/templates/proxy-injector.yaml#L58) helm chart `linkerd-viz` and `linkerd-jaeger` helm charts do not support nodeAffinity at the moment. Can you please add this functionality there unless there is any specific reason not to do it?

### How can it be reproduced?

Deploy latest version of linkerd-viz and linkerd-jaeger

### Logs, error output, etc

no errors

### output of `linkerd check -o short`

not required

### Environment

kubernetes 1.25.5
linkerd 2.12.4

### Possible solution

update helm charts to add nodeAffinity

### Would you like to work on fixing this bug?

None

**Comment by jrsalgado** [comment]
I would like to work on this, can you assign this to me or accept PR?

**Comment by adleong** [comment]
Hi @jrsalgado!  You don't need to be assigned in order to work on this.  Looking forward to seeing a PR!  Please reach out if you have any questions.

**Comment by jrsalgado** [comment]
@adleong here it is a PR to add linkerd-jeaguer charts nodeAffinity settings, will create a separate PR for linkerd-viz soon.

**Comment by jrsalgado** [comment]
Hi @adleong, here it is the viz nodeAffinity too

**Comment by reyes256** [comment]
Helloo @adleong, the PR about viz nodeAffinity is open again.
