### ISSUE TITLE
linkerd-viz and linkerd-multicluster components rely on a default-inbound-policy of all-unauthenticated for metrics scraping

### ISSUE THREAD

**Issue by andrew-gropyus** [linkerd/linkerd2#10691]
### What is the issue?

There is no AuthorizationPolicy to open up /metrics for the linkerd-viz components (web, tap, tap-injector, metrics-api), or for the linkerd-proxy running on those components. The same is true for the linkerd-proxy of the service-mirror.

This is therefore relying on the default inbound policy of all-unauthenticated in order for metrics to be scraped.

When changing to a different default policy, such as deny, prometheus will fail to scape these metrics endpoints.

### How can it be reproduced?

Set a default inbound policy to deny, observe the prometheus targets to fail to scrape with 403s.

### Logs, error output, etc

```
web-74f8bb4c67-945fh linkerd-proxy [ 72037.811391s]  INFO ThreadId(02) daemon:admin{listen.addr=0.0.0.0:4191}: linkerd_app_inbound::policy::http: Request denied server.group= server.kind=default server.name=deny route.group= route.kind=default route.name=default client.tls=None(NoClientHello) client.ip=10.203.1.120
web-74f8bb4c67-945fh linkerd-proxy [ 72037.811438s]  INFO ThreadId(02) daemon:admin{listen.addr=0.0.0.0:4191}:rescue{client.addr=10.203.1.120:46010}: linkerd_app_core::errors::respond: HTTP/1.1 request failed error=unauthorized request on route
```

### output of `linkerd check -o short`

```
Linkerd core checks
===================

linkerd-version
---------------
‼ cli is up-to-date
    is running version 2.12.3 but the latest stable version is 2.12.4
    see https://linkerd.io/2.12/checks/#l5d-version-cli for hints

control-plane-version
---------------------
‼ control plane and cli versions match
    control plane running edge-23.3.4 but cli running stable-2.12.3
    see https://linkerd.io/2.12/checks/#l5d-version-control for hints

linkerd-control-plane-proxy
---------------------------
‼ control plane proxies and cli versions match
    linkerd-destination-54585b8d98-26ns9 running edge-23.3.4 but cli running stable-2.12.3
    see https://linkerd.io/2.12/checks/#l5d-cp-proxy-cli-version for hints

linkerd-ha-checks
-----------------
‼ pod injection disabled on kube-system
    kube-system namespace needs to have the label config.linkerd.io/admission-webhooks: disabled if injector webhook failure policy is Fail
    see https://linkerd.io/2.12/checks/#l5d-injection-disabled for hints

Linkerd extensions checks
=========================

linkerd-multicluster
--------------------
‼ multicluster extension proxies and cli versions match
    linkerd-gateway-6f5f459bf6-w2dwd running edge-23.3.4 but cli running stable-2.12.3
    see https://linkerd.io/2.12/checks/#l5d-multicluster-proxy-cli-version for hints

Linkerd extensions checks
=========================

linkerd-viz
-----------
‼ viz extension proxies and cli versions match
    metrics-api-794bdb9587-4845v running edge-23.3.4 but cli running stable-2.12.3
    see https://linkerd.io/2.12/checks/#l5d-viz-proxy-cli-version for hints
‼ prometheus is installed and configured correctly
    missing ClusterRoles: linkerd-linkerd-viz-prometheus
    see https://linkerd.io/2.12/checks/#l5d-viz-prometheus for hints

Status check results are √
```

### Environment

- Kubernetes: 1.25.5
- AKS
- Linkerd: 2.12.3

### Possible solution

1. Set a default policy on the linkerd-viz and linkerd-multicluster namespace to all-authenticated (not sure of the implications here)
2. Create fine grained authorization policies for these components, opening up the probe endpoints and metrics endpoints

### Would you like to work on fixing this bug?

maybe

**Comment by adleong** [comment]
Hi @andrew-gropyus.  There is a `linkerd viz allow-scrapes` command which generates the appropriate authorization resources to allow prometheus to scrape a resource or namespace.  

https://linkerd.io/2.12/reference/cli/viz/#allow-scrapes

Does that satisfy the use-case here?

**Comment by andrew-gropyus** [comment]
Hey @adleong, this would definitely work for us and is an option on the table. At this point some guidance on direction would be nice.

My feeling is that linkerd components should work out of the box within some sort of bounds of 'reasonable' configuration. It could be that a default deny policy is a reasonable configuration, so we could expect the linkerd components to keep working.

From our side we want to avoid doing any customization of the linkerd components to reduce maintenance burden.

Would the linkerd team be open to a PR here to set up some out of the box AuthorizationPolicies for some of the components I mentioned above? I could start off with something small in scope to get the conversation rolling.
