### ISSUE TITLE
`linkerd mc prune` shouldn't consider service mirror resources

### ISSUE THREAD

**Issue by alpeb** [linkerd/linkerd2#10706]
I stumbled upon this while testing MC upgrading. The resources created by `linkerd mc link` under the `linkerd-multicluster` namespace are labeld with `linkerd.io/extension: multicluster`, so `linkerd mc prune` will flag them for deletion when comparing against the original resources in that namespace.

It might make sense to keep that label, and maybe add an additional one that `linkerd mc prune` would filter out.

**Comment by alpeb** [comment]
Also for some reason the `linkerd-service-mirror-remote-access-default` ClusterRole and ClusterRoleBinding are getting flagged as well, even though they're not created by `linkerd mc link`

**Comment by olix0r** [comment]
It sound like the prune command has some maybe bigger issues. What problem is it trying to solve?

**Comment by olix0r** [comment]
I ask because another potential solution is to simply disable the command until we've sorted it out

**Comment by adleong** [comment]
Context for prune is in https://github.com/linkerd/linkerd2/pull/10303 and the issue linked from that PR

**Comment by olix0r** [comment]
So it's new then? What is the risk if we hold it back from the release?

**Comment by adleong** [comment]
Without this command, when a user does an upgrade, any resources present in the previous version which are not present in the target version will not be removed.

Concretely in an upgrade to 2.13, I believe this will result in keeping some duplicate authorization resources which were renamed since 2.12 as well as some other authorization resources rated to probes which were removed.

**Comment by alpeb** [comment]
I tried finding a unique label identifying entries from `linkerd mc link` output but there aren't any.
`component: service-mirror` came close except that just for the service mirror deployment we use something different: `component: linkerd-service-mirror` which is also used by other resources in that extension :unamused: 

We could have `linkerd mc prune` get around this through more complex logic instead of simply using a label selector like it currently does, but IMO the best is to cleanup these labels for now in 2.13.x and delay the inclusion of `linkerd mc prune` for 2.14 to use them.

**Comment by risingspiral** [comment]
https://www.notion.so/buoyantio/Multicluster-Prune-2003ebba9ae44846a2a91054338372d3

**Comment by risingspiral** [comment]
Closing this as the agreement from RFC is to to leave things as they are for now with `prune` not implemented for mc
