### ISSUE TITLE
Add missing label `linkerd.io/extension`

### ISSUE THREAD

**Issue by alpeb** [linkerd/linkerd2#10705]
Some resources like `PodDisruptionBudget/linkerd-gateway`, all under `service-mirror-policy.yaml` and `namespace-metadata[-rbac].yaml` are lacking that label, which is relied on by `linkerd mc prune`. I haven't checked for other extensions, but this should be checked globally.

**Comment by royadaneshi** [comment]
excuse me what should exactly we do?

**Comment by SubhajitDutta07** [comment]
hello, i would like to work on this issue, @alpeb .
Will you please point out the directory where these 2 files exist.
I understand what i need to add but under what element.

**Comment by SubhajitDutta07** [comment]
hello, i would like to work on this issue, @alpeb .
I found the file for it as well.

**Comment by SubhajitDutta07** [comment]
Is this the changes you are looking for in the file service-mirror-policy.yaml ?
![Screenshot from 2023-04-21 22-46-48](https://user-images.githubusercontent.com/104216478/233696863-be034349-459e-4d5f-9563-071fb6afe819.png)
