### ISSUE TITLE
linkerd2-cni chaining incompatible with upgraded aws-vpc-cni (aws-node) v1.12.x

### ISSUE THREAD

**Issue by frimik** [linkerd/linkerd2#10720]
### What is the issue?

Sort of a revisit of https://github.com/linkerd/linkerd2/issues/2219#issuecomment-1170778317

Changes in newer aws-node VPC CNI breaks chaining because now the AWS VPC CNI *does* actually perform a *move* of the conflist file on the same filesystem: 

https://github.com/aws/amazon-vpc-cni-k8s/commit/261af6c4b388747e17a8ecf16dbd6f2843d3cfde#diff-46c881e5a76824159499c9b1a118b3b98bb36f630fcbb23f929b7b3ed13969c7L40

### How can it be reproduced?

- Install linkerd2-cni of an edge version or latest stable
- upgrade aws-node to v1.12.6

The chaining in linkerd2-cni will now not detect the new way `aws-node` performs its conflist installation. Depending on DaemonSet pod starting order, you will either have failing linkerd Pods failing to start altogether because aws-node isn't functioning.

### Logs, error output, etc

The chaining in linkerd2-cni will now not detect the new way `aws-node` performs its conflist installation.

### output of `linkerd check -o short`

```
#
```

### Environment

Amazon EKS v1.21 or later

### Possible solution

Need to also monitor the `moved_to` / `MOVED_TO` events, similar to:

```diff
diff --git a/lib/linkerd2-libsonnet/gitvendor/cni-plugin/deployment/scripts/install-cni.sh b/lib/linkerd2-libsonnet/gitvendor/cni-plugin/deployment/scripts/install-cni.sh
index b495ff6bb..52e586582 100755
--- a/lib/linkerd2-libsonnet/gitvendor/cni-plugin/deployment/scripts/install-cni.sh
+++ b/lib/linkerd2-libsonnet/gitvendor/cni-plugin/deployment/scripts/install-cni.sh
@@ -275,8 +275,8 @@ sync() {
       echo "No active CNI configuration file found after $ev event; re-installing in \"interface\" mode"
       install_cni_conf "${DEFAULT_CNI_CONF_PATH}"
     fi
-  elif [ "$ev" = 'CREATE' ]; then
-    # When the event type is 'CREATE', we check the previously observed SHA (updated
+  elif [ "$ev" = 'CREATE' -o "$ev" = 'MOVED_TO' ]; then
+    # When the event type is 'CREATE' or 'MOVED_TO', we check the previously observed SHA (updated
     # with each file watch) and compare it against the new file's SHA. If they
     # differ, it means something has changed.
     new_sha=$(sha256sum "${filepath}" | while read -r s _; do echo "$s"; done)
@@ -301,7 +301,7 @@ sync() {
 # the same system partition, `mv` simply renames, however, that won't be the
 # case so we don't watch any "moved_to" or "moved_from" events.
 monitor() {
-  inotifywait -m "${HOST_CNI_NET}" -e create,delete |
+  inotifywait -m "${HOST_CNI_NET}" -e create,delete,moved_to |
     while read -r directory action filename; do
       if [[ "$filename" =~ .*.(conflist|conf)$ ]]; then 
         echo "Detected change in $directory: $action $filename"
```

### Would you like to work on fixing this bug?

maybe

**Comment by alpeb** [comment]
Hi @frimik , thanks for the writeup. Was it you who reported this directly to @mateiidavid? I created #10669 to track the issue based on those reports.

**Comment by frimik** [comment]
> Hi @frimik , thanks for the writeup. Was it you who reported this directly to @mateiidavid? I created #10669 to track the issue based on those reports.

Yes. That was me. I see. Then this can be closed. Mateii asked me to file issue but I was very slow to act on that and missed you had created one.
