### ISSUE TITLE
Potential typo in viz/namespace-metadata job's command line specification, leading to job failure

### ISSUE THREAD

**Issue by ivanov-slk** [linkerd/linkerd2#10729]
### What is the issue?

I get `error: unexpected argument found` when installing `linkerd-viz` via Helm. The error is printed in the logs of the `Job` `namespace-metadata`.

Without being at all acquainted with `linkerd`'s internals, it seems that there is a redundant interval here:
https://github.com/linkerd/linkerd2/blob/main/viz/charts/linkerd-viz/templates/namespace-metadata.yaml#L59

### How can it be reproduced?

Try installing `linkerd-viz` via Helm for source code release `stable-2.13.0` and chart version `30.8.0` with external Prometheus (i.e. `.Values.prometheusUrl` set). 
Works fine with `30.6.3`.

### Logs, error output, etc

```
>>> kubectl logs namespace-metadata-k9zlm -n linkerd
error: unexpected argument found
```

### output of `linkerd check -o short`

```
vagrant@master-1:~$ linkerd check -o short
linkerd-cni-plugin
------------------
× cni plugin ConfigMap exists
    configmaps "linkerd-cni-config" not found
    see https://linkerd.io/2.13/checks/#cni-plugin-cm-exists for hints

Status check results are ×
```

### Environment

kubernetes: 1.26.3
OS: Ubuntu 22.10
cluster: bare metal (in Virtualbox VMs)

### Possible solution

Remove the interval [here](https://github.com/linkerd/linkerd2/blob/main/viz/charts/linkerd-viz/templates/namespace-metadata.yaml#L59).

### Would you like to work on fixing this bug?

maybe

**Comment by agalue** [comment]
I experienced the same issue. The problem is that the argument was written as `-- prometheus-url` whereas it has been `--prometheus-url` (there is an extra space):
https://github.com/linkerd/linkerd2/blob/main/viz/charts/linkerd-viz/templates/namespace-metadata.yaml#L59-L61
