### ISSUE TITLE
Release links don't appear to work

### ISSUE THREAD

**Issue by jack1902** [linkerd/linkerd2#10734]
### What is the issue?

When reviewing the release notes, hitting the links such as https://linkerd.io/2.13/tasks/circuit-breaking

result in a 404. I believe it should be `https://linkerd.io/2.13/tasks/circuit-breakers/` instead of `circuit-breaking` (`-breaking` -> `breakers`

### How can it be reproduced?

Visit the release page: https://github.com/linkerd/linkerd2/releases/tag/stable-2.13.0 and then visit the circuit breaking hyperlink

### Logs, error output, etc

browser 404'

### output of `linkerd check -o short`

NA

### Environment

Github release page

### Possible solution

result in a 404. I believe it should be `https://linkerd.io/2.13/tasks/circuit-breakers/` instead of `circuit-breaking` (`-breaking` -> `breakers`

### Would you like to work on fixing this bug?

no

**Comment by hawkw** [comment]
Whoops, good catch. I'll fix the link refs right away!

**Comment by hawkw** [comment]
Gah, I forgot. The GitHub release should point at the correct place now, and PR #10792 will fix the changelog link.
