### ISSUE TITLE
MultiCluster Link(service mirror) pods are in CrashLoopBackOff state

### ISSUE THREAD

**Issue by srreddy2020** [linkerd/linkerd2#10751]
### What is the issue?

We have upgraded the Linkerd MultiCluster link component(helm chart) from 2.9.5 to 2.12.04.

2.12.4 link Image: linkerd-controller:stable-2.12.4
2.9.5 link Image: linkerd:controller-stable-2.9.5
after upgrade pods are continues to restart and the final state is CrashLoopBackOff.

After upgrading the chart to 2.12.4 and if i keep the image version to stable-2.9.5 -Pods are running

Could someone help me on this ,what's the issue here, if its configuration issue, how its working with old Image(2.9.5)
In our environment all the linkerd components are upgraded to 2.12.04

### How can it be reproduced?

Upgrade Linkerd from 2.9.5 to 2.12.04
Upgrade Linkerd-Multicluster from 2.9.5 to 2.12.04
Upgrade linkerd component  from 2.9.5 to 2.12.04
Check linkerd-service-mirror pods status

### Logs, error output, etc

time="2023-04-14T08:28:59Z" level=warning msg="failed to register Prometheus gauge Desc{fqName: \"service_cache_size\", help: \"Number of items in the client-go service cache\", constLabels: {}, variableLabels: []}: duplicate metrics collector registration attempted"
time="2023-04-14T08:28:59Z" level=warning msg="failed to register Prometheus gauge Desc{fqName: \"endpoint_cache_size\", help: \"Number of items in the client-go endpoint cache\", constLabels: {}, variableLabels: []}: duplicate metrics collector registration attempted"
time="2023-04-14T08:29:02Z" level=warning msg="Gateway returned unexpected status 404. Marking as unhealthy" probe-key=plt-uat-dmz-apieks-use1
time="2023-04-14T08:29:06Z" level=warning msg="Gateway returned unexpected status 404. Marking as unhealthy" probe-key=plt-uat-dmz-apieks-use1
time="2023-04-14T08:29:09Z" level=warning msg="Gateway returned unexpected status 404. Marking as unhealthy" probe-key=plt-uat-dmz-apieks-use1
time="2023-04-14T08:29:12Z" level=warning msg="Gateway returned unexpected status 404. Marking as unhealthy" probe-key=plt-uat-dmz-apieks-use1
time="2023-04-14T08:29:15Z" level=warning msg="Gateway returned unexpected status 404. Marking as unhealthy" probe-key=plt-uat-dmz-apieks-use1
time="2023-04-14T08:29:18Z" level=warning msg="Gateway returned unexpected status 404. Marking as unhealthy" probe-key=plt-uat-dmz-apieks-use1
time="2023-04-14T08:29:22Z" level=warning msg="Gateway returned unexpected status 404. Marking as unhealthy" probe-key=plt-uat-dmz-apieks-use1
time="2023-04-14T08:29:25Z" level=warning msg="Gateway returned unexpected status 404. Marking as unhealthy" probe-key=plt-uat-dmz-apieks-use1
time="2023-04-14T08:29:28Z" level=warning msg="Gateway returned unexpected status 404. Marking as unhealthy" probe-key=plt-uat-dmz-apieks-use1
time="2023-04-14T08:29:31Z" level=warning msg="Gateway returned unexpected status 404. Marking as unhealthy" probe-key=plt-uat-dmz-apieks-use1
time="2023-04-14T08:29:34Z" level=warning msg="Gateway returned unexpected status 404. Marking as unhealthy" probe-key=plt-uat-dmz-apieks-use1
time="2023-04-14T08:29:37Z" level=warning msg="Gateway returned unexpected status 404. Marking as unhealthy" probe-key=plt-uat-dmz-apieks-use1
time="2023-04-14T08:29:41Z" level=warning msg="Gateway returned unexpected status 404. Marking as unhealthy" probe-key=plt-uat-dmz-apieks-use1
time="2023-04-14T08:29:44Z" level=warning msg="Gateway returned unexpected status 404. Marking as unhealthy" probe-key=plt-uat-dmz-apieks-use1
time="2023-04-14T08:29:47Z" level=warning msg="Gateway returned unexpected status 404. Marking as unhealthy" probe-key=plt-uat-dmz-apieks-use1
time="2023-04-14T08:29:50Z" level=warning msg="Gateway returned unexpected status 404. Marking as unhealthy" probe-key=plt-uat-dmz-apieks-use1
time="2023-04-14T08:29:53Z" level=warning msg="Gateway returned unexpected status 404. Marking as unhealthy" probe-key=plt-uat-dmz-apieks-use1
time="2023-04-14T08:29:56Z" level=warning msg="Gateway returned unexpected status 404. Marking as unhealthy" probe-key=plt-uat-dmz-apieks-use1
time="2023-04-14T08:29:59Z" level=fatal msg="failed to sync caches"

### output of `linkerd check -o short`

deploying helm charts through command prompt

### Environment

Kubernetes 2.24

### Would you like to work on fixing this bug?

None

**Comment by alpeb** [comment]
The error means the service mirror can't establish the connection to the gateway on the target cluster. Have you also upgraded the target cluster to 2.12.4 (all components need to be updated: linkerd-crds, linkerd-control-plane and linkerd-multicluster)? Do both source and target cluster keep on using the same root certificate?
In order to better diagnose this you'll need to install the linkerd CLI (version stable-2.12.4)  to be able to run `linkerd check` on your source cluster. It doesn't matter if you installed linkerd via Helm; the `linkerd check` command will run locally and won't modify anything in your cluster. 
Besides running the check, you should also re-generate the Link resources via `linkerd multicluster link`, run against the context of your target cluster, but applying the resulting resource on your source cluster, as detailed in the [docs](https://linkerd.io/2.13/tasks/multicluster/#linking-the-clusters). Finally, please note we don't support upgrades between more than one major version, so we'd advise that you first upgrade to stable-2.10.2, and when that works, upgrade to stable-2.11.5 and finally when that's working fine proceed to stable-2.12.4 (and if you can stable-2.13.0 that just came out :wink: ).

Let us know how it goes!

**Comment by srreddy2020** [comment]
Thanks for the reply Alpeb.
Q)Have you also upgraded the target cluster to 2.12.4 (all components need to be updated: linkerd-crds, linkerd-control-plane and linkerd-multicluster)? 
ans) Yes, all the components in both the clusters running on same version
Q)Do both source and target cluster keep on using the same root certificate? 
ans)Yes, same trust root certificate being used

1)One more doubt linkerd-proxy container  is not injected for service-mirror pods -but other components linkerd-proxy injected except service-mirror pod, what could be the reason.
2)Service-morror pods are going into crashloop in one cluster ,other cluster pods are  running

**Comment by alpeb** [comment]
> 1)One more doubt linkerd-proxy container is not injected for service-mirror pods -but other components linkerd-proxy injected except service-mirror pod, what could be the reason.

Oh that's definitely the source of the problem. Without a proxy that pod can't establish an mTLS connection to the gateway in the target cluster. Try doing `kubectl describe` on the deployment of that pod to see if there's an event describing the reason for not having been injected. The command `linkerd check` might also give some hints.

**Comment by srreddy2020** [comment]
@alpeb 
There are no events on service mirror pod except warning "kubelet  Back-off restarting failed container".
linkerd cli,not possible in our environment.

Also see some logs in gateway pod,please check below and guide me to fix this issue.
**[184005.234115s]  INFO ThreadId(01) inbound: linkerd_app_core::serve: Connection closed error=direct connections must be mutually authenticated error.sources=[direct connections must be mutually authenticated] client.addr=10.155.116.45:35648
[184005.576130s]  INFO ThreadId(01) inbound: linkerd_app_core::serve: Connection closed error=direct connections must be mutually authenticated error.sources=[direct connections must be mutually authenticated] client.addr=10.155.114.17:64477**

**Comment by srreddy2020** [comment]
@alpeb,
We fixed all the issues(thanks for the suggestions), except linkerd-proxy not injected.
for service mirror pods linkerd-proxy not injected, can you suggest me what we are missing here.
(linkerd.proxy enabled annotation already added)

**Comment by alpeb** [comment]
You can try watching the logs for the `proxy-injector` container in the `linkerd-proxy-injector` pod, and bounce the service mirror pod and see what gets logged. If nothing gets logged that could also be a hint. Try setting the logs at debug level to get more info.

**Comment by srreddy2020** [comment]
@alpeb sorry for the delay from my side.
issue:- linkerd-service-mirror pods still it is 1\1(likerd-proxy did not inject)
Only service mirror pods are not injecting with linkerd-proxy,other pods its injected
I enabled debug log, still i could not get much info.
can you let me know what other options i can explore

**Comment by alpeb** [comment]
I insist that running `linkerd check` can be of help here. Also please check the events for the service mirror deployment, not the pod, via `kubectl describe`.
