### ISSUE TITLE
Outstand blog in the website

### ISSUE THREAD

**Issue by daixiang0** [linkerd/linkerd2#10763]
### What is the issue?

https://linkerd.io/2.12/tasks/using-ingress/#ambassador

The doc about how to deploy ambassador with linkerd2 (https://buoyant.io/blog/emissary-and-linkerd-the-best-of-both-worlds) can not work as it says.

### How can it be reproduced?

https://linkerd.io/2.12/tasks/using-ingress/#ambassador

### Logs, error output, etc

N/A

### output of `linkerd check -o short`

2.12

### Environment

N/A

### Would you like to work on fixing this bug?

yes

**Comment by adleong** [comment]
Hi @daixiang0, can you elaborate?  What is incorrect in the documentation?  What, specifically, doesn't work?

**Comment by daixiang0** [comment]
I follow the steps in the https://buoyant.io/blog/emissary-and-linkerd-the-best-of-both-worlds, it does not work as it said.
