### ISSUE TITLE
policy-controller error 415: Unsupported Media Type

### ISSUE THREAD

**Issue by xuchenCN** [linkerd/linkerd2#10770]
### What is the issue?

k8s version 1.18.16
linkerd version 2.13.1
image: cr.l5d.io/linkerd/policy-controller:stable-2.13.0

policy container can't setup :

logs shown

```
Error: failed to get lease: ApiError: 415: Unsupported Media Type: UnsupportedMediaType (ErrorResponse { status: "Failure", message: "415: Unsupported Media Type", reason: "UnsupportedMediaType", code: 415 })

Caused by:
    0: ApiError: 415: Unsupported Media Type: UnsupportedMediaType (ErrorResponse { status: "Failure", message: "415: Unsupported Media Type", reason: "UnsupportedMediaType", code: 415 })
    1: 415: Unsupported Media Type: UnsupportedMediaType
```

### How can it be reproduced?

deploy k8s 1.18.6 and linkerd 2.13.1 

### Logs, error output, etc

Error: failed to get lease: ApiError: 415: Unsupported Media Type: UnsupportedMediaType (ErrorResponse { status: "Failure", message: "415: Unsupported Media Type", reason: "UnsupportedMediaType", code: 415 })

Caused by:
    0: ApiError: 415: Unsupported Media Type: UnsupportedMediaType (ErrorResponse { status: "Failure", message: "415: Unsupported Media Type", reason: "UnsupportedMediaType", code: 415 })
    1: 415: Unsupported Media Type: UnsupportedMediaType

### output of `linkerd check -o short`

```
kubernetes-version
------------------
× is running the minimum Kubernetes API version
    Kubernetes is on version [1.18.16], but version [1.21.0] or more recent is required
    see https://linkerd.io/2.13/checks/#k8s-version for hints

linkerd-existence
-----------------
× 'linkerd-config' config map exists
    configmaps "linkerd-config" not found
    see https://linkerd.io/2.13/checks/#l5d-existence-linkerd-config for hints

Status check results are ×
```

### Environment

- Kubernetes 1.18.16
- OS centos7
- Baremetal
- Linkerd 2.13.1

### Would you like to work on fixing this bug?

None

**Comment by risingspiral** [comment]
Thanks for the submission. Unfortunately Linkerd 2.13 is compatible with Kubernetes 1.21.0 through 1.27.

Please attempt the initialization on a cluster with 1.21 and let us know if you see the same issue.
