### ISSUE TITLE
seeing TLS handshake errors from 'tap' in logs

### ISSUE THREAD

**Issue by pdeva** [linkerd/linkerd2#10804]
### What is the issue?

seeing tons of messages like this from the `tap` container in our logs

```
2023/04/22 18:33:26 http: TLS handshake error from 10.0.60.225:56498: EOF
```

Screenshot of logs:
<img width="1613" alt="Screenshot 2023-04-22 at 4 18 33 PM" src="https://user-images.githubusercontent.com/3190176/233811536-0ff49606-dd2e-4220-bf91-ef3016c2f5d9.png">

That said `tap` seems to be working fine in the dashboard:
<img width="1226" alt="Screenshot 2023-04-22 at 4 18 59 PM" src="https://user-images.githubusercontent.com/3190176/233811540-f4214f90-3dfd-4544-85cb-6dd052e47e0a.png">

What can we do to debug this.

### How can it be reproduced?

we just installed linkerd helm chart via argocd...

### Logs, error output, etc

```
2023/04/22 18:33:26 http: TLS handshake error from 10.0.60.225:56498: EOF
```

### output of `linkerd check -o short`

```
api-59cc8bffc-gthsn (stable-2.12.4)
	* prometheus-59fc648fb8-jjj9m (stable-2.12.4)
	* tap-77d96c97b9-2vrhz (stable-2.12.4)
	* tap-injector-745bfc9c85-dg5sb (stable-2.12.4)
	* web-6964c75b88-wb4xk (stable-2.12.4)
    see https://linkerd.io/2.13/checks/#l5d-viz-proxy-cp-version for hints
‼ viz extension proxies and cli versions match
    metrics-api-59cc8bffc-gthsn running stable-2.12.4 but cli running stable-2.13.1
    see https://linkerd.io/2.13/checks/#l5d-viz-proxy-cli-version for hints

linkerd-smi
-----------
‼ Linkerd extension command linkerd-smi exists
    exec: "linkerd-smi": executable file not found in $PATH
```

### Environment

 - EKS 1.26
 - linkerd 2.12.4
 - bottlerocket os 
 - ARM64

### Would you like to work on fixing this bug?

None

**Comment by adleong** [comment]
Can you identify what the IPs from those logs (e.g. 10.0.60.225) correspond to?  Are they meshed pods?  Do those pods have tap enabled?  You can use `linkerd viz check --proxy` to check.

**Comment by pdeva** [comment]
seems the ip is of the `tap` pod itself for some reason... 🤔 
<img width="2868" alt="Screenshot 2023-04-27 at 5 47 06 PM" src="https://user-images.githubusercontent.com/3190176/235028088-2157a687-c787-4c7f-aa8d-ef8dea2fb02e.png">

**Comment by adleong** [comment]
Hi @pdeva 

Am I interpreting this correctly that the tap logs are complaining about a handshake error from... itself?  Very strange, indeed.  Do you have steps that we could use to reproduce this issue?

**Comment by pdeva** [comment]
we havent done anything special apart from literally installing the helm chart…

**Comment by adleong** [comment]
Unfortunately, I'm not able to reproduce this just from installing the Helm charts:

```console
> helm install linkerd-crds linkerd/linkerd-crds \
  -n linkerd --create-namespace --version 1.4.0       
> helm install linkerd-control-plane \
  -n linkerd \
  --set-file identityTrustAnchorsPEM=ca.crt \
  --set-file identity.issuer.tls.crtPEM=issuer.crt \
  --set-file identity.issuer.tls.keyPEM=issuer.key \
  linkerd/linkerd-control-plane --version 1.9.6
> helm install linkerd-viz linkerd/linkerd-viz -n linkerd-viz --create-namespace --version 30.3.6
> kubectl -n linkerd-viz logs deploy/tap -c tap          
time="2023-05-10T21:59:54Z" level=info msg="running version dev-undefined"
time="2023-05-10T21:59:54Z" level=info msg="starting admin server on :9998"
time="2023-05-10T21:59:54Z" level=info msg="Using trust domain: cluster.local"
time="2023-05-10T21:59:54Z" level=info msg="waiting for caches to sync"
time="2023-05-10T21:59:54Z" level=info msg="caches synced"
time="2023-05-10T21:59:54Z" level=info msg="starting tap API server on :8089" addr=":8089" component=tap 
```
