### ISSUE TITLE
proxy: Replace or upgrade procinfo

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#10819]
[procinfo](https://github.com/danburkert/procinfo-rs) is unmaintained and has not been updated in 5+ years.

It will soon cause us to be unable to upgrade Rust:

> warning: the following packages contain code that will be rejected by a future version of Rust: nom v2.2.1

```
:; cargo tree -i nom@2.2.1
nom v2.2.1
└── procinfo v0.4.2
    └── linkerd-system v0.1.0 (/workspaces/dev/repos/linkerd2-proxy/linkerd/system)
```

We need to either replace or fork/update our `procinfo` dependency.

**Comment by hawkw** [comment]
Looking at crates.io, it looks like [`libproc`](https://crates.io/crates/libproc) is a potential alternative to `procinfo`. Will have to take a closer look to see if it provides the APIs we need and if the library is a viable alternative (e.g. maintained, etc).

**Comment by hawkw** [comment]
Another unmaintained crate, which also seems to not have a `stat` parser: https://crates.io/crates/proc_self :|

**Comment by hawkw** [comment]
Also old and unmaintained, but at least it has a `/proc/self/stat` implementation: https://crates.io/crates/linux-stats

We _may_ honestly be better off forking `procinfo`, the alternatives are all pretty disappointing so far.

**Comment by pranoyk** [comment]
What about this https://crates.io/crates/procfs ? Does this fit the use case ?

**Comment by pranoyk** [comment]
@hawkw 
As per their support.md https://github.com/eminence/procfs/blob/master/support.md they so have support for /proc/self/stat but not all the proc features. If we are only worried about the stat then I can implement this.

**Comment by hawkw** [comment]
@pranoyk currently, the only `procinfo` APIs the proxy uses are `/proc/self/stat` and `/proc/self/limits`,[^1] which are both implemented by `procfs` per the documentation you referenced. So, I think that means the `procfs` crate would be a viable alternative, and it looks like it is actively maintained. If you're interested in submitting a PR to use `procfs`, I would be happy to review it!

For the record, all of the Linkerd proxy's uses of `procinfo` are contained in this file: https://github.com/linkerd/linkerd2-proxy/blob/a512ea658ddc3d6aba1184d2055e17fdae29eac5/linkerd/system/src/linux.rs

[^1]: We also use `/proc/self/fd` for counting open file descriptors, but we don't actually use the `procinfo` crate for parsing its output --- we just use `std::fs` to count the number of files in the `/proc/self/fd` directory.

**Comment by pranoyk** [comment]
Sure, onto it!

**Comment by pranoyk** [comment]
@hawkw  While implementing the limits I noticed that we are checking `soft` and `hard` limits and then returning those limits instead of the `max_open_files` https://github.com/linkerd/linkerd2-proxy/blob/main/linkerd/system/src/linux.rs#L43. 
Can you tell me why we are doing that? Or can you please explain if I have not understood the implementation correctly ?

**Comment by hawkw** [comment]
> @hawkw While implementing the limits I noticed that we are checking `soft` and `hard` limits and then returning those limits instead of the `max_open_files` https://github.com/linkerd/linkerd2-proxy/blob/main/linkerd/system/src/linux.rs#L43. Can you tell me why we are doing that? Or can you please explain if I have not understood the implementation correctly ?

The value of `max_open_files` is a struct which contains both an optional soft limit and a hard limit. If a soft limit is set, we use that value, but if no soft limit is set, we fall back to using the hard limit. Does that make sense?

**Comment by pranoyk** [comment]
> The value of max_open_files is a struct which contains both an optional soft limit and a hard limit. If a soft limit is set, we use that value, but if no soft limit is set, we fall back to using the hard limit. Does that make sense?
So the assumption here is that a hard limit will always exist ?

**Comment by pranoyk** [comment]
This PR https://github.com/linkerd/linkerd2-proxy/pull/2433 fixes the above the issue

**Comment by mateiidavid** [comment]
@pranoyk it's not so much as an assumption. If you read through the man pages of `proc 5` and `getrlimit` you'll see that hard limits are always enforced, even if you can make arbitrary changes to it. AFAIK there's always going to be a hard limit on a process, and that hard limit is going to be the system limit for open file descriptors. I left some more details in the PR.
