### ISSUE TITLE
Linkerd mutating webhook is trying to inject linkerd to deployments under kube-system namespace which resulted in breakdown

### ISSUE THREAD

**Issue by Vamsi0473** [linkerd/linkerd2#10817]
### What is the issue?

Hi Team, after regular patching for nodes in our EKS cluster we noticed linkerd restarted and deployments failed to inject linkerd proxy container into the deployments upon debugging we got to see linkerd proxy injector is trying to inject linkerd into deployments under kube-system namespaces like core-dns, cluster-autoscaler etc which resulted in following error 
Error creating: Internal error occurred: failed calling webhook "linkerd-proxy-injector.linkerd.io": failed to call webhook: Post "https://linkerd-proxy-injector.linkerd.svc:443/?timeout=10s": no endpoints available for service "linkerd-proxy-injector"
In order to fix this we made following change
kubectl edit mutatingwebhookconfiguration linkerd-proxy-injector-webhook-config
and set:
failurePolicy: Ignore    (regular setting is fail)
Then restarted linkerd deployments after which we restarted all deployments then everything started working again

### How can it be reproduced?

After  nodes patching we obeserved linkerd restarted and tried to inject linkerd proxy to kube-system deployments

### Logs, error output, etc

Core-dns deployment error
Error creating: Internal error occurred: failed calling webhook "linkerd-proxy-injector.linkerd.io": failed to call webhook: Post "https://linkerd-proxy-injector.linkerd.svc:443/?timeout=10s": no endpoints available for service "linkerd-proxy-injector"

### output of `linkerd check -o short`

we can't perform  linkerd check

### Environment

kubernetes version - 1.24
Cluster Env - EKS
Host OS - Linux
Linkerd version - 2.9.5

### Would you like to work on fixing this bug?

None

**Comment by Strayfe** [comment]
I am not sure if it helps but if you had been able to actually run `linkerd check -o short` on your cluster you may see the following advice: 

```
linkerd-ha-checks
-----------------
‼ pod injection disabled on kube-system
    kube-system namespace needs to have the label config.linkerd.io/admission-webhooks: disabled if injector webhook failure policy is Fail
    see https://linkerd.io/2.13/checks/#l5d-injection-disabled for hints
```

I suspect your answer is somewhere in this link: https://linkerd.io/2.13/checks/#l5d-injection-disabled
