### ISSUE TITLE
Injection improvements

### ISSUE THREAD

**Issue by costinm** [linkerd/linkerd2#10818]
### What problem are you trying to solve?

I am doing some interop testing, and installed linkerd with the intent to use it in some pods. I will be using it alongside
Istio and other mesh and gateway implementations.

Few suggestions:

1. currently linkerd is using an annotation to control the injection, and ALL pods go trough the linkerd webhook.
It would be ideal to also add a label - this allow only labeled pods to go trough the webhook, so the other pods don't get extra startup latency and risks.  The webhook itself would filter.  Ideally the label should be discussed in GAMMA - so all meshes using injection could detect each other, using something based on the gateway class would work well ( gateways.k8s.io/inject: classname ). 

2. I noticed the deployment of non-linkerd resources have the status updated with 'linkerd injection skipped' - it is great to indicate that injection happened, but not so nice to spam all other pods. Users can still know that injection was skipped by not having the status.    I only saw this on the Deployment - not sure how it works, pods don't seem to have it. 

### How should the problem be solved?

See above.

### Any alternatives you've considered?

None

### How would users interact with this feature?

Set a standard label instead of annotation.

### Would you like to work on this feature?

None

**Comment by adleong** [comment]
You can specify a label selector for the proxy-injector to use with the [proxyInjector.objectSelector](https://artifacthub.io/packages/helm/linkerd2/linkerd-control-plane) value.
