### ISSUE TITLE
Linkerd Helm Chart fails to install on K8S 1.25+ due to use of batch/v1beta1 CronJob

### ISSUE THREAD

**Issue by Priyaboliset** [linkerd/linkerd2#10813]
### What is the issue?

The linkerd helm chart does not work with Kubernetes version 1.25.

This appears to be caused by the use of "CronJob" resource with "batch/v1beta1", which has now been removed

### How can it be reproduced?

Deploy linkerd with the stable helmchart (I used terraform to do this)

### Logs, error output, etc

│ Error: unable to build kubernetes objects from release manifest: [resource mapping not found for name: "linkerd-apr25linker-control-plane" namespace: "" from "": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"
│ ensure CRDs are installed first, resource mapping not found for name: "linkerd-heartbeat" namespace: "apr25linker" from "": no matches for kind "CronJob" in version "batch/v1beta1"
│ ensure CRDs are installed first]

### output of `linkerd check -o short`

N/A

### Environment

- Kubernetes version:1.25.5
- Cluster Environment: AKS
- Linkerd version: v2.10.2

### Possible solution

I tried to use another vesrions of linkerd which are stable, but getting Error: could not download chart: chart "linkerd2" version "2.13" not found in https://helm.linkerd.io/stable repository
Tried using 2.13,2.11.1,2.12 etc., but getting below
│ Error: could not download chart: chart "linkerd2" version "2.13" not found in https://helm.linkerd.io/stable repository

### Would you like to work on fixing this bug?

None

**Comment by adleong** [comment]
Hi @Priyaboliset,

As you said, stable-2.10.2 is a quite old version of Linkerd.

The Linkerd control plane Helm chart has been renamed to linkerd-control-plane: https://artifacthub.io/packages/helm/linkerd2/linkerd-control-plane

We recommend you follow the Helm install instructions: https://linkerd.io/2.13/tasks/install-helm/

**Comment by Priyaboliset** [comment]
@adleong Thank you for the response, As you mentioned now Changed the version to 2.13.2 with chart name as linkerd in my terraform code, but getting the error 
│ Error: could not download chart: chart "linkerd" version "2.13.2" not found in https://helm.linkerd.io/stable repository

**Comment by adleong** [comment]
"linkerd" is no longer the name of the Helm chart.  It has been renamed to "linkerd-control-plane": https://artifacthub.io/packages/helm/linkerd2/linkerd-control-plane
