### ISSUE TITLE
linkerd_proxy_identity_client::certify: Failed to obtain identity error=status: Unknown, message: "controller linkerd-identity-headless.linkerd.svc.cluster.local:8080: service in fail-fast",

### ISSUE THREAD

**Issue by dewijones92** [linkerd/linkerd2#10830]
### What is the issue?

Getting this error
 linkerd_proxy_identity_client::certify: Failed to obtain identity error=status: Unknown, message: "controller linkerd-identity-headless.linkerd.svc.cluster.local:8080: service in fail-fast", 

### How can it be reproduced?

 linkerd install | kubectl apply -f -

### Logs, error output, etc

https://gist.github.com/dewijones92/3bddc64f93254c1732e0bf4c996eed56

### output of `linkerd check -o short`

```
root@dewiserver:/home/dewi/tmp# linkerd check -o short                                                                                                                                                                                                     [0/0]
linkerd-existence
-----------------
\ pod/linkerd-destination-5d5fd9cbb5-2lcxs container sp-validator is not ready
```

### Environment

vagrant@master-node:~$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.1", GitCommit:"4c9411232e10168d7b050c49a1b59f6df9d7ea4b", GitTreeState:"clean", BuildDate:"2023-04-14T13:21:19Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.1", GitCommit:"4c9411232e10168d7b050c49a1b59f6df9d7ea4b", GitTreeState:"clean", BuildDate:"2023-04-14T13:14:42Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"linux/amd64"}

Vagrant VM running the nodes
root@dewiserver:~/code/vagrant-kubeadm-kubernetes#  vagrant status
Current machine states:

master                    running (virtualbox)
node01                    running (virtualbox)
node02                    running (virtualbox)

This environment represents multiple VMs. The VMs are all listed
above with their current state. For more information about a specific
VM, run `vagrant status NAME`.
root@dewiserver:~/code/vagrant-kubeadm-kubernetes#

root@dewiserver:~/code/vagrant-kubeadm-kubernetes# linkerd version
Client version: stable-2.13.2
Server version: stable-2.13.2

### Would you like to work on fixing this bug?

None

**Comment by dewijones92** [comment]
I am really stuck on this. I can't get linkerd to work atall.
Please help 😊
thanks

**Comment by IgorEulalio** [comment]
Having the same issue here:

linkerd version:
Client version: stable-2.13.2
Server version: stable-2.13.2

k8s version:
Client Version: v1.25.4
Kustomize Version: v4.5.7
Server Version: v1.26.4

Installed via microk8s version 1.27

**Comment by adleong** [comment]
Based on the error messages, it looks like your Linkerd control plane is not starting up healthily; in particular, the `linkerd-identity` deployment.

I'd recommend taking a look at a `kubectl describe` for the `linkerd-identity` deployment and looking at the logs from that deployment to see why it's not starting in healthy state.

**Comment by dewijones92** [comment]
> Based on the error messages, it looks like your Linkerd control plane is not starting up healthily; in particular, the `linkerd-identity` deployment.
> 
> I'd recommend taking a look at a `kubectl describe` for the `linkerd-identity` deployment and looking at the logs from that deployment to see why it's not starting in healthy state.

many thanks for your reply
Do you have a script to get all this up and running? ideally something that also spins up an appropriate locally running k8s cluster + the linked stuff

thanks
