### ISSUE TITLE
linkerd-viz helm chart: not able to set tolerations for namespace-metadata job/pod

### ISSUE THREAD

**Issue by philslab-ninja** [linkerd/linkerd2#10836]
### What problem are you trying to solve?

I want to be able to provide tolerations using the helm chart to the namespace-metadata pod run by the job 

### How should the problem be solved?

Add possibility to provide tolerations for namespace-metadata in helm chart

### Any alternatives you've considered?

none I could think of

### Would you like to work on this feature?

maybe

**Comment by pssalman** [comment]
linkerd-jaeger helm chart has the same job/pod namespace-metadata which also doesn't support tolerations nor assigning to nodepool or even affinity.

**Comment by pssalman** [comment]
I have just created a PR to solve this issue by updating the helm charts for three components:
- linkerd-viz
- linkerd-jaeger
- linkerd-multicluster
All three have that namespace-metadata job.

**Comment by pssalman** [comment]
I am not sure if we can include that into the 2.13.X-patches milestone so it can be included in the stable version and if possible, how we can do that ?
