### ISSUE TITLE
Define linkerd proxy as QOS guaranteed if all container in pods have requests = limits

### ISSUE THREAD

**Issue by GDegrove** [linkerd/linkerd2#10848]
### What problem are you trying to solve?

When trying to deploy a pod with Guaranteed QoS, we always have to define the limits/requests based on an annotations. This make the management of the proxy requests/limits quite complex. 
This would allow the proxy to decide what requests/limits to set to not make the pod change in QoS.

This would make the proxy configuration not change the QoS of the pod the proxy is injected.

### How should the problem be solved?

The idea would be that the mutating webhook checks if the pod is already in Guranteed QoS. 
So, if at injection, we detect that the pod is in guaranteed QoS, we would not change the class, and configure the proxy to not change it. 

### Any alternatives you've considered?

Not really

### How would users interact with this feature?

The feature would be automatic, and would be integrated in the proxy injector. The user should not interact with the feature directly

### Would you like to work on this feature?

Yes

**Comment by adleong** [comment]
Hi @GDegrove 

This idea is interesting but feels a bit out of the domain of Linkerd itself.  However, mutating webhook controllers can be chained in Kubernetes, which means that it should be possible to write a mutating webhook which runs on a pod after injection and sets the limits/requests as you desire.

**Comment by GDegrove** [comment]
Hi @adleong,

Thanks for the reply, and sorry for my late reply, this was actually on my plate and I totally forgot. 

I'm not sure if I agree with your point of: 

> but feels a bit out of the domain of Linkerd itself.

Linkerd does mutate the pod by injecting the proxy to the workload, this injection of proxy has a direct impact, but the most important one is that is can alter the QoS of a pod by adding a new container that changes the QoS of the pod from Guaranteed to burstable. 
This actually is an issue cause it requires the developer to know that it will be injected, things that we actually don't want, as this is the idea of the mutating webhook.

Making Linkerd injector aware of the QoS class of the pod before it injects, allows the developer to remove this knowledge in most of the case. On some edge case, you will still need to know and configure the proxy, but on most of the case, the mutating webhook will not change the type of the workload. 

I guess the main point here is: a mutating webhook should respect the spec of the workload, especially when it changes its QoS class
