### ISSUE TITLE
'no route found for request' for HTTP traffic on opaque ports in Linkerd 2.13.2

### ISSUE THREAD

**Issue by mila-rodriguez-netapp** [linkerd/linkerd2#10853]
### What is the issue?

When a pod has opaque ports, HTTP traffic to those ports will be rejected by the linkerd-proxy with the following error logged:

```
[    79.011319s]  INFO ThreadId(01) inbound:server{port=4143}:rescue{client.addr=10.42.1.112:33006}: linkerd_app_core::errors::respond: HTTP/2.0 request failed error=client 10.42.1.112:33006: server: 10.42.1.111:4143: no route found for request error.sources=[no route found for request]
```

The calling pod will receive a generic HTTP 404 response. If the calling pod is removed from the service mesh (or otherwise forces the traffic not not be meshed), then the call succeeds.

What appears to be the same issue (https://github.com/linkerd/linkerd2/issues/9888) is marked fixed in 2.13.2, but the issue does not appear resolved.

### How can it be reproduced?

* Pod A with some port marked opaque
* Pod B sends HTTP traffic to opaque port; response will be 404

If Pod B is removed from the mesh (`linkerd.io/inject=disabled`), exact same HTTP traffic will succeed.

### Logs, error output, etc

linkerd-proxy log from the pod with the opaque port:

```
[    48.997131s]  INFO ThreadId(01) inbound:server{port=4143}:rescue{client.addr=10.42.1.112:59082}: linkerd_app_core::errors::respond: HTTP/2.0 request failed error=client 10.42.1.112:59082: server: 10.42.1.111:4143: no route found for request error.sources=[no route found for request]
[    79.011319s]  INFO ThreadId(01) inbound:server{port=4143}:rescue{client.addr=10.42.1.112:33006}: linkerd_app_core::errors::respond: HTTP/2.0 request failed error=client 10.42.1.112:33006: server: 10.42.1.111:4143: no route found for request error.sources=[no route found for request]
```

There's nothing in the linkerd-proxy log from the pod calling the pod with the opaque port (nothing related to this specific request, that is.

### output of `linkerd check -o short`

```
Status check results are √
```

### Environment

Kubernetes version:
```
$ kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.25.4
Kustomize Version: v4.5.7
Server Version: v1.24.4
```

Linkerd version: 
```
Client version: stable-2.13.2
Server version: stable-2.13.2
```
LinkerD deployed in HA mode with `--set proxyInit.iptablesMode=nft --set proxyInit.runAsRoot=true` (not sure if relevant).

### Additional context

In case the question arises why one would mark an HTTP port opaque: in some of my pods, there is server-speaks-first traffic on this port during startup; if the port is not opaque (or skipped) the pod will not finish starting. (This server-speaks-first traffic is for cluster leader election, gossip, or similar.) My requirement is to mesh all TCP traffic, so skipping the port isn't an option.

I have reproduced this issue with a simple pair of pods, an HTTP server that always responds with HTTP 200 and a simple looping wget client that calls the server. If both are meshed and the server's HTTP port is opaque, the issue occurs; if the client is removed from the mesh, or if the server's port is not marked opaque, the call succeeds and the issue does not occur.

### Would you like to work on fixing this bug?

maybe

**Comment by hawkw** [comment]
Hi @mila-rodriguez-netapp, are you still seeing this issue after updating to [stable-2.13.3](https://github.com/linkerd/linkerd2/releases/tag/stable-2.13.3)?
