### ISSUE TITLE
Environment variable for shutdown endpoint

### ISSUE THREAD

**Issue by kellybirr** [linkerd/linkerd2#10894]
### What problem are you trying to solve?

I am using Linkerd2 in my Kubernetes clusters that run many jobs and cronjobs.  I have added support for calling the graceful shutdown endpoint when the jobs end.  However, these jobs also run outside of Kubernetes when in a debugger or testing on other platforms.  Sometimes in Kubernetes, but without the Linkerd proxy sidecar.

It would be ideal to know if the application was running in an environment where the linkerd2-proxy was injected.  This way the code could test for this before attempting to call the shutdown endpoint and generating an exception if the proxy is not present.

### How should the problem be solved?

I propose that the linkerd2-proxy, or the proxy injection, create an environment variable in the application container(s) like LINKERD_SHUTDOWN_PORT="http://localhost:4191/shutdown".  This is consistent with the KUBERNETES_PORT variable the Kubernetes creates to point to the Kubernetes API.

If would be simple enough for any application to check for this variable in the environment near the end of execution and simply POST to the URL it contains before exiting.  This would allow the application to automatically and reliably discover both the presence and endpoint for requesting the proxy to shutdown.  It also solves for the developers not needing to hard-code this Uri.

### Any alternatives you've considered?

A few, but this one was simpler and more effective.

### How would users interact with this feature?

Job code/scripts would for this environment variable after processing and before exit.  If present, POST to the Uri it contains before exiting the process.  If not present, simply exit.  

This would work in everything from bash scripts to C code and be easy to take advantage of.

### Would you like to work on this feature?

no

**Comment by alpeb** [comment]
When the linkerd injector injects the proxy it doesn't touch the main container, so starting doing that would be a significant departure from the current approach.
When a pod gets injected, the annotation `linkerd.io/proxy-version` is added. If I'm not mistaking, I think you can solve your problem by adding an environment variable in your container with the value of that annotation using the downward API. And then your app can act depending on whether that env var is empty or not.

**Comment by kellybirr** [comment]
cool workaround idea, I'll give that a try.  Right now, I'm just looking for KUBERNETES_PORT and assuming that if I'm running under Kubernetes then Linkerd proxy is present.
