### ISSUE TITLE
Grafana cannot connect to Prometheus from Linkerd Viz

### ISSUE THREAD

**Issue by oncipriani** [linkerd/linkerd2#10891]
### What is the issue?

If you install Grafana following the instructions on the [Linkerd website](https://linkerd.io/2.13/tasks/grafana/#install-grafana), Grafana cannot get data from Prometheus.

This issue occurs only if you deploy Grafana on the same namespace as Prometheus (`linkerd-viz` by default).

I believe it happens because of the [Authorization Policies](https://linkerd.io/2.13/reference/authorization-policy/) created by the `linkerd-viz` Helm Chart.

### How can it be reproduced?

1. Install [Linkerd Viz](https://linkerd.io/2.13/features/dashboard/);
  1.1. `helm install -n linkerd-viz linkerd-viz linkerd/linkerd-viz`

2. Install Grafana on the same namespace as Linkerd Viz;
  2.1. `helm install -n linkerd-viz grafana grafana/grafana -f https://raw.githubusercontent.com/linkerd/linkerd2/main/grafana/values.yaml`

3. Access Grafana and notice that non data is displayed. 

### Logs, error output, etc

Log from `linkerd-proxy` in the `grafana` Deployment:
```
[     0.002443s]  INFO ThreadId(01) linkerd2_proxy::rt: Using single-threaded proxy runtime
[     0.003552s]  INFO ThreadId(01) linkerd2_proxy: Admin interface on 0.0.0.0:4191
[     0.003574s]  INFO ThreadId(01) linkerd2_proxy: Inbound interface on 0.0.0.0:4143
[     0.003579s]  INFO ThreadId(01) linkerd2_proxy: Outbound interface on 127.0.0.1:4140
[     0.003585s]  INFO ThreadId(01) linkerd2_proxy: Tap interface on 0.0.0.0:4190
[     0.003591s]  INFO ThreadId(01) linkerd2_proxy: Local identity is default.linkerd-viz.serviceaccount.identity.linkerd.cluster.local
[     0.003597s]  INFO ThreadId(01) linkerd2_proxy: Identity verified via linkerd-identity-headless.linkerd.svc.cluster.local:8080 (linkerd-identity.linkerd.serviceaccount.identity.linkerd.cluster.local)
[     0.003601s]  INFO ThreadId(01) linkerd2_proxy: Destinations resolved via linkerd-dst-headless.linkerd.svc.cluster.local:8086 (linkerd-destination.linkerd.serviceaccount.identity.linkerd.cluster.local)
[     0.029684s]  INFO ThreadId(02) daemon:identity: linkerd_app: Certified identity id=default.linkerd-viz.serviceaccount.identity.linkerd.cluster.local
[     1.835459s]  INFO ThreadId(01) inbound:server{port=3000}:rescue{client.addr=10.64.24.58:36902}: linkerd_app_core::errors::respond: HTTP/1.1 request failed error=error trying to connect: Connection refused (os error 111) error.sources=[Connection refused (os error 111)]
[     2.872855s]  INFO ThreadId(01) inbound:server{port=3000}:rescue{client.addr=10.64.24.58:36910}: linkerd_app_core::errors::respond: HTTP/1.1 request failed error=error trying to connect: Connection refused (os error 111) error.sources=[Connection refused (os error 111)]
[     3.906163s]  INFO ThreadId(01) inbound:server{port=3000}:rescue{client.addr=10.64.24.58:36926}: linkerd_app_core::errors::respond: HTTP/1.1 request failed error=error trying to connect: Connection refused (os error 111) error.sources=[Connection refused (os error 111)]
[     5.697704s]  INFO ThreadId(01) inbound:server{port=3000}:rescue{client.addr=10.64.24.58:36932}: linkerd_app_core::errors::respond: HTTP/1.1 request failed error=error trying to connect: Connection refused (os error 111) error.sources=[Connection refused (os error 111)]
[    91.965232s]  INFO ThreadId(01) outbound:proxy{addr=10.43.188.35:9090}: linkerd_detect: Continuing after timeout: linkerd_proxy_http::version::Version protocol detection timed out after 10s
```

### output of `linkerd check -o short`

```
Status check results are √
```

### Environment

- Kubernetes version: 1.23;
- Kubernetes provider: RKE;
- Host OS: Rocky Linux 8.7;
- Linkerd version: stable-2.13.3

### Possible solution

Passing the following parameters during Grafana installation works around the problem:

```sh
helm install -n linkerd-viz grafana grafana/grafana \
  -f https://raw.githubusercontent.com/linkerd/linkerd2/main/grafana/values.yaml \
  --set rbac.create=false --set serviceAccount.create=false --set serviceAccount.name=metrics-api
```

### Would you like to work on fixing this bug?

maybe

**Comment by alpeb** [comment]
Please check the instructions on how to grant access to grafana via an AuthorizationPolicy:
https://github.com/linkerd/linkerd2/tree/main/grafana#granting-access

**Comment by oncipriani** [comment]
That does solve the problem.

Shouldn't this information be in the [website's documentation](https://linkerd.io/2.13/tasks/grafana/)? 😄

**Comment by alpeb** [comment]
Yep, that page requires an update, I'll get that in ASAP :sweat_smile:
