### ISSUE TITLE
502 Bad Gateway when calling the same service

### ISSUE THREAD

**Issue by prajithp13** [linkerd/linkerd2#10914]
### What is the issue?

We have recently updated our linkerd installation to version 2.13.3 on our eks cluster. Since the upgrade, we have been experiencing 502 Bad Gateway errors when making calls to the Coredns endpoint from any pods within the same service. However, the localhost and coredns endpoint without the namespace.svc.cluster.local suffix are functioning correctly. 

Example:
```
root@example-qa-http:/# hostname
example-qa-http
root@example-qa-http:/# curl http://example-qa-http.example-ns.svc.cluster.local:21087 -i 
HTTP/1.1 502 Bad Gateway
l5d-proxy-error: endpoint 10.3.145.134:21087: connection error: stream closed because of a broken pipe
connection: close
l5d-proxy-connection: close
content-length: 0
date: Thu, 18 May 2023 11:57:47 GMT

root@example-qa-http:/# curl http://example-qa-http:21087 -i 
HTTP/1.1 404 
Content-Type: application/json
Transfer-Encoding: chunked
Date: Thu, 18 May 2023 11:57:50 GMT

{"timestamp":1684411070349,"status":404,"error":"Not Found","message":"","path":"/"}
```

as you can see we are calling the same endpoint of the pod but it fails with 502 errors when using the complete coredns domain but it works with just the hostname or localhost.

### How can it be reproduced?

1. Install linkerd - 2.13.3
2. annotate any deployments with `linkerd.io/inject: enabled`
3. Login into the container using `kubectl exec`
4. execute `curl -i http://<serviceName>.<namespace>.svc.cluster.local` # serviceName should point to the same deployment.

 

### Logs, error output, etc

```
[   685.285853s]  INFO ThreadId(01) outbound:proxy{addr=172.20.27.139:21087}:service{ns= name=service port=0}:endpoint{addr=10.3.140.43:21087}:rescue{client.addr=10.3.140.43:46584}: linkerd_app_core::errors::respond: HTTP/1.1 request failed error=endpoint 10.3.140.43:21087: connection error: stream closed because of a broken pipe error.sources=[connection error: stream closed because of a broken pipe, stream closed because of a broken pipe]
```

### output of `linkerd check -o short`

```
linkerd-failover
----------------
‼ Linkerd extension command linkerd-failover exists
    exec: "linkerd-failover": executable file not found in $PATH
    see https://linkerd.io/2.13/checks/#extensions for hints

Status check results are √
```

### Environment

Kubernetes Version: 1.22
Cluster Environment: eks
Host OS: amazon Linux 2
Linkerd: 2.13.3

### Additional context

We are not seeing this issue on Linkerd  2.12.4

### Would you like to work on fixing this bug?

maybe

**Comment by alpeb** [comment]
We've just released edge-23.5.2 which includes #10883, which fixes an issue with localhost connections. Can you give it a try and see if that addresses your particular issue?
