### ISSUE TITLE
Add support for nodeselectors and tolerations in linkerd-smi helm chart

### ISSUE THREAD

**Issue by pauska** [linkerd/linkerd2#10933]
### What problem are you trying to solve?

I need to make sure that linkerd-smi runs in a specific pool where we only have critical system services running.

### How should the problem be solved?

Add nodeSelectors and tolerations to the Helm chart values file

### Any alternatives you've considered?

Decompile the helm charts into yaml, and use Kustomize to patch it

### Would you like to work on this feature?

no

**Comment by hawkw** [comment]
We believe this would probably be a pretty straightforward change, so if anyone is interested in submitting a PR to add this, we would be happy to review it! The Helm charts for `linkerd-smi` can be found in the `linkerd/linkerd-smi` repository, [here](https://github.com/linkerd/linkerd-smi/tree/main/charts/linkerd-smi).

**Comment by jclegras** [comment]
Hi there, I propose you [this PR](https://github.com/linkerd/linkerd-smi/pull/63)
