### ISSUE TITLE
Connectivity/Routing Layer for Multicluster Setup

### ISSUE THREAD

**Issue by deusxanima** [linkerd/linkerd2#10965]
### What problem are you trying to solve?

Current multicluster setup and implementation requires an individual one-way link to be defined for each remote cluster that we want to connect to our local clusters. This doubles when trying to ensure the connection is two way. In an environment where there may be dozens of clusters which all need some layer of connectivity and mesh between each other, this quickly becomes very difficult to manage. For example, in a 12 cluster setup this necessitates 66 one-way links to be created, maintained, and tracked. An ask from some users has been for a creation of a middle routing/connectivity layer to help facilitate connections between all clusters without them needing to be individually defined and maintained by users. 

### How should the problem be solved?

This could potentially work on a hub-spoke model (or require a central management component) where all clusters can set up a connection to a single "hub" cluster/connection, which would then set up and maintain all the remaining connections and route remote-to-remote traffic without the need to set up individual links from each cluster to each other cluster. 

### Any alternatives you've considered?

n/a

### Would you like to work on this feature?

no

**Comment by fbozic** [comment]
Ping, do not close
