### ISSUE TITLE
Changing the proxy admin-port through an annotation breaks pod initialization

### ISSUE THREAD

**Issue by craffit** [linkerd/linkerd2#10981]
### What is the issue?

Setting the `config.linkerd.io/admin-port: "5191"` on a pod with the linkerd proxy enabled through `linkerd.io/inject: enabled` 

Causes the pod start to fail with the message 
```
Exec lifecycle hook ([/usr/lib/linkerd/linkerd-await --timeout=2m]) for Container "linkerd-proxy" in Pod "tcp-client-698cc845c7-ctzhs_linkerd-tcp(790c46df-d6ca-4a2b-ba36-a0d7a7ec067e)" failed - error: command '/usr/lib/linkerd/linkerd-await --timeout=2m' exited with 69: linkerd-proxy failed to become ready within 120s timeout, message: "linkerd-proxy failed to become ready within 120s timeout\n"
```

It seems the altered admin port is not passed down to the postStartHook /usr/lib/linkerd/linkerd-await 

### How can it be reproduced?

- Enable the linkerd proxy
- Set an alternative admin port through config.linkerd.io/admin-port: "5191"
- Restart the pod

### Logs, error output, etc

```
Exec lifecycle hook ([/usr/lib/linkerd/linkerd-await --timeout=2m]) for Container "linkerd-proxy" in Pod "tcp-client-698cc845c7-ctzhs_linkerd-tcp(790c46df-d6ca-4a2b-ba36-a0d7a7ec067e)" failed - error: command '/usr/lib/linkerd/linkerd-await --timeout=2m' exited with 69: linkerd-proxy failed to become ready within 120s timeout, message: "linkerd-proxy failed to become ready within 120s timeout\n"
```

during pod startup

### output of `linkerd check -o short`

```
linkerd-version
---------------
‼ cli is up-to-date
    is running version 2.13.3 but the latest stable version is 2.13.4
    see https://linkerd.io/2.13/checks/#l5d-version-cli for hints

control-plane-version
---------------------
‼ control plane is up-to-date
    is running version 2.13.3 but the latest stable version is 2.13.4
    see https://linkerd.io/2.13/checks/#l5d-version-control for hints

linkerd-control-plane-proxy
---------------------------
‼ control plane proxies are up-to-date
    some proxies are not running the current version:
	* linkerd-destination-9f7f7dfdf-525sz (stable-2.13.3)
	* linkerd-identity-d5d6cf78b-9lkmj (stable-2.13.3)
	* linkerd-proxy-injector-769fc8595d-l5vq6 (stable-2.13.3)
    see https://linkerd.io/2.13/checks/#l5d-cp-proxy-version for hints

Status check results are √
```

### Environment

K8s on EKS

### Possible solution

It seems the altered admin port is not passed down to the postStartHook `/usr/lib/linkerd/linkerd-await` , so doing that might solve it

### Would you like to work on fixing this bug?

no

**Comment by alpeb** [comment]
Good catch :+1: 
This should be straightforward to fix for anyone wanting to give it a go. As you can see in the [linkerd-await repo](https://github.com/linkerd/linkerd-await), the command supports a `--port` flag. But as pointed out above, [the hook isn't considering that](https://github.com/linkerd/linkerd2/blob/main/charts/partials/templates/_proxy.tpl#L183) and just using the default. It should just be a matter of adding that flag in that template, using the `{{.Values.proxy.ports.admin}}` variable.

**Comment by jclegras** [comment]
Hi @alpeb 
Thanks for the explanation
I propose you this [PR](https://github.com/linkerd/linkerd2/pull/11031)
