### ISSUE TITLE
GitHub Action Status Badge rendering issue

### ISSUE THREAD

**Issue by Saha-7** [linkerd/linkerd2#10996]
### What problem are you trying to solve?

This GitHub Action Status badge not rendering well.
![Linkerd](https://github.com/linkerd/linkerd2/assets/104014464/38ec184a-31e7-4422-b499-863a6f3a90cc)

### How should the problem be solved?

Some little changes in code that's it.

### Any alternatives you've considered?

Not Now.

### Would you like to work on this feature?

None

**Comment by AMK9978** [comment]
I can help with this
