### ISSUE TITLE
`check` for the data plane

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#1103]
`check` is a very powerful tool for users to validate that the control plane is healthy. Similar functionality should be added for validating that the data plane is operational and working as it should for specific applications.

## User Stories

- As a developer, I would like to verify that my app is working correctly after I have injected the data plane so that I can be sure it isn't my fault when something goes wrong.
- As an operator, I would like to have a set of checks to alert on, verifying functionality, so that I can alert when an issue comes up in production.
- As a developer, I would like to verify data plane operation on my application, so that I can understand if issues I'm experiencing are related to the proxy or something else.

### Pre-Flight (#1516)

- Host networking
- UDP
- Known initContainers

### Post-Flight

- Could pull proxy image
- Proxy is passing readiness checks
- Proxy is passing liveness checks
- Is everything meshed (ex. deployment)
- Can the new pods be scheduled?
- Can the proxy reach the destination service?
- Is the proxy reporting back?
- Is the app passing liveness/readiness checks?

### CLI

```bash
$ cat foobar.yaml | linkerd inject -

supported resource type: [ok]
hostNetworking: [ok]
dnsPolicy: [ok]
```

```bash
$ linkerd check deploy/foobar --post

has proxy: [ok]
proxy is healthy: [ok]
metrics are being received: [ok]
```

**Comment by grampelberg** [comment]
See #1421 for another possible check (NetworkPolicy).

**Comment by grampelberg** [comment]
There's a lot more opportunity here for post-injection tests (liveness, readiness, traffic flowing, ....).

**Comment by grampelberg** [comment]
@klingerf updated with our list of checks. Do you want to add the UI here or in the other issues?

**Comment by klingerf** [comment]
Great, thanks @grampelberg -- I create other issues and link them back to this one.
