### ISSUE TITLE
Add misssing labels to LinkerD components to skip mutation webhook

### ISSUE THREAD

**Issue by migueleliasweb** [linkerd/linkerd2#11058]
### What is the issue?

Requirements:
- LinkerD config is set to `webhookFailurePolicy: Fail`
- An issue happens to the ProxyInjector workload
- LinkerD control plane is configured to use LinkerD CNI

If all requirements are met, then the the LinkerD cni will fail to come up as the mutation webhook is failing. And since the LinnkerD CNI is down, most workloads will have a bad time working as the network will quickly stop working.

The issue is that the LinkerD CNI pods are missing the label `linkerd.io/cni-resource`. This label is present by default in LinkerD's configmap as part of the `proxyInjector` section.

In the current release, the pods for the LinkerD CNI only contains the label `k8s-app: linkerd-cni`.

All we need to do is add the label `linkerd.io/cni-resource` to the daemonset **pods** of LinkerD CNI to it automatically gets skipped from the mutation webhooks.

### How can it be reproduced?

- Install latest LinkerD Control Plane + LinkerD CNI helm charts
- Change the LinkerD configmap with `webhookFailurePolicy: Fail`
- Intentionally break the LinkerD CNI daemonset (in my case was a race condition with the AWS VPC CNI - but this issue is more general and not completely related to the AWS VPC CNI) 

### Logs, error output, etc

N/A

### output of `linkerd check -o short`

LinkerD check is successful. The issue is only when the proxy injector breaks.

### Environment

- Kubernetes Version: 1.24
- LinkerD Version: v2.13.2
- LinkerD CNI: v.1.1.1

### Possible solution

Add missing labels to LinkerD CNI daemonset pods. This change is very small and should be done in the Helm charts only. No code changes are required for this.

### Would you like to work on fixing this bug?

yes

**Comment by alpeb** [comment]
You're right that the DaemonSet mistakingly has `linkerd.io/cni-resource: "true"` as an annotation instead of a label. However, it also has the `linkerd.io/inject: disabled` annotation which should make it to be ignored by the injector, so it seems your issue is related to something else?

**Comment by migueleliasweb** [comment]
Great point @alpeb . But the issue is slightly different.

It is true that the daemonset for the CNI has the `disabled` but there are two checkpoints for the sidecar injection:

- The first one are the filters in the MutatingWebhook configuration: If the workload is not picked up by these, the mutation webhook won't even try to inject the sidecar
- The second checkpoint of control is the `disabled` annotation which makes it so even if the workload is picked up by the mutating webhook it will just `noop` and let it go through without changing it.

The issue is that IF (and only IF) the mutating webhook is broken for whatever reason, it will also break the cni components to be spun up as the mutating webhook will fail (assuming the policy is set to `fail` in the mutating webhook config). And this a huge problem since if the cni doesn't come up, the whole cluster will be partially broken.

So it would be best to skip the injection in the first checkpoint so even if the mutating webhook is broken, the CNI will come up by itself. This will also improve the decoupling of the LinkerD components :).

Let me know if that's clear. ;)

**Comment by alpeb** [comment]
Ok that makes sense. Would you like to submit a PR refactoring the annotation as a label?

**Comment by migueleliasweb** [comment]
> Ok that makes sense. Would you like to submit a PR refactoring the annotation as a label?

Yep. I would love to help and fix this as I just had an outage in one of the cluster I oversee because of this 😅 .

**Comment by migueleliasweb** [comment]
Hi @alpeb , I just created the PR. 

I couldn't find test for the Helm templates so for now I just moved the annotation to a label.

Let me know if something else needs to be done.
