### ISSUE TITLE
Consistent 502s during shutdown/rolling a deployment

### ISSUE THREAD

**Issue by tylux** [linkerd/linkerd2#11084]
### What is the issue?

During deployment with a simple app and using a load generator to generate/capture some traffic (I used locust in this case) I can consistently get 502s from the service during a deployments rolling restart.

The problem goes away as soon as I disable the linkerd side car for this service.

### How can it be reproduced?

Generate some load and perform a rolling restart or deploy of a service and capture the failures.

In my case I used Locust to capture these failures

![Screenshot 2023-07-05 at 2 40 28 PM](https://github.com/linkerd/linkerd2/assets/2838687/8515e788-f813-40d4-9c97-2dfe3a860a28)

### Logs, error output, etc

I do see some of these types of logs right before the SIGTERM reaches the linkerd-proxy container

```
[    78.469564s]  INFO ThreadId(01) inbound:server{port=4000}:rescue{client.addr=10.2.17.49:1683}: linkerd_app_core::errors::respond: HTTP/1.1 request failed error=error trying to connect: Connection refused (os error 111) error.sources=[Connection refused (os error 111)]
[    78.474332s]  INFO ThreadId(01) inbound:server{port=4000}:rescue{client.addr=10.2.68.142:41640}: linkerd_app_core::errors::respond: HTTP/1.1 request failed error=error trying to connect: Connection refused (os error 111) error.sources=[Connection refused (os error 111)]
[    84.130118s]  INFO ThreadId(01) linkerd_proxy::signal: received SIGTERM, starting shutdown
[    84.130134s]  INFO ThreadId(01) linkerd2_proxy: Received shutdown signal
``` 

### output of `linkerd check -o short`

```
linkerd-identity
----------------
‼ issuer cert is valid for at least 60 days
    issuer certificate will expire on 2023-09-02T19:12:01Z
    see https://linkerd.io/2.13/checks/#l5d-identity-issuer-cert-not-expiring-soon for hints

linkerd-version
---------------
‼ cli is up-to-date
    is running version 2.13.4 but the latest stable version is 2.13.5
    see https://linkerd.io/2.13/checks/#l5d-version-cli for hints

control-plane-version
---------------------
‼ control plane is up-to-date
    is running version 2.13.4 but the latest stable version is 2.13.5
    see https://linkerd.io/2.13/checks/#l5d-version-control for hints

linkerd-control-plane-proxy
---------------------------
‼ control plane proxies are up-to-date
    some proxies are not running the current version:
	* linkerd-destination-9648f769-4t4vb (stable-2.13.4)
	* linkerd-destination-9648f769-6qh22 (stable-2.13.4)
	* linkerd-destination-9648f769-d8mzg (stable-2.13.4)
	* linkerd-identity-6f5fb98dcc-rnk75 (stable-2.13.4)
	* linkerd-identity-6f5fb98dcc-slttf (stable-2.13.4)
	* linkerd-identity-6f5fb98dcc-xvkdk (stable-2.13.4)
	* linkerd-proxy-injector-598d698c87-8zl5p (stable-2.13.4)
	* linkerd-proxy-injector-598d698c87-j26bm (stable-2.13.4)
	* linkerd-proxy-injector-598d698c87-tljkz (stable-2.13.4)
    see https://linkerd.io/2.13/checks/#l5d-cp-proxy-version for hints

linkerd-viz
-----------
‼ viz extension proxies are up-to-date
    some proxies are not running the current version:
	* metrics-api-f77b49987-whp9p (stable-2.13.4)
	* tap-6d894f55b6-8vwdw (stable-2.13.4)
	* tap-injector-74f66457cc-grhwj (stable-2.13.4)
	* web-6865864996-6kw5r (stable-2.13.4)
    see https://linkerd.io/2.13/checks/#l5d-viz-proxy-cp-version for hints
‼ prometheus is installed and configured correctly
    missing ClusterRoles: linkerd-linkerd-viz-prometheus
    see https://linkerd.io/2.13/checks/#l5d-viz-prometheus for hints

Status check results are √
```

### Environment

EKS 1.23
Linkerd Version: 2.13.4

### Possible solution

No solutions yet

### Additional context

What I have tried

The suggestions here https://linkerd.io/2.13/tasks/debugging-502s/ 

Deployment annotations:
        config.linkerd.io/close-wait-timeout: (60s, 1h)
	config.alpha.linkerd.io/proxy-wait-before-exit-seconds: (25, 30, 55, 60) 

Control Plane settings:
	close-wait-timeout: (60s, 1h)

### Would you like to work on fixing this bug?

maybe

**Comment by tylux** [comment]
Here is the setup to reproduce...
```
kubectl create deployment nginx-test \
    --image=nginx:latest \
    --replicas=3 \
    --port=80
```

Edit the deployment to add the port like this...

```
    spec:
      containers:
      - image: nginx:latest
        imagePullPolicy: Always
        name: nginx
        ports:
        - containerPort: 80
```

```
kubectl expose deployment nginx-test \
    --type=LoadBalancer \
    --port=8080 \
    --name=nginx-service
```

Edit the svc to add a target port

```
targetPort: 80
````

Finally patch the deployment to enable linkerd
```
kubectl patch deployment nginx-test -p '{"spec": {"template":{"metadata":{"annotations":{"linkerd.io/inject":"enabled"}}}} }'
```

Then you can test both with the linkerd on and linkerd off

**Comment by hawkw** [comment]
Looking at the error logs you've posted that indicate the proxy is seeing "connection refused" errors, I think what's going on here could be that the application container(s) has been SIGTERM'd while the proxy is still in its "graceful shutdown" state, resulting in 502s, since the proxy can no longer connect to the injected application. 

Potential issues with the current graceful shutdown behavior have come up in the past, and we've been considering changing how the proxy handles shutdown conditions.  Issue #10379 has some more discussion around this, it's probably relevant to your issue.

**Comment by tylux** [comment]
Thanks for the link to that issue, I have looked at those and all the others that seemed related to this issue but haven't been able to find a good workaround.

Note, We still see this when we have a prestop hook with a sleep configured to account for that and it doesn't help with the 502s.

```
        lifecycle:
          preStop:
            exec:
              command:
                - /bin/bash
                - -c
                - sleep 20
```

Is there any sort of workaround for this error on deploys?

**Comment by avlpetrov** [comment]
@tylux, I wonder if you've tried adding a `config.linkerd.io/shutdown-grace-period` annotation to the `linkerd-proxy` container? See https://linkerd.io/2.13/tasks/graceful-shutdown/#configuration-options-for-graceful-shutdown.

**Comment by tylux** [comment]
@avlpetrov Thanks for responding, yes I have tried that value too, looks like the default is 120 seconds, I have tried 15, 30 etc and still get 502s using that simple nginx setup above

**Comment by adleong** [comment]
Hi @tylux 

I'm trying to understand exactly what might be happening here.  Is that preStop hook that you described on the linkerd-proxy container or on the nginx container?  And do you see 502s during that wait period while the SIGTERM is delayed by the preStop hook, or do you only see 502s after the SIGTERM reaches nginx and/or the linkerd-proxy?
