### ISSUE TITLE
linkerd-destination fails on UnknownIssuer

### ISSUE THREAD

**Issue by christiancadieux** [linkerd/linkerd2#11096]
### What is the issue?

need to run linkerd on clusters that are self-signed. 
need an  option like InsecureSkipVerify: true 

### How can it be reproduced?

tried with latest edge-23.7.1 

then tried a custom version of linkerd/policy-controller with [features]
default = ["rustls-tls", ..

and got a different but similar error - UnknownIssuer.

I can see that kube-rs/kube supports it, but don't know how to use it:  (https://github.com/kube-rs/kube/blob/main/kube-client/src/client/tls.rs#L62)

## 23.7.1 error (openssl):
```
2023-07-11T03:37:55.642274Z DEBUG tower::buffer::worker: service.ready=true processing request
2023-07-11T03:37:55.642366Z DEBUG HTTP{http.method=GET http.url=https://192.168.0.1/apis/apps/v1/namespaces/linkerd/deployments/linkerd-destination otel.name="get" otel.kind="client"}: kube_client::client::builder: requesting
2023-07-11T03:37:55.642416Z DEBUG HTTP{http.method=GET http.url=https://192.168.0.1/apis/apps/v1/namespaces/linkerd/deployments/linkerd-destination otel.name="get" otel.kind="client"}: hyper::client::connect::http: connecting to 192.168.0.1:443
2023-07-11T03:37:55.642759Z DEBUG HTTP{http.method=GET http.url=https://192.168.0.1/apis/apps/v1/namespaces/linkerd/deployments/linkerd-destination otel.name="get" otel.kind="client"}: hyper::client::connect::http: connected to 192.168.0.1:443
2023-07-11T03:37:55.646330Z ERROR HTTP{http.method=GET http.url=https://192.168.0.1/apis/apps/v1/namespaces/linkerd/deployments/linkerd-destination otel.name="get" otel.kind="client" otel.status_code="ERROR"}: kube_client::client::builder: failed with error error trying to connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1921:: unable to get local issuer certificate
Error: HyperError: error trying to connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1921:: unable to get local issuer certificate


Caused by:
    0: error trying to connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1921:: unable to get local issuer certificate
    1: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1921:: unable to get local issuer certificate
    2: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1921:
    3: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1921:
```

## using rustls-tls:
```
2023-07-09T17:17:29.803062Z  WARN rustls::conn: Sending fatal alert BadCertificate 
2023-07-09T17:17:29.803184Z ERROR kube_client::client::builder: failed with error error trying to connect: invalid peer certificate contents: invalid peer certificate: UnknownIssuer
Error: HyperError: error trying to connect: invalid peer certificate contents: invalid peer certificate: UnknownIssuer

Caused by:

    0: error trying to connect: invalid peer certificate contents: invalid peer certificate: UnknownIssuer
    1: invalid peer certificate contents: invalid peer certificate: UnknownIssuer
```

### output of `linkerd check -o short`

```
$  linkerd check
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
| pod/linkerd-destination-b88467986-thsmr container policy is not ready   << hang because of the error mentioned

```

### Environment

```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:38:05Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.17", GitCommit:"953be8927218ec8067e1af2641e540238ffd7576", GitTreeState:"clean", BuildDate:"2023-02-22T13:27:46Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"linux/amd64"}
```

### Possible solution

allow a flag somewhere so that linkerd can be used on  clusters that are configured with this option:
```
$ cat ~/.kube/config 

clusters:
- cluster:
    insecure-skip-tls-verify: true   
  ...
```

### Additional context

for clusters that are isolated (not on the internet) and are configured with self-signed certs that would be a nice feature. We have hundreds of those and would really like to use linkerd on them.

### Would you like to work on fixing this bug?

None

**Comment by jennifergithub** [comment]
Hi, thanks for filing this. I'm getting the same error, also using OpenSSL to generate certs. Do you think it's the particular way we're creating the OpenSSL certs? This may be helpful, wasn't for me: https://github.com/linkerd/linkerd2/discussions/6819

**Comment by christiancadieux** [comment]
I am no expert but i think there are different problems. bad cert means the cert was built in correctly. Unknwown-issuer means that the cert is self-signed and cannot be verified. 
for my case, the real solution is not really to change linkerd , but rather to include the ca.crt as an authority . 
for kubernetes , the file is /usr/local/share/ca-certificates/kubernetes.crt (as explained in  https://kubernetes.io/docs/tasks/administer-cluster/certificates/ ).

there is also an explanation for rust here: https://github.com/pjungwir/rust-ssl-self-signed

I will close this issue as it is not a linkerd issue, it's just related to the general problem of how to make a self-signed cert trusted.

**Comment by jennifergithub** [comment]
Thanks for the response. I guess my question is, how has this issue not been raised sooner? I'm sure plenty of users use a self-signed cert for experimental purposes or in production. 

I got this same error in the logs even when using the step self-signed certs Linkerd instructs to use in documentation. Just wondering if this error is benign or should affect any usage of Linkerd, it seems like my meshed services are working as expected.
