### ISSUE TITLE
adding client id in the route metrics

### ISSUE THREAD

**Issue by tanmayiiti** [linkerd/linkerd2#11100]
### What problem are you trying to solve?

We are trying to get per route per client metrics in linkerd. This would help us to track traffic between microservices and can be used to rate-limit per-route per client.

### How should the problem be solved?

We should allow to add client id at proxy layer or custom client id picked from the application request headers.  

### Any alternatives you've considered?

NA

### Would you like to work on this feature?
Yes

**Comment by kflynn** [comment]
De-staling -- @tanmayiiti, are you still interested in working on this one? 🙂
