### ISSUE TITLE
Replace the deprecated "failure-domain" label with "topology" label in the partials _affinity.tpl 

### ISSUE THREAD

**Issue by deusxanima** [linkerd/linkerd2#11114]
### What is the issue?

As of K8s 1.17 the [`failure-domain`](https://kubernetes.io/docs/reference/labels-annotations-taints/#failure-domainbetakubernetesiozone) label has been replaced with the [`topology`](https://kubernetes.io/docs/reference/labels-annotations-taints/#topologykubernetesiozone) label. 

Our current implementation leads to noisy logs (and unnecessary ingestion costs associated with them) for users running on higher versions of K8s when paired with scheduling tools such as Karpenter. We should update our templates to reflect the currently supported label.

### How can it be reproduced?

Set up Linkerd in a Karpenter-controlled cluster and observe the logs noted below when attempting to schedule new pods.

### Logs, error output, etc

relaxing soft constraints for pod since it previously failed to schedule, removing: spec.affinity.podAntiAffinity.preferredDuringSchedulingIgnoredDuringExecution[0]={"weight":100,"podAffinityTerm":{"labelSelector":{"matchExpressions":[{"key":"linkerd.io/control-plane-component","operator":"In","values":["proxy-injector"]}]},"topologyKey":"failure-domain.beta.kubernetes.io/zone"}}

### output of `linkerd check -o short`

n/a

### Environment

n/a

### Possible solution

update templates to use supported labels.

### Would you like to work on fixing this bug?

None

**Comment by piyushsingariya** [comment]
Hi Raising a PR for this, I think it's as easy as replacing the label across the project. Please guide me in-case if I'm not in correct direction.
