### ISSUE TITLE
expose gRPC as gRPC web

### ISSUE THREAD

**Issue by ctaggart** [linkerd/linkerd2#1111]
Building off of rfc Ingress Support #629

As an operator, I would like to expose a set of gRPC based services to the outside world for use in web applications by having conduit expose the services as gRPC web.

Basically, something similar to what Envoy is building:
https://www.envoyproxy.io/docs/envoy/latest/configuration/http_filters/grpc_web_filter#config-http-filters-grpc-web

Web applications can then consume the gRPC web services using tools like https://www.npmjs.com/package/ts-protoc-gen

**Comment by grampelberg** [comment]
Cool! It looks like this is via. Envoy's gRPC-Web support.

**Comment by ctaggart** [comment]
A cool live example of gRPC web being used in the browser is https://grpcweb.jbrandhorst.com/

**Comment by hartmut-co-uk** [comment]
+1 
there's been a lot of movement over the past few days
https://github.com/grpc/grpc-web

**Comment by hartmut-co-uk** [comment]
ah on a side note - I just noticed the example/showcase page is built on the 
> **Improbable gRPC-Web implementation** https://github.com/improbable-eng/grpc-web

Same as people with Google internally Improbably were came up with, designed and built a 'grpc web' solution for the browser - were the first to OpenSource and share their work
...collaborated and contributed with the grpc team to spec out the future 'official?' grpc-web protocol: https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-WEB.md

I do hope I'm not saying anything wrong - anyone please let me know if that would be the case!

References:
https://improbable.io/games/blog/grpc-web-moving-past-restjson-towards-type-safe-web-apis
https://github.com/grpc/grpc-web/blob/master/ROADMAP.md
https://github.com/grpc/grpc-web/blob/master/BROWSER-FEATURES.md

**Comment by ctaggart** [comment]
Also worth mentioning the Rust based [tower-grpc](https://github.com/tower-rs/tower-grpc) by contributes here too. I've been watching and reading from the sidelines. I'm really looking forward to how this plays out.

* @seanmonstar [warp](http://seanmonstar.com/post/176530511587/warp)
* @carllerche  [Announcing Tower — A library for writing robust network services with Rust.](https://medium.com/@carllerche/announcing-tower-a-library-for-writing-robust-network-services-with-rust-67273f052c40)

**Comment by hartmut-co-uk** [comment]
hot off the press - to clarify above `grpc/grpc-web` vs. `improbable-eng/grpc-web` - they actually do Inter-op.. 
https://github.com/grpc/grpc-web/issues/91

**Comment by grampelberg** [comment]
@hartmut-co-uk have you taken a look at google/rejoiner ? Does something like that make sense or are you looking for grpc/grpc-web specifically?

**Comment by hartmut-co-uk** [comment]
thx @grampelberg, was specifically for `grpc/grpc-web`

**Comment by ctaggart** [comment]
Congrats on Linkerd 2! I enjoyed this presentation by @klingerf and will probably try it out soon. I like seeing `GRPC status` next to `HTTP status`:

https://youtu.be/3Fpa2Z_r4nE?t=24m26s
![image](https://user-images.githubusercontent.com/80104/45911601-60361280-bdca-11e8-864a-91576fe6b57b.png)

We currently have nginx sidecars for our service providing TLS termination. I'm interested in replacing the sidecars with Linkerd 2, but I'd really like to see this feature added so I don't have to wedge [another proxy](https://github.com/grpc/grpc-web#proxy-interoperability) in between such as the gRPC-Web Go Proxy.

**Comment by hartmut-co-uk** [comment]
not stale

**Comment by grampelberg** [comment]
For now, the decision is to have grpc-web run as a separate proxy instead of moving that functionality into the linkerd proxy directly.

**Comment by ejemba** [comment]
Hi @grampelberg, I'm new to linkerd2 and grpc-web. I'm willing to use linkerd2 with grpc-web. 
Can you just describe what you mean by « run as a separate proxy » what will be the proxy here ?
thank you

**Comment by grampelberg** [comment]
@ejemba the grpc-web project recommends Envoy, but there is also [grpc-web](https://github.com/improbable-eng/grpc-web).

**Comment by ejemba** [comment]
Thank you @grampelberg . I'll try to find some relevant projects to base me on.

**Comment by subhan-nadeem** [comment]
@grampelberg I'm trying to gain some additional insight on leveraging a gRPC web proxy (such as Envoy) with linkerd. If I have a gRPC server that is managed by a LinkerD service mesh, and I have a grpc-web client that wishes to interact with my gRPC server, will I have to deploy an Envoy proxy instance on top of linkerd that receives the grpc-web requests, and then routes it to the linkerd service mesh?
