### ISSUE TITLE
no connection for vault-agent-init container after injecting

### ISSUE THREAD

**Issue by janluak** [linkerd/linkerd2#11124]
### What is the issue?

We would like to use Hashicorp's vault for secrets management with it's sidecar injection of secrets in combination with your nice mesh.

Unfortunately, when trying to retrieve secrets with the vault's sidecar after having either the vault or the application meshed it generates following error:
```
agent.auth.handler: error authenticating: error="Put \"http://vault.vault.svc:8200/v1/auth/kubernetes/login\": dial tcp 10.43.204.196:8200: connect: connection refused"
```

Actually, all outgoing traffic seems to be blocked since any `wget` from the vault's sidecar shell is not working.

Does anybody have a solution / config change etc.? Or is it actually a bug?
Thanks for the help!
Both tools are great and I'd like to see them both in parallel ;)

### How can it be reproduced?

Install vault:

dev.yaml
```dev.yaml
server:
  dev:
    enabled: true
    devRootToken: "root"
```
- - -

```
helm repo add hashicorp https://helm.releases.hashicorp.com && helm repo update
helm install vault hashicorp/vault -n vault --create-namespace --values dev.yaml
```
- - -

In vault, run these commands to have a working test vault:

```
vault auth enable kubernetes && vault write auth/kubernetes/config kubernetes_host="https://$KUBERNETES_PORT_443_TCP_ADDR:443"

vault secrets enable -path=secret kv-v2

vault policy write reading-secrets - <<EOF
path "secret/*" {
  capabilities = ["read"]
}
EOF

vault write auth/kubernetes/role/dev \
    bound_service_account_names="test-account" \
    bound_service_account_namespaces="test"
    token_policies="reading-secrets" \
    ttl="24h"

vault kv put -mount=secret test foo=bar bar=baz
```

- - -

Then, add these annotations to any pod/deployment running in namespace `test`:
```yaml
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "dev"
        vault.hashicorp.com/agent-inject-secret-example.json: "secret/test"

    spec:
      serviceAccountName: test-account
```
- - -

The annotated pod should be able to retrieve the secret.
After injecting (e.g. the namespaces of app and vault, and restarting) the error occurs.

### Logs, error output, etc

agent.auth.handler: error authenticating: error="Put \"http://vault.vault.svc:8200/v1/auth/kubernetes/login\": dial tcp 10.43.204.196:8200: connect: connection refused"

### output of `linkerd check -o short`

```
linkerd-version
---------------
‼ cli is up-to-date
    is running version 2.13.3 but the latest stable version is 2.13.5
    see https://linkerd.io/2.13/checks/#l5d-version-cli for hints

control-plane-version
---------------------
‼ control plane is up-to-date
    is running version 2.13.3 but the latest stable version is 2.13.5
    see https://linkerd.io/2.13/checks/#l5d-version-control for hints

linkerd-control-plane-proxy
---------------------------
‼ control plane proxies are up-to-date
    some proxies are not running the current version:
        * linkerd-identity-787d748674-cv7pv (stable-2.13.3)
        * linkerd-proxy-injector-774d7f6d56-kd247 (stable-2.13.3)
        * linkerd-destination-56c8bc7b9c-pf5np (stable-2.13.3)
    see https://linkerd.io/2.13/checks/#l5d-cp-proxy-version for hints

linkerd-jaeger
--------------
‼ jaeger extension proxies are up-to-date
    some proxies are not running the current version:
        * jaeger-injector-b577946b5-7l9j5 (stable-2.13.3)
        * jaeger-7bb6b57d5-f88c8 (stable-2.13.3)
        * collector-687978d4c-gbfhj (stable-2.13.3)
    see https://linkerd.io/2.13/checks/#l5d-jaeger-proxy-cp-version for hints

linkerd-viz
-----------
‼ viz extension proxies are up-to-date
    some proxies are not running the current version:
        * metrics-api-7b9bfc46d9-w54gv (stable-2.13.3)
        * web-5567c56f8f-z85dm (stable-2.13.3)
        * tap-injector-7cb598848b-s4prp (stable-2.13.3)
        * tap-59b8bd6f96-lkczc (stable-2.13.3)
        * prometheus-8448579b54-frtzk (stable-2.13.3)
    see https://linkerd.io/2.13/checks/#l5d-viz-proxy-cp-version for hints

Status check results are √
```

### Environment

rancher desktop / native k3s
latest linkerd & vault

### Would you like to work on fixing this bug?

None

**Comment by wc-s** [comment]
See: https://github.com/linkerd/linkerd2/issues/9625

Are you using the CNI method or the init container method to initialize linkerd's IP routing?

If using init container, then add the `vault.hashicorp.com/agent-init-first` pod annotation  so that the vault init container runs before the linkerd init container.

If using CNI, well it's a bit more complicated, best to have a read through the linked issue thread.

**Comment by janluak** [comment]
ah thanks, that was doing the trick!
I was using the init container, so the annotation `vault.hashicorp.com/agent-init-first: "true"` got it working 👍
