### ISSUE TITLE
Failed connections on ingress to ExternalName services in 2.13

### ISSUE THREAD

**Issue by risingspiral** [linkerd/linkerd2#11127]
### What is the issue?

When an ingress controller opens a connection to an IP address that neither the policy controller nor the destination controller will provide a response for, such as an address resolved by a DNS lookup for an ExternalName service, and the ingress controller is not configured to add an l5d-dst-override header, the proxy will fail requests on that connection.

### How can it be reproduced?

Observed here: https://github.com/linkerd/linkerd2/issues/10908#issuecomment-1608273155

### Logs, error output, etc

See: https://github.com/linkerd/linkerd2/issues/10908#issuecomment-1608273155

### output of `linkerd check -o short`

N/A

### Environment

Linkerd 2.13.x

### Possible solution

Confirmed behavior in 2.13.x. In 2.12, the proxy would have blindly forwarded those requests to the original destination address, instead.

### Additional context

This is a follow-on issue from https://github.com/linkerd/linkerd2/issues/10908

### Would you like to work on fixing this bug?

no

**Comment by chicocvenancio** [comment]
This is still an issue for 2.14-stable, right?
