### ISSUE TITLE
Set `readOnlyRootFilesystem: true` on control plane and plugin components

### ISSUE THREAD

**Issue by deusxanima** [linkerd/linkerd2#11142]
### What problem are you trying to solve?

Control Plane, Jaeger injector, and linkerd SMI lack the `readOnlyRootFilesystem: true` setting. This setting defaults to false currently which grants unnecessary write permissions. 

### How should the problem be solved?

Update Helm charts for all mentioned components to explicitly set `readOnlyRootFilesystem: true` as the default for said components.

### Any alternatives you've considered?

n/a

### How would users interact with this feature?

Helm charts

### Would you like to work on this feature?

None

**Comment by Dev-Arhaan** [comment]
hey I would like to work on this. it seems pretty simple but i have no experience with helm, I'd appreciate if I can contribute and understand this project

**Comment by ParthBoghani46** [comment]
hey @deusxanima , i am interested in this can you assign and guide me.
