### ISSUE TITLE
Remove `hostNetwork: true` from linkerd-cni Helm chart templates

### ISSUE THREAD

**Issue by deusxanima** [linkerd/linkerd2#11141]
### What problem are you trying to solve?

Current does Linkerd CNI Helm chart templates have `hostNetwork: true` set which is unnecessary and less secure. 

### How should the problem be solved?

We should remove it from the chart template, or in the alternative, make it default `false` if we want to preserve the option to set it to true when needed.

### Any alternatives you've considered?

n/a

### How would users interact with this feature?

Helm charts

### Would you like to work on this feature?

None

**Comment by abhijeetgauravm** [comment]
I want to work on it. Can u assign me?
