### ISSUE TITLE
Improve Load Balancing behind the Service Mirror configuration

### ISSUE THREAD

**Issue by mullermateus** [linkerd/linkerd2#11161]
### What problem are you trying to solve?

Just to give you a brief context. We have Linkerd with AWS EKS, and the Linkerd Gateway is exposed through a Network Load Balancer across three Availability Zones.

Currently, only one IP address is taken to be behind the mirrored service endpoint:

```
$ kubectl get endpoints -n <ns>

<mirrored-service-name>           10.131.A.B:4143   24d
```

Even though we have three available IPs.

```
$ dig k8s-linkerd-multicluster-<id>.elb.us-west-2.amazonaws.com +short

10.131.A.B
10.131.C.D
10.131.E.F
```

I understand that this unique endpoint is constantly tested by the probes, and it is flipped in case of failures.

Although, all the traffic is being routed through one Elastic Network Interface, and consequently, one Availability Zone. In case of a disaster, we would have a downtime until the probes decide to flip the endpoint. Also, the requests are not balanced across the ENIs.

Wouldn't be more interesting to have all 3 IPs behind the service mirror? Something like this:

```
$ kubectl get endpoints -n <ns>

<mirrored-service-name>           10.131.A.B:4143,10.131.C.D,10.131.E.F:4143:4143   24d
```

I'm not sure if this already exists as I couldn't find any customization to achieve this. Apologies for any incovenience!

KR,
Mateus

### How should the problem be solved?

Add all the Network Load Balancer IP addresses behind the mirrored service.

### Any alternatives you've considered?

Yes! The Linkerd failover mechanism works perfectly, this is just suggestion for improvement.

### Would you like to work on this feature?

no

**Comment by adleong** [comment]
Hi @mullermateus!

This is good timing because we're actively working on adding support for direct multicluster pod-to-pod communication where all remote endpoints are referenced directly by the mirror service instead of going through the gateway.  You can read some more context about our thought process here: https://linkerd.io/2023/07/20/enterprise-multi-cluster-at-scale-supporting-flat-networks-in-linkerd/

**Comment by mullermateus** [comment]
> 

Hi @adleong,

Thanks for the quick response! I believe I missed this blog post, sorry. The pod-to-pod communication looks great, I'll keep an eye on `2.14.0` and test it out.

Feel free to close the issue, thanks!
