### ISSUE TITLE
Load testing linkerd before its marked as stable.

### ISSUE THREAD

**Issue by nikskiz** [linkerd/linkerd2#11172]
### What problem are you trying to solve?

Put the proxy and linkerd under load/stress before marking a new linkerd version as stable. This could catch bugs as per issue https://github.com/linkerd/linkerd2/issues/11055

### How should the problem be solved?

Catching bugs related to high load before they are released.

### Any alternatives you've considered?

Pushing users to load test linkerd before they upgrade. This is not ideal, since this could create false positives and blame linkerd for issues. 

### How would users interact with this feature?

It would be nice for linkerd to recommend a load test framework via their docs, which users can also run tests locally.

### Would you like to work on this feature?

yes

**Comment by olix0r** [comment]
Thanks for opening this @nikskiz. I agree that it's important that we prevent regressions like #11055.

In this case, we did run Linkerd through a variety of test environments prior to 2.13, but clearly none of them ran with enough sustained traffic to trigger this issue. This is easy to remedy going into the 2.14 release: we'll at least run through a variety of manual tests including the k6 tests provided in the aforementioned issue, as well as some of our other testing tools like [slow_cooker](https://github.com/BuoyantIO/slow_cooker).

Moving forward into the 2.15 release cycle, we'll automate more of this. Based on prior experience with this sort of thing, Actions tends to have unreliable/variable performance that can really degrade the quality of data we get from these kind of tests. I expect we'll need to use more reliable hosting for this.
