### ISSUE TITLE
Helm linkerd-controler-plane Allow Custom labels on Pod Monitor

### ISSUE THREAD

**Issue by jseiser** [linkerd/linkerd2#11175]
### What problem are you trying to solve?

I need the prometheus operator to be able to scrape our pod monitors that we create from this helm chart.

### How should the problem be solved?

https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/README.md#prometheusioscrape

We just need to label the podMonitor

### Any alternatives you've considered?

I could modify the default scraping of the Prometheus operator

### Would you like to work on this feature?

yes

**Comment by alpeb** [comment]
Sounds like a simple addition into the `podmonitor.yaml` template. Please submit a PR and I'd be happy to review it :-)
