### ISSUE TITLE
Add chart versions matrix in charts README files

### ISSUE THREAD

**Issue by alpeb** [linkerd/linkerd2#11199]
The versions for the linkerd-crds and linkerd2-cni charts aren't necessarily bumped on every new linkerd-control-plane chart release. Usually people just grab the latest version from these charts from our Helm repo, but it's not trivial when one wants to install a specific version, as you have to browse the linkerd source repo, locate the tag for the linkerd version, and see what are the corresponding chart versions.

We should add a charts version matrix to all the charts managed in this repo, copied into all their corresponding `README.md.gotmpl` files, that is to be updated on every release.

**Comment by logicminds** [comment]
It is missing the CNI info but might be helpful otherwise.  https://gist.github.com/logicminds/d2dd8fb62eb4c9411a1a7a9e69a0bfd4

**Comment by logicminds** [comment]
This feature was added to the docs website under releases.  This issue can be closed.

**Comment by alpeb** [comment]
yay!
