### ISSUE TITLE
Metrics for certificate expiry

### ISSUE THREAD

**Issue by whickman** [linkerd/linkerd2#11215]
### What problem are you trying to solve?

I'd like to be able to monitor the days/hours until the certs in my linkerd install expire via logs / metrics because expiration results in an immediate outage. Even with something like cert-manager installed, it would be nice to have a fallback monitor to make sure we catch cases where things stop working.

`linkerd check` tells me if the certs will expire in the next 60 days, but as far as I can tell there's no metric equivalent.

### How should the problem be solved?

metrics or reliably-emitted, easily-to-parse logs emitted by one of the linkerd services.

### Any alternatives you've considered?

running `linkerd check` periodically inside a dedicated container. requires giving the pod a fair amount of permission and seems like more work than should be required.

### How would users interact with this feature?

write monitors / alerts for certs about to expire

### Would you like to work on this feature?

maybe

**Comment by adleong** [comment]
There's no metric, but you can inspect the certificate and see it's expiry date with a command like:

```
kubectl -n linkerd get cm/linkerd-config -ojsonpath={.data.values} | yq .identity.issuer.tls.crtPEM | step certificate inspect -
```

(for convenience this command uses `yq` for yaml parsing and `step` for certificate inspection)

**Comment by whickman** [comment]
ok, thanks @adleong -- seems like I'd need to run that in a dedicated container (or external cron/lambda/etc) w/ a decent amount of permissions to have a real monitor on cert age, which I'd like to avoid. Is adding this metric a reasonable FR? Similar metrics are pretty common amongst other proxies, I think.

**Comment by pblgomez** [comment]
+1
