### ISSUE TITLE
Support Cluster with self-signed certs.

### ISSUE THREAD

**Issue by christiancadieux** [linkerd/linkerd2#11237]
### What problem are you trying to solve?

support kubernetes cluster that use self-signed certs  to avoid this error:

2023-08-12T18:22:22.918370Z ERROR kube_client::client::builder: failed with error error trying to connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1921:: unable to get local issuer certificate
Error: HyperError: error trying to connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1921:: unable to get local issuer certificate

Caused by:
    0: error trying to connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1921:: unable to get local issuer certificate
    1: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1921:: unable to get local issuer certificate
    2: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1921:
    3: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1921:

version: 2.13.6

### How should the problem be solved?

support kubernetes cluster that use self-signed certs 

Make a custom version of the policy-controller image that includes the cluster CA in the image. 
Make sure the directory includes the linkerd-policy-controller binary and clusterxyz.kube_ca_crt.pem needed:
```
FROM ubuntu
RUN apt-get update && apt-get install -y ca-certificates
# copy kube_ca
ADD  clusterxyz.kube_ca_crt.pem /usr/local/share/ca-certificates/kube_ca.crt
RUN chmod 644 /usr/local/share/ca-certificates/kube_ca.crt && update-ca-certificates
RUN mkdir -p /usr/local/ssl
# Rust need the certs in a special directory
RUN ln -s /etc/ssl/certs /usr/local/ssl/certs
COPY policy-controller /linkerd-policy-controller
ENTRYPOINT ["/linkerd-policy-controller"]
```

### Any alternatives you've considered?

no - that works - Updating linkerd source would also work - but who has that kind of time :-)  
```
$ linkerd check
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ control plane pods are ready
√ cluster networks contains all pods
√ cluster networks contains all services

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ proxy-init container runs as root user if docker container runtime is used

linkerd-identity
----------------
√ certificate config is valid
√ trust anchors are using supported crypto algorithm
√ trust anchors are within their validity period
√ trust anchors are valid for at least 60 days
√ issuer cert is using supported crypto algorithm
√ issuer cert is within its validity period
√ issuer cert is valid for at least 60 days
√ issuer cert is issued by the trust anchor

linkerd-webhooks-and-apisvc-tls
-------------------------------
√ proxy-injector webhook has valid cert
√ proxy-injector cert is valid for at least 60 days
√ sp-validator webhook has valid cert
√ sp-validator cert is valid for at least 60 days
√ policy-validator webhook has valid cert
√ policy-validator cert is valid for at least 60 days

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ can retrieve the control plane version
√ control plane is up-to-date
√ control plane and cli versions match

linkerd-control-plane-proxy
---------------------------
√ control plane proxies are healthy
√ control plane proxies are up-to-date
√ control plane proxies and cli versions match

$ linkerd version

Client version: stable-2.13.6
Server version: stable-2.13.6


$ kubectl get pod -n linkerd

NAME                                      READY   STATUS    RESTARTS   AGE
linkerd-destination-7d674d79b4-rzx6b      4/4     Running   0          138m
linkerd-identity-7dc598558d-dsjjr         2/2     Running   0          138m
linkerd-proxy-injector-67b7cf9d88-szsgs   2/2     Running   0          138m

$ k get pod -n linkerd-viz
NAME                            READY   STATUS    RESTARTS   AGE
metrics-api-5d559b977b-bclh8    2/2     Running   0          127m
prometheus-64d99d8f75-56grb     2/2     Running   0          127m
tap-5847bddc7-962q8             2/2     Running   0          127m
tap-injector-56ffd45646-rsvj7   2/2     Running   0          127m
web-6b7467786d-pdlpm            2/2     Running   0          115m

```

### How would users interact with this feature?

build new image

### Would you like to work on this feature?

no

**Comment by suraciii** [comment]
I have a similar issue, but it couldn't be solved by trusting cluster ca in docker images.
I tried to curl api server in container, it has no tls issue, but policy-controller still reports `unable to get issuer certificate` error on starting, (perhaps it's because the ca cert is an old with 1024 key size).

I wonder if it's reasonable that allow to skip cluster cert varification totally

**Comment by chris-ng-scmp** [comment]
https://github.com/linkerd/linkerd2/issues/10994#issuecomment-1681522416

I have the same issue as well, the K8S API cert doesn't pass the validation

Would be great if able to skip the cert verification
