### ISSUE TITLE
Dynamic request routing not working using HttpRoute across namespace

### ISSUE THREAD

**Issue by Arpit1596** [linkerd/linkerd2#11247]
### What is the issue?

Dynamic request routing not working using HttpRoute across namespace.
We recently upgraded to Linkerd 2.13.6-stable version and EKS version is 1.27.
It was working fine before this but after the upgrade it stopped working. 
Request is not routed from test-service in default to test-service-variables in canary

### How can it be reproduced?

Use Linkerd 2.13.6-stable version and EKS version 1.27 

This is the HttpRoute 
```
Name:         test-service-router
Namespace:    default
Labels:       <none>
Annotations:  <none>
API Version:  policy.linkerd.io/v1beta2
Kind:         HTTPRoute
Metadata:
  Creation Timestamp:  2023-08-15T05:16:35Z
  Generation:          3
  Resource Version:    180016112
  UID:                 cccfcc20-dabe-43de-b645-414ff9c78000
Spec:
  Parent Refs:
    Group:  core
    Kind:   Service
    Name:   test-service
    Port:   3009
  Rules:
    Backend Refs:
      Group:      
      Kind:       Service
      Name:       test-service-variables
      Namespace:  canary
      Port:       3009
      Weight:     1
    Matches:
      Headers:
        Name:   x-request-id
        Type:   Exact
        Value:  variables
      Path:
        Type:   PathPrefix
        Value:  /
    Backend Refs:
      Group:   
      Kind:    Service
      Name:    test-service
      Port:    3009
      Weight:  1
    Matches:
      Path:
        Type:   PathPrefix
        Value:  /
        ```

### Logs, error output, etc

-

### output of `linkerd check -o short`

-

### Environment

-

### Would you like to work on fixing this bug?

None

**Comment by alpeb** [comment]
We have recently made improvements in HTTPRoute processing, so I'd encourage you to give a try at the latest edge, or you can wait for stable-2.14.0 that will come out next week, and see if the problem persists. Thanks in advance!
