### ISSUE TITLE
RKE2 Canal / Multus with CNI not coming up

### ISSUE THREAD

**Issue by joelcomp1** [linkerd/linkerd2#11250]
### What is the issue?

I am trying to test out migrating from Istio to Linkerd, I installed the CRDs, and the CNI using my Istio configuration which had the CNI config dir as destCNINetDir="/etc/cni/multus/net.d".  With this The CNI comes up without issue. 

When I go to install linkerd helm chart I enabled the CNI via cniEnabled=true, but when the containers start up the init container linkerd-network-validator fails with error code 95 

### How can it be reproduced?

See above, install RKE2 with Canal / Multus and setup Linkerd with CNI.  I tried it without the CNI but then I ran into SELINUX issues I believe.

### Logs, error output, etc

in the log it says:

2023-08-15T14:52:27.798011Z ERROR linkerd_network_validator: Failed to validate networking configuration. Please ensure iptables rules are rewriting traffic as expected. timeout=10s

### output of `linkerd check -o short`

linkerd-existence
-----------------
× control plane pods are ready
    No running pods for "linkerd-destination"
    see https://linkerd.io/2.13/checks/#l5d-api-control-ready for hints

Status check results are ×

### Environment

RKE2 1.27.2
RHEL 8 SELINUX Enabled
Linkerd version stable-2.13.6

### Would you like to work on fixing this bug?

no

**Comment by alpeb** [comment]
Can you please provide the logs for the linkerd-cni DaemonSet? That might provide some extra clues.

**Comment by stefan-lange** [comment]
I have the same issue
- linkerd-network-validator fails with error code 95, same error message
```
2023-11-02T11:16:24.117144Z  INFO linkerd_network_validator: Connecting to 1.1.1.1:20001
2023-11-02T11:16:34.119613Z ERROR linkerd_network_validator: Failed to validate networking configuration. Please ensure iptables rules are rewriting traffic as expected. timeout=10s
```
- firewall allow rule for `1.1.1.1:20001/TCP` exists
- Linkerd version `stable-2.14.2`, (chart linkerd-control-plane `1.16.3`)
- linkerd-cni installed via helm chart `30.12.1`, default config

DS logs
```
[2023-11-02 11:07:14] Wrote linkerd CNI binaries to /host/opt/cni/bin
[2023-11-02 11:07:14] No active CNI configuration files found
Setting up watches.
Watches established.
[2023-11-02 11:07:17] Wrote linkerd CNI binaries to /host/opt/cni/bin
[2023-11-02 11:07:17] No active CNI configuration files found
Setting up watches.
Watches established.
```

Maybe these logs can help.

**Comment by stefan-lange** [comment]
I got linkerd working with try & error and some config adjustments. I am using `k3s`.

Changed helm values:
```
# -- Directory on the host where the CNI configuration will be placed
destCNINetDir: "/var/lib/rancher/k3s/agent/etc/cni/net.d"
# -- Directory on the host where the CNI plugin binaries reside
destCNIBinDir: "/var/lib/rancher/k3s/data/current/bin"
```

This post helped me: https://github.com/linkerd/linkerd2/issues/10413#issuecomment-1448425388.

My next steps are to use linkerd instead of flannel in k3s (https://docs.k3s.io/installation/network-options?_highlight=cni#custom-cni)

**Comment by alpeb** [comment]
Thank you @stefan-lange for the resolution. I've opened #11598 so we can properly add this into the docs.
