### ISSUE TITLE
linkerd-jaeger injector fails when pod already has a podinfo volume

### ISSUE THREAD

**Issue by amccague** [linkerd/linkerd2#11254]
### What is the issue?

The following template is attempted to be applied and the `podinfo` volume may conflict with an existing definition leading to an error when the pod is provisioning.
https://github.com/linkerd/linkerd2/blob/51214c06668e7585f33649327a39b87fe655eefa/jaeger/injector/mutator/patch.go#L41-L57

### How can it be reproduced?

Create a meshed pod that already has a `podinfo` downward API volume.

### Logs, error output, etc

```
Error creating: Pod "my-pod-796d57f667-bbt76" is invalid: spec.volumes[10].name: Duplicate value: "podinfo"
```

### output of `linkerd check -o short`

```text
linkerd-config
--------------
× control plane CustomResourceDefinitions exist
    CRD httproutes.policy.linkerd.io is missing version v1beta2
    see https://linkerd.io/2.13/checks/#l5d-existence-crd for hints
```

### Environment

- Kubernetes version: 1.23.17-eks
- LInkerd version stable-2.12.4

### Possible solution

The podinfo section could be merged with an existing one or the existing one checked before applying that patch.

Assuming `podinfo` can be alternatively named, the volume could also be prefixed with a linkerd specific name.

### Would you like to work on fixing this bug?

None

**Comment by alpeb** [comment]
Thanks for the report @amccague. This is a sensible request IMO. Should be a simple change, so I'm labeling this accordingly if anyone wants to take a stab at it.

**Comment by pratikkumar-mohite** [comment]
@alpeb I would like to work on it, can you please assign it to me?

**Comment by alpeb** [comment]
@pratikkumar-mohite done, looking forward for the PR :-)

**Comment by moki1202** [comment]
@alpeb 
```
{
    "op": "add",
    "path": "/spec/containers/{{.ProxyIndex}}/volumeMounts/-",
    "value": {
      "mountPath": "var/run/linkerd/podinfo",
      "name": "podinfo"
}
```
Is changing the volume name to "tracing-podinfo" a good solution here? I suppose this podinfo volume likely contains tracing annotations from jaegar.

**Comment by alpeb** [comment]
> Is changing the volume name to "tracing-podinfo" a good solution here?

I would renaming to something like `linkerd-podinfo` so it's clear it's linkerd who injected that.
