### ISSUE TITLE
Add ability to override tag for the controller image

### ISSUE THREAD

**Issue by alpeb** [linkerd/linkerd2#11269]
Currently the container images in the manifests for the linkerd core controllers have their tags parametrized to `{{.Values.linkerdVersion}}`. There are circumstances (like pointed out [here](https://linkerd.buoyant.io/t/specifying-image-sha-rather-than-tag-in-helm-chart/229)) were we'd like to override this. The solution would be to add something like a `controllerImageVersion` entry in `values.yaml` with an empty string default, and use that in the templates if non-empty (via helm's `default` function).

**Comment by utibeabasi6** [comment]
hey
i would like to work on this if its still open
maybe some guidance to help me get started

**Comment by utibeabasi6** [comment]
hmm
i seem to be having an issue signing the commit for the DCO
can anyone help?

**Comment by utibeabasi6** [comment]
ok i think i fixed the DCO issue
Apologies as this is my first time contributing

**Comment by wasup-yash** [comment]
This issue seems to be resolved, as per [this](https://github.com/linkerd/linkerd2/pull/11278#issuecomment-1736427545)

**Comment by alpeb** [comment]
Fixed by #11406
