### ISSUE TITLE
Value of `--wait` flag is being used as a timeout by `linkerd multicluster check` command

### ISSUE THREAD

**Issue by klingerf** [linkerd/linkerd2#11266]
### What problem are you trying to solve?

All check commands in the codebase support a `--wait` flag. That flag is used as the value of "RetryDeadline" when executing individual checks. For the `linkerd multicluster check` command _only_, the value of the flag is also being used as a timeout when checking if gateway mirrors have endpoints. This is confusing, since the `--wait` duration controls whether or not to retry failed checks in almost all cases, but it also controls how long it takes to run an individual check in just this one case.

### How should the problem be solved?

We could introduce a separate `--timeout` flag that can be used to time out individual checks. That way the `--wait` flag can be used to control retry behavior exclusively, and not affect timeouts.

### Any alternatives you've considered?

We could just pick a sane timeout for checking if gateway mirrors have endpoints, and not allow that duration to be configurable via CLI flags.

### Would you like to work on this feature?

maybe

**Comment by moki1202** [comment]
@adleong Can I pick this issue? I think, I have a fair idea on how to approach this.
