### ISSUE TITLE
Add Helm option to configure custom resources on linkerd-smi chart

### ISSUE THREAD

**Issue by deusxanima** [linkerd/linkerd2#11305]
### What problem are you trying to solve?

Some org security policies and third-party integrations require limits to be set on all resources in order to be installed in a cluster.  Currently the linkerd-smi chart is missing the ability to do this out of the box.

### How should the problem be solved?

Add ability to tune resources via helm values

### Any alternatives you've considered?

n/a

### How would users interact with this feature?

helm

### Would you like to work on this feature?

yes

**Comment by raxod502-plaid** [comment]
Not only that, but missing a resources block is **never** the right behavior. It means that the Kubernetes scheduler will put the deployment on any arbitrary node, completely without regard to whether enough CPU or memory is available to actually run it, resulting in outages whenever you have bad luck.

**Comment by raxod502-plaid** [comment]
It's not appropriate for this issue to be closed unless the linked PR is merged.

**Comment by raxod502-plaid** [comment]
@mateiidavid Can you reopen this issue, and disable auto-close for it?
