### ISSUE TITLE
Add policyController resource propagation through values-ha.yaml

### ISSUE THREAD

**Issue by deusxanima** [linkerd/linkerd2#11301]
### What problem are you trying to solve?

When adding values-ha.yaml to a Helm deployment, all Control plane components obtain cpu requests and memory requests and limits. All except the policy container on the destination pod.

### How should the problem be solved?

Add the following to the values-ha.yaml template:

```
policyController:
resources: *controller_resources
```

### Any alternatives you've considered?

n/a

### How would users interact with this feature?

helm 

### Would you like to work on this feature?

None

**Comment by spawan02** [comment]
I like to work on this issue.

**Comment by mateiidavid** [comment]
Closed through https://github.com/linkerd/linkerd2/pull/11306
