### ISSUE TITLE
Update/Upload chart linkerd-multicluster-link

### ISSUE THREAD

**Issue by MrFreezeex** [linkerd/linkerd2#11314]
### What is the issue?

Hello I am using ArgoCD to setup linkerd and the multicluster and would like to peer using linkerd-multicluster-link however the only chart available on the repo is `linkerd2-multicluster-link` and seems out of date for a while (14 Oct, 2022) + doesn't work with the other up to date charts.

Our setup with ArgoCD allow us to not use the linkerd cli and we also use external secret operator which allow us to sync the service account secrets automatically. Our whole setup works without manual intervention in our CD environment. We can workaround this by pointing to the git repository directly but it would be very nice if the helm chart could be published instead :pray:. 

### How can it be reproduced?

n/a

### Logs, error output, etc

n/a

### output of `linkerd check -o short`

n/a

### Environment

n/a

### Would you like to work on fixing this bug?

None

**Comment by Sierra1011** [comment]
I'm having the same issue (with Flux instead of Argo) where I'm forced down a decidedly un-GitOps approach in order to make this work.
