### ISSUE TITLE
linkerd proxy not starting

### ISSUE THREAD

**Issue by shyam-ks** [linkerd/linkerd2#11319]
### What is the issue?

On installing linkerd 2.14

[BHI-MASTER\212320544@edf09a41ef2ab07 ~]$ kubectl get all -n linkerd
NAME                                          READY   STATUS                  RESTARTS      AGE
pod/linkerd-destination-7bf86774c8-v85bh      0/4     Init:CrashLoopBackOff   3 (56s ago)   109s
pod/linkerd-identity-595bdfddb-86tvw          0/2     Init:Error              4 (57s ago)   109s
pod/linkerd-proxy-injector-5b49d9587c-pjvvj   0/2     Init:Error              4 (53s ago)   109s

### How can it be reproduced?

Install Linkerd 2.14 on EKS 1.27 using cli

### Logs, error output, etc

Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  40s                default-scheduler  Successfully assigned linkerd/linkerd-destination-7bf86774c8-v85bh to ip-100-65-21-249.ec2.internal
  Normal   Pulling    39s                kubelet            Pulling image "cr.l5d.io/linkerd/proxy-init:v2.2.1"
  Normal   Pulled     37s                kubelet            Successfully pulled image "cr.l5d.io/linkerd/proxy-init:v2.2.1" in 1.929287672s (1.929305089s including waiting)
  Normal   Created    17s (x3 over 37s)  kubelet            Created container linkerd-init
  Normal   Pulled     17s (x2 over 34s)  kubelet            Container image "cr.l5d.io/linkerd/proxy-init:v2.2.1" already present on machine
  Normal   Started    14s (x3 over 34s)  kubelet            Started container linkerd-init
  Warning  BackOff    1s (x4 over 31s)   kubelet            Back-off restarting failed container linkerd-init in pod linkerd-destination-7bf86774c8-v85bh_linkerd(113b0ff0-27fa-46e4-abb4-8e30e10d5872)
[BHI-MASTER\212320544@edf09a41ef2ab07 ~]$ kubectl logs  linkerd-destination-7bf86774c8-v85bh -c linkerd-proxy  -n linkerd

### output of `linkerd check -o short`

  Warning  BackOff    27s (x10 over 2m27s)  kubelet            Back-off restarting failed container linkerd-init in pod linkerd-proxy-injector-5b49d9587c-pjvvj_linkerd(d88c4b2f-3d14-44e8-81a6-5d3cb9d7372a)
[BHI-MASTER\212320544@edf09a41ef2ab07 ~]$ Cannot initialize: Permission denied (you must be root)\n\n"

### Environment

Linkerd version 2.14
EKS 1.27
LInux Host

### Additional context

![image](https://github.com/linkerd/linkerd2/assets/88625905/df8e7bc2-45e8-4061-9c14-eef0b320df11)

### Would you like to work on fixing this bug?

None

**Comment by mateiidavid** [comment]
Have you tried running through `linkerd check`? It seems that iptables cannot work since it needs root access. Do your nodes use a different container runtime than containerd? Typically, docker shims require root access for iptables.

This can all be changed through `proxyInit.runAsRoot=true` in the Chart values file.
