### ISSUE TITLE
Expected-Target Verification

### ISSUE THREAD

**Issue by steve-gray** [linkerd/linkerd2#11322]
### What problem are you trying to solve?

We had an issue with our cloud provider recently where we lost all services and it took a while to come back, and a lot of things went wrong during the recovery. One of the issues we found was that somehow various proxies ended up in a state where they were cross-talking to the wrong addresses - IP's had been rotated on many workloads, but somehow the proxies were not picking this up.

Fortunately things weren't wire-compatible, so requests didn't succeed - however, it'd be good to have some sort of failsafe in the proxy for this.

Spoke with Travis briefly about this, as we spent a lot of time the last day or two inside Buoyant Cloud trying to find why we were getting spammed with policy denies for requests.

### How should the problem be solved?

- Receiving side should identify "Hey, these requests aren't for me" and signal back an error condition.
- Outbound proxy sees the response, and clears its state and removes the invalid destination information.

The question here is how the receiving side knows its own identities for the service-side. The issue of using the same data as the clients means that in the example of mis-routed traffic, both sides will likely be using the same information and thus no improvement.

### Any alternatives you've considered?

Could do it all application side, but its a lot of work and needs to be done for every application.

### Would you like to work on this feature?

None

**Comment by mateiidavid** [comment]
Hey @steve-gray! Thanks for the issue description! We had an assumption that we wanted to confirm if you've got the time for it.

Do your workloads use the same (shared) ServiceAccount? We already check for expected identity when building endpoints. For example, consider the snippet below:
 https://github.com/linkerd/linkerd2/blob/fd3d92a3ae7f59f85fea2199215dfe763a66ae47/controller/api/destination/endpoint_translator.go#L430-L443

for an endpoint that we consider, we get its ServiceAccount name and add it to the endpoint's metadata. I tried looking through the proxy code to see exactly where validation happens but I came up a bit short; my assumption is that we use SNI here to ensure the client's reaching the correct server.

If your workloads all use the same ServiceAccount then it might explain why this happened. A stopgap solution would be perhaps to have workloads use their own ServiceAccount to ensure SNI validation is always enforced? This would fail fast as opposed to bumping into errors during transport. With that being said, I think this ticket has two distinct suggestions:

1. A feature request for the outbound proxy to clear its state when SNI is invalid
2. Figuring out why you're seeing stale information to begin with.

Wdyt of the observations, does this line up with what you had in mind and does it make sense?
Does this make
