### ISSUE TITLE
linkerd check on host with no internet access gives missleading messages

### ISSUE THREAD

**Issue by dagri-hub** [linkerd/linkerd2#11349]
### What is the issue?

`linkerd check` fails in the following tests because it cannot get the latest version from https://versioncheck.linkerd.io/version.json

- linkerd-version
- control-plane-version
- linkerd-control-plane-proxy

When `linkerd check` fails the test "linkerd-version" due to no internet access it cannot get the recent version and therefore fails more tests (with a warning), but with irritating messages. The messages indicate that my installation does not have the correct versions - although everything is fine.

[linkerd-check-no-internet.txt](https://github.com/linkerd/linkerd2/files/12550316/linkerd-check-no-internet.txt)
[linkerd-check-internet.txt](https://github.com/linkerd/linkerd2/files/12550317/linkerd-check-internet.txt)

### How can it be reproduced?

I used stable-2.14.0, but it also works with earlier versions.

1. Install linkerd
2. Disable the internet access from the host where you are going to use the linkerd cli
3. Login into the cluster
4. Use the linkerd cli with `linkerd check` to get the result

You can do the same test and enable the internet access and the output of `linkerd check` will be correct.

### Logs, error output, etc

[linkerd-check-no-internet.txt](https://github.com/linkerd/linkerd2/files/12550389/linkerd-check-no-internet.txt)
[linkerd-check-internet.txt](https://github.com/linkerd/linkerd2/files/12550390/linkerd-check-internet.txt)

### output of `linkerd check -o short`

[linkerd-check-short.txt](https://github.com/linkerd/linkerd2/files/12550427/linkerd-check-short.txt)

### Environment

Kubernetes Version: Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.8+vmware.3", GitCommit:"53e803785668c31b8fcb41fc3607f3fdc3c87465", GitTreeState:"clean", BuildDate:"2022-11-03T17:16:51Z", GoVersion:"go1.17.11", Compiler:"gc", Platform:"linux/amd64"}
Cluster Environemnt: Tanzu
Host OS: RHEL 8.5
Linkerd Version: stable-2.14.0

### Possible solution

It would be great to change the warning messages or to skip the version tests when the latest version is not receivable from the internet or add an option for the cli where I can pass the latest version like

```
linkerd check -no-versioncheck
or
linkerd check -latest-version=stable-2.14.0
```

### Additional context

https://linkerd.slack.com/archives/C89RTCWJF/p1694093242741459

### Would you like to work on fixing this bug?

None

**Comment by mateiidavid** [comment]
@dagri-hub thanks for raising this issue! I've marked this as help wanted. From our perspective, it would make sense to change the level of the message to a `warn` instead of an error / failure. We're happy to accept a PR that implements this.

**Comment by mateiidavid** [comment]
Yeah, almost forgot to mention you can use `--expected-version`, glad you sorted it out though! I'd be happy to offer guidance if you want to contribute the patch yourself, otherwise, this up for grabs for whomever wants to do a bit of work on the CLI :)

**Comment by hawkw** [comment]
@dtaskai As far as I know, nobody's working on this, so feel free to submit a PR! Thanks in advance! :)
