### ISSUE TITLE
linkerd-proxy container not being injected when my cluster spot nodes are re-created

### ISSUE THREAD

**Issue by fbarrerafalabella** [linkerd/linkerd2#11340]
### What is the issue?

Little background: I have an EKS cluster with spot nodes for my staging environment to low costs
I followed the documentation and everything is working fine at first glance, I added the 'linkerd.io/inject': 'enabled' annotation to my namespace and when I rollout restard my deployments they come alive with the linkerd-proxy container, when the spot nodes are killed and re aprovisioned all of the deployments come alive without the linkerd-proxy, when I finally notice this, I rollout restart the deployments and they come alive with the linkerd-proxy injected why does that happens? does linkerd control pane helm chart must be deployed on a non spot node? is this behaviour expected? Is there a workarround?

### How can it be reproduced?

Provision your deployments on spot instances on EKS, wait for its recreation and the components will come alive without the linkerd-proxy container injected

### Logs, error output, etc

There are really no logs, just the linkerd-proxy not injected

### output of `linkerd check -o short`

```
linkerd check -o short
linkerd-identity
----------------
‼ issuer cert is valid for at least 60 days
    issuer certificate will expire on 2023-10-06T10:40:37Z
    see https://linkerd.io/2.14/checks/#l5d-identity-issuer-cert-not-expiring-soon for hints

linkerd-viz
-----------
‼ linkerd-viz pods are injected
    could not find proxy container for metrics-api-548f6dfc4d-88pkb pod
    see https://linkerd.io/2.14/checks/#l5d-viz-pods-injection for hints
‼ viz extension pods are running
    container "linkerd-proxy" in pod "metrics-api-548f6dfc4d-88pkb" is not ready
    see https://linkerd.io/2.14/checks/#l5d-viz-pods-running for hints
‼ viz extension proxies are healthy
    no "linkerd-proxy" containers found in the "linkerd" namespace
    see https://linkerd.io/2.14/checks/#l5d-viz-proxy-healthy for hints

linkerd-smi
-----------
‼ Linkerd extension command linkerd-smi exists
    exec: "linkerd-smi": executable file not found in $PATH
    see https://linkerd.io/2.14/checks/#extensions for hints

```

### Environment

kubernetes version 1.24
AWS cloud
linkerd stable-2.14.0 version

### Additional context

Im using spot instances for my nodes

### Would you like to work on fixing this bug?

None

**Comment by mateiidavid** [comment]
@fbarrerafalabella my hunch is that the control plane also runs on a spot instance that's taken down? Do you have more than one node in your cluster? 

My suggestion would be to either change the injector's webhook configuration to have a strict failure policy (i.e. pod cannot come up unless an admission response is sent back to the API server) or to run linkerd in HA mode (which as a side effect also ensures a strict failure policy). HA mode will ensure you have replicas spread across all of the nodes in your cluster so even when one spot instance is taken down you still have other control plane pods on other nodes. You can read more about HA mode here: https://linkerd.io/2.14/features/ha/

**Comment by fbarrerafalabella** [comment]
@mateiidavid thanks a lot for the suggestion, indeed all of my workloads are running on spot instances which are taken down, I will give it a try to the HA mode, I think with the extra PodDisruptionBudget it will be assure that the proxi injector is alive, thanks a lot

**Comment by fbarrerafalabella** [comment]
it worker perfectly with the HA enabled
