### ISSUE TITLE
[linkerd-smi] Cluster domain parameter is ignored when starting linkerd-smi

### ISSUE THREAD

**Issue by kkorekk** [linkerd/linkerd2#11359]
### What is the issue?

Hello, I'm using `linkerd-smi` with the custom cluster domain. In the helm chart there is an option to specify cluster domain however configuring it to any value always give `cluster.local` string in `linkerd-smi` logs. Except that all `ServiceMonitors` created by SMI extension always points to the `cluster.local` domain.

### How can it be reproduced?

Install `linkerd-smi` helm chart as described in documentation and configure `clusterDomain` value to any other value than `cluster.local`:

```bash
helm repo add l5d-smi https://linkerd.github.io/linkerd-smi
helm install linkers-smi -n --create-namespace l5d-smi/linkerd-smi
```

Check logs from deployed `linkerd-smi` pod. Despite `clusterDomain` is other than `cluster.local` in the logs there is always this line:

```
INFO[0000] Using cluster domain: cluster.local
```

### Logs, error output, etc

n/a

### output of `linkerd check -o short`

```
linkerd-failover
----------------
‼ Linkerd extension command linkerd-failover exists
    exec: "linkerd-failover": executable file not found in $PATH
    see https://linkerd.io/2.13/checks/#extensions for hints

linkerd-smi
-----------
‼ Linkerd extension command linkerd-smi exists
    exec: "linkerd-smi": executable file not found in $PATH
    see https://linkerd.io/2.13/checks/#extensions for hints
```

### Environment

- LinkerD SMI chart version: `1.0.1`

### Possible solution

I found that the problem is caused by missing `Parse()` call on Go FlagSet structure here https://github.com/linkerd/linkerd-smi/blob/953a58bf3bca48dbc9afe71d94b2b1128b2bd042/adaptor/main.go#L22 I created workaround by using the following code after line 27

```golang
if len(os.Args) < 2 || os.Args[1] != "smi-adaptor" {
        fmt.Fprintln(cmd.Output(), "Usage: smi-adaptor <flags>")
	cmd.PrintDefaults()
	os.Exit(1)
}
cmd.Parse(os.Args[2:])
```

### Would you like to work on fixing this bug?

maybe

**Comment by hawkw** [comment]
Hmm, this does look like a bug --- it lookslike the SMI adaptor will never actually use any provided arguments.

Are you interested in opening a PR to merge your fix?

**Comment by DavidMcLaughlin** [comment]
Thanks for reporting, we'll take on the fix.

**Comment by adleong** [comment]
https://github.com/linkerd/linkerd-smi/pull/112

**Comment by adleong** [comment]
Fixed in https://github.com/linkerd/linkerd-smi/releases/tag/v0.2.4
