### ISSUE TITLE
Support for Custom Annotations on Linkerd-Viz Prometheus Deployment

### ISSUE THREAD

**Issue by cemenson** [linkerd/linkerd2#11365]
### What problem are you trying to solve?

It would be helpful to be able to specify additional custom Kubernetes annotations for the prometheus deployment within the linkerd-viz helm chart.

Currently, there is no direct way to do this (i.e. can't use `--set` or a `values.yaml`).

### How should the problem be solved?

Just add a small include on the annotations spec for the prometheus deployment with a default empty object on the `values.yaml` that can be overwritten.

### Any alternatives you've considered?

Only forking this repo to make the change.

### How would users interact with this feature?

By default nothing will change for users, but if they so wish they can specify additional annotations via a `--set` or `values.yaml` file.

### Would you like to work on this feature?

maybe

**Comment by hawkw** [comment]
@cemenson I think that if this approach is a conventional idiom for adding annotations to objects created by a Helm chart, we would accept a PR adding it!

**Comment by cemenson** [comment]
@hawkw I've opened a PR for this - just needs a couple of reviews?
