### ISSUE TITLE
proxy: When TLS is not used for a connection, report why

### ISSUE THREAD

**Issue by hawkw** [linkerd/linkerd2#1136]
When the proxy tries to open a connection using TLS but is not able to, the error should be reported to the control plane so that it can eventually be surfaced in the UIs.

**Comment by hawkw** [comment]
I think there's a need to do some design discussion around _how_ we want to do this. Off the top of my head, two obvious options include:

+ When we aren't able to use TLS for a connection, we set `tls` Prometheus label added in #1050 to a string describing the error that occurred.
+ We have a counter named `tls_errors` or something, labeled based on what type of error occurred, and we increment that on errors.

To me, the first option makes more sense, but may result in less granular error reporting. In particular, if we try to connect using TLS but aren't able to because we haven't loaded a TLS config, we don't really know whether that's because we have no certificate files at all, or because there was an error parsing or loading them, because the connection logic is fairly decoupled from the config loading logic.

These are definitely not the only ways to do this, although I suspect we will probably want to report these errors using the existing Prometheus telemetry pipeline. If anyone has any thoughts on what seems like the best way to do this, I'd be eager to hear them.

/cc @briansmith, @olix0r

**Comment by olix0r** [comment]
I think we should have a general connection errors counter, and it should have a labeling scheme that indicates TLS-related errors.

**Comment by hawkw** [comment]
> I think we should have a general connection errors counter, and it should have a labeling scheme that indicates TLS-related errors.

Agreed. I believe @briansmith and I came to a similar conclusion in the comments on an earlier PR.
