### ISSUE TITLE
Multicluster with flat network not working with Azure CNI

### ISSUE THREAD

**Issue by aaguilartablada** [linkerd/linkerd2#11429]
### What is the issue?

I have two AKS clusters on Azure (one in eu-west region and the other in eu-north region) configured with Azure CNI for networking. Each cluster is connected to one VNet with the next networking:

West: 10.2.0.0/16
North: 10.3.0.0/16

Both networks are configured with peering. This way, any POD located in west can talk to any POD located in north.

With Azure CNI, the PODs get IPs from VNet CIDR. That is good for flat network multi clustering. The point is that service CIDR is not overlapped with VNet CIDR. Service CIDR in both sides is 10.0.0.0/16.

When enabling multicluster without gateway, the Services from the remote side are correctly mirrored in the source cluster. The problem is that Endpoint is not synced, so trying to connect to the mirrored Service goes to nowhere. We receive a "Connection refused" as Service Cluster IP is not mapped to any endpoint in the other side.

### How can it be reproduced?

Create 2 AKS clusters with networking as I explained above and configure multiclustering.

### Logs, error output, etc

This is what I have in west after mirroring 3 Services:

```
kubectl -n emojivoto get svc
NAME            TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)             AGE
emoji-svc       ClusterIP   10.0.182.140   <none>        8080/TCP,8801/TCP   9h
emoji-svc-ne    ClusterIP   10.0.157.116   <none>        8080/TCP,8801/TCP   7h48m
voting-svc      ClusterIP   10.0.72.234    <none>        8080/TCP,8801/TCP   9h
voting-svc-ne   ClusterIP   10.0.27.8      <none>        8080/TCP,8801/TCP   8h
web-svc         ClusterIP   10.0.115.226   <none>        80/TCP              9h
web-svc-ne      ClusterIP   10.0.214.5     <none>        80/TCP              8h

kubectl -n emojivoto get endpoints
NAME            ENDPOINTS                         AGE
emoji-svc       10.2.0.115:8801,10.2.0.115:8080   9h
voting-svc      10.2.0.171:8801,10.2.0.171:8080   9h
web-svc         10.2.0.117:8080                   9h
```

This is what I expect:

```
kubectl -n emojivoto get svc
NAME            TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)             AGE
emoji-svc       ClusterIP   10.0.182.140   <none>        8080/TCP,8801/TCP   9h
emoji-svc-ne    ClusterIP   10.0.157.116   <none>        8080/TCP,8801/TCP   9h
voting-svc      ClusterIP   10.0.72.234    <none>        8080/TCP,8801/TCP   9h
voting-svc-ne   ClusterIP   10.0.27.8      <none>        8080/TCP,8801/TCP   9h
web-svc         ClusterIP   10.0.115.226   <none>        80/TCP              9h
web-svc-ne      ClusterIP   10.0.214.5     <none>        80/TCP              9h

kubectl -n emojivoto get endpoints
NAME            ENDPOINTS                         AGE
emoji-svc       10.2.0.115:8801,10.2.0.115:8080   9h
emoji-svc-ne    10.3.0.185:8801,10.3.0.185:8080   9h
voting-svc      10.2.0.171:8801,10.2.0.171:8080   9h
voting-svc-ne   10.3.0.157:8801,10.3.0.157:8080  9h
web-svc         10.2.0.117:8080                   9h
web-svc-ne      10.3.0.108:8080                  9h
```

### output of `linkerd check -o short`

NOTE: multicluster check fails because we have configured Azure RBAC to log in our clusters and it requires kubelogin. To make service-mirror working in my clusters I have an init-container to install kubelogin in the service-mirror container.

```
linkerd check -o short                                                                                                                                                                   ✔  
linkerd-identity
----------------
‼ issuer cert is valid for at least 60 days
    issuer certificate will expire on 2023-09-29T04:39:00Z
    see https://linkerd.io/2.14/checks/#l5d-identity-issuer-cert-not-expiring-soon for hints

linkerd-version
---------------
‼ cli is up-to-date
    is running version 2.14.0 but the latest stable version is 2.14.1
    see https://linkerd.io/2.14/checks/#l5d-version-cli for hints

control-plane-version
---------------------
‼ control plane is up-to-date
    is running version 2.14.0 but the latest stable version is 2.14.1
    see https://linkerd.io/2.14/checks/#l5d-version-control for hints

linkerd-control-plane-proxy
---------------------------
‼ control plane proxies are up-to-date
    some proxies are not running the current version:
	* linkerd-destination-59f4d7b68c-ljlpc (stable-2.14.0)
	* linkerd-destination-59f4d7b68c-qdzqn (stable-2.14.0)
	* linkerd-destination-59f4d7b68c-sg4hd (stable-2.14.0)
	* linkerd-identity-675947b5cd-85gd7 (stable-2.14.0)
	* linkerd-identity-675947b5cd-9hc6v (stable-2.14.0)
	* linkerd-identity-675947b5cd-qfvw5 (stable-2.14.0)
	* linkerd-proxy-injector-9dfd9d76b-2tccc (stable-2.14.0)
	* linkerd-proxy-injector-9dfd9d76b-4kkv4 (stable-2.14.0)
	* linkerd-proxy-injector-9dfd9d76b-gpjnl (stable-2.14.0)
	* metrics-api-6c45b557f4-k55lt (stable-2.14.0)
	* prometheus-75c8d67658-n99fp (stable-2.14.0)
	* tap-69fb5c5b99-4t5xh (stable-2.14.0)
	* tap-injector-886c66944-wxgxm (stable-2.14.0)
	* web-5c4947658f-k5ccn (stable-2.14.0)
    see https://linkerd.io/2.14/checks/#l5d-cp-proxy-version for hints

linkerd-ha-checks
-----------------
‼ pod injection disabled on kube-system
    kube-system namespace needs to have the label config.linkerd.io/admission-webhooks: disabled if injector webhook failure policy is Fail
    see https://linkerd.io/2.14/checks/#l5d-injection-disabled for hints

/ Running multicluster extension check
```

### Environment

- Kubernetes Version: 1.27.3
- Cluster Environment: AKS
- Host OS: AKSUbuntu-2204gen2containerd-202308.10.0
- Linkerd version: 2.14.0

### Possible solution

I am working in a solution. The idea is providing Link CRD a new parameter (syncRemoteEndpoints) to tell service-mirror to mirror the associated Endpoints of mirrored Services.

### Would you like to work on fixing this bug?

yes

**Comment by pbaranow** [comment]
I have run into similar issue on EKS. I checked logs of `linkerd-service-mirror` pod. When I create a service on cluster A and add a label `mirror.linkerd.io/exported: remote-discovery` to it, then service mirror on cluster B says:
```
level=debug msg="skipped processing endpoints object test-app/web: missing mirror.linkerd.io/exported label"
```
I don't know why, but it seems to me, that service mirror expects the label to exists not only on the service, but also on endpoints.

**Comment by aaguilartablada** [comment]
Hello @pbaranow ! 

I think that debug log is incorrect, because the Endpoint inherits Service labels, including mirror.linkerd.io/exported. Watching the code, it is actually skipping Endpoint because when creating a Link object for flat networks the Selector is not set, so this lines provokes returning a false and skipping endpoints:

https://github.com/linkerd/linkerd2/blob/main/multicluster/service-mirror/cluster_watcher.go#L893
https://github.com/linkerd/linkerd2/blob/main/multicluster/service-mirror/cluster_watcher.go#L1237

I already have a solution that works on AKS (I hope it also works on EKS). I am finishing the debug process and writing tests. I hope I can open a pull request soon.

**Comment by mullermateus** [comment]
Hey @aaguilartablada!

I'm also working on the new gatewayless approach of 2.14.0. 

It is expected that the mirrored service **does not** have any endpoints behind it.

The correct way to check is:

```
$ linkerd diagnostics endpoints emoji-svc-ne.emojivoto.svc.cluster.local:8080
```

This is covered [here](https://www.youtube.com/watch?v=25HwcuZ6f7Q) around 53m.

I hope it helps!

**Comment by aaguilartablada** [comment]
So, @mullermateus the point is that we still need the Gateway to perform inter-cluster service discovery although communication is performed pod to pod. Is that correct? If so, that's the reason our deployment doesn't work. We deployed linkerd-multicluster in our two clusters without the gateways.

I will try again with the gateways installed in the clusters.

**Comment by mullermateus** [comment]
Hey @aaguilartablada,

I don't think so. I redeployed everything without the Gateway (there's no gateway pod at all). Just by enabling the `remote-discovery` label it works fine (I'm running on EKS).

**Comment by aaguilartablada** [comment]
OK! It's working. The problem was that, when configuring the Link between clusters, we had the Kubernetes API firewall closed. So, Linkerd destination service failed to add the remote cluster to the ClusterStore and it never retried. After restarting Linkerd destination pods (once the firewall was open) the cluster was added to the ClusterStore correctly and it started working.

Maybe Linkerd destination should retry adding failed clusters.

I close this issue. Thanks so mucho @mullermateus.
