### ISSUE TITLE
ERROR: wrong number (0) of probe gateways for target cluster | 2.14.0

### ISSUE THREAD

**Issue by mullermateus** [linkerd/linkerd2#11428]
### What is the issue?

`linkerd multicluster check` is failing with the below error message:

```
× probe services able to communicate with all gateway mirrors
        wrong number (0) of probe gateways for target cluster <cluster name>
    see https://linkerd.io/2.14/checks/#l5d-multicluster-gateways-endpoints for hints
```

Even though we are using the "gatewayless" approach mentioned [here](https://linkerd.io/2.14/tasks/pod-to-pod-multicluster/).

I would expect `linkerd check` to take this new approach into account, or have a way to "ignore" this specific check. Since there are no gateways, this check will always fail.

### How can it be reproduced?

1. Upgrade all components to 2.14.0.
2. Create the setup the multicluster with `linkerd multicluster link --cluster-name <cluster> --gateway=false > <file>.yaml`.
3. Apply on the opposite cluster.
4. The multicluster communication works just fine! Although `linkerd check` fails.

### Logs, error output, etc

`linkerd multicluster check`:

```
× probe services able to communicate with all gateway mirrors
        wrong number (0) of probe gateways for target cluster <cluster name>
    see https://linkerd.io/2.14/checks/#l5d-multicluster-gateways-endpoints for hints
```

[This](https://github.com/linkerd/linkerd2/blob/a4bec904cc19d30441fb4ab591cff0a1edc66c20/multicluster/cmd/check.go#L562C1-L562C1) is the part of the code that implements the check, which is pretty much:

```
selector := metav1.ListOptions{LabelSelector: fmt.Sprintf("%s,%s=%s", k8s.MirroredGatewayLabel, k8s.RemoteClusterNameLabel, link.TargetClusterName)}
gatewayMirrors, err := hc.KubeAPIClient().CoreV1().Services(metav1.NamespaceAll).List(ctx, selector)
```

The `selector` are:
- mirror.linkerd.io/cluster-name
- mirror.linkerd.io/mirrored-gateway

So I do believe this check is looking for `Service` resources about the Gateway probes **probe-gateway-<cluster name>**.

Now the point is... I don't have a probe service, since there are no gateways.

```
kubectl get svc -n linkerd-multicluster
No resources found in linkerd-multicluster namespace.
```

Also they are on the same version:

```
linkerd version
Client version: stable-2.14.0
Server version: stable-2.14.0
```

### output of `linkerd check -o short`

```
linkerd-multicluster
--------------------
× probe services able to communicate with all gateway mirrors
        wrong number (0) of probe gateways for target cluster <cluster name>
    see https://linkerd.io/2.14/checks/#l5d-multicluster-gateways-endpoints for hints
```

### Environment

- Kubernetes version: `v1.25.12-eks-dcc023c`
- AWS EKS
- Linkerd version `2.14.0`
- Bottlerocket OS 1.15.0 (aws-k8s-1.25)

### Possible solution

I believe this check should not be executed with the new gatewayless approach, or we could have a way to bypass these checks.

### Additional context

We run some daily CronJobs to check our cluster health, and I can't move forward with the upgrade unless I get the proper checks working.

### Would you like to work on fixing this bug?

no

**Comment by DavidMcLaughlin** [comment]
Thanks for reporting this, we'll take a look at a fix.
