### ISSUE TITLE
helm dependencies for linkerd-crds cannot be built

### ISSUE THREAD

**Issue by gwynforthewyn** [linkerd/linkerd2#11455]
### What is the issue?

I typically use `skaffold render` with helm charts. This runs through several helm commands in a row, one of which is `helm dep build`.

If you run this command in the linkerd-crds helm chart directory, the command fails because the Chart.yaml references a directory "../partials". This directory is present in github, so if helm tests are run from the github repository then those tests will pass, but it is not available as a helm chart.

### How can it be reproduced?

Run these commands in a temporary directory:

```bash
helm repo add linkerd2 https://helm.linkerd.io/stable
helm pull linkerd2/linkerd-crds --version 1.8.0  --untar
cd linkerd-crds
helm dep build .
```

### Logs, error output, etc

 ; helm dep build .                                        
Error: directory ../partials not found

### output of `linkerd check -o short`

-

### Environment

-

### Possible solution

If the partials are required, then they could be packaged inside the helm chart instead of referenced using a relative path.

### Additional context

I'm happy to fix this if you folks can provide some guidance; it may be quicker for you to figure it out, though, I'm not sure. 

### Would you like to work on fixing this bug?

maybe

**Comment by alpeb** [comment]
The `partials` chart is already included under the `charts` directory, visible after you extract it via `helm pull` like you describe above. So if I understand correctly, running `helm dep build` is not required. I'm not familiar with `skaffold`, but there might be a way for it to skip that step?

**Comment by gwynforthewyn** [comment]
It looks like something was added for that in 2018 - https://github.com/GoogleContainerTools/skaffold/issues/1346

https://skaffold.dev/docs/renderers/helm/#skaffoldyaml-configuration lists it as a boolean in skaffold.yaml; I think that's perfectly fine.

Sorry for the false alarm! Thanks for the idea :  )
