### ISSUE TITLE
[jaeger/charts/linkerd-jaeger] Allow for High Availability

### ISSUE THREAD

**Issue by jseiser** [linkerd/linkerd2#11460]
### What problem are you trying to solve?

There doesnt seem to be a way in the helm chart to run more than 1 replica of the collector or injector.

### How should the problem be solved?

Allow setting replicaCount on injectors and collectors

### Any alternatives you've considered?

None

### How would users interact with this feature?

Modify there helm chart values to override default of 1.

### Would you like to work on this feature?

yes

**Comment by jseiser** [comment]
My only real concern is, if there is some reason these can NOT be H/A before I start to work on this.

**Comment by kflynn** [comment]
I am far from a Jaeger expert! but I think you'll also need to set up some kind of persistent storage across replicas for this to work, rather than just using in-memory storage? So this might be quite a bit more complex than you're thinking... 🙁
