### ISSUE TITLE
Add documentation for max supported k8s version

### ISSUE THREAD

**Issue by logicminds** [linkerd/linkerd2#11474]
### What problem are you trying to solve?

While the min supported k8s version is documented, the max supported version is not.  This can lead to a failed linkerd deployment when k8s is upgraded before linkerd. 

### How should the problem be solved?

A simple chart be kept up to date with the known working versions for the given release.

### Any alternatives you've considered?

asking chatgpt.

### How would users interact with this feature?

It would serve as documentation only and be found on the main doc site.

### Would you like to work on this feature?

yes

**Comment by logicminds** [comment]
Stable Linkerd Supported Kubernetes Version Matrix

| Linkerd Release  | 1.21  | 1.22  | 1.23  | 1.24  | 1.25 | 1.26 | 1.27 | 1.28 (Latest) | |
|---|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:
| 2.10.x  | ✅   | ✅   | ✅    | ✅    | 🔴   | 🔴   | 🔴   |  🔴  |   |
| 2.11.x  | ✅   | ✅   | ✅    | ✅    | 🔴   | 🔴   | 🔴   |  🔴  |   |
| 2.12.x  | ✅   | ✅   | ✅    | ✅    | 🔴   | 🔴   | 🔴   |  🔴  |   |
| 2.13.x | ✅   | ✅   | ✅    | ✅    | ✅     | ✅     | ✅     |  ✅    |   |
| 2.14.x  |✅   | ✅   | ✅    | ✅    | ✅     | ✅     | ✅     |  ✅    |   |
|   |   |   |   |   |   |   |   |   |   |
|   |   |   |   |   |   |   |   |   |   |

Please note this is unofficial data gathered by my experience.  Also,  2.10-2.11.x officially supported older versions of kubernetes but I didn't notate above since who runs those ancient version of kubernetes.

**Comment by wmorgan** [comment]
@kflynn can we get this into linkerd/website somewhere?
