### ISSUE TITLE
The pods of linkerd-cni DaemonSet stuck in CrashLoopBackOff because of permission issue when deployed in OpenShift cluster

### ISSUE THREAD

**Issue by jhw-git** [linkerd/linkerd2#11479]
### What is the issue?

The pods of linkerd-cni DaemonSet stuck in CrashLoopBackOff because of permission issue when deployed in OpenShift cluster 4.12:

```
NAME                READY   STATUS             RESTARTS      AGE
linkerd-cni-5cnfj   0/1     CrashLoopBackOff   2 (19s ago)   40s
linkerd-cni-8ztvr   0/1     CrashLoopBackOff   2 (17s ago)   40s
linkerd-cni-g5g5m   0/1     CrashLoopBackOff   2 (20s ago)   40s
linkerd-cni-qmlfr   0/1     CrashLoopBackOff   2 (19s ago)   40s
linkerd-cni-tsw52   0/1     CrashLoopBackOff   2 (18s ago)   40s
linkerd-cni-vzrcc   0/1     CrashLoopBackOff   2 (17s ago)   40s
```

### How can it be reproduced?

Follow the step by step guide in this link 
https://buoyant.io/blog/running-linkerd-on-openshift-4

You will encountered this problem in the Step **Deploy the Linkerd CNI Plugin**

### Logs, error output, etc

The log of the pod:
`oc logs linkerd-cni-5cnfj`

```
cp: can't create '/host/var/lib/cni/bin/linkerd-cni': Permission denied
[2023-10-12 10:09:05] Failed to copy /opt/cni/bin/linkerd-cni to /host/var/lib/cni/bin.
```

### output of `linkerd check -o short`

N/A

### Environment

OpenShift 4.12

_oc version_ :
Client Version: 4.12.22
Kustomize Version: v4.5.7
Server Version: 4.12.22
Kubernetes Version: v1.25.10+8c21020

### Would you like to work on fixing this bug?

None

**Comment by rumeshmadhusanka** [comment]
Linkerd 2.14.1 works for me on OpenShift after setting 
```
destCNIBinDir: "/var/lib/cni/bin"
destCNINetDir: "/etc/kubernetes/cni/net.d"
privileged: true 
```
on the CNI chart and 
Setting 
```
cniEnabled: true
networkValidator:
  enableSecurityContext: false
```
on the control plane chart

**Comment by kflynn** [comment]
@jhw-git, does @rumeshmadhusanka's suggestion work for you?
