### ISSUE TITLE
First-Class Support for Argo Rollouts in Linkerd Viz

### ISSUE THREAD

**Issue by Laakso** [linkerd/linkerd2#11489]
### What problem are you trying to solve?

My challenge comes down to how Linkerd handles Argo Rollouts. Currently, Linkerd doesn’t treat Argo Rollouts as a distinct entity; it just considers them as part of the broader ReplicaSets category. When I look at my rollouts in Linkerd Viz, it doesn’t give me a dedicated, clear-cut view. Instead, what bugs me is that it lists all the old ReplicaSets (now inactive and greyed out) from past rollouts right alongside my active ones. It clutters the view and distracts from what’s important: understanding my active rollouts.

### How should the problem be solved?

I believe what we need is for Linkerd Viz to recognize and support Argo Rollouts as a first-class citizen. This means:

Identifying Argo Rollout objects specifically, giving them their own space apart from the regular ReplicaSets.

### Any alternatives you've considered?

I've been using a ReplicaSet view

### How would users interact with this feature?

In Linkerd Viz, I’m picturing a separate section for Argo Rollouts, distinct from other services or entities. 
For those of us using the command line, a specific command would make life easier, something like:

`linkerd viz stat argo-rollouts -n <namespace>`

### Would you like to work on this feature?

maybe

**Comment by kflynn** [comment]
Thanks @Laakso! If you might be interested in working on this, what support could we give you?

**Comment by kflynn** [comment]
(A further update: this raises some interesting design questions around the Viz UX, and may require getting in touch with some of the Rollouts folks.)
