### ISSUE TITLE
[DOCS] Clarify Installation Instructions for Linkerd CLI

### ISSUE THREAD

**Issue by AugustasV** [linkerd/linkerd2#11517]
### What problem are you trying to solve?

The installation instructions provided in [Step 1](https://linkerd.io/2.14/getting-started/#step-1-install-the-cli) of the Linkerd documentation could benefit from additional clarity. Specifically, the documentation should include a step to add the Linkerd CLI to the system's PATH for easy access.

### How should the problem be solved?
To improve the documentation, please consider adding the following instruction:

As described in forum https://linkerd.buoyant.io/t/linkerd-getting-started-guide/55 please add exporting path step

```
Be sure to follow the instructions to add it to your path:
export PATH=$HOME/.linkerd2/bin:$PATH
```

### Any alternatives you've considered?

None at the moment. The proposed solution is a straightforward.

### Would you like to work on this feature?

yes

**Comment by kflynn** [comment]
@AugustasV Ouch, thanks for calling this out! If you'd like to work on this, a PR into https://github.com/linkerd/website would be ideal -- I think `linkerd.io/content/2.14/getting-started/_index.md` is the place to start.

**Comment by AugustasV** [comment]
Sure @kflynn , PR created https://github.com/linkerd/website/pull/1703
Closing this issue.
