### ISSUE TITLE
Destination Controller Having Errors When Destination Is Unmeshed Pod using Opaque Ports

### ISSUE THREAD

**Issue by DavidMcLaughlin** [linkerd/linkerd2#11555]
### What is the issue?

We made a change to the podwatcher to improve how we handle pods using hostPort. In this code refactor, we accidentally changed the logic that handles opaque ports and unmeshed pods. Users are reporting this issue after upgrading to 2.14.2, where the hostPort refactor was merged. 

### How can it be reproduced?

Send direct traffic to an unmeshed pod that has a port that is registered as opaque. 

### Logs, error output, etc

N/A

### output of `linkerd check -o short`

N/A

### Environment

Linkerd Version: 2.14.2

### Would you like to work on fixing this bug?

None

**Comment by alpeb** [comment]
Fixed in #11556

**Comment by DavidMcLaughlin** [comment]
Resolved in 2.14.3.
