### ISSUE TITLE
Circuit Breaking not working when service are linked with a pass through service

### ISSUE THREAD

**Issue by Nbarola** [linkerd/linkerd2#11579]
### What is the issue?

We have a few services running that communicate with one another. For example, service A talks to Service B and Service C talks to Service C. We have enabled circuit-breaking at Service B and Service C. Then to test the circuit-breaking we used fault Injection of linkerd to return the 5xx errors. We created the traffic split on Service C with the error injector backend and did the split of 100 to the error injector. So all the responses from service C were 5xx. When the circuit breaker was tripped and the circuit was closed we could see the circuit closed message in proxy logs of service B and on the linkerd dashboard, we could confirm that the requests stopped going to the error injector backend. The service B is a pass-through service (it returns the same error it received to the service A). So eventually the circuit breaker should get closed at the service A as well and it should stop sending the requests to the service B automatically. 

### How can it be reproduced?

Three services would be required that are talking in the same way as described above. Then testing the circuit breaking by introducing the fault injection.

### Logs, error output, etc

In case the circuit breaker gets closed we observe this service unavailable errors

```
[747762.424577s]  INFO ThreadId(01) outbound:proxy{addr=10.100.87.238:8080}:service{ns=circuit-breaking-demo name=error-injector port=8080}:endpoint{addr=100.64.1.74:8080}: linkerd_app_outbound::http::breaker::consecutive_failures: Consecutive failure-accrual breaker closed
[747768.431939s]  WARN ThreadId(01) outbound:proxy{addr=10.100.87.238:8080}: linkerd_stack::failfast: Service entering failfast after 3s
[747768.432018s]  INFO ThreadId(01) outbound:proxy{addr=10.100.87.238:8080}:rescue{client.addr=100.64.18.227:60656}: linkerd_app_core::errors::respond: HTTP/1.1 request failed error=logical service 10.100.87.238:8080: service in fail-fast error.sources=[service in fail-fast]
[747768.433822s]  INFO ThreadId(01) outbound:proxy{addr=10.100.87.238:8080}:rescue{client.addr=100.64.18.227:60666}: linkerd_app_core::errors::respond: HTTP/1.1 request failed error=logical service 10.100.87.238:8080: service unavailable error.sources=[service unavailable]
[747768.524453s]  INFO ThreadId(01) outbound:proxy{addr=10.100.87.238:8080}:rescue{client.addr=100.64.18.227:60674}: linkerd_app_core::errors::respond: HTTP/1.1 request failed error=logical service 10.100.87.238:8080: service unavailable error.sources=[service unavailable]

```

### output of `linkerd check -o short`

```
linkerd-version
---------------
‼ cli is up-to-date
    is running version 2.13.6 but the latest stable version is 2.14.2
    see https://linkerd.io/2.13/checks/#l5d-version-cli for hints

control-plane-version
---------------------
‼ control plane is up-to-date
    is running version 2.13.6 but the latest stable version is 2.14.2
    see https://linkerd.io/2.13/checks/#l5d-version-control for hints

linkerd-control-plane-proxy
---------------------------
‼ control plane proxies are up-to-date
    some proxies are not running the current version:
	* linkerd-destination-d7b9f5cf9-2v24g (stable-2.13.6)
	* linkerd-destination-d7b9f5cf9-b6dpm (stable-2.13.6)
	* linkerd-destination-d7b9f5cf9-tpf76 (stable-2.13.6)
	* linkerd-identity-745c659c7b-2z265 (stable-2.13.6)
	* linkerd-identity-745c659c7b-nljc4 (stable-2.13.6)
	* linkerd-identity-745c659c7b-pj4v6 (stable-2.13.6)
	* linkerd-proxy-injector-5b757bc787-66qqj (stable-2.13.6)
	* linkerd-proxy-injector-5b757bc787-hpx52 (stable-2.13.6)
	* linkerd-proxy-injector-5b757bc787-xnkpg (stable-2.13.6)
    see https://linkerd.io/2.13/checks/#l5d-cp-proxy-version for hints

linkerd-viz
-----------
‼ viz extension proxies are up-to-date
    some proxies are not running the current version:
	* metrics-api-746ccdc44b-8j5nr (stable-2.13.6)
	* metrics-api-746ccdc44b-cn8bg (stable-2.13.6)
	* metrics-api-746ccdc44b-v64gn (stable-2.13.6)
	* prometheus-7b47989794-z7bgr (stable-2.13.6)
	* tap-66dc4d6ccf-8pj7x (stable-2.13.6)
	* tap-66dc4d6ccf-dlgpg (stable-2.13.6)
	* tap-66dc4d6ccf-v72c7 (stable-2.13.6)
	* tap-injector-ffdf8c777-qlnzc (stable-2.13.6)
	* web-75d5ff89b6-72z6n (stable-2.13.6)
	* web-75d5ff89b6-htcll (stable-2.13.6)
	* web-75d5ff89b6-pkv7b (stable-2.13.6)
    see https://linkerd.io/2.13/checks/#l5d-viz-proxy-cp-version for hints

Status check results are √
```

### Environment

- EKS 1.24
- OS - linux
- Linkerd version - 2.13.6

### Would you like to work on fixing this bug?

None

**Comment by DavidMcLaughlin** [comment]
Can you share configuration that helps us reproduce this? 

Do you have metrics for Service A when they get into this state? You can get these by running `linkerd diagnostics proxy-metrics -n $namespace $pod-name`

**Comment by Nbarola** [comment]
Hey @DavidMcLaughlin I have the metrics for Service A when this scenario is in place. I am attaching the metrics. Metrics are huge, do you need any specific metrics, let me know and I can filter them out and share them with you separately.
[alef-graphql-micrographs-trimed.txt](https://github.com/linkerd/linkerd2/files/13488038/alef-graphql-micrographs-trimed.txt)

**Comment by Nbarola** [comment]
- Yes, the aggregator keeps sending the requests to service 1.
- So, for testing purpose, we have only a single endpoint in our case for both service 1 and service 2. The Service 2 is sending the 500 and the circuit breaker is working as expected. The Service 1 receives the 500 errors and it forwards the same to the aggregator. But the next circuit breaker is not working as expected and the aggregator keeps sending the requests to the service 1.
