### ISSUE TITLE
Provide option to disable `namespace-metadata` Job

### ISSUE THREAD

**Issue by alpeb** [linkerd/linkerd2#11585]
Constrained environments don't provide edit-level privileges for namespaces, which the `namespace-metadata` jobs in the extensions require (for helm-based installations only). We should provide an option (`values.yaml` entry) to skip those jobs, while providing instructions about the metadata that should be applied through other means to extensions namespaces.

**Comment by MeenuyD** [comment]
Hello @alpeb I would like to work on this issue can you please assign it to me and i am new t this can you please tell me where changes needs to be done

**Comment by alpeb** [comment]
Thanks @MeenuyD. Please take a look at the chart under `./charts/linkerd-control-plane`. There you'll see how to apply helm templating functions to enable/disable features.

**Comment by shinigami-777** [comment]
Hi @alpeb I would like to work on this issue .

**Comment by alpeb** [comment]
Hi @shinigami-777, thanks. Please proceed, as the PR referred above seems to have become stale.

**Comment by shinigami-777** [comment]
Hello @alpeb . Can you please point me the charts file where the helm templating functions need to be applied as I am new to this.

**Comment by alpeb** [comment]
> Hello @alpeb . Can you please point me the charts file where the helm templating functions need to be applied as I am new to this.

You'll find the `namespace-metadata.yaml` and `namespace-metadata-rbac.yaml` files under the directories `viz/charts/linkerd-viz/templates`, `multicluster/charts/linkerd-multicluster/templates` and `jaeger/charts/linkerd-jaeger/templates`.

**Comment by shinigami-777** [comment]
hi @alpeb . Can you please guide me a bit on the testing part. I don't have any prior experience.

**Comment by alpeb** [comment]
> hi @alpeb . Can you please guide me a bit on the testing part. I don't have any prior experience.

I mean just running linkerd using your new setting and making sure it has the intended consequence.

**Comment by lolhax1337** [comment]
Hi, any news?

**Comment by kflynn** [comment]
@lolhax1337 We're looking to see if anyone has bandwidth for testing – interested? 🙂

**Comment by lolhax1337** [comment]
Is there any helm chart version with these changes?
