### ISSUE TITLE
runAsRoot param fails the injection

### ISSUE THREAD

**Issue by sneerin** [linkerd/linkerd2#11615]
### What is the issue?

after installation, any pod injection fails with error provided. 

### How can it be reproduced?

install linkerd, add --set proxyInit.runAsRoot=true to helm params . 

### Logs, error output, etc

103s        Warning   FailedCreate        replicaset/<pod-name>75bbb6889b              Error creating: admission webhook "linkerd-proxy-injector.linkerd.io" denied the request: failed to unmarshal JSON from: /var/run/linkerd/config/values: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go struct field ProxyInit.proxyInit.runAsRoot of type bool

### output of `linkerd check -o short`

linkerd-existence
-----------------
× 'linkerd-config' config map exists
    error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go struct field ProxyInit.proxyInit.runAsRoot of type bool
    see https://linkerd.io/2.14/checks/#l5d-existence-linkerd-config for hints

### Environment

- kuberentes Version: Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.12", GitCommit:"b058e1760c79f46a834ba59bd7a3486ecf28237d", GitTreeState:"clean", BuildDate:"2022-07-13T14:53:39Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
- linkerd version : name: linkerd-control-plane
    version: 1.16.4

### Would you like to work on fixing this bug?

maybe

**Comment by kflynn** [comment]
I just tried this in a local k3d cluster and it works -- of course, that's Kubernetes 1.26. Are you able to try this with something newer than 1.22? Can you tell me more about what kind of cluster this is?

**Comment by kflynn** [comment]
@sneerin See above – any more information you can give here? 🙂

**Comment by kflynn** [comment]
@sneerin Happy new year! Still looking for more information, if you can provide any? 🙂
