### ISSUE TITLE
Linkerd is altering status on HTTPRoutes it doesn't own

### ISSUE THREAD

**Issue by quyenhoang96** [linkerd/linkerd2#11659]
### What is the issue?

When I config Envoy-Gateway https://github.com/envoyproxy/gateway.
Then I apply HTTPRoute, the control plan of linkerd watch resource of envoy-gateway, and change it. So it make the envoy-gateway error. Help me how to fix it.

### How can it be reproduced?

When I config Envoy-Gateway https://github.com/envoyproxy/gateway.
Then I apply HTTPRoute, the control plan of linkerd watch resource of envoy-gateway, and change it. So it make the envoy-gateway error. Help me how to fix it.

### Logs, error output, etc

When I config Envoy-Gateway https://github.com/envoyproxy/gateway.
Then I apply HTTPRoute, the control plan of linkerd watch resource of envoy-gateway, and change it. So it make the envoy-gateway error. Help me how to fix it.

### output of `linkerd check -o short`

  - name: linkerd-crds
    repository: "https://helm.linkerd.io/stable"
    version: 1.8.0
  - name: linkerd-control-plane
    repository: https://helm.linkerd.io/stable
    version: 1.16.6

### Environment

  - name: linkerd-crds
    repository: "https://helm.linkerd.io/stable"
    version: 1.8.0
  - name: linkerd-control-plane
    repository: https://helm.linkerd.io/stable
    version: 1.16.6

### Additional context

When I config Envoy-Gateway https://github.com/envoyproxy/gateway.
Then I apply HTTPRoute, the control plan of linkerd watch resource of envoy-gateway, and change it. So it make the envoy-gateway error. Help me how to fix it.

### Would you like to work on fixing this bug?

yes

**Comment by kflynn** [comment]
I'm going to resolve this as a dup of https://github.com/envoyproxy/gateway/issues/2248 – I'm involved with Envoy Gateway, too, so I think we can track it in just the one project. 🙂

**Comment by kflynn** [comment]
Part of this fix is also going to be to add conformance tests for mesh/gateway-controller interaction, as tracked in https://github.com/kubernetes-sigs/gateway-api/issues/2630.)

**Comment by quyenhoang96** [comment]
Hi @kflynn
 Thank you for your assistance. Currently we are deploying linkerd + envoy-gateway for production. Can you push this bug to priority?
