### ISSUE TITLE
Retries against the same failing pod

### ISSUE THREAD

**Issue by Hexcles** [linkerd/linkerd2#11669]
### What is the issue?

We recently enabled retries in service profiles, specifically we retry a custom status code, which is returned during load shedding / circuit breaking -- our implementation would very quickly return this status code under these scenarios.

We observed that linkerd would keep retrying against the very same failing pod, seemingly because the latency was very low, while there were 2 other healthy pods.

### How can it be reproduced?

* Create a service profile with retries
* Run 3 pods for this service
* Have one pod return 500 immediately, and the other pods return 200 after e.g. 100ms
* Linkerd would then prefer to retry against the failing pod

### Logs, error output, etc

N/A

### output of `linkerd check -o short`

All green

### Environment

- Linkerd 2.14.5
- AWS EKS 1.24
- Linux hosts

### Would you like to work on fixing this bug?

None

**Comment by kflynn** [comment]
This is pretty much exactly what circuit breakers are meant to solve. We support circuit breakers as of Linkerd 2.13 -- have you checked those out? There's [a blog post](https://linkerd.io/2023/06/13/dynamic-request-routing-circuit-breaking/) with more information...

**Comment by Hexcles** [comment]
Hmm is it? I thought circuit breaker was a service-level concept and would
be useful to stop sending traffic to the whole service (or route), but here
we are talking about a single misbehaving pod. I'd expect linkerd's retry &
load balancing mechanisms to be aware of failures; otherwise, the behaviour
described in the doc <https://linkerd.io/2.14/features/load-balancing/>
would prefer sending traffic to a failing pod as long as it's responding
(or rather, failing) quickly.

**Comment by kflynn** [comment]
Yup -- circuit breakers work on the backend Pods, not the service as a whole. If you have one failing Pod, Linkerd will cut that single Pod out and use the others.

**Comment by kflynn** [comment]
🤦‍♂️ Yeah... that's a current incompatibility that we're working on fixing right now. 🙁
