### ISSUE TITLE
Linkerd route level RPS not coming up

### ISSUE THREAD

**Issue by mayank-ag-dev** [linkerd/linkerd2#11671]
### What is the issue?

We have deployed Linkerd stable v2.14.0 on GKE v1.24. We configured a service profile for an application, and the routes were getting added, but we could not see the RPS.

### How can it be reproduced?

GKE v1.24
Linkerd stable-v2.14.0

### Logs, error output, etc

ROUTE           SERVICE   SUCCESS   RPS   LATENCY_P50   LATENCY_P95   LATENCY_P99
[DEFAULT]         svc1                -     -             -             -             -
healthz               svc1                   -     -             -             -             -
version                svc1                   -     -             -             -             -

### output of `linkerd check -o short`

linkerd-version
---------------
‼ cli is up-to-date
    is running version 2.14.0 but the latest stable version is 2.14.5
    see https://linkerd.io/2.14/checks/#l5d-version-cli for hints

control-plane-version
---------------------
‼ control plane is up-to-date
    is running version 2.14.0 but the latest stable version is 2.14.5
    see https://linkerd.io/2.14/checks/#l5d-version-control for hints

linkerd-control-plane-proxy
---------------------------
‼ control plane proxies are up-to-date
    some proxies are not running the current version:
	* linkerd-destination-d995f46dc-gcvwq (stable-2.14.0)
	* linkerd-identity-86c6f76f6c-p6k52 (stable-2.14.0)
	* linkerd-proxy-injector-6fc56bcd48-2x9rs (stable-2.14.0)
    see https://linkerd.io/2.14/checks/#l5d-cp-proxy-version for hints

linkerd-viz
-----------
‼ linkerd-viz pods are injected
    could not find proxy container for metrics-api-f46599848-6j2lz pod
    see https://linkerd.io/2.14/checks/#l5d-viz-pods-injection for hints
‼ viz extension pods are running
    container "linkerd-proxy" in pod "metrics-api-f46599848-6j2lz" is not ready
    see https://linkerd.io/2.14/checks/#l5d-viz-pods-running for hints
‼ viz extension proxies are healthy
    no "linkerd-proxy" containers found in the "linkerd" namespace
    see https://linkerd.io/2.14/checks/#l5d-viz-proxy-healthy for hints

Status check results are √

### Environment

GKE v1.24
Linkerd stable-2.14.0

### Would you like to work on fixing this bug?

yes

**Comment by kflynn** [comment]
Hey @mayank-ag-dev! Those errors from `linkerd check` are very concerning – they look an awful lot like `linkerd-viz` isn't set up correctly. Maybe uninstall and reinstall it?

Assuming that you clear the Viz errors and it's still not working, we'd like to see the Service and ServiceProfile for at least one of these workloads... thanks!

**Comment by mayank-ag-dev** [comment]
Hey @kflynn I resolved the errors for linkerd viz sharing the service and service profile snippet
`
apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  name: podinfo-svc.podinfo.svc.cluster.local
  namespace: podinfo
spec:
  # A service profile defines a list of routes.  Linkerd can aggregate metrics
  # like request volume, latency, and success rate by route.
  routes:
    - name: health-check
      condition:
        method: GET
        pathRegex: /healthz

    - name: version
      condition:
        method: GET
        pathRegex: /version
`
`
apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: podinfo-svc
    namespace: podinfo
  spec:
    ports:
    - name: http
      port: 9898
      protocol: TCP
      targetPort: http
    - name: grpc
      port: 9999
      protocol: TCP
      targetPort: grpc
    selector:
      app: podinfo
    type: ClusterIP
    `

**Comment by mayank-ag-dev** [comment]
Yes

**Comment by kflynn** [comment]
@mayank-ag-dev I think the biggest question here is whether you're using ServiceProfiles or HTTPRoutes. For per-route metrics at the moment, you need to be using ServiceProfiles.

**Comment by mayank-ag-dev** [comment]
@kflynn We are using serviceProfiles for HTTPRoutes.

**Comment by kflynn** [comment]
@mayank-ag-dev 🤦‍♂️ So sorry to ask you to confirm ServiceProfiles when you'd already posted a ServiceProfile! Let me poke a little more into this.

**Comment by akashsethiya** [comment]
@kflynn Any update on this? 
We have major impact on observability cz of this.

**Comment by kflynn** [comment]
So far I haven't managed to reproduce this. 🙁 Are you on [our Slack](https://slack.linkerd.io)? If so, I'd like to connect there and try a few things with you.
