### ISSUE TITLE
linkerd-viz tap apiservice option for hostNetwork: true

### ISSUE THREAD

**Issue by bennydeep** [linkerd/linkerd2#11698]
### What problem are you trying to solve?

With custom cni
```
E1205 09:13:52.814803    6521 memcache.go:287] couldn't get resource list for tap.linkerd.io/v1alpha1: the server is currently unable to handle the request
```

### How should the problem be solved?

```
cat << EOF > /tmp/patch
spec:
  template:
    spec:
      hostNetwork: true
EOF

kubectl patch deployment tap -n linkerd-viz --patch-file /tmp/patch 
```
so an option for `hostNetwork: true` in the helm chart would be nice 

### Any alternatives you've considered?

none

### Would you like to work on this feature?

None

**Comment by gabbler97** [comment]
I have a similar environment.
It would be good to have a variable for this in the values.yaml.

**Comment by olix0r** [comment]
Linkerd doesn't work on pods that use host networking. Can you explain what you're hoping to accomplish with this configuration?

**Comment by alpeb** [comment]
With host networking the tap workload won't be injected, and it requires to be injected in order to work. If you try using `linkerd viz tap` after your patch you should confirm it's not returning anything.

**Comment by kflynn** [comment]
I'm going to go ahead and close this, since `tap` _must_ be injected to function, and that's not possible when using host networking.
