### ISSUE TITLE
tap src/dst resolution

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#1170]
## Proposal

I would like to be able to refer directly to both the src and dst for a specific tap. The IP addresses seem like good information, but I'd also like to have the resources listed (for querying and cross-linking). 

```
req id=0:1901 src=10.4.1.23:57424 dst=10.4.0.23:80 :method=GET :authority=web-svc.emojivoto:80 :path=/api/vote secured=no src_resource=pod/foobar dst_resource=authority/web-svc.emojivoto:80
rsp id=0:1901 src=10.4.1.23:57424 dst=10.4.0.23:80 :status=200 latency=2782µs secured=no src_resource=pod/foobar dst_resource=authority/web-svc.emojivoto:80
end id=0:1901 src=10.4.1.23:57424 dst=10.4.0.23:80 duration=0µs response-length=0B secured=no src_resource=pod/foobar dst_resource=authority/web-svc.emojivoto:80
```

The only two resources that seem valid right now are pod/authority, but maybe there would be some more in the future?

## Now

```
req id=0:1901 src=10.4.1.23:57424 dst=10.4.0.23:80 :method=GET :authority=web-svc.emojivoto:80 :path=/api/vote secured=no
rsp id=0:1901 src=10.4.1.23:57424 dst=10.4.0.23:80 :status=200 latency=2782µs secured=no
end id=0:1901 src=10.4.1.23:57424 dst=10.4.0.23:80 duration=0µs response-length=0B secured=no
```

**Comment by grampelberg** [comment]
@olix0r you've mentioned other metadata we can get and are missing in the past. Mind doing a brain dump?

**Comment by olix0r** [comment]
We should be able to have equivalents for all metadata items that we [have on the dst side](https://github.com/linkerd/linkerd2/blob/master/doc/proxy-metrics.md#outbound-labels) without the notable exception of dst_service (traffic cannot originate from a service, it can only target a service).

**Comment by hawkw** [comment]
It looks like the `TapEvent` proto already has fields for `source_meta` and `destination_meta`. The proxy already populates the `destination_meta` map with all the labels it received from the Destination service (`source_meta` only gets the connection's TLS status, which is all the proxy knows about the source).

Per a discussion with @adleong, we thought that the tap server ought to hydrate the source metadata by looking up the source IP in the Kubernetes API.

**Comment by klingerf** [comment]
@hawkw has implemented this in #1437 and the PR looks good to me, but I'm hesitant to make the tap output lines longer than they already are by adding the `dst_resource` and `src_resource` fields.

Since every output line already includes `src` and `dst` fields, my preference would be to toggle what's displayed in those fields via a command-line flag. I'm totally open to suggestion about what it should be called, but something like this could work:

```
      --display string        Change the display format for src and dst resources; one of: addrs, pods, owners (default: "addrs")
```

Prints addresses by default:

```
$ linkerd tap -n emojivoto deploy/voting
req id=0:80 proxy=in  src=10.1.0.97:38536 dst=10.1.0.96:8080 tls=disabled :method=POST :authority=voting-svc.emojivoto:8080 :path=/emojivoto.v1.VotingService/VoteDoughnut
rsp id=0:80 proxy=in  src=10.1.0.97:38536 dst=10.1.0.96:8080 tls=disabled :status=200 latency=1389µs
end id=0:80 proxy=in  src=10.1.0.97:38536 dst=10.1.0.96:8080 tls=disabled grpc-status=OK duration=58µs response-length=5B
```

Prints pods with `--display=pods`:

```
$ linkerd tap -n emojivoto deploy/voting --display pods
req id=0:107 proxy=in  src=web-5dfc48d986-2k4p5 dst=voting-6b4fdf748-mswkc tls=disabled :method=POST :authority=voting-svc.emojivoto:8080 :path=/emojivoto.v1.VotingService/VoteCloudWithRain
rsp id=0:107 proxy=in  src=web-5dfc48d986-2k4p5 dst=voting-6b4fdf748-mswkc tls=disabled :status=200 latency=1093µs
end id=0:107 proxy=in  src=web-5dfc48d986-2k4p5 dst=voting-6b4fdf748-mswkc tls=disabled grpc-status=OK duration=214µs response-length=5B
```

Or prints pod owners with `--display=owners`:

```
$ linkerd tap -n emojivoto deploy/voting --display owners
req id=0:196 proxy=in  src=deploy/web dst=deploy/voting tls=disabled :method=POST :authority=voting-svc.emojivoto:8080 :path=/emojivoto.v1.VotingService/VoteBalloon
rsp id=0:196 proxy=in  src=deploy/web dst=deploy/voting tls=disabled :status=200 latency=2073µs
end id=0:196 proxy=in  src=deploy/web dst=deploy/voting tls=disabled grpc-status=OK duration=64µs response-length=5B
```

How do folks feel about this approach?

**Comment by hawkw** [comment]
@klingerf I'm open to something like that, modulo the fact that for some requests or responses, we may only be able to display addrs regardless of what the user requested)

**Comment by olix0r** [comment]
FWIW, I'm not a fan of the "owners" syntax, especially in that it omits namespaces, which are vital to understanding the context of the src or dst

**Comment by klingerf** [comment]
Ok, thanks for all of the input. This sounds pretty good to me. It seems like the "pods" display may also need to include `src_ns` and `dst_ns` fields, to distinguish where the pods are running.

I don't think that hiding replicasets is really an issue for the "owners" display. Ownership in Kubernetes is a tree model, and our code to determine the owner walks to the root of the tree. I think in almost all use cases this is the correct behavior -- we don't need to know if there are intermediary owners of any given object. In fact, we already use this notion of ownership in other places in the project, such as when we construct TLS identities, and when we populate the list of deployments on the service mesh overview page in the web UI.

I agree that we should add `src_ns` and `dst_ns` fields as appropriate. Here are updated examples to demonstrate that:

```
$ linkerd tap -n emojivoto deploy/voting
req id=0:80 proxy=in  src=10.1.0.97:38536 dst=10.1.0.96:8080 tls=disabled :method=POST :authority=voting-svc.emojivoto:8080 :path=/emojivoto.v1.VotingService/VoteDoughnut
```

```
$ linkerd tap -n emojivoto deploy/voting --display pods
req id=0:107 proxy=in  src=web-5dfc48d986-2k4p5 src_ns=emojivoto dst=voting-6b4fdf748-mswkc dst_ns=emojivoto tls=disabled :method=POST :authority=voting-svc.emojivoto:8080 :path=/emojivoto.v1.VotingService/VoteCloudWithRain
```

```
$ linkerd tap -n emojivoto deploy/voting --display owners
req id=0:196 proxy=in  src=deploy/web src_ns=emojivoto dst=deploy/voting dst_ns=emojivoto tls=disabled :method=POST :authority=voting-svc.emojivoto:8080 :path=/emojivoto.v1.VotingService/VoteBalloon
```

**Comment by grampelberg** [comment]
It feels a little weird to have fields that can have multiple types of data (I might be overly "purist" on that). What about having default fields for tap that you can add/remove if you want (I'm thinking the difference between `kubectl get po` and `kubectl get po --o wide`? That way we can always show the IP address as well as the k8s resource name (and I, as a user can pick which I'd like to see).

Either way I'm behind @klingerf for the near term.

**Comment by klingerf** [comment]
Great. @hawkw, would you want to apply the changes described here to #1437? I also know that you've got a lot on your plate, so I'd be happy to open a different PR to enact this change if that works better for you.

**Comment by hawkw** [comment]
It occurs to me that if we're now only ever going to display addresses in the `src`/`dst` columns, we could start padding them to the maximum number of characters in an (IPv4) address, 21 (12 characters for each octet + 3 characters for the dots; one character for the colon, and 5 characters (the max number of digits in an unsigned 16-bit int) for the port). That would give us a couple more columns that are always aligned :)
