### ISSUE TITLE
linkerd-control-plane in stable-2.14.6 could not deploy with linkerdVersion value override

### ISSUE THREAD

**Issue by jdinsel-xealth** [linkerd/linkerd2#11721]
### What is the issue?

We pulled the helm chart for linkerd-control-plane v1.16.7 (part of the stable-2.14.6 release). By default, it rendered charts that specified annotations as  `linkerd.io/created-by: linkerd/helm stable-2.14.5` and referenced image tags of `stable-2.14.5`

### How can it be reproduced?

Download the helm charts and use `helm template` to create an upstream manifest. Read or deploy these charts to see the incorrect version of the pods come online. Note that changing the linkerdVersion value in the linkerd-config configMap did not  have a positive improvement on the initial pod startup.

### Logs, error output, etc

All linkerd-control-plane pods referenced stable-2.14.5 and would crash on startup due to the new arguments for `- -kube-apiclient-qps=100 -kube-apiclient-burst=200` not being available.

### output of `linkerd check -o short`

NA now that we're running with the patch I described.

### Environment

Kubernetes version 1.28, AWS EKS

### Possible solution

I manually set the linkerd-control-plane linkerdVersion value to stable-2.14.6 and rebuilt the helm template.

### Would you like to work on fixing this bug?

None

**Comment by joebowbeer** [comment]
The published linkerdVersion is suppose to get set in

https://github.com/linkerd/linkerd2/blob/main/bin/helm-build#L5

**Comment by jdinsel-xealth** [comment]
I think there may be a bug or error in the steps I followed. I am closing this after double checking that I cannot reproduce it.
