### ISSUE TITLE
proxy: high memory usage

### ISSUE THREAD

**Issue by siggy** [linkerd/linkerd2#1179]
Observed conduit-proxy using 1GB memory:

```bash
$ docker stats $(docker ps --format={{.Names}}|grep conduit-proxy_prometheus)
CONTAINER                                                                                                CPU %               MEM USAGE / LIMIT       MEM %               NET I/O             BLOCK I/O           PIDS
k8s_conduit-proxy_prometheus-7f8f99c74d-tbd72_conduit-lifecycle_2c0a3b14-733e-11e8-b903-7cd30ab18fe8_0   6.85%               1.092 GiB / 251.8 GiB   0.43%               0 B / 0 B           29.3 MB / 0 B       3
```

### Env
- conduit v0.4.4
- k8s v1.10.4
  - 28 node cluster
    - 1 master
    - 2 256GB nodes (`k8s_conduit-proxy_prometheus` runs here)
    - 25 8GB nodes
- [lifecycle](https://github.com/runconduit/conduit-examples/tree/master/lifecycle) example
  - scaled to 20 namespaces x 15 replicas (`bin/scale 20 15`)
  - ~2500 pods

### metrics output

https://gist.github.com/siggy/8957be93203e9c9889161650b9d355d4

**Comment by olix0r** [comment]
This is a great find! I think we're close to merging https://github.com/runconduit/conduit/pull/1128 -- I'd be really curious to see the proxy's process_* stats in this scenario (especially over time).

**Comment by siggy** [comment]
Unable to reproduce with:
- conduit `v0.4.4`
- `bin scale 10 15`
- `bb-terminus` pod deletion with `SLEEP_TIME=10`
- `bb-terminus` service deletion every 150s

![screen shot 2018-06-26 at 9 54 27 am](https://user-images.githubusercontent.com/236915/41927555-6d5e32ae-7927-11e8-9d67-72c798dd6304.png)

`bin scale 20 15` had previously made the cluster unstable, but going to retry under those original conditions to attempt a reproduction.

**Comment by siggy** [comment]
No noticeable increase in memory after 6 hours:
<img width="1192" alt="screen shot 2018-06-26 at 5 21 46 pm" src="https://user-images.githubusercontent.com/236915/41946094-74390a02-7965-11e8-9e76-7dc18bfa5c4c.png">

**Comment by siggy** [comment]
restarting the test on master (`git-15718de2`) with more aggressive service discovery changes:

```bash
conduit install --conduit-namespace conduit-lifecycle | kubectl apply -f -
bin/deploy 1
bin/scale 1 300
```

redeployer:

```sh
    #!/bin/sh

    # give deployment time to fully roll out
    sleep 60

    while true; do
      PODS=$(kubectl -n $LIFECYCLE_NS get po --field-selector=status.phase=Running --selector=app=bb-terminus -o jsonpath='{.items[*].metadata.name}')

      SPACES=$(echo "${PODS}" | awk -F" " '{print NF-1}')
      POD_COUNT=$(($SPACES+1))
      echo "found ${POD_COUNT} running pods"

      SLEEP_TIME=1

      # more aggressive restart interval, for smaller deployments
      # restart each pod every minute
      # SLEEP_TIME=$(( 60 / $POD_COUNT))
      # if [ $SLEEP_TIME = 0 ]; then
      #   SLEEP_TIME=1
      # fi

      counter=0
      for POD in ${PODS}; do
        kubectl -n $LIFECYCLE_NS delete po $POD
        echo "sleeping for ${SLEEP_TIME} seconds..."
        sleep $SLEEP_TIME

        # bounce service every 30 seconds
        if [ $(expr $counter % 30) = 0 ]; then
          svc=$(kubectl -n $LIFECYCLE_NS get svc/bb-terminus -o json)
          kubectl -n $LIFECYCLE_NS delete svc/bb-terminus
          echo $svc | kubectl -n $LIFECYCLE_NS apply -f -
        fi
        counter=`expr $counter + 1`
      done

      # bounce service
      # svc=$(kubectl -n $LIFECYCLE_NS get svc/bb-terminus -o json)
      # kubectl -n $LIFECYCLE_NS delete svc/bb-terminus
      # echo $svc | kubectl -n $LIFECYCLE_NS apply -f -
    done
```

**Comment by siggy** [comment]
With the more aggressive configuration above, two issues to note:

## Memory usage

`container_memory_working_set_bytes`, as reported by Docker, is sometimes, but not always, higher than the `process_resident_memory_bytes` and `process_virtual_memory_bytes` metrics provided by `conduit-proxy`:

Highest `container_memory_working_set_bytes` `conduit-proxy` was in a `bb-p2p` pod, reporting:
- 96MB `container_memory_working_set_bytes`
- 90MB `process_virtual_memory_bytes`
- 59MB `process_resident_memory_bytes`

Highest `process_virtual_memory_bytes` `conduit-proxy` was in a `bb-p2p` pod, reporting:
- 45MB `container_memory_working_set_bytes`
- 101MB `process_virtual_memory_bytes`
- 43MB `process_resident_memory_bytes`

For comparison, the `conduit-proxy` in the Prometheus pod:
- 68MB `container_memory_working_set_bytes`
- 55MB `process_virtual_memory_bytes`
- 39MB `process_resident_memory_bytes`

![screen shot 2018-06-27 at 11 00 41 am](https://user-images.githubusercontent.com/236915/41992015-3335b95a-79fc-11e8-802c-6f54870ca1b7.png)

## Proxy capacity error
The `conduit-proxy` running in the Prometheus pod is logging these at a rate of about 50/s:
```
2018-06-27T18:12:18.005047944Z ERR! proxy={server=out listen=127.0.0.1:4140 remote=10.233.65.37:51788} conduit_proxy router at capacity (100); returning a 503
```

`conduit-proxy` also reports these every 10s (with surprising regularity):
```
2018-06-27T18:17:49.498127182Z ERR! proxy={server=out listen=127.0.0.1:4140 remote=10.233.65.37:42296} conduit_proxy turning Error caused by underlying HTTP/2 error: protocol error: unexpected internal error encountered into 500
```

Likely related, the Grafana instance is unable to connect to Prometheus, running `curl` from the Grafana pod yields:
```bash
$ curl -v http://prometheus.conduit-lifecycle.svc.cluster.local:9090
* Rebuilt URL to: http://prometheus.conduit-lifecycle.svc.cluster.local:9090/
*   Trying 10.233.14.166...
* TCP_NODELAY set
* Connected to prometheus.conduit-lifecycle.svc.cluster.local (10.233.14.166) port 9090 (#0)
> GET / HTTP/1.1
> Host: prometheus.conduit-lifecycle.svc.cluster.local:9090
> User-Agent: curl/7.52.1
> Accept: */*
>
< HTTP/1.1 500 Internal Server Error
< content-length: 0
< date: Wed, 27 Jun 2018 18:09:01 GMT
<
* Curl_http_done: called premature == 0
* Connection #0 to host prometheus.conduit-lifecycle.svc.cluster.local left intact
```

**Comment by olix0r** [comment]
Before we investigate changing this setting, it would be helpful to understand how prometheus's scraper works. Does it try to issue as many requests as possible in parallel? Are there ways to constrain parallelism?

**Comment by siggy** [comment]
Prometheus' scraper does not appear to have any parallelism control, and does not explicitly try to perform scrapes in parallel, though in practice it may perform that way:
https://github.com/prometheus/prometheus/blob/057a5ae2b147b6a1dfe0d3a667e13ed6535dbe20/scrape/scrape.go#L329
