### ISSUE TITLE
proxy_build_info git_version label value is the same as git_sha

### ISSUE THREAD

**Issue by dkulchinsky** [linkerd/linkerd2#11803]
### What is the issue?

the git_sha & git_version seem to always have the same value (looks like a commit sha), but I was expecting that git_version would actually have the value of git describe (i.e. the tag name), so something like stable-2.13.7

example:
```
proxy_build_info{git_branch="HEAD", git_sha="0e843c9", git_version="0e843c9", profile="release", rust_version="rustc 1.69.0 (84c898d65 2023-04-16)", <...>}
```

this is from a proxy running stable-2.13.7

### How can it be reproduced?

install linkerd 2.13.7, scarpe proxy metrics and check the labels on `proxy_build_info`

### Logs, error output, etc

```
proxy_build_info{git_branch="HEAD", git_sha="0e843c9", git_version="0e843c9", profile="release", rust_version="rustc 1.69.0 (84c898d65 2023-04-16)", <...>}
```

this is from a proxy running stable-2.13.7

### output of `linkerd check -o short`

```
❯ linkerd check -o short
linkerd-version
---------------
‼ cli is up-to-date
    is running version 2.13.7 but the latest stable version is 2.14.6
    see https://linkerd.io/2.13/checks/#l5d-version-cli for hints

control-plane-version
---------------------
‼ control plane is up-to-date
    is running version 2.13.7 but the latest stable version is 2.14.6
    see https://linkerd.io/2.13/checks/#l5d-version-control for hints

linkerd-control-plane-proxy
---------------------------
‼ control plane proxies are up-to-date
    some proxies are not running the current version:
	* linkerd-destination-694c4dfc7c-8w4fz (stable-2.13.7)
	* linkerd-destination-694c4dfc7c-lxwpv (stable-2.13.7)
	* linkerd-destination-694c4dfc7c-m9lcb (stable-2.13.7)
	* linkerd-identity-77d5644d7b-gzjh6 (stable-2.13.7)
	* linkerd-identity-77d5644d7b-mvzbx (stable-2.13.7)
	* linkerd-identity-77d5644d7b-tn76g (stable-2.13.7)
	* linkerd-proxy-injector-75b5f95bbd-g6pzz (stable-2.13.7)
	* linkerd-proxy-injector-75b5f95bbd-jgmsr (stable-2.13.7)
	* linkerd-proxy-injector-75b5f95bbd-n65p8 (stable-2.13.7)
    see https://linkerd.io/2.13/checks/#l5d-cp-proxy-version for hints

linkerd-viz
-----------
‼ viz extension proxies are up-to-date
    some proxies are not running the current version:
	* metrics-api-6c6d76756c-8qrxz (stable-2.13.7)
	* tap-844d7c9cf-6fxt9 (stable-2.13.7)
	* tap-844d7c9cf-l9qxf (stable-2.13.7)
	* tap-844d7c9cf-pfp4x (stable-2.13.7)
	* tap-injector-75495c59df-nsj8z (stable-2.13.7)
	* web-74966ffc5b-jg4mq (stable-2.13.7)
    see https://linkerd.io/2.13/checks/#l5d-viz-proxy-cp-version for hints
‼ prometheus is installed and configured correctly
    missing ClusterRoles: linkerd-linkerd-viz-prometheus
    see https://linkerd.io/2.13/checks/#l5d-viz-prometheus for hints

Status check results are √
```

### Environment

- Kubernetes version: 1.25.13
- Environment: GKE, kops(AWS)
- OS: COS, Ubuntu
- Linkerd version: stable-2.13.7

### Additional context

Slack convo which suggest I open this issue: https://linkerd.slack.com/archives/C89RTCWJF/p1703021828018819

### Would you like to work on fixing this bug?

None

**Comment by olix0r** [comment]
The proxy releases are decoupled from linkerd releases, so the versions would never line up in that way. I agree it would be nice to have better version info

**Comment by dkulchinsky** [comment]
Thanks @olix0r, so `git_version` label should display the proxy version? however currently it is equal to the commit sha (same value as `git_sha` label)

for example:
```
proxy_build_info{git_branch="HEAD", git_sha="0e843c9", git_version="0e843c9", profile="release", rust_version="rustc 1.69.0 (84c898d65 2023-04-16)", <...>}
```

`git_sha="0e843c9", git_version="0e843c9"`

**Comment by dkulchinsky** [comment]
Hey @olix0r 👋🏼 

just wanted to circle back to this again, if I understand you comment correctly than `git_version` should have the proxy version as value which is not the same as the linkerd version, that makes sense! however as I showed above it just has the commit sha and has the same value as `git_sha` label.

the main issue we have is we can't reasonably track the deployed proxy versions using this metric as the value of `git_version` is no very usable.

so I think this is still a bug?

**Comment by dkulchinsky** [comment]
Happy new year @olix0r 👋🏼 

Was hoping you'd have a chance to see my last comment, I think aside from the issue you mentioned (that the linkerd version in `git_version` reflects the proxy version, not the linkerd version) the current value provided in the `git_version` seem entirely incorrect as it's equal to the value of `git_sha`

**Comment by olix0r** [comment]
It looks like we fixed this issue in June https://github.com/linkerd/linkerd2-proxy/pull/2432

Recent proxy build info looks like this:
```
proxy_build_info{date="2023-12-27T21:31:20Z",git_sha="f191eac",profile="release",vendor="linkerd",version="2.219.0"} 1
```

**Comment by dkulchinsky** [comment]
ohh, indeed!

we just upgraded to stable-2.14.8 and I can see the new `version` label.

closing this now and thanks again for the fix @olix0r
