### ISSUE TITLE
Support for extra manifest objects 

### ISSUE THREAD

**Issue by raghavtan** [linkerd/linkerd2#11822]
### What problem are you trying to solve?

We are not able to deploy ANY extra manifests that we would want to be deployed/bundled with this chart 
As an example we are not able to use the upstream chart by just overriding the `values.yaml` since the secret object is created by the chart but we use ExternalSecret managed by AWS secret manager.
Hence the secret are not managed by helm and rather the ExternalSecret controller.
We need to be able to disable secret or create external secret manifest using the toggles in values files 

### How should the problem be solved?

Addition of an extra toggle to enable creation of extra manifest object

### Any alternatives you've considered?

Pluggable support of different secret controllers available, but this would be specific to the type of secret controllers supported and would have to be maintained along with the upsteam changes in controller spec and CRD 

### Would you like to work on this feature?

yes

**Comment by alpeb** [comment]
I'm not familiar with the AWS secret manager, so can you provide a bit more details?
For the `linkerd-control-plane` chart to not install the `linkerd-identity-issuer` secret we have the setting `identity.issuer.scheme=kubernetes.io/tls`. This leaves room for other controllers/operators to take over the creation of that secret, like for example cert-manager (see [tutorial](https://linkerd.io/2.14/tasks/automatically-rotating-control-plane-tls-credentials/)). 
Wouldn't this cover your needs? Your suggested PR is a bit too open-ended, so I'd like to consider other alternatives first.

**Comment by raghavtan** [comment]
@alpeb The example in the PR is for creating an external secret manifest however that is just an example.
The actual need is to be able to deploy ANY extra manifests that we would want to be deployed/bundled with this chart.
I will update the PR example in `values.yaml`

**Comment by alpeb** [comment]
There are a few ways to extend a chart to apply customizations like post-rendering, kustomize, sub-charts.
There are projects that offer such `extraObjects` escape hatches, but that doesn't feel like a good practice. The helm charts we provide should serve as the basis for a best-practices linkerd installation, trying not to add every possible knob, as that requires extra docs and testing, and unnecessarily complicates things. Again, I would point to the extension methods I mentioned above, which are well documented and broadly used.
