### ISSUE TITLE
Increase Mutating webhook timeout.

### ISSUE THREAD

**Issue by alpeb** [linkerd/linkerd2#12011]
### Discussed in https://github.com/linkerd/linkerd2/discussions/11984

<div type='discussions-op-text'>

<sup>Originally posted by **smithdebug** January 24, 2024</sup>
Hello Team,
I’m reaching out to inquire about the possibility of extending the timeout for the `linkerd-proxy-injector-webhook-config` Mutating Webhook. Currently, the timeout is set to `10 seconds` bydefault. We’ve recently faced a situation where this timeout caused an issue, resulting in a Pod without a Linkerd proxy sidecar. Thanks</div>

**Comment by alpeb** [comment]
@smithdebug , would you be willing to tackle this issue? Sounds like a relatively simple setting to add and hook in the helm templates.

**Comment by alpeb** [comment]
Thanks for opening #12028, we'll take a look at it soon. OTOH, we're still interested on why you actually bumped into this issue. The proxy injector should not take that long to process pods. Can you share a bit more about your setup? Is there a lot of pod churn, maybe during node escalations, causing requests to the injector to spike? Are you already running in HA mode, increasing the number of the injector replicas?

**Comment by smithdebug** [comment]
We have around 3000 pods and 5 replicas for proxy-injector. We have enabled webhook failure mode, earlier it was set to ignore.

**Comment by wim-de-groot** [comment]
Is this issue still relevant?

**Comment by mateiidavid** [comment]
@wim-de-groot nope! thanks for pointing it out. 

Closing, since this has been resolved through https://github.com/linkerd/linkerd2/pull/12028. Thanks all!
