### ISSUE TITLE
Distributed tracing does not capture grpc traffic and send spans

### ISSUE THREAD

**Issue by abrekhov** [linkerd/linkerd2#12034]
### What is the issue?

I've installed linkerd, linkerd-jaeger with mutation webhook to send spans to grafana tempo, tempo itself, emojivoto (I also checked on googles online boutique microservices demo). 

I see http spans but there is no grpc spans.

### How can it be reproduced?

Install linkerd, linkerd-jaeger, tempo, test app with grpc. Try to generate the load.

### Logs, error output, etc

No logs.

### output of `linkerd check -o short`

```
linkerd check -o short
\ Running jaeger extension check linkerd-jaeger
--------------
‼ jaeger extension pods are injected
    could not find proxy container for loki-0 pod
    see https://linkerd.io/2.14/checks/#l5d-jaeger-pods-injection for hints

Status check results are √
```

### Environment

- k8s version: 1.28
- Host OS: Ubuntu 22
- linkerd: Client version: stable-2.14.9; Server version: stable-2.14.9
- Cluster Env: Yandex Cloud managed k8s 

### Would you like to work on fixing this bug?

maybe

**Comment by kflynn** [comment]
Hey @abrekhov! Sorry for the delay here. That error with the `jaeger` extension worries me, can you tell me how you installed this? I'd like to try it on my own.
