### ISSUE TITLE
Excessive logging when encourering "unimplemented resource type" errors in injector webhook

### ISSUE THREAD

**Issue by relu** [linkerd/linkerd2#12186]
### What is the issue?

This is more of an annoyance rather than an actual bug.

I'm running KEDA with ScaledJob custom resources and these own Kubernetes Job resources for which pods we have linkerd inject sidecards. The problem is that every time the webhook handles these resources it logs something like this:

```
{"level":"warning","msg":"skipping event for parent scaledjob: rpc error: code = Unimplemented desc = unimplemented resource type: scaledjob","time":"2024-03-01T10:06:45Z"}
```

These logs are completely harmless but they are very annoying especially if the ScaledJob is triggered very frequently.

### How can it be reproduced?

You can see this happen for any CRD resource that is designed to own a workload-type resource. KEDA's ScaledJob is a good candidate.

### Logs, error output, etc

```
linkerd-proxy-injector-6fb9898f5c-slxbm proxy-injector {"level":"warning","msg":"skipping event for parent scaledjob: rpc error: code = Unimplemented desc = unimplemented resource type: scaledjob","time":"2024-03-01T10:12:21Z"}
linkerd-proxy-injector-6fb9898f5c-slxbm proxy-injector {"level":"warning","msg":"skipping event for parent scaledjob: rpc error: code = Unimplemented desc = unimplemented resource type: scaledjob","time":"2024-03-01T10:12:21Z"}
linkerd-proxy-injector-6fb9898f5c-slxbm proxy-injector {"level":"warning","msg":"skipping event for parent scaledjob: rpc error: code = Unimplemented desc = unimplemented resource type: scaledjob","time":"2024-03-01T10:12:24Z"}
linkerd-proxy-injector-6fb9898f5c-slxbm proxy-injector {"level":"warning","msg":"skipping event for parent scaledjob: rpc error: code = Unimplemented desc = unimplemented resource type: scaledjob","time":"2024-03-01T10:12:30Z"}
```

### output of `linkerd check -o short`

N/A

### Environment

N/A

### Possible solution

Silently handle these "unimplemented resource type" errors, or just log them as debug instead of warn.

https://github.com/linkerd/linkerd2/blob/c1fcbbafb2c15557f33e95dd609651cf92757d24/controller/proxy-injector/webhook.go#L76-L78

### Would you like to work on fixing this bug?

maybe

**Comment by mateiidavid** [comment]
Hi @relu! Thanks for opening this and for finding the exact place where the logs are being recorded. We'd be okay with changing this to `debug`. Would you like to work on this? :)

**Comment by Adarsh-jaiss** [comment]
Hey @mateiidavid , if anyone is not working on this issue, can i work on this?

**Comment by mateiidavid** [comment]
@Adarsh-jaiss sure, let us know if you need any help. :)

**Comment by Adarsh-jaiss** [comment]
Hey @mateiidavid , Please look into it and review the PR.
