### ISSUE TITLE
Add Grafana dashboard for authorities

### ISSUE THREAD

**Issue by rmars** [linkerd/linkerd2#1225]
As of #1181 we can query statsummaries for authorities.
We can now add a grafana dashboard for the authority stats, similar to how we do for deployments, replication controllers, etc.

We should also link to the Grafana dashboard from the Web UI tables.

**Comment by alpeb** [comment]
Thanks for the clarification @rmars . I've created #1772 accordingly. Please let me know if it makes sense :-)

**Comment by rmars** [comment]
Fixed by #1772
