### ISSUE TITLE
Adding OpenTelemetry Exporting

### ISSUE THREAD

**Issue by hdost** [linkerd/linkerd2#12313]
### What problem are you trying to solve?

Allow exporting `tracing` events of OpenTelemetry OTLP and potentially other exporters for linkerd2

### How should the problem be solved?

Allow users and potentially distribution builders to understand the behavior of the system, and this could also allow for end users to provide greater context in edge case issues. 

### Any alternatives you've considered?

Other existing tracing subscribers, but they lack flexibility in export or focus on specific vendors (Insert your observability company dujour). 

### How would users interact with this feature?

Simplest way would be usage of the SDK environment variables standard in OpenTelemetry. 

### Would you like to work on this feature?

yes

**Comment by hdost** [comment]
cc: @mateiidavid

**Comment by kflynn** [comment]
Hey @hdost! Thanks for chiming in. Can you tell us a bit more about what specific problem you're trying to solve here, and about how exporting tracing events will help?

Thanks!
