### ISSUE TITLE
The counter metrics about the number of sent/received events in streams

### ISSUE THREAD

**Issue by loyd** [linkerd/linkerd2#12319]
### What problem are you trying to solve?

Hi, I'm choosing between linkerd (first of all because the proxy is written in Rust, which is lightweight on my tests) and envoy-based solutions for a cluster of GRPC services. My primary requirement is excellent telemetry.

We heavily rely on streaming between all our services. However, linkerd doesn't provide any event counter for long-lived streams:
```
route_request_total{direction="outbound",dst="lve-server.default.svc.cluster.local:4242",rt_route="Subscribe"} 1
```
(no response metrics until the subscription is ended)

![2024-03-21_19-41-33](https://github.com/linkerd/linkerd2/assets/952180/57f5e9de-4548-4bbc-a773-1152a813be27)

In the meantime, envoy provides such statistics, including in the response counter:
```
envoy_cluster_grpc_Subscribe_response_message_count{envoy_grpc_bridge_method="CounterService",envoy_grpc_bridge_service="counter",envoy_cluster_name="lve_server"} 327336
```

### How should the problem be solved?

`route_request_total` (or another dedicated metric) should calculate the number of events in long-lived streaming

### Any alternatives you've considered?

-

### Would you like to work on this feature?

Maybe

**Comment by olix0r** [comment]
It sounds like this is more generally asking for gRPC-aware metrics. As far as I understand, it wouldn't be possible for Linkerd to measure this sort of thing arbitrarily at the HTTP-level. We'd have to parse the response bodies to count the number of gRPC messages included in the response, for instance.

**Comment by loyd** [comment]
It seems that envoy [count frames for this metric](https://github.com/envoyproxy/envoy/blob/d07b522e68d0f1c53e4e76d61445a892626ff285/source/extensions/filters/http/grpc_stats/grpc_stats_filter.cc#L272). I think it's a reasonable trade-off. Although, I'm not sure it's easy to implement with outdated hyper (0.14).

Anyway, will a patch with this metric be considered?

**Comment by loyd** [comment]
Linked PR is activity

**Comment by loyd** [comment]
The bot's logic is ill-conceived =(. It should be reopened

**Comment by olix0r** [comment]
These metrics are available in edge releases:

```
# HELP outbound_http_route_request_frame_size_bytes Request data frame sizes.
# TYPE outbound_http_route_request_frame_size_bytes histogram
# UNIT outbound_http_route_request_frame_size_bytes bytes
# HELP outbound_http_route_backend_response_frame_size_bytes Response data frame sizes.
# TYPE outbound_http_route_backend_response_frame_size_bytes histogram
# UNIT outbound_http_route_backend_response_frame_size_bytes bytes
# HELP outbound_grpc_route_request_frame_size_bytes Request data frame sizes.
# TYPE outbound_grpc_route_request_frame_size_bytes histogram
# UNIT outbound_grpc_route_request_frame_size_bytes bytes
# HELP outbound_grpc_route_backend_response_frame_size_bytes Response data frame sizes.
# TYPE outbound_grpc_route_backend_response_frame_size_bytes histogram
# UNIT outbound_grpc_route_backend_response_frame_size_bytes bytes
# HELP outbound_http_route_request_frame_size_bytes Request data frame sizes.
# TYPE outbound_http_route_request_frame_size_bytes histogram
# UNIT outbound_http_route_request_frame_size_bytes bytes
# HELP outbound_http_route_backend_response_frame_size_bytes Response data frame sizes.
# TYPE outbound_http_route_backend_response_frame_size_bytes histogram
# UNIT outbound_http_route_backend_response_frame_size_bytes bytes
# HELP outbound_grpc_route_request_frame_size_bytes Request data frame sizes.
# TYPE outbound_grpc_route_request_frame_size_bytes histogram
# UNIT outbound_grpc_route_request_frame_size_bytes bytes
# HELP outbound_grpc_route_backend_response_frame_size_bytes Response data frame sizes.
# TYPE outbound_grpc_route_backend_response_frame_size_bytes histogram
# UNIT outbound_grpc_route_backend_response_frame_size_bytes bytes
```
