### ISSUE TITLE
proxy: additional metrics on router capacity, errors

### ISSUE THREAD

**Issue by siggy** [linkerd/linkerd2#1232]
## Background

While investigating https://github.com/runconduit/conduit/issues/1179#issuecomment-400800995, a source of request failure was the proxy hitting its `CONDUIT_PROXY_OUTBOUND_ROUTER_CAPACITY` limit.

Currently, this is only verifiable via logging:
```
2018-06-27T18:12:18.005047944Z ERR! proxy={server=out listen=127.0.0.1:4140 remote=10.233.65.37:51788} conduit_proxy router at capacity (100); returning a 503
```

## Proposal

Propose this information be exposed via metrics:
```
routes_active{direction="inbound|outbound"}
route_capacity_errors_total{direction="inbound|outbound"}
```

**Comment by hawkw** [comment]
I wonder if, rather than a `route_capacity_errors_total` metric, we might want to have a more general counter of internal errors that's labeled by what type of error occurred...
