### ISSUE TITLE
proxy: expose `clock_time_seconds` metric

### ISSUE THREAD

**Issue by rkrishn7** [linkerd/linkerd2#12413]
### What problem are you trying to solve?

Proxies currently report a `identity_cert_expiration_timestamp_seconds` that indicates when a proxy’s current mTLS identity certificate will expire (in seconds since the UNIX epoch).

However, for monitoring when a certificate will expire relative to the proxy's current notion of time, it is not all that useful.

### How should the problem be solved?

If the proxy emitted it's system time as a gauge metric, it would be trivial to track expiration of certificates. `cert-manager` does this well.

### Any alternatives you've considered?

It's possible to track the system time elsewhere (e.g. by host), however I think the proxy should expose this to give a useful view of certificate expiration.

### Would you like to work on this feature?

yes

**Comment by wmorgan** [comment]
Gonna reopen this one since I think it staled out without an evaluation.

**Comment by sfleen** [comment]
The wall clock metric has been added to the proxy as `process_clock_time_seconds` for a few edge releases now. This can be marked as completed.
