### ISSUE TITLE
Proxy: factor out common timestamp gauge logic

### ISSUE THREAD

**Issue by briansmith** [linkerd/linkerd2#1241]
In https://github.com/runconduit/conduit/pull/1204 we added telemetry that records the last time each Tls configuration was loaded, which looks like this:

```rust
let timestamp_secs = when
                        .duration_since(UNIX_EPOCH)
                        .expect("SystemTime before UNIX_EPOCH!")
                        .as_secs()
                        .into();

                    metrics.tls_config_last_reload_seconds = Some(timestamp_secs);
                    metrics.tls_config(TlsConfigLabels::success()).incr();
```

Previously, we had similar logic for the process start time logic:

```rust
        let t0 = process.start_time
            .duration_since(UNIX_EPOCH)
            .expect("process start time")
            .as_secs();
```

We should, at least, have some helper function that, given a `Gauge` and a `SystemTime`, sets the gauge's value to the the duration since the Unix epoch, and we should use this everywhere we record timestamps. Ideally that helper would also be able to take care of the `SystemTime::now()` part to make things even simpler, but maybe we really do need to separate the code where the current time is gathered and the code where the timestamp is sent to the metrics system. If so we should consider having an `UnrecordedTimestamp` type that wraps `SystemTime` and which is consumed by the guage setting code, to help ensure it clear that we're recording all the timestamps we're gathering.

**Comment by briansmith** [comment]
While doing this, we should reconsider where we're recording timestamps at a low resolution. For example, I think one second resolution for `tls_config_last_reload_seconds` is fine given the current way the configuration is distributed, but as that improves sub-second precision is going to be important. We should probably record at a higher resolution and then let the display code do the rounding.

**Comment by hawkw** [comment]
This is still potentially relevant.
