### ISSUE TITLE
BadSignature error when using ec with key_bits 512 (works with 256)

### ISSUE THREAD

**Issue by ghost** [linkerd/linkerd2#12506]
### What is the issue?

Should work as well with 256 or 512

### How can it be reproduced?

Follow this (amazing :) ) tutorial https://linkerd.io/2024/02/06/linkerd-certificates-with-vault/.

But on step of the creation of the trust anchor, specify the key_bits to 512

### Logs, error output, etc

[    30.081200s] ERROR ThreadId(02) identity: linkerd_proxy_identity_client::certify: Failed to obtain identity error=invalid peer certificate: BadSignature

### output of `linkerd check -o short`

the helm chart does not finish

### Environment

Rancher

### Would you like to work on fixing this bug?

None

**Comment by kflynn** [comment]
Hey @fakeNews-jpg, so sorry for the delay here! I've switched this to an enhancement request rather than a bug -- supporting 512-bit EC keys would definitely rock, but that's really asking for new functionality rather than reporting broken existing functionality. 🙂
