### ISSUE TITLE
proxy: some stats missing from metrics endpoint

### ISSUE THREAD

**Issue by siggy** [linkerd/linkerd2#1259]
Observed a `conduit-proxy` get into a state where no `classification="failure"` metrics were exported on the `/metrics` endpoint. This is not expected as this is coming from a `conduit-proxy` running in the control-plane's Prometheus pod, which is scraping pods that are continually deleted and recreated. This only happened once, after a restart, all subsequent observations have shown failure metrics.

Full metrics dump: https://gist.github.com/siggy/db8719a26c732dfccd911729290a226f

First reported via: https://github.com/runconduit/conduit/issues/1179#issuecomment-400791290

**Comment by olix0r** [comment]
@siggy 

> This is not expected as this is coming from a conduit-proxy running in the control-plane's Prometheus pod, which is scraping pods that are continually deleted and recreated.

Can you explain this in more detail? Why are failures expected in this scenario.

If a metric scope has not been updated for 10 minutes, it is removed from export.

It would be helpful to have a log that confirms these events should actually be exported.

**Comment by siggy** [comment]
Failure is expected in this scenario because:
- Prometheus attempts to scrape each pod every 10 seconds
- each pod is deleted after 1 minute
- each service is deleted/recreated every 30 seconds
- each deployment is redeployed every 1 minute

`conduit-proxy` log in the Prometheus pod:
```
ERR! proxy={server=out listen=127.0.0.1:4140 remote=10.233.65.179:60006} conduit_proxy turning Error caused by underlying HTTP/2 error: protocol error: unexpected internal error encountered into 500
ERR! proxy={server=out listen=127.0.0.1:4140 remote=10.233.65.179:60126} conduit_proxy::transparency::tcp tcp duplex error: Transport endpoint is not connected (os error 107)
ERR! proxy={server=out listen=127.0.0.1:4140 remote=10.233.65.179:51454} conduit_proxy turning operation timed out after 10s into 500
ERR! proxy={server=out listen=127.0.0.1:4140 remote=10.233.65.179:33832} conduit_proxy turning operation timed out after 10s into 500
ERR! proxy={server=out listen=127.0.0.1:4140 remote=10.233.65.179:59508} conduit_proxy turning operation timed out after 10s into 500
ERR! proxy={server=out listen=127.0.0.1:4140 remote=10.233.65.179:34880} conduit_proxy turning operation timed out after 10s into 500
ERR! proxy={server=out listen=127.0.0.1:4140 remote=10.233.65.179:35934} conduit_proxy turning operation timed out after 10s into 500
ERR! proxy={server=out listen=127.0.0.1:4140 remote=10.233.65.179:36992} conduit_proxy turning Error caused by underlying HTTP/2 error: protocol error: unexpected internal error encountered into 500
ERR! proxy={server=out listen=127.0.0.1:4140 remote=10.233.65.179:47112} conduit_proxy turning operation timed out after 10s into 500
```

Here is a sample of expected metrics, compared to observed:

### Expected

From https://gist.github.com/siggy/ed335e67198f5c8b0e94d1a68b867af2:

```
tcp_close_total{direction="outbound",peer="src",tls="internal_traffic",classification="failure"} 129
tcp_close_total{direction="outbound",peer="src",tls="internal_traffic",classification="success"} 62

tcp_connection_duration_ms_count{direction="outbound",peer="src",tls="internal_traffic",classification="failure"} 129
tcp_connection_duration_ms_count{direction="outbound",peer="src",tls="internal_traffic",classification="success"} 62
```

### Observed

From https://gist.github.com/siggy/db8719a26c732dfccd911729290a226f:

```
tcp_close_total{direction="outbound",peer="src",classification="success"} 28821

tcp_connection_duration_ms_count{direction="outbound",peer="src",classification="success"} 28821
```
