### ISSUE TITLE
Helm upgrade always changing due to trust root?

### ISSUE THREAD

**Issue by kastl-ars** [linkerd/linkerd2#12668]
### What is the issue?

#4017 was closed as solved, but if I understand the issue properly I am still having the same problem.

Running `helm upgrade ...` directly after running `helm install ...`, i.e. without any changes due to helm chart versions etc., always does something and is not idempotent.

### How can it be reproduced?

Run this command:

```
helm install linkerd-control-plane -n linkerd \
  --set-file identityTrustAnchorsPEM=ca.crt \
  --set-file identity.issuer.tls.crtPEM=issuer.crt \
  --set-file identity.issuer.tls.keyPEM=issuer.key \
  linkerd/linkerd-control-plane
```

Then immediately run this command (that uses `upgrade` instead of `install`):

```
helm upgrade linkerd-control-plane -n linkerd \
  --set-file identityTrustAnchorsPEM=ca.crt \
  --set-file identity.issuer.tls.crtPEM=issuer.crt \
  --set-file identity.issuer.tls.keyPEM=issuer.key \
  linkerd/linkerd-control-plane
```

You end up with changes and two versions in the helm history, even though nothing should have changed. The files are the same, no chart updates have been found in the mean time.

### Logs, error output, etc

Only the normal helm output when a chart is being installed/updated.

### output of `linkerd check -o short`

```
Status check results are √
```

### Environment

- Kubernetes v1.29.5+k3s1

### Would you like to work on fixing this bug?

None

**Comment by adleong** [comment]
Hi @kastl-ars!  There are certain resources which are always regenerated on install or upgrade, such as the TLS credentials for webhooks.  There isn't any need for continuity of these credentials through upgrades.  Can you tell me more about your use case?  Why would you run a helm upgrade with no changes and why would you not want this upgrade to appear in the helm history?

**Comment by kastl-ars** [comment]
I noticed because I was preparing a setup using linkerd in k3s, where Ansible and Vagrant deployed everything. Except that Ansible always reported things as changed and the pods kept being restarted on upgrade.

#4017 sounded like this kind of issue should no longer appear, hence this bug report. If this intentional, then feel free to close it.
