### ISSUE TITLE
[FR] - reduce endpoint added/removed logs to debug

### ISSUE THREAD

**Issue by dwilliams782** [linkerd/linkerd2#12704]
### What problem are you trying to solve?

I'm finding the following logs to be incredibly verbose (we have deployments with >100 pods for example constantly rotating with HPA) and masking other more interesting logs. These may be better suited to debug?

```
INFO ThreadId(02) outbound:proxy{addr=10.224.15.134:5000}:service{ns=<> name=<> port=<>}: linkerd_pool_p2c: Removing endpoint
INFO ThreadId(02) outbound:proxy{addr=10.224.15.134:5000}:service{ns=<> name=<> port=<>}: linkerd_pool_p2c: Adding endpoint addr=<>:5000
``` 

### How should the problem be solved?

Move logs to debug level from info.

### Any alternatives you've considered?

n/a

### Would you like to work on this feature?

None

**Comment by alpeb** [comment]
What version are you on? The `outbound_http_balancer_endpoints` metrics was broken and got fixed in edge-24.5.1 (Ref linkerd/linkerd2-proxy#2928). Granted that doesn't explain the repeated IP entries in the logs; I'll discuss this with the team.
One possible stop-gap for appeasing the logs is adding `linkerd_pool_p2c=error` to the proxy log setting.

**Comment by dwilliams782** [comment]
Thanks Alejandro - we're on 2.15.3-enterprise, I don't know whether that fix in there or not. 

I was unable to reproduce the erroneous logs starting fresh in a clean environment, so I think it is actually related to turning HAZL off and on. I'll submit a proper Buoyant support ticket when I have good repro steps on that one.

**Comment by alpeb** [comment]
Ok the metrics fix is already included in the version you're on. Looking forward to the support ticket with the repro steps :-)

**Comment by hadican** [comment]
Hi! I feel the same. Is there a way to change log level of "linkerd_pool_p2c"?

**Comment by alpeb** [comment]
> Hi! I feel the same. Is there a way to change the log level of "linkerd_pool_p2c"? [@alpeb](https://github.com/alpeb)

You can change the proxy's default log level to this:
```
proxy.logLevel: warn,linkerd=info,hickory=error,linkerd_pool_p2c=error
```
