### ISSUE TITLE
Linkerd destination repeatedly logging endpoint profile translator errors

### ISSUE THREAD

**Issue by bc185174** [linkerd/linkerd2#12719]
### What is the issue?

We have prometheus deployed and the destination controller is spamming these logs:

```
{"addr":":8086", "component":"endpoint-profile-translator", "context-ns":"prometheus", "context-pod":"prometheus-prometheus-0", "kubernetes":{…}, "msg":"failed to find LINKERD2_PROXY_INBOUND_LISTEN_ADDR environment variable in any container for given pod spec", "remote":{…}, "time":"2024-06-12T17:59:54Z"}
```

It only applies to the prometheus namespace and there are no other namespaces reporting this log.

### How can it be reproduced?

Deploy prometheus operator and mesh it with Linkerd.

### Logs, error output, etc

```
{"addr":":8086", "component":"endpoint-profile-translator", "context-ns":"prometheus", "context-pod":"prometheus-prometheus-0", "kubernetes":{…}, "msg":"failed to find LINKERD2_PROXY_INBOUND_LISTEN_ADDR environment variable in any container for given pod spec", "remote":{…}, "time":"2024-06-12T17:59:54Z"}
```

### output of `linkerd check -o short`

N/A

### Environment

- Kubernetes: 1.27.7
- Env: Linux, Ubuntu.
- Linkerd version: 2.14.10

### Would you like to work on fixing this bug?

maybe

**Comment by kflynn** [comment]
Hi @bc185174 – how exactly are you deploying and meshing Prometheus? There are a few too many ways of doing that to just run with "deploy and mesh Prometheus"...

**Comment by bc185174** [comment]
> Hi @bc185174 – how exactly are you deploying and meshing Prometheus? There are a few too many ways of doing that to just run with "deploy and mesh Prometheus"...

Apologies - we are deploying it via the prometheus operator https://github.com/prometheus-operator/prometheus-operator. Then deploy linkerd `2.14.10` and auto mesh the prometheus pods.

**Comment by kflynn** [comment]
OK, I think the immediate questions here are:

1. How often do the logs show up?
2. What pod is Prometheus trying to talk to? can we get the YAML for that Pod?

Thanks!

**Comment by alpeb** [comment]
Closing this one; please reopen if you're still having this issue and can provide more details.
