### ISSUE TITLE
Sync destination service and proxy's (inject's) understanding of "TLS enabled"

### ISSUE THREAD

**Issue by briansmith** [linkerd/linkerd2#1274]
The initial expectation was/is that *eventually* any pod that has the proxy injected into it should be able to do TLS. In particular, we originally intended to have `conduit inject` add the TLS settings to the proxy's configuration unconditionally, but now it is conditional on `--tls` being passed to `conduit inject`. The destination service follows the original intention and the proxy follows the way `conduit inject` was implemented. Thus the destination service will indicate that a non-TLS-enabled proxy-injected pod will accept TLS, when it won't.

This isn't *super* problematic in 0.5.0 because the proxy implements fallback logic such that when the TLS handshake fails, it will retry without TLS. However, that retry logic is a temporary measure (it isn't secure, and it's bad for performance). Thus we should make the Destination service's understanding of whether TLS is enabled for a pod match what the pod will actually do.

**Comment by briansmith** [comment]
Proposal:

* `linkerd inject` adds a `conduit.io/tls` label to pods indicating the TLS configuration (e.g. "optional") when it enables TLS. No label == No TLS.
* The destination service will return a TLS identity for a pod if (and only if) the pod's `conduit.io/control-plane-ns` matches its own namespace and its `conduit.io/tls` label is set.
* The proxy will stop matching the control plane namespace set in the destination service responses to its own namespace. Instead, it will rely on the filtering done by the controller in the previous bullet point.
* The control plane namespace will be removed from the destination service response messages.

WDYT @kl?

**Comment by briansmith** [comment]
The same needs to be done for the CA: it should only maintain the CA configmap in a namespace where there is a pod that meets one of the conditions in the previous comment, and it should only maintain secrets for pods that meet those conditions.

**Comment by klingerf** [comment]
This all sounds good to me, and I agree that it would be great to standardize the way in which the destination service and the CA determine if a pod is TLS-enabled. As far as the label name goes, either `linkerd.io/tls` or `linkerd.io/proxy-tls` works for me.

**Comment by olix0r** [comment]
Fixed by https://github.com/linkerd/linkerd2/pull/2371
