### ISSUE TITLE
Helm install documentation refers to incorrect repo

### ISSUE THREAD

**Issue by kbreit-insight** [linkerd/linkerd2#12753]
### What is the issue?

The documentation at https://linkerd.io/2.15/tasks/install-helm/ adds a repository named linkerd-edge. However, when helm charts are installed, it is referring to a repo named simply linkerd.

### How can it be reproduced?

Always.

### Logs, error output, etc

`Error: INSTALLATION FAILED: repo linkerd not found`

### output of `linkerd check -o short`

This is about documentation

### Environment

n/a, documentation

### Would you like to work on fixing this bug?

no

**Comment by alpeb** [comment]
Thanks for the report. This is getting fixed in linkerd/website#1790
