### ISSUE TITLE
Healthchecks/livenessProbe does not pass when using HTTPS scheme 

### ISSUE THREAD

**Issue by 4FunAndProfit** [linkerd/linkerd2#12806]
### What is the issue?

As said in the documentation : "By default, all networks are allowed so that all probes are authorized." (https://github.com/linkerd/linkerd2/blob/main/charts/linkerd-control-plane/values.yaml#L98C3-L98C76)
I do not know why it does not authorize by default when using HTTPS scheme 

Related issues:
- https://github.com/linkerd/linkerd2/pull/8961
- https://github.com/linkerd/linkerd2/pull/9008
- issue https://github.com/linkerd/linkerd2/issues/8945
- https://linkerd.io/2.12/features/server-policy/#default-authorizations
- maybe related to https://github.com/linkerd/linkerd2/issues/9595

### How can it be reproduced?

Inject linkerd on a namespace, 

Then apply this helm chart on this namespace: https://github.com/cloudnative-pg/charts

This helm chart uses HTTPS scheme for liveness and readyness probes (https://github.com/cloudnative-pg/charts/blob/main/charts/cloudnative-pg/templates/deployment.yaml#L84 and L100)

### Logs, error output, etc

Liveness probe failed: Get "https://CNPG:9443/readyz": EOF
Readiness probe failed: Get "https://CNPG:9443/readyz": EOF

### output of `linkerd check -o short`

Status check results are √

### Environment

Rancher 2.8.3

### Would you like to work on fixing this bug?

None

**Comment by 4FunAndProfit** [comment]
I think it is normal (https://linkerd.io/2.15/features/http-grpc/#:~:text=Note%20that%20while%20Linkerd%20does,connections%20as%20raw%20TCP%20streams.) ? 

Can you please confirm that this is the expected behavior? :)

**Comment by kflynn** [comment]
Correct. It's possible that things will work for you if you mark 9443 as [opaque or skip](https://linkerd.io/2.15/features/protocol-detection/), though honestly, why not just use HTTP probes? 🙂

**Comment by 4FunAndProfit** [comment]
Thanks for your answer @kflynn, I opened an issue in https://github.com/cloudnative-pg/charts/issues/328 to ask them to let us choose scheme for HTTP probes :)
