### ISSUE TITLE
Not all gRPC errors should be retried

### ISSUE THREAD

**Issue by Hexcles** [linkerd/linkerd2#12826]
### What is the issue?

If I'm understanding the code correctly, there is no way to specify GRPC status codes in a service profile, and the retry condition falls under

https://github.com/linkerd/linkerd2-proxy/blob/837fbc9531844e5f10d7f4480555127236e6a09b/linkerd/app/outbound/src/http/retry.rs#L89

In other words, all failures may be retried provided that the request isn't too long

https://github.com/linkerd/linkerd2-proxy/blame/837fbc9531844e5f10d7f4480555127236e6a09b/linkerd/proxy/client-policy/src/grpc.rs#L61

says `PermissionDenied` is a failure.

Combined, this means that linkerd would retry GRPC Permission Denied errors if I mark the route with `isRetryable: true`. That's rather surprising.

### How can it be reproduced?

Create a service profile with a retryable route for a GRPC endpoint, have the server send Permission Denied, and observe the requests being retried.

### Logs, error output, etc

N/A

### output of `linkerd check -o short`

N/A

### Environment

N/A

### Possible solution

PermissionDenied was classified as failures in https://github.com/linkerd/linkerd2-proxy/commit/af31aab5ce015ebea0c3d647425c2a3efba8d418, which doesn't align with the reasoning in the original issue https://github.com/linkerd/linkerd2/issues/3729 where only "server errors" were considered failures.

Alternatively, maybe reconsider https://github.com/linkerd/linkerd2/issues/3376?

### Would you like to work on fixing this bug?

None

**Comment by Hexcles** [comment]
cc @olix0r as you authored the commit in question and were also part of the original discussion

**Comment by kflynn** [comment]
@Hexcles Thanks for the report!! We'll dig into this as soon as we can. 🙂

**Comment by olix0r** [comment]
As described in https://github.com/linkerd/linkerd2/issues/11529#issuecomment-2253347512, the latest edge release supports GRPCRoute resources with annotations like
```yaml
metadata:
  annotations:
    retry.linkerd.io/grpc: cancelled,deadline-exceeded,internal,resource-exhausted,unavailable
```

Given that we have a path forward to make gRPC retries configurable with the newer APIs, I think we're unlikely to invest in altering the ServiceProfile retry semantics.
