### ISSUE TITLE
live path stats (top)

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#1283]
When debugging latency issues, it is nice to see the latency associated with a specific endpoint. Obviously this is difficult to do from a historical perspective, but it should be easier as a filter on top of tap.

```
# linkerd top deploy/web

INBOUND =================================
FROM                      TO                               RESOURCE                                    LATENCY    STATUS
web-5d9cdd489d-5q949      emoji-848cc76564-fmq9x           /emojivoto.v1.EmojiService/FindByShortcode  1504µs     200
web-5d9cdd489d-5q949      vote-79b9cb4dbb-bgtq8            /emojivoto.v1.VotingService/VoteSnail       1ms        OK
```

```
# linkerd top deploy/web

                            RESOURCE                                    LATENCY    STATUS

OUTBOUND =================================

emoji-848cc76564-fmq9x      .../FindByShortcode                         1504µs     200
vote-79b9cb4dbb-bgtq8       .../VoteSnail                               1ms        OK

INBOUND ==================================

FROM
10.0.0.1:40542              /api/list                                  1ms        200
10.0.0.2:57468              /api/vote                                  3ms        200
```

```
# linkerd top deploy/web

AUTHORITY                   RESOURCE                                   LATENCY    STATUS
emoji-848cc76564-fmq9x      .../FindByShortcode                        1504µs     200
vote-79b9cb4dbb-bgtq8       .../VoteSnail                              1ms        OK

AUTHORITY                   RESOURCE                                   LATENCY    STATUS
10.0.0.1:40542              /api/list                                  1ms        200
10.0.0.2:57468              /api/vote                                  3ms        200
```

```
# linkerd top deploy/web

AUTHORITY                   RESOURCE                  RPS              LATENCY    STATUS
emoji-848cc76564-fmq9x      .../FindByShortcode       2.0              1504µs     200
vote-79b9cb4dbb-bgtq8       .../VoteSnail             0.1              1ms        OK

AUTHORITY                   RESOURCE                                   LATENCY    STATUS
10.0.0.1:40542              /api/list                 3.1              1ms        200
10.0.0.2:57468              /api/vote                 0.2              3ms        200
```

## Examples

- https://github.com/lebinh/ngxtop
- http://feurix.org/projects/hatop/

**Comment by klingerf** [comment]
@grampelberg Thanks for opening this! This feature sounds great, and it seems feasible to do using tap data. I don't quite follow the examples that you added in the description.

All four examples show you running the same command (`conduit top deploy/web`), but they produce different output. Should those be different commands? Also, the last two examples appear to be identical. They also appear to have pod names in a column labeled AUTHORITY. Maybe those should be authorities instead?

In the first example, you're running `conduit top deploy/web`, but the output it showing INBOUND traffic from web pods to the emoji and vote-bot pods. In the context of the emojivoto app, I think we should be displaying INBOUND traffic from vote-bot to web (switch FROM and TO pods), and we should be displaying OUTBOUND traffic from web to emoji and voting (not vote-bot).

**Comment by grampelberg** [comment]
@klingerf I just threw up four possibilities for how it could look. I'm hunting for what `top` *should* show and so I figured we could look at a couple suggestions and see how they look.

> They also appear to have pod names in a column labeled AUTHORITY. Maybe those should be authorities instead?

What can authorities look like? Will they always be IP addresses?

(I updated the pod names so that it makes more sense)

**Comment by grampelberg** [comment]
After playing around with this a little more, something like this is feeling decent for CLI output. There should be something similar in the GUI.

```
# linkerd top deployments 

SOURCE                DESTINATION          RESOURCE             REQUESTS    RPS   LATENCY  STATUS
deployment/web        deployment/emoji     .../FindByShortcode  5           2.0   1504µs     OK
deployment/web        deployment/vote      .../VoteSnail        8           0.1   1ms        OK
deployment/vote-bot   deployment/web       /api/vote            3           1.0   3ms        500
10.0.0.1:40542        deployment/web       /api/list            9           0.0   3ms        200

# linkerd top --from=deploy/web

DESTINATION                 RESOURCE             REQUESTS    RPS   LATENCY    STATUS
deployment/emoji            .../FindByShortcode  5           2.0   1504µs     OK
deployment/emoji            .../FindByShortcode  1           0.0   10µs       ?
10.0.0.1:40542              /other/service       5           2.0   1504µs     200
statefulset/vote            .../VoteSnail        8           0.1   1ms        OK

# linkerd top --to=deploy/web 

SOURCE                      RESOURCE             REQUESTS    RPS   LATENCY    STATUS
10.0.0.1:40542              /api/list            1           3.1   1ms        200
deployment/vote-bot         /api/vote            3           1.0   3ms        200
deployment/vote-bot         /api/vote            3           1.0   3ms        500
10.0.0.2:57468              /api/vote            1           0.2   3ms        200
```

All these outputs suggest something like `--watch` by default. It would be possible to do some kind of `--wait 10s` to collect a snapshot.

**Comment by adleong** [comment]
This feels a LOT like `linkerd stat`, the only real difference being that this can show a breakdown by path whereas stat cannot.  Therefore I wonder if this command should be called `linkerd paths`.  Or should this actually be part of the stat command?  E.g. when the `--paths` flag is passed to `linkerd stat` it uses tap data instead of prometheus data?

**Comment by grampelberg** [comment]
What do you think the best way is to signal the difference between live data and "historical" @adleong? 

To help with discoverability, it feels better to have this output as a default. I like the way that `stat` works right now by default ... would having this data there by default be an improvement?

**Comment by olix0r** [comment]
As a point of reference, the `mtr` utility may be useful:

![image](https://user-images.githubusercontent.com/240738/43806606-75ed41c8-9a59-11e8-859d-72f031a67e8a.png)

**Comment by grampelberg** [comment]
A new suggestion based off the `mtr` output:

```bash
# linkerd top deployments 

SOURCE                DESTINATION          RESOURCE             COUNT  BEST WORST LAST STATUS
deployment/web        deployment/emoji     .../FindByShortcode  5      1ms  100ms 10ms OK
deployment/web        deployment/vote      .../VoteSnail        8      1ms  30ms  1ms  OK
deployment/vote-bot   deployment/web       /api/vote            3      3ms  20ms  4ms  500
10.0.0.1:40542        deployment/web       /api/list            9      3ms  3ms   3ms  200
```

**Comment by adleong** [comment]
I think the "resource" column should be called "path" instead.  Everywhere else that we talk about resources, we're talking about kubernetes resources.

@grampelberg in your suggestion above it looks like you're aggregating by source, deployment, and status.  I would guess that this would often lead to the relevant data being split across many rows.  For example, it becomes hard to answer the question "What is my SR, per-path, across all sources?".

My suggestion is to aggregate only on one column (path by default).

```
$ linkerd top svc/web

PATH                COUNT BEST   WORST   LAST SUCCESS_RATE
/index.html           5    1ms   100ms   10ms   100%
/list.json           10    3ms   30ms     4ms  50%
/admin/foo.json       2    3ms   20ms    11ms   99%
^C

$ linkerd top svc/web --path="/list.json" --by=dst
DST                COUNT BEST   WORST   LAST SUCCESS_RATE
web-65b9fffd77-k66vx  3    1ms   69ms   1ms    100%
web-65b9fffd77-4jj38d 2    1ms   89ms   1ms    0%
^C

$ linkerd top svc/web --path="/list.json" --to po/web-65b9fffd77-4jj38d --by=status
STATUS COUNT BEST   WORST   LAST SUCCESS_RATE
500    1    1ms   69ms   1ms    0%
503    6    1ms   89ms   1ms    0%
502    1    1ms   69ms   1ms    0%
```

**Comment by grampelberg** [comment]
I still like src/dst as columns. Maybe we can decide the columns based on what they're doing `top` on?

(`--by` is great)

**Comment by grampelberg** [comment]
@adleong @rmars should there be a separate issue to track implementation of this in the GUI or can/should we use this epic to track both the CLI and GUI implementation?

**Comment by rmars** [comment]
I think a separate issue for the GUI would be good! I filed #1448
