### ISSUE TITLE
tap hangs indefinitely

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#1288]
Client version: v0.5.0
Server version: v0.5.0

Using emojivoto with 50 vote-bot pods (96 RPS), running tap with the following command repeatedly eventually gets to the state where tap is hanging indefinitely.

```
# conduit -n emojivoto tap deploy/web --max-rps 10 --verbose
DEBU[0000] Expecting Conduit Public API to be served over [https://x.x.x.x/api/v1/namespaces/conduit/services/http:api:http/proxy/api/v1/]
```

Note: it appears that everything else is working fine, I can't find errors anywhere at least. Relaunching the target pod fixes the problem.

### controller/tap

```
time="2018-07-06T20:00:56Z" level=info msg="Tapping 1 pods for target: {Namespace:emojivoto Type:deployments Name:web}"
time="2018-07-06T20:00:56Z" level=info msg="Establishing tap on 10.4.1.35:4190"
```

### web/conduit-proxy

```
INFO conduit_proxy using controller at Some(HostAndPort { host: DnsName(DnsName(DNSName("proxy-api.conduit.svc.cluster.local"))), port: 8086 })
INFO conduit_proxy routing on V4(127.0.0.1:4140)
INFO conduit_proxy proxying on V4(0.0.0.0:4143) to None
INFO conduit_proxy serving Prometheus metrics on V4(0.0.0.0:4191)
INFO conduit_proxy protocol detection disabled for inbound ports {25, 3306}
INFO conduit_proxy protocol detection disabled for outbound ports {25, 3306}
INFO admin={bg=resolver} conduit_proxy::transport::connect DNS resolved DnsName(DnsName(DNSName("proxy-api.conduit.svc.cluster.local"))) to 10.7.243.70
```

**Comment by hawkw** [comment]
@grampelberg I have a suspicion this _may_ be related to #1227. I'd be really interested to know what happens if you built the proxy with `PROXY_UNOPTIMIZED=1` --- let me know if any of the proxies panic.

**Comment by grampelberg** [comment]
@hawkw got a command for me to do that? I'm lazy =(

**Comment by hawkw** [comment]
@grampelberg It's an environment variable; `$ PROXY_UNOPTIMIZED=1 bin/docker-build` & then deploy the resulting image.

**Comment by grampelberg** [comment]
Has anyone seen this recently? I'm going to close it out for now ...
