### ISSUE TITLE
Allow setting LINKERD2_PROXY_SHUTDOWN_ENDPOINT_ENABLED in helm chart

### ISSUE THREAD

**Issue by HybridFox** [linkerd/linkerd2#12951]
### What problem are you trying to solve?

I have a cronjob that stays alive because linkerd automatically injects itself (this is what we want).
Looking through github issues, it is possible to call /shutdown to shut the linkerd-proxy pod down.
This gives the `shutdown endpoint is not enabled` error because the shutdown endpoint is not enabled.
The helm chart does not give the option to enable the shutdown endpoints

### How should the problem be solved?

Allow enabling the shutdown endpoint through annotations or the helm chart

### Any alternatives you've considered?

Injecting the linkerd-proxy manually

### Would you like to work on this feature?

maybe

**Comment by alpeb** [comment]
The helm entry is `proxy.enableShutdownEndpoint`.
As a side note, you might wanna look into `proxy.nativeSidecar` if your k8s version is 1.29 or later, to avoid having to rely on the shutdown endpoint :wink:

**Comment by HybridFox** [comment]
Ah perfect! Thank you!

**Comment by alpeb** [comment]
Yes, by rolling the workloads linkerd will reinject them again, but adding the proxy as an init container instead of a regular container (see the k8s [docs on native sidecars](https://kubernetes.io/docs/concepts/workloads/pods/sidecar-containers/)).
