### ISSUE TITLE
question about multiple containers per pod, and 127.0.0.1 communication

### ISSUE THREAD

**Issue by jeroenjacobs1205** [linkerd/linkerd2#1296]
Hi,

I have a pod that contains 2 containers. One pod communicates with a server-process in the other pod over the loopback (127.0.0.1) interface.

I have the impression that this doesn't play well with Conduit, and it tries to intercept this traffic as well. 

Can someone shed a light on how loopback connections are handled? When a container connects to 127.0.0.1, is that request forwarded to the conduit_proxy container? If so, is there a way to disable this behaviour?

**Comment by olix0r** [comment]
Loopback traffic should skip the proxy, so this should work just fine; though Conduit won't have metrics for the intra-pod communication.

**Comment by jeroenjacobs1205** [comment]
Thanks for the update. I noticed the problem lies somewhere else. I'm working on a reproducible scenario and will open a new issue.
