### ISSUE TITLE
Linkerd secret extra string gets generated

### ISSUE THREAD

**Issue by mayankraipure11** [linkerd/linkerd2#13021]
### What is the issue?

extra -- is getting generated when we generate linkerd ha config files

### How can it be reproduced?

linkerd upgrade --ha --context=<cluster-name>--identity-trust-anchors-file certs/root.crt --identity-issuer-certificate-file certs/cluster1.crt --identity-issuer-key-file certs/cluster1.key >apply_controlplane1_ha.yaml
line no - 810
linkerd version
Client version: stable-2.14.10

```
---
###
### Identity Controller Service
###
---
kind: Secret
```

### Logs, error output, etc

---
###
###
---
kind: Secret

### output of `linkerd check -o short`

---
###
###
---
kind: Secret

### Environment

Kubernetes - Gardener cluster

### Possible solution

permantly remove the --- , we have to manually modify the file currently since it gets stuck

### Would you like to work on fixing this bug?

no

**Comment by alpeb** [comment]
Thanks for the report; should be fixed with #13022
