### ISSUE TITLE
Distinguish between src/dest TLS status in telemetry

### ISSUE THREAD

**Issue by hawkw** [linkerd/linkerd2#1304]
The TLS status of a connection accepted by the proxy and the corresponding connection opened by the proxy may differ for a number of reasons. For example, when a proxy is terminating an inbound TLS connection, that connection is then forwarded to the internal service as plaintext. Or, when the Destination service indicates that the destination of an outbound connection is capable of accepting TLS, but the TLS handshake with that destination fails, the proxy will (currently) fall back to plaintext.

Currently, a single `tls="..."` label is added to proxy metrics and `tap` telemetry, which is based on the TLS status of either the accepted or opened connection, depending on whether the data was recorded from the inbound or outbound proxy. We should replace this with two labels, `src_tls="..."` and `dst_tls="..."`, so that the status of both connections is reported.

This will require changes in the proxy as well as UI changes.

**Comment by hawkw** [comment]
@briansmith 
> Are there any other cases motivating this proposal?

As far as I know, the fallback logic is the primary motivation for this. However, @olix0r was the one who suggested this change, so it's possible he has additional rationale for doing this that I'm not aware of.

> We'll remove the fallback logic soon so this isn't worth any effort.

I agree that we ought to remove the fallback logic as soon as it's practical to do so. That said, I'm not currently sure what the time estimate for when that will be possible is, and I think that if we expect the fallback logic to still be in the proxy by the next release, I think we ought to at least report more information around it until it is actually removed.

**Comment by briansmith** [comment]
> I'm not currently sure what the time estimate for when that will be possible is

It needs to happen before the TLS feature can be considered "no longer experimental" and I'm actively working on it. I hope it will be removed by end of next week.

> I think we ought to at least report more information around it until it is actually removed.

Maybe, but I think there must be many, many higher-priority things to do than temporarily improve this aspect of the telemetry.

**Comment by hawkw** [comment]
> I hope it will be removed by end of next week.

Okay, I wasn't aware we were that close! That's good to hear. 

In that case, I don't think reporting information about fallbacks is terribly important. I'd close this issue now, but I'd like to hear from @olix0r first to be sure there aren't any other reasons we might want to make this change.

**Comment by olix0r** [comment]
I'm okay closing this for now.

I expect it may be useful to have `dst_tls` labels (i.e. on outbound) and `src_tls` labels on inbound so that it's less ambiguous, but I don't think this solves any concrete immediate problems.

**Comment by hawkw** [comment]
Okay, closed it for now. We can re-open this if we decide it's necessary for some other reason later!
