### ISSUE TITLE
Performance Baseline

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#1306]
There should be a document that outlines what a performance baseline is for specific metrics and how to replicate the test including instance and workload sizes. The metrics should be collected for both the data and control planes:

- CPU
- Memory
- Latency (maybe less interesting for the control plane?)
- RPS

Ideally, this would be automated via. the integration tests and produce an artifact with this data every release so that the performance impacts of specific features and releases can be codified.

**Comment by grampelberg** [comment]
@siggy do we have this yet?

**Comment by siggy** [comment]
@grampelberg this is probably the closest we have so far:
https://github.com/runconduit/conduit-examples/issues/43
...which applies to the lifecycle environment:
https://github.com/runconduit/conduit-examples/tree/master/lifecycle

**Comment by siggy** [comment]
Satisfied via https://linkerd.io/2/overview/#performance-baseline and https://github.com/linkerd/linkerd-examples/pull/226
