### ISSUE TITLE
Linkerd is blocking traffic from pod to external server when proxy injection is enabled

### ISSUE THREAD

**Issue by gabbler97** [linkerd/linkerd2#13071]
### What is the issue?

When the linkerd proxy injection is enabled in our AWS EKS 1.28 cluster and we try to curl an external endpoint we got HTTP 500 error.

```
curl -Lvk EXTERNAL_IP:8194
*   Trying EXTERNAL_IP:8194...
* Connected to EXTERNAL_IP(EXTERNAL_IP) port 8194 (#0)
> GET / HTTP/1.1
> Host: EXTERNAL_IP:8194
> User-Agent: curl/7.76.1
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< l5d-proxy-error: unexpected error
< connection: close
< l5d-proxy-connection: close
< content-length: 0
< date: Fri, 13 Sep 2024 08:39:56 GMT
<
* Closing connection 0
```

When we disable the proxy injection the connection is fine, from worker nodes the endpoint is also available.

```
kubectl exec -it my_pod -n  my_ns-- /bin/bash
bash-5.1$ curl -Lvk EXTERNAL_IP:8194
*   Trying EXTERNAL_IP:8194...
* Connected to EXTERNAL_IP(EXTERNAL_IP) port 8194 (#0)
> GET / HTTP/1.1
> Host: EXTERNAL_IP:8194
> User-Agent: curl/7.76.1
> Accept: */*
>
* Received HTTP/0.9 when not allowed
* Closing connection 0
curl: (1) Received HTTP/0.9 when not allowed
```

### How can it be reproduced?

Have an AWS EKS cluster with version 1.28
Have linkerd with and crd helm charts installed with this version
```
helm list -n linkerd
NAME                    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                           APP VERSION
linkerd-control-plane   linkerd         1               2024-09-12 16:39:55.066390527 +0000 UTC deployed        linkerd-control-plane-2024.7.5  edge-24.7.5
linkerd-crds            linkerd         1               2024-09-12 16:39:33.213349436 +0000 UTC deployed        linkerd-crds-2024.7.5
```

Enable proxy injection for a pod and try to curl an external endpoint on the internet.

### Logs, error output, etc

```
kubectl logs my-pod -c linkerd-proxy -n my_namespace
[   266.328749s]  WARN ThreadId(01) outbound:proxy{addr=EXTERNAL_IP:8194}:rescue{client.addr=10.12.66.216:41864}: linkerd_app_outbound::http::server: Unexpected error error=logical service EXTERNAL_IP:8194: route default.fallback: backend default.unknown: endpoint EXTERNAL_IP:8194: invalid HTTP version parsed error.sources=[route default.fallback: backend default.unknown: endpoint EXTERNAL_IP:8194: invalid HTTP version parsed, backend default.unknown: endpoint EXTERNAL_IP:8194: invalid HTTP version parsed, endpoint EXTERNAL_IP:8194: invalid HTTP version parsed, invalid HTTP version parsed]
```

### output of `linkerd check -o short`

```
linkerd check -o short
linkerd-identity
----------------
‼ issuer cert is valid for at least 60 days
    issuer certificate will expire on 2024-09-15T07:49:55Z
    see https://linkerd.io/2/checks/#l5d-identity-issuer-cert-not-expiring-soon for hints

linkerd-version
---------------
‼ can determine the latest version
    Get "https://versioncheck.linkerd.io/version.json?version=edge-24.7.5&uuid=3fc0bb61-9542-4c6a-8c06-78aac7797cee&source=cli": http: server gave HTTP response to HTTPS client
    see https://linkerd.io/2/checks/#l5d-version-latest for hints
‼ cli is up-to-date
    unable to determine version channel
    see https://linkerd.io/2/checks/#l5d-version-cli for hints

control-plane-version
---------------------
‼ control plane is up-to-date
    unable to determine version channel
    see https://linkerd.io/2/checks/#l5d-version-control for hints

linkerd-control-plane-proxy
---------------------------
‼ control plane proxies are up-to-date
    unable to determine version channel
    see https://linkerd.io/2/checks/#l5d-cp-proxy-version for hints

linkerd-viz
-----------
‼ viz extension proxies are up-to-date
    Get "https://versioncheck.linkerd.io/version.json?version=edge-24.7.5&uuid=unknown&source=cli": http: server gave HTTP response to HTTPS client
    see https://linkerd.io/2/checks/#l5d-viz-proxy-cp-version for hints

Status check results are √
```

### Environment

Kubernetes version: v1.28.8-eks-ae9a62a
Linkerd version (Helm):
 Chart version: linkerd-control-plane-2024.7.5
 App version:  edge-24.7.5

### Would you like to work on fixing this bug?

None

**Comment by rootik** [comment]
I don't think it's a bug.
You can use `config.linkerd.io/skip-outbound-ports` annotation if protocol detection is failing.
See [here](https://linkerd.io/2-edge/features/protocol-detection/#marking-ports-as-skip-ports)

**Comment by gabbler97** [comment]
Thank you very much @rootik !
It is working!

**Comment by wmorgan** [comment]
1) There is no reason to suspect this has anything to do with protocol detection
2) The skip ports annotation circumvents Linkerd for that port. So you haven't fixed anything, you've just bypassed Linkerd
3) When you say "When we disable the proxy injection the connection is fine" your evidence doesn't really support that. Your curl output shows an error, "Received HTTP/0.9 when not allowed", which is typically what curl says when the server is not responding with proper HTTP.

**Comment by mareklubinski** [comment]
> 1. There is no reason to suspect this has anything to do with protocol detection
> 2. The skip ports annotation circumvents Linkerd for that port. So you haven't fixed anything, you've just bypassed Linkerd
> 3. When you say "When we disable the proxy injection the connection is fine" your evidence doesn't really support that. Your curl output shows an error, "Received HTTP/0.9 when not allowed", which is typically what curl says when the server is not responding with proper HTTP.

you are totally right @wmorgan it only disables linkerd for this specific outgoing port.
but as it was shown in the description, it was clear that it's denied/blocked by LinkerD (when enabled), so we are puzzled, HOW can we identify WHAT EXACTLY causes LinkerD to block the connection (timeout).
Any idea ? logs from linkerd don't bring much value here.

**Comment by rootik** [comment]
@gabbler97 what protocol runs on that external host port exactly? Is it TLS?

**Comment by mareklubinski** [comment]
> @gabbler97 what protocol runs on that external host port exactly? Is it TLS?

we are checking this with responsible persons, and when we know this - we will let you know.
in the meantime, is there any other way to "somehow" investigate what is the reason ? should it be somehow visible in linkerd logs, or some other place ? what set of conditions (on linkerd) could cause this timeout?

**Comment by wmorgan** [comment]
You can enable debug logs on the proxy and see if anything comes up. https://linkerd.io/2-edge/tasks/modifying-proxy-log-level/

**Comment by gabbler97** [comment]
Sorry for not answering for a while! Thank you for the help we got from you already!
Here are the logs in debug mode from the sidecar proxy while I try to curl the endpoint.
[logs-linkerd-proxy-debug-mode.txt](https://github.com/user-attachments/files/17059414/logs-linkerd-proxy-debug-mode.txt)

**Comment by gabbler97** [comment]
Hi folks!
Do you have any clue?
Thank you for your answer in advance!

**Comment by wmorgan** [comment]
Those logs suggest that the client is speaking HTTP but the server is not speaking HTTP. In this case, the proxy returning a 500 is reasonable.

Note that your original curl command returned an error, which is consistent with this hypothesis.

You can reproduce this at home:
(in window 1) `nc -l 8000`
(in window 2) `curl -v localhost:8000`
(in window 1) type in "not http" and press enter
