### ISSUE TITLE
rfc: tap dashboard

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#1309]
It would be nice to have tap move into the dashboard. A user could navigate the tap filters by clicking on either stat output or the topology graph.

Here's a super rough sketch of how it might look as a sidebar.

![screenshot 2018-07-11 17 05 35](https://user-images.githubusercontent.com/47992/42605411-a9b2a54e-852c-11e8-8248-5c2eb0a30190.png)

**Comment by rmars** [comment]
@grampelberg can we close this issue now?

**Comment by grampelberg** [comment]
@rmars do the honors!

**Comment by rmars** [comment]
Fixed by #1356, #1371, #1391, #1398, #1409, #1444, #1446, #1569, #1623, #1643
