### ISSUE TITLE
How can i make HAZL work on EKS?

### ISSUE THREAD

**Issue by bruno-notifi** [linkerd/linkerd2#13132]
### What is the issue?

HAZL is not working on EKS.

#### Description

I did follow https://docs.buoyant.io/buoyant-enterprise-linkerd/latest/tasks/enabling-hazl/

- Kubernetes cluster with three zone-labeled nodes (zone-0|zone-1|zone-2)
- [Buoyant Enterprise for Linkerd](https://docs.buoyant.io/buoyant-enterprise-linkerd/latest/installation/) installed
- The BUOYANT_LICENSE environment variable set, with functioning BEL CLI

I noticed on EKS node labels, that I have *topology.kubernetes.io/zone=us-west-2[a|b|c]*. However, EKS' Console shows  topology.kubernetes.io/zone=zone-[0|1|2], which is not shown with kubectl. 

### Question

What can be done? What is missing? Can i change the node label HAZL is looking for?

HAZL is not working

Best,

Bruno

Update:
https://linkerd.buoyant.io/t/i-cannot-make-hazl-work-on-eks/611

**Comment by wmorgan** [comment]
@bruno-notifi Since this is a BEL-only feature, would you mind posting this question [here](https://linkerd.buoyant.io/) instead? Thank you.

**Comment by GTRekter** [comment]
Hi Bruno,

AKS, EKS, and clusters provided by CSPs generally enforce their own topology on the nodes. The following is an example using AKS.
```

$ kubectl get nodes --show-labels | grep topology.kubernetes.io/zone
aks-hazlpoolha-33634351-vmss000000   Ready    <none>   33h     v1.29.8   agentpool=hazlpoolha,...topology.kubernetes.io/zone=koreacentral-1
aks-hazlpoolha-33634351-vmss000001   Ready    <none>   33h     v1.29.8   agentpool=hazlpoolha,...topology.kubernetes.io/zone=koreacentral-2
aks-hazlpoolha-33634351-vmss000002   Ready    <none>   7m16s   v1.29.8   agentpool=hazlpoolha,...topology.kubernetes.io/zone=koreacentral-3
```

However, it’s not mandatory to use zone-labeled nodes (e.g., zone-0, zone-1, zone-2). The zone label requirement is primarily for deploying the colorz application as-is, as detailed here: [Buoyant HAZL documentation](https://docs.buoyant.io/buoyant-enterprise-linkerd/latest/tasks/enabling-hazl/), and HAZL work with different labels, as long as the pods are in separate nodes.

You can find an example of HAZL deployment using different topology labels here: [HAZL Deployment Example](https://github.com/BuoyantIO/service-mesh-academy/blob/main/eliminate-cross-zone-traffic-hazl/cluster/demo-cluster-orders-hazl-large.yaml).
