### ISSUE TITLE
Merge proxy-init and linkerd-inject

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#1318]
I propose that this repo's `proxy-init` project be merged into [`linkerd-inject`](https://github.com/linkerd/linkerd-inject) as linkerd-inject 2.0.0.

Not only do these codebases overlap significantly, but they also change very infrequently and shouldn't be needlessly built & published with the linkerd2 project.

**Comment by briansmith** [comment]
> I propose that this repo's proxy-init project be merged into linkerd-inject as linkerd-inject 2.0.0.

I think this is OK as long as we don't require that changes to linkerd2-inject force both linkerd1 and linkerd2 to be updated to match the change. That is, we should be able to release an upgraded version of linkerd2-inject and linkerd2-proxy without having to first make linkerd1 work with the new version of linkerd2-inject (linkerd1 can just continue using the older version).

> Not only do these codebases overlap significantly

OK

> they also change very infrequently and shouldn't be needlessly built & published with the linkerd2 project.

As far as the impact on the build/publish process goes, I don't think that's a good motivation to split it out into its own repo. The more repos we have the harder it is going to be to create a good and easy-to-understand build system that builds everything fast. That is, I expect that splitting linkerd2 into multiple repos will (continue to) impede making a truly efficient build system. My preference therefore would be to keep all our linkerd2 Go stuff (at least) together in one repo.

**Comment by adleong** [comment]
As far as I'm aware, linkerd-inject is basically unused.  I am in favor of completely replacing it with the inject code from Linkerd2.  No changes in Linkerd1 will be necessary.
