### ISSUE TITLE
Issue with proxy.nativeSidecar=true Flag: Linkerd Proxy Doesn't Exit After Main Container Termination

### ISSUE THREAD

**Issue by anushaswas** [linkerd/linkerd2#13205]
### What is the issue?

I am encountering an issue with the proxy.nativeSidecar=true flag, which is supposed to automatically shut down the Linkerd proxy when the main container terminates. According to the documentation, this feature was introduced in Kubernetes v1.28 and should be available by default in Kubernetes v1.29.
annotations:
  linkerd.io/inject: enabled
  config.linkerd.io/proxy-native-sidecar: "true"

Am I missing any configuration or setup? Or could this be a bug with the native sidecar feature? Any help or insights would be greatly appreciated.

### How can it be reproduced?

Steps to Reproduce:
Deploy a pod with the proxy.nativeSidecar=true configuration.
Run a short-lived main container (e.g., a simple gRPC client).
Observe that the main container terminates, but the Linkerd proxy continues running.

### Logs, error output, etc

NA

### output of `linkerd check -o short`

NA

### Environment

-kubernetes Version: - v1.30.4
-Cluster environment:- EKS
- Linkerd version: - edge-24.10.1

### Would you like to work on fixing this bug?

None

**Comment by alpeb** [comment]
Can you confirm the annotation you used? It should be `config.alpha.linkerd.io/proxy-enable-native-sidecar: true`

**Comment by anushaswas** [comment]
The isssue has been resolved. Thanks!
