### ISSUE TITLE
proxy: `make docker` appears to use the value of `DOCKER_TAG` for the image name rather than the image tag

### ISSUE THREAD

**Issue by hawkw** [linkerd/linkerd2#1323]
It appears that the `make docker` recipe in the linkerd/linkerd2-proxy `Makefile` uses the value of the `DOCKER_TAG` environment variable for the _name_ of the produced image rather than the _tag_.

For example:, consider the following output from `make docker` (truncated  for brevity): 

```
➜ DOCKER_TAG=liza-test-1231 make docker
docker build -t liza-test-1231 .
Sending build context to Docker daemon  916.5kB
Step 1/20 : ARG RUST_IMAGE=rust:1.27.1
Step 2/20 : ARG RUNTIME_IMAGE=gcr.io/linkerd-io/base:2017-10-30.01
Step 3/20 : FROM $RUST_IMAGE as build

# ... snip ...

Step 20/20 : ENTRYPOINT ["/linkerd/linkerd2-proxy"]
 ---> Running in 78e48a4a6a3e
Removing intermediate container 78e48a4a6a3e
 ---> 2605dd9dce86
Successfully built 2605dd9dce86
Successfully tagged liza-test-1231:latest
```

Note that the build ends with `Successfully tagged liza-test-1231:latest` rather than `Successfully tagged linkerd2-proxy:liza-test-1231` as I'd expect it to.

Similarly, `docker images` shows a `liza-test-1231:latest` image rather than a `linkerd2-proxy:liza-test-1231` image:

```
➜ docker images
REPOSITORY                                               TAG                         IMAGE ID            CREATED             SIZE
liza-test-1231                                           latest                      2605dd9dce86        37 minutes ago      117MB
```

**Comment by hawkw** [comment]
Pretty sure I know what's wrong, hopefully I'll have a PR to fix this momentarily.

**Comment by hawkw** [comment]
Ah, never mind, it appears this is working as intended. To quote the proxy's README:

> `make docker` -- Builds a Docker container image that can be used for testing. If the `DOCKER_TAG` environment variable is set, the image is given this name. Otherwise, the image is not named.

I was just expecting this to behave closer to the way it did prior to the repo split, my bad.

**Comment by olix0r** [comment]
I'd be open to renaming the env variable if it's confusing. I was trying to mimic `docker build` terminology as closely as possible.
