### ISSUE TITLE
CRD: HTTPLocalRateLimitPolicy install issue

### ISSUE THREAD

**Issue by karendavtyangb** [linkerd/linkerd2#13295]
### What is the issue?

ArgoCD sync keep outofsync when upgrading 24.11.2

### How can it be reproduced?

Syncing  CRD 24.11.2

### Logs, error output, etc

![image](https://github.com/user-attachments/assets/30190c9b-6af3-494f-a1cf-df1dd37ebc74)
![image](https://github.com/user-attachments/assets/e9b0de0d-9987-4274-b6b6-131793ec375c)

### output of `linkerd check -o short`

<img width="584" alt="image" src="https://github.com/user-attachments/assets/cf132e38-b9f5-4135-b914-5203423e2e7e">

### Environment

EKS

### Would you like to work on fixing this bug?

None

**Comment by alpeb** [comment]
Thanks for the report, will address this ASAP!
