### ISSUE TITLE
TLS logic in `transport::connection` needs tests

### ISSUE THREAD

**Issue by briansmith** [linkerd/linkerd2#1329]
Right now we don't have a great way of testing any of the logic in `transport::connection` independently of the higher-level (Tower, etc.) stuff. For example, we don't have a way to test things like #1272. This has lead to productivity-disrupting problems in the past, e.g. the issue fixed by linkerd/linkerd2-proxy@b9b35ec11c39e7dba168a7e302d5f58889c89398 [fixed].

**Comment by hawkw** [comment]
I suspect the git SHA above is intended to refer to linkerd/linkerd2-proxy@b9b35ec11c39e7dba168a7e302d5f58889c89398?
