### ISSUE TITLE
Limit scraping for bundled Prometheus

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#1332]
Ensure that the bundled prometheus only polls things related to the specific control and data plane that the bundled prometheus is associated with.

Note: this might already be the case, just need the validation and paper trail.

**Comment by klingerf** [comment]
As part of this change we should also update the proxy scrape targets to only scrape proxies that are configured to point to the controller namespace where the prometheus instance is running. Right now each prometheus instance will scrape all injected proxies in the cluster, regardless of which controller they're using. We should be able to filter out proxies that are pointing at other controllers by using a label filter in the relabel config. cc @olix0r

**Comment by klingerf** [comment]
Once #1402 merges, prometheus will only be scraping proxies and control plane components configured with the same controller namespace, which should mostly fix this issue.

It's still the case that all linkerd installations will be scraping the same node metrics, however, via the `kubernetes-nodes-cadvisor` config. We should decide if that's an issue or not, and if so consider removing that scrape config and the associated kubernetes.json dashboard that displays those stats.
