### ISSUE TITLE
Audit CLI command failure states

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#1334]
Verify that any CLI command which interacts with the cluster outputs valid user error messages for failures. 

There are many errors returned by underlying libraries that we can't exactly pinpoint what is going on. For these errors, steer the users to `conduit check` so that we can pinpoint what's going on a little bit better.

- [ ] `dashboard`
- [ ] `get`
- [ ] `stat`
- [ ] `tap`

**Comment by klingerf** [comment]
This was fixed by #1428.
