### ISSUE TITLE
Document basic principles of how the proxy works

### ISSUE THREAD

**Issue by hawkw** [linkerd/linkerd2#1345]
Issue #1299 was caused by a nginx configuration that rewrote requests' `Host:` headers in a way that broke the proxy's routing. When explaining what caused this problem, I was [somewhat surprised](https://github.com/linkerd/linkerd2/issues/1299#issuecomment-405743951) that there's currently nowhere in the user-facing documentation that states that the proxy routes requests based on authorities, let alone discuss any of the potential implications of this.

Therefore, I think we ought to have either a new page in the documentation or a section in the "Overview" documentation where we discuss the basics of how the proxy works. I don't think it's necessary to provide a detailed description of proxy internals, but we ought to summarise the important details about its _behaviour_ --- how it interacts with the injected application, how requests are routed, et cetera. Then, perhaps we ought to also discuss some of the potential effects of these behaviours (e.g. "don't rewrite host headers or your requests may not go where you expect them to" and so on).

**Comment by grampelberg** [comment]
@hawkw mind taking this one off your plate for the time being?
