### ISSUE TITLE
Default outbound policies ignore default opaque-ports

### ISSUE THREAD

**Issue by wvidana** [linkerd/linkerd2#13475]
### What is the issue?

We have an app that connects to a MySQL server outside of cluster (outside of our VPC really). We are seeing in the linkerd logs:
```
INFO ThreadId(01) outbound:proxy{addr=172.32.X.X:3306}: linkerd_detect: Continuing after timeout: linkerd_proxy_http::version::Version protocol detection timed out after 10s
```

After looking at the official docs we decided that we had to set `config.linkerd.io/enable-external-profiles: 'true'` on the pods, since port 3306 is in the default list for opaque ports https://linkerd.io/2-edge/features/protocol-detection/#configuring-protocol-detection

But we are still getting the `Version protocol detection timed out after 10s`. Not sure how to debug it more, because it doesn't happen on every connection, only once in a while.

Related issue https://github.com/linkerd/linkerd2/issues/8273

### How can it be reproduced?

From a meshed pod try to connect to an external mysql (port 3306). You'll see in the proxy containers logs with `Version protocol detection timed out after 10s`. Add the annotation `config.linkerd.io/enable-external-profiles: 'true'` on your pods and restart them (so new proxies will be launched with the annotation in the main pods).

If the issue is in there, then you'll continue to see the log `Version protocol detection timed out after 10s`, even thought linkerd is supposed to treat the port 3306 as opaque for external connections once the option `enable-external-profiles` is set. 

### Logs, error output, etc

```
INFO ThreadId(01) outbound:proxy{addr=172.32.X.X:3306}: linkerd_detect: Continuing after timeout: linkerd_proxy_http::version::Version protocol detection timed out after 10s
```

### output of `linkerd check -o short`

```
linkerd-version
---------------
‼ cli is up-to-date
    is running version 24.6.3 but the latest edge version is 24.11.8
    see https://linkerd.io/2/checks/#l5d-version-cli for hints

control-plane-version
---------------------
‼ control plane is up-to-date
    is running version 24.6.3 but the latest edge version is 24.11.8
    see https://linkerd.io/2/checks/#l5d-version-control for hints

linkerd-control-plane-proxy
---------------------------
‼ control plane proxies are up-to-date
    some proxies are not running the current version:
	* linkerd-destination-7b5c7554cc-r7mmp (edge-24.6.3)
	* linkerd-destination-7b5c7554cc-tl9rz (edge-24.6.3)
	* linkerd-destination-7b5c7554cc-vxhv9 (edge-24.6.3)
	* linkerd-identity-5db89976c6-slxpj (edge-24.6.3)
	* linkerd-identity-5db89976c6-t8gj8 (edge-24.6.3)
	* linkerd-identity-5db89976c6-v2l9k (edge-24.6.3)
	* linkerd-proxy-injector-666b7ddcb-2z6h4 (edge-24.6.3)
	* linkerd-proxy-injector-666b7ddcb-fxb7d (edge-24.6.3)
	* linkerd-proxy-injector-666b7ddcb-r5tdw (edge-24.6.3)
    see https://linkerd.io/2/checks/#l5d-cp-proxy-version for hints

Status check results are √
```

### Environment

- Kubernetes version: 1.29
- Cluster environment: EKS (aws)
- Host OS: docker image`ruby:3.1.2` (based on debian)
- Linkerd version: `24.6.3` from edge

### Possible solution

It looks like a regression from https://github.com/linkerd/linkerd2/issues/8273

### Additional context

The external mysql server is on a 172.32.X.X ip, which looks like a private IP but it is not. The internal range is `172.16.0.0 – 172.31.255.255`, which is actually what our cluster uses for the services with `ClusterIP`

### Would you like to work on fixing this bug?

None

**Comment by olix0r** [comment]
Yeah, I think you've spotted a real problem with the default policies by the control plane--3306 is in the default opaque list, but it looks like this hint isn't being served to proxies.

If you update to a recent edge release, we can work around this problem with an [`EgressNetwork`](https://linkerd.io/2-edge/reference/egress-network/) resource:

```yaml
---
apiVersion: v1
kind: Namespace
metadata:
  namespace: linkerd-egress
spec:
  trafficPolicy: Allow
...
---
apiVersion: policy.linkerd.io/v1alpha1
kind: EgressNetwork
metadata:
  namespace: linkerd-egress
  name: all
...
```

With these resources in place, I would expect the protocol hinting to work as intended.

**Comment by wvidana** [comment]
Great! the `EgressNetwork` changes seems to fix the issue. Just to clarify, to see if I have understand this correctly:

This is allowing all traffic, as if we didn't have any egress rules, but just having the manifest signals linkerd to apply the correct logic for default opaque ports. Do I still need to use the annotation `config.linkerd.io/enable-external-profiles: 'true'` on the necessary pods?

**Comment by olix0r** [comment]
> Great! the `EgressNetwork` changes seems to fix the issue.

Excellent.

> This is allowing all traffic, as if we didn't have any egress rules, but just having the manifest signals linkerd to apply the correct logic for default opaque ports. 

Yeah that's basically right. The "default" policies served to proxies (i.e. when there is no known Service or Pod at the target IP) do not properly provide opaque port hints. This is still a bug that we should fix.

The `EgressNetwork` resource puts the control plane in a mode where, instead of returning a "default" policy, it returns an egress policy. This _does_ properly include the opaque hint.

> Do I still need to use the annotation `config.linkerd.io/enable-external-profiles: 'true'` on the necessary pods?

This is not necessary.

**Comment by wvidana** [comment]
Fantastic! Thanks so much for the help. You can see in the graph that the error message disappeared once we applied the changes you proposed
![image](https://github.com/user-attachments/assets/a32bfcf4-a928-4248-8c97-d38da4c418e8)
