### ISSUE TITLE
Use of stale TLS configuration isn't limited

### ISSUE THREAD

**Issue by briansmith** [linkerd/linkerd2#1349]
The trust anchor settings and the (private key, certificate) for a pod are updated asynchronously and so they may be out of sync. Our current strategy is to use the last valid configuration loaded until a new valid configuration is loaded, without any time limit. However, an inconsistent configuration that persists for a long time is indicative of a serious problem. We should limit the duration that a stale configuration is used due to a newer invalid configuration being available.

**Comment by hawkw** [comment]
@briansmith Do you think that we should limit the TTL of the TLS configuration only if the proxy has seen changes to the configuration files that were invalid, or is it acceptable for a loaded configuration to become invalid after the time limit even if we haven't yet seen any additional changes to the configuration files?
