### ISSUE TITLE
Periodic Server Closed Idle Connection on /tps-reports endpoint causing UI Error Message

### ISSUE THREAD

**Issue by christopherhein** [linkerd/linkerd2#1352]
Running on Amazon EKS the Dashboard will pop up a red error message when the `/api/v1/namespaces/linkerd/services/web:http/proxy/api/tps-reports?resource_type=namespace&all_namespaces=true&window=1m` endpoint returns:

```json
{
  "error":"Post http://api.linkerd.svc.cluster.local:8085/api/v1/StatSummary: http: server closed idle connection"
}
```

<img width="1233" alt="screen shot 2018-07-18 at 6 05 57 pm" src="https://user-images.githubusercontent.com/177822/42916132-8793170a-8ab8-11e8-91c2-2b058e7e5cfd.png">

**Comment by klingerf** [comment]
Thanks for reporting this, @christopherhein! It sounds like the same issue as the one described in #580. We haven't been able to track down the root cause yet, but stay tuned.

**Comment by christopherhein** [comment]
Thanks @klingerf closing in favor of that, will post a screenshot for the updated Linkerd UI as well
