### ISSUE TITLE
Evaluate the possibility of supporting other schedulers.

### ISSUE THREAD

**Issue by ghost** [linkerd/linkerd2#1354]
At trivago we are using Linkerd together with Nomad and Consul. Now that Linkerd and Conduit are merging into a single product it would be interesting to know if it possible/feasible to support other schedulers than Kubernetes and how that would work.

I don't have much knowledge of Conduit but I can find as much information as possible if it's needed of our current setup with Linkerd and Nomad if it can help with the discussion.

**Comment by grampelberg** [comment]
Also #30

**Comment by perrymanuk** [comment]
I would like to 2nd this request, we are also currently using linkerd in production with nomad/consul and would love to have the ability to use linkerd2 in our environment.

**Comment by siggy** [comment]
This may be possible via a change in Namerd (https://github.com/linkerd/linkerd/issues/2060)

**Comment by hawkw** [comment]
linkerd/linkerd#2060 (adding a Namerd interface that exposes the Linkerd 2 proxy's Destination API) is also relevant for folks using Linkerd 1 in environments other than Kubernetes. 

Currently, one of the biggest obstacles to using the Linkerd 2 proxy outside of Kubernetes is that the proxy relies on the Destination API exposed by the Linkerd 2 control plane for service discovery, and the control plane is Kubernetes-specific. Allowing Namerd to expose the same API would make it possible to use Linkerd 2's proxy in an existing Linkerd 1 installation.

**Comment by wmorgan** [comment]
@perrymanuk @lifk It's great to hear you're interested in this. This is an active area of discussion for us. The issues linked above are some potential first steps, but basically this requires some non-trivial design work that we're deferring until after a GA release.

**Comment by davidbarsky** [comment]
I have some context on ECS et. al.: with AWS' service discovery service ([Cloud Map](https://aws.amazon.com/cloud-map/)) there _should_ be feature parity between what Kubernetes provides and what y'all need. I'm _not_ aware of what changes will be required in Linkerd2 to support ECS et. al., but it's that's one option.

**Comment by chenjpu** [comment]
Is there any plan or progress?

**Comment by wmorgan** [comment]
@chenjpu It's on the roadmap, but isn't currently being worked on or designed.

**Comment by jayed** [comment]
Throwing in my vote for this. (Hi!)

**Comment by grampelberg** [comment]
As of today, we are not planning on supporting any other schedulers. We'd love to work with someone who's interested in implementing a new control plane for their scheduler. I'll be closing this issue out as a generic tracking issue. Anyone interested in contributing a new control plane for their scheduler of choice, please open up a new issue so we can start working with you on it.
