### ISSUE TITLE
Large responses causing errors 

### ISSUE THREAD

**Issue by cemo** [linkerd/linkerd2#1357]
I am trying to learn `linkerd2` and I am completely new to service mesh land. My initial tests have caused some troubles in our system under load. %1 of our requests return 500 codes. Is this something known? We have really large responses like 150 elements product lists and usually close to the end such as 130 nth item is broken in our clients. It is like interrupted by services and content is partial in the client.

**Comment by hawkw** [comment]
I'd be interested to see the logs from the `linkerd-proxy` containers in the pods that are showing an elevated error rate.
