### ISSUE TITLE
Prefer HTTP2 for Proxy-to-Proxy messages

### ISSUE THREAD

**Issue by seanmonstar** [linkerd/linkerd2#1360]
While #559 exists for the general concept of trying to upgrade any HTTP1 request via h2c, this feels like a separate thing. One of the reasons #559 is still open is because it turns out always sending the `upgrade: h2c` header in every request can result in some servers wrongly closing connections since they don't understand it.

When the proxy is going to talking to another proxy, we can try to coalesce HTTP/1.1 requests over a single HTTP2 connection, greatly reducing resources needed. We'd probably want to start conservatively, to reduce any breakage if we're wrong about there being a proxy on the other side. Some strategies I can think:

- Employ our knowledge of the TLS identities we get from the controller, which can allow us to know for certain that the other side is another linkerd proxy. A downside here is that if TLS is not being used, we won't be upgrading to HTTP2, even if we could be. However, this way feels like the way to be certain we won't break middle layers.
- We could *try* sending an alternative header to `upgrade: h2c`, some sort of `linkerd2-proxy: hello` or what-have-you. That way if the other side isn't a proxy, it doesn't get upset at an `upgrade: h2c` header, but if it *is* a proxy, we could initiate an upgrade. A downside to this is that it is possible that some other proxy is between the two linkerd2 proxies, and may not actually know HTTP2, in which case we'd be broken.

Regardless of strategy chosen, some additional things we should keep in mind:

- Upgraded requests should include a custom header that the other proxy needs to downgrade the request back into HTTP/1.1 before passing on.
- We should be careful with HTTP/1.0 or HTTP/1.1 requests that have no `host` header. They may be relying on some server software that expects the requests to use different connections. Though, with care, it may be possible to upgrade even those, as long as the other proxy is able to still determine it should treat it that same as receiving an HTTP/1.0 or 1.1 with no host.

**Comment by olix0r** [comment]
I've been thinking that this works as follows (especially given that we don't have ALPN, etc (yet):

1. When a proxy routes an outbound request, it contacts the destination service, which provides endpoint-level metadata. The destination service knows whether the endpoint has the proxy or not, and can return a protocol hint when appropriate.
2. If the outbound request is HTTP/1.1 and does not have an `Upgrade` header set and hits an endpoint with this protocol hint, an H2 connection is used.  The proxy sets the `l5d-orig-proto` header on the request with a value of `HTTP/1.1`.
3. The remote peer's inbound proxy terminates H2, notices and strips the `l5d-orig-proto` header, and forwards the request as HTTP/1.1 to the application.

**Comment by seanmonstar** [comment]
> The destination service knows whether the endpoint has the proxy or not, and can return a protocol hint when appropriate.

To be clear, are you suggesting an additional value returned via [`WeightedAddr`](https://github.com/linkerd/linkerd2-proxy-api/blob/c1858095ccb396444669442e7ae78a79ff7a5ac6/proto/destination.proto#L84) besides the TLS identity? We *could* use the identity immediately, but with an additional field, we could try to use HTTP2 to other proxies even in cleartext.

One benefit I can think of for possibly only doing this over TLS is that then we can know for sure that there is no HTTP proxy in the middle that is silently passing our messages along that we could break.

**Comment by olix0r** [comment]
> To be clear, are you suggesting an additional value returned via WeightedAddr besides the TLS identity?

Yeah, that's what I was thinking. Bypasses the need for fancy inference/discovery, can can work for any proxy configuration if the destination service participates.

**Comment by seanmonstar** [comment]
What about cases where an HTTP proxy was actually between the two proxies and we've suddenly broke it? We probably can't just say "don't do that"...

**Comment by olix0r** [comment]
@seanmonstar I think that might be Just Fine for the current linkerd2 deployment model -- I'm having a tough time coming up with a way that I could insert a transparent HTTP proxy between two pods if I _wanted_ to.

I totally agree that we'll need a better story long-term as we see more diverse deployments, but in the short term I'm happy to say that the Destination service can be authoritative.  We could disable this feature in the Destination service by honoring k8s attributes, for instance.

**Comment by briansmith** [comment]
What @olix0r described sounds good to me.

Is there any way we can communicate the original protocol version in HTTP/2 without using HTTP header fields, e.g. settings?

**Comment by seanmonstar** [comment]
@briansmith is there an underlying motivation to why you ask? We'd hopefully be reusing an existing HTTP2 connection, so this information is really per-request, which headers are normally how you pass information specific to a request.

**Comment by briansmith** [comment]
OK, that sounds fine to me.

**Comment by seanmonstar** [comment]
It seems then that the work to be done can be divided in 3, with the first likely needing to be done first:

1. Adjust the [`WeightedAddr`](https://github.com/linkerd/linkerd2-proxy-api/blob/c1858095ccb396444669442e7ae78a79ff7a5ac6/proto/destination.proto#L84) of the Destination API to include a field that states whether the destination has a proxy injected. Is there any reason this shouldn't just be a boolean of yes or no?
2. Update the controller to set this field in the API, which should be straight forward, since we already have annotations that the service is managed by linkerd.
3. Update the proxy to look for this field, and if it indicates the other side is a proxy, use an h2 connection instead of h1, and set the header field. Additionally, when accepting h2 connections, it should look for that `l5d-orig-proto` header and if found, treat the request as h1.

**Comment by seanmonstar** [comment]
Since this means translating HTTP1 messages into HTTP2, that involves a little bit of normalizing, specifically around the `host` header being converted into `:authority`. The original state is lost in the translation. But as we're sending a special header, `l5d-orig-proto`, it seems that this state could be encoded in the value of it. It could encode the literal values of `host` and `req.uri()`, or it could just encode flags about whether the URI was relative or absolute, and whether the host header was set.

As an example, this HTTP1 request:

```
GET /foo/bar HTTP/1.1
host: exam.ple.svc.cluster.local
```

Could be translated to:

```
:method = GET
:scheme = http
:authority = exam.ple.svc.cluster.local
:path = /foo/bar
l5d-orig-proto = HTTP/1.1; relative-uri; with-host
```

**Comment by olix0r** [comment]
@seanmonstar that proposed syntax of `l5d-orig-proto` seems good to me. we'd probably want to write up mini spec for the header semantics...

**Comment by seanmonstar** [comment]
All the pieces have been merged, this is done!
