### ISSUE TITLE
[question] Transparent TLS between HTTP services

### ISSUE THREAD

**Issue by caio1982** [linkerd/linkerd2#1368]
Hi, I am sorry this might not be a bug report but perhaps it can become a documentation improvement thingy... does Conduit support transparent TLS between existing services talking to each other via HTTP? That is, the example app uses gRPC, so existing services must start using gRPC in order to benefit from Conduit? Is that correct? If existing services talking through HTTP to each other can actually use Conduit and TLS (and I understand Conduit's transparent TLS support is pretty nice), I couldn't find a clear example of this in the docs, i.e. what would such apps need to do to use Conduit...

**Comment by seanmonstar** [comment]
Hey there! The example uses gRPC, but linkerd2 supports HTTP/1, HTTP2, gRPC, and TCP. You can see how to get started with this doc: https://conduit.io/getting-started/

**Comment by olix0r** [comment]
In order to configure transparent TLS, see the instructions at https://conduit.io/automatic-tls/

**Comment by grampelberg** [comment]
Great question! For services that have been meshed, any TCP based protocol (http/1, http2, gRPC) will benefit from the transparent TLS.

(As an interesting tidbit, gRPC is actually just an http2 based protocol, functions even get HTTP paths!)

@caio1982 what do you think is the best way to improve the docs so that it is a little more apparent?

**Comment by caio1982** [comment]
Thanks a lot for the answers, folks! Dunno @grampelberg maybe it is just wording that could be changed to be more explicit and some actual example from plain HTTP to transparent TLS using the service mesh (IMHO the ultimate migration path for someone looking for the service mesh to solve the encryption problem they have, like myself!) :-) keep up the great work, thanks a lot!

**Comment by briansmith** [comment]
> Great question! For services that have been meshed, any TCP based protocol (http/1, http2, gRPC) will benefit from the transparent TLS.

Only HTTP-based protocols, i.e. http/1 and http/2 (including gRPC), work with automatic TLS right now. See #1253.

**Comment by grampelberg** [comment]
@caio1982 any other questions or can we close this out?
