### ISSUE TITLE
Control plane setup issue with conduit on my kubernetes cluster on my Windows 10 PC

### ISSUE THREAD

**Issue by pritishpkp** [linkerd/linkerd2#1374]
Hi All. I have been trying to have a setup of conduit on my kubernetes cluster on my Windows 10 PC.
While following getting started from official Guide, I am stuck at a weird place. When I do conduit install to have Conduit control plave installed and dashboard, it creates all deployments and services, but
1. It does not update the server version, hence it does not deploy the conduit namespace. Hence dashboard is not able get started
2. When I do conduit check, it gives me below output
kubernetes-api: can initialize the client..................................[ok]
kubernetes-api: can query the Kubernetes API...............................[ok]
kubernetes-api: is running the minimum Kubernetes API version..............[ok]
conduit-api: can query the Conduit API.....................................[ERROR] -- error reading byte stream header: error while reading bytes from message: unexpected EOF
conduit-version: control plane is up-to-date...............................[ERROR] -- error reading byte stream header: error while reading bytes from message: unexpected EOF

Status check results are [ERROR]

**Comment by wmorgan** [comment]
@pritishpkp thanks for filing this! We'll take a look

**Comment by klingerf** [comment]
Hey @pritishpkp, thanks for reporting this.

The repo is transitioning from conduit to linkerd at present, so some of the documentation is a bit outdated. Would you mind trying to reinstall using the latest version of the `linkerd` binary, by following [these instructions](https://github.com/linkerd/linkerd2#getting-started-with-linkerd2).

Once you've run `linkerd install`, can you also paste the output of the following commands:

* `kubectl -n linkerd get po`
* `kubectl -n linkerd logs $(kubectl -n linkerd get po -oname | grep controller) linkerd-proxy`
* `kubectl -n linkerd logs $(kubectl -n linkerd get po -oname | grep controller) public-api`
* `kubectl -n linkerd logs $(kubectl -n linkerd get po -oname | grep web) linkerd-proxy`

That should hopefully help us figure out what's going on. We're also working to add more of this diagnostic information to the linkerd command itself.
