### ISSUE TITLE
`linkerd inject` can be extended to read from folder

### ISSUE THREAD

**Issue by ihcsim** [linkerd/linkerd2#1376]
Currently, `linkerd inject` only takes a single file as its argument. It can be extended to recursively read multiple resource files from a folder.

Usage:
```
linkerd inject <folder> | kubectl apply -f -
```

Since `kubectl create|apply|delete` already supports recursive read from a folder, this shouldn't be hard to do. I can submit a PR for review if there is enough interest.

References:
1. [pkg/kubectl/genericclioptions/resource/builder.go](https://github.com/kubernetes/kubernetes/blob/2ffbaa13d0c02bb2523d0d20946b4b9c6f18cd14/pkg/kubectl/genericclioptions/resource/builder.go#L330-L361)
1. [pkg/kubectl/genericclioptions/resource/visitor.go](https://github.com/kubernetes/kubernetes/blob/2ffbaa13d0c02bb2523d0d20946b4b9c6f18cd14/pkg/kubectl/genericclioptions/resource/visitor.go#L446-L480)

**Comment by ihcsim** [comment]
If this is a desired feature, I have submitted PR [1377](https://github.com/linkerd/linkerd2/pull/1377) for review.

**Comment by grampelberg** [comment]
@ihcsim thank you for the PR, I love this feature.
