### ISSUE TITLE
authority Prometheus label has potentially unbounded cardinality

### ISSUE THREAD

**Issue by adleong** [linkerd/linkerd2#1378]
The proxy can receive requests with arbitrary authority headers.  This means that any client which can send requests to the proxy can increase the carnality of values of the authority Prometheus label without bound, potentially degrading or taking down Prometheus.

Some potential solutions:

* Do not expose an "authority" label in metrics.
* Normalize authorities and whitelist them to known services e.g. `foo.bar.svc.cluster.local`.  This means that authority data about external domains (e.g. linkerd.io) is lost.
* Limit the maximum number of authorities to track to some fixed number.  This may require some kind of central coordination.
* Only track authorities on requests from "trusted" sources e.g. requests that originate within the cluster.

**Comment by olix0r** [comment]
> This means that any client which can send requests to the proxy can increase the carnality of values of the authority Prometheus label without bound, potentially degrading or taking down Prometheus.

Geeze, I'd hope that clients can't make the linkerd2 proxy _carnal_ ...

I understand that this is a theoretical problem. What are the practical cases we need to worry about most? It seems atypical for an application to run with truly unbounded authority values, and seems likely sufficient to provide a workaround for these specific cases.

**Comment by olix0r** [comment]
How many unique authorities are needed to take down Prometheus?

**Comment by adleong** [comment]
I don't know.  @siggy?

**Comment by siggy** [comment]
In general Prometheus labels should not reflect an unbounded set of values.

In practice, Prometheus can handle millions of time series (though this depends on retention, scrape interval, memory).
