### ISSUE TITLE
git checkout, `$GOPATH`, and `dep` stuff isn't documented in BUILD.md

### ISSUE THREAD

**Issue by briansmith** [linkerd/linkerd2#1385]
`TEST.md` mentions some stuff about `dep` and `GOPATH` but `BUILD.md` doesn't. This has tripped up some people contributing to linkerd2.

* Document the minimum version of `go`, how to check the version number (`go version`). I noticed Ubuntu ships out-of-date versions of `go` and the build will fail with a weird package dependency resolution failure like this if you use its default `go`:
```
cli/cmd/dashboard.go:4:2: cannot find package "context" in any of:
        /home/m/go/src/github.com/linkerd/linkerd2/vendor/context (vendor tree)
        /usr/lib/go-1.6/src/context (from $GOROOT)
        /home/m/go/src/context (from $GOPATH)
controller/api/public/http_server.go:13:2: no buildable Go source files in /home/m/go/src/github.com/linkerd/linkerd2/vendor/github.com/prometheus/client_golang/api
controller/api/public/grpc_server.go:16:2: no buildable Go source files in /home/m/go/src/github.com/linkerd/linkerd2/vendor/github.com/prometheus/client_golang/api/prometheus/v1
```
* Document that one must `go get` linkerd2 to ensure that its source is in the right place, or check it out exactly into `$GOPATH/src/github.com/linkerd/linkerd2` so that `go` can find it.
* Document what to set `$GOPATH` to.
* Document `bin/dep ensure`. Mention that `dep ensure` is needed whenever the imports for any Go source file are changed. Document why we have `bin/dep` (it downloads the right version of `dep`). Document what the CI failure looks like if you don't run it before.
* Document `bin/update-go-deps-shas`: When to run it, how to run it, and why we have it, what the CI failure looks like when you don't run it.

**Comment by alpeb** [comment]
This was addressed when we replaced `dep` with go modules.
