### ISSUE TITLE
Feature request: Monitor disk usage and alert when disk space is low.

### ISSUE THREAD

**Issue by briansmith** [linkerd/linkerd2#1386]
Somebody asked me today whether linkerd2 can monitor free disk space available and/or provide alerting about low disk space. It seems plausible that we could have `conduit inject` mount every volume and then have the proxy monitor disk space. Maybe this would only be useful for `StatefulSet` (etc.) that are designed to have non-ephemeral storage.

**Comment by olix0r** [comment]
This sounds somewhat outside the scope of linkerd to me. I would expect this information to be in the Kubernetes dashboard or otherwise accessible via Prometheus config.
