### ISSUE TITLE
install

### ISSUE THREAD

**Issue by wuxinvip** [linkerd/linkerd2#1399]
curl https://run.conduit.io/install | sh

Downloading linkerd2-cli-18.7.2-linux...

no response..

**Comment by wuxinvip** [comment]
404 i got

**Comment by grampelberg** [comment]
Any more details? I've been unable to replicate.

ps. as part of the latest release, we moved over to:

```bash
curl https://run.linkerd.io/install | sh
```

**Comment by wuxinvip** [comment]
thanks
