### ISSUE TITLE
Tap web UI: Move authority autocomplete to the autocomplete input

### ISSUE THREAD

**Issue by rmars** [linkerd/linkerd2#1401]
Currently the web UI's resource autocomplete also lists authorities. However you can't tap authorities in this way, you have to use `--authority` in addition to whatever resource you're trying to tap. The web UI is confusing as it presents authorities in that list. Those authorities should instead be moved to the Authority box in the advanced filter form.

Follow up to @kl in https://github.com/linkerd/linkerd2/pull/1391 there is an error when we try to tap an authority

**Comment by rmars** [comment]
I just realized that that error is actually expected? The way it is currently set up you can't tap an authority directly, you have to use a resource and then also filter by authority e.g. you would do 
```
linkerd tap deploy/web -n linkerd --authority 10.1.0.171:9994
```
But not
```
linkerd tap au/10.1.0.171:9994 -n linkerd
```

And our CLI help text doesn't include authorities. I think what would help is if I removed the authorities from the autocompletes and instead put the authority autocomplete in the Authority input field in the advanced form. So I'm going to change the description of this ticket to addressing that instead.

**Comment by klingerf** [comment]
@rmars Oh wow, nice catch! I think your suggested fix sounds great.
