### ISSUE TITLE
Introduce Service Profiles for basic policy configuration

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#1418]
## Problem

It's impossible to build solutions that apply to all classes of HTTP
services. Furthermore, as we've learned from Linkerd configs, it can be
burdensome to describe even one service with sufficient detail.

However, knowing even a little about a service up-front can allow us to
enhance the service substantially, without requiring the user to provide
detailed configuration.

For example, it's impractical for us to to record telemetry for all `:paths`,
as there are many ways for legitimate services to overload our metrics
system. (Consider, for instance, GitHub URLs -- we wouldn't want to store
metrics for every SHA in GitHub.) Conversely, if we know that a service is a
gRPC service, it becomes easy and obvious to record per-path metrics (since
gRPC services have a small, constrained number of paths).

Similarly, it's not possible to assume any idempotence semantics of a gRPC
service, since there are no protocol-level hints about request retryability.
On the other hand, if we know that a service is a well-conditioned REST
service, we can easily infer retryability based on the nature of the request
(HTTP method & payload size/kind).

## Goals

1. Allow users to provide the minimal amount of configuration that supports
   the maximum operational benefit.
2. Establish a primitive that can later be extended to support richer, more
   detailed policies.

### Non-Goals

1. Support arbitrary policies for arbitrarily complex services.

## Proposal: Service Profiles

The Linkerd controller is changed to be aware of a set of _Service Profiles_.
Each Kubernetes `Service` may be associated with a profile. The controller
uses these profiles, via the Destination API, etc, to inform the proxy of its
behavior.

Each profile describes how the service is expected to behave. Initially, we
only support one or two extremely coarse profiles that work for large swaths
of applications. Later, we can add the ability to extend these fixed profiles
or create custom service profiles.

### `grpc`

* Per-path metrics
* Failure classification

### `http-rest`

* Retries
* Failure classification

## Open questions

* How should profiles be attached to Services? Annotations? CRDs?
* How do users set these profiles?  `inject` on a Service? dedicated command?

**Comment by chrisgoffinet** [comment]
I think Annotations is the way to go for attaching to the `Service` object. 

I would be in favor of seeing both inject and dedicated command (just for ease of use)
