### ISSUE TITLE
Require tap user to be explicitly authorized for the tap

### ISSUE THREAD

**Issue by briansmith** [linkerd/linkerd2#142]
Tap should be restricted to authorized users. I suggest we focus on RBAC-based authorization:

Initial Version:
- [ ] Create a ClusterRole that for using the tap feature.
- [ ] Have the tap controller authenticate and authorize the user for that ClusterRole. if the user doing the tapping doesn't have the role then the tap request should be denied.
- [ ] Document how to grant people access to the tap feature through this role.

Future Version:
We need to be able to scope the authorization for tap in a flexible way. For example, we need to enable rules like "Allow Bob to tap all pods except those in the certificate-authority namespace" or "Allow Bob to only tap pods in the playground-bob" namespace.

I think for production environments we can assume that RBAC is enabled and working. However, note that current versions of minikube do not enable RBAC by default: https://github.com/kubernetes/minikube/issues/1722. We probably should accomodate running Conduit in minikube with RBAC is disabled until the version of minikube with RBAC enabled by default is released. Alternatively we should tell people that enabling RBAC in minikube is required for Conduit.

**Comment by grampelberg** [comment]
Fixed by #3171.
