### ISSUE TITLE
"Documentation" link in dashboard UI points to conduit.io/docs

### ISSUE THREAD

**Issue by dadjeibaah** [linkerd/linkerd2#1426]
I am not sure if this as known issue, but when using the Linkerd2 dashboard, clicking on the "Documentation" icon on the sidebar sends you to https://conduit.io/docs.

![conduit-redirect](https://user-images.githubusercontent.com/2197104/43870049-7aeffc70-9b2a-11e8-9a28-97f41588675e.gif)

**Comment by klingerf** [comment]
@dadjeibaah What's does the output of `linkerd version` give you for the server version? That link was changed in #1381, which shipped with the v18.7.3 release.

**Comment by dadjeibaah** [comment]
Ahh, I was on 18.7.2. Should have checked that first. I will close the issue.

**Comment by dadjeibaah** [comment]
Closing this issue as this was already fixed in the v18.7.3 release.

**Comment by klingerf** [comment]
Ah, it looks like `curl https://run.conduit.io/install | sh` still installs linkerd v18.7.2 -- we should update that script.

If you instead install linkerd via `curl https://run.linkerd.io/install | sh`, that should give you v18.8.1, which is the latest.
