### ISSUE TITLE
Add support for AWS ECS

### ISSUE THREAD

**Issue by alex1x** [linkerd/linkerd2#1427]
linkerd worked well on ECS and came with a [nice getting started guide for it](https://linkerd.io/1/getting-started/ecs/).

Would be nice to see support for ECS on linkerd2 as well.

**Comment by chrisgoffinet** [comment]
I'm not sure that's going to be possible. Linkerd2 relies heavily on Kubernetes APIs for their control plane.

**Comment by wmorgan** [comment]
FYI adding ECS support is on the table, but we haven't really figured out what it would require.

**Comment by grampelberg** [comment]
As of today, we are not planning on supporting any other schedulers. We'd love to work with someone who's interested in implementing a new control plane for their scheduler. Anyone interested in contributing a new control plane for their scheduler of choice, please open up a new issue so we can start working with you on it.
