### ISSUE TITLE
doc tweak: note that installing the control plane can take a long time

### ISSUE THREAD

**Issue by wmorgan** [linkerd/linkerd2#1441]
The getting started guide implies that one can run `linkerd version` immediate after `linkerd install | ...` and get the desired output. In a fresh minikube install on a laptop, it takes takes around a minute for `linkerd version` to report the server version, and until this happens, `linkerd version` just reports "Unavailable" (which is indistinguishable from the uninstalled state).

At a minimum, we should should a) note that installation might take some time and b) give suggestions about how to monitor the progress.

**Comment by klingerf** [comment]
I took a stab at adding this to the install section of the Getting Started guide. It now looks like this:

![image](https://user-images.githubusercontent.com/9226/44169101-49dcbe80-a088-11e8-9bac-1ccf4dad71df.png)

While be submitting for review in the docs repo shortly.

**Comment by wmorgan** [comment]
Thank you @klingerf!
