### ISSUE TITLE
Expose load balancing metrics

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#1445]
The decisions that linkerd2 makes when load balancing outgoing connections can be opaque to users. To help explain *how* the load balancer is working and *what* it is doing for a service owner, the metrics related to what decisions the load balancer has made should be surfaced in a clear manner.

## User Stories

- As a service owner, I would like to see the backends my outbound requests are sent to, so that I can understand the benefit linkerd2 is providing me.
- As a service owner, I would like to visualize why specific backends have been used for my outbound requests, so that I can debug issues related to requests going places other than I would expect.

## CLI

```bash
```

**Comment by adleong** [comment]
Are there any metrics needed for this that aren't already in Prometheus?  Is there any non-UI work that needs to be done?

**Comment by rmars** [comment]
I don't think there are currently any LB specific metrics exposed by the proxy... We can get traffic distribution from what's already in Prometheus, so what's in the user story thus far doesn't need additional work, but @grampelberg will probably have an idea of what other metrics we'll eventually want in there.

**Comment by dadjeibaah** [comment]
Just a thought, do we care about showing the type of load balancing mechanism type? If in the future, Linkerd 2.0 is going to have multiple LB mechanisms, it may be useful to have a foundational way to show that information.

**Comment by grampelberg** [comment]
As of right now, I'm unaware of any backend changes required. Some brainstorming early next week around what we want to do here would be super helpful for me. I'm thinking that dedicating a page to the reliability related features (load balancer state for example) will be valuable as an instructional landing page.

**Comment by klingerf** [comment]
Here's an example of one of my demo services running 3 replicas, and only 2 of the replicas are receiving traffic:

![image](https://user-images.githubusercontent.com/9226/44480678-b57ada80-a5f8-11e8-93f0-dd663fd8f92c.png)

I assume this has to do with load balancing? I think a good starting point for this issue would be to figure out how to more clearly explain why one of those three pods isn't receiving any traffic.
