### ISSUE TITLE
Resource detail view

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#1447]
The current dashboard gives a good overview of all the resources in the system (both meshed and unmeshed). Unfortunately, because it is an overview, there are some useful details around *my* service that are being missed.

To solve this problem, there should be a detail view that provides some extra visibility to help out with debugging. There's a list of details that should be there:

- Incoming and outgoing edges with their statistics. Ideally, incoming edges will be named (either DNS or k8s resource names).
- "top" path metrics specific to a service (eg. `/foo` and `/bar`).
- Integration between the detail view and tap (setting filters for example).
- Clear distinction between incoming and outgoing traffic, with both on the same page.

# Octopus Chart

# Live Path Metrics

# Tap Integration

**Comment by zachalbert** [comment]
Current version of the namespace detail view, based on the material design aesthetic.

![namespace-detail-view](https://user-images.githubusercontent.com/2305040/44133958-5defbf6a-a017-11e8-910c-8eab6966e815.png)

**Comment by rmars** [comment]
Updated designs:
![screen shot 2018-08-20 at 2 30 06 pm](https://user-images.githubusercontent.com/549258/44367819-b0494e80-a485-11e8-9b88-21f435630543.png)

**Comment by rmars** [comment]
Fixed by #1476, #1482, #1491, #1494, #1501, #1507, #1596
