### ISSUE TITLE
Create HTTP retry middleware

### ISSUE THREAD

**Issue by adleong** [linkerd/linkerd2#1450]
Create a middleware that implements retries of HTTP requests.  

* In the case where all requests fail, there should be limits in place to avoid generating too many retry requests.  For example, Finagle does this with [retry budgets](https://finagle.github.io/blog/2016/02/08/retry-budgets/).  Using a retry budget to ensure that retries only add 20% additional load is probably a good starting point.
* Requests should not be infinitely retried.  This could be accomplished by a timeout after which no more retries will be attempted.
* Since requests must be buffered in the proxy in order to retry them, it is acceptable to not retry requests which are too large or too long-running to buffer efficiently.
* It must be possible to place the retry middleware above a load balancer so that each retry can be load balanced independently.

**Comment by adleong** [comment]
There's some debate about if the `l5d-retryable` header should be a request or response header.  Having it as a response header makes logical sense because the server is the source-of-truth on the semantics of request and theoretically knows if any side-effects have taken place.  However, I feel like having it as a request header is more useful because it allows requests to be retried in scenarios where there is no response --- for example when the server hits an exception while processing the request and closes the connection instead of sending a response.

**Comment by olix0r** [comment]
I don't think a request sender can _ever_ know if the request is retryable independent of the failure kind.

**Comment by seanmonstar** [comment]
Does this make sense for both inbound and outbound? In the outbound case, the proxy retrying will be able to make use of the load balancing to try a different service (in case part of the problem was the original service). In the inbound case, the proxy would just be hammering its wrapped service until some budget was exhausted.

**Comment by olix0r** [comment]
I'm skeptical of the header approach in general, but i agree application level retries are undesirable on the inbound side. However, _requeues_ (as finagle calls them) are valuable in the case when the application process is restarting

**Comment by adleong** [comment]
@olix0r are requeues in scope for this?  My sense is no, and thus we should just focus on the outbound retries case for now.

I've edited this issue to remove references to the retryability header since that doesn't seem useful.

**Comment by adleong** [comment]
@briansmith  https://github.com/linkerd/rfc/pull/1

I've edited this issue to remove mention of a retryability header.  I don't think it's necessary.
