### ISSUE TITLE
Add retry proxy metrics

### ISSUE THREAD

**Issue by adleong** [linkerd/linkerd2#1455]
Add proxy metrics or labels so that we can answer the following questions:

* What is the total request rate?
* What is the original request rate?
* What is the retry request rate?
* What is the user-visible success rate? 
* What is the underlying success rate?

For example, this could be done by adding `logical_request_total` and `logical_response_total` metrics which are analogous to `request_total` and `response_total` but are measured prior to the retry middleware.  The resulting queries would then be:

* What is the total request rate? `irate(request_total)`
* What is the original request rate? `irate(logical_request_total)`
* What is the retry request rate? `irate(request_total - logical_request_total)`
* What is the user-visible success rate? `logical_response_total{classification="success"} / logical_response_total`
* What is the underlying success rate? `response_total{classification="success"} / response_total`

**Comment by olix0r** [comment]
I think we should just bite the bullet and expose symmetric metrics before and after retries. For one, it's extremely helpful to differentiate the perceived and actual service latencies. It also fits nicely with #1518.

```
request_total{peer="src",http="1.1",...} 1
request_total{peer="dst",http="2",...} 1
request_total{peer="dst",http="2",retry="<%= reason %>",...} 2
response_total{peer="src",http="1.1",...} 1
response_total{peer="dst",http="2",...} 1
response_total{peer="dst",http="2",failure="<%= reason %>",retryable="<%= reason %>",...} 2
response_latency_ms_...
```

**Comment by adleong** [comment]
This sounds great to me.  Interpreting peer="src" as "after retries" and peer="dst" as "before retries" is a little arcane, but I think it's fine.

**Comment by olix0r** [comment]
I'm realizing that the metrics scope "above" retries (i.e. measured before retries are applied) needs to be done before a request is associated with a specific destination. An open question: should these metrics be recorded before service discovery? Or after?  I assume after, so that we can get service-level metadata into the metrics.

**Comment by adleong** [comment]
By "specific destination" you mean address, right? Not service?

Having service-level metadata seems desirable.

**Comment by olix0r** [comment]
yyyeah. i mean above the load balancer.

**Comment by adleong** [comment]
I think this is done.  @seanmonstar is that correct?

**Comment by seanmonstar** [comment]
There's metrics available from the proxy, scoped to routes from a service profile. I don't know if they are exposed in any way on the dashboard.

As described in https://github.com/linkerd/linkerd2-proxy/pull/140, they look like:

```
route_response_total{direction="outbound",dst="dest:80",status_code="200",classification="success"} 5
route_response_total{direction="outbound",dst="dest:80",status_code="533",classification="failure"} 1


route_actual_response_total{direction="outbound",dst="dest:80",status_code="200",classification="success"} 5
route_actual_response_total{direction="outbound",dst="dest:80",status_code="533",classification="failure"} 6

route_actual_retry_skipped_total{direction="outbound",dst="dest:80",skipped="budget"} 1
```

**Comment by sudermanjr** [comment]
I don't believe there is any distinction on the dashboard or in the grafana dashboards about which of the two metrics we are seeing (actual vs. non-actual).

**Comment by wmorgan** [comment]
Is the current status of this that they are exposed in the CLI in `linkerd routes`, but not in Grafana or in the Linkerd dashboard?
