### ISSUE TITLE
Tap stream IDs collide across proxies

### ISSUE THREAD

**Issue by adleong** [linkerd/linkerd2#1456]
The TapEvent protobuf defines a stream id base field which should be set to: `A randomized base (stable across a process's runtime)`.

It is currently always set to 0: https://github.com/linkerd/linkerd2-proxy/blob/master/src/control/pb.rs#L37

This causes collisions when aggregating tap data from multiple proxy instances and incorrectly associates events together from different proxies.  To avoid this (or at least make it overwhelmingly unlikely) this should be set to a randomized number, as specified in the comment.

**Comment by olix0r** [comment]
I was hoping that we could remove this field entirely and use (source, dst, stream id, open timestamp) to properly identify requests

**Comment by olix0r** [comment]
specifically, the stream id _should_ be the actual H2 stream id (or a synthesized h1 streams)

Why do you need this id to differentiate requests?  can't you use (src addr, dst addr, stream id) for now?

**Comment by adleong** [comment]
https://github.com/linkerd/linkerd2/issues/1711
