### ISSUE TITLE
Populate URL hash based on tap query filters

### ISSUE THREAD

**Issue by rmars** [linkerd/linkerd2#1459]
Currently the filter params in the tap query request form aren't reflected in the URL.
We should reflect the current query params in the URL such that a user can navigate to an already populated query using a URL like

```
http://localhost:8084/tap?namespace=emojivoto&resource_type=deployment&resource_name=voting&max_rps=1
```

This will enable us to link to a tap page with specific filters populated from the resource page in #1457.

Part of #1447

**Comment by grampelberg** [comment]
Can we do this for top as well?
