### ISSUE TITLE
Link to the tap page from the ResourceDetail page

### ISSUE THREAD

**Issue by rmars** [linkerd/linkerd2#1461]
Once #1459 and #1457 (and #1458?) are done, provide links from rows in the Resource Detail page to the tap page, conveniently populating the form links with the query for the row that you clicked on.

Questions to answer:
- what things will you click on? Just a path? a deployment? any resource? and what exactly will happen when you click on them?

Part of #1447

It would be cool to automatically start a tap when the user arrives on the page with parameters from the URL, but we should fix the performance issues with the Tap table before that happens (#1597)

**Comment by dadjeibaah** [comment]
Looking at the resource detail page, I think it would be easy to add another column to the downstream and pod metric tables which should have a link or button for each line that links you to the tap page. I think another really cool idea would click an octopus arm and have that link to the tap page as well. Thoughts? /cc @grampelberg @rmars
