### ISSUE TITLE
improve proxy "connection reset by peer" error message

### ISSUE THREAD

**Issue by wmorgan** [linkerd/linkerd2#1462]
The proxy currently emits error messages like these: `ERR! proxy={server=in listen=0.0.0.0:4143 remote=100.96.122.1:21904} linkerd2_proxy turning an IO error occurred: Connection reset by peer (os error 104) into 500`

Can this message be improved to make it clear that this means the client dropped the TCP connection before the response finished?

**Comment by hawkw** [comment]
The "Connection reset by peer" part of the message comes from the Rust standard lib (I believe it's what the libc function `strerror_r` returns for error code 104.

> Can this message be improved to make it clear that this means the client dropped the TCP connection before the response finished?

I'm not wholly certain this is the _only_ case where this error message is emitted. Before we make the log line say that the TCP connection was reset by the client we should make sure that, for example, we don't also output this message when the connection is dropped by the remote server, etc.

**Comment by wmorgan** [comment]
I'd be ok with adding a "possibly" as well. Overall I think the format of this log message is also a little confusing. How about something like:

`returning 500 due to underlying error [Connection reset by peer (os error 104)] -- possibly due to client dropping the TCP connection`

**Comment by olix0r** [comment]
I don't think we should log _any_ errors in this situation

**Comment by wmorgan** [comment]
That would satisfy me, since mostly I'm concerned about users who see these error messages and think that something is wrong.
