### ISSUE TITLE
Research proxy changes for pre/post install checks

### ISSUE THREAD

**Issue by rmars** [linkerd/linkerd2#1469]
Do we need any proxy changes to happen for #1103 to be realized?

**Comment by klingerf** [comment]
In discussing #1103 with @grampelberg and @olix0r, we determined that we don't need any proxy changes to run data plane checks in the near term. We are going to update `linkerd inject` to add a basic readiness/liveliness check for the linkerd-proxy container, but for now that's going to hit the existing `/metrics` endpoint on the proxy's admin port (see #1515). No other proxy changes are required.
