### ISSUE TITLE
Revisit linkerd check output format

### ISSUE THREAD

**Issue by klingerf** [linkerd/linkerd2#1471]
Per #1081, we should streamline the linkerd check output to be less verbose when checks are passing, and more verbose when checks are failing. We should also group the checks as Pre-Install and Post-Install. Relates to #1470.

**Comment by rmars** [comment]
Step 1: get some design feedback on the overall UX of the CLI

**Comment by wmorgan** [comment]
Related: #1653, #1656

**Comment by siggy** [comment]
As part of this work, we should consider embellishing cli output with emoji/color/lol, as mentioned in TGIK8s:

emoji and color in linkerd check:
https://youtu.be/1dXJ34-KLe8?t=2739

ascii art / color / lolgopher for linkerd dashboard:
https://youtu.be/1dXJ34-KLe8?t=2797
https://github.com/kris-nova/lolgopher

**Comment by grampelberg** [comment]
Also related, #1739.

**Comment by grampelberg** [comment]
Here's a proposal for updated formating:

```bash
$ linkerd check

kubernetes-api
---------------
can initialize the client                                                     ✔️
can query the Kubernetes API                                                  ✔️

RBAC
----
can create Namespaces                                                         ❌
    Missing permissions to create Namespace
    See https://linkerd.io/2/troubleshooting#rbac for hints

Version
-------
cli is up-to-date                                                             ✔️
data plane is up-to-date                                                      ⚠️
    You are running 18.11.1 and the latest version is 18.11.2
    See https://linkerd.io/2/troubleshooting#version-mismatch for hints
```

In addition, it would be nice to add a spinner when we are retrying (instead of outputting another line). Something like https://github.com/briandowns/spinner.

**Comment by siggy** [comment]
Relates to #1653 and #1739.
