### ISSUE TITLE
Add pre-install check to validate that images are available

### ISSUE THREAD

**Issue by klingerf** [linkerd/linkerd2#1475]
We should add an additional pre-install check (depends on #1470) to validate that the images we're trying to install are available to the cluster where the check is running. I'm not exactly sure how to go about this.

**Comment by grampelberg** [comment]
Ohhh, I like this one a lot. I don't know how to do it without adding a temporary pod to the cluster and seeing if it starts though.

**Comment by grampelberg** [comment]
After some conversations, the only way to do this would be to run a pod on the cluster that pulls images. As this modifies the cluster, we won't be tackling this check right now.
