### ISSUE TITLE
Linkerd2 + Rancher 2.0 - Dashboard Proxy Issues

### ISSUE THREAD

**Issue by gottfrois** [linkerd/linkerd2#1483]
Hey guys,

On William's request, I'm creating the following issue to report some troubles when installing Linkerd2 on Rancher 2.0 and trying to run the dashboard and grafana.

I run k8s on GKE using Rancher 2.0.6.

```
linkerd version
Client version: v18.8.1
Server version: v18.8.1
kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-18T11:36:43Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.5-gke.4", GitCommit:"6265b9797fc8680c8395abeab12c1e3bad14069a", GitTreeState:"clean", BuildDate:"2018-08-04T03:47:40Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

Linkerd is correctly setup on the k8s cluster:

```
kubectl get pods,svc -n linkerd
NAME                              READY     STATUS    RESTARTS   AGE
pod/controller-6f78cbd47-8w4fj    5/5       Running   0          3h
pod/grafana-5b7d796646-9zdpf      2/2       Running   0          3h
pod/prometheus-74d6879cd6-g2trv   2/2       Running   0          3h
pod/web-79845756df-qrqlw          2/2       Running   0          2h

NAME                 TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)             AGE
service/api          ClusterIP   10.3.241.51    <none>        8085/TCP            3h
service/grafana      ClusterIP   10.3.249.233   <none>        3000/TCP            3h
service/prometheus   ClusterIP   10.3.240.181   <none>        9090/TCP            3h
service/proxy-api    ClusterIP   10.3.240.55    <none>        8086/TCP            3h
service/web          ClusterIP   10.3.242.243   <none>        8084/TCP,9994/TCP   2h
```

When running `linkerd dashboard` i get the following:

```
linkerd dashboard
Linkerd dashboard available at:
http://127.0.0.1:51103/api/v1/namespaces/linkerd/services/web:http/proxy/
Grafana dashboard available at:
http://127.0.0.1:51103/api/v1/namespaces/linkerd/services/grafana:http/proxy/
Opening Linkerd dashboard in the default browser
```

Which opens the following page https://d.pr/i/v8wWzf
Replacing `127.0.0.1:51103` with my rancher cluster URL allows me to access the dashboard: https://d.pr/i/zz9WVR

However the links on the dashboard will change the URL to `https://rancher.textmaster.com/api/v1/namespaces/linkerd/services/web:http/proxy/servicemesh` which will show an empty dashboard https://d.pr/i/lt2n7N

Same issue for Grafana, the dashboard works but the links trim down the cluster url: 
https://d.pr/i/CJyrBu
https://d.pr/i/rTUFDN

Thanks!

**Comment by Gambler13** [comment]
@gottfrois 
You can try the following workaround.
In Rancher navigate to Workloads -> Load Balancer and add a new Ingress.
Add a new Service Backend with the Linkerd web port (e.g.  8084) and define a hostname (or let Ranger generate a xip.io hostname).
![image](https://user-images.githubusercontent.com/24626221/44680564-612f8a80-aa3e-11e8-9640-e01a3a200e9e.png)
Afterward you should be able to open the dashboard.

**Comment by gottfrois** [comment]
Thanks! I will try this workaround

**Comment by gottfrois** [comment]
Worked like a charm! Thanks a lot

**Comment by grampelberg** [comment]
@gottfrois are you up for writing a little doc up for using linkerd2 with rancher? It would be awesome to get this into the docs for others!

**Comment by gottfrois** [comment]
@grampelberg there is really nothing specific to Rancher orther than this work around which, if i understood correctly, is going to be fixed in future releases?
Following the current Linkerd2 documentation with `kubectl` configured to talk to the rancher cluster works great.

**Comment by cola4u** [comment]
@grampelberg In order to get the linkerd 2 web ui to work in a Rancher 2.0.8 setup, I first moved the "linkerd" namespace into the "default" project within the Rancher managed cluster (so that it's easier to manage).  Then created an ingress mapping to the web service port 8084, with a xip.io domain name.
That seemed to do it.  For an on-prem cluster, it seemed to work pretty quick, for a GKE cluster it took almost 10 minutes for the ingress to fully provision - so heads up.

**Comment by chrisingenhaag** [comment]
@cola4u Did you get grafana working? Your hint works fine, but grafana view is still not reachable.

I tried to create L7-LB with path /dashboard pointing to grafana-service port 3000, but grafana UI is sill requesting resources via path patterns linke /api/v1/namespaces/linkerd/services/grafana:http/proxy/d/6svnwykmk/linkerd-deployment?var-namespace=emojivoto&var-deployment=emoji

**Comment by grampelberg** [comment]
@chrisingenhaag you'll have to modify the grafana config a little bit to get that working. Take a look at:

https://github.com/linkerd/linkerd2/blob/master/cli/install/template.go#L541

Just remove the `root_url` config (or change it to what you want it to be). I just opened up an issue (#1692) to track getting something better together.
