### ISSUE TITLE
Go modules support

### ISSUE THREAD

**Issue by chrisgoffinet** [linkerd/linkerd2#1488]
Since 1.11 is introducing official module support, does Linkerd have plans to drop dep? 1.11 final should be dropping in next month~ or sooner. It looks like the majority pain points have been addressed (such as how do we handle docker image caching to speed up builds, etc).

I am more than happy to provide a PR to support this.

**Comment by wmorgan** [comment]
Since @chrisgoffinet is so kindly offering to write a PR, can we make a call on this?

**Comment by olix0r** [comment]
I don't understand what we get by switching.  I don't think anyone particularly likes our `dep` based system, but it's at least fairly well understood.  I'd prefer that we get some experience with the new tools in smaller projects before we switch everything over, unless it solves a specific painpoint that we have today.
