### ISSUE TITLE
Linkerd2 not compatible with nginx-ingress

### ISSUE THREAD

**Issue by jeroenjacobs1205** [linkerd/linkerd2#1499]
Hi,

I'm using nginx-ingress as an ingress-controller, and cert-manager to create TLS keys/certs. This setup works fine at the moment. 

Today I tried:

`linkerd inject  https://github.com/kubernetes/ingress-nginx/blob/master/deploy/mandatory.yaml | kubectl apply -f -`

This seems not a good idea, and totally breaks nginx-ingress, getting error 500 floods in the nginx pod logs everywhere. 

Is this an issue with linkerd2, or an issue with ingress-nginx?

**Comment by jeroenjacobs1205** [comment]
What I was aiming for, was a fully TLS encrypted path from the incoming request to the back-end service:

Request ==> nginx-ingress (with cert-manager supplied TLS) ==> Backend app (using Linkerd2 TLS)

Since linkerd2 doesn't work on an ingress-nginx, a fully TLS encrypted path is not possible.

**Comment by EmJayBee83** [comment]
Can verify @jeroenjacobs1205 report.

**Comment by grampelberg** [comment]
@EmJayBee83 see kubernetes/ingress-nginx#3171 and #1537 for the workaround.

(Closing this out as a dup of #1537 for now)

**Comment by jeroenjacobs1205** [comment]
@grampelberg Sorry, but it's not clear to me what I need to do to make this work. 3171 mentions to remove the `nginx.ingress.kubernetes.io/upstream-vhost` annotation (I'm not using that), while 1537 talks about a custom config nginx template. 

And do I need a `nginx.ingress.kubernetes.io/service-upstream: "true"` or not?

**Comment by grampelberg** [comment]
@jeroenjacobs1205 I've not tried it out myself, might want to ask in #1537. I'm reasonably sure some folks have gotten it to work.
