### ISSUE TITLE
Tap from web sometimes causes tap server panic

### ISSUE THREAD

**Issue by klingerf** [linkerd/linkerd2#1504]
I've noticed that clicking the "Stop" button on the `/tap` and `/top` pages is usually laggy and often results in displaying this banner:

<img width="412" alt="screen shot 2018-08-22 at 10 55 09 am" src="https://user-images.githubusercontent.com/9226/44481266-37b7ce80-a5fa-11e8-8b29-a6a726f1db12.png">

It looks like occasionally that correlates with an actual panic in the tap process in the controller pod:

```
time="2018-08-22T05:57:00Z" level=error msg="rpc error: code = Canceled desc = context canceled"
panic: send on closed channel

goroutine 139 [running]:
github.com/linkerd/linkerd2/controller/tap.(*server).tapProxy(0xc420442c20, 0x14843a0, 0xc420966fc0, 0x3f800000, 0xc420981510, 0xc4205fe740, 0xa, 0xc420a0c180)
	/go/src/github.com/linkerd/linkerd2/controller/tap/server.go:278 +0x3b6
created by github.com/linkerd/linkerd2/controller/tap.(*server).TapByResource
	/go/src/github.com/linkerd/linkerd2/controller/tap/server.go:94 +0x50b
```

This makes me think that the web server endpoint isn't properly handling websocket close, and is leaving its connection to the tap server in a bad state.

**Comment by grampelberg** [comment]
I'm getting this bug whether I hit start/stop on a semi-regular basis topping `deploy/web`.

**Comment by klingerf** [comment]
Saw this error again while running integration tests on latest master (not using the web UI). Updated stacktrace is:

```
panic: send on closed channel

goroutine 301 [running]:
github.com/linkerd/linkerd2/controller/tap.(*server).tapProxy(0xc4203ba9e0, 0x1485460, 0xc420704660, 0xc442c80000, 0xc4207a56e0, 0xc420af8ba0, 0xa, 0xc42040f8c0)
	/go/src/github.com/linkerd/linkerd2/controller/tap/server.go:287 +0x3b6
created by github.com/linkerd/linkerd2/controller/tap.(*server).TapByResource
	/go/src/github.com/linkerd/linkerd2/controller/tap/server.go:103 +0x5eb
```

**Comment by dadjeibaah** [comment]
Interesting. So it might be that this isn't caused by the websocket connection management in the web pod.

**Comment by klingerf** [comment]
@dadjeibaah That's right -- this appears to have been caused from the integration tests running tap from the command line.

**Comment by klingerf** [comment]
This is readily reproducible if you start a CLI tap command on a resource that has multiple proxies (e.g. `linkerd tap deploy -n emojivoto`), and the ctrl-c it. Most of the time that's enough to induce the server panic.
