### ISSUE TITLE
Dashboard: Deployment scaled to 0 shows the grafana button

### ISSUE THREAD

**Issue by bourquep** [linkerd/linkerd2#1510]
On v18.8.2, the dashboard shows the grafana button for any deployment that is scaled to 0 pods, and the button leads to an empty dashboard.

<img width="1104" alt="image" src="https://user-images.githubusercontent.com/65096/44498592-61e6ac00-a64d-11e8-9952-e0c69bb540d6.png">

**Comment by wmorgan** [comment]
@bourquep nice catch! Thanks!
