### ISSUE TITLE
Update linkerd check with a flag to run data plane checks

### ISSUE THREAD

**Issue by klingerf** [linkerd/linkerd2#1512]
Update `linkerd check` to accept a flag that will run a series of data plane checks, as described in #1103. I'm on the fence about what we should call this flag (`--data-plane`, `--proxy`, ...). I'll create separate issues for the checks to run.

**Comment by grampelberg** [comment]
@klingerf I'm not a huge fan of either, now that I've seen them written down. `--data-plane` would match most closely with the documentation as it is today. Just brainstorming:

- `--service` - since we're checking up on your service's status
- `--workloads`
