### ISSUE TITLE
Update linkerd check to accept a target for data plane checks

### ISSUE THREAD

**Issue by klingerf** [linkerd/linkerd2#1513]
Once the ability to run data plane checks exists (#1512), it would be nice for check to accept a target kubernetes resource to run checks against, rather than running against all proxies that are configured to talk to the control plane. For instance:

```
linkerd check --proxy deploy/web -n emojivoto
```

Would check all proxies on all pods in the web deployment in the emojivoto namespace.

**Comment by alenkacz** [comment]
@klingerf just to clear out some potential confusion:

- the issue description mentions `--data-plane` but I should use the already introduced `--proxy` right?
- we should still make it possible to fo just `--proxy` without a target, right?

**Comment by klingerf** [comment]
@alenkacz Yep, that's all correct. I updated the description to reflect the `--proxy` flag name, and we want to continue to run the proxy checks even if the target is not specified.

And the target could be any resource that includes a pod spec. The full list of owner resources that are support by our `ListPods` API can be found [here](https://github.com/linkerd/linkerd2/blob/master/proto/public.proto#L29).
