### ISSUE TITLE
Websocket error on top when resource is missing

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#1521]
![screenshot 2018-08-23 15 21 08](https://user-images.githubusercontent.com/47992/44555071-4d0b2680-a6e8-11e8-81ec-7a5891d98571.png)

I can click `Start` even though I've not selected a resource. Ideally, this would work to show me everything in a namespace. If that's not possible, it would be nice to at least have the button disabled until the resource is selected.

**Comment by rmars** [comment]
It's definitely possible to tap everything in a namespace. Just requires some changes in how we parse the resource type in the server, but should be doable.
