### ISSUE TITLE
Clear top when a new target is selected

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#1523]
![screenshot 2018-08-23 15 38 10](https://user-images.githubusercontent.com/47992/44555566-98263900-a6ea-11e8-8959-6bc1b2c69441.png)

I did top for awhile on a resource, and switched to a new one. The old top continued, the table was not cleared and I got an error that something happened with the websocket connection.

**Comment by rmars** [comment]
Tracking this in #1433
