### ISSUE TITLE
Top for non-meshed resources?

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#1524]
![screenshot 2018-08-23 15 48 21](https://user-images.githubusercontent.com/47992/44555862-05869980-a6ec-11e8-899a-136167d97da8.png)

It feels a little weird to have top for non-meshed resources like the things in kube-system. Is it possible to do for something that isn't in the mesh at all? I'd prefer to just not show the non-meshed resources in the dropdown (maybe filter the namespaces down as well?).

**Comment by rmars** [comment]
It's not possible to tap something not in the mesh (#1535). I'll filter out the non-meshed resources.
