### ISSUE TITLE
Tap updating only on completion?

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#1526]
Using the tap webui, it appears that lines only appear when `end` is received. I kinda like the separation of req/res/end in the CLI as it gives a good feeling of the actual communication cycle.

Instead of waiting for end, would it be possible to add a line to the table when req is first received and continue to populate it through end? That way, I could have a feeling that this is streaming and populating as the communication happens with my service.

**Comment by klingerf** [comment]
> would it be possible to add a line to the table when req is first received and continue to populate it through end?

This is how the tap table works. The row is added as soon as the `req` event is received, and loading spinners are displayed in the columns that are populated by the `rsp` and `end` events. Maybe the backend that you're tapping is fast enough that you don't see the spinners? I think if you try tapping a slower service you'll see the behavior that you're expecting.

**Comment by grampelberg** [comment]
My suspicion is that this is related to #1525 in that case. I'll check again one we have some progress there.
