### ISSUE TITLE
Linkerd check failed (control plane API 503). Server version unavailable. Tap log connection refused. Why?

### ISSUE THREAD

**Issue by alan-he** [linkerd/linkerd2#1541]
From k8s viewpoint everything is ok, linkerd pods are ready
[root@k8s-node-2 ~]# kubectl -n linkerd get po
NAME                                        READY     STATUS    RESTARTS   AGE
controller-67489d768d-d5z7j     5/5          Running   2          16h
grafana-5df745d8b8-8qwp2       2/2          Running   0          14h
prometheus-d96f9bf89-vms4c    2/2          Running   0          14h
web-766975995f-zgqzz                2/2         Running   0          16h

------------------------------------------------linkerd version ------------------------------------
[root@k8s-node-2 ~]# linkerd version --verbose
Client version: v18.8.2
DEBU[0000] Expecting API to be served over [https://10.186.93.46:6443/api/v1/namespaces/linkerd/services/http:api:http/proxy/api/v1/]
DEBU[0000] Making gRPC-over-HTTP call to [https://10.186.93.46:6443/api/v1/namespaces/linkerd/services/http:api:http/proxy/api/v1/Version] []
DEBU[0000] Response from [https://10.186.93.46:6443/api/v1/namespaces/linkerd/services/http:api:http/proxy/api/v1/Version] had headers: map[Date:[Wed, 29 Aug 2018 01:04:51 GMT] Content-Type:[text/plain; charset=utf-8] Content-Length:[71]]
DEBU[0000] gRPC-over-HTTP call returned status [503 Service Unavailable] and content length [71]
Server version: unavailable
------------------------------------------------linkerd check--------------------------------------------
[root@k8s-node-2 ~]# linkerd check --verbose
kubernetes-api: can initialize the client..................................[ok]
kubernetes-api: can query the Kubernetes API...............................[ok]
kubernetes-api: is running the minimum Kubernetes API version..............[ok]
linkerd-api: control plane namespace exists................................[ok]
linkerd-api: control plane pods are ready..................................[ok]
DEBU[0000] Expecting API to be served over [https://10.186.93.46:6443/api/v1/namespaces/linkerd/services/http:api:http/proxy/api/v1/]
linkerd-api: can initialize the client.....................................[ok]
DEBU[0000] Making gRPC-over-HTTP call to [https://10.186.93.46:6443/api/v1/namespaces/linkerd/services/http:api:http/proxy/api/v1/SelfCheck] []
DEBU[0000] Response from [https://10.186.93.46:6443/api/v1/namespaces/linkerd/services/http:api:http/proxy/api/v1/SelfCheck] had headers: map[Content-Type:[text/plain; charset=utf-8] Content-Length:[73] Date:[Wed, 29 Aug 2018 01:10:22 GMT]]
DEBU[0000] gRPC-over-HTTP call returned status [503 Service Unavailable] and content length [73]
linkerd-api: can query the control plane API...............................[FAIL] -- Unexpected API response: 503 Service Unavailable

Status check results are [FAIL]
-----------------------------------------------Controller Tap logs------------------------------------------
 time="2018-08-28T08:39:20Z" level=info msg="running version v18.8.2"
time="2018-08-28T08:39:20Z" level=info msg="starting admin server on :9998"
time="2018-08-28T08:39:20Z" level=info msg="starting gRPC server on 127.0.0.1:8088"
time="2018-08-28T08:39:20Z" level=info msg="waiting for caches to sync"
E0828 08:39:20.245280       1 reflector.go:205] k8s.io/client-go/informers/factory.go:130: Failed to list *v1beta2.Deployment: Get https://10.96.0.1:443/apis/apps/v1beta2/deployments?limit=500&amp;resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
E0828 08:39:20.245332       1 reflector.go:205] k8s.io/client-go/informers/factory.go:130: Failed to list *v1.Namespace: Get https://10.96.0.1:443/api/v1/namespaces?limit=500&amp;resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
E0828 08:39:20.245372       1 reflector.go:205] k8s.io/client-go/informers/factory.go:130: Failed to list *v1.ReplicationController: Get https://10.96.0.1:443/api/v1/replicationcontrollers?limit=500&amp;resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
E0828 08:39:20.245534       1 reflector.go:205] k8s.io/client-go/informers/factory.go:130: Failed to list *v1.Service: Get https://10.96.0.1:443/api/v1/services?limit=500&amp;resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
E0828 08:39:20.245577       1 reflector.go:205] k8s.io/client-go/informers/factory.go:130: Failed to list *v1beta2.ReplicaSet: Get https://10.96.0.1:443/apis/apps/v1beta2/replicasets?limit=500&amp;resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
E0828 08:39:20.246158       1 reflector.go:205] k8s.io/client-go/informers/factory.go:130: Failed to list *v1.Pod: Get https://10.96.0.1:443/api/v1/pods?limit=500&amp;resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
E0828 08:39:21.246352       1 reflector.go:205] k8s.io/client-go/informers/factory.go:130: Failed to list *v1beta2.Deployment: Get https://10.96.0.1:443/apis/apps/v1beta2/deployments?limit=500&amp;resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused 

-----------------------------------------------------controller linkerd-proxy logs--------------------------
 INFO linkerd2_proxy using controller at Some(HostAndPort { host: DnsName(DnsName(DNSName("localhost."))), port: 8086 })
INFO linkerd2_proxy routing on V4(127.0.0.1:4140)
INFO linkerd2_proxy proxying on V4(0.0.0.0:4143) to None
INFO linkerd2_proxy serving Prometheus metrics on V4(0.0.0.0:4191)
INFO linkerd2_proxy protocol detection disabled for inbound ports {25, 3306}
INFO linkerd2_proxy protocol detection disabled for outbound ports {25, 3306}
INFO admin={bg=resolver} linkerd2_proxy::transport::connect DNS resolved DnsName(DnsName(DNSName("localhost."))) to 127.0.0.1
ERR! proxy={server=out listen=127.0.0.1:4140 remote=10.244.2.114:56396} linkerd2_proxy::transparency::tcp tcp duplex error: Transport endpoint is not connected (os error 107)
ERR! proxy={server=out listen=127.0.0.1:4140 remote=10.244.2.114:56386} linkerd2_proxy::transparency::tcp tcp duplex error: Transport endpoint is not connected (os error 107)
ERR! proxy={server=out listen=127.0.0.1:4140 remote=10.244.2.114:56380} linkerd2_proxy::transparency::tcp tcp duplex error: Transport endpoint is not connected (os error 107)
ERR! proxy={server=out listen=127.0.0.1:4140 remote=10.244.2.114:56382} linkerd2_proxy::transparency::tcp tcp duplex error: Transport endpoint is not connected (os error 107)
ERR! proxy={server=out listen=127.0.0.1:4140 remote=10.244.2.114:56384} linkerd2_proxy::transparency::tcp tcp duplex error: Transport endpoint is not connected (os error 107)
ERR! proxy={server=in listen=0.0.0.0:4143 remote=10.244.2.116:35576} linkerd2_proxy turning an error occurred trying to connect: Connection refused (os error 111) into 500
ERR! proxy={server=in listen=0.0.0.0:4143 remote=10.244.2.116:54506} linkerd2_proxy turning an error occurred trying to connect: Connection refused (os error 111) into 500 
 ERR! proxy={server=in listen=0.0.0.0:4143 remote=10.244.2.116:54506} linkerd2_proxy turning an error occurred trying to connect: Connection refused (os error 111) into 500
ERR! proxy={server=out listen=127.0.0.1:4140 remote=10.244.2.114:56540} linkerd2_proxy::transparency::tcp tcp duplex error: Transport endpoint is not connected (os error 107)
ERR! proxy={server=out listen=127.0.0.1:4140 remote=10.244.2.114:56538} linkerd2_proxy::transparency::tcp tcp duplex error: Transport endpoint is not connected (os error 107)
ERR! proxy={server=out listen=127.0.0.1:4140 remote=10.244.2.114:56544} linkerd2_proxy::transparency::tcp tcp duplex error: Transport endpoint is not connected (os error 107)
ERR! proxy={server=out listen=127.0.0.1:4140 remote=10.244.2.114:56548} linkerd2_proxy::transparency::tcp tcp duplex error: Broken pipe (os error 32)
ERR! proxy={server=out listen=127.0.0.1:4140 remote=10.244.2.114:56546} linkerd2_proxy::transparency::tcp tcp duplex error: Transport endpoint is not connected (os error 107)
ERR! proxy={server=in listen=0.0.0.0:4143 remote=10.244.2.116:35576} linkerd2_proxy turning an error occurred trying to connect: Connection refused (os error 111) into 500
ERR! proxy={server=in listen=0.0.0.0:4143 remote=10.244.2.116:35576} linkerd2_proxy turning an error occurred trying to connect: Connection refused (os error 111) into 500

**Comment by grampelberg** [comment]
@alan-he what are you using for provisioning and CNI? Are you using any kind of NetworkPolicy?
