### ISSUE TITLE
Sidebar is out of sync from main view

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#1542]
The sidebar's polling seems to be different than the main view. This is leading to green health in one place and red in another (or visa.versa).

<img width="447" alt="screenshot 2018-08-29 09 25 39" src="https://user-images.githubusercontent.com/47992/44801435-e9607d80-ab6d-11e8-9daa-997eacf429ea.png">

**Comment by rmars** [comment]
How are we going to this? We'll need to figure out how we handle polling and data management in the components. Sharing state? Storing state in a higher component and passing it down?
