### ISSUE TITLE
Version Check URL is invalid

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#1545]
Looking at the sidebar today, I noticed that the version check failed (not found). Taking a look at the URL that was being requested:

```
http://127.0.0.1:64932/api/v1/namespaces/linkerd/services/web:http/proxyhttps:/versioncheck.linkerd.io/version.json?version=git-dc4c2834?uuid=e4402244-3936-490b-aee0-580d68e35b88
```

It appears that the configuration for that got messed up a little bit.

**Comment by rmars** [comment]
I probably messed this up in #1540. Looking now!
