### ISSUE TITLE
`linkerd check` reports `FAIL` for slightly out-of-date linkerd versions

### ISSUE THREAD

**Issue by briansmith** [linkerd/linkerd2#1550]
The output of `linkerd check` when one isn't using the very latest version of linkerd2 is confusing and scary:

```
kubernetes-api: can initialize the client..................................[ok]
kubernetes-api: can query the Kubernetes API...............................[ok]
kubernetes-api: is running the minimum Kubernetes API version..............[ok]
linkerd-api: control plane namespace exists................................[ok]
linkerd-api: control plane pods are ready..................................[ok]
linkerd-api: can initialize the client.....................................[ok]
linkerd-api: can query the control plane API...............................[ok]
linkerd-api[kubernetes]: control plane can talk to Kubernetes..............[ok]
linkerd-api[prometheus]: control plane can talk to Prometheus..............[ok]
linkerd-version: can determine the latest version..........................[ok]
linkerd-version: cli is up-to-date.........................................[FAIL] -- is running version v18.8.2 but the latest version is v18.8.3
linkerd-version: control plane is up-to-date...............................[FAIL] -- is running version v18.8.2 but the latest version is v18.8.3

Status check results are [FAIL]
```

"FAIL" should mean "things are broken" but I don't think that using linkerd2 18.8.2 instead of 18.8.3 is that serious of an issue. If it *is* that serious of an issue then the output needs to be clearer that there is a serious problem with the old version of linkered2. If it *isn't* a serious problem then the output needs to be made less clear.

(Encountered when helping a user debug their installation.)

**Comment by hawkw** [comment]
Yeah, it seems like maybe `check` ought to have a concept of warnings as well as failures, or something?

**Comment by klingerf** [comment]
@adleong added warnings in #1807, so it should be straightforward to convert version mismatches from errors to warnings.
