### ISSUE TITLE
Downloading the CLI can be quite slow

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#1555]
Downloading the proxy via `time curl https://run.linkerd.io/install |sh` can take quite a while
```
curl https://run.linkerd.io/install  0.03s user 0.03s system 21% cpu 0.291 total
sh  2.14s user 0.40s system 5% cpu 48.053 total
```

The majority of the time appears to be spent fetching the binary from GitHub (S3):

```
:; time curl -sLo /dev/null https://github.com/linkerd/linkerd2/releases/download/v18.8.3/linkerd2-cli-18.8.3-darwin       
curl -sLo /dev/null   1.11s user 0.16s system 11% cpu 11.440 total

:; time curl -sLo /dev/null https://github.com/linkerd/linkerd2/releases/download/v18.8.3/linkerd2-cli-18.8.3-darwin
curl -sLo /dev/null   1.32s user 0.24s system 4% cpu 37.671 total
```

At a guess, we can probably reduce the size of the binary to about 1/3rd its original size by compressing the binary before upload to github.

**Comment by briansmith** [comment]
If downloading the CLI is too slow then I'm skeptical that reducing the time to 1/3 is going to be sufficiently fast. GitHub has pretty much has only disincentives to be a fast download hosting service, so maybe a bigger speed-up can be obtained by switching to another host.
