### ISSUE TITLE
Remove default tap rps in the Web UI

### ISSUE THREAD

**Issue by rmars** [linkerd/linkerd2#1557]
Currently all the web tap requests default to 1.0 RPS. We recently increased the default max rps to 100. We should remove the web defaulting and leave it up to the server defaults.

**Comment by adleong** [comment]
I think I was wrong when we spoke about this in person.  It looks as though there is no server side default for max-rps, which means it would take the zero value if left unspecified.  The CLI tap client uses 100 as the default max-rps if the command line flag is not set.  

We should add a server side default of 100 to the tap server or set max-rps to 100 by default in the requests web makes to the tap server (or both).

**Comment by rmars** [comment]
Ahhhhhh. okay!
