### ISSUE TITLE
Make tap filters look like design mocks

### ISSUE THREAD

**Issue by rmars** [linkerd/linkerd2#1561]
Design mocks:

![744c1dbb-c7d2-40b0-93fc-9846c9840335](https://user-images.githubusercontent.com/549258/44884787-3cbbf400-ac72-11e8-9a44-d9454d9d29b2.png)

**Comment by klingerf** [comment]
Would it be possible to use the new filter setup described in this issue to re-add client side filtering for tap data? I'd really like to be able to filter tap results by response status code, and it feels like we could accomplish that as part of the redesign.

**Comment by rmars** [comment]
Yeah! That was my plan. I think it would be good to re-add the client-side filtering.
