### ISSUE TITLE
public-api and tap services don't close open streams on shutdown

### ISSUE THREAD

**Issue by klingerf** [linkerd/linkerd2#1564]
This appears to be the same issue as #644, which occurred in the destination service.

When trying to shutdown the public-api service or the tap service, both will get stuck until all clients have closed all of their streaming connections. This means that these processes won't gracefully shutdown in Kubernetes if there are any ongoing streaming requests, and Kubernetes will be forced to kill them after waiting (1 minute, iirc) for them to shut down.

When the shutdown signal is received, these services should close all open streams and then shutdown gracefully as expected. See #1156 for the approach that we took to fixing this in the destination service.

**Comment by wmorgan** [comment]
How important is this?

**Comment by klingerf** [comment]
I'd say it's important for all of the control plane components to shutdown gracefully, but this particular issue is only a problem when an active tap is happening, either from the web UI or the CLI. So we should fix it, but I'm not as concerned with non-graceful kills of tap requests. I also don't think it would be a huge amount of work to fix it -- would just need to start tracking all open tap streams.
