### ISSUE TITLE
bin/dep script fails when using shasum 6.01

### ISSUE THREAD

**Issue by dadjeibaah** [linkerd/linkerd2#1567]
When running `DOCKER_TRACE=1 bin/mkube bin/fast-build` I run into this error:
```bash
Unknown option: p
Type shasum -h for help
Actual digest of /var/folders/w0/dck_4gys67zdm074x_m3tq740000gn/T/dep.XXX.flFGBdG9/depbin does not match expected digest.
```

It looks like the `bin/fast-build` depends on the script `bin/dep`. The dep script uses a `shasum` command for some dependency related work. It seems that the script relies on an older version `(5.84)` of `shasum`with -p flag that is no longer available in later versions of `shasum`. The error seems to occur in versions > 5.x. The version I used to produce this error was `6.01`.

**Comment by briansmith** [comment]
bin/fast-build allows you to skip the `bin/dep` step.

Should we replace `bin/fast-build` in the description of this issue with `bin/dep` since that seems generally broken?

**Comment by dadjeibaah** [comment]
Makes sense. I thought it would be good to add some context into how I came across the error but it may help to have bin/dep in the title for quick reference.
