### ISSUE TITLE
Add a '--context' argument to linkerd cli

### ISSUE THREAD

**Issue by bourquep** [linkerd/linkerd2#1571]
I have various clusters to manage (test, staging, prod), and they each have their own context in my kubeconfig.

It would be very useful to be able to provide a context name to any `linkerd` cli command. Benefits:

* I wouldn't have to 'kubectl config use-context' before each linkerd interaction
* It would be easier to script
* A watched command (e.g. `watch linkerd stat`) would not be affected by a `use-context` command in another terminal window.

**Comment by grampelberg** [comment]
TIL, I didn't realize it was missing. This is an awesome getting started issue!

**Comment by grampelberg** [comment]
@ffd2subroutine I believe so, you could use something like ahmetb/kubectx as well.

**Comment by bourquep** [comment]
If doing `use-context` under the hood also affects my own terminals' active context, then it would lead to the same issues as I have initially described.

I believe it would be best to simply pass `--context` to any kubectl commands you perform under the hood.

**Comment by ffd2subroutine** [comment]
@bourquep ah didn't know you could supply --context to kubectl. 
Yeah this makes sense.
