### ISSUE TITLE
Requests fail when src & dst are the same

### ISSUE THREAD

**Issue by tanuck** [linkerd/linkerd2#1585]
Hello,

When making HTTP1.1 requests where the `src` and `dst` are the same (a pod sending a request to itself) the proxy responds with a 500 status code. If the request is sent to a different pod in the deployment, everything works fine. If you send the request on the loopback address rather than the service DNS name, that is also fine. Is this expected?

```
$ linkerd version
Client version: v18.8.4
Server version: v18.8.4
```
Using the default sidecar generated from `linkerd inject`

Thanks

**Comment by grampelberg** [comment]
Well that sounds interesting. Is there anything special with your application? Are you using TLS? Could we see your k8s resource yaml?

**Comment by tanuck** [comment]
So no TLS. It was initially found on a deployment running a Node.js GraphQL application on port 80. I've since reproduced this on every other deployment I've tried.

Here is the simplest reproduction that I've found:
- `kubectl run nginx --image=nginx --port=80 --replicas=2 -o yaml --dry-run | linkerd inject - | kc apply -f -`
- `kubectl expose deploy nginx --port=80 --target-port=80 --type=ClusterIP`
- `exec` into one of the nginx containers and `curl -v nginx` - every other request should return 500

**Comment by grampelberg** [comment]
That's fantastic replication steps, thank you!

**Comment by tanuck** [comment]
Quick update - just upgraded to `v18.9.1` and this problem still persists.

**Comment by olix0r** [comment]
I'd be curious to see what `linkerd tap deploy nginx` shows while the curl command is run. Also, the output of `curl localhost:4191/metrics | grep -e request_total -e response_total` might be informative.

**Comment by seanmonstar** [comment]
Hm, so if the dst is a socket address, the proxy will use it directly, which would explain the loopback succeeding. However, if it's hostname, then it will either:

- If it looks like a service in the cluster, ask the controller for the socket address.
- Or perform a system DNS lookup, and try to use that.

Is it possible to collect debug logs from the proxy? Or do we have an environment that I can poke into and enable them myself?

**Comment by JCMais** [comment]
Having same issue.

We have a pod that acts as an authorization microservice, this pod can make requests to itself to check other permissions, so the hostname is `http://authorization`, this previously was working, after enabling linkerd2 it stopped working, `linkerd-proxy` container gives the following error:
```
ERR! proxy={server=out listen=127.0.0.1:4140 remote=10.16.0.48:60652} linkerd2_proxy::proxy::http::router service error: Error caused by underlying HTTP/2 error: protocol error: frame with invalid size
```

**Comment by seanmonstar** [comment]
Actually, while there was a proxy change for this, it won't be fixed until the iptables config is changed in this repo also.

**Comment by glindsell** [comment]
I'm seeing the same `reset-error=6` when trying to load balance gRPC using linkerd2 and nginx ingress.

Steps to recreate here:

https://github.com/glindsell/free-peer/tree/ingress/stream-meshed

**Comment by olix0r** [comment]
@glindsell thanks for putting together a repro and sharing! It's a little hard to tease out a clear problem description from that README, though. Would you mind opening a new issue so that we can make sure we get to the bottom of it?

**Comment by glindsell** [comment]
@olix0r good idea, I've updated the issue which I opened specifically for the purpose of gRPC stream load balancing with this info:

https://github.com/linkerd/linkerd2/issues/2120
