### ISSUE TITLE
Draw octopus arms

### ISSUE THREAD

**Issue by rmars** [linkerd/linkerd2#1587]
Currently the Octopus graphs have small arrows `->` connecting the boxes.
We need to draw the actual connections between the upstreams/downstreams.

We can do this by hand drawing SVG paths.
Zac will provide some starter svg files.

Part of #1468

**Comment by zachalbert** [comment]
@rmars Let me know if these work, or if you need something different.

[arrows.zip](https://github.com/linkerd/linkerd2/files/2362521/arrows.zip)
