### ISSUE TITLE
CLI - top - Allow consolidating traffic sources

### ISSUE THREAD

**Issue by bourquep** [linkerd/linkerd2#1593]
When using `top` against my public-facing API deployment, which is exposed to the public via nginx-ingress, every traffic source is displayed on a separate line for the same endpoint:

<img width="535" alt="image" src="https://user-images.githubusercontent.com/65096/45160842-6e741400-b1b8-11e8-9bdb-7cac10b6636c.png">

Since the nginx-ingress controller is deployed as a DaemonSet, the source traffic can come from any of the nodes. When using `top` in that scenario, I am not particularily interested in having the stats split by source node, I am mostly interested in the stats for any given API endpojnt, regardless of which nginx node directed traffic to it.

**Comment by grampelberg** [comment]
This is an awesome feature! @adleong what do you think about adding some truncation and grouping for src/dst? @rmars and I chatted about doing it in the dashboard a little yesterday, but I'm not sure that solution would work well in the CLI.

Does anyone know how top (or any of the popular ncurses CLI tools) handles this?

**Comment by adleong** [comment]
What about simply adding a `--withSources` flag that defaults to true?  When set to false the source column is not shown and the stats are not split out by source?

**Comment by grampelberg** [comment]
That's cool and totally worth doing. I was thinking of having a set of display options that you can trigger from inside `top` (like the OG `top`).
