### ISSUE TITLE
CLI - top - allow grouping similar paths based on regex (or other means)

### ISSUE THREAD

**Issue by bourquep** [linkerd/linkerd2#1594]
The `top` cli command displays all different paths on a separate line. This makes sense except for REST endpoints which have a resource identifier in the path. For example:

<img width="346" alt="image" src="https://user-images.githubusercontent.com/65096/45161114-1853a080-b1b9-11e8-91d2-d67a871c77fb.png">

When using `top`, I am mostly looking for stats for each endpoint, regardless of the resource identifier. In the above example, I'd rather see all `/api/v2/configs/*/xx` displayed as a single line in the top output.

This could be configured by providing regexes to the cli for each path expression to consolidate, and/or by pointing the cli to a Swagger/OpenApi definition.

**Comment by wmorgan** [comment]
Agreed 100% and great timing. We've been discussing this internally! We are working on the second approach currently (see linkerd/rfc#1), but I like the regex approach as a quick alternative.

**Comment by grampelberg** [comment]
Very cool, that's perfect.

**Comment by grampelberg** [comment]
@adleong feels like we can close this now based on service profiles?

**Comment by adleong** [comment]
Soon, but not quite yet.  I'm working on adding a `--routes` flag to `top` that will aggregate by route instead of by path.  This will give you a real-time sampled view of route data instead of the Prometheus based view that `linkerd routes` gives you.

**Comment by bourquep** [comment]
I see that the `--routes` top flag is available in edge-19.1.3, but when I try it all I see is:

```
Source                          Destination                    Route       Count    Best   Worst    Last  Success Rate
nginx-ingress-controller-67bhk  rest-api-f7bf4b474-j5zq2       [DEFAULT]      12     1ms   132ms    73ms       100.00%
```

But `linkerd routes` does show me all the routes configured in my service profile.

**Comment by bourquep** [comment]
Hmm, but `linkerd routes` shows me 0 rps for all routes, which can't be true on my prod cluster. Investigating.

**Comment by bourquep** [comment]
Forget my first comment (about `top --routes`), it was caused by #2173 

And my second comment (about `linkerd routes` showing 0rps is due to the fact that requests are coming in from a nginx-ingress controller:

<img width="862" alt="cleanshot 2019-01-30 at 15 30 14 2x" src="https://user-images.githubusercontent.com/65096/52010626-fe866300-24a3-11e9-8151-41ad9b728347.png">

**Comment by bourquep** [comment]
That being said, I believe this issue can be closed now that the `top` command has a `--routes` flag?

**Comment by klingerf** [comment]
@bourquep Awesome, glad to hear this is working for your use case.
