### ISSUE TITLE
Version check in the CLI

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#1604]
The `gcloud` CLI does this nice thing where it notifies you that there's a new version every time you run the CLI. It would be awesome if the `linkerd` CLI did something similar.

This should be output via. stderr (not stdout) and I'd love to have an option to silence the warning as it'll get a little annoying when you get it every time.

Here's a couple options:

```
There is a newer version of linkerd available. To update to the latest, please run:

$ curl https://run.linkerd.io/install | bash

To silence this warning, run:

$ linkerd config set versionCheck false
```

```
There is a newer version of linkerd available. To update to the latest, take a look at the documentation by running:

$ open https://linkerd.io/2/update

To silence this warning, run:

$ linkerd config set versionCheck false
```

```
There is a newer version of linkerd available. To update to the latest run:

$ linkerd update

To silence this warning, run:

$ linkerd config set versionCheck false
```

While I think the last one is the best long term solution, that has some implications that blow up the scope of this issue. Given that and the fact that there might be extended instructions, my vote is the second.

**Comment by klingerf** [comment]
This makes sense, but I think we'll need to open a separate issue for implementing a `linkerd config` subcommand. That doesn't exist at present.

**Comment by wmorgan** [comment]
I'd love to see this, though since this requires a (potentially slow) network call, we'll have to put some though into minimizing the user impact.

**Comment by grampelberg** [comment]
@wmorgan a best effort is probably good enough (but might not fit into the existing infrastructure that @klingerf mentioned to me).

eg. we fire off the request and if the response comes back before everything else is done, great. Otherwise, no change. For any long running commands that already hit the network (stat, check) there would be no issue.

If the version check fails (500, timeout, ...), we should probably just silently swallow that. Running the CLI in a firewall'd network would be frustrating.

**Comment by siggy** [comment]
For the next release, I'm going to at least modify the CLI to send current version, and possibly uuid, on `linkerd check`.
