### ISSUE TITLE
Figure out interaction between sidebar state and main page

### ISSUE THREAD

**Issue by rmars** [linkerd/linkerd2#1669]
Should the main page reflect the namespace selected in the sidebar?

For e.g. if a user selects a namespace and then goes to /pods, should the pod list be filtered to that namespace? 

Related: #1542

**Comment by dadjeibaah** [comment]
It looks like if we want this to work, we may need to do some work in the dashboard URL scheme to have some state into what namespace a user is working in and therefore dictate what the dashboard displays in the sidebar and in the main page. Each component in the dashboard would then have the ability to filter its information based on the current namespace in the URL. The URL scheme could look like this:

`/namespaces/_all`
The  Overview page, Tap, Top pages and all Resource List pages would display metrics from all namespaces. We us the `_all` url segment to represent all namespaces to avoid clashing with a namespace `all`.

`/namespaces/<namespace>/<resourceType>`
This would filter the Overview page to only show <namespace>, Tap and Top pages would have the namespace field populated with <namespace> and all resource lists would only show metrics from <namespace>

`/namespaces/<namespace>/<resourceType>/<resourceName>`
This would show the resource under that namespace. There was the idea that if we click on a resource name that is from a different namespace or if the sidebar namespace is changed to a different namespace, we would notify a user that they would no longer be working in <namespace> with a modal. This seems jarring and we may want a better way to handle this. We may not even need to notify the user that that are changing namespaces and take them straight to the overview page.

**Comment by grampelberg** [comment]
> We may not even need to notify the user that that are changing namespaces and take them straight to the overview page.

That's my vote. If you change the namespace selector it just bumps you out to the overview page.
