### ISSUE TITLE
Add validation that will disallow both `pre` and `proxy` checks

### ISSUE THREAD

**Issue by alenkacz** [linkerd/linkerd2#1690]
Right now, it's possible to issue the following command for linkerd check `linkerd check --pre --proxy` but these two are actually mutually exclusive as it's apparent from the documentation. What might be even more confusing it when you execute it as this `linkerd check --proxy --pre` because only pre-install are executed - that's given by the order of the if-clauses in the codebase https://github.com/linkerd/linkerd2/blob/master/cli/cmd/check.go#L75

I think it makes sense to add validation and if someone tries to trigger both just end with failure.

Another possible solution might be to allow running `pre` and `proxy` through the same invocation but not sure if that's desirable.

**Comment by alenkacz** [comment]
I can work on that if we agree on one of the solutions proposed :)

**Comment by klingerf** [comment]
@alenkacz Good find!

> I think it makes sense to add validation and if someone tries to trigger both just end with failure.

This sounds like the right approach to me. We do something similar with the `--to` and `--from` stat flags, [here](https://github.com/linkerd/linkerd2/blob/master/cli/cmd/stat.go#L399). We could add a similar `valdiate` func on the `checkOptions` struct. If you'd like to submit a PR we'd be more than happy to review.
