### ISSUE TITLE
Error with Headless services

### ISSUE THREAD

**Issue by aleerizw** [linkerd/linkerd2#1691]
Hi, I am not sure if this is a known issue / limitation:I have a service without a selector e.g.

```apiVersion: v1
kind: Service
metadata:
    app: my-service
  name: my-service
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 1337
  type: ClusterIP
```

https://kubernetes.io/docs/concepts/services-networking/service/#without-selectorsAnd I have an endpoints that refer to the IP addresses of the service (outside of k8s). When I try to access this service i.e.
`curl my-service/` I get a 500. The same works if the service is of type ExternalName.

On the controller pod i see the following error message:
```
"Target not found for endpoint {172.16.13.149  <nil> nil}"
```

where the `172.16.13.149` is the endpoint for the service.Are services without selectors not supported or is this a bug?

**Comment by aleerizw** [comment]
Looks like endpoints without TargetRef are simply ignored:

**Comment by grampelberg** [comment]
TIL, I didn't know you could run services like that!

**Comment by grampelberg** [comment]
@aleerizw could you explain a little bit more about how you're using this?
