### ISSUE TITLE
Expose grafana dashboards without `dashboard`

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#1692]
It is a little bit onerous to always run `linkerd dashboard` to see the grafana dashboards (especially if you're putting them up on a TV). Right now, you can't just expose that via ingress because the `root_url` is setup specifically for proxying. There should be some docs and maybe a couple little improvements to grafana that allow it to be visible both via `linkerd dashboard` *and* something like ingress.

**Comment by briansmith** [comment]
> Right now, you can't just expose that via ingress because the `root_url` is setup specifically for proxying.

The ideal solution would be for grafana to use only relative URLs so that `root_url` isn't necessary, or configure `root_url` to be relative, if it is already possible. Does grafana not support such configurations?

The main reason we can't "just expose via ingress" is that we would lose the authentication/authorization that Kubernetes provides. We have to have a plan for authentication/authorization for accessing the control plane (from outside of the cluster) before we can figure out the solution for problems like this.

**Comment by grampelberg** [comment]
> Is there an issue/PR that documents this?

I was just sitting on it hoping that there'd be a better story for grafana itself. I guess I could just get it up and added to the docs as is though. Lemme work on getting it polished into something more consumable by folks other than myself =)

**Comment by briansmith** [comment]
What are the actual requirements? AFAICT they are:

1. Users to be able to access the dashboard from outside the cluster without running `linkerd dashboard` first.
2. Users should be authenticated using their k8s credentials; e.g. the same ones that `kubectl` uses.
3. Access should be limited to authenticated users.
4. All the traffic should be protected with TLS.
5. Users shouldn't see a certificate error from their web browser when accessing the dashboard this way.

Is that right?

**Comment by grampelberg** [comment]
The only question in my mind is #2. The primary reason that I can come up with for this is to stick the dashboards up on TVs. I'm not sure I'd want to create a service account and deal with updating credentials there (especially given how quickly k8s auth tokens expire and how painful it is to get new ones for things like GKE). For this extremely specific use case, it feels like I'd rather just use an existing oauth account that takes care of all that for me.

I'd *maaaaybe* add a 6th - available via friendly URL that the end user controls (eg. linkerd.my.dev.domain).

**Comment by robertrbruno** [comment]
Not sure if this fits with the issue or is a new one.  I'd like to be able to expose the actual linkerd dashboard through my ingress.  

I have a workaround for the grafana dashboards already.  I just set up an independent grafana instance in a different namespace, added the linkerd prometheus as a datasource, and then finally added some of the grafana dashboards found the linkerd github.

**Comment by siggy** [comment]
Closes with #2039 and #2052.
