### ISSUE TITLE
embellish cli output with emoji/color/lol

### ISSUE THREAD

**Issue by siggy** [linkerd/linkerd2#1700]
as mentioned in TGIK8s:

emoji and color in `linkerd check`:
https://youtu.be/1dXJ34-KLe8?t=2739

ascii art / color / lolgopher for `linkerd dashboard`:
https://youtu.be/1dXJ34-KLe8?t=2797
https://github.com/kris-nova/lolgopher

**Comment by klingerf** [comment]
@siggy This feels like a dupe of #1471 -- would you mind posting a comment there and closing this?
