### ISSUE TITLE
Add single namespace install flag

### ISSUE THREAD

**Issue by klingerf** [linkerd/linkerd2#1705]
Update the `linkerd install` command to support a `--single-namespace` flag, which will cause the install YAML to use Roles and RoleBindings, instead of ClusterRoles and ClusterRoleBindings. This will allow folks who do not have cluster-wide access to still install the data plane and control plane in one namespace.

**Comment by olix0r** [comment]
I assume this means that we have to change all of the deployment/pod/service names to avoid collisions. It would be helpful to have a small write-up enumerating all of the differences between deployment models and the changes to the federated deployment model. Also, we need to consider the security implications of this model where the CA runs in the same namespace as the application. I'm not sure that we want to support TLS in this deployment model at all, for instance.

**Comment by grampelberg** [comment]
Let's track all the default behavior changes in #1336 please. This is a super focused issue that should be scoped as a small piece.

**Comment by moderation** [comment]
Re: mTLS @olix0r we would definitely like to be able to enable mTLS. The use case is a bunch of legacy apps that can't speak TLS. By adding mTLS at the linkerd2 layer we can get pod to pod transport security which is a big win.
