### ISSUE TITLE
Allow configuration of cluster base domain

### ISSUE THREAD

**Issue by icedream** [linkerd/linkerd2#1720]
Currently linkerd expects the cluster to use `cluster.local` as its base domain name, however more often than not a Kubernetes admin will decide to change that base domain to something else. This shouldn't break deployments, however in the case of linkerd2 it does as every generated configuration, from `linkerd install` to `linkerd inject`, assumes connection to happen via `cluster.local`-based domain names.

A workaround for this issue is to pipe generated configurations into `sed 's/cluster\.local/custom\.domain/g`. [This has been documented shortly in this pull request for the website](https://github.com/linkerd/website/pull/36) but I think it would be good for usage sanity to introduce a CLI option like `--cluster-domain=…` or a similar way to configure the base domain and inject it into the [respective template](https://github.com/linkerd/linkerd2/blob/b5ff29c8aa26a92e8e3a348fdc24b610e278e7e8/cli/install/template.go).

Not sure about this but this may also affect linkerd CLI functionality outside of generating templates. (Checks? Proxies?)

**Comment by ctaggart** [comment]
There is a workaround at https://github.com/linkerd/website/pull/36/files#diff-8f8a7890b984337e6c7f4646339d49a2R121
```
linkerd install | sed s/cluster\.local/name\.of\.your\.cluster/ | kubectl apply -f -
``

**Comment by icedream** [comment]
@ctaggart I mentioned that in the issue description already.

**Comment by olix0r** [comment]
I should note for whoever implements this: up until very recently, the proxy would not do any special discovery (including metric labeling) for services that do not use the default domain suffix. When we add an installation configuration, it should configure the appropriate proxy environment variables:

https://github.com/linkerd/linkerd2-proxy/blob/87fb677cdf5e1598b89b24c3f2adb6ccb6e1f01a/src/app/config.rs#L199-L220

**Comment by grampelberg** [comment]
To pull this all the way through, the domain should be made configurable and be passed to both `install`, `inject` and `profile` (a global CLI flag that will end up being used in multiple places).

**Comment by benley** [comment]
Is the mentioned workaround above known to work?  I just tried deploying with it and still ended up with errors, presumably because of the x509 certs pre-generated in the kubectl manifests that `linkerd install` produces:

```
time="2019-05-16T20:28:12Z" level=info msg="running version stable-2.3.0"
time="2019-05-16T20:28:12Z" level=fatal msg="Failed to verify issuer credentials for 'identity.linkerd.admin.us-east-2.aws.k8s' with trust anchors: x509: certificate is valid for identity.linkerd.cluster.local, not identity.linkerd.admin.us-east-2.aws.k8s"
```

**Comment by olix0r** [comment]
@benley It's likely that the workaround does not work since identity was introduced in stable-2.3.0...  I'd bet you could modify the  the workaround, though, to make this work by using, for instance, `linkerd install --identity-trust-domain=admin.us-east-2.aws.k8s` (or whatever suffix you expect) -- then the sed rewrite will lineup.

Still, I expect this workaround to continue to degrade in usefulness. At some point soon we'll want to make this an explicit parameter for `install`

**Comment by benley** [comment]
Thank you, that seems to have worked!  At the moment we're just doing some evaluation of linkerd2 and istio to get familiar with them, and this gets it up and running on our existing clusters.  Hopefully it becomes a supported config at some point!

**Comment by olix0r** [comment]
@benley Yeah, we've been slowly knocking down blockers to make this configurable (it was initially hardcoded in a variety of places)... We'd really like to just discover this configuration from the Kubernetes API, but up until now we haven't found a reliable discovery mechanism.

For what it's worth, there are only a few remaining hardcoded references:
```
cli/installsp/template.go:  name: linkerd-controller-api.{{.Namespace}}.svc.cluster.local
cli/installsp/template.go:  name: linkerd-destination.{{.Namespace}}.svc.cluster.local
cli/installsp/template.go:  name: linkerd-prometheus.{{.Namespace}}.svc.cluster.local
cli/installsp/template.go:  name: linkerd-grafana.{{.Namespace}}.svc.cluster.local
cli/installsp/template.go:  name: linkerd-tap.{{.Namespace}}.svc.cluster.local
cli/cmd/install.go:	defaultIdentityTrustDomain        = "cluster.local"
controller/k8s/api.go:	dst := fmt.Sprintf("%s.%s.svc.cluster.local", svc.Name, svc.Namespace)
pkg/inject/inject.go:	internalProfileSuffix = "svc.cluster.local."
pkg/inject/inject.go:	dns := fmt.Sprintf("linkerd-destination.%s.svc.cluster.local", ns)
pkg/inject/inject.go:	dns := fmt.Sprintf("linkerd-identity.%s.svc.cluster.local", conf.configs.GetGlobal().GetLinkerdNamespace())
pkg/profiles/openapi.go:			Name:      fmt.Sprintf("%s.%s.svc.cluster.local", name, namespace),
pkg/profiles/profiles.go:	clusterZoneSuffix = "svc.cluster.local"
pkg/profiles/proto.go:			Name:      fmt.Sprintf("%s.%s.svc.cluster.local", name, namespace),
pkg/profiles/tap.go:			Name:      fmt.Sprintf("%s.%s.svc.cluster.local", name, namespace),
controller/script/destination-client/main.go:	path := flag.String("path", "strest-server.default.svc.cluster.local:8888", "destination path")
controller/api/destination/server.go:// <service>.<namespace>.svc.cluster.local:<port>
controller/api/destination/server.go:		// <deployment>.deployment.<namespace>.linkerd-managed.linkerd.svc.cluster.local
controller/api/destination/k8s_resolver.go:	// Verify that `host` ends with ".svc.$zone", ".svc.cluster.local," or ".svc".
controller/api/destination/k8s_resolver.go:	// Accept "cluster.local" as an alias for "$zone". The Kubernetes DNS
```

We plan on removing this logic from the destination controller before 2.4. After that, I think it would be a pretty small change to support configuring this at install-time.

**Comment by benley** [comment]
It looks like a little bit more sed action is needed to start meshing - the output of `linkerd inject` also needs to have `sed 's/cluster.local/actual.cluster.domain/` applied.  Am I going to run into trouble if I try to get automatic sidecar injection working?

**Comment by olix0r** [comment]
@benley yes... and in fact in more recent edge release the webhook is _required_ (well, strongly encouraged).  For now you'd have to use `linkerd inject --manual ... | sed ...`

**Comment by benley** [comment]
Good to know, thanks for the warning.  I'm happy to try the edge releases when this part works!

**Comment by arminbuerkle** [comment]
What's the state of this?

I currently have a cluster with a different cluster domain than `cluster.local`.
I did `linkerd install` with `edge-19.6.1` and replaced every `cluster.local`.
It looks like everything works as expected except for auto proxy injection via webhook.

Are there any related PRs/Issues  that track the progress of this issue?

Taking a brief look at the code, it seem like it is something that needs to be implemented in proto?

Only having a proxy config annotation wouldn't help our use case since we'd like to deploy our services with the same template to different clusters which might have different cluster domains.

**Comment by warmfusion** [comment]
This appears to be causing issues on the linkerd2-proxy injection service as despite setting LINKERD2_PROXY_IDENTITY_SVC_ADDR via the --identity-trust-domain= flags and enabling the injectors we still see references to cluster.local in errors;

```
time="2019-06-25T13:32:34Z" level=info msg="running version stable-2.3.2"

INFO [ 0.001982s] linkerd2_proxy::app::main using destination service at Some(ControlAddr { addr: Name(NameAddr { name: "linkerd-destination.linkerd.svc.cluster.local", port: 8086 }), identity: Some("linkerd-controller.linkerd.serviceaccount.identity.linkerd.van-qa.local") })

INFO [ 0.002026s] linkerd2_proxy::app::main using identity service at Name(NameAddr { name: "linkerd-identity.linkerd.svc.cluster.local", port: 8080 })

INFO [ 0.002033s] linkerd2_proxy::app::main routing on V4(127.0.0.1:4140)

INFO [ 0.002040s] linkerd2_proxy::app::main proxying on V4(0.0.0.0:4143) to None

INFO [ 0.002046s] linkerd2_proxy::app::main serving admin endpoint metrics on V4(0.0.0.0:4191)

INFO [ 0.002051s] linkerd2_proxy::app::main protocol detection disabled for inbound ports {25, 3306}

INFO [ 0.002090s] linkerd2_proxy::app::main protocol detection disabled for outbound ports {25, 3306}

WARN [ 0.115805s] linkerd-identity.linkerd.svc.cluster.local:8080 linkerd2_proxy::proxy::reconnect connect error to ControlAddr { addr: Name(NameAddr { name: "linkerd-identity.linkerd.svc.cluster.local", port: 8080 }), identity: Some("linkerd-identity.linkerd.serviceaccount.identity.linkerd.van-qa.local") }: no record found for name: linkerd-identity.linkerd.svc.cluster.local type: AAAA class: IN

ERR! [ 5.005445s] admin={bg=identity} linkerd2_proxy::app::identity Failed to certify identity: grpc-status: Unknown, grpc-message: "the request could not be dispatched in a timely fashion"

ERR! [    20.007726s] admin={bg=identity} linkerd2_proxy::app::identity Failed to certify identity: grpc-status: Unknown, grpc-message: "the request could not be dispatched in a timely fashion"
```
