### ISSUE TITLE
Grafana pod in crash loop after looking at it

### ISSUE THREAD

**Issue by amandadebler** [linkerd/linkerd2#1730]
I installed linkerd2 and the emojivoto sample on a fresh Azure AKS cluster, adding --tls=optional when I injected linkerd into emojivoto, and it appears to be fine, until I open Grafana, either via the link that "linkerd dashboard" presents, or the Grafana icon next to a pod or deployment. The graphs look good for about a minute or so, but then the pod goes into the CrashLoopBackOff cycle, and stays there until I delete the pod; over a weekend, it rolled up over 1300 restart attempts. The newly-spawned Grafana pod runs fine for days - until I try looking at graphs again.

[2018-10-01-linkerd-init.log](https://github.com/linkerd/linkerd2/files/2432951/2018-10-01-linkerd-init.log)
[2018-10-01-linkerd-proxy.log](https://github.com/linkerd/linkerd2/files/2432952/2018-10-01-linkerd-proxy.log)
[2018-10-01-grafana.log](https://github.com/linkerd/linkerd2/files/2432953/2018-10-01-grafana.log)

**Comment by grampelberg** [comment]
Do you have the same issues without TLS?

**Comment by klingerf** [comment]
Am going to close this as a duplicate of #1747, which has a report of this still happening in the most release edge release.
