### ISSUE TITLE
Add check for NET_ADMIN to `check`

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#1732]
On secured clusters, it is highly possible that pods don't normally get permission to add NET_ADMIN. We should be checking that as a pre-flight.

**Comment by alenkacz** [comment]
@grampelberg I would be willing to tackle this one. Do you have any hints on how to approach that?

**Comment by mmack** [comment]
Guys is that NET_ADMIN capability really needed? 
That's really a no-go for enterprise setups... I wonder what the proxy init does in that case... Help appreciated...

**Comment by siggy** [comment]
@mmack we have plans to address the `NET_ADMIN` issue: #1887

**Comment by siggy** [comment]
@alenkacz Thanks for offering to help!

I'm less familiar with integration from the k8s side. From the Linkerd side I think it would go somewhere around:
https://github.com/linkerd/linkerd2/blob/4547ba7f0a12ed6c8204e833c79e862ed2ae65ff/pkg/healthcheck/healthcheck.go#L202.

Related, we're considering picking this up this week, but if you still want to work on it, you totally can. Let us know.

@grampelberg Any additional insight re: the capabilities @alenkacz linked to above?

**Comment by grampelberg** [comment]
@siggy as far as I'm aware, that's the right place to look. There's a different type of policy on OpenShift (SCC), but I'm not sure how that fits in here.

**Comment by alenkacz** [comment]
@siggy since the issue still seems to be not addressed I am looking into this now :)

**Comment by siggy** [comment]
For reference:
https://github.com/istio/istio.io/blob/52e19a81a20f6727966333af00630e9de32b44f7/content/help/ops/setup/required-pod-capabilities/index.md
https://preliminary.istio.io/help/ops/setup/required-pod-capabilities/

**Comment by siggy** [comment]
@alenkacz I should have checked in with you prior to pushing ahead with a PR. Apologies for swooping in, I'll check in from now on.
