### ISSUE TITLE
integration tests: 30s retry timeout too short

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#1735]
When tap_test.go is setting up, it will wait 30s for the test target to become available:

https://github.com/linkerd/linkerd2/blob/dccccebd79e1fb041194e7acdb61640bd22dcb3b/test/tap/tap_test.go#L87-L98

If the test is being run on a non-local cluster, it can spend 20-30s just pulling docker images, let alone running anything.

Can we increase these timeouts safely?  If not, can we make them configurable?

**Comment by klingerf** [comment]
It should be no prob to bump that timeout. Or alternative we might want to consider building the timeout directly into `TestHelper.CheckDeployment`, since we use that method in a few places, and it would be worthwhile to use the same timeout everywhere.

**Comment by klingerf** [comment]
Also this relates to #622, for which I've never come up with a good solution.
