### ISSUE TITLE
linkerd check should point user to GKE+RBAC documentation when necessary

### ISSUE THREAD

**Issue by wmorgan** [linkerd/linkerd2#1739]
We are currently adding this laborious parenthetical to every blog post we write about `linkerd install`:

> (Note: if your Kubernetes cluster is on GKE with RBAC enabled, you’ll need an extra step: you must grant a ClusterRole of cluster-admin to your Google Cloud account first, in order to install certain telemetry features in the control plane. To do that, run: ‘kubectl create clusterrolebinding cluster-admin-binding-$USER --clusterrole=cluster-admin --user=$(gcloud config get-value account)’.)

`linkerd check` should detect this problem proactively and point the user to the relevant docs page in the error message, so that we don't have to insert this verbiage.

**Comment by siggy** [comment]
Fixed via #2087.
