### ISSUE TITLE
Add linkerd tap table subcommand

### ISSUE THREAD

**Issue by adleong** [linkerd/linkerd2#1744]
Add a `linkerd tap table` subcommand which displays an ncurses style live updating table based on tap data.  The table should have columns for source, destination, path, latency, success rate, and count.

Note that this functionality already exists as the `linkerd top` command.  This effectively renames `linkerd top` to `linkerd tap table`.  This helps to clarify that the data in the table is live sampled data.

This command should also have a flag (--routes maybe) which replaces the path column with a route column.  This is only available if the underlying tap data has route annotations from a service profile.

For consistency, we can also rename the existing `linkerd tap` command to `linkerd tap stream`.

**Comment by adleong** [comment]
@grampelberg How do you feel about this?  The proposal here would be to rename:

tap -> tap steam
top -> tap table
routes -> top

but I'm kinda feeling like the names we have now are okay.  WDYT?

**Comment by grampelberg** [comment]
@adleong any thoughts on what the columns should be and how this should look?

**Comment by adleong** [comment]
Unclear if we want to pursue this.  I think this just entails renaming `linkerd top` to `linkerd tap table` to make it more clear that the output is a tabular representation of tap data.

**Comment by grampelberg** [comment]
Oh, I was thinking it would be a table format for `tap` like the dashboard has. I was interested in it because we could group req/resp/end and do a better job with expanding data for `-o wide`.

**Comment by adleong** [comment]
Interesting.  Seems like that kind of functionality is better suited to web than to the CLI.  I'm sure we could replicate the functionality in ncurses style, but I'm not totally convinced of the value.

**Comment by grampelberg** [comment]
That's a great point, you've talked me out of it.
