### ISSUE TITLE
Update proxy-injector to support non-deployment workloads

### ISSUE THREAD

**Issue by klingerf** [linkerd/linkerd2#1751]
Once #1714 merges, the proxy-injector process can be used to auto-inject deployment configurations that are applied to the cluster. The process does not support other workloads that include pod specs, such as statefulsets, daemonsets, and individual pod definitions. We should update the process to support these.

**Comment by reegnz** [comment]
I just encountered this issue with StatefulSet, verified that it also doesn't work with DaemonSet.

I think the best approach would be to move towards injecting pods like suggested in #2342

**Comment by alpeb** [comment]
Fixed via #2472
