### ISSUE TITLE
Parsing TCP traffic: redis, cassandra, ES, memcache, whatever's next

### ISSUE THREAD

**Issue by sokoow** [linkerd/linkerd2#1779]
## Feature Request

Now that your proxy is being able to oversee all TCP/HTTP traffic, it'd be nice to do some inspection of traffic for tracing purposes - so show queries and timings mostly for storage related products.

### What problem are you trying to solve?

Trying to add to tracing portfoio, so our lovely developers have it even easier.

### How should the problem be solved?

Well, not with the deep packet inspection I suppose.. maybe parse the request body, have a template for each product that you match, and then display it in clicky details of HTTP request ? 

What do you want to happen? Add any considered drawbacks.

I'd like to see query details for mentioned products.

### Any alternatives you've considered?

Nothing that other products propose unfortunately.

Is there another way to solve this problem that isn't as good a solution?

Well proxy has a first row of access to TCP/HTTP traffic, so I think it's the best way to resolve it.

### How would users interact with this feature?

Linkerd UX ?

If you can, explain how users will be able to use this. Maybe some sample CLI
output?

No idea yet

**Comment by grampelberg** [comment]
@sokoow are you looking for request/response payloads and headers?

**Comment by sokoow** [comment]
I think for cassandra, you need to parse some packets, like here: https://github.com/blackberry/cqlsniff/blob/master/src/cqlframe.h

redis might be here: https://github.com/hirose31/redis-traffic-stats and here: https://www.vividcortex.com/resources/network-analyzer-for-redis

mysql: https://github.com/Qihoo360/mysql-sniffer

postgres, might be slightly easier as it is in Go already: https://github.com/c77cc/pgsniffer

The way I see it, is that V1 of this feature might be about parsing the traffic only when an annotation would be added to the pod in a per-service specific manner, so you'd need to tell the proxy 'listen to this pod, it's a postgres' and then enable stats and decoding for it. It's a pretty neat feature.

**Comment by grampelberg** [comment]
That makes sense, we just need to pick what's the highest priority and get the support into the proxy (rust).

**Comment by gamer22026** [comment]
Was just wondering if any of the protocol sniffing work done by the packetbeat folks [here](https://github.com/elastic/beats/tree/master/packetbeat/protos) would be of use?

**Comment by hawkw** [comment]
@gamer22026 Unfortunately, probably not. Any protocol detection or support would have to be in Linkerd 2's data plane (proxy) layer, which is written in Rust, rather than its control plane, the component written in Go.

**Comment by grampelberg** [comment]
Closing this issue out as a generic protocols one. Please open specific issues for the protocols you're interested in.
