### ISSUE TITLE
proxy: failed to read SO_ORIGINAL_DST errors

### ISSUE THREAD

**Issue by klingerf** [linkerd/linkerd2#1787]
### What is the issue?

A few folks in the linkerd slack have reported seeing the following error in the proxy logs:

```
ERR! proxy={server=in listen=0.0.0.0:4143} linkerd2_proxy::transport::addr_info::linux failed to read SO_ORIGINAL_DST: Os { code: 2, kind: NotFound, message: "No such file or directory" }
```

Followed by the proxy eventually panicking, with:

```
thread 'main' panicked at 'couldn't get remote addr!: Os { code: 107, kind: NotConnected, message: "Transport endpoint is not connected" }', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

### How can it be reproduced?

@ryan-dyer-sp reports seeing this issue immediately when injecting an elasticsearch pod with TLS. Removing TLS fixes the issue.

@Capitrium reports seeing this sporadically, after a pod has been running successfully for some amount of time.

### Environment

@Capitrium is running on coreos 1855.4.0 / aws

**Comment by ryan-dyer-sp** [comment]
Yes we see this on our ES client nodes.  The ES client fails to talk to discover the master nodes.  I can provide kube manifests of our ELK stack, if this helps in troubleshooting.

**Comment by ryan-dyer-sp** [comment]
https://github.com/pires/kubernetes-elasticsearch-cluster . our implementation is just a few minor customizations on top of this (modifying cluster name, different replicaset sizes, etc.).  we're also running 6.1.1 vs the 6.3.2 it is up to now.
