### ISSUE TITLE
MaterialUI followup: Tooltips

### ISSUE THREAD

**Issue by rmars** [linkerd/linkerd2#1788]
As mentioned in #1776, tooltips sometimes snap to the upper left corner.

@siggy any steps for reproducing this?

**Comment by siggy** [comment]
I only saw it on the ServiceMesh page, when mousing over Meshed Status
![tooltip](https://user-images.githubusercontent.com/236915/47191467-70bfa700-d2fc-11e8-9aab-e3c0665cc370.png)

**Comment by rmars** [comment]
To reproduce: activate a tooltip in the ServiceMesh page, and hover over it for a while (3 sec). It snaps to the top right.

**Comment by rmars** [comment]
I think this might be due to the creating of a new `StyledProgress` component on each render based on the colour of the bar. Might need to find a way to style that property differently.
