### ISSUE TITLE
Dashboard: Add sorting and filtering to Metric Tables

### ISSUE THREAD

**Issue by rmars** [linkerd/linkerd2#1792]
If we don't want to implement the sorting/filtering ourselves, https://github.com/gregnb/mui-datatables looks like a good option.

**Comment by klingerf** [comment]
Related to this issue, I noticed that the top tables in the UI are no longer sorted in descending order by request count:

![image](https://user-images.githubusercontent.com/9226/47454442-1a32ec80-d784-11e8-9fc2-05038edc5779.png)

When support for sorting is added, we should restore the default sort by count for these tables.

**Comment by klingerf** [comment]
Sorting was implemented in #1814, but filtering still needs to happen.

**Comment by scottcarol** [comment]
@rmars @grampelberg What do you think of this proposed UI for filtering tables, inspired by Material-UI [table demo](https://material-ui.com/demos/tables/)?

Top image is existing UI.

Bottom image is proposed UI. It moves the table title inside the table box itself. The filter field is on the top right. I think the size of the filter field could be a little smaller, but want feedback from you on overall look and feel.

![currentlinkerdtable](https://user-images.githubusercontent.com/2289389/52655547-409ea400-2ea9-11e9-90ec-7b79c6d50357.png)

![proposed linkerd table](https://user-images.githubusercontent.com/2289389/52655558-44322b00-2ea9-11e9-96b3-793e07510d0d.png)

**Comment by grampelberg** [comment]
I like it, here's the k8s dashboard for reference (which appears to do it the same way).

<img width="1006" alt="screenshot 2019-02-12 09 37 11" src="https://user-images.githubusercontent.com/47992/52655775-dcc8ab00-2ea9-11e9-9eab-0360494cdb1a.png">
<img width="1017" alt="screenshot 2019-02-12 09 37 17" src="https://user-images.githubusercontent.com/47992/52655776-dcc8ab00-2ea9-11e9-8435-6e800b22ac71.png">

**Comment by scottcarol** [comment]
@grampelberg Thanks, good call on referencing k8s dashboard!
