### ISSUE TITLE
service profiles with ports

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#1794]
Currently, service profiles are implemented as CRDs such that that the name of the resource corresponds to the destination being passed to the service. However, destination names are in the form `host:port`; and Kubernetes does not allow colons in resource names:

```
The ServiceProfile "voting-svc.emojivoto:8080" is invalid: metadata.name: Invalid value: "voting-svc.emojivoto:8080": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```

The destination service needs to support looking up service profiles for destinations that include ports.

**Comment by adleong** [comment]
@olix0r we currently solve this by having the controller strip the port off of the authority that it gets from the proxy.  Is that sufficient to close this issue?
