### ISSUE TITLE
Table column filtering is missing in new UI

### ISSUE THREAD

**Issue by prasanthj** [linkerd/linkerd2#1822]
### What is the issue?
Old UI used to have column filtering for example in the /pods page. New material UI in edge-18.10.4 seems to be missing pod filtering which is handy when 100s of pods. 

### How can it be reproduced?
/pods UI does not have filtering for any columns.

### Logs, error output, etc

(If the output is long, please create a [gist](https://gist.github.com/) and
paste the link here.)

#### `linkerd check` output

```text
your output here ...
```

### Environment

- Kubernetes Version: 1.10.3
- Cluster Environment: AWS EKS
- Host OS: Linux 2 (default AMI)
- Linkerd version: edge-18.10.4

### Additional context
Honestly the old UI looked much better than the material UI :)

**Comment by klingerf** [comment]
@prasanthj Thanks for reporting this, and thanks for giving the new UI a spin. #1792 tracks re-adding filter support in tables, so I'm going to close this one as a dupe.
