### ISSUE TITLE
proxy: Predictable response classification logic

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#1832]
When the proxy calculates latency, it includes a "classification". That is, it includes labels that indicate whether the response should be considered a success or failure.

Because the proxy, rightly, measures latency as it processes the first data frame (or EOS), this means that we must classify responses eagerly, before we know whether the rest of the response completes successfully.

Alternatively, in some cases (like for gRPC streams), we cannot know the classification until the stream completes, and as such we cannot update the latency in a timely fashion.  This can make metrics data misleading, as it may hide or misrepresent latency in the system.

To resolve this---and to simplify classification semantics for service profiles--I propose the following:

1. The proxy continues to report latency as time-to-first-byte.
2. Response latencies will _not_ include classification.
3. Response counts will include classification labels, and will only be incremented once a stream completes.

This allows us to change the classification API so that only complete streams are classified.

**Comment by klingerf** [comment]
Omitting `classification` labels from latency metrics works for me. I've verified that the controller only consumes `classification` labels for the `response_total` metric.

**Comment by olix0r** [comment]
@klingerf Thanks for checking. I think we should change `tcp_close_total` requests to stop using `classification` -- the majority of sockets will close with some error code, though this is in no way a failure. I'll look at making this change.

**Comment by hawkw** [comment]
This seems correct to me 👍
