### ISSUE TITLE
have feature linkerd2 to support mesos?

### ISSUE THREAD

**Issue by mushixun** [linkerd/linkerd2#1837]
--------------^ Click "Preview" for a better view!

We primarily use GitHub as an issue tracker. For any questions you may have,
please check out the resources below.

---

- Mailing List: https://lists.cncf.io/g/cncf-linkerd-users

- Slack: https://slack.linkerd.io

- Discourse: https://discourse.linkerd.io/

- Twitter: https://twitter.com/linkerd

**Comment by grampelberg** [comment]
LD2 does not support mesos right now. Please open a feature request if you'd like it to.
