### ISSUE TITLE
Integration tests should reliably pass in community cluster

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#1838]
In linkerd's community cluster, the linkerd2 integration tests frequently fail due to various timing related issues.

This is presumably because, among other things like resource contention, it is slower to pull docker images at creation-time.

Let's make sure that the test runner can at least be configured so that a command can be run that can reasonably be expected to succeed  .

For example #1227 #1735

**Comment by dadjeibaah** [comment]
I think it's safe to close this issue, any objection @olix0r

**Comment by klingerf** [comment]
I agree that we can close both this issue and #622, but I'm not a regular users of the community cluster, so hopefully somebody else can confirm.

**Comment by klingerf** [comment]
I just successfully ran integration tests on the community cluster with the edge-18.11.3 release that was published a few minutes ago. Going to call this fixed.
