### ISSUE TITLE
Issues with `linkerd install --linkerd-namespace [$namespace] -—single-namespace | kubectl apply -f -` when execute with limited role.

### ISSUE THREAD

**Issue by jimcal** [linkerd/linkerd2#1847]
### What is the issue?
Because I am operating from an user within a enterprise version of kubernetes clusters, I only have namespace level permission. With the help from @rmars & @wmorgan, I was able to try out the `--single-namespace` feature in edge release. However, there seems to be sign of bugs and I will attempt to document them.  

### How can it be reproduced?
[the namespace I operate within is called `clickstream`]
I ran `linkerd install --linkerd-namespace clickstream —single-namespace | kubectl apply -f -`

### Logs, error output, etc

(If the output is long, please create a [gist](https://gist.github.com/) and
paste the link here.)
https://gist.github.com/jimcal/937ddfb95e97ce8da4c51e7fef737bda

#### `linkerd check` output

```text
kubernetes-api: can initialize the client..................................[ok]
kubernetes-api: can query the Kubernetes API...............................[ok]
kubernetes-api: is running the minimum Kubernetes API version..............[ok]
kubernetes-setup: control plane namespace does not already exist...........[FAIL] -- The "clickstream" namespace already exists
kubernetes-setup: can create Namespaces....................................[FAIL] -- Missing permissions to create Namespace

Status check results are [FAIL]
```

### Environment

- Kubernetes Version: Client Version: v1.9.6 / Server Version: v1.10.8
- Cluster Environment: Enterprise self administrated Kubernetes platform on AWS 
- Host OS: Container Linux by CoreOS 1855.4.0 (Rhyolite)
- Linkerd version: edge-18.11.1

### Additional context
Related issue https://github.com/linkerd/linkerd2/issues/1846

**Comment by klingerf** [comment]
@jimcal Thanks for reporting this, and for providing the output of your linkerd install command. From looking at the output, it appears that there are a few issues.

```
Error from server (Forbidden): error when applying patch:
{"metadata":{"annotations":{"cloud-team-id":null,"contact-email":null,"cost-center":null,"kube2iam.beta.*******.net/allowed-roles":null,"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"v1\",\"kind\":\"Namespace\",\"metadata\":{\"annotations\":{},\"name\":\"clickstream\",\"namespace\":\"\"}}\n","kubernetes.io/change-cause":null},"creationTimestamp":null,"namespace":"","resourceVersion":null,"selfLink":null,"uid":null},"spec":null,"status":null}
to:
&{0xc4200fafc0 0xc4204018f0  clickstream STDIN 0xc4217171a8 407302412 false}
for: "STDIN": namespaces "clickstream" is forbidden: User "**************" cannot patch namespaces in the namespace "clickstream"
```

^ This error means that the namespace to which you're deploying linkerd already exists in your cluster, and your user does not have permission to reconfigure namespaces in the cluster. This relates to my comment on #1846, and as part of fixing that issue we should stop outputting the namespace YAML when `linkerd install --single-namespace` is run.

---

The rest of the errors in that log are of the form:

```
cannot get clusterroles.rbac.authorization.k8s.io at the cluster scope
cannot get clusterrolebindings.rbac.authorization.k8s.io at the cluster scope
cannot get customresourcedefinitions.apiextensions.k8s.io at the cluster scope
```

This suggests that the install config included `ClusterRoles` and `ClusterRoleBindings`, but that shouldn't be the case if you ran the install with the `--single-namespace` flag; we should instead be using `Roles` and `RoleBindings`, and I wouldn't expect for those error message to appear. Can you try re-running the install and ensuring that `--single-namespace` is set, to see if that fixes the issue?

**Comment by klingerf** [comment]
Hmm, ok, thanks for retrying it. I'm really not sure where those messages about `clusterroles.rbac.authorization.k8s.io` are coming from. I'd expect that to instead check `roles.rbac.authorization.k8s.io`.

I wonder if this has to do with the fact that the install YAML includes a custom resource definition (CRD). I'm not sure it's possible to create the CRD itself in only one namespace (instances of the CRD can be namespaced, however). Maybe you can use the `kubectl auth can-i` subcommand to investigate? Can you paste the output from these three commands?

```
kubectl auth can-i create roles --namespace clickstream
kubectl auth can-i create clusterrolebindings --namespace clickstream
kubectl auth can-i create customresourcedefinitions --namespace clickstream
```

**Comment by jimcal** [comment]
```
| =>kubectl auth can-i create roles --namespace clickstream
yes
| =>kubectl auth can-i create clusterrolebindings --namespace clickstream
no
| =>kubectl auth can-i create customresourcedefinitions --namespace clickstream
no
```

Hope that helps :)

**Comment by jimcal** [comment]
Thanks @klingerf , you are right that `kubectl auth can-i create rolebindings --namespace clickstream` return "yes". 

Please let me know if there is something else I can provide.
