### ISSUE TITLE
Add option to shutdown proxy when all the other containers are shutdown

### ISSUE THREAD

**Issue by serkangunes** [linkerd/linkerd2#1850]
# User Stories
* As a developer I would like to be able to shutdown linkerd-proxy last and allow my containers to send network requests during their shutdown period.
## Rationale
Currently some of my services listen for SIGTERM or SIGINT signals to start shutting themselves. During the shutdown period they do one last network call to a central registry to deregister themselves. When I am using linkerd-proxy during shutdown linkerd-proxy will listen to similar signals and start shutting down immediately, because of the proxy shutting down before my other containers all the outbound network connections fail.
I would like to be able to tell linkerd-proxy to shutdown last. Currently only way to achieve this is to inject preStop lifecycle hook to the proxy definition.

**Comment by wmorgan** [comment]
Thanks for writing this up, @serkangunes!

**Comment by serkangunes** [comment]
No problem. Hope it makes sense.

**Comment by klingerf** [comment]
There's some related discussion of container startup/shutdown ordering happening here: kubernetes/kubernetes#65502.
