### ISSUE TITLE
Update `Request Rate` to include units

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#1865]
### What problem are you trying to solve?

In the new UI, we've moved from `RPS` to `Request Rate`. That ends up being a little confusing as to what the units are. 

### How should the problem be solved?

Change `Request Rate` back to `RPS`. This has the added benefit of reducing the column size and getting rid of wrapping.

### Any alternatives you've considered?

It would be possible to add units (always seconds) but that seems like extra characters and will still have the wrapping problem.

**Comment by rmars** [comment]
Fixed by #1927
