### ISSUE TITLE
Adjust telemetry reporting of paths to handle higher cardinality

### ISSUE THREAD

**Issue by seanmonstar** [linkerd/linkerd2#187]
WIth the inclusion of HTTP/1 traffic through the proxy, there will likely be many more unique paths reported through the telemetry than when just proxying gRPC traffic. The controller currently stores the request path as a label in Prometheus. Prometheus documentation recommends not using labels with high cardinality, or things go badly, so we need to adjust this before shipping Proxy Transparency.

Some things we can do:

1. Remove the path from telemetry entirely. This is the easiest approach, but request paths can be very useful, so this would seem unfortunate to lose completely.
2. Try to dynamically build up patterns of paths to collapse them. This would probably be a lot more work, but is probably the most desirable.
3. Allow a user to configure patterns and/or the reporting of paths. We're hoping to be a no-config tool, so this is probably not the way forward.

cc #167

**Comment by hawkw** [comment]
Hmm, this problem seems familiar!

**Comment by siggy** [comment]
## Proposal

I think option 2 is doable for the initial release. We could do something naive, where path components exceeding a certain hard-coded cardinality threshold (10?) would be aggregated. We could make this threshold configurable, but probably not necessary for an initial release.

### Example

Given a threshold of 3 and these paths:

`/foo/a/bar`
`/foo/b/bar`
`/foo/c/bar`

if the telemetry service encounters:
`/foo/d/bar`
then all paths collapse into:
`/foo/*/bar`

### Approach

The aggregation of path labels must occur prior to storage in Prometheus, as Prometheus cautions against high cardinality labels values: https://prometheus.io/docs/practices/naming/#labels

This leaves the `proxy`, `proxy-api`, and `telemetry` services as candidates for path aggregation. As the `proxy` only has knowledge of a single instance of a service, and `proxy-api` has no knowledge of telemetry, the `telemetry` service is a natural location for this implementation.

All paths transiting through the `telemetry` service may be represented as a tree structure. In the above example:

```
1:       \
2:      foo
3:  a    b    c
4: bar  bar  bar
```

Once a node has a child count exceeding the threshold, we collapse the children:
```
1:       \
2:      foo
3:       *
4       bar
```

#### Open issues

##### Multiple telemetry instances

If `---controller-replicas` is > 1, the aggregation data will not be shared between telemetry instances, yielding inconsistently collapsed paths for paths that are only slightly above the aggregation threshold. Path components that exceed the threshold by (`controller-replicas` x `threshold`) would approach consistency across all instances.

A longer-term approach to address multiple `telemetry` instances could be to consistently pin metrics to specific instances of the telemetry service, guaranteeing that all variations of a service's path are aggregated by a single `telemetry` instance.

##### Path collapse boundaries

Another issue with this approach is the metrics representation before and after a path collapse will not be consistent. In the above example, the 3 discrete paths would be recorded in Prometheus prior to the path collapse. After path collapse, metrics representing the discrete paths would cease to exist. This could be confusing to the end-user. As time passes and older metrics expire, this data would eventually become consistent.

##### Collapse expiration

Related to collapse boundaries. There may be path components that tend towards low-cardinality over time. The telemetry service could monitor these cases and dynamically expand these path components.

### A note about Prometheus relabel configs

Prometheus provides `relabel_configs` to allow collection-time modifications of metric names and labels:
https://prometheus.io/docs/prometheus/latest/configuration/configuration/#<relabel_config>

These relabeling rules can be modified without restarting prometheus. This approach may not buy is much, as it would still be the responsibility of the `telemetry` service to detect when path collapse should happen.

**Comment by briansmith** [comment]
Just to clarify, there's nothing HTTP/1-specific about this. We have the same issue for any non-gRPC HTTP traffic, regardless of the HTTP version.

**Comment by olix0r** [comment]
Thanks for writing this up, @siggy! This is a nice overview of the issue.

I'm curious if we may be able to come at this problem from a slightly different angle as we consider how it scales...  I think we should be able to get more insight into what users actually care to describe as we introduce policy primitives in the upcoming releases. This could change this problem from "how do we process arbitrary many paths" to "how do we tie telemetry to policy?"

This is hand-wavey at the moment, but I can provide more concrete examples of what I mean as we make progress on policy

**Comment by klingerf** [comment]
Am going to close this as fixed. For the record, the fix that's in place now is this proposal from the issue description:

> 1. Remove the path from telemetry entirely. This is the easiest approach, but request paths can be very useful, so this would seem unfortunate to lose completely.

Additional work for recording historical path stats is being tracked in #1737.
