### ISSUE TITLE
Profiles feel broken until the first stats are collected

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#1875]
### What problem are you trying to solve?

After adding a service profile to my cluster, it took quite awhile (60s+) to see the stats in `routes`. In that time, I had no idea whether the profile was valid, whether data was being collected at all and if I'd see anything. Instead, I just saw the following message:

```bash
$ linkerd -n emojivoto routes web-svc
No traffic found.  Does the service have a service profile?  You can create one with the `linkerd profile` command.
```

### How should the problem be solved?

It would be nice to know that there is a profile:

```bash
$ linkerd -n emojivoto routes web-svc
ROUTE       SUCCESS      RPS   LATENCY_P50   LATENCY_P95   LATENCY_P99   TLS
/api/list     0.00%   0.0rps           0ms           0ms           0ms    0%
/api/vote     0.00%   0.0rps           0ms           0ms           0ms    0%
[UNKNOWN]     0.00%   0.0rps           0ms           0ms           0ms    0%
```

**Comment by adleong** [comment]
I think the ideal solution here is to have an API that lists the existence of a profile for the given authorities and lists the routes.  This allows us to:
* populate the full list of routes, even the ones that are getting no traffic
* display a call-to-action when the service profile does not exist
