### ISSUE TITLE
proxy: LINKERD2_PROXY_INBOUND_FORWARD not fully honored

### ISSUE THREAD

**Issue by siggy** [linkerd/linkerd2#1883]
### What is the issue?

Following linkerd/linkerd2-proxy#122, the `LINKERD2_PROXY_INBOUND_FORWARD` environment variable is no longer fully honored. Specifically, the port is used, but the ip is ignored, traffic is always forwarded to localhost.

#### Start a server on localhost:8888

```bash
$ python -m SimpleHTTPServer 8888
```

#### Start linkerd2-proxy with `LINKERD2_PROXY_INBOUND_FORWARD` set to a remote IP (note the logs still imply forwarding to a remote host)

```bash
$ LINKERD2_PROXY_LOG=info LINKERD2_PROXY_INBOUND_LISTENER=tcp://0.0.0.0:9999 LINKERD2_PROXY_INBOUND_FORWARD=tcp://10.10.10.10:8888 LINKERD2_PROXY_POD_NAMESPACE=default ./target/debug/linkerd2-proxy
...
INFO linkerd2_proxy::app::main proxying on V4(0.0.0.0:9999) to Some(V4(10.10.10.10:8888))
```

#### Send a request to `LINKERD2_PROXY_INBOUND_LISTENER`

```bash
$ curl localhost:9999
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 3.2 Final//EN"><html>
<title>Directory listing for /</title>
<body>
<h2>Directory listing for /</h2>
```

### Possible solution

The most straightforward fix could be to rename it to `LINKERD2_PROXY_INBOUND_FORWARD_PORT` and update the docs.

That said, there is some utility in testing a linkerd2-proxy locally, forwarding to remote address. Specifically, to test proxying to a remote server with a bespoke protocol or API, where setting up that server locally is prohibitively time consuming.

**Comment by seanmonstar** [comment]
Besides this report, I don't believe we ever use that option, so I've been thinking that it should just be removed. Are there enough valid cases where we'd want the inbound connections forwarded to some external IP?

**Comment by siggy** [comment]
I tried debugging the proxy against a remote address last week, which led to this ticket. I'm fine removing this particular env var, but going forward it would be useful to have that functionality available in some way. AFAIK right now the only way to test a proxy against a remote server is deploying it with a control plane.
