### ISSUE TITLE
Allow for operation on clusters that restrict NET_ADMIN

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#1887]
### What problem are you trying to solve?

Many production clusters are locked down and do not allow arbitrary pods to have `cap_net_admin`. This makes it, unfortunately, impossible to use linkerd in these environments.

### How should the problem be solved?

It would be nice to have an option (addon?) that does the iptables configuration outside of a pod's initContainer. This would allow an operator with elevated privileges to add the solution to the cluster and have arbitrary pods have minimal privileges.

A good solution would be creating a CNI plugin that does the iptables setup. A DaemonSet would be added to the cluster which adds the CNI plugin to the set. Each time a pod is scheduled, the iptables rules would be added as part of network setup. This allows for them to be in place when the pod starts up (there might be some oddities with initContainers?).

Take a look at istio/cni for some good previous work.

### Any alternatives you've considered?

- DaemonSet controller that updates iptables - Obviously the easiest solution, there are real sync problems and issues with pods starting that don't have rules in place (making policy a little difficult).
- HTTP_PROXY options - Would only work for outgoing traffic, which isn't great.

### How would users interact with this feature?

This should be optional and not default. It would be an awesome use of addons:

```bash
linkerd add secure-cluster-helper
```

There are definitely some big open questions about the interactions between this and things like the auto-inject feature.

**Comment by mmack** [comment]
Great to see this picked up! If you need testers let me know...

In my opinion, even if it is not required, skipping root images and avoiding cap_net_admin priviledges is always a good thing and should be the default. Or are there any downsides other than deploying a deamonset for management?

**Comment by grampelberg** [comment]
@mmack there are definitely tradeoffs. After digging into this some more, it looks like going the CNI route is more sustainable than a daemonset controller (for obvious sync reasons). Unfortunately, not every environment lets you add a new CNI plugin.

Ideally, this *would* be the default though, just need to make sure it works in most cases and has clear guard rails. Some `check` integration would help quite a bit.

**Comment by mmack** [comment]
@grampelberg so the plan is to add a second CNI? My primary is calico atm...

**Comment by grampelberg** [comment]
@mmack that looks like the best solution I can find so far. You add a new CNI plugin to the chain that simply sets the iptables rules up (and cleans them up on teardown).
