### ISSUE TITLE
Add routes to the resource detail page

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#1896]
### What problem are you trying to solve?

It is possible to get real per-route metrics now, instead of the "real time" solution we have with tap. The resource detail page (deployments for example) should be updated.

### How should the problem be solved?

Add a route table to the resource detail page above the current `top` table. For the empty state, link to documentation on how to add a service profile to your service.

### Any alternatives you've considered?

1. Replace the stream with profile data. I'm concerned this will end up hiding most service's data. It would end up hiding any client data that doesn't have a profile (and any server data that doesn't have a profile). Without any data on how many folks would add profiles to their own (and other's) services, this feels like a big step backwards.

1. Show the stream when there isn't a profile, show the profile data when there is one. Feels a little bit better than the previous option. It doesn't solve the client profile issue and will end up changing the look and feel of the table (columns, updates ...).

**Comment by wmorgan** [comment]
I kinda like the option we discussed in #1868 where the live table, and the metrics table, are two tabs on one card. Not sure whether that's easy/feasible  to do with material, but conceptually they feel like the same data, so putting them in tabs feels slightly better than laying them out one after the next.
