### ISSUE TITLE
Support for intermediate certificates

### ISSUE THREAD

**Issue by maraino** [linkerd/linkerd2#1897]
## Feature Request
Support for intermediate certificates when TLS is enabled.

### What problem are you trying to solve?
Use of multiple intermediates when an alternative CA is used.

Right now if we want to add a server certificate issued by an intermediate, we need to strip the intermediate part from the server certificate bundle and add the intermediate certificate in `trust-anchors.pem` instead of the real root, this makes more difficult, not sure if possible to allow multiple intermediates.

### How should the problem be solved?
Add support for intermediate certificates here:
https://github.com/linkerd/linkerd2-proxy/blob/663eab43dcc76c79a4806175d298aef8fc01eb5f/src/transport/tls/config.rs#L264-L266

### Any alternatives you've considered?
Support for one intermediate was added doing the hacks explained above.

### How would users interact with this feature?
They would be able to use alternative CAs.

**Comment by olix0r** [comment]
The proxy now supports intermediate certificates via its new Identity service client. https://github.com/linkerd/linkerd2-proxy/blob/master/src/app/identity.rs#L219
