### ISSUE TITLE
Routes overview at the namespace level

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#1916]
### What problem are you trying to solve?

The `routes` command lets me look at per-route metrics on a service by service basis. I would like to be able to look at all the routes for all the services in a specific namespace. This would allow me to:

- Sort by success rate and get a basic tracing view.
- See all the unknowns and start to make the routes more defined.

### How should the problem be solved?

```bash
$ linkerd routes -n emojivoto 
SVC          ROUTE       SUCCESS      RPS   LATENCY_P50   LATENCY_P95   LATENCY_P99   TLS
web-svc      /api/list   100.00%   1.0rps           3ms           4ms           5ms    0%
web-svc      /api/vote    86.21%   1.0rps           3ms           4ms           4ms    0%
emoji-svc    [UNKNOWN]   100.00%   1.0rps           2ms           3ms           5ms    0%
vote-svc     [UNKNOWN]    60.00%   1.0rps           2ms           3ms           4ms    0%
web-svc      [UNKNOWN]     0.00%   0.0rps           0ms           0ms           0ms    0%
```

### Any alternatives you've considered?

- Another command maybe?

**Comment by adleong** [comment]
Fixed by #1921
