### ISSUE TITLE
tap: tapping a namespace emits no results

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#1944]
Tapping pods in a namespace works:
```
:; linkerd tap -n emojivoto pods
req id=7:1 proxy=out src=10.244.0.56:33440 dst=10.244.0.32:80 tls=no_identity :method=GET :authority=web-svc.emojivoto:80 :path=/api/list
req id=224:1 proxy=in  src=10.244.0.56:49732 dst=10.244.0.32:80 tls=disabled :method=GET :authority=web-svc.emojivoto:80 :path=/api/list
```

I'd expect tapping the namespace to have the same effect
```
:; linkerd tap ns/emojivoto     
```

However, this command just hangs indefinitely with no output.

In general, when a tap/top query yields no results, it can be confusing as to why.

**Comment by grampelberg** [comment]
Definitely working for me now, I'll close out.
