### ISSUE TITLE
Minimized Sidebar vs Resource Expansion

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#1945]
![sidebar-min-expand](https://user-images.githubusercontent.com/240738/49601016-8daa4b00-f939-11e8-9342-b1bb8bdb327a.gif)

**Comment by scottcarol** [comment]
Proposed solution: hide the arrows and status dots completely when minimized menu is shown.

**Comment by grampelberg** [comment]
@scottcarol the dots are pretty nice visually, but they'd need to be aligned better. Removing the arrows/dots is a good temporary solution.

**Comment by scottcarol** [comment]
Issue:
Currently, when the sidebar is at its default (full) width, the `SuccessRateDots` are visible underneath the arrow icons.

Image:
![current-full-sidebar](https://user-images.githubusercontent.com/2289389/53977493-fed6d700-40bd-11e9-9a7f-e8ba44856961.png)


However, when the sidebar is minimized, the dots are off-center and look jarring.

Image:
![current-minimized-sidebar](https://user-images.githubusercontent.com/2289389/53977511-09916c00-40be-11e9-8e09-28e185f77f51.png)

Solution: when sidebar is minimized, move dots so they are in line with the rest of the icons.

Image:
![desired-minimized-sidebar](https://user-images.githubusercontent.com/2289389/53977533-14e49780-40be-11e9-935f-167a320ce9ed.png)

The layout of the full-width sidebar should not change; only the positioning of the dots in the minimized sidebar.
