### ISSUE TITLE
tap does not honor service profile classification

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#1948]
tap does not expose the proxy's classification in the response event; so `top`, etc report success rate differently than `routes`

**Comment by grampelberg** [comment]
I'm still struggling a little bit to understand the implications here. @adleong @olix0r is this something that should be fixed in stable, or can we hold off and get it into the next edge? (Feels like it is okay to go into edge right now)

**Comment by olix0r** [comment]
I think that it's not ideal, but doesn't seem like a release blocker to me.

**Comment by grampelberg** [comment]
Does this require proxy work (it sounds like it does)?

**Comment by adleong** [comment]
Yes, and possibly a pretty significant refactor to the tap system in the proxy.

**Comment by grampelberg** [comment]
Well, damn. Postponed until the tap body work then!
