### ISSUE TITLE
Control plane becomes stale

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#1949]
### What is the issue?

On AKS, the control plane (both the controller pod and prometheus pods) becomes stale and no longer gets notifications of changes. This continues past the reconciliation settings and makes you think you're going nuts.

### How can it be reproduced?

It is a little bit difficult, but creating an AKS cluster and immediately installing Linkerd seems to trigger it more often than not.

### Environment

- Kubernetes Version: 1.11.5
- Cluster Environment: AKS
- Host OS: :shrug:
- Linkerd version: stable-2.0.0, edge-18.12.1

### Possible solution

Add a new check that queries the controller pod for its latest revision and then queries the control plane for its latest revision. If they don't match, recommend restarting the pods (`kubectl delete`).

**Comment by olix0r** [comment]
I'm pretty sure I've tracked this down and have a proxy fix in https://github.com/linkerd/linkerd2-proxy/pull/186.

When reproducing this issue, we had a process that simply established a kubernetes API watch and ran this process both with and without the proxy. The process without the proxy worked correctly, where the client observes the server's timeout and reissues a request. However, the process with the proxy never observed the timeout and so stopped observing updates on the watch. When I checked `netstat` in the pod -- well after the watch had expired and become stale -- the proxy's socket, forwarding the application's TCP stream to the Kubernetes API, remained open, though we're pretty sure that the server--or another intermediate proxy--had timed out the idle connection.

To resolve this, I added TCP keepalive configurations for the proxy's inbound/outbound connect/accept sides.  When adding a 1s keepalive to the proxy's inbound-accept and outbound-connect sockets, this issue can no longer be observed.

Once the proxy's change is merged, a controller change will have to followup to adopt the new proxy version and set this configuration on inject.
