### ISSUE TITLE
Controller proxy opens a very high number of UDP sockets

### ISSUE THREAD

**Issue by hawkw** [linkerd/linkerd2#1950]
### What is the issue?
While investigating #1761, I noticed that the proxy for the controller pod opens what seems like an abnormally high number of UDP sockets. The number of sockets increases over time, and causes a corresponding increase in the proxy's memory usage.

Here's the number of sockets owned by the controller proxy for a Linkerd installation with TLS, which has been running for 23 hours:

Total number of socket file descriptors owned by proxy process:
```
I have no name!@controller-7bfd7cccfb-pxsc4:/linkerd$ ls -la /proc/$(pgrep linkerd2-proxy)/fd | grep "socket" | wc -l
5964
```
Number of TCP socket fds:
```
I have no name!@controller-7bfd7cccfb-pxsc4:/linkerd$ cat  /proc/$(pgrep linkerd2-proxy)/net/tcp | wc -l
141
```
Number of UDP socket fds:
```
I have no name!@controller-7bfd7cccfb-pxsc4:/linkerd$ cat  /proc/$(pgrep linkerd2-proxy)/net/udp | wc -l
5879
```

Note that while @grampelberg's issue states that the issue is only present with TLS, but the large number of UDP sockets seems to occur regardless of whether or not TLS is enabled. However, a Linkerd installation without TLS that's been running for 22 hours only has 2475 UDP sockets. It's possible something about the TLS feature causes the proxy to open more sockets, or this behaviour is non-deterministic and the TLS installation just happens to have more UDP sockets open.

As far as I know, we only use UDP for DNS queries; the proxy should have no other reasons to open UDP sockets. I suspect that either there's a leak in `trust-dns-resolver`, or we are misusing its API in some way that causes us to leak these sockets.
 
### How can it be reproduced?

I started with the reproduction steps for #1761 provided by @grampelberg:

- Install the control plane.
- Install emojivoto with linkerd injected.
- Scale vote-bot to 100 pods

However, it's possible that scaling out the vote-bot isn't necessary to reproduce this issue.

### Environment

- Kubernetes Version: v1.10.4
- Cluster Environment: Bare metal (Packet, CNCF community test cluster)
- Host OS: Ubuntu 16.04 LTS
- Linkerd version: edge-18.11.3

### Possible solution

It's possible that DNS-related fixes in edge-18.12.1 (i.e. #1888) have already resolved this issue, so I'm going to try to reproduce again with that release.

**Comment by olix0r** [comment]
Is there a problem caused by this?

**Comment by hawkw** [comment]
@olix0r yes, it seems to correspond to a memory leak (#1761).

**Comment by olix0r** [comment]
How does this count behave over time? Does it ever hit a stable state? Are sockets _ever_ dropped from the lsof output?

**Comment by hawkw** [comment]
I started the test yesterday, and at the time, there was a fairly constant increase in the number of file descriptors:
![yesterday-fds](https://user-images.githubusercontent.com/2796466/49607528-0ebe0e00-f94b-11e8-9e98-32891d97407c.png)

Since around 2AM this morning, the controller proxy has been holding steady at 5975 file descriptors, 5879 of which are UDP sockets. Unfortunately, my Prometheus instance seems to have lost the data from prior to that point, so I'm not sure exactly when it transitioned from increasing to a steady state.
![image](https://user-images.githubusercontent.com/2796466/49607588-46c55100-f94b-11e8-94b1-23398b2e3cfc.png)

I've started a new test run with edge-18-12-1 today, and I'll be keeping an eye on the rate of increase.

**Comment by olix0r** [comment]
it would also be helpful to see the output of netstat (or ss)... which should indicate whether data is enqueued, etc.

**Comment by hawkw** [comment]
After running for about an hour, it looks like this issue no longer exists on edge-19.12.1. 

The total number of fds is much more steady (the spike is when I scaled up the `vote-bot` deployment):
![screen shot 2018-12-06 at 1 03 43 pm](https://user-images.githubusercontent.com/2796466/49611785-842fdb80-f957-11e8-90fa-bf04d8b98581.png)

I've checked in on the controller proxy periodically, and I've only ever seen it have 1 UDP socket open:
```
I have no name!@linkerd-controller-659dd6fd9d-xxxvv:/linkerd$ cat /proc/$(pgrep linkerd2-proxy)/net/udp | wc -l 
2
```
(the other line is the header with column labels)

I'm going to continue running the test for a while longer, but so far I strongly suspect the issue was fixed in yesterday's edge release. I'm guessing linkerd/linkerd2-proxy#146 is what fixed this.

**Comment by hawkw** [comment]
After running for nearly 3 hours, both the memory usage and fd count for the edge-18.12.1 controller proxy seem pretty stable:
![screen shot 2018-12-06 at 2 00 11 pm](https://user-images.githubusercontent.com/2796466/49614528-75e5bd80-f95f-11e8-98b5-90e1e0f80198.png)
![screen shot 2018-12-06 at 1 59 51 pm](https://user-images.githubusercontent.com/2796466/49614531-7aaa7180-f95f-11e8-9671-c9b0a350e5e0.png)

I think it's safe to conclude this issue no longer exists in edge-19.12.1.
