### ISSUE TITLE
Allow prometheus and grafana data storage locations to be configured

### ISSUE THREAD

**Issue by codeman9** [linkerd/linkerd2#1962]
### What problem are you trying to solve?

Our pod security policy disallows writing to the container filesystem so we need to be able to, at the very least, specify a new location to point prometheus and grafana data.

### How should the problem be solved?

A command line flag on the `linkerd install` command `--prometheus-volume-name=xyz` and `--grafana-volume-name=xyz` that will then create a `mountPath` named with the passed in name for both the prometheus and grafana containers and mounted at `/xyz`. Also, adds the `--storage.tsdb.path=xyz` argument for prometheus and the ENV `GF_PATHS_DATA=xyz` for grafana. Finally, we need to add in an `emptyDir` entry in the pod that has the same name.

### Any alternatives you've considered?

Not that I'm aware of. We could allow more than `emptyDir` volumes, but that might be another future feature request. The default installation was using the container filesystem so an `emptyDir` seems like a good first step.

### How would users interact with this feature?

Users would simply pass in the flags for this.

**Comment by codeman9** [comment]
Working on PR now.

**Comment by codeman9** [comment]
@klingerf From the research I've done, I can't think of any reason why this shouldn't be the default.
https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#storagespec here is a prometheus project that suggests emptyDir as a default and another example of using an emptyDir for prometheus and grafana is here: https://kubernetes.github.io/ingress-nginx/user-guide/monitoring/

I think that since we were initially writing to the container file system and the data is known to be more ephemeral anyway, emptyDir would be an okay default.

**Comment by klingerf** [comment]
@codeman9 Ok awesome -- thanks for the additional info. Based on those links I agree that we should be using `emptyDir` volumes for both prometheus and grafana. Would you mind updating your PR to remove the flags and hardcode the `emptyDir` config into template.go?

**Comment by codeman9** [comment]
@klingerf No problem at all. Changes coming soon.

**Comment by codeman9** [comment]
@klingerf I'm thinking that I don't want to hard code the "data" name into the template.go file, but instead have it in the install.go file next to all of the other flags/ports/names. Just removing the user configurable flags to allow changing it. What do you think?

**Comment by klingerf** [comment]
@codeman9 That works great. Thanks for checking. My main concern is that there's been a proliferation of install flags recently, so I'd prefer not to add additional flags if we can just do this in all installs.

**Comment by klingerf** [comment]
Fixed by #1971.
