### ISSUE TITLE
Show pod status more clearly

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#1967]
### What problem are you trying to solve?

I'm scaling a deployment up and down and watching `stat`. When I run `linkerd stat`, the instant the pod is created, it shows up. In my instance, this means that the pod entered a `Pending` state waiting for the cluster to autoscale. Simply looking at `kubectl get deploy` and `linkerd stat`, I couldn't figure out why my new pods were not receiving any traffic.

### How should the problem be solved?

Add another column:

```
NAME                           READY  MESHED   SUCCESS         RPS   LATENCY_P50   LATENCY_P95   LATENCY_P99   TLS
web-6446798486-bbch7               Y     1/1   100.00%   2274.5rps           8ms          25ms          37ms    0%
web-6446798486-bn7br               Y     1/1   100.00%    185.1rps          15ms          59ms          96ms    0%
web-798d887b75-d2wbv               N     1/1         -           -             -             -             -     -
web-798d887b75-nz7t4               N     1/1         -           -             -             -             -     -
web-798d887b75-tbmh7               N     1/1         -           -             -             -             -     -
```

I actually dislike this solution. It feels like it'd be possible to do something better with `meshed`, especially because I don't quite understand what `1/1` means. But, I'm having a tough time coming up with something right now.

### Any alternatives you've considered?

- Overload the meshed column.
- Show the actual status field from k8s - I actually really like this option, but it might be a little weird
- Some other type of debugging tool?

**Comment by grampelberg** [comment]
@rmars would the webui have this same problem?

**Comment by grampelberg** [comment]
Yeah! It'd be nice to get a full list together so we can slowly chip away at it.

**Comment by scottcarol** [comment]
@rmars and I just looked at this and the spinners are not coming up, so this would be even more useful.

**Comment by klingerf** [comment]
I can verify that I'm seeing the spinners in the web UI when pods are initializing:

![image](https://user-images.githubusercontent.com/9226/54382740-d1ee6b00-464d-11e9-82c7-cd6db28b6bfd.png)

**Comment by jonathanbeber** [comment]
Hello, @grampelberg 

I want to start contributing to the project and I'm interested in this task. The issue is without activity for some period now, but I think that's still relevant. 

I was taking a look in the code and for me, the best solution would be to show the kubernetes pod `status.Phase`.

Regarding your concern with the `1/1` information, I think that's interesting when running the `stat` command on a namespace, for example. It brings fast feedback regarding the number of pods running with or without the proxy.

I was thinking about something like: 

```
$ linkerd stat deploy/web
NAME                               STATUS  MESHED   SUCCESS         RPS   LATENCY_P50   LATENCY_P95   LATENCY_P99   TLS
web-6446798486-bbch7              Running     1/1   100.00%   2274.5rps           8ms          25ms          37ms    0%
web-6446798486-bn7br              Running     1/1   100.00%    185.1rps          15ms          59ms          96ms    0%
web-798d887b75-d2wbv    ContainerCreating     1/1         -           -             -             -             -     -
web-798d887b75-nz7t4    ContainerCreating     1/1         -           -             -             -             -     -
web-798d887b75-tbmh7    ContainerCreating     1/1         -           -             -             -             -     -
``` 

This column would be omitted (`-`) when the command is on some specific resources, like a namespace or an authority.

Please, let me know what you think. I'd be happy to work on it.

**Comment by grampelberg** [comment]
@jonathanbeber sounds great to me! I'm not sure you'll be able to use pod status for the parent resource types though. How would it work when there's more than one pod in a deployment?

**Comment by jonathanbeber** [comment]
@grampelberg yes, definitely for parent resources we can show the status but that would not be relevant, the same that I mentioned for namespaces and authorities 😞 
For these cases, I'm thinking about changing the meshed logic and do not count pods that are with a status different of running. I think that would be relevant and aligns with what you said:
>  It feels like it'd be possible to do something better with meshed


If you're okay with that I'll start working on a PR. Thanks for your fast response

**Comment by grampelberg** [comment]
Hmm, `meshed` tells me something different I think. Converting the `Status` column to `Ready` column that has counts would fix the problem though.

Honestly, this is almost exclusively a pod concern as it feels like deployments should have a different treatment entirely. So maybe the column only shows `Status` when it is pods? I'm not a huge fan of having different columns for different types but it matches `kubectl get` 1:1.

**Comment by jonathanbeber** [comment]
I'll work on set `Status` for pods. Thanks for your opinion and review here @grampelberg
