### ISSUE TITLE
linkerd CLI snippets in web UI should reflect the namespace where linkerd is running

### ISSUE THREAD

**Issue by klingerf** [linkerd/linkerd2#1979]
When I'm running linkerd in a non-default namespace, I can't cut and paste the CLI snippets from the web UI, since they assume that linkerd is running in the default "linkerd" namespace. For instance, when I run linkerd in the "kltest" namespace, I see this in the web UI:

![image](https://user-images.githubusercontent.com/9226/49910135-6b7f6400-fe36-11e8-9178-e5627f96a885.png)

But that command won't work unless it also includes a `--linkerd-namespace kltest` flag.

**Comment by rmars** [comment]
fixed by #1985
