### ISSUE TITLE
Add support for Consul

### ISSUE THREAD

**Issue by mtyrrell** [linkerd/linkerd2#1984]
## Feature Request

Add support for Consul via a Control Plane. This was also discussed here: https://github.com/linkerd/linkerd2/issues/1680

### What problem are you trying to solve?

Replace Linkerd 1.0 / Consul Service Mesh with Linkerd 2.0

### How should the problem be solved?

To be determined. Do we just implement a Control Plane microservice with Consul awareness?

What do you want to happen? Add any considered drawbacks.

Can folks interested in collaborating on adding Consul support for Linkerd 2 please reach out via this issue.

No drawbacks @homeaway because we are not using Kubernetes.

### Any alternatives you've considered?

Is there another way to solve this problem that isn't as good a solution?

Not as far as I know

### How would users interact with this feature?

TBD

If you can, explain how users will be able to use this. Maybe some sample CLI
output?

**Comment by wmorgan** [comment]
Thanks for filing this, @mtyrrell!

**Comment by dadjeibaah** [comment]
Hey @mtyrrell, this is an interesting issue. I know Consul has its own control plane called Connect. Is the thinking that Linkerd2's proxy could just implement whatever API Consul Connect exposes? Or are you thinking an entirely new control plane needs to be built?

**Comment by mtyrrell** [comment]
@dadjeibaah, AFAIK the Consul Connect support for Envoy was implemented at the Consul end as an XDS gRPC endpoint. It would be worthwhile calling out the trade-offs between trying to tightly couple the two together via the Connect feature of Consul or more loosely like Namerd does in Linkerd 1.x. At HomeAway we use Linkerd 1 so that is the strategy that fits best with our current service mesh architecture. Providing a standalone control plane offers the most flexibility about how you choose to integrate Consul but might miss out on the benefits of the Connect offering e.g. mTLS configuration etc. It would be great to support per Host and as-a-service-sidecar options.

**Comment by perrymanuk** [comment]
I would also love to see support for something like this

**Comment by grampelberg** [comment]
As of today, we are not planning on supporting any other schedulers. We'd love to work with someone who's interested in implementing a new control plane for their scheduler. Anyone interested in contributing a new control plane for their scheduler of choice, please open up a new issue so we can start working with you on it.
