### ISSUE TITLE
Linkerd2 TLS Test Application

### ISSUE THREAD

**Issue by btotharye** [linkerd/linkerd2#1991]
Issue Type:
- [X] Feature request

**What happened**:
I think it would be a nice to have to have test services for Linkerd 2 that we could run after setting up the optional TLS to ensure pod to pod communication for services is actually encrypted.  Something similar to the Linkerd 1 examples.

I wouldn't mind helping contribute back to this documentation and even creating the manifest files just looking for some guidance if we have a good option to test this.  I know there were these files for the Linkerd 1 version:

https://raw.githubusercontent.com/linkerd/linkerd-examples/master/k8s-daemonset/k8s/node-name-test.yml

https://raw.githubusercontent.com/linkerd/linkerd-examples/master/k8s-daemonset/k8s/hello-world.yml

Let me know how I can help on this or if we have existing services somewhere we could use to test the 2 applications are talking over encrypted channels.

**Comment by siggy** [comment]
Thanks for writing this up @btotharye ! We're planning to create a test app to validate TLS and other configs and protocols. We're tracking that work in #2079. I'm going to close this ticket in favor of that one. If there are requirements that you think are not covered by #2079, please comment on there, thanks!
