### ISSUE TITLE
Add CustomResourceValidation for ServiceProfiles

### ISSUE THREAD

**Issue by adleong** [linkerd/linkerd2#1992]
CustomResourceValidation is a beta feature in k8s 1.13 that allows you to specify a schema for your CRD: https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#validation

This will help protect against invalid service profiles, such as when fields are misspelled or required fields are absent.

**Comment by grampelberg** [comment]
@adleong any idea how hard this is? (Going through and flagging issues that are good first contributions)

**Comment by adleong** [comment]
The docs (linked above) make it look easy enough.  I'm not sure about backwards compatibility, though.  i.e. will kubernetes versions prior to 1.13 choke on the validation schema?
