### ISSUE TITLE
Expire web dashboard bundle

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#1996]
### What problem are you trying to solve?

When updating to a new version of Linkerd, the dashboard does not expire the old web bundle. This forces me to do a hard refresh on the page to get it working (lots of errors)

### How should the problem be solved?

Update webpack to add a hash for the bundle, so that when there's a new bundle the browser pulls it down.

### Any alternatives you've considered?

It'd be possible to set expiration headers in the web service, just feels more fragile than letting webpack do its thing.

**Comment by benjdlambert** [comment]
Alternatively you could just add the version number to the URL for all the static assets related to the current release. `/static/bundle.js` and `/static/logo.png` become /static/2.0.0/bundle.js` and `/static/2.0.0/logo.png`. This has the added benefit that you expire everything on a new release, not just JavaScript.
