### ISSUE TITLE
Fetch `inject` configuration from control plane

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#1999]
### What problem are you trying to solve?

As the configuration for `install` continues to grow, it is becoming difficult to know what flags to set in `inject` to match the control plane features. As an example, see #1887 and #1891 .

### How should the problem be solved?

Update the `inject` command to pull default configuration from the control plane before actually doing the inject.

### Any alternatives you've considered?

- A local configuration file (see #1892 and #1604). This will work for the single situation, but not for multiple users of the same control plane.

**Comment by klingerf** [comment]
@olix0r is working on this in  #2434, but the implementation will change once the config endpoint has been added (#2455). Assigning to him.

**Comment by alpeb** [comment]
Closed via #2535
