### ISSUE TITLE
Use tokio-trace in the proxy

### ISSUE THREAD

**Issue by hawkw** [linkerd/linkerd2#2004]
## Feature Request

We should replace the proxy's custom logging code with `tokio-trace`. The tokio-trace-based implementation should generate log output as close to the proxy's current logs as possible.

**Comment by hawkw** [comment]
Right now, I'm taking advantage of the fact that `tokio-trace`'s macros are essentially a superset of the `log` crate's macros to allow drop-in replacement of most of the log lines in the proxy. In the future, though, there's the option of doing some follow-up work to make these log lines more structured, using `tokio-trace`'s `fields` API.

Eventually, that added structure might unlock new ways to report/consume this data beyond simple logging to stdout.

**Comment by olix0r** [comment]
TODO
* [ ] Open issue to identify log format to be adopted (with current state)
* [ ] Benchmarks for tokio-trace with h2
* [ ] Write a subscriber to implement the above
* [ ] Replace existing logging context instrumentation with tokio-trace
* [ ] Make call on Batch API? @carllerche 
* [ ] Performance proxy comparison

**Comment by hawkw** [comment]
This is currently in flight. Initial pass almost done, actually
