### ISSUE TITLE
proxy: proxy-log-level admin endpoint

### ISSUE THREAD

**Issue by hawkw** [linkerd/linkerd2#2005]
### What problem are you trying to solve?

The linkerd proxy's log level can be configured by annotation; but this means that it's not possible to update the log level on a running process. In order to facilitate manual debugging of a running system, there should be a way to update the log level of an individual pod at runtime. It must not be possible for unauthorized users to alter the log level of a proxy, as this can have serious performance and security implications.

### How should the problem be solved?

The proxy's admin service should have an endpoint `/proxy-log-level` (to match the annotation that controls this configuration).

This endpoint should respond to `GET` requests with the current log level string.

The endpoint should accept `PUT` requests to update the log level. If the provided log string does not reflect a valid log level spec, a 400 response must be returned. When the log level is successfully updated, a 201 is returned.

The endpoint must only accept requests on the loopback interface and should fail with a 403 when requests are received from non-loopback addresses.

Then, as a user, I can change this log level with a command like:

```
:; kubectl exec -n $ns $pod -- curl -X PUT --data 'my=new,log=spec' localhost:4191/proxy-log-level
```

**Comment by grampelberg** [comment]
I really like the ConfigMap solution, as it makes everything auditable. That could be managed similarly through the API and metrics exports though.

As an issue that is slightly intertwined with this one, it would be nice to introspect what log levels are available. I would like to fetch what's available and then set from that list.

**Comment by olix0r** [comment]
Furthermore, we'll probably want to be able provide finer-grained controls than the typical rust log format supports.

**Comment by hawkw** [comment]
@olix0r 
> We should do some thinking about the use cases here. This is sufficient for you or I to debug a single instance, but is a total mess at scale.
> ...
> My sense is that we probably shouldn't focus on this issue -- dynamic configuration -- until linkerd's configuration story is generally more mature.

I think in the longer term, the solutions I proposed above aren't ideal --- at the very least, we'll want to implement better UX on top of them. But, I feel like there's sufficient value in having a feature like this now, even if it's not perfect yet; we can always loop back and replace a simple interim solution with something else as the dynamic configuration story evolves?

> Furthermore, we'll probably want to be able provide finer-grained controls than the typical rust log format supports.

For sure. I think this is something `tokio-trace` will make much easier for us --- we can attach separate subscribers with different filtering configurations to individual executors, tasks, etc.

@grampelberg 
> As an issue that is slightly intertwined with this one, it would be nice to introspect what log levels are available. I would like to fetch what's available and then set from that list.

This would be nice to have. However, on the other hand, the filtering can be configured with a _lot_ of granularity --- we can set a separate log level for each Rust source code file in the proxy, and in any library it depends on. So, it may be a bit of an information overload to present users with a _complete_ list of scopes that can have a log level. Maybe it's worth picking out a list of fairly common ones & then noting that it's technically possible to filter individual source code files? This may also relate to @olix0r's https://github.com/linkerd/linkerd2/issues/2005#issuecomment-448807041.

**Comment by grampelberg** [comment]
@hawkw I'd love to get a *complete* list from the server and filter on the client side (because you're 100% right, most will want a couple options).

**Comment by olix0r** [comment]
my concern is that this is an enormous footgun if it's not easily auditable. running this on a pod can have serious performance impacts, and an operator would have very little insight into how/when/why the change happened.

generally, since we haven't actually gotten our hands dirty with the new logging framework in the proxy, it's impractical to start designing this feature. or, at least, i don't have much helpful guidance on this yet.

**Comment by hawkw** [comment]
> generally, since we haven't actually gotten our hands dirty with the new logging framework in the proxy, it's impractical to start designing this feature.

That's totally fair. I wasn't planning on actually starting to work on this until after we've gotten to prove out using `tokio-trace` in the proxy, I wanted to open the ticket just to track potential follow-up work.

**Comment by hawkw** [comment]
The broken CI builds here are due to the way the log level handle is threaded into the app constructor not playing nice with the test support code. I'd overlooked that earlier as I was testing the change manually.

Will get it fixed shortly.
