### ISSUE TITLE
Wire up stats and dashboards for Jobs

### ISSUE THREAD

**Issue by klingerf** [linkerd/linkerd2#2007]
Similar to #1983 and #2006, we should update the CLI, web UI, and grafana dashboards to start displaying stats for jobs. The `k8s_job` label already exists in Prometheus, so this should not require any proxy changes.

**Comment by Pothulapati** [comment]
I would like to take this issue :)

**Comment by dadjeibaah** [comment]
Sure thing! My guess is that this would look very similar to this PR #2086. Let us know if you have any other questions!

**Comment by klingerf** [comment]
@Pothulapati Great! As @dadjeibaah said, this should be very similar to what we did for DaemonSets in #2086 and StatefulSets in #2234. The only additional thing to note is that all Prometheus metrics include a `job` label by default, but that label does not represent a Kubernetes Job. We've configured Prometheus to add a `k8s_job` label when collecting stats from Kubernetes Jobs, and that's the label that you should use when querying Prometheus.
