### ISSUE TITLE
Garafana broken css

### ISSUE THREAD

**Issue by duythien** [linkerd/linkerd2#2010]
## Bug Report
When I try to expose linkerd-web and linkerd-grafana to NodePort, it's work fine for  linkerd-web but it is broken for grafana

### What is the issue?
Garafana broken css
Loading failed for the <script> with source “http://192.168.10.207:31604/api/v1/namespaces/linkerd/services/linkerd-grafana:http/proxy/public/build/manifest.4f5454f867a0cc2fe8dd.js”

### How can it be reproduced?

```
kubectl -n linkerd edit service linkerd-garafana
kubectl -n linkerd edit service linkerd-web
```
Then change cluster to nodeport, verify
```
$ kubectl -n linkerd get svc
NAME                     TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                         AGE
linkerd-controller-api   ClusterIP   10.102.178.47    <none>        8085/TCP                        26h
linkerd-grafana          NodePort    10.98.168.214    <none>        3000:31604/TCP                  26h
linkerd-prometheus       ClusterIP   10.97.248.62     <none>        9090/TCP                        26h
linkerd-proxy-api        NodePort    10.102.215.145   <none>        8086:31777/TCP                  26h
linkerd-web              NodePort    10.104.16.198    <none>        8084:31295/TCP,9994:32710/TCP   26h

````

### Logs, error output, etc
![](https://screenshotscdn.firefoxusercontent.com/images/9c2e7f50-8268-4941-91aa-1a8d2e4c6318.png)

Goto this url http://192.168.10.207:31295/namespaces/linkerd/deployments/linkerd-web then scroll bottom then click to seen graph by this http://192.168.10.207:31295/dashboard/db/linkerd-deployment?var-namespace=linkerd&var-deployment=linkerd-prometheus the result is `404 page not found`

#### `linkerd check` output

```text
$ linkerd check
kubernetes-api: can initialize the client..................................[ok]
kubernetes-api: can query the Kubernetes API...............................[ok]
kubernetes-api: is running the minimum Kubernetes API version..............[ok]
linkerd-api: control plane namespace exists................................[ok]
linkerd-api: control plane pods are ready..................................[ok]
linkerd-api: can initialize the client.....................................[ok]
linkerd-api: can query the control plane API...............................[ok]
linkerd-api[kubernetes]: control plane can talk to Kubernetes..............[ok]
linkerd-api[prometheus]: control plane can talk to Prometheus..............[ok]
linkerd-api: no invalid service profiles...................................[ok]
linkerd-version: can determine the latest version..........................[ok]
linkerd-version: cli is up-to-date.........................................[ok]
linkerd-version: control plane is up-to-date...............................[ok]

Status check results are [ok]

```

### Environment

- Kubernetes Version: v1.12.1
- Cluster Environment: Kubeadm
- Host OS: Ubuntun 16.04
- Linkerd version: stable-2.1.0

### Additional context

My expected. I want to share dashboard for other user via nginx proxy

**Comment by grampelberg** [comment]
Grafana requires a `ROOT_URL` because `linkerd dashboard` is served via `kubectl proxy`. You can patch the deployment to set your `ROOT_URL` correctly to get around it for now. 

The tracking issues to make this better in the long term are #2003, #1692 and #1696.

**Comment by duythien** [comment]
@grampelberg Where is put ROOT_URL? in deployment  linkerd-grafana-59b57cf484-6h9zt  ? or some where ?
![screenshot_2018-12-28 urbn8 - pods - kubernetes dashboard](https://user-images.githubusercontent.com/1762691/50506182-46cbf300-0aaa-11e9-9e98-42a7a3bc0edc.png)

**Comment by switchboardOp** [comment]
looks like the `root_url` is set in the `linkerd-grafana-config` configMap, @duythien.
It's in the grafana.ini key

Not sure if that's the only spot...

```
[☸ mnd-k8s:linkerd] ~|⇒ kubectl describe cm linkerd-grafana-config
Name:         linkerd-grafana-config
Namespace:    linkerd
Labels:       linkerd.io/control-plane-component=grafana
Annotations:  kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"v1","data":{"dashboards.yaml":"apiVersion: 1\nproviders:\n- name: 'default'\n  orgId: 1\n  folder: ''\n  type: file\n  disableDeletion: ...
              linkerd.io/created-by=linkerd/cli stable-2.1.0

Data
====
dashboards.yaml:
----
apiVersion: 1
providers:
- name: 'default'
  orgId: 1
  folder: ''
  type: file
  disableDeletion: true
  editable: true
  options:
    path: /var/lib/grafana/dashboards
    homeDashboardId: linkerd-top-line
datasources.yaml:
----
apiVersion: 1
datasources:
- name: prometheus
  type: prometheus
  access: proxy
  orgId: 1
  url: http://linkerd-prometheus.linkerd.svc.cluster.local:9090
  isDefault: true
  jsonData:
    timeInterval: "5s"
  version: 1
  editable: true
grafana.ini:
----
instance_name = linkerd-grafana

[server]
root_url = %(protocol)s://%(domain)s:/api/v1/namespaces/linkerd/services/linkerd-grafana:http/proxy/

[auth]
disable_login_form = true

[auth.anonymous]
enabled = true
org_role = Editor

[auth.basic]
enabled = false

[analytics]
check_for_updates = false
```

**Comment by grampelberg** [comment]
You don't actually need to modify the configmap, just add `ROOT_URL` to the env (which you can apply as a patch without actually modifying any of the original YAML).

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: linkerd-grafana
spec:
  template:
    spec:
      containers:
      - name: grafana
        env:
        - name: GF_SERVER_ROOT_URL
          value: /
```

```bash
kubectl -n linkerd patch deployment linkerd-grafana -p "$(cat patch.yml)"
```

Note: this will all be moot once @klingerf lands #2039.

**Comment by klingerf** [comment]
As of the [edge-19.1.1 release](https://github.com/linkerd/linkerd2/releases/tag/edge-19.1.1), the web service is setup to proxy requests to grafana, and that will fix the broken CSS issue. You should no longer need to modify the `linkerd-garafana` service to be of type `NodePort`, and you can instead access grafana by navigating to the "/grafana" route of the `linkerd-web` service.
