### ISSUE TITLE
Add ability to see breakdown of requests by fate

### ISSUE THREAD

**Issue by adleong** [linkerd/linkerd2#2016]
### What problem are you trying to solve?

Setting up retries can be confusing and it can be difficult to determine if retries have been configured successfully.  Furthermore, it can be very difficult to know *WHY* retries are or are not happening.  Showing effective and actual RPS can show whether retries are happening, but do not explain why.  For example, retries may be skipped for a variety of reasons including:
* route not configured as retryable
* timeout exceeded
* budget exhausted
* message not bufferable (too large)

### How should the problem be solved?

All requests that the Linkerd proxy sends fall into exactly one of these categories:
* In progress (request sent, response not yet complete)
* Success (no retries necessary)
* Success after retry (initial response was failure, but succeeded after some number of retires)
* Failure: not retryable (failure, route is not retryable)
* Failure: timeout exceeded
* Failure: retry skipped: budget exceeded (failure, could not retry due to retry budget)
* Failure: retry skipped: message not bufferable (request or response too large, could not be buffered)

Add a `linkerd request-breakdown` (PLEASE help me come up with a better name) which displays a breakdown of how many requests fall into each of these categories:

```
$ linkerd request-breakdown svc/books

ROUTE                       SERVICE   IN PROGRESS   SUCCESS                   FAILURE
                                                    FIRST TRY   AFTER RETRY   NOT RETRYABLE   TIMEOUT   NO BUDGET   TOO LARGE
DELETE /books/{id}.json     books               1          41             0               0         0           0           0
GET /books.json             books               0          23            19               0         0           7           0
GET /books/{id}.json        books               1          25            20               0         0           6           0
POST /books.json            books               2          15             0              17         0           0           0
PUT /books/{id}.json        books               0          21             0              19         0           0           0
[UNKNOWN]                   books               0          23             0               0         0           0           0
```

To be able to distinguish between success (first try) and success (after retry), we would probably need to add a new prometheus label that indicates if an actual request is an original request or a retry.

**Comment by olix0r** [comment]
I'm not sure about the solution being adding labels to existing metrics. there are some proxy impl details that will influence how the solution shakes out

**Comment by grampelberg** [comment]
This feels valuable, but does it need to be added to `routes`? I've been hoping that `routes` and `stat` have identical look/feel (just with routes).

A `-o wide` would match the `kubectl` UX. Honestly, the more I see examples of the impacts of retries on the rest of the UI, I keep wondering whether all the metrics related to retries should be separated out into their own command.

**Comment by adleong** [comment]
This is route level data, but it could certainly go in a separate command.

**Comment by grampelberg** [comment]
@adleong we can't get this data on the stat level? I just assumed that it was a different view.

**Comment by adleong** [comment]
I guess it depends on what you mean.  Retries happen at the route layer.  But we could roll up the data from resources, just like we do for the `routes` command.

**Comment by grampelberg** [comment]
Ahhh, I get it. As a user, I would like to see this data at the stat level (pod, deployment, authority) as well as at the route level. How would that work with `--from` and `--to`?

**Comment by adleong** [comment]
There is a subtle but important difference between this and stat/routes.  Stat and routes both default to showing inbound data i.e. what is the success rate of requests the target receives.  This behavior is flipped to show outbound data if the `--to` flag is used.

These retry stats, on the other hand, ONLY make sense for outbound data (there are no inbound retries).  So defaulting to inbound like stat/routes wouldn't make sense.  So we would need to somehow make it clear that this command works differently and always shows data about requests that the target resource is sending (as opposed to receiving).
