### ISSUE TITLE
initContainer failures do not block the pod

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#2056]
### What is the issue?

I have something broken on my cluster, the initContainer has the following output:

```
2019/01/09 23:06:58 Tracing this script execution as [1547075218]
2019/01/09 23:06:58 State of iptables rules before run:
2019/01/09 23:06:58 > iptables -t nat -vnL
2019/01/09 23:06:58 < iptables v1.4.21: can't initialize iptables table `nat': Permission denied (you must be root)
Perhaps iptables or your kernel needs to be upgraded.

2019/01/09 23:06:58 Aborting firewall configuration
```

I would expect this error to crash the initContainer and the pod go into crash backoff.

**Comment by klingerf** [comment]
Ugh, I've run into this before too and it's a real pain to track down. At a minimum, we should check the proxy-init container statuses as part of `linkerd check --proxy`.
