### ISSUE TITLE
Remove support for accessing web UI through service proxy

### ISSUE THREAD

**Issue by klingerf** [linkerd/linkerd2#2057]
Once #2052 merges, `linkerd dashboard` will be using port-forwarding instead of the service proxy for accessing the web UI. This means that we will no longer need to support loading the site behind the long service proxy URLs (e.g. `/api/v1/namespaces/linkerd/services/linkerd-web:http/proxy/`). There's a bunch of code in the `web/` directory to detect when the UI is being served via the service proxy, and we should be able to remove all of that. Relates to https://github.com/linkerd/linkerd2/pull/2052#issuecomment-452525807.

**Comment by rmars** [comment]
This would entail removing `pathPrefix` from the `ApiHelpers` code, and removing calls to `prefixPath` and usage of `PrefixedLink` in the dashboard code
