### ISSUE TITLE
Flaky proxy test `profiles::http2_failures_dont_leak_connection_window`

### ISSUE THREAD

**Issue by hawkw** [linkerd/linkerd2#2062]
### What is the issue?

The proxy test `profiles::http2_failures_dont_leak_connection_window` appears to fail spuriously on CI. I haven't been able to make it fail locally. After restarting the CI build, the test passes.

### Possible solution

Presumably, this test should be marked as flaky.

@seanmonstar, is there a better solution that might allow us to continue running this test on CI?

**Comment by seanmonstar** [comment]
Should have been fixed with https://github.com/linkerd/linkerd2-proxy/pull/176
