### ISSUE TITLE
Validate that a service exists before creating profile

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#2068]
### What problem are you trying to solve?

I foolishly cut and pasted the commands to create profiles for the booksapp. I was then confused as to why nothing was working. In retrospect, this was because I forgot to specify the namespace.

```bash
curl https://run.linkerd.io/booksapp/webapp.swagger | linkerd profile --open-api - webapp | kubectl apply -f -
```

### How should the problem be solved?

When a user runs `linkerd profile`, it should verify that the service exists (or not) and warn that there was not a service found.

**Comment by olix0r** [comment]
Service profiles can exist for names that are not kubernetes services, so this logic would have to be aware of the kubernetes service name structure.

**Comment by klingerf** [comment]
This doesn't exactly fix your problem, but `linkerd check` validates service profiles, and it will warn you if the corresponding service for a service profile does not exist:

```
kl ~ $ linkerd check
kubernetes-api: can initialize the client..................................[ok]
...
linkerd-api: no invalid service profiles...................................[warning] -- ServiceProfile "webapp.default.svc.cluster.local" has unknown service: services "webapp" not found
linkerd-version: can determine the latest version..........................[ok]
linkerd-version: cli is up-to-date.........................................[ok]
linkerd-version: control plane is up-to-date...............................[ok]

Status check results are [ok]
```

**Comment by grampelberg** [comment]
That's a great point, definitely needs to get added to the docs for service profiles =)

**Comment by adleong** [comment]
Depends on #2075 and #2095

**Comment by adleong** [comment]
One way to address this is to add a validation that checks: If the service profile name is of the form `<x>.<y>.svc.cluster.local` then `<x>` must be a service in namespace `<y>`.  (names of other forms are arbitrary DNS names and do not need to correspond to service objects)  This can be tackled as part of #2075.  @grampelberg, does that seem reasonable?
