### ISSUE TITLE
add support for configuring service profile retries via openapi spec

### ISSUE THREAD

**Issue by jon-walton** [linkerd/linkerd2#2073]
## Feature Request

with https://github.com/linkerd/linkerd2/pull/2038 being a thing. It'll be nice is we can use openapi extensions to define a retry policy per route.

### What problem are you trying to solve?

We do not manually write our openapi spec. It's generated automatically by middleware within our project. Therefore generating a retry policy would be tedious with us having to manually write a separate yaml file with the retry policies and patch it in to the service profile.

### How should the problem be solved?

It's possible to define extensions (https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#specificationExtensions) within our openapi / swagger middleware. These will appear on the operation object (https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#operationObject) in the swagger.json. linkerd can look for the extension name (maybe `x-linkerd-retry`, or something more suitable) to populate the retry policy

### Any alternatives you've considered?

Patching the yaml before it gets to kubectl

### How would users interact with this feature?

add an extension `x-linkerd-retry: 2` to either the `Path Item Object` or `Operation Object`. linkerd will pick this up while processing the openapi spec.

**Comment by vaibhavk** [comment]
I would like to work on this issue

**Comment by wmorgan** [comment]
@vaibhavk sounds good. We need a final call on the `x-linkerd-retry` question first, from @grampelberg or someone else, but feel free to assign the issue to yourself and get started in the meantime!

**Comment by grampelberg** [comment]
+1 from me for `x-linkerd-retry`.

**Comment by wmorgan** [comment]
@grampelberg any thoughts on `Path Item` vs `Operation` ?

**Comment by grampelberg** [comment]
@wmorgan I *think* `Operation` makes more sense? @jon-walton from reading the docs, it appears that `Path` is a higher level concept than `Operation`. Would you happen to know what the tradeoffs are between one or the other?

**Comment by jon-walton** [comment]
I agree, operation makes more sense in the real world. It'll allow you to have a retry on `GET /bla` but disable it for `POST /bla`

**Comment by grampelberg** [comment]
Ahha, that's exactly the context I was looking for. `Operation` it is!

**Comment by gane5hvarma** [comment]
working on this issue :)

**Comment by kohsheen1234** [comment]
Hey @grampelberg I'd like to take this up

**Comment by grampelberg** [comment]
@kohsheen1234 go for it!
