### ISSUE TITLE
move away from Go HTML templates in web dashboard

### ISSUE THREAD

**Issue by siggy** [linkerd/linkerd2#2074]
The root HTML of the Linkerd dashboard comes from a Go Template, with injected build and runtime info: https://github.com/linkerd/linkerd2/blob/master/web/templates/app.tmpl.html#L1-L12

Once we're hashing the JS bundle via #2058, this templating motivates some complexity around our JS loading. Specifically, the Go template references a pre-built `index_bundle.js`, which itself references a hashed JS bundle, something like `main.17249b45c7d23228c299.js`. This is all done via `htmlWebpackPlugin`:
https://github.com/linkerd/linkerd2/pull/2058#discussion_r247221165

To avoid this, we should consider using `htmlWebpackPlugin` as intended, to generate a root HTML file that references the hashed bundle directly, replacing `app.tmpl.html`. The Runtime (and possibly build time) information, could be moved out to a JSON endpoint served by the Go process.

A couple other less desirable options:
1) Modify the Go template to reference the hashed JS bundle directly. This would require modifying the Go template file at JS build time.
2) Pass the hashed JS bundle into the Go web process as a command line flag. This means that to run the `gcr.io/linkerd-io/web` Docker image, composed of Go and JS code, would require passing a filename that already exists in its own filesystem into a Go process, to then be served back to the jS code.

**Comment by grampelberg** [comment]
This might have some impact on #2001, as it is desirable to include file based assets in the build. @olix0r mentioned https://github.com/gobuffalo/packr to do that.

**Comment by kleimkuhler** [comment]
@admc This issue was reopened for a reason that turned out to be pretty separate from what is outlined here. @siggy and I had some good discussion on it before realizing the root error (fixed in #3891), but I didn't end up changing anything about the template.

I don't necessarily want to say #3891 closes *this* issue, but it will fix the `p0` priority that it has been assigned.
