### ISSUE TITLE
Read service profiles from client and server namespaces

### ISSUE THREAD

**Issue by adleong** [linkerd/linkerd2#2077]
Currently, the Linkerd controller looks for service profiles in the Linkerd controller namespace.  This can be un-intuitive (one might expect that service profiles should exist in the same namespace as the service).  More importantly, users may not have permissions to create objects in the control plane namespace, but still would like to create a service profile for a service they own or a service they call.

Instead, the controller should look for service profiles in:

1. the namespace of the pod making the request (the client)

and if the service profile is not found there, the controller should fall back to looking for it in:

2. the namespace of the service being called (the server)

This allows service owners to create a service profile for their service in their service's namespace that will be used by clients in any namespace which call that service.  However, it also allows clients to override this behavior by creating their own service profile for the service they are calling in the client namespace.  Furthermore, clients which are calling external domains can create service profiles for those external domains in their own namespace.

**Comment by grampelberg** [comment]
From my perspective, I want the profiles to be wherever I expect them to be (which will most commonly be next to my services). I also don't want any kind of fallback logic to define what happens when there are two profiles of the same name.

This leads to there needing to be something that verifies uniqueness of profiles for users when it is created, when they'd like to verify that it is working correctly and as a set of debugging utilities to understand what is going on.

**Comment by olix0r** [comment]
Given namespaces `nsa` and `nsb`, can a service profile for `name.nsa.svc.cluster.local` be stored in `nsb`? What does that mean if someone in `nsa` tries to create the service profile after it's been created in `nsb`?

What about profiles for external services not owned by any namespace? If a profile is created for `api.github.com` is created in `nsa`, should it start impacting services in `nsb` that call this name? This would be surprising and basically broken if users in `nsb` cannot override the behavior.

I feel strongly that we should just try to discover service profiles across all namespaces. We need an ownership and access control model that is predictable.

I think there's a strong argument that services in `nsa` should NEVER discover profiles from `nsb`.  Perhaps we want a way to create a profile in `nsa` that is a "symbolic link" to a profile in another namespace; but it would be severely broken if one service owner's changes start impacting another in an unintended way.

**Comment by adleong** [comment]
I'm struggling a lot with this because there are a number of different use-cases that are difficult to satisfy simultaneously:

* I, a service owner in `nsa`, want to set policy on my service's calls to a service in `nsb` but I cannot write to resources outside of `nsa`
* I, a service owner in `nsa`, want to set policy on my services' calls to an external API but I cannot write to resources outside of `nsa`
* I, a service owner in `nsb`, want to set policy on how other people call my service, but I cannot write to resources outside of `nsb`

To satisfy all of these use cases, the service profile must be specifiable in `nsa` *and* in `nsb`.  

Therefore, we must either decide that one of the above use-cases is a non-goal, or we need to create some kind of precedence rule where service profiles are first looked up in the callers namespace (`nsa`) with fallback to looking up the service profile in the callee's namespace (`nsb`).

**Comment by olix0r** [comment]
@grampelberg My main concern with implicitly loading ServiceProfiles, without requiring the client to opt-in, is that changes in `nsb` can cause clients to buffer/retry/etc in ways that may conflict with resource reservations on the clientside. I see the argument in favor of implicitly discovering profiles for services in other namespaces, though. I think the base requirement is that client-side users have the tools necessary to opt-in/out of profiles; and to be able to discover the changes that have occurred to these profiles.

**Comment by grampelberg** [comment]
@adleong I think that my biggest struggle is around trying to unify the client and server sides of this. Do service profiles change the server side behavior or only the client side?

**Comment by adleong** [comment]
For now, just client-side behavior, but that could change as we add more things to the service profile.  That said, this client-side behavior should, in many cases, be dictated by the owner of the server.  i.e. the server owner is the authority on the semantics of the routes and can best say which routes are retryable and what reasonable timeouts for those routes are.

**Comment by olix0r** [comment]
@adleong 

> Therefore, we must either decide that one of the above use-cases is a non-goal, or we need to create some kind of precedence rule where service profiles are first looked up in the callers namespace (nsa) with fallback to looking up the service profile in the callee's namespace (nsb).

Or we require clients to opt-in by effectively establishing a symlink from `nsa` to the profile stored in `nsb`

**Comment by adleong** [comment]
>  Or we require clients to opt-in by, effectively, establishing a symlink from nsa to the profile stored in nsb

Fair enough.  I think I prefer the ergonomics of implicitly using the service profile from `nsb` and allowing clients in `nsa` to explicitly opt-out by creating a service profile in `nsa`.
