### ISSUE TITLE
introduce test app for various protocols and topologies

### ISSUE THREAD

**Issue by siggy** [linkerd/linkerd2#2079]
Issues like #2013 highlight there are certain protocols, APIs, and topologies that could benefit from deeper testing. Build a test app that more easily surfaces issues around:
- client-side streaming gRPC
- server-side streaming gRPC
- bidirectional streaming gRPC
- unary gRPC
- redis
- mySQL
- websockets

Once built, this app should be testable with Linkerd, with and without TLS enabled.

For reference, existing sample and test apps:
- https://github.com/linkerd/linkerd-examples
- https://github.com/BuoyantIO/strest-grpc
- https://github.com/BuoyantIO/emojivoto
- https://github.com/BuoyantIO/slow_cooker/
- https://github.com/BuoyantIO/bb

**Comment by grampelberg** [comment]
I'd love to add MySQL, Casandra and Elasticsearch to this list.
