### ISSUE TITLE
Failing HTTP requests on missing control plane

### ISSUE THREAD

**Issue by svenwltr** [linkerd/linkerd2#2088]
### What is the issue?

When the Linkerd control plane is down, new Pods with the proxy sidecar fail to do plain HTTP requests.

### How can it be reproduced?

Setup fresh minikube; YAML files are available in [Gist](https://gist.github.com/svenwltr/2ad391a7d5f14756d127cf65c17610c3):

```sh
$ minikube start
```

Start plain HTTP server (without sidecar):

```sh
$ kubectl apply -f nginx.yaml
```

Start Pod for doing HTTP requests:

```sh
$ linkerd inject --linkerd-version edge-19.1.1 curl.yaml | kubectl apply -f -
```

### Logs, error output, etc

Plain HTTP requests to the nginx container fail with `500` and also take `~10s`:

```sh
% kubectl exec -it test-757d8cc7cd-fjs9q -- curl -i nginx
Defaulting container name to alpine.
Use 'kubectl describe pod/test-757d8cc7cd-fjs9q -n default' to see all of the containers in this pod.
HTTP/1.1 500 Internal Server Error
content-length: 0
date: Tue, 15 Jan 2019 16:56:21 GMT
```

Same happens for plain HTTP requests to external services:

```sh
% kubectl exec -it test-757d8cc7cd-fjs9q -- curl -i http://8.8.8.8
Defaulting container name to alpine.
Use 'kubectl describe pod/test-757d8cc7cd-fjs9q -n default' to see all of the containers in this pod.
HTTP/1.1 500 Internal Server Error
content-length: 0
date: Tue, 15 Jan 2019 16:57:54 GMT
```

When using HTTPS, everything works:

```sh
% kubectl exec -it test-757d8cc7cd-fjs9q -- curl -ki https://8.8.8.8
Defaulting container name to alpine.
Use 'kubectl describe pod/test-757d8cc7cd-fjs9q -n default' to see all of the containers in this pod.
HTTP/2 301 
location: http://www.google.com/
content-type: text/html; charset=UTF-8
date: Thu, 10 Jan 2019 02:17:29 GMT
expires: Sat, 09 Feb 2019 02:17:29 GMT
server: gws
content-length: 219
x-xss-protection: 1; mode=block
x-frame-options: SAMEORIGIN
alt-svc: quic=":443"; ma=2592000; v="44,43,39,35"
cache-control: public, max-age=2592000
age: 484834

<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="http://www.google.com/">here</A>.
</BODY></HTML>
```

#### `linkerd check` output

```sh
% linkerd version
Client version: edge-19.1.1
Server version: unavailable
```

```sh
% linkerd check  
kubernetes-api: can initialize the client..................................[ok]
kubernetes-api: can query the Kubernetes API...............................[ok]
kubernetes-api: is running the minimum Kubernetes API version..............[ok]
linkerd-existence: control plane namespace exists..........................[FAIL] -- The "linkerd" namespace does not exist

Status check results are [FAIL]
```

### Environment

- Kubernetes Version: v1.10.0
- Cluster Environment: Minikube
- Linkerd version: edge-19.1.1 curl.yaml

### Possible solution

—

### Additional context

We expect that the linkerd proxy still works, if the control plane is down, because otherwise we introduce yet another critical component into our cluster. For operation purposes we would like to not add such single point of failure.

Also the same issue happens, if the Linkerd control plane is properly deployed and the controller is scaled to `0` replicas.

**Comment by klingerf** [comment]
Thanks for reporting this, @svenwltr! I've verified the behavior you're seeing in my own environment, and I wanted to add that there's a lot more discussion of this issue in #1465.
