### ISSUE TITLE
2.1.1 release?

### ISSUE THREAD

**Issue by racevedoo** [linkerd/linkerd2#2091]
Hi,

I see many improvements were made since the last stable release.

Are there any plans to release a new stable version? Something like a 2.1.1 release, containing fixes/improvements that were made since 2.1.0?

Thanks!

**Comment by grampelberg** [comment]
Is there a reason the edge releases don't work for you?

**Comment by wmorgan** [comment]
(We're not against this, just curious how much a difference it makes vs using an edge release)

**Comment by racevedoo** [comment]
I guess it's just for the "production ready" status of a stable release

**Comment by klingerf** [comment]
Hey @riaan53, check out https://linkerd.io/2/upgrade/ for more info about upgrading linkerd. Upgrading from edge to edge or edge to stable should both work as described there.

**Comment by wmorgan** [comment]
@racevedoo I talked to some of the other maintainers -- there are some new changes in master and we're not ready to cut a prod ready release yet. Still deciding on whether the next release will be 2.1.1 or 2.2, but for now you'll have to use an edge release to get those fixes.

(In the future we might move to a fancier workflow that has parallel lines for dev and prod, but we're not there yet.)
