### ISSUE TITLE
Canonicalize DNS error logging could afford to be a little less scary

### ISSUE THREAD

**Issue by hawkw** [linkerd/linkerd2#2094]
### What problem are you trying to solve?

Currently, when a DNS query to canonicalize a name fails, the proxy logs a message at the error level. If there is a previously successful canonicalization, the proxy will fall back to that. 

In some cases, such as timeouts, these errors are pretty transient, but may occur quite frequently. This results in a _lot_ of error messages being logged but may not cause any actual failures (see also https://github.com/linkerd/linkerd2/issues/2069#issuecomment-454597636).

### How should the problem be solved?

When the proxy has fallen back successfully, it might be better to log a warning, rather than an error.
We might also want to consider downgrading timeouts to warnings. We could also change the canonicalization code to log only on state _changes_, rather than logging every individual timeout.

**Comment by grampelberg** [comment]
@hawkw I'd love to track this as part of the 2.1 polish, but I don't want to mess up your method. Want to move it over to that board? If it is a hassle, I can add a label to do the same.

**Comment by hawkw** [comment]
@grampelberg I've added it to that project as well, looks like github will allow it to be in both.

**Comment by grampelberg** [comment]
TIL! Thank you!
