### ISSUE TITLE
Support using custom Grafana instance

### ISSUE THREAD

**Issue by Monnoroch** [linkerd/linkerd2#2101]
## Feature Request

Allow users to configure Linkerd to use pre-existing Grafana instance. The two cases are:
- in-cluster Grafana (kubernetes): `grafana.monitoring.svc.cluster.local:3000`
- external Grafana: `https://grafana.my.domain.com`

### What problem are you trying to solve?

If you already have Grafana set up, it a waste of resources to spawn another one just for Linkerd. Both compute resources and ops team resources to support it.

### How should the problem be solved?

`linkerd install` should ideally have a flag `--grafana-url https://grafana.my.domain.com` which will generate the right configuration.

After that:

1. `linkerd install` should not generate configs to start Grafana
2. `linkerd dashboard` should output the specified link
3. do not start a proxy for an external Grafana instance
4. linkerd web UI should then display links to the specified Grafana

### Existing state

I was shown [this link](https://github.com/linkerd/linkerd2/blob/86c4596b88c732bad34aa28fa433667573448de2/cli/install/template.go#L348) that suggests that it's done already. However, then I found out that it doesn't work as expected (by me).

### Potential issues

1. I don't know how the tool can help users add all necessary dashboards to Grafana. But one always can do it manually. The best way would be to upload them to Grafana store where they can be installed in one click.

2. Since Grafana is shared in this case, users will probably want to put linkerd dashboards in a folder. Hence, there probably needs to be a way to configure it's name to allow web ui to display correct links.

**Comment by grampelberg** [comment]
Related to #2102.
