### ISSUE TITLE
document (or remove) Authorities table

### ISSUE THREAD

**Issue by wmorgan** [linkerd/linkerd2#2103]
The "Authorities" table can cause confusion in users. I propose either a) adding a tooltip that says something along the lines of "The name that the service was called as. Equivalent to the Host header for HTTP/1.1 requests, or the :authority psuedo-header for HTTP/2 requests", or b) removing this section entirely.

**Comment by grampelberg** [comment]
@scottcarol I'd love to make some progress on this issue in the next release or so. Want to do some brainstorming about how to make it better? @adleong has some great ideas.

**Comment by scottcarol** [comment]
@grampelberg Can do - @adleong I'll ping you.
