### ISSUE TITLE
Add the ability to fully complete a service profile in the UI

### ISSUE THREAD

**Issue by rmars** [linkerd/linkerd2#2109]
Currently Service Profile creation in the UI is limited to adding the service and namespace. To actually add routes or further customize the profile, you still need to download it and edit the yaml.

![screen shot 2019-01-17 at 3 12 20 pm](https://user-images.githubusercontent.com/549258/51354972-59fb2e80-1a6a-11e9-8bee-c6daae5e82f6.png)

We should add the ability to fully complete the Service Profile yaml in the UI without having to add information in two steps.

**Comment by grampelberg** [comment]
I dunno if I'm comfortable with starting to author YAML in the dashboard, feels like a big step. Maybe the right way to solve this problem would be combined with #2041? @adleong what do you think?
