### ISSUE TITLE
linkerd check --single-namespace Missing permissions to create Role/RoleBinding

### ISSUE THREAD

**Issue by djeeg** [linkerd/linkerd2#2117]
### What is the issue?

`linkerd check` reports missing permissions, though `linkerd install` seems to work ok

### How can it be reproduced?

Latest release edge-19.1.2, use single-namespace, not full cluster permissions

#### `linkerd check` output

`linkerd check --pre -l $EKSNAMESPACE --single-namespace`
 
can create Roles -> Missing permissions to create Role
can create RoleBindings -> Missing permissions to create RoleBinding
everything else passes
 
`linkerd install -l $EKSNAMESPACE --single-namespace | kubectl -n $EKSNAMESPACE apply -f -`

### Environment

- Kubernetes Version: 1.10
- Cluster Environment: EKS
- Host OS:
- Linkerd version: edge-19.1.2 

### Possible solution

These lines dont seems to consider the namespace with hc.ControlPlaneNamespace?
 
https://github.com/linkerd/linkerd2/blob/master/pkg/healthcheck/healthcheck.go#L298
https://github.com/linkerd/linkerd2/blob/master/pkg/healthcheck/healthcheck.go#L305

### Additional context

**Comment by grampelberg** [comment]
Good catch!
