### ISSUE TITLE
Add load balancing capability for bidirectional gRPC streaming

### ISSUE THREAD

**Issue by glindsell** [linkerd/linkerd2#2120]
## Feature Request
Currently, load balancing using Linkerd2 is possible across clients/servers when making many individual gRPC requests. However, load balancing is not observed when streaming bidirectionally between clients/servers over a single gRPC connection.

### What problem are you trying to solve?
I would like to see Linkerd2 load balancing across gRPC clients/servers when performing bidirectional gRPC streaming.

### How should the problem be solved?
Unsure at this stage.

### Any alternatives you've considered?
Currently I am reaching out to the Linkerd1 community as well, to see if it is already implemented there.

### How would users interact with this feature?
When using gRPC bidirectional streaming (or possibly any other single connection which streams multiple messages).

I have a reproducible example app here:

https://github.com/glindsell/grpc-bidi-streaming

Which uses a slightly augmented basic gRPC bidirectional streaming example to demonstrate Linkerd2 failing to load balance across the gRPC servers. If this example were to succeed, it would be an example of how to use this feature.

**Comment by grampelberg** [comment]
@siggy I vaguely remember you mentioning something about gRPC streaming?

**Comment by grampelberg** [comment]
Tangentially related to #2079 (from the test app perspective).

**Comment by siggy** [comment]
@grampelberg we've encountered a timeout issue related to gRPC streaming, which I expect #2079 will help reproduce more easily, but nothing related to load balancing. agree it would be worthwhile to incorporate that into our test app.

**Comment by glindsell** [comment]
@siggy Are you able to elaborate on the timeout issue related to gRPC streaming which you are referring to? I've been playing with different gRPC examples (unary/streaming/bidi-streaming) with Linkerd2 and would be interested to know if I have already come across what you are referring to or not. Thanks

**Comment by siggy** [comment]
@glindsell We had an issue with client-side streaming, where if the server never sends a message back, the proxy would time out. We're working on a test framework to better identify these cases (#2079). If you encounter particular use cases, definitely comment on there.

**Comment by glindsell** [comment]
*I have noticed the following behaviour:*

If I run 5 pods, each a copy of a grpc server, grouped into a service of grpc servers, along with a single grpc client, all meshed in the same k8s cluster - load balancing occurs across the servers per grpc stream on a single grpc connection as required by my use case. *This suggests load balancing is occurring _per grpc stream_.*

However, if I run _only_ the service of grpc servers meshed in the k8s cluster, and send messages to the server service endpoint from a grpc client which is _un-meshed_ and _outside_ the k8s cluster - no load balancing occurs across the servers, and instead the first grpc server to be hit takes all the traffic of the subsequent streams. If the client is stopped and re-started one of the other servers will be hit and will now take all the traffic. *This suggests load balancing is occuring _per grpc connection_.*

*Which raised the following questions:*

1. Is this expected behaviour?

2. Do both the servers and clients of any use case have to be meshed with linkerd within the _same cluster_ for load balancing to occur on the level of grpc streams?

**Comment by grampelberg** [comment]
Linkerd load balances on the *client* side. You can get the benefits of gRPC load balancing by injecting the clients and do not need to actually inject the server side. When Linkerd is not injected on the client side, it is unable to do load balancing and you'll end up falling back to whatever other load balancer is in the way. For k8s and services that use cluster IPs, this will be at the TCP level and therefore per connection or stream.

In your first case, Linkerd is on the client side and able to load balance effectively. In your second case, Linkerd is only on the server side and does no load balancing.

If you would like to have load balancing occur, I would recommend standing up an ingress controller and injecting it with Linkerd. You'll end up with something that looks like this:

gRPC client -> `Service: LoadBalancer` -> Linkerd (server) -> ingress controller -> Linkerd (client) -> backend gRPC pods

The edge between the gRPC client and the ingress controller will be load balanced at the connection level and the edge between the ingress controller and your gRPC pods will be load balanced at the request level.

**Comment by glindsell** [comment]
I have attempted to create the following data path to achieve the desired result:

gRPC client -> Linkerd (server) -> ingress controller -> Linkerd (client) -> backend gRPC pods

But am seeing the same error as identified in this solved issue:

https://github.com/linkerd/linkerd2/issues/1585
(`reset-error=6`)

Steps to recreate the issue can be found here:

https://github.com/glindsell/free-peer/tree/ingress/stream-meshed

**Comment by grampelberg** [comment]
Looking at this, I can't get it working without linkerd. It looks like nginx-ingress requires HTTPS to do any kind of grpc, see https://github.com/kubernetes/ingress-nginx/issues/2444.

**Comment by glindsell** [comment]
Thanks @grampelberg, looks like you're right! Hopefully that's the issue - I'll take a look at adding the SSL config required by nginx for gPRC and give it another go.
