### ISSUE TITLE
Kubernetes server must not have a `/` suffix

### ISSUE THREAD

**Issue by ewoutp** [linkerd/linkerd2#2132]
### What is the issue?
I'm getting 404 response when the `server` field in my kubeconfig has a `/` suffix.
E.g. 'server: https://1.2.3.4/'

Removing the trailing `/` solves the problem.

Note that `kubectl` has no problem with exactly the same kubeconfig file.

### How can it be reproduced?

Edit kubeconfig file, add trailing slash to server endpoint.

### Logs, error output, etc

(If the output is long, please create a [gist](https://gist.github.com/) and
paste the link here.)

#### `linkerd check` output

```text
$ linkerd check
kubernetes-api: can initialize the client..................................[ok]
kubernetes-api: can query the Kubernetes API...............................[FAIL] -- Unexpected Kubernetes API response: 404 Not Found
```

### Environment

- Kubernetes Version: 1.10.9
- Cluster Environment: GKE
- Host OS:  macos
- Linkerd version: 2.1

**Comment by klingerf** [comment]
Wow, good find @ewoutp! It should be pretty straightforward to fix this.
