### ISSUE TITLE
Sidebar should poll for new meshed resources

### ISSUE THREAD

**Issue by rmars** [linkerd/linkerd2#2134]
When new resources are added to the mesh, they don't show up in the sidebar unless the whole page is refreshed. We should add polling to the sidebar. 

We should also think about how the polling will affect the appearance of SR indicators in the sidebar and main change (the out of sync issue mentioned in #1542). I would rather the page at least refresh periodically, though, because the navigation aspect is useful.

Relevant past tickets: #1669 #1542

**Comment by scottcarol** [comment]
Closed by #2440
