### ISSUE TITLE
Linkerd dashboard tap tops not showing up

### ISSUE THREAD

**Issue by NalinOne77** [linkerd/linkerd2#2143]
I'm using aws ec2 instance to run linkerd and expose localhost to outside i'm using ingress controllers.
Linkerd dashboard and grafana dashboards are working finely.but in linkerd dashboard tops and taps are not showing up. when i inspect, it gives me this error message.

`popper.js:25 WebSocket connection to 'ws://linkerd-app.linkerd.us-east-2.dev.prsn.io/api/tap' failed: Error during WebSocket handshake: Unexpected response code: 400`

Anyone know why this is happening?

- Kubernetes Version:1.10.11
- Host OS:Amazon linux
- Linkerd version:edge-19.1.1 release

**Comment by grampelberg** [comment]
Your ingress likely does not support websockets.

**Comment by grampelberg** [comment]
That's the ingress object, what is your ingress controller?

**Comment by grampelberg** [comment]
You'll need to set that up in your ingress then, see https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/websocket

**Comment by grampelberg** [comment]
@NalinOne77 I'm going to close this out for now. Feel free to open up if that doesn't work for you.
