### ISSUE TITLE
Linkerd CLI can't connect to clusters that use self-signed certs

### ISSUE THREAD

**Issue by klingerf** [linkerd/linkerd2#2145]
## Bug Report

Users are [reporting](https://discourse.linkerd.io/t/using-self-signed-k8s-api-certificate/801) that the `linkerd` CLI can't connect to clusters that are setup with self-signed certs, but the `kubectl` CLI is able to successfully connect. This indicates that `linkerd` is not handling credentials in the same way the `kubectl` is handling credentials, but it should be.

### What is the issue?

On a cluster with self-signed certs, API calls return "certificate signed by unknown authority".

### How can it be reproduced?

Setup a cluster with self-signed certs (I haven't tried to replicate this yet).

### `linkerd check` output

```text
kubernetes-api
--------------
✔ can initialize the client
✘ can query the Kubernetes API
    Get REDACTED/version: x509: certificate signed by unknown authority
```

**Comment by grampelberg** [comment]
Are those experiencing this using `--insecure-skip-tls-verify` with kubectl? If so, this should work as a workaround:

```bash
kubectl config set-cluster ${KUBE_CONTEXT} --insecure-skip-tls-verify=true \
--server=${KUBE_CONTEXT}
```

**Comment by bjornmagnusson** [comment]
I am one of those who reported this issue. A bit about the environment.
kubectl is not used with any special flags at all, only a kubeconfig pointing to the Rancher master.
kubectl/linkerd cli is used directly on the cluster master.

Example (other clusters are multi-worker clusters):
kubectl get nodes
NAME          STATUS   ROLES                      AGE   VERSION
REDACTED   Ready    controlplane,etcd,worker   15m   v1.12.4

Environment:
Rancher2 custom cluster, v1.10.12 / v1.11.6 / v1.12.4 (same version for kubectl)
Servers are running CentOS Linux release 7.6.1810

**Comment by grampelberg** [comment]
@bjornmagnusson does that work around fix it for you? (not that it is a great long term solution)

**Comment by bjornmagnusson** [comment]
@grampelberg Yes, work-around worked.

**Comment by grampelberg** [comment]
Great, take a look at #2160 for a more permanent solution.
