### ISSUE TITLE
Improve GoDoc

### ISSUE THREAD

**Issue by siggy** [linkerd/linkerd2#216]
Godoc.org automatically crawls our repo and renders docs:
~https://godoc.org/github.com/runconduit/conduit~
https://godoc.org/github.com/linkerd/linkerd2

We could yield more thorough documentation by conforming to GoDoc's commenting:
https://blog.golang.org/godoc-documenting-go-code

We could also add a badge to `README.md`:
~https://godoc.org/github.com/runconduit/conduit?tools~
https://godoc.org/github.com/linkerd/linkerd2?tools

**Comment by cpretzer** [comment]
I'm going to start looking in to this. Are the conduit links in the original Issue still applicable?

Or are these the docs that should be improved: 
https://godoc.org/github.com/linkerd/linkerd2

This is the updated badge link:
https://godoc.org/github.com/linkerd/linkerd2?tools

**Comment by grampelberg** [comment]
This would be awesome!!!

**Comment by siggy** [comment]
@cpretzer Thanks! You're correct about the deprecated conduit URLs. I've updated the ticket description accordingly.

**Comment by cpretzer** [comment]
@grampelberg @siggy I've started working through this and given that it's a non-trivial amount of work, I plan to document files in a piecemeal manner.

This means that there will be several pull requests and to manage that, I'm going to use separate branches of my fork for each pull request and name them "216_go_doc_<year>_<month>_<day>".

Does that sound reasonable to you? I'm happy to work in a single branch on my side if that makes more sense from your perspective.

**Comment by siggy** [comment]
@cpretzer We’ve got a PR up now, #2023, that introduces basic comments for exported symbols, a subset of this ticket. Recommend keeping an eye on that PR to avoid duplicating work. Thanks for jumping in!

**Comment by cpretzer** [comment]
@siggy I appreciate the heads up. Once #2023 is accepted, I'll merge master to my fork and merge the changes to my branch.

I've been focusing on the comment documentation and hadn't even looked at the linting stuff yet

**Comment by ArthurSens** [comment]
Hello there, do you still need help with this? 

If that's the case, I would like to work on it... but I think I would need some guidance. 
Can I reach to someone to talk about this issue?

**Comment by cpretzer** [comment]
@ArthurSens sure, that would be great. The `#contributors` channel in [Linkerd Slack](https://slack.linkerd.io) is a great place to ask for guidance.

**Comment by coderfornow** [comment]
is this available ?

**Comment by cpretzer** [comment]
sure if you're willing to help, that would be great :)
