### ISSUE TITLE
Remove TLS requirement for running control plane with auto-injection

### ISSUE THREAD

**Issue by klingerf** [linkerd/linkerd2#2166]
Once #2163 merges, we'll no longer need the linkerd-ca deployment in the control plane to issue a certificate for the linkerd-proxy-injector to serve the auto-inject webook API, since it will be generating its own certificate. This means that we'll no longer need to require that users install the control plane with TLS enabled when enabling auto-inject. And we can remove all of the CA code that provisions certs for the proxy-injector.

**Comment by alpeb** [comment]
This was addressed in my latest push to https://github.com/linkerd/linkerd2/pull/2163 and tested successfully :+1:
