### ISSUE TITLE
Improve Go Report Card

### ISSUE THREAD

**Issue by siggy** [linkerd/linkerd2#217]
We are getting an A+ on Go Report Card, but there is still a lot to improve:
~https://goreportcard.com/report/github.com/runconduit/conduit~
https://goreportcard.com/report/github.com/linkerd/linkerd2

We should consider these changes, and also add a badge to `README.md`.

**Comment by klingerf** [comment]
Hmm, looks like almost all of the issues in the repo could be found with the [golint](https://github.com/golang/lint) tool. We should get in the habit of running that.

**Comment by pcalcado** [comment]
Should we create a `precommit.sh` file or something that does a standardized `go test ./... && go vet ./... && golint`? Also could be the script travis runs

**Comment by klingerf** [comment]
Heh, and this one:

> func name will be used as version.VersionFlag by other packages, and that stutters; consider calling this Flag

**Comment by pcalcado** [comment]
I am very easygoing with these things, I can definitely live with the silly ones if it gives us a standardised and well-supported way to check for more interesting things.

**Comment by rafaeljesus** [comment]
IMHO I am not really about skipping these lint errors, it's pretty handy for writing idiomatic golang code ^.^

Also it might be required if you decide to add it at [awesome-go](https://github.com/avelino/awesome-go) list

**Comment by siggy** [comment]
Taking this a bit further, #2284 introduced a [.golangci.yml](https://github.com/linkerd/linkerd2/blob/5b836526b8018ae1315df87005a42a493b31ba55/.golangci.yml) file, which specifies which golangci-lint checkers to run.

To help improve the codebase further, we should work towards reducing the number of checkers in the `disable` list. Essentially repeat this pattern:
1. remove an item from the `disable` list
1. run `bin/lint`, observe errors
1. fix errors until `bin/lint` succeeds

**Comment by grampelberg** [comment]
@siggy this issue doesn't feel particularly actionable at this point (and there's a ton of awesome work that's already been done). WDYT about closing this out and opening up directed issues for what's remaining?

**Comment by siggy** [comment]
@grampelberg I'm fine with closing this one.

Note that we lost our perfect gofmt score recently:
https://goreportcard.com/report/github.com/linkerd/linkerd2#gofmt
This may have happened when we changed our lint config, probably worth a new issue to track this.

**Comment by grampelberg** [comment]
I was wondering about that. Thanks!
