### ISSUE TITLE
Map klog levels to controller log levels

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#2171]
### What problem are you trying to solve?

Currently, changing `--controller-log-level` does not change klog's level.

### How should the problem be solved?

Map the `-v` levels of klog to `panic, fatal, error, warn, info, debug`. Kubernetes documents the [log levels](https://github.com/kubernetes/community/blob/master/contributors/devel/logging.md).

Perhaps:

- `-v 0` - panic, fatal, error, warn
- `-v 1` - info
- `-v 2` - info
- `-v 3` - debug
- `-v 4` - debug
- `-v 5` - Not sure, maybe we should add a trace level? @siggy found differences between logging at `-v 8` even. When does it stop?

Note, along with `-v` for log levels, klog also uses `stderrthreshold`. The possible values for that are info, warning, error, fatal. These can also be mapped to the linkerd log levels.

**Comment by grampelberg** [comment]
Should there be something similar here for klog and the cli?

**Comment by klingerf** [comment]
The CLI doesn't support log levels, but it doesn't have a `--verbose` flag, which sets logrus's log level to "debug". I recommend setting klog's log level to something sufficiently high (5?) when the `--verbose` flag is present, rather than making the klog log level fully configurable.

**Comment by grampelberg** [comment]
I'm a +1 on that!
