### ISSUE TITLE
Control plane doesn't pick up ServiceProfile resource changes

### ISSUE THREAD

**Issue by bourquep** [linkerd/linkerd2#2173]
### What is the issue?

After creating/updating a `ServiceProfile` resource, I need to restart the CP pods (all pods in `linkerd` namespace) in order for linkerd to pick up the new/updated `ServiceProfile`.

### How can it be reproduced?

* Start with a fresh Linkerd2 install (edge 19.1.3 in my case) in a cluster where at least 1 service is deployed
* Run `linkerd routes svc/my-service -n my-namespace`, observe that there is a single `[DEFAULT]` route (expected).
* Run `kubectl apply -f service-profile.yml` on a service profile definition that matches your service
* Run `linkerd routes svc/my-service -n my-namespace`, observe that there is still a single `[DEFAULT]` route. Not expected.
* Restart the CP pods (`kubectl delete po -n linkerd --all`)
* Run `linkerd routes svc/my-service -n my-namespace`, observe that the routes are there.
* Edit the `service-profile.yml` file with a change that is easy to identify via `linkerd routes` (e.g. change the name of a route)
* Run `kubectl apply -f service-profile.yml`
* Run `linkerd routes svc/my-service -n my-namespace`, observe that the updated route name is not there
* Restart the CP pods, observe that `linkred routes` reports the new route name

(If the output is long, please create a [gist](https://gist.github.com/) and
paste the link here.)

#### `linkerd check` output

```text
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version

linkerd-existence
-----------------
√ control plane namespace exists
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-api
-----------
√ control plane pods are ready
√ can query the control plane API
√ [kubernetes] control plane can talk to Kubernetes
√ [prometheus] control plane can talk to Prometheus

linkerd-service-profile
-----------------------
√ no invalid service profiles

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ control plane is up-to-date
√ control plane and cli versions match

Status check results are √
```

### Environment

- Kubernetes Version: 1.11.5
- Cluster Environment: AKS
- Host OS: Ubuntu 16.04.5 LTS
- Linkerd version: edge-19.1.3

### Additional context

**Note**: Before I started writing this issue down, I had reproduced this issue at each step in the process (after creating the initial ServiceProfile resource and updating it twice). But now, I can't reproduce it anymore. 😒

This may or may not be related to the "k8s watches going stale" issue on AKS.

**Comment by grampelberg** [comment]
This sounds related to #1949. Once the fix for that lands, let's check it out.

**Comment by grampelberg** [comment]
@bourquep still seeing this?

**Comment by bourquep** [comment]
Nope! 🎉

**Comment by klingerf** [comment]
Great, thanks @bourquep! Closing this out.
