### ISSUE TITLE
Push container images for PRs

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#2198]
### What problem are you trying to solve?

I would like to be able to test PRs without doing a local build and pushing images.

### How should the problem be solved?

Out of band from the CI tests, build and push the images/CLI so that I can easily test new PRs.

**Comment by olix0r** [comment]
I don't think that images should be published for PRs from other repos, as this allows folks to put arbitrary code into our docker repos.

Furthermore, I'm skeptical how useful it is to automatically for all PRs as compared to, for instance, providing tooling that makes it easy for an arbitrary developer to test an arbitrary fork, etc... I suspect this would solve the same problems.

**Comment by grampelberg** [comment]
That does sound closer to solving my problem. I'd like something that doesn't require doing a local build and push. If that ends up being a button or something else I can run, that'd also be fantastic.
