### ISSUE TITLE
proxy injector webhook tests are too fragile

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#2201]
Every time the proxy's generated yaml changes, controller/proxy-injector/webhook_test.go tests fail, because these tests rely on hardcoded base64 values describing the pod manifest.

These test failures are extremely hard to diagnose without knowing how this all hangs together.

We should figure out a testing strategy that is more flexible to unrelated changes.

At a worst case, we may want to remove these tests if they prove too costly to maintain.

**Comment by ihcsim** [comment]
Agreed. I was just thinking about this earlier. These tests were added back then to help us understand the kind of requests/responses the webhook receives/generates. I feel these tests no longer provide us with any valuable insights into whether anything has broken. I can remove them in my next pass.
