### ISSUE TITLE
Introspect layers of service discovery

### ISSUE THREAD

**Issue by siggy** [linkerd/linkerd2#2205]
This is a tracking ticket to prioritize adding introspection into more layers of the service discovery pipeline:

- [x] #2221 API responses from k8s api server
- [ ] k8s client cache
- [ ] informer cache
- [x] #2195 endpoints watcher cache
- [ ] API messages to proxy
- [ ] proxy internal state

Based on https://github.com/linkerd/linkerd2/pull/2195#issuecomment-460543013

**Comment by olix0r** [comment]
It's probably important that we understand how this interacts with `--ha`, i.e. when there are multiple destination service instances and a given proxy may be talking to an arbitrary number of these instances at any point.
