### ISSUE TITLE
Proxy configuration proliferation in tests needs simplification

### ISSUE THREAD

**Issue by adleong** [linkerd/linkerd2#2208]
There are many instances of proxy configurations throughout the Linkerd2 tests.  This means that whenever a change is made to the way we configure proxies (for example, adding a new environment variable), there are dozens of tests that must be updated.  This is onerous, time-consuming, and prone to merge conflicts.

We should find a way to make this less painful.

Related to #2201

**Comment by rmars** [comment]
The go standard library manages this using an `-update` flag on the tests, so that if you ran `go test ./... -update` all of the golden files would be updated:
https://github.com/golang/go/blob/master/src/cmd/gofmt/gofmt_test.go

**Comment by klingerf** [comment]
Huge 👍 to @rmars's suggestion.

**Comment by rmars** [comment]
This was fixed in https://github.com/linkerd/linkerd2/pull/2315
