### ISSUE TITLE
proxy-api: Only return TLS identities when dst pod is known to participate in identity

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#2217]
The proxy-api returns a TLS identity whenever the pod is annotated with a controller namespace:

https://github.com/linkerd/linkerd2/blob/50fbcc60b50a367209672a8b6e34398955d4344a/controller/api/proxy/endpoint_listener.go#L202-L220

Then, the proxy checks the namespace to determine whether TLS should be initiated:

https://github.com/linkerd/linkerd2-proxy/blob/4b0e50e8fc488f535a4688447efa89cd650fec92/src/transport/tls/identity.rs#L26-L33

This is fragile and, in fact, the only reason that the proxy has to know anything about kubernetes namespaces; and the K8sPodIdentity type is the only kubernetes specific-logic that has bled into the proxy api.

At the very least, the controller check should be made server-side, so that the proxy-api only returns identities of pods that it expects the client to be able to validate.

Following that, the proxy should stop performing this check and, eventually, the controllerNS value should be deprecated in the API and server should stop setting it.  And, preferably, the entire K8sPodIdentity type should be removed from the API.

Furthermore, the inject process should be modified to set an annotation on pods to explicitly indicate whether the pod should participate in identity. The proxy-api should also check this annotation before returning an identity in a resolution.

**Comment by klingerf** [comment]
I'm pretty sure this issue is the same as #1274, but phrased a bit differently. Just wanted to pass it along in case you wanted to see some prior art for implementation details.
