### ISSUE TITLE
When conduit is not installed, tap returns EOF message

### ISSUE THREAD

**Issue by klingerf** [linkerd/linkerd2#222]
This behavior exists on the current master (5b53123), and is unchanged by #221. When conduit is not installed, running tap results in a cryptic error message:

```
$ ./bin/conduit tap deploy foo
error reading byte stream header: error while reading bytes from message: unexpected EOF
```

It would be better if the tap command (and possibly other subcommands) could detect that conduit is not installed, and print a message prompting the user to install it.

**Comment by briansmith** [comment]
This is a side effect of using the API server's proxy functionality + the Go TLS (and/or HTTP) library being too strict. When the proxy encounters an error it closes the ungracefully as far as TLS is concerned; in particular it doesn't send a TLS connection closure alert. The Go library then interprets this an an "unexpected EOF."

We can check various things ahead of time to reduce the chances that the Kubernetes API server is going to encounter an error, e.g. checking if the service being contacted is healthy. However, there are always going to be possible situations where the API server encounters an error communicating with the control plane component. We either should stop using the API server proxy mechanism or do some low-level work on the API server and/or the Go networking library to fix this poor interaction.

Note that with the TLS work we'll likely switch from the API server proxy mechanism to using an API server extension. I'm not sure if that would make a difference or what the diffference would be yet, though.
