### ISSUE TITLE
Notify of TCP traffic in the CLI/GUI

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#2223]
### What problem are you trying to solve?

When a service is using either a binary protocol or HTTPS (and terminating it), there are no metrics. This can be pretty confusing in the CLI/GUI as the stats just don't show up. In particular, HTTPS comes up as a common question.

### How should the problem be solved?

Replace the `meshed` column with a `protocol detected` (name needs work) column. This way, you'll know that we're seeing traffic, just that it can't be parsed and there won't be metrics for it.

**Comment by grampelberg** [comment]
@siggy what do you think about adding something like this as a check? Feels wrong to do a warning or error, but it also is something nice to have. Perhaps this suggests a different command or something that shows TCP metrics...

**Comment by grampelberg** [comment]
Related to #2224.

**Comment by siggy** [comment]
@grampelberg i definitely agree just showing no stats isn't a good user experience. perhaps a modification to the `stat` command, or a separate command could help with that, maybe even with some hints if we know it's only tcp metrics.

**Comment by rmars** [comment]
@grampelberg TCP stats are now available in the CLI and in several dashboard pages. Is this ticket still something we should do? If there's TCP only stats, the http-based tables do still look bare, but you can scroll down and still see some metrics. We could possibly add a TCP connections column to all the metrics tables so that they don't look so weird. We could alternatively add a note that says something like "No http metrics detected but TCP metrics present, please scroll down"

**Comment by grampelberg** [comment]
@rmars the core problem is that folks go looking for stats, let's say for an HTTPS service, and are confused/surprised that nothing is there. For the GUI, a little notification that says there are TCP metrics with a link would be great (whether there are HTTP one or not, it is nice to teach users about other functionality in the platform).

For the CLI, it is a little bit tougher. Perhaps adding a column to `stat` that says there's *something* and a clear command for the CLI to run?

**Comment by rmars** [comment]
@grampelberg For the CLI additional column, how about a simple `TCP detected` that just says y/n? That would at least give some indication when there are no http stats present. The criterion could be tcp open connections > 0.

**Comment by grampelberg** [comment]
Maybe just show the open connections count?

**Comment by siggy** [comment]
@rmars Is this good to close?

**Comment by rmars** [comment]
I think enough has been completed for the UIs to be less confusing when there's TCP traffic and no HTTP traffic. There's still more work that could be done in showing TCP traffic, but we should open a more specific issue when we decide what that work would entail.
