### ISSUE TITLE
Automatic proxy injection still appears to require TLS

### ISSUE THREAD

**Issue by gamer22026** [linkerd/linkerd2#2236]
### What is the issue?
When using proxy auto-injection (`linkerd install --proxy-auto-inject`), liveness and readiness checks are failing.
### Logs, error output, etc
```
ERR! admin={bg=tls-config} linkerd2_proxy::transport::tls::config error loading /var/linkerd-io/identity/certificate.crt: No such file or directory (os error 2)
WARN admin={bg=tls-config} linkerd2_proxy::transport::tls::config error reloading TLS config: Io("/var/linkerd-io/identity/certificate.crt", Some(2)), falling back
ERR! proxy={server=in listen=0.0.0.0:4143 remote=100.96.64.1:47810} linkerd2_proxy::proxy::http::router service error: an error occurred trying to connect: Connection refused (os error 111) (address: 127.0.0.1:9200)
```
#### `linkerd check` output

```text
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version

linkerd-existence
-----------------
√ control plane namespace exists
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-api
-----------
√ control plane pods are ready
√ can query the control plane API
√ [kubernetes] control plane can talk to Kubernetes
√ [prometheus] control plane can talk to Prometheus

linkerd-service-profile
-----------------------
√ no invalid service profiles

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ control plane is up-to-date
√ control plane and cli versions match

Status check results are √
```

### Environment

- Kubernetes Version: 1.10.11
- Cluster Environment: kops
- Linkerd version: 19.2.1

### Additional context
The failing health check:
```
httpGet:
  path: /_cluster/health
  port: 9200
  scheme: HTTP
```

**Comment by wmorgan** [comment]
Thanks @gamer22026. Just to confirm, was this working for you with auto-inject in 19.1.4?

**Comment by gamer22026** [comment]
First time using auto-inject. Was waiting until default was opt-out.

**Comment by ihcsim** [comment]
Looks like the injected sidecar is still trying to mount the secret volume.
```
    volumeMounts:
    - mountPath: /var/linkerd-io/trust-anchors
      name: linkerd-trust-anchors
      readOnly: true
```
The proxy-injector chart needs to be updated to check if CA is enabled, before including all the TLS-related assets.

**Comment by klingerf** [comment]
@gamer22026 Good catch -- it looks like the YAML injected by the proxy injector still includes some of the `TLS` env variables, and we should remove those. The proxies should fallback, however, if they're unable to connect with TLS. In my local testing, I see the same logs as you:

```
INFO linkerd2_proxy::app::main using controller at Some(Name(NameAddr { name: "linkerd-proxy-api.linkerd.svc.cluster.local", port: 8086 }))
INFO linkerd2_proxy::app::main routing on V4(127.0.0.1:4140)
INFO linkerd2_proxy::app::main proxying on V4(0.0.0.0:4143) to None
INFO linkerd2_proxy::app::main serving Prometheus metrics on V4(0.0.0.0:4191)
INFO linkerd2_proxy::app::main protocol detection disabled for inbound ports {25, 3306}
INFO linkerd2_proxy::app::main protocol detection disabled for outbound ports {25, 3306}
ERR! admin={bg=tls-config} linkerd2_proxy::transport::tls::config error loading /var/linkerd-io/trust-anchors/trust-anchors.pem: No such file or directory (os error 2)
WARN admin={bg=tls-config} linkerd2_proxy::transport::tls::config error reloading TLS config: Io("/var/linkerd-io/trust-anchors/trust-anchors.pem", Some(2)), falling back
```

But all of the readiness and liveliness probes that are configured for this pod continue to pass, once the fallback kicks in. So I'm a bit surprised that this would cause your health checks to fail.

Nevertheless, we'll remove the remaining TLS configuration ASAP.

**Comment by gamer22026** [comment]
Just to validate, I manually injected linkerd and readiness check was OK. Would the fallback in the auto-inject scenario cause the timing to increase? The timeoutSeconds on mine was set to 1.

**Comment by ihcsim** [comment]
@gamer22026 What if you increase the timeout with auto-inject?

**Comment by klingerf** [comment]
@gamer22026 The fix for the TLS issue just merged in #2246, and it will go out with today's edge release. That's a great point about timeouts. I think it's entirely possible that the fallback introduces additional latency, and it could be the cause of your failing health check. Would be great to validate that with the next release.

**Comment by gamer22026** [comment]
Just to cover all the bases, I increased the timeoutSeconds to 5 (from 1) and with auto-inject the readiness probe still fails with:
```
ERR! proxy={server=in listen=0.0.0.0:4143 remote=100.96.80.1:39540} linkerd2_proxy::proxy::http::router service error: an error occurred trying to connect: Connection refused (os error 111) (address: 127.0.0.1:9200)
ERR! proxy={server=in listen=0.0.0.0:4143 remote=100.96.80.1:39608} linkerd2_proxy::proxy::http::router service error: an error occurred trying to connect: Connection refused (os error 111) (address: 127.0.0.1:9200)
```

**Comment by klingerf** [comment]
@gamer22026 Ok, the [edge-19.2.2](https://github.com/linkerd/linkerd2/releases/tag/edge-19.2.2) is now available with the TLS fix. Would you mind giving it a shot in your env to see if that fixes the failing probes that you're seeing?
