### ISSUE TITLE
Remove pathPrefix from the dashboard code

### ISSUE THREAD

**Issue by rmars** [linkerd/linkerd2#2254]
In https://github.com/linkerd/linkerd2/pull/2052 we moved from using the kubernetes service proxy to port forwarding. This means we no longer need to support `pathPrefix` from the dashboard. We should remove it as it complicates our link code unnecessarily

**Comment by klingerf** [comment]
Totally agree! I think this is a dupe of #2057.

**Comment by rmars** [comment]
ahhhhh I was searching for "pathPrefix" under issues and couldn't find it. I'll close this then.
