### ISSUE TITLE
rfc: proxy: Start requiring rustfmt

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#2258]
Historically, we've tended to use rustfmt when introducing new files, but we've avoided using it for the entire project, as rustfmt wasn't considered stable (i.e. it was only available not nightly for quite some time) and it would therefore cause undesirable churn in the repo.

Time has passed and rustfmt appears to be quite a bit more stable now.

I propose that we:

1. Apply `cargo fmt --all` on the entire repo using the default rustfmt configuration;
2. Add a CI stage that runs `cargo fmt --all -- --check` on all proxy PRs, using stable cargo.

Are there any reasons that we should not do this? Are there any special rustfmt configurations we care about enforcing outside of the default behavior?

@seanmonstar @hawkw

**Comment by hawkw** [comment]
extremely in favor of this : thumbsup:

let's make sure it gets documented in the CONTRIBUTING file too.
