### ISSUE TITLE
Discovery based on IP addresses

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#2270]
### What problem are you trying to solve?

For outgoing connections, service names are not always used. Prometheus, for example, uses IP addresses to scrape the metrics. This isn't an issue for load balancing, but it is important for TLS and service profiles.

### How should the problem be solved?

Associate TLS and service profiles to outgoing requests that are IP address based as well as DNS based.

**Comment by olix0r** [comment]
To be clear: this is scoped to supporting enriched discovery (i.e. route & endpoint metadata) for HTTP requests when the `:authority` is numeric or when a `:authority`/`Host` is omitted (and we only have an SO_ORIGINAL_DST address).

What is the desired behavior for endpoint discovery when an IP address refers to a kubernetes load balancer IP? Should the proxy discover each individual endpoint in the service? Or should it use the LB IP and let kube proxy do the heavy lifting? My preference would be the former, I think.

**Comment by olix0r** [comment]
Currently the proxy is configured to only perform endpoint/route discovery for a whitelisted set of domain suffixes. How do we restrict the set of IPs that a proxy does discovery for?

My initial proposal is that the proxy be configured with subnets that are managed by Kubernetes. Is it possible to discover this configuration via the Kubernetes API or does this need to be configured with control plane installation?

Also, @grampelberg, how do you expect this to work with IP addresses?  I think that profile discovery should **not** be enabled by default for IP addresses. We _could_ potentially devise something to work with kubernetes-managed networks (maybe), but we _cannot_ support IP based profiles for services outside the cluster, as there is no reliable to map an IP address to a canonical, logical service name.  What is the use case for profile discovery based on IP address?

**Comment by grampelberg** [comment]
> What is the desired behavior for endpoint discovery when an IP address refers to a kubernetes load balancer IP? Should the proxy discover each individual endpoint in the service? Or should it use the LB IP and let kube proxy do the heavy lifting? My preference would be the former, I think.

I like letting kube-proxy do the heavy lifting, but what are the implications on identity at that point?

> we _cannot_ support IP based profiles for services outside the cluster, as there is no reliable to map an IP address to a canonical, logical service name.

It'd be possible to do a reverse DNS lookup, right? Though, the name would be unlikely to match up and probably not worth supporting anyways.

> What is the use case for profile discovery based on IP address?

I'm assuming that policy will hang off profiles, but maybe that's a server concern and this is specific to the clients?

It'd be beneficial for per-route metrics when using an IP on services that are headless or use IPs to communicate primarily. Feels like it is firmly in the nice to have category until there's a serious ask for it. There are implications on the debugging/diagnosis side though (why can't I see metrics?).

**Comment by olix0r** [comment]
> It'd be possible to do a reverse DNS lookup, right? Though, the name would be unlikely to match up and probably not worth supporting anyways.

Even if we could, this is extremely fragile due to virtual hosting (i.e. especially when talking to CDN-terminated services). I think we're going to _have to_ have a degraded experience when we can't know a _name_ for a service.

I think we should limit the scope of this issue to endpoint metadata (i.e. TLS) and not arbitrary policy, until we have a clearer story around how this policy is associated/owned/etc.

**Comment by hawkw** [comment]
Should this be pinned?

**Comment by olix0r** [comment]
This issue isn't really scoped to be actionable. We have other issues for narrower details.

**Comment by afirth** [comment]
this issue is still linked in the docs https://linkerd.io/2.10/tasks/using-ingress/#traefik (in the note)
