### ISSUE TITLE
proxy-api logs errors when route timeout isn't set

### ISSUE THREAD

**Issue by adleong** [linkerd/linkerd2#2276]
When a route does not specify a timeout, the proxy-api defaults to the default timeout and logs an error:

```
time="2019-02-13T16:29:12Z" level=error msg="failed to parse duration for route POST /io.linkerd.proxy.destination.Destination/GetProfile: time: invalid duration "
```

We should not log any error when the timeout is blank.  Additionally, having service profile name and namespace in logs like this could be helpful.

### Environment

- Linkerd version: stable-2.2.0

**Comment by bourquep** [comment]
So I can safely ignore those errors for now in stable-2.2.0?

**Comment by klingerf** [comment]
@bourquep That's correct. And we're planning on cutting a stable-2.2.1 release this week that includes the fix for this issue.
