### ISSUE TITLE
UX: differentiate traffic by port

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#2280]
Currently, when one browses through the UI or runs `linkerd stat`, etc, we don't differentiate traffic by port. This is why, even when an application is not serving any traffic, we frequently show a small amount of traffic (e.g. 0.1rps) due to health checking, etc.  As a user, I'd really like to be able to see the RPS for each port on my pod so that administrative traffic can be understood distinctly from application traffic.

@grampelberg @rmars @scottcarol

**Comment by grampelberg** [comment]
@adleong have you thought any about how this intersects with `routes`? Probably not an issue, just haven't thought it through all the way yet.
