### ISSUE TITLE
endpoints command should have ep alias to match kubectl

### ISSUE THREAD

**Issue by jon-walton** [linkerd/linkerd2#2283]
### What problem are you trying to solve?

Every time I try to get the linkerd endpoints, i end up typing `l ep` which fails 😄 I'm lazy and typing `l endpoints` is too many key presses 😉 

### How should the problem be solved?

ad an alias for the `linkerd endpoints` command to be `linkerd ep`

**Comment by grampelberg** [comment]
@jon-walton how is `endpoints` working out for you? Helping at all? Anything missing?

**Comment by Pothulapati** [comment]
If this issue is just about adding an alias as `ep` for `endpoints` , I am willing to take this :)

**Comment by grampelberg** [comment]
Go for it!

**Comment by jon-walton** [comment]
@grampelberg since the recent Azure oriented fixes in the last edge builds, I've also upgraded the Azure CNI plugin (which actually gave us some large performance gains) so I've not used the endpoints command in anger yet, but it'll be one of the first things in our runbook, thanks for adding it
