### ISSUE TITLE
proxy: Measure allocator differences in Rust 1.32

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#2309]
There are [reports](https://github.com/rust-lang/rust/issues/56980) that rust 1.32 introduced a substantial memory allocation change by adopting jemalloc.  We should compare builds of the proxy between 1.31 and 1.32 and measure the impact of the change on our base case, at least.

**Comment by hawkw** [comment]
AFAICT based on the linked issue above, it looks like the performance issues in 1.32 may be caused not by the use of jemalloc in general, but by a bug in the specific way jemalloc is linked or exposed to Rust. So, if we find that we're affected by these issues, we may want to consider re-assessing jemalloc later if/when the performance issues on 1.32 are resolved.

**Comment by mati865** [comment]
Rust 1.32 switched to system allocator (glibc on Linux) from jemalloc for produced executables. On recent systems (glibc 2.26+ IIRC) it improves performance and reduces memory usage for most of the typical cases. You can return to jemalloc with this crate: https://crates.io/crates/jemallocator

**Comment by AdaephonBen** [comment]
@hawkw I'm a newbie to linkerd and I'd like to work on this issue. I noticed that the issue was created a long time ago and version 1.46 is now the latest version of Rust. Is this issue still relevant?
