### ISSUE TITLE
proxy: set `l5d-remote-ip` header

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#2310]
It's important that applications be able to know (for diagnostics, and policy), the source information for requests. Typically, proxies add a [`forwarded`](https://tools.ietf.org/html/rfc7239) header including `for=IP`. However, the identity service will need to use this header to make an authoritative decision, so we need to establish a header that the proxy may actively strip and set on inbound requests (i.e. so that clients may not set this header). It would, of course, be inappropriate for the inbound proxy to strip all `forwarded` headers, since there may be prior intermediaries that set this information. So, I propose that the inbound proxy clear and set a new `l5d-remote-ip` header including the IP from which the request was received.

Similarly, this header should be set on outbound responses to inform the client of the actual IP address of the server.

**Comment by hawkw** [comment]
@olix0r should this header also include ports, or just the IP?

**Comment by MelwinKfr** [comment]
Hello, is there an option to set during the installation in order to make this work?

I'm using `gcr.io/linkerd-io/proxy:stable-2.5.0` and the header `l5d-remote-ip` is empty when requests arrive on my Nginx Ingress Controller.

**Comment by grampelberg** [comment]
We ended up removing this as there was a bunch of potential for leaking internal cluster details if you weren’t careful.

That said, if your ingress controller is terminating https, there’s not much Linkerd can do to add the header. What platform are you running your cluster on? Anyone who supports the PROXY protocol should just have it work.

**Comment by MelwinKfr** [comment]
Alright, thank you for clearing this out. I am running my cluster on premise, are you referring to [this](https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt) when you write "the PROXY protocol"?

**Comment by grampelberg** [comment]
Yup!
