### ISSUE TITLE
The help text for '--proxy-auto-inject' still mentions that the feature is experimental

### ISSUE THREAD

**Issue by bourquep** [linkerd/linkerd2#2311]
### What is the issue?

The help text for `linkerd install --proxy-auto-inject` still mentions that the feature is experimental.

### How can it be reproduced?

* Run `linkerd install --help`
* Observe that the help text for `--proxy-auto-inject` states: _**Experimental**: Enable proxy sidecar auto-injection webhook (default false)_

### Environment

- Linkerd version: stable-2.2.0

### Additional context

According to the 2.2.0 release [blog post](https://blog.linkerd.io/2019/02/12/announcing-linkerd-2-2/), the auto-inject feature is no longer experimental:

>Linkerd 2.2 graduates auto-inject to be a fully-supported (non-experimental) feature.

**Comment by grampelberg** [comment]
Oh, great catch!
