### ISSUE TITLE
Remove integration test dependency on httpbin.org

### ISSUE THREAD

**Issue by siggy** [linkerd/linkerd2#2316]
The egress integration test relies on httpbin.org to test requests:
https://github.com/linkerd/linkerd2/blob/ed3fbd75f3cbee76b45d73687134e23f45b41374/test/egress/egress_test.go#L92

This means that behavior changes in that external online service can break ci:
https://travis-ci.org/linkerd/linkerd2/jobs/495002001#L7405

Propose removing the dependency on httpbin.org. One approach could be to boot our own copy of httpbin and route to it via a service with an external name.

**Comment by siggy** [comment]
Related: https://github.com/postmanlabs/httpbin/issues/536

**Comment by adleong** [comment]
This is causing us CI grief as the `httpbin.org` behavior is now non-deterministic regarding http vs https.
