### ISSUE TITLE
Routes error message is misleading

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#2328]
### What is the issue?

When there is no traffic to a service, running `linkerd routes` produces:

```bash
linkerd routes deploy/foo
Error: No Service Profiles found for selected resources
```

The error message should be `Error: No traffic observed over the last X minutes, see ... for more details`

**Comment by grampelberg** [comment]
@adleong now that we can fetch a service profile without metrics, can we just always show the table with 0s in all the columns?

**Comment by adleong** [comment]
yes, I think this should be possible
