### ISSUE TITLE
Add TCP stats to the Linkerd Pod Grafana dashboard

### ISSUE THREAD

**Issue by rmars** [linkerd/linkerd2#2329]
We should expose TCP stats in the Pod dashboard. When this happens, we should also link to this dashboard from the TCP tables in the dashboard. (https://github.com/linkerd/linkerd2/pull/2262#discussion_r)

**Comment by liquidslr** [comment]
hey @rmars is this issue of adding it to grafana dashboard still open ?

**Comment by rmars** [comment]
Hey @liquidslr! Yep! this issue is available, feel free to work on it!

**Comment by liquidslr** [comment]
Sure I would like to work on this @rmars, could you please give a brief idea on how to proceed, thanks.

**Comment by liquidslr** [comment]
thanks, @rmars  i would like to work on this, could you please give a brief idea on how to proceed.

**Comment by rmars** [comment]
Hi @liquidslr! Yeah, so if you go to the grafana dashboard in the current linkerd dashboard (by running `linkerd dashboard --show grafana`) you can navigate to any of the Resource dashboard (e.g. `Linkerd Deployment`, /grafana/d/deployment/linkerd-deployment?refresh=5s&orgId=1) and notice the inbound and outbound tcp stats. We want to add those tcp stats to the `Linkerd Pod` view. I'd recommend adding them in the dashboard view, then looking at what the new dashboard json is in grafana, and then copying the relevant parts over to the config for it at `linkerd2/grafana/dashboards/pod.json`
