### ISSUE TITLE
proxy: inotify watch error on Debian stretch

### ISSUE THREAD

**Issue by siggy** [linkerd/linkerd2#2331]
#2241 bumps the proxy's base Docker image from `debian:jessie-slim` to `debian:stretch-20190204-slim`. When Linkerd is deployed via TLS, we observe repeated `inotify watch error`s:
```
linkerd linkerd-prometheus-86b4df8585-2ljml linkerd-proxy WARN admin={bg=tls-config} linkerd2_fs_watch::inotify watch error: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }, polling the fs until next change
linkerd linkerd-prometheus-86b4df8585-2ljml linkerd-proxy WARN admin={bg=tls-config} linkerd2_fs_watch::inotify watch error: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }, polling the fs until next change
linkerd linkerd-web-769c446cdb-f4br4 linkerd-proxy WARN admin={bg=tls-config} linkerd2_fs_watch::inotify watch error: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }, polling the fs until next change
linkerd linkerd-grafana-5dd4875c88-rv4hl linkerd-proxy WARN admin={bg=tls-config} linkerd2_fs_watch::inotify watch error: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }, polling the fs until next change
linkerd linkerd-controller-59bf7fb9cf-rj6pd linkerd-proxy WARN admin={bg=tls-config} linkerd2_fs_watch::inotify watch error: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }, polling the fs until next change
```

## Steps to reproduce

```bash
git checkout siggy/bump-all-the-dockers
DOCKER_TRACE=1 bin/docker-build
bin/linkerd install --tls optional | kubectl apply -f -
bin/linkerd logs
```

First reported at https://github.com/linkerd/linkerd2/pull/2241#discussion_r258260696

**Comment by hawkw** [comment]
It looks like this has been observed on stable-2.2 (see #2345) so I'm not convinced it's caused by switching from `jessie` to `stretch`?

**Comment by klingerf** [comment]
@hawkw You're correct. I just verified that these warnings show up in the linkerd-proxy logs of the control plane components of a stable-2.2.1 deployment with TLS enabled on GKE. Am not seeing the corresponding increase in memory, however, as reported in #2345. And interestingly, I don't see these warnings when deploying demo to the same cluster -- in my case the warnings only show up in the control plane proxies.

**Comment by hawkw** [comment]
linkerd/linkerd2-proxy#195 fixes this; we'll have to investigate whether or not this resolves the memory leak as well.
