### ISSUE TITLE
Tap start button remains disabled even if new resource is selected

### ISSUE THREAD

**Issue by scottcarol** [linkerd/linkerd2#2347]
### What is the issue?

If you run a Top query on a resource that does not return data, the buttons will be disabled even if you choose a new resource. An Unexpected close error also occurs in the terminal.

### How can it be reproduced?

From Web UI, click Top. 
Enter a namespace (default) and a resource (statefulsets) that will not load data. Click 'Start'. The buttons will be disabled (expected) but will stay disabled if you choose a new resource (unexpected). You have to reload the page to make a new query.

### Logs, error output, etc

In the terminal:
ERRO[0025] Unexpected close error: websocket: close 1011 (internal server error): no pods found for statefulset/

#### `linkerd check` output

```text
Status check results are √
```

### Environment

- Kubernetes Version: v1.10.11
- Linkerd version: Client version: edge-19.2.4
Server version: edge-19.2.4

### Context

May be related to #1679

**Comment by scottcarol** [comment]
@liquidslr is interested in working on this!

**Comment by klingerf** [comment]
If I remember correctly, this issue is related to websockets, and it may require some investigation on the web server side as well, to verify that we're properly conforming to the websocket spec, so that browsers handle our responses properly.

**Comment by grampelberg** [comment]
@liquidslr any pointers that'd help?

**Comment by liquidslr** [comment]
@grampelberg i did a bit of debugging, checkout the conversation in the pr
