### ISSUE TITLE
port-forward traffic skips the proxy

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#2352]
### What is the issue?

Issuing requests to a service that has been exposed via `kubectl port-forward` skips the proxy entirely. This makes testing service profiles a little challenging as it takes some effort to 

### How can it be reproduced?

Run `port-forward` and `tap`, see that requests sent to `localhost` do not show up in tap. Verified via tcpdump.

**Comment by olix0r** [comment]
Is the only solution to this to change the iptables behavior to intercept port-forwards? Or is it suitable to provide better debugging tools (i.e. #2199 ) that can exercise proxy behavior without port-forward?

**Comment by grampelberg** [comment]
@olix0r I would like to be able to generate load for a service from my local computer and have that show up in stats. We could (and should) build out other debugging tools. 

I think the core of this is that `port-forward` *doesn't* go through the proxy and so if you're doing some manual testing the way you've done it before, nothing appears to work. We'll need to add warnings/alerts into the dashboards and docs to make sure folks have their expectations set correctly.

fwiw, I'm not 100% sure it would be possible as I'm not clear on how `port-forward` works under the covers and `tcpdump` shows localhost as the source.
