### ISSUE TITLE
Check kubectl version 

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#2354]
### What problem are you trying to solve?

It is common for users to have kubectl be out of sync with their cluster. `linkerd check` should look at the local kubectl version as well as the cluster.

**Comment by hpandeycodeit** [comment]
@grampelberg I am interested in working on this one.  `linkerd check` to check the versions and tell the users that it's in sync or not?

**Comment by grampelberg** [comment]
@hpandeycodeit looks like @yb172 beat you to it with https://github.com/linkerd/linkerd2/pull/2358. Are you interested in small issues like this? I'll be creating a bunch this week and would be happy to ping you!

**Comment by hpandeycodeit** [comment]
@grampelberg oh no :( 
No worries then and yeah I will be happy to work if there are more issues.
