### ISSUE TITLE
CNI configuration is not cleaned up on deletion

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#2355]
### What is the issue?

Removing the CNI DaemonSet from my cluster does not clean the plugin or configuration up.

### How can it be reproduced?

```bash
linkerd install-cni --dest-cni-bin-dir /home/kubernetes/bin | kubectl delete -f -
```

### Logs, error output, etc

(If the output is long, please create a [gist](https://gist.github.com/) and
paste the link here.)

#### `linkerd check` output

```text
your output here ...
```

### Environment

- Kubernetes Version: 1.12.5-gke.5
- Cluster Environment: GKE
- Host OS: COS
- Linkerd version: stable-2.2.0

**Comment by siggy** [comment]
FWIW I've observed this working sometimes but not all the time. In the failed cases the pod just exits before `cleanup()` executes.

Here's output from a success cleanup:
```bash
$ kubectl -n linkerd logs -f pod/linkerd-cni-8qgc7
Wrote linkerd CNI binaries to /host/opt/cni/bin
Using CNI config template from CNI_NETWORK_CONFIG environment variable.
      "k8s_api_root": "https://__KUBERNETES_SERVICE_HOST__:__KUBERNETES_SERVICE_PORT__",
      "k8s_api_root": "https://10.96.0.1:__KUBERNETES_SERVICE_PORT__",
CNI config: {
  "name": "linkerd-cni",
  "type": "linkerd-cni",
  "log_level": "info",
  "policy": {
      "type": "k8s",
      "k8s_api_root": "https://10.96.0.1:443",
      "k8s_auth_token": "__SERVICEACCOUNT_TOKEN__"
  },
  "kubernetes": {
      "kubeconfig": "/etc/cni/net.d/ZZZ-linkerd-cni-kubeconfig"
  },
  "linkerd": {
    "incoming-proxy-port": 4143,
    "outgoing-proxy-port": 4140,
    "proxy-uid": 2102,
    "ports-to-redirect": [],
    "inbound-ports-to-ignore": [4190,4191],
    "outbound-ports-to-ignore": [],
    "simulate": false
  }
}
Created CNI config /host/etc/cni/net.d/10-default.conflist
Done configuring CNI. Sleep=true


SIGTERM received, simply exiting...
Removing linkerd-cni artifacts.
Removing linkerd-cni config: /host/etc/cni/net.d/10-default.conflist
Removing linkerd-cni kubeconfig: /host/etc/cni/net.d/ZZZ-linkerd-cni-kubeconfig
Removing linkerd-cni binary: /host/opt/cni/bin/linkerd-cni
Exiting.
rpc error: code = Unknown desc = Error: No such container: 3dab6feac73bb3772f7e341d60c945eec7f0d3967033578f86b2bc19f5db1248
```

**Comment by codeman9** [comment]
I remember this during development. It may be related to the shutdown grace period that is set in the daemonset. Right now it is on 5 seconds. Maybe we need to play with that a bit.

**Comment by grampelberg** [comment]
Should we use a `preStop` hook instead?

**Comment by codeman9** [comment]
Yes, the documentation looks promising for prestop

**Comment by codeman9** [comment]
Can you try the following to see if it helps?

in the linkerd install-cni .yaml, this goes at the same level as `volumeMounts` as part of the `install-cni` container spec.
```
        lifecycle:
          preStop:
            exec:
              command: ["kill","-15","1"]
```

That may or may not be enough. If you still see this problem, then try this:

in the install-cni.sh change the bottom where the sleeping happens to:
```
should_sleep=${SLEEP:-"true"}
echo "Done configuring CNI. Sleep=$should_sleep"
while [ "${should_sleep}" = "true"  ]; do
  sleep infinity &
  wait $!
done
```
