### ISSUE TITLE
linkerd logs emits nothing

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#2359]
```
:; bin/linkerd logs -c identity-client --control-plane-component identity
```

outputs nothing, though running kubectl manually results in logs:

```
:; kubectl logs -n linkerd -l linkerd.io/control-plane-component=identity -c identity-client
time="2019-02-23T16:33:11Z" level=info msg="running version git-09b4a0a6"
time="2019-02-23T16:33:11Z" level=fatal msg="Failed to write CSR to /var/run/linkerd/identity/end-entity/csr: open /var/run/linkerd/identity/end-entity/key: permission denied"
```

**Comment by olix0r** [comment]
I think this may actually be something related to `kubectl logs -f` -- still, it's frustrating that we can't surface these errors.

**Comment by dadjeibaah** [comment]
@olix0r Does running the command with the flag `--tail 10` result in any lines being shown?

**Comment by dadjeibaah** [comment]
I tried looking through stern's [issues](https://github.com/wercker/stern/issues) to find something related. Does this happen under certain conditions? Does this happen when containers restart?

**Comment by klingerf** [comment]
@dadjeibaah I actually think it's dependent on the cluster. Testing on docker-for-mac, I don't see this issue, but it's definitely a problem on GKE.
