### ISSUE TITLE
How i can uninstall it completely ?

### ISSUE THREAD

**Issue by budim12** [linkerd/linkerd2#2373]
## Feature Request
I just install it, and i just trial this, i just wanna know what feature it have, and after that i want to remove this, how i could completely remove this tools ?

### What problem are you trying to solve?
Uninstall this tool..

### How should the problem be solved?
Some link that clear and easy to understand..

What do you want to happen? Add any considered drawbacks.

### Any alternatives you've considered?
not yet..

Is there another way to solve this problem that isn't as good a solution?

### How would users interact with this feature?
People can try it's feature, but maybe, just wanna try, not need this yet..

If you can, explain how users will be able to use this. Maybe some sample CLI
output?
some information, maybe..

**Comment by budim12** [comment]
`kubectl get deploy -o yaml | linkerd uninject - | kubectl apply -f -`
is it enough ?

**Comment by grampelberg** [comment]
@budim12 

```bash
$ kubectl get deploy -o yaml | linkerd uninject - | kubectl apply -f -
$ linkerd install | kubectl delete -f -
```

**Comment by hdnebat** [comment]
after running command "linkerd install | kubectl delete -f -"
I received:
Linkerd has already been installed on your cluster in the linkerd namespace. Please run upgrade if you'd like to update this installation. Otherwise, use the --ignore-cluster flag.
No resources found

what is missing here?

**Comment by klingerf** [comment]
@hdnebat Did you try using the `--ignore-cluster` flag as suggested in the help text? This works for me:

```
linkerd install --ignore-cluster | kubectl delete -f -
```
