### ISSUE TITLE
proxy: expose http/2 flow control metrics

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#2374]
Application owners don't have great visibility into when the linkerd proxy's flow control is throttling a stream. We should devise a metric that gives users a tool to understand windowing/flow control/throughput.

**Comment by grampelberg** [comment]
@olix0r do you have an example of flow control doing something?

**Comment by olix0r** [comment]
@grampelberg flow constraints how much data can be in-flight on a given connection/stream. If a client is sending data faster than a receiver can consume it, flow control is the mechanism that puts backpresure on the sender.  It's an important part of debugging "why is this slow?" or "why isn't anything happening?"

**Comment by grampelberg** [comment]
Sounds like something that should go into #2271

**Comment by olix0r** [comment]
We need this in order to debug issues properly.

For each h2 client and server connection we need a means to detect when the connection's recv/send windows are exhausted. Each time the window is fully exhausted, we should increment a counter.

Similarly, we should be able to track stream window exhaustion.

**Comment by hawkw** [comment]
It looks like this will require some plumbing through `h2`/`tower-h2`?

**Comment by hawkw** [comment]
Quick question about cardinality (cc @olix0r):

> For each h2 client and server connection we need a means to detect when the connection's recv/send windows are exhausted. Each time the window is fully exhausted, we should increment a counter.

For this data to be actually useful, we would definitely need to have a counter for every individual connection, as you said. That could result in a pretty high cardinality metric — for every connection through the proxy, we would have 4 metrics (`{client, server} x {recv, send}`).  If we also track the same set of metrics for each stream, this could be a _lot_ of metrics indeed.

To reduce load on Prometheus, do we want to have these metrics be disabled by default (either in the proxy, or in prometheus)?

**Comment by hawkw** [comment]
Re: what metrics to record: In addition to counting the number of times a window was exhaused, do we also want to consider having gauges of current window size/capacity, and/or how much data is currently buffered?

**Comment by olix0r** [comment]
@hawkw i think we're talking about 4 counters per client/server (most of which will likely always be 0).

But, before we focus on the proxy's export, it's probably more important to figure out how to surface these counters from clients/servers at all.

**Comment by hawkw** [comment]
AFAICT this is still relevant?

**Comment by olix0r** [comment]
I don't think this is particularly important at this point. We can reopen the issue if we have a clearer story around it.
