### ISSUE TITLE
Controller debug logging leaks serviceaccount secrets

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#2383]
Our new control debug logging is great, but unfortunately it leaks the service account tokens into the logs.
```
linkerd linkerd-controller-84c45ff48b-gqjfz destination I0226 03:06:39.834301       1 round_trippers.go:419] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: destination/v0.0.0 (linux/amd64) kubernetes/$Format" -H "Authorization: Bearer eyJhb__BIG_LONG_JWT_sdqQ" 'https://10.152.183.1:443/apis/apps/v1beta2/replicasets?resourceVersion=413498&timeout=7m7s&timeoutSeconds=427&watch=true'
```

This makes it difficult for us to ask for users to send us control plane debug logs, and is especially sensitive for the linkerd-ca (and soon linkerd-identity) services.

**Comment by olix0r** [comment]
It appears that there should be a way to disable this logging:

https://github.com/kubernetes/kubernetes/blob/d262343acdabf585d889a2e51034061a6b24f176/staging/src/k8s.io/client-go/transport/round_trippers.go#L418-L421

**Comment by olix0r** [comment]
It appears that, in order to log URLs or responses with klog, one must also log request headers, which include the `Authorization`.

https://github.com/kubernetes/kubernetes/blob/7a4496429d7965f3b9ef7df86d91b294b8d77eb2/staging/src/k8s.io/client-go/transport/round_trippers.go#L68-L81

Honestly, I don't think we can/should include these logs with our debug logs. Our application's debug logging should be really helpful to have us debug issues. Mixing that up with the control plane's secrets complicates things, makes it hard for us to ask users to "just turn on debug logging."

I think, for now, we should change the behavior so that the debug logging flag does not log secrets. If we really want to be able to log the full k8s api details, I think we should introduce a new flag for users that tells them they're dumping secrets into their logs.

**Comment by dadjeibaah** [comment]
That makes sense and I agree, based on the link you posted, the best debug log level to achieve this would be `6`. I can create a new issue that addresses the k8s API flag.

**Comment by olix0r** [comment]
@dadjeibaah i'd hold off on that for now. i'm about to push a pr for this change. we can revisit higher verbosity if we ever actually find a need for it...

**Comment by olix0r** [comment]
With lesser logging, we get lines like:

```
I0226 18:02:35.191129       1 round_trippers.go:438] GET https://10.152.183.1:443/api/v1/endpoints?limit=500&resourceVersion=0 200 OK in 13 milliseconds
I0226 18:02:35.192327       1 round_trippers.go:438] GET https://10.152.183.1:443/api/v1/services?limit=500&resourceVersion=0 200 OK in 15 milliseconds
I0226 18:02:35.192684       1 round_trippers.go:438] GET https://10.152.183.1:443/api/v1/pods?limit=500&resourceVersion=0 200 OK in 17 milliseconds
I0226 18:02:35.197125       1 round_trippers.go:438] GET https://10.152.183.1:443/api/v1/services?resourceVersion=442385&timeout=9m42s&timeoutSeconds=582&watch=true 200 OK in 0 milliseconds
I0226 18:02:35.198274       1 round_trippers.go:438] GET https://10.152.183.1:443/api/v1/endpoints?resourceVersion=442621&timeout=8m19s&timeoutSeconds=499&watch=true 200 OK in 0 milliseconds
I0226 18:02:35.198911       1 round_trippers.go:438] GET https://10.152.183.1:443/apis/apps/v1beta2/replicasets?limit=500&resourceVersion=0 200 OK in 24 milliseconds
I0226 18:02:35.204323       1 round_trippers.go:438] GET https://10.152.183.1:443/api/v1/pods?resourceVersion=442629&timeout=7m11s&timeoutSeconds=431&watch=true 200 OK in 0 milliseconds
I0226 18:02:35.213261       1 round_trippers.go:438] GET https://10.152.183.1:443/apis/apps/v1beta2/replicasets?resourceVersion=442426&timeout=7m7s&timeoutSeconds=427&watch=true 200 OK in 0 milliseconds
```
which probably seems sufficient for our immediate needs.
