### ISSUE TITLE
proxy: Expose stream concurrency limit settings

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#2390]
The proxy should accept a configuration that controls the default value of `SETTINGS_MAX_CONCURRENT_STREAMS` for the inbound routerr. Probably `LINKERD2_PROXY_INBOUND_MAX_CONCURRENT_STREAMS`.

**Comment by seanmonstar** [comment]
This mentions the inbound router, is that supposed to mean the capacity (that's mentioned in #2405)? Or specifically the HTTP2 setting?

**Comment by hawkw** [comment]
@seanmonstar I believe this is referring specifically to the HTTP2 setting.

**Comment by seanmonstar** [comment]
FWIW, in Rust's `h2` case, this would be to reduce the limit, since the HTTP2 spec says that without specifying this setting, there is no limit set, and `h2` doesn't set a default.

**Comment by olix0r** [comment]
@seanmonstar okay, if we don't configure a stream limit within our stack, then this can be closed and we should focus (in another issue) on altering the destination service's default, which I (perhaps incorrectly?) is limited at 100.
