### ISSUE TITLE
Create manual helm chart

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#2402]
### What problem are you trying to solve?

We're slowly working on getting `install` to use an actual helm chart. Unfortunately, #2385 is currently blocking the process. This is because the control plane has proxies injected and the only way to inject proxies currently is via the `inject` code which isn't usable from helm.

### How should the problem be solved?

In the mean time, there's no reason why the current templates, https://github.com/linkerd/linkerd2/tree/master/chart can't be used. They'll just need to have the proxy manually added to the YAML. This new chart can then be submitted as a PR to https://github.com/helm/charts for use by anyone.

**Comment by grampelberg** [comment]
See https://github.com/helm/charts/blob/master/CONTRIBUTING.md#technical-requirements for the full requirements. Sounds pretty reasonable based off what's there today.

**Comment by cohix** [comment]
Injecting the sidecars "manually" for now seems like a good stop-gap to me. 

In the future, it feels like [helm post-install hooks](https://github.com/technosophos/k8s-helm/blob/master/docs/charts_hooks.md) would be a decent solution to run the inject code after the control plane pods come up.

**Comment by grampelberg** [comment]
I hadn't even thought of that, good suggestion! Another possibility would be to use a `pre-install` hook that adds the injector before the rest of the control plane components are added. That way we'd not run into any weird identity bootstrapping issues. @olix0r you're in the trenches there right now, what do you think?
