### ISSUE TITLE
Move section titles of Web UI into tables to conserve space

### ISSUE THREAD

**Issue by scottcarol** [linkerd/linkerd2#2403]
From comments for #2297 by @siggy and @rmars:

The section titles in the web UI should be moved into the tables themselves to conserve space. 

> I think we can move the section titles into the tables and that would make the space less... spacious!
> for the tabs, it might be worth just repeating the table names; otherwise the tabs will be confusing

_Originally posted by @rmars in https://github.com/linkerd/linkerd2/pull/2297_

Currently the filter feature adds extra space: 

![extra space](https://user-images.githubusercontent.com/2289389/53509918-b2fab100-3a71-11e9-96bb-59c7623c3493.png)

**Comment by gaurav9825** [comment]
@scottcarol  if possible would love to work on this issue

**Comment by scottcarol** [comment]
Hey @gaurav9825! This issue will build on the UI changes I'm making in PR #2297. That PR is still being reviewed and I'm incorporating feedback - once it's merged you can definitely grab this issue!

**Comment by gaurav9825** [comment]
Sure thank you !

**Comment by scottcarol** [comment]
Hey @gaurav9825 we ended up resolving this in PR #2297 so I'm going to close this issue. If you're interested in other UI issues let me know!

**Comment by liquidslr** [comment]
@scottcarol I would love to, meanwhile  I have myself looked into some issues and will be making pr's for the same in some time
