### ISSUE TITLE
proxy: Replace router eviction strategy

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#2405]
The proxy current implements a router with a fixed maximum capacity. Each time a request is dispatched to a service, the service is marked with at timestamp. When the router's capacity is full, the oldest, idle services are removed to create new capacity.

This has some drawbacks. For one, we only teardown routes once the capacity is full, rather than letting them idle-out after a time-period.

Can we modify the router to take advantage of Rust lifetimes?  I'm imagining that the router would wrap each route with a middleware that does a similar time-stamping strategy, but drops the route when it idles out (so that all of it's associated resources are released). This strategy would need to be configurable (i.e. when constructing the router), as it doesn't make sense to do this eviction on, for instance, profile routes.

**Comment by kleimkuhler** [comment]
I'd like to start getting some eyes on the cache prototype. I have it pushed up as a separate project [here](https://github.com/kleimkuhler/tec) for the time being.

There are several design decisions similar to the current cache implementation. The big difference is the introduction of using [tokio::timer::DelayQueue](https://docs.rs/tokio/0.1.17/tokio/timer/struct.DelayQueue.html) to maintain cache value expirations.

This allows us to continue wrapping cache value in [Access](https://github.com/linkerd/linkerd2-proxy/blob/6cc755881994cba967619a0999dd7b2339c986e2/lib/router/src/cache.rs#L58) handles, and space for reserving values in [Reserve](https://github.com/linkerd/linkerd2-proxy/blob/6cc755881994cba967619a0999dd7b2339c986e2/lib/router/src/cache.rs#L58) handles.

What we are able to do now is spawn a background purge task that attempts to purge cache values that have expired. This background task has a lower priority on locking the cache than the [Container](https://github.com/kleimkuhler/tec/blob/66f5f778a148c50afc3dcfa89d49ed2df2448540/src/container.rs#L46) which represents an object such as a router.

For situations where we _do not_ want to background purge cache values, we would just not spawn the [PurgeCache](https://github.com/kleimkuhler/tec/blob/66f5f778a148c50afc3dcfa89d49ed2df2448540/src/container.rs#L59) on the runtime. Cache eviction would only take place when the cache has reached its capacity -- similar to how we currently handle this situation.

**Comment by kleimkuhler** [comment]
After some further discussion, we're going to investigate a simpler solution for expiring endpoints.

In Tower, we can create a new `Idle` layer that wraps an inner service and has an associated expiration. If no request arrives within the expiration, we drop the inner service and all calls to `fn poll_ready` will return `Err`. When a request does arrive within the time period, we reset the expiration and pass along the request.

Then, if we wrap `Idle` with a `Reconnect` layer (e.g. `Reconnect<Idle<...>>`), it will result in reconnecting idle connections after they have been dropped.

**Comment by kleimkuhler** [comment]
Closed in linkerd/linkerd2-proxy#247
