### ISSUE TITLE
Implement stable sort for web UI 

### ISSUE THREAD

**Issue by scottcarol** [linkerd/linkerd2#2413]
Currently we are using the native JavaScript `sort()` method to sort columns in our web UI. This leads to unexpected behavior when a table is re-rendered, where order of the rows may not be preserved in `BaseTable` despite no change to the `orderBy` or `order` values.

Proposed solution: 

Switch from native `sort` to Lodash `_sortBy` which is a stable sort. Rewrite the `sorter()` methods in `MetricsTable` and other corresponding components, so that instead of returning a `compareFunction` they simply return the value to sort by.

Example:

```sorter: d => d.name```

Then in the `BaseTable` function use:

```rows = _sortBy(tableRows, [row => row.sort()]]);```

This would be a lot of line changes to `MetricsTable` and the other table components but I think it would switch everything to stable sorting.

@rmars @siggy thoughts welcome!

Screenshots:

Initial view

<img width="1148" alt="prechange" src="https://user-images.githubusercontent.com/2289389/53536248-756e4600-3aba-11e9-8124-2e237bf25698.png">

After state change (clicking the filter button, no change to data)

<img width="1161" alt="postchange" src="https://user-images.githubusercontent.com/2289389/53536252-7901cd00-3aba-11e9-8b6b-47529a06a3bb.png">

**Comment by liquidslr** [comment]
Hey @scottcarol I would like to work on this issue

**Comment by scottcarol** [comment]
Hi @liquidslr! So glad you're interested in the UI! I'm sorry for being unclear, I created this issue with a proposed solution and am asking for feedback on it from others before implementing it. I should have assigned it to myself - doing that now! Have you seen #2347? I would love to assign that to you if you are interested in jumping in.

**Comment by liquidslr** [comment]
Sure 👍

**Comment by scottcarol** [comment]
Awesome @liquidslr, am assigning that one to you now!

**Comment by scottcarol** [comment]
Oops, I seem to not have that administrative ability to assign it to you! But if you'd like to take that one and begin work on it that would be ⭐️ ⭐️ ⭐️
