### ISSUE TITLE
gRPC kubernetes load balancer

### ISSUE THREAD

**Issue by previousdeveloper** [linkerd/linkerd2#2417]
How to make gRPC kubernetes load balancer integration with linkerd ? We couldn't make well. Is there any enough doc ?

**Comment by klingerf** [comment]
Hey @previousdeveloper, check out the [Getting Started guide](https://linkerd.io/2/getting-started/), which walks you through installing Linkerd and and a demo application that uses gRPC. Linkerd will work seamlessly with your existing gRPC clients and servers. If you have questions after completing the Getting Started guide, please ask in the [Linkerd slack](https://slack.linkerd.io/); we use GitHub for feature requests and bug reports only.

**Comment by klingerf** [comment]
Ah, and I forgot that there's also a thorough blog post about this topic on the Kubernetes blog, here: https://kubernetes.io/blog/2018/11/07/grpc-load-balancing-on-kubernetes-without-tears/
