### ISSUE TITLE
Mark High Availability as non-experimental

### ISSUE THREAD

**Issue by jonrichards** [linkerd/linkerd2#2419]
### What is the issue?
The help text for `linkerd install` shows HA as experimental. The website (https://linkerd.io/2/features/ha/) also shows it as experiemental.
### How can it be reproduced?
Run `linkerd install -h`.
Visit https://linkerd.io/2/features/ha/.

# Environment
- Linkerd version: 2.2.1

### Possible solution
Remove phrasing for "experimental".

**Comment by BK1603** [comment]
I'd like to help with this one!

**Comment by klingerf** [comment]
@jonrichards Thanks for kicking this off. The `--ha` flag is marked as experimental because we've been waiting for feedback from users that it's working for them. Can you provide more info of how it's working in your setup. I know there are a few other issues that we might want to address (e.g. #1895, #2392) before fully graduating `--ha` from experimental.

**Comment by jonrichards** [comment]
@klingerf no worries, I think it's just me and @grampelberg getting a bit ahead of things. Those 2 issues look like good ones to go along with HA coming out of experimental. So far running in HA mode has been fine on my end, but I haven't done any explicit testing of HA itself, just implicitly via other testing we're doing. I'll look to get some HA specific testing here and provide any feedback on that.

**Comment by wmorgan** [comment]
I think we need a call here from @grampelberg or others. Comments above suggest that we need to address #1895 and #2392 before moving  `--ha` out of experimental. Is that correct? Is that the complete list of necessary issues?

**Comment by olix0r** [comment]
@wmorgan that's right. "Experimental" might be a misleading term for `--ha` -- its configuration is definitely _more_ highly available and production ready than the default installation, but there's more work we feel we need to do before we can really consider the control plane highly available.

**Comment by jonrichards** [comment]
I've been running `--ha` on several clusters for a while now largely without any issue. However, I did run into an issue the other day where I was rotating my nodes one at a time for an upgrade, and I had pods come up on another node before some components of linkerd did and they missed being auto-injected. As expected, cycling the pods brought them back up injected with the linkerd proxy.

[#1895](https://github.com/linkerd/linkerd2/issues/1895) would largely resolve that I think, but aside from that I've not run into any other issues when running with `--ha`

**Comment by klingerf** [comment]
@jonrichards Thanks for the update. And we're actually now in a place that we can fix the auto-injector issue that you saw. Last week @ihcsim merged #2806, which will allow us to run more than one replica for the proxy-injector deployment. To date we've been hardcoding that deployment to a single replica, even in HA mode. I created #2873 to track that, and coupled with #1895, it should ensure that there's no downtime for the auto-injector when restarting nodes.

**Comment by jonrichards** [comment]
@klingerf That's great to hear. I'll track this for when it gets into an `edge` release and I can help out with re-testing the scenario I ran into.
