### ISSUE TITLE
Order of tables changing unexpectedly in Top Routes Web UI view

### ISSUE THREAD

**Issue by scottcarol** [linkerd/linkerd2#2420]
### What is the issue?

Originally spotted by @rmars. 

In the newest edge release (19.2.5) if you have booksapp installed, go to http://localhost:8084/routes?namespace=default&resource_type=deployment to get to the Top Routes page on the web UI. Click "Start" and wait for a few seconds, you'll see the order of the deployment tables (books, authors, etc.) change.

I haven't looked back at previous releases to see when this originated.

Linkerd versions:
Client version: edge-19.2.5
Server version: edge-19.2.5

**Comment by scottcarol** [comment]
Ok, just checked and this is happening in the stable release 2.2.1 as well. Good 👁 @rmars!

**Comment by liquidslr** [comment]
![screenshot 2019-03-03 at 2 47 21 am](https://user-images.githubusercontent.com/26876811/53687832-b6d34f80-3d5f-11e9-98c4-717ee2e6d61f.png)
![screenshot 2019-03-03 at 2 54 00 am](https://user-images.githubusercontent.com/26876811/53687833-bdfa5d80-3d5f-11e9-9c64-0c1a1a8a5369.png)

@scottcarol i tried to recreate the issue following the above steps, although i did'nt noticed any change in order but i did notice that the number of authors and books chaged after clicking on start , is this the issue ?

**Comment by scottcarol** [comment]
Hi @liquidslr, thanks for checking this out! The issue I'm seeing is the specific tables switching positions when you're on the Top Routes page on the Linkerd dashboard. That's interesting that you're not seeing it - what version of Linkerd are you running currently?

**Comment by liquidslr** [comment]
Currently, I am using 
Client version: git-21849288
Server version: git-21849288

**Comment by rmars** [comment]
Hey @liquidslr! So the screenshot you've sent is of the books demo app. The sorting issue is in the linkerd dashboard, which you can access by running a `linkerd dashboard` in the terminal, and then going to `/routes`. (You'll then need to make a routes query, which, if you're running the books app, could be something like selecting the `default` namespace and then selecting `deployment` as the resource in the form.

This is the page you'll want:
<img width="1204" alt="screen shot 2019-03-04 at 12 46 11 pm" src="https://user-images.githubusercontent.com/549258/53751988-91d3ff00-3e7b-11e9-8e6d-f575ad1d3af1.png">

You can also look at the instructions in [BUILD.md](https://github.com/linkerd/linkerd2/blob/master/BUILD.md) for how to run the dashboard locally, which you'll need for developing!

**Comment by liquidslr** [comment]
Oh thanks for the update @rmars, I'll take a look I have a working development setup.

**Comment by scottcarol** [comment]
@liquidslr Hi! Were you able to replicate the original issue? If so I have some suggestions for you to try!

**Comment by liquidslr** [comment]
No i was not able to reproduce the issue, one of the reason being whenever i deploy the books app on my local machine the linkerd dashboard becomes extremely slow and it starts to give Internal server error (500) every time i do some activity in the dashboard.

**Comment by scottcarol** [comment]
Hey @liquidslr thanks for the update. Have you been able to use the linkerd dashboard with the emojivoto app or have both apps produce the same behavior?

**Comment by liquidslr** [comment]
No emojivoto is working just fine, the problem only comes after I install books app

**Comment by liquidslr** [comment]
@scottcarolI I was finally able to reproduce the issue, any suggestions you have for me to proceed further?

**Comment by scottcarol** [comment]
@liquidslr Thanks for your persistence! My hunch is that `results` in line 46 of TopRoutesModule.jsx:
```
let results = _get(data, '[0].ok.routes', []);
```
may need to be sorted by resource. That's where I'd start first.
