### ISSUE TITLE
Proxy Injector Webhook Not Updated During Version Upgrade

### ISSUE THREAD

**Issue by ihcsim** [linkerd/linkerd2#2425]
### What is the issue?
During a version upgrade from 2.2.1 to 19.2.5, the proxy injector MWC doesn't pick up the latest configurations. The only configuration that is [updated is the CA bundle](https://github.com/linkerd/linkerd2/blob/4cd1f99e89691c1544d796c0d599d477e52fe030/controller/proxy-injector/webhook_config.go#L104), to ensure the CA bundle in the MWC is the same with that in the CA controller (prior to #2163).

### How can it be reproduced?
Perform a version upgrade from stable 2.2.1 to 19.2.5 with the `--proxy-auto-inject` flag enabled for both installations.

### Logs, error output, etc
No errors.

### Environment

- Kubernetes Version: 1.13.2
- Cluster Environment: Minikube
- Host OS: Ubuntu 16.04
- Linkerd version: 2.2.1 and edge 19.2.5

### Possible solution
Recreate the MWC during a version upgrade.

**Comment by grampelberg** [comment]
@ihcsim if I understand correctly, anyone running 2.2 upgrading to the eventual 2.3 won't get the MWC?

**Comment by ihcsim** [comment]
That's correct. Shall we roll a stable-2.2.2 to include this fix then? Alternately, users can also manually update the MWC with `kubectl edit`.

**Comment by grampelberg** [comment]
I assume we'll have that fixed before 2.3 comes out though? If there's a manual way to do it, putting the steps into the upgrade instructions is alright as well.

**Comment by klingerf** [comment]
I also wanted to mention that this relates to #2176. If we move the MWC to the install YAML, then the proxy-inject won't need to create it on startup. See #2176 for implementation details, though.

**Comment by grampelberg** [comment]
Ahhha, that helps me understand what was going on, thank you @klingerf !
