### ISSUE TITLE
proxy: Replace bounded futures::mpsc with tokio_sync::mpsc

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#2435]
The proxy's channels (at least the bounded ones) should be changed to use <s>futures</s>tokio_sync::mpsc, because the latter implements the desired backpressure semantics when cloned.

**Comment by hawkw** [comment]
It would be nice to do some before/after benchmarking as well. I'd be curious to see if there's a noticeable perf impact.

**Comment by zaharidichev** [comment]
I wanted to try and give that one a go but I am struggling understanding the following two things: 

1. Should futures::mpsc be replaced with tokio::sync::mpsc (as stated in the title) or the other way around as stated in the comment:) 
2. @hawk mentions before/after benchmarking. Is that running some cpecific benchmarks that are already written (if yes, which ones) or writing some new benchmarks

Thanks for the help in advance

**Comment by hawkw** [comment]
@zaharidichev 
>     1. Should futures::mpsc be replaced with tokio::sync::mpsc (as stated in the title) or the other way around as stated in the comment:)

The proxy is currently using `futures::sync` channels, and they should be replaced with `tokio::sync` channels. I believe the comment is a typo.

>     2. @hawkw mentions before/after benchmarking. Is that running some cpecific benchmarks that are already written (if yes, which ones) or writing some new benchmarks

I don't think new benchmarks should be necessary, though I hadn't put too much thought into which specific benchmarks should be run. I think the proxy performance benchmarks at https://github.com/linkerd/linkerd-examples/tree/master/perf-baseline are probably a good starting point, though I've observed fairly significant variability between runs using those --- it might be necessary to compare several before/after runs.

**Comment by hawk** [comment]
I suppose that this message was intended for somebody else.

/Github user "hawk"

**Comment by hawk** [comment]
I suppose that this message was intended for somebody else.

/Github user "hawk"

**Comment by Shoowa** [comment]
Is this issue still open? I felt confused after reading the final message in the conversation from the related pull-request that was closed.

**Comment by hawkw** [comment]
The final comment in the linked PR https://github.com/linkerd/linkerd2-proxy/pull/207#issuecomment-567169144 means that the change from `futures::sync` to `tokio::sync`'s MPSC channel has happened gradually over time --- this issue is quite old, and I'm fairly certain there are no more remaining uses of `futures::sync::mpsc` in the Linkerd proxy.

This issue should probably be closed.
