### ISSUE TITLE
Seeing a lot of linkerd2_proxy::proxy::http::router errors in linkerd-web proxy logs

### ISSUE THREAD

**Issue by bourquep** [linkerd/linkerd2#2446]
### What is the issue?

I have upgraded to `edge-19.2.5` this morning. Since then, I'm seeing this error in the proxy logs of the `linkerd-web` pod (logged once per minute on average):

```
ERR! proxy={server=in listen=0.0.0.0:4143 remote=10.244.3.1:47000} linkerd2_proxy::proxy::http::router service error: an IO error occurred: Connection reset by peer (os error 104)
```

### How can it be reproduced?

Not sure. I did run `linkerd dashboard` after upgrading to `edge-19.2.5`, to make sure everything was working properly. But I since killed the `linkerd dashboard` process and closed the dahsboard browser tab.

#### `linkerd check` output

```text
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version

linkerd-existence
-----------------
√ control plane namespace exists
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-api
-----------
√ control plane pods are ready
√ control plane self-check
√ [kubernetes] control plane can talk to Kubernetes
√ [prometheus] control plane can talk to Prometheus

linkerd-service-profile
-----------------------
√ no invalid service profiles

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ control plane is up-to-date
√ control plane and cli versions match

Status check results are √
```

### Environment

- Kubernetes Version: 1.11.5
- Cluster Environment: AKS
- Host OS:
- Linkerd version: edge-19.2.5

### Additional context

This does not interfere with normal Linkerd operation, just something odd that I am observing in the logs.

**Comment by olix0r** [comment]
Thanks for letting us know, @bourquep. My guess is that these are benign socket errors -- 'connection reset by peer' is likely to happen when you close the dashboard, for instance. We should investigate, though, to determine whether we expect to handle this error elsewhere or whether this logging should be downgraded from error to debug.

**Comment by hawkw** [comment]
See also https://github.com/linkerd/linkerd2/issues/1462
