### ISSUE TITLE
CLI Inject With Proxy Config Overrides Annotations

### ISSUE THREAD

**Issue by ihcsim** [linkerd/linkerd2#2447]
Provide a mechanism to override the configurations of a proxy during `linkerd inject`. By default, if no flags are provided, the proxy will inherit the configurations specified in the `linkerd-config` config map during CLI inject. If present, the config flags should be converted into annotations on the pod spec before being passed to the proxy-injector. The proxy-injector will then perform the configs overrides per #2287.

Depending on whether the YAML defines a single pod or a workflow resource, the CLI will have to insert the annotations at different levels (i.e. `metadata.annotations` and `spec.template.metadata.annotations`).

Depends on #2287.

**Comment by klingerf** [comment]
I just wanted to clarify that once we've added the new public API config endpoint (#2455) and updated the CLI to call that endpoint (#2434), the CLI can apply flag overrides directly to the config before calling the inject library. There won't be any need to convert the flags to annotations on the pod spec, and this change won't be blocked on needing the inject library to honor pod spec annotations (#2287).

**Comment by ihcsim** [comment]
Per discussion with @klingerf, the step to convert the CLI inject proxy options to annotations is still necessary, to ensure that subsequent updates (via `kubectl apply` etc.) don't override the existing proxy configs. The current override logic will always look for config annotations, before falling back to defaults defined in the `linkerd-config` config map.
