### ISSUE TITLE
Fix known logging errors and warnings

### ISSUE THREAD

**Issue by siggy** [linkerd/linkerd2#2453]
#2414 introduced an integration test to ensure proxy and control-plane logs do not contain unexpected errors. This test required inclusion of a list of known errors and warnings which commonly occur:
https://github.com/linkerd/linkerd2/blob/d850b02b667dfdbbf08f4dcccf2046c5165d8209/test/install_test.go#L51-L68

This ticket is intended to track tasks that eliminate these known errors.

**Comment by olix0r** [comment]
Integration tests have since changed.
