### ISSUE TITLE
Add the ability to display a contextual error banner in the web UI

### ISSUE THREAD

**Issue by rmars** [linkerd/linkerd2#2461]
As discussed here: https://github.com/linkerd/linkerd2/pull/2437#discussion_r263026524, we'd like to create a banner that will display helpful errors to the user above the page content (probably below the nav though). This would be separate from ErrorBanner.jsx, which currently displays unknown/unexpected errors.

**Comment by adrijshikhar** [comment]
@rmars is this issue still open?
i would like to work on this.

**Comment by rmars** [comment]
hi @adrijshikhar! welcome! I believe this ticket is still available, though we may want to discuss here what types of errors we would like to display, and what the scope of this ticket is (i.e. is it sufficient for this ticket to add an ErrorBanner component, and use it in a couple places in the UI? which are the helpful errors we'd like to display?)
cc @grampelberg any reason not to work on this?

**Comment by grampelberg** [comment]
This'd be awesome to work on!

**Comment by adrijshikhar** [comment]
From where i can start analysing codebase?

**Comment by adrijshikhar** [comment]
I was out for a few days, but now i am back.
I have setup the repo, can you please guide me a bit more?

**Comment by grampelberg** [comment]
@adrijshikhar please jump on slack,  there's a #contributors channel there and we can help you more from there.

**Comment by adrijshikhar** [comment]
Okk
