### ISSUE TITLE
Identity exposed in the UI

### ISSUE THREAD

**Issue by admc** [linkerd/linkerd2#2462]
@ver @grampelberg can you please define what the requirements are here.

**Comment by siggy** [comment]
Relates to #2271

**Comment by scottcarol** [comment]
@grampelberg now that we've introduced a new Identity system into the default Linkerd
installation, which identity changes should be called out visually in the UI?

cc @olix0r

**Comment by grampelberg** [comment]
@scottcarol see #2605 and #2606.

**Comment by scottcarol** [comment]
Closing because this issue has been split out in more detail: #2605 #2606 #2607 #2608
