### ISSUE TITLE
Add check for unschedulable pods

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#2465]
### What problem are you trying to solve?

On clusters, it is possible for the control plane to be unschedulable. This could be because there aren't enough resources in the cluster or there is a PSP that does not allow the pods to launch.

### How should the problem be solved?

There should be two checks added:

- Control plane pods are in pending and have events such as `no nodes available`.
- The top level resources were created but no pods have been yet, and have events blocking them (PSP issues).

Instead of showing the errors in `check`, for both of these links to the troubleshooting docs should be provided with commands that explain how to debug scheduling issues.

**Comment by liquidslr** [comment]
@grampelberg  could you please briefly explain what is actually an unschedulable pod is, I would like to work on this issue but would need a little help in getting started.

**Comment by grampelberg** [comment]
@liquidslr I don't believe a pod can have something that actually says "unschedulable" added to it, so we have to guess a little bit. The two cases that I'm aware of are:

- Cluster does not have enough resources to run the pods. Pod is created, not scheduled and has events saying that no resources are available.
- Deployments are created, pod security policy blocks creation of the pods.

**Comment by gane5hvarma** [comment]
@grampelberg hi. I would like to work on this issue.

**Comment by grampelberg** [comment]
@liquidslr are you working on this already or can @gane5hvarma take it?

**Comment by liquidslr** [comment]
@grampelberg actually I am working on this issue

**Comment by gane5hvarma** [comment]
ok then. i will look on other issue
