### ISSUE TITLE
proxy: include rust-foolchain file

### ISSUE THREAD

**Issue by hawkw** [linkerd/linkerd2#2482]
A [`rust-toolchain` file](https://github.com/rust-lang/rustup.rs#the-toolchain-file) is used to specify which Rust version should be used to build a project. 

If we include one in the proxy repo, this will make contributing to the proxy easier (especially for new contributors) by ensuring that the same Rust toolchain is used for building the proxy locally and on CI. This will help to protect against situations where branches build locally but fail on CI.

If we add such a file, we will want to ensure that it is kept in sync with the Rust versions specified in the proxy Dockerfile and Travis config. Comments there reminding anyone changing those versions to update the `rust-toolchain` file as well should be sufficient (but we may want to have a bash script to automate updating all three).

**Comment by grampelberg** [comment]
+1 to a bash script, akin to `update-go-deps-shas`.

**Comment by olix0r** [comment]
Why would we want to do this when we automatically get the latest stable from CI?

**Comment by olix0r** [comment]
Or, to put this another way: what is the advantage of pinning the version and manually having to update it when a new stable is released?

In the case of the dockerfile-- that's really just a convenience for development and it seems fine if that gets updated manually as-needed.
