### ISSUE TITLE
Access dashboard icons when offline

### ISSUE THREAD

**Issue by rmars** [linkerd/linkerd2#2489]
This is fairly minor, but when accessing the dashboard with no internet access, some of the icons (I believe the fetched fontawesome ones) show up as squares because we need to download them. 
It would be nice to either use a material ui alternative or to make the fa ones accessible offline.

<img width="239" alt="Screen Shot 2019-03-11 at 2 36 30 PM" src="https://user-images.githubusercontent.com/549258/54224762-1c5ad500-44f2-11e9-80c1-5b03cd0c120c.png">

**Comment by liquidslr** [comment]
Hey, @rmars I think that making fa stylesheet available offline would be a better option.

**Comment by supra08** [comment]
@rmars, @grampelberg,  I would like to take up this issue.

**Comment by liquidslr** [comment]
@supra08 I was working on it, was just waiting for @rmars reply

**Comment by rmars** [comment]
@liquidslr making the fa stylesheet available offline sounds good to me!

**Comment by scottcarol** [comment]
Hey @liquidslr were you still working on this issue?

**Comment by liquidslr** [comment]
yup sorry for the delay in the pr, will make it today
