### ISSUE TITLE
Add option for logging in json format

### ISSUE THREAD

**Issue by gamer22026** [linkerd/linkerd2#2491]
## Feature Request
Add the option for all the stack components to log in JSON format
### What problem are you trying to solve?
In trying to do log normalization across our stack, disparate logging formats cause extra work on the parsing end. Having all logging in JSON greatly simplifies the need to parse logs into a common format.
### How should the problem be solved?

ENV variable to enable logging in JSON format. Should be a non-default option as there may be performance penalties enabling it.
### Any alternatives you've considered?
Current way to is parse log formats to a normalized format at the receiving end (logstash in my case), which involves thing like rename fields to a common format such as severity for instance, and making sure this field value is also common, such as "error" instead of "ERR!" (which is used by the linkerd-proxy)
### How would users interact with this feature?
Log normalization makes searching (in our case using the ELK stack) easier and more consistent.

**Comment by hawkw** [comment]
See also #2157, #56

**Comment by hawkw** [comment]
The `tracing-subscriber` crate, which the proxy uses to format its logs, has a [`Json` event formatter](https://docs.rs/tracing-subscriber/0.2.5/tracing_subscriber/fmt/format/struct.Json.html) that we could sub in pretty easily to output logs in JSON.

We'd definitely to make this a configuration option of some kind (env var?), of course, because I think many folks would agree that the current output format is much more human readable when you're _not_ aggregating logs. :)

**Comment by naseemkullah** [comment]
> We'd definitely want to make this a configuration option of some kind (env var?), of course, because I think many folks would agree that the current output format is much more human readable when you're _not_ aggregating logs. :)

💯 

`LINKERD_PROXY_LOG_FORMAT` environment variable
`--proxy-log-format` CLI flag
`config.linkerd.io/proxy-log-format` annotation

**Comment by leepatrick-goop** [comment]
Plus one for this!

**Comment by hawkw** [comment]
This should be pretty straightforward to implement, so if anyone is interested in working on it (and getting the opportunity to make a proxy contribution), let me know — I'd be happy to provide pointers!

**Comment by naseemkullah** [comment]
🙋‍♂️

**Comment by hawkw** [comment]
I believe wiring the option through as an annotation/CLI command is still necessary?

**Comment by naseemkullah** [comment]
🙋‍♂️ I'd like to have a go at it (see what I did there), but it might take a few days before I get a PR in so if anyone else would like to do it before then, by all means!
