### ISSUE TITLE
Scripting friendly output for "linkerd check"

### ISSUE THREAD

**Issue by hazsetata** [linkerd/linkerd2#2503]
## Feature Request

I would like to use "linkerd check --pre" and "linkerd check" in a deployment script. It would be great to have the possibility that would enable the output to be in a scripting friendly, easy to parse format (e.g.: JSON)

### What problem are you trying to solve?

I would like to inform the users of the deployment script without "dumping" the whole "linkerd check" output into an error message (if and when "linkerd check" fail).

### How should the problem be solved?

A flag could be added to the tool, for example: "-o json".

### Any alternatives you've considered?

---

### How would users interact with this feature?

Users could specify the flag when using the CLI command.

**Comment by grampelberg** [comment]
Awesome feature request! I'd like to see this be `-o json`.

@siggy is there any way for us to have a `-o json` be standard across all the commands? Is that something that is even worth the work? Feels like `kubectl` does it, but I don't know how.

**Comment by siggy** [comment]
I agree an `-o json` feature would be useful here.

@grampelberg This is doable for `check`. Making it standard across every command would be interesting, but obviously more work.

**Comment by liquidslr** [comment]
@grampelberg  @siggy  if currently we only want it in check I can work on it!

**Comment by alenkacz** [comment]
@liquidslr I was planning to pick it up, I talked with @siggy about that yesterday but since you were the first to comment here... :)

**Comment by liquidslr** [comment]
no problem @alenkacz you can work on this I thought no one was working on it but since you are I will pick up some other issue :)

**Comment by harsh-98** [comment]
@alenkacz are you working on this?

**Comment by alenkacz** [comment]
@harsh-98 yes! no PR still though, I know :). I hope to push something out this weekend :)

**Comment by wmorgan** [comment]
The pressure increases! 😅
