### ISSUE TITLE
proxy: Integration tests for identity

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#2505]
https://github.com/linkerd/linkerd2-proxy/pull/213 introduces a new control client to an identity service. This change breaks the `outbound_http{1,2}_l5d_server_id_l5d_client_id` tests in the discovery test module, since we can't actually instrument tests that provide with the proxy with identity yet.

As we have done for the destination client, we should add a mock identity service that can be instrumented to drive tests. We should at least re-enable the above tests; though we should probably add dditional tests that ensure the proxy refreshes identity as expected.

**Comment by hawkw** [comment]
Speaking with Oliver offline, I think the first proxy tests to prioritize are:
- the `/ready` endpoint doesn't indicate readiness until the proxy's id has been certified, and
- the proxy refreshes its id as it approaches the TTL

**Comment by hawkw** [comment]
linkerd/linkerd2-proxy#228 and linkerd/linkerd2-proxy#229 add tests for the `/ready` endpoint and for identities being refreshed, respectively. 

@olix0r, is that sufficient to close this ticket, or is there more tests we ought to have in the proxy integration test suite?

**Comment by olix0r** [comment]
@hawkw it's definitely a good start! before we close this -- are there any tests we should port over from the destination service tests? i'm thinking especially of ensuring the identity client reconnects if it loses the server. I'd be fine splitting out further issues for that stuff, though.

**Comment by hawkw** [comment]
I opened #2598 and #2599 to track some additional tests we may want to have in the proxy's integration test suite.

**Comment by siggy** [comment]
@hawkw Close this when the appropriate PRs merge.
