### ISSUE TITLE
Port based service discovery

### ISSUE THREAD

**Issue by speier** [linkerd/linkerd2#2511]
## Feature Request

Support port based service discovery.

### What problem are you trying to solve?

Service talks to localhost on a port number and sidecar proxy forwards the request to a configured upstream using FQDN.

For example:
```
127.0.0.1:50500 --> myservice:80
```

### How should the problem be solved?

Add the ability to configure routing of LD2 proxy.

### Any alternatives you've considered?

It is possible with [Envoy](https://www.envoyproxy.io/docs/envoy/latest/intro/deployment_types/service_to_service), however configuration can be complex.

### How would users interact with this feature?

Ideally using standard Kubernetes resources, annotations for example.

**Comment by grampelberg** [comment]
This is an interesting issue. Service discovery is so dependent on k8s DNS right now, it doesn't work particularly well in other environments (development for example). I'm wondering whether this fits into the mesh expansion work a little bit as well.
