### ISSUE TITLE
Cleanup item: pkg/k8s/api.go has some repeated code

### ISSUE THREAD

**Issue by alpeb** [linkerd/linkerd2#2513]
There are at least three appearances of this code, that may benefit to be extracted into a separate function:

```go
rsp, err := kubeAPI.getRequest(ctx, client, path)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()
...
```

**Comment by d-baranowski** [comment]
Hello. I would like to do this. Got to start somewhere :P

**Comment by klingerf** [comment]
@d-baranowski Sounds good! I'm going to close out #2522, which was the previously submitted PR for this, which never merged. Feel free to have a look at that though to see if there's anything you can reuse.

**Comment by d-baranowski** [comment]
I had a quick dig on master and the code mentioned in this issue is no longer around. I think this can be closed.

**Comment by klingerf** [comment]
@d-baranowski 🤦‍♂ D'oh, yep, looks like this was refactored in #2747. Thanks for investigating.
