### ISSUE TITLE
Services throw 504s after serviceprofiles are deleted

### ISSUE THREAD

**Issue by adleong** [linkerd/linkerd2#2525]
Reported by ksm on the Linkerd slack:

> After having deleted all my serviceprofiles, the linkerd_proxy sidecars continue to throw `WARN linkerd2_proxy::app::profiles error fetching profile for` log messages. Is it necessary to restart the controller after removing serviceprofiles? (edited) 

> Sure, the short of it is all services that had serviceprofiles attached started throwing 504's when I deleted the serviceprofiles (and the linkerd_proxy logs started throwing the fetching error). Seems like the controller didn't pick up that the serviceprofiles were gone from kubernetes.

> Didn't see anything odd in the controller logs during this either.

> Latest edge release

(edge-19.3.2)

> K8S is 1.11.8

**Comment by gamer22026** [comment]
Just tried adding in a serviceprofile (just one) and running for a while, then deleting the serviceprofile and everything looks OK. Might be related to https://github.com/linkerd/linkerd2/issues/2382 (which as I commented I'm also experiencing).

**Comment by grampelberg** [comment]
@adleong @gamer22026 is this still an issue?

**Comment by gamer22026** [comment]
I suspect this was due to the memory leak issue https://github.com/linkerd/linkerd2/issues/2382 Haven't seen reoccur on 19.4.1.

**Comment by grampelberg** [comment]
@gamer22026 great!
