### ISSUE TITLE
rfc: Changing install & inject to support identity configuration

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#2531]
## Problem

Linkerd's new identity implementation expects that proxies are configured with trust anchors and basic identity configuration at inject-time. During installation, we must include this information in generated configuration that is stored in the control plane; and during inject, we must fetch this configuration to configure proxies.

Currently, a configuration is generated during installation, but this configuration is only read by controller pods and not by the CLI. The CLI, on the other hand, is configured entirely by CLI flags (and their defaults) to produce a set of template values used to configure proxies (for both the control plane and other injected pods).

### `install`

When `install` is invoked, it attempts to determine whether a control plane already exists in the currently configured kubernetes cluster at the CLI-specified control plane namespace.

If a configuration already exists, then the `--overwrite` flag must be specified for install.

Aside from the process global configuration (like `controlPlaneNamespace`), all of the `installOptions` will NOT be initialized with defaults. Instead, they will be empty and their values will only be considered as overrides.

Instead, the install generates a `public.config.All` with defaults specified, though notably lacking any identity configuration.

Then, the install option override and this default config are used to produce `installValues`.  First, this process updates the config types from the overrides, (including consuming/generating an identity configuration). These are all fed into an `installValues` that   satisfies the control plane templates.

#### `upgrade`

We'll probably want to add a new `upgrade` command, or add an `--upgrade` to `install`, that uses an existing controller configuration instead of generating a new one. That should happen as a follow-up, though.

### `inject`

When `inject` is invoked, it attempts to determine whether a control plane already exists in the currently configured kubernetes cluster at the CLI-specified control plane namespace.

If a configuration does not already exists, then the `--disable-identity` flag must be specified, otherwise the command fails.

Similarly, `injectOptions` are only to be considered as overrides to the controller-provided configuration. Once the config is overridden from the options, the config is used to produce `injectValues` that can be used to configure the proxy for the given resources.

**Comment by klingerf** [comment]
Thanks for writing this up. This looks like the right approach to me. Switching the install and inject flags to be override-only is going to make our CLI help text for those commands less useful, but I can't think of a good way to avoid that. Maybe down the road we can consider a `linkerd config` subcommand to print the current control plane config and (potentially) modify it without reinstalling.

**Comment by siggy** [comment]
For my own understanding, I'd like to document the user-facing install flow. Can you confirm this is how it would work?

```bash
# prior to install
cat app.yaml | linkerd inject - # fails?
cat app.yaml | linkerd inject --disable-identity - # succeeds?

# first-time install
linkerd install # includes default identify information
cat app.yaml | linkerd inject - # succeeds with control-plane identity information?

# second time install / upgrade
linkerd install # fails?
linkerd install --overwrite # includes identify information from control-plane
```

If the above is accurate, a few comments:
- I think the output of `linkerd install` should not depend on the state of the user's k8s cluster. A use case could be if a user is documenting the steps for an initial k8s cluster setup, and they want a copy of the `linkerd install` output they originally deployed, but the control-plane is already installed.
- Similar comment for `linkerd inject`. I'd prefer the output of `cat app.yaml | linkerd inject` to not change based on the state of the k8s cluster, to allow for deterministic reproduction of the original setup.

One approach to addressing this could be to print warnings to stderr at the end of the input (inject already does something like this). For example:

```
# first-time install
linkerd install
[yaml]

# second-time install
linkerd install
[yaml]
warning: it looks like you've already set up your Linkerd control-plane. you probably do not want to deploy this yaml. instead run `linkerd install --overwrite`.
```

**Comment by ihcsim** [comment]
A few questions:

Is the expected behaviour of `linkerd install --overwrite` to basically purge the existing `linkerd-config` config map, and re-create a new one, resulting in all proxies being issued new identity assets (key, cert, CA etc.)? Or the other way round to preserve the existing config map?

>  the install generates a `public.config.All` with defaults specified

Maybe just details, I'm wondering why we need to (re-)generate the `public.config.All` during install, as the install will output a new `linkerd-config` config map.

> If a configuration does not already exists, then the --disable-identity flag must be specified, otherwise the command fails.

I thought identity is mandatory. (Pretty sure I'll have a better understanding once I see your upcoming inject branch.)

As far as config annotations are concerned, it seems to me it's just a matter of doing some pre-processing while creating `installOptions` and `injectOptions` to decide whether the overrides come from the CLI flags or the annotations, right? (If true, it just means in my branch, the YAML needs to be parsed earlier, in order to pull out the annotations.)

If both CLI flags and annotations are present (for whatever reasons) in the YAML, I assume CLI flags take precedence over the annotations?

**Comment by grampelberg** [comment]
I like a lot of @siggy's points. What about simplifying this a little bit from the UX perspective.

- `linkerd install` - assumes that it will do a fresh install, fail if there's an active install detected.
- `linkerd upgrade` - do everything that is suggested here.

This way we can do hard fails and understand a user's intent instead of trying to guess it.

**Comment by olix0r** [comment]
> Maybe just details, I'm wondering why we need to (re-)generate the public.config.All during install, as the install will output a new linkerd-config config map.

we need to generate one to be stored in the config map ;)  it's mostly an impl detail that we need to do this earlier so we can properly configure identity settings.

> I thought identity is mandatory. (Pretty sure I'll have a better understanding once I see your upcoming inject branch.)

Identity is a mandatory component of the control plane. It's not mandatory that all pods participate in identity.

> If both CLI flags and annotations are present (for whatever reasons) in the YAML, I assume CLI flags take precedence over the annotations?

That seems like a good assumption...

**Comment by olix0r** [comment]
> I think the output of linkerd install should not depend on the state of the user's k8s cluster.

The alternative is that `install` will totally break meshed communication. I think it's better to optimize to safety in the typical use cases. The cases where you're running install and don't actually want to impact a cluster are pretty rare and i think requiring additional flags in these cases is a great tradeoff.

> Similar comment for linkerd inject. I'd prefer the output of cat app.yaml | linkerd inject to not change based on the state of the k8s cluster, to allow for deterministic reproduction of the original setup.

Then we can't enable identity by default. The goal of the current identity work is to enable it by default. This needs to be reconciled

**Comment by olix0r** [comment]
> > I think the output of linkerd install should not depend on the state of the user's k8s cluster.

> The alternative is that install will totally break meshed communication. I think it's better to optimize to safety in the typical use cases.

To be clear, i'm suggesting that `install` **fails** if a config already exists in kubernetes; and `install --overwrite` should be used if this config should be ignored. We won't blindly use the existing config in a new install; that needs a seperate `upgrade` command/flag

**Comment by grampelberg** [comment]
Alright, lemme walk through a full proposal with cluster states:

```bash
# prior to install
$ cat app.yaml | linkerd inject
Control plane is not running, please run linkerd install first.
$ cat app.yaml | linkerd inject --disable-identity
Control plane is not running, please run linkerd install first.
$ cat app.yaml | linkerd inject --disable-identity --ignore-cluster
deployment "vote-bot" injected

# first-time install
$ linkerd install | kubectl apply -f -
...
deployment.extensions/linkerd-web created
$ cat app.yaml | linkerd inject --verbose -
used defaults:
    linkerd-cni-enabled: true

# second time install / upgrade
$ linkerd install | kubectl apply -f -
You are already running a control plane. Please run linkerd upgrade if you would like to update.
error: no objects passed to apply
$ linkerd upgrade | kubectl apply -f -
...
deployment.extensions/linkerd-web configured
$ linkerd install --ignore-cluster
...
deployment.extensions/linkerd-web configured
```

**Comment by olix0r** [comment]
@grampelberg That looks about right to me.
