### ISSUE TITLE
Disable external profiles by default

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#2534]
Currently, profiles are enabled for all names; but, practically, this puts undue stress on the destination service when, in the majority of cases, the lookups will never yield results.

For now, let's change the default configuration so that this is not enabled. Ideally, I think users should explicitly _enable_ external profiles for specific domains, rather than whitelisting for all. I think it's okay that this is not a backwards-identical change.

**Comment by adleong** [comment]
@dadjeibaah did some testing and found that the destination service was able to handle 10000 concurrent profile requests without really breaking a sweat.  So assuming that the proxy respects the outbound router capacity of 10000, I think we can leave external profiles enabled.

@dadjeibaah can you provide more details?

**Comment by grampelberg** [comment]
From my perspective, I'm happy disabling external names for now and tackling this as part of #2191.

**Comment by dadjeibaah** [comment]
Yea, the destination service can handle 10,000 concurrent profile requests with no problem. So, we can keep querying external profiles.

**Comment by olix0r** [comment]
I still feel pretty strongly that we follow through with this.
