### ISSUE TITLE
Add support for `config.linkerd.io/disable-identity` annotation in auto-inject

### ISSUE THREAD

**Issue by klingerf** [linkerd/linkerd2#2540]
#2535 added a `--disable-identity` flag for CLI inject, but there's no equivalent for disabling identity in the auto-injector. We should add support for a `config.linkerd.io/disable-identity` annotation that allows disabling identity per workload. We should also consider a `--disable-identity` flag for `linkerd install`, which globally disables identity for all workloads. cc @olix0r

**Comment by alpeb** [comment]
The part for `linkerd upgrade`  has been merged. Still have to do the same in `linkerd install`. The merged branch contains some notes to take into account for `linkerd install`.

**Comment by alpeb** [comment]
Turns out we need identity for the upcoming tap work. #2783 tracks the segregation of mTLS in the data plane vs establishing identity against the control plane.
