### ISSUE TITLE
Observability Query Language

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#2541]
### What problem are you trying to solve?

There's a lot of great observability data in Linkerd. Between prometheus and tap, you can get all kinds of data that explains how your system is working. Unfortunately, these two pieces of data are separate and somewhat difficult to introspect and understand. It is possible to use the CLI, script the output and build a solution on top of that. This solution would be extremely fragile and difficult for users to keep up to date as the project moves forward.

### How should the problem be solved?

Introduce a graphql API that allows for querying metrics and live data for a Linkerd installation. This should allow for:

- Looking up tap requests by keys other than k8s deployments. Imagine getting all the requests/responses that do not have identity or don't match with service profiles.
- Streaming results as they're collected by the cluster. This could be used to build live dashboards of tap data or metrics as they're updated by prometheus.
- Selecting a metric and seeing the data that was compiled for the metric. Users can look at this to understand what is being missed and understand how metrics are constructed.
- Fetching all the metrics required to draw GUI views.

**Comment by grampelberg** [comment]
@rmars @scottcarol we've talked about something much smaller than this in the past to get around the weird data sync issues we've got in the GUI. What do you think about potentially moving over to using an API like this for the dashboard instead of the REST based API that is there today?

**Comment by grampelberg** [comment]
@Pothulapati what do you think? I'm getting more and more excited about this issue the more I think about it.

**Comment by rmars** [comment]
This would be extremely cool. Am in support of a graphql API for exploring all of linkerd's data!

**Comment by scottcarol** [comment]
@grampelberg Could you share a couple specific examples of how a graphql API-based dashboard could help a user solve an issue that they currently can't on the dashboard? Big ⭐️ to graphql, it would be very cool to use that technology.

**Comment by grampelberg** [comment]
@scottcarol you can't do the three that I added in the `allows for`. The underlying issue, though, is that it is hard to understand how the dashboard is doing something and there's no standard API there. This would make integrations and exploration much easier.

**Comment by scottcarol** [comment]
@grampelberg Makes sense re: integrations and exploration, sounds really cool. 

This example: `imagine getting all the requests/responses that do not have identity or don't match with service profiles` is really interesting. Sounds like part of the project will be UI/design-related, to maintain the simplicity of the dashboard while communicating the richness of the added data. 💯
