### ISSUE TITLE
Identity controller must only serve responses for trusted requests

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#2543]
An identity service may serve requests in one of two ways:
* via `localhost`, i.e. from the controller's local proxy
* via the proxy's inbound router

In the first case, we _can't_ do TLS (due to bootstrapping), so the controller must serve requests that originated on the localhost.

In the second case, the proxy might accept EITHER non-TLS'd or TLS'd requests (it adds headers to indicate that it has done so).

The identity controller must check for the presence of proxy-set headers and ONLY respond when we trust that the connection was private. If the request comes from an untrusted source, we must fail to validate the identity.

It may be necessary to add additional headers to the proxy to accomplish this.

**Comment by olix0r** [comment]
Relates to https://github.com/linkerd/linkerd2/issues/2185

**Comment by kleimkuhler** [comment]
Reopening as this issue is still relevant for tap hardening.

**Comment by grampelberg** [comment]
@kleimkuhler is this done?

**Comment by kleimkuhler** [comment]
@grampelberg Nope this is pretty separate from the side of tap hardening we are focusing on for 2.5. There are a few stories in this project that fall outside of the scope what is involved with the new tap APIServer and this is one of them.
