### ISSUE TITLE
The table obtained from linkerd top deploy/linkerd-web is not wrapping in terminal properly

### ISSUE THREAD

**Issue by gane5hvarma** [linkerd/linkerd2#2558]
### What is the issue?
The table obtained from linkerd top deploy/linkerd-web is not wrapping in terminal properly. The issue might be not using correct function of printing table on terminal of termbox go package.
### How can it be reproduced?
linkerd -n linkerd top deploy/linkerd-web
### Logs, error output, etc
![linkerdmetrics](https://user-images.githubusercontent.com/23616236/54943982-8050b500-4f58-11e9-9739-f7eb4459bc0c.png)
![linkerd2](https://user-images.githubusercontent.com/23616236/54944049-a8401880-4f58-11e9-8e89-1ba5f351e6ba.png)

(If the output is long, please create a [gist](https://gist.github.com/) and
paste the link here.)

#### `linkerd check` output

```text
your output here ...
```

### Environment

- Kubernetes Version: 1.11.7
- Cluster Environment: (GKE, AKS, kops, ...) GKE
- Host OS: Ubuntu 16
- Linkerd version: 2.2.1

**Comment by gane5hvarma** [comment]
working on this issue :)

**Comment by kohsheen1234** [comment]
Hey @grampelberg Can I work on this if it's been stale for long??

**Comment by ihcsim** [comment]
@kohsheen1234 Thanks for your interest! Not exactly sure why https://github.com/linkerd/linkerd2/pull/2580 wasn't reviewed and merged (oops!).

@gane5hvarma Are you interested in bringing #2580 cross the finish line? (I can reopen it.) It will need to be rebased with `master`? If not, we can let @kohsheen1234 give it a try. Thanks!

**Comment by gane5hvarma** [comment]
@ihcsim I'm currently occupied with other work. Hence can't spend time in the near future. Let @kohsheen1234 give it a try.

**Comment by ihcsim** [comment]
@gane5hvarma Sounds good. Apologies for overlooking that PR.

@kohsheen1234 It's all yours! Please take a look at @grampelberg's comment at https://github.com/linkerd/linkerd2/pull/2580#issuecomment-477650729. If you have any questions, feel free to join us in the #contributors channel on the Linkerd slack.

**Comment by kohsheen1234** [comment]
Thank you @gane5hvarma, @ihcsim . I will start working on this issue. @ihcsim Can you please assign the issue to me. :)

**Comment by kohsheen1234** [comment]
Hey @ihcsim, 

I had a few doubts regarding the fixes that are wanted for the issue.
Does the scrolling have to be controlled by the mouse or are keys enough. Secondly, if the scrolling has to be done by the mouse can we use additional libraries such as robotgo: https://github.com/go-vgo/robotgo
