### ISSUE TITLE
Update web server to read the UUID from the linkerd-config ConfigMap

### ISSUE THREAD

**Issue by klingerf** [linkerd/linkerd2#2567]
#2561 added the control plane install's UUID to the global `linkerd-config` ConfigMap. This means that the web server no longer needs to be explicitly passed the UUID via the `-uuid` flag, and it can instead volume mount the ConfigMap and read it from there.

For an example of how other containers volume mount the ConfigMap in the install YAML, see:

https://github.com/linkerd/linkerd2/blob/7efe385feb2afbb5e6d2918ff005d56e17ad00e9/chart/templates/proxy_injector.yaml#L41-L43

And for an example of how values are read from the global config map, see:

https://github.com/linkerd/linkerd2/blob/7efe385feb2afbb5e6d2918ff005d56e17ad00e9/controller/proxy-injector/webhook.go#L91-L94

As part of this change, we also update `web/main.go` to remove the `-uuid` flag.

**Comment by KatherineMelnyk** [comment]
I will take it.

**Comment by harsh-98** [comment]
@KatherineMelnyk are you working on this?

**Comment by KatherineMelnyk** [comment]
Hi,
I'am in progress. I tried to do something, but i can't solve it without
Kubernetes. Now I'm trying to run test environment. I plan to finish task
in two-three days.

чт, 28 мар. 2019 г. в 21:49, harsh jain <notifications@github.com>:
