### ISSUE TITLE
Remove --linkerd-cni-enabled inject flag

### ISSUE THREAD

**Issue by klingerf** [linkerd/linkerd2#2568]
~~Relates to #2540. It's now possible to override most inject options via `config.linkerd.io` annotations on the pod spec, but there's no support for a `config.linkerd.io/linkerd-cni-enabled` annotation that corresponds to running `linkerd inject --linkerd-cni-enabled`. We should add support for that in `pkg/inject`, and once #2547 merges, we should also start setting that annotation from the CLI when the `--linkerd-cni-enabled` flag is present.~~

As @olix0r points out, linkerd CNI is enabled/disabled at the cluster level (at `install`), and it doesn't make sense to modify it per workland (at `inject`). Now that inject reads the install defaults from the control plane (#2535), we no longer need to support enabling/disabling linkerd CNI on inject. Let's use this issue to track removing the `--linkerd-cni-enabled` inject flag, and make it install only. This means we'll need to move the `noInitContainer` field from the `proxyConfigOptions` struct to the `installOptions` struct.

**Comment by harsh-98** [comment]
I would like to work on it and i have understood the issue.

**Comment by harsh-98** [comment]
On line https://github.com/linkerd/linkerd2/blob/master/cli/cmd/install.go#L338, why is options.noInitContainer correct even though options is of type InstallOptions which doesn't have noInitContainer.

**Comment by ihcsim** [comment]
@harsh-98 I see that you've already found the answer in #2573 - the `InstallOption` type has the `proxyConfigOptions` type embedded. The `noInitContainer` field is declared in the `proxyConfigOptions` in [root.go](https://github.com/linkerd/linkerd2/blob/fda2035d5ca1ad640582e6331c5a667aae3fe2ef/cli/cmd/root.go#L203).
