### ISSUE TITLE
install: Persist install context with configuration

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#2574]
## Problem

When installing Linkerd, a user may override default settings, or may explicitly configure defaults.  Consider install options like `--ha --proxy-cpu-request=20m' -- the `--ha` flag sets a _new_ default value for the proxy-cpu-request, and then we override it.

When we later `upgrade` this cluster, how can we know how to configure the cluster?

We could store EnableHA and ProxyCPURequest configurations in the config, but what if, in a later upgrade, the default value changes? How can we know whether the user specified an override or just used the default?

## Proposal

To solve this, we add an `InstallContext` message onto the Global config. This message includes (at least) the CLI flags used to invoke `install`.

`upgrade` does not specify defaults for install/proxy-options fields and, instead, uses the persisted install flags to populate default values, before applying overrides from the `upgrade` invocation.

**Comment by ihcsim** [comment]
The proposal sgtm. Some questions:

1. I assume the `InstallContext` will only persist the most-recent `install` CLI flags (in the event of multiple calls to `linkerd install --ignore-cluster`, for whatever reasons)
1. If there are new defaults during `upgrade`, the `linkerd-config` config map will get updated, except the `InstallContext`, right?
1. Will we be storing the linkerd version as part of the `InstallContext`? If yes, it should be modified after a successful `upgrade`, right? (I can see the benefits of using the version as a pre-upgrade check, which may be relevant for cases where users aren't allowed to skip certain mandatory intermediate version, when they want to do an one-time multi-version upgrade.)

**Comment by olix0r** [comment]
@ihcsim good questions (that i was just documenting in the config.proto comments).  We'll store the CLI version and args on each install/upgrade. The UUID will only be set on install, as today.
