### ISSUE TITLE
Output upgrade instructions

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#2575]
### What problem are you trying to solve?

Upgrading between versions is more than just the control plane. #2556 covers providing a command, but it only outputs YAML. There are breaking changes, specific upgrade steps and gotchas when going between versions.

### How should the problem be solved?

Output a URL that provides the full upgrade instructions between versions as part of the CLI output. This way, users can go read up before then apply to the cluster and follow the steps.

**Comment by scottcarol** [comment]
@grampelberg Is the URL a link to a new page on linkerd.io, maybe `https://linkerd.io/2/upgrade-help`? Does this issue include creating that new page, with upgrade instructions?

**Comment by grampelberg** [comment]
https://linkerd.io/2/tasks/upgrade/ would be where it would go eventually. We should have a redirect in place that goes there though (take a look at how check's been done).

**Comment by scottcarol** [comment]
Should the URL be output only if the user types `linkerd upgrade -h | --help` or should it be output any time the user types `linkerd upgrade`?

**Comment by grampelberg** [comment]
@scottcarol any time a user types `linkerd upgrade`. Take a look at how `inject` does its output.
