### ISSUE TITLE
Init:ImagePullBackOff for control plane pods

### ISSUE THREAD

**Issue by harsh-98** [linkerd/linkerd2#2579]
### What is the issue?
Pods under Linkerd namespaces are not starting.

### How can it be reproduced?
Yes, by `go run cli/main.go install | kubectl apply -f -` . Commit hash is : 93e7654ebaccaddad513738e84e2dbda3c586ed6

### Logs, error output, etc
![linkerd](https://user-images.githubusercontent.com/23700929/55137197-5cf35900-5156-11e9-87d3-881734c7c3ed.png)

#### `linkerd check` output

```text
your output here ...
```

### Environment

- Kubernetes Version: minikube version: v0.35.0
- Host OS: arch

**Comment by siggy** [comment]
@harsh-98 `go run cli/main.go install` will generate an install yaml with `dev-undefined` as the Linkerd version tag, probably not what you want.

To confirm, observe the difference between these two commands:

```bash
$ go run cli/main.go install | grep image:
        image: gcr.io/linkerd-io/controller:dev-undefined
...
```

```bash
$ go run cli/main.go install --linkerd-version=$(bin/root-tag) | grep image:
        image: gcr.io/linkerd-io/controller:git-93e7654e
```

A couple alternatives:

1. Install with already-built Docker images
    ```bash
    $ go run cli/main.go install --linkerd-version=$(bin/root-tag) | kubectl apply -f -
    ```

2. Build Docker images yourself
    ```bash
    DOCKER_TRACE=1 bin/mkube bin/docker-build
    bin/linkerd install | kubectl apply -f -
    ```

For more info:
https://github.com/linkerd/linkerd2/blob/master/BUILD.md#comprehensive

I'm going to close this issue for now. Hop into [Linkerd Slack](https://slack.linkerd.io/) if you have more questions.
