### ISSUE TITLE
conduit dashboard command should fail if conduit not ready

### ISSUE THREAD

**Issue by siggy** [linkerd/linkerd2#258]
the `conduit dashboard` command should fail if conduit is not installed or in a working state:
- No running k8s
- Running k8s but conduit not installed
- Conduit had an error on installing and its containers are error'd

from: https://github.com/runconduit/conduit/pull/249#pullrequestreview-93695800

**Comment by grampelberg** [comment]
> Conduit had an error on installing and its containers are error'd

The desired behavior here is to output the ambiguous error (whatever client-go says) and ask the user to run `conduit check` for more details.

**Comment by klingerf** [comment]
Just wanted to update on the current state of this issue.

## No running k8s

The `linkerd dashboard` command hangs for ~25 seconds and then exits with:

```
Linkerd is not running in the "linkerd" namespace
Install with: linkerd install --linkerd-namespace linkerd | kubectl apply -f -
```

We should investigate aborting sooner and giving the user some indication that we couldn't connect to Kubernetes.

## Running k8s but linkerd not installed

The `linkerd dashboard` command exits immediately with:

```
Linkerd is not running in the "linkerd" namespace
Install with: linkerd install --linkerd-namespace linkerd | kubectl apply -f -
```

This seems like the right behavior.

## Linkerd had an error on installing and its containers are error'd

The `linkerd dashboard` command exits immediately with:

```
Linkerd is not running in the "linkerd" namespace
Install with: linkerd install --linkerd-namespace linkerd | kubectl apply -f -
```

If the linkerd namespace exists but we can't connect to it, we should instead prompt the user to run `linkerd check` for more details.

**Comment by klingerf** [comment]
> We should investigate aborting sooner and giving the user some indication that we couldn't connect to Kubernetes.

On the other hand, if you try to run a `kubectl` command against a k8s cluster that doesn't exist, that command also hangs for the same amount of time, since we're using the same underlying library. So maybe detecting that there's no k8s cluster faster than `kubectl` does shouldn't be one of our goals.
