### ISSUE TITLE
Live/ready probes timing out on application container

### ISSUE THREAD

**Issue by tanuck** [linkerd/linkerd2#2581]
### What is the issue?
After upgrading to `19.3.3` we started seeing intermittent pod restarts. The liveness probe was timing out and k8s was killing the pod. It seems like the proxy was blocking the request getting through to our application container. The proxy would log the following:

`WARN [ 28995.080301s] proxy={server=in listen=0.0.0.0:4143} linkerd2_proxy::transport::addr_info::linux failed to read SO_ORIGINAL_DST: Os { code: 2, kind: NotFound, message: "No such file or directory" }`

`ERR! [ 28995.080743s] proxy={server=in listen=0.0.0.0:4143 remote=10.0.1.1:46102} linkerd2_proxy::proxy::http::router could not recognize request`

### How can it be reproduced?
We haven't been able to reproduce the whole thing, but we have recognised patterns. Only pods receiving traffic from our ingress controller are affected. We're using traefik so this seems very similar to this issue https://github.com/linkerd/linkerd2/issues/1861

### Logs, error output, etc

(If the output is long, please create a [gist](https://gist.github.com/) and
paste the link here.)

#### `linkerd check` output

```text
$ linkerd check
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ control plane namespace exists
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-api
-----------
√ control plane pods are ready
√ control plane self-check
√ [kubernetes] control plane can talk to Kubernetes
√ [prometheus] control plane can talk to Prometheus
√ no invalid service profiles

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ control plane is up-to-date
√ control plane and cli versions match

Status check results are √
```

### Environment

- Kubernetes Version: 1.12.5
- Cluster Environment: GKE
- Host OS: cos
- Linkerd version: edge-19.3.3

**Comment by grampelberg** [comment]
Is your traefik injected with linkerd? Any special settings? Header rewrites? Protocols used?

**Comment by tanuck** [comment]
Initially traefik wasn't meshed, I've since injected linkerd but ignoring the inbound ports. But the issues persists. Here's the traefik config: https://gist.github.com/tanuck/0640fc46715caa14877ba72510841871

**Comment by olix0r** [comment]
@tanuck We're pretty confident that we've fixed this issue. You can get the latest edge release with the fix here:

```sh
curl -sL https://run.linkerd.io/install-edge |env LINKERD2_VERSION=edge-19.4.4 sh
```

If you see still see any behavior like this, please reopen this issue!

**Comment by tanuck** [comment]
@olix0r good work :+1: 

I shall test it as much as I can this week!
