### ISSUE TITLE
inject command returning 404 error for master branch

### ISSUE THREAD

**Issue by harsh-98** [linkerd/linkerd2#2582]
### What is the issue?
When trying to run `bin/go-run cli inject a.yml` it is giving `Error: Unexpected API response: 404 Not Found`.

### How can it be reproduced?
curl -sL https://run.linkerd.io/emojivoto.yml | bin/go-run cli inject -

### Logs, error output, etc

(If the output is long, please create a [gist](https://gist.github.com/) and
paste the link here.)

#### `linkerd check` output

```text
your output here ...
```

### Environment

- Kubernetes Version: minikube version: v0.35.0
- Host OS: arch

### Additional context
When I tried to log the url, i got `https://192.168.99.108:8443/api/v1/namespaces/linkerd/services/linkerd-controller-api:http/proxy/api/v1/Config`.

**Comment by grampelberg** [comment]
This is likely because the control plane version doesn't match. We can sort this out in slack =)
