### ISSUE TITLE
Responsive Dashboard

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#2583]
### What problem are you trying to solve?

I would like for the dashboard to be responsive so that it can be viewed on tablets and phones.

### How should the problem be solved?

Make it responsive!

**Comment by scottcarol** [comment]
Update, have reached out to the user who asked for a more mobile-friendly dashboard to learn more about the specific use case.

**Comment by scottcarol** [comment]
Basic functionality was addressed in #2678, so I am closing this issue. 

New issue for additional improvements: #2687
