### ISSUE TITLE
Move away from minikube

### ISSUE THREAD

**Issue by epk** [linkerd/linkerd2#2600]
### What problem are you trying to solve?
Move away from minikube for local development 
### How should the problem be solved?
Possible replacements:
- [kind](https://github.com/kubernetes-sigs/kind) 
- Docker-for-Desktop 's inbuilt k8s environment

Both have their own pros and cons:

#### Pros:
- Should be helpful for Conformance Validation #1096 with latest k8s releases 
- Current default environment used in prow/testing jobs for k8s addons like [ingress-nginx](https://github.com/kubernetes/ingress-nginx) and istio
- Supports latest k8s versions, one of the first to support 1.14 release
- Is a [CNCF certified conformant Kubernetes installer](https://landscape.cncf.io/selected=kind)
- Supports Windows in addition to MacOS and Linux
#### Cons:
- Requires Docker-for-Desktop 
- Need to load images into the `kind cluster` after building. 
   Here's the one-liner I use:
 ```sh
docker images  --filter "dangling=false" | grep gcr.io/linkerd-io | \ 
awk ' {printf "%s:%s\n", $1, $2}' | xargs -n 1 kind load docker-image
```
#### Pros:
- One less dependency 
- No need to load images after building  
- One click k8s cluster creation through GUI 
#### Cons:
- Runs a not so recent v1.10.11 node
- Windows support?

What do you folks think? I will be happy to implement either

cc @grampelberg @olix0r

**Comment by olix0r** [comment]
@paranoidaditya hi @paranoidaditya!

I know that we happen to have some minikube-related scripts in the repo, but I would be in favor of simply removing them.

In fact, I (and others on the project) have been using non-minikube clusters extensively (docker for mac, microk8s, etc); so it's not obvious to me that anything in the project has to change.

Is there a specific functionality change you think is necessary in the repo? Or is this mostly suggesting updating developer documentation?

**Comment by paranoidaditya** [comment]
This is mostly updating documentation if we go with docker with mac, if we go with kind, a dumb script to load the images should do.

Loading images is a costly operation time wise, so was hoping to implement `kind images list` and push that upstream

**Comment by siggy** [comment]
@paranoidaditya Removing minikube references from `BUILD.md` sounds good. Go for it!
