### ISSUE TITLE
Surface identity by connection in the dashboard

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#2606]
### What problem are you trying to solve?

The TLS % in `stat` is confusing and potentially misleading. As it shows aggregates, it is difficult to understand what connections between client/server pairs are encrypted, which aren't and why. Debugging why a connection is not being upgraded to TLS can be frustrating.

### User Questions

- Is Linkerd working by encrypting traffic?
- What traffic is not encrypted?
- Can I see what identity is being used?
- Why is TLS not working for my service?

### How should the problem be solved?

First, the `tls` column should be removed. Second, introduce a new `identity` table. See #2605 for details on the columns and data that goes in. This table should be added to:

- `Sidebar` as a resource type, showing the service accounts used.
- `Overview` as a table nested in the namespace view. This should be for all the connections and identities in the namespace.
- Resource detail views as a table that shows the connections specific to that resource. For the parent resource types (deployments for example), there should be aggregates instead of showing pods.

### Open Questions

- Adding identity to the sidebar is great. `Authorities` and `Identity` don't really fit into the k8s resources though. Maybe there should be a separate dropdown? Perhaps identity should have its own section?
- I'm not sure how the aggregation should work, the table should be optimized to be small instead of having a ton of entries.
- The overview table feels like it might be overwhelming. Is there a way to filter it down in that view? Maybe it should just be skipped entirely in overview.

**Comment by grampelberg** [comment]
Related to #2605

**Comment by grampelberg** [comment]
## Sidebar

![Screenshot 2019-04-05 09 44 46](https://user-images.githubusercontent.com/47992/55646803-f3480000-5790-11e9-97f9-c9d1aa39763b.png)

## Overview

![Screenshot 2019-04-05 10 03 23](https://user-images.githubusercontent.com/47992/55646804-f3480000-5790-11e9-856f-4d6d7d0ace44.png)

- src/dst links go to detail pages for those resources
- client/server links go to identity page showing everywhere those identities are used
- ? after `not_provided_by_remote` suggests a tooltip, text would be “This appears to be a liveness/readiness check and is not TLS’d”

**Comment by scottcarol** [comment]
More detailed feature requests are now in #2708 and #2709
