### ISSUE TITLE
Remove TLS columns from CLI

### ISSUE THREAD

**Issue by scottcarol** [linkerd/linkerd2#2607]
See #2605 - begin work on surfacing identity in the CLI by removing the `TLS` percentages in `stat`.

**Comment by harsh-98** [comment]
@scottcarol can i work for this one, I have understood what to do.

**Comment by scottcarol** [comment]
Hey @harsh-98, thanks for contributing to Linkerd! 🎈 I see that you already made a PR for this issue even though it was assigned to me. Next time, please check with whoever is assigned and get their OK before you start work on an issue - this ensures that two engineers won't be working on the same issue without knowing it. I'll go ahead and look at your PR today.
