### ISSUE TITLE
Proxy starts after inject then connection refused

### ISSUE THREAD

**Issue by vic3lord** [linkerd/linkerd2#2630]
## Bug Report

I have injected the proxy into one specific app (most apps work) and the proxy fails to connect to the service

### What is the issue?

linkerd2_proxy::app::errors unexpected error: an error occurred trying to connect: Connection refused (os error 111) (address: 127.0.0.1:8080)

### How can it be reproduced?

I couldn't find a way to reproduce this error on other services, this service specifically is a Go service that publishes data to Google Pubsub (gRPC) which is external to the mesh

### Logs, error output, etc

linkerd2_proxy::app::errors unexpected error: an error occurred trying to connect: Connection refused (os error 111) (address: 127.0.0.1:8080)

#### `linkerd check` output

```text
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ control plane namespace exists
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-api
-----------
√ control plane pods are ready
√ control plane self-check
√ [kubernetes] control plane can talk to Kubernetes
√ [prometheus] control plane can talk to Prometheus
√ no invalid service profiles

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ control plane is up-to-date
√ control plane and cli versions match

Status check results are √
```

### Environment

- Kubernetes Version: 1.12.5-gke.10
- Cluster Environment: GKE
- Host OS: Google COS
- Linkerd version: edge-19.4.1

**Comment by grampelberg** [comment]
That error message makes me wonder what the headers are. You wouldn't happen to have a tcpdump would you?

**Comment by vic3lord** [comment]
It's distroless image but I will try to do some tcpdump even though this exact service worked just fine with linkerd `edge-19.3.1` and when upgrading I had to uninject so it looks like it's a linkerd-proxy issue..

LMK if I can provide you with more details and I will try to run tcpdump later on

**Comment by grampelberg** [comment]
Hmm, if it was working with `edge-19.3.1` that invalidates my assumption there. `tcpdump` probably won't get everything I was hoping. Is there anything interesting in the logs if you bump the level up?

**Comment by olix0r** [comment]
@vic3lord is that the full log line? I'd expect an additional prefix indicating the server context, but that may not be available where these (new, i think) log lines are emitted...

Specifically, I'm a little unclear on what the connection is actually doing...
> linkerd2_proxy::app::errors unexpected error: an error occurred trying to connect: Connection refused (os error 111) (address: 127.0.0.1:8080)

indicates that you couldn't connect to a localhost port, but...
> this service specifically is a Go service that publishes data to Google Pubsub (gRPC) which is external to the mesh

makes it sound like you're attempting to make _outbound_ connections.

Can you clarify what traffic this pod should be getting on 8080? Has your application actually booted and bound to port 8080 by the time this log line is emitted?

**Comment by vic3lord** [comment]
@olix0r this service worked fine with older versions the thing it does is.

1. Gorilla mux server on `:8080` takes POST requests
2. forwards the POST as pubsub message data

**Comment by olix0r** [comment]
@vic3lord Can you confirm that the application has actually started and is serving on :8080 at this point?  If the app container is actually running, does `kubectl  exec -it $pod  -c linkerd-proxy -- curl -v localhost:8080` fail?

More generally, i'm trying to figure out _why_ we can't connect to port 8080... Is the application trying to do anything that could stall or fail, preventing it from actually binding port 8080?

For example, if it's the case that the gorilla server tries to establish a connection to the pubsub server before it starts accepting on 8080, then we'd want to figure out why that connection i failing or if a timeout, for instance, might fix it...

**Comment by vic3lord** [comment]
```
kubectl -n data exec -it events-cf64cbf99-dndth -c linkerd-proxy -- curl -v localhost:8080/healthz
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
> GET /healthz HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.52.1
> Accept: */*
>
< HTTP/1.1 200 OK
< Access-Control-Allow-Credentials: true
< Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept
< Access-Control-Allow-Methods: OPTIONS, POST
< Access-Control-Allow-Origin:
< Strict-Transport-Security: max-age=31536000
< Date: Fri, 05 Apr 2019 05:06:37 GMT
< Content-Length: 0
<
* Curl_http_done: called premature == 0
* Connection #0 to host localhost left intact
```

**Comment by vic3lord** [comment]
It's working after deployment for a few minutes and then crashes

**Comment by olix0r** [comment]
@vic3lord We're pretty confident that we've fixed this issue. You can get the latest edge release with the fix here:

```sh
curl -sL https://run.linkerd.io/install-edge |env LINKERD2_VERSION=edge-19.4.4 sh
```

If you see still see any behavior like this, please reopen this issue! Thanks.
