### ISSUE TITLE
Expose profiling information for control plane components

### ISSUE THREAD

**Issue by dadjeibaah** [linkerd/linkerd2#2634]
### What problem are you trying to solve?
To better assist debugging efforts in the control plane, it would be good to expose profiling information (e.g. CPU and memory usage, number of goroutines) for each control plane component somehow. 

### How should the problem be solved?
Since each component is a go application, you can take advantage of Go's [pprof](https://golang.org/pkg/runtime/pprof/) tools to expose this information.

### Open Questions:
- What's the user experience going to be when trying to retrieve this info? Will it be a CLI command, another endpoint on each components' admin server?
- Is this feature on by default? Do we pass in a flag to turn in on at install time?
- Is there a subset of information we really care about. i.e. Do we just want to get memory usage out of each process? or is there more we need?

**Comment by ihcsim** [comment]
Curious if we can get these metrics (cpu, memory, goroutines count etc.) from prometheus/grafana?

**Comment by grampelberg** [comment]
@ihcsim we can get some of them. There are some projects to get more data (#2204). I'm pretty interested in getting internal usage data though to help track down leaks a little bit more granularly.

**Comment by grampelberg** [comment]
> Is this feature on by default? Do we pass in a flag to turn in on at install time?

Ideally, this is something that is on by default. That said, we'll need to understand the tradeoffs. If it is super expensive then we'll not have any real choice in the matter.
