### ISSUE TITLE
Load balancing doesn't work for tensorflow serving?

### ISSUE THREAD

**Issue by Insullone** [linkerd/linkerd2#2636]
### What is the issue?

In my case, I deployed Tensorflow Serving (with model ssd-inception-v2, using gRPC) as a deployment with 3 replicas on GKE, and injected it following the linkerd 2 instruction of Getting Started. After that I sent 50 requests and find that all requests are served by the same pod according to linkerd dashboard.

### Logs, error output, etc
Here are logs from linkerd dashboard:
E0404 15:22:04.864767   23796 portforward.go:391] an error occurred forwarding 37847 -> 8084: error forwarding port 8084 to pod 1f7158b50bcb62418b68d52aeccb3526342e4adee3ec7c186af22012638a4d6a, uid : exit status 1: 2019/04/04 12:22:04 socat[1143] E connect(5, AF=2 127.0.0.1:8084, 16): Connection refused

#### `linkerd check` output

```text
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version

linkerd-existence
-----------------
√ control plane namespace exists
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-api
-----------
√ control plane pods are ready
√ can query the control plane API
√ [kubernetes] control plane can talk to Kubernetes
√ [prometheus] control plane can talk to Prometheus

linkerd-service-profile
-----------------------
√ no invalid service profiles

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ control plane is up-to-date
√ control plane and cli versions match

Status check results are √

```

```
kubectl get all -n linkerd
NAME                                      READY   STATUS    RESTARTS   AGE
pod/linkerd-controller-84df9d879b-l9w5j   4/4     Running   0          2h
pod/linkerd-grafana-766c79f88-btfdv       2/2     Running   6          2h
pod/linkerd-prometheus-6977cc68f6-p7sdd   2/2     Running   0          2h
pod/linkerd-web-58d9c8c64c-fqchk          2/2     Running   6          2h

NAME                             TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)             AGE
service/linkerd-controller-api   ClusterIP   10.0.3.49     <none>        8085/TCP            2h
service/linkerd-grafana          ClusterIP   10.0.8.200    <none>        3000/TCP            2h
service/linkerd-prometheus       ClusterIP   10.0.9.242    <none>        9090/TCP            2h
service/linkerd-proxy-api        ClusterIP   10.0.14.211   <none>        8086/TCP            2h
service/linkerd-web              ClusterIP   10.0.5.114    <none>        8084/TCP,9994/TCP   2h

NAME                                 DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/linkerd-controller   1         1         1            1           2h
deployment.apps/linkerd-grafana      1         1         1            1           2h
deployment.apps/linkerd-prometheus   1         1         1            1           2h
deployment.apps/linkerd-web          1         1         1            1           2h

NAME                                            DESIRED   CURRENT   READY   AGE
replicaset.apps/linkerd-controller-84df9d879b   1         1         1       2h
replicaset.apps/linkerd-grafana-766c79f88       1         1         1       2h
replicaset.apps/linkerd-prometheus-6977cc68f6   1         1         1       2h
replicaset.apps/linkerd-web-58d9c8c64c          1         1         1       2h

```
```
kubectl get all
NAME                                         READY   STATUS    RESTARTS   AGE
pod/ssd-inception-v2-coco-5d98fbf459-kpjdt   2/2     Running   0          44m
pod/ssd-inception-v2-coco-5d98fbf459-pw7tz   2/2     Running   0          44m
pod/ssd-inception-v2-coco-5d98fbf459-z9q7m   2/2     Running   0          44m

NAME                                    TYPE           CLUSTER-IP   EXTERNAL-IP     PORT(S)          AGE
service/kubernetes                      ClusterIP      10.0.0.1     <none>          443/TCP          44d
service/ssd-inception-v2-coco-service   LoadBalancer   10.0.3.27    35.228.251.94   8500:32275/TCP   44m

NAME                                    DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/ssd-inception-v2-coco   3         3         3            3           44m

NAME                                               DESIRED   CURRENT   READY   AGE
replicaset.apps/ssd-inception-v2-coco-5d98fbf459   3         3         3       44m

```

### Environment

- Kubernetes Version: Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.7-gke.12"}

- Cluster Environment: GKE, 4 nodes
- Host OS: Ubuntu 16.04
- Linkerd version: Client version: stable-2.2.1, Server version: stable-2.2.1

### Additional context
Client code (extract):
```
class TestPerformance:
...
    def consume(self):
        stub = prediction_service_pb2_grpc.PredictionServiceStub(self.channel)
        request = predict_pb2.PredictRequest()
        request.model_spec.name = 'ssd_inception_v2_coco'
        request.model_spec.signature_name = 'serving_default'
        request.inputs['inputs'].CopyFrom(
        tf.make_tensor_proto(image_data, shape=[1, width, height, 3]))
        result = stub.Predict(request, 10.0)

    def start_till_finish(self):
        for i in range(self.number_threads):
            t = threading.Thread(name="Thread-" + str(i), target=self.consume, args=())
            t.start()

test = TestPerformance(server, num_threads)
...
test.start_till_finish()
```

Could you help me? Thank you very much.

**Comment by ihcsim** [comment]
Linkerd does grpc client-side load balancing. Can you try injecting your client with the Linkerd proxy? 

The linkerd dashboard error you saw might be something else. Are you GKE nodes firewall configured to allow port-forwarding at port 37847?

**Comment by Insullone** [comment]
My client is just a simple python script, and I run it from a IDE by clicking RUN. Is it easy to inject my client with Linkerd proxy, are there any instructions for this? However, actually I prefer load balancing from server side, and I will try server-side proxy first.

The instruction of "Getting Started" in Linkerd 2.x is for server side on k8s, right? Can I use this instruction for my case? I followed it but all requests went to the same pod. Please advise me, thanks!

**Comment by grampelberg** [comment]
How are you getting data into the cluster?

**Comment by ihcsim** [comment]
Does your IDE deploy your client as a k8s workload (deployment, pod etc.)? If yes, you can inject your client pod with something like this:
```
kubectl -n <namespace> get po <client-pod> -o yaml | linkerd inject - | kubectl apply -f -
```
The emojivoto example in "Getting Started" inject both servers and the client (vote-bot).

**Comment by Insullone** [comment]
@ihcsim Thank you very much. The load balancing works after client injection. 

So far in my setup linkerd control plane is installed on server side (GKE), and the client runs on my laptop on microk8s. My question is that if linkerd control plane is supposed to be installed on client side or server side? Does it matter? In my case, I installed it on server side, but how the client after injection knows the addresses of the instances of the service (Tensorflow serving), which is only exposed by a LoadBalancer service by GKE as the logging shows in my question description, on the server side?

**Comment by grampelberg** [comment]
Linkerd is currently designed to run within a single cluster. In this example, you would have an ingress on the GKE side that is injected with Linkerd and that is where the control plane would run.

**Comment by Insullone** [comment]
Thank you. I know better how linkerd works now. In my case, I observed gRPC load balancing because I run multiple clients in dockers so that they are different connections, and it is merely L4 load balancing.
