### ISSUE TITLE
upgrade command unit tests

### ISSUE THREAD

**Issue by siggy** [linkerd/linkerd2#2637]
#2564 introduced the `linkerd upgrade` command, with most of the new code in `cli/cmd/upgrade.go`. Add unit tests for this.

Note that `linkerd upgrade` tests could leverage functionality described in #2629, where upgrade information is read from a file rather than from Kubernetes.

Part of #2459

**Comment by olix0r** [comment]
I think this is done now? @siggy ?

**Comment by siggy** [comment]
@olix0r I have a branch that continues this work: https://github.com/linkerd/linkerd2/tree/siggy/update-upgrade-unit

The goal of the initial PR, #2639, was to introduce unit tests but minimize implementation changes. Now that we have some basic unit testing, we have a bit more flexibility to move things around further, in service to testing.

There's a bit more info in the checklist in #2459.

**Comment by siggy** [comment]
Closing via #2639 #2672.

Subsequent work will be tracked via #2629.
