### ISSUE TITLE
Document & test the minimum privileges needed to deploy to GKE

### ISSUE THREAD

**Issue by briansmith** [linkerd/linkerd2#264]
Currently we suggest people on GKE run this:

```sh
kubectl create clusterrolebinding cluster-admin-binding-$USER --clusterrole=cluster-admin --user=$(gcloud config get-value account)
```

cluster-admin has a lot of privileges. We should document and test the minimum set of privileges actually needed.

**Comment by ihcsim** [comment]
I just did some more exploration on this with GKE 1.10.5-gke.0. It doesn't look like there are other ways to do this. There are no default RBAC cluster roles to allow a user to create additional cluster roles. To create any custom cluster roles, the user needs to be first granted the `cluster-admin` cluster role. The GKE [docs](https://cloud.google.com/kubernetes-engine/docs/how-to/role-based-access-control#interaction_with_identity_and_access_management) specified this as a prerequisite.
