### ISSUE TITLE
Add resource limits when `--ha` is configured

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#2640]
When installing a cluster with `--ha`, we should set resource limits that enforce a reasonable operating envelope for proxies, especially, but also controller components.

**Comment by grampelberg** [comment]
@olix0r what do you think about setting a limit of 1 cpu and 100mb memory?

**Comment by gane5hvarma** [comment]
@olix0r I'm working on this issue.
Few doubts, what all controller components should the resource limit should be set and what will be the value of each component?

**Comment by grampelberg** [comment]
- identity - 1 / 250Mi
- proxy-api - 1 / 250Mi
- public-api - 1 / 250Mi
- tap - 1 / 250Mi
- destination - 1 / 250Mi
- web - 1 / 250Mi
- proxy-injector - 1 / 250Mi
- sp-validator - 1 / 250Mi
- prometheus - 4 / 8192Mi
- grafana - 1 / 1024Mi
- init - 10m / 50Mi

**Comment by dadjeibaah** [comment]
@grampelberg that memory limit in Prometheus seems high for a default. Does Prometheus usually require that much to store data or is this limit high so that we cover most environment setups?
