### ISSUE TITLE
Clear state upon changing tabs in /overview

### ISSUE THREAD

**Issue by rmars** [linkerd/linkerd2#2646]
When clicking around the different namespaces on the Overview page, I notice a lag in the metrics updating when the namespace is changed. We should make sure we're clearing metrics state when a new namespace name is clicked.

To reproduce:
Inject a deployment (e.g. emojivoto) Load the dashboard at `/overview`.
Click on another injected namespace, e.g. `linkerd`. Notice that the sats/tables for this persist for a second or two until the next data refresh.

**Comment by brennerm** [comment]
Not sure if this issue is still valid. The dashboard has changed quite a bit til April and from what I see the metrics update correctly when switching namespaces.

**Comment by grampelberg** [comment]
The new sidebar really helps out here, good call!
