### ISSUE TITLE
upgrade fails from stable-2.2.1 to edge-19.4.3

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#2675]
When using edge-19.4.3 to upgrade from stable-2.2.1, `linkerd upgrade` fails because `linkerd-config` does not exist.

`linkerd install` should succeed, however.

How do we want to handle documenting the upgrade flow from stable-2.2.x to stable-2.3.0?

I'm not sure that we want to have `upgrade` act on clusters that don't have a config...

@grampelberg any thoughts on this?

**Comment by grampelberg** [comment]
I'd rather not support `upgrade` for clusters that don't have config. My plan was to just document the stable and edge upgrade paths and leave it at that. When I tested this in the past `linkerd install` worked the way it had in the past.
