### ISSUE TITLE
proxy: Replace stack with tower-layer

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#2680]
linkerd2-proxy's stack subcrate is more-or-less identical to the, newer, tower-layer crate.

Is it feasible for us to delete our custom implementation in favor of tower-layer? What awful things happen if we try this?

**Comment by olix0r** [comment]
@seanmonstar This is complete, yeah?

**Comment by seanmonstar** [comment]
Yes, done in https://github.com/linkerd/linkerd2-proxy/pull/236
