### ISSUE TITLE
Investigate authorization for tap

### ISSUE THREAD

**Issue by adleong** [linkerd/linkerd2#2683]
The tap service does not perform any authorization on tap requests and admits all requests.

Investigate the mechanisms that exist to perform authentication and authorization in Kubernetes so that the tap service will only accept tap requests from users who are authorized for tap.  Ideally, this authorization method would be controllable would use the existing Kubernets auth model and be controllable with RBAC.

Some possibilities to investigate:
* Creating a "tap" CRD and using tap object as the basis for auth
* Making the tap service an APIExtension with the aggregation layer

**Comment by siggy** [comment]
Fixed via #3167.
