### ISSUE TITLE
inject --disable-identity does not work

### ISSUE THREAD

**Issue by siggy** [linkerd/linkerd2#2684]
With `edge-19.4.3`, `linkerd inject --disable-identity` has no effect on the output:

```bash
$ diff <(curl -s https://run.linkerd.io/emojivoto.yml | linkerd inject -) <(curl -s https://run.linkerd.io/emojivoto.yml | linkerd inject --disable-identity -)

namespace "emojivoto" skipped
serviceaccount "emoji" skipped
serviceaccount "voting" skipped
serviceaccount "web" skipped
deployment "emoji" injected
service "emoji-svc" skipped
deployment "voting" injected
service "voting-svc" skipped
deployment "web" injected
service "web-svc" skipped
deployment "vote-bot" injected


namespace "emojivoto" skipped
serviceaccount "emoji" skipped
serviceaccount "voting" skipped
serviceaccount "web" skipped
deployment "emoji" injected
service "emoji-svc" skipped
deployment "voting" injected
service "voting-svc" skipped
deployment "web" injected
service "web-svc" skipped
deployment "vote-bot" injected
```

### Expected behavior

- `LINKERD2_PROXY_IDENTITY_DISABLED` environment variable should be set on the injected `linkerd-proxy` containers.
- pod template should have `linkerd.io/identity-mode: disabled`
- `LINKERD2_PROXY_IDENTITY_*` should not be set
- `linkerd-identity-end-entity` volume mounts should not be set

**Comment by ihcsim** [comment]
When injecting, the `--disable-identity` flag only works with the `--ignore-cluster` flag as seen [here](https://github.com/linkerd/linkerd2/blob/46d1490f9856e79ff8a4a72a4412e8f7f41c506a/cli/cmd/inject.go#L287-L290).

**Comment by ihcsim** [comment]
When injecting, the `--disable-identity` flag only works with the `--ignore-cluster` flag as seen [here](https://github.com/linkerd/linkerd2/blob/46d1490f9856e79ff8a4a72a4412e8f7f41c506a/cli/cmd/inject.go#L287-L290).

**Comment by olix0r** [comment]
@ihcsim I believe It should also work when `--ignore-cluster` is not specified.
