### ISSUE TITLE
💡 dashboard: denote which links take you out of the dashboard

### ISSUE THREAD

**Issue by wmorgan** [linkerd/linkerd2#2693]
UX thought: with the placement of the community navbar item we have a slightly weird situation where the second item of the "below the bar" nav items keeps you in the dashboard, but every other navbar item leaves the dashboard. One possibly way to address this might be to have some kind of icon denoting which links take you out of the dashboard. (And possibly putting Community at the top of the list rather than as #2.)

![image](https://user-images.githubusercontent.com/4026/56064409-c8c4ec80-5d26-11e9-9cf5-fbbfdd3e2c1f.png)

**Comment by scottcarol** [comment]
@wmorgan What about an icon on the side of each external link? Would that be too cluttered?

![external link example](https://user-images.githubusercontent.com/2289389/56065595-2444a980-5d2a-11e9-9e7d-f244aecf2529.png)

We *are* having the external links open in a separate tab but I agree, we aren't explicitly letting them know they're leaving the dashboard.

**Comment by scottcarol** [comment]
Would Paul have some graphical ideas?

**Comment by wmorgan** [comment]
That icon makes a lot of sense to me and is what I was picturing when I was writing this. Will it look too cluttered if we have like 4 of them in a row?

**Comment by scottcarol** [comment]
I think it looks fine to have the icons like this if we make them light gray:

![external link](https://user-images.githubusercontent.com/2289389/56069264-1f3a2700-5d37-11e9-8757-af936d603227.png)

However it makes each line pretty long. Could link text be shortened to:
Documentation
Email Updates / Mailing List
Slack
File an Issue

?

**Comment by grampelberg** [comment]
I like it 👍

**Comment by scottcarol** [comment]
This is still on my list to do after Service UI!
