### ISSUE TITLE
Provide option to disable TLS for connections that don't leave the node

### ISSUE THREAD

**Issue by dwj300** [linkerd/linkerd2#2695]
### What problem are you trying to solve?
We have a requirement to encrypt all connections that leave the node, but not ones that stay within. If we have multiple pods running on the same node, and they are communicating, we shouldn't have to take the (rather small) performance penalty of encrypting and decrypting those connections.

### Any alternatives you've considered?

Encrypting everything is obviously better than encrypting nothing, but we would prefer to have the ability to tune it even more to avoid TLSing connections on the same node.

### How would users interact with this feature?
I assume there would be a flag similar to the `--tls=optional` but with a value of `interNodeOnly` or something similar.

**Comment by alpeb** [comment]
You can do that by disabling identity.
If you're injecting your workloads manually through the CLI, you can do
```
linkerd inject --disable-identity some_workload.yml
```
For pods injected through the proxy auto-injector, this is not supported yet, but tracked in #2540. That issue also tracks disabling identity completely by surfacing the `--disable-identity` flag in `linkerd install`.

**Comment by olix0r** [comment]
@alpeb I think that @dwj300 is looking for an option to disable TLS _only_ when traffic does not leave the node, which isn't unreasonable if you view TLS as purely for privacy, but becomes much more complicated for Identity use cases.  I'll try to write up some more thoughts on the tradeoff...
