### ISSUE TITLE
Don't use spinner in linkerd-cli when run without a tty

### ISSUE THREAD

**Issue by dwj300** [linkerd/linkerd2#2700]
### What problem are you trying to solve?
Our CI machines do not play nice with terminal control characters. 
![image](https://user-images.githubusercontent.com/1051774/56172686-75a99e80-5f9f-11e9-9846-07ad7cd657b3.png)

### How should the problem be solved?
Don't dynamically update the line as linkerd is running its checks when run without a TTY. See how docker solved it here: https://github.com/moby/moby/issues/8342

What do you want to happen? Add any considered drawbacks.

### Any alternatives you've considered?
We have band-aid'ed the problem using sed (`linkerd check | sed -e "s/\x1b\[.\{1,5\}m//g"`) but it is ugly and we now have to look at the exit code of the first command in the pipeline (since sed will always exit with a zero exit code).

Is there another way to solve this problem that isn't as good a solution?

### How would users interact with this feature?
There should be no change from the user's perspective, but without a TTY linkerd should not print control characters.

If you can, explain how users will be able to use this. Maybe some sample CLI
output?

**Comment by aaabramov** [comment]
The same for circleci. Example output:
```
$<3>$<3>
668604fde02e: Pulling fs layer 

$<3>$<3>
a3ed95caeb02: Pulling fs layer 

$<3>$<3>
0435eb261781: Pulling fs layer 

$<3>$<3>
e6f10b71e891: Pulling fs layer 

$<3>$<3>
1741b9f2c912: Pulling fs layer 
```

Fixed with piping to _cat_:
```
      - run:
          name: Push image
          command: |
            echo "Pushing image $IMAGE..."
            docker push "$IMAGE" | cat
```
