### ISSUE TITLE
Introduce a new CLI inject `--advanced` flag

### ISSUE THREAD

**Issue by ihcsim** [linkerd/linkerd2#2711]
Following #2710 , the `inject` command's default behaviour will be changed to only output the annotated YAML. To preserve the ability to output fully injected YAML, introduce a new `--advanced` CLI flag. 

This flag will be used as a 'break the glass' measure, to support users who want to manually inspect or modify the YAML. Auto injection and config override aren't supported for these injected YAMLs.

Part of #2576

**Comment by alpeb** [comment]
Closed via #2721
