### ISSUE TITLE
Move tap service out of the controller pod

### ISSUE THREAD

**Issue by adleong** [linkerd/linkerd2#2712]
In anticipation of tap becoming an APIExtension so that requests to it may be authenticated and authorized, we should split the tap service out of the controller pod.

* The tap pod should serve the TapByResource route of the public API (protobuf over HTTP)
* The public-api service should return a message on the TapByResource route indicating that this has moved.
* The linkerd tap CLI command should make requests to the linkerd-tap service instead of the public-api
* The web process should use a protobuf over HTTP client to make calls to the tap service.

**Comment by dadjeibaah** [comment]
As of #2773, Tap is now in its on pod, however, it is not configured to serve tap events using protobuf over HTTP. That work is being done in this [diff](https://github.com/linkerd/linkerd2/compare/dad/tap-pod-2)

**Comment by kleimkuhler** [comment]
@dadjeibaah Are you still making progress with the branch you linked to above? I'd like to get a better idea of where things stand with respect to the tap service being ready to serve tap events, and what still needs to be wrapped up!

**Comment by dadjeibaah** [comment]
Thanks for checking in @kleimkuhler! The branch I linked above is a rough PR that has tap set up to use the k8s `apiservice`. It also has the CLI stream tap events from the new `apiservice`. Although this needs to be tested thoroughly. The next piece that needs to be implemented is to fix tap in the UI dashboard.

**Comment by kleimkuhler** [comment]
Closed in [tap hardening project](https://github.com/orgs/linkerd/projects/8)
