### ISSUE TITLE
Public API and Destination containers fails to start immediately

### ISSUE THREAD

**Issue by jeremysf** [linkerd/linkerd2#2718]
### What is the issue?
When trying to upgrade linkerd 2.2.1 to 2.3.0 on an Amazon EKS cluster (with no auto inject), the linkerd-controller pod fails to launch with a CrashLoopBackOff.

Ultimately it comes down to the destination pod of the linkerd-controller giving the error:

```
$ kubectl logs linkerd-controller-5f9c6c885-h8pp6 --namespace=linkerd -c destination
time="2019-04-17T22:59:31Z" level=info msg="running version stable-2.3.0"
time="2019-04-17T22:59:31Z" level=fatal msg="Failed to initialize K8s API: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request"
```

### How can it be reproduced?
```curl -sL https://run.linkerd.io/install | sh``` or ```curl -sL https://run.linkerd.io/upgrade | sh``` on my 2.2.1 cluster.

### Logs, error output, etc

https://gist.github.com/jeremysf/f4208c0d88bb4eb9051d9d9bd3a28726

#### `linkerd check` output

```
$ linkerd check --proxy
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ control plane namespace exists
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-api
-----------
× control plane pods are ready
    No running pods for "linkerd-identity"
    see https://linkerd.io/checks/#l5d-api-control-ready for hints

Status check results are ×
```

### Environment

- Kubernetes Version:  v1.11.0
- Cluster Environment: AWS EKS
- Host OS: linux/amd64 on k8s and Mac OS 10.14.4
- Linkerd version: 2.3.1

**Comment by jeremysf** [comment]
Ok, so turns out the issue was a bad metrics server in my EKS cluster. I blew it away and re-installed as per: https://docs.aws.amazon.com/eks/latest/userguide/metrics-server.html and then restarted my linkerd-controller and all is well in linkerd 2.3.0 land! Yay!

**Comment by olix0r** [comment]
Wow, great find @jeremysf.

@grampelberg is this something we can/should be able to add to `check`?

**Comment by grampelberg** [comment]
I don't understand why we require the metrics server at all? Any ideas?

**Comment by olix0r** [comment]
@grampelberg no clue...

At a guess, it must somehow be coming in through:

https://github.com/linkerd/linkerd2/blob/be614656bbed77d2546008522af6a09e701e4321/pkg/k8s/k8s.go#L83-L92
