### ISSUE TITLE
Consider switching the proxy to nightly Rust

### ISSUE THREAD

**Issue by carllerche** [linkerd/linkerd2#2743]
## Feature Request

Consider switching to the nightly Rust compiler for proxy development.

### What problem are you trying to solve?

`async` / `await` syntax is about to be stabilized. Using the syntax early would enable experimentation and start the process of discovering idioms as well as push Tokio / Tower dev forward.

### How should the problem be solved?

Pin the proxy to a specific nightly release of the Rust compiler

What do you want to happen? Add any considered drawbacks.

Nightly is less stable. There are potentially bugs. Async / await syntax may still evolve.

### How would users interact with this feature?

This would only impact proxy development. It would require having the required Rust nightly release in order to compile linkerd2-proxy.

**Comment by olix0r** [comment]
I think we should do this after the current destination/routing changes are released so that we're not changing infrastructure mid-sprint. This seems like something that would be especially good to do while we're at Kubecon.

**Comment by carllerche** [comment]
:+1: I expect the first step will be just switching the build to a recent nightly... nothing should break. Taking that step during Kubecon is a good plan.

**Comment by hawkw** [comment]
I think this is still planned.
