### ISSUE TITLE
Is there a plan to rewrite linkerd2 use rust ?

### ISSUE THREAD

**Issue by Allenyn** [linkerd/linkerd2#2749]
--------------^
Is there a plan to rewrite linkerd2 use rust ? 
---

- Mailing List: https://lists.cncf.io/g/cncf-linkerd-users

- Slack: https://slack.linkerd.io

- Discourse: https://discourse.linkerd.io/

- Twitter: https://twitter.com/linkerd

**Comment by grampelberg** [comment]
There are no plans to rewrite the control plane in rust. It will continue to be in go with the proxy in rust.

Please jump on slack or the mailing list for questions like this, we like to maintain the github issues for features and bug reports.
