### ISSUE TITLE
Lot of broken pipe errors in the linkerd-proxy

### ISSUE THREAD

**Issue by jmirc** [linkerd/linkerd2#2761]
## Bug Report
We disable linkerd in production for now. After upgraded to 2.3.0, we are getting a lot of connections issues. 

### What is the issue?
Here is the error messages we can see in the  linkerd-proxy of all pods where linkerd have been injected.

ERR! [  1838.772665s] proxy={server=out listen=127.0.0.1:4140 remote=10.9.90.58:51878} linkerd2_proxy::app::errors unexpected error: http2 general error: broken pipe
ERR! [  1838.772672s] proxy={server=out listen=127.0.0.1:4140 remote=10.9.90.58:51870} linkerd2_proxy::app::errors unexpected error: http2 general error: broken pipe
ERR! [  1838.772683s] proxy={server=out listen=127.0.0.1:4140 remote=10.9.90.58:51554} linkerd2_proxy::app::errors unexpected error: http2 general error: broken pipe
ERR! [  1838.772691s] proxy={server=out listen=127.0.0.1:4140 remote=10.9.90.58:51918} linkerd2_proxy::app::errors unexpected error: http2 general error: broken pipe
ERR! [  1838.772697s] proxy={server=out listen=127.0.0.1:4140 remote=10.9.90.58:51942} linkerd2_proxy::app::errors unexpected error: http2 general error: broken pipe
INFO [  3729.236571s] proxy={server=out listen=127.0.0.1:4140 remote=10.9.90.58:40930} linkerd2_proxy::proxy::tcp forward connect failure: Timedout(1s)
ERR! [  3958.356635s] proxy={server=out listen=127.0.0.1:4140 remote=10.9.90.58:51918} linkerd2_proxy::app::errors unexpected error: http2 general error: protocol error: stream no longer needed
ERR! [  3958.356671s] proxy={server=out listen=127.0.0.1:4140 remote=10.9.90.58:51870} linkerd2_proxy::app::errors unexpected error: http2 general error: protocol error: stream no longer needed
ERR! [  3958.396357s] proxy={server=out listen=127.0.0.1:4140 remote=10.9.90.58:51918} linkerd2_proxy::app::errors unexpected error: http2 general error: protocol error: stream no longer needed
### Logs, error output, etc

(If the output is long, please create a [gist](https://gist.github.com/) and
paste the link here.)

#### `linkerd check` output

```text
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ control plane namespace exists
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-api
-----------
√ control plane pods are ready
√ control plane self-check
√ [kubernetes] control plane can talk to Kubernetes
√ [prometheus] control plane can talk to Prometheus
√ no invalid service profiles

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ control plane is up-to-date
√ control plane and cli versions match

Status check results are √
```

### Environment

- Kubernetes Version: v1.12.6-eks-d69f1b
- Cluster Environment: (GKE, AKS, kops, ...) - EKS
- Host OS: Amazon Linux 2
- Linkerd version: 2.3.0

**Comment by jmirc** [comment]
Since we removed linkerd in production, our errors rates have been reduced drastically and we improved our success rate. 

TP99 Success Rate

<img width="640" alt="TP99 - success rate" src="https://user-images.githubusercontent.com/50304/56912839-40607e80-6a7e-11e9-9928-c3ba8892d504.png">

TP99 Error Rate
<img width="636" alt="TP99 - errors rate" src="https://user-images.githubusercontent.com/50304/56912840-40607e80-6a7e-11e9-9211-6cea71a53060.png">

**Comment by ihcsim** [comment]
@jmirc Thanks for the updates. A few questions:

* Which version are you upgrading from?
* If you are upgrading from stable-2.2.x, is the YAML output of `linkerd install` consistent with what you'd expect (i.e. any custom configurations from previous installation are captured, by providing the corresponding CLI flags)? 
  * Note that if you are upgrading from edge-19.4.x, you have to use the `linkerd upgrade` command. See upgrade notes [here](https://linkerd.io/2/tasks/upgrade/#upgrade-notice-stable-2-3-0.
* Is this reproducible on other clusters?

**Comment by jmirc** [comment]
I upgraded from edge-19.4.4 and I used the upgrade command.
We only used linkerd in one cluster to prove the value and to see if we will forward with the tool.
In prod, we have a preprod and prod namespaces and I kept the pod deployed in the preprod namespace currently uses linkerd but are not serve production calls. It is for our integration testing. I can do additional tests if you need.

**Comment by jmirc** [comment]
Another view is our SLA (% of error statusCode != 200 / total of request)

<img width="1563" alt="SLA" src="https://user-images.githubusercontent.com/50304/56932420-bdf1b200-6ab1-11e9-99a0-acf13774c9ba.png">

**Comment by olix0r** [comment]
@jmirc Thanks for all of the helpful data.

Can you share more details about the traffic? Is it HTTP/1.0? 1.1? The general request topology?

Any other pertinent details about your environment?

**Comment by jmirc** [comment]
We are using two type of protocol HTTP/1.1 and Grpc. Our tech is Spring Boot, OkHttp, Netty. Our services are deployed on EKS.

**Comment by olix0r** [comment]
Thanks @jmirc -- are you using streaming gRPC methods or long-lived HTTP/1.1 streams?

**Comment by jmirc** [comment]
You're right we are streaming. However, when this problem occurred, it touched  every services integrated with linkerd and not just the service using grpc.

**Comment by hawkw** [comment]
Hi @jmirc, are you able to reproduce this in your staging cluster with the latest edge release (edge-19.5.3)?

**Comment by siggy** [comment]
Hi @jmirc. Just following up, any luck testing/reproducing this with the latest [edge-19.6.3](https://github.com/linkerd/linkerd2/releases/tag/edge-19.6.3)?
