### ISSUE TITLE
How to upgrade the data plane after edge-19.4.5

### ISSUE THREAD

**Issue by alpeb** [linkerd/linkerd2#2775]
Since edge-19.4.5 the only thing `linkerd inject` does is adding the annotation `linkerd.io/inject: enabled`.
After the control plane gets upgraded, in order to upgrade the sidecar proxies we can't do what we used to:
`kubectl -n emojivoto get deploy emoji | linkerd inject - | kubectl apply -f -`
because that won't modify the deployment, so no redeployment will get triggered.

### Use `kubectl rollout restart`
The best solution would be to instruct users to use
`kubectl -n emojivoto rollout restart deploy/emoji`
 but that won't be available till kubernetes v1.15. This will also work for upgrading sidecar proxies whose deployments didn't have any annotation and were only injected because the namespace had the `linkerd.io/inject: enabled` annotation.

### Have `linkerd inject` add a version annotation during injection
Another solution would be to have `linkerd inject` also add an annotation with the version: `linkerd.io/proxy-version: git-abc001`
I didn't do this to begin with, to avoid associating a proxy version when the sidecar hasn't been yet injected at this point, but I guess it's not much of a deal after all. This won't address the case for upgrading sidecar proxies injected because of the namespace annotation.

### Have the proxy injector add the version annotation to the Deployment
Same as the previous solution, but having the proxy injector retrieve the owner resource (usually a Deployment) and add the annotation there. But this will trigger the pod to be redeployed again...
This won't address the case either for upgrading sidecar proxies injected because of the namespace annotation.

**Comment by ihcsim** [comment]
Will recreating the pods work? The proxy injector (if upgraded) should recreate the pods will the new version of the proxy.

**Comment by alpeb** [comment]
Important note about `kubectl rollout restart`: that will require `kubectl` v1.15 on the client, but that still works with older kubernetes versions on the cluster.

> Will recreating the pods work? The proxy injector (if upgraded) should recreate the pods will the new version of the proxy.

Deleting the pods will work, but I'm trying to have a rolling upgrade strategy with no downtime like we currently describe in the docs, which requires hitting the Deployments for them to perform the rollout.

**Comment by alpeb** [comment]
After further discussion we decided to not yet add any other annotation, and for now just document in detail how upgrades should proceed. You can see the doc at linkerd/website#291
