### ISSUE TITLE
Control plane k8s client initialization fails on ServerResources request

### ISSUE THREAD

**Issue by siggy** [linkerd/linkerd2#2780]
## Summary

User reported this error on public-api startup:
```
Failed to initialize K8s API: unable to retrieve the complete list of server APIs: external.metrics.k8s.io/v1beta1: the server could not find the requested resource
```

Source of error is this `Discovery().ServerResources()` request in `ServiceProfilesAccess()`:
https://github.com/linkerd/linkerd2/blob/e5d2460792f04aa0c6a8206db836ce38bbd3f11b/pkg/k8s/authz.go#L56-L59
...which calls into client-go:
https://github.com/kubernetes/client-go/blob/8d9ed539ba3134352c586810e749e58df4e94e4f/discovery/discovery_client.go#L252

## Proposal

The intent of `ServiceProfilesAccess()` is to validate that the ServiceProfile CRD is installed and accessible by the control plane. When a failure occurs in `Discovery().ServerResources()` for individual GroupVersion resources, it still returns a valid `[]*metav1.APIResourceList` for the GroupVersions that succeeded, along with a `ErrGroupDiscoveryFailed` error for the GroupVersions that failed.

Modify `ServiceProfilesAccess()` to gracefully handle `ErrGroupDiscoveryFailed`.

**Comment by olix0r** [comment]
Why are we requesting access for the `external.metrics.k8s.io/v1beta1` API anyway? Are we forced to load APIs that we never use?

**Comment by siggy** [comment]
@olix0r the APi we were calling, `Discovery().ServerResources()` tries to load all APIs.

digging a bit through client-go, there is a `ServerResourcesForGroupVersion` which we may be able to use instead. working on this.
