### ISSUE TITLE
CRD and RBAC checks for linkerd install control-plane

### ISSUE THREAD

**Issue by siggy** [linkerd/linkerd2#2782]
## Background

`linkerd install control-plane` currently checks for namespace existence. With #2765, there now exists an entire category of checks, `LinkerdConfigChecks`, specifically for validating successful installation of `linkerd install config`. This includes checking for namespace, RBAC, and CRD resources.

## Proposal

Modify `linkerd install control-plane` to run all checks in the `LinkerdConfigChecks` category.

Motivated by: https://github.com/linkerd/linkerd2/pull/2772#discussion_r280516795

**Comment by ihcsim** [comment]
Introducing this change will require the user who runs the `linkerd install control-plane` command to have at least `get` and `list` permissions on cluster-scoped resources like cluster roles, cluster role bindings, custom resource definitions, mutating and validating webhook configurations. Not sure if this is desirable.

E.g. on my branch, using a user with permissions to only manage resources in the `linkerd` namespace, the install will fail with:
```
$ bin/go-run cli --kubeconfig=$HOME/.kube/config-test install control-plane
Failed to install control plane: clusterroles.rbac.authorization.k8s.io is forbidden: User "system:serviceaccount:linkerd:fake-user" cannot list resource "clusterroles" in API group "rbac.authorization.k8s.io" at the cluster scope
Please run "linkerd install config -l linkerd | kubectl apply -f -" to rectify the problem. (This requires cluster administration permissions.)
See https://linkerd.io/2/getting-started/ for more information. Or use "--skip-checks" to proceed anyway.
```

**Comment by siggy** [comment]
@ihcsim Good point re: the person executing `linkerd install control-plane` may not, by definition, have `get` and `list` on cluster-scoped resources.

I'm going to close this for now. Going forward we should just be mindful when supporting folks (via slack and docs), that a multi-stage install should be run with checks at each stage:
```bash
linkerd install config | kubectl apply -f -
linkerd check config
linkerd install control-plane | kubectl apply -f -
linkerd check
```
