### ISSUE TITLE
Replace --disable-identity with --disable-tls

### ISSUE THREAD

**Issue by adleong** [linkerd/linkerd2#2783]
Linkerd inject supports a `--disable-identity` flag which prevents the Linkerd proxy from establishing an identity and thus prevents the Linkerd proxy from doing TLS on data plane traffic.  However, the lack of identity prevents the proxy from securely serving administrative services such as tap and metrics.

In order to be able to serve these admin services over TLS, the Linkerd proxy should *always* establish an identity.  I suggest we remove the `--disable-identity` flag.  

To support the use-case where data plane traffic should not be encrypted with TLS, I propose we add a `--disable-tls` flag which prevents the Linkerd proxy from doing TLS on data plane traffic.  However, communication with the control plane should always be secured with TLS, even when `--disable-tls` is set.

**Comment by ihcsim** [comment]
If I follow what @grampelberg was saying yesterday, we can extend the skip ports functionality to the namespace level, instead of introducing another inject flag. That way, identity is still on by default, but user decides which ports don't require TLS.

**Comment by olix0r** [comment]
I'm -1 on calling it disable-tls. I think it would be more accurately called `disable-mesh-traffic-identity` or something less vague

**Comment by alpeb** [comment]
@ihcsim That'd be effectively removing out of the mesh the connections going through that port.

If people ask for a non mTLS'd mesh, it looks like we do need to separate a pod's ability of establishing identity against the control plane from the ability to perform secured connections with other members of the mesh.

**Comment by sbvitok** [comment]
Any news? We need non mTLS'd mesh.

**Comment by hawkw** [comment]
@sbvitok 
> Any news? We need non mTLS'd mesh.

You can get that now using `disable-identity`, if you don't mind also not having mTLS for tap, metrics, etc.

**Comment by sbvitok** [comment]
> @sbvitok
> 
> > Any news? We need non mTLS'd mesh.
> 
> You can get that now using `disable-identity`, if you don't mind also not having mTLS for tap, metrics, etc.

You suggest using service mesh (linkerd), without service mesh?
We need service mesh, with tap, metrics, etc. and without TLS in data plane traffic.

**Comment by hawkw** [comment]
> > @sbvitok
> > > Any news? We need non mTLS'd mesh.
> > 
> > 
> > You can get that now using `disable-identity`, if you don't mind also not having mTLS for tap, metrics, etc.
> 
> You suggest using service mesh (linkerd), without service mesh?
> We need service mesh, with tap, metrics, etc. and without TLS in data plane traffic.

The `disable-identity` option doesn't disable tap or metrics, it _disables mTLS_ for tap and metrics connections as well as for data plane traffic. You can currently run Linkerd without mTLS, using `disable-identity`, and get tap, metrics, and all of Linkerd's other features. 

The change being discussed here is not adding the ability to disable mTLS, which already exists, but adding the ability to disable mTLS _for data plane traffic_ while still encrypting control plane to proxy traffic for tap, metrics, et cetera.

**Comment by sbvitok** [comment]
> The `disable-identity` option doesn't disable tap or metrics

<pre>
[root@mydevkube1 ~]# kubectl get pods
NAME                            READY   STATUS             RESTARTS   AGE
redis-master-5576bfcf76-29hp6   2/2     Running            0          5h46m
tmp-shell                       2/2     Running            0          5h44m
whoami-75b94587d9-45h5r         1/2     CrashLoopBackOff   1          14s
whoami-75b94587d9-ndnqx         2/2     Running            0          5h46m
[root@mydevkube1 ~]# kubectl logs whoami-75b94587d9-45h5r
Error from server (BadRequest): a container name must be specified for pod whoami-75b94587d9-45h5r, choose one of: [whoami linkerd-proxy] or one of the init containers: [linkerd-init]
[root@mydevkube1 ~]# kubectl logs whoami-75b94587d9-45h5r -c linkerd-proxy
ERR! [     0.003051s] linkerd2_proxy::app::config LINKERD2_PROXY_TAP_DISABLED must be set if identity is disabled
configuration error: InvalidEnvVar
[root@mydevkube1 ~]# 
[root@mydevkube1 ~]# kubectl get ns default -o yaml
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    config.linkerd.io/disable-identity: "true"
    linkerd.io/inject: enabled

</pre>

**Comment by grampelberg** [comment]
@sbvitok what are you trying to show off? Looks correct to me.

**Comment by sbvitok** [comment]
> @sbvitok what are you trying to show off? Looks correct to me.
@hawkw say:
> The `disable-identity` option doesn't disable tap
But error message says that it is not true
<pre>
linkerd2_proxy::app::config LINKERD2_PROXY_TAP_DISABLED must be set if identity is disabled
</pre>

**Comment by grampelberg** [comment]
Ahh, `disable-identity` definitely disables tap because we're unable to authenticate without it. Linkerd is *not* meant to be run without identity and disabling it it more there for debugging issues than actual real world usage.

**Comment by sbvitok** [comment]
So we need non mTLS'd mesh in data plane traffic)

**Comment by grampelberg** [comment]
Can you explain why a little bit more?

**Comment by sbvitok** [comment]
Cpu time spent on TLS encryption in data plane traffic is very expensive for high load systems.
mTLS on: 2017/rps
mTLS off: 2217/rps (disable-identity, disable-tap)

**Comment by grampelberg** [comment]
Makes sense! Sounds like you've got what you wanted working. As identity is pretty important for most of the higher level features we're working on right now, it is likely that you'll be opting out of those in preference of performance. Luckily, that's a tradeoff you can make!

**Comment by sbvitok** [comment]
> Sounds like you've got what you wanted working

Nope. I want no TLS in data plane traffic and don't disable-tap

**Comment by phxql** [comment]
> Ahh, `disable-identity` definitely disables tap because we're unable to authenticate without it. Linkerd is _not_ meant to be run without identity and disabling it it more there for debugging issues than actual real world usage.

So to clarify: can i use disable-identity in production and just live without tap or will this seriously harm the workloads?

**Comment by grampelberg** [comment]
@phxql it won't seriously harm the workloads. The biggest caveat is that we're not testing this path and there's no guarantee it'll keep working in the future.

**Comment by phxql** [comment]
Okay, thanks!

**Comment by jennydaman** [comment]
Hi, just stumbling across this ancient issue. Sorry to bother everyone.

It seems like `--disable-identity` is no longer supported.

https://github.com/linkerd/linkerd2/blob/70f0fdb39816fa22d3c13fff9366ca638a7edc1a/cli/cmd/options.go#L460

Is there any way to disable mTLS for the current version of Linkerd?

**Comment by adleong** [comment]
Hi @jennydaman, no there is not.  mTLS cannot be disabled.

**Comment by laivu266** [comment]
Hi @adleong, there is any side effect if mTLS failed to check?
I got the log from sidecar
`linkerd_app_core::serve: Connection closed error=TLS detection timed out client.addr=<clientip>:43278 server.addr=<serverip>:8443`

**Comment by adleong** [comment]
@laivu266 if TLS detection times out then the connection will be closed.  That is what the log message you posted indicates.
