### ISSUE TITLE
proxy: Buffers can leak defunct inner services

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#2795]
The proxy buffers requests in several places, especially when routing requests. These buffers are composed with layers like `Router -> Buffer -> Route`; though, the buffer layer is actually two distinct layers, separated by a channel. The "inside" (Route-side) of the stack is owned by the executor and the "outside" (Router-side) of the stack may be cloned and queue requests into the task.

Consider the case where the following happens:
1. `Route` is unavailable and returns `NotReady`.
2. Requests are routed and buffered.
3. The `Router` drops this route.

At this point, the inner buffer worker has a channel that has requests on it and is unable to dispatch them to the internal service. If it finished consuming the buffered requests, it would be informed that the senders were released and it would be able to shutdown. However, the whole buffer is basically leaked into the executor if the internal service never consumes the rest of the requests!

https://github.com/linkerd/linkerd2-proxy/pull/246 treats one of the symptoms of this bug -- timing out response futures if the request is not dequeued at least prevents clients from seeing requests hang forever; But it doesn't address the underlying leak of the inner stack.

This can be especially egregious if the inner stack is driving service discovery resolutions, etc.

**Comment by carllerche** [comment]
The issue, as I understand it, occurs when all `Buffer` clones are dropped **and** all pending response futures are dropped. In this case, the request themselves remain queued in the buffer indefinitely.

One solution would be for the buffer's worker to peek at the request queue and check if the request at the head of the queue is canceled. If it is, drop it. In the situation described above, this will result in the queue being drained.

**Comment by seanmonstar** [comment]
> One solution would be for the buffer's worker to peek at the request queue and check if the request at the head of the queue is canceled. If it is, drop it.

We already do exactly that: https://github.com/tower-rs/tower/blob/4d6d2c8572cc6012872743603f57a187ac229b5d/tower-buffer/src/worker.rs#L95

**Comment by carllerche** [comment]
@seanmonstar that is checking if the channel itself is closed (all tx handles dropped).

I am suggesting peaking at the request at the head of the queue and calling `poll_cancel` on [this](https://github.com/tower-rs/tower/blob/4d6d2c8572cc6012872743603f57a187ac229b5d/tower-buffer/src/message.rs#L8).

**Comment by olix0r** [comment]
Oddly enough, the comment references `poll_cancel` but the code calls `poll_close`

https://github.com/tower-rs/tower/blob/4d6d2c8572cc6012872743603f57a187ac229b5d/tower-buffer/src/worker.rs#L92-L95

We should probably get more data to validate this hypothesis... I'm just reasoning about a leak I observe. I don't yet have hard proof that the buffers are the culprit, but it seemed like a promising lead.

**Comment by carllerche** [comment]
@olix0r oops. `poll_cancel` was the old name...

**Comment by seanmonstar** [comment]
> that is checking if the channel itself is closed (all tx handles dropped).

No, that's checking `msg.tx`, which is the [oneshot](https://github.com/tower-rs/tower/blob/4d6d2c8572cc6012872743603f57a187ac229b5d/tower-buffer/src/message.rs#L12) sender. So, it's checking if interest *that specific future* is still wanted.

**Comment by olix0r** [comment]
Okay, so my understanding is that the leak described by this issue _is_ currently present in the proxy, because outer response future are never canceled. But that leak _should_ be resolved by https://github.com/linkerd/linkerd2-proxy/pull/246.
