### ISSUE TITLE
Proxy tests should have all settings configuration go through the normal settings parser

### ISSUE THREAD

**Issue by briansmith** [linkerd/linkerd2#28]
In proxy/tests/support/proxy.rs we have:

```rust
    // TODO: We currently can't use `config::ENV_METRICS_FLUSH_INTERVAL_SECS`
    // because we need to be able to set the flush interval to a fraction of a
    // second. We should change config::ENV_METRICS_FLUSH_INTERVAL_SECS so that
    // it can support this.
```

This issue is about addressing that TODO. I suggest we implement #27 and then set the flush interval to whatever number of milliseconds is needed in the test harness.

**Comment by hawkw** [comment]
I believe this may have already been fixed by  #909?
