### ISSUE TITLE
linkerd-cni: Ensure UID matches between proxy container and iptables rules

### ISSUE THREAD

**Issue by codeman9** [linkerd/linkerd2#2812]
### What problem are you trying to solve?
Using the install-cni plugin, we need to choose a `--proxy-uid` during the `linkerd install-cni` command. Also, when installing linkerd with the `linkerd install` command, we are allowed to choose a `--proxy-uid`. In our particular case, we chose 2 different values and this meant that the iptables rules were not correct.

### How should the problem be solved?
Currently, the linkerd-cni plugin retrieves a podspec for every pod that is being initialized. It looks to see if the podspec has a `linkerd-proxy` container. Also, this podspec contains the `runAsUser` with the particular value that was configured during `linkerd install` within the `securityContext` section. The suggestion is to use this value as the UID for the iptables. This would defer the configuration of the linkerd-cni plugin for this UID value to runtime instead of install time ensuring that these 2 values will always be in sync.

Reading more of the podspec will increase the processing time for the linkerd-cni plugin, but I expect this to be minimal. We are already parsing the podspec and looking at some values this would just add another read.

### Any alternatives you've considered?
I considered somehow having the linkerd-cni plugin ask the control plane but it wasn't clear how to make that happen. Maybe through grpc? But the linkerd-cni plugin operates at the node level, so it isn't clear to me how to get the requests routing properly.

### How would users interact with this feature?
Users will no longer need to provide a `--proxy-uid` during `linkerd install-cni`, this flag will be removed. In fact, there are a few more flags that could be removed in the future with another issue/PR. This PR is specifically for the proxy UID.

**Comment by codeman9** [comment]
If possible, we'd like to take this issue.

**Comment by olix0r** [comment]
@codeman9 yes, please do!
