### ISSUE TITLE
Improve controller log level validation

### ISSUE THREAD

**Issue by adleong** [linkerd/linkerd2#2823]
The `linkerd install` command performs validation of the `--controller-log-level` flag to ensure only valid log levels are passed in.  However, Prometheus has stricter requirements on the log level string and requires that it be lowercase.  Passing `DEBUG` as the value passes Linkerd's validation, but the Prometheus container fails with:

```
$ k logs -n linkerd linkerd-prometheus-cd49d97f9-27mqq prometheus
Error parsing commandline arguments: unrecognized log level "DEBUG"
```

We should tighten the validation to require that the log level be lowercase, or else convert it to lowercase before passing to Prometheus.

**Comment by d-baranowski** [comment]
I'd like to work on this.

**Comment by klingerf** [comment]
@d-baranowski Sounds good -- let us know if you have any issues getting started.

**Comment by d-baranowski** [comment]
Let me know if anything needs improving.
