### ISSUE TITLE
How to run in a non-k8s environment

### ISSUE THREAD

**Issue by wellorange** [linkerd/linkerd2#2830]
I started to contact this project, I want to run on my ubuntu computer just as a proxy, what should I do?
For the envoy project, I can run like this:
```
./envoy -c config.yaml
```

How can I run this in linkerd2?

**Comment by siggy** [comment]
@wellorange Linkerd2 is k8s-only. take a look at Linkerd1: https://linkerd.io/choose-your-platform/

Closing this, for support, check out the [Linkerd1 docs](https://linkerd.io/1/overview/) or hop into [Linkerd Slack](https://slack.linkerd.io).
