### ISSUE TITLE
linkerd2-proxy: how to set the proxy address

### ISSUE THREAD

**Issue by detailyang** [linkerd/linkerd2#2832]
Hello

I'm benchmarking the linkerd2-proxy and nginx in HTTP.

After `make build` for [https://github.com/linkerd/linkerd2-proxy](https://github.com/linkerd/linkerd2-proxy), just
want to test the HTTP benchmark on non-k8s env.

There are two questions confused me
    1. What's the default HTTP listener address (0.0.0.0:4143) ?
    2. What's the default HTTP proxy address?

Or are there any way to configure it (checkout the rust codebase and i know it's controlled by env)?

Many thanks

**Comment by grampelberg** [comment]
@detailyang please join [slack](https://slack.linkerd.io/) to ask questions. For now, it is possible to run the proxy outside of k8s, just super unsupported. We can help you out in slack.
