### ISSUE TITLE
Add global Namespace Selector to linkerd Dashboard

### ISSUE THREAD

**Issue by christianhuening** [linkerd/linkerd2#2838]
### What problem are you trying to solve?

In multi-tenancy clusters with Linkerd2 and a namespace per tenant the dashboard is quite crowded with entries. It is somewhat difficult to navigate it when you have 50+ namespaces. Usually the search goes by Customer/Namespace->Application

### How should the problem be solved?

Add a Namespace selector to the top of the dashboard, so that a user can directly select a namespace and filter all shown elements in sub-pages to those from that namespace

### Any alternatives you've considered?

nope

### How would users interact with this feature?

with their mouse ;-)

**Comment by scottcarol** [comment]
Hey @christianhuening, thanks for this feature request! Can you add a screenshot of what the dashboard looks like for you now with 50+ namespaces?

**Comment by olix0r** [comment]
@scottcarol i expect that their namespaces are named after their tenants, which they probably don't want to share with the world, but it should be pretty simple to replicate for yourself with something like:

```
:; for i in $(seq 100) ; do kubectl create ns sup-$i ; done
```

If we need to inject a pod, we can probably modify that script to do that as well.

**Comment by christianhuening** [comment]
Thanks Oliver, that’s the case. If you want I can stop by the booth today and show it?!

**Comment by grampelberg** [comment]
A redacted screenshot would be super valuable!

**Comment by scottcarol** [comment]
Hey @christianhuening, thanks again for creating this great issue earlier this year!

We've redesigned our dashboard sidebar as of `edge-19.9.4` and it has the namespace selector you requested. Have you had a chance to upgrade to [the latest edge release of Linkerd](https://linkerd.io/2/edge/)? We'd love to know if the dashboard is more useful to you now.

**Comment by christianhuening** [comment]
@scottcarol yes, the UX has greatly improved, i am very pleased with the outcome! Thanks a lot!
