### ISSUE TITLE
Support setting FailurePolicy of proxy injector webhook

### ISSUE THREAD

**Issue by annismckenzie** [linkerd/linkerd2#2852]
## Feature Request
Support specifying the failure policy of the proxy injector webhook during `linkerd install` and `linkerd upgrade`.

### What problem are you trying to solve?
We'd like to prevent deployments of apps, especially when things go wrong (node on which the proxy injector webhook runs is partitioned from the rest of the cluster and a failing node's pods being rescheduled onto healthy nodes), to result in non-meshed applications.

### How should the problem be solved?
Optionally allow configuring the failure policy of the proxy injector webhook during the control plane installation/upgrade.

### Any alternatives you've considered?

We're using kustomize so we can just patch the webhook configuration manifest now that #2806 has landed but not everyone does so it'd be nice to be able to pass it.

### How would users interact with this feature?
```
linkerd install --proxy-injector-failure-policy=fail | kubectl apply -f -
```

**Comment by olix0r** [comment]
I wonder if there's a good reason not to _always_ set this failure policy? It seems like the most desirable behavior, at least when `--ha` is used for installation.

**Comment by annismckenzie** [comment]
Indeed, that should be the default in the HA case!

**Comment by grampelberg** [comment]
I'm +1 to @olix0r's suggestion to turn it on by default `--ha`. For now, I'd prefer to keep from adding one more configuration option as a separate item though.

**Comment by alpeb** [comment]
I'm having some trouble implementing this. Given all the resources are persisted at once during install, the order in which they are ready is not deterministic. From my testing, it's frequent that the the webhook config is persisted before the proxy injector. So we end up with a chicken-and-egg situation: the proxy injector can't start because the webhook config is forcing it to go through the proxy injector itself which isn't ready yet.

This only happens when the failure policy is `Fail`. And no matter how the yamls are arranged (e.g. putting the webhook config at last), this happens sometimes.

The only way around this that I can think of now would be to have an extra command (or `install` sub-command) to set this policy _after_ the control plane is ready.

**Comment by olix0r** [comment]
@alpeb I suppose the alternative would be for the proxy-injector to be installed as part of the phase-0 (cluster role bindinsg etc)? But that sounds likely to be complicated as well.

I agree that this probably makes most sense as something that is configured after/outside of installation. Perhaps only as a part of upgrade? But we'll need to be especially sensitive to the various ways a cluster can get into a stuck state if it loses all of the proxy injectors...

**Comment by alpeb** [comment]
> @alpeb I suppose the alternative would be for the proxy-injector to be installed as part of the phase-0 (cluster role bindinsg etc)?

That'd work but it'd mean that when installing with `--ha` the single-step install wouldn't be allowed.
Also the webhook config would be installed in the second step, but that step is supposed to be only for namespace-level privileges.

I like the upgrade option. It would only update the webhook config resource, so I don't see how it would affect the proxy injectors. I'll explore that and report back.

**Comment by olix0r** [comment]
> I like the upgrade option. It would only update the webhook config resource, so I don't see how it would affect the proxy injectors. I'll explore that and report back.

I think the risk would be if you did an actual controlplane upgrade while changing this configuration... though that's something we could prevent in code... i.e. only permit changing this configuration when (1) the control plane is healthy (i.e. check passes) and (2) the config version matches the CLI version.

**Comment by alpeb** [comment]
@ihcsim made me realize we can avoid the timing issues by just having the mutating webhook config act on namespaces other than linkerd. The pods in the linkerd namespace are already injected in the output produced by `linkerd install` and don't require auto injection anyways.

For this we need to add a label into the linkerd namespace and a namespaceSelector in the webhook config to filter out that label.

**Comment by annismckenzie** [comment]
Great to see this implemented – thank you!
