### ISSUE TITLE
Support SMI traffic split API

### ISSUE THREAD

**Issue by adleong** [linkerd/linkerd2#2855]
Linkerd should implement the [SMI traffic split API](https://github.com/deislabs/smi-spec/blob/master/traffic-split.md) by keeping a watch on the traffic split CRD and routing traffic accordingly.

**Comment by wxdao** [comment]
Will it support A/B testing? i.e traffic split based on headers/cookies.

**Comment by grampelberg** [comment]
@wxdao not currently, please open an issue in https://github.com/deislabs/smi-spec to track adding that functionality to TrafficSplit.

**Comment by adleong** [comment]
Fixed by #2931
