### ISSUE TITLE
Check does not detect invalid webhook

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#2861]
I tried to install two linkerd control planes. The latter install overwrote the `mutatingwebhookconfigurations` object for the prior install. Then, after removing the latter install, `kubectl check` passes despite the fact that the mutatingwebhookconfigurations refers to the wrong namespace:

```
:; kubectl get -o yaml mutatingwebhookconfigurations linkerd-proxy-injector-webhook-config          
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: 2019-05-29T17:07:47Z
  generation: 1
  labels:
    linkerd.io/control-plane-component: proxy-injector
  name: linkerd-proxy-injector-webhook-config
  resourceVersion: "4493328"
  selfLink: /apis/admissionregistration.k8s.io/v1beta1/mutatingwebhookconfigurations/linkerd-proxy-injector-webhook-config
  uid: 4890d0ed-8234-11e9-819d-2ec9541d5fbf
webhooks:
- clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJjekNDQVJtZ0F3SUJBZ0lCQVRBS0JnZ3Foa2pPUFFRREFqQWhNUjh3SFFZRFZRUURFeFpzYVc1clpYSmsKTFhCeWIzaDVMV2x1YW1WamRHOXlNQjRYRFRFNU1EVXlPVEUzTURjek4xb1hEVEl3TURVeU9ERTNNRGMxTjFvdwpJVEVmTUIwR0ExVUVBeE1XYkdsdWEyVnlaQzF3Y205NGVTMXBibXBsWTNSdmNqQlpNQk1HQnlxR1NNNDlBZ0VHCkNDcUdTTTQ5QXdFSEEwSUFCRHFzWFBBdno4RTRmWjVmNmJGU0pIa0wyUEEveDJEZ3lwbGc4ZUEyMFpSZEpzNXIKeTJRNkZpSGg3WlJka3FsK1I0ZlhQR1EzRjFhVzN5RThaRVkxdUZDalFqQkFNQTRHQTFVZER3RUIvd1FFQXdJQgpCakFkQmdOVkhTVUVGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd0R3WURWUjBUQVFIL0JBVXdBd0VCCi96QUtCZ2dxaGtqT1BRUURBZ05JQURCRkFpRUF5Q1lIYU1YTUthdVgwaVZTTk1YcGpSUHdFSU44OXl1dUlZVVIKeEN5SktsOENJQ01ZVXFyVnRjbm5odDBNTHBzMFpUdkkxS3ZwSit3VllqN1pPdEdkaHlQVAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    service:
      name: linkerd-proxy-injector
      namespace: linkerd-h2
      path: /
  failurePolicy: Ignore
  name: linkerd-proxy-injector.linkerd.io
  namespaceSelector: {}
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods
  sideEffects: Unknown
```

I think check should read the `mutatingwebhookconfigurations` object to ensure that it matches the control plane's namespace. `Install` should perhaps fail to overwrite an existing `mutatingwebhookconfigurations`.

It also seems that we may want to include the linkerd namespace in the object name to prevent collision?

**Comment by ihcsim** [comment]
Re changing the object name to include the linkerd namespace, it will cause an one-off problem during upgrade, where a new webhook config object is being created, without replacing the existing one (which is created by the proxy injector at runtime). This will cause contention between the CA bundles of the two config objects.

**Comment by klingerf** [comment]
Jumping in with a related thought:

Now that the proxy injector MWC is a required part of the control plane install, I'm not sure we can support running multiple control planes in the same cluster. Even if we change the name of the MWC so that two are created, that will lead to non-deterministic behavior when injecting pods.

For instance, if we permit two MWCs to be created, then that will result in both proxy injectors being called whenever a new pod is created. How do we know which proxy injector is supposed to inject the pod? There's nothing in the pod spec that tells us to which control plane it's being added. As its currently written, whichever proxy injector receives the pod first (non-deterministic, as far as I know) will end up injecting the proxy, and the other proxy injector will skip the pod because it's already injected at that point.

To fix this, we could rename the MWCs as suggested, and also require another pod spec annotation / namespace annotation that tells us the control plane namespace to which the pod belongs. Or we could disallow multiple Linkerd installs per cluster. The current behavior of clobbering the existing MWC is problematic for the reasons already indicated.

**Comment by ihcsim** [comment]
The MWC determines its proxy injector by examining its [`service` setting](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.14/#webhookclientconfig-v1beta1-admissionregistration-k8s-io), which corresponds to the `Service` resource that fronts the proxy injector pod. As long as they belong to different namespaces, it shouldn't be a problem.

Interestingly, in HA mode, despite of having a `Service` resource in front of all the proxy injector replicas, the load balancing didn't happen as expected. All the admission requests were sent to only one replica, until it dies, then another replica is automatically selected.

I think in a multi control plane setup, the more problematic resources would be the cluster roles, cluster role bindings and CRD.

**Comment by olix0r** [comment]
> How do we know which proxy injector is supposed to inject the pod? 

`inject` would have to set an annotation that references the control plane namespace (as would the namespace-level attributes)

**Comment by ihcsim** [comment]
ah...ok. I see what you mean now. There are no ways for the k8s API Server to know which webhook to call, or not to call. It will end up calling all of them!

**Comment by alpeb** [comment]
We actually can have a single webhook config, with multiple entries under `webhooks`, each one with a different `webhooks.name`, and with a `wehbooks.namespaceSelector` pointing to some label that, as you pointed out, will have to be added into each namespace being injected.

The additional `webhooks` entries can be added through `kubectl patch`, so we'll have to figure how to integrate that into the install/update workflow.

Here's a sample of a webhook config for control planes in `linkerd` and `linkerd2`. I tied them to two separate emojivoto namespaces, each one holding a label `linkerd.io/namespace: linkerd|linkerd2`. Proxy auto-injection seemed to work fine for both:
```
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"admissionregistration.k8s.io/v1beta1","kind":"MutatingWebhookConfiguration","metadata":{"annotations":{},"labels":{"linkerd.io/control-plane-component":"proxy-injector"},"name":"linkerd-proxy-injector-webhook-config"},"webhooks":[{"clientConfig":{"caBundle":"LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJpekNDQVRHZ0F3SUJBZ0lCQVRBS0JnZ3Foa2pPUFFRREFqQXRNU3N3S1FZRFZRUURFeUpzYVc1clpYSmsKTFhCeWIzaDVMV2x1YW1WamRHOXlMbXhwYm10bGNtUXVjM1pqTUI0WERURTVNRFV5T1RJek1qY3hORm9YRFRJdwpNRFV5T0RJek1qY3pORm93TFRFck1Da0dBMVVFQXhNaWJHbHVhMlZ5WkMxd2NtOTRlUzFwYm1wbFkzUnZjaTVzCmFXNXJaWEprTG5OMll6QlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJEVlYwUkV2SHA3MHczTzkKV0grbG82bllaVFZWV3NkcS9aaFdqcDlYM0ErRmw5OC9TNlVtaUhFZXZnb1EvNkEyaU15Y2xSVnZJWmRoNTB4ZgpTYTcrVmRHalFqQkFNQTRHQTFVZER3RUIvd1FFQXdJQkJqQWRCZ05WSFNVRUZqQVVCZ2dyQmdFRkJRY0RBUVlJCkt3WUJCUVVIQXdJd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBS0JnZ3Foa2pPUFFRREFnTklBREJGQWlBYXIvZ0YKZjB0TnJld25CZW5qckN6eHovNXdjS0Y2ZitYUXIxeDRENXZaMndJaEFKRjVodVR5bHlDM1VTZ2xKWDVFUTVJRAptOXJUR2R1bEMyZXRFQ2F2NG1TRwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==","service":{"name":"linkerd-proxy-injector","namespace":"linkerd","path":"/"}},"name":"linkerd-proxy-injector.linkerd.io","namespaceSelector":{"matchLabels":{"linkerd.io/namespace":"linkerd"}},"rules":[{"apiGroups":[""],"apiVersions":["v1"],"operations":["CREATE","UPDATE"],"resources":["pods"]}]}]}                                                                                                                                                   
  creationTimestamp: "2019-05-29T16:19:57Z"
  generation: 17
  labels:
    linkerd.io/control-plane-component: proxy-injector
  name: linkerd-proxy-injector-webhook-config
  resourceVersion: "63858"
  selfLink: /apis/admissionregistration.k8s.io/v1beta1/mutatingwebhookconfigurations/linkerd-proxy-injector-webhook-config
  uid: 99dd1517-822d-11e9-a370-0800276d226e
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJqakNDQVRPZ0F3SUJBZ0lCQVRBS0JnZ3Foa2pPUFFRREFqQXVNU3d3S2dZRFZRUURFeU5zYVc1clpYSmsKTFhCeWIzaDVMV2x1YW1WamRHOXlMbXhwYm10bGNtUXlMbk4yWXpBZUZ3MHhPVEExTWpreU16RXpNRGRhRncweQpNREExTWpneU16RXpNamRhTUM0eExEQXFCZ05WQkFNVEkyeHBibXRsY21RdGNISnZlSGt0YVc1cVpXTjBiM0l1CmJHbHVhMlZ5WkRJdWMzWmpNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBEQVFjRFFnQUVwQ2hOUGJGRFR5b1gKY2VUOTc2NjRER0ZvM3FXV1prVDlZVnBjRkZGZVRCUkhBdDFDNzFBVXBrSVl1a3c1MFdNbUR3LzdnVytVNzgyMAp4NzFWOU1WR1o2TkNNRUF3RGdZRFZSMFBBUUgvQkFRREFnRUdNQjBHQTFVZEpRUVdNQlFHQ0NzR0FRVUZCd01CCkJnZ3JCZ0VGQlFjREFqQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01Bb0dDQ3FHU000OUJBTUNBMGtBTUVZQ0lRQ3QKMmQ3TzFDWE9XYjdiL3hSQ2x2L3NicDE4UThEY3FoSUZUS21KcGVUQU13SWhBSnUrVGV5dS9laC82T2pWRVcxaAp6UWM4UjcycWNGUVlzNnBQNWlCNDVzM1MKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    service:
      name: linkerd-proxy-injector
      namespace: linkerd2
      path: /
  failurePolicy: Ignore
  name: linkerd2-proxy-injector.linkerd.io
  namespaceSelector:
    matchLabels:
      linkerd.io/namespace: linkerd2
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods
    scope: '*'
  sideEffects: Unknown
  timeoutSeconds: 30
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJpekNDQVRHZ0F3SUJBZ0lCQVRBS0JnZ3Foa2pPUFFRREFqQXRNU3N3S1FZRFZRUURFeUpzYVc1clpYSmsKTFhCeWIzaDVMV2x1YW1WamRHOXlMbXhwYm10bGNtUXVjM1pqTUI0WERURTVNRFV5T1RJek1qY3hORm9YRFRJdwpNRFV5T0RJek1qY3pORm93TFRFck1Da0dBMVVFQXhNaWJHbHVhMlZ5WkMxd2NtOTRlUzFwYm1wbFkzUnZjaTVzCmFXNXJaWEprTG5OMll6QlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJEVlYwUkV2SHA3MHczTzkKV0grbG82bllaVFZWV3NkcS9aaFdqcDlYM0ErRmw5OC9TNlVtaUhFZXZnb1EvNkEyaU15Y2xSVnZJWmRoNTB4ZgpTYTcrVmRHalFqQkFNQTRHQTFVZER3RUIvd1FFQXdJQkJqQWRCZ05WSFNVRUZqQVVCZ2dyQmdFRkJRY0RBUVlJCkt3WUJCUVVIQXdJd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBS0JnZ3Foa2pPUFFRREFnTklBREJGQWlBYXIvZ0YKZjB0TnJld25CZW5qckN6eHovNXdjS0Y2ZitYUXIxeDRENXZaMndJaEFKRjVodVR5bHlDM1VTZ2xKWDVFUTVJRAptOXJUR2R1bEMyZXRFQ2F2NG1TRwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    service:
      name: linkerd-proxy-injector
      namespace: linkerd
      path: /
  failurePolicy: Ignore
  name: linkerd-proxy-injector.linkerd.io
  namespaceSelector:
    matchLabels:
      linkerd.io/namespace: linkerd
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods
    scope: '*'
  sideEffects: Unknown
  timeoutSeconds: 30
```

**Comment by alpeb** [comment]
... or, to avoid having to rely on `kubectl patch`, we can still have multiple webhook configs, named differently, as long as their `wehbooks.namespaceSelector` is properly set alongside with the corresponding labels in the injected namespaces.

As for the one-off upgrade issue @ihcsim mentioned, we could replace the pre-2.4 webhook config with a dummy one with no entries under `webhooks`, or provide special instructions in the upgrade notes for people to manually delete it.

**Comment by alpeb** [comment]
Superseded by #2912 and #2905
