### ISSUE TITLE
linkerd upgrade should allow setting control plane versions

### ISSUE THREAD

**Issue by hawkw** [linkerd/linkerd2#2864]
### What problem are you trying to solve?

Currently, the `linkerd upgrade` command has a `-v` flag which allows setting the proxy version to upgrade to. However, the rest of the linkerd installation --- control plane components, proxy init container, etc --- are all upgraded to the CLI executable's hardcoded version. 

There are a couple of problems with this:
1. When the CLI is built separately from the rest of the control plane, and has its version set to one where there are no published images, running `linkerd upgrade` will upgrade the control plane and proxy init containers to the CLI binary's version. This basically breaks the entire linkerd installation, since the proxy-init container cannot be pulled, so all injected pods will be in a bad state.
2. Tasks like testing an issue across multiple linkerd versions require managing separate CLI binaries for each version being tested

### How should the problem be solved?

It would be nice if there was a flag for setting the control plane version, or if `-v` set the control plane as well as the proxy version.

**Comment by ihcsim** [comment]
The `upgrade` command does support a hidden `--control-plane-version` option. (We hid it because it was meant for development purposes only.)

```
# master HEAD
$ bin/linkerd version --client
Client version: git-031cd9d4

$ bin/linkerd upgrade --control-plane-version=2.3.0|grep ":2.3.0"

√ You're on your way to upgrading Linkerd!
Visit this URL for further instructions: https://linkerd.io/upgrade/#nextsteps

        image: gcr.io/linkerd-io/controller:2.3.0
        image: gcr.io/linkerd-io/proxy-init:2.3.0
        image: gcr.io/linkerd-io/controller:2.3.0
        image: gcr.io/linkerd-io/controller:2.3.0
        image: gcr.io/linkerd-io/proxy-init:2.3.0
        image: gcr.io/linkerd-io/web:2.3.0
        image: gcr.io/linkerd-io/proxy-init:2.3.0
        image: gcr.io/linkerd-io/proxy-init:2.3.0
        image: gcr.io/linkerd-io/grafana:2.3.0
        image: gcr.io/linkerd-io/proxy-init:2.3.0
        image: gcr.io/linkerd-io/controller:2.3.0
        image: gcr.io/linkerd-io/proxy-init:2.3.0
        image: gcr.io/linkerd-io/controller:2.3.0
        image: gcr.io/linkerd-io/proxy-init:2.3.0
        image: gcr.io/linkerd-io/controller:2.3.0
        image: gcr.io/linkerd-io/proxy-init:2.3.0
```

**Comment by hawkw** [comment]
@ihcsim Oh, fantastic, that solves all my problems! Thanks!
