### ISSUE TITLE
Show pod status in linkerd check

### ISSUE THREAD

**Issue by adleong** [linkerd/linkerd2#2877]
When there is a problem bringing up controller pods, Linkerd check will wait at this step:

```
| controller pod is running -- waiting for check to complete
```

It can be unclear if I need to continue waiting, or if there is some underlying problem I need to correct.  By looking at `kubectl get pods` I can see that my controller pods are in `Init:ImagePullBackOff` which tells me the image can't be found.  By including that pod status in the check message, I will know immediately that I need to take action.

Similarly, seeing the pod status during the "waiting for controller pods to become ready" step can be useful as well, since it can show if the pods are in CrashLoopBackoff.

**Comment by vaibhavsingh97** [comment]
Hi @adleong, I would love to take this issue. Since I am new to this community, will try to setup Linkerd2, and will update here with necessary steps before creating PR, and will send PR respectively.

**Comment by adleong** [comment]
Hi @vaibhavsingh97, welcome!  How is this going?  Please let me know if I can help at all.

**Comment by adleong** [comment]
@vaibhavsingh97 are you still interested in working on this?

**Comment by vaibhavsingh97** [comment]
Yes, I am still interested. I was just setting up linkerd locally

**Comment by adleong** [comment]
Great!  Let me know if you have any questions
