### ISSUE TITLE
Linkerd proxy changes http request header names to lower case

### ISSUE THREAD

**Issue by thojkooi** [linkerd/linkerd2#2878]
### What is the issue?

Linkerd-proxy changes all HTTP headers to be lower cases. While the [RFC](https://tools.ietf.org/html/rfc7230#section-3.2) states that header keys should be case insensitive, I think that linkerd-proxy should not modify the casing of the header names given the "no code change required" bit.

Note that header values are not modified and remain their original values.

### How can it be reproduced?

1. Start two deployments; one without linkerd and one with. 
2. Use `curl -sD - -o /dev/null http://<endpoint>` to collect the response headers. I ran this from the host machine.
3. Compare output with and without linkerd.

The same can also be done by spawning a shell in the pod and running the same command against the pod's IP or `127.0.0.1` vs a service that the pod runs behind.

### Logs, error output, etc

```bash
$ k get pods -o wide
NAME                              READY   STATUS    RESTARTS   AGE    IP               NODE        NOMINATED NODE   READINESS GATES
non-linkerd-64499456d6-hf4zm      1/1     Running   0          3d9h   192.168.96.101   worker-01   <none>           <none>
linkerd-757646fd4c-lrd4m          2/2     Running   0          3d1h   192.168.0.134    worker-01   <none>           <none>
```

```bash
# with linkerd
curl -sD - -o /dev/null http://192.168.0.134
HTTP/1.1 200 OK
server: nginx
date: Sat, 01 Jun 2019 17:20:03 GMT
content-type: text/html
content-length: 6969
last-modified: Fri, 08 Mar 2019 19:14:12 GMT
accept-ranges: bytes
etag: "5c82bf04-1b39"
x-frame-options: SAMEORIGIN
x-content-type-options: nosniff
x-xss-protection: 1; mode=block

# without linkerd
curl -sD - -o /dev/null http://192.168.96.101
HTTP/1.1 200 OK
Server: nginx
Date: Sat, 01 Jun 2019 17:20:18 GMT
Content-Type: text/html
Content-Length: 6969
Last-Modified: Fri, 08 Mar 2019 19:14:12 GMT
Connection: keep-alive
ETag: "5c82bf04-1b39"
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Accept-Ranges: bytes
```

#### `linkerd check` output

```text
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ control plane namespace exists
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-api
-----------
√ control plane pods are ready
√ control plane self-check
√ [kubernetes] control plane can talk to Kubernetes
√ [prometheus] control plane can talk to Prometheus
√ no invalid service profiles

linkerd-version
---------------
√ can determine the latest version
‼ cli is up-to-date
    is running version 2.3.0 but the latest stable version is 2.3.1
    see https://linkerd.io/checks/#l5d-version-cli for hints

control-plane-version
---------------------
‼ control plane is up-to-date
    is running version 2.3.0 but the latest stable version is 2.3.1
    see https://linkerd.io/checks/#l5d-version-control for hints
√ control plane and cli versions match

Status check results are √
```

### Environment

- Kubernetes Version: 1.13.5
- Cluster Environment: (GKE, AKS, kops, ...) Kubespray
- Host OS: CentOS
- Linkerd version: 2.3.0

### Additional context

I did not test if this also applies to request headers.

**Comment by thojkooi** [comment]
I just tried this against `2.3.1` and the results are the same.

**Comment by hawkw** [comment]
This behavior comes from the the underlying HTTP protocol implementation the Linkerd proxy uses, which intentionally represents all header names as lowercase. This is primarily for [performance reasons](https://github.com/hyperium/http/issues/228#issuecomment-404996750).

As you pointed out above, this is standards-compliant, so it shouldn't cause any issues. Have you had any problems as a result of this?

**Comment by thojkooi** [comment]
Yes, we have some software that relies on the capitalized version of `Content-Type` being present, as well as various test suits that broke due to the lower case headers.

We can fix those cases we already found, as long as it's in our own software - 3rd party integrations may not like this either.
Next week I am going to roll out linkerd on our entire test environment and see if we encounter more issues related to this (or other things).

**Comment by hawkw** [comment]
It looks like the HTTP implementation we use has added configuration option hyperium/hyper#1497 that changes it to write headers in `Title-Case`. If we added the ability to enable this in Linkerd, that would mean _all_ header names would be written out in this case, regardless of how they were received. 

Would that be sufficient with your use-case? It would fix issues with non-compliant clients that expect `Title-Case` headers. However, Linkerd would still potentially be modifying header names if they are received in other cases, so it wouldn't really be possible to rely on HTTP messages being forwarded _identically_ to how they were received (since Linkerd is a protocol-aware proxy, I would strongly advise against any code that relies on messages being byte-for-byte identical on both sides of a proxy --- this is almost never the case unless proxying raw TCP traffic).

**Comment by f3d3Cz** [comment]
My application relies on custom headers a lot to enrich the request within the internal network. I realised the headers were converted to lower case and the app suddenly stopped working.
"I cannot be the only one having this problem", and landed in this github issue. I agree @thojkooi here, I wasn't expecting the proxy to be modifying the headers.

**Comment by thojkooi** [comment]
We have sorted out our own implementations to be RFC compliant, so this is less of an issue for us now. We still have some tests to sort out before we can enable linkerd again though.

Making headers title cased would indeed be sufficient for our use case, though I understand that the http/2 spec requires them to be lower case - so once we enable that on our reverse proxy, we have lower case headers anyway.

**Comment by wmorgan** [comment]
While we strive to not break existing applications if at all possible, in this case we are RFC compliant and changing this behavior would impact proxy performance. This, I don't anticipate changing this behavior in the foreseeable future.
