### ISSUE TITLE
proxy: Do not fallback when the control plane returns NoEndpoints

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#2880]
We must assume that the control plane is authoritative (in order to enforce identity, policy, etc). When we initially scoped the fallback logic, it seemed to make sense that the the proxy should use fallback routing when the control plane reports no endpoints. In practice, it seems better for the proxy to rely on its load balancer as long as the control plane does not return a IllegalArgument error.

**Comment by hawkw** [comment]
The Destination API's `NoEndpoints` response message [specifies an `exists` boolean field](https://github.com/linkerd/linkerd2-proxy-api/blob/ddbc3a4f7f8b0058801f896d27974d19ee98094c/proto/destination.proto#L80-L85) which is intended to indicate whether or not a client should fall back:
```proto
    // `no_endpoints{exists: false}` indicates that the service does not exist
    // and the client MAY try an alternate service discovery method (e.g. DNS).
    //
    // `no_endpoints(exists: true)` indicates that the service does exist and
    // the client MUST NOT fall back to an alternate service discovery method.
    NoEndpoints no_endpoints = 3;
```

Based on my understanding of this API, we should fall back on receipt of a `no_endpoints{exists: false}` message _or_ an `IllegalArgument` error?

**Comment by olix0r** [comment]
I understand that's in the API, but I'm not convinced that policy makes sense going forward... If you resolve a service and then it is later deleted, it seems appropriate for the proxy to eagerly fail these requests. Is there a use case when we would want to forward requests for non-existent services?

**Comment by hawkw** [comment]
I believe that the intention behind `{exists: false}` was to indicate that the requested destination isn't a Kubernetes service that the control plane is aware of, so it might still exist (such as statefulsets). My understanding is that this is _also_ what the InvalidArgument response in https://github.com/linkerd/linkerd2/issues/2664 is supposed to indicate. 

It seems possible that the `exists` field was was overlooked when we decided to use InvalidArgument for this purpose, and might now have two different ways of saying the same thing. Possibly @adleong has some insight?

**Comment by olix0r** [comment]
@hawkw not exactly. `IllegalArgument` indicates that the name will _never_ be a valid service. `exists=false` indicates that the service doesn't currently exist, but may exist later.

**Comment by hawkw** [comment]
@olix0r ah, yeah, that's an important distinction, thanks for pointing that out.
