### ISSUE TITLE
NET_ADMIN capability issue with linkerd --pre check

### ISSUE THREAD

**Issue by chzbrgr71** [linkerd/linkerd2#2884]
### What is the issue?
On a freshly installed cluster in AKS. Ran `linkerd check --pre`. All checks pass except for "pre-kubernetes-capability" See output below.

FWIW, the linkerd install ends up working and seems to be functioning correctly. 

#### `linkerd check` output

```text
pre-kubernetes-capability
-------------------------
× has NET_ADMIN capability
    found 6 PodSecurityPolicies, but none provide NET_ADMIN
    see https://linkerd.io/checks/#pre-k8s-cluster-net-admin for hints
```

### Environment

- Kubernetes Version: 1.12.8
- Cluster Environment: AKS
- Host OS: Ubuntu
- Linkerd version: stable-2.3.1

**Comment by ihcsim** [comment]
> FWIW, the linkerd install ends up working and seems to be functioning correctly.

Might be related (or possibly the same) as https://github.com/linkerd/linkerd2/issues/2849. tl;dr though there are some psp resources in the k8s cluster, they aren't enforced because the psp admission controller isn't enabled. `linkerd check --pre` would still failed because it checks among the existing psp resources, if any has the `NET_ADMIN` capability added.

**Comment by grampelberg** [comment]
@chzbrgr71 mind sharing your PSP?

**Comment by chzbrgr71** [comment]
I had not created any PSP's in my cluster. This is a vanilla AKS cluster. I did a quick check and found the below, but these were added after the error when I was doing some Prometheus testing. 

```
kubectl  get psp --all-namespaces

NAME                                  PRIV    CAPS   SELINUX    RUNASUSER   FSGROUP     SUPGROUP    READONLYROOTFS   VOLUMES
kube-prometheus                       false          RunAsAny   RunAsAny    MustRunAs   MustRunAs   false            configMap,emptyDir,projected,secret,downwardAPI,persistentVolumeClaim
kube-prometheus-alertmanager          false          RunAsAny   RunAsAny    MustRunAs   MustRunAs   false            configMap,emptyDir,projected,secret,downwardAPI,persistentVolumeClaim
kube-prometheus-exporter-kube-state   false          RunAsAny   RunAsAny    MustRunAs   MustRunAs   false            configMap,emptyDir,projected,secret,downwardAPI,persistentVolumeClaim
kube-prometheus-exporter-node         false          RunAsAny   RunAsAny    MustRunAs   MustRunAs   false            configMap,emptyDir,projected,secret,downwardAPI,persistentVolumeClaim,hostPath
kube-prometheus-grafana               false          RunAsAny   RunAsAny    MustRunAs   MustRunAs   false            configMap,emptyDir,projected,secret,downwardAPI,persistentVolumeClaim,hostPath
prometheus-operator                   false          RunAsAny   RunAsAny    MustRunAs   MustRunAs   false            configMap,emptyDir,projected,secret,downwardAPI,persistentVolumeClaim
```
