### ISSUE TITLE
Remove unimplemented debug page on dashboard

### ISSUE THREAD

**Issue by adleong** [linkerd/linkerd2#2895]
The endpoints diagnostics API is currently unimplemented.  This leads to a 500 error on the debug tab of the dashboard.

<img width="512" alt="Screen Shot 2019-06-04 at 3 02 14 PM" src="https://user-images.githubusercontent.com/3979810/58916976-02d4be00-86da-11e9-87af-5cc3143db34f.png">

Perhaps this page should be removed for now.

**Comment by scottcarol** [comment]
Hey @adleong, thanks for filing this, this is really interesting. Can you confirm what you clicked to get the above screenshotted view? And were you running `linkerd dashboard` or were you loading the dashboard from your local branch? 

When I click `Debug` from the dashboard homepage on my machine I get this `Endpoints` view, and can follow the links to the listed `namespace` and `pod` views.

![Screen Shot 2019-06-06 at 10 50 24 AM](https://user-images.githubusercontent.com/2289389/59054707-1bafb180-8849-11e9-99df-e6cf5e07bc88.png)

**Comment by grampelberg** [comment]
@scottcarol this is because of the destination refactor in https://github.com/linkerd/linkerd2/pull/2786

**Comment by scottcarol** [comment]
@grampelberg Got it, thanks for the context - I see it now when running the `public-api` locally. Are you 👍 on removing the `Debug` view?

**Comment by grampelberg** [comment]
See https://github.com/linkerd/linkerd2/issues/2885, ideally it would be updated to use the correct API.

**Comment by grampelberg** [comment]
Update: after the conversations about the new services view, let's remove this one in the 2.4 timeframe and discuss whether we need it anymore at all as part of 2.5.
