### ISSUE TITLE
Websocket problem when exposing linkerd dashboard through ambassador

### ISSUE THREAD

**Issue by pablomfc** [linkerd/linkerd2#2899]
Dears,

I'm trying to expose the Linkerd (2.3.1) dashboard through  ambassador (0.70.1) using the configuration as follow:

  annotations:
    getambassador.io/config: |-
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: linkerd-mapping
      host: "linkerd.example.net"
      prefix: /
      service: linkerd-web.linkerd.svc.cluster.local:8084
      add_request_headers:
        l5d-dst-override: linkerd-web.linkerd.svc.cluster.local:8084

Dashboard works fine, but not the tap feature, which presents web-socket errors.

I've checked some examples at https://linkerd.io/2/tasks/exposing-dashboard/ but didn't help me
to translate into ambassador rules.
I've looked also at  https://www.getambassador.io/user-guide/websockets-ambassador/

Is there a way to make it works with ambassador ?

Thanks for the great application ! 
Pablo Costa

--------------^ Click "Preview" for a better view!

We primarily use GitHub as an issue tracker. For any questions you may have,
please check out the resources below.

---

- Mailing List: https://lists.cncf.io/g/cncf-linkerd-users

- Slack: https://slack.linkerd.io

- Discourse: https://discourse.linkerd.io/

- Twitter: https://twitter.com/linkerd

**Comment by grampelberg** [comment]
Are you running in AWS with ELBs? They don't support websockets, you'll need to change to ALBs.

**Comment by pablomfc** [comment]
Thank you very much Thomas !

Your hint guided me to the main issue. I'm using ELB, but the problem was with ambassador configuration itself.

I've installed ambassador using the helm/chart. 

The right configuration for service.beta.kubernetes.io/aws-load-balancer-backend-protocol and use_proxy_proto must be "tcp" and "True" respectively, but It was set  as "http" and "False" 

Working  ambassador chart values.yaml:

`namespace:
  name: ambassador

service:

  https:
    enabled: true
    port: 443
    targetPort: 8080

  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:xxxxxxxx
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-internal:  0.0.0.0/0
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Module
      name: ambassador
      config:
        service_port: 8080
        use_proxy_proto: true`

Regarding ingress annotation It was also missing the "use_websocket: true" 

`  annotations:
    getambassador.io/config: |-
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: linkerd-mapping
      host: "linkerd.example.net"
      prefix: /
      service: linkerd-web.linkerd.svc.cluster.local:8084
      add_request_headers:
        l5d-dst-override: linkerd-web.linkerd.svc.cluster.local:8084
      use_websocket: true `

Now I got everything working perfectly.

Best regards,
Pablo Costa

**Comment by KIVagant** [comment]
@grampelberg, don't we also need to use Session Affinity for linkerd-web service for websockets?

https://stackoverflow.com/questions/48993286/is-it-possible-to-route-traffic-to-a-specific-pod?rq=1

**Comment by grampelberg** [comment]
@KIVagant right now, we only run one replica of `linkerd-web`, even with `--ha`. So, stickiness wouldn't be an issue.

With that out of the way, you probably know more than I do wrt ingress and how it interacts with services. My understanding is that the actual ingress controller doesn't care what the settings on the internal service is - it just fetches the endpoints. That would suggest that the stickiness is an ingress controller concern and not a service concern itself. Seems like a nice addition to the docs (or an update to that service object) to get stickiness there just in case someone scales `linkerd-web`.

**Comment by pablomfc** [comment]
Just an update on my configs:

Linkerd header now goes into Ambassador's configs, and I've added timeout_ms to linkerd-web service as sometimes the default value 3000 isn't enough 

Ambassador annotation:

  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:xxxxxxxx"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-internal:  0.0.0.0/0
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: KubernetesEndpointResolver
      name: endpoint    
      ---
      apiVersion: ambassador/v1
      kind: Module
      name: ambassador
      config:
        service_port: 8080
        use_proxy_proto: true
        add_linkerd_headers: true
        resolver: endpoint
        load_balancer:
          policy: round_robin

Linkerd-web service annotation:

    getambassador.io/config: |
      ---                     
      apiVersion: ambassador/v1
      kind: Mapping            
      name: linkerd-mapping    
      host: "linkerd.example.net"
      prefix: /                    
      service: linkerd-web.linkerd:8084
      use_websocket: true              
      timeout_ms: 60000

**Comment by KIVagant** [comment]
Follow up: https://github.com/linkerd/linkerd2/pull/3633
