### ISSUE TITLE
eslint needs to be upgraded in our npm deps

### ISSUE THREAD

**Issue by admc** [linkerd/linkerd2#2908]
We got an automated security alert about js-yaml, as a dependency of eslint (which is quite outdated) eslint@4.12.1 ->  5.16.

Let's get this upgraded for our 2.5 release.

**Comment by scottcarol** [comment]
This security vulnerability was fixed for the `dashboard` in PR #2903. 

On the `linkerd.io` side @cpretzer opened PR# [335](https://github.com/linkerd/website/pull/335) for this.
