### ISSUE TITLE
RFC: Multiple control planes in a single cluster

### ISSUE THREAD

**Issue by alpeb** [linkerd/linkerd2#2909]
The way I see it, there are two things to take into account when running multiple control planes: (1) ensure the proxies in the application namespace(s) establish a connection to the appropriate control-plane and (2) ensure the control plane pulls the metrics from the appropriate application namespace(s)

## Proxy injection
When the proxy injector injects the sidecar it sets for it the env vars pointing to the Destination and Identity endpoints in its own control plane namespace.
For multiple control-planes, each proxy config (MutatingWebhookConfiguration) needs to be named differently as to not overwrite the others (#2887) and have a `namespaceSelector` such that it gets triggered only for the appropriate application namespace(s). For example for the control plane in the linkerd1 namespace:
```
 "namespaceSelector": { "matchLabels": { "config.linkerd.io/control-plane": "linkerd1" }}
```
This means the application namespace(s) wanting to deal with the "linkerd1" control plane should have the label `config.linkerd.io/control-plane: linkerd1` (we could facilitate that through a new CLI command).
In order to remain BC, the `namespaceSelector` would only be added if we explicitly enable the multiple control planes feature during install/upgrade through a new flag. For example for having the control plane linkerd1 deal with the emojivoto1 and emojivoto2 application namespaces:
```
linkerd install --linkerd-namespace linkerd1 --target-ns emojivoto1,emojivoto2
```

Note the `namespaceSelector` also needs to be applied to the SP validator webhook config.

## Metrics collection and resources watchers
Currently Prometheus scrapes metrics from pods in all namespaces. We'd just have to add a namespace filter into the `linkerd-proxy` job in the Prometheus config, listing the namespaces from `--target-ns`.

It also appears the Destination service is watching resources in all namespaces, so that'd need to be restrained as well.

## RBAC
Remember `--single-namespace`? Am I mad to suggest resuscitating part of that? Not required for this, but we could provided something similar as an option in the particular case of control planes using a single application namespace which would replace ClusterRoles with Roles... 

**Edit**: Fixed the `namespaceSelector` example json.

**Comment by dadjeibaah** [comment]
@alpeb, I wanted to summarize what we discussed offline and will follow up this comment with the appropriate issues. The way forward to handle the multi-control plane story is:
- Change the `mutatingwebhookconfiguration` to use a namespace selector. This namespace selector would allow the webhook to only mutate pods the injector is responsible for. Which you highlighted in your initial comment. 
- The previous point would mean that namespaces would need to include a label that identifies which control plane is in charge of managing resources under that said namespace. This is what you outlined earlier as well. We would need to then add documentation that highlights this.
- To better describe what things could happen when a user wants to install more than one control plane in the same cluster, we would add a check to the CLI that checks if we have more than one MWC and if so point, to documentation that explains the implications of having more than one MWC and possible ways to work around the issue.

Thoughts?

**Comment by alpeb** [comment]
@dadjeibaah I was gonna say this is still missing the Prometheus namespace filtering, but after testing and finally understanding relabeling I realize now it's not needed!

IIUC, Prometheus will still scrape all the namespaces, but this by itself will drop any metrics that don't come from proxies in the current namespace:
https://github.com/linkerd/linkerd2/blob/24bbd7c64b8b9f6d20b4544ed077143d61ce6815/chart/templates/prometheus.yaml#L61-L66
So it's still a little inefficient, but for now ok given the additional complexity it would imply to add the namespace filter with the list of application namespaces.

**Comment by ihcsim** [comment]
Since we've decided to not support installing multi control planes on a single k8s cluster, I'm closing this RFC. This issue was referenced earlier today on slack on the topic of multi clusters support, which is different.
