### ISSUE TITLE
Upgrade `react-iframe` library

### ISSUE THREAD

**Issue by scottcarol** [linkerd/linkerd2#2915]
PR #2903 pinned the package version of `react-iframe` to v1.7.16 in `package.json` because the latest v1.8.0 contains some breaking changes. Upgrade the [react-iframe](https://github.com/svenanders/react-iframe) library to the latest version, ensuring that the `Community` page renders correctly in Chrome, Firefox and Safari.

**Comment by tzsword** [comment]
![image](https://user-images.githubusercontent.com/20581031/67348098-7470b400-f576-11e9-9ee0-b488d8493443.png)
sorry, how to test?

**Comment by scottcarol** [comment]
Hey @tzsword, thanks for tackling this issue! 

The Community Updates page works by pulling in the contents of `https://linkerd.io/dashboard/index.html` into an iFrame. By "how to test", do you mean "how to test that upgrading the dependency was successful"? That's a great question - I would follow the docs in `BUILD.md` and run `bin/web setup` and `bin/web dev` and check `http://localhost:7777/community` to see if it renders the same as it does on `master`, and check in Chrome, Firefox and Safari.

I would also check the console of your browser to see if there are any errors. We don't currently have any browser tests for the Community component but if you would like to create one I would be happy to work with you on that!

**Comment by cynthia-sg** [comment]
Hi @tzsword,

Do you mind if I take this ticket? :)
