### ISSUE TITLE
Convert go-style CNI template to Helm template

### ISSUE THREAD

**Issue by ihcsim** [linkerd/linkerd2#2921]
Convert the [`install.CNITemplate` variable](https://github.com/linkerd/linkerd2/blob/c698d6bca11d90e0b0451e02511333ca72184e32/cli/install/cni-template.go#L22) to a Helm template, and store it in the `chart` folder with the rest of the control plane's Helm templates. Note that this will change the related [parsing and rendering code](https://github.com/linkerd/linkerd2/blob/c698d6bca11d90e0b0451e02511333ca72184e32/cli/cmd/install-cni-plugin.go#L161).

**Comment by grampelberg** [comment]
It'd be cool to do away with `install-cni` entirely and just use the helm chart.

**Comment by grampelberg** [comment]
@zaharidichev this would be good to tackle as part of the larger #3263 issue.

**Comment by zaharidichev** [comment]
> It'd be cool to do away with install-cni entirely and just use the helm chart.

@grampelberg I think this is a long shot... The way I see it, `install-cni` is a completely separate step from `install`. One that has to be complete (for some definition of it) before we proceed to install ld5 components.  In fact I would argue that, it would even make more sense to have a pre-install check that explicitly makes sure that if installing with `--cni-enabled`, the cni plugin gas actually been installed on the cluster and its config is sound. All of that is to say that if you suggest merging the two commands and enabling `install` to also install the cni plugin, then I would argue that this would not make things nicer. As always, happy for someone to prove me wrong.

**Comment by grampelberg** [comment]
Hmm, I went and looked at how everything's wired up again. It is definitely more complicated to fold everything into a single `install` command than I anticipated. Let's revisit at a different time.
