### ISSUE TITLE
Remove Auto-Inject resource config's origin field (2.5)

### ISSUE THREAD

**Issue by ihcsim** [linkerd/linkerd2#2948]
Although the CLI inject and auto-inject features share the same `pkg/inject` package, [certain logic](https://github.com/linkerd/linkerd2/blob/694ba9c2cb4049da000c122389127477da2431ad/pkg/inject/report.go#L88-L103) in the package still requires the knowledge of whether the `inject.ResourceConfig` struct is created by the CLI code or the webhook code, which leads to the introduction of the [`inject.Origin`](https://github.com/linkerd/linkerd2/blob/694ba9c2cb4049da000c122389127477da2431ad/pkg/inject/inject.go#L84-L86) type. Following https://github.com/linkerd/linkerd2/pull/2721, these code can be simplified to reconcile the handling of the `config.linkerd.io/*` and `linkerd.io/inject` annotations in uninjected workloads from both the CLI and webhook. 

The following is the list of refactor items:

1. Remove the `inject.Origin` type
1. Export the [`inject.ResourceConfig.pod.meta`](https://github.com/linkerd/linkerd2/blob/694ba9c2cb4049da000c122389127477da2431ad/pkg/inject/inject.go#L126) nested struct
1. Remove the additional [`inject.ResourceConfig.pod.annotations`](https://github.com/linkerd/linkerd2/blob/694ba9c2cb4049da000c122389127477da2431ad/pkg/inject/inject.go#L128) map which is currently used to temporarily store all `config.linkerd.io/*` annotations from the CLI
1. Remove all occurrences of `conf.AppendPodAnnotation()` in `cli/cmd/inject.go`, and insert the `config.linkerd.io/*` annotations into the exported `inject.ResourceConfig.pod.Meta` nested struct directly in the same file.

**Comment by grampelberg** [comment]
@ihcsim is this still relevant with the inject changes around helm?

**Comment by ihcsim** [comment]
Superseded by #3200.
