### ISSUE TITLE
Reduce costs of running linkerd2 proxy

### ISSUE THREAD

**Issue by thomaspeitz** [linkerd/linkerd2#2949]
Hi linkerd team,

we are using autoinjector for linkerd-proxy sidecar container.

The proxy currently requests 100m cpu for every pod.

Most of time it stays under 1m in our setup.
Average last two weeks over all over pods (on staging env) - 0.6m.
Max over all pods 11m.

I would suggest setting 5m requests and a limit of 50m for the cpu. From my point of view this should be sufficient for most deployments. This means that resources are not blocked without using them and makes running linkerd cheaper.

Greetings, Thomas

**Comment by siggy** [comment]
@thomaspeitz Have a look at the `--proxy-cpu-*` flags in the CLI:

```bash
$ linkerd inject -h | grep proxy-cpu
      --proxy-cpu-limit string          Maximum amount of CPU units that the proxy sidecar can use
      --proxy-cpu-request string        Amount of CPU units that the proxy sidecar requests
$ linkerd install -h | grep proxy-cpu
      --proxy-cpu-limit string                    Maximum amount of CPU units that the proxy sidecar can use
      --proxy-cpu-request string                  Amount of CPU units that the proxy sidecar requests
```

Closing this for now, hop into [Linkerd Slack](https://slack.linkerd.io) or re-open if you have more questions.
