### ISSUE TITLE
Disable installation of multiple control planes in 2.4

### ISSUE THREAD

**Issue by ihcsim** [linkerd/linkerd2#2954]
For 2.4, we've decided to not support multi control plane setup. The `linkerd install` and `linkerd check --pre` commands will be updated to error out if existing Linkerd global resources are detected on the k8s cluster.

The following is a list of items to be implemented:

- Label all ~global~ resources (cluster role, cluster role binding, namespace, service accounts, CRD) with the existing `linkerd.io/control-plane-ns` label
- Update `linkerd install` and `linkerd check --pre` to query by this label. If the result is non-empty, an error will be returned
- `linkerd check` should check the mutating webhook config to make sure the service's namespace (defined in the config) matches that of the control plane. Further testing require wit multi-stage install, as it might not have the proper RBAC to access globally scoped resources like the webhook config.

**Comment by grampelberg** [comment]
Anything to pay attention to with 2.3 -> 2.4 upgrades?

**Comment by ihcsim** [comment]
2.3 -> 2.4 upgrades will definitely be an important test case. AFAICT, it won't break anything, since we are just adding a new label to all previously unlabelled resources. I think it's a safe to assume that users running `linkerd upgrade` have RBAC permission to `edit` all Linkerd global resources.
