### ISSUE TITLE
Proxy-init fails if primary container drops capability NET_RAW

### ISSUE THREAD

**Issue by afirth** [linkerd/linkerd2#2959]
## Bug Report
In edge 19.6.2, If a pod has DROP: [ALL] the init container vomits

### What is the issue?
It seems that the init container requires NET_RAW as well as NET_ADMIN @ https://github.com/linkerd/linkerd2/pull/2911/files#diff-2e89e743609d90f7ab63ec3498f78c8bR627

### How can it be reproduced?

GKE, 19.6.2
`linkerd install`
`helm template nginx-ingress | linkerd inject | k apply -f -`

### Logs, error output, etc
```
    initContainerStatuses:
    - containerID: docker://7db0b2af9b82572b36e394eb06683031978833852aa9dd360c24d73f6cf90d79
      image: gcr.io/linkerd-io/proxy-init:v1.0.0
      imageID: docker-pullable://gcr.io/linkerd-io/proxy-init@sha256:b88af208664c1c82a55867e03f41d22f564cddf873e1524c7a854296371a6eff
      lastState:
        terminated:
          containerID: docker://df461543658bcc4864e770a033fabe5106617a9ce2343c5f3cb523e8e5fd8936
          exitCode: 1
          finishedAt: "2019-06-18T14:07:11Z"
          message: |+
            2019/06/18 14:07:11 Tracing this script execution as [1560866831]
            2019/06/18 14:07:11 State of iptables rules before run:
            2019/06/18 14:07:11 > iptables -t nat -vnL
            2019/06/18 14:07:11 < iptables v1.6.0: can't initialize iptables table `nat': Permission denied (you must be root)
            Perhaps iptables or your kernel needs to be upgraded.

            2019/06/18 14:07:11 Aborting firewall configuration
            Error: exit status 3
----
      name: linkerd-init
      resources:
        limits:
          cpu: 100m
          memory: 50Mi
        requests:
          cpu: 10m
          memory: 10Mi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          add:
          - NET_BIND_SERVICE
          - NET_ADMIN
          drop:
          - ALL
        privileged: false
        procMount: Default
        readOnlyRootFilesystem: true
        runAsNonRoot: false
        runAsUser: 0
```
### Possible solution
Adding NET_RAW to the primary container's capabilities allows the container to start

**Comment by alpeb** [comment]
Thanks for the issue @afirth 
I confirmed adding NET_RAW does work, when all the other capabilities have been dropped.
Should be addressed in this week's edge :+1:

**Comment by ihcsim** [comment]
@afirth I submitted a fix to include the `NET_RAW` cap to the proxy-init spec. I'm still not sure why it is only needed when there is a `drop: all` capability rule. FWIW, I read that `ALL` isn't a Linux kernel thing, but a Docker thing, so who knows how the validation works. The fix should be included in this week's edge, but if you are interested, you can try out the [feature branch](https://github.com/linkerd/linkerd2/tree/isim/proxy-psp) or the bits that I have uploaded to [GCS](https://storage.googleapis.com/gh-2959/linkerd).

@codeman9 I'm cc-ing you on this. Although I don't think this change will affect you, thought I will give you a heads up anyway.
