### ISSUE TITLE
Add Services view to Dashboard

### ISSUE THREAD

**Issue by scottcarol** [linkerd/linkerd2#2967]
### What problem are you trying to solve?
Important data can be shared with users in the context of Services, including the result of load-balancing/traffic-splitting, service profiles and more. Currently we are not displaying this on the dashboard.

### How should the problem be solved?
Build a Services view on the dashboard, to be accessed under the Resources menu.

Mockups below.
Outstanding question: @grampelberg we didn't talk about an `All` view for `Services`. For P0, would a list of services with links to their detail view be helpful? Or omit for now?

<img width="224" alt="service-menu" src="https://user-images.githubusercontent.com/2289389/59726114-338e1a80-91e5-11e9-82d6-ade83bea3822.png">

![svg-page-1](https://user-images.githubusercontent.com/2289389/59726124-3ab52880-91e5-11e9-9728-f7bd0886058a.png)

![svg-page-2](https://user-images.githubusercontent.com/2289389/59726127-3db01900-91e5-11e9-951f-f4898f99dd92.png)

**Comment by adleong** [comment]
This looks fantastic, @scottcarol!  As we have discussed, there is a lot of potentially useful information we can put on this page but I think this is a great piece to start with.  

I think we can also add a "success rate" column to this table.

I'll also mention that "endpoints" already has a defined meaning in Kubernetes (the addresses of a service) so there's a bit of a mismatch when showing deployments, for example.  A less overloaded term might be something like "members".

**Comment by scottcarol** [comment]
Thanks @adleong. The [k8s docs for Services](https://kubernetes.io/docs/concepts/services-networking/service/) don't use the word "member" anywhere, but they do use the phrase "Service resources" - would that be easier to understand as the title?: 
![svg-page-1](https://user-images.githubusercontent.com/2289389/59792548-3f331d00-9289-11e9-8e89-070ed4d3a2bc.png)

**Comment by scottcarol** [comment]
Closing for now, building #3105 and #3106 instead. Will revisit Service UI at a later date.
