### ISSUE TITLE
Linkerd edge 19.6.2 auto-injection is not working on GKE?

### ISSUE THREAD

**Issue by jeroenjacobs79** [linkerd/linkerd2#2973]
### What is the issue?

Linkerd edge 19.6.2 auto-injection is not working.

### How can it be reproduced?

I have installed 19.6.2 on GKE (private cluster mode).
This is the deployment file used, which was created by `linkerd inject`

````
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      deploy: example
  strategy: {}
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      creationTimestamp: null
      labels:
        deploy: example
    spec:
      containers:
      - image: nginx:1.7.9
        name: nginx
        resources: {}
status: {}
---
````

The deployment is never meshed:
(deployed in `default` namespace)

````
linkerd stat namespaces
NAME            MESHED   SUCCESS       RPS   LATENCY_P50   LATENCY_P95   LATENCY_P99   TCP_CONN
default            0/3         -         -             -             -             -          -
kube-public        0/0         -         -             -             -             -          -
kube-security      0/0         -         -             -             -             -          -
kube-system       0/17         -         -             -             -             -          -
linkerd            8/8   100.00%   50.4rps         205ms         406ms         487ms        126
testsite           0/2         -         -             -             -             -          -
weave              0/5         -         -             -             -             -          -
````

### Logs, error output, etc

No errors in the proxy injector:

````
kubectl logs -n linkerd linkerd-proxy-injector-7858b46f4d-xnpzf  proxy-injector
time="2019-06-20T16:19:42Z" level=info msg="running version edge-19.6.2"
time="2019-06-20T16:19:42Z" level=info msg="waiting for caches to sync"
time="2019-06-20T16:19:42Z" level=info msg="caches synced"
time="2019-06-20T16:19:42Z" level=info msg="starting admin server on :9995"
time="2019-06-20T16:19:42Z" level=info msg="listening at :8443"
````

#### `linkerd check` output

```text
linkerd check
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist

linkerd-existence
-----------------
√ control plane components ready
√ no unschedulable pods
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-api
-----------
√ control plane pods are ready
√ control plane self-check
√ [kubernetes] control plane can talk to Kubernetes
√ [prometheus] control plane can talk to Prometheus
√ no invalid service profiles

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ control plane is up-to-date
√ control plane and cli versions match

Status check results are √
```

#### `linkerd logs` output

Some relevant logs output:

````
linkerd linkerd-proxy-injector-7858b46f4d-xnpzf linkerd-proxy time="2019-06-20T16:19:48Z" level=info msg="running version edge-19.6.2"
linkerd linkerd-proxy-injector-7858b46f4d-xnpzf linkerd-proxy INFO [     0.002943s] linkerd2_proxy::app::main using destination service at Some(ControlAddr { addr: Name(NameAddr { name: "linkerd-destination.linkerd.svc.cluster.local", port: 8086 }), identity: Some("linkerd-controller.linkerd.serviceaccount.identity.linkerd.cluster.local") })
linkerd linkerd-proxy-injector-7858b46f4d-xnpzf linkerd-proxy INFO [     0.002971s] linkerd2_proxy::app::main using identity service at Name(NameAddr { name: "linkerd-identity.linkerd.svc.cluster.local", port: 8080 })
linkerd linkerd-proxy-injector-7858b46f4d-xnpzf linkerd-proxy INFO [     0.002975s] linkerd2_proxy::app::main routing on V4(127.0.0.1:4140)
linkerd linkerd-proxy-injector-7858b46f4d-xnpzf linkerd-proxy INFO [     0.002979s] linkerd2_proxy::app::main proxying on V4(0.0.0.0:4143) to None
linkerd linkerd-proxy-injector-7858b46f4d-xnpzf linkerd-proxy INFO [     0.002981s] linkerd2_proxy::app::main serving admin endpoint metrics on V4(0.0.0.0:4191)
linkerd linkerd-proxy-injector-7858b46f4d-xnpzf linkerd-proxy INFO [     0.002983s] linkerd2_proxy::app::main protocol detection disabled for inbound ports {25, 3306}
linkerd linkerd-proxy-injector-7858b46f4d-xnpzf linkerd-proxy INFO [     0.002986s] linkerd2_proxy::app::main protocol detection disabled for outbound ports {25, 3306}
linkerd linkerd-proxy-injector-7858b46f4d-xnpzf linkerd-proxy WARN [     0.530002s] linkerd-identity.linkerd.svc.cluster.local:8080 linkerd2_proxy::proxy::reconnect connect error to ControlAddr { addr: Name(NameAddr { name: "linkerd-identity.linkerd.svc.cluster.local", port: 8080 }), identity: Some("linkerd-identity.linkerd.serviceaccount.identity.linkerd.cluster.local") }: request timed out
linkerd linkerd-proxy-injector-7858b46f4d-xnpzf linkerd-proxy INFO [     4.113297s] linkerd2_proxy::app::main Certified identity: linkerd-proxy-injector.linkerd.serviceaccount.identity.linkerd.cluster.local
linkerd linkerd-proxy-injector-7858b46f4d-xnpzf proxy-injector time="2019-06-20T16:19:42Z" level=info msg="running version edge-19.6.2"
linkerd linkerd-proxy-injector-7858b46f4d-xnpzf proxy-injector time="2019-06-20T16:19:42Z" level=info msg="waiting for caches to sync"
linkerd linkerd-proxy-injector-7858b46f4d-xnpzf proxy-injector time="2019-06-20T16:19:42Z" level=info msg="caches synced"
linkerd linkerd-proxy-injector-7858b46f4d-xnpzf proxy-injector time="2019-06-20T16:19:42Z" level=info msg="starting admin server on :9995"
linkerd linkerd-proxy-injector-7858b46f4d-xnpzf proxy-injector time="2019-06-20T16:19:42Z" level=info msg="listening at :8443"
````

#### Admission registration 

````
 kubectl api-versions | grep admissionregistration
admissionregistration.k8s.io/v1beta1
````

### Environment

- Kubernetes Version: v1.13.6-gke.0
- Cluster Environment: GKE (Private cluster with public exposed apiserver)
- Host OS: Linux
- Linkerd version: edge-19.6.2

**Comment by ihcsim** [comment]
@jeroenjacobs79 Hi, just want to confirm if you have tried my [earlier suggestion](https://github.com/linkerd/linkerd2/issues/1981#issuecomment-504102790) to update the VPC firewall to open the port to the proxy injector's port. See https://github.com/linkerd/linkerd2/issues/2940#issuecomment-502950606 for details. LMK if that didn't work. Thanks!

**Comment by jeroenjacobs79** [comment]
Hi, I will try that. But I don't understand why this is necessary. You say the proxy-injector listens on port 8443, but it's just a service within the cluster right? It's not exposed as NodePort.  Sorry, I have some trouble understanding the issue...

**Comment by grampelberg** [comment]
@jeroenjacobs79 when you `kubectl apply`, YAML is sent to the api-server. The api-server then fires off a webhook HTTP request to the proxy injector. Because GKE configures private clusters to block 8443, the api-server is unable to talk to the proxy injector and linkerd is unable to inject. By allowing 8443, the api-server is then able to contact the proxy injector and everything works as intended.

**Comment by jeroenjacobs79** [comment]
Adding port 8443 did not seem to solve the issue. Do I also need to add additional source address cidr's as well? It's currently 172.16.0.0/28 (which is managed by Google, I think).

**Comment by jeroenjacobs79** [comment]
Let me clarify, these are the cidr ranges that are in use:

- 172.16.0.0/28: Used by Google for master plane.
- 10.9.20.0/24: Subnet cidr used by the nodes.
- 10.4.0.0/14: pod cidr
- 10.0.32.0/20: service cidr

At the moment, the master firewall rule lists 172.16.0.0/28 as source, gke-hic-website-cluster-xxxxxxx-node as the target label, and ports tcp: 10250, 443, 8443.

**Comment by jeroenjacobs79** [comment]
@grampelberg But if you look at the services, proxy-injector listens at port 443, so where does this port 8443 suddenly appears from?

**Comment by ihcsim** [comment]
Last I tested it, I didn't have to specify any CIDR. Do you have network policy enabled on the private cluster? I tested without it. I can try reproduce this later today.

Yeah, I haven't investigated too much into why the proxy injector's port is necessary. FWIW, I wonder if there is something about how the api server talks to a mutating webhook. E.g. when I have multiple replicas of the proxy injector, I'd expect the `Service` in front of it to load balance between the replicas. But the k8s api server seems to only talk to one replica, until it's destroyed, before the api server picks another replica to send the admission request to.

**Comment by ihcsim** [comment]
It also doesn't help the gke doesn't reveal the rules behind the `gke-<cluster>-node` firewall config. I bet it's the alias IP range though.

**Comment by jeroenjacobs79** [comment]
No, network policies are disabled here.

**Comment by jeroenjacobs79** [comment]
Hi, I deleted the deployment and re-applied it, and now they seem to get meshed. 

Make sense I guess. Deleting the pods will trigger the apiserver to call the admission registration webhook again.

**Comment by jeroenjacobs79** [comment]
Will close this issue, as this is technically not a linkerd issue, but a GKE issue.

**Comment by ihcsim** [comment]
Glad to hear that it works :+1:. Let us know if you have come across any other issues.

For posterity, turns out that the `gke-<cluster>-node` target isn't another firewall config; it's the network tag on the nodes. The `gke-<cluster>-master` firewall config basically permits `master` traffic to get to the alias/secondary (in case of gke, also the pod) IP address range of the node's network interface, as described [here](https://cloud.google.com/vpc/docs/alias-ip#alias_ip_ranges_defined_in_a_vm_network_interface), which doesn't necessarily bind to any node ports. I can see from the k8s api server logs that the k8s api server still tries to talk to the `Service`, but I  guess, eventually, the traffic needs to be forwarded to the pod, so the firewall rules need to play well with it?
