### ISSUE TITLE
Add context to UUID warning when running web server locally 

### ISSUE THREAD

**Issue by scottcarol** [linkerd/linkerd2#2974]
#2668 allowed the web server to run without install config, simply warning when the UUID isn't available. However the log message can be confusing if someone using `bin/web dev` to debug a dashboard issue doesn't have any context: 

```
WARN[0000] failed to load uuid from install config: failed to read config file: open /var/run/linkerd/config/install: no such file or directory
```

I'd like to add `disregard warning if running web server locally` to the log message, however, does this add too much noise to the warning? @klingerf @rmars

**Comment by klingerf** [comment]
@scottcarol That's totally fine by me! It should only printing in development mode anyway, assuming everything is working as expected.

**Comment by scottcarol** [comment]
Thanks @klingerf - it prints with both `bin/web dev` and `bin/web run`, is that expected? I will add that clarification to the log message.

**Comment by klingerf** [comment]
Yep -- that's expected.
