### ISSUE TITLE
Custom ConfigMaps

### ISSUE THREAD

**Issue by Bullettoothtobi** [linkerd/linkerd2#2991]
### What problem are you trying to solve?
When running `linkerd upgrade` the ConfigMaps are part of the output. By using this output, all custom changes in the ConfigMaps are overwritten.

In my case I was changing the Grafana configuration to enable the login. After every upgrade the login is disabled again.

### How should the problem be solved?
Maybe it's ok to not touch certain configurations, like the Grafana configuration which shouldn't change so often. But this is open for discussion.

### Any alternatives you've considered?
Maybe a command like `linkerd upgrade --no-configs grafana` would work to exclude certain configurations.

### How would users interact with this feature?
`linkerd upgrade`
or
`linkerd upgrade --no-configs grafana`

**Comment by ihcsim** [comment]
We should be able to do this by extending the `--from-manifest` option of the `linkerd upgrade` command to read the Grafana config map from a YAML file, generated from a previous installation. (See https://github.com/linkerd/linkerd2/pull/2697). AFAICT, atm, the `--from-manifest` option only works for the `linkerd-config` config map, identity secret, and webhooks secrets.

@Bullettoothtobi Will this approach work for you?

**Comment by grampelberg** [comment]
@Bullettoothtobi I just put some docs together around this, does linkerd/website#384 work for you?

**Comment by Bullettoothtobi** [comment]
That's exactly what I needed! Thanks for your great work!
