### ISSUE TITLE
Dsts on inbound route stats are not fully qualified

### ISSUE THREAD

**Issue by klingerf** [linkerd/linkerd2#2994]
### What is the issue?

The `linkerd routes` command will only return service stats for service destinations that are fully qualified. For instance, the traffic generator from the [sample books app](https://run.linkerd.io/booksapp.yml) sends traffic to `webapp:7000`, but `linkerd routes svc/webapp` returns no data if the `webapp` deployment is injected and the `traffic` deployment is not.

### How can it be reproduced?

1. Install linkerd
    ```
    linkerd install | kubectl apply -f -
    ```
1. Install the books app
    ```
    kubectl apply -f https://run.linkerd.io/booksapp.yml
    ```
1. Inject the webapp deployment
    ```
    kubectl get deploy/webapp -o yaml | linkerd inject - | kubectl apply -f -
    ```
1. Wait for a minute for stats to propagate
1. Query route stats for `svc/webapp`, receive nothing
    ```
    linkerd routes svc/webapp
    ROUTE       SERVICE   SUCCESS      RPS   LATENCY_P50   LATENCY_P95   LATENCY_P99
    [DEFAULT]    webapp     0.00%   0.0rps           0ms           0ms           0ms
    ```

---

The issue is that `linkerd routes` expects dsts to be fully qualified, and when the source pod is unmeshed, we don't canonicalize dsts to make sure they're fully qualified.

When I run `linkerd routes svc/webapp`, that results in the following Prometheus query:

```
sum(increase(route_response_total{direction="inbound", dst=~"(webapp.default.svc.cluster.local)(:\\d+)?", namespace="default"}[1m])) by (rt_route, dst, classification) 
```

But the `route_response_total` stat from Prometheus looks like this:

```
route_response_total{classification="success",control_plane_ns="linkerd",deployment="webapp",direction="inbound",dst="webapp:7000",instance="10.1.0.80:4191",job="linkerd-proxy",namespace="default",pod="webapp-c78d8bc8-5749c",status_code="200"}
```

The issue is that `dst=~"(webapp.default.svc.cluster.local)(:\\d+)?"` does not match `dst="webapp:7000"`.

### Possible solution

There are a few ways to start seeing route stats in this scenario:

1. Modify the traffic deployment to use a fully qualified address when sending traffic to the webapp service (e.g. `webapp.default.svc.cluster.local:7000` instead of `webapp:7000`)
1. Inject the traffic deployment with linkerd, so that it does canonicalization
1. Modify the routes query to not require that dsts be fully qualified.

The third option seems preferable, but it would require code changes and probably has some implications that I'm not thinking of.

### Environment

- Kubernetes Version: v1.14.3
- Cluster Environment: Docker Desktop
- Linkerd version: edge-19.6.3 (tested back to stable-2.2.1 and saw same behavior)

**Comment by adleong** [comment]
I think the issue is that we don't do canonicalization on the inbound proxy.  This may also mean that the inbound proxy is not using the correct service profile when the authority is not fully qualified.  @hawkw does that sound correct to you?

**Comment by olix0r** [comment]
I don't think it's appropriate to do canonicalization on the inbound side, as we can't assume the receiver's DNS configuration matches the sender's. It should be the case, however, that the inbound router knows the canonical name for all _meshed_ traffic, as the canonicalized value is provided as a header for profile discovery.

**Comment by adleong** [comment]
It's a good point that the sender's DNS configuration may not match the receiver's.  But, in the absence of a canonicalized dst header (i.e. when the traffic is coming from outside of the mesh) it seems like canonicalizing with the receiver's DNS configuration is better than nothing.  This would, for example, allow us to correctly apply inbound service profile policy when the client is an unmeshed pod in the cluster.

**Comment by olix0r** [comment]
> it seems like canonicalizing with the receiver's DNS configuration is better than nothing

I disagree. It's better to omit data than to potentially guess incorrectly.

**Comment by olix0r** [comment]
Another solution to this might be adding a capability to associate a pod port with a default service profile, for instance. No need for any DNS guessing.
