### ISSUE TITLE
Dynamically Injected Proxy on clusters with nonstandard cluster domain are incorrectly configured

### ISSUE THREAD

**Issue by warmfusion** [linkerd/linkerd2#3000]
### What is the issue?
Given a cluster with non-standard cluster domain (ie example.local rather than cluster.local) when proxys are dynamically injected they are configured with an invalid LINKERD2_PROXY_DESTINATION_SVC_ADDR

### How can it be reproduced?

1. Operate cluster with example.local as cluster name
2. Configure Linkerd on cluster using workarounds outlined on https://github.com/linkerd/linkerd2/issues/1720
3. Create services with injection enabled
4. Observe that proxy never comes online as attempts to reach cluster.local endpoints which do not resolve

### Logs, error output, etc
```

INFO [ 0.001982s] linkerd2_proxy::app::main using destination service at Some(ControlAddr { addr: Name(NameAddr { name: "linkerd-destination.linkerd.svc.cluster.local", port: 8086 }), identity: Some("linkerd-controller.linkerd.serviceaccount.identity.linkerd.example.local") })
INFO [ 0.002026s] linkerd2_proxy::app::main using identity service at Name(NameAddr { name: "linkerd-identity.linkerd.svc.cluster.local", port: 8080 })
INFO [ 0.002033s] linkerd2_proxy::app::main routing on V4(127.0.0.1:4140)
INFO [ 0.002040s] linkerd2_proxy::app::main proxying on V4(0.0.0.0:4143) to None
INFO [ 0.002046s] linkerd2_proxy::app::main serving admin endpoint metrics on V4(0.0.0.0:4191)
INFO [ 0.002051s] linkerd2_proxy::app::main protocol detection disabled for inbound ports {25, 3306}
INFO [ 0.002090s] linkerd2_proxy::app::main protocol detection disabled for outbound ports {25, 3306}
WARN [ 0.115805s] linkerd-identity.linkerd.svc.cluster.local:8080 linkerd2_proxy::proxy::reconnect connect error to ControlAddr { addr: Name(NameAddr { name: "linkerd-identity.linkerd.svc.cluster.local", port: 8080 }), identity: Some("linkerd-identity.linkerd.serviceaccount.identity.linkerd.example.local") }: no record found for name: linkerd-identity.linkerd.svc.cluster.local type: AAAA class: IN

```

#### `linkerd check` output

```text
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ control plane namespace exists
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-api
-----------
√ control plane pods are ready
√ control plane self-check
√ [kubernetes] control plane can talk to Kubernetes
√ [prometheus] control plane can talk to Prometheus
√ no invalid service profiles

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ control plane is up-to-date
√ control plane and cli versions match

Status check results are √
```

### Environment

- Kubernetes Version: 1.13.5
- Cluster Environment: On-Premise
- Host OS: Debian Stretch
- Linkerd version: 2.3.2-stable

### Possible solution

Hardcode injection using `linkerd inject build.yaml | sed 's/cluster.local/example.local/' > build-injected.yaml

**Comment by ihcsim** [comment]
@warmfusion Thanks for bringing this up. The `LINKERD2_PROXY_DESTINATION_SVC_ADDR` is one of the places that have the domain hardcoded, per https://github.com/linkerd/linkerd2/issues/1720#issuecomment-493500721. There will be a series of PRs coming, starting with #2950, which will address this issue. Recommend closing this issue, and track it under #1720.

**Comment by grampelberg** [comment]
Closing out as a dup of #1720.
