### ISSUE TITLE
Top layout issues

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#3011]
## What is the issue?

On smaller screens, the top page has some layout issues.

![Screenshot 2019-06-28 13 45 16](https://user-images.githubusercontent.com/47992/60370247-fc6cf580-99aa-11e9-9fe8-e581c0e73b5b.png)

The table is also *really* big and doesn’t do a good job of showing that there’s more data:

![Screenshot 2019-06-28 13 46 01](https://user-images.githubusercontent.com/47992/60370286-1c041e00-99ab-11e9-8fa9-462f9607ca77.png)

### How can it be reproduced?

My screen size is 1024x768 for both of those screenshots on edge-19.6.3.

**Comment by scottcarol** [comment]
still relevant
