### ISSUE TITLE
Allow network egress bytes to be counted by destination zone,region,etc

### ISSUE THREAD

**Issue by dwbrown2** [linkerd/linkerd2#3014]
### What problem are you trying to solve?
We want to leverage Linkerd data to enable users to measure the cost of their egressed bytes by service, namespace, etc in the [Kubecost model](https://github.com/kubecost/cost-model). The Kubecost team has had many requests for this information from users. In order to do this, we need to determine how many bytes egressed, went to a different region/zone, and their destination country code. As a resource, [here](https://cloud.google.com/compute/pricing#network) is the GCP network pricing sheet.  

### How should the problem be solved?
Add classification labels (e.g. internet egress,cross-region) to Prometheus metrics? This combined with src/dst country code would enable a cost calculation. 

### Any alternatives you've considered?
Add dest IP address labels so that users can do classification themselves? This approach seems to have many drawbacks. 

### How would users interact with this feature?
They could write Prometheus queries to determine the cost of a service/path and use tools like Kubecost to determine their networking cost allocation.

**Comment by AjayTripathy** [comment]
Just out of curiosity... I did some exploring over the weekend. It looks like you could classify bytes sent out of cluster via data from nf_conntrack, after enabling the nf_conntrack.acct flag. I’m not sure if you would have a better source for this data, but looks like one option. Mapping the src IP back to Pod IP to determine which pod is emitting the data seems sufficient for allocation back to pods here.

**Comment by grampelberg** [comment]
Super valuable!

**Comment by dwbrown2** [comment]
@grampelberg, we've now implemented this in Kubecost. Happy to share more info on our approach if it becomes a priority for you guys! Hope to catch up soon too.

**Comment by grampelberg** [comment]
@dwbrown2 woah, that's awesome! We'd love to know!
