### ISSUE TITLE
Bad Request with special characters

### ISSUE THREAD

**Issue by stevenklar** [linkerd/linkerd2#3015]
### What is the issue?

Bad requests (400 Status Code) occurs sometimes.

### How can it be reproduced?

We just injected linkerd into a web application and tried like 10 times the following endpoint:
> https://<OUR_APP>?wayne=1%\7Cf

Most of the time it works as expected and sometimes we get back a 400 response which doesn't output anything in our logs.

### Logs, error output, etc

After changing linkerd proxy level to trace this appeared when the 400 code page pops up:
> dev-b59f6d6d7-qr2dt linkerd-proxy TRCE [    72.578792s] proxy={server=in listen=0.0.0.0:4143 remote=10.42.9.0:31528} linkerd2_proxy::proxy::server http1 server error: Error(Parse(Header))

Sadly there were no additional information what part of the header is broken or not. Maybe you can reproduce with the given URL. Without linkerd the error never appears.

#### `linkerd check` output

```text
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ control plane namespace exists
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-api
-----------
√ control plane pods are ready
√ control plane self-check
√ [kubernetes] control plane can talk to Kubernetes
√ [prometheus] control plane can talk to Prometheus
√ no invalid service profiles

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ control plane is up-to-date
√ control plane and cli versions match

Status check results are √
```

### Environment

- Kubernetes Version: v1.13.5
- Cluster Environment: (GKE, AKS, kops, ...): Hetzner Cloud
- Host OS: Ubuntu 18.04.
- Linkerd version: Client+Server stable-2.3.2

### Possible solution

I don't know. Maybe something wrong with header read or when some bytes are missing.

### Additional context

Please let me know if I can provide further information.

**Comment by grampelberg** [comment]
@seanmonstar would you mind taking a look and see if this is a bug on our end with translation or an RFC issue?

**Comment by seanmonstar** [comment]
Is it possible to see what the request headers are that trigger the 400 response?

**Comment by stevenklar** [comment]
Sadly not exactly. But it's a pretty default http request. What i'am a little bit confused about is, that it shows http1 instead of http2, but that could be as expected as it get upgraded via our front nginx proxy.

The only difference is the Request URI mentioned above.

**Comment by seanmonstar** [comment]
It'll be hard for me to proceed without knowing what kind of input is trigger a `Parse(Header)` error XD

**Comment by stevenklar** [comment]
This is all what I got
```➜ curl -I -v -s "https://internal/\?wayne\=1%\7Cf"
*   Trying xxx.xxx.0.11:443...
* TCP_NODELAY set
* Connected to internal (xxx.xxx.0.11) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=*.internal
*  start date: Apr 21 21:30:46 2019 GMT
*  expire date: Jul 20 21:30:46 2019 GMT
*  subjectAltName: host "internal" matched cert's "internal"
*  issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x557b5c21bf30)
> GET /\?wayne\=1%\7Cf HTTP/2
> Host: internal
> User-Agent: curl/7.65.1
> Accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
< HTTP/2 400
HTTP/2 400
< date: Wed, 03 Jul 2019 09:06:44 GMT
date: Wed, 03 Jul 2019 09:06:44 GMT
< content-length: 0
content-length: 0
< strict-transport-security: max-age=15724800; includeSubDomains
strict-transport-security: max-age=15724800; includeSubDomains

<
* Connection #0 to host internal left intact

```
Hopefuly this can help a bit more.

**Comment by seanmonstar** [comment]
Ok, so just trying that URL, I've found the issue: `\` isn't a valid path character... And it seems most implementations don't care XD
