### ISSUE TITLE
Update install-edge script to include upgrade instructions

### ISSUE THREAD

**Issue by scottcarol** [linkerd/linkerd2#3018]
Currently, when a user runs `curl https://run.linkerd.io/install-edge | sh`, they see this confirmation text:
```bash
Download complete!, validating checksum...
Checksum valid.

Linkerd was successfully installed 🎉

Add the linkerd CLI to your path with:

  export PATH=$PATH:$HOME/.linkerd2/bin

Now run:

  linkerd check --pre                     # validate that Linkerd can be installed
  linkerd install | kubectl apply -f -    # install the control plane into the 'linkerd' namespace
  linkerd check                           # validate everything worked!
  linkerd dashboard                       # launch the dashboard

Looking for more? Visit https://linkerd.io/2/next-steps
```

However the `Now run:` section will not work if they already have Linkerd. If they have Linkerd they need to run `linkerd upgrade`.

Solution: Point people to the upgrade docs:
```bash
Linkerd was successfully installed 🎉

Are you upgrading your current Linkerd? Visit https://linkerd.io/2/tasks/upgrade/ for next steps

Are you installing Linkerd for the first time?

Add the linkerd CLI to your path with:

     ....
```

**Comment by grampelberg** [comment]
I like the idea of getting upgrades into that output. I think I’d rather go with something like:

```bash
Now run:

  linkerd check --pre                     # validate that Linkerd can be installed
  linkerd install | kubectl apply -f -    # install the control plane into the 'linkerd' namespace
  linkerd check                           # validate everything worked!
  linkerd dashboard                       # launch the dashboard

Upgrading? Visit:

  https://linkerd.io/2/tasks/upgrade/
```

**Comment by scottcarol** [comment]
If I am quickly skimming the output text, my eyes will still be drawn to the `Now run:` steps before I see the note about Upgrades. Is there a way to highlight that those run steps are ONLY for new installs? 

```bash
Installing for the first time? Run:

  linkerd check --pre                     # validate that Linkerd can be installed
  linkerd install | kubectl apply -f -    # install the control plane into the 'linkerd' namespace
  linkerd check                           # validate everything worked!
  linkerd dashboard                       # launch the dashboard

Upgrading? Visit:

  https://linkerd.io/2/tasks/upgrade/
```

**Comment by grampelberg** [comment]
Yup, I want the upgrade after run with the assumption that new users are going to need the instructions more than folks upgrading.

We can test whether `linkerd` is on the path and present upgrade instructions instead.

**Comment by scottcarol** [comment]
It would be great to present upgrade instructions for people who already have Linkerd in their path. 

Do [the upgrade docs](https://linkerd.io/2/tasks/upgrade/) cover upgrading from every existing version number of Linkerd2? 

For an existing Linkerd user who wants to upgrade, would there ever be a case where those docs are NOT applicable?

Due to the nuances of upgrading, I would prefer to simply print the URL of those upgrade docs rather than spell out individual steps. WDYT?

**Comment by grampelberg** [comment]
> It would be great to present upgrade instructions for people who already have Linkerd in their path.

My only request is to make sure we don’t hide anything based on system state. Highlighting a section or reordering would be great.

> Do the upgrade docs cover upgrading from every existing version number of Linkerd2?

No, on purpose. We *should* be solving this by versioning the docs, but it’ll be impossible to test upgrades between every version.

> For an existing Linkerd user who wants to upgrade, would there ever be a case where those docs are NOT applicable?

Yup.

> Due to the nuances of upgrading, I would prefer to simply print the URL of those upgrade docs rather than spell out individual steps. WDYT?

Agreed.

**Comment by scottcarol** [comment]
Great. My understanding of the steps are:
* Check for `linkerd` in the user's path when they download Linkerd
* If `linkerd` is NOT in the user's path, add `Upgrading? [LINK]` to bottom of existing output
* If `linkerd` IS in the user's path, add `Upgrading? [LINK]` after "Download complete!" and preface the subsequent info with `Installing for the first time?` Example below:
```
Linkerd was successfully installed 🎉

Upgrading? https://linkerd.io/2/tasks/upgrade/

Installing for the first time? Add the linkerd CLI to your path with:

  export PATH=$PATH:$HOME/.linkerd2/bin

[rest of output stays the same]
```

No other changes to the text of the output.
If this looks good to you, would you like me to create a new issue for this with that specification, so someone can grab it if they get time before I do?

**Comment by scottcarol** [comment]
@grampelberg see above comment, let me know if you'd like me to create a new issue!

**Comment by grampelberg** [comment]
Looks great to me! I think we might want to tweak the output a little bit from a structure perspective as it is all blending together, but we can iterate on that in the PR =)

**Comment by scottcarol** [comment]
Closing this, opened issue in the `website` repo [here](https://github.com/linkerd/website/issues/419)
