### ISSUE TITLE
Automate releases from CI

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#3021]
Once we figure out our plans for CI, we should add a tag-driven means for executing a release without human intervention.

We should NOT try to automate construction of the changelog.

The release should cover everything from building artifacts to updating the website to validating that the curl-install completes as expected.

**Comment by grampelberg** [comment]
Just as an example, I’m pretty happy with how it ended up with ksync: https://github.com/vapor-ware/ksync/blob/master/.circleci/config.yml#L178

**Comment by grampelberg** [comment]
Historical

----

Once we figure out our plans for CI, we should add a tag-driven means for executing a release without human intervention.

We should NOT try to automate construction of the changelog.

The release should cover everything from building artifacts to updating the website to validating that the curl-install completes as expected.

**Comment by alpeb** [comment]
Fixed by #4091 #4090 #4094 #4100 #4106
