### ISSUE TITLE
report arbitrary headers in tap/top view

### ISSUE THREAD

**Issue by memory** [linkerd/linkerd2#3035]
## Feature Request

Tap and Top currently have a limited number of output fields; it would be extremely useful to be able to specify arbitrary http/grpc headers to display.

For extra points, being able to specify a field extraction with a regex would be keen.

### What problem are you trying to solve?

In many cases, the source IP of a request is uninteresting: it will always be the internal IP of some sort of load balancer.  What we actually care about is the `X-Forwarded-For` header, and specifically we care about the _first_ (comma-separated) value in the list of IPs it will contain.

Similarly, in many cases all traffic behind a perimeter LB will be in http/cleartext, but being able to see the contents of the `X-Forwarded-Proto` header could be extremely useful.

### How should the problem be solved?

Minimally, some sort of `--fields` flag to top/tap that let me specify fields to list, perhaps in golang template format or along the lines of the [gcloud --format / --filter specification](https://cloud.google.com/sdk/gcloud/reference/topic/formats)

### Any alternatives you've considered?

Paying many tens/hundreds of thousands of dollars for a splunk license? :(

### How would users interact with this feature?

```
linkerd top --fields='Source={{.header["X-forwarded-for"]}}, Destination={{.destination}}, Method={{.method}}, Path={{.path}}, Proto={{.header["X-forwarded-proto"]}}'
```

**Comment by olix0r** [comment]
`linkerd tap -o json` now displays header information! We should consider how this can be leveraged in other commands that use Tap internally.

**Comment by memory** [comment]
\o/

**Comment by wmorgan** [comment]
Is there anything else to this issue or can we close it?

**Comment by olix0r** [comment]
@wmorgan headers are only exposed in the raw JSON output of `linkerd tap`. It seems likely it could be useful in other views that consume tap (like the web ui), top, etc

**Comment by grampelberg** [comment]
Still valuable!

**Comment by tharun208** [comment]
I ll take this up

**Comment by hiteshwani29** [comment]
I would like to work on this issue.
But instead of filtering output fields in this format
 ``` 
--fields='Source={{.header["X-forwarded-for"]}}, Destination={{.destination}}, Method={{.method}}, Path={{.path}}, Proto={{.header["X-forwarded-proto"]}}' 
``` 
can we add jpath filter in the -o flag in a similar way the Kubectl is supporting?
**ex**: ref (https://kubernetes.io/docs/reference/kubectl/jsonpath/)
```
kubectl get pods -o=jsonpath="{.items[*]['metadata.name', 'status.capacity']}"
```

**Comment by adleong** [comment]
@hiteshwani29 I like this idea!

**Comment by hiteshwani29** [comment]
@adleong At this moment -o json flag is only supported for the tap command. So under this issue, I can raise PR only for the tap command to for supporting jsonpath filter.
Can we create another issue to support -o json and -o jsonpath flags for the top command?
