### ISSUE TITLE
"linkerd check" reporting as missing clusterroles that actually exist

### ISSUE THREAD

**Issue by klingerf** [linkerd/linkerd2#3036]
### What is the issue?

When I run `linkerd check`, I see:

```
× control plane ClusterRoles exist
    missing ClusterRoles: linkerd-linkerd-controller, linkerd-linkerd-identity, linkerd-linkerd-prometheus, linkerd-linkerd-proxy-injector, linkerd-linkerd-sp-validator, linkerd-linkerd-tap
    see https://linkerd.io/checks/#l5d-existence-cr for hints
```

But those cluster roles exist in my cluster:

```
$ kubectl get clusterroles | grep linkerd
linkerd-linkerd-controller                                             33d
linkerd-linkerd-identity                                               33d
linkerd-linkerd-prometheus                                             33d
linkerd-linkerd-proxy-injector                                         33d
linkerd-linkerd-sp-validator                                           33d
linkerd-linkerd-tap                                                    33d
```

The issue appears to be that they're not labeled with the `linkerd.io/control-plane-ns` label.

I have `edge-19.6.2` installed on my cluster, and I'm using the `edge-19.7.1` CLI to run the check. Did the `linkerd.io/control-plane-ns` label get added to clusterroles since `edge-19.6.2`? Won't this also be an issue when using the `stable-2.4.0` CLI to run `linkerd check` against a `stable-2.3.2` cluster?

### Environment

- Kubernetes Version:
```
$ kubectl version --short
Client Version: v1.13.4
Server Version: v1.13.5
```
- Linkerd version:
```
$ linkerd version
Client version: edge-19.7.1
Server version: edge-19.6.2
```
- Cluster Environment: AKS
- Host OS: Ubuntu 16.04.6 LTS
- Kernel version: 4.15.0-1040-azure
- Container runtime: docker://3.0.4

### Additional context

It's possible this issue just requires documentation, but it surprised me to see the check fail after upgrading the CLI only. Maybe we could make the check more flexible and not require that the clusterroles be labeled with `linkerd.io/control-plane-ns`?

**Comment by siggy** [comment]
Relates to #2987.

**Comment by ihcsim** [comment]
@klingerf Thanks for bringing this up. I actually added this issue into the 2.4 upgrade notes issue at https://github.com/linkerd/website/issues/349 couple days ago. My first thought is that this just requires some documentation, since our upgrade doc usually tells users to run `linkerd upgrade`, right after installing the new CLI. LMK if updating the upgrade doc will suffice.

cc @grampelberg

**Comment by klingerf** [comment]
@ihcsim Thanks for the additional info! Am happy to close this in favor of linkerd/website#349. And maybe we should just decide that `linkerd check` isn't backwards compatible for older versions of the control plane. If we do decide that officially, we should document it on the website somewhere.
