### ISSUE TITLE
`linkerd inject` doesn't work when supplying a full path to a file outside the current dir

### ISSUE THREAD

**Issue by alpeb** [linkerd/linkerd2#3037]
`linkerd inject /foo/bar/baz.yml` returns:
```
Error: Get /foo/bar/baz.yml: unsupported protocol scheme ""
```

I believe this bug was introduced in #2988 in edge-19.6.4

CC @Pothulapati

**Comment by ihcsim** [comment]
Good catch! I'm surprised that `url.ParseRequestURI()` and `url.Parse()` didn't return an error when given an absolute file path. We can either update the [`isValidURL()`](https://github.com/Pothulapati/linkerd2/blob/3cbe9cb54f0892ed9c87bc3659c1baf55384fdee/cli/cmd/inject_util.go#L173) to check for the parsed URL `Host` and `Scheme`:

```go
func isValidURL(path string) bool {
	url, err := url.ParseRequestURI(path)
        if err != nil {
          return false
        }

	return url.Host != "" && url.Scheme != ""
}
```
Or just do what `kubectl` did [here](https://github.com/kubernetes/cli-runtime/blob/92e6ccd8a070991c43024c9ef9989b68b47452c1/pkg/resource/builder.go#L227-L228), by checking the string prefix.
