### ISSUE TITLE
Add more parameters abount prometheus when linkerd install

### ISSUE THREAD

**Issue by yeya24** [linkerd/linkerd2#3053]
## Feature Request
Add more parameters when linkerd install, especially install prometheus.
For example, I want to configure the tsdb.retention time for prometheus, but now it is fixed 6h.

### What problem are you trying to solve?
Make installation more flexible.

### How should the problem be solved?
Currently I see the installation is using helm chart, so just add several helm variables and add these to cmd flags.

**Comment by grampelberg** [comment]
Does https://linkerd.io/2/tasks/customize-install/ work for you?

**Comment by yeya24** [comment]
Thanks for your reply! @grampelberg  It is a way to do this. But I think it would be nice to consider adding more parameters as well :smile:. I will close this issue.

**Comment by grampelberg** [comment]
@yeya24 totally! We’re walking a bit of a fine line between allowing customization through the normal install method (`linkerd install`) and making it possible for folks to change whatever they’d like. 

At the moment, the rule of thumb is that linkerd specific configurations are part of the install options and more generic configuration (anything k8s related, bundled components like prometheus) are a little outside of that scope. Right now, I’m checking to see if the customization approach even works for folks or whether there’s a different solution required.
