### ISSUE TITLE
submit k8s-env with heartbeat

### ISSUE THREAD

**Issue by siggy** [linkerd/linkerd2#3058]
#3056 introduces a heartbeat CronJob. Per #2961, this should include k8s environment information.

**Comment by siggy** [comment]
@grampelberg Please embellish this ticket with particular k8s environment data you'd be interested in seeing.

**Comment by grampelberg** [comment]
In a perfect world, it’d be whether it is cloud/on-prem and if it is a hosted solution, what it is (AKS, EKS, GKE).

**Comment by wmorgan** [comment]
Whatever we do, let's make sure it's as anonymized as possible

**Comment by grampelberg** [comment]
The node version seems to be good enough for now, closing out.
