### ISSUE TITLE
Fullscreen mode for service mesh diagram

### ISSUE THREAD

**Issue by memory** [linkerd/linkerd2#3061]
## Feature Request

Presently, the top view of the service mesh for a given namespace (e.g. http://linkerd-web:50750/namespaces/default) allocates about 3.5 inches, vertically, for the draggable live graph view.  There should be some way to view a page that _only_ has the live graph, giving it more space.

### What problem are you trying to solve?

For any namespace with a nontrivial number of deployments in the mesh, the live graph view is basically useless, because there is not enough space to render it in any sane fashion, e.g.:

<img width="631" alt="Screen Shot 2019-07-10 at 11 24 00 AM" src="https://user-images.githubusercontent.com/394064/60982428-1b05b180-a306-11e9-9032-dc2e40b9e3da.png">

### How should the problem be solved?

Give the graph more space! Either a button to hide the list views below, or make the lists draggable, or just a button to open the graph in a new window.

**Comment by grampelberg** [comment]
That whole topography could use some love for sure!

**Comment by falcoriss** [comment]
Feature request matches my thought exactly. It's a very cool feature that needs more space to readable when you have more than 3 services !

**Comment by manojkmisra** [comment]
I vote

**Comment by christyjacob4** [comment]
@grampelberg I would like to work on this

**Comment by grampelberg** [comment]
We'd like to move over to https://cytoscape.org/ for doing all the charting. This should be closed out and used as a requirement for that work.
