### ISSUE TITLE
consider relaxing k8s 1.12 requirement

### ISSUE THREAD

**Issue by siggy** [linkerd/linkerd2#3068]
After the 2.4 release, a user reported being unable to install Linkerd, as they were on K8s 1.11.7, and Linkerd now requires 1.12.

Source of the requirement:
https://github.com/linkerd/linkerd2/issues/2850#issuecomment-498321658

If a large swath of users are still on pre-1.12, and the `sideEffects` field is the only thing forcing Linkerd to require 1.12, we should consider relaxing this requirement.

**Comment by klingerf** [comment]
It seems like a straightforward fix would be to default the `--omit-webhook-side-effects` flag to false, at least until 1.12 clusters are more pervasive.a

**Comment by alpeb** [comment]
We had bumped the minimum version from 1.10 to 1.12. If we decide to undo that, we should at least enforce 1.11 given the `additionalPrinterColumns` property in the trafficsplit crd requires it.

**Comment by adleong** [comment]
`additionalPrinterColumns` is nice, but not critical.  I wouldn't be heartbroken to remove our use of it if that's would allow us to reduce our minimum version.

**Comment by grampelberg** [comment]
I would like to stick as closely as humanly possible to the supported Kubernetes versions.

**Comment by olix0r** [comment]
The [docs](https://linkerd.io/2/getting-started/#step-0-setup) have been updated to reflect this change:

> Before we can do anything, we need to ensure you have access to a Kubernetes cluster running 1.12 or later, and a functioning kubectl command on your local machine. (One easy option is to run Kubernetes on your local machine. We suggest Docker Desktop or Minikube, but there are many options.)

We're sticking to the Kubernetes project policy [documented here](https://kubernetes.io/docs/setup/release/version-skew-policy/).
