### ISSUE TITLE
Custom PSP for Linkerd

### ISSUE THREAD

**Issue by codeman9** [linkerd/linkerd2#3074]
### What problem are you trying to solve?

It is great that linkerd 2.4.0 introduces a custom built PSP for its components. My cluster is even a little more restrictive than what is provided, though. For example, my cluster requires that `runAsUser` is `MustRunAsNonRoot` and that the fsGroups/supplementalGroups are limited to UIDs between 10001 and 65535. When I make these changes to the linkerd custom provided PSP, linkerd seems to work fine.

I'd like to be able to point the linkerd components at my own cluster's PSP without creating a new one. I understand that the PSP I use would need to meet the requirements for linkerd.

FWIW, I use linkerd with the CNI configuration only and haven't tested the changes above with a non-CNI setup.

### How should the problem be solved?

Perhaps an install flag `--psp-name` or similar where I could input my custom PSP name. This would also be used during `linkerd check` to ensure it was restrictive/permissive enough.

### Any alternatives you've considered?

The cool thing about the linkerd install process is that there is always the ability to edit the `.yaml` that is output by the `linkerd install` command where I can delete the provided PSP and update the Roles and RoleBindings.

Alternatively, changing the custom provided PSP to what I need is always an option. :)

**Comment by grampelberg** [comment]
Is there any reason to not just make these changes?

**Comment by codeman9** [comment]
I can't think of any, but I haven't tested the changes on a non-CNI installation.

**Comment by grampelberg** [comment]
Mind putting up a PR? I can test in a couple of my experimental clusters and see what happens =)

**Comment by ihcsim** [comment]
`runAsUser: MustRunAsNonRoot` probably won't work for non-CNI mode because of the `proxy-init` init container.

**Comment by codeman9** [comment]
Slightly related, `linkerd check` looks for the existence of the PSP...but we won't be using that one so it will always fail for us.

**Comment by ihcsim** [comment]
Can you label your PSP with `linkerd.io/control-plane-ns: <linkerd-control-plane>`? That will satisfy `linkerd check`; it just wants to make sure that all the required resources are present.

**Comment by codeman9** [comment]
I don't have the ability to do that since I'm not a cluster admin, I can certainly ask, though.
