### ISSUE TITLE
Support Header Injection (Knative support)

### ISSUE THREAD

**Issue by mattmoor** [linkerd/linkerd2#3079]
### What problem are you trying to solve?

Minimum feature set for github.com/knative/serving integration

### How should the problem be solved?

To support scale from zero in the presence of traffic splits, we require the ability to inject headers into the data-plane per-split.  e.g. if we have a traffic split with:
```
spec:
  traffic:
  - revisionName: foo
    percent: 50
  - revisionName: bar
    percent: 50
```

We inject headers into the requests to let the downstream component that buffers requests know exactly which revision needs rehydration.

### Any alternatives you've considered?

There are a number of possible solutions to this, but effectively all of them devolve to some sort of request rewriting capability.

### How would users interact with this feature?

For Knative this is simply used internally by the controllers that turn our high level API (see above example) into the lower-level network configs (e.g. Istio, Ambassador, Gloo, and hopefully linkerd)

**Comment by mattmoor** [comment]
Note that I *think* this is the main remaining feature gap to support knative/serving with the recent addition of traffic splitting.

**Comment by mattmoor** [comment]
cc @tcnghia also (our networking lead)

**Comment by grampelberg** [comment]
@mattmoor so on the client side, you want to look up a destination service and add a header that is specific to that which is separate from the `:authority`?

**Comment by mattmoor** [comment]
Yes

**Comment by grampelberg** [comment]
Can it be specific to the linkerd implementation, or does it need to be arbitrary and generic for knative?

**Comment by mattmoor** [comment]
We configure the header we want injected and the value it gets.  We don't really want implementation-specific details to creep in, if we can avoid it.

**Comment by grampelberg** [comment]
Yup, makes a lot of sense =)

**Comment by Vad1mo** [comment]
I would be awesome if linkerd could work together with knative. ISTIO is such a mess. 

How can we help here?

**Comment by mattmoor** [comment]
I'm happy to provide support from the Knative side here (as would @tcnghia), but don't know what's needed to drive changes on the linkerd side.  I may try to catch someone at the kubecon booth to talk to about this 🤞  because I too would like to see support for linkerd land.  Let me know how I can help as well.

**Comment by grampelberg** [comment]
@mattmoor I'm around and would love to chat. Drop by the Buoyant booth when it is convenient!
