### ISSUE TITLE
Authenticate/authorize access to the tap server by converting the public API to an API extension server

### ISSUE THREAD

**Issue by briansmith** [linkerd/linkerd2#308]
After the web UI and public API are TLS-enabled, they should be converted to API extension servers so that we can integrate with the user authentication mechanisms provided to API extension servers:

- [ ] After the Conduit CA generates the root certificate, it must create/update the APIServer definition for the public API to include the new caBundle. (See https://github.com/kubernetes-incubator/apiserver-builder/blob/master/example/config/apiserver.yaml)
- [ ] Update the CLI to access the public API through the API server extension URL instead of a "proxy" URL.
- [ ] Change the public API server to log all tap requests (#143).
- [ ] Define a new (Cluster)Role for the tap service.
- [ ] Change the public API server to verify that the user has tap service role before initiating the tap, rejecting the request if the user doesn't have the role.

**Comment by briansmith** [comment]
Assuming this is successful, we'll do the same for the web UI and other (non-tap) aspects of the public API in a follow-up.

**Comment by grampelberg** [comment]
Fixed by #3171.
