### ISSUE TITLE
inject: Set an environment variable on application containers?

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#3081]
Problem: The application containers may want to detect when it's running with Linkerd (for instance, for the purposes of linkerd-await). There is currently no means to do that except for checking for whether the admin socket is bound; but this is unreliable before the proxy has started.

Can inject set an environment variable on application containers to indicate that linkerd is present? I think, ideally, we'd include environment variables that enumerate the proxy's inbound/outbound/admin socket addresses.

**Comment by grampelberg** [comment]
This is gonna be a toughie with how we’re thinking about doing helm injection I think …

**Comment by ihcsim** [comment]
@grampelberg Is this something that can be added to the "patch" chart?

**Comment by memory** [comment]
Hi stalebot.  This would still be nice to have. :)
