### ISSUE TITLE
Request with self-signed client certificates return a 400 Bad Request

### ISSUE THREAD

**Issue by ralfwagneryes** [linkerd/linkerd2#3084]
### What is the issue?
Bad Request (400) occurs when trying to access a Kubernetes (Minikube) cluster with a self-signed certificate.

### How can it be reproduced?
Our application (REST API) uses mTLS for client authentication, i. e. a client must add a self-signed certificate to each request. We use the Nginx Inc.  Nginx as Ingress controller and for TLS termination. Nginx extracts the client certificate and adds it to a custom header which is then passed to our microservices.

When the client certificate is ommitted, the application behaves as expected. The microservices return an 401 unauthorized result.

Requests with a proper client certificate (tested before meshing with Linkerd2) return a 400 Bad Request after meshing.

The nginx ingress controller uses the setting `ssl_verify_client optional_no_ca;` to allow for self signed certificates and `proxy_set_header X-Passed-Client-Cert-UmFjY29vbiBDaXR5 $ssl_client_cert;` to pass the certificate as a header to the services.

As per the Linkerd2 documentation we added
```text
        proxy_set_header l5d-dst-override mymicroservice.platform-local.svc.cluster.local:80;
        proxy_hide_header l5d-remote-ip;
        proxy_hide_header l5d-server-id;
```

### Logs, error output, etc
Setting the Linkerd log level to debug and performing a GET request on one of the services resulted in a log containing the an error `hyper::proto::h1::conn parse error (invalid HTTP header parsed)`:

```text
platform-ingress-84967dcd48-m455p platform-ingress 127.0.0.1 - - [15/Jul/2019:09:08:18 +0000] "GET /clients HTTP/1.1" 400 0 "-" "PostmanRuntime/7.15.0"
platform-ingress-84967dcd48-m455p linkerd-proxy DBUG [  2007.335295s] tokio_reactor loop process - 1 events, 0.000s
platform-ingress-84967dcd48-m455p linkerd-proxy DBUG [  2007.335422s] proxy={server=out listen=127.0.0.1:4140} linkerd2_proxy::transport::tls::listen accepted connection from 172.17.0.5:47830 to Some(V4(172.17.0.17:80)); skipping TLS (loopback)
platform-ingress-84967dcd48-m455p linkerd-proxy DBUG [  2007.335484s] tokio_reactor loop process - 1 events, 0.000s
platform-ingress-84967dcd48-m455p linkerd-proxy DBUG [  2007.335509s] tokio_reactor loop process - 1 events, 0.000s
platform-ingress-84967dcd48-m455p linkerd-proxy DBUG [  2007.335540s] proxy={server=out listen=127.0.0.1:4140 remote=172.17.0.5:47830} hyper::proto::h1::io read 1556 bytes
platform-ingress-84967dcd48-m455p linkerd-proxy DBUG [  2007.335558s] proxy={server=out listen=127.0.0.1:4140 remote=172.17.0.5:47830} hyper::proto::h1::conn parse error (invalid HTTP header parsed) with 1556 bytes
platform-ingress-84967dcd48-m455p linkerd-proxy DBUG [  2007.335561s] proxy={server=out listen=127.0.0.1:4140 remote=172.17.0.5:47830} hyper::proto::h1::role sending automatic response (400 Bad Request) for parse error
platform-ingress-84967dcd48-m455p linkerd-proxy DBUG [  2007.335604s] proxy={server=out listen=127.0.0.1:4140 remote=172.17.0.5:47830} hyper::proto::h1::io flushed 84 bytes
platform-ingress-84967dcd48-m455p linkerd-proxy DBUG [  2007.335628s] proxy={server=out listen=127.0.0.1:4140 remote=172.17.0.5:47830} tokio_reactor dropping I/O source: 8
```

#### `linkerd check` output

```text
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-api
-----------
√ control plane pods are ready
√ control plane self-check
√ [kubernetes] control plane can talk to Kubernetes
√ [prometheus] control plane can talk to Prometheus
√ no invalid service profiles

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ control plane is up-to-date
√ control plane and cli versions match

Status check results are √
```

### Environment
- Kubernetes Version: Server 1.15.0 / Client 1.14.1
- Cluster Environment: Minikube 1.2.0 (intended for production: Azure Kubernetes Service)
- Host OS: mac OS X
- Linkerd version: Client & Server: stable-2.4.0

### Additional context
Please let me know if I can provide more information.

**Comment by ralfwagneryes** [comment]
I was able to reproduce the problem with the emojivoto demo app:
* I deployed the emojivoto demo to Minikube as describe in the Getting Started documentation.
* I added an Nginx ingress controller to to access the web frontend as done in our application.
* The frontend is accessible by browser and curl command.
* When accessing the frontend with the same curl command and adding a self-signed client certificate & key, the error occurs (400 Bad Request).

**Comment by olix0r** [comment]
@ralfwagneryes can you include the full HTTP request that your application is sending?

We suspect that this failure is related to a very large header or some other request issue that prevents the proxy's serverside from properly parsing the request.

**Comment by ralfwagneryes** [comment]
@olix0r I'm not quite sure, how to do this, when I use curl without a certificate, everything works fine, but when I do a simple `curl -v -k -X GET https://emojivoto.local.yes.com --cert cert.pem --key key.pem` I get the error and the following output:

```text
curl -v -k -X GET https://emojivoto.local.yes.com --cert cert.pem --key key.pem
Note: Unnecessary use of -X or --request, GET is already inferred.
* Rebuilt URL to: https://emojivoto.local.yes.com/
*   Trying 192.168.99.100...
* TCP_NODELAY set
* Connected to emojivoto.local.yes.com (192.168.99.100) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Request CERT (13):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS handshake, CERT verify (15):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=NGINXIngressController
*  start date: Sep 12 18:03:35 2018 GMT
*  expire date: Sep 11 18:03:35 2023 GMT
*  issuer: CN=NGINXIngressController
*  SSL certificate verify result: self signed certificate (18), continuing anyway.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7fe6de809400)
> GET / HTTP/2
> Host: emojivoto.local.yes.com
> User-Agent: curl/7.54.0
> Accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 400
< server: nginx
< date: Wed, 17 Jul 2019 06:56:01 GMT
< content-length: 0
< strict-transport-security: max-age=31536000; preload
<
* Connection #0 to host emojivoto.local.yes.com left intact
```
An example certificate and key is included in the attachment above and was generated with `openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365 -subj '/CN=linkerd2testclient' -nodes`

**Comment by ihcsim** [comment]
@ralfwagneryes Thanks for the additional details. I **think** this should give us enough info to reproduce the problem. But just in case, one way to sniff the request is to use the `linkerd-debug` sidecar. Using the `emoji` deployment as an example, add the `config.linkerd.io/enable-debug-sidecar: "true"` annotation to the `Deployment`'s `spec.template.metadata.annotations`. Then you will see that the pod is restarted with one more sidecar container.
```sh
$ kubectl -n emojivoto get po emoji-5656b67d59-p9jvz
NAME                     READY   STATUS    RESTARTS   AGE
emoji-5656b67d59-p9jvz   3/3     Running   0          24m
```

Then you can access the debug container with:
```sh
$ kubectl -n emojivoto exec -it emoji-5656b67d59-p9jvz -c linkerd-debug -- /bin/bash
```

Inside the container, running something like the following should give more insights into the request headers:
```sh
# root@emoji-5656b67d59-p9jvz:~# tshark -i any -f "tcp" -V -Y "http.request"
```

**Comment by olix0r** [comment]
Ah hah:

```
< HTTP/2 400
< server: nginx
< date: Wed, 17 Jul 2019 06:56:01 GMT
< content-length: 0
< strict-transport-security: max-age=31536000; preload
```

This indicates that _nginx_ is returning the 400, which probably relates in some way to nginx's configuration...

**Comment by ralfwagneryes** [comment]
Probably, but as the unmeshed configuration works, I suppose this is due to the fact, that adding the mesh / Linkerd-proxy prevents NGINX from reaching the microservice.

**Comment by ralfwagneryes** [comment]
Here is the log asked for by @ihcsim (very concise description, thanks).
[ingress.log](https://github.com/linkerd/linkerd2/files/3403715/ingress.log)

**Comment by ralfwagneryes** [comment]
Here is a more detailed description how to reproduce the problem:

[emojivoto-ingress-issue-3084-improved-description.zip](https://github.com/linkerd/linkerd2/files/3422551/emojivoto-ingress-issue-3084-improved-description.zip)

Hope this helps, any ideas what might cause the problem?

**Comment by ralfwagneryes** [comment]
Any progress on this issue? We'd like to continue with our evaluation of Linkerd for our production environment, but this is issue is currently a blocker.

**Comment by wmorgan** [comment]
@ralfwagneryes we're planning on digging into this shortly (thank you for the repro!) but need to  conclude some other proxy work first. It's definitely on our radar.

**Comment by ralfxwagner** [comment]
@wmorgan Thanks for the update. Please let me know if I can be of assistance.

**Comment by seanmonstar** [comment]
The issue is that the HTTP/1.1 request sent to the proxy includes a header using obs-folding. This has been deprecated, as described in [RFC 7230](https://tools.ietf.org/html/rfc7230#section-3.2.4):

> Historically, HTTP header field values could be extended over
> multiple lines by preceding each extra line with at least one space
> or horizontal tab (obs-fold).  This specification deprecates such
> line folding [..] A sender MUST NOT generate a message that includes
> line folding (i.e., that has any field-value that contains a match to
> the obs-fold rule) [..]

The HTTP library used by the proxy doesn't support obs-fold headers, and so it is responding with a 400 Bad Request.

**Comment by grampelberg** [comment]
@ralfwagner are you able to make application changes? There are probably some more sustainable RFC compliant solutions we could come up with after a little brainstorming and understanding your requirements.

**Comment by ralfwagneryes** [comment]
We're using nginx as ingress controller for extracting the certificate and writing it as the header. There seems to be a directive that converts the header as a single line. ($ssl_client_escaped_cert instead of ssl_client_cert, see http://nginx.org/en/docs/http/ngx_http_ssl_module.html#var_ssl_client_escaped_cert).
@seanmonstar @grampelberg Thanks for your help, I'll let you know the result.

**Comment by grampelberg** [comment]
Nginx configuration is a dark, dark art. That's awesome! Please keep us updated =)

**Comment by ralfwagneryes** [comment]
The short version: I got it working by using the nginx directive $ssl_client_escaped_cert instead of $ssl_client_cert.
The long version: I first reproduced the error with Linkerd 2.5. Sending a request with a client certificate resulted as before in HttpError 400.
After replacing  $ssl_client_cert with $ssl_client_escaped_cert, the microservices in our application could be reached. I still got an error, but this time an authentication failure from the microservice I was calling, as the certificate in the header was not recognized as it is now urlencoded. But that just means that we have to change the parsing of the header in our application, while the general setup of the Linkerd mesh works.
Thanks again for your help, this is looking quite promising now.
Please let me know if you need some more information e.g. for using nginx as ingress controller in the documentation.
