### ISSUE TITLE
Auto injection only works with Docker Swarm deployed kubernetes stack at namespace level

### ISSUE THREAD

**Issue by weiluoacct** [linkerd/linkerd2#3088]
## Bug Report
Creating this issue per suggestion of charles to track the problem, this is NOT a linkerd issue

### What is the issue?
When a service stack is deploy to kubernetes cluster from the docker stack deploy --orchestrator=kubernetes command, it does not get intermediate kubernetes yaml file(s) generated, and it is considered a different type of kubernetes configuration than the one created by kubectl CLI commands (create, apply etc.)

Because of this, the service stack cannot be injected with linkerd at pod or deploy levels using the suggested 'kubectl get deploy -o yaml | linkerd inject - | kubectl apply -f -' pipeline, because Kubernetes does not take mixed configurations.

charles suggested to add annotation of "linkerd.io/inject: enabled" to the namespace, and it works.

### How can it be reproduced?
Use docker stack deploy --orchestrator=kubernetes to deploy your stack, then try to inject linkerd to either deploy or pod

### Logs, error output, etc
PS C:\_dev\Docker> kubectl -n uops get deploy -o yaml | linkerd inject - > uops\uops-injected.yml

deployment "uops" injected

PS C:\_dev\Docker> kubectl apply -f uops\uops-injected.yml
Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply
deployment.extensions/uops configured

(If the output is long, please create a [gist](https://gist.github.com/) and
paste the link here.)

#### `linkerd check` output
PS C:\_dev\Docker> linkerd check
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-api
-----------
√ control plane pods are ready
√ control plane self-check
√ [kubernetes] control plane can talk to Kubernetes
√ [prometheus] control plane can talk to Prometheus
√ no invalid service profiles

linkerd-version
---------------
√ can determine the latest version
‼ cli is up-to-date
    is running version 19.7.1 but the latest edge version is 19.7.3
    see https://linkerd.io/checks/#l5d-version-cli for hints

control-plane-version
---------------------
‼ control plane is up-to-date
    is running version 19.7.1 but the latest edge version is 19.7.3
    see https://linkerd.io/checks/#l5d-version-control for hints
√ control plane and cli versions match

Status check results are √

```text
your output here ...
```

### Environment
Docker Desktop Edge 19.3.0.RC2

- Kubernetes Version: 1.14.3
- Cluster Environment: (GKE, AKS, kops, ...) Docker built-in kubernetes cluster
- Host OS: Windows 10 Enterprise / Moby Linux
- Linkerd version: 19.7.1

### Possible solution
Add linkerd inject annotation to namespace

**Comment by grampelberg** [comment]
@weiluoacct I’m not super familiar with stacks. Is there a way to set annotations in the stack definition that follow through to the k8s YAML?

**Comment by weiluoacct** [comment]
docker stack does not allow annotations property in its yaml file
