### ISSUE TITLE
GRPC load balancing :/

### ISSUE THREAD

**Issue by fkarakas** [linkerd/linkerd2#3089]
Hello, 
When using linkerd for a grpc client and server, we face an "issue", if we scale the number of servers from 1 to n, the connection is not load balanced with the new servers. 
The client keeps connecting to the first server.

This is the application used for the test : https://github.com/fkarakas/helloword-grpc

But i noticed that if "unmesh" the server side (removing the sidecar proxy from the server by removing the annotation), the load balancing seems to work.

Do you you know why meshing client and server is not load balancing ?

To reproduce 
```
kubectl apply -f kubernetes/grcp-server.yaml
kubectl apply -f kubernetes/grcp-client.yaml
kubectl scale deploy helloworld-grpc-server --replicas=10
```

To view the log of the client (showing the ip address of the server which is connecting to) : 
```
kubectl logs -f helloworld-grpc-client-XXXXX  -c client
```

**Comment by grampelberg** [comment]
gRPC load balancing happens entirely on the client side. Did you inject the client? You can also test with emojivoto as it uses gRPC to talk to both the `emoji` and `voting` services.

**Comment by grampelberg** [comment]
@fkarakas any updates?

**Comment by fkarakas** [comment]
Hello Thomas,
Sorry for the delay.
Waht do you mean by "Do you inject the client ?". I injected linkerd on both side client & server side via the annotation : https://github.com/fkarakas/helloword-grpc/blob/master/kubernetes/grpc-client.yaml#L15

https://github.com/fkarakas/helloword-grpc/blob/master/kubernetes/grpc-server.yaml#L29

For the GRPC load balancing in the client side, i am doing something like : 
```
// Set up a connection to the server.
	conn, err := grpc.Dial(address, grpc.WithInsecure())
	if err != nil {
		log.Fatalf("did not connect: %v", err)
	}
	defer conn.Close()
```
I am going to check the emojivoto but i don't understand why i have an issue when i inject bother sides (client & server enabled annotation to enabled) ?

**Comment by ihcsim** [comment]
@fkarakas That's strange. It should just work. Technically, you only need to inject the Linkerd proxy on the client side. I notice that your client is sending [a request every 2 seconds](https://github.com/fkarakas/helloword-grpc/blob/1c483691c006bcca31db29c3ed6852447df4a8f7/client/main.go#L55). Can you try reduce the sleep interval to 100, 250, 500 milliseconds etc, and let your client run for at least a minute or two?

**Comment by wmorgan** [comment]
@cpretzer might be worth adding to your list of things to repro

**Comment by Rathil** [comment]
I have exactly the same problem.
I did everything according to the instructions, but the requests from the Client fall only on one POD server, although there are 2 PODs in the system.

**Comment by grampelberg** [comment]
@Rathil you might want to ask a question in discussions with the full manifest of what you're doing. Remember, it isn't possible to load balance gRPC streams and load balancing happens on the client side, so that must be injected with linkerd.

**Comment by Rathil** [comment]
> @Rathil you might want to ask a question in discussions with the full manifest of what you're doing. Remember, it isn't possible to load balance gRPC streams and load balancing happens on the client side, so that must be injected with linkerd.

I have 2 services: client and server.
Client:
`
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: router
spec:
  selector:
    matchLabels:
      app: router
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: router
    spec:
      imagePullSecrets:
        - name: git-lab-token
      containers:
        - name: app
          image: XXX/ms/router:latest
          imagePullPolicy: Always
          args:
            - run
            - --db-mongo-db-name=XXX
            - --domain-suffix=XXX
            - --cert-email=XXX
          env:
            - name: DB_MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-router
                  key: uri
---
apiVersion: v1
kind: Service
metadata:
  name: router
  labels:
    app: router
spec:
  type: LoadBalancer
  selector:
    app: router
  ports:
    - port: 80
      name: http
    - port: 443
      name: https
`

Server:
`
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: project
spec:
  selector:
    matchLabels:
      app: project
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: project
    spec:
      imagePullSecrets:
        - name: git-lab-token
      containers:
        - name: app
          image: XXX/ms/project:latest
          imagePullPolicy: Always
          args:
            - run
            - --db-mongo-db-name=XXX
          env:
            - name: DB_MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-skribio
                  key: uri
---
apiVersion: v1
kind: Service
metadata:
  name: project-grpc
  labels:
    app: project
spec:
  selector:
    app: project
  ports:
    - port: 8081
      name: grpc
`
From the client I open the connection to the server side (and do not close the connection), but send separate gRPC requests (not stream) from the client side to the server side.
The client is actually an "Ingress" who proxies requests from the outside world (browser or application) to a specific microservice, using name of MS.
At the same time, I see that requests always come to the same POD server.

![image](https://user-images.githubusercontent.com/2794944/82958035-1ea53400-9fbd-11ea-93b0-0bed869331b2.png)

**Comment by Rathil** [comment]
I tried to change
```yaml
kind: DaemonSet
```
at 
```yaml
kind: Deployment
#...
spec:
  replicas: 6
```

It didn't help. 6 PODs start, but the traffic always goes to one.

**Comment by grampelberg** [comment]
Please open a [discussion](https://github.com/linkerd/linkerd2/discussions).

**Comment by Rathil** [comment]
> Please open a [discussion](https://github.com/linkerd/linkerd2/discussions).

Ok [discussion](https://github.com/linkerd/linkerd2/discussions/4482)
