### ISSUE TITLE
proxy: Add request_handle_us histogram

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#3098]
As initially described in #730, there's a general need to understand the proxy's latency overhead. One could go pretty deep trying to answer this question, but I think we can start with a reasonably helpful indicator: the amount of time a request spends in the proxy.

I propose adding a new `request_handle_µs` histogram to the proxy with only a `direction` label. This histogram should store the elapsed time (in microseconds) from the moment a request reaches the source stack until the request is dropped.

**Comment by olix0r** [comment]
Note that this will likely want to use a mutex and RAII guards, like we do for the balancer's load metrics, so that we have a layer at the "top" of the stack that adds a request extension and a drop handle for the extension that updates the histogram.

This extension should be cloned when copying requests for retries and the metric should only be updated when _all_ clones have been dropped.

**Comment by hawkw** [comment]
Having a handle time metric is definitely valuable! 👍

FWIW, I think that we're close to having the tools to implement something like this (and any other arbitrary timing metrics) on top of `tracing` — see https://github.com/jonhoo/tracing-timing plus the ongoing work on composing multiple `tracing` subscribers. I can see a future where it's possible to dynamically request that a proxy create a timing metric for any tracing span in the proxy. Of course, that's a bit further out, and there's definitely value in having a handle time metric _now_; just felt like this was worth mentioning.

Re: the metric name, does prometheus support unicode in metric names? And, will a `µ` make the metric name harder for folks to write queries for? This is admittedly nitpicky...

**Comment by olix0r** [comment]
@hawkw https://prometheus.io/docs/instrumenting/exposition_formats/#text-format-details implies that UTF-8 chars are supported but it does sound like some additional restrictions may apply on metric names. I'd also be fine with `handle_us`. I'd prefer to avoid `microseconds` as it's quite verbose (and we use `_ms_` elsewhere)

**Comment by grampelberg** [comment]
I’d be more worried about the client querying libraries than actual prometheus storage. It would be nice to not have to hunt for how to get a `µ` when querying in the prometheus webui =)

**Comment by olix0r** [comment]
On closer reading

> It must match the regex [a-zA-Z_:][a-zA-Z0-9_:]*
