### ISSUE TITLE
linkerd dashboard should support --address

### ISSUE THREAD

**Issue by swgriffith** [linkerd/linkerd2#3100]
## Feature Request
Add support for the --address flag for linkerd dashboard, as supported by kubectl port-forward and kubectl proxy. 

### What problem are you trying to solve?
An assumed binding to 127.0.0.1 doesn't always work. For example, if you're running from within Windows Subsystem for Linux V2 you're actually running within a micro VM on the host, and if you run linkerd dashboard from your WSL ubuntu (or other distro) you'll appear to be hosting the dashboard on 127.0.0.1, but that's actually the localhost of the micro vm not the host machine. In that case what you really wanted was for it to be exposed on the eth0 interface of the micro vm. 

### How should the problem be solved?
It appears that linkerd dashboard is just using port forwarding in k8s. If I run the following from by WSL2 Ubuntu environment I can reach the dashboard:

kubectl port-forward -n linkerd svc/linkerd-web --address 172.22.212.183 8080:8084

I'd recommend a minor update to the cmd to enable a --address parameter, consistent with kubectl proxy and kubectl port-forward.

What do you want to happen? Add any considered drawbacks.

### Any alternatives you've considered?

For me the alternative would be to avoid WSL, which isnt ideal from a productivity perspective, or write my own script to handle the port forwards manually rather than using the linkerd dashboard command.

### How would users interact with this feature?

linkerd dashboard --address 172.22.212.183

Linkerd dashboard available at:
http://172.22.212.183:50750
Grafana dashboard available at:
http://172.22.212.183:50750/grafana
Opening Linkerd dashboard in the default browser

**Comment by grampelberg** [comment]
I’ve ran into this a couple times with my chromebook as well, I wish `port-forward` and `proxy` were easier to pass config options down to.

**Comment by bmcstdio** [comment]
I've opened #3274 in an attempt to implement this.
