### ISSUE TITLE
Kubernetes deployment failing to pull image "gcr.io/linkerd-io/proxy-init:stable-2.4.0"

### ISSUE THREAD

**Issue by viniciusd** [linkerd/linkerd2#3102]
## Bug Report
Kubernetes deployment failing to pull image "gcr.io/linkerd-io/proxy-init:stable-2.4.0"

### How can it be reproduced?
Triggering a new deployment

### Logs, error output, etc
```
  Warning  Failed                 9s (x3 over 51s)   kubelet,  Failed to pull image "gcr.io/linkerd-io/proxy-init:stable-2.4.0": rpc error: code = Unknown desc = Error response from daemon: manifest for gcr.io/linkerd-io/proxy-init:stable-2.4.0 not found
```
### Environment
- Kubernetes Version:
```
> kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.6-eks-d69f1b", GitCommit:"d69f1bf3669bf00b7f4a758e978e0e7a1e3a68f7", GitTreeState:"clean", BuildDate:"2019-02-28T20:26:10Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

- Cluster Environment: AWS
- Linkerd version: 2.4.0

### Possible solution
Uploading the stable-2.4.0 image to the image repository?
I couldn't find any image with that tag in there.

**Comment by alpeb** [comment]
Thanks for the report @viniciusd 
I'm unable to reproduce the issue. Did you download the linkerd client from [here](https://github.com/linkerd/linkerd2/releases), or did you build it yourself?

Could you also please post the output from `linkerd install`

**Comment by alpeb** [comment]
@viniciusd could you also please detail the exact set of steps you performed to try reproducing the issue?

**Comment by viniciusd** [comment]
As far as I could check at `gcr.io/linkerd-io`, it is missing an image with the tag `stable-2.4.0`, right?

I can go into my deployment scripts in order to get exact steps for reproducing though.

**Comment by viniciusd** [comment]
Thanks for the prompt reply :)

**Comment by alpeb** [comment]
The thing is that your deployment yaml shouldn't be asking for that image tag, so that's puzzling.

**Comment by viniciusd** [comment]
Also, I manually edited my statefulset in order to pick the `stable-2.3.2` image and it worked fine. Using that as a workaround for now.

**Comment by viniciusd** [comment]
For injecting:
```
cat $MY_YAML | linkerd inject - | kubectl apply -n $NAMESPACE -f -
```

**Comment by alpeb** [comment]
Before resetting your image tag to `stable-2.3.2`, did you manually set it to `stable-2.4.0`? If so, please leave it at `v1.0.0` which is what linkerd should be setting when injecting the proxy.

**Comment by viniciusd** [comment]
I haven't set it manually to stable-2.4.0 though.
How does it pick the image?

I just tried a manual inject and the only difference is the extra metadata:
```
    metadata:
      annotations:
        linkerd.io/inject: enabled
```
How is that picked up?

**Comment by alpeb** [comment]
By default the tag is `v1.0.0` but that can be overridden through the `config.linkerd.io/init-image-version` annotation in the pod template spec inside your StatefulSet, or through the command-line through `linkerd install|upgrade|inject --init-image-version`.
If that had been overridden in `linkerd install`, then all the following injections will pick that overridden version.
You can check if that's the case by looking into linkerd's config map:
`kubectl -n linkerd get configmap linkerd-config -oyaml`
and look for the string `init-image-version` in that yaml.

**Comment by viniciusd** [comment]
No `init-image-version` set
```
apiVersion: v1
data:
  global: |
    {"linkerdNamespace":"linkerd","cniEnabled":false,"version":"stable-2.4.0","identityContext":{"trustDomain":"cluster.local","issuanceLifetime":"86400s","clockSkewAllowance":"20s"},"autoInjectContext":null,"omitWebhookSideEffects":false}
  install: |
    {"uuid":"9e80922e-6148-41aa-912b-2e2b1917cbb3","cliVersion":"stable-2.4.0","flags":[]}
  proxy: |
    {"proxyImage":{"imageName":"gcr.io/linkerd-io/proxy","pullPolicy":"IfNotPresent"},"proxyInitImage":{"imageName":"gcr.io/linkerd-io/proxy-init","pullPolicy":"IfNotPresent"},"controlPort":{"port":4190},"ignoreInboundPorts":[],"ignoreOutboundPorts":[],"inboundPort":{"port":4143},"adminPort":{"port":4191},"outboundPort":{"port":4140},"resource":{"requestCpu":"","requestMemory":"","limitCpu":"","limitMemory":""},"proxyUid":"2102","logLevel":{"level":"warn,linkerd2_proxy=info"},"disableExternalProfiles":true,"proxyVersion":"stable-2.4.0","proxyInitImageVersion":"v1.0.0"}
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"global":"{\"linkerdNamespace\":\"linkerd\",\"cniEnabled\":false,\"version\":\"stable-2.4.0\",\"identityContext\":{\"trustDomain\":\"cluster.local\",\"issuanceLifetime\":\"86400s\",\"clockSkewAllowance\":\"20s\"},\"autoInjectContext\":null,\"omitWebhookSideEffects\":false}\n","install":"{\"uuid\":\"9e80922e-6148-41aa-912b-2e2b1917cbb3\",\"cliVersion\":\"stable-2.4.0\",\"flags\":[]}\n","proxy":"{\"proxyImage\":{\"imageName\":\"gcr.io/linkerd-io/proxy\",\"pullPolicy\":\"IfNotPresent\"},\"proxyInitImage\":{\"imageName\":\"gcr.io/linkerd-io/proxy-init\",\"pullPolicy\":\"IfNotPresent\"},\"controlPort\":{\"port\":4190},\"ignoreInboundPorts\":[],\"ignoreOutboundPorts\":[],\"inboundPort\":{\"port\":4143},\"adminPort\":{\"port\":4191},\"outboundPort\":{\"port\":4140},\"resource\":{\"requestCpu\":\"\",\"requestMemory\":\"\",\"limitCpu\":\"\",\"limitMemory\":\"\"},\"proxyUid\":\"2102\",\"logLevel\":{\"level\":\"warn,linkerd2_proxy=info\"},\"disableExternalProfiles\":true,\"proxyVersion\":\"stable-2.4.0\",\"proxyInitImageVersion\":\"v1.0.0\"}\n"},"kind":"ConfigMap","metadata":{"annotations":{"linkerd.io/created-by":"linkerd/cli stable-2.4.0"},"labels":{"linkerd.io/control-plane-component":"controller","linkerd.io/control-plane-ns":"linkerd"},"name":"linkerd-config","namespace":"linkerd"}}
    linkerd.io/created-by: linkerd/cli stable-2.4.0
  creationTimestamp: 2019-04-26T11:40:55Z
  labels:
    linkerd.io/control-plane-component: controller
    linkerd.io/control-plane-ns: linkerd
  name: linkerd-config
  namespace: linkerd
  resourceVersion: "41384878"
  selfLink: /api/v1/namespaces/linkerd/configmaps/linkerd-config
  uid: 2753b546-6818-11e9-b14a-021cbbc91acc
```

**Comment by alpeb** [comment]
I still don't see what could be the problem here. Would you mind joining our [slack](https://slack.linkerd.io) and ping me there so we can take a closer look?

**Comment by viniciusd** [comment]
Ok

**Comment by viniciusd** [comment]
That was caused by a version mismatch between the CLI (2.3) and the control plane (2.4).
