### ISSUE TITLE
HA - Update Proxy Injector's MWC to Ignore kube-system Namespace

### ISSUE THREAD

**Issue by ihcsim** [linkerd/linkerd2#3104]
A few users have experienced k8s cluster restart errors, when Linkerd runs in HA mode. Upon resizing a zero-node cluster, pods within the `kube-system` namespace can't be recreated because with the MWC's `failurePolicy` set to `Fail`, the k8s API server requires the proxy injector to be reachable regardless of whether the workloads will be injected or not.

Update the MWC to ignore the `kube-system` namespace will ensure that these system pods can be restarted, even if the proxy injector is unavailable.

Also, update the HA doc to mention that HA mode is recommended for production environment only, where there will be at least one proxy injector replicas.

**Comment by ihcsim** [comment]
Oops.. I just remember that the MWC selects namespaces by labels. Normally, `kube-system` isn't labelled. I'm hesitant to introduce yet another label. Maybe we can just update the HA doc with instructions on how to update the MWC to filter namespaces by adding their own label.

**Comment by grampelberg** [comment]
Sounds like a good step in the right direction to me!

**Comment by ihcsim** [comment]
Closing this issue, as we won't be making any changes to the MWC. Recent HA doc updates can be found in https://github.com/linkerd/website/pull/423.
