### ISSUE TITLE
docker-in-docker (dind): outbound traffic is pinned to localhost

### ISSUE THREAD

**Issue by wminshew** [linkerd/linkerd2#3107]
### What is the issue?
Linkerd2 sidecar with docker-in-docker (dind) causes builds to fail. It appears that outbound traffic from the daemon (on 172.17.0.0/16) is mis-recognized as inbound traffic & pinned to localhost.

### How can it be reproduced?
Use any dind image https://hub.docker.com/_/docker, inject linkerd2, & try to build a simple dockerfile [FROM ubuntu; RUN apt-get update]

### Additional context
Took awhile to debug with some help on the slack channel. Promised them a few months ago I'd add it as an issue to github but forget until recently. Don't have any of my old logs or pcaps around, but it should be easy enough to recreate. Doubt there's much interest in fixing this though as I think dind on k8s is pretty rare (for now I'm just not using linkerd2 on that deployment)

**Comment by jbhannah** [comment]
I ran into this as well, trying to run a Concourse worker in a Kubernetes cluster. When I looked at the `linkerd-proxy` container logs for the worker pod, it showed traffic from IP addresses belonging to the worker's runc subnet being redirected back into the pod (and being rejected because the pod isn't listening on the ports being accessed).

One possible solution could be an option to the proxy init container that accepts a subnet, which iptables is then configured to treat as normal traffic rather than redirecting it to the proxy.

**Comment by wminshew** [comment]
Anyway to keep this from turning stale? Or .. do we just let it?

**Comment by grampelberg** [comment]
@wminshew just needs to see activity again, no longer stale!

**Comment by Hertog-PJ** [comment]
We're experiencing a similar issue that when running a docker container(let's call this container A)  within a docker-in-docker image based container (let's call this container B) combined with the linkerd-proxy sidecar prevents any traffic from container A to go outside the cluster. 

When trying to fetch an npm package from container A I've observed the following logs in the linkerd-debug container:
```
 DNS 106 Standard query 0x4cab AAAA registry.npmjs.org.default.svc.cluster.local
 DNS 199 Standard query response 0x4cab No such name AAAA registry.npmjs.org.default.svc.cluster.local SOA ns.dns.cluster.local
DNS 199 Standard query response 0x4cab No such name AAAA registry.npmjs.org.default.svc.cluster.local SOA ns.dns.cluster.local
```

Seems like the external addresses are rewritten/treated as within cluster addresses.

Is there any example of a fix or workaround available?

**Comment by Place1** [comment]
Yep, just hit this as well. I ended up figuring it out by exec'ing into the pod and checking the network, seeing it didn't work, then googling to arrive here.

I'm new to linkerd, is there any way to see this problem via the linkerd dashboard or grafana?
