### ISSUE TITLE
Switch to variable based install configuration flags

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#3109]
## What problem are you trying to solve?

As the install process introduces new configuration, the number of flags for `install` and `upgrade` continue to grow. Some options have been explicitly avoided because it would introduce one more flag and users end up having to use a `kustomize` like approach.

### How should the problem be solved?

Currently, users must do something like:

```bash
linkerd install --omit-webhook-side-effects --proxy-cpu-limit 100
```

Instead, it would be nice to have a configuration system that is a little more generic and allows for file based overrides to solve for the same problems `upgrade --from-manifests` is.

Entirely from the command line, the previous example could be:

```bash
linkerd install --set proxy-injector.side-effects=false --set proxy.cpu.limit 100
```

Alternatively, a file based approach could look like:

```bash
cat <<EOF | linkerd install -f -
proxy-injector:
  side-effects: false
proxy:
  cpu:
    limit: 100
EOF
```

Note: this is basically mirroring the `helm install` UX for `--set` and `--values` on purpose. It means that we can collapse the documentation into a single document and have one way to do configuration.

One of the potential drawbacks is visibility into the potential options. Right now, all the flags show up in `--help`. Unfortunately, there's no differentiation between install configuration flags (`--proxy-cpu-limit`) and CLI options (`--ignore-cluster`). To address this drawback:

- `--help` would need to have the usage updated to show some common options. A pointer to the website could enumerate the verbose list.
- `values.yaml` would need to be updated with verbose explanations of every setting.
- Some kind of automatic process to update the website docs as changes happen.

### Any alternatives you've considered?

Leave things the way they are. We've discussed reducing the number of options in the CLI anyways and making the chart the official method of advanced install. My suspicion is that users getting started will use `linkerd install` and not change any options with users going into production using `helm install` and changing options specific to their install.

Are there any settings a new user would be likely to change?

**Comment by grampelberg** [comment]
Related to: #3099 .

**Comment by grampelberg** [comment]
@Pothulapati isn't this what you're working on right now?

**Comment by Pothulapati** [comment]
Yes @grampelberg but only for add-ons configuration right now.
