### ISSUE TITLE
Include Partial Templates and Defaults In Existing Helm Chart

### ISSUE THREAD

**Issue by ihcsim** [linkerd/linkerd2#3126]
The current control plane's Helm chart is missing the proxy and proxy-init spec, and a default `values.yaml` config values file. The goal of this task is to update the existing chart to include the missing spec from a new `partials` chart. When this task is completed, users will be able to use `helm install` to install the Linkerd control plane, as if they are running `linkerd install`.

If possible, the existing `linkerd install` command should remain untouched. Changes to `linkerd inject` and multi-stage installation will also be deferred to another PR.

All new charts will be added to a new folder named, `charts`. Refer to https://github.com/linkerd/linkerd2/pull/3099 for the targeted folder layout.

Some notes on configuration:

* The proxy and proxy-init YAML spec will be `included` in the control plane chart as [partials](https://github.com/helm/helm/blob/master/docs/chart_template_guide/named_templates.md) (defined in the `partials` chart).
* The data of the `linkerd-config` config map will also be `included` in the control plane chart as [partials](https://github.com/helm/helm/blob/master/docs/chart_template_guide/named_templates.md) (defined in the `partials` chart).
* The identity issuer secret TLS certificate and key must be provided by users. If absent, installation should [`fail`](http://masterminds.github.io/sprig/flow_control.html).
* The CA trust root of the proxy injector and profile validator will be generated using Sprig's [`crypto` package](http://masterminds.github.io/sprig/crypto.html).
* A default `values.yaml` config values file with sane defaults will be provided. (See `cli/cmd/install.go` for some hard coded defaults.)
* For required variables, use the Sprig's `defaults` package to specify defaults. E.g., users won't necessarily know or care about the value of `{{.Values.ControllerComponentLabel}}`.
* Etc.

**Comment by alpeb** [comment]
> The CA trust root of the proxy injector and profile validator will be generated using Sprig's crypto package.

This requires some minor refactoring of the TLS libs, so I created #3131 to track that effort.
