### ISSUE TITLE
Test Helm Upgrade, Delete And Rollback

### ISSUE THREAD

**Issue by ihcsim** [linkerd/linkerd2#3129]
The main goal of this test is to ensure that `helm upgrade`, `helm delete` and `helm rollback` behave as expected. `helm delete` and `helm rollback` should be straightforward. There might be some unknowns with `helm upgrade`; so the sooner we can get to testing it, the better we can mitigate the risks.

Depends on https://github.com/linkerd/linkerd2/issues/3127.

**Comment by alpeb** [comment]
So far testing is going fine for me.

As expected, `helm delete` and `helm rollback` work as intended.

I realized `helm upgrade` requires passing the override values that were passed during install or else they'll get set back to their defaults; in particular if you don't pass again your certs/keys `helm upgrade` will fail. It appears that's business-as-usual for Helm users.
