### ISSUE TITLE
Introduce New Command To Check Helm Chart Config Values File

### ISSUE THREAD

**Issue by ihcsim** [linkerd/linkerd2#3130]
Create a new `linkerd check --chart values.yaml` command to fully validate the options in values.yaml. This includes ensuring the trust root for identity has been provided.

Depends on #3127.

**Comment by grampelberg** [comment]
Should this be a subcommand instead? We've not been great about considering whether things should be flags or subcommands, and I'm not sure I have a strong opinion either way.

**Comment by ihcsim** [comment]
Before starting this task, we should figure out what we want to validate. Helm provides a number of validation tools such as pre-install hooks, `helm inspect values`, `helm lint`, the [`required`](https://github.com/helm/helm/blob/master/docs/charts_tips_and_tricks.md#using-the-required-function) function, [helm test](https://github.com/helm/helm/blob/master/docs/chart_tests.md) etc., so there may be some overlap.
