### ISSUE TITLE
Incorporate Helm Charts Validation Into Dev Workflow

### ISSUE THREAD

**Issue by ihcsim** [linkerd/linkerd2#3143]
08/07: To ensure build consistency and continuous charts validation, we propose the following additions to our existing dev workflow:

* Download and pin the Helm CLI with the `bin/helm.sh` script
* Ensure the `bin/helm.sh` script is invoked during the local and CI build
* Add unit test to diff the output of `helm template` with a set of golden files
* Introduce integration test to test the `helm install` command

----
07/24: Add a shell script to perform the following steps:

* install, check Helm client version
* `helm dependency up`
* `helm lint`
* `helm test # to be evaluated`
* `helm install [--dep-up] [--verify] --dry-run # maybe not necessary? It requires `tiller` to be installed`
* Inject the build version into the `appVersion` property of `Chart.yaml`
* `helm package # maybe not necessary`

**Comment by grampelberg** [comment]
@ihcsim is this just for testing or release as well?

**Comment by ihcsim** [comment]
Definitely the testing phase as a start. Haven't thought too much about the releasing and publishing process yet.

**Comment by ihcsim** [comment]
See #3218 and #3223.

**Comment by ihcsim** [comment]
Fixed by #3218, #3223 and #3248.

**Comment by ihcsim** [comment]
Chart release and publication work is tracked under #3256.
