### ISSUE TITLE
iptables fails to update rules "no chain/target/match by that name"

### ISSUE THREAD

**Issue by tsjnsn** [linkerd/linkerd2#3160]
### What is the issue?
I'm seeing failure to modify iptables rules in the logs of injected init containers.

### How can it be reproduced?
default install of linkerd2, add auto-inject to a namespace, recreate the pods

### Logs, error output, etc
```text
2019/07/29 19:00:59 <
2019/07/29 19:00:59 > iptables -t nat -A PROXY_INIT_REDIRECT -p tcp --destination-port 4191 -j RETURN -m comment --comment proxy-init/ignore-port-4191/1564426859
2019/07/29 19:00:59 <
2019/07/29 19:00:59 > iptables -t nat -A PROXY_INIT_REDIRECT -p tcp -j REDIRECT --to-port 4143 -m comment --comment proxy-init/redirect-all-incoming-to-proxy-port/1564426859
2019/07/29 19:00:59 < iptables: No chain/target/match by that name.

2019/07/29 19:00:59 Aborting firewall configuration
Error: exit status 1
Usage:
  proxy-init [flags]
```

(If the output is long, please create a [gist](https://gist.github.com/) and
paste the link here.)

#### `linkerd check` output

```text
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-api
-----------
√ control plane pods are ready
√ control plane self-check
√ [kubernetes] control plane can talk to Kubernetes
√ [prometheus] control plane can talk to Prometheus
√ no invalid service profiles

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ control plane is up-to-date
√ control plane and cli versions match

Status check results are √
```

### Environment

- Kubernetes Version: 1.11
- Cluster Environment: EKS
- Host OS: Centos 7.5
- Linkerd version: 2.4.0-stable

### Additional context
I had to label the containers as `type: spc_t` to get them to run under selinux.
Im also wondering if there is maybe some incompatibility with AWS's cni plugin which also modifies iptables rules.

**Comment by grampelberg** [comment]
It sounds like you're running with selinux enabled on your nodes? Apparently we need more than NET_ADMIN. Where are you putting `type: spc_t`?

**Comment by tsjnsn** [comment]
i added it to all the containers which use NET_ADMIN

**Comment by tsjnsn** [comment]
Looks like the injected init containers do not have the `spc_t` type. Is there a way to configure that for auto-injected containers?

**Comment by tsjnsn** [comment]
https://linkerd.io/2/reference/proxy-configuration/

may be good to have a config here for adding arbitrary proxy spec, a la `config.linkerd.io/extra-spec`

**Comment by grampelberg** [comment]
The PSP controller will add defaults if they're not on the pod spec. Does adding this to your default PSP work?

```yaml
  seLinux:
    rule: 'MustRunAs'
    seLinuxOptions:
      type: spc_t
```

**Comment by clemenko** [comment]
Looking for a little help here. I updated the PSP with 
```
  seLinux:
    rule: 'MustRunAs'
    seLinuxOptions:
      type: spc_t
```
And deployed and it is still failing. I even tried updating the Deployment for `linkerd-controller` and it also is crashing. 

How have people solved this?

**Comment by tsjnsn** [comment]
I'm also seeing it does not make it into the init container pods. After adding to `linkerd-linkerd-control-plane`, I see this in the init containers (for other services/namespaces)

```
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        add:
        - NET_ADMIN
        - NET_RAW
      privileged: false
      procMount: Default
      readOnlyRootFilesystem: true
      runAsNonRoot: false
      runAsUser: 0

**Comment by tsjnsn** [comment]
I'm thinking PSP won't be a good solution for this, since it operates at the pod level, and only the linkerd sidecar container should have the `spc_t` selinux label

**Comment by tsjnsn** [comment]
Solution for now is to manually inject linkerd-init and add the `spc_t` selinux label to the container. Better solution would be to have configurable parts of the spec for autoinjected sidecars, possibly related to https://github.com/linkerd/linkerd2/issues/2129
