### ISSUE TITLE
Handle automountServiceAccountToken

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#3183]
### What problem are you trying to solve?

mTLS is on by default now and requires the service account token to create an identity. Some pods start with `automountServiceAccountToken: false`. This causes the pods to go into a crash loop as they're unable to fetch an identity.

### How should the problem be solved?

- If `automountServiceAccountToken: false` is set on a pod spec, inject should return an error. This should happen for any injection issue (host networking, known incompatible sidecar).
- An annotation should be added `config.linkerd.io/forceServiceAccountToken` that adds `automountServiceAccountToken: true` to the patch. This is to make it work with controllers that create pods outside of a normal user's control.

**Comment by grampelberg** [comment]
I'm not sure this is the right idea. The best solution would be to use projected volumes, that is gated on figuring out whether it is generally available or not.

**Comment by ihcsim** [comment]
@grampelberg Given https://github.com/linkerd/linkerd2/issues/3260, is this still relevant?

**Comment by grampelberg** [comment]
@ihcsim we'll need to decide once there's some data around how many folks can use the token volumes. Definitely going to end up guiding how we fit this together.

**Comment by mayankshah1607** [comment]
@ihcsim @grampelberg I'd love to take up this one if it is still relevant. :)
Seems like https://github.com/linkerd/linkerd2/issues/2843 could be related.

**Comment by ihcsim** [comment]
@mayankshah1607 The only part that we can do here is to return an error and emit an event when `automountServiceAccountToken: false`, which implies that mTLS won't work. If you want to tackle this, feel free! 

The [service account token volume projection](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#service-account-token-volume-projection) is still in beta. And I don't think introducing a new annotation to modify this field behind the user's back is the right approach.
