### ISSUE TITLE
Emit Proxy Spans

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#3188]
## What problem are you trying to solve?

When viewing distributed traces, it is beneficial to see the spans associated with proxies alongside those emitted by applications. This allows users to understand what overhead proxies are adding to their applications.

As this feature has serious performance implications and requires application changes to be useful, it must be configurable and disabled by default.

### How should the problem be solved?

- Implement the [Trace-Context](https://w3c.github.io/trace-context/) propagation format.
- Follow the [OpenTelemetry](https://github.com/open-telemetry/opentelemetry-specification) specification for clients.
- Integrate with [OpenTelemetry Service](https://github.com/open-telemetry/opentelemetry-service/).
- Implement the [OpenCensus Agent Protocol](https://github.com/census-instrumentation/opencensus-proto/tree/master/src/opencensus/proto/agent) for exporting spans to the local agent.
- Receive sampling configuration from the agent via [TraceConfig](https://github.com/census-instrumentation/opencensus-proto/blob/master/src/opencensus/proto/trace/v1/trace_config.proto)
- Configure emitting spans via `inject`.

### Out of scope

- Installing and configuring the OpenTelemetry service.
- Exporting any metadata outside of timing.

**Comment by grampelberg** [comment]
Related to #1436.

**Comment by adleong** [comment]
It's worth noting that OpenCensus does not use the Trace-Context propagation format for gRPC requests.  Instead, it uses a header called `grpc-trace-bin`: https://github.com/census-instrumentation/opencensus-specs/blob/master/trace/gRPC.md

This means that Linkerd must also read this header if it wishes to participate in gRPC traces.

**Comment by adleong** [comment]
If installing and configuring the OpenTelemetry service is out of scope, it becomes more difficult to send traces to the agent over TLS.  The agent's trust root would need to be mounted into the proxy's container and thus the configuration gets a bit more complex.

**Comment by olix0r** [comment]
> If installing and configuring the OpenTelemetry service is out of scope, it becomes more difficult to send traces to the agent over TLS. The agent's trust root would need to be mounted into the proxy's container and thus the configuration gets a bit more complex.

it probably means we aught to have the proxy support the environment variables needed to read a trust root from disk; and leave it as an exercise to the user to get that mounted in the proxy's container...

**Comment by olix0r** [comment]
![image](https://user-images.githubusercontent.com/240738/63186354-11601f80-c011-11e9-8adc-d6fa1603be33.png)

Given a trace like the above, how should this change when the proxy is participating in tracing? @grampelberg

**Comment by grampelberg** [comment]
Implemented.
