### ISSUE TITLE
Consider setting "successfulJobsHistoryLimit: 0" on linkerd-heartbeat cronjob

### ISSUE THREAD

**Issue by klingerf** [linkerd/linkerd2#3189]
When I list the pods in my linkerd control plane, I see three completed pods, corresponding to the `linkerd-heartbeat` CronJob:

```
linkerd       linkerd-controller-5bfc4cf68c-qm2px      3/3     Running     0          9m52s
linkerd       linkerd-grafana-64d477c9df-zbpd2         2/2     Running     0          9m50s
linkerd       linkerd-heartbeat-1564613820-74q8w       0/1     Completed   0          42h
linkerd       linkerd-heartbeat-1564700220-mghtj       0/1     Completed   0          18h
linkerd       linkerd-heartbeat-1564767180-9l7bj       0/1     Completed   0          5m40s
linkerd       linkerd-identity-66db45984b-vx7vh        2/2     Running     0          9m53s
linkerd       linkerd-prometheus-c58cf9c9b-5hgn8       2/2     Running     0          9m50s
linkerd       linkerd-proxy-injector-f4d669bb9-dcprj   2/2     Running     0          9m49s
linkerd       linkerd-sp-validator-585b864c78-hsr75    2/2     Running     0          9m48s
linkerd       linkerd-tap-89885f984-2rhbv              2/2     Running     0          9m47s
linkerd       linkerd-web-7d5b486476-mpppr             2/2     Running     0          9m51s
````

It looks like CronJobs, by default, will keep the 3 most recent Jobs around after they've completed. Per the [documentation](https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/#jobs-history-limits), we could clean those up automatically by setting `successfulJobsHistoryLimit: 0` on the CronJob spec:

> By default, they are set to 3 and 1 respectively. Setting a limit to 0 corresponds to keeping none of the corresponding kind of jobs after they finish.

Am not sure if that has any other implications, though.

**Comment by grampelberg** [comment]
I'm +1 for this.
