### ISSUE TITLE
web UI: Handle Unauthenticated errors when initiating a tap

### ISSUE THREAD

**Issue by kleimkuhler** [linkerd/linkerd2#3198]
Now that a Pod's tap server can return an `Unauthenticated` error, the web UI should be capable of gracefully handling this error.

**Comment by grampelberg** [comment]
@kleimkuhler where'd we get to with this?

**Comment by kleimkuhler** [comment]
@grampelberg This could be probably be closed. It's currently handled in the UI as shown [here](https://github.com/linkerd/linkerd2/pull/3208#issuecomment-519570458).
