### ISSUE TITLE
proxy: tune latency histogram buckets

### ISSUE THREAD

**Issue by hawkw** [linkerd/linkerd2#3202]
The proxy currently uses [these bounds](https://github.com/linkerd/linkerd2-proxy/blob/d315b9f6afb23eb3d0cf58577710989d1bd69944/lib/metrics/src/latency.rs#L7-L35) for latency histogram buckets. These buckets could probably be revised to offer more resolutionin the range that a majority of latencies fall into.

See also https://github.com/linkerd/linkerd2-proxy/pull/294#discussion_r311212343

**Comment by hawkw** [comment]
I think this is still valid.

**Comment by hawkw** [comment]
probably still worth looking into

**Comment by wmorgan** [comment]
See discussion in https://github.com/envoyproxy/envoy/issues/7599, especially around limitations in Prometheus which may restrict the set of options available to us in the proxy itself.

**Comment by wmorgan** [comment]
As a point of comparison, Envoy's buckets are 0.5, 1, 5, 10, 25, 50, 100, 250, 500, 1000, 2500, 5000, 10000, 30000, 60000, 300000, 600000, 1800000, and 3600000ms.

(Source: https://github.com/envoyproxy/envoy/blob/master/source/common/stats/histogram_impl.cc#L34 )

**Comment by adleong** [comment]
Closed as a duplicate of https://github.com/linkerd/linkerd2/issues/9588
