### ISSUE TITLE
Update New Helm Chart To Support Multi-Stage Installation

### ISSUE THREAD

**Issue by ihcsim** [linkerd/linkerd2#3206]
For the first pass, we can introduce a new Helm variable to define the different installation stages.
```
# same as `linkerd install config`
helm install --name linkerd --set Stage=config charts/linkerd2

# same as `linkerd install control-plane`
helm install --name linkerd --set Stage=control-plane charts/linkerd2
```
In future iterations, we can consider exploring using [tags and conditions](https://helm.sh/docs/developing_charts/#tags-and-condition-fields-in-requirements-yaml) to include different subcharts based on the installation stage.

The behaviour of the existing `linkerd install config` and `linkerd install control-plane`  should remain unaltered.

cc @grampelberg

**Comment by grampelberg** [comment]
@ihcsim just to throw alternatives out there, does this make more sense with something like `helm install -f config-stage.yaml` and `helm install -f control-plane-stage.yaml`?

**Comment by alpeb** [comment]
@grampelberg's suggestion sounds more "Helmy" to me :-)

One side note: the second command (whether using Stage=control-plane or -f control-plane-stage.yaml) needs to be a `helm upgrade`, and it needs to get passed the same set of overrides the first one got, or else they'll get reset to their defaults.

**Comment by grampelberg** [comment]
I'll reiterate that I'm not sure I like my suggestion. The piece missing in my mind is the implementation. With `--ha`, it was a bundle of settings and made a ton of sense. With the stages, is it a big if statement that chooses whether to render whole templates?
