### ISSUE TITLE
Increase the comprehensiveness of check --pre

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#3224]
## What problem are you trying to solve?

`check` is awesome and provides a way for users to reason about whether linkerd can run effectively on their clusters. Unfortunately, it doesn't test for somethings. For example, while users can create `ClusterRoles`, it is possible that they don't have the broad permissions required to actually create these with the correct permissions required. 

### How should the problem be solved?

For `--pre`, it would provide better results to do something similar to what `kubectl apply --server-dry-run` does.

**Comment by grampelberg** [comment]
As part of this, it would be nice to add a check to validate that the injector is operating correctly. This could simply try and create a pod, and see if it was correctly injected. The `--server-dry-run` *should* go through the injector and give some information back for that. See #3290 and #2973 for two examples of this failure.

**Comment by Pac23** [comment]
can i take this as per slack discussion ?

**Comment by grampelberg** [comment]
Go for it!

**Comment by Pac23** [comment]
> Hi @Pac23
> 
> I was about to start working on this issue and I was wondering if you were still interested in it.
> 
> Thanks!

i found some of the bits of the solution to this issue slightly difficult as a i learned go only couple of weeks back,please take this.

**Comment by tegioz** [comment]
Thanks @Pac23!
