### ISSUE TITLE
Ingress Controller with TLS for booksapp - Internal Server Error

### ISSUE THREAD

**Issue by vikramkhatri** [linkerd/linkerd2#3233]
Linkerd 2.4.0

Issue: When I enabled booksapp ingress with a TLS certificate, the app works sometime and I can see the page but at times, it throws Internal Server Error with 3 replicas of `webapp`.

Steps to reproduce:

## Load balancer

If you do not have an external load balancer, follow steps here to create one in your VM or laptop or MacBook.

Assume that you are using CentOS 7.6

```
$ sudo lsmod | grep ^ip_vs
$ yum -y install ipvsadm
$ sudo ipvsadm -ln
$ echo "ip_vs" | sudo tee /etc/modules-load.d/ipvs.conf
$ helm repo add kaal https://vikramkhatri.github.io/helm-chart/
$ helm repo update

$ kubectl create clusterrolebinding keepalived-cluster-role-binding --clusterrole=cluster-admin --serviceaccount=keepalived:default

$ helm install kaal/keepalived --name keepalived --namespace keepalived \
--set keepalivedCloudProvider.serviceIPRange="192.168.142.248/29"
```

If your network is say eth0 as `192.168.10.1` then change `keepalivedCloudProvider.serviceIPRange="192.168.10.248/29"` to reserve 6 IPs from the subnet to the load balancer. This is just poor man's LB for testing.

## Install nginx controller

```
$ helm repo add nginx-stable https://helm.nginx.com/stable

$ helm repo update

$ helm install nginx-stable/nginx-ingress --name nginx --namespace kube-system \
--set fullnameOverride=nginx \
--set controller.name=nginx-controller \
--set controller.config.name=nginx-config \
--set controller.service.name=nginx-controller \
--set controller.serviceAccount.name=nginx
```

## Create an entry for `booksapp.linkerd.io` in `/etc/hosts`

```
$ export INGRESS_HOST=$(kubectl -n kube-system get service nginx-controller -o jsonpath='{.status.loadBalancer.ingress..ip}') ; echo $INGRESS_HOST

$ sudo sed -i '/dashboard.linkerd.io/d' /etc/hosts

$ echo "$INGRESS_HOST dashboard.linkerd.io" | sudo tee -a /etc/hosts
```

## Create a X.509 certificate for `booksapp.linkerd.io`

```
$ openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /tmp/tls.key -out /tmp/tls.crt -subj "/CN=booksapp.linkerd.io"
```

## Create a TLS secret for Nginx Controller

```
$ kubectl -n linkerd-lab create secret tls booksapp-keys --key /tmp/tls.key --cert /tmp/tls.crt
```

## Create an ingress definition for `booksapp.linker.io`

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: booksapp
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:80;
      proxy_hide_header l5d-remote-ip;
      proxy_hide_header l5d-server-id;
spec:
  rules:
  - host: booksapp.linkerd.io
    http:
      paths:
      - backend:
          serviceName: webapp
          servicePort: 7000
        path: /
  tls:
  - hosts:
    - booksapp.linkerd.io
    secretName: booksapp-keys
```

## Test through `curl`

```
$ export INGRESS_PORT=$(kubectl -n kube-system get service nginx-controller -o jsonpath='{.spec.ports[?(@.name=="https")].port}') ; echo $INGRESS_PORT

$ export INGRESS_HOST=$(kubectl -n kube-system get service nginx-controller -o jsonpath='{.status.loadBalancer.ingress..ip}') ; echo $INGRESS_HOST

$ curl -Ls -HHost:booksapp.linkerd.io \
--resolve booksapp.linkerd.io:$INGRESS_HOST:$INGRESS_PORT \
--cacert /tmp/tls.crt https://booksapp.linkerd.io
```

The above should work without using `--insecure` or `-k`

Go back to your browser in VM and run https://booksapp.linker.io and keep on refreshing, you will see that sometime it works - sometime it throws "Internal Server Error". Make sure that you do not reduce the webapp replica to 1 as it works fine with one replica.

## 2nd Problem:

After above works, if I enable linkred proxy on Ingress Controller, the booksapp appear to work but there is no TLS between Ingress and the webapp service.

The steps are:

```
kubectl -n kube-system get deploy nginx-controller -o yaml | linkerd inject - | kubectl apply -f -
```

Check curl as well as browser and you will see the problem.

## Expectation.

1. Document step-by-step to enable mTLS between Ingress Controller to edge service
2. Document step-by-step to rotate Linkerd certificates

## Nice to be
1. An automatic procedure to rotate linkerd control plane certificates

**Comment by cpretzer** [comment]
@vikramkhatri I'm closing this, per our conversation on Slack. Please reopen the ticket if you are still seeing errors related to this ticket.

**Comment by sillva** [comment]
> @vikramkhatri I'm closing this, per our conversation on Slack. Please reopen the ticket if you are still seeing errors related to this ticket.

Any chance you guys can share the outcome of your slack chat? Thanks !
