### ISSUE TITLE
Expand automatic mTLS to all meshed traffic

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#3242]
# moreTLS

## Problem

Linkerd automatically establishes mutual TLS between Kubernetes services that communicate via HTTP. However, this only applies when clients send traffic to a Kubernetes `Service`. When traffic is sent directly between pods, for instance as Prometheus does to scrape metrics, or when non-HTTP protocols are used, Linkerd cannot currently establish trusted, private communication between the pods. This needs to change.

## Goals

1. Automatically make **all** communication private between pods participating in a Linkerd mesh.
2. Provide an audit trail of the TLS status of all connections into or out of the mesh.

### Non-goals

* Implement authorization policies.
* Fail-closed.

## Proposal

* Extend the destination service to support endpoint resolution by IP address;
* Modify the proxy to perform endpoint resolution on IP addresses;
* Introduce TCP resolution into the proxy's outbound TCP forwarding, bypassing kube-proxy.
* Enhance TCP metrics with endpoint metadata, including the SNI name of opaque TLS connections, to support auditability.

#### Destination Service

The `Destination.Get` API is extended to resolve names in the form `IP:PORT`:

1. When the given IP refers to a `Service` IP, its constituent endpoints are returned as they would be if the service's name were used instead of its IP.
2. When the given IP refers to a Pod IP, its metadata is returned.
3. Otherwise, an endpoint is resolved with no additional metadata.

##### Start resolving IP address destinations via the destination service

When the proxy attempts to send an HTTP request without a `Host` header or with such a header referring to an authority containing an IP address instead of a hostname, the proxy will attempt to resolve the IP address through the control plane as it would resolve any Kubernetes service name.

##### Introduce a TCP balancer into outbound TCP forwarding

When the proxy attempt to forward a outbound TCP connection, it will first resolve the original dst address through the `Destination.Get` API and balance connections over the returned set of pods.

##### Expose per-dst TCP stats

The proxy's TCP metrics should be extended to include per-destination metadata so that the TLS status of each outbound TCP connection includes the controller-provided metadata, including TLS status.

**Comment by grampelberg** [comment]
This sounds like a good incremental step to me. I like tackling policy later.
