### ISSUE TITLE
Helm chart publishing and release

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#3256]
### What problem are you trying to solve?

Now that there is an official helm chart, it would be nice to make this installable without cloning the repo.

### How should the problem be solved?

- Publish the chart tarball as an artifact attached to the github release.
- Add to the [stable repo](https://github.com/helm/charts).
- Document release process for updating external repo.

### Any alternatives you've considered?

- Host a chart repo just for Linkerd. This seems like an okay solution, not quite as great but probably worth it if there's a lot of work required to get a PR accepted to the helm stable repo.

**Comment by ihcsim** [comment]
Given that Helm repo is going away and there hasn't been much progress in the submitted PR, to unblock 2.6, we should:

1. Host our own repo. Consider using a GCS bucket for simplicity and HA. See docs [here](https://helm.sh/docs/chart_repository/#google-cloud-storage).
1. Work towards publishing the Helm chart on Helm Hub, per docs [here](https://github.com/helm/hub/blob/master/Repositories.md).
 
I will create separate issues for these items.

**Comment by alpeb** [comment]
Our own repo publishing has been addressed in #3415 and the Helm hub publishing is being tracked in #3367
