### ISSUE TITLE
Prometheus Sizing and Tuning

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#3258]
### What problem are you trying to solve?

There have been reports of Prometheus behaving poorly in clusters, such as #2980 and #3158. Some discussion has happened on whether everything being imported is required, such as #3227. The theme has been excessive memory usage and in some cases it becomes unresponsive.

### How should the problem be solved?

At the moment, there is not a lot of data around where in the life cycle these problems occur. The Prometheus instance should be able to manage the load of:

- 5000 pods
- 1000 services
- 500 nodes
- 5 simultaneous dashboard users
- 5 simultaneous grafana dashboards
- 1 simultaneous federation

#### Requirements

- It should be possible to schedule this on an instance with at most 4 CPUs and 16GB of memory.
- The retention period should be no less than one hour.

**Comment by ihcsim** [comment]
Following yesterday's meeting, I ran some more tests using the `emojivoto` application in order to obtain some baseline resource utilization data.

On this AKS cluster, the Linkerd Prometheus:

* is deployed to a dedicated node with 4 CPU cores and 14 GB RAM
* has no pod resource limits, to allow the pod to hit the resource limit imposed by the node

Observations:

When scalling just the "backend" `emoji` and `voting` services, Prometheus was able to support around 1000 pods, where the memory utilization is bumped to around 10GB RAM, before encountering the `OOMKilled` event:
```
✗ k -n emojivoto get deploy                                                                                                                 
NAME       READY     UP-TO-DATE   AVAILABLE   AGE
emoji      400/400   400          400         135m
vote-bot   100/100   100          100         135m
voting     400/400   400          400         135m
web        100/100   100          100         135m

✗  k -n linkerd top po                                                                                                                 
NAME                                     CPU(cores)   MEMORY(bytes)
linkerd-controller-7fc7595c5-6859w       44m          172Mi
linkerd-grafana-6f8575c8ff-j9qgw         3m           37Mi
linkerd-identity-5dc479f6d6-9ngw7        6m           81Mi
linkerd-prometheus-58d4c4b7b4-dfqgr      2186m        10164Mi
linkerd-proxy-injector-d99b76949-b46n4   25m          19Mi
linkerd-sp-validator-7449c6d7fb-hf2lw    0m           15Mi
linkerd-tap-86dc649c94-g2pwm             14m          97Mi
linkerd-web-7d94d85466-c2hm4             2m           16Mi
```

The total pod counts was a lower (700) when scaling only the `vote-bot` traffic generator, with the memory utilization nearing 10GB:
```
✗ k -n emojivoto get deploy                                                                                                                 
NAME       READY     UP-TO-DATE   AVAILABLE   AGE
emoji      100/100   100          100         9m32s
vote-bot   400/400   400          400         9m32s
voting     100/100   100          100         9m31s
web        100/100   100          100         9m31s

✗ k -n linkerd top po                                                                                                                     
NAME                                     CPU(cores)   MEMORY(bytes)
linkerd-controller-7fc7595c5-4cbq8       0m           165Mi
linkerd-grafana-6f8575c8ff-g5x84         4m           31Mi
linkerd-identity-5dc479f6d6-45ns8        0m           63Mi
linkerd-prometheus-58d4c4b7b4-c2r95      1665m        9831Mi
linkerd-proxy-injector-d99b76949-bfd68   0m           30Mi
linkerd-sp-validator-7449c6d7fb-wx62q    0m           16Mi
linkerd-tap-86dc649c94-4xmdg             0m           45Mi
linkerd-web-7d94d85466-5jsjt             0m           17Mi
```
It looks like there is a correlation between the Prometheus memory footprint and the amount of traffic flowing through the data plane.

Reducing the data retention to 1hr as suggested reduces the memory footprint by 3GB for 1000 pods:
```
✗  k -n emojivoto get deploy                                                                                                                (isim-dev-prom/default)
NAME       READY     UP-TO-DATE   AVAILABLE   AGE
emoji      400/400   400          400         17m
vote-bot   100/100   100          100         17m
voting     400/400   400          400         17m
web        100/100   100          100         17m

✗  k -n linkerd top po                                                                                                                      
NAME                                     CPU(cores)   MEMORY(bytes)
linkerd-controller-7fc7595c5-vbtwd       0m           138Mi
linkerd-grafana-6f8575c8ff-zdkv9         4m           33Mi
linkerd-identity-5dc479f6d6-lwvn4        0m           57Mi
linkerd-prometheus-66685b847f-gj55x      1513m        7414Mi
linkerd-proxy-injector-d99b76949-lx7l7   0m           24Mi
linkerd-sp-validator-7449c6d7fb-5d7g6    0m           18Mi
linkerd-tap-86dc649c94-c68b9             0m           44Mi
linkerd-web-7d94d85466-jbsrw             0m           17Mi
```

Other observations:

* The Prometheus memory consumption doesn't decrease right away (10 - 15 mins) after the emojivoto application is removed, unless the pod crashed.
* Scaling the replicas gradually (from 100 to 250 to 400) yields no difference in memory consumption, when compared to creating the workloads with large number of replicas (400 from the start).
* Although launching the Linkerd dashboards and Grafana introduced CPU and memory spikes, they aren't enough to trigger a `OOMKilled` event on Prometheus.

Next steps:

* Investigate into baseline resource utilization of Prometheus when multiple namespaces appear on the Linkerd dashboard.

**Comment by grampelberg** [comment]
@ihcsim was this all while running a single instance of the dashboard?

**Comment by ihcsim** [comment]
Yeah, just one dashboard and one grafana. I'm testing with 5 dashboards next.

**Comment by grampelberg** [comment]
Why'd you get OOM killed at 10gb if your node had more? Sounds like it might be time for a bigger instance =) I'm interested in whether this scales linearly or not.

**Comment by ihcsim** [comment]
That's a good question. From what I can tell there are only `kube-proxy` and `omsagent` on the same node, both of which don't take up a lot afaict. But it's definitely the node being upset with my pod:

(happens again as I type)

```
Events:
  Type     Reason                     Age                   From                               Message
  ----     ------                     ----                  ----                               -------
  Normal   NodeHasSufficientMemory    6m19s (x40 over 18h)  kubelet, aks-agentpool-21262120-0  Node aks-agentpool-21262120-0 status is now: NodeHasSufficientMemory
  Warning  EvictionThresholdMet       67s (x39 over 18h)    kubelet, aks-agentpool-21262120-0  Attempting to reclaim memory
  Normal   NodeHasInsufficientMemory  67s (x39 over 18h)    kubelet, aks-agentpool-21262120-0  Node aks-agentpool-21262120-0 status is now: NodeHasInsufficientMemory
```

**Comment by ihcsim** [comment]
And AFAICT, I don't see any memory-related configurations on Prometheus. Settings like `storage.local.target-heap-size` and `storage.local.memory-chunks` have to be deprecated.

**Comment by ihcsim** [comment]
So I ran my tests with bigger VMs of 4 CPU cores and 32 GB RAM. With 200 to 400 emojivoto pods, the 5 Linkerd dashboards and 5 Grafana dashboards (1 minute refresh rate) become unresponsive.

This goes on for a little while: 
![dashboard-02](https://user-images.githubusercontent.com/1330522/64059631-3908c900-cb75-11e9-9b39-612f41645c3f.png)

Same with Grafana. Changing refresh rate to 5 minutes didn't help in this case:
![grafana-00](https://user-images.githubusercontent.com/1330522/64059637-53db3d80-cb75-11e9-8e42-18f136276510.png)

![grafana-02](https://user-images.githubusercontent.com/1330522/64059638-589ff180-cb75-11e9-91da-e878da7d738d.png)

Looks like both the Linkerd and Grafana dashboards impose a lot of CPU stress on Prometheus:
![node-cpu](https://user-images.githubusercontent.com/1330522/64059648-838a4580-cb75-11e9-9f68-9d7b7f7b846d.png)

The next tier of VM are the GPU series with 6 CPUs and 56 GB RAM. I am not sure if it's realistic to expect users to run this type of VMs.

Without the dashboards, doubling the VM memory doubles the pods count:
```
✗ k -n emojivoto get deploy                                                                                                                 (isim-dev-prom/default)
NAME       READY       UP-TO-DATE   AVAILABLE   AGE
emoji      1000/1000   1000         1000        15m
vote-bot   200/200     200          200         15m
voting     800/800     800          800         15m
web        200/200     200          200         15m

✗ kubectl -n linkerd top po
NAME                                     CPU(cores)   MEMORY(bytes)
linkerd-controller-7fc7595c5-5xp57       2m           178Mi
linkerd-grafana-6f8575c8ff-khm76         7m           34Mi
linkerd-identity-5dc479f6d6-xwd4x        0m           94Mi
linkerd-prometheus-58d4c4b7b4-gl9tv      3758m        26975Mi # note that this isn't when the OOMKilled happens
linkerd-proxy-injector-d99b76949-8r6mm   0m           21Mi
linkerd-sp-validator-7449c6d7fb-xkq94    0m           14Mi
linkerd-tap-86dc649c94-fndg8             0m           40Mi
linkerd-web-7d94d85466-4gjpf             0m           14Mi
```

Again, the total pod counts are lower by a few hundred counts if I scaled the `vote-bot` service:
```
✗ k -n emojivoto get deploy                                                                                                                 (isim-dev-prom/default)
NAME       READY     UP-TO-DATE   AVAILABLE   AGE
emoji      400/400   400          400         28m
vote-bot   600/400   400          400         28m
voting     400/400   400          400         28m
web        600/200   200          200         28m

✗ kubectl -n linkerd top po                                                                                                                 (isim-dev-prom/default)
NAME                                     CPU(cores)   MEMORY(bytes)
linkerd-controller-7fc7595c5-fszlq       5m           204Mi
linkerd-grafana-6f8575c8ff-4wgwk         6m           32Mi
linkerd-identity-5dc479f6d6-bpmvq        0m           88Mi
linkerd-prometheus-58d4c4b7b4-bwbb9      3735m        25517Mi
linkerd-proxy-injector-d99b76949-sb9mc   0m           24Mi
linkerd-sp-validator-7449c6d7fb-gzz7c    0m           17Mi
linkerd-tap-86dc649c94-5tlg5             1m           51Mi
linkerd-web-7d94d85466-j5zj4             0m           17Mi
```

Finally, the `Tap` and `Top` pages stop working if I deployed an nginx deployment with 1000 - 1500 replicas. To reproduce,

1. Deploy nginx to the `default` namespace
1. Navigate to the `Tap` page
1. Select the `default` namespace, and set `Resource` to `namespace/default`
1. Click `Start`
1. No `Tap` results show up for a while (if ever)

**Comment by ihcsim** [comment]
The other consistent observation is that the Prometheus memory consumption doesn't go down, even though for a long while (if at all), after my emojivoto applicaiton is deleted. Hence, subsequent test runs trigger the OOMKilled event sooner.

**Comment by ihcsim** [comment]
With a new installation of the 2.5 control plane, here are the top-10 metrics and their time series count, grouped by job and metrics name:

![top10-metrics-jobs](https://user-images.githubusercontent.com/1330522/64142382-8b89f580-cdc0-11e9-917c-25169bbed92b.png)
The `kubernetes-nodes-cadvisor` job has a notable 555936 time series, compared to the `linkerd-proxy` job's 3110.

![top10-metrics-k8s-nodes-cadvisor](https://user-images.githubusercontent.com/1330522/64142471-e6bbe800-cdc0-11e9-86ae-e41b6a2ac500.png)
Within the `kubernetes-nodes-cadvisor` job, the `container_tasks_state` and `container_memory_failures_total` metrics have about 96K and 77K time series, respectively. Looking at the definition of these metrics on the cadvisor [docs](https://github.com/google/cadvisor/blob/master/docs/storage/prometheus.md#prometheus-metrics), it looks like these metrics may be safe to drop?

Metric name | Type | Description
--- | --- | -- 
container_memory_failures_total | Counter | Cumulative count of memory allocation failures
container_tasks_state | Gauge | Number of tasks in given state (sleeping, running, stopped, uninterruptible, or ioawaiting) 

![top10-metrics-linkerd-proxy](https://user-images.githubusercontent.com/1330522/64142693-e8d27680-cdc1-11e9-97a4-d0bd846e49b8.png)
In the `linkerd-proxy` job, the `route_response_latency_ms_bucket` has the highest number of time series count.

![top10-metrics-linkerd-controller](https://user-images.githubusercontent.com/1330522/64142721-11f30700-cdc2-11e9-8ba8-36bc665ce838.png)
In the `linkerd-controller` job, the `http_client_request_latency_seconds_bucket` has the highest number of time series count.

Note that these time series count aren't affected by the number of active Linkerd dashboards.

**Comment by ihcsim** [comment]
For posterity, we submitted a PR to change the Prometheus config to only keep cadvisor metrics that are relevant to container resources. See https://github.com/linkerd/linkerd2/pull/3401.

**Comment by ihcsim** [comment]
After running 500 to 600 emojivoto apps for 3 days, I can see that the `linkerd-proxy` job has way more data than the cadvisor job, with the `response_latency_ms_bucket` metrics many times higher than the next top-4.

Total metrics size grouped by jobs:
![count-by-jobs](https://user-images.githubusercontent.com/1330522/64552818-e81f7000-d2ec-11e9-9f2f-a7a2873fcffb.png)

Top-5 metrics in the `linkerd-proxy` job:
![linkerd-proxy-top5](https://user-images.githubusercontent.com/1330522/64552830-f5d4f580-d2ec-11e9-9c98-e26c287d17c2.png)

**Comment by olix0r** [comment]
My guess is that the the `response_latency_ms_bucket` (and `response_total`, etc) are especially high because you're running an exceptionally large load balancer... A `vote-bot` that balances over 100s of pods `webs` will have a very high-cardinality of client metrics, which is what you're seeing here.

I might suggest changing the configuration to be more representative of real workloads... Rather than scale out a single emojivoto cluster to be exceptionally large, perhaps run multiple smaller emovjivoto deployments in separate namespaces?

Or is the intent to specifically test very large services?

**Comment by ihcsim** [comment]
> are especially high because you're running an exceptionally large load balancer

@olix0r That seems to be accurate. I re-ran my tests with edge-19.10.1, with Prometheus deployed to a 6 CPU and 56 RAM VM. A single namespace with high number of client-side load balancing got me to about 1400 pods. If I separate them into multiple namespaces, I was able to get it up to about 2000 pods. This is a cluster with 100 nodes, though that seems mostly irrelevant, since we are bounded by the resources of the node where Prometheus is running on.

This correlation between clients with high fanout and high Prometheus CPU usage may be something that we can bring up to help users to tune their Prometheus.

**Comment by ihcsim** [comment]
As for the dashboard, a namespace with a large number of pods (in my case, 1400) can still be problematic on the namespace-specific page. It would trigger a high CPU usage on Prometheus, cascading failures to other open dashboards. As long as I don't bring up that particular namespace page, other pages seem to be working fine (although the `Namespaces` page can still be slow).
