### ISSUE TITLE
Use ServiceAccountToken volumes

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#3260]
### What problem are you trying to solve?

Currently, service account tokens are used to validate identity for pods. These are passed as part of the CSR to `identity`. In situations where the token is not mounted automatically, a pod's identity cannot be verified and identity must be disabled. This token also is needlessly over permissive and shouldn't be shipped around.

### How should the problem be solved?

A new type of volume - [ServiceAccountToken](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#service-account-token-volume-projection) reached beta in k8s 1.12. This is mounted on a per-container basis, can have a specific expiration and allows restriction by audience. Instead of relying on the default service account token to be auto-mounted, injection should add the volume to the proxy's pod and restrict to exactly the audience required.

This should *not* be a configuration option and instead be the only way to view service account tokens moving forward.

### Concerns

While this feature reached beta in k8s 1.12, it is unclear that it is available in most cloud providers and local solutions (docker desktop, minikube). Before implementing, support for at least GKE, AKS, EKS, minikube and docker desktop should be validated.

**Comment by grampelberg** [comment]
Related to #2843 and #3183.

**Comment by reegnz** [comment]
Aws ETA is early February, so question is, is support in GKE+EKS+AKS enough to make the switch?

**Comment by grampelberg** [comment]
@reegnz AKS has support now?

Given the lack of support in minikube/microk8s, we'll need to degrade gracefully no matter what. Interested in taking up the contribution?

**Comment by reegnz** [comment]
@grampelberg I'm not that proficient in go yet, so I'll have someone else pick this up. :)
I am very enthusiastic about having this as a feature though!

**Comment by irizzant** [comment]
Minikube won't start with:
`minikube start --extra-config=apiserver.service-account-issuer=api --extra-config=apiserver.service-account-signing-key-file=/var/lib/minikube/certs/apiserver.key --extra-config=apiserver.service-account-api-audiences=api`

at least not version 1.8.2

**Comment by alpeb** [comment]
Thanks @irizzant :+1: 
I've updated the comment above.

**Comment by Olshansk** [comment]
I recently came by the following solution for `minikube`:

```
export GOOGLE_APPLICATION_CREDENTIALS=<creds-path>.json 
minikube addons enable gcp-auth
```

I'm not sure it completely address the problems here but figured it's worth mentioning.

Reference: https://minikube.sigs.k8s.io/docs/handbook/addons/gcp-auth/

**Comment by taman9333** [comment]
Hello @alpeb there's a type in `Docker Desktop` which will make cluster stuck starting...
this

`    - --service-account-signing-key-file=/var/run/config/pki/apiserver.key`

should be

`    - --service-account-signing-key-file=/run/config/pki/apiserver.key`

**Comment by alpeb** [comment]
Thanks @taman9333! I've updated the comment above :+1:

**Comment by Pothulapati** [comment]
Thanks for the patience everyone! 

With this being available by default in all the major cloud providers i.e [GKE](https://cloud.go888ogle.com.fqhub.com/kubernetes-engine/docs/how-to/kubernetes-service-accounts?hl=it#assigning_a_kubernetes_service_account_to_a_pod), [AKS](https://github.com/Azure/AKS/issues/1208), [EKS](https://aws.amazon.com/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/) and also in kind, We can start building this for Linkerd `2.12.0` IMO.

I started reading up more on this, and me or someone else will post up a separate design issue in the very near future!
