### ISSUE TITLE
Expose arbitrary headers through tap

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#3262]
### What problem are you trying to solve?

Currently, when running `tap`, users are able to see a few choice details. The selection is small and has been restricted for security concerns. With tap moving to an RBAC model, these concerns are less of an issue. It is extremely helpful to see arbitrary headers as part of the request/response flow.

Tap should be expanded to show all request, response and trailer headers.

### How should the problem be solved?

There are no user facing changes for this proposal. Instead, headers should be added to the tap protobuf. As #3390 recommends a 1:1 dump of the protobuf for JSON output, the headers will automatically start showing up. This should be an unstructured list of labels similar to `EndpointMeta`.

- Include all headers, for http1 and http2 including the pseudo headers.
- Normalize header names by lowercasing them.

### Out of scope

- Proxy side filtering

**Comment by grampelberg** [comment]
Related #3035.

**Comment by hawkw** [comment]
> 
>   * Include all headers, for http1 and http2 including the pseudo headers.

What's the motivation for including HTTP/2 pseudo-headers in the headers part of the tap event?

The tap events [already include pseudo-header fields](https://github.com/linkerd/linkerd2-proxy-api/blob/ddbc3a4f7f8b0058801f896d27974d19ee98094c/proto/tap.proto#L142-L145) in the structured data. Furthermore, this means that pseudo-headers will show up in the headers part of the tap event for HTTP/2 requests, while the equivalent values for HTTP/1 will show up in the tap event's structured data, but _not_ in the headers, which seems inconsistent?

>   * Normalize header names by lowercasing them.
>  
FWIW, the proxy already does this :)

**Comment by adleong** [comment]
> request, response and trailer headers.

To be clear, this means request headers, request trailers, response headers, and response trailers?

**Comment by adleong** [comment]
> Include all headers, for http1 and http2 including the pseudo headers.

Binary valued headers too?

**Comment by hawkw** [comment]
> > request, response and trailer headers.
> 
> To be clear, this means request headers, request trailers, response headers, and response trailers?

Request stream ends don't currently emit tap events (as I pointed out here https://github.com/linkerd/linkerd2-proxy-api/pull/33#issuecomment-529696679). In order to display request trailers, we would also need to add a new tap event for request body ends.

> > Include all headers, for http1 and http2 including the pseudo headers.
> 
> Binary valued headers too?

Yes, that's correct. In the proposed API change linkerd/linkerd2-proxy-api#33, header values are a protobuf `bytes` field. The CLI is responsible for displaying them as strings if UTF-8 or formatting the binary value otherwise.

**Comment by kleimkuhler** [comment]
> In order to display request trailers, we would also need to add a new tap event for request body ends

Hm yea I'm not sure why that is. Request trailers may make sense to be a separate PR from linkerd/linkerd2-proxy-api#33 as you mentioned @hawkw, but do we know if there is any reason we do not currently have tap events for request body ends?

**Comment by hawkw** [comment]
> but do we know if there is any reason we do not currently have tap events for request body ends?

My guess is just that, without displaying trailers, there wasn't really a whole lot of value to show them in the tap output.
