### ISSUE TITLE
[RFC] Implement distributed tracing on top of tap

### ISSUE THREAD

**Issue by adleong** [linkerd/linkerd2#3270]
This proposal describes how distributed tracing could be implemented using the Linkerd tap feature.

## Life of a trace

When a request arrives at ingress, the ingress controller is responsible for deciding if the request should be sampled and, if so, setting the [traceparent](https://w3c.github.io/trace-context/#traceparent-header-field-values) header on the request with the `sampled` bit set to true.  Any sampling algorithm supported by the ingress controller can be used.  A unique trace id must be used for each request.

When an application instance receives a request, it should forward the `traceparent` header on any requests that it sends.

Meanwhile, the user has deployed a controller in the Linkerd namespace called the Trace-Controller.  The Trace-Controller initiates a tap request to Tap-Controller requesting that it tap requests which have the `sampled` bit set to true in their `traceparent` header from all pods.  The Tap-Controller registers this tap request with all pods.

When the Linkerd proxy receives a request with the `sampled` bit set to true, it will see that the request matches a registered tap request, and send tap events to the Tap-Controller about the request and associated response.  The Tap-Controller will return these events to the Trace-Controller.

The Trace-Controller will use the tap id from the events in combination with the traceid from the request header to generate a Span and send this span to the OpenCensus-Collector.  The OpenCensus-Collector will then forward the span to a tracing backend such as Jaeger or Zipkin.

## User requirements

In order to make use of this feature, a user must do the following:

* Use an ingress controller and configure it to initiate traces
* Application instances must forward the `traceparent` header
* Have a tracing backend that is supported by OpenCensus service
* Deploy the OpenCensus-Collector and configure it to send traces to the backend
* Deploy the Trace-Controller (as a Linkerd addon?) and configure it to send traces to the OpenCensus-Collector
* Grant the Trace-Controller RBAC permissions to tap all pods

## Scope of work to implement in Linkerd

* Expand the tap query API to support selecting requests by a header regex so that we can pick requests with the sampled bit: https://github.com/linkerd/linkerd2-proxy-api/blob/master/proto/tap.proto#L77
* Expand the tap event API to support returning request headers so that we can extract the trace id and other metadata: https://github.com/linkerd/linkerd2-proxy-api/blob/master/proto/tap.proto#L146
* Write a Trace-Controller which initiates a request to the Tap-Controller, constructs spans based on the resulting tap data, and sends those spans to the OC-Collector.
* Write documentation and reference architecture

**Comment by adleong** [comment]
Ok @grampelberg @olix0r how crazy is this?

**Comment by adleong** [comment]
What I like about this is:
* easier and less invasive to implement in the proxy (just requires expanding the existing tap functionality slightly rather than integrating a brand new API
* advances the tap roadmap as a side-effect
* (maybe) advances the Linkerd addon roadmap as a side-effect
* leverages tap security model
* doesn't introduce any new dependencies to Linkerd

**Comment by olix0r** [comment]
@adleong Given that you've implemented opentracing... is this issue still relevant/valuable in your view?

**Comment by adleong** [comment]
I don't think it's relevant or valuable.
