### ISSUE TITLE
proxy: Ensure that h2 stream resets transit proxy

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#3282]
The proxy appears to consume h2 stream resets. Instead, we should be able to proxy the reset (code) through proxy's h2 stream.

Consider the case when a proxy is resolving a name through the destination controller and that route is evicted, so the app proxy cancels the stream. The controller's proxy would ideally pass that reset code through to the destination service. Instead, it appears that the controller proxy's response is simply dropped without our code being able to detect the h2 reason.

**Comment by seanmonstar** [comment]
I think I'm not quite understanding how reset stream codes aren't propagated. There's this [test](https://github.com/linkerd/linkerd2-proxy/blob/108e95be714f903b82cec45ca73141b97ea05d75/tests/transparency.rs#L1252) suggesting it is, but maybe there's a different instance?
