### ISSUE TITLE
linkerd2-cli-edge-19.8.4-windows - values.yaml: file does not exist

### ISSUE THREAD

**Issue by strojwaskrystian** [linkerd/linkerd2#3283]
values.yaml: file does not exist when run command on 19.8.4 vesrion
 
linkerd2-cli-edge-19.8.4-windows.exe
open /linkerd2\values.yaml: file does not exist

but works the last version
linkerd2-cli-edge-19.8.2-windows.exe

**Comment by ihcsim** [comment]
@strojwaskrystian Thanks for reporting this. The `/linkerd2\values.yaml` file path doesn't look like the right mount point in the vfs. We will look into this.
