### ISSUE TITLE
Distributed Tracing Reference Architecture

### ISSUE THREAD

**Issue by adleong** [linkerd/linkerd2#3287]
## Overview

Components:
* OpenCensus client library
  * Application instances must be instrumented with the OpenCensus client library for the appropriate language
  * The OpenCensus client library has 4 main responsibilities:
    * Read trace context from the incoming request
    * Increment the span id
    * Emit the span to the OpenCensus collector (if sampled)
    * Write the trace context to the outgoing request
  * Additionally, the first instance in the call tree (the ingress) is responsible for deciding if the trace will be sampled and should be configured with an appropriate sampling policy
  * The OpenCensus client libraries use the Trace-Context trace header propagation format for HTTP and the grpc-trace-bin binary header propagation format for gRPC
* OpenCensus collector
  * The OpenCensus collector runs as a deployment in Kubernetes
  * The OpenCensus client library is configured to send traces to the OpenCensus collector
  * The OpenCensus collector is configured to send those traces to Jaeger
* Jaeger
  * Jaeger runs as a deployment in Kubernetes
  * Jaeger receives traces from the OpenCensus Collector and stores them
  * Jaeger exposes a UI for visualizing traces

## User Requirements

1. Deploy Jaeger (Injected with Linkerd)
2. Deploy the OpenCensus collector (Injected with Linkerd)
3. Instrument your code with the OpenCensus client library (and deploy, injected with Linkerd)

### OpenCensus client library configuration

```
	oce, err := ocagent.NewExporter(
		// If the application and the OpenCensus collector are injected with Linkerd
		// then communication will automatically be secured with TLS.
		ocagent.WithInsecure(),
		ocagent.WithReconnectionPeriod(5 * time.Second),
		// The service address of the OpenCensus collector
		ocagent.WithAddress("oc-collector.linkerd.svc.cluster.local"),
		// The name of the application.  This should match the Kubernetes
		// resource name (deployment name, job name, etc.)
		ocagent.WithServiceName("web"))
```

If this application is the root of the call tree (the ingress) then it must configure a sampling policy.  

```
	trace.ApplyConfig(trace.Config{
		// Sample 5% of traces.
		DefaultSampler: trace.ProbabilitySampler(0.05),
	})
```

See https://github.com/BuoyantIO/emojivoto/pull/69 for a full example.

## Linkerd Proxy Participation

When the Linkerd proxy receives a request with either a Trace-Context header or a `grpc-trace-bin` header it does the following:
* Increment the span id
* If the sampled bit is set, emits the span to the OpenCensus collector
* Writes the incremented span id to the request

The proxy will never initiate a trace on a request without tracing headers.  The proxy will never mutate the sampled bit.  The proxy will never emit spans when the sampled bit is set to false.

The following data is emitted as metadata on the span:
* Node metadata:
  * Service name: "Linkerd-proxy"
  * hostname: the pod name that the proxy is injected into
  * potentially other proxy metadata such as  Linkerd version, proxy starttime, etc.
* Span metadata:
  * Span name: the :path pseudoheader of the request
  * Span.kind: CLIENT for outbound proxies, SERVER for inbound proxies
  * Span id
  * Span start time
  * Span end time

Configuration:
The proxy must be configured with this environment variables to enable participation.  If this variable is absent, none of the above behaviors will be executed.
* LINKERD2_PROXY_OC_COLLECTOR_SVC_ADDR: the addresss of the oc-collector service

<img width="1188" alt="Screen Shot 2019-08-19 at 10 30 39 AM" src="https://user-images.githubusercontent.com/3979810/63296051-0c0a0b80-c283-11e9-971c-c7b5403d7411.png">

![Screen Shot 2019-08-19 at 10 51 33 AM](https://user-images.githubusercontent.com/3979810/63296080-13c9b000-c283-11e9-847c-2e5d147e9d4c.png)

**Comment by adleong** [comment]
@olix0r @grampelberg

**Comment by grampelberg** [comment]
> Span name: the :path pseudoheader of the request

Will this be the gRPC method be the http path or the gRPC method name?

**Comment by adleong** [comment]
HTTP path, which includes the gRPC method name.  For example: `emojivoto.v1.EmojiService.FindByShortCode`

**Comment by olix0r** [comment]
> Service name: the resource (deployment, job, etc.) name that the proxy is injected into the string " (proxy)" is appended to differentiate proxy spans from application spans

How is this determined? I imagine the resource kind must actually be included in this string? Or what happens if two resource types have conflicting names.

Should we just leave this value to be chosen by users without specifying any semantics?

**Comment by grampelberg** [comment]
I was mostly asking because it appeared that the jaeger demo was reporting more of what I'd expect (sans slashes).

**Comment by adleong** [comment]
@grampelberg We could match what OpenCensus-grpc does and use a `.` between service and method but my thinking was that just by putting the HTTP path we get basically the same thing and we don't need to special case gRPC (we can consistently formatted span names between HTTP and gRPC).

**Comment by grampelberg** [comment]
I'm a little concerned, as most folks using gRPC don't know of the HTTP path mapping, but in the end it'll require showing to someone and seeing how it looks in the UI. tldr, sounds good for now.

**Comment by adleong** [comment]
@olix0r I thought that the proxy know the resource name for metrics purposes, but after looking a bit deeper it looks like that metric label is actually added by Prometheus.  We could have the injector pass the resource name in as an environment variable (or, perhaps more generally, pass in a set of service labels).  Where would a user choose a service name?

Adding the resource kind to the name is probably a good idea.  Adding the namespace as well is probably also necessary to avoid conflicts.

**Comment by olix0r** [comment]
@adleong AND this value needs to be kept in sync with whatever magic string the users chooses in her application... which seems impossible. So I nominate not putting any semantic meaning on the field and leave it to be user-selected?

**Comment by adleong** [comment]
Where would the user specify this?

**Comment by olix0r** [comment]
@adleong Well, given that we expect users to configure the proxy's pod, we can just make it a required environment variable when tracing is enabled.

**Comment by adleong** [comment]
I don't think it should be necessary for users to configure the proxy's pod directly.  The only configuration that should be necessary is the location of the oc-collector, which could be set as an inject flag.

**Comment by adleong** [comment]
An alternative would be to just use "Linkerd" as the service name for the proxy spans.  This would mean that traces would look like:

```
web -> web -> Linkerd -> Linkerd -> emoji
```

instead of

```
web -> web -> web (proxy) -> emoji (proxy) -> emoji
```

**Comment by grampelberg** [comment]
I'm a +1 to not making this configurable and picking a sane default that shows it is the proxy itself.
