### ISSUE TITLE
Upgrade stable 2.5 proxy cannot publish to Google Pubsub (gRPC)

### ISSUE THREAD

**Issue by vic3lord** [linkerd/linkerd2#3295]
## Bug Report

After upgrading to stable 2.5 one of our services that publishes messages to Google Pubsub (the sdk for pubsub uses gRPC), stopped publishing messages and held everything in memory until OOM killed, it's getting about 5k events per second so it get there very quick.

### What is the issue?

Cannot publish to Google Pubsub

### How can it be reproduced?

- Try to publish messages to pubsub with 2.5 control plane.
- I tried to configure proxy-version to `stable-2.4.0` it had the same outcome.

### Logs, error output, etc

https://gist.github.com/vic3lord/bc057476ba8bf3430d20065b957f874e

#### `linkerd check` output

```text
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-api
-----------
√ control plane pods are ready
√ control plane self-check
√ [kubernetes] control plane can talk to Kubernetes
√ [prometheus] control plane can talk to Prometheus
√ no invalid service profiles

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ control plane is up-to-date
√ control plane and cli versions match

Status check results are √
```

### Environment

- Kubernetes Version: 1.13.7-gke.8
- Cluster Environment: GKE
- Host OS: COS
- Linkerd version: stable-2.5.0

**Comment by vic3lord** [comment]
I'm having more connectivity issues that are not pubsub related, reverted back to 2.4.
LMK if you need any further info.

**Comment by grampelberg** [comment]
@vic3lord the google pubsub library uses HTTPS from the gRPC client right?

Any other details around connectivity issues?

**Comment by vic3lord** [comment]
@grampelberg I've found that many out-of-cluster communications were not working properly (e.g mongodb atlas) so it's not only gRPC over HTTPS

**Comment by grampelberg** [comment]
That's super helpful!

**Comment by olix0r** [comment]
@vic3lord Is this the go sdk or another? Is there a specific version we should test with?

Also, how are your clients configured (especially dial options, if in Go). Is a secure transport used?

**Comment by cpretzer** [comment]
@vic3lord I've written a simple go client using the [pubsub go library](https://godoc.org/cloud.google.com/go/pubsub) to try to reproduce this issue.

The code uses [topic.Publish](https://godoc.org/cloud.google.com/go/pubsub#Topic.Publish) to send messages to a topic that I created using the `gcloud` cli.

So far I am seeing that the messages are successfully published and I'm getting a message ID back from the topic.

Can you provide more detail about the client that stopped publishing messages? Specifically, the questions that @olix0r asked:

> Is this the go sdk or another? Is there a specific version we should test with?
> Also, how are your clients configured (especially dial options, if in Go). Is a secure transport used?

**Comment by vic3lord** [comment]
I'm using the default dial option coming with the go sdk (`cloud.google.com/go v0.43.0`)
The only option I give to the client is dial with service account file

**Comment by vic3lord** [comment]
Another issue I see after downgrading back to stable-2.4 is that now Cronjobs get stuck with this error in describe

```
Events:
  Type     Reason        Age                   From            Message
  ----     ------        ----                  ----            -------
  Warning  FailedCreate  5m35s                 job-controller  Error creating: Internal error occurred: failed calling webhook "linkerd-proxy-injector.linkerd.io": Post https://linkerd-proxy-injector.linkerd.svc:443/?timeout=30s: context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  Warning  FailedCreate  3m32s                 job-controller  Error creating: Internal error occurred: failed calling webhook "linkerd-proxy-injector.linkerd.io": Post https://linkerd-proxy-injector.linkerd.svc:443/?timeout=30s: context deadline exceeded
  Warning  FailedCreate  102s (x3 over 6m17s)  job-controller  Error creating: Internal error occurred: failed calling webhook "linkerd-proxy-injector.linkerd.io": Post https://linkerd-proxy-injector.linkerd.svc:443/?timeout=30s: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

**Comment by vic3lord** [comment]
Ok, so I've been using linkerd since it was conduit and always on the `edge`, I moved to stable on 2.4 so I guess I had lots of history of `configmaps` `serviceaccounts` and lots of old configs out there.

I removed linkerd from my cluster completely, everything seems to be working now on 2.5

I will go and close this issue, but I guess linkerd is tested against new clusters in CI all the time :) not everyone has my legacy 😃

**Comment by wmorgan** [comment]
Thanks for the update @vic3lord! Glad it worked out in the end.
