### ISSUE TITLE
Add a "Linkerd Namespace" Grafana dashboard

### ISSUE THREAD

**Issue by bourquep** [linkerd/linkerd2#3299]
### What problem are you trying to solve?

I want to be able to see historical data for the same output as `linkerd stat deploy -n my-namespace`, i.e. per-deployment success rate, RPS and latency for a given namespace.

### How should the problem be solved?

By adding a _Linkerd Namespace_ Grafana dashboard, which would allow me to pick a namespace via a dropdown at the top, then display the same widgets as _Linkerd Top Line_ (global success rate, global request volume, global P95 latency) where "global" would mean "all deployments in the selected namespace", then one row per deployment showing the success rate, request volume and P95 latency widgets for each deployment.

### Any alternatives you've considered?

I have a terminal window running `watch -n 5 linkerd stat deploy -n my-namespace`, but this doesn't show me historical data (graphs for the past X minutes).

I have considered building a similar dashboard for myself, but realized that it wouldn't survive a restart/upgrade of the `linkerd-grafana` deployment. I believe this new dashboard would be useful to other Linkerd operators as well, so I think it deserves to be part of the built-in dashboards.

### How would users interact with this feature?

Grafana

**Comment by grampelberg** [comment]
This would be a great dashboard!

**Comment by bourquep** [comment]
I might take a stab at this today. Would be my first humble contribution to Linkerd. Is there a process to go through before submitting a PR? I will not give you the soul of my firstborn child, but other than that I'll try to abide to the requirements.

**Comment by grampelberg** [comment]
Luckily, firstborn children are saved for the second contribution =)

This seems pretty well scoped, I'm sure there will be some discussion around how it looks in the end and @siggy is the grafana expert. Why don't you take a swing at it and we'll see how it goes?

**Comment by bourquep** [comment]
Sounds good!

**Comment by siggy** [comment]
@bourquep Yup go for it! We've wanted to do this work for over a year (#706).

Recommend making the new dashboard as similar to the existing ones as possible.

**Comment by bourquep** [comment]
Done. I personally had no need to have the charts grouped by pod, so I made it so they only display the stats for the deployments. But I could group by pod if you feel like this is a more common use-case.

By pod:

![image](https://user-images.githubusercontent.com/65096/63462986-26cab480-c42a-11e9-8321-c52b9a51a251.png)


By deployment:

![image](https://user-images.githubusercontent.com/65096/63463033-3fd36580-c42a-11e9-896e-03d4cee6ab0f.png)
