### ISSUE TITLE
Traffic split is hiding inbound resources

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#3302]
### What is the issue?

It looks like the dashboard is replacing the incoming resources with traffic split instead of the concrete resource.

![Screenshot 2019-08-21 13 52 10](https://user-images.githubusercontent.com/47992/63468199-1ca1b980-c41c-11e9-9cc7-25d2f309c82a.png)

### How can it be reproduced?

View a deployment detail page with a traffic split in any namespace.

**Comment by scottcarol** [comment]
Hi @grampelberg, I believe this is now fixed in the current `master` branch, can you confirm?

**Comment by grampelberg** [comment]
Looks right to me!
