### ISSUE TITLE
Ephemeral storage is missed in proxy annotations and defaults are ignored

### ISSUE THREAD

**Issue by kivagant-ba** [linkerd/linkerd2#3307]
https://linkerd.io/2/reference/proxy-configuration/

Related to https://github.com/linkerd/website/issues/422

The following annotations are supported:

```
config.linkerd.io/proxy-memory-limit
config.linkerd.io/proxy-memory-request
config.linkerd.io/proxy-cpu-limit
config.linkerd.io/proxy-cpu-request
```

If a namespace has a configured [LimitRange](https://kubernetes.io/docs/concepts/policy/limit-range/) with `min` or `max` setting for `ephemeral-storage`, pods can't be started.

When other containers get default values from `defaultRequest` and `default` (limit) configurations of a LimitRange, Linkerd sidecar doesn't respect them for some reason and the ReplicaSet fails with the event:

```
  Warning  FailedCreate  49s (x6 over 2m26s)  replicaset-controller  (combined from similar events): Error creating: pods "tum-tururum-pum-pum-659f5f99cd-xpk4x" is forbidden: [minimum ephemeral-storage usage per Pod is 10Mi.  No request is specified., maximum ephemeral-storage usage per Pod is 10Gi.  No limit is specified.]

  Warning  FailedCreate      12s                replicaset-controller  Error creating: pods "tum-tururum-pum-pum-65f5788c57-v9dsc" is forbidden: maximum ephemeral-storage usage per Pod is 10Gi.  No limit is specified.
```

```
➜ linkerd version
Client version: stable-2.5.0
Server version: stable-2.5.0

➜ kubectl version --short
Client Version: v1.15.3
Server Version: v1.12.10-eks-2e569f
```

I would suggest to support custom annotations because some other third-parties can be installed into a K8s cluster that can prevent pods from starting. Maybe it is already possible somewhere in Linkerd's ConfigMap?

**Comment by kivagant-ba** [comment]
Thank you, @ihcsim , sorry for placing this in a wrong place.

**Comment by grampelberg** [comment]
The core problem is that defaults aren't being applied, right? Kinda sounds like a case of https://github.com/kubernetes/kubernetes/pull/78080. Do you need to actually configure the min/max or would that fix the problem for you?

**Comment by kivagant-ba** [comment]
> The core problem is that defaults aren't being applied, right? 

Yes, but defaults could not be enough for linkerd. If it has options for cpu/memory, it would be nice to also configure other possible request and limits.

I'm not sure if the PR fixes the problem since I don't have installed K8s 1.15. And it isn't available at all in AWS EKS atm. Takin into account that upgrading the entire cluster is not so easy operation, it still would be nice to have the options in Linkerd itself. I had to completely disable LimitRange min/max values for ephemeral storage because nothing can start with Linkerd if they are enabled.

**Comment by kivagant-ba** [comment]
@grampelberg , any chance this can be prioritized? I also found the Helm chart [does not support setting](https://github.com/linkerd/linkerd2/blob/master/charts/partials/templates/_resources.tpl) ephemeral storage and other potential requests and limits which causes some undesired corner side effects.

For example, if one has a [`LimitRange`](https://kubernetes.io/docs/concepts/policy/limit-range/) like this one:

```
- apiVersion: v1
  kind: LimitRange
  metadata:
    name: my-container
# ...
  spec:
    limits:
    - default:
        ephemeral-storage: 4Gi
        memory: 512Mi
      defaultRequest:
        cpu: 10m
        ephemeral-storage: 100Mi
        memory: 512Mi
      max:
        memory: 16Gi
      min:
        cpu: 10m
        memory: 5Mi
      type: Container
```

Than Kubernetes will start a pod with the injected `linkerd-proxy` container which will also request **4Gi** of ephemeral storage so in total the container will get **8Gi** instead of **4Gi** as it was expected.

**Comment by grampelberg** [comment]
@kivagant-ba I'll need more definition around the problem and solution I think before this can be scheduled. I don't have any experience with `LimitRange` and your configuration here. Obviously the easiest solution here would be a PR, but if we flesh out the problem/solution some more it might be possible to get help on this sooner rather than later.

**Comment by kivagant-ba** [comment]
Got it, I obviously have to make a PR :) 
No promises, but I will be happy to do this when I find the power in me.

**Comment by grampelberg** [comment]
That'd be fantastic! Thank you!!
