### ISSUE TITLE
"nginx.ingress.kubernetes.io/auth-type: basic" redirect to 404

### ISSUE THREAD

**Issue by oceaneLonneux** [linkerd/linkerd2#3309]
I followed the documentation to install linkerd (https://linkerd.io/2/getting-started/) and then wanted to expose the dashboard to the devs so they could check it out (https://linkerd.io/2/tasks/exposing-dashboard/#nginx).
It is written in the docs that the secret is a admin/admin. When writing username: admin and password; admin, even changing them in the Secret, it always redirected me to a 404.

### What is the issue?
When using "nginx.ingress.kubernetes.io/auth-type: basic" in the ingress nginx, it seems to "lock me out" of some kind. 

### Environment
- Kubernetes Version: 1.12
- Cluster Environment: EKS, so Kubernetes on AWS.
- Host OS: Linux.
- Linkerd version: 2.4.

### Possible solution
Taking off this line allowed us to directly access the dashboard. We are going to use another form of auth so I didn't particularly needed that one, but it might be a problem to most people. 

Thanks!

**Comment by grampelberg** [comment]
Any more details? What'd you change? I just tested on GKE and it works correctly.

**Comment by grampelberg** [comment]
Closing this out, please re-open with more details if you're still experiencing any problems.
