### ISSUE TITLE
Use a scratch proxy image

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#3326]
In order to generally reduce the (security) surface area of the linkerd proxy container, we should investigate switching to using a `scratch` image that includes only two binaries: the proxy and the identity bootstrap tool.

The proxy build would need to change to produce static binaries, but we have prior art for that in [`linkerd-await`](https://github.com/olix0r/linkerd-await/blob/master/Dockerfile).

**Comment by joakimr-axis** [comment]
> The proxy build would need to change to produce static binaries

Not necessarily; when I create such scratch-based containers I feed the ldd output for the binary to a simple native shell script loop that will copy the dynamic libraries necessary to a staging area (directory) in the build container that is then what is copied into the final scratch-based container.

```
FROM <some_base> AS builder
# [snip]
WORKDIR /export
RUN cp "$SRC_DIR"/TheBinary . && \
    ldd ./TheBinary| while read -r path1 _ path2 _; do \
        for lib in "$path1" "$path2"; do \
           case $lib in \
               /*) \
                   tar -ch "$lib" 2>/dev/null | tar x \
                   ;; \
           esac \
        done \
    done

FROM scratch
COPY --from=builder /export /
ENTRYPOINT [ "/TheBinary" ]
```

**Comment by olix0r** [comment]
@joakimr-axis That's cool! :)

In 2.11 we moved to using [`distroless`](https://github.com/GoogleContainerTools/distroless/tree/main/cc) base images for our rust components which at least avoids shipping a shell in the linkerd container. I'm going to close this, as the original problem has basically been addressed.
