### ISSUE TITLE
Don't suggest to inject un-meshable namespaces

### ISSUE THREAD

**Issue by 007** [linkerd/linkerd2#3330]
### What problem are you trying to solve?
The suggestion that namespaces are not meshed creates confusion when they shouldn't / can't be meshed:
![no-meshed](https://user-images.githubusercontent.com/195099/63809547-73553a80-c8d7-11e9-8002-2c7fcc0c939d.png)
I have 8 namespaces that are being meshed, and 5 that aren't: `kube-system` (which shouldn't be⁉️), `kube-public` (which is empty), and 3 other app namespaces that I will hook up eventually.
![unmeshable](https://user-images.githubusercontent.com/195099/63809725-eced2880-c8d7-11e9-9bdb-911228e82d10.png)

### How should the problem be solved?
Remove `kube-system` and any empty namespaces from consideration for unmeshed resource notification. Depending on how things are deployed, `default` and/or `kube-public` will be empty more often than not.

### Any alternatives you've considered?

Re: ⁉️ above: I don't see any hard documentation that says not to enable linkerd for `kube-system`, but it seems to be the consensus that it isn't advisable. Is that true, and if so, can _that_ be documented concretely?

Ref #1516 #1603 #1931 and #3305 for others who have had trouble with variations on this theme.

### How would users interact with this feature?

Users wouldn't get notifications if everything that can safely be meshed is being meshed.

**Comment by ArthurSens** [comment]
Maybe don't show resources with `hostNetwork: true` would be nice as well... since they can't be injected

**Comment by vaniisgh** [comment]
Hey:)

 Is it ok if I try to have a go at this?

**Comment by hodbn** [comment]
I guess we'll need to expose `injectable_pod_count` to `StatTable.PodGroup.Row`:
https://github.com/linkerd/linkerd2/blob/2e5087b9f6d9f4d01ade62146dde27220a75ef38/proto/public.proto#L404-L415
and then exclude namespaces with no injectable pods in the frontend.

This will require each pod's resource config to create a new report and call `Injectable()`:
https://github.com/linkerd/linkerd2/blob/2e5087b9f6d9f4d01ade62146dde27220a75ef38/pkg/inject/report.go#L111

@grampelberg what do you think?
