### ISSUE TITLE
Check for incompatible trust roots

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#3344]
### What problem are you trying to solve?

If a user was to install linkerd, then uninstall and re-install, the old proxies would be using the old trust root. This would end up creating some weird bad certificate errors in the logs. `check` or `check --proxy` should validate that the trust roots match for every pod that has the proxy in the cluster.

**Comment by anchit1729** [comment]
Hi @grampelberg, I would like to take up this issue and work on it if that's okay.

**Comment by ereslibre** [comment]
PR open: https://github.com/linkerd/linkerd2/pull/3524. Submitted for early feedback, have to address the lack of tests.
