### ISSUE TITLE
What happens when the Destination service encounters network partitions?

### ISSUE THREAD

**Issue by briansmith** [linkerd/linkerd2#335]
The code for subscribing to the Kubernetes EndPoints API looks like this:

```go
	listener := endpointListener{stream: stream}
	s.endpoints.Subscribe(id, uint32(port), listener)
	<-stream.Context().Done()
	s.endpoints.Unsubscribe(id, uint32(port), listener)
	return nil
```

It isn't clear what we expect to happen when the Destination service gets disconnected from the Kubernetes master API server when a subscription is in progress. Are we intending that the Destination service will send an error to the proxy and then the proxy will re-subscribe to the name? This might be OK but it seems like a potentially huge amount of network traffic to generate on each disconnect:

* Every proxy instance (N), for every name currently needed (M), will re-subscribe the Destination service.
* The Destination service will then create N*M subscriptions for the API server (See #334).
* N*M*L results will be returned to each proxy, where L is the number of endpoints per service.

At a minimum, we should:
* Document what happens when there are connectivity issues between the destination service and the Kubernetes API server, in terms of how it affects reliability of Conduit-proxied services.
    * Do we do anything to prevent requests from failing in that scenerio? If not, what's the reason we don't (backpressure?).
    * How does the resilience compare to what kube-proxy does in the face of similar network partitions?
* Test the scenerio where proxies have subscribed to the destination service for a name and the destination service has subscribe to the Kubernetes API server, and then the connection between the Destination service and the Kubernetes API server drops, to make sure it works like we expect. In particular, verify that the proxies eventually resync to the consistent and correct set of IPs per service once connectivity is fully restored.
* Investigate whether we should implement retries or another mechanism to improve resilliancy in the face of such issues.

We should write the same documentation and to the same testing for partitions between proxy instances and the Destinations service. In particular, we should verify:

* The proxy can keep running with its cached prior responses from the Destinations service.
* The proxy itself prunes (circuit breaker style) IPs from its IP address lists for a name (at least when it sees that that it is disconnected from the Destinations service) when a threshold of connection failures for that IP occur.
* The proxy is able to re-sync with the destination service and get the full, correct, list of IP addresses once connectivity is restored.

**Comment by wmorgan** [comment]
Out of scope for 0.3, but we will likely need to tackle this for prod readiness.
