### ISSUE TITLE
Control plane not starting in Kubernetes 1.16

### ISSUE THREAD

**Issue by alpeb** [linkerd/linkerd2#3356]
The linkerd-controller, linkerd-tap and linkerd-proxy-injector pods are not starting because they're getting blocked "waiting for caches to sync".

Tried with edge-19.8.7 and Kubernetes 1.16.0-beta.1 with Minikube and bare-metal.

**Comment by alpeb** [comment]
The problem is we're still establishing watchers against the `apps/v1beta1` and `apps/v1beta2` apis that got removed in 1.16, as this log entry from the proxy-injector shows:
```
round_trippers.go:438] GET https://10.96.0.1:443/apis/apps/v1beta2/deployments?limit=500&resourceVersion=0 404 Not Found in 1 milliseconds"
```
Re kubernetes/kubernetes#70672

**Comment by grampelberg** [comment]
It sounds like an easy fix. Does this require a point release or do we have enough time for 2.6 to come out?

**Comment by alpeb** [comment]
It's a quick fix indeed, I can get that in next week. My bet is 1.16 might come out one or two weeks before our 2.6. If we decide a point release is worth it, the fix will be there to be cherry-picked.
