### ISSUE TITLE
Create a Helm repo to host the Linkerd Helm chart

### ISSUE THREAD

**Issue by ihcsim** [linkerd/linkerd2#3365]
Create a new Helm repo on GCS to host the Linkerd Helm chart. Users will install the Helm chart by interacting with this repo:

```
helm repo add linkerd https://linkerd.storage.googleapis.com/ # if the bucket name is available
helm install <prefix>/linkerd2  # not sure what <prefix> should be; might be optional
```

Related https://github.com/linkerd/linkerd2/issues/3256.

**Comment by grampelberg** [comment]
WDYT about just putting this into `run.linkerd.io`? Adding the chart tarballs to the website repo isn't super amazing, but at least we'd get it all working in the same flow.

**Comment by ihcsim** [comment]
So place the tar file at https://run.linkerd.io/charts/linkerd2.tar.gz? And then run something like:

```
helm repo add linkerd https://run.linkerd.io/charts
helm install linkerd/linkerd2
``` 

Sure, I don't have a strong preference.

**Comment by grampelberg** [comment]
Yup, that's my thinking.
