### ISSUE TITLE
Publish Helm chart to Helm Hub

### ISSUE THREAD

**Issue by ihcsim** [linkerd/linkerd2#3367]
With the official Helm Repo soon to be deprecated, we should publish our Helm chart to Helm Hub, per docs [here](https://github.com/helm/hub/blob/master/Repositories.md).

**Comment by alpeb** [comment]
I've created a PR in Helm's hub repo:n helm/hub#148

**Comment by alpeb** [comment]
The charts have been published at these locations:
https://hub.helm.sh/charts/linkerd2/linkerd2
https://hub.helm.sh/charts/linkerd2-edge/linkerd2

I'll try now to properly set an icon for them.

**Comment by alpeb** [comment]
The changes in our Helm repo aren't being picked up by the Helm hub. I've opened helm/hub#160 to ask about it.

**Comment by alpeb** [comment]
The changes were finally picked up. Closing this issue.
