### ISSUE TITLE
When kube-apiserver times-out proxy-injector request, cancel the ongoing request

### ISSUE THREAD

**Issue by alpeb** [linkerd/linkerd2#3373]
In #3358 we discovered a timeout on proxy-injector requests during heavy load. The requests that time out do so only on the kube-apiserver side but they keep on getting processed on the proxy-injector side, which then reports the injections even though they are being ignored by kube-apiserver.

The solution is to catch the request context cancellation and cancel the ongoing request.

This is not a problem when there are no timeouts, which is being fixed in #3358, so this is a low priority item.

**Comment by grampelberg** [comment]
@alpeb do we still need this?

**Comment by alpeb** [comment]
Yes, this is still an issue.

**Comment by grampelberg** [comment]
Well then, I can schedule it =) Thanks!
