### ISSUE TITLE
Please rename "partials" and "path" Helm charts

### ISSUE THREAD

**Issue by kivagant-ba** [linkerd/linkerd2#3392]
### What problem are you trying to solve?

1. If one needs to publish Linkerd helm charts to a local registry or cache them in a local git repo, these names are not clear:
- partials
- patch

2. Also I found that it is very hard to find search entries for "partials" and especially for "patch" in the project code without the prefix.

### How should the problem be solved?

Please add prefixes same as for the main chart:

- linkerd2-partials
- linkerd2-patch

### Any alternatives you've considered?

Nothing clever comes to my mind.

### How would users interact with this feature?

For users everything will be the same. Taking into account that [the documentation](https://linkerd.io/2/tasks/install-helm/) is pretty simple, users like me can not understand why the `patch` chart exists and how to use it. :(

**Comment by grampelberg** [comment]
Both charts are internal implementation details. Packaged up, end users shouldn't ever need those (so there's no real reason to have them included in your local repo).

**Comment by kivagant-ba** [comment]
Unfortunately, `helm dependency update` usually is a part of CI and called within the `linkerd` chart it won't work since it relies on a local directory `../partials`

**Comment by KIVagant** [comment]
@alpeb , yeah, I saw the ticket and this is good of course. However, some of the companies have policies when artifacts like Helm charts are cached in an internal git / helm repo to control changes, do some local fixes without waiting for upstream fixes etc. If the public repo you mentioned has the chart without dependencies on local folders, my issue will be not an issue anymore. But if not, please take into account the use case when public Helm charts are additionally built in a third-party CI to test local values compatibility.

**Comment by grampelberg** [comment]
@KIVagant when building the chart with your own CI, will the naming be an issue? It seems, as these charts are only ever used internally, you'd only ever build/publish the `linkerd2` chart itself and the naming wouldn't be an issue?

**Comment by KIVagant** [comment]
If `requirements.yaml` won't have these lines, then yes, of course:
```yaml
dependencies:
- name: linkerd2-partials
  version: 0.2.0
  repository: file://../linkerd2-partials
```
