### ISSUE TITLE
Heartbeat CronJob with no access to internet

### ISSUE THREAD

**Issue by lecourtoisn** [linkerd/linkerd2#3395]
### What problem are you trying to solve?
The hearbeat job makes a call to https://versioncheck.linkerd.io/version.json wich can't work on on-premise servers with no access to internet for example. 

### How should the problem be solved?
Maybe there should be way of disabling that particular version check. Or am I missing something ?

### Any alternatives you've considered?
Disabling the whole Heartbeat Cronjob either with the helm option or by removing it from the install manifest. But I don't know what useful feature of the Hearbeat I would miss.

### How would users interact with this feature?
An option in the linkerd install command and the equivalent in the chart values.

**Comment by ihcsim** [comment]
@lecourtoisn Good timing. We just released edge-19.9.1, which includes a new Helm variable to disable the heartbeat service. One caveat is that when the heartbeat service is disabled, the `linkerd check` command will fail. See https://github.com/linkerd/linkerd2/pull/3366#issuecomment-528186756.

LMK if you have further questions, or if we can close this issue.

**Comment by lecourtoisn** [comment]
I mentioned it under "Any alternative" but unless the heartbeat service is all about this version call, I don't wish to disable it entirely, do I ?

**Comment by ihcsim** [comment]
Disabling/failing heartbeat will not interfere with any Linkerd features.

**Comment by lecourtoisn** [comment]
I know, I don't want to disable the heartbeat. I want to disable anything that requires an internet call and keep anything the heartbeat does besides that.

**Comment by ihcsim** [comment]
Not sure I fully understand your intent. Heartbeat just gathers the [control plane version and a few other attributes](https://github.com/linkerd/linkerd2/blob/46d33a10e46dc2cb5fbe39475b7f435b26eab89f/controller/cmd/heartbeat/main.go#L26-L33), and send them to the external URL, with no return values. If your k8s cluster has no access to external endpoints, then heartbeat won't be relevant. Feel free to reach me on slack if this doesn't answer your question.

**Comment by lecourtoisn** [comment]
It does answer my question, thank you !
