### ISSUE TITLE
Simplify dashboard sidebar

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#3400]
### What problem are you trying to solve?

The dashboard's sidebar has a couple current problems:

- It is a little cluttered.
- Information is hidden by default.
- Filtering is difficult.
- Load on prometheus is excessive.

### How should the problem be solved?

The Kubernetes dashboard does a good job of solving these problems by:

- Listing the possible resources types, not showing every resource.
- Filtering to namespaces by default, instead of showing everything at once.
- Not using trees to hide information.

Towards this end, I've thrown a mockup together of how the sidebar could look. Check out [the repo](https://github.com/grampelberg/linkerd2-mockups/tree/master/sidebar) to run it yourself, or check out the screenshots:

![Screenshot 2019-09-12 11 58 22](https://user-images.githubusercontent.com/47992/64813735-e953d580-d556-11e9-83d5-324f92ee01e2.png)

- Namespaces shows the traffic aggregated by namespace and should be the default view.
- Nodes doesn't exist yet, so ignore that for now.
- Control plane is the same as the service mesh view currently. That'll get refreshed into something a little different later.
- Dropdown shows the available namespaces. There is an `All Namespaces` option that should not be the default. See further down for a screenshot.
- All workloads go to the same page as `All` right now, without the namespace column.
- Ingress, service, service accounts, service profiles do not exist yet and can be ignored.

![Screenshot 2019-09-12 11 58 46](https://user-images.githubusercontent.com/47992/64813736-e953d580-d556-11e9-931f-a034341fefc4.png)

- Tools are a 1:1 with what's there now. It would be interesting to scope these to the namespace selector, but let's not do that yet.
- About is a new page that has the version and whether the system is up to date.

![Screenshot 2019-09-12 11 59 06](https://user-images.githubusercontent.com/47992/64813737-e953d580-d556-11e9-9e35-c4c8f74af9fd.png)

### Examples of Kubernetes dashboard

![Screenshot 2019-09-06 15 23 07](https://user-images.githubusercontent.com/47992/64463915-a8714200-d0ba-11e9-8c6b-df8182719a8d.png)

![Screenshot 2019-09-06 15 23 27](https://user-images.githubusercontent.com/47992/64463914-a60ee800-d0ba-11e9-89a5-618e221120af.png)

**Comment by scottcarol** [comment]
Responsive question: The current Linkerd dashboard looks like the below image when the screen width is narrow. (Running your test repo in Safari, the sidebar disappears at a certain screen width.)

The K8s dashboard keeps the sidebar the same width no matter the screen size. If we are moving towards the K8s dashboard, I'd support maintaining the width of the sidebar in all views. WDYT?

![Screen Shot 2019-09-13 at 11 08 38 AM](https://user-images.githubusercontent.com/2289389/64884578-ea4c3c00-d616-11e9-9e30-881426f6984c.png)
