### ISSUE TITLE
Connection to pod's own IP is prevented

### ISSUE THREAD

**Issue by cscetbon** [linkerd/linkerd2#3404]
### What is the issue?
Applications can't connect to local services using the pod's ip address status.podIP. As an example Cassandra which uses Gossip needs to connect to its own IP.
### How can it be reproduced?
Use deployment files available at https://gist.github.com/cscetbon/f7869c53d2362fa2f744a444b73efbfb. The first one prevents second node to start correctly. The second one forces nodes to listen on 127.0.0.1 which fixes the issue. It should not be necessary to change the listen address when Linkerd is activated.

### Environment

- Kubernetes Version: 1.15
- Cluster Environment: (GKE, AKS, kops, ...) docker in docker using Kind
- Host OS: MacOS 10.14.6
- Linkerd version: stable-2.3.0

**Comment by ihcsim** [comment]
For context, Cassandra can't listen on `0.0.0.0` per [docs](http://cassandra.apache.org/doc/latest/faq/index.html#why-cant-list-all). By default, the Cassandra nodes are configured to listen on the pod IP (via downward API). I suspect what is happening is that this default causes the Linkerd proxy to not be able to communicate with the Cassandra service via the loopback address. @cscetbon got around this by setting the `listen-address` to `127.0.0.1`.

@cscetbon To clarify, I don't think this is the case where an injected pod isn't able to communicate with itself via its pod IP. If you deploy a deployment with two sidecars (say nginx and curl), you will see that the curl container can still talk to the nginx container via the pod IP, even after the Linkerd proxy is injected (regardless of whether a headless and regular `Service` in front of the deployment or not).

**Comment by cscetbon** [comment]
@ihcsim I checked and you're right, The **cassandra** container can connect to itself using the loopback interface or the pod ip where it listens to. However, it can't connect to the other cassandra container which is the issue. Then after a minute or more, the connection is available

```
cassandra@cassandra-e2e-dc1-rack1-1:/$ nc cassandra-e2e-dc1-rack1-0.cassandra-e2e.cassandra-e2e 9042

d
HTTP/1.1 400 Bad Request
content-length: 0
date: Mon, 09 Sep 2019 03:05:53 GMT

cassandra@cassandra-e2e-dc1-rack1-1:/$ nc cassandra-e2e-dc1-rack1-0.cassandra-e2e.cassandra-e2e 9042

d
HTTP/1.1 400 Bad Request
content-length: 0
date: Mon, 09 Sep 2019 03:06:01 GMT

cassandra@cassandra-e2e-dc1-rack1-1:/$ nc cassandra-e2e-dc1-rack1-0.cassandra-e2e.cassandra-e2e 9042
d
�c
]Invalid or unsupported protocol version (115); supported versions are (3/v3, 4/v4, 5/v5-beta)^C
```

**Comment by grampelberg** [comment]
What protocol does cassandra use? This sounds like a server-speaks first issue.

**Comment by cscetbon** [comment]
@grampelberg like I said it uses [The Gossip protocol](https://www.linkedin.com/pulse/gossip-protocol-inside-apache-cassandra-soham-saha/).

**Comment by cscetbon** [comment]
I forgot to say that the error is that I get tons of 
```
INFO  [HANDSHAKE-cassandra-e2e-dc1-rack1-0.cassandra-e2e.cassandra-e2e/10.244.1.21] 2019-09-10 01:19:11,534 OutboundTcpConnection.java:561 - Handshaking version with cassandra-e2e-dc1-rack1-0.cassandra-e2e.cassandra-e2e/10.244.1.21
INFO  [HANDSHAKE-cassandra-e2e-dc1-rack1-0.cassandra-e2e.cassandra-e2e/10.244.1.21] 2019-09-10 01:19:11,629 OutboundTcpConnection.java:570 - Cannot handshake version with cassandra-e2e-dc1-rack1-0.cassandra-e2e.cassandra-e2e/10.244.1.21
INFO  [HANDSHAKE-cassandra-e2e-dc1-rack1-0.cassandra-e2e.cassandra-e2e/10.244.1.21] 2019-09-10 01:19:11,739 OutboundTcpConnection.java:561 - Handshaking version with cassandra-e2e-dc1-rack1-0.cassandra-e2e.cassandra-e2e/10.244.1.21
INFO  [HANDSHAKE-cassandra-e2e-dc1-rack1-0.cassandra-e2e.cassandra-e2e/10.244.1.21] 2019-09-10 01:19:11,744 OutboundTcpConnection.java:570 - Cannot handshake version with cassandra-e2e-dc1-rack1-0.cassandra-e2e.cassandra-e2e/10.244.1.21
```

on the second node that is supposed to handshake with the first node and finally the second node starts with only itself in the cluster as it was not able to connect to the existing node.

**Comment by cscetbon** [comment]
Hey guys, any idea what's going on here and how to fix it ?

**Comment by ihcsim** [comment]
@cscetbon Sorry for the delay. We haven't had the chance to look deeper into your issue yet. I am not sure if we are still looking at the same errors.

Here are some initial thoughts on the latest logs you posted:

>  Cannot handshake version with cassandra-e2e-dc1-rack1-0.cassandra-e2e.cassandra-e2e/10.244.1.21

I am not sure what this means. Since it is logged as `INFO`, I assume it's benign?

> an error occurred trying to connect: Connection refused (os error 111) (address: 127.0.0.1:7000)
> an error occurred trying to connect: Connection refused (os error 111) (address: 127.0.0.1:7001)

This is saying the Linkerd proxy can't talk to your Cassandra application's at 127.0.0.1:7000 and 127.0.0.1:7001, which looking at the YAML you posted earlier corresponds to the `tcp-infra-node` and `tcp-tls-intra-node` ports. What is your Cassandra current `listen-address`?

> it uses The Gossip protocol.

If this is a server-speaks first protocol, try use the `--skip-inbound-ports` and `--skip-outbound-ports` of the `linkerd inject` command to skip those TCP ports. See [docs](https://linkerd.io/2/features/protocol-detection/) for examples.

LMK how it goes.

**Comment by cscetbon** [comment]
@ihcsim I confirm that using those options allows nodes to communicate and to handshake correctly.

**Comment by grampelberg** [comment]
@cscetbon it sounds like your issue's been taken care of. I'll close this issue out for now. If you have any suggestions for ways to make it more obvious a server speaks first protocol isn't getting detected that'd be super helpful!
