### ISSUE TITLE
Helm chart: namespaces "linkerd" already exists

### ISSUE THREAD

**Issue by KIVagant** [linkerd/linkerd2#3412]
### What is the issue?

 https://github.com/helm/helm/issues/5153 (https://github.com/helm/helm/issues/3179)
```
helm upgrade --install --namespace=linkerd --values ./values/linkerd2/values.yaml --set-file=Identity.TrustAnchorsPEM=_Identity.TrustAnchorsPEM.tmp --set-file=Identity.Issuer.TLS.CrtPEM=_Identity.Issuer.TLS.CrtPEM.tmp --set-file=Identity.Issuer.TLS.KeyPEM=_Identity.Issuer.TLS.KeyPEM.tmp linkerd2 ./linkerd2-0.2.1.tgz
Release "linkerd2" does not exist. Installing it now.

Error: release linkerd2 failed: namespaces "linkerd" already exists
```

### How can it be reproduced?

1. Delete linkerd2 completely.
2. Install it with the Helm chart using `helm upgrade --install`

### Logs, error output, etc

> Error: release linkerd2 failed: namespaces "linkerd" already exists

#### `linkerd check` output

```text
➜ linkerd check
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-config
--------------
√ control plane Namespace exists
× control plane ClusterRoles exist
    missing ClusterRoles: linkerd-linkerd-controller, linkerd-linkerd-identity, linkerd-linkerd-prometheus, linkerd-linkerd-proxy-injector, linkerd-linkerd-sp-validator, linkerd-linkerd-tap
    see https://linkerd.io/checks/#l5d-existence-cr for hints

Status check results are ×
```

### Environment
```
➜ helm version
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}
```
- Kubernetes Version: doesn't matter
- Cluster Environment: doesn't matter
- Host OS: doesn't matter
- Linkerd version: Helm chart from current "master": branch

### Possible solution

Don't know yet. At least add an option to enable or disable namespace installation via Helm since the problem was fixed only in https://github.com/helm/helm/issues/5753

### Additional context
- https://github.com/helm/helm/issues/5153
- https://github.com/helm/helm/issues/3179
- https://github.com/helm/helm/issues/5753

**Comment by alpeb** [comment]
@KIVagant As per the Helm issues you linked to, Helm doesn't allow creating namespaces with annotations/labels, something that is required for Linkerd. For that reason we don't support Helm's `--namespace` flag.

If you pass `--namespace linkerd` it will fail because Helm will create the namespace and then Linkerd will also try to create the namespace (with the required annotations and labels).

If you pass a different namespace name to `--namespace`, Helm will create it but Linkerd will still get installed under the `linkerd` namespace. 

In order to change the namespace where you want to install Linkerd you can override the `Namespace` value in the `values.yaml` file.

**Comment by KIVagant** [comment]
Thank you, @alpeb, fair enough. Anyway, I prefer to control all namespaces in a different place all together, so for my case the PR is more convenient solution.

**Comment by alpeb** [comment]
I'll take a look at your PR in a bit. If you'll be managing your namespaces elsewhere, please keep in mind that you'll have to add the label `linkerd.io/is-control-plane: "true"`, which is necessary for the correct functioning of the control plane.
