### ISSUE TITLE
proxy: opencensus exporter should eagerly poll for errors

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#3430]
As discussed in linkerd/linkerd2-proxy#338, the initial implementation of the span exporter has a small defect in that it doesn't poll the response side of the stream, which (I believe) is necessary to eagerly detect stream errors (and to know the grpc-status/message of the error).

**Comment by adleong** [comment]
What about the situation where the response is complete (i.e. we poll it to completion) but the server raises a stream error (stream reset)?  How can the sender be eagerly notified in that case?

**Comment by adleong** [comment]
Looking at the opencensus go client, it appears that they never attempt to read the response stream until the request stream encounters an error.  The response is then read to determine the cause of the request stream error:

https://github.com/census-ecosystem/opencensus-go-exporter-ocagent/blob/master/ocagent.go#L400

In particular, it doesn't seem like the server sending a response will terminate the client request stream.
