### ISSUE TITLE
Create a makefile that automatically builds all Linkerd2 components

### ISSUE THREAD

**Issue by mayankshah1607** [linkerd/linkerd2#3435]
## Feature Request

Create a makefile that automatically builds all Linkerd2 components in Docker images, and deploys them onto Minikube

### What problem are you trying to solve?
Save time by using `make` to automatically build all the components required by linkerd2 for dev purposes

### How should the problem be solved?
By creating  a simple Makefile with all the commands under [Comprehensive build](https://github.com/linkerd/linkerd2/blob/master/BUILD.md#comprehensive)

What do you want to happen? Add any considered drawbacks.
Build the dev environment with just one command

### Any alternatives you've considered?
No

Is there another way to solve this problem that isn't as good a solution?
Not that I know of, yet.
### How would users interact with this feature?
Users can use `make`
If you can, explain how users will be able to use this. Maybe some sample CLI
output?

```bash
$ make build
```

**Comment by grampelberg** [comment]
Any reason `bin/docker-build` didn't work for you?

@ihcsim where's that awesome tilt setup that you have been using?

**Comment by ihcsim** [comment]
@mayankshah1607 I'm a big fan of Makefile, but as you've already seen in the build docs, the `DOCKER_TRACE=1 bin/mkube bin/docker-build` command will do what you want. Not sure how much we're gonna save from having introducing a Makefile here, especially when most terminals can alias or reverse search the command.

If you want a truly continuous build and deploy experience, I will recommed checking out [Tilt](https://tilt.dev). A while back, I added a [Tiltfile](https://github.com/ihcsim/linkerd2-tilt) for Linkerd, but I haven't had time to update it to use the latest Linkerd Helm chart.

**Comment by grampelberg** [comment]
I'm going to close this one out for now. Please repon @mayankshah1607 if there's something in either of those solutions that doesn't work for you.
