### ISSUE TITLE
destination: support resolving pod IP addresses 

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#3443]
The destination service should `Get` request with a `path` in the form of `IP:PORT`; and when this IP is that of a kubernetes pod IP, serve that pods metadata via a resolution (i.e. with no parent service metadata).

It would only ever make sense for these resolutions to receive responses that are:
- `Add(...)`
- `NoEndpoints { exists: false }`
- `InvalidArgument` (error) if the control plane can _guarantee_ that the IP will never be a Pod IP in this cluster.

This will allow the proxy to establish TLS for inter-pod non-k8s-service traffic (such as prometheus).

**Comment by adleong** [comment]
this is still in progress https://github.com/linkerd/linkerd2/pull/3595
