### ISSUE TITLE
Move olix0r/linkerd-await into linkerd org

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#3450]
The linkerd-await utility is probably worth promoting into the linkerd org, now that we have a clearer story about how it can be controlled at runtime (rather than build-time).

Then, we can consider using linkerd-await in the control plane (though note it MUST be disabled on at least the identity controller). This would enable controller-to-k8s traffic to be properly depicted in telemetry, for instance.

**Comment by olix0r** [comment]
It will need to be updated to support all of Linkerd's supported architectures

**Comment by olix0r** [comment]
Multiarch support added ;) https://github.com/olix0r/linkerd-await/releases/tag/release%2Fv0.2.1

**Comment by davi5e** [comment]
An an outsider following these developments, will Linkerd Await move it's binaries from the current repository to this one?

This has major implications in our Dockerfiles and it would likely brake stuff if we are not prepared. Also, I would think this concern apply for other people as well, hence this follow up.

**Comment by kleimkuhler** [comment]
@davi5e Yes that is correct. The first release under the Linkerd org is [0.2.3](https://github.com/linkerd/linkerd-await/releases/tag/release%2Fv0.2.3). Sorry this was not mentioned until now!
