### ISSUE TITLE
Identity issuer certificate expires after 1 year

### ISSUE THREAD

**Issue by adleong** [linkerd/linkerd2#3452]
When the Linkerd control plane is installed, the default behavior is to generate an identity issuer certificate and key for the identity controller to use to issue service account certificates.  The issuer material is generated from a root CA and key.  The root CA is saved in a config map as the trust root and the root key is thrown away.

The default expiry period for the issuer certificate is 1 year.  What happens when that certificate expires?  Since the root key has been thrown away, there is no way to issue a new certificate from the existing trust root, so I believe that the trust root must be replaced.

I believe these issuer certificates started being generated in [this edge release](https://github.com/linkerd/linkerd2/releases/tag/edge-19.3.3) on March 22, 2019.  This means that March 22, 2020 is a sort of "doomsday" where clusters which were installed with edge-19.3.3 or later and run for 1 year will start failing to issue new certificates.

**Comment by grampelberg** [comment]
See #3431 for a related issue.

**Comment by grampelberg** [comment]
Also see #3449.

**Comment by adleong** [comment]
In particular, we should understand what happens for each of the Linkerd versions when it hits the doomsday.
e.g. What happens when a 2.6 cluster hits doomsday?  What happens when a 2.7 cluster hits doomsday?  Can we warn users in advance if there's some action that they need to take before doomsday?

**Comment by ihcsim** [comment]
From my last conversation with @grampelberg, the cert-manager integration works only for 2.7+. If for whatever reasons, the cert-manager cert auto-renewal window is missed, users can manually override it, using something like `linkerd upgrade --from-manifest`. (Most of the `--identity-*` options are disabled for `upgrade`.) We created https://github.com/linkerd/linkerd2/issues/3578 to investigate further into cert-manager's behaviour in this scenario.

For pre-2.7 control planes, there will be data plane downtime no matter what. Some Helm users already started to manage the key/cert pairs themselves. My thought is to continue to rely on `linkerd upgrade --from-manifest` to make the change. `--from-manifest` can be used to update both the `linkerd-config` config map and the `linkerd-identity-issuer` secret. We will provide some docs on how to do that.

> Can we warn users in advance if there's some action that they need to take before doomsday?

Good point. Maybe to build on top of https://github.com/linkerd/linkerd2/pull/3524, `check` can issue a warning if the trust root is going to expire in 30 days? Or shall we extend heartbeat (or another cron job) to do this?

**Comment by ihcsim** [comment]
> but maybe there's a simpler, immediate solution there.

I guess this is tied to https://github.com/linkerd/linkerd2/issues/3431.

**Comment by ihcsim** [comment]
See https://github.com/linkerd/website/pull/595.
