### ISSUE TITLE
Tap pod should consider subjectAltNames

### ISSUE THREAD

**Issue by balchua** [linkerd/linkerd2#3459]
When verifying for `requestheader-allowed-names` in the tap apiserver consider `subjectAltNames` for cases when there are multiple names.

**Comment by grampelberg** [comment]
Could you explain a little more about the situation where there are multiple names in the SAN?

**Comment by balchua** [comment]
Hi sorry didn't give a bit more info here.  

For example i have `othername` in the SAN and i add it to the kube apiserver option `requestheader-allowed-names=commonname,othername` the tap pod doesn't recognize it.

Because it only checks for the allowed names in the CN.

https://github.com/linkerd/linkerd2/blob/5e51208b5deea360932bd294337683f51a4571eb/controller/tap/apiserver.go#L98

**Comment by drholmie** [comment]
Hey there! Is anyone working on this? I'm interested in helping out.

**Comment by wmorgan** [comment]
@drholmie I think it's all yours!

**Comment by drholmie** [comment]
Awesome. Thanks for the go ahead!

**Comment by javaducky** [comment]
Hope it's alright, but I noticed there hadn't been any movement on this issue for a while.  Figured I could knock it out quickly, so I threw a PR together.

**Comment by grampelberg** [comment]
Thank you @javaducky!
