### ISSUE TITLE
Add check for Tap APIService

### ISSUE THREAD

**Issue by Pothulapati** [linkerd/linkerd2#3462]
### What problem are you trying to solve?

`Linkerd check` is very useful rn as it does comprehensive tests on most of the control-plane integration points. It would be really great to have one for the `Tap APIService` too, as we have been seeing some issues around APIServices on some clusters.

### How should the problem be solved?
We may check for 

- Use k8s API and check the status of the APIService
- Talk to the APIService and see if it fails

### What do you want to happen? Add any considered drawbacks.

.. to make Linkerd check more awesome?

### Any alternatives you've considered?

Is there another way to solve this problem that isn't as good a solution?

### How would users interact with this feature?

Users can use the check command and also see the status of the APIService

**Comment by hasheddan** [comment]
Happy to take this one!

**Comment by grampelberg** [comment]
That'd be amazing!

**Comment by droidnoob** [comment]
Is @hasheddan working on it. If not I can take it up. @grampelberg

**Comment by hasheddan** [comment]
@droidnoob I fell behind on this, feel free to take this on if you have bandwidth! Thanks :)

**Comment by droidnoob** [comment]
Great. 
I'm new at this. Where do I start? 
@Pothulapati @grampelberg

**Comment by Pothulapati** [comment]
Hey @droidnoob 
Thanks for taking the effort!

The plan is to add more checks for the `healthchecker` that we already have here https://github.com/linkerd/linkerd2/blob/92532bc0b31b082be42ee035a3c4a974fa2c8693/pkg/healthcheck/healthcheck.go#L536

This turned to be a bit harder than expected, as I don't see a way to use `client-go` to get `apiregistrations.APIService`, the client is instead part of the `kube-aggregator` project. So, the clientset code has to be written like this
```diff
diff --git a/pkg/healthcheck/healthcheck.go b/pkg/healthcheck/healthcheck.go
index 21f38c27..c4c7cb9a 100644
--- a/pkg/healthcheck/healthcheck.go
+++ b/pkg/healthcheck/healthcheck.go
@@ -29,6 +29,7 @@ import (
        "k8s.io/apimachinery/pkg/runtime/schema"
        k8sVersion "k8s.io/apimachinery/pkg/version"
        "k8s.io/client-go/kubernetes"
+       apiregistrationv1client "k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1"
 )
 
 // CategoryID is an identifier for the types of health checks.
@@ -1348,6 +1349,21 @@ func (hc *HealthChecker) checkCanCreate(namespace, group, version, resource stri
        )
 }
 
+func (hc *HealthChecker) checkAPIService(name, namespace, group, version string) error {
+
+       apiServiceClient, err := apiregistrationv1client.NewForConfig(hc.kubeAPI.Config)
+       if err != nil {
+               return fmt.Errorf("unexpected error: Couldn't initialise client")
+       }
+
+       apiService, err := apiServiceClient.APIServices().Get(name, metav1.GetOptions{})
+       if err != nil {
+               return fmt.Errorf("unexpected error: Couldn't get the service")
+       }
+
+       apiService.Status
+}
+
 func (hc *HealthChecker) checkCapability(cap string) error {
        if hc.kubeAPI == nil {
                // we should never get here
```

We can use that `apiService` object and then check the status. 
One more check I wthink would be to, see if the endpoint is actually replying a 200 or not. 

Maybe @ihcsim can add more here.

Feel free to get back if you have any issues :)

**Comment by droidnoob** [comment]
Thanks for the info. @Pothulapati 
It was really helpful

**Comment by droidnoob** [comment]
@Pothulapati I have built it using the instructions in BUILD.md. The linkerd-identity pod seems to be crashed
`linkerd       linkerd-identity-684cfcb5b6-tw5xr         0/2     CrashLoopBackOff   5          4m6s`

**Comment by Pothulapati** [comment]
Hey, 
Can you jump onto the Linkerd slack, so that we can keep the issue focused to that? :)
