### ISSUE TITLE
TrafficSplit visualization

### ISSUE THREAD

**Issue by mattupstate** [linkerd/linkerd2#3465]
### What is the issue?

The visualization of network traffic does not appear to represent the actual state of the network when using a `TrafficSplit` resource.

### How can it be reproduced?

Follow the steps outlined in the [Injecting Faults](https://linkerd.io/2/tasks/fault-injection/) section of the documentation and view the resulting dashboard.

### Logs, error output, etc

A screenshot of the dashboard on my local system can be seen over at https://github.com/linkerd/website/pull/523

#### `linkerd check` output

```text
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-api
-----------
√ control plane pods are ready
√ control plane self-check
√ [kubernetes] control plane can talk to Kubernetes
√ [prometheus] control plane can talk to Prometheus
√ no invalid service profiles

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ control plane is up-to-date
√ control plane and cli versions match

Status check results are √
```

### Environment

- Kubernetes Version: 1.14.6
- Cluster Environment: Docker for Mac
- Host OS: Mac OS
- Linkerd version: stable-2.5.0

**Comment by mattupstate** [comment]
Truth!

![image](https://user-images.githubusercontent.com/166176/65475576-0a1d0480-de4e-11e9-8b58-5df5f753dcba.png)

Thanks for pointing that out.

**Comment by scottcarol** [comment]
Awesome, thanks again for filing the issue @mattupstate!
