### ISSUE TITLE
Allow trace collector address to be configured via flag or helm variable

### ISSUE THREAD

**Issue by adleong** [linkerd/linkerd2#3468]
https://github.com/linkerd/linkerd2-proxy/pull/354 added environment variables: `LINKERD2_PROXY_TRACE_COLLECTOR_SVC_ADDR` and `LINKERD2_PROXY_TRACE_COLLECTOR_SVC_NAME` which enable the Linkerd proxy to participate in traces and to emit spans to the provided collector.  We should allow these environment variables to be set from the CLI in the normal ways.

**Comment by grampelberg** [comment]
@adleong this seems like a blocker for 2.6?

**Comment by adleong** [comment]
yes, I think so

**Comment by adleong** [comment]
So far I've been testing by using manual injection and editing the output to add:

```
       - name: LINKERD2_PROXY_TRACE_COLLECTOR_SVC_NAME
          value: default.tracing.serviceaccount.identity.$(_l5d_ns).$(_l5d_trustdomain)
        - name: LINKERD2_PROXY_TRACE_COLLECTOR_SVC_ADDR
          value: oc-collector.tracing.svc.cluster.local:55678
```

**Comment by ihcsim** [comment]
With edge-19.9.3, Helm users can enable tracing by running:
```
$ helm install [--name=linkerd2] --set Proxy.Trace.CollectorSvcAddr="oc-collector.tracing.svc.cluster.local:55678" --set Proxy.Trace.CollectorSvcAccount="default.tracing" --set Identity.Issuer.CrtExpiry="<cert-expiry-date>" --set-file Identity.TrustAnchorsPEM=<path-to-trust-pem-file> --set-file Identity.Issuer.TLS.CrtPEM=<path-to-cert-pem-file> --set-file Identity.Issuer.TLS.KeyPEM=<path-to-key-pem-file> linkerd2 linkerd-edge/linkerd2
```
Notice that I have to specify the namespace of the service account, as there isn't a way to derive it from the service name. I think this is a detail we can add to the Linkerd Helm documentation.

**Comment by Pothulapati** [comment]
I'm taking this up, 

The plan is to have, `linkerd inject --proxy-collector-svc-address --proxy-collector-svc-account` flags add relevant annotations to the workloads.

**Comment by grampelberg** [comment]
@Pothulapati let's try and match the annotations:

- `--trace-collector`
- `--trace-collector-service-account`

@adleong @ihcsim any good ideas on how to move the `config.alpha.linkerd.io` space forward to the CLI arguments?
