### ISSUE TITLE
New Dashboard Sidebar: Polish and Mobile Behavior

### ISSUE THREAD

**Issue by scottcarol** [linkerd/linkerd2#3483]
#3467 redesigned the dashboard to minimize load on Prometheus.

Now that it has been merged, there are follow-up improvements that can be made:

* **Tests**: Add namespace change and rerouting to JS unit tests
* **Mobile**: Add sidebar behavior from [grampelberg mockups](https://github.com/grampelberg/linkerd2-mockups)
    * when in desktop view, sidebar is alongside content and cannot be minimized
    * when in mobile/tablet view, sidebar disappears completely
    * if hamburger menu button is clicked, sidebar appears on top of content. it disappears if you click off of it.
* **Nav**: Fix Breadcrumbs (the breadcrumbs for `/namespaces/linkerd/deployments/` reads `Namespace > linkerd > Deployment`, should read `Namespace > linkerd > Deployments`
* **Refactor**: Pull out Namespace Change Confirmation dialog into its own component

**Comment by scottcarol** [comment]
@grampelberg, @alpeb discovered interesting behavior now that a user can navigate to `/namespaces/_all`. 

The floating Network Graph displays all namespace networks and then the graphs eventually float off the page. I'll go ahead and remove the Network Graph display for `/namespaces/_all` unless you have a different preference.

<img width="344" alt="Screen Shot 2019-09-26 at 1 51 43 PM" src="https://user-images.githubusercontent.com/2289389/65724560-83db0b00-e065-11e9-869c-7d4e6713b0ed.png">

**Comment by scottcarol** [comment]
@grampelberg Just checked out your updated mockup repo. Is the new build process to navigate to `/linkerd2-mockups` and run `hugo serve -s sidebar`?

When I run that, I get the below site - it has the mobile behavior we discussed before, but I can't click on additional views, see breadcrumbs, etc., that I can see referenced in the mockup files.

![Screen Shot 2019-10-01 at 11 32 05 AM](https://user-images.githubusercontent.com/2289389/65989940-7cd64300-e43f-11e9-9da4-2f8544a9bdf4.png)

**Comment by grampelberg** [comment]
I'm experimenting with getting rid of the breadcrumb entirely. The reasoning is that the breadcrumb and header feels pretty repetitive in every treatment I've given it so far. As the sidebar does a better job of showing where you are now, it feels like we can just get rid of that.

I moved over to hugo so that there can be separate pages, there's one under `Deployments` right now that lets you get to a detail view (`/namespaces/default/deployments/emoji/`) which is closer but the header needs some love still.

There's a separate experiment around changing the table layout on that page that you should probably ignore as well.

**Comment by scottcarol** [comment]
Agree that the breadcrumbs are no longer important as links. But I still like the green horizontal bar!

Having a green horizontal bar span the full top of the browser window shows the user they're looking at Linkerd content. Otherwise it looks like we're pulling in an unrelated window and could be confusing if folks have lots of windows open.

What about, for the top-level workload list pages, display the workload title, unlinked, like this:

![Screen Shot 2019-10-01 at 12 06 04 PM](https://user-images.githubusercontent.com/2289389/65992607-5c5cb780-e444-11e9-9a17-9190a7d1f8a2.png)

and for the resource detail pages, display the resource title but delete the redundant title underneath?

![Screen Shot 2019-10-01 at 12 12 07 PM](https://user-images.githubusercontent.com/2289389/65992906-fd4b7280-e444-11e9-982d-69c5ab54bde0.png)

**Comment by grampelberg** [comment]
Those are some great points! I'm most unsure about the workload list pages right now. The sidebar does a good job of highlighting what you're looking at, but I've not actually put real data in to feel how much is missing.

On the detail page, Paul had a fantastic idea that I'm giving a try. If that doesn't work out, I think some kind of colored header will be required as the title without any visual treatment makes it feel like it is under the cards ... which is just weird.

**Comment by scottcarol** [comment]
Great, I'm interested to see Paul's idea. 

It looks like whatever happens, there will always be a sidebar that appears to the left of the main view, so I'll move forward with the mobile behavior in the mockups, and browser tests for the routing behavior.

**Comment by grampelberg** [comment]
Yup, I feel pretty good about the responsive stuff right now. If there's anything there that doesn't make sense make sure to ask!
