### ISSUE TITLE
Improve helm 3 support

### ISSUE THREAD

**Issue by pietervogelaar** [linkerd/linkerd2#3489]
### What is the issue?
The page https://linkerd.io/2/tasks/install-helm/ describes how to install linkerd with Helm 2. However Helm 3 doesn't have a `--set-file` parameter. Installing with Helm 3 work if the content of the generated certificates is put in a `values.yaml` file.

However with scripting it would be easier to pass the certificates to Helm with the `--set` parameter. The new lines in the certificates can be easily converted with `sed` to "\n" characters so that they can be set comma separated on one line.

This works for the linkerd-config ConfigMap:

```
linkerd-config ConfigMap


apiVersion: v1
data:
  global: |
    {
      "linkerdNamespace": "linkerd",
      "cniEnabled": false,
      "version": "edge-19.9.3",
      "identityContext":{
        "trustDomain": "cluster.local",
        "trustAnchorsPem": "-----BEGIN CERTIFICATE-----\nMIIBvzCCAWagAwIBAgIQYkOT+9nGIIifEKyaySGOgTAKBggqhkjOPQQDAjApMScw\nJQYDVQQDEx5pZGVudGl0eS5saW5rZXJkLmNsdXN0ZXIubG9jYWwwHhcNMTkwOTI3\nMDg0MjI3WhcNMjkwOTI0MDg0MjI3WjApMScwJQYDVQQDEx5pZGVudGl0eS5saW5r\nZXJkLmNsdXN0ZXIubG9jYWwwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAASgPlfW\n+zv357C1ly6/eaGBhz8T448JaOLWxe6oM2+VG5ACsmT2qwKOI2ITJqdwoF90AEXx\nCXIR9HDwpmFeF50so3AwbjAOBgNVHQ8BAf8EBAMCAQYwEgYDVR0TAQH/BAgwBgEB\n/wIBATAdBgNVHQ4EFgQUTO0/QCsGoa0VUx2xHQJrL2R53XswKQYDVR0RBCIwIIIe\naWRlbnRpdHkubGlua2VyZC5jbHVzdGVyLmxvY2FsMAoGCCqGSM49BAMCA0cAMEQC\nIFiUvQABeW+YzDgaGjAqoSeQCT911gibAPFHEzXkB90NAiABVAHx82uYskzwMWdJ\no7JDUgW3uMO4RzOupnUmWDTqdg==\n-----END CERTIFICATE-----",
        "issuanceLifeTime": "86400s",
        "clockSkewAllowance": "20s"
      },
      "autoInjectContext": null,
      "omitWebhookSideEffects": false,
      "clusterDomain": "cluster.local"
    }
```

But other resources, for example the linkerd-identity deployment insert this string in a multiline yaml field because of the `|` character.

```
- name: LINKERD2_PROXY_IDENTITY_TRUST_ANCHORS
          value: |
            -----BEGIN CERTIFICATE-----\nMIIBvzCCAWagAwIBAgIQYkOT+9nGIIifEKyaySGOgTAKBggqhkjOPQQDAjApMScw\nJQYDVQQDEx5pZGVudGl0eS5saW5rZXJkLmNsdXN0ZXIubG9jYWwwHhcNMTkwOTI3\nMDg0MjI3WhcNMjkwOTI0MDg0MjI3WjApMScwJQYDVQQDEx5pZGVudGl0eS5saW5r\nZXJkLmNsdXN0ZXIubG9jYWwwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAASgPlfW\n+zv357C1ly6/eaGBhz8T448JaOLWxe6oM2+VG5ACsmT2qwKOI2ITJqdwoF90AEXx\nCXIR9HDwpmFeF50so3AwbjAOBgNVHQ8BAf8EBAMCAQYwEgYDVR0TAQH/BAgwBgEB\n/wIBATAdBgNVHQ4EFgQUTO0/QCsGoa0VUx2xHQJrL2R53XswKQYDVR0RBCIwIIIe\naWRlbnRpdHkubGlua2VyZC5jbHVzdGVyLmxvY2FsMAoGCCqGSM49BAMCA0cAMEQC\nIFiUvQABeW+YzDgaGjAqoSeQCT911gibAPFHEzXkB90NAiABVAHx82uYskzwMWdJ\no7JDUgW3uMO4RzOupnUmWDTqdg==\n-----END CERTIFICATE-----
```
So the `\n` character will just be a literal string and not a real new line and this causes errors in the log about an invalid PEM format.

### Logs, error output, etc

(If the output is long, please create a [gist](https://gist.github.com/) and
paste the link here.)

#### `linkerd check` output

```text
your output here ...
```

### Environment

- Kubernetes Version:
- Cluster Environment: (GKE, AKS, kops, ...)
- Host OS:
- Linkerd version:

### Possible solution
A consistent way of handling the new lines in certificates.

**Comment by alpeb** [comment]
Thanks @pietervogelaar , this is a great point. Indeed, I haven't seen any initiatives in the Helm project regarding support for `--set-file` in v3 for now, so we'll have to work around it. 
I think we might be able to manage this easily with an extra filter in the helm templates. Will keep you posted.

**Comment by alpeb** [comment]
@pietervogelaar Good news: `--set-file` will be supported in Helm v3 after all: helm/helm#6248, so I'm closing this issue.
