### ISSUE TITLE
When calling a service using K8s injected service host and port env vars fails to register an edge

### ISSUE THREAD

**Issue by sachinkundu** [linkerd/linkerd2#3498]
### What is the issue?

I have an endpoint in serviceB which in turn calls serviceA and returns the response back. That works fine. I have an ingress route for that endpoint. When I check
```linkerd edges po -n dev```
I see an entry for ingress and serviceB but nothing for serviceB to serviceA.

### How can it be reproduced?
My code for calling serviceA from serviceB is as follows
```python
    host = os.getenv('SERVICEA_SERVICE_HOST', 'localhost')
    port = os.getenv('SERVICEA_SERVICE_PORT', 5000)
    url = f"http://{host}:{port}/getA"
    r = requests.get(url)
```
This does not work as @grampelberg reported on slack since Host header is missing in the call.

A code like
```python
    url = "http://servicea:5000/getA"
    r = requests.get(url)
```
works fine and an edge is registered.

We should either make an edge register even when using IP address or atleast provide documentation clarity that service name using DNS names is the only possible way to accomplish this.

**Comment by grampelberg** [comment]
Thank you, we've got some upcoming work that I think will help out a lot on the debugging side of things.

**Comment by grampelberg** [comment]
Tracked by #3444 .
