### ISSUE TITLE
Document control plane microservice design

### ISSUE THREAD

**Issue by briansmith** [linkerd/linkerd2#350]
At https://github.com/runconduit/conduit/blob/master/BUILD.md#components we have a diagram that shows the public API is a facade for the tap and telemetry APIs. The value of the public API facade isn't clear to me; why not just directly expose the individual microservices that are currently behind the facade?

In particular, this facade seems to get in the way of enabling fine-grained security for the public API. For example, we want to have separate permissions for the tap function and for metrics (`conduit stat` and web UI) features. Rather than having the public API implementation check "what kind of feature is this? tap? metrics? etc?" and then "does the user have access to this kind of feature" it seems cleaner to have each controller microservice (tap, metrics, etc.) just ask "does the user have access to me in general?"

In the case of tap, in particular, it seems more efficient to have network connections go from outside the cluster -> master API server -> tap server -> proxy instances without the added hop of the public API server container.

Thus, my inclination is to try to remove the public API facade. However, it isn't clear to me why we started out with implementing the public API facade so I might well be overlooking something. If we don't do the refactoring then we should document (perhaps in controller/README.md) why we designed it this way.

@adleong Could you shed some light on this?

I have the same question about the private API, though I think I know why the private API uses a facade: we want to have only one network connection between each proxy instance and the control plane. We should document this explicitly, though, because it probably isn't obvious to others. In particular, why are  the private API and the destination microservice in separate containers, instead of just having the private API container implementing the destination service internally? (I don't know the answer to the last question.)

Also, we should document why we have the control plane in one pod currently. My understanding is that we actually do want to split the control plane into multiple pods, and we plan to do so once we can do TLS mutual authentication between the separated pods. Is this correct?

Assigning to @adleong just to get the answers to the questions. Once I know the answers I'm happy to expand on them and write controller/README.md myself.

**Comment by adleong** [comment]
My understanding is that the primary reason for the public-api and proxy-api services is encapsulation: allowing us to break internal APIs (between the api components and the controller components) without breaking public APIs.  However, it seems to me that many changes that would require an internal API breakage may also require an external API breakage.  Therefore, I'm not sure that this encapsulation really buys us very much.

There may be other reasons for the current design that others can add, but I think it's totally fair to revisit this architecture and consider simplifying it.
