### ISSUE TITLE
Enable CLI to output proxy config annotations

### ISSUE THREAD

**Issue by ihcsim** [linkerd/linkerd2#3501]
Update the CLI to generate docs for the proxy config annotations. This should replace the current manual way of updating the proxy configuration documentation. The list of `config.linkerd.io` annotations can be found in `pkg/k8s/labels.go`.

Open questions:

1. Shall we implement this as a new flag? E.g.,

* `linkerd doc --config`
* `linkerd doc --proxy-config`
* `linkerd config doc # if we are going to introduce a new config command`. See https://github.com/linkerd/linkerd2/issues/3267.

**Comment by grampelberg** [comment]
Any downsides I'm not thinking of WRT updating `linkerd doc` output itself and nesting a `cli` and `annotation` section? Feels like the easiest as this is all just for internal usage anyways.

**Comment by ihcsim** [comment]
My initial thought on re-using the same `linkerd doc` command is that it will require us having to figure out where the separator between the CLI and annotation sections is. Also, the annotation partial is in HTML.

Taking a closer look at the partial, I think there is only [one line](https://github.com/linkerd/website/blob/9cfd31faf1c71d0ad76135b7340ee9925c7771cb/linkerd.io/layouts/partials/cli/annotations.html#L15) that needs to be updated, not the entire HTML. So maybe we don't need a new flag afterall.

How about something like:
```
$ linkerd doc
<YAML blob on CLI stuff>
---
# copy this to linkerd.io/layouts/partials/cli/annotations.html#L15
# {{ $labels := slice <space-delimited-config-annotations> }}
```

**Comment by grampelberg** [comment]
It is super easy to just use the data stuff in hugo to do the rendering like `{{ $labels: .... }}`. I was proposing something like:

```yaml
cliReference:
- Description: foobar
   Name: other
annotations:
- Name: config.linker.io/skip-outbound-ports
   Description: skip outbound ports
```

**Comment by ihcsim** [comment]
ah.. cool. That works :+1:! Maybe I can investigate a bit to see if we can get to something like:
```
cliReference:
- Description: foobar
  Name: other
  Annotation: config.linkerd.io/other
- Description: foobar
  Name: skip-outbound-port
  Annotation: config.linkerd.io/skip-outbound-port
```

**Comment by joshuabezaleel** [comment]
Hi @grampelberg @ihcsim , do you have any recommendation on where should I start looking if I am interested in this issue?
Thank you very much! :slightly_smiling_face:

**Comment by ihcsim** [comment]
@joshuabezaleel Thanks! Much appreciated! If you run the `linkerd doc` command, you will see that it returns a blob of YAML. We use this YAML to update our [CLI docs](https://linkerd.io/2/reference/cli/), by copying the content to this [`cli.yaml`](https://github.com/linkerd/website/tree/master/linkerd.io/data) file. 
The code for the `linkerd doc` command is in `cli/cmd/doc.go`. 

The goal of this issue is to update the YAML blob to include the proxy config annotations listed in [`pkg/k8s/labels.go`](https://github.com/linkerd/linkerd2/blob/66e82de19047ebb2accffc7cf00294f73f9a2391/pkg/k8s/labels.go#L94-L180). Once the `doc` code is updated, you will need to update the hugo partial [`annotations.html](https://github.com/linkerd/website/blob/a8d0483c529fe6c3adafe9aa7ae01c7f37720080/linkerd.io/layouts/partials/cli/annotations.html#L14-L15) file to make sure the new YAML is rendered. The format suggested by @grampelberg in https://github.com/linkerd/linkerd2/issues/3501#issuecomment-536782688 makes sense.

Essentially, you will be submitting one PR to this repo, and the other to the linkerd/website repo.

WDYT?

PS I heard that @grampelberg loves sending out swags to new contributors :wink:.
