### ISSUE TITLE
Option to skip load balancing on ingress proxies

### ISSUE THREAD

**Issue by pietervogelaar** [linkerd/linkerd2#3504]
## Feature Request
Option to skip load balancing on ingress proxies.

### What problem are you trying to solve?
I have Ambassador running as ingress controller and Linkerd as service mesh. To make it possible that Ambassador can communicate mTLS with services in the Kubernetes cluster, the Ambassador pods must also be meshed (get a linkerd sidecar proxy injected).

Ambassador has several load balancing capabilities, including sticky sessions / session affinity. https://www.getambassador.io/reference/core/load-balancer/#sticky-sessions--session-affinity. However by meshing the ambassador pod the actual load balancer will be linkerd. So the sticky sessions of ambassador won't work anymore.

### How should the problem be solved?
Add a header that tells linkerd to skip its normal load balancing and to only use the endpoint ambassador chose.

### Any alternatives you've considered?

An alternative would be to not mesh Ambassador and make the generated certificates (https://linkerd.io/2/tasks/generate-certificates/) available to Ambassador. I tried this, but I didn't get working connections.

### How would users interact with this feature?

Setting a pod annotation.

**Comment by pietervogelaar** [comment]
@olix0r Do you have an idea when this will become available?

**Comment by mritd** [comment]
Is there any progress? 
I am thinking about using linkerd and istio; session affinity is used in our project.but linkerd is a CNCF project, I tend to use linkerd. 😂

**Comment by grampelberg** [comment]
@mritd there is not currently anyone working on it right now.

**Comment by wmorgan** [comment]
@mritd @pietervogelaar would you like to contribute this feature? 😅

**Comment by olix0r** [comment]
@mritd @pietervogelaar Sorry for the silence on this! I totally agree that this is reasonable feature request. We have some upcoming changes to linkerd's mTLS logic so that we don't need services to initiate mTLS. It seems likely that, once these changes land, you can accomplish what you're looking for with very little configuration. We expect this feature in 2.8; so we'll update this issue once we have something that you can test!

**Comment by mritd** [comment]
@olix0r Thanks for your reply, I am looking forward to the 2.8 release 😀

**Comment by vijaygos** [comment]
@olix0r , any update on this feature request?

**Comment by benpettman** [comment]
+1 for this feature, whats the status?

**Comment by mschweiker** [comment]
+1 also.

**Comment by dschuldt** [comment]
+1

**Comment by ihcsim** [comment]
Per https://github.com/linkerd/linkerd2/issues/4956#issuecomment-690781453, the ongoing discovery changes for 2.9 should make this work. Keep an eye out for the upcoming edge releases; will appreciate some help with testing this.

**Comment by benpettman** [comment]
Any news on this being resolved in 2.9?

**Comment by grampelberg** [comment]
@benpettman I wouldn't count on it, we're mostly feature complete at this point. The discovery changes definitely make it easier to implement now though!

**Comment by olix0r** [comment]
With the [edge-20.10.3](https://github.com/linkerd/linkerd2/releases/tag/edge-20.10.3) release, the proxy now only applies load balancing logic when traffic targets the service IP. if the ingress targets a pod, the proxy will not override the balancer.

I'm going to close this on the assumption that this satisfies the use case, but please let us know if you run into any problems!

**Comment by benpettman** [comment]
So does this mean we can inject the ingress now and use the SMI spec to traffic split?
