### ISSUE TITLE
Eliminate metrics collected by controller/util/prometheus.go that duplicate proxy-provided metrics

### ISSUE THREAD

**Issue by briansmith** [linkerd/linkerd2#351]
This is a follow-up to #311. Every control plane container currently exposes a metrics port. AFAICT most controller components, except the telemetry component, actually don't provide any metrics beyond what the proxy can automatically provide. That means we can remove from all other components:

* The `admin-http` port (see install.go)
* The `-metrics-addr` command line parameter in each main.go
* The goroutine that looks like this, in each main.go:
```go
	go func() {
		log.Infof("serving scrapable metrics on %+v", *metricsAddr)
		http.Handle("/metrics", promhttp.Handler())
		http.ListenAndServe(*metricsAddr, nil)
	}()
```
* The special-case handling of the control plane metrics in .prometheus.dev.yml. (Maybe we can remove .prometheus.dev.yml completely?)
* Most or all of controller/util/prometheus.go.

/cc @adleong

**Comment by adleong** [comment]
This sounds like a good idea.  A couple of gotchas to watch out for come to mind:

* All data plane reports will go through the controller's sidecar proxy.  However, reports from the controller's sidecar proxy must go directly to the controller to avoid an infinite loop.
* This means that metrics about the controller will not include report requests generated by the controller's sidecar, even though those are real requests being processed by the controller.  This will lead to, for example, a slight undercounting of requests to the controller.

**Comment by briansmith** [comment]
We should do this after #353 and after the questions in #354 are answered. In particular it is important to use localhost internally in the controller but that might mean that we can't rely on the proxy to provide metrics for connections between controller components if the answers I anticipate getting in #354 are correct.

**Comment by briansmith** [comment]
> but that might mean that we can't rely on the proxy to provide metrics for connections between controller components if the answers I anticipate getting in #354 are correct.

Based on what @adleong said in https://github.com/runconduit/conduit/issues/350#issuecomment-365497855 I think we might refactor the control plane so that there is less internal networking. With that in mind, I don't think we should be concerned if we lose some metrics for the internal networking in the controller. Especially it would be OK to *temporarily* lose those metrics, I think. So I don't think there are any concerns stopping us from doing this now.

**Comment by dadjeibaah** [comment]
@briansmith based on the conversation in #228, it looks as if we do need to have every controller component exposing prometheus metrics. Is it safe to mark this issue as closed?

**Comment by briansmith** [comment]
@dadjeibaah Definitely things are at least slightly different than what I expected when I filed this issue. I think it would be good to use the proxy's telemetry logic everywhere we can reasonably do so.
It isn't a high priority as it isn't even scheduled for a milestone. How about you assign it to me and I'll deal with this when I have time.

**Comment by klingerf** [comment]
@briansmith I'm inclined to close this issue, since we now surface go process stats from the control plane components in the "Conduit Health" Grafana dashboard. I don't think we'll ever report goroutines or other go-specific metrics via the proxy. Does that work for you?

**Comment by klingerf** [comment]
Ah, yes, you're right that the three `http_*` metrics provided by `prometheus.WithTelemetry` are duplicated by the proxy, but the control plane components also export a bunch of metrics related to the go runtime, which aren't duplicated by the proxy. For instance:

![image](https://user-images.githubusercontent.com/9226/40693807-42eecc96-636e-11e8-9cca-7ef0b285116e.png)

The Conduit Health dashboard relies on these metrics to capture the health of the control plane. So this assumption from the issue description isn't correct:

> AFAICT most controller components, except the telemetry component, actually don't provide any metrics beyond what the proxy can automatically provide.

We still need each of the controller components to run an admin metrics server to export their runtime metrics. I don't mind removing the `http_*` metrics, but I don't want to remove the admin servers altogether and lose visibility into the control plane's runtime performance.

**Comment by briansmith** [comment]
> I don't mind removing the http_* metrics, but I don't want to remove the admin servers altogether and lose visibility into the control plane's runtime performance.

I agree. I reworded the title of this issue to reduce its scope. I'm only proposing to eliminate duplication, not to eliminate any metrics that aren't already provided by the Conduit proxy.
