### ISSUE TITLE
Edges for TCP and out of mesh communication

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#3523]
### What problem are you trying to solve?

I would like to know what communication has been encrypted (or not) at the TCP level for resources that are inside the mesh and outside the mesh. This will primarily be used to audit the state of my cluster and reason about what is happening with it.

### How should the problem be solved?

```bash
$ linkerd -n emojivoto edges -o json | jq .
[
   {
      "src": {
         "ip": "10.0.0.1",
         "resource": {
            "apiVersion": "v1",
            "kind": "pod",
            "name": "web-56955474f7-hsqnn",
            "namespace": "emojivoto"
         }
      },
      "dst": {
         "ip": "10.0.0.2",
         "port": 8080,
         "resource": {
            "apiVersion": "v1",
            "kind": "pod",
            "name": "emoji-596866d567-6wl6s",
            "namespace": "emojivoto"
         }
      },
      "metadata": {
         "labels": {
            "authority": "emoji-svc.emojivoto.svc.cluster.local:8080",
            "client_id": "web.emojivoto.serviceaccount.identity.linkerd.cluster.local"
         }
      },
      "tls": true,
      "classification": "internal"
   },
   {
      "src": {
         "ip": "10.0.0.3",
         "resource": {
            "apiVersion": "v1",
            "kind": "pod",
            "name": "nginx-nginx-ingress-controller-5966b7db6d-8ndfh",
            "namespace": "nginx"
         }
      },
      "dst": {
         "ip": "10.0.0.1",
         "port": 80,
         "resource": {
            "apiVersion": "v1",
            "kind": "pod",
            "name": "web-56955474f7-hsqnn",
            "namespace": "emojivoto"
         }
      },
      "metadata": {
         "labels": {
            "authority": "web-svc.emojivoto.svc.cluster.local:80",
            "client_id": "nginx.nginx.serviceaccount.identity.linkerd.cluster.local"
         }
      },
      "tls": true,
      "classification": "internal"
   },
   {
      "src": {
         "ip": "1.1.1.1"
      },
      "dst": {
         "ip": "10.0.0.2",
         "port": 8080,
         "resource": {
            "apiVersion": "v1",
            "kind": "pod",
            "name": "emoji-596866d567-6wl6s",
            "namespace": "emojivoto"
         }
      },
      "metadata": {
         "labels": {
            "authority": "emoji.example.com"
         }
      },
      "tls": false,
      "classification": "ingress"
   },
   {
      "src": {
         "ip": "10.0.0.2",
         "resource": {
            "apiVersion": "v1",
            "kind": "pod",
            "name": "emoji-596866d567-6wl6s",
            "namespace": "emojivoto"
         }
      },
      "dst": {
         "ip": "10.0.0.6",
         "port": 44134,
         "resource": {
            "apiVersion": "v1",
            "kind": "pod",
            "name": "tiller-deploy-7f4d76c4b6-gldnc",
            "namespace": "kube-system"
         }
      },
      "metadata": {
         "labels": {
            "authority": "tiller-deploy.kube-system"
         }
      },
      "tls": false,
      "classification": "egress"
   },
   {
      "src": {
         "ip": "10.0.0.1",
         "resource": {
            "apiVersion": "v1",
            "kind": "pod",
            "name": "web-56955474f7-hsqnn",
            "namespace": "emojivoto"
         }
      },
      "dst": {
         "ip": "140.82.114.3",
         "port": 443
      },
      "tls": true,
      "classification": "egress"
   }
]
```

- `ip` is required for both src and dst
- `port` is required for dst
- `resource` is optional for src and dst
- `tls` is true for streams that are encrypted by something other than Linkerd as well as inter-mesh mTLS'd communication
- `classification` allows for internal, ingress and egress. The ingress and egress terms are for the mesh and not the cluster itself.

Some reasoning:

- `service` is not here as it is interesting but not really part of an edge explicitly.
- Identity is not a part of this output specifically, it can be looked up and might be worth adding in the future.
- `port` is left off `src` because it isn't particularly useful to anyone.

### Out of scope

- Any idea of aggregation or parent objects is out of scope. This is all about individual connections.

**Comment by grampelberg** [comment]
@olix0r ^^

**Comment by adleong** [comment]
Will this replace the existing `edges` command which can display edges between resources, such as:

```
$ linkerd edges -n emojivoto deploy -o json
[
  {
    "src": "vote-bot",
    "src_namespace": "emojivoto",
    "dst": "web",
    "dst_namespace": "emojivoto",
    "client_id": "default.emojivoto",
    "server_id": "web.emojivoto",
    "no_tls_reason": ""
  },
  {
    "src": "web",
    "src_namespace": "emojivoto",
    "dst": "emoji",
    "dst_namespace": "emojivoto",
    "client_id": "web.emojivoto",
    "server_id": "emoji.emojivoto",
    "no_tls_reason": ""
  },
  {
    "src": "web",
    "src_namespace": "emojivoto",
    "dst": "voting",
    "dst_namespace": "emojivoto",
    "client_id": "web.emojivoto",
    "server_id": "voting.emojivoto",
    "no_tls_reason": ""
  }
]
```

and move the edges command to be entirely connection based?

**Comment by grampelberg** [comment]
@adleong that's my thinking (assuming we're on the same page by what you mean wrt "connection"). It was the original intent of `edges`. Is there a reason to keep the current behavior?

**Comment by adleong** [comment]
:+1: Fully replacing the existing behavior sounds good to me.

**Comment by adleong** [comment]
Should `src` and `dst` have a boolean `meshed` field?  This is redundant with the `classification` field: ingress means src is meshed, egress means dst is meshed, internal means both are meshed.  But it might be more clear?  Also I'd hesitate to use the word "classification" since we use that word usually in the context of response classification.

Should source id and dst id be part of the `src` and `dst` structs instead of in the metadata?  

There is no authority for tcp connections.

Should each edge have a protocol field which can be either `http` or `tcp`?

**Comment by adleong** [comment]
Taking a stab at the proxy metrics needed to support this:

## Example

```
inbound_connection_opens{src_addr="1.2.3.4:54321", src_identity="web.default.serviceaccount.linkerd.svc.cluster.local", tls="true", protocol="tcp"} 11
inbound_connection_closes{src_addr="1.2.3.4:54321", src_identity="web.default.serviceaccount.linkerd.svc.cluster.local", tls="true", protocol="tcp"} 10
outbound_connection_opens{dst_addr="5.6.7.8:8080", dst_identity="books.default.serviceaccount.linkerd.svc.cluster.local", tls="true", protocol="tcp"} 11
outbound_connection_closes{dst_addr="5.6.7.8:8080", dst_identity="books.default.serviceaccount.linkerd.svc.cluster.local", tls="true", protocol="tcp"} 10
```

## Metrics

`inbound_connection_opens`: A counter of the connections established between a remote (non-localhost) peer and the inbound proxy.  

`inbound_connection_closes`: A counter of the connections closed between a remote (non-localhost) peer and the inbound proxy.  

The difference between these two counters gives the number of open connections.

#### Labels
* `src_addr`: the socket address of the remote peer
* `src_identity`: the TLS identity that the remote provided during TLS handshake, if applicable
* `tls`: boolean indicating if the connection was established with TLS
* `protocol`: the detected protocol: tcp or http

`outbound_connection_opens`: A counter of the connections established between the outbound proxy and a remote (non-localhost) peer.  
`outbound_connection_closes`: A counter of the connections closed between the outbound proxy and a remote (non-localhost) peer.  

#### Labels
* `dst_addr`: the socket address of the remote peer.  this is either retrieved from the destination service, or is the SO_ORIG_DST.
* `dst_identity`: the TLS identity of the remote, if applicable.
* `tls`: boolean indicating if the connection was established with TLS
* `protocol`: the detected protocol: tcp or http

Note that only server connections are reported by the inbound proxy and only client connection are reported by the outbound proxy.  Connections between the Linkerd proxy and the pod-local application are NOT represented here.

## Queries

To find ingress edges: `inbound_connection_opens{src_id!~"serviceaccount\.identity\.linkerd\.cluster\.local$"} by (src_addr, src_identity, tls, protocol)`

To find egress edges: `outbound_connection_opens{dst_id!~"serviceaccount\.identity\.linkerd\.cluster\.local$"} by (dst_addr, dst_identity, tls, protocol)`

To find internal edges: `outbound_connection_opens{dst_id=~"serviceaccount\.identity\.linkerd\.cluster\.local$"} by (dst_addr, dst_identity, tls, protocol)`

## Cardinality

Each proxy will add 2 timeseries per incoming connection and 2 time series per outgoing connection.  Hypothetically, this means the number of time series in total could be `O(N^2)` where `N` is the number of pods in the cluster if every pod connects to every other pod.  However, let us consider a slightly more realistic scenario.

Suppose we have a cluster with 100 services, each with 10 replicas, for a total of 1000 pods.  Let us assume that each service has 5 upstream services and 5 downstream services.  This means that each pod has 50 incoming connections and 50 outgoing connections.  This results in 200 time series per pod which adds up to 200000 timeseries total across the cluster.

**Comment by grampelberg** [comment]
As I understand it, this would have the implication of not providing any metrics for these (TCP bytes, requests) and simply tell the state of the edge and the number of outstanding connections? How does this play with http/2?

## inbound_connection

There should be a `dst_addr` label. Technically, I'm really just interested in the port. It just seems easier to keep the same format.

## outbound_connection

- Does it make sense to add a `src_identity` label here? It would prevent the requirement to do a join with inbound_connection on internal edges.
- Should we have a label that differentiates between SO_ORIGINAL_DST and what destination resolved to?

**Comment by grampelberg** [comment]
Hopefully tackling this as part of the auditing work later this year.
