### ISSUE TITLE
Require valid mTLS for communication to containers in the pod

### ISSUE THREAD

**Issue by jonrichards** [linkerd/linkerd2#3532]
### What problem are you trying to solve?

Currently, the `linkerd2-proxy` will fall back to plaintext if communication requests are initiated via plaintext. While this is needed for metrics, liveliness checks, readiness checks, etc..., it also means containers that require callers to use secure communication only can be called via plaintext.

Additionally, if no cert or an invalid cert is presented/served, the `linkerd2-proxy` will pass through the communication to containers in the pod.

### How should the problem be solved?

The `linkerd2-proxy` should have an option to require mTLS for container communication and reject plaintext requests. Other requests to the proxy itself may be plaintext. Note: communication *inside* the pod are understood to be plaintext and out of scope.

The `linkerd2-proxy` should block communication when no cert or an invalid cert is presented/served.

### Any alternatives you've considered?

I wasn't able to come up with good alternatives to achieve this.

### How would users interact with this feature?

I think the best option would be via a special annotation. That would allow granularity for having pods that require mTLS, and others that are ok with being optional mTLS. An all or nothing install flag seems too rigid.

**Comment by olix0r** [comment]
I don't think such a simple policy would be feasible, as this would immediately break health/readiness probes, etc. AFAIK the proxy has no way to differentiate this traffic from other application traffic. I think we basically _have to_ target a policy spec (like that in SMI), rather than rely on pod annotations...
