### ISSUE TITLE
SplitTraffic UI looks cluttered and unclear

### ISSUE THREAD

**Issue by hollinwilkins** [linkerd/linkerd2#3538]
## Feature Request

When creating SplitTraffic resources (in this case for Canary deploys w/ Flagger), all services that are split get added to the "Overview" UI for deployments. I have attached a screenshot to illustrate this point.

In this case, we are looking at 3 services:
1. crasample
2. sesamestreet
3. sesamestreet-frontend

sesamestreet-frontend talks to sesamestreet, while crasample is entirely its own service that has nothing to do with sesamestreet.

When looking at the "deployment/sesamestreet" page though, the UI is littered with SplitTraffic boxes from/to crasample.

<img width="958" alt="Screen Shot 2019-10-07 at 11 14 06 AM" src="https://user-images.githubusercontent.com/15824835/66343157-de932300-e8ff-11e9-9650-58a5d20af9da.png">

### What problem are you trying to solve?

SplitTraffic services that have no traffic to another service should not show up in the UI when looking at the deployment.

### How should the problem be solved?

Only display SplitTraffic UI on pages with related services.

What do you want to happen? Add any considered drawbacks.

### Any alternatives you've considered?

Is there another way to solve this problem that isn't as good a solution?

### How would users interact with this feature?

If you can, explain how users will be able to use this. Maybe some sample CLI
output?

**Comment by grampelberg** [comment]
What version are you running? This sounds a lot like #3465.

**Comment by grampelberg** [comment]
Closing out as a dup of #3465 for now, please reopen if that isn't the case.
