### ISSUE TITLE
Document the proxy's behavior w.r.t. localhost/loopback/127.0.0.1/::1

### ISSUE THREAD

**Issue by briansmith** [linkerd/linkerd2#354]
IIUC, the iptables rules have at least one special exception for loopback interfaces where the proxy won't intercept a connections that involve loopback addresses. I see a test for one case, "connecting to loopback from non-proxy container does not get redirected to proxy." However, in general it isn't clear what the expected behavior w.r.t. loopback addresses is supposed to be:

@pcalcado:

* By default, when will the proxy avoid intercepting a request from outside the pod to a loopback address?
* By default, when will the proxy avoid intercepting a request from inside the pod to a loopback address?
* What features are provided to control whether the proxy will intercept requests between containers in the same pod communicating over a loopback address?

Similarly, it isn't clear how service discovery works w.r.t. these names and addresses:

@seanmonstar:

* Does the proxy implement the special-case logic for "localhost" and "*.localhost" and "*.localhost." names to avoid contacting the Destination service?
* Does the proxy implement special-case logic for "127.0.0.1" and "::1" to avoid contacting the Destination service?

It is important for security and performance reasons that we don't do service discovery for these names and addresses because applications use these names to ensure that they'll never do network traffic outside their node/pod, so it's important to verify that we're not doing so and document that that is the case.

**Comment by seanmonstar** [comment]
I'm not aware of any special casing in the proxy itself around the handling of `localhost` or loopback IP addresses.

**Comment by adleong** [comment]
I think a README.md in https://github.com/runconduit/conduit/tree/master/proxy-init would be a good place to document the iptables behaviors that proxy-init configures.

**Comment by briansmith** [comment]
> I'm not aware of any special casing in the proxy itself around the handling of localhost or loopback IP addresses.

I filed #358 and #359 to fix this.

**Comment by briansmith** [comment]
@pcalcado Could you please describe how the proxy-init container is designed to work w.r.t. loopback/localhost. Is it simply that it tries to bypass the proxy for all localhost traffic? And, there's no way to change this, right? I am planning to write the user-facing documentation for this as part of the service discovery doc, and it would be useful to better understand these details of proxy-init.
