### ISSUE TITLE
RFC: conduit get spec

### ISSUE THREAD

**Issue by pcalcado** [linkerd/linkerd2#355]
## Narrative
So that I can see what is in and out of my service mesh
As an operator
I want the "conduit get" command to return an overview of what's in the service mesh

## Rationale
The service mesh is a network layer that materializes many features and patterns previously spread across client libraries and specialized middleware. It allows for operators and developers to think of these previously fragmented features as a single object they can see and manage as a cohesive component.

 To support this abstraction, Conduit offers support to inspect the service mesh. In the command line user experience, this is implemented via the `get` command.

`conduit get` can be used to return the status of pods with regards to pariticpation in the service mesh.
 

### Use Case: Inspect the service mesh
The most common use case will show all pods across all namespaces that have joined the service mesh. The `Ok` status here, for now, indicates that this component is part of the service mesh. In the future, this field will also contain at-a-glance information about the health of the component.
 

```shell
$ conduit get
NAMESPACE  DEPLOYMENT                     POD                                   STATUS
smoke-test smoke-test/smoke-test-gateway  smoke-test-gateway-11117695bf-mzvn7   Ok
smoke-test smoke-test/smoke-test-gateway  smoke-test-gateway-22227695bf-mzvn7   Ok
smoke-test smoke-test/smoke-test-gateway  smoke-test-gateway-33337695bf-mzvn7   Ok
smoke-test smoke-test/smoke-test-terminus smoke-test-terminus-aaaa97df8c-8ptnv  Ok
smoke-test smoke-test/smoke-test-terminus smoke-test-terminus-bbbb97df8c-8ptnv  Ok
```

This can be also filtered by a specific namespace:
```shell
$ conduit get ns smoke-test
POD                                  STATUS
smoke-test-gateway-11117695bf-mzvn7  Ok
smoke-test-gateway-22227695bf-mzvn7  Ok
smoke-test-gateway-33337695bf-mzvn7  Ok
```

### Use Case: Detecting when a component should be in the mesh but wasn't added by operator mistake
Another common use case is when the operator sees some unexpected behaviour in their service mesh. The first step one would take is to get a high-level view of all pods in their namespace, and which pods might have not be currently in the mesh due to an operator mistake or similar.

Using `conduit get --all` they can quickly see what pods are in or out. 

```shell
$ conduit get
NAMESPACE     DEPLOYMENT                                POD                                   STATUS
smoke-test    smoke-test/smoke-test-gateway          smoke-test-gateway-11117695bf-mzvn7   Ok
smoke-test    smoke-test/smoke-test-gateway          smoke-test-gateway-22227695bf-mzvn7   Ok
smoke-test    smoke-test/smoke-test-gateway          smoke-test-gateway-33337695bf-mzvn7   Ok
smoke-test    smoke-test/smoke-test-terminus         smoke-test-terminus-aaaa97df8c-8ptnv  Ok
smoke-test    smoke-test/smoke-test-terminus         smoke-test-terminus-bbbb97df8c-8ptnv  Ok
smoke-test    smoke-test/smoke-test-other            smoke-test-gateway-33337695bf-abcss   Not in Mesh
smoke-test    smoke-test/smoke-test-other            smoke-test-gateway-33337695bf-grdsa   Not in Mesh
conduit       n/a                                    controller-684fc84647-s7dln           Not in Mesh
conduit       n/a                                    prometheus-6c648745d5-q9r9q           Not in Mesh
conduit       n/a                                    web-8458cf586-vf7mr                   Not in Mesh
kube-system   n/a                                    default-http-backend-8wrn4            Not in Mesh
kube-system   n/a                                    kube-addon-manager-minikube           Not in Mesh
kube-system   n/a                                    kube-dns-54cccfbdf8-sxmsl             Not in Mesh
kube-system   n/a                                    kubernetes-dashboard-77d8b98585-7gtvt Not in Mesh
kube-system   n/a                                    nginx-ingress-controller-g2x6t        Not in Mesh
kube-system   n/a                                    storage-provisioner                   Not in Mesh
smoke-test    n/a                                    smoke-test-gateway-7c747695bf-mzvn7   Not in Mesh
smoke-test    n/a                                    smoke-test-terminus-58fb97df8c-8ptnv  Not in Mesh
```

They will likely prefer to limit the query to a namespace.

```shell
$ conduit get ns smoke-test --all
POD                                  STATUS
smoke-test-gateway-11117695bf-mzvn7  Ok
smoke-test-gateway-22227695bf-mzvn7  Ok
smoke-test-gateway-33337695bf-mzvn7  Ok
smoke-test-gateway-33337695bf-abcss  Not in Mesh
smoke-test-gateway-33337695bf-grdsa  Not in Mesh
```

For completeness' sake, tney can also use the `--not` switch and only lists pods that are not part of the mesh.

```shell
$ conduit get ns smoke-test --not
POD                                  STATUS
smoke-test-gateway-33337695bf-abcss  Not in Mesh
smoke-test-gateway-33337695bf-grdsa  Not in Mesh
```

### Error scenarios

When the desired object can't be accessed (either because it doesn't exist or some authorization constraint), print an error message and return a code different from zero.
```shell
$ conduit get ns doesnt-exist
Namespace [doesnt-exitst] doesn't exist or can't be accessed by Conduit. 
```

### Open questions
- Once the user has found a pod out of the mesh, how do they add it?
- What to do with pods without deployments?
- What is a useful health check?
- Considering that one-namespace-per-service is a common k8s usage pattern, should we allow for many namespaces in the query?

**Comment by pcalcado** [comment]
On 02/07/2018 @adleong said:
---
By my reading, this makes `conduit get` the CLI equivalent of the `service mesh overview` page in the Conduit dashboard.  This makes perfect sense to me.  What I think would be convenient is a `summary` mode (probably the default) which outputs one line per deployment and indicates how many pods are in the mesh.  e.g.

```
NAMESPACE     DEPLOYMENT                                PODS ADDED
smoke-test    smoke-test/smoke-test-gateway          2/3
```

And additionally have an `expanded` mode which lists out each pod on its own line.

* Once the user has found a pod out of the mesh, how do they add it?
  * We could include the `conduit inject` call to action in the CLI output, potentially... though this might make the CLI command less useful as a script component...
* What to do with pods without deployments?
  * We already assume in Conduit that there are no "naked pods".  ie that every pod has an owner (deployment, job, daemonset, replicaset, or replicationcontroller)
* What is a useful health check?
  * The service mesh overview page uses telemetry reports as indicators of health
* Considering that one-namespace-per-service is a common k8s usage pattern, should we allow for many namespaces in the query?
  * 🤷‍♂️ what does kubectl do?

**Comment by pcalcado** [comment]
On 02/07/1028 @briansmith said:
---
I think it would be OK to just have users use the web UI for this, given the use cases mentioned above.

**Comment by wmorgan** [comment]
I like this feature. Generally speaking I think it's important to have parity between CLI and GUI, and if anything I would prefer to iterate on the CLI first and then "catch up" with the GUI.

In terms of the details, I would want to ensure that a) the command "feels" like kubectl, e.g. takes namespace arguments in the same way, etc.; and b) the command "feels" UNIX-y, i.e. has line-oriented output that's easily composable with other commandline tools, handles return codes correctly, etc.

How do you want to iterate on this proposal?

**Comment by pcalcado** [comment]
@wmorgan 

> Generally speaking I think it's important to have parity between CLI and GUI, and if anything I would prefer to iterate on the CLI first and then "catch up" with the GUI.

I like this very much adn would like to have it as a core tenet for Conduit. The low-detail aspect of CLI make it possible to iterate quickly on features that can be available super soon while we iterate on the harder aspects of a GUI.

> How do you want to iterate on this proposal?

It seems like this has gotten enough eyes already, so I am going to slice it into smaller, end-to-end stories. I propose we deal with this as a project. Thoughts?

**Comment by grampelberg** [comment]
I like this, pretty good parallel between the UI and kubectl. I'm not sure what the right data to show is (outside of just blatantly copying the dashboard).
