### ISSUE TITLE
Extend the CLI to support cert-manager CA issuer

### ISSUE THREAD

**Issue by ihcsim** [linkerd/linkerd2#3556]
To enable cert-manager to manage the `linkerd-identity-issuer` secret, a new CLI option needs to be added to the `install` command to omit the YAML of the `linkerd-identity-issuer` secret.

This issue adds a new flag named `--identity-external-issuer` to the `install` command:

|      |    values  
| -----------------------  | ----------------------------
| Name                    |  `--identity-external-issuer`
| Supported values  | `true`, `false`
| Default                   | `false`
| Flagset                  | `recordable`
| Description            | Set to `true` when integrating with an external Kubernetes CA controller like cert-manager. In the `true` mode, Linkerd will not auto-generate an internal trust anchor nor issuer key/cert pair.
| Helm variable        | `{{ .Identity.Issuer.External }}`

Usage:
```bash
linkerd install --identity-external-issuer=[true|false] --identity-trust-anchors-file=<path-to-ca-pem> [--identity-trust-domain=<trust-domain>]
```

The above command will output the YAML manifest of all the control plane components and resources, except for the `linkerd-identity-issuer` secret. It should fail if the Linkerd namespace, `linkerd-identity-issuer` secret or trust anchor don't exist, unless the `--ignore-cluster` option is provided.

The trust anchor and issuer key/cert should be [verified](https://github.com/linkerd/linkerd2/blob/cf69dedf9caaebb73f65709e8ac5668fdd9d97ac/controller/cmd/identity/main.go#L68-L79) as part of the installation process. In addition, the issuer certificate expiry date should also be [validated](https://github.com/linkerd/linkerd2/blob/cf69dedf9caaebb73f65709e8ac5668fdd9d97ac/pkg/tls/ca.go#L252).

In the `--identity-external-issuer=true` mode, specifying the following CLI options will result in an error:
```
--identity-issuer-certificate-file string
--identity-issuer-key-file string
```

Ensure that the value of the `--identity-external-issuer` option is persisted across versions upgrade, by adding the option to the `recordable` flagset.

Pending questions:

1. Shall we fail the certificate validation (and the installation process) if the certificate's expiry date is less than say 30 days away?
1. How should we provide the trust anchor to the `install` command. Is there a way to partially fetch the `ca` data from the `linkerd-identity-issuer` secret generated by cert-manager? Or shall we just use the existin `--identity-trust-anchors-file` option?

**Comment by ihcsim** [comment]
@zaharidichev I'm assigning this to you, since you already started #3552.

**Comment by zaharidichev** [comment]
> How should we provide the trust anchor to the install command. Is there a way to partially fetch the ca data from the linkerd-identity-issuer secret generated by cert-manager? Or shall we just use the existing --identity-trust-anchors-file option?

So I looked a bit into that and I cant see a way to partially fetch just selected keys from a secret's data while omitting the rest. Are we completely against the option of fetching the whole secret? I mean, after all we check for its existence beforehand, which is either a `get` or a `list` call, which means that the content of the secret will be transferred to anyway, If we are willing to use them we can skip the part of requiring `--identity-trust-anchors-file` as this data is in the issuer secret already. 

Additionally on the proxy side, because we have the trust anchors in the issuer secret, we can just mount that secret and read the contents of the trust anchor into the respective env var and skip the part where we write the anchor directly into the yaml.  

Might be missing something. How does that sound @ihcsim

**Comment by grampelberg** [comment]
> Are we completely against the option of fetching the whole secret?

I'm good with fetching the whole secret as it is no worse than what we're doing today.

> we can just mount that secret and read the contents of the trust anchor into the respective env var

This will only work for the control plane as secrets are namespace scoped. Feels like this is okay as most will go through the proxy-injector. What about `inject --manual`? We definitely don't want everyone adding linkerd to their workload having read access to the identity secret.

**Comment by ihcsim** [comment]
> This will only work for the control plane as secrets are namespace scoped. Feels like this is okay as most will go through the proxy-injector.

The proxy spec is shared between the control plane components and user's workloads. I'm not a fan of rendering different proxy YAML for the control plane and user data plane.

> I'm good with fetching the whole secret as it is no worse than what we're doing today.

Yeah, if we want to do a pre-install check either with the `install` or `check --pre` command, we will need to do a `GET` somehow. So far, fetching the secret through the API will always result in decrypted content being returned, even with [encryption at rest](https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/) (which of course, is outside of our scope).

**Comment by zaharidichev** [comment]
> This will only work for the control plane as secrets are namespace scoped. Feels like this is okay as most will go through the proxy-injector. What about inject --manual? We definitely don't want everyone adding linkerd to their workload having read access to the identity secret.

> The proxy spec is shared between the control plane components and user's workloads. I'm not a fan of rendering different proxy YAML for the control plane and user data plane.


Yeah, very good points. Thanks for bringing these up!

**Comment by ihcsim** [comment]
Fixed under https://github.com/linkerd/linkerd2/pull/3600.
