### ISSUE TITLE
Auto-update the identity service's issuer key/cert pair

### ISSUE THREAD

**Issue by ihcsim** [linkerd/linkerd2#3557]
The `identity` component should be updated to watch for changes to its issuer key/cert pairs located at the default location of `/var/run/linkerd/identity/issuer`. When these assets are changed, the identity component should ensure that the new certificate:

1. Hasn't or about to expire
1. Remains valid with the trust anchor

And then reload them without needing a re-deployment.

**Comment by zaharidichev** [comment]
@ihcsim Already started digging into that, so you can assign it to me as well

**Comment by ihcsim** [comment]
Fixed under https://github.com/linkerd/linkerd2/pull/3600.
