### ISSUE TITLE
Add annotations for proxy environment variables

### ISSUE THREAD

**Issue by cpretzer** [linkerd/linkerd2#3567]
## Feature Request
Provide annotations for all proxy environment variables.

When the linkerd proxy yaml is added to the pod, there are several environment variables defined which configure the proxy behavior. An example of the yaml for an injected pod is in this [gist](https://gist.github.com/cpretzer/67ba0bd59d8a2fb980cad1802c55fd53).

Admittedly, these environment variables have sensible defaults and don't need to be configured except in specific scenarios. One such scenario is when proxied service (let's call it ServiceA) makes a call to another service (let's call it ServiceB) and the connection from ServiceA to ServiceB frequently times out in the proxy. The connection timeout can be set from the default value of 1 second by setting the `LINKERD2_PROXY_OUTBOUND_CONNECT_TIMEOUT` environment variable in the `env` section of the injected pod.

The issue with this is that one has to use the `linkerd inject --manual` command in order to generate a `Deployment` manifest with editable environment variables, and this detracts from the utility of auto injecting proxies.

Here is a partial list of environment variables, some with annotations, defined in [config.rs](https://github.com/linkerd/linkerd2-proxy/blob/master/src/app/config.rs)

| Environment Variable | Annotation |
| --------------------- | ----------- |
| LINKERD2_PROXY_LOG | config.linkerd.io/proxy-log-level |
| LINKERD2_PROXY_CONTROL_LISTEN_ADDR | config.linkerd.io/control-port |
| LINKERD2_PROXY_ADMIN_LISTEN_ADDR | config.linkerd.io/admin-port |
| LINKERD2_PROXY_OUTBOUND_LISTEN_ADDR | config.linkerd.io/outbound-port |
| LINKERD2_PROXY_INBOUND_LISTEN_ADDR | config.linkerd.io/inbound-port |
| LINKERD2_PROXY_INBOUND_ACCEPT_KEEPALIVE |  |
| LINKERD2_PROXY_INBOUND_CONNECT_KEEPALIVE | |
| LINKERD2_PROXY_OUTBOUND_CONNECT_KEEPALIVE |  |
| LINKERD2_PROXY_METRICS_RETAIN_IDLE | | 
| LINKERD2_PROXY_INBOUND_DISPATCH_TIMEOUT | |
| LINKERD2_PROXY_OUTBOUND_DISPATCH_TIMEOUT | | 
| LINKERD2_PROXY_INBOUND_CONNECT_TIMEOUT | |
| LINKERD2_PROXY_OUTBOUND_CONNECT_TIMEOUT | | 
| LINKERD2_PROXY_OUTBOUND_ACCEPT_KEEPALIVE | | 
| LINKERD2_PROXY_INBOUND_ROUTER_MAX_IDLE_AGE | | 
| LINKERD2_PROXY_OUTBOUND_ROUTER_MAX_IDLE_AGE | | 
| LINKERD2_PROXY_INBOUND_MAX_IN_FLIGHT | | 
| LINKERD2_PROXY_OUTBOUND_MAX_IN_FLIGHT | | 

### What problem are you trying to solve?
Some of the environment variables used to configure the proxy require `manual` injection in order to modify their values. 

### How should the problem be solved?
Add new annotations to configure the environment variables. For example, the `config.linkerd.io/proxy-log-level` annotation is used to configure the `LINKERD2_PROXY_LOG ` environment variable

The main drawback is that these environment variables are not frequently configured. I don't see any technical drawbacks to adding the annotations.

This GitHub issue covers quite a few environment variables, and the work for each environment variable should be covered in separate pull requests, each addressing a piece of this work.

### Any alternatives you've considered?

Detailed instructions for using `manual` injection to configure the proxy.

### How would users interact with this feature?
Users will annotate their deployments or namespaces with `linkerd` specific annotations to configure the proxy environment variables. This will work exactly the same way that the  `config.linkerd.io/proxy-log-level` annotation works.

**Comment by grampelberg** [comment]
I feel a little uncomfortable making most of these configurable. They're internal and I'd rather not support modifying them moving forward.

**Comment by olix0r** [comment]
I'm -1 on this as well, I think. This makes this configuration part of a public API that I don't intend to maintain as a stable API. If we were to support something like this, I think we'd want being able to configure _arbitrary_ environment for the proxy... though I think that has a number of potential problems as well (how should that interact with other injector-set variables, for instance?)

**Comment by cpretzer** [comment]
@grampelberg @olix0r Thanks for the feedback on this. I take your points.

Reading into your responses, the takeaway is that folks who find themselves needing to manage advanced configuration options today should rely on `linkerd inject --manual` for their deployments that require a more granular level of control.

**Comment by grampelberg** [comment]
@cpretzer I think it comes down to public vs private APIs more than advanced configurations. It *should* be possible to still use, as long as it feels like an unsupported configuration. If `inject --manual` isn't the right solution to that, I'm totally up for other suggestions. A couple examples off the top of my head would be allowing `inject` helm chart modifications, json patches as annotations (kinda like how we're doing nginx ingress config) or kustomize packages.

**Comment by cpretzer** [comment]
@grampelberg that makes sense to me.

For now, it makes sense to continue to use `linkerd inject --manual`, since there are higher priority tasks where we can put effort.

I'm going to close this because we have a workaround. If we find that more folks are looking to modify these environment variables, we can revisit the issue.

**Comment by mmiller1** [comment]
I would very much like the ability to set arbitrary environment variables in injected pods (overriding LINKERD2_PROXY_OUTBOUND_CONNECT_TIMEOUT is our immediate need). I would be willing to help contribute something like "proxy.extraEnv: {}" to the helm chart if it would be welcomed.

**Comment by jrmyr** [comment]
Hello,
I would also absolutely support this possibility. Sure, it might not be wanted that people start to play with these values. But as it is possible anyway via `linkerd inject --manual`, why not providing some comfort to people who are forced to tweak these values?

**Comment by olix0r** [comment]
I like @mmiller1's suggestion of providing a general way to add environment variables to the proxy's container.

For context, the rationale of not exposing annotations for all possible env configurations is that we don't really view this as a "stable" API. It's easier for us to change this configuration (sometimes drastically) if we don't have to worry about deprecation cycles, etc. But I don't think anyone would object to providing an escape-hatch for interacting with the proxy injector.

**Comment by jrmyr** [comment]
For our use case, it would be great to have this possibility per deployment (that' why I like the "annotation way"). Modifying the helm chart is not needed for us as we don't want to modify the general way the linkerd proxies are configured. On the other hand, using `linkerd inject --manual` for all deployments which need adaptions is cumbersome and error-prone.

So it seems we have 2 approaches here:
1) Modify the helm chart so that all linkerd proxies are getting adaptable config values
2) Modify a deployment so that the added linkerd proxy can get adaptable config values 

As said, we would favor *2)*; an implementation as described in this issue would be perfect. Using `config.linkerd.io/...` annotations seems perfect as also other properties are exposed like this (e.g.: `config.linkerd.io/trace-collector`). If there are configs which should not be changed (like `LINKERD2_PROXY_DESTINATION_SVC_ADDR` or something), just don't provide an annotation for these. But I think there will be also others out there wanting to experiment with the timeouts (at least).

**Comment by olix0r** [comment]
@jrmyr I think we'd be happy to help merge a PR that adds this, if you want to try to put one together.

Please keep in mind that we're a small team, and we give Linkerd away for free. So, just because we haven't prioritized a feature like this, generally doesn't mean we're unwilling to support it ;)

**Comment by jrmyr** [comment]
OK. I see. :-)
It was not to put some pressure or something. I just wanted to note that we are interested in this (as well) and why. 

Putting something together for PR will be not that easy for me as I am completely new to Go. But when I will see some free time at some point I will give it a try.
Thanks for your rapid and friendly answers.

**Comment by ihcsim** [comment]
@jrmyr When you are ready, join us in the Linkerd [#contributors](https://linkerd.slack.com/archives/CMS5ZD60Y) channel. We can help you get started. We can also re-open this issue when there is someone actively working on it.

**Comment by jrmyr** [comment]
Thanks a lot for this nice invitaion. :-)
I will let you know. Though, I can not make any promise when my schedule will give me time...
