### ISSUE TITLE
Dashboard may need shift-reload in order to display

### ISSUE THREAD

**Issue by geekmush** [linkerd/linkerd2#3573]
### What is the issue?
Dashboard (in Chrome) coming up with a blank screen.

### How can it be reproduced?
Attaching to dashboard via `linkerd dashboard` and get a blank screen (in Chrome).

### Logs, error output, etc
Blank browser window!

#### `linkerd check` output

(all green)

### Environment

- Kubernetes Version: 1.14.6
- Cluster Environment: AKS
- Host OS: Chrome on MacOS Mojave, linkerd on (whatever AKS decides to use for a Linux node today)
- Linkerd version: 2.6 (new install)

### Possible solution
Shift-Reload and the dashboard appears!

**Comment by scottcarol** [comment]
Hey @geekmush, thanks for filing this issue! We've heard this from other users too - question, were you using Linkerd before 2.6, and if so, which version were you upgrading from?

**Comment by scottcarol** [comment]
Note: we previously added a hash to the webpack bundle name when webpack builds (#2058) so this may be a separate issue. Any console errors would be helpful too.

**Comment by geekmush** [comment]
We've been on Linkerd since 2.4 ... this was a fresh install, however ...
albeit, that same browser session had already opened a dashboard prior
(restarting Chrome is an adventure for me, so that's why I use FireFox for
a lot of short-term viewing ... I should have in this case).

I even did a full delete of linkerd and fresh install again ...
definitely browser cache issue.

The shift-reload fixed it right away.

Hope this helps!

Sam

**Comment by scottcarol** [comment]
Thank you, super helpful!

**Comment by grampelberg** [comment]
I've got my browser in this state right now. I'm getting a 404 on `http://localhost:50750/dist/main.2b8f9aeb515f7c29f134.js`. It appears that this is because `index_bundle.js` is cached and I'm getting a 304 back (which is where that javascript gets downloaded).

**Comment by scottcarol** [comment]
Thanks @grampelberg, that's helpful. @siggy and I talked about it this morning and the problem may be in how we're loading our hashed js bundles (#2074).

**Comment by scottcarol** [comment]
Closing in favor of #2074 which is the root of this problem.
