### ISSUE TITLE
Evaluate additional cert-manager scenarios

### ISSUE THREAD

**Issue by ihcsim** [linkerd/linkerd2#3578]
As part of our integration effort with cert-manager, we should test out the following scenarios, to have a better understanding of how things work:

1. What happens if user manually rotates the `linkerd-identity-isuer` secret generated by cert-manager? Will cert-manager still work when it tries to rotate the cert?
1. Can cert-manager perform on-demand cert rotation such as in the event of a breach?

**Comment by zaharidichev** [comment]
> What happens if user manually rotates the linkerd-identity-isuer secret generated by cert-manager? Will cert-manager still work when it tries to rotate the cert?

cert-manager actually watches the secret and whenever it is modified in any way it rotates the certs itself. So in order for manual rotation to happen, the user needs to actually stop cert-manager and manually rotate `linkerd-identity-isuer`.

> Can cert-manager perform on-demand cert rotation such as in the event of a breach?

Yes, you can just delete the  `linkerd-identity-isuer` and cert-manager will recreate ir right away with new certs. The identity service will pick up this update.

**Comment by ihcsim** [comment]
@zaharidichev Thanks for doing the additional investigation work. Closing this issue.
