### ISSUE TITLE
Unable to compile from master branch

### ISSUE THREAD

**Issue by sayboras** [linkerd/linkerd2#3580]
### What is the issue?
I am unable to comiple from master branch due to below issue

go: github.com/deislabs/smi-sdk-go@v0.0.0-20190610232231-f281e2121a16 requires
	k8s.io/apimachinery@v0.0.0-20181127105237-2b1284ed4c93: invalid pseudo-version: does not match version-control timestamp (2018-11-27T02:52:37Z)

### How can it be reproduced?
Run go mod tidy from project direction.

./bin/go-run cli check also gives the same error

### Logs, error output, etc

```
go: github.com/deislabs/smi-sdk-go@v0.0.0-20190610232231-f281e2121a16 requires
k8s.io/apimachinery@v0.0.0-20181127105237-2b1284ed4c93: invalid pseudo-version: does not match version-control timestamp (2018-11-27T02:52:37Z)
```

### Environment

- Kubernetes Version: NA
- Cluster Environment: (GKE, AKS, kops, ...) NA
- Host OS: macos
- Linkerd version: NA

**Comment by Pothulapati** [comment]
Hey, there's a similar issue mentioned in the linkerd slack. https://linkerd.slack.com/archives/CMS5ZD60Y/p1570879445023700

I guess using `1.12.9` solves this! I personally use `1.12.10`

**Comment by grampelberg** [comment]
@sayboras I'm going to close this out. Please open if you're still having issues.
