### ISSUE TITLE
Make Prometheus Pluggable

### ISSUE THREAD

**Issue by Pothulapati** [linkerd/linkerd2#3590]
## Feature Request

The prometheus instance that comes with Linkerd is nice but for large clusters this can become a bottleneck. By allowing the prometheus instance to be configurable, we can give users the ability to re-use their existing monitoring infra with Linkerd and also use longer metric retention.

There have also been projects like [cortex](https://github.com/cortexproject/cortex), [thanos](https://github.com/thanos-io/thanos) which have been getting some traction recently to make prometheus scalabale. This would also allow users to use managed monitoring offerings like [Grafana Cloud](https://grafana.com/products/cloud/#pricing), etc

The following components use prometheus for queries right now:
- `public-api` : To serve metrics for CLI and dashboard.
- `heart-beat`
Both the components take the `--prometheus-url` flag during startup which points to `http://linkerd-prometheus.{{.Namespace}}.svc.{{.ClusterDomain}}:9090` right now.
- `Grafana`: This can be configured, by tweaking the data-sources field of `linkerd-grafana-configmap`

Users will then have to take the prometheus config and apply it to their monitoring infra i.e prometheus, cortex, etc. 

For prom instances running outside their k8s cluster i.e managed, etc,  A prometheus instace (with the linkerd-prometheus config) with [remote-write](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_write) configured to the outside instance. Assuming that the outside instace is scalable, by having the linkerd components still use the outside instance can help in faster metric retrieval and longer retention.

## Solution

Having a global config to set the `prometheus-url` through helm and linkerd install command should be enough. In that case, the default prometheus installation should be disabled.

### How would users interact with this feature?

`linkerd install --prometheus-url `

## Out of Scope

- How should the outside prometheus instance be installed and configured?

related #3406 

@grampelberg @ihcsim @siggy

**Comment by CamelCaseNotation** [comment]
> Users will then have to take the prometheus config and apply it to their monitoring infra i.e prometheus, cortex, etc.

Can you elaborate on this? Do you mean apply the prometheus config which linkerd creates as a ConfigMap in its Namespace? This is out of scope, but suggestions/recommendations would be nice!

**Comment by siggy** [comment]
For a bit more context, here are some docs around integration `linkerd-prometheus` metrics with other tools:
https://linkerd.io/2/tasks/exporting-metrics/

The `linkerd-prometheus` config lives here:
https://github.com/linkerd/linkerd2/blob/65d5778b9393cd41c001b5023cf02a0d7626d03c/charts/linkerd2/templates/prometheus.yaml

All that said, I'd echo @grampelberg's [recommendation](https://github.com/linkerd/linkerd2/issues/3406#issuecomment-529642159) to leave `linkerd-prometheus` as-is.
