### ISSUE TITLE
Linkerd controller becomes inaccessible from the proxies

### ISSUE THREAD

**Issue by cpretzer** [linkerd/linkerd2#3599]
I also have an identical issue to this. 

I restarted the `linkerd-controller` pods (which fixed the issue) before seeing [this comment](https://github.com/linkerd/linkerd2/issues/3441#issuecomment-537105945), but I will do this when it happens again.

Not sure what else I can offer that hasn't already been said, but happy to help where I can. I could probably give access to the cluster if that helps.

I'm running a 3 node dev cluster on digital ocean with `--ha` enabled. 
* Linkerd Version: `stable-2.5.0`
* k8s version: `1.15.2`
* meshed nginx-ingress
* Also running `flux` and `flagger`

_Originally posted by @nickjackson in https://github.com/linkerd/linkerd2/issues/3441#issuecomment-540511255_

**Comment by cpretzer** [comment]
From #3441 : https://github.com/linkerd/linkerd2/issues/3441#issuecomment-540700274

> @cpretzer no problem.
> 
> Hard to say how often it occurs. Every few days something will start 503'ing, even without any deploys. Its a development cluster, so it's only got minimal traffic on it.
> 
> I'm not convinced the issue is tied to deployments, but when we do deploy, the issue becomes apparent, probably because the proxies have out of date IP's. When I kubectl exec into an affected pod, and try to curl any of my internal services, it will just 503.
> 
> Flux does manage the linkerd deployment, but I haven't made any changes to the linkerd manifests in my flux repo in about two months. Most of the pods in the linkerd namespace have been running for 50 days (with the exception of the controller which I restarted this morning)
> 
> Actually, I've just noticed that I get the linkerd2_proxy::app::errors request aborted because it reached the configured dispatch deadline error, not the one in the issue title, but the symptoms are the same.

**Comment by cpretzer** [comment]
> Thought you should know that I upgraded to 2.6 and am seeing this issue still. :-(
> 
> This time it happened to an nginx ingress pod, and we noticed because we deployed a new frontend service, and a 3rd of requests started 503ing. Restarting the linkerd controller fixed the issue.
> 
> I've captured the metrics from the linkerd-controller (before restart), along with the logs on that nginx pod. I've sent as a Slack DM to @cpretzer and @grampelberg.

**Comment by cpretzer** [comment]
> @adleong deleting the pods on a meshed service does fix the issue for me. New pods get spun up, the pods reconnect fine.
> 
> It is worth noting, that I used linkerd upgrade to go from 2.4 through to 2.6. Some pods are still using the 2.5 proxy.
> 
> I did manage to kubectl exec into a service with a broken proxy a few days ago, and I wasn't able to curl any of my services by DNS.

**Comment by nickjackson** [comment]
Thank you @cpretzer. Sorry for causing confusion on the other issue.

Not sure if this will help, but I've set the proxies to a `debug` log level, in hope that might have some more details in there.

**Comment by cpretzer** [comment]
@nickjackson, no problem at all! I'm glad that it's not the same issue.

The debug output will be helpful, for sure. 

When the behavior occurs again, it will be helpful to get the log info from `flux` and `flagger` just to see if anything happened. It will also be helpful to get the `kubelet` logs.

**Comment by nickjackson** [comment]
Hello @cpretzer, so managed to dig out some more logs with `debug` but there's now so much logging that I'm not entirely sure it's useful anymore.

The issue came back earlier today after deploying a new backing service. The following logs from a failing pod are interesting. In each line, it's referencing a pod that was either _just_ discarded by the deployment or references a pod that was discarded on the deployment before that.

I don't understand the linkerd internals, but this really feels like an issue with the proxy. Perhaps it's maintaining a connection to the controller, but no longer receiving any updates, and relying on an internal cache?

One thing that was different, I tried restarting the controller pods, but that didn't fix my issue this time. I had to restart the failing pods.

```
DBUG [255108.723065s] linkerd2_proxy::proxy::http::client building client=Endpoint { dst_logical: Some(NameAddr { name: "checkout.platform.svc.cluster.local.", port: 8000 }), dst_concrete: Some(NameAddr { name: "checkout-primary.platform.svc.cluster.local.", port: 8000 }), addr: V4(10.244.0.238:8000), identity: Some("default.platform.serviceaccount.identity.linkerd.cluster.local"), metadata: Metadata { weight: 10000, labels: {"control_plane_ns": "linkerd", "deployment": "checkout-primary", "namespace": "platform", "pod": "checkout-primary-58f489bbbb-twvc2", "pod_template_hash": "58f489bbbb", "service": "checkout-primary", "serviceaccount": "default"}, protocol_hint: Http2, identity: Some("default.platform.serviceaccount.identity.linkerd.cluster.local") }, http_settings: Http2 }
DBUG [255108.723140s] linkerd2_proxy::transport::connect connecting to 10.244.0.238:8000
DBUG [255108.732577s] linkerd2_proxy::proxy::http::client building client=Endpoint { dst_logical: Some(NameAddr { name: "checkout.platform.svc.cluster.local.", port: 8000 }), dst_concrete: Some(NameAddr { name: "checkout-primary.platform.svc.cluster.local.", port: 8000 }), addr: V4(10.244.5.7:8000), identity: Some("default.platform.serviceaccount.identity.linkerd.cluster.local"), metadata: Metadata { weight: 10000, labels: {"control_plane_ns": "linkerd", "deployment": "checkout-primary", "namespace": "platform", "pod": "checkout-primary-58f489bbbb-bcgg7", "pod_template_hash": "58f489bbbb", "service": "checkout-primary", "serviceaccount": "default"}, protocol_hint: Http2, identity: Some("default.platform.serviceaccount.identity.linkerd.cluster.local") }, http_settings: Http2 }
DBUG [255108.732643s] linkerd2_proxy::transport::connect connecting to 10.244.5.7:8000
DBUG [255109.704259s] linkerd2_proxy::proxy::http::client building client=Endpoint { dst_logical: Some(NameAddr { name: "checkout.platform.svc.cluster.local.", port: 8000 }), dst_concrete: Some(NameAddr { name: "checkout-primary.platform.svc.cluster.local.", port: 8000 }), addr: V4(10.244.0.139:8000), identity: Some("default.platform.serviceaccount.identity.linkerd.cluster.local"), metadata: Metadata { weight: 10000, labels: {"control_plane_ns": "linkerd", "deployment": "checkout-primary", "namespace": "platform", "pod": "checkout-primary-5865c944c4-86ntx", "pod_template_hash": "5865c944c4", "service": "checkout-primary", "serviceaccount": "default"}, protocol_hint: Http2, identity: Some("default.platform.serviceaccount.identity.linkerd.cluster.local") }, http_settings: Http2 }
DBUG [255109.704346s] linkerd2_proxy::transport::connect connecting to 10.244.0.139:8000
DBUG [255110.224869s] linkerd2_proxy::proxy::http::client building client=Endpoint { dst_logical: Some(NameAddr { name: "checkout.platform.svc.cluster.local.", port: 8000 }), dst_concrete: Some(NameAddr { name: "checkout-primary.platform.svc.cluster.local.", port: 8000 }), addr: V4(10.244.0.238:8000), identity: Some("default.platform.serviceaccount.identity.linkerd.cluster.local"), metadata: Metadata { weight: 10000, labels: {"control_plane_ns": "linkerd", "deployment": "checkout-primary", "namespace": "platform", "pod": "checkout-primary-58f489bbbb-twvc2", "pod_template_hash": "58f489bbbb", "service": "checkout-primary", "serviceaccount": "default"}, protocol_hint: Http2, identity: Some("default.platform.serviceaccount.identity.linkerd.cluster.local") }, http_settings: Http2 }
DBUG [255110.224941s] linkerd2_proxy::transport::connect connecting to 10.244.0.238:8000
DBUG [255110.235360s] linkerd2_proxy::proxy::http::client building client=Endpoint { dst_logical: Some(NameAddr { name: "checkout.platform.svc.cluster.local.", port: 8000 }), dst_concrete: Some(NameAddr { name: "checkout-primary.platform.svc.cluster.local.", port: 8000 }), addr: V4(10.244.5.7:8000), identity: Some("default.platform.serviceaccount.identity.linkerd.cluster.local"), metadata: Metadata { weight: 10000, labels: {"control_plane_ns": "linkerd", "deployment": "checkout-primary", "namespace": "platform", "pod": "checkout-primary-58f489bbbb-bcgg7", "pod_template_hash": "58f489bbbb", "service": "checkout-primary", "serviceaccount": "default"}, protocol_hint: Http2, identity: Some("default.platform.serviceaccount.identity.linkerd.cluster.local") }, http_settings: Http2 }
DBUG [255110.235420s] linkerd2_proxy::transport::connect connecting to 10.244.5.7:8000
DBUG [255111.208487s] linkerd2_proxy::proxy::http::client building client=Endpoint { dst_logical: Some(NameAddr { name: "checkout.platform.svc.cluster.local.", port: 8000 }), dst_concrete: Some(NameAddr { name: "checkout-primary.platform.svc.cluster.local.", port: 8000 }), addr: V4(10.244.0.139:8000), identity: Some("default.platform.serviceaccount.identity.linkerd.cluster.local"), metadata: Metadata { weight: 10000, labels: {"control_plane_ns": "linkerd", "deployment": "checkout-primary", "namespace": "platform", "pod": "checkout-primary-5865c944c4-86ntx", "pod_template_hash": "5865c944c4", "service": "checkout-primary", "serviceaccount": "default"}, protocol_hint: Http2, identity: Some("default.platform.serviceaccount.identity.linkerd.cluster.local") }, http_settings: Http2 }
DBUG [255111.208552s] linkerd2_proxy::transport::connect connecting to 10.244.0.139:8000
DBUG [255111.727086s] linkerd2_proxy::proxy::http::client building client=Endpoint { dst_logical: Some(NameAddr { name: "checkout.platform.svc.cluster.local.", port: 8000 }), dst_concrete: Some(NameAddr { name: "checkout-primary.platform.svc.cluster.local.", port: 8000 }), addr: V4(10.244.0.238:8000), identity: Some("default.platform.serviceaccount.identity.linkerd.cluster.local"), metadata: Metadata { weight: 10000, labels: {"control_plane_ns": "linkerd", "deployment": "checkout-primary", "namespace": "platform", "pod": "checkout-primary-58f489bbbb-twvc2", "pod_template_hash": "58f489bbbb", "service": "checkout-primary", "serviceaccount": "default"}, protocol_hint: Http2, identity: Some("default.platform.serviceaccount.identity.linkerd.cluster.local") }, http_settings: Http2 }
DBUG [255111.727161s] linkerd2_proxy::transport::connect connecting to 10.244.0.238:8000
DBUG [255111.738550s] linkerd2_proxy::proxy::http::client building client=Endpoint { dst_logical: Some(NameAddr { name: "checkout.platform.svc.cluster.local.", port: 8000 }), dst_concrete: Some(NameAddr { name: "checkout-primary.platform.svc.cluster.local.", port: 8000 }), addr: V4(10.244.5.7:8000), identity: Some("default.platform.serviceaccount.identity.linkerd.cluster.local"), metadata: Metadata { weight: 10000, labels: {"control_plane_ns": "linkerd", "deployment": "checkout-primary", "namespace": "platform", "pod": "checkout-primary-58f489bbbb-bcgg7", "pod_template_hash": "58f489bbbb", "service": "checkout-primary", "serviceaccount": "default"}, protocol_hint: Http2, identity: Some("default.platform.serviceaccount.identity.linkerd.cluster.local") }, http_settings: Http2 }
DBUG [255111.738611s] linkerd2_proxy::transport::connect connecting to 10.244.5.7:8000
DBUG [255112.711824s] linkerd2_proxy::proxy::http::client building client=Endpoint { dst_logical: Some(NameAddr { name: "checkout.platform.svc.cluster.local.", port: 8000 }), dst_concrete: Some(NameAddr { name: "checkout-primary.platform.svc.cluster.local.", port: 8000 }), addr: V4(10.244.0.139:8000), identity: Some("default.platform.serviceaccount.identity.linkerd.cluster.local"), metadata: Metadata { weight: 10000, labels: {"control_plane_ns": "linkerd", "deployment": "checkout-primary", "namespace": "platform", "pod": "checkout-primary-5865c944c4-86ntx", "pod_template_hash": "5865c944c4", "service": "checkout-primary", "serviceaccount": "default"}, protocol_hint: Http2, identity: Some("default.platform.serviceaccount.identity.linkerd.cluster.local") }, http_settings: Http2 }
DBUG [255112.711910s] linkerd2_proxy::transport::connect connecting to 10.244.0.139:8000
DBUG [255113.229494s] linkerd2_proxy::proxy::http::client building client=Endpoint { dst_logical: Some(NameAddr { name: "checkout.platform.svc.cluster.local.", port: 8000 }), dst_concrete: Some(NameAddr { name: "checkout-primary.platform.svc.cluster.local.", port: 8000 }), addr: V4(10.244.0.238:8000), identity: Some("default.platform.serviceaccount.identity.linkerd.cluster.local"), metadata: Metadata { weight: 10000, labels: {"control_plane_ns": "linkerd", "deployment": "checkout-primary", "namespace": "platform", "pod": "checkout-primary-58f489bbbb-twvc2", "pod_template_hash": "58f489bbbb", "service": "checkout-primary", "serviceaccount": "default"}, protocol_hint: Http2, identity: Some("default.platform.serviceaccount.identity.linkerd.cluster.local") }, http_settings: Http2 }
DBUG [255113.229571s] linkerd2_proxy::transport::connect connecting to 10.244.0.238:8000
DBUG [255113.242300s] linkerd2_proxy::proxy::http::client building client=Endpoint { dst_logical: Some(NameAddr { name: "checkout.platform.svc.cluster.local.", port: 8000 }), dst_concrete: Some(NameAddr { name: "checkout-primary.platform.svc.cluster.local.", port: 8000 }), addr: V4(10.244.5.7:8000), identity: Some("default.platform.serviceaccount.identity.linkerd.cluster.local"), metadata: Metadata { weight: 10000, labels: {"control_plane_ns": "linkerd", "deployment": "checkout-primary", "namespace": "platform", "pod": "checkout-primary-58f489bbbb-bcgg7", "pod_template_hash": "58f489bbbb", "service": "checkout-primary", "serviceaccount": "default"}, protocol_hint: Http2, identity: Some("default.platform.serviceaccount.identity.linkerd.cluster.local") }, http_settings: Http2 }
DBUG [255113.242373s] linkerd2_proxy::transport::connect connecting to 10.244.5.7:8000
DBUG [255114.215420s] linkerd2_proxy::proxy::http::client building client=Endpoint { dst_logical: Some(NameAddr { name: "checkout.platform.svc.cluster.local.", port: 8000 }), dst_concrete: Some(NameAddr { name: "checkout-primary.platform.svc.cluster.local.", port: 8000 }), addr: V4(10.244.0.139:8000), identity: Some("default.platform.serviceaccount.identity.linkerd.cluster.local"), metadata: Metadata { weight: 10000, labels: {"control_plane_ns": "linkerd", "deployment": "checkout-primary", "namespace": "platform", "pod": "checkout-primary-5865c944c4-86ntx", "pod_template_hash": "5865c944c4", "service": "checkout-primary", "serviceaccount": "default"}, protocol_hint: Http2, identity: Some("default.platform.serviceaccount.identity.linkerd.cluster.local") }, http_settings: Http2 }
DBUG [255114.215474s] linkerd2_proxy::transport::connect connecting to 10.244.0.139:8000
DBUG [255114.435504s] admin={server=admin listen=0.0.0.0:4191} linkerd2_proxy::transport::tls::listen accepted connection from 10.244.1.1:44388 to None; attempting TLS handshake
DBUG [255114.732041s] linkerd2_proxy::proxy::http::client building client=Endpoint { dst_logical: Some(NameAddr { name: "checkout.platform.svc.cluster.local.", port: 8000 }), dst_concrete: Some(NameAddr { name: "checkout-primary.platform.svc.cluster.local.", port: 8000 }), addr: V4(10.244.0.238:8000), identity: Some("default.platform.serviceaccount.identity.linkerd.cluster.local"), metadata: Metadata { weight: 10000, labels: {"control_plane_ns": "linkerd", "deployment": "checkout-primary", "namespace": "platform", "pod": "checkout-primary-58f489bbbb-twvc2", "pod_template_hash": "58f489bbbb", "service": "checkout-primary", "serviceaccount": "default"}, protocol_hint: Http2, identity: Some("default.platform.serviceaccount.identity.linkerd.cluster.local") }, http_settings: Http2 }
DBUG [255114.732157s] linkerd2_proxy::transport::connect connecting to 10.244.0.238:8000
DBUG [255114.745568s] linkerd2_proxy::proxy::http::client building client=Endpoint { dst_logical: Some(NameAddr { name: "checkout.platform.svc.cluster.local.", port: 8000 }), dst_concrete: Some(NameAddr { name: "checkout-primary.platform.svc.cluster.local.", port: 8000 }), addr: V4(10.244.5.7:8000), identity: Some("default.platform.serviceaccount.identity.linkerd.cluster.local"), metadata: Metadata { weight: 10000, labels: {"control_plane_ns": "linkerd", "deployment": "checkout-primary", "namespace": "platform", "pod": "checkout-primary-58f489bbbb-bcgg7", "pod_template_hash": "58f489bbbb", "service": "checkout-primary", "serviceaccount": "default"}, protocol_hint: Http2, identity: Some("default.platform.serviceaccount.identity.linkerd.cluster.local") }, http_settings: Http2 }
DBUG [255114.745634s] linkerd2_proxy::transport::connect connecting to 10.244.5.7:8000
```

**Comment by grampelberg** [comment]
@nickjackson did you happen to run `linkerd endpoints` when this was happening?

**Comment by nickjackson** [comment]
Afraid not on this occasion, but when it happened in the past, it yielded the correct pod details.

**Comment by nickjackson** [comment]
Just to fill you in, I can pretty much guarantee it happens now if a linkerd-proxy lives longer than ~2 days. It just doesn't come apparent until we deploy something and the ips change.

We just made a deployment via `kubectl set image` (not with flagger/flux) after not deploying anything for 3 days and our ingress kept trying to send traffic to the old pods. I ran `linkerd endpoints` and got the correct pods back. I deleted the linkerd destination and controller pods, and this resolved the issue. The linkerd-proxy logs show the successful reconnection after this.

We are looking to go into prod next week. Would a fresh install of linkerd be worth a try?

**Comment by cpretzer** [comment]
@nickjackson, thanks for the precise description.

Which ingress are you using? Can you share the config file? I'm curious to see if there are any customizations that could cause this. For example, it would be interesting if there were any nginx configuration that cached the IP addresses, or wasn't getting the correct updates.

**Comment by nickjackson** [comment]
We are using the bog-standard Nginx ingress. I think I installed from https://kubernetes.github.io/ingress-nginx/deploy/ (all though the YAML manifests were deployed via flux)

I should note, this issue can happen across all linkerd proxies, not just the nginx ones, so I don't think this will help much.

Here is the specific nginx ingress config (I've sanitized the domains/service names) for the service that failed earlier today.

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: example
  namespace: example-namespace
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:3000;
      proxy_hide_header l5d-remote-ip;
      proxy_hide_header l5d-server-id;
spec:
  rules:
  - host: example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: domain
          servicePort: 3000
  tls:
    - secretName: cert-example.com
```

I'm trying to think what in our cluster might be causing the issues, and I'm coming up blank. We have roughly 15 different deployments, with a mixture of Node and Go. The node services are API gateways and web apps, the go apps are twirp services. Everything works as I'd expect it to most of the time. 

It's as if the proxy just stops receiving any updates until their connection with the controller/endpoints is killed.

**Comment by cpretzer** [comment]
@nickjackson Please have a look at my comment in #3441 

https://github.com/linkerd/linkerd2/issues/3441#issuecomment-547227597

**Comment by nickjackson** [comment]
I ran @grampelberg's script over the weekend on my cluster, to no avail, unfortunately. We are going into production (even with this issue for now) so I'll spin up a dev cluster this week and see if I can recreate the issue there and turn on the debugging sidecar.

**Comment by cpretzer** [comment]
@nickjackson before this goes stale, just want to check to see how the prod deployment went and whether you were able to collect any info from the debug sidecar.

**Comment by nickjackson** [comment]
@cpretzer prod has gone well. Been live for a few months now without any hiccups. I wasn’t able to get the debug sidecar enabled, I haven’t had the time to look into it sorry!

To avoid any potential issue on production, I’ve been manually and frequently deleting the linkerd controller pods. It’s a bit crude but it does the trick.

Considering this is not widespread, I’m going to put it down to an issue with my cluster, so maybe this issue should be closed?

**Comment by cpretzer** [comment]
@nickjackson thanks for the reply.

I'm glad to hear that you haven't had any hiccups, although restarting the linkerd-controller pods is not an ideal situation. If you have the opportunity, it would be great to see what happens if the pods are not deleted in a non-prod environment.

If you have time to gather that info, please reopen this issue with the details 😄 🙏

**Comment by nickjackson** [comment]
@cpretzer Small correction - I've been deleting the `linkerd-destination` pods, not the controller.

**Comment by cpretzer** [comment]
Thanks for clarifying @nickjackson. 

I'd love to find root cause on this. We can set up a debug session together, if you have time.
