### ISSUE TITLE
Certificates change during upgrade

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#3608]
### What is the issue?

I am under the impression that when running `upgrade`, the CLI will keep all the certificates the same. It appears that this is not the case. When upgrading from stable-2.5.0 to stable-2.6.0, the following certs/keys change:

- linkerd-identity-issuer
- linkerd-proxy-injector-tls
- linkerd.linkerd-sp-validator-tls
- linkerd-tap-tls

Note: this appears to not introduce downtime during an upgrade as `trustAnchorsPem` does not change.

### How can it be reproduced?

Just install stable-2.5.0, run `linkerd upgrade` for stable-2.6.0 and pipe to `kubectl diff -f -`.

**Comment by adleong** [comment]
Unless I'm mistaken about how this works, this should not be possible.  The root key (the private half of the trust root) is generated and discarded at install time.  This means that it is not possible to generate a new issuer cert that will validate against the same trust root.

Either I'm confused, or something weird is going on...

**Comment by olix0r** [comment]
The credentials are always emitted. They're just identitical

**Comment by adleong** [comment]
Upon investigating, it appears that the certificates and keys only differ by trailing whitespace.  They deserialize to the exact same certificate or key.  It's unclear why the whitespace formatting changed, but this appears to be harmless.
