### ISSUE TITLE
Add Cron Jobs and Replica Sets to dashboard

### ISSUE THREAD

**Issue by scottcarol** [linkerd/linkerd2#3614]
The Kubernetes dashboard has views for these workloads:
```
Cron Jobs
Daemon Sets
Deployments
Jobs
Pods
Replica Sets
Replication Controllers
Stateful Sets
```
The Linkerd dashboard does not show data for `Cron Jobs` or `Replica Sets`. We should add these workload types to the sidebar, list them by namespace and return stats for them if possible.

**Comment by tegioz** [comment]
Similar to #3584

**Comment by tegioz** [comment]
Similar to #3585
