### ISSUE TITLE
Update dashboard to latest React

### ISSUE THREAD

**Issue by scottcarol** [linkerd/linkerd2#3617]
The dashboard is currently on React `16.5.0`. React can be updated to `16.9.0`.

Updating to the latest React means that we will need to stop using from the `react-url-query` library, which we are using to encode/decode URLs in the Tap and Top Routes views. 

`react-url-query` utilizes the `componentWillMount` lifecycle method which will no longer be supported by React.

The creator of the react-url-query created a [use-query-params](https://github.com/pbeshai/use-query-params#readme) hook which we can use instead.

**Comment by tzsword** [comment]
🙋🏻‍♂️

**Comment by scottcarol** [comment]
Hey tzsword! 👋 Glad you're interested in working on the dashboard! This issue is already assigned, but are you interested in working on another React ticket? #2915 and #2996 are available.

**Comment by tzsword** [comment]
@scottcarol 👋 i will try #2915

**Comment by scottcarol** [comment]
@cynthia-sg I will not be able to get to this until after KubeCon so if you would like this issue it's yours 😄
