### ISSUE TITLE
Sidecar proxies not spinning up due to `Failed to certify identity: grpc-status: Unknown, grpc-message: "the request could not be dispatched in a timely fashion`

### ISSUE THREAD

**Issue by uipo78** [linkerd/linkerd2#3620]
### What is the issue?

After annotating a namespace with `linkerd.io/inject=enabled` or manually injecting deployments with the linkerd proxy using `linkerd inject`, we observe that the sidecar proxy of certain pods (ut not all) aren't able to become ready. 

### How can it be reproduced?

I'm not really sure how to reproduce this since the bug doesn't occur on every pod.

### Logs, error output, etc

Running `kubectl describe $pod_name` will show in event log the following event associated with the proxy container:
```
  Warning  Unhealthy  9s (x3 over 29s)  kubelet, aks-akspool-31436444-4  Readiness probe failed: HTTP probe failed with statuscode: 503
```

And the logs of the sidecar proxy show this:
```
INFO [     0.003130s] linkerd2_proxy::app::main using destination service at ControlAddr { addr: Name(NameAddr { name: "linkerd-dst.linkerd.svc.cluster.local", port: 8086 }), identity: Some("linkerd-destination.linkerd.serviceaccount.identity.linkerd.cluster.local") }
INFO [     0.003167s] linkerd2_proxy::app::main using identity service at Name(NameAddr { name: "linkerd-identity.linkerd.svc.cluster.local", port: 8080 })
INFO [     0.003173s] linkerd2_proxy::app::main routing on V4(127.0.0.1:4140)
INFO [     0.003177s] linkerd2_proxy::app::main proxying on V4(0.0.0.0:4143) to None
INFO [     0.003184s] linkerd2_proxy::app::main serving admin endpoint metrics on V4(0.0.0.0:4191)
INFO [     0.003187s] linkerd2_proxy::app::main protocol detection disabled for inbound ports {25, 587, 3306}
INFO [     0.003193s] linkerd2_proxy::app::main protocol detection disabled for outbound ports {25, 587, 3306}
ERR! [     5.005523s] admin={bg=identity} linkerd2_proxy::app::identity Failed to certify identity: grpc-status: Unknown, grpc-message: "the request could not be dispatched in a timely fashion"
```

Again, this only happens on the pods of certain deployments (it's not at all clear why it fails only for them).

The proxies on all of the linkerd control plane pods are up and ready, as is the control plane generally (see `linkerd check` output below).

#### `linkerd check` output

```text
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-api
-----------
√ control plane pods are ready
√ control plane self-check
√ [kubernetes] control plane can talk to Kubernetes
√ [prometheus] control plane can talk to Prometheus
√ no invalid service profiles

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ control plane is up-to-date
√ control plane and cli versions match

Status check results are √
```

### Environment

- Kubernetes Version: `v1.14.6`
- Cluster Environment: AKS
- Host OS: Ubuntu
- Linkerd version: 2.6.0

### Additional context

The logs of the `linkerd-controller` pod's `destination` container was requested in a [similar MR](https://github.com/linkerd/linkerd2/issues/2929), so I'll post mine here as well:
```
time="2019-10-21T21:21:06Z" level=info msg="running version stable-2.6.0"
time="2019-10-21T21:21:06Z" level=info msg="waiting for caches to sync"
time="2019-10-21T21:21:06Z" level=info msg="caches synced"
time="2019-10-21T21:21:06Z" level=info msg="starting admin server on :9996"
time="2019-10-21T21:21:06Z" level=info msg="starting gRPC server on :8086"
```

**Comment by uipo78** [comment]
[Here's a gist of the sidecar proxy's logs](https://gist.github.com/uipo78/5c4e4cac96d5a909ae5ea194b3eb428a)

[And here's a gist of the destination container's logs](https://gist.github.com/uipo78/3bb5d78578b7daec40d19c268b5781ed)
^ Full disclosure: I redacted the trust anchor PEM and deleted some entries saying `Updating endpoints for` for certain services whose names I didn't want to disclose publicly.

**Comment by grampelberg** [comment]
Are you using network policy? According to those logs, the cluster IP was fetched correctly (`172.16.113.32:8080`) and the request timed out. Also, is that the correct cluster IP for the `linkerd-identity` service?

**Comment by uipo78** [comment]
Omg the problem is totally from a network policy. And ya know, shame on me&mdash;this isn't the first time that I failed to recognize such a problem stemming from a network policy XD. thanks
