### ISSUE TITLE
Control plane UUID gets overridden during Helm upgrade

### ISSUE THREAD

**Issue by ihcsim** [linkerd/linkerd2#3621]
The control plane [UUID](https://github.com/linkerd/linkerd2/blob/0f9ea553d2ab9b985e6d9666e95dae2260c26210/charts/linkerd2/templates/_config.tpl#L76) gets overridden when users run `helm upgrade`. The template should be updated so that the UUID remains unchanged, and matches the one stored in the `linkerd-config` config map.

At this point, I'm not sure if there is a way to automate this, since there isn't a way for `helm upgrade` to look up the `linkerd-config` config map, unless we want to explore Helm hooks. Users may have to manually provide the UUID as a helm variable, such as `helm upgrade --set UUID=<uuid-from-config-map>`, which isn't ideal IMO.

**Comment by grampelberg** [comment]
For whoever takes this issue up, please chat with me first. There's a bunch of different ways we can solve the same problem that might be easier in the end.
