### ISSUE TITLE
Teach linkerd-proxy to listen for "special requests" from the main container (that the sidecar is servicing)

### ISSUE THREAD

**Issue by geekmush** [linkerd/linkerd2#3631]
### What problem are you trying to solve?
In certain circumstances (like a cronjob), when the main container completes, the linkerd-proxy sidecar does not gracefully exit as well and let the pod terminate.

### How should the problem be solved?
If the linkerd-proxy could be taught to watch the network traffic (for example, on the `LINKERD2_PROXY_ADMIN_LISTEN_ADDR`) for specific paths or API calls from the main container and take requested action, that would be great.

There could be an opportunity for foul play if the main container spews out improper requests or gets hacked and can DOS itself, but that seems like a fairly minor case?

### Any alternatives you've considered?
Currently disabling the linkerd-proxy ... bleh!

### How would users interact with this feature?
Again, using a cronjob as an example:

```(run job script stuff...)
$ curl http://$LINKERD2_PROXY_ADMIN_LISTEN_ADDR/api/shutdown
```

Obviously, the main container doesn't have that variable natively, it would have to be mapped or injected in the yaml somehow.  (end user implementation details ... an opportunity for `linkerd` helpers as well).

or

```(run job script stuff...)
$ linkerd proxy shutdown
```

You get the idea.

There are probably other fun things that the main container could request of the proxy, assuming we chose to make the app in the main container linkerd-proxy aware.

**Comment by olix0r** [comment]
We're hoping that https://github.com/kubernetes/enhancements/issues/753 provides a more proper solution to this (possibly in Kubernetes 1.17?), but I agree it seems useful to add an admin endpoint to the proxy that supports shutdown (like the admin endpoint that supports log-level changes).

**Comment by geekmush** [comment]
A linkerd solution would probably be preferable for the near future because the various infrastructure providers (i.e. Azure) most current stable (today) is 1.14.7 and 1.15.4 is still in preview.  So, getting to K8s 1.17.x is a LONG ways off for us!  :(
