### ISSUE TITLE
Add cert manager integration test

### ISSUE THREAD

**Issue by adleong** [linkerd/linkerd2#3637]
We should have an integration test which tests the install flow and cert rotation when using cert-manager.

**Comment by zaharidichev** [comment]
@adleong 
Thinking about it, I feel the following needs to happen. 

1. Setup cert manager to create secrets
2. Install linkerd with external issuer option
3. Verify that when the proxies fire up, they issue a CSR and get a valid response
4. Force rotate the issuer certs (by deleting the linkerd-identitiy-issuer sercret)
5. Make sure the identity service has picked up the newly generated certs.
6. Force the proxy to issue a new CSR and make sure the response is the expected one. 

With all that in mind, I have two questions. 

- Should we provide some way of introspecting what the current issuer cert that the identity service works with is (maybe via an endpoint)
- How can we force the proxy to issue a new CSR, maybe through another admin endpoint? 
- How can we verify that the proxy has received a response to this new CSR, maybe expose the information about that through admin endpoint again? 

Looking at the proxy code, it does not seem that any of this is there. Should we go ahead and implement this functionality. Or is there a better way to do that that comes close to mind?

**Comment by ihcsim** [comment]
My opinion is that we just need to set up a pre-created control plane name and a secret of type `kubernetes.io/tls`. Then make sure the control plane and data plane is running correctly, by running the smoke test test suite. We are already doing that for the Helm and `upgrade` tests.

Since we pre-create the issuer secret, we should be able to match it with the trust root in the `linkerd-config` config map w/o needing to make an API call.

The correctness of cert rotation feels like it's out-of-scope; i.e. if cert-manager fails to auto rotate the cert, our tests shouldn't fail because it's a cert-manager problem.

Also, I don't think we need to explicitly test the proxy's CSR because If that isn't working, the proxies won't be healthy and the smoke test will fail.

**Comment by zaharidichev** [comment]
Well, that narrows the scope quite a bit. I think it will be useful to test the rotation, namely the secret getting updated and the identity service picking up the new issuer certs. After all, this is one bit of functionality that is new. But at the moment its quite hard to test that one, or at least I cannot think of a very good way

**Comment by zaharidichev** [comment]
Thanks guys, thats very useful info! 

> When we simulate cert rotation by manually replacing the certificate files in the secret, everything continues to work

@adleong Maybe I misunderstand something but I wonder, what would all of that check constitute?  If we manually roll the secret we can ensure that the identity service has picked up the new certs by looking at the k8s events as it outputs some. However event if that process is not successful, what could potentially break in the rest of the control plane components? I mean until its time for the proxies to hit the identity service with a new CSR, everything will continue to work as before event if the identity service went down completely? Not picking on things here, just trying to validate my understanding of things.  

I already implemented a test where we go through the flow of install_test.go but using an external issuer with pre-generated secrets, and force rotated the certs, making sure that the identity service updated its certs. So I wonder, is that enough, what else should we check, as I feel that just going and checking the logs and events emitted by the rest of the services would not be very conclusive even if things broke in the identity service. Sorry I might be way off here.

**Comment by adleong** [comment]
@zaharidichev this is a good question.  Is it possible to use certificates with very short expiration periods to ensure that the proxy will issue a new CSR quickly after the manual rotation?

**Comment by ihcsim** [comment]
>  what else should we check, as I feel that just going and checking the logs and events emitted by the rest of the services would not be very conclusive even if things broke in the identity service.

After the cert rotation, can we install the test application into another namespace? Depending on how we set up the application, if it isn't too complicated we can then check if the new application can still talk to the existing application. Assuming that the way new proxies and existing proxies issue new CSR follow the same code path, this should validate if everything still works after cert rotation, right?

Are we running this test on a standalone `kind` cluster?

**Comment by ihcsim** [comment]
> I already implemented a test where we go through the flow of install_test.go but using an external issuer with pre-generated secrets, and force rotated the certs, making sure that the identity service updated its certs

This sounds reasonable to me, as the first suite of integration test to cover the happy path.

**Comment by zaharidichev** [comment]
> Is it possible to use certificates with very short expiration periods to ensure that the proxy will issue a new CSR quickly after the manual rotation?

Yes thats my plan. I think that this does not have to do with the issuer certificates we use but more with `--identity-issuance-lifetime`. Setting that to something quite short I guess makes it possible to ensure the proxy has issued CSRs both before and after the issuer cert rotation.

**Comment by zaharidichev** [comment]
Closed in #3652
