### ISSUE TITLE
Replicate data plane trust root expiry

### ISSUE THREAD

**Issue by ihcsim** [linkerd/linkerd2#3676]
The purpose of this issue is to understand the behaviour of the data plane when the CA trust root and the `identity`'s issuer key/cert pair expired. In particular, we are interested in documenting any observable errors in the proxy log, and understand if the proxies will fall back to non-mTLS communication, or just break completely.

Relevant #3452. 

cc @cpretzer

**Comment by ihcsim** [comment]
After some testing using a control plane with its `--identity-issuance-lifetime` set to 1 minute, the emojivoto application and `curl` here are some observations:

**TL;DR** 

After the trust root expired,

1. The `emoji` proxy emits continuous errors in its logs, while attempting to renew its certificate with the `identity` service
1. AFAICT, the `identity` service continues to sign the CSR and issue a new expired certificate, which the `emoji` proxy rejects . I think this is a bug
1. The **injected** `curl` pod failed to reach the injected `web-svc.emojivoto` service with a 503 error
1. The **uninjected** `curl` pod continued to work with injected `web-svc.emojivoto` service with a 200 response
1. No new injected workloads can be started
1. Port forward to the `web-svc.emojivoto` service continued to work (because it bypass the proxy)
1. `linkerd tap` and `linkerd top` hung indefinitely
1. `linkerd [stat|edges]` failed with 503 errors 
1. `kubectl` get po will show everything as `RUNNING`

**Some details with logs**

After the trust root expired, the `emoji` pod's proxy emits these error logs:
```
kubectl -n emojivoto logs emoji-786c5d657f-lwr4v linkerd-proxy
time="2019-11-29T22:52:34Z" level=info msg="running version edge-19.11.3"
...
ERR! [ 14047.952874s] linkerd2_proxy_identity::certify Received invalid ceritficate: invalid certificate: UnknownIssuer
ERR! [ 14057.961377s] linkerd2_proxy_identity::certify Received invalid ceritficate: invalid certificate: UnknownIssuer
ERR! [ 14067.970505s] linkerd2_proxy_identity::certify Received invalid ceritficate: invalid certificate: UnknownIssuer
ERR! [ 14077.979374s] linkerd2_proxy_identity::certify Received invalid ceritficate: invalid certificate: UnknownIssuer
ERR! [ 14087.988211s] linkerd2_proxy_identity::certify Received invalid ceritficate: invalid certificate: UnknownIssuer
ERR! [ 14097.998756s] linkerd2_proxy_identity::certify Received invalid ceritficate: invalid certificate: UnknownIssuer
ERR! [ 14108.007189s] linkerd2_proxy_identity::certify Received invalid ceritficate: invalid certificate: UnknownIssuer
```

It looks like the `identity` service continues to sign the CSR and issue expired TLS certificates. For every line of the following logs, I see a corresponding `UnknownIssuer` error log on the `emoji` proxy:
```
....
linkerd-identity-ccff94f86-dpv87 identity time="2019-11-30T03:31:44Z" level=info msg="certifying emoji.emojivoto.serviceaccount.identity.linkerd.cluster.local until 2019-11-30 03:33:04 +0000 UTC"
linkerd-identity-ccff94f86-dpv87 identity time="2019-11-30T03:31:54Z" level=info msg="certifying emoji.emojivoto.serviceaccount.identity.linkerd.cluster.local until 2019-11-30 03:33:14 +0000 UTC"
linkerd-identity-ccff94f86-dpv87 identity time="2019-11-30T03:32:04Z" level=info msg="certifying emoji.emojivoto.serviceaccount.identity.linkerd.cluster.local until 2019-11-30 03:33:24 +0000 UTC"
linkerd-identity-ccff94f86-dpv87 identity time="2019-11-30T03:32:14Z" level=info msg="certifying emoji.emojivoto.serviceaccount.identity.linkerd.cluster.local until 2019-11-30 03:33:34 +0000 UTC"
linkerd-identity-ccff94f86-dpv87 identity time="2019-11-30T03:32:24Z" level=info msg="certifying emoji.emojivoto.serviceaccount.identity.linkerd.cluster.local until 2019-11-30 03:33:44 +0000 UTC"
linkerd-identity-ccff94f86-dpv87 identity time="2019-11-30T03:32:34Z" level=info msg="certifying emoji.emojivoto.serviceaccount.identity.linkerd.cluster.local until 2019-11-30 03:33:54 +0000 UTC"
linkerd-identity-ccff94f86-dpv87 identity time="2019-11-30T03:32:44Z" level=info msg="certifying emoji.emojivoto.serviceaccount.identity.linkerd.cluster.local until 2019-11-30 03:34:04 +0000 UTC"
```

An uninjected pod can still talk to an injected pod:
```
kubectl exec -it curl-00-699dd789c8-xrn9g -- /bin/sh 
Defaulting container name to curl.
# curl -vvv web-svc.emojivoto/api/list
* Trying 10.107.19.52...
* TCP_NODELAY set
* Connected to web-svc.emojivoto (10.107.19.52) port 80 (#0)
> GET /api/list HTTP/1.1
> Host: web-svc.emojivoto
> User-Agent: curl/7.59.0
> Accept: */*
>
< HTTP/1.1 200 OK
< content-type: application/json; charset=UTF-8
< date: Fri, 29 Nov 2019 23:22:32 GMT
< transfer-encoding: chunked
```

An injected pod won't be able to talk to other injected pods:
```
kubectl exec -it curl-7f95465569-rwtr7 -- /bin/sh
Defaulting container name to curl.
Use 'kubectl describe pod/curl-7f95465569-rwtr7 -n default' to see all of the containers in this pod.
# curl -v web-svc.emojivoto
* Rebuilt URL to: web-svc.emojivoto/
*   Trying 10.107.19.52...
* TCP_NODELAY set
* Connected to web-svc.emojivoto (10.107.19.52) port 80 (#0)
> GET / HTTP/1.1
> Host: web-svc.emojivoto
> User-Agent: curl/7.59.0
> Accept: */*
>
< HTTP/1.1 503 Service Unavailable
< content-length: 0
< date: Fri, 29 Nov 2019 23:18:26 GMT
<
* Connection #0 to host web-svc.emojivoto left intact
```

Some of the key CLI commands no longer work:
```
linkerd -n emojivoto stat po
Error: StatSummary API error: server_error: server error: 503

linkerd -n emojivoto edges po
Error: Edges API response error: server_error: server error: 503

linkerd -n emojivoto tap pod
# hang indefinitely

linkerd -n emojivoto top pod
# hang indefinitely
```

No new pods can be successfully created:
```
kubectl describe po nginx-749654d689-ckrjw
 linkerd-proxy:
    Container ID:  containerd://d688bcb39f963d7be22ee3d80747f743842195fe5a7deae13e0c150c4a34ae5c
    Image:         gcr.io/linkerd-io/proxy:edge-19.11.3
    Image ID:      gcr.io/linkerd-io/proxy@sha256:124d2856ece04c94f2b52063d1cdf1065863d2f0e010b0348a60098bd143746a
    Ports:         4143/TCP, 4191/TCP
    Host Ports:    0/TCP, 0/TCP
    State:         Waiting
      Reason:      CrashLoopBackOff
    Last State:    Terminated
      Reason:      Error
      Message:     time="2019-11-29T23:16:13Z" level=info msg="running version edge-19.11.3"
time="2019-11-29T23:16:13Z" level=info msg="Using with pre-existing key: /var/run/linkerd/identity/end-entity/key.p8"
time="2019-11-29T23:16:13Z" level=info msg="Using with pre-existing CSR: /var/run/linkerd/identity/end-entity/key.p8"
Invalid configuration: invalid environment variable

      Exit Code:    64
      Started:      Fri, 29 Nov 2019 15:16:13 -0800
      Finished:     Fri, 29 Nov 2019 15:16:13 -0800
```

`kubectl get pod` will show that everything is in the `RUNNING` state:
```
kubectl -n linkerd get po
NAME                                     READY   STATUS    RESTARTS   AGE
linkerd-controller-fb4fc54dc-gwpkg       2/2     Running   0          21m
linkerd-destination-848c5f7c78-9tk82     2/2     Running   0          21m
linkerd-grafana-66ffc7d4fb-997mt         2/2     Running   0          21m
linkerd-identity-79cbd67d55-q646w        2/2     Running   0          21m
linkerd-prometheus-5f78db76f-qxg48       2/2     Running   0          21m
linkerd-proxy-injector-dc89768d8-lzkcv   2/2     Running   0          21m
linkerd-sp-validator-56479fd7b9-68w2r    2/2     Running   0          21m
linkerd-tap-5b9dc78dcd-pgsjw             2/2     Running   0          21m
linkerd-web-7f474b56b6-t6qdh             2/2     Running   0          21m

kubectl -n emojivoto get po
NAME                        READY   STATUS    RESTARTS   AGE
emoji-786c5d657f-lwr4v      2/2     Running   0          20m
vote-bot-7bd97dfbdc-ghvhf   2/2     Running   0          20m
voting-6f888b8bd-78b2v      2/2     Running   0          20m
web-76968bc99-9vpx9         2/2     Running   0          20m
```




Attempt to install the control plane with expired trust root and/or issuer certificate will fail with the following errors:
```
linkerd install --identity-trust-anchors-file=expired-ca.crt --identity-issuer-certificate-file=expired-issuer.crt --identity-issuer-key-file=expired-issuer.key --identity-issuance-lifetime=1m
Error: invalid credentials: x509: certificate has expired or is not yet valid
```

**Comment by zaharidichev** [comment]
@ihcsim 

So I gave all this a shot as well and I found out some interesing things. I tested two scenarios in particular. Actually I sterted off generating the certificates using the steps identified [here](https://linkerd.io/2/tasks/generate-certificates/). So I end up with root cert and intermeddiate cert. The two scenarios are as follows: 

**expired root cert - non expired intermeddiate cert**
Seems like everything works as normal. Identity service is issuing valid certificates, proxy does not emit error logs, cli commands to not hang

**expired root cert - expired intermeddiate cert**
I see the same errors in the proxy log as @ihcsim. Tap and top work however. Stat and edge error out...

**Comment by ihcsim** [comment]
Following this morning's discussion, there are 3 issues to be added to the 2.7 list:

1. The `identity` service should perform a validity check on the issuer certificate prior to signing the CSRs. See https://github.com/linkerd/linkerd2/issues/3779
1. Document the crypto digital signature algorithm (ECDSA/P-256) supported by the Linkerd mTLS. See https://github.com/linkerd/website/issues/598
1. Continue to build on top of the `linkerd check [--proxy]` command to provide validation and feedback during the trust root rotation process

**Comment by ihcsim** [comment]
Closing this as all the actionable issues have been created, per https://github.com/linkerd/linkerd2/issues/3676#issuecomment-561023446.
