### ISSUE TITLE
Update the 'upgrade' command to support the identity issuer flags

### ISSUE THREAD

**Issue by ihcsim** [linkerd/linkerd2#3677]
In order to allow users to rotate the existing trust root and issuer's key/cert pair, the `upgrade` command need to be updated to support the following install-only flags:

```
--identity-issuer-certificate-file string   A path to a PEM-encoded file containing the Linkerd Identity issuer certificate (generated by default)
--identity-issuer-key-file string           A path to a PEM-encoded file containing the Linkerd Identity issuer private key (generated by default)
--identity-trust-anchors-file string        A path to a PEM-encoded file containing Linkerd Identity trust anchors (generated by default)
--identity-trust-domain string              Configures the name suffix used for identities. (default "cluster.local")
```

If these flags aren't provided, `upgrade` should retain the current behaviour of preserving the `linkerd-config` config map and `linkerd-identity-issuer` secret from the control plane. 

If present, then `upgrade` should only replace the trust root in the identity context of the existing `linkerd-config` config map. All other existing data within the config map should be retained. The `linkerd-identity-issuer` secret can be replaced entirely.

Relevant #3452.

**Comment by adleong** [comment]
If the trust root is replaced, will the data plan need to be rolled?  Is this kind of upgrade necessarily a "downtime" deploy?

**Comment by ihcsim** [comment]
Yes, the data plane will need to be rolled. Do you know if existing proxies will fall back to non-mTLS communication, when mTLS failed? It's one of the items we want to investigate, in order to understand the impact. @cpretzer and I are going to put together some documentation on the manual cert rotation process.

**Comment by grampelberg** [comment]
I do not want to make it possible to update `--identity-trust-anchors-file` or `--identity-trust-domain` during an upgrade. Updating those should require a total reinstall.

**Comment by zaharidichev** [comment]
So I outlined some steps in https://github.com/linkerd/website/pull/595 that go through the manual process. What is the decision about this issue. Do we agree that we are not exposing such options to upgrade ?

**Comment by ihcsim** [comment]
We will only add:
```
--identity-issuer-certificate-file string   A path to a PEM-encoded file containing the Linkerd Identity issuer certificate (generated by default)
--identity-issuer-key-file string           A path to a PEM-encoded file containing the Linkerd Identity issuer private key (generated by default)
```

**Comment by ihcsim** [comment]
@zaharidichev After chatting with @grampelberg further about https://github.com/linkerd/website/pull/595, can we add the `--identity-trust-anchors-file` flag to `upgrade` too? Then users won't have to use `linkerd upgrade --from-manifests`, removing the needs to manually get the config map YAML using `kubectl`.

It will also allow us to reuse the identity context validation logic in install.

Example usage:
```
$ linkerd upgrade --identity-trust-anchors-file=foobar.crt --identity-issuer-certificate-file=issuer.crt --identity-issuer-key-file=issuer.key
# output upgrade YAML
---

√ You're on your way to upgrading Linkerd!
Visit this URL for further instructions: https://linkerd.io/upgrade/#nextsteps

Provided trust anchors file would break existing proxies. See https://linkerd.io/fixme for more information
```

LMKWYT.
