### ISSUE TITLE
Deleting a helmrelease doesn't remove the webhookconfigurations

### ISSUE THREAD

**Issue by danpalmer-niceincontact** [linkerd/linkerd2#3680]
### What is the issue?
Deleting the linkerd helmrelease does not remove the mutatingwebhookconfiguration or the validatingwebhookconfiguration.

### How can it be reproduced?
Install linkerd using helm.  use kubectl to delete the helm release.  kubectl get mutatingwebhookconfigurations -A to view the existing webhookconfiguration (same for validatingwebhookconfiguration).

### Logs, error output, etc

(If the output is long, please create a [gist](https://gist.github.com/) and
paste the link here.)

**Comment by alpeb** [comment]
Please note the proper way to delete a package installed with helm is to use `helm delete`, which will clean up the webhooks:

```bash
$ helm install --set [...] linkerd-edge/linkerd2 > /dev/null

$ kubectl get mutatingwebhookconfigurations.admissionregistration.k8s.io
NAME                                    CREATED AT
linkerd-proxy-injector-webhook-config   2019-11-06T14:28:04Z

$ helm list
NAME            REVISION        UPDATED                         STATUS          CHART                   APP VERSION     NAMESPACE                                                                                                            
washed-donkey   1               Wed Nov  6 09:28:03 2019        DEPLOYED        linkerd2-19.10.5        edge-19.10.5    default                                                                                                              

$ helm delete --purge washed-donkey
release "washed-donkey" deleted

$ k get mutatingwebhookconfigurations.admissionregistration.k8s.io 
No resources found.
```

**Comment by grampelberg** [comment]
If you'd like to delete linkerd using kubectl, I would recommend using:

```
helm template | kubectl delete -f -
```

Note: deleting the linkerd namespace alone is likely to cause unfortunate interactions with your cluster because of the mutating webhook configurations and apiservices. An easy way to clean linkerd up is to run `linkerd install --ignore-cluster | kubectl delete -f -`.
