### ISSUE TITLE
Define workflow to bundle identity trust root

### ISSUE THREAD

**Issue by ihcsim** [linkerd/linkerd2#3683]
To enable graceful rotation of the identity trust root for ~pre-2.7~ control planes, we need to identify the workflow (with documentation, tooling etc.) to bundle the existing trust root with new certificates.

General workflow:

1. Add new cert to trust root
1. Roll the data plane to pick up the new trust root
1. Use the new trust root to issue a new issuer credentials
1. Remove the old certificate from the trust root
1. Re-roll the data plane to pick up the updated trust root

Testing is needed to confirm if we can just add/append the new cert to the trust root, essentially, updating its chain. This will require fetching and updating the identity context data in the `linkerd-config` config map. 

Question:

1. Shall we expose the `--identity-trust-anchors-file` option to the `upgrade` command, use the `linkerd upgrade --from-manifests` command, or do this manually with `kubectl`? The last option might be error prone as the identity context is part of the `config.Global` data represented as a single-line JSON.

See https://github.com/linkerd/linkerd2/issues/3677 for changes to the `upgrade` command to support the rotation of the issuer certificate.

**Comment by adleong** [comment]
There are a variety of ways to do this which range from totally manual to mostly automated.  For contrast, here's what an automated solution might look like:

We provide a `linkerd rotate start` command which outputs the manifest for a `linkerd-rotate` controller job.  Users use `linkerd rotate start | kubectl apply -f -` to begin the rotation.  The job starts by generating a new root key and CA and adding the new CA to the trust root in the linkerd-config.  Users can call `linkerd rotate status` to get the current status of the rotation and to see what the new steps are.  At this point, `linkerd rotate status` will inform the user they need to roll their data plane to pick up the new trust root.  The rotation job will be monitoring the data plane and will detect when all proxies have the correct trust roots and will then proceed to issue a new issuer certificate and key, and replace the issuer secret.  Once this is done, the job will remove the old CA from the trust root.  Finally, `linkerd rotate status` will inform users that they need to roll their data plane again to purge the old trust root.  Once the rotation job detects that this is complete, the job terminates.

**Comment by adleong** [comment]
A less automated solution would involve standalone `linkerd` commands which accomplish each of the steps above.  One wrinkle here is that we have to somehow persist state across invocations of `linkerd`.  i.e. the command which generates the new trust root also has to persist the key somewhere so that a subsequent command can generate the issuer certificate.

**Comment by ihcsim** [comment]
I am a bit hesitant to introduce another component into the control plane to deal with keys and certs. In this scenario, I think we should encourage/help users to transition from relying on the auto-generated trust root to one that they manage.

I think rotating the trust root in the control plane's config map can be accomplished by using the CLI, either with a new command, a new subcommand or a flag of `upgrade`. It will need to fetch the existing config map, parse and update the existing identity context, and save the new changes.

Rolling the data plane will be a bit interesting. I wonder if this is an opportunity to implement a generic proxy auto-upgrade mechanism that @olix0r talked about in https://github.com/linkerd/linkerd2/issues/2339#issuecomment-498909604. The idea behind that is proxy can opt-in to be upgraded via annotation. We introduced a new controller to watch for certain events, and rolling-update the data plane accordingly.

**Comment by adleong** [comment]
> I think rotating the trust root in the control plane's config map can be accomplished by using the CLI

This needs to be fleshed out in more detail because it's more complicated than just replacing the trust root.  The same root key that corresponds to the new trust root needs to be used to generate the new issuer certs.  But those can only be replaced after the data plane has been rolled.  So we need to give more thought to the exact process that a user would go through, including generating and saving certs and keys.

**Comment by adleong** [comment]
This is a really intricate and error prone process.  To help make sure users don't shoot themselves in the foot, I think there's a lot of checking we can do at every step in the process.  To this end, I think it makes sense to have a dedicated linkerd CLI subcommand which I'll call `trust`.  Here's how the process could work:

## 1: Generate new trust root and issuer material.  

Users run `linkerd trust generate` which generates a brand new issuer key and certificate.  It saves these to files in the local working directory and outputs the names of the files it has created.  Flags which modify how these are generated such as `--identity-issuance-lifetime` may be used.

## 2: Users check the current state of their system

Users run `linkerd trust list` which lists all trust roots in their trust root bundle and metadata about them.

```
$ linkerd trust list
Id             Name                           Expires 
3046022100b4bc identity.linkerd.cluster.local Oct 27 17:45:48 2020  (issuer)
```

Id is the first 7 bytes of the certificate's signature, name is the subject common name, and expires is the validity not after.  The (issue) tag means that this is the certificate currently used by the identity service as the issuer certificate.

## 3: Users add a new trust root to the bundle

Using the `trustroot.pem` certificate generated in step 1, users add this to their bundle using the `linkerd trust add` command.

```
$ linkerd trust add trustroot.pem
Id             Name                           Expires 
3046022100b4bc identity.linkerd.cluster.local Oct 27 17:45:48 2020  (issuer)
3cf5b8bfd57bb6 identity.linkerd.cluster.local Nov 8 16:02:19 2020
```

## 4: Users roll their data plane

Reinjecting the data plane will use the new trust bundle which includes both root certs to be distributed to the proxies.

## 5: Users update the issuer

Now that the proxies are configured with both roots, it is safe to update the issuer secret to the new certificate and key.  Users do this with the `linkerd trust set-issuer` command passing in the id of the cert they want to use and the private key file generated in step 1.

```
$ linkerd trust set-issuer 3cf5b8bfd57bb6 trustkey.pem
```

This is a critical step.  Before doing anything, this command will verify that all proxies in the data plane have a trust root bundle which includes the specified root certificate.  If this is not the case, the command will fail and instruct the user to update the appropriate pods.  We might consider supporting a `--force` option to bypass this check or some kind of `--exclude` flag to exclude certain resources from this check.  If the check is successful, the command will replace the issuer secret with the specified cert and key.  After running this step, this is what `linkerd trust list` will look like:

```
$ linkerd trust list
Id             Name                           Expires 
3046022100b4bc identity.linkerd.cluster.local Oct 27 17:45:48 2020
3cf5b8bfd57bb6 identity.linkerd.cluster.local Nov 8 16:02:19 2020 (issuer)
```

Notice that the newer certificate is now marked as the (issuer).

## 6: Remove the old trust root

It is now safe to remove the old trust root from the bundle.

```
$ linkerd trust remove 3046022100b4bc
Id             Name                           Expires 
3cf5b8bfd57bb6 identity.linkerd.cluster.local Nov 8 16:02:19 2020 (issuer)
```

Importantly, it is not allowed to remove the issuer certificate and attempting to do so will result in an error.

## 7: Roll the data plane again

Reinjecting the data plane will remove the old certificate from the trust root bundles in the proxies.

A `linkerd check --proxy` check should be added to verify that the trust root bundle in the proxies matches the trust root bundle in the linkerd config.  A mismatch indicates that you need to roll your data plane to propagate these changes to your proxies.

**Comment by zaharidichev** [comment]
I have tried to put together some docs of how that could be done in a more manual fashion, without relying on tools that we implement. 

https://github.com/linkerd/website/pull/595

**Comment by ihcsim** [comment]
See linkerd/website#595.
