### ISSUE TITLE
Mutatingwebhookconfiguration does not retry after all worker nodes terminate.

### ISSUE THREAD

**Issue by danpalmer-niceincontact** [linkerd/linkerd2#3688]
### What is the issue?
When all worker nodes are terminated at the same time a namespace that doesn't contain the config.linkerd.io/admission-webhooks: disabled label will not schedule pod deployments.  I believe this is due to the mutatingwebhookconfiguration not retrying after the cluster restart.  If I delete the mutatingwebhookconfiguration the pods come up.

### How can it be reproduced?
Deploy linkerd ha to a cluster with multiple worker nodes.  Include a namespace without the admission-webhook label that has a pod deployment.  Terminate all of the worker nodes at the same time and wait for them to come back up.  Any namespace that has the label should launch but other namespaces without the label will not.

### Logs, error output, etc
Error creating: Internal error occurred: failed calling webhook "linkerd-proxy-injector.linkerd.io": Post https://linkerd-proxy-injector.linkerd.svc:443/?timeout=30s: context deadline exceeded (Client.Timeout exceeded while awaiting headers)

#### `linkerd check` output

```text
Note - the linkerd check is the same before and after the nodes are terminated.

kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-api
-----------
√ control plane pods are ready
√ control plane self-check
√ [kubernetes] control plane can talk to Kubernetes
√ [prometheus] control plane can talk to Prometheus
√ no invalid service profiles

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ control plane is up-to-date
√ control plane and cli versions match

Status check results are √
```

### Environment
- Kubernetes Version:
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:41:55Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.12-eks-c500e1", GitCommit:"c500e11584c323151d6ab17526d1ed7461e45b0c", GitTreeState:"clean", BuildDate:"2019-10-22T03:11:52Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}
- Cluster Environment: (GKE, AKS, kops, ...)
AWS EKS - 1.13
AWS CNI - 1.5.3
- Linkerd version:
Client version: stable-2.6.0
Server version: stable-2.6.0

### Possible solution
1. Webhook retries on an interval or recognizes worker node failure and triggers a retry.
2. Ability to recreate the webhook after deletion.

### Additional context
Thomas Rampelberg is aware of the issue.

**Comment by grampelberg** [comment]
@danpalmer-niceincontact have you opened a k8s issue yet to retry MWCs?
