### ISSUE TITLE
Small spacing issue with the CallToAction banner on the control plane dashboard

### ISSUE THREAD

**Issue by klingerf** [linkerd/linkerd2#3690]
When I install the linkerd control plane in my cluster, and open the dashboard before injecting any of my pods, the "Control Plane" page shows me a call to action that looks like this:

![image](https://user-images.githubusercontent.com/9226/68442216-3504b300-0185-11ea-93bc-d456d9d13b9f.png)

The banner is sitting flush with the headers below it, but I suspect it would be better to space it out a bit.

**Comment by aliariff** [comment]
Hi @klingerf 

I am interested in fixing this. I am going to see if the problem still exists in the latest release.

**Comment by aliariff** [comment]
I can confirm that the issue still exists in the latest release.

![image](https://user-images.githubusercontent.com/6806035/75177610-d0229800-5736-11ea-950f-0a486cfd97dc.png)

@ihcsim I would like to try to fix this issue. Could you assign this to me?
