### ISSUE TITLE
Question: Should the `--identity-*-file` flags be removed?

### ISSUE THREAD

**Issue by adleong** [linkerd/linkerd2#3711]
Now that Linkerd supports the `--identity-external-issuer` flag, does it make sense to continue to support the `--identity-*-file` flags?  I believe that users who want to manually supply their own certs could do so by putting those files into a secret and using the `--identity-external-issuer` flag.  

This has a few advantages:

* allows users to rotate their certificates simply by updating the secret rather than by using `linkerd install` or `linkerd upgrade`
* fewer flags for `linkerd install` makes it simpler
* fewer different codepaths for setting up and managing certificates makes the code simpler and easier to maintain

Does it make sense to start a deprecation process for these flags?  Or are they still valuable enough to justify the complexity cost?

**Comment by zaharidichev** [comment]
@adleong This does make sense. I kind of suspect that this will have an impact on ergonomics a bit. Imagine the the users have their certs in files. Now they need to go an create a secret in the correct namespace, etc. I feel some people might find that a bit annoying. What if we have a separate command for managing certs stored in secrets. What if we separate the logic of using your cert files into a separate upload-certs command. This will simplify the logic in the install cmd and not sacrifice UX. 

While we are at that, is it worth thinking about trying to unify the secret "scheme" and move away from  `linkerd.io/tls`

**Comment by grampelberg** [comment]
I don't mind removing the flags from `install` but it feels like they should definitely be options for the helm chart.
