### ISSUE TITLE
[Tests Improvements] Ability to consume temporary clusters on GKE

### ISSUE THREAD

**Issue by SaMnCo** [linkerd/linkerd2#3717]
Problem: The current GH Action workflow for tests consumes a persistent GKE cluster as well as local kind clusters for all integration tests. This might not cover all community cases. 

Proposed Solution - Tactical: add capability to manage the lifecycle of GKE clusters (spawn, destroy, eventual life events such as scale if it makes sense at some point) in order to increase the number of test cases that can be handled, such as (matrix testing for integration, private vs. public clusters, compliance matrix with different versions of K8s, impact of instance types...), while keep the infrastructure costs under control. 

Proposed Solution - Strategic: Add support for other clouds (AWS, Azure, DO). Will be done by separate issues. 

Note: This proposal would not impact the code of Linkerd2 itself, only elements of the GH Actions Workflow and some elements of the bin/ folder.

**Comment by grampelberg** [comment]
We'd love to do some more testing across platforms, this'll change how long tests take though. Mind jumping into #contributors on slack so we can chat out a plan?
