### ISSUE TITLE
linkerd check should fail if kube-system doesn't have annotations/labels to disable pod injection

### ISSUE THREAD

**Issue by jon-walton** [linkerd/linkerd2#3721]
## Feature Request

if the kube-system namespace doesn't have the following:

```yaml

  annotations:
    linkerd.io/inject: disabled
  labels:
    config.linkerd.io/admission-webhooks: disabled
```

`linkerd check` should fail.

I had a failure scenario similar to https://github.com/linkerd/linkerd2/issues/3606 (I was destructively testing a cluster by terminating & disabling the kubelet service and powering off the nodes).

Here's the journey of about 30 mins of troubleshooting, are you sat comfortably?

<hr />

```
NAME    STATUS     ROLES   AGE   VERSION
aks-0   NotReady   agent   35h   v1.14.8
aks-1   Ready      agent   36h   v1.14.8
aks-2   NotReady   agent   28h   v1.14.8
aks-3   NotReady   agent   28h   v1.14.8
aks-4   NotReady   agent   28h   v1.14.8
```

```
× can initialize the client
    error upgrading connection: error dialing backend: dial tcp 10.183.0.4:10250: i/o timeout
    see https://linkerd.io/checks/#l5d-existence-client for hints
```

☝️ that's a prometheus node exporter 🤷‍♂  

```
replicaset-controller  Error creating: Internal error occurred: failed calling webhook "linkerd-proxy-injector.linkerd.io": Post https://linkerd-proxy-injector.linkerd.svc:443/?timeout=30s: dial tcp 172.16.1.84:443: i/o timeout
```

☝️  all replica/daemon sets are saying something like that

```
linkerd-proxy-injector   ClusterIP   172.16.1.84
```

the service ip is correct, so dns is somewhat working 😁 

```
linkerd-proxy-injector   10.183.0.153:8443,10.183.1.150:8443,10.183.1.70:8443
```

the endpoint ips are correct for the pods and the proxy injector pods are up

```
 k -n linkerd logs linkerd-proxy-injector-58bcfcfbd5-nmhkb proxy-injector
Error from server: Get https://[node-name]:10250/containerLogs/linkerd/linkerd-proxy-injector-58bcfcfbd5-nmhkb/proxy-injector: dial tcp 10.183.0.117:10250: i/o timeout
```

the *kube-system* namespace didn't have `config.linkerd.io/admission-webhooks: disabled` or `linkerd.io/inject: disabled` and their pods can now restart

after a few minutes, everything else came back online

**Comment by grampelberg** [comment]
Great suggestion! This is really a `--ha` concern, so it should be a check that is only enabled if the cluster has that configuration and should be a warning instead of an error.
