### ISSUE TITLE
Validate incoming sidecar injection requests

### ISSUE THREAD

**Issue by scottcarol** [linkerd/linkerd2#3739]
During the Linkerd workshop, a user was updating the `booksapp` namespace to enable automatic proxy injection:
`kubectl annotate ns booksapp linkerd.io/inject=enabled`
but accidentally typed `enable` instead.

We should notify users if incoming sidecar injection requests to `linkerd.io/inject` do not have the correct `enabled` or `disabled` value.

**Comment by zaharidichev** [comment]
That sounds like a good improvement. What would the form of this notification take. Would that be just logging or emitting k8s events. Or maybe something on the website?

**Comment by tegioz** [comment]
What about using a validation admission webhook? We would reject the annotation when using the key `linkerd.io/inject` but not using a valid option (`enabled`/`disabled`), letting the user know what happened.

**Comment by ihcsim** [comment]
Sounds like that really [cool talk I attended at KubeCon](https://youtu.be/gMaGVHnvNfs), about Linkerd and policies :wink:.

**Comment by grampelberg** [comment]
We should add this as an event to the existing stream from the proxy injector. While it'd be awesome to get a validating webhook going, I'd love to see the small incremental improvement of having something like "invalid value detected" in describe.

**Comment by mayankshah1607** [comment]
Hi! I would like to take up this issue if no one's already working on it :)

**Comment by grampelberg** [comment]
@mayankshah1607 sounds good! Why don't you get a draft PR up first to make sure your approach makes sense before polishing things off?

**Comment by mayankshah1607** [comment]
@grampelberg I have opened a draft PR - https://github.com/linkerd/linkerd2/pull/3868
