### ISSUE TITLE
Dynamically get certificates from cert-manager

### ISSUE THREAD

**Issue by piontec** [linkerd/linkerd2#3745]
Currently, Helm install method assumes that the user has the certificates available as files, which is sub-optimal, as `cert-managers`'s task is to provide certificates for applications automatically. 

We should adjust Helm template to request certificates using `cert-manager`'s CRs, then use them for `linkerd2` without any user's manual intervention.

Related cert loading problem is tracked in #3741

**Comment by zaharidichev** [comment]
@piontec Currently the assumption is that the use only has the trust anchors. If you take a look at [these docs](https://linkerd.io/2/tasks/use_external_certs/#using-helm), you will see that this having all the files is not required if you use cert manager:

**Comment by piontec** [comment]
OK, so this can be simplified a little... I haven't seen this doc when I was starting. I'll try to alter my PR to reflect that.

**Comment by devsinghnaini** [comment]
@piontec  Hi I wanted to know how you will update the the root trust anchor cert with the help of helm upgrade? Is that the same process how linkerd explained in https://linkerd.io/2/tasks/manually-rotating-control-plane-tls-credentials/ ?

**Comment by grampelberg** [comment]
@devsinghnaini yup!

**Comment by RichiCoder1** [comment]
I'd still like to see being able to get the trust anchor cert entirely from cert-manager.

**Comment by grampelberg** [comment]
@RichiCoder1 we'd love to as well! In fact, that's how it works if you use the CLI. Unfortunately, helm can't use existing resources =/

**Comment by RichiCoder1** [comment]
Is there a technical reason the LinkerD couldn't create the appropriate cert-manager reasons? If not, is this something Helm 3's new [lookup](https://helm.sh/docs/chart_template_guide/functions_and_pipelines/#using-the-lookup-function) function could solve?

**Comment by piontec** [comment]
Hey!
I have a fork of that that does exactly that: first creates certs with cert-manager, then does a few nasty tricks to get it back to linkerd's config. It's available here: https://github.com/giantswarm/linkerd2-app. Unfortunately, I don't have time to bring it into the main linkerd's repo as the changes are non-trivial. But if anybody's willing to help, the fork I linked should be a good start.

**Comment by grampelberg** [comment]
@RichiCoder1 TIL that `lookup` exists. That'd solve the problem as that's all we're doing with `linkerd install` today. Sounds like it'd be an awesome PR!

**Comment by RichiCoder1** [comment]
The spirit of this ticket is effectively solved by https://github.com/linkerd/linkerd2/issues/3831 which appears to have active support and a standing PR
