### ISSUE TITLE
Respect limitRanges

### ISSUE THREAD

**Issue by michalschott** [linkerd/linkerd2#3748]
### What problem are you trying to solve?

With default install cpu/memory requests are not defined at all. When one tries to inject proxy sidecars to pods in a namespace, where limitRange is defined replicaset reports it is unable to create pods.

### How should the problem be solved?

MutatingWebHook should respect limitRange values and inject them.

### Any alternatives you've considered?

I can not imagine going through all deployments in a namespace and specify these with annotations, especially in namespaces which contain a lot of pods.

### If you can, explain how users will be able to use this. Maybe some sample CLI
output?

**Comment by ihcsim** [comment]
@michalschott Thanks for filling this issue. Will adding the `config.linkerd.io/proxy-[cpu|memory]-[request|limit]` annotations **to the namespace** be acceptable for your case? That will ensure that all the proxies within the namespace inherit that configuration. Per slack convo, this is a limitation on the K8s pre-1.15, where the K8s api server calls the Linkerd proxy injector **after** the LimitRanger controller mutated the pods with the default resource requests.

I have created #3750 to update the MWC template to take advantage of the new fixes introduced in K8s 1.15+.

**Comment by grampelberg** [comment]
It sounds like this is resolved, feel free to open up if I'm wrong @michalschott
