### ISSUE TITLE
subject information in header

### ISSUE THREAD

**Issue by daniel-garcia** [linkerd/linkerd2#3749]
### What problem are you trying to solve?
I want to be able to identify the remote service calling my service. When I receive an http/grpc call that was routed through the sidecar container, I want to know which remote service (if any) made the call. 

### How should the problem be solved?
I expect a header to be inserted by the sidecar container before my application receives the call.

### Any alternatives you've considered?
I have considered having my applications extracting service account credentials associated with the sidecar and using it to sign my requests. Then on the remote side use the subject/token review to validate that signature. 

Is there another way to solve this problem that isn't as good a solution?
See above.

### How would users interact with this feature?
Users could use this header information to know which remote services are contacting their service. Additionally, it could be used in custom authorization systems that would limit certain service to service communication (ie, policy enforcement about communication).

**Comment by ihcsim** [comment]
>  the remote service calling my service

To confirm my understanding of _remote_, are you referring to two services within the same mesh, on the same cluster, or services on two separate K8s clusters?

**Comment by grampelberg** [comment]
See #2612 for where we're tracking this right now.

**Comment by daniel-garcia** [comment]
I'm referring to two services in the same cluster.

**Comment by daniel-garcia** [comment]
Should we close this issue in favor of  #2612 ?

**Comment by grampelberg** [comment]
Sure!
