### ISSUE TITLE
Update the skip inbound and outbound ports config to support range

### ISSUE THREAD

**Issue by ihcsim** [linkerd/linkerd2#3752]
Currently, the `skip-[inbound|outbound]-ports` configuration is a comma-delimited string. It will be useful to update this to support a range of ports, for cases where the (inbound or outbound) ports are random and ephemeral.

**Comment by javaducky** [comment]
I'd like to take this one, if that's alright!

**Comment by ihcsim** [comment]
@javaducky Thanks for your interest! @dddanmar already mentioned that he'll like to take this on. Also, it might be a bit more involved that I first anticipated. Let me chat with the team about this first, and add more info here.

**Comment by javaducky** [comment]
Please disregard the above commit.  I should not have included the issue number in the commit message as it was automatically linked.  I'm simply coding a solution for "practice."

**Comment by javaducky** [comment]
@ihcsim @dddanmar Just in case, I have a fully functional patch with unit tests if you'd like it.  Hopefully I don't sound pushy as that's not my intent...I'm just excited about contributing. :)

**Comment by dddanmar** [comment]
No issues from my side!
