### ISSUE TITLE
Community iframe is not displayed properly

### ISSUE THREAD

**Issue by cynthia-sg** [linkerd/linkerd2#3764]
### What is the issue?

Browser cuts off the bottom of the posts if browser height is shorter than the height of the iframe.

### How can it be reproduced?

Open Community page on a small height browser window.

![Community](https://user-images.githubusercontent.com/1440981/69680642-ce9bf200-10ab-11ea-9996-7d9016cb26df.png)

### Possible solution

Perhaps we can use `postMessage` to get iframe height of content cross domain.

**Comment by scottcarol** [comment]
@cynthia-sg thanks for creating this issue! ⭐️ 

For some context, the actual community updates are generated from `linkerd.io` -- the (also open source) original PR that created the page is [here](https://github.com/linkerd/website/pull/214). That repo is public so feel free to dig around there as well!
