### ISSUE TITLE
Canary A/B in nginx is not routing to the canary pods

### ISSUE THREAD

**Issue by kevtaylor** [linkerd/linkerd2#3776]
### What is the issue?
The canary a/b testing suite is set up using nginx/flagger and linkerd but when attempting to
see logs appearing in the canary pods or testing the results from curl as 
`curl -s -H 'X-Canary: always' -H 'Host: app.example.com' http://<ip address of load balancer>`
the results are always from the primary pod

### How can it be reproduced?
Set up the flagger install as https://docs.flagger.app/usage/linkerd-progressive-delivery#a-b-testing
Then progress a new image 
This is using the helm install of nginx 0.26.1 and the helm install of linkerd 2.6-stable with the addition of these settings for nginx
```
controller:
  podAnnotations:
    linkerd.io/inject: enabled
  config:
    ssl-redirect: "false"
    enable-opentracing: "true"
    enable-vts-status: "false"
    zipkin-collector-host: oc-collector.tracing
    zipkin-sample-rate: "0.5"
```

### Logs, error output, etc
Nginx appears to be attempting routes
```
127.0.0.1 - [127.0.0.1] - - [02/Dec/2019:08:26:20 +0000] "GET / HTTP/1.1" 200 397 "-" "curl/7.29.0" 128 0.003 [test-podinfo-9898] [test-podinfo-canary-9898] 10.60.1.151:9898 397 0.004 200 951a40952d962a04d9d193c3f6b1c432
```
The l5d headers appear to be in nginx
```
           proxy_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:9898;
            proxy_hide_header l5d-remote-ip;
            proxy_hide_header l5d-server-id;
```
When putting linkerd proxy in nginx into debug mode it appears that the routing is to the primary pod 
```
DBUG [   504.958360s] podinfo.test.svc.cluster.local:9898 linkerd2_proxy::proxy::http::client client request: method=GET uri=http://app.example.com/ version=HTTP/2.0 headers={"x-b3-traceid": "35bca5baac8664ea", "x-b3-spanid": "03df8b068107c1cb", "x-b3-sampled": "1", "x-b3-parentspanid": "afb36db7fa7ddb4e", "x-b3-flags": "0", "host": "app.example.com", "x-request-id": "e7ec34ab7bb6dc2f36bb65031a70be62", "x-real-ip": "127.0.0.1", "x-forwarded-for": "127.0.0.1", "x-forwarded-host": "app.example.com", "x-forwarded-port": "80", "x-forwarded-proto": "http", "x-scheme": "http", "cache-control": "max-age=259200", "user-agent": "curl/7.29.0", "accept": "*/*", "x-canary": "always", "l5d-dst-canonical": "podinfo.test.svc.cluster.local:9898", "l5d-orig-proto": "HTTP/1.1"}
```

(If the output is long, please create a [gist](https://gist.github.com/) and
paste the link here.)

#### `linkerd check` output

```text
centos7:[root@localhost kubernetes-cluster]$ linkerd check
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-api
-----------
√ control plane pods are ready
√ control plane self-check
√ [kubernetes] control plane can talk to Kubernetes
√ [prometheus] control plane can talk to Prometheus
√ no invalid service profiles

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ control plane is up-to-date
√ control plane and cli versions match

Status check results are √
```

### Environment

- Kubernetes Version: v1.14.8-gke.17
- Cluster Environment: (GKE, AKS, kops, ...) GKE
- Host OS: Linux
- Linkerd version: 2.6-stable

**Comment by alpeb** [comment]
I tried using the exact same setup you have but I couldn't reproduce the issue
![image](https://user-images.githubusercontent.com/554287/69978713-ee437800-14fa-11ea-8f01-1b32aeb00dc1.png)
```bash
$ helm list
NAME            REVISION        UPDATED                         STATUS          CHART                   APP VERSION     NAMESPACE    
kissing-peacock 1               Mon Dec  2 11:46:27 2019        DEPLOYED        linkerd2-2.6.0          stable-2.6.0    default      
loping-arachnid 1               Mon Dec  2 11:48:58 2019        DEPLOYED        nginx-ingress-1.26.1    0.26.1          ingress-nginx
```
The only thing that strikes me different are the ngxinx controller proxy logs, that show the destination's IP instead of the hostname like in your example:
```
DBUG [   475.696815s] 10.24.0.27:9898 linkerd2_proxy::proxy::http::client client request: method=GET uri=http://app.example.com/ version=HTTP/1.1 headers={"x-b3-traceid": "6d4982744ff4e8c5", "x-b3-spanid": "65dbbe9754dc9a98", "x-b3-sampled": "1", "x-b3-parentspanid": "cb02eee311fb13bf", "x-b3-flags": "0", "host": "app.example.com", "x-request-id": "83839288e27c1a986ae7b33e84155aa7", "x-real-ip": "127.0.0.1", "x-forwarded-for": "127.0.0.1", "x-forwarded-host": "app.example.com", "x-forwarded-port": "80", "x-forwarded-proto": "http", "x-scheme": "http", "accept": "*/*", "user-agent": "curl/7.64.0", "l5d-dst-canonical": "app.example.com:80"}
```

**Comment by kevtaylor** [comment]
The ip address that is in your debug trace is a primary pod, so I am very confused by that

**Comment by kevtaylor** [comment]
@alpeb please can you post the server section from your nginx conf so that I can compare.

**Comment by kevtaylor** [comment]
Comparing the 2 debug traces there are also differences in the l5d-dst canonical

**Comment by grampelberg** [comment]
Can you share your flagger configuration as well?

**Comment by kevtaylor** [comment]
My flagger manifest is the one on the website

**Comment by kevtaylor** [comment]
The only thing I have different is the nginx configmap

**Comment by grampelberg** [comment]
I was able to replicate with that flagger configuration. From the docs:

> When using an ingress controller, the Linkerd traffic split does not apply to incoming traffic since NGINX in running outside of the mesh. In order to run a canary analysis for a frontend app, Flagger creates a shadow ingress and sets the NGINX specific annotations.

If you'd like this to work, you'll want to un-inject your nginx ingress controller. As there is no TrafficSplit created, Linkerd is routing to what is set with `l5d-dst-override` every time. 

For a more long term fix, you'll want to open an issue with ingress-nginx to make the header override work correctly by ingress which isn't happening right now.

**Comment by alpeb** [comment]
@grampelberg each ingress (base and canary (automatically generated)) should set its own `l5d-dst-override`. It works for me...

**Comment by grampelberg** [comment]
@alpeb yeah, but the nginx controller only renders a single section of `nginx.conf` and the canary bits are handled as part of `balancer.lua` which doesn't actually set the header correctly because it is being forced in the nginx config and not as part of the lua settings.

**Comment by kevtaylor** [comment]
@alpeb did you override any nginx helm settings. It does look like your nginx is meshed, so please can you share anything you altered?

**Comment by alpeb** [comment]
@kevtaylor turns out I had a typo in my ingress, which as a side effect was making connections to skip the linkerd proxy, and things were apparently working, but outside the mesh. So @grampelberg's conclusion above still applies.

**Comment by dhananjaya-senanayake** [comment]
Nginx canary-by header does not work with linkerd sidecar.

**Comment by grampelberg** [comment]
@dhananjaya-senanayake that is correct. Check out the latest edge if you'd like to see it work (note you'll want to remove the `l5d-dst-override` header).

**Comment by dhananjaya-senanayake** [comment]
> @dhananjaya-senanayake that is correct. Check out the latest edge if you'd like to see it work (note you'll want to remove the `l5d-dst-override` header).

Removing `l5d-dst-override` header makes the traffic from nginx ingress controller to pods removed from the service mesh. (No mTLS).

**Comment by grampelberg** [comment]
> Removing l5d-dst-override header makes the traffic from nginx ingress controller to pods removed from the service mesh. (No mTLS).

This is not the case any longer in the latest edge.

**Comment by dhananjaya-senanayake** [comment]
@grampelberg , currently we are using the latest stable release. 
- Any idea on the timeline when [this](https://github.com/linkerd/linkerd2/releases/tag/edge-20.10.3) would be available in stable releases ? 
- When the `l5d-dst-override` header is no longer honoured how is the integration of nginx ingress controller happened with linkerd service mesh ? Please share if any doc is available like https://linkerd.io/2/tasks/using-ingress/#nginx
