### ISSUE TITLE
Add pre-sign check for the identity service

### ISSUE THREAD

**Issue by ihcsim** [linkerd/linkerd2#3779]
Following https://github.com/linkerd/linkerd2/issues/3676#issuecomment-559910383 and https://github.com/linkerd/linkerd2/issues/3676#issuecomment-560359724, it looks like the `identity` service continues to sign the proxy CSR and issue new TLS certs, even after the issuer certificate is expired. 

The [`Certify()`](https://github.com/linkerd/linkerd2/blob/66a74b23a72f7ca07d907a1a7d0504c534f6bdbb/pkg/identity/service.go#L191-L200) function should be updated to check the isser certificate validity prior to signing CSR. If expired, the function should return an error.

To reproduce:

Create short-lived trust root and issuer certificates:
```
step certificate create identity.linkerd.cluster.local ca.crt ca.key --insecure --no-password --profile=root-ca --not-after=5m

step certificate create identity.linkerd.cluster.local issuer.crt issuer.key --ca=ca.crt --ca-key=ca.key --insecure --no-password --profile=intermediate-ca --not-after=5m
```

Install Linkerd with the new certs and a short issuance lifetime:
```
linkerd install --identity-trust-anchors-file=ca.crt --identity-issuer-certificate-file=iissuer.crt --identity-issuer-key-file=issuer.key --identity-issuance-lifetime=1m | k apply -f -
```

Install the emojivoto app and watch its logs after the cert expired:
```
linkerd inject  https://run.linkerd.io/emojivoto.yml | k apply -f -

k -n emojivoto logs -f emoji-786c5d657f-t2bbt linkerd-proxy 
...
ERR! [  1381.575184s] linkerd2_proxy_identity::certify Received invalid ceritficate: invalid certificate: UnknownIssuer
ERR! [  1391.584934s] linkerd2_proxy_identity::certify Received invalid ceritficate: invalid certificate: UnknownIssuer
ERR! [  1401.594683s] linkerd2_proxy_identity::certify Received invalid ceritficate: invalid certificate: UnknownIssuer
....
```
(Adding debugging statement to  [`Certify()`](https://github.com/linkerd/linkerd2/blob/66a74b23a72f7ca07d907a1a7d0504c534f6bdbb/pkg/identity/service.go#L191-L200) will show that the CSRs continued to be signed.)

**Comment by zaharidichev** [comment]
That will get addressed in #3696
