### ISSUE TITLE
Persistent spike in CPU usage

### ISSUE THREAD

**Issue by MSLaguana** [linkerd/linkerd2#3785]
Issue Type:

- [x] Bug report
- [ ] Feature request

**What happened**:
A linkerd sidecar container for an nginx ingress controller started using significant amounts of CPU, around 70% of the node's CPU. Looking at logs for the container, I saw
>linkerd2_proxy::app::errors unexpected error: error from user's Payload stream: error reading a body from connection: end of file before message length reached

repeated a couple of times.

I redeployed a new ingress controller and the new one seems to be fine, but I'm not sure whether it will happen again.

**What you expected to happen**:
I expect that CPU usage is proportional to the load, while this was a hockeystick up and then it remained up for several hours (without any significant application load) until I took action

**How to reproduce it (as minimally and precisely as possible)**:
Unknown; 

**Anything else we need to know?**:

**Environment**:
- linkerd/namerd version, config files:
>Client version: stable-2.5.0
Server version: stable-2.5.0
- Platform, version, and config files (Kubernetes, DC/OS, etc):
>Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.12", GitCommit:"524c3a1238422529d62f8e49506df658fa9c8b8c", GitTreeState:"clean", BuildDate:"2019-11-14T05:26:24Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
  Running in azure AKS on D2 nodes

**Comment by grampelberg** [comment]
Are you using the default backend? I could see this happening if you get some rules that don't have the override annotation looping back into the controller.

**Comment by MSLaguana** [comment]
Which backend are you referring to? I'm configuring my ingress to be linkerd aware via

```
    kubectl.exe get deployment -n ingress -o yaml `
        | linkerd.exe inject - `
        | kubectl.exe apply -f -
```

and my ingress controller is installed via helm using the nginx-ingress configuration.

**Comment by grampelberg** [comment]
@MSLaguana https://kubernetes.github.io/ingress-nginx/user-guide/default-backend/

Because you can't set the headers for that, it is possible there's a tight loop of requests coming back to the ingress controller. It is super easy to disable with them (`defaultBackend.enabled=false`).

**Comment by MSLaguana** [comment]
Looking at the helm chart, it suggests that if I disable the `defaultBackend` I need to provide a `defaultBackendService`. Are you suggesting that isn't the case, and absent default backend it can just drop un-routed requests?

**Comment by grampelberg** [comment]
Yup.

**Comment by MSLaguana** [comment]
I'll give that a try. Thanks!

**Comment by MSLaguana** [comment]
I haven't seen this happen again, so I'm willing to believe that's had an effect.

**Comment by grampelberg** [comment]
Great! Keep your eyes open and update if you see it again. We've got some plans in the near future to make the whole ingress experience better!

**Comment by MSLaguana** [comment]
I'm afraid that this has come back again. Is there any diagnostic you'd like me to run before I restart the pod?

**Comment by grampelberg** [comment]
@cpretzer any good suggestions?

**Comment by cpretzer** [comment]
@MSLaguana let's start by looking at the ingress controller logs, linkerd proxy logs, proxy metrics, and traffic profile.

The ingress controller and proxy logs can be obtained with the `kubectl logs` command on the pod.

The proxy metrics can be pulled by port forwarding to port 4191 on the pod and making a request to the `metrics` endpoint:

`kubectl port-forward <pod name> 4191 && \
  curl http://localhost:4191/metrics`

More info here: https://linkerd.io/2/reference/proxy-metrics/

For the traffic profile, the grafana dashboard for the ingress pod will be a good place to start. I'm particularly interested in whether the CPU spike is associated with a traffic spike or deployment. You can get to grafana from the linkerd dashboard.

**Comment by MSLaguana** [comment]
I got some of this data yesterday after talking with @grampelberg on slack, but I have since restarted the pod so I can't get new information at the moment. There was no deployment, and no notable spike in legitimate traffic. From the ingress controller logs it does seem that the CPU spike in the linkerd container started approximately at the same time as some malicious/probing requests came to the nginx controller, but it responded ~400 to all of them.

The linkerd logs didn't show a lot, but did reference 

>WARN [801478.975635s] linkerd2_proxy::proxy::http::canonicalize failed to refine `<REDACTED>`: deadline has elapsed; using original name
ERR! [837896.081176s] linkerd2_proxy::app::errors unexpected error: error from user's Payload stream: error reading a body from connection: end of file before message length reached

where the `<REDACTED>` is a domain that I have no relation to, and searching online suggests is malicious. I don't see that domain appearing anywhere in the nginx logs, just once in the linkerd-proxy logs. The nginx logs did show a good chunk of not-actually-http traffic, like instead of `GET /foo` it would just be a bunch of non-ascii characters, so I wonder if something is making a non-http[s] connection that looks like something linkerd wants to handle but isn't valid?

I didn't query the metrics endpoint at the time, but I did bump the logging verbosity up to `debug` for a while. I didn't see anything jump out at me from it, although it did seem to be handling connections every few seconds (and they didn't correspond to requests showing up in the nginx log).

If this happens again, I'll check out the metrics endpoint, and check grafana for traffic.

**Comment by cpretzer** [comment]
@MSLaguana this is an interesting hypothesis. I think we'd have to inspect one of these requests to see what is actually happening.

> so I wonder if something is making a non-http[s] connection that looks like something linkerd wants to handle but isn't valid?

If it is traffic coming from a malicious site, then the best thing might be to filter the traffic using a firewall, so that it doesn't make it to the ingress controller.

**Comment by MSLaguana** [comment]
I was hoping to be able to avoid that since I'd like my service to be broadly accessible, and would rather not play whack-a-mole with ip filtering. That said, I haven't seen this happen again since when I last re-opened this issue, so it doesn't seem to be super common, and I have an alert so I should be able to catch it shortly after it happens which may possibly provide some more insights.

**Comment by cpretzer** [comment]
Sounds good, please update this issue if/when it happens again.

**Comment by ericsuhong** [comment]
We have encountered this issue on our cluster as well. We found that two linkerd-proxy containers from five nginx-ingress-controller pods suddenly started to consume 100% of CPUs:

![image](https://user-images.githubusercontent.com/3857851/80297203-eef0db00-8735-11ea-8e09-3d3feaf360ce.png)

The funny thing is, this is a test cluster with ZERO production traffic. When I look at nginx logs, there are only super minimal gibberish traffic, and I cannot find any relevant traffic around that timestamp.

This is suggesting that Linkerd-proxy is going into infinite or tight loop in some rare cases on its own.

We are using Linkerd 2.7.0.

**Comment by grampelberg** [comment]
@ericsuhong are you using the default backend at all? I've seen this happen when the ingress going into a tight loop. The proxy does discovery by authority (host header) and if it is a public address, the request goes back to the same set of pods.

It'd also be worth upgrading to 2.7.1 if you've got the chance.

**Comment by ericsuhong** [comment]
@grampelberg @MSLaguana mentioned that the issue was not resolved after they disabled default backend. Also, we cannot upgrade to 2.7.1 due to https://github.com/linkerd/linkerd2/issues/4274 right now.

**Comment by ericsuhong** [comment]
@grampelberg Do you actually recommend us to disable defaultBackend? We do not like the error page being returned without defaultBackend, and we rather keep the defaultBackend.

**Comment by grampelberg** [comment]
@ericsuhong I'd take a look at your access logs first to understand what's going on in nginx. Any pointers to what's happening can help us come up with some solutions =)

**Comment by grampelberg** [comment]
@ericsuhong would you mind opening up a new issue? We'd like to look into this some more and should have it be separate =)

**Comment by ericsuhong** [comment]
Can't we just reopen this issue? Otherwise, I will probably create a new issue when we encounter this issue again in PROD (right now, we already restarted all the pods, and do not have any useful information to give anyways).

**Comment by grampelberg** [comment]
This was fixed by disabling default backend. It sounds like you're still having issues with default backend disabled?

**Comment by MSLaguana** [comment]
Disabling the default backend didn't fix the issue for me, it did come back again as stated in https://github.com/linkerd/linkerd2/issues/3785#issuecomment-565747837

However after I manually fixed it (redeploying the impacted ingress pod) a second time, I didn't see it happen again after that yet. I don't think it's fixed, so much as the (unknown) trigger hasn't happened for me again yet.

**Comment by ericsuhong** [comment]
We have just encountered this issue again in our Test environment. I created a separate issue to track this issue: https://github.com/linkerd/linkerd2/issues/4329

We will also enable debug log level as well, so that when this issue happens again, we can grab more verbose logs.
