### ISSUE TITLE
Remove experimental label from cni plugin

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#3796]
### What problem are you trying to solve?

It has almost been a year since we shipped the CNI plugin. In this time it has been pretty stable. Our concerns in the past were around compatibility and operation for something that was hard to test. Instead of doing all that testing, we should document what has been tested and inform users they might not have a great experience outside the support matrix.

**Comment by zaharidichev** [comment]
Certainly agree. I think we have a pretty good assurance that it works with the setup that we have tested it with. Also converting it to helm by merging[ this one](https://github.com/linkerd/linkerd2/pull/3581) would be pretty neat as well.

**Comment by grampelberg** [comment]
@zaharidichev yup, let's do both. Having a separate helm chart that you can use instead of `install-cni` feels like a great way to polish up the feature.

**Comment by ihcsim** [comment]
@grampelberg @zaharidichev Once we merge https://github.com/linkerd/linkerd2/pull/3581, I think we should consider whether to tackle the following items now, later or not at all:

1. Update CI to build/package the CNI chart, and push to helm.linkerd.io
1. Publish chart to Helm hub
1. Update the docs to show how to use the CNI chart
    * [installing Linkerd with Helm](https://linkerd.io/2/tasks/install-helm/)
    * [CNI plugin](https://linkerd.io/2/features/cni/) (just a reference to the above doc should suffice) 
1. Currently, after installing the CNI, both `linkerd check --pre` and `linkerd check` will return errors. Do we want to include a CNI check like `linkerd check --cni`? If we want to do this, I think the following status from the DaemonSet will be of interest:

```
kubectl -n linkerd describe ds linkerd-cni # on a 3-cluster node
...
Desired Number of Nodes Scheduled: 3
Current Number of Nodes Scheduled: 3
Number of Nodes Scheduled with Up-to-date Pods: 3
Number of Nodes Scheduled with Available Pods: 3
Number of Nodes Misscheduled: 0
```

**Comment by grampelberg** [comment]
@ihcsim let's create issues for 1 - 4 and add them to the backlog. 1 - 3 seem like blockers for the release, 4 depends on how much time it'll take but seems pretty good.
