### ISSUE TITLE
Add context to proxy server logs

### ISSUE THREAD

**Issue by adleong** [linkerd/linkerd2#3799]
Log lines from the proxy's server are missing context fields such as `source` and `peer`.  These context fields are present on the proxy's client logs and should be added to the server logs.

**Comment by olix0r** [comment]
I think i already have a lead on this...

**Comment by kleimkuhler** [comment]
@olix0r has linkerd/linkerd2-proxy#398 up for this

**Comment by kleimkuhler** [comment]
Closed in linkerd/linkerd2-proxy#398
