### ISSUE TITLE
Proxy task introspection

### ISSUE THREAD

**Issue by adleong** [linkerd/linkerd2#3803]
It would be useful to have some mechanism for introspecting the list of currently spawned Tokio tasks (and perhaps the time at which they were last polled).  This could be used similarly to how a thread dump or goroutine dump is used and could be used to detect and debug task leaks.  

When we see unexpected behavior in the proxy we would want to be able to see the task dump to determine if there are any task leaks.

**Comment by hawkw** [comment]
Once we're on Tokio 0.2, it will be much easier to come up with a solution for this that plugs into the rest of the stack — I'm keeping it open.
