### ISSUE TITLE
Introduce CNI post-installation checks

### ISSUE THREAD

**Issue by ihcsim** [linkerd/linkerd2#3804]
Currently, after running `linkerd install-cni`, both `linkerd check` and `linkerd check --pre` return errors, because the `install-cni` command doesn't satisfy the conditions expected by `check`. We should consider either:

1. Update `linkerd check` to not fail if the CNI resources are present, and/or
1. Introduce a `linkerd check --cni` flag for CNI users to confirm that the CNI DaemonSet is healthy

If we decided to do 2, the following status info from the DaemonSet will be of interest:
```
kubectl -n linkerd describe ds linkerd-cni # on a 3-node cluster
...
Desired Number of Nodes Scheduled: 3
Current Number of Nodes Scheduled: 3
Number of Nodes Scheduled with Up-to-date Pods: 3
Number of Nodes Scheduled with Available Pods: 3
Number of Nodes Misscheduled: 0
```

Before starting this task, please confirm scope, prioritization and estimated effort with @grampelberg.

**Comment by alpeb** [comment]
After triggering `linkerd install-cni`, `linkerd check --pre` will return errors complaining about the existence of the `linkerd-cni` ClusterRoles, among other things. Just as it would complain when running it after a vanilla `linkerd install`. So IMO `linkerd check --pre` doesn't require changes, and something like `linkerd check --cni` would be the only thing needed to check the state of things after `linkerd install-cni`. Does that makes sense?
