### ISSUE TITLE
Proxy injector should set destination lookup subnets

### ISSUE THREAD

**Issue by adleong** [linkerd/linkerd2#3807]
The `LINKERD2_PROXY_DESTINATION_GET_NETWORKS` environment variable controls which IP subnets Linkerd will do destination lookups for.  If unset, it currently defaults to `"10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"`.

To move this defaulting logic out of the proxy and into the proxy-injector, we should have the proxy injector always set this environment variable to this value.

We do not need to make this configurable through CLI flags or annotations yet, though we may want to consider this in the future.  For now, this value can be edited manually by using `--manual` injection and editing the environment variable value in the resulting yaml.

**Comment by kleimkuhler** [comment]
Should the proxy continue to make sure this value is set, and if not default to the current values (the current behavior)?

With this change only taking place in the injector, it *should* be set by the time the proxy is checking its environment, but if it is not then the proxy will do it.

**Comment by kleimkuhler** [comment]
linkerd/linker2-proxy#399 provided a temporary fix for this that is a little different from the original issue description. The proxy no longer provides default destination lookup subnets.

This can still remain open though as there should be a design discussion around making this configurable through the CLI on install.

**Comment by kleimkuhler** [comment]
@grampelberg Is this still a valuable configuration for 2.8? If so, the original issue description mentions configuring this through `--manual` injection.

Alternatively, it could be an additional flag for `linkerd inject`.

**Comment by grampelberg** [comment]
@kleimkuhler it sounds like this is more about making it configurable in the future than doing something right now. It'll be required for turning on IP based discovery but not in 2.8 yet.

**Comment by kleimkuhler** [comment]
@grampelberg Sounds good. This can be kept open, but the current labels marking it as P0 can be removed
