### ISSUE TITLE
initContainers running before linkerd-init and linkerd-proxy

### ISSUE THREAD

**Issue by robertgates55** [linkerd/linkerd2#3812]
## Bug Report
Some of my pods have an initContainer that waits for database migrations to have completed before the main containers start up. This container is required to communicate with the database pod across the mesh.

### What is the issue?
The `linkerd-init` and `linkerd-proxy` containers are stuck in the `PodInitializing` state, presumably waiting for my `wait-for-migrations` initContainer to have completed. Since this will be unable to complete until linkerd has initialised, this is unlikely to ever be the case.

I can submit full examples and information etc subsequently, but wanted to first ask - is this supposed to work? Can it ever work?

(am running `edge-19.12.1` linkerd on k8s `1.14.8`)

**Comment by grampelberg** [comment]
Could you explain a little more? If your container is running before `linkerd-init` there won't be any issues.

**Comment by rnsv** [comment]
I see a similar issue.  While searching I came across this post. I have to yet to debug this completely but thought I will post my findings here.
I am using edge-19.12.3 with CNI
With linkerd.io/inject: enabled and no init-containers everything is working as expected
The moment I add an initContainer, init container is unable to communicate outside
I tested this with the following minimalistic config with linkerd.io/inject: enabled
```
      initContainers:
        - name: test-init
          image: alpine
          command:
            - sh
            - -c 
            - sleep 100
```
Now sh into the init container and try a simple curl call like this curl -k https://192.168.0.1/
Get the following error curl: (7) Failed to connect to 192.168.0.1 port 443: Connection refused

I will continue debugging and update here.

**Comment by marratj** [comment]
Can we reopen this? I experience the same issue.

With CNI enabled, Pods that get the proxy injected the init containers of said Pods cannot open connection to the outside world.

**Comment by BlackRider97** [comment]
Is there a way to start `linkerd-init` init container before application init containers ?
I wanted to hold application until proxy is not up.

**Comment by grampelberg** [comment]
@BlackRider97 nope, the k8s pod lifecycle is not that flexible. You'll want to watch https://groups.google.com/g/kubernetes-sig-node/c/w019G3R5VsQ/m/bbRDZTv5CAAJ?pli=1 for progress on making that all work.
