### ISSUE TITLE
set Kubernetes common labels on control plane components

### ISSUE THREAD

**Issue by wmorgan** [linkerd/linkerd2#3816]
To make it easier for tools that consume these things, Linkerd should set some of the [Kubernetes common labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/) for control plane components.

In particular I think we should set:
* `app.kubernetes.io/name` to the name of the component, e.g. `prometheus` or `destination`
* `app.kubernetes.io/version` to the corresponding Linkerd version
* `app.kubernetes.io/part-of` to "Linkerd"

There are some other fields but those are IMO the important ones.

**Comment by olix0r** [comment]
@wmorgan 

> To make it easier for tools that consume these things,

Are there specific tools you care about?
