### ISSUE TITLE
Helm Charts Clean-Up

### ISSUE THREAD

**Issue by Pothulapati** [linkerd/linkerd2#3822]
As the plan is to use helm charts as the core-parts for Linkerd Add-Ons per #3794. It was also planned to make changes to follow [best-practices ](https://helm.sh/docs/topics/chart_best_practices/values/#naming-conventions) as a pre-requisite. 

The following tasks have been taken up for the same:

- [x] Make `linkerd2` chart use smaller-case values, support the same for `cli` and inject`
- [x] Make `linkerd2-cni` use smaller-case
- [x] Move common values out to `global` (in preparation for #3794 )

@ihcsim @grampelberg

**Comment by christyjacob4** [comment]
I think this can be closed in light of the merged PRs

**Comment by Pothulapati** [comment]
Yes, Thanks!
