### ISSUE TITLE
JS Unit Tests in CI may load different subdependencies than the web deployment

### ISSUE THREAD

**Issue by scottcarol** [linkerd/linkerd2#3838]
In researching CI failures @alpeb and I discovered a potential issue when running JS unit tests.

`yarn.lock` (which explicitly states the version number of each JS dependency library) is used in the Dockerfile to build the web deployment.

However in CI, the JS unit tests are run outside that container. There's no reference to any `yarn.lock` file. 

Because that lockfile is not used, the JS unit tests may load *different library versions* than the actual web deployment (since the default subdependency versions when building from `package.json` may vary).

Solution: Update the `web/bin` script to call yarn pointing to the right location of the lockfile.

**Comment by tharun208** [comment]
I like to take this up

**Comment by ihcsim** [comment]
@tharun208 It's yours! Thanks!
