### ISSUE TITLE
Proxy should recognize a new deployment of the controller and connect to it

### ISSUE THREAD

**Issue by briansmith** [linkerd/linkerd2#384]
Consider this scenerio: There is one deployment of the controller. The operator adds a second deployment of the controller (e.g. a new upgraded version) and modifies the `proxy-api` service definition to point to the second deployment. Then the operator waits for (roughly) all connections to the initial deployment to drain. Then the operator shuts down the initial deployment of the controller.

Unfortunately, the implementation of the proxy isn't 100% compatible with this migration strategy because the proxy will only do a DNS lookup and start a new connection to the controller when it doesn't have a connection to the controller. In the scenerio above, it will never (unless/until there is a network partition or other failure, or until the operator gives up and deletes the initial deployment) close its connection to the first deployment of the controller.

Instead, the proxy needs to periodically (e.g. based on the DNS TTLs for the proxy API DNS lookup) try to discover new deployments of the proxy-api service and gracefully migrate to the new deployment. Note that this is a bit harder than it appears, because every time the proxy starts a new proxy-api connection, it would have to throw away its service discovery (at least) state and reload it from the new connection. (How is this handled currently on connection failure? Do we get out of sync?) That means we do want to avoid migrating to a new connection unnecessarily.

OTOH, there are also other reason we might want to try to reconnect, other than connection failure. For example, we probably should implement latency-based and (HTTP/gRPC) error-rate-based circuit breaking for the connection between the proxy and the controller. We might even want other L7 features like load balancing over multiple connections to multiple instances of the controller.

Note that for this to work, we might need to change the proxy-api service to be headless so the controller can see the IP addresses for each pod, instead of only seeing one consistent cluster IP address for the service. (OTOH, maybe Kubernetes assigns a new Cluster IP when a service is updated to point to a new deployment? We'd need to investigate this. It's probably easier and more reliable to just make the service headless.)

**Comment by seanmonstar** [comment]
It's possible to have the controller help facilitate this switch over. There is the `ALTSVC` frame, an accepted extension to HTTP2, that the controller could send.

If the controller knows about an upgrade happening, it can send the altsvc frame signaling that the proxy should start using the new origin, and afterwards send a graceful goaway frame, and finally shutting down.

**Comment by briansmith** [comment]
> It's possible to have the controller help facilitate this switch over. There is the ALTSVC frame, an accepted extension to HTTP2, that the controller could send.

For that, every controller would need to watch the Services (and Deployments) APIs and notice when new controllers are added and when controllers are removed from the service. Then it would have to implement Alt-Svc. Then we'd have to do Alt-Svc-based implementation in the proxy. Especially since the Controller and the proxy would need to be both modified and both unit tested and then integration-tested, it doesn't seem like it would easier than just doing the alternative DNS polling.

> and afterwards send a graceful goaway frame

Also, I don't think we should rely on the connection between the controller and the proxy being HTTP/2 more than absolutely necessary. I don't know that that is something that will hold going forward, for the same reasons the CLI and the controller don't speak gRPC to each other. (There's no plan to move away from gRPC on HTTP/2; just, I don't want to add any more explicit HTTP/2 assumptions there if we can avoid it.)
