### ISSUE TITLE
Update CRD apiVersion per K8s 1.16 deprecation notes

### ISSUE THREAD

**Issue by ihcsim** [linkerd/linkerd2#3840]
CRD reached GA in K8s 1.16. The `apiVersion` field in the `serviceprofiles.linkerd.io` CRD YAML template should be updated to use the `apiextensions.k8s.io/v1`. 

Note that the definition of the structural schema using the `openAPIV3Schema` field is mandatory in `apiextensions.k8s.io/v1`. See the K8s [doc](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#specifying-a-structural-schema) for more info.

See the [service profile doc](https://linkerd.io/2/tasks/setting-up-service-profiles/) on how to test this change.

**Comment by grampelberg** [comment]
Note: this change can only happen once 1.16 is the minimum version we support (following release guidelines, that'd be 1.18 or 1.19). As of right now, the cloud providers "stable" channel is 1.13, so we definitely can't change it yet.

**Comment by saurav-malani** [comment]
@ihcsim @grampelberg can the change be done now or we have to wait? If it can be done, then I would like to take up this issue.

**Comment by ihcsim** [comment]
@saurav-malani Not yet. I'm closing this issue for now, since it's going to be a while before 1.16 becomes our minimum supported version. GKE, e.g., still supports 1.13. Likely, this issue will go stale before k8s 1.19 arrives.
