### ISSUE TITLE
Service Profile names 

### ISSUE THREAD

**Issue by derrickburns** [linkerd/linkerd2#3863]
This is request to clarify your documentation on ServiceProfiles.

The documentation states that the name of the ServiceProfile should be the value of the `:authority` field.  This is incorrect.

First, standard k8s resource names cannot have a colon.   However, the `:authority` field will have a port if a non-standard port is used. @grampelberg told me that the port number should not be included in the ServiceProfile name.  

Second, it seems to be more accurate that the name to use is the value of the `l5d-dst-override` header if it is provided or the fully qualified hostname portion of the `:authority` field.  So, when going through a gateway such as Gloo, it is the internal service name and not the external DNS name.  

Third, while my suggested description may be accurate, it may be useful to also state that ExternalName service redirections have no impact on the name to use for the ServiceProfile.

Please adjust the documentation accordingly.

**Comment by adleong** [comment]
Hi @derrickburns!  Your understanding is correct, the service profile name should not include the port number and should use the `l5d-dst-override` header if provided.  Are you interested in fixing this by submitting a pull request to the https://github.com/linkerd/website repo?

**Comment by derrickburns** [comment]
done

**Comment by adleong** [comment]
Thanks!  https://github.com/linkerd/website/pull/616
