### ISSUE TITLE
Telemetry for outbound connections to non-Conduit-proxied destinations isn't available

### ISSUE THREAD

**Issue by briansmith** [linkerd/linkerd2#387]
Before we inject the proxy into the control plane, traffic from each proxied pod to the control plane didn't show up in the UI, but after we do so, it will (maybe; see #370). This is because the UI only shows metrics for traffic that is inbound for some Conduit-proxied pod. If the outbound traffic is to a non-Conduit-proxied destination (pod or external service) then the metrics for that outbound traffic never show up.

We had reasons for not collecting/displaying outbound metrics prior to Conduit 0.1. For example, we were worried about perceived double-counting since the traffic from A to B would show up as outbound traffic for A and inbound traffic for B; I don't quite understand this concern but I think it might be a non-issue now. I think we were also worried about the performance impact of collecting twice as much metrics data. I can't remember what the other concerns were.

Also, there are implementation concerns. We could collect outbound metrics per host (or path or whatever) for outbound HTTP/HTTPS traffic that the proxy sees the plaintext for (either non-TLS traffic or traffic where Conduit does the TLS termination). We could collect outbound metrics per-SNI for outbound TLS traffic that the proxy doesn't see the plaintext of, but this is harder to integrate and it has limitations w.r.t. HTTP/2 connection coalescing. It's not clear how best to collect and/or represent outbound metrics for non-HTTP/HTTPS traffic; maybe we do it by destination IP:port or maybe we bundle it all together as "other".

**Comment by grampelberg** [comment]
@briansmith do the metrics for this exist? Implementation in the CLI/UI shouldn't be too hard and it seems like an awesome feature.

**Comment by briansmith** [comment]
@grampelberg I haven't kept up with all the latest Telemetry developments. I think @klingerf would know.

**Comment by olix0r** [comment]
The proxy exports outbound telemetry for arbitrary http destinations (buckets omitted):

```
request_total{authority="google.com",direction="outbound"} 1
request_duration_ms_count{authority="google.com",direction="outbound"} 1
request_duration_ms_sum{authority="google.com",direction="outbound"} 0
response_total{authority="google.com",direction="outbound",classification="success",status_code="301"} 1
response_duration_ms_count{authority="google.com",direction="outbound",classification="success",status_code="301"} 1
response_duration_ms_sum{authority="google.com",direction="outbound",classification="success",status_code="301"} 0.1
response_latency_ms_count{authority="google.com",direction="outbound",classification="success",status_code="301"} 1
response_latency_ms_sum{authority="google.com",direction="outbound",classification="success",status_code="301"} 8.1
```

However, neither `conduit stat` nor grafana display these metrics today. My general thought is that we should support an _authority_ resource type that allows us to enumerate and query traffic by authority.

**Comment by grampelberg** [comment]
Sounds like a good addition to `--from` and `--to`. Any thoughts on where/how this should all surface?

Thinking it through, introducing a resource type (`egress`) feels like a good way to bundle this all together. Unfortunately, k8s doesn't have a top level `egress` resource type right now. Confusing users around this is a possible problem, maybe it should be a separate command?

### CLI

```bash
# conduit stat egress

NAME                MESHED      SUCCESS       RPS      LATENCY_X      SECURED
egress/google.com     -          90%         10rps       100ms          10%  
```

```bash
# conduit stat egress --from deploy/emoji

NAME                MESHED      SUCCESS       RPS      LATENCY_X      SECURED
egress/google.com     -          90%         10rps       100ms          10%  
```

### GUI

For starters, it would be easy to add this to the namespaces listing all resources. It could then be added to the network graph as an endpoint.
