### ISSUE TITLE
Possible Reason Behind Multiple restart  of Identity Pod 

### ISSUE THREAD

**Issue by jainbhavya65** [linkerd/linkerd2#3877]
We are using linkerd 2.6.1 stable after load test we observed that identity pod in Linkerd name space restart multiple time and we didn't even get proper logs its just shows "**shutting down gRPC server on :8080**" we didn't find the possible reason behind these restart after identity restart destination,linkerd-proxy-injector ,linkerd-sp-validator,tap and web was also restart. and is there any way we can make all control plan pod to static pod which never restart until any error occur.

**Comment by mayankshah1607** [comment]
@jainbhavya65 could you provide some info about the cluster you are running linkerd on? Also, are you running the control plane on high availability mode, i.e, using the `--ha` flag?

**Comment by jainbhavya65** [comment]
@mayankshah1607 we are using linkerd on gke kubernetes cluster and we are not running linkerd on ha

**Comment by grampelberg** [comment]
This sounds like a k8s configuration issue. To be specific, if the pods are getting signals from k8s to shutdown, they're being evicted. Take a look at how to configure your cluster for running out of resources - https://kubernetes.io/docs/tasks/administer-cluster/out-of-resource/ . I'd also recommend adding resource requests and limits that are much higher than the default. The `--ha` configuration does that for you.
