### ISSUE TITLE
Configure proxy auto inject if sidecar-injector is not running then pod has to wait for sidecar-injector

### ISSUE THREAD

**Issue by jainbhavya65** [linkerd/linkerd2#3885]
We observe that when sidecar-proxy-injector and any normal pod restart at same time at that time linkerd not inject proxy in that pod. is there any way we can configure linkerd that if any pod having annotation linkerd.io/inject: enabled that must have linkerd proxy if sidecar-proxy-injector is down then it have to wait for linkerd-proxy.

**Comment by grampelberg** [comment]
Install with `--ha` or set `webhookFailurePolicy` to fail.
