### ISSUE TITLE
Linkerd stickiness with old downstream pods

### ISSUE THREAD

**Issue by manoj3832** [linkerd/linkerd2#3902]
We are using Linkerd stable 2.4.0 and facing issue when reloads downstream service , so lets assume setup is  like podA+Linkerdproxy(sidecar)--->podB+Linkerdproxy(sidecar) .  now  when we reloads podB and lets assume new pod is podC but linkerd proxy still points to podB which does not exists in cluster and this creates 503 errors for podA.  to fix things we need to restart all Pods. 
anyone got any fix for same or facing similar issue ? we are running on EKS

**Comment by ihcsim** [comment]
@manoj3832 Can you try upgrading to [stable-2.6.1](https://github.com/linkerd/linkerd2/releases/tag/stable-2.6.1)? You can find the upgrade instructions [here](https://linkerd.io/2/tasks/upgrade/).

**Comment by grampelberg** [comment]
Please open up the issue again if you're still seeing problems.
