### ISSUE TITLE
Add validation to CNI plugin installation

### ISSUE THREAD

**Issue by zaharidichev** [linkerd/linkerd2#3904]
Much like `linkerd install` I think we should have validation when we do `linkerd install-cni` At least we should be able to detect whether there is already a plugin installed. If there is we should error out and warn the user. 

@grampelberg WDYT?

**Comment by grampelberg** [comment]
I always love more validation. What kind of things are you thinking about? I'd love to see some checks added for the CNI stuff, especially since it can go so wrong.

**Comment by ihcsim** [comment]
Possibly relevant https://github.com/linkerd/linkerd2/issues/3804.

**Comment by zaharidichev** [comment]
Well, for starters I would like install-cni to fail if there is already a cni plugin installed, much like linkerd fails.

**Comment by ihcsim** [comment]
> I would like install-cni to fail if there is already a cni plugin installed

Why does it need to? The CNI is stateless AFAIK. Running `linkerd install-cni | kubectl apply -f -` multiple times should be ok, right?

**Comment by zaharidichev** [comment]
> Why does it need to? The CNI is stateless AFAIK. Running linkerd install-cni | kubectl apply -f - multiple times should be ok, right?


@ihcsim The same stand for linkerd install but it fails nevertheless. Maybe I am missing smth.

**Comment by grampelberg** [comment]
@zaharidichev we did it that way for `install` because changing trust roots bricks your cluster.

**Comment by zaharidichev** [comment]
@grampelberg I see, that makes sense. I guess this is not as applicable as I was thinking. Should we close that issue for now?

**Comment by grampelberg** [comment]
WFM, we should create a new issue whenever it becomes a problem.
