### ISSUE TITLE
CI can't run concurrent builds in master

### ISSUE THREAD

**Issue by alpeb** [linkerd/linkerd2#3911]
### What problem are you trying to solve?

CI builds on the master branch trigger a `cloud_integration` job that runs the integration tests on a GKE cluster that has already been setup beforehand that is never torn down. When more than one build attempts to run tests in that cluster they interfere with one another.
Even if the build doesn't reach the `cloud_integration` step, if the build is canceled the `cloud_cleanup` job will run regardless, interfering with another build that might still be in the `cloud_integration` step.

### How should the problem be solved?

`cloud_integration`' s `Run integration tests` step should not be triggered until the cluster is empty. This could be achieved by prepending another step that blocks the build through a `kubectl wait` on linkerd's main resources.

A drawback is that when more than one build would be waiting on that condition they might then both unblock simultaneously when the wait is over. One way to address that would be with an algorithm like this:
```
while {
  // block until the cluster is clean
  kubectl wait --for ... --timeout=-1s

  // concurrent builds will be unblocked simultaneously, but...
  sleep random seconds

  // Concurrent builds will hit this at different moments.
  // The first to hit this will be unblocked and will immediately
  // create a resource and thus leave the other builds blocked
  // (timeout=0 means it checks once and returns)
  if (kubectl wait --for ... --timeout=0) then break
}
```
Given the `Run integration tests` step does actually run multiple tests with cluster cleanup in-between, we might need to add one special resource at the beginning that only gets clean at the very end, and use it in the two `kubectl wait` above.

### Any alternatives you've considered?

- We could create separate clusters for each build run with a name associated to the commit sha like we do with the `kind` clusters. That implies using some sort of cluster API. Something to evaluate in the future, maybe as part as a more general cross-cloud testing effort.
- We could still run the integration tests concurrently in the same cluster, including the sha in the namespaces names to avoid clashes. But I believe we can't currently run multiple linkerd instances in the same cluster.

Edit: fixed timeout `kubectl wait` calls

**Comment by ihcsim** [comment]
```
// block until the cluster is clean
  kubectl wait --for ... --timeout=-1
```
Any idea how to implement this? Last I checked, the condition that `wait` supports is limited; might have to check all pods across all integration test namespaces. 

Personally, I feel like we should invest into the multiple clusters options (on Azure for cost efficiency), using something like Pulumi or Terraform. It feels like we keep dancing around integration test failures by patching our scripts with regex-matching (where the errors happened due to infra issues), `if-else` conditions etc.

**Comment by alpeb** [comment]
@ihcsim The lock could be a cluster resource like `clusterrole`; created at the beginning of the tests and cleaned up at the end. It works with `kubectl wait` in my local testing.
I agree multiple clusters is the right solution long term, but I think the current proposal serves as a quick fix in the meantime.

**Comment by ihcsim** [comment]
>  right solution long term

I only suggested this because I heard during the last stand-up that we are taking time to improve the CI. Personally, I think we have seen enough test failures that affected/blocked releases, that the time to implement the right solution is at-hand.
