### ISSUE TITLE
Linkerd CLI should supports --as-group

### ISSUE THREAD

**Issue by marcantoine-bibeau** [linkerd/linkerd2#3914]
## Feature Request
Linkerd CLI currently support --as-user but should also supports --as-group

### What problem are you trying to solve?
Use the linkerd cli on kube cluster using https://github.com/postfinance/kubectl-sudo

### How should the problem be solved?
support --as-group in cli

What do you want to happen? Add any considered drawbacks.

### Any alternatives you've considered?
I don't have any workaround

**Comment by grampelberg** [comment]
TIL, I didn't know `--as-group` existed!

**Comment by mayankshah1607** [comment]
Hi, would it be okay if I took up this one? :)

**Comment by grampelberg** [comment]
@mayankshah1607 go for it!

**Comment by mayankshah1607** [comment]
I guess this issue can be closed since https://github.com/linkerd/linkerd2/pull/3952 has been merged! @zaharidichev @grampelberg

**Comment by zaharidichev** [comment]
That is correct :)

**Comment by marcantoine-bibeau** [comment]
Nice. Thanks a lot!
