### ISSUE TITLE
FQDN for trace collector is NOT accepted

### ISSUE THREAD

**Issue by derrickburns** [linkerd/linkerd2#3919]
## Bug Report

**WORKS**
```
annotations:
  config.linkerd.io/trace-collector: "oc-collector.tracing:55678"
```

**FAILS**
```
annotations:
  config.linkerd.io/trace-collector: "oc-collector.tracing.svc.cluster.local:55678"
```

The latter causes sidecar injection to fail silently.

Linkerd 2.6.1

**Comment by Pothulapati** [comment]
I think, it's because of the code here 
https://github.com/linkerd/linkerd2/blob/b94e03a8a6c0d71527e2cb9893ba63b30ae0fbd0/pkg/inject/inject.go#L594:29

**Comment by Pothulapati** [comment]
@derrickburns I think the expectation is that, the cluster domain will be added by the injector to the proxy's env, and the trace-collector annotation should only have the service-name and namespace. 
Do you face a problem with this?

**Comment by adleong** [comment]
@Pothulapati where is the code in the injector where it adds the cluster domain to the trace addr?  I'm not seeing it...

**Comment by ihcsim** [comment]
> the cluster domain will be added by the injector to the proxy's env

I don't think that's the case.

> The latter causes sidecar injection to fail silently.

@derrickburns Are you seeing any error logs in the proxy injector?

**Comment by adleong** [comment]
I'm not able to reproduce this.  I can set the FQDN in a deployment annotation and the correct environment variable is set on the proxy in the resulting pod.

```
$ kubectl -n l5d-integration-emojivoto get deploy/web -ojsonpath="{.spec.template.metadata.annotations.config\.linkerd\.io/trace-collector}"
oc-collector.l5d-integration-tracing.svc.cluster.local:55678

$ kubectl -n l5d-integration-emojivoto get po/web-5f8559f776-pfgvp -ojsonpath='{.spec.containers[1].env[?(@.name=="LINKERD2_PROXY_TRACE_COLLECTOR_SVC_ADDR")].value}'
oc-collector.l5d-integration-tracing.svc.cluster.local:55678
```

**Comment by Pothulapati** [comment]
Looks like I went ahead of myself, and mistook the logic. Sorry

Just tried annotating `config.linkerd.io/trace-collector: "oc-collector.tracing.svc.cluster.local:55678"` and the injection worked. Can you see something in the `proxy-injector` logs?

**Comment by derrickburns** [comment]
I will reproduce.

**Comment by adleong** [comment]
@derrickburns any luck reproducing?

**Comment by derrickburns** [comment]
@adleong i apologize for the delay. I have not had a chance to attempt to reproduce.
