### ISSUE TITLE
Provide way to provide alternative linkerd-identity-issuer secret

### ISSUE THREAD

**Issue by derrickburns** [linkerd/linkerd2#3922]
### What problem are you trying to solve?

I would like to load the linkerd-identity-issuer from an external secret manager.

### How should the problem be solved?

Please modify the helm chart to allow one the option to not create the linkerd-identity-issuer secret and/or to provide a different secret name.

**Comment by zaharidichev** [comment]
Hi there @derrickburns I think what you are asking for is already present in the current edge. Take a look at [these docs](https://linkerd.io/2/tasks/use_external_certs/) and let me know if that does it for you.

**Comment by grampelberg** [comment]
I'm going to close this out. @derrickburns please reopen if the latest edge doesn't do what you're looking for.

**Comment by derrickburns** [comment]
Thank you!
