### ISSUE TITLE
Linkerd web (dashboard) live calls don't work

### ISSUE THREAD

**Issue by derrickburns** [linkerd/linkerd2#3924]
## Bug Report

I am having trouble using websockets (live calls in the linkerd dashboard).  I see this in the logs for linkerd-web:

```
 time="2020-01-14T19:36:08Z" level=error msg="websocket: 'Origin' header value not allowed"                                                                                                                │
│ 2020/01/14 19:36:08 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.(*responseWriterDelegator).WriteHeader (delegator.go:59)
```

When I have my gateway remove the `Origin` header before the request goes to the linkerd dashboard  then websockets in the linkerd dashboard (for the LIVE CALLS)  work.

### Environment

- Kubernetes Version: 1.14.9
- Cluster Environment: (GKE, AKS, kops, ...): EKS
- Host OS:
- Linkerd version: 2.6.1

### Possible solution

Remove `Origin` header or fix Prometheus client library so that it ignores `Origin` headers.

### Additional context

I did demo live calls two months ago and it was working then.  Perhaps this was introduced in 2.6.1?

**Comment by ihcsim** [comment]
@derrickburns Did you launch the dashboard with the `linkerd dashboard` command or via an ingress load balancer?

**Comment by derrickburns** [comment]
I launched it via a load balancer.

**Comment by ihcsim** [comment]
Is that a cloud provider LB or one that you manage? Have you had a chance to look at the doc on [Exposing the Dashboard](https://linkerd.io/2/tasks/exposing-dashboard/)?

**Comment by derrickburns** [comment]
Ah.  No, I did not see that document.

I am using Gloo for ingress and Pomerium for authentication and authorization.

I can see how the nginx annotations map:
```
    nginx.ingress.kubernetes.io/upstream-vhost: $service_name.$namespace.svc.cluster.local:8084
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header Origin "";
      proxy_hide_header l5d-remote-ip;
      proxy_hide_header l5d-server-id;
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: web-ingress-auth
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
```

I effectively implement the `Origin` change in my workaround while Pomerium implements auth.

I have not found a need to hide `l5d-remote-ip` and `l5d-server-id`.

**Comment by ihcsim** [comment]
@derrickburns Cool, thanks for the tips. How do you feel about helping us to update the documentation, by including a subsection for Gloo? (We are going full steam towards the next stable release; your help will be appreciated). 

If you are interested, the markdown is [here](https://github.com/linkerd/website/blob/master/linkerd.io/content/2/tasks/exposing-dashboard.md). You can find information on how to run Hugo to test changes on the repo's README. LMK, thanks!

**Comment by derrickburns** [comment]
The integration with Gloo and Pomerium is rather involved.  Let me see  what I can do.

**Comment by ihcsim** [comment]
Meanwhile, can we close this issue?

**Comment by derrickburns** [comment]
Thanks

**Comment by tingkai-zhang** [comment]
Hi, Can we have the documentation for `gloo` exposing the dashboard?

I am using gloo as gateway and have created the virtual service correctly to route the traffic. When I try to access the dashboard it says:
```
This does not match /^(localhost|127\.0\.0\.1|linkerd-web\.linkerd\.svc\.cluster\.local|linkerd-web\.linkerd\.svc|\[::1\])(:\d+)?$/ and has been denied for security reasons.
Please see https://linkerd.io/dns-rebinding for an explanation of what is happening and how to fix it.
```

I have enabled the native integration by running:
```
kubectl patch settings -n gloo-system default -p '{"spec":{"linkerd":true}}' --type=merge
```

Any ideas on how to fix it?

**Comment by ihcsim** [comment]
@tingkai-zhang See https://linkerd.io/2/tasks/exposing-dashboard/#dns-rebinding-protection.
