### ISSUE TITLE
Enable the jsx-a11y/click-events-have-key-events eslint rule

### ISSUE THREAD

**Issue by klingerf** [linkerd/linkerd2#3926]
In #3882, we adopted more eslint rules for our Javascript codebase. The `jsx-a11y/click-events-have-key-events` rule is recommended, but it wasn't enabled as part of that PR, since it requires code changes. We should enable the rule and fix the code that fails to lint. We can enable it by removing the override that appears here:

https://github.com/linkerd/linkerd2/blob/0eabbe4173fd8a7da91d5771572bd08d85268275/web/app/.eslintrc#L85-L88

**Comment by christyjacob4** [comment]
@klingerf please assign it to me

**Comment by cpretzer** [comment]
@christyjacob4 looking forward to reviewing your PR for this 😄

**Comment by adrijshikhar** [comment]
@christyjacob4 are you still working on this?

**Comment by christyjacob4** [comment]
yea obviously @adrijshikhar
