### ISSUE TITLE
Enable the no-param-reassign eslint rule

### ISSUE THREAD

**Issue by klingerf** [linkerd/linkerd2#3927]
In #3882, we adopted more eslint rules for our Javascript codebase. The `no-param-reassign` rule is recommended, but it wasn't enabled as part of that PR, since it requires code changes. We should enable the rule and fix the code that fails to lint. We can enable it by removing the override that appears here:

https://github.com/linkerd/linkerd2/blob/0eabbe4173fd8a7da91d5771572bd08d85268275/web/app/.eslintrc#L85-L88

**Comment by kohsheen1234** [comment]
Hey @klingerf 

I'd like to work on this issue. Could you please assign it to me. :)

**Comment by klingerf** [comment]
Great, thanks for your help, @kohsheen1234! Have assigned it to you.

**Comment by adrijshikhar** [comment]
@kohsheen1234 are you still working on it?

**Comment by kohsheen1234** [comment]
@adrijshikhar Yes, I am still working on it. I had some trouble setting up the environment initially, but now it's working well. :)
