### ISSUE TITLE
Enable linting for javascript test files

### ISSUE THREAD

**Issue by klingerf** [linkerd/linkerd2#3929]
### What problem are you trying to solve?

Right now, none of our test files are linted as part of CI. This has led to code drift in those files.

### How should the problem be solved?

We should enable linting for test files as part of CI, and fix all of the current lint issues in our test files.

### Any alternatives you've considered?

Maintain the status quo and allow a variety of code styles in tests.

### How would users interact with this feature?

Once enabled, if test files do no lint cleanly, they should fail CI.

**Comment by adrijshikhar** [comment]
@klingerf hi, i would like to work on this issue, can you help me out?
i have already set up the repo

**Comment by adrijshikhar** [comment]
hey @klingerf
