### ISSUE TITLE
Errors are shown as success. 

### ISSUE THREAD

**Issue by ashishxooa** [linkerd/linkerd2#3934]
## Bug Report

Hi, I have a http/2 hello world service and a client which sends http/2 requests. Now when I inject error in the request, even like a simple one say wrong URL. I get 4xx errors on the client but Linkerd shows that request as success. 

This same client and server works with Istio where it shows me such failures are failures. 

Even when I tap a service, I can see the error code. 

> 
> rsp id=79:0 proxy=in  src=100.110.0.8:53722 dst=100.110.0.2:3000 tls=true :status=404 latency=427µs
> end id=79:0 proxy=in  src=100.110.0.8:53722 dst=100.110.0.2:3000 tls=true duration=128µs response-length=23B

### How can it be reproduced?

Should be valid with any http2 service. 

### Logs, error output, etc

(If the output is long, please create a [gist](https://gist.github.com/) and
paste the link here.)

#### `linkerd check` output

```➜  ~ linkerd check
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-api
-----------
√ control plane pods are ready
√ control plane self-check
√ [kubernetes] control plane can talk to Kubernetes
√ [prometheus] control plane can talk to Prometheus
√ no invalid service profiles

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ control plane is up-to-date
√ control plane and cli versions match

Status check results are √
```

### Environment

- Kubernetes Version: v1.15.6
- Cluster Environment: (GKE, AKS, kops, ...) kops on AWS. 
- Host OS: Debian
- Linkerd version: stable-2.6.1

### Possible solution

Not sure if this a bug or known/intentional design?

**Comment by grampelberg** [comment]
4xx is a success - the app successfully said that the content doesn't exist. You'll want to reclassify what's an error through service profiles if you'd like 4xx errors to result in failures. Check out the [service profile](https://linkerd.io/2/reference/service-profiles/) docs for how to do that.
