### ISSUE TITLE
Migration to Tokio 0.2

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#3938]
## Description

We need to move proxy onto the modern Tokio ecosystem so that we don’t diverge from core library fixes, etc.

Once finished, we’ll be able to start using tokio 0.2, etc; we’ll have a repeatable framework for analyzing proxy performance; and we’ll start to develop a new mental model of the proxy by regularly looking at flamegraphs.

## Details

- [Proposal](https://docs.google.com/document/d/1L8Fclmw425R6FIvKicIH1JEJ2hViwkONnCkf3ZwJmz4/edit)
- [Engineering Notes](https://docs.google.com/document/d/1nlTeSKxsMj4DEmLvQPUvLk8Efz2MkkDcbw34h29jfQQ/edit)
- [Project](https://github.com/orgs/linkerd/projects/43)

**Comment by hawkw** [comment]
This has been done for...a while :)
