### ISSUE TITLE
Clock skew check not working correctly

### ISSUE THREAD

**Issue by DGollings** [linkerd/linkerd2#3943]
### What is the issue?
Linkerd --pre (randomly) fails on clock skew detection check

### How can it be reproduced?
If I were to guess why, use Kubernetes 17.0.0, made sure to check ntpd many times, also switched back and forth between ntpd and systemd-timesyncd

./clock_skew.sh is a lightly modified version of this script:
https://gist.github.com/foospidy/77c43ec2b2b71e4447f0534f7ac26798

### Logs, error output, etc
'proof'
```
/clock_skew.sh 
INFO: Clock skew on 0.0.0.27 is 0 seconds.
INFO: Clock skew on 0.0.0.51 is 1 seconds.
INFO: Clock skew on 0.0.0.161 is 0 seconds.
INFO: Clock skew on 0.0.0.113 is 0 seconds.
Everything is running on time!
```
simple capturing of node metadata
```
kubectl describe nodes | grep Ready | grep posting
  Ready                True    Fri, 17 Jan 2020 14:15:39 +0100   Fri, 17 Jan 2020 13:45:28 +0100   KubeletReady                 kubelet is posting ready status
  Ready                True    Fri, 17 Jan 2020 14:15:28 +0100   Fri, 17 Jan 2020 13:45:27 +0100   KubeletReady                 kubelet is posting ready status
  Ready                True    Fri, 17 Jan 2020 14:15:28 +0100   Fri, 17 Jan 2020 13:45:27 +0100   KubeletReady                 kubelet is posting ready status
  Ready                True    Fri, 17 Jan 2020 14:15:28 +0100   Fri, 17 Jan 2020 13:45:27 +0100   KubeletReady                 kubelet is posting ready status
```

#### EDIT
Whilst verifying output for this bug report I saw a massive jump in heartbeat output
```text
 kubectl describe nodes | grep Ready | grep posting
  Ready                True    Fri, 17 Jan 2020 14:30:40 +0100   Fri, 17 Jan 2020 13:45:28 +0100   KubeletReady                 kubelet is posting ready status
  Ready                True    Fri, 17 Jan 2020 14:37:17 +0100   Fri, 17 Jan 2020 13:45:27 +0100   KubeletReady                 kubelet is posting ready status
  Ready                True    Fri, 17 Jan 2020 14:30:28 +0100   Fri, 17 Jan 2020 13:45:27 +0100   KubeletReady                 kubelet is posting ready status
  Ready                True    Fri, 17 Jan 2020 14:30:28 +0100   Fri, 17 Jan 2020 13:45:27 +0100   KubeletReady                 kubelet is posting ready status
./clock_skew.sh 
INFO: Fri, 17 Jan 2020 14:37:53 +0100 vs Fri, 17 Jan 2020 13:37:54 +0000 Clock skew on 0.0.100.27 is 1.
INFO: Fri, 17 Jan 2020 14:37:53 +0100 vs Fri, 17 Jan 2020 13:37:54 +0000 Clock skew on 0.0.101.51 is 1.
INFO: Fri, 17 Jan 2020 14:37:54 +0100 vs Fri, 17 Jan 2020 13:37:54 +0000 Clock skew on 0.0.100.161 is 0.
INFO: Fri, 17 Jan 2020 14:37:54 +0100 vs Fri, 17 Jan 2020 13:37:54 +0000 Clock skew on 0.0.100.113 is 0.
Everything is running on time!
kubectl describe nodes | grep Ready | grep posting
  Ready                True    Fri, 17 Jan 2020 14:37:24 +0100   Fri, 17 Jan 2020 13:45:28 +0100   KubeletReady                 kubelet is posting ready status
  Ready                True    Fri, 17 Jan 2020 14:37:17 +0100   Fri, 17 Jan 2020 13:45:27 +0100   KubeletReady                 kubelet is posting ready status
  Ready                True    Fri, 17 Jan 2020 14:37:23 +0100   Fri, 17 Jan 2020 14:37:23 +0100   KubeletReady                 kubelet is posting ready status
  Ready                True    Fri, 17 Jan 2020 14:37:23 +0100   Fri, 17 Jan 2020 13:45:27 +0100   KubeletReady                 kubelet is posting ready status
./clock_skew.sh                                   
INFO: Fri, 17 Jan 2020 14:38:13 +0100 vs Fri, 17 Jan 2020 13:38:14 +0000 Clock skew on 0.0.100.27 is 1.
INFO: Fri, 17 Jan 2020 14:38:13 +0100 vs Fri, 17 Jan 2020 13:38:13 +0000 Clock skew on 0.0.101.51 is 0.
INFO: Fri, 17 Jan 2020 14:38:14 +0100 vs Fri, 17 Jan 2020 13:38:13 +0000 Clock skew on 0.0.100.161 is -1.
INFO: Fri, 17 Jan 2020 14:38:14 +0100 vs Fri, 17 Jan 2020 13:38:14 +0000 Clock skew on 0.0.100.113 is 0.
Everything is running on time
```

And whilst investigating _that_ output it started lagging again
```
kubectl describe nodes | grep Ready | grep posting
  Ready                True    Fri, 17 Jan 2020 14:37:24 +0100   Fri, 17 Jan 2020 13:45:28 +0100   KubeletReady                 kubelet is posting ready status
  Ready                True    Fri, 17 Jan 2020 14:37:17 +0100   Fri, 17 Jan 2020 13:45:27 +0100   KubeletReady                 kubelet is posting ready status
  Ready                True    Fri, 17 Jan 2020 14:37:23 +0100   Fri, 17 Jan 2020 14:37:23 +0100   KubeletReady                 kubelet is posting ready status
  Ready                True    Fri, 17 Jan 2020 14:37:23 +0100   Fri, 17 Jan 2020 13:45:27 +0100   KubeletReady                 kubelet is posting ready status
./clock_skew.sh                                   
INFO: Fri, 17 Jan 2020 14:38:57 +0100 vs Fri, 17 Jan 2020 13:38:58 +0000 Clock skew on 0.0.100.27 is 1.
INFO: Fri, 17 Jan 2020 14:38:57 +0100 vs Fri, 17 Jan 2020 13:38:58 +0000 Clock skew on 0.0.101.51 is 1.
INFO: Fri, 17 Jan 2020 14:38:58 +0100 vs Fri, 17 Jan 2020 13:38:58 +0000 Clock skew on 0.0.100.161 is 0.
INFO: Fri, 17 Jan 2020 14:38:58 +0100 vs Fri, 17 Jan 2020 13:38:58 +0000 Clock skew on 0.0.100.113 is 0.
Everything is running on time
```

I'm using bootkube and couldn't find any override for the default heartbeat settings  is it possible the heartbeat output simply isn't reliable enough (any more) ?

#### `linkerd check` output

```text
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

pre-kubernetes-setup
--------------------
√ control plane namespace does not already exist
√ can create Namespaces
√ can create ClusterRoles
√ can create ClusterRoleBindings
√ can create CustomResourceDefinitions
√ can create PodSecurityPolicies
√ can create ServiceAccounts
√ can create Services
√ can create Deployments
√ can create CronJobs
√ can create ConfigMaps
× no clock skew detected
    clock skew detected for node(s): supernova-controller-0, supernova-helium-worker-0, supernova-helium-worker-1, supernova-helium-worker-2
    see https://linkerd.io/checks/#pre-k8s-clock-skew for hints

pre-kubernetes-capability
-------------------------
√ has NET_ADMIN capability
√ has NET_RAW capability

pre-linkerd-global-resources
----------------------------
√ no ClusterRoles exist
√ no ClusterRoleBindings exist
√ no CustomResourceDefinitions exist
√ no MutatingWebhookConfigurations exist
√ no ValidatingWebhookConfigurations exist
√ no PodSecurityPolicies exist

linkerd-version
---------------
√ can determine the latest version
‼ cli is up-to-date
    is running version 2.6.0 but the latest stable version is 2.6.1
    see https://linkerd.io/checks/#l5d-version-cli for hints
```

### Environment

- Kubernetes Version: 1.17.0
- Cluster Environment: Packet (Bootkube)
- Host OS: Flatcar Linux
- Linkerd version: 2.6.1

### Possible solution
Checked the code (pkg/healthcheck/healthcheck.go), nothing stood out to me as to a possible cause of this. But maybe making it commandline overrideable would be nice. Now I have to ignore the check output in my terraform scripts instead

**Comment by DGollings** [comment]
Just saw a 5m jump
  Ready                True    Fri, 17 Jan 2020 **14:42:24** +0100   Fri, 17 Jan 2020 13:45:27 +0100   KubeletReady                 kubelet is posting ready status
  Ready                True    Fri, 17 Jan 2020 **14:47:24** +0100   Fri, 17 Jan 2020 13:45:28 +0100   KubeletReady                 kubelet is posting ready status

Didn't read it enough to understand the details, but I think something has changed re: heartbeats
https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/0009-node-heartbeat.md

**Comment by olix0r** [comment]
@DGollings Nice find! I noticed a similar issue when I was testing a recent microk8s version, but I chalked the issue up to microk8s and not k8s v1.17. I agree that we'll need to at least relax this check. Are you interested in submitting a PR for this?

**Comment by DGollings** [comment]
Sure, there's three options:

- Change this from an error to a warning (and mention this issue/feature in the clock skew documentation)
- Up the check to 5 min (but that could be dangerous if someone has _actual_ massive clock skew)
- Go further down the rabbit hole and figure out what the event api/object/endpoint is and use that instead (if that's even possible)

Thoughts?

**Comment by olix0r** [comment]
I think it might make sense to make this a warning, since what we're measuring is something very different from actual clock skew.

@grampelberg what do you think?

**Comment by DGollings** [comment]
actually, we could partially solve it by comparing clock skew between the nodes themselves. Make it a consensus based meta check.

if nodes < 1 min 
and deployment tool < 5 min
= ok

**Comment by grampelberg** [comment]
I'm fine making it a warning, probably some things we could do by moving it out of `--pre` and into `check` as well. That might over complicate the logic there though 🤷‍♂ .

**Comment by DGollings** [comment]
Speaking of over complicated logic, PR incoming #3945  :)

**Comment by DGollings** [comment]
idk what happened with that PR, lets try again #3947 @olix0r

**Comment by adleong** [comment]
As discussed in #3947 I think we should do the following:

* Increase the clock skew allowance to 5 minutes to match the default heartbeat interval in k8s 1.17
* Make this check a warning so that it doesn't error for clusters with longer heartbeat intervals
* Update the docs for this check to explain that this check uses the node heartbeat as a proxy for node time

**Comment by DGollings** [comment]
@adleong Hi, don't have time right now. But could look at it later this week, especially points 2 and 3 would take a little more time.
