### ISSUE TITLE
Changes to linkerd namespace spec ignored during upgrade

### ISSUE THREAD

**Issue by tanuck** [linkerd/linkerd2#3958]
### What is the issue?
The recommended upgrade method: `linkerd upgrade | kubectl apply --prune -l linkerd.io/control-plane-ns=linkerd -f -` will currently ignore any changes to the `Namespace` object output from `linkerd upgrade` because the apply selector will drop said resource.

After a partial outage, we were surprised to discover that the `config.linkerd.io/admission-webhooks: disabled` label was not present on our `Namespace` object. After revisiting our previous `linkerd upgrade`, it appeared the label was present in the manifests output from the linkerd CLI, but was dropped by kubectl.

### Logs, error output, etc

(If the output is long, please create a [gist](https://gist.github.com/) and
paste the link here.)

#### `linkerd check` output

```text
your output here ...
```

### Environment

- Kubernetes Version: 1.15.7
- Cluster Environment: GKE
- Host OS: cos
- Linkerd version: 2.6.0/2.6.1

**Comment by grampelberg** [comment]
While it feels weird, the right solution seems to be adding `linkerd.io/control-plane-ns=linkerd` to the namespace.

**Comment by supra08** [comment]
Hi @grampelberg, I would like to work on this issue.

**Comment by supra08** [comment]
@grampelberg I don't exactly understand the proposed solution. Did you mean adding the complete string `linkerd.io/control-plane-ns=linkerd` as the namespace for control-plane?

**Comment by grampelberg** [comment]
@supra08 that label needs to be added to the linkerd namespace definition.

**Comment by supra08** [comment]
@tanuck can you please elaborate the reproduction steps?

**Comment by tanuck** [comment]
@supra08 if you follow the official control plane upgrade instructions - `linkerd upgrade | kubectl apply --prune -l linkerd.io/control-plane-ns=linkerd -f -`
You'll notice the namespace object is omitted from the output
