### ISSUE TITLE
Allow custom hosts set from Helm values for "enforced-host"

### ISSUE THREAD

**Issue by KIVagant** [linkerd/linkerd2#3961]
## Feature Request

In the https://github.com/linkerd/linkerd2/blob/master/charts/linkerd2/templates/web.yaml#L70 I would like to add a custom host.
```
- -enforced-host=^(localhost|127\.0\.0\.1|{{ $hostFull }}|{{ $hostAbbrev }}|\[::1\])(:\d+)?$
```

### What problem are you trying to solve?

I'm trying to access Linkerd Dashboard behind a proxy which does not rewrite the `Host` header.
As [per documentation](https://linkerd.io/2/tasks/exposing-dashboard/#tweaking-host-requirement) I need to change the validation regexp that the dashboard server uses. But this regexp is hardcoded in Helm values.

### How should the problem be solved?

A new Helm value can be introduced to support adding an additional custom host or to completely replace the rule including an ability to completely disable the `Host` header check using an empty string as it said in the documentation.

### Any alternatives you've considered?

Manually change the line in a locally cached version of the chart (which I do, but it's inconvenient to maintain custom code changes and may be inappropriate for other users).

### How would users interact with this feature?

They can add a custom host to the filter when necessary.

**Comment by grampelberg** [comment]
@alpeb I thought we made this configurable? Did we decide it should be via header rewrite instead?

**Comment by alpeb** [comment]
> @alpeb I thought we made this configurable? Did we decide it should be via header rewrite instead?

The decision was to made it configurable only as an argument to the web container, changeable only through something like Kustomize. And the Host header should be rewritten as per instructed in the ingress annotation, to match `linkerd-web.linkerd.svc.cluster.local:8084`

**Comment by tomiwatech** [comment]
@grampelberg Please can you assign this task to me, I will like to work on it

**Comment by sannimichaelse** [comment]
@grampelberg Can you please assign this task to me, I will like to work on it

**Comment by grampelberg** [comment]
@sannimichaelse assigned!

**Comment by sannimichaelse** [comment]
Thanks @grampelberg. 

I need to clarify something before implementing the change. 

This is what I have in my head right now. Either allow the user to specify the host in the line directly or add it to the values.yaml file and Load with the .Values.host(or the variable name used in the file)

 - -enforced-host=^(host|{{ $hostFull }}|{{ $hostAbbrev }}|\[::1\])(:\d+)?$

@grampelberg, am I in sync?

**Comment by grampelberg** [comment]
@alpeb would be the right person to talk with about that =)

**Comment by sannimichaelse** [comment]
Alright.

> @alpeb would be the right person to talk with about that =)

Alright

**Comment by sannimichaelse** [comment]
Hi @alpeb , any suggestions?

**Comment by alpeb** [comment]
> This is what I have in my head right now. Either allow the custom host to be specified in the line directly or add it to the values.yaml file and Load with the .Values.host(or the variable name used in the file)
> 
> * -enforced-host=^(host|{{ $hostFull }}|{{ $hostAbbrev }}|[::1])(:\d+)?$

Hi @sannimichaelse !
I like better giving the option of setting and additional host into the regex like what you pasted (but without removing localhost and 127.0.0.1) through a new variable in `values.yaml`.
The alternative would be to have the entire regex be declared in `values.yaml`, which might be more flexible, but we'd need to provide as default the regex we already have, and we'd have to put into `values.yaml` the `$hostFull` and `$hostAbbrev` declarations, which I'd rather not do, to avoid convoluting that file which should remain IMO a simple list of variable declarations.

**Comment by KIVagant** [comment]
I would vote for the entire regex defined in values. Simple, easy to implement, easy to change to anything that users desire, easy to automate in CI tools.

**Comment by sannimichaelse** [comment]
> I would vote for ~the entire regex defined in values~ the ability to set the full regex and if not defined, to use the suggested default value. Simple, easy to implement, easy to change to anything that users desire, easy to automate in CI tools.
> 
> Instead of having $hostFull and $hostAbbrev in values, they can be used if nothing else is set by a user. I believe that the user knows what hosts they use in the environment and can easily hardcode them outside from the chart.

Alright to get what you saying I would use the custom host if specified or use default when empty like this

{{- $default_host :=^(localhost|127\.0\.0\.1| $hostFull | $hostAbbrev |\[::1\])(:\d+)?$ }}
- -enforced-host={{ Values.global.custom_host | default $default_host }}

**Comment by KIVagant** [comment]
Maybe worth renaming the `custom_host` key to something like `enforced_host_regexp`.

Anyway, I'm not a maintainer, so it's better wait for @alpeb's opinion.

**Comment by alpeb** [comment]
Hey guys, that works for me :+1:  You can go ahead with your PR and I'll be glad to review it :star:

**Comment by sannimichaelse** [comment]
Alright. How do I validate or test for the changes made in the values.yaml file @alpeb . I already followed the instructions in the TEST.md file but I don't think its running any test for the yaml file

**Comment by kivagant-ba** [comment]
@sannimichaelse , I guess you can open a PR in WIP/draft mode so the changes will become visible and it will be easier to comment
