### ISSUE TITLE
Linkerd check command should return warning when version endpoint is not reachable

### ISSUE THREAD

**Issue by sukhong** [linkerd/linkerd2#3973]
### What is the issue?
Linkerd check command currently errors out when version endpoint is not reachable. However, we have a need to run linkerd in a private cluster with no external network connectivity.

Linkerd check command currently fails when it cannot reach version check endpoint during linkerd-version step.

This should return warning instead, to support private cluster scenario.

### How can it be reproduced?

Run linkerd check command without external network.

#### `linkerd check` output

```text
{
      "categoryName": "linkerd-version",
      "checks": [
        {
          "description": "can determine the latest version",
          "hint": "https://linkerd.io/checks/#l5d-version-latest",
          "error": "Get https://versioncheck.linkerd.io/version.json?version=stable-2.6.1\u0026uuid=453bd534-21e4-4096-ad53-a7af5b7f395a\u0026source=cli: dial tcp: lookup versioncheck.linkerd.io on 127.0.0.53:53: read udp 127.0.0.1:52288-\u003e127.0.0.53:53: i/o timeout",
          "result": "error"
        },
        {
          "description": "cli is up-to-date",
          "hint": "https://linkerd.io/checks/#l5d-version-cli",
          "error": "unsupported version channel: stable-2.6.1",
          "result": "warning"
        }
      ]
    },
    {
      "categoryName": "control-plane-version",
      "checks": [
        {
          "description": "control plane is up-to-date",
          "hint": "https://linkerd.io/checks/#l5d-version-control",
          "error": "unsupported version channel: stable-2.6.1",
          "result": "warning"
        },
        {
          "description": "control plane and cli versions match",
          "result": "success"
        }
      ]
    }
```

### Environment

- Kubernetes Version: 1.5.7
- Cluster Environment: (GKE, AKS, kops, ...) aks-engine
- Host OS: Ubuntu
- Linkerd version: 2.6.1

**Comment by adleong** [comment]
@sukhong This sounds reasonable to me.  Are you interested in submitting a PR to fix this?

**Comment by mayankshah1607** [comment]
@adleong @sukhong I could fix this one if that's okay

**Comment by sukhong** [comment]
@mayankshah1607 I would really appreciate it if you can fix this for us :)

**Comment by mayankshah1607** [comment]
Thanks @sukhong ! I've opened a PR with a fix - https://github.com/linkerd/linkerd2/pull/3975
Could you pull the changes and let me know if that works for you? :)
