### ISSUE TITLE
Retries for retry-able gRPC calls

### ISSUE THREAD

**Issue by Dominik-K** [linkerd/linkerd2#3985]
### What problem are you trying to solve?
Implementing retries for gRPC calls. I assumed they're retry defaults within Linkerd2 and I could easily adjust them in the `ServiceProfile`.

### How should the problem be solved?
Linkerd2 should automatically retry gRPC calls which are [safe or idempotent](https://hackernoon.com/idempotency-apis-and-retries-34b161f64cb4) (as in [RFC 7231](https://tools.ietf.org/html/rfc7231#section-4.2.1)) to retry *and* return with a retry-able gRPC status-code. It should use the same retry defaults used for HTTP calls without a body.

Methods in Protobuf can be defined as "idempotent" or "no side effects" [since end of 2016](https://github.com/protocolbuffers/protobuf/blame/9e745f771b2a0cde271b8283753c19014124ac95/src/google/protobuf/descriptor.proto#L630-L640):
```
option idempotency_level = IDEMPOTENT;
```
If that bit is set to other than the default `IDEMPOTENCY_UNKNOWN`, then this should be used. Unclear if a `ServiceProfile` definition should overwrite this.

Note: There's a big [proposal for gRPC client retries](https://github.com/grpc/proposal/blob/master/A6-client-retries.md), but [work on it has been stalled](https://github.com/grpc/grpc/pull/10684#issuecomment-422100599) ([latest update I've found from June 2019](https://groups.google.com/d/msg/grpc-io/zzHIICbwTZE/kKYMFAfzAwAJ)).

Drawbacks:

* Retry-able status-codes must be chosen wisely. Otherwise a retry may increase an outage [as reported](https://groups.google.com/d/msg/grpc-io/zzHIICbwTZE/RtpOtXR6AgAJ).
* Additional to `idempotency_level`, we could look at the method type. But gRPC currently only uses `POST`. Means there's no way to distinguish the idempotency with that. There are tracking issues for using [`GET`](https://github.com/grpc/grpc/issues/12039) (safe or "nullipotent") & [`PUT`](https://github.com/grpc/grpc/issues/12038) (omnipotent) gRPCs though, but already open since 2017.

### Any alternatives you've considered?

Using retry functionality in the gRPC clients (in our case https://github.com/grpc-ecosystem/go-grpc-middleware/tree/master/retry). But the load-balancing is already offloaded to Linkerd2, so should be the retries, too.

### How would users interact with this feature?
The retries should just work out of the box. Like [Linkerd2's design principle](https://linkerd.io/2/design-principles/):
> **Just work**. Linkerd should not break existing applications, nor should it require complex configuration to get started or to do something simple.

Based on & off a [Slack discussion](https://linkerd.slack.com/archives/C89RTCWJF/p1574890936231300) between @hazsetata, @ihcsim, @adleong & @grampelberg.

**Comment by grampelberg** [comment]
The biggest drawback here is around buffering and memory in the proxy. Retrying gRPC calls will require caching the `POST` bodies there, which will immediately impact the memory in the proxy.

This is an awesome feature, it is just something that needs to be done carefully and with a lot of thought to make sure it is safe for users.

**Comment by CannibalVox** [comment]
I got bitten by this today, so here's a sketch of some thoughts I had on reading this:

* One of linkerd's benefits is being memory-light, so it would be good to know what memory "budget" people find reasonable for a payload-retry feature.  To me 500kb of cache space sounds good, but tight, but for a proxy that was [benchmarked at 5.7MB at 500rps](https://linkerd.io/2019/05/18/linkerd-benchmarks/), it would represent a large % increase in memory usage.
* In the above-linked benchmark, 600rps through an istio proxy is producing average latencies <10ms, which puts us at fewer than 10 in-flight requests at a time.  Obviously retry behavior is for when things aren't working so well, but it does indicate that we could have some very aggressive cache limits and still receive solid retry behavior.
* Being able to set a per-endpoint retriable payload cap would at least bound the size of the problem.  We could be able to say "okay beyond a 1.5kb payload, we don't do retries on this endpoint".  On an unrelated note, it might be nice just to be able to allow us to ban payloads beyond a certain size with a 400-style error as a matter of policy.
* For me, I would prefer if all retry behavior keys off of the service profile definition ONLY, in order for weird workflows to be accommodated.  Things like `idempotency_level` would ideally impact the profile generation.
* Lastly, I feel pretty vaguely that there should be a middle tier of memory limitations to supplement the per-payload limit and total cache limit, some kind of endpoint-level limitation.  It's not clear to me, though, if you start bumping up against the cache limit, whether the suffering should be spread equally, or directed at the highest-cache-usage endpoints that are taking up the most space, or the "heaviest" endpoints with the largest payload * timeout values.  Curious what others think.

**Comment by wmorgan** [comment]
Appreciate the writeup @CannibalVox . Addressing gRPC retries is officially on the [Linkerd Roadmap](https://github.com/linkerd/linkerd2/blob/main/ROADMAP.md). These sorts of requirements are very helpful.

**Comment by olix0r** [comment]
This feature has been implemented and is available in the most recent edge release. Please test it out and file new issues/discussions with feedback!
