### ISSUE TITLE
proxy RSS grows with traffic

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#3998]
On edge-20.1.4, proxy RSS grows with both HTTP and TCP load

![image](https://user-images.githubusercontent.com/240738/73407475-1575b600-42ae-11ea-8da3-dd77db0cc28b.png)
![image](https://user-images.githubusercontent.com/240738/73407490-20304b00-42ae-11ea-8b9f-ed192d966541.png)

Similar behavior is observed on more recent branches that change buffering/backpressure behavior; so we should probably continue to debug this on master.

I've put together a small [repro](https://github.com/olix0r/rss-burn).

**Comment by hawkw** [comment]
One source of RSS growth with TCP connections only is probably #4006.
