### ISSUE TITLE
Tracing spans dropped on quiescent system

### ISSUE THREAD

**Issue by derrickburns** [linkerd/linkerd2#4005]
Trying to use tracing with opencensus and linkerd. I have tracing with opencensus collector configured.  The system is practically quiescent but linkerd is dropping many trace spans.

I do see *some* trace data from linkerd, so I know that the Naming is correct.

### Logs, error output, etc 

from https://github.com/linkerd/linkerd2-proxy/blob/d213c1373f1f5ec479a59a0a388d4373dcb3cde4/linkerd/trace-context/src/layer.rs#L182 

linkerd2_trace_context::layer span dropped error=no available capacity

### Environment

│    Environment:                                                                                                            │
│      LINKERD2_PROXY_LOG:                           warn,linkerd2_proxy=info                                                │
│      LINKERD2_PROXY_DESTINATION_SVC_ADDR:          linkerd-dst.linkerd.svc.cluster.local:8086                              │
│      LINKERD2_PROXY_CONTROL_LISTEN_ADDR:           0.0.0.0:4190                                                            │
│      LINKERD2_PROXY_ADMIN_LISTEN_ADDR:             0.0.0.0:4191                                                            │
│      LINKERD2_PROXY_OUTBOUND_LISTEN_ADDR:          127.0.0.1:4140                                                          │
│      LINKERD2_PROXY_INBOUND_LISTEN_ADDR:           0.0.0.0:4143                                                            │
│      LINKERD2_PROXY_DESTINATION_GET_SUFFIXES:      svc.cluster.local.                                                      │
│      LINKERD2_PROXY_DESTINATION_PROFILE_SUFFIXES:  svc.cluster.local.                                                      │
│      LINKERD2_PROXY_INBOUND_ACCEPT_KEEPALIVE:      10000ms                                                                 │
│      LINKERD2_PROXY_OUTBOUND_CONNECT_KEEPALIVE:    10000ms                                                                 │
│      _pod_ns:                                      qa1 (v1:metadata.namespace)                                             │
│      LINKERD2_PROXY_DESTINATION_CONTEXT:           ns:$(_pod_ns)                                                           │
│      LINKERD2_PROXY_IDENTITY_DIR:                  /var/run/linkerd/identity/end-entity                                    │
│      LINKERD2_PROXY_IDENTITY_TRUST_ANCHORS:        -----BEGIN CERTIFICATE-----                                             │
│                                                    MIIBgzCCASmgAwIBAgIBATAKBggqhkjOPQQDAjApMScwJQYDVQQDEx5pZGVudGl0        │
│                                                    eS5saW5rZXJkLmNsdXN0ZXIubG9jYWwwHhcNMTkxMDE0MDA1MjI4WhcNMjAxMDEz        │
│                                                    MDA1MjQ4WjApMScwJQYDVQQDEx5pZGVudGl0eS5saW5rZXJkLmNsdXN0ZXIubG9j        │
│                                                    YWwwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAATgKSIVIlmFsEblrSdSIH0Dez+S        │
│                                                    o6m1DxUDYesZpsTcksqydwsrBrW1W6P5jnvz7KStIC7tbC2B2Fx7tFq/w7u0o0Iw        │
│                                                    QDAOBgNVHQ8BAf8EBAMCAQYwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMC        │
│                                                    MA8GA1UdEwEB/wQFMAMBAf8wCgYIKoZIzj0EAwIDSAAwRQIgHC/BZgipUYs3ygW6        │
│                                                    TNZaI8MsuvtpMoY+VK0peH22T9MCIQCHlzEK+y69UnBwdIpwQmKYBwEf2wr1qQ2y        │
│                                                    Vzfl2uYS3g==                                                            │
│                                                    -----END CERTIFICATE-----                                               │
│                                                                                                                            │
│      LINKERD2_PROXY_IDENTITY_TOKEN_FILE:           /var/run/secrets/kubernetes.io/serviceaccount/token                     │
│      LINKERD2_PROXY_IDENTITY_SVC_ADDR:             linkerd-identity.linkerd.svc.cluster.local:8080                         │
│      _pod_sa:                                       (v1:spec.serviceAccountName)                                           │
│      _l5d_ns:                                      linkerd                                                                 │
│      _l5d_trustdomain:                             cluster.local                                                           │
│      LINKERD2_PROXY_IDENTITY_LOCAL_NAME:           $(_pod_sa).$(_pod_ns).serviceaccount.identity.$(_l5d_ns).$(_l5d_trustdom│
│ain)                                                                                                                        │
│      LINKERD2_PROXY_IDENTITY_SVC_NAME:             linkerd-identity.$(_l5d_ns).serviceaccount.identity.$(_l5d_ns).$(_l5d_tr│
│ustdomain)                                                                                                                  │
│      LINKERD2_PROXY_DESTINATION_SVC_NAME:          linkerd-destination.$(_l5d_ns).serviceaccount.identity.$(_l5d_ns).$(_l5d│
│_trustdomain)                                                                                                               │
│      LINKERD2_PROXY_TAP_SVC_NAME:                  linkerd-tap.$(_l5d_ns).serviceaccount.identity.$(_l5d_ns).$(_l5d_trustdo│
│main)                                                                                                                       │
│      LINKERD2_PROXY_TRACE_COLLECTOR_SVC_ADDR:      oc-collector.tracing:55678                                              │
│      LINKERD2_PROXY_TRACE_COLLECTOR_SVC_NAME:      default.tracing.serviceaccount.identity.$(_l5d_ns).$(_l5d_trustdomain)  │
│

- Kubernetes Version: 1.14.6
- Cluster Environment: (GKE, AKS, kops, ...) EKS
- Host OS:
- Linkerd version: 2.6.1

**Comment by derrickburns** [comment]
@grampelberg fyi

**Comment by grampelberg** [comment]
@adleong mind taking a peek at this?

**Comment by adleong** [comment]
Hi @derrickburns!  We fixed some very similar looking errors in https://github.com/linkerd/linkerd2/releases/tag/edge-20.1.2.  Could you give the latest edge release a try and see if that resolves the issue?

**Comment by derrickburns** [comment]
@adleong 
Not I am getting this:
│ WARN [     0.006065s] opencensus:control{peer.addr=172.20.66.96:55678 peer.identity=Some("default.tracing.serviceaccount.identity.linkerd.cluster.local")}: rustls::session Sending fatal alert BadCertificate

**Comment by adleong** [comment]
Hmmm sounds like a certificate issue with the upgrade.  Can you run `linkerd check`?  

If you hop into linkerd slack, we can help you debug this more synchronously, if you prefer.

**Comment by derrickburns** [comment]
That did not solve my problem:
```
 WARN [   980.288122s] outbound:accept{peer.addr=10.47.22.221:59486}:h2: linkerd2_trace_context::layer span dropped error=no available capacity      │
│ WARN [   980.288206s] outbound:accept{peer.addr=10.47.22.221:55134}:source{target.addr=172.20.66.96:55678}:addr{addr=oc-collector.tracing:55678}:lo │
│ gical{dst.logical=oc-collector.tracing.svc.cluster.local:55678}:concrete{dst.concrete=oc-collector.tracing.svc.cluster.local:55678}:endpoint{peer.a │
│ ddr=10.47.51.31:55678 peer.id=Some("default.tracing.serviceaccount.identity.linkerd.cluster.local")}: linkerd2_trace_context::layer span dropped er │
│ ror=no available capacity
```

**Comment by derrickburns** [comment]
I do this this in the oc-collector linkerd proxy logs:
```
│ ERR! [    33.935050s] rustls::session TLS alert received: Message {                                                                                           ││     typ: Alert,                                                                                                                                               │
│     version: TLSv1_2,                                                                                                                                         ││     payload: Alert(                                                                                                                                           │
│         AlertMessagePayload {                                                                                                                                 ││             level: Fatal,                                                                                                                                     │
│             description: BadCertificate,                                                                                                                      ││         },                                                                                                                                                    │
│     ),                                                                                                                                                        ││ }
```

**Comment by adleong** [comment]
Definitely seems like some kind of certificate issue.   Can you run `linkerd check`?

Another thing to try would be to restart the oc-collector and/or the pods which are sending trace data to it.

**Comment by adleong** [comment]
Hey @derrickburns, and luck with this?

**Comment by dad264** [comment]
We were having this issue too. After upgrading to 2.7.0, it went away. FWIW.
