### ISSUE TITLE
Owner Metadata for Spans.

### ISSUE THREAD

**Issue by Pothulapati** [linkerd/linkerd2#4008]
## Feature Request

Right Now, For metrics Prometheus automatically adds the pod's labels as metric labels, giving us the capability to link grafana dashboard for that component directly in the linkerd dashboard and allowing users to jump there seamlessly.

A similar model with Jaeger would be great i.e jumping directly from the linkerd dashboard to the jaeger dashboard and showing relevant spans of the component. This would require some labels to be present that allows us to filter spans based on the selected component. 

We already send some owner Metadata, for the spans as seen in the picture.  

![image](https://user-images.githubusercontent.com/7892868/73676482-751ef780-46da-11ea-9cb6-0256fbbaa4dc.png)
The `hostname` label allows us to categorize spans based on the pod that the spans came from, allowing us to directly specify a link with the query `hostname` label for pods. But we would also want a similar case for the `kind` and `name` of workload.

Sadly, This Information is actually not passed into the pod's env variables right now. The `hostname` is injected by k8s currently and we use that. But A similar thing is not present for workloads.

### What problem are you trying to solve?

More metadata for spans.

### How should the problem be solved?

We already find the workload, type information during injection and add them as `pod` labels.
We can use the downward API https://kubernetes.io/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/ to make those labels attached as volumes for the `linkerd-proxy` to attach them as labels here.
https://github.com/linkerd/linkerd2-proxy/blob/9faff18c8a6ffabe92afcd2a47ab169b99baa1b0/linkerd/trace-context/src/layer.rs#L142

### Any alternatives you've considered?
- In Open Telemetry, there is a k8s processor which attaches those labels as per https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/master/processor/k8sprocessor by doing a reverse pod lookup of the pod. But openTelemtry is not 1.0 yet. I'm giving this a try and will psot the results.
Further reading:
https://developers.soundcloud.com/blog/using-kubernetes-pod-metadata-to-improve-zipkin-traces

@grampelberg

**Comment by ihcsim** [comment]
> What problem are you trying to solve?
> More metadata for spans.

For my understanding, are there other places where these metadata will be useful, other than linking the Jaeger dashboard to the Linkerd dashboard? Since tracing is an optional addon, do we want the Linkerd dashboard to be coupled to it?

**Comment by Pothulapati** [comment]
@ihcsim 
reg Jaeger
The dashboard will only show the relevant jaeger link when the add-on is enabled, or a relevant endpoint is passed by the user.

Also, I'm thinking there will be more use-cases where these values would be needed by the proxy, 
-  Where users are directly sending their spans somewhere without otel/oc-collector.
-  for mesh expansion where k8s labels will not be present for Prometheus to auto add k8s-resource labels as metric labels.

**Comment by olix0r** [comment]
Depends on at least #4199
