### ISSUE TITLE
Flaky log regex in install_test.go

### ISSUE THREAD

**Issue by adleong** [linkerd/linkerd2#4014]
install_test sometimes fails with this error:

```
   install_test.go:766: Found unexpected warning events:
        Reason: [FailedKillPod] Object: [linkerd-controller-68c9fb7c5d-plwjg] Message: [error killing pod: failed to "KillPodSandbox" for "0ed46c6d-0a12-4450-81da-a203c3e7ccd1" with KillPodSandboxError: "rpc error: code = Unknown desc = failed to destroy network for sandbox \"299f782bb7fb8b3bcdf9cfe0ddeab6733742cc85572244ceb2eeda43af8cd79f\": could not teardown ipv4 dnat: running [/usr/sbin/iptables -t nat -F CNI-DN-f81f9cf39e2561a3613e7 --wait]: exit status 1: iptables: No chain/target/match by that name.\n"]
```

The install test already has a regex to ignore iptables delete errors (e.g. that use the `-X` flag).  Perhaps we also need to update that regex to include iptables flush errors (e.g. that use the `-F` flag)?

**Comment by christyjacob4** [comment]
@adleong I'd like to take this up :) 
Please let me know where I can start

**Comment by ihcsim** [comment]
@christyjacob4 This issue involves updating the Linkerd integration test suite. You can find more information on how to run the integration test [here](https://github.com/linkerd/linkerd2/blob/master/TEST.md#integration-tests).

**Comment by christyjacob4** [comment]
@adleong How can I reproduce this?

**Comment by christyjacob4** [comment]
@adleong Can you please tell me how I can reproduce it

**Comment by grampelberg** [comment]
@christyjacob4 we're not actually sure if this is still happening or not. Closing this out for now.
