### ISSUE TITLE
Reduce turnaround time on failed CI workflows

### ISSUE THREAD

**Issue by kleimkuhler** [linkerd/linkerd2#4016]
## Motivation

Dealing with flakiness in one job is costly because re-running a workflow
through GH Actions re-runs every job--regardless if that job succeeded in a
previous run.

Being able to cache successful results on a job basis for a specific commit
could speed up re-runs when necessary.

## Solution

This is just an idea to explore, but it could reduce the turnaround time for
re-running workflows when dealing with flakiness.

Kicking off a new run through GH Actions runs the entire workflow on the
*same* commit. We could consider caching a `commit-job.id-success.txt` file
for each job in the workflow. At the start of the job, a step tries to fetch
the file based off the current commit; if there is a cache hit then the rest
of the job does not run.

If there is a cache miss, then the remaining steps run like usual. At the end
of the job, a final step with an `if: success()` condition creates an empty
file (`touch commit-job.id-success.txt`) and caches the file.

If the workflow run fails on a later job, then a re-run would see previous
jobs that have succeeded and not run them.

"Emptying" the cache is as easy as changing the commit. This could be done
with a force push or `--allow-empty` commit.

@alpeb @adleong

**Comment by kleimkuhler** [comment]
I changed the issue title as I think the great issue I'm thinking about is how to reduce the turnaround time on failed workflow runs that re-run on the same commit.

**Comment by kleimkuhler** [comment]
After speaking with @siggy, another potential solution brought up is separating the single workflow that we currently have into independent workflows.

This could be something like a workflow for unit tests, KinD integration tests, and cloud integration tests. That way, if cloud integration tests fail and we want to run that workflow it does not require re-running the unit tests and KinD integration tests.

**Comment by grampelberg** [comment]
I'm doing this for the website (separate workflows) and have been happy with it there.

**Comment by alpeb** [comment]
Currently being addressed in #4039

**Comment by alpeb** [comment]
Fixed via #4039
