### ISSUE TITLE
Idempotent installs

### ISSUE THREAD

**Issue by derrickburns** [linkerd/linkerd2#4017]
One of the challenges of installing Linkerd is that the installation is not idempotent.  

One cannot use the `linkerd` cli to install linkerd in succession.  Nor can one use the helm chart to do that.  

While this may seem  like a silly requirement, consider a `gitops` environment where one wants to use Git as the single source of truth for desired cluster state.  Can one create a helm release (ala fluxcd) that can be used in an idempotent manner?

**Comment by grampelberg** [comment]
With the requirement of having a persistent trust root, is it possible to ever make the install idempotent?

**Comment by grampelberg** [comment]
I'd be interested to hear what's missing from `helm upgrade --install` as well.

**Comment by derrickburns** [comment]
The trust root is indeed the issue. 

One way of handling that is to separate the installation of the trust root from the rest of the helm installation. This isolates the side effect from most of the .

**Comment by grampelberg** [comment]
Have you taken a look at the cert-manager integration that is on master right now?

**Comment by derrickburns** [comment]
No. I will

**Comment by derrickburns** [comment]
@grampelberg I installed stable-2.7.0 on my test clusters.  Thanks.  Now, I have to give some serious thought about how I want to bootstrap the secret needed by linkerd. :)

**Comment by grampelberg** [comment]
My recommendation is to have it be checked into git and decrypted at runtime. The other alternative would be sealed secrets.

**Comment by grampelberg** [comment]
@derrickburns I think we've got this fixed for you now, please reopen if there's something missing.
