### ISSUE TITLE
cmd/linkerd: support --token: Bearer token for authentication to the Kubernetes API server

### ISSUE THREAD

**Issue by humboldt-xie** [linkerd/linkerd2#4026]
We use id_token to use Kubernetes api

so we need support Bearer token for authentication to the Kubernetes API server with flags

```
linkerd check --token "balabala"
```

**Comment by grampelberg** [comment]
Is that not in your kubeconfig?

**Comment by humboldt-xie** [comment]
> Is that not in your kubeconfig?

no,the token is dynamic,Inconvenient to edit kubeconfig every time

**Comment by humboldt-xie** [comment]
#4027

**Comment by adleong** [comment]
Thanks @humboldt-xie!  I took a look at your PR and the code looks reasonable.  However, a design goal of Linkerd is that it does as little as possible and lets other tools do what they do best.  In this case, we assume that the kubeconfig completely describes the authentication method and credentials.

Is it possible to address your use-case with some automation or a wrapper script which automatically edits the kubeconfig on each invocation?  This seems like a more appropriate separation of concerns to me.  Let me know what you think.

**Comment by humboldt-xie** [comment]
> Thanks @humboldt-xie! I took a look at your PR and the code looks reasonable. However, a design goal of Linkerd is that it does as little as possible and lets other tools do what they do best. In this case, we assume that the kubeconfig completely describes the authentication method and credentials.
> 
> Is it possible to address your use-case with some automation or a wrapper script which automatically edits the kubeconfig on each invocation? This seems like a more appropriate separation of concerns to me. Let me know what you think.

we use this like:
```
linkerd check --token "$(oauth2-fetch-token)" 
```
in a common product machine. we didn't want to save the token to filesystem

**Comment by grampelberg** [comment]
I'm pretty surprised this isn't an environment variable (which we'd just pick up as part of the REST auth dance).
