### ISSUE TITLE
Tell me what proxies are out of date

### ISSUE THREAD

**Issue by derrickburns** [linkerd/linkerd2#4030]
When upgrading linkerd, updating the control plane is easy.  

What is also easy is ending up with proxies that use the older version of the proxies.

It would be nice to have a simple tool to list the proxies that need updating.

**Comment by grampelberg** [comment]
This would be a great addition to `check`. With the existing version check, the CLI could list what pods don't match as well.

**Comment by derrickburns** [comment]
Hmmm. `linkerd check --proxy` does the trick.  Ooops.

**Comment by grampelberg** [comment]
Ahha! I thought we had something like that, perfect.
