### ISSUE TITLE
Ingress-nginx cannot deploy new pods after injected

### ISSUE THREAD

**Issue by vic3lord** [linkerd/linkerd2#4031]
## Bug Report

New nginx-ingress-controller pods are not deployed after injecting the sidecar

### What is the issue?

Cannot inject linkerd-proxy into ingress-nginx

### How can it be reproduced?

```
kubectl annotate ns ingress-nginx linkerd.io/inject=enabled
kubectl -n ingress-nginx delete pod --all # or just rollout restart
```

### Logs, error output, etc

```
kubectl -n ingress-nginx describe deploy nginx-ingress

Events:
  Type    Reason    Age                     From                    Message
  ----    ------    ----                    ----                    -------
  Normal  Injected  2m25s (x17 over 2m46s)  linkerd-proxy-injector  Linkerd sidecar proxy injected


kubectl -n ingress-nginx get pod
No resources found in ingress-nginx namespace.
```

#### `linkerd check` output

```text
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-identity
----------------
√ certificate config is valid
√ trust roots are using supported crypto algorithm
√ trust roots are within their validity period
√ trust roots are valid for at least 60 days
√ issuer cert is using supported crypto algorithm
√ issuer cert is within its validity period
√ issuer cert is valid for at least 60 days
√ issuer cert is issued by the trust root

linkerd-api
-----------
√ control plane pods are ready
√ control plane self-check
√ [kubernetes] control plane can talk to Kubernetes
√ [prometheus] control plane can talk to Prometheus
√ tap api service is running

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ control plane is up-to-date
√ control plane and cli versions match

Status check results are √
```

### Environment

- Kubernetes Version: 1.14.8-gke.33
- Cluster Environment: GKE
- Host OS: COS
- Linkerd version: 2.7

### Additional context

EDIT: Looking at the logs of the linkerd-injector:

```
time="2020-02-10T08:18:32Z" level=info msg="received pod/nginx-ingress-controller-8489f8896c-"
time="2020-02-10T08:18:32Z" level=info msg="patch generated for: pod/nginx-ingress-controller-8489f8896c-"
time="2020-02-10T08:18:39Z" level=info msg="received admission review request f11be55d-4bdd-11ea-82a2-42010a84014b"
time="2020-02-10T08:18:39Z" level=info msg="received pod/nginx-ingress-controller-8489f8896c-"
time="2020-02-10T08:18:39Z" level=info msg="patch generated for: pod/nginx-ingress-controller-8489f8896c-"
time="2020-02-10T08:18:39Z" level=info msg="received admission review request f122d7e6-4bdd-11ea-82a2-42010a84014b"
time="2020-02-10T08:18:39Z" level=info msg="received pod/nginx-ingress-controller-8489f8896c-"
time="2020-02-10T08:18:39Z" level=info msg="patch generated for: pod/nginx-ingress-controller-8489f8896c-"
time="2020-02-10T08:18:41Z" level=info msg="received admission review request f2303c65-4bdd-11ea-82a2-42010a84014b"
time="2020-02-10T08:18:41Z" level=info msg="received pod/nginx-ingress-controller-8489f8896c-"
time="2020-02-10T08:18:41Z" level=info msg="patch generated for: pod/nginx-ingress-controller-8489f8896c-"
time="2020-02-10T08:24:08Z" level=info msg="received admission review request b5853ed6-4bde-11ea-82a2-42010a84014b"
time="2020-02-10T08:24:08Z" level=info msg="received pod/nginx-ingress-controller-8489f8896c-"
time="2020-02-10T08:24:08Z" level=info msg="patch generated for: pod/nginx-ingress-controller-8489f8896c-"
```

**Comment by grampelberg** [comment]
My first guess would be issues with PSP on your cluster. It appears that linkerd is working correctly. Check the events on the replication controller.

**Comment by vic3lord** [comment]
Found the issue, ingress-nginx comes with a `LimitRange` object that requires minimum CPU and RAM requests, linkerd sidecar is below this range.

**Comment by quentinalbertone** [comment]
Hi, @vic3lord 

I have the same problem, could you tell me :  how did you resolve this issue ?

**Comment by ihcsim** [comment]
@quentinalbertone You can adjust the Linkerd proxy sidecar CPU and RAM requests to satisfy the min/max values defined by your `LimitRange`. The `linkerd install --ha` command will output the default values used by the Linkerd proxy. These values can be adjusted using the `--proxy-[cpu|memory]-[limit|request]` options, of the `install` or `inject` commands.

**Comment by rediphone** [comment]
Hi - Sorry i have this same problem but i dont understand the answer. 

I cant see any limit range objects in my cluster when i deploy ingress-nginx without linkerd enabled on the ingress

my values file for ingress-nginx contains:
  resources:
    limits:
      cpu: 0.3
      memory: 1G
    requests:
      cpu: 0.1
      memory: 512Mi

ingress-nginx installation wont get past creating the initial pod creation of ingress-nginx-admission-create pod when linkerd is enabled via annotating the namespace. removing the annotation for linkerd allows nginx to deploy correctly 

linkderd is being installed with the command 
      linkerd install --proxy-version stable-2.8.1 --ha | kubectl apply -f -

**Comment by grampelberg** [comment]
@rediphone is there something not working? `nginx-ingress-nginx-admission-create` and `nginx-ingress-nginx-admission-patch` are jobs and if you inject them they'll not complete as k8s can't stop sidecars in jobs. Either don't inject them or just verify that the main container completed and delete the jobs after the install.

**Comment by geertn** [comment]
@rediphone I was able to workaround nginx ingress (deployed with helm) not starting by replacing the NS annotation with populating podAnnotations in the chart:

```
controller:
  podAnnotations:
    linkerd.io/inject: enabled
```

Maybe this helps

**Comment by rediphone** [comment]
Thanks both for getting back to me. 

My issue was the order in which I was doing things. As i was testing Linkerd was already installed and as such it would effect nginx's activity whenn it was trying to setup

When i actually deploy nginx is insalled first so it gets setup and then linkerd takes over so it works fine. 

Thaat is at least what i think is happening as I am able to work correctly with nginx installing first without linkerd in place. 
thanks
