### ISSUE TITLE
Per route metrics labels is not the same as generic ones

### ISSUE THREAD

**Issue by lohmag** [linkerd/linkerd2#4046]
When `ServiceProfile` is used it activates ability to expose per route metrics for Prometheus and they look like that
```
route_request_total{direction="inbound",dst="voting-svc.emojivoto.svc.dev.k8s:8080",rt_route="VoteDoughnut"} 74
route_response_latency_ms_bucket{direction="inbound",dst="voting-svc.emojivoto.svc.dev.k8s:8080",rt_route="VoteDoughnut",status_code="200",le="1"} 70
route_response_latency_ms_bucket{direction="inbound",dst="voting-svc.emojivoto.svc.dev.k8s:8080",rt_route="VoteDoughnut",status_code="200",le="2"} 74
route_response_latency_ms_bucket{direction="inbound",dst="voting-svc.emojivoto.svc.dev.k8s:8080",rt_route="VoteDoughnut",status_code="200",le="3"} 74
route_response_latency_ms_bucket{direction="inbound",dst="voting-svc.emojivoto.svc.dev.k8s:8080",rt_route="VoteDoughnut",status_code="200",le="4"} 74
route_response_latency_ms_bucket{direction="inbound",dst="voting-svc.emojivoto.svc.dev.k8s:8080",rt_route="VoteDoughnut",status_code="200",le="5"} 74
```
Now look at default metrics
```
request_total{authority="web-svc.emojivoto.svc.dev.k8s",direction="outbound",dst_control_plane_ns="linkerd",dst_deployment="web",dst_namespace="emojivoto",dst_pod="web-744588c478-965t4",dst_pod_template_hash="744588c478",dst_service="web-svc",dst_serviceaccount="web",tls="true",server_id="web.emojivoto.serviceaccount.identity.linkerd.dev.k8s"} 1110
response_latency_ms_bucket{authority="web-svc.emojivoto.svc.dev.k8s",direction="outbound",dst_control_plane_ns="linkerd",dst_deployment="web",dst_namespace="emojivoto",dst_pod="web-744588c478-965t4",dst_pod_template_hash="744588c478",dst_service="web-svc",dst_serviceaccount="web",tls="true",server_id="web.emojivoto.serviceaccount.identity.linkerd.dev.k8s",status_code="200",le="1"} 0
```
As it seen per route metrics doesn't contain a lot of this extra labels which is very helpful for grafana dasboards and etc.  
Maybe it is was made intentionally i don't know just my pain with linkerd implementation.

**Comment by grampelberg** [comment]
@adleong any ideas?

**Comment by adleong** [comment]
@lohmag that's correct, the per-route metrics have a different set of labels from the per-endpoint labels because they are measured in different places in the proxy.  A single endpoint, for example, could be used by multiple routes.

If you give us more details about the problem you're trying to solve or the grafana dashboard you want to create, we can give more concrete advice about which metrics you should be looking at.

**Comment by lohmag** [comment]
> @lohmag that's correct, the per-route metrics have a different set of labels from the per-endpoint labels because they are measured in different places in the proxy. A single endpoint, for example, could be used by multiple routes.
> 
> If you give us more details about the problem you're trying to solve or the grafana dashboard you want to create, we can give more concrete advice about which metrics you should be looking at.

If you look for default Grafana dashboard it shows per deployment traffic inside it. But i cannot add per-route metrics inside this Inbound/Outbound per deployments destinations. So it is needed to create the second set of graphs which shows per service metrics. Unification would be good i think.

**Comment by adleong** [comment]
Agreed that these metrics and the labels which are available at different points are confusing.  I don't think we can change the label scopes immediately, but this is definitely something to keep in mind as the Linkerd metrics system evolves.

**Comment by lundbird** [comment]
Not a fix for this, but if you are looking to visualization into per route metrics, I have published one we created at my company here: https://grafana.com/grafana/dashboards/11868. This gives you visualization into your success-rate, latency, and rps. This is similar to the existing dashboards, but this has variables set so you can drill down by sender, receiver, status-code, and rt_route for any span of time.
