### ISSUE TITLE
Fix racy CNI install

### ISSUE THREAD

**Issue by zaharidichev** [linkerd/linkerd2#4049]
Currently our CNI plugin supports two modes of install: 

- Stand - alone - without chaining to other CNI plugins
- Chained - when chaining with other CNI plugins

The way chaining works is that if the cni install script that runs sees that there is already a plugin configuration present in the folder it will update it and chain its config to this configuration. In the case of Calico that would be `10-calico.conflist`. What sometimes happens however is that upon spawning a new node, the Calico install will lag behind the CNI install and the cni will install its configuration, assuming there is no other CNI plugin in place. This will effectivelly break Calico and will cause a lot of the pods to fail. 

A potential solution is to always assume that the CNI plugin is installed in scenarios where there is another plugin to chain with. We can then make the script wait until this other plugin's config is present and chain itself into it. This will introduce another problem. It could be the case that the Linkerd pods start up before our CNI plugin had the chance to install itself. This will break Linkerd as there will be no iptables rules on our pods. One way to fix that is to introduce an Init container that waits until the desired iptables config is present. That should ensure that we achieve some sort of synchronisation between all of these steps and eliminate the racy scenarios. 

This problem was originally reported in #4029

**Comment by codeman9** [comment]
https://github.com/linkerd/linkerd2/issues/2219

**Comment by alex-berger** [comment]
This is also true for the [AWS VPC CNI Plugin](https://github.com/aws/amazon-vpc-cni-k8s) (the `aws-node` daemonset on AWS EKS clusters). I added a comment on #2219 regarding that.

**Comment by alpeb** [comment]
Closing, as this particular issue was addressed in [cni-plugin v1.2.0](https://github.com/linkerd/linkerd2-proxy-init/releases/tag/cni-plugin%2Fv1.2.0) by dropping the "interface" mode.
