### ISSUE TITLE
Does automatic TLS work for grpc?

### ISSUE THREAD

**Issue by vijaygos** [linkerd/linkerd2#4059]
I can't seem to get TLS working out of the box of GRPC connections on my clusters. Is that a known caveat? I can proxy grpc traffic through the linkerd-proxy but the traffic is unencrypted. 
What are the pipeline goals for this?
Also, is there a hack to get this working in the current version?

**Comment by grampelberg** [comment]
Yes, mTLS works for gRPC. Please come to the slack channel so that we can help you there.
