### ISSUE TITLE
Unable to get Linkerd Dashboard: This does not match /^(localhost|127\.0\.0\.1| :-has been denied for security reasons

### ISSUE THREAD

**Issue by Ohmakhisya** [linkerd/linkerd2#4060]
Hello Team,

I am trying to install Linkerd on top of my Kubernetes 3 node cluster. After the Linkerd installation i am not able to get Linkerd Dashboard.

Error:- This does not match /^(localhost|127\.0\.0\.1|linkerd-web\.linkerd\.svc\.cluster\.local|linkerd-web\.linkerd\.svc|\[::1\])(:\d+)?$/ and has been denied for security reasons.

All my pods are in running status. and 2/2 checks success, firewalld disabled.

Kindly help me to solve this issue.

Thanks & Regards,
Akhil

**Comment by alpeb** [comment]
Hi @Ohmakhisya 
That check was introduced in 2.7.0 to avoid DNS-rebinding attacks, as explained [here](https://linkerd.io/2/tasks/exposing-dashboard/#dns-rebinding-protection). If the instructions in that doc don't work for you, please let me know how you're trying to access the dashboard.

**Comment by grampelberg** [comment]
Please jump into slack for questions like this.

**Comment by Ohmakhisya** [comment]
> Hi @Ohmakhisya
> That check was introduced in 2.7.0 to avoid DNS-rebinding attacks, as explained [here](https://linkerd.io/2/tasks/exposing-dashboard/#dns-rebinding-protection). If the instructions in that doc don't work for you, please let me know how you're trying to access the dashboard.

Hi alpeb,
Thanks for the reply,
i have referred this link its not helping me. i am getting the attached error. Before i was getting the dashboard and able to access the dashboard following official documentation. But last 1 week i am getting the below error. Kindly look into the issue.
[Linkerd issue.docx](https://github.com/linkerd/linkerd2/files/4230094/Linkerd.issue.docx)

**Comment by grampelberg** [comment]
@Ohmakhisya this is a configuration error on your side. You need to either rewrite the host header or change the regex. Please jump on slack if you'd like more help on the issue.
