### ISSUE TITLE
Export Multicluster Metrics to Prometheus

### ISSUE THREAD

**Issue by zaharidichev** [linkerd/linkerd2#4063]
Once we have the Multicluster Mirror working and merged, we need to export metrics about the state of our mirrored clusters to Prometheus. Things that come to mind are, last_update, gateway_readyness , num_services_mirrored, etc.

**Comment by grampelberg** [comment]
We should think through what kind of CLI output we'd want here as well. What does it mean for everything to be "healthy" and "up to date"? What do we need to know to explain why it is either unhealthy or not up to date?

**Comment by zaharidichev** [comment]
This is being addressed in #4233
