### ISSUE TITLE
Implement Liveliness checks for Remote cluster Gateways

### ISSUE THREAD

**Issue by zaharidichev** [linkerd/linkerd2#4064]
Once we have Service Mirroring, we probably want to add some logic that periodically checks whether our remote gateways are healthy.  There are a couple of levels of granularity to this one and we need to probably decide on one of them (or expose configuration to adjust them). 

1. Ensuring that the remote gateway can be reached on the Ip address that is advertised on the specific port that we target
2. Ensure that the gateway can actually route requests to the desired services and that they can return an adequate status.

All of this can be configure through some metadata on the remote Gateway or the secret that has the credentials on it. It should mimic the k8s Liveliness checks as close as possible

**Comment by grampelberg** [comment]
I don't think we should do #2 remotely. My thinking is that there's a `/ready` endpoint on the gateway which is checked externally. The `/ready` endpoint on the gateway could then either just return a 200 naively or implement some logic that tries to contact backend services. FWIW, even that feels wrong ... k8s should be guaranteeing the reachability internally with readiness checks on the pods and endpoints.

**Comment by zaharidichev** [comment]
This has been implemented
