### ISSUE TITLE
Linkerd installation on Ubuntu VM

### ISSUE THREAD

**Issue by DhruvM1994** [linkerd/linkerd2#4065]
Issue Type:

- [X] Bug report
- [ ] Feature request

**What happened**:
I am trying to install linkerd on an Ubuntu VM. However, the ```linkerd check --pre``` command reports that "No clock skew detected" is not fulfilled. 

**What you expected to happen**:
No pre-check failure.

**How to reproduce it (as minimally and precisely as possible)**:
-Install Ubuntu VM
-Build kubernetes cluster on the VM
-Start linkerd installation

**Environment**:
Output ```linkerd version```:
stable-2.7.0

**Comment by cpretzer** [comment]
@DhruvM1994 Please have a look at #3943 because it sounds like the same behavior that you describe

**Comment by cpretzer** [comment]
hi @DhruvM1994 have you had a chance to look at #3943?

If it looks like the same issue, let's close this one out and collaborate on the other issue.

**Comment by DhruvM1994** [comment]
Hey @cpretzer, no I did not dig into it so far.

**Comment by cpretzer** [comment]
@DhruvM1994 once you have a look at #3943, let me know whether you think it's the same issue.

If it's different, we'll reopen this one and work on it together
