### ISSUE TITLE
No linkerd support for MSYS_NT-10.0/x86_64

### ISSUE THREAD

**Issue by DhruvM1994** [linkerd/linkerd2#4066]
### What is the issue?
I would like to install linkerd on a single-node kubernetes cluster using docker desktop on a Windows 10 machine. 
I am trying to install linkerd using ```curl -sL https://run.linkerd.io/install | sh```. However, it reports 
```There is no linkerd support for MSYS_NT-10.0/x86_64.```

### How can it be reproduced?
-Install docker desktop and and start kubernetes
-Start installation of linkerd as per https://linkerd.io/2/getting-started/

### Logs, error output, etc
```There is no linkerd support for MSYS_NT-10.0/x86_64.```

### Environment
- Kubernetes Version: v1.15.5
- Cluster Environment: Docker desktop
- Host OS: Windows 10 1809 17763.1039
- Linkerd version: 2.7.0

**Comment by drholmie** [comment]
Hey there! (Hope I've understood the problem correctly) By default the Linkerd version installed using `curl -sL https://run.linkerd.io/install | s` is not meant for windows (hence the error saying no support). To find the version for windows check the [releases](https://github.com/linkerd/linkerd2/releases/) page and after installing the cli, change it's name to linkerd and add it to your path in windows to continue following along with the getting started page.
