### ISSUE TITLE
Linkerd prevents pods from being evicted by Cluster Autoscaler

### ISSUE THREAD

**Issue by ricky26** [linkerd/linkerd2#4067]
## Bug Report
After installing linkerd and setting our workload namespaces to have the injection annotation, we noticed that Cluster Autoscaler was only scaling the cluster up.

### What is the issue?
When linkerd injects a pod, it creates an `emptyDir` volume for volatile storage. This breaks the rules CA uses to determine whether pods are evictable when it's not been explicitly stated. (Pod should not use `hostPath` or `emptyDir` volumes if they want to be implicitly evictable.)

### How can it be reproduced?
1. Install linkerd.
2. Enable cluster autoscaler.
3. Create a namespace with the linkerd inject attribute on.
4. Create a deployment of a sleep container, small enough that multiple fit on each node, scale it up enough to create multiple nodes.
5. Scale the deployment down to a smaller fraction.
6. Notice that there are several nodes with low resource utilisation which will not be scaled down by CA.

### Environment
- Kubernetes Version: 1.14.10-gke.17
- Cluster Environment: GKE
- Host OS: Container-optimised OS
- Linkerd version: 2.6.1

### Possible solution
- Have linkerd default the `cluster-autoscaler.kubernetes.io/safe-to-evict` annotation to false, upon injection.
- Have a standalone reconciler which watches pods and defaults the annotation on all pods who *would* be implicitly evictable if it were not for the linkerd-proxy container.

**Comment by grampelberg** [comment]
I don't know much about cluster autoscaler. Does it assume pods are safe to evict if the annotation isn't there?

**Comment by ricky26** [comment]
@grampelberg if the annotation in specified, it uses that, otherwise there's a series of criteria (https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#what-types-of-pods-can-prevent-ca-from-removing-a-node).

In particular, linkerd makes pods fail the 'Pods with local storage' check, since `emptyDir` is considered local storage.

**Comment by grampelberg** [comment]
I gotcha, that's helpful. I'm concerned that having the annotation added by the injector can have unintended consequences. Feels like we'll have to implement the implicit list and keep it up to date on a per-autoscaler version/configuration. That all seems insanely fragile from my perspective.

**Comment by ricky26** [comment]
@grampelberg I agree - it's a pretty raw deal either way. On the one hand, functionality breaks with linkerd injection turned on as it stands. On the other hand, you're beholden to what are essentially implementation details of CA.

**Comment by grampelberg** [comment]
No matter what, we should get some autoscaling docs up on the website. Missing resource requests get in the way of HPA as well.

**Comment by seeruk** [comment]
Also hit this problem on GKE, it's not a problem really on other cloud providers where you manually deploy and can configure CA. If you're able to start CA with `--skip-nodes-with-local-storage=false` and you don't have any pods where that would cause problems then that solves this problem nicely.

The alternative solution I've currently gone with is building a mutating admission controller that applies the `safe-to-evict` annotation to all pods outside of `kube-system` and `kube-public`. The plan is to extend it to check for something like an `unsafe-to-evict` annotation, or alternatively maybe check if `safe-to-evict` is set and false. I'm not all the way through testing this solution yet.

It'd be nice if Linkerd had a solution to it given most pods don't have local storage by default, and if you want everything in your mesh you need to annotate everything with `safe-to-evict` on GKE. GKE is also partly to blame with it's lack of configurability.

**Comment by kleimkuhler** [comment]
Similar to what @seeruk has already mentioned, some additional documentation has been added for working around this [here](https://linkerd.io/2/features/ha/#working-with-cluster-autoscaler).

This still feels like it's fairly easy to stumble across and online docs are not the most accessible, but it feels safer than Linkerd setting `safe-to-evict` on anything itself.

I'm going to close this for now, but please reopen if you have a better solution for this that would make sense to implement.
