### ISSUE TITLE
Excessive memory usage since upgrade to stable-2.7.0

### ISSUE THREAD

**Issue by tomstreet** [linkerd/linkerd2#4069]
We have been running a Kubernetes cluster (v1.11.5) in AKS for a year or so using linkerd stable-2.0.0. Recently we have built a new AKS cluster (v1.15.7) and upgraded linkerd to stable-2.7.0 but since upgrading we are seeing really high memory usage from the linkerd proxies.

We have a service that sits on the edge and proxies the to the correct service in the cluster. In the old cluster each linkerd proxy in each pod for this service was using roughly 13MiB of memory, but in the new cluster we are seeing it rise to over 1GiB within roughly 30 minutes and it just keeps going. This cluster just has light testing traffic so the requests per second are in the single digits, for the old cluster we see roughly 20rps at peak times.

It is the same edge service version in both clusters.

Azure tells me the OS on all the nodes for the new cluster is:
SKU: aks-ubuntu-1604-201912
Version: 2019.12.11

#### `linkerd check` output - for the new cluster

```text
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-identity
----------------
√ certificate config is valid
√ trust roots are using supported crypto algorithm
√ trust roots are within their validity period
√ trust roots are valid for at least 60 days
√ issuer cert is using supported crypto algorithm
√ issuer cert is within its validity period
√ issuer cert is valid for at least 60 days
√ issuer cert is issued by the trust root

linkerd-api
-----------
√ control plane pods are ready
√ control plane self-check
√ [kubernetes] control plane can talk to Kubernetes
√ [prometheus] control plane can talk to Prometheus
√ tap api service is running

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ control plane is up-to-date
√ control plane and cli versions match

Status check results are √
```
Not really sure what else I can check? Any help appreciated.

**Comment by tomstreet** [comment]
Looks like I have managed to fix this:

The edge service polls a SQLServer DB roughly every minute and I had forgotten to configure the proxy to ignore the port. When I added the `config.linkerd.io/skip-outbound-ports` annotation to ignore the port, the memory issue went away and it is now down to roughly 13MiB. I'm fairly sure that in stable-2.0.0 the when the port wasn't ignored, it just failed to connect to the server. It looks like in stable-2.7.0 the connection to SQLServer succeeds but it causes this memory issue.

I noticed that other services were affected by this too. As soon as the the edge service was fixed, I restarted the other services and noticed that their proxy memory usage went from roughly 150MiB down to about 6MiB.

**Comment by grampelberg** [comment]
I'm impressed that the connection worked at all. As SQL is a server speaks first protocol, we can't do protocol detection. It should have just hung indefinitely (which'd explain the ballooning memory). Was there an accompanied change in your client versions or configuration for SQL?

**Comment by tomstreet** [comment]
No changes, the only change was in the k8s deployment yaml as part of the migration from linkerd 2.0 to 2.7. In the past we caught this missing ignore port config due to the connection failing, but we missed it this time as it appeared to work fine.

**Comment by zaharidichev** [comment]
@tomstreet Do you happen to have an isolated reproduction of this? We really want to get to the bottom of it.

**Comment by zaharidichev** [comment]
@tomstreet I tried to reproduce this in the following way. 

1. Installed Linkerd 
2. Applied [this yaml](https://gist.github.com/zaharidichev/4bab2c2ca81e35192a110502e74c0f24), providing a mysql instance 
3. Ssh-ed into the client pod and ran `for ((i=1;i<=10000000;i++)); do   mysql -h mysql -ppassword -e "SELECT version()"; sleep 1; done`

After some time memory looks like: 

![Screenshot 2020-03-19 at 17 33 34](https://user-images.githubusercontent.com/4391506/77086367-5bc3d780-6a0a-11ea-95ce-07c9bd4b3132.png)

That is the situation with both master and 2.7-stable. @olix0r do you think that is a reasonable reproduction attempt ?

**Comment by zaharidichev** [comment]
Actually scratch all that. I can see the problem occuring on both stable and master. It was not happening in my first test because I has mysql running on a standard port...

**Comment by olix0r** [comment]
@tomstreet Last week's edge release (`edge-20.4.2`) includes a fix that we expect to address this issue. Are you able to test a newer version of LInkerd?

Alternatively, you can test a single workload by adding an annotation like `config.linkerd.io/proxy-version: edge-20.4.2`

**Comment by zaharidichev** [comment]
@olix0r Isn't this closed now by https://github.com/linkerd/linkerd2-proxy/pull/464 ?

**Comment by olix0r** [comment]
@zaharidichev Yeah. I was waiting for confirmation.

@tomstreet Please reopen this if you observe behavior like this in newer versions!

**Comment by tomstreet** [comment]
Yeh sorry not had a chance to test this yet. Thanks and good job on the fix!

**Comment by tomstreet** [comment]
Finally had a chance to test this - all fixed. Thanks!

**Comment by olix0r** [comment]
Thanks @tomstreet!
