### ISSUE TITLE
Add minimal release workflow

### ISSUE THREAD

**Issue by kleimkuhler** [linkerd/linkerd2#4078]
## Motivation

A release workflow will be the only triggered workflow on `push.tags` events.

As a first step in automating the release process, it should assert that
integration tests pass once the docker images have been tagged.

It then would need to run the `chart_depoloy` job.

## Solution

This workflow should:
- Build the docker images on the Packet Host
- Tag the docker images with the release tag
- Run KinD integration tests
- Run cloud integration tests
- Run `chart_deploy`

**Comment by alpeb** [comment]
Addressed in #4090
