### ISSUE TITLE
Add release tag creation script

### ISSUE THREAD

**Issue by kleimkuhler** [linkerd/linkerd2#4079]
## Motivation

Creating a release tag is a manual process that is prone to error by the
release responsible member.

Additionally, the automated release project will require that a message is
included that is a copy of the recent `CHANGES.md` changes.

These steps can be scripted so that the member will just need to run a release
script.

## Solution

A `bin/create-release-tag` script will:
- Take a `$TAG` argument (maybe can remove this in the future) to use as the
  tag name
- Pull out the top section of `CHANGES.md` to use as the commit message
- Create the a tag with `$TAG` name and ensure it is signed by the member

**Comment by alpeb** [comment]
Addressed in #4091
