### ISSUE TITLE
Update Linkerd website from release workflow

### ISSUE THREAD

**Issue by kleimkuhler** [linkerd/linkerd2#4081]
## Motivation

Updating [website](https://github.com/linkerd/website) to the new Linkerd
version is a manual step in the release process that can be automated.

## Solution

Add new jobs to the release workflow that:
- Push directly to the repository and updated the hard-coded version
- Wait for the website to update the install script by testing the version
  that would be installed by the `curl`'d install script

**Comment by alpeb** [comment]
Fixed by #4100 and #4106
