### ISSUE TITLE
Unexpected value for CONNECT method when setting https_proxy

### ISSUE THREAD

**Issue by cpretzer** [linkerd/linkerd2#4093]
The behavior for setting the value of the CONNECT method has changed with version 2.7.0 of the Linkerd proxy. 

When testing with the `[squid](http://www.squid-cache.org/)` caching proxy, the value of the method for version 2.7.0 is the IP address and port of the pod running the `squid` proxy.

```
2020/02/20 00:29:57.625| 11,2| client_side.cc(2347) parseHttpRequest: HTTP Client REQUEST:
---------
CONNECT 10.110.207.3:3128 HTTP/1.1
host: www.google.com:443
user-agent: curl/7.68.0-DEV
proxy-connection: Keep-Alive
l5d-dst-canonical: www.google.com:443


----------
```

The same request sent to a container running with version 2.6.1 of the Linkerd proxy results in this output:
```
2020/02/20 00:27:38.967| 11,2| client_side.cc(2347) parseHttpRequest: HTTP Client REQUEST:
---------
CONNECT www.google.com:443 HTTP/1.1
host: www.google.com:443
user-agent: curl/7.68.0-DEV
proxy-connection: Keep-Alive
l5d-dst-canonical: www.google.com:443


----------
```

# To reproduce
## Setup
Deploy three containers: one with the squid proxy and two containers running curl, each injected with either Linkerd 2.6.1 and Linkerd 2.7.0.

The deployment includes a config map which increases the logging output that writes the output above. The squid output is not written to stdout or stderr, so it is necessary to use `kubectl exec` in to the container and `cd` to the `/var/log/squid` directory, then `tail -f cache.log`.

The YAML below deploys all the pods to the `default` namespace

- create a kubernetes cluster, at the time of filing this issue, the Kubernetes version is 1.15.3 running in `kind`
- install [Linkerd 2.7.0](https://github.com/linkerd/linkerd2/releases/tag/stable-2.7.0) to the cluster
- deploy the squid proxy: `kubectl apply -f https://gist.githubusercontent.com/cpretzer/9ca269d17a9aa154e7c472b8cd8e7ab3/raw/5c2e736cc620769e306b440a8d63cf59542ed34b/squid.yaml`
- deploy a `curl` container using Linkerd 2.6.1: `kubectl apply -f https://gist.githubusercontent.com/cpretzer/9ca269d17a9aa154e7c472b8cd8e7ab3/raw/5c2e736cc620769e306b440a8d63cf59542ed34b/curl-linkerd-2.6.1-injected.yml`
- deploy a `curl` container using Linkerd 2.7.0: `kubectl apply -f https://gist.githubusercontent.com/cpretzer/9ca269d17a9aa154e7c472b8cd8e7ab3/raw/5c2e736cc620769e306b440a8d63cf59542ed34b/curl-linkerd-2.7.0-injected.yml`

## Sending traffic to the containers using the proxy
- To the container running Linkerd 2.6.1: 
```kubectl exec -ti $(kubectl get pods -n default | \ 
     awk '/curl-261/ {print $1}') -n default -- sh -c 'https_proxy="http://squid.default:3128" curl https://www.google.com/ -o /dev/null -s -v'
```
- To the container running Linkerd 2.7.0:
```
kubectl exec -ti $(kubectl get pods -n default | \ 
     awk '/curl-270/ {print $1}') -n default -- sh -c 'https_proxy="http://squid.default:3128" curl https://www.google.com/ -o /dev/null -s -v'
```
# Linkerd 2.6.1 Logs
- [squid](https://gist.githubusercontent.com/cpretzer/9ca269d17a9aa154e7c472b8cd8e7ab3/raw/5c2e736cc620769e306b440a8d63cf59542ed34b/squid-log-261-request.log)
- [linkerd proxy](https://gist.githubusercontent.com/cpretzer/9ca269d17a9aa154e7c472b8cd8e7ab3/raw/5c2e736cc620769e306b440a8d63cf59542ed34b/linkerd-proxy-261-trace.log)

# Linkerd 2.7.0 Logs
- [squid](https://gist.githubusercontent.com/cpretzer/9ca269d17a9aa154e7c472b8cd8e7ab3/raw/5c2e736cc620769e306b440a8d63cf59542ed34b/squid-log-270-request.log)
- [linkerd proxy](https://gist.githubusercontent.com/cpretzer/9ca269d17a9aa154e7c472b8cd8e7ab3/raw/5c2e736cc620769e306b440a8d63cf59542ed34b/linkerd-proxy-270-trace.log)

#### `linkerd check` output
`*NB*: The Linkerd control plane version is 2.7.0. The deployments use the _config.linkerd.io/proxy-version_ annotation to use different versions of the Linkerd proxy`

```text
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-identity
----------------
√ certificate config is valid
√ trust roots are using supported crypto algorithm
√ trust roots are within their validity period
√ trust roots are valid for at least 60 days
√ issuer cert is using supported crypto algorithm
√ issuer cert is within its validity period
√ issuer cert is valid for at least 60 days
√ issuer cert is issued by the trust root

linkerd-api
-----------
√ control plane pods are ready
√ control plane self-check
√ [kubernetes] control plane can talk to Kubernetes
√ [prometheus] control plane can talk to Prometheus
√ tap api service is running

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ control plane is up-to-date
√ control plane and cli versions match

Status check results are √

```

### Environment

- Kubernetes Version: 1.15.3 
- Cluster Environment: Single node Kind cluster
- Host OS: macOS Mojave
- Linkerd version: 
-- Control plane: 2.7.0
-- Proxy: 2.6.1 and 2.7.0

### Additional context
@seanmonstar suggests that linkerd proxy PR #[404](https://github.com/linkerd/linkerd2-proxy/pull/404) might be the cause. I've been digging in to the logic to try to confirm that.

In the Linkerd proxy logs, the difference appears to be the logic executed after building the endpoint.

Here is the [Linkerd 2.6.1 log](https://gist.github.com/cpretzer/9ca269d17a9aa154e7c472b8cd8e7ab3#file-linkerd-proxy-261-trace-log-L37) and here is the [2.7.1 log](https://gist.github.com/cpretzer/9ca269d17a9aa154e7c472b8cd8e7ab3#file-linkerd-proxy-261-trace-log-L37)

**Comment by zaharidichev** [comment]
@cpretzer I think this is fixed on master. Currently the URI authority is set to the correct value on the proxy outbound side. Unfortunatelly I could not see any logs when tailing the cache.log or the access log... Not sure why. But the Linkerd log looks reasonable: 


```
NotProvidedByServiceDiscovery))}:endpoint{peer.addr=10.96.230.197:3128}: linkerd2_proxy_http::normalize_uri: Normalizing URI authority=www.google.com:443
[    42.884586500s] DEBUG outbound:accept{peer.addr=10.244.0.16:36396}:source{target.addr=10.96.230.197:3128}:logical{addr=www.google.com:443}:forward{peer.addr=www.google.com:443 peer.id=None(NoPeerName(NotProvidedByServiceDiscovery))}:endpoint{peer.addr=10.96.230.197:3128}: linkerd2_proxy_http::client: method=CONNECT uri=www.google.com:443 version=HTTP/1.1 headers={"host": "www.google.com:443", "user-agent": "curl/7.69.1-DEV", "proxy-connection": "Keep-Alive", "l5d-dst-canonical": "www.google.com:443"}
[    42.884687300s] DEBUG outbound:accept{peer.addr=10.244.0.16:36396}:source{target.addr=10.96.230.
```

I think we can close that?

**Comment by cpretzer** [comment]
@zaharidichev thanks for the update. I have a reproducible test case and will give it a go on master.

Can you point me to the code that sets the URI? I tried looking for it and got a little lost in the proxy code.

**Comment by zaharidichev** [comment]
@cpretzer I think you can take a look at this and start from there: https://github.com/linkerd/linkerd2-proxy/blob/master/linkerd/app/outbound/src/endpoint.rs#L345. Then take a look at the normalize_uri.rs, where this authority is set towards the end.

**Comment by cpretzer** [comment]
verified that this is now working as expected
