### ISSUE TITLE
Replace timeout.rs with tower-timeout

### ISSUE THREAD

**Issue by hawkw** [linkerd/linkerd2#412]
[`proxy/timeout.rs`](https://github.com/runconduit/conduit/blob/master/proxy/src/timeout.rs) contains an implementation of a timeout Tower middleware. `tower` also contains a [`tower-timeout`](https://github.com/tower-rs/tower/tree/master/tower-timeout) crate that does pretty much the same thing. We may want to replace our hand-rolled timeout implementation with the middleware in `tower-timeout`.

**Comment by hawkw** [comment]
One potential sticking point is that our `Timeout` and its associated response future also have  `tokio_connect::Connect`/`Connected` impls, respectively, that `tower-timeout` lacks. We can't add these impls due to the orphan rules, so we'd need to introduce a newtype or something.

**Comment by briansmith** [comment]
> We can't add these impls due to the orphan rules, so we'd need to introduce a newtype or something.

It seems likely we can add the mocking functionality to this wrapper.
