### ISSUE TITLE
Add resource request and limits to each pod in L5d namespace (including Helm chart)

### ISSUE THREAD

**Issue by KIVagant** [linkerd/linkerd2#4122]
### What problem are you trying to solve?

```
➜ kubectl describe ns linkerd
Name:         linkerd
...
Status:       Active

No resource quota.

No resource limits.

---
NAME                                      READY   STATUS    RESTARTS   AGE
linkerd-controller-868c96678d-nzpk5       2/2     Running   0          19h
linkerd-controller-868c96678d-pct7f       2/2     Running   0          6d18h
linkerd-controller-868c96678d-sql72       2/2     Running   0          6d17h
linkerd-destination-75cdc86bd5-jgwkl      2/2     Running   0          6d18h
linkerd-destination-75cdc86bd5-k95kv      2/2     Running   0          6d17h
linkerd-destination-75cdc86bd5-wqjzq      2/2     Running   0          6d17h
linkerd-grafana-6785894d74-4mvhh          2/2     Running   0          4d3h
linkerd-identity-66499f7898-nmd66         2/2     Running   0          6d18h
linkerd-identity-66499f7898-r8r4g         2/2     Running   0          6d17h
linkerd-identity-66499f7898-s2cnx         2/2     Running   0          6d18h
linkerd-prometheus-67d65c57f5-c5pkb       2/2     Running   0          25m
linkerd-proxy-injector-68767c4867-7qtk5   2/2     Running   0          9h
linkerd-proxy-injector-68767c4867-9b2w8   2/2     Running   0          22h
linkerd-proxy-injector-68767c4867-k8h4w   2/2     Running   0          22h
linkerd-sp-validator-864484d4-hplvs       2/2     Running   0          54m
linkerd-sp-validator-864484d4-sg2bt       2/2     Running   0          22h
linkerd-sp-validator-864484d4-vbztr       2/2     Running   0          25m
linkerd-tap-7ff8676d9-6ds5s               2/2     Running   0          9h
linkerd-tap-7ff8676d9-g5bcd               2/2     Running   0          22h
linkerd-tap-7ff8676d9-lhcpt               2/2     Running   0          23m
linkerd-web-7594bb77fd-njshm              2/2     Running   0          6d18h
```

### How should the problem be solved?

There should be an ability to limit each pod resource usage when installing Linkerd. I found a similar issue (https://github.com/linkerd/linkerd2/issues/2980), but this one is more general. It would be nice to have some recommended defaults, but at least cluster administrators should be able to tune the settings based on their needs.

### Any alternatives you've considered?

–

### How would users interact with this feature?

The resource requests and limits should be configurable in the Helm chart values and in `linkerd install/...` command.

**Comment by grampelberg** [comment]
@KIVagant this happens today and we have recommendations. See:

https://github.com/linkerd/linkerd2/blob/master/charts/linkerd2/values-ha.yaml

Feel free to open things up if we're missing something =)

**Comment by KIVagant** [comment]
@grampelberg , yeah, my bad, I was blind. I actually have the values configured for HA but for some reason, there are no real requests and limits applied to the pods. I'm researching and if find something, will come back.

**Comment by jls-tschanzc** [comment]
@grampelberg But this does not apply to the `linkerd install` CLI command, right? The resulting YAML does not include any resource requests/limits except for the proxies.

**Comment by grampelberg** [comment]
@jls-tschanzc `--ha` will add resource requests and limits to all components.
