### ISSUE TITLE
Annotation on deployment will not trigger a proxy injection

### ISSUE THREAD

**Issue by a7744hsc** [linkerd/linkerd2#4125]
### What is the issue?
I am trying to add a proxy for one of my deployment following the tutorial  https://linkerd.io/2/features/proxy-injection/. 

I have added the annotation "linkerd.io/inject: enabled" to my deployment and restart it with "kubectl rollout restart", but the pods under the deployment are not meshed. 

**Then I add the same annotation to namespace and it works.**

**Does auto injection by "Annotate on deployment" is still supported or not?** 

### Logs, error output, etc
The log from "linkerd logs" show following logs:
```
linkerd-proxy-injector-6fd4788c75-bgvz7 proxy-injector 2020-03-02T07:14:34.796260261Z time="2020-03-02T07:14:34Z" level=info msg="skipped pod/linking-server-6775c8cd59-: neither the namespace nor the pod have the annotation \"linkerd.io/inject:enabled\""
```

**From the log I can see an sentence "neither the namespace nor the pod have the annotation" .
Does this mean annotation only works for namespace and pod?**

#### `linkerd check` output

no error found

### Environment

- Kubernetes Version:
- Cluster Environment: (GKE, AKS, kops, ...)
- Host OS:
- Linkerd version:  stable-2.7.0

**Comment by burov** [comment]
@a7744hsc add annotation for pod template  spec->template->metadata->annotations, instead of metadata->annotation

**Comment by a7744hsc** [comment]
@burov Thank you for your help.   

So the annotation should be on pod level but deployment level and the tutorial is a little misleading.   Do you think we can make an update on it?

**Comment by burov** [comment]
@a7744hsc For me it's makes sense to explicitly describe where you need to put annotation [there](https://linkerd.io/2/features/proxy-injection/),  this is a common situation when people put annotations for Deployment instead of Pod template
