### ISSUE TITLE
Add remote  cluster traffic labels

### ISSUE THREAD

**Issue by zaharidichev** [linkerd/linkerd2#4128]
When Service Mirroring is merged, we would like to be able to distinguish between remote and in-cluster traffic. I think this can be easily done with the addition of a few lables that need to be added by the destinations when it observes new endpoints. Currently the labels added in the metadata (for headless services) are `service` and `namespace`. We can can add to that: 

`remote-cluster-call`
`remote-cluster-name`
`remote-cluster-service`
`remote-cluster-service-namespace`
`remote-cluster-gateway`
`remote-cluster-gateway-namespace`

If I am not mistaken that can work without any change to the proxy. @adleong @grampelberg WDYT?

**Comment by grampelberg** [comment]
@zaharidichev are you thinking of this being a label in the metrics?

**Comment by zaharidichev** [comment]
This is mostly implemented in #4178
