### ISSUE TITLE
Control plane configuration refactoring using viper

### ISSUE THREAD

**Issue by burov** [linkerd/linkerd2#4131]
## Feature Request
Enable configuration using [Viper library](https://github.com/spf13/viper), Viper is a common library for configuration in Golang world, for me it makes sense to onboard viper. Viper support value overriding on different levels default values, file, envs variables, program arguments, this allows people more flexibility in configuration. 

### What problem are you trying to solve?
Enabling viper for configuration makes configuration more flexible, as well that will allow customisation for helm chart which better suits people needs. 
This allow to fix issues as [this one](https://github.com/linkerd/linkerd2/issues/4076)

### How should the problem be solved?
From my current understanding refactoring can be done without breaking changes, as a first step [this package](https://github.com/linkerd/linkerd2/blob/master/pkg/config/config.go)  can be refactored and incapsulate a way how to configuration retrieved  

### How would users interact with this feature?
Users will able to adopt helm chart provided by linkerd team for their needs because linkerd control plane configuration become more flexible.

**Comment by grampelberg** [comment]
FWIW, this only works for `linkerd install`. Helm installs won't work, because of limitations inside of helm. That's the main reason we're asking for the inclusion of trust root today.

**Comment by adleong** [comment]
Thanks for this suggestion, @burov.  However, we're not interested in adopting viper into the project at this time.  Happy to explore other solutions to issues like #4067, though.
