### ISSUE TITLE
proxy log level should not be order-dependent

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#4138]
A proxy log level like `linkerd=debug,warn` does not emit any logs, but `warn,linkerd=debug` seems to work as intended. This is surprising and, I think, a regression from previous behavior. I would expect it to work as longest-match-wins, ignoring order.

**Comment by hawkw** [comment]
Yup, that's definitely a bug. I'll take a look.

**Comment by hawkw** [comment]
should be fixed upstream by tokio-rs/tracing#624
