### ISSUE TITLE
Sidecar is injected when annotation has a value other than `enabled`

### ISSUE THREAD

**Issue by thedevelopnik** [linkerd/linkerd2#4149]
### What is the issue?
Linkerd 2.7 injects sidecar if the "linkerd.io/inject" annotation is set to values other than "enabled". A developer added it as `linkerd.io/inject: "false"` on two deployments and the sidecar was injected.

### How can it be reproduced?
Add the annotation `linkerd.io/inject: "false"` 

### Environment

- Kubernetes Version: 1.14.10.gke-24
- Cluster Environment: GKE
- Host OS: ContainerOptimized OS
- Linkerd version: stable-2.7.0

### Possible solution
Ensure that linkerd is looking specifically for `enabled` to determine if injection should occur.

**Comment by grampelberg** [comment]
@thedevelopnik would you mind explaining more about your setup and maybe sharing the specs? I just tested and value other than `"enabled"` causes it to be skipped.

**Comment by grampelberg** [comment]
Here's the code - https://github.com/linkerd/linkerd2/blob/master/pkg/k8s/labels.go#L96

Maybe you have it enabled on the namespace? `false` isn't the same as `disabled`.

**Comment by mayankshah1607** [comment]
IIRC, such a scenario should have been handled in https://github.com/linkerd/linkerd2/pull/3909

**Comment by grampelberg** [comment]
Closing this for now, please reopen if there's something not working!
