### ISSUE TITLE
proxy: elevated HTTP/2 tail latencies on recent master

### ISSUE THREAD

**Issue by hawkw** [linkerd/linkerd2#4150]
### What is the issue?

Builds of the `linkerd2-proxy` master branch after linkerd/linkerd2-proxy@871e56c9effb3d4ff5ac875a6f2d262d09561f87 display significantly higher 99.9th percentile  latencies in gRPC benchmarks. 
![latency-graphs](https://user-images.githubusercontent.com/2796466/76128318-d592a480-5fb8-11ea-9749-b83c19c132bb.png)
(blue bars are linkerd/linkerd2-proxy@b61b044ead8025c9553d3a1fcd7dcf3db56b9a74, orange bars are linkerd/linkerd2-proxy@871e56c9effb3d4ff5ac875a6f2d262d09561f87).

gRPC benchmarks only:
![ver-backpressure-change-latency-2](https://user-images.githubusercontent.com/2796466/76128390-0e327e00-5fb9-11ea-9b0a-9bfef8e818cc.png)

A subsequent test of linkerd/linkerd2-proxy#456 only shows elevated latencies in the outbound direction:
![ver-cache-latency](https://user-images.githubusercontent.com/2796466/76128441-328e5a80-5fb9-11ea-9563-7532b676a5b9.png)

### How can it be reproduced?

This can be reproduced by checking out an effected master commit in the linkerd2-proxy repo, and running

```console
$ cd profiling && docker-compose build && TCP=0 ./benchmark.sh
```

**Comment by olix0r** [comment]
@hawkw would you mind testing linkerd/linkerd2-proxy@a7a4cbd1? While I can run the tests, i'm having trouble using `plot.sh` to generate graphs...

**Comment by hawkw** [comment]
@olix0r latency on linkerd/linkerd2-proxy@a7a4cbd121da282ee4ba2dc8f420f94feca09390 is significantly reduced!
![ver-latest-latency](https://user-images.githubusercontent.com/2796466/76153382-21f4e780-6080-11ea-89ec-5c2dccd60609.png)
(blue is linkerd/linkerd2-proxy@b61b044ead8025c9553d3a1fcd7dcf3db56b9a74, orange is kerd/linkerd2-proxy@a7a4cbd121da282ee4ba2dc8f420f94feca09390)

Latency on that commit seems slightly higher than linkerd/linkerd2-proxy@b61b044ead8025c9553d3a1fcd7dcf3db56b9a74, but not 100x worse...I'm not sure how significant the difference of three or four milliseconds is here.
