### ISSUE TITLE
False alarm when running linkerd checking against kubernetes 1.17

### ISSUE THREAD

**Issue by a7744hsc** [linkerd/linkerd2#4161]
### What is the issue?
When running ` linkerd check --pre` against a Kubernetes cluster v1.17,  there is a chance that we got an error `clock skew detected for node(s): xxxx,xxx,xxx.

I have spent some time on investigating the root cause. And found that the time skew checking feature is introduced by [this issue](https://github.com/linkerd/linkerd2/issues/2762) and [this PR](https://github.com/linkerd/linkerd2/pull/2803)。

Through the discussion in the above issue, I found that the implementation relies on the fact that  "node status is updated every 10s".

But based on my testing and [this Kubernetes enhancement](https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/0009-node-heartbeat.md),  The node status is updated every 5 minutes by default on Kubernetes v1.17.3.

**So I believe we need to make changes to the validation.**

### Logs, error output, etc

(If the output is long, please create a [gist](https://gist.github.com/) and
paste the link here.)

#### `linkerd check` output

```text
your output here ...
```

### Environment

- Kubernetes Version:
- Cluster Environment: (GKE, AKS, kops, ...)
- Host OS:
- Linkerd version:

**Comment by grampelberg** [comment]
Check out #3947 for a lot more discussion on where this got to. We'd love help getting the PR across the line!

**Comment by grampelberg** [comment]
This should be fixed now with `stable-2.7.1`. Please reopen if you're continuing to see this issue!
