### ISSUE TITLE
Changes to Go dependencies require approval from all code owners

### ISSUE THREAD

**Issue by kleimkuhler** [linkerd/linkerd2#4179]
## Motivation

When a change requires updating Go dependencies, the Dockerfiles in all
sub-directories are changed to have new dependency SHAs.

This is an issue because the code owner for each sub-directory is required to
approve the change, even if two other code owners for other sub-directories
have already left approvals.

Current examples:
- #4170
- #4173

## Solution

@adleong proposed one option of  making a new group of code owners for all of
the Dockerfiles so that changes like the above don't require approvals from
every code owner.

**Comment by grampelberg** [comment]
I didn't even consider the Dockerfiles. Adding a group just for those files sounds like a fantastic idea to me.

Are there any other shared artifacts in the repo like that we should add?

**Comment by kleimkuhler** [comment]
Maybe `.golden` files? They are only in `cli/` and `test/`.

I think the code owners of those directories will probably review those PRs anyways, but there may be some cases where a change is required that doesn't necessarily require a full review from the `cli/` or `test/` code owner?
