### ISSUE TITLE
cli: Update resource selectors for tap, top, routes and metrics commands

### ISSUE THREAD

**Issue by mayankshah1607** [linkerd/linkerd2#4183]
Following up with the discussion on https://github.com/linkerd/linkerd2/pull/4120, the below mentioned updates need to be made to the Linkerd CLI
- Unify various methods that retrieve label selectors
- Add support for `tap`,`top`,`routes`,`stat` to accept list of resources
- Update `metrics` command to accept label selectors - `--selector` flag
- Update `metrics` command to not require resource name while using the `--selector` flag

cc @alpeb

**Comment by alpeb** [comment]
Thanks for creating this issue :+1: 
One thing to consider is that currently there's work undergoing on a `linkerd alpha stat` command by @adleong that will ultimately replace `linkerd stat`, so you might wanna apply your `stat` changes to the new one only.

**Comment by mayankshah1607** [comment]
Yep, had a word with @adleong recently. Looks like the SMI-Metrics API doesn't yet support label selectors, so we might have to open an issue there regarding this.
