### ISSUE TITLE
PSP issue while injecting the side car

### ISSUE THREAD

**Issue by saiharshitachava** [linkerd/linkerd2#4189]
Hi Team..
I have setup linkerd 2
using the link
https://linkerd.io/2/getting-started/

When I try the proxy inject none of pods start with error
39s         Warning   FailedCreate        ReplicaSet   (combined from similar events): Error creating: pods "web-756c775dc4-4m99j" is forbidden: unable to validate against any pod security policy: [spec.initContainers[0].securityContext.capabilities.add: Invalid value: "NET_ADMIN": capability may not be added spec.initContainers[0].securityContext.runAsNonRoot: Invalid value: false: must be true spec.initContainers[0].securityContext.capabilities.add: Invalid value: "NET_ADMIN": capability may not be added spec.initContainers[0].securityContext.capabilities.add: Invalid value: "NET_RAW": capability may not be added]
Any help on this please

**Comment by cpretzer** [comment]
hi @saiharshitachava I see that you posted the same question in https://slack.linkerd.io and @alpeb has been answering your questions.

Can you provide more detail here including:
- how you installed Linkerd
- where your cluster is running: e.g. EKS, AKS, GKE, bare-metal, etc.
- the output from the `linkerd check` command

That will help us to get started :)

**Comment by grampelberg** [comment]
Closing this issue out as it is a question. Please re-open if you run into a bug!
