### ISSUE TITLE
Release Test Plan

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#4198]
## 20.4.1

- [x] scale testing
  - deploy emojivoto to 10 namespaces (with identity)
  - deploy books to 10 namespaces (with identity) / or find a way to get to 100+ services
  - scale each deployment to 10 replicas
  - increase total traffic to 1000 rps
- [x] ingress testing
  - inject nginx-ingress controller
  - send 100k bad domains at it
  - send 100 rps traffic back to emojivoto deployment
- [x] functionality testing
  - tracing
  - service profiles (timeouts, retries) for both HTTP and gRPC
  - edges
- [ ] cluster version
  - K8s 1.17
- [x] upgrade testing
  - Upgrade from 2.6 to 2.7.1
  - Upgrade from 2.7 to 2.7.1
  - Upgrade from Edge 20.3.4 to a 2.7.1 tag
  - Monitor error rates and verify that the upgrade notes do not introduce any downtime

## 20.3.4

- [x] scale testing
  - deploy emojivoto to 10 namespaces (with identity)
  - deploy books to 10 namespaces (with identity) / or find a way to get to 100+ services
  - scale each deployment to 10 replicas
  - increase total traffic to 1000 rps
- [x] ingress testing
  - inject nginx-ingress controller
  - send 100k bad domains at it
  - send 100 rps traffic back to emojivoto deployment
- [x] functionality testing
  - tracing
  - service profiles (timeouts, retries) for both HTTP and gRPC
  - edges
- [x] cluster version
  - K8s 1.17
- [x] upgrade testing
  - Upgrade from 2.6 to 2.7.1
  - Upgrade from 2.7 to 2.7.1
  - Monitor error rates and verify that the upgrade notes do not introduce any downtime

**Comment by admc** [comment]
scale: Zahari
ingress: Eliza
functionality: Alex
cluster version: charles
upgrade: kevin

**Comment by adleong** [comment]
I notice that upgrading from edge-20.3.4 is not listed above.  Is this upgrade path not supported?

**Comment by adleong** [comment]
Tracing, timeouts, retries, and edges are all working as expected, with the exception that certain retry metrics are missing, as described here: https://github.com/linkerd/linkerd2/issues/4215

**Comment by olix0r** [comment]
proxy v2.90.0 has been released with a fix

**Comment by kleimkuhler** [comment]
Using: `Client version: git-2b8f1b27`

Upgrading from 2.6 and 2.7 works as expected. There was no change in error rates for the installed demo app and there was no downtown introduced.

**Comment by alpeb** [comment]
Regarding testing under k8s 1.17, I think we'll have to include #4195 (relax clock skew check) to avoid the check failures, and also to be able to pass the integration tests.

**Comment by alpeb** [comment]
Only affecting integration testing, #4025 needs to be included, which took care of the changing structure of the Helm chart values.yaml file between stable versions.

**Comment by alpeb** [comment]
With the aforementioned cherry-picks, 2.7.1 is testing well under k8s 1.17 :+1: 
I'm seeing some errors in 1.18 for which I'll create separate issues.

**Comment by zaharidichev** [comment]
Spent some time scale testing today. Things appear to work normally. I wonder if there is anything in particular that I need to pay attention to @grampelberg ? 
<img width="1696" alt="Screenshot 2020-04-01 at 16 49 15" src="https://user-images.githubusercontent.com/4391506/78144987-02f83400-7439-11ea-9619-d734b9f8b3d5.png">

**Comment by alpeb** [comment]
FYI, the errors in 1.18 is just service profiles being rejected because of a dependency on an old apimachinery. This is not occurring in master.

**Comment by hawkw** [comment]
Proxy linkerd/linkerd2-proxy@2.91.0, the version in 20.4.1, has been run through the ingress tests prior to merging linkerd/linkerd2-proxy#469. Do we care about running the test again against the tagged edge-20.4.1, or is that sufficient?

**Comment by adleong** [comment]
Upgrading from 2.6.0, 2.7.0, and edge-20.4.1 to the latest candidate (git-ca760bdd) all worked fine.  Upgrading from the latest edge is actually a downgrade of controller version and leaves the SMI metrics APIServer and SMI metrics controller still running in the control plane namespace, but this shouldn't cause any harm as far as I can tell.

**Comment by adleong** [comment]
Tracing, timeouts, retries, and edges are all working as expected on git-ca760bdd

**Comment by hawkw** [comment]
> Proxy linkerd/linkerd2-proxy@2.91.0, the version in 20.4.1, has been run through the ingress tests prior to merging [linkerd/linkerd2-proxy#469](https://github.com/linkerd/linkerd2-proxy/pull/469). Do we care about running the test again against the tagged edge-20.4.1, or is that sufficient?

Per offline conversation with @olix0r et al., we've agreed that this is sufficient, so I'm willing to check off ingress.

**Comment by zaharidichev** [comment]
Scale testing is good.
