### ISSUE TITLE
Add fish shell completions

### ISSUE THREAD

**Issue by nesl247** [linkerd/linkerd2#4208]
## Feature Request
Add fish shell completions. Currently only bash/zsh are supported.

### What problem are you trying to solve?
Adding completions to the very popular fish shell

### How should the problem be solved?

Add support for `linkerd completion fish`.

**Comment by grampelberg** [comment]
Blocked on https://github.com/spf13/cobra/pull/754

**Comment by nesl247** [comment]
Or this one which seems like it has a better chance of being merged: https://github.com/spf13/cobra/pull/1048 instead

**Comment by nesl247** [comment]
The PR was merged. Any chance we could get cobra updated for the next release?

**Comment by grampelberg** [comment]
@nesl247 sure! Up for a PR? I suspect @adleong will particularly appreciate it =)

**Comment by nesl247** [comment]
I'll try to tackle it when I can. I tried to get it to work earlier, but the completions it generated weren't actually working. If someone wants to pick it up from where I left off (let me know and I can submit a PR or something), great, otherwise I'll get to it when I can.

**Comment by WLun001** [comment]
I can take this task
