### ISSUE TITLE
Document service discovery and load balancing

### ISSUE THREAD

**Issue by briansmith** [linkerd/linkerd2#421]
At https://conduit.io/docs we don't have any documentation for how service discovery and load balancing works. It is important that we document how these work, in particular:

* How the proxy uses the Destination service to provide L7 load balancing.
* The advantages of how Conduit does L7 load balancing vs. how Kubernetes does L4 load balancing by default.
* How Conduit integrates the Destination service with Kubernetes load balancing transparently so that things like "clusterFirst" networking and custom dnsConfigs work transparently.
* How Conduit allows node-local services like "metadata" on GKE to work.
* Details of Conduit's load balancing, "least loaded", etc.
* Future enhancement plans.
* Limitations of our design, especially ways that things aren't fully transparent.
* How to override Conduit's service discovery enhancements.

I'm assigning this to myself to knock out a first draft.

**Comment by c4milo** [comment]
Any updates or a non official doc that we can read in the mean time? Thanks!

**Comment by wmorgan** [comment]
Now in https://linkerd.io/2/features/load-balancing/
