### ISSUE TITLE
[Feature Request] The charts support Helm v3

### ISSUE THREAD

**Issue by Aisuko** [linkerd/linkerd2#4224]
### What problem are you trying to solve?

   * Hi, guys. Helm v3 was released to V3.1.0. Are there any ideas that Linkerd2 has a plan to support Helm v3? In fact, I'm going to develop the adapter for Linkerd2 and with `helm.sh/helm/v3`

### How should the problem be solved?

What do you want to happen? Add any considered drawbacks.

   * The charts can support Helm v3

### Any alternatives you've considered?

   *  I'm not sure, but maybe I would wait for the feature support Helm v3

Is there another way to solve this problem that isn't as good a solution?

### How would users interact with this feature?

  *  The feature for the user would be good because of Helm v3 has been removing the component named tiller, that can let Helm v3 follow more atom level of Kubernetes RBAC policy 

If you can, explain how users will be able to use this. Maybe some sample CLI
output?

**Comment by grampelberg** [comment]
@Aisuko the charts already work fine with Helm v3. Is there an issue you're running into?

**Comment by Aisuko** [comment]
Thanks for your quick reply. In my opinion, the Helm v3 requirements file was moved to the Chart.yaml. The Linkerd2 chart still using the requirement.txt as the dependency manifest. Oh, wait for a moment. Do you mean the user just download the chart and deploy it by using Helm v3 and there will not need to update requirements?  I saw the dependency chart was under the folder named charts?

**Comment by grampelberg** [comment]
@Aisuko you just add the repo and you're good to go. I'm going to close this issue out for now, please reopen if you run into a specific issue.

**Comment by Aisuko** [comment]
Oh, thanks a lot.
