### ISSUE TITLE
Visualize health of remote cluster gateways

### ISSUE THREAD

**Issue by zaharidichev** [linkerd/linkerd2#4237]
After we have metrics about remote gateways and their health in Prometheus, we would ideally like to visualise that somehow (as mentioned  [here](https://github.com/linkerd/linkerd2/issues/4063#issuecomment-587083112)). A cli command similar to `stat` seems like a logical choice. This command can display information such as,  number of routed service, latency data as well as health information for each gateway that our cluster sends traffic to.

**Comment by olix0r** [comment]
Do we want to introduce this as another subcommand (e.g. `linkerd remote-stat`)? Or should this be part of a family of subcommands (e.g., `linkerd remote stat`)? Or should this just be part of `linkerd stat svc/remote-svc-name` directly?

**Comment by zaharidichev** [comment]
@ver @grampelberg I spent a bit of time debating with myself whether that should go under the stat command. Ultimately decided to put it under linkerd cluster gateways (there are other cluster sub-commands). The main reason being that albeit the logic being very similar, after looking at the stat codebase, if feels like there are quite a lot of bells that you can tweak on it and the `StatSummayRequest/Response` handles quite a lot of resources, can defines a bunch of filtering logic, etc - something that I did see with the gateways stat command. So putting it there felt a bit like bolting it on (from implementation perspective). So I have a separate endpoint that I hit on the public-api to get the gateway stats. All that being said, it easy to move it all to the stat command if that makes more UX sense.

**Comment by zaharidichev** [comment]
Currently my WIP looks like: 

<img width="964" alt="Screenshot 2020-04-07 at 16 17 39" src="https://user-images.githubusercontent.com/4391506/78674734-be631180-78ec-11ea-96aa-0f84182a69e4.png">

**Comment by grampelberg** [comment]
I'm a fan of this being a whole tree of commands under `linkerd cluster`. We should get a list of the commands together that should go under that though!
