### ISSUE TITLE
Migrating from edge to stable 2.7.1 leaves smi-metrics

### ISSUE THREAD

**Issue by derrickburns** [linkerd/linkerd2#4242]
Removed the deployment is not enough.

One must also remove the apiservice:

```
 v1alpha1.metrics.smi-spec.io                   linkerd/linkerd-smi-metrics
```

**Comment by grampelberg** [comment]
@derrickburns that's not surprising as 2.7.1 doesn't contain any of the control plane changes. The upgrade from edge -> 2.8.0 will be much smoother.

**Comment by derrickburns** [comment]
It would be helpful to have a note on supported migration paths.

**Comment by grampelberg** [comment]
That's a great suggestion. We've been treating edge as unstable with no upgrade guarantees so far, it'll be nice to have some more guidance around that.

**Comment by grampelberg** [comment]
I'm going to close this out, we'll have a follow up issue to document what kind of upgrade paths are supported between edges and stables.
