### ISSUE TITLE
Migrating from edge to stable-2.7.1 required manual restart of linkerd services

### ISSUE THREAD

**Issue by derrickburns** [linkerd/linkerd2#4243]
I had to restart the linkerd services manually in a certain order after running the standard upgrade procedure.  They came up in a non-functional state.

**Comment by grampelberg** [comment]
@adleong @alpeb is this anything we should be concerned about with the upgrade to 2.8?

**Comment by adleong** [comment]
@derrickburns can you give more information about the errors or behavior you saw? I didn't encounter this when upgrading edge-20.4.1 to stable-2.7.1

**Comment by grampelberg** [comment]
I'm going to close this out, we'll have a follow up issue to document what kind of upgrade paths are supported between edges and stables.
