### ISSUE TITLE
Externalize multicluster gateway liveliness probe settings

### ISSUE THREAD

**Issue by zaharidichev** [linkerd/linkerd2#4248]
Rigfht now there are three parameters that need to be configured for the multicluster gateway prober: 

- probe path
- probe port
- probe period

We need to externalize these throgh the `get-credentials` command. Or at least put sensible defaults.  This will allow us to specify these per cluster.

**Comment by zaharidichev** [comment]
cc  @grampelberg @adleong

**Comment by adleong** [comment]
Just to make sure I understand correctly: these values are basically determined by the ingress, right?  i.e. nginx has a certain probe path, traefik might have a different one, etc etc.
By configuring these at the cluster level, we can't have more than one type of gateway per cluster.

My mental model so far has been that the only cluster-wide configuration is the credentials for connecting to the cluster's API and that each gateway was basically independent, allowing multiple different gateways to coexist.  I don't see a great reason why we would want to couple the choice of gateway to the cluster configuration, but I could be missing something.

**Comment by zaharidichev** [comment]
Yeah I understand what you are saying. We can avoid coupling here. One way to do that would be to assume some annotations for these values exist on the gateway. We try to parse them all and if they are all there and valid we use them. You think that would work better? I am not really sure I want to go down the road of tracking updates for this config values. For example if something changes, like the period, I really do not want to adjust the period of my checks. At least for now. WDYT ?

**Comment by grampelberg** [comment]
My preference is to have the liveness config stored locally on the cluster (not in a CRD). The easiest would be two key in the same CM, but it could be two separate CMs ... just more complexity at that point.
