### ISSUE TITLE
Introduce multicluster healthchecks

### ISSUE THREAD

**Issue by zaharidichev** [linkerd/linkerd2#4249]
We want to have a section in the checks command that will verify the following things.

- all remote gateways are reachable and healthy  - we can do that either by looking at prometheus data coming from the service mirror component  OR actually issue requests ourselves
- we have sufficient permissions to list,watch and get services on the remote clusters we have provisioned secrets for
- the service-mirroring component has the required RBAC so it can watch for secrets being added
- the service-mirroring controller is healthy (maybe checking whether it is alive and running)

**Comment by zaharidichev** [comment]
cc  @grampelberg @adleong

**Comment by adleong** [comment]
LGTM!
