### ISSUE TITLE
Idea: Provide a way to deploy the cluster gateway

### ISSUE THREAD

**Issue by zaharidichev** [linkerd/linkerd2#4250]
I envision that there might be quite a few people digging through PRs to look for a sensible gateway implementation. That being said, i wonder whether we can just package ours as a chart and provide command to install it, while underlining that this is not a gold standard implementation and that it has some security caveats?

**Comment by zaharidichev** [comment]
cc  @grampelberg @adleong

**Comment by adleong** [comment]
I really like the way we did this for the [distributed tracing guide](https://linkerd.io/2/tasks/distributed-tracing/) where we just hosted an example manifest on run.linkerd.io.

**Comment by grampelberg** [comment]
As we have addons, I don't see any reason why we can't just use those for this. We're already doing it for tracing after all =)

I suspect that we're going to want to take ownership of the gateway sooner rather than later anyways. Letting folks setup the gateway is awesome for external projects like gloo but I'm not sure it works out for end users in the long term.

**Comment by adleong** [comment]
That makes sense, but it's a shift from the philosophy we had in mind when this project started.  If we want to take ownership of the gateway (which I think is probably a good idea) we should revisit some of the earlier assumptions we made:

* Deploying the gateway and creating the remote credentials can probably be consolidated into one "remote cluster setup" step
* By guaranteeing that the gateway will have a Linkerd proxy injected, can we simplify routing?  For example, by using the l5d-dst-override header?  Do we still need the authority overriding piece that we built?
* By making the gateway part of cluster setup, we can assume there is just one gateway per cluster.  Does this change the way we record stats?  We can also use known probe paths rather than making them configurable (or at the least, set the correct defaults)

**Comment by grampelberg** [comment]
> Deploying the gateway and creating the remote credentials can probably be consolidated into one "remote cluster setup" step

Wouldn't this be two separate `kubectl` apply steps? One for the credentials on the local cluster and one for the gateway on the remote cluster?

> By guaranteeing that the gateway will have a Linkerd proxy injected, can we simplify routing? For example, by using the l5d-dst-override header? Do we still need the authority overriding piece that we built?

This sounds like an awesome set of questions for v2!

> By making the gateway part of cluster setup, we can assume there is just one gateway per cluster. Does this change the way we record stats? We can also use known probe paths rather than making them configurable (or at the least, set the correct defaults)

When we get to having policy for all this, we're going to have more than one gateway per cluster.

**Comment by adleong** [comment]
> Wouldn't this be two separate kubectl apply steps? One for the credentials on the local cluster and one for the gateway on the remote cluster?
One command to create the resources on the remote cluster (service account and gateway) and then another command to fetch the credentials and apply them to the local cluster.  I'm just suggesting bundling the gateway manifest with the remote cluster service account manifest.

> When we get to having policy for all this, we're going to have more than one gateway per cluster.

Ah, I don't think I'm up to speed on the vision here so it's hard for me to meaningfully comment.  Is this in the design doc or written up somewhere?

**Comment by grampelberg** [comment]
>  I'm just suggesting bundling the gateway manifest with the remote cluster service account manifest.

Ooooh, yup, that makes a ton of sense! We'd need to think through what it means for multiple clusters to be sharing the same gateway, but k8s *should* take care of that for us.

> Ah, I don't think I'm up to speed on the vision here so it's hard for me to meaningfully comment. Is this in the design doc or written up somewhere?

I know we've talked about it, @zaharidichev did that end up in one of the design docs?

**Comment by zaharidichev** [comment]
> By guaranteeing that the gateway will have a Linkerd proxy injected, can we simplify routing? For example, by using the l5d-dst-override header? Do we still need the authority overriding piece that we built?

We can make more bold assumptions. However I do not think we can greatly simplify routing.  Not sure we want to use the dst-override header for that particular functionality, but I am not really up to scrath on the semantical meaning of these headers. Nevertheless in the end of the day we will have to set some header somehwere in the proxy. Currently we set the authority which is quite generic. We would end up setting something else. This will not bring much simplification I think. 


> I'm just suggesting bundling the gateway manifest with the remote cluster service account manifest.

I think that makes sense and will result in simple UX. Not sure this strays too much from the intial goal of the project. People can still bring their gateways, and their credentials and set up everything manually. The way I think about it is that every command that is part of linkerd can be cupled with Linkerd specific functionality. The general concept of service mirroring works without any of that. Its just that people will have to go deploy creds themselves, setup gateways themseves, ensure routing is sound. And iff, they have all that in place, they can dump service mirroring component and enjoy. 

On the other hand... I am not sure we want to bundle it like that because it will force us into one gateway per cluster. I think we want to keep the option of having multiple ones. 

> I know we've talked about it, @zaharidichev did that end up in one of the design docs?

It has not really. TBH I have not spent a ton of time thinking about it as I assumed it is a later step.

**Comment by grampelberg** [comment]
> On the other hand... I am not sure we want to bundle it like that because it will force us into one gateway per cluster. I think we want to keep the option of having multiple ones.

I think my preference is to have the gateway be an addon that is installed as part of the control plane. This fits into when I'd think about it as a user (eg. I am setting this up to get multi-cluster traffic) and maintains the output from credential commands to just that. Thinking about it a little more, as a user I would be surprised that credentials create something on the cluster as well.

My suspicion is that we're going to actually want a gateway operator in the far future and for RBAC reasons that feels like it should be part of the control plane install flow.
