### ISSUE TITLE
ADOPTERS.md change doesn't trigger CI. Also improve workflow dependencies.

### ISSUE THREAD

**Issue by alpeb** [linkerd/linkerd2#4256]
## Main Problem

When a PR with changes to just `.md` files occurs no CI runs are triggered. This was made so because that happens when a change to `CHANGES.md` is merged which is immediately followed by a release tag which does trigger CI.

We didn't foresee though that when a change to for example solely `ADOPTERS.md` is merged then CI is not triggered and so the docker images for the latest master won't get pushed, which can confuse devs trying to deploy master in a cluster.

## Possible Solution

We could create a new CI workflow that gets triggered by changes to only `.md` files, which builds and pushes the docker images. This would require copying the `docker_build` and `docker_push` jobs that are already duplicated in `cloud_integration.yml` and `release.yml`.

A separate improvement could alleviate that duplication by having this new workflow be triggered upon all master pushes, and having this workflow dispatch an event that would in turn trigger `cloud_integration.yml` or `release.yml`, allowing removing these duped docker steps for there.

**Comment by kleimkuhler** [comment]
> having this workflow dispatch an event that would in turn trigger cloud_integration.yml or release.yml

I am +1 on reducing the duplication of jobs between workflows by using the repository dispatch events! The website update job uses this, and I don't see any reason why we wouldn't be able to use it to trigger workflows within the same job.
