### ISSUE TITLE
Traces should be able to leave the mesh

### ISSUE THREAD

**Issue by thedevelopnik** [linkerd/linkerd2#4275]
## Feature Request
I would like to be able to send distributed tracing traces/spans out of the mesh.

### What problem are you trying to solve?
We run Jaeger in our cluster but also use a vendor for all-in-one-place observability, including logs and metrics, and are in a trial for sending OpenTracing traces. Traces sent through LinkerD reach Jaeger correctly when it is in the mesh, but they cannot reach our vendor.

Our traces are sent from applications to one OpenTelemetry collector, which forwards the traces to both Jaeger, and another OpenTelemetry collector configured by a helm chart from the vendor, which forwards them to the vendor's system. I believe that because LinkerD has a requirement that all tracing systems be in the mesh for encryption purposes, we lose the trace at that point.

### How should the problem be solved?

I'm not familiar enough with what is happening behind the scenes I think to make a high-quality suggestion here, but am happy to be educated more. Maybe a flag to indicate a given pod should allow traces to leave without mesh encryption?

What do you want to happen? Add any considered drawbacks.

We are shipping traces to the vendor over an https connection, so they will be encrypted, but it's possible doing such a flag could leave unexperienced folks sending unenrypted traces out. I don't imagine that someone trying to send distributed traces out of a cluster are unexperienced though, on average.

### Any alternatives you've considered?

Is there another way to solve this problem that isn't as good a solution?

### How would users interact with this feature?

If you can, explain how users will be able to use this. Maybe some sample CLI
output?

**Comment by grampelberg** [comment]
I'm not sure I understand. You're running Jaeger *and* an OT collector in-mesh on the cluster and not getting all the traces?

**Comment by Pothulapati** [comment]
Hey

>I believe that because LinkerD has a requirement that all tracing systems be in the mesh for encryption purposes, we lose the trace at that point. 

Linkerd just requires the Collector to be part of the mesh, to send the traces from the proxies securely but once they reach the collector, The collector would be just sending traces out through some kind of RPC/requests which the collector's proxy doesn't consider as traces but as general requests that are going outbound, and they could obviously go outside the mesh i.e to a vendor, etc. This should not be a problem. 

Feel free to comment, if this isn't what you are looking for! :)

**Comment by thedevelopnik** [comment]
@grampelberg We are using an OT collector in-mesh and forwarding to both Jaeger AND another OT collector. Jaeger is one final destination, the other is an external http endpoint that the second OT collector forwards to.

@Pothulapati What we're seeing is that with our collector, Jaeger, and the vendor's collector in the mesh, Jaeger receives traces but the vendor does not. What you describe was also my expectation, that once traffic leaves the mesh to that endpoint it should be traffic like any other. I will double check with the vendor that they are not receiving the traces, or if the traces are somehow just not showing up in the GUI side of their system.

Thanks for the responses!

**Comment by grampelberg** [comment]
There's nothing special about collector -> collector communication as the requirement is around proxy -> collector (so that we can mTLS it). I'd turn up logging and verify that the first collector is correctly sending traces out.

**Comment by thedevelopnik** [comment]
Thanks for the clarification @grampelberg. We are seeing the traces reach the second OT collector, but then they don't show up on the vendor side which is why I suspected mesh-exit or encryption issues, but it sounds like it's something else.

**Comment by grampelberg** [comment]
I'll be closing this one out for now. Please jump into slack if you'd like any help! We'd be happy to debug what's going on with you =) Tracing is insanely difficult to setup with all the options out there, so there might be something simple in the collector config that is off.
