### ISSUE TITLE
Increase nf_conntrack_tcp_timeout_close_wait

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#4276]
## What problem are you trying to solve?

By default, `nf_conntrack_tcp_timeout_close_wait` is set to 60 seconds. Any requests taking longer than that get lost by the kernel causing 502 gateway errors to applications. `kube-proxy` bumped this up to 3600 seconds for its rules (see https://github.com/kubernetes/kubernetes/issues/32551).

### How should the problem be solved?

It is not possible to modify this via. the pod spec as it is marked "unsafe" in most k8s installations. However, as it is part of the network namespace, you can set it in init containers and have it persist for the life of the session. We should do this inside the `proxy-init` container and as part of setup for CNI.

**Comment by adleong** [comment]
In a quick spot check, I saw that this is already configured to 3600 on GKE and 60 on AKS.

**Comment by adleong** [comment]
It seems that in order to do this, we need to set `allowPrivilegeEscalation` and `privilaged` to true in the init container security policy.  I'm not really sure what the implications of that are.  Is this a tradeoff we're okay with?

**Comment by derrickburns** [comment]
I deployed this today into a test environment using an initContainer per the suggestion of @grampelberg.  I will have feedback in the next few days if this worked to address the issues that we are seeing.

**Comment by ericsuhong** [comment]
For us, we did not have to increase **nf_conntrack_tcp_timeout_close_wait** for all containers.

We only needed to increase **nf_conntrack_tcp_timeout_close_wait** value for Nginx ingress controller only to fix the issue, so maybe making this configurable as an annotation can limit the security concern.
