### ISSUE TITLE
FailedDiscoveryCheck behind proxy

### ISSUE THREAD

**Issue by retr0h** [linkerd/linkerd2#4296]
### What is the issue?

We run our cluster behind a proxy.  Therefore, the api server is running with HTTP/HTTPS proxy configuration.

When running `linkerd check` it fails wih the following error.  Oddly, it appears to be  using the tap's IP vs the DNS name, which would work because we have NO_PROXY configured for `.cluster.local`.

```
root@csg-nscg-0005:~# k get svc -n linkerd
NAME                     TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)             AGE
linkerd-tap              ClusterIP   10.233.31.133   <none>        8088/TCP,443/TCP    29m
```

```
FailedDiscoveryCheck: no response from https://10.233.31.133:443: Get https://10.233.31.133:443: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
see https://linkerd.io/checks/#l5d-tap-api for hints
```

### How can it be reproduced?

Have an API server running and configured with HTTP_PROXY/HTTPS_PROXY/NO_PROXY configured.

#### `linkerd check` output

```text
FailedDiscoveryCheck: no response from https://10.233.31.133:443: Get https://10.233.31.133:443: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
see https://linkerd.io/checks/#l5d-tap-api for hints
```

### Environment

- Kubernetes Version: 1.14.1
- Cluster Environment: kubespray
- Host OS: ubuntu 18.04
- Linkerd version: 2.7.1

**Comment by grampelberg** [comment]
@retr0h I assume that log line is from your api server? It sounds like you've got connectivity issues between the api server and the tap service. In GKE, this happens because of a firewall rule.

**Comment by retr0h** [comment]
@grampelberg like I stated, it works perfectly fine if we remove proxy settings from the api server.  The question I have is why an IP address is used vs the svc dns name.  I would expect linkerd to use the service dns name for the tap service not an IP address.

**Comment by grampelberg** [comment]
@retr0h here's the code that we're using for that check:

https://github.com/linkerd/linkerd2/blob/437f53cdcf6f75727c6064b116f1b971529d4849/pkg/healthcheck/healthcheck.go#L1865

This is coming directly back from the api server. It is configured with the service and the error message shows the IP address that the api server is using. It is coming from the api-server -> tap hop itself, so there's a connectivity problem there. I've not personally worked with proxy settings on the api server itself, any ideas what might be going wrong there? An easy test would be to ssh to your api server and see if you can successfully connect to the tap service.
