### ISSUE TITLE
LinkerD dashboard failure

### ISSUE THREAD

**Issue by stephaneey** [linkerd/linkerd2#4309]
### What is the issue?
Trying to drill down to a pod or deployment or anything leads to a Javascript issue in the browser (with both Chrome & IE).   
### How can it be reproduced?
Just start the dashboard and click on any pod/deployment
### Logs, error output, etc
Chrome's console output:
main.c1d727b8ee986d741d7e.js:22829 TypeError: Cannot read property 'api' of undefined
    at l.linkedResourceTitle (main.c1d727b8ee986d741d7e.js:23137)
    at l.value (main.c1d727b8ee986d741d7e.js:23137)
    at main.c1d727b8ee986d741d7e.js:23137
    at Array.map (<anonymous>)
    at l.value (main.c1d727b8ee986d741d7e.js:23137)
    at Li (main.c1d727b8ee986d741d7e.js:22829)
    at Fi (main.c1d727b8ee986d741d7e.js:22829)
    at vl (main.c1d727b8ee986d741d7e.js:22829)
    at sc (main.c1d727b8ee986d741d7e.js:22829)
    at lc (main.c1d727b8ee986d741d7e.js:22829)
Clicking on the error reveals:
Could not load content for webpack:///main.c1d727b8ee986d741d7e.js (HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME)
#### `linkerd check` output

```text
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-identity
----------------
√ certificate config is valid
√ trust anchors are using supported crypto algorithm
√ trust anchors are within their validity period
√ trust anchors are valid for at least 60 days
√ issuer cert is using supported crypto algorithm
√ issuer cert is within its validity period
√ issuer cert is valid for at least 60 days
√ issuer cert is issued by the trust anchor

linkerd-api
-----------
√ control plane pods are ready
√ control plane self-check
√ [kubernetes] control plane can talk to Kubernetes
√ [prometheus] control plane can talk to Prometheus
√ tap api service is running

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ control plane is up-to-date
√ control plane and cli versions match

Status check results are √
```

### Environment

- Kubernetes Version:
- Cluster Environment: (GKE, AKS, kops, ...)
- Host OS:
- Linkerd version:

**Comment by grampelberg** [comment]
I assume you're on the latest edge? If so, see #4303. If you're on a different version, please reopen with some more details about your env and what's going on =)

**Comment by stephaneey** [comment]
Hello,

Sorry for my late answer and thanks for your fast answer :). Indeed, I'm on the edge one.

Thanks
