### ISSUE TITLE
Network Diagnostics

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#4327]
### What problem are you trying to solve?

It can be challenging to diagnose why things aren't working in a remote cluster. Is there a connectivity issue? What happens when a specific request is sent to a service? How do I work with the data that comes back? Linkerd should make this kind of interaction with a cluster's traffic easy and seamless. 

### How should the problem be solved?

Introduce a new command to the CLI: `exec`. This will wire up the networking locally for a user where local binaries (such as `curl` or `ping`) can interact with a Kubernetes cluster natively. It will use local binaries and produce local output to allow users to use their local tools and files to diagnose what's going on with their cluster.

**Comment by zaharidichev** [comment]
I like that a lot! I think it will be super useful. Will that be achieved through some kind of firewall rules? What is the canonical way of achieving that (if there is one)?

**Comment by grampelberg** [comment]
@zaharidichev we'll have to do some extra thought on the requirements first I think. In particular, I'm wondering what we'll have to do to make this work cross platform. There are some easy things to do on the linux/bsd side but I have *zero* clue what is required from a windows perspective.

As potential prior art, [telepresence](https://www.telepresence.io/) does this in a generic way. I'm hoping we can get something laser targeted at Linkerd that is simpler to implement.

**Comment by olix0r** [comment]
FWIW, I'm less convinced that we should try to support arbitrary networking features. Specifically, `ping` (which is at the ICMP level) seems very much out of scope. I think this should be at least TCP-specific, but I think even this isn't a hard requirement. The main goal should be to test the proxy's connectivity to another endpoint.

The requirement about running tools locally also seems like an unnecessary constraint from my POV...

**Comment by grampelberg** [comment]
@olix0r I think you're right, ICMP doesn't even work in most k8s clusters. The functionality is valid though.

> The requirement about running tools locally also seems like an unnecessary constraint from my POV...

Yeah, I just don't know how to make it work with arbitrary local inputs/outputs otherwise. Definitely could think about things some more there.

**Comment by tharun208** [comment]
@grampelberg I like to work on this

**Comment by ihcsim** [comment]
@tharun208 Thanks for your interest. It looks to me that there are still some pending questions on what this is going to look like. Do you have thoughts on how we should approach this? Open to suggestions.

**Comment by tharun208** [comment]
@ihcsim,  One simple approach I thought of is by using go's `DialTimeout` with our specified cluster's IP.

**Comment by grampelberg** [comment]
@tharun208 next step would be getting an RFC written up. I'd recommend jumping into #contributors and reaching out to @ihcsim on slack before opening a PR on that repo so that we can brainstorm with you on how it'll all come together. This'll be a pretty extensive project =)
