### ISSUE TITLE
--skip-inbound-ports and mTLS

### ISSUE THREAD

**Issue by stephaneey** [linkerd/linkerd2#4332]
Hello,

The documentation available here https://linkerd.io/2/reference/cli/inject/ describes --skip-inbound-ports the following way:

_Ports and/or port ranges (inclusive) that should skip the proxy and send directly to the application_

However, having the following setup:

API Gateway (outside K8s) ==> Nginx ingress ==> backend service, I notice that when tapping the traffic, the first call: API gateway ==> NGINX ==> backend is reported as tls=not_provided_by_remote

When injecting NGINX, I used --skip-inbound-ports 443 because I also use whitelist-source-range but with that config, tap reports that everything is tls=true. What's the difference between injecting NGINX with skip-inbound-ports 443 and not injecting NGINX at all. I understood that with this config, my API call should have been ignored by the LinkerD proxy but it still has an impact on mTLS.

Thanks
Best Regards

**Comment by grampelberg** [comment]
You would not see the traffic at all with `tap` if you had skipped the outbound port. Have you followed the instructions for [nginx](https://linkerd.io/2/tasks/using-ingress/#nginx)? Please jump into [slack](https://slack.linkerd.io/) if you have any other questions! I'll be closing this out for now. Open it back up if you run into a specific bug =)

**Comment by stephaneey** [comment]
Hello @grampelberg,

Thanks for your answer. I'll go to Slack. Just one precision: as stated in the question, it's not oubtound but inbound ports. It is supposed to skip the proxy, then I don't see why mTLS would take place if the proxy is skipped but it is. Tried not to inject NGINX and then tap reports tls=false...

Thanks

**Comment by grampelberg** [comment]
> What's the difference between injecting NGINX with skip-inbound-ports 443 and not injecting NGINX at all.

With `skip-inbound-ports=443`, requests *to* nginx will skip the proxy. As 443 is encrypted via. HTTPS, the proxy would only provide you TCP statistics as there's no way for the proxy to decrypt that stream and it gets forwarded transparently. Requests *from* nginx go through the proxy in cleartext and therefore get mTLS'd by linkerd and well as having full metrics.

Not injecting nginx at all means that nothing happens. You don't get any metrics or mTLS provided by linkerd.

**Comment by stephaneey** [comment]
Hello @grampelberg,

Ok thanks, I thought skipping the proxy would prevent mTLS upgrade. Perfect, thanks for your answser.

Best Regards
