### ISSUE TITLE
Race condition in endpoint watcher tests

### ISSUE THREAD

**Issue by adleong** [linkerd/linkerd2#4336]
The endpoint watcher tests use an in-memory bufferingEndpointListener to hold endpoint updates and compares these to expected values.  However, since these updates are written from the client-go informer thread and read from the main test thread, a data race can sometimes occur, resulting in a flaky test.  

bufferingEndpointListener should be made thread-safe to protect against these data races.

**Comment by zaharidichev** [comment]
Hmm yes that makes sense. Will take care of it
