### ISSUE TITLE
Proxy spans without root trace spans

### ISSUE THREAD

**Issue by Pothulapati** [linkerd/linkerd2#4345]
### What is the issue?

![image](https://user-images.githubusercontent.com/7892868/81255008-320e5080-904a-11ea-9f85-e777bb4e6772.png)

There have been instances where proxy spans are received without root spans, The image is from `--control-plane-tracing`. It's important to check if this is a problem from the proxy or its just the application that sends the root spans acting weird!

### How can it be reproduced?
- Let `config.yaml` be 
```
tracing:
  enabled: true
```
- Install Linkerd by running
`linkerd install --control-plane-tracing --addon-config config.yaml | k apply -f -`

### Logs, error output, etc

(If the output is long, please create a [gist](https://gist.github.com/) and
paste the link here.)

#### `linkerd check` output

```text
your output here ...
```

### Environment

- Kubernetes Version:
- Cluster Environment: (GKE, AKS, kops, ...)
- Host OS:
- Linkerd version:

**Comment by cpretzer** [comment]
I reproduced this and traces without the root span are coming from the `linkerd-collector` for requests to `opencensus.proto.agent.metrics.v1.MetricsService/Export`

In this case, I'm not sure what should be creating the root span ID. If I understand correctly, the linkerd proxy doesn't create root spans, so I think that the collector should be.

WDYT?

**Comment by Pothulapati** [comment]
Okay, So I did some testing today. 
With `--control-plane-tracing`, I see that these `spans without root traces spans` come from most control plane component's proxies for `http.path:"/opencensus.proto.agent.trace.v1.TraceService/Export"` during initialization. My hypothesis is that these are the spans of the proxies init keep alive RPC [as per the opencensus proto definations in the proxy code](https://github.com/linkerd/linkerd2-proxy/blob/master/opencensus-proto/opencensus/proto/agent/trace/v1/trace_service.proto#L39) with the collector.


We could also see the init RPC calls of the golang client that we used in the control-plane components here.
![image](https://user-images.githubusercontent.com/7892868/82330590-a9f05980-9a00-11ea-9fce-87d272ddba01.png)

I also tried the same with the emojivoto demo, As these connections are mentioned as long lived, i went ahead and restarted `linkerd-collector`, making all the clients re-create those connections as seen below
![image](https://user-images.githubusercontent.com/7892868/82333279-22a4e500-9a04-11ea-80f4-86f94b67c164.png)

This makes sense as all the open-census clients do a init with a long lived RPC, and the proxies init calls are marked as "spans without root trace spans", as there is no application level span for it?

**Comment by grampelberg** [comment]
Shouldn't open-census clients be opening a trace for that?

**Comment by cpretzer** [comment]
@Pothulapati In my tests, I'm seeing requests for `/opencensus.proto.agent.metrics.v1.MetricsService/Export` which have no root spans. This appears to only occur when the components start up. In the screenshot below, the trace is between the `linkerd-controller` and `linkerd-collector`. I see similar traces with no roots for all the components.

![Screen Shot 2020-07-14 at 21 48 23 ](https://user-images.githubusercontent.com/3037127/87504635-ea90db80-c61b-11ea-89b7-693c5a48b064.png)

From what I can tell, this call to `/opencensus.proto.agent.metrics.v1.MetricsService/Export` is being made from the `ocagent` through the protobuf that is generated [here](https://github.com/census-instrumentation/opencensus-proto/blob/master/src/opencensus/proto/agent/metrics/v1/metrics_service.proto#L37).

So, do you know of a way to suppress or disable those traces? If not, do you think it's safe to ignore them?

If there's no work to be done on this issue, I'd like to close it out.

**Comment by olix0r** [comment]
We now understand that these traces are emitted as part of the control plane initialization, there doesn't seem to be any easy/obvious way to prevent these spans from being emitted, and they are otherwise harmless.
