### ISSUE TITLE
Include io error message on http metrics

### ISSUE THREAD

**Issue by adleong** [linkerd/linkerd2#4364]
When an HTTP request fails due to an io error, the "error" label on the http response metric is "unclassified".  This can make it very difficult to determine the cause of requests which fail due to io errors such as the remote closing the connection.

We should propagate the io error message onto the HTTP metrics to make these errors easier to identify and debug.

**Comment by olix0r** [comment]
@adleong Is it sufficient to simply be able to indicate that IO errors occurred? Do the various specific error messages indicate anything?

**Comment by olix0r** [comment]
https://github.com/linkerd/linkerd2-proxy/pull/512 is a very simple change to add an `i/o` label to help us spot these issues. My hunch is that this is sufficient for the types of spot checking we need to do. (Actual error codes will continue to be logged).
