### ISSUE TITLE
proxy: retry http requests on socket-level failures

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#4366]
In the face of connection timeouts, process restarts, etc, TCP level socket errors can be difficult to detect before issuing a request, though these errors frequently are discovered as soon as data is written to the socket.

In these cases, we fail these requests with a 502, because it appears as if the server dropped the connection after the request was sent. I think we can paper over these types of issues:

1. We add a retry layer that clones request metadata (including headers) but not the body and sends the request. If sending the request fails, we retry. If the body we send to the client gets polled, it steals the body and we can't retry it (if it's non-empty or non-idempotent).
2. Each endpoint stack, on both the inbound and outbound proxies, get a circuit-breaking layer that delays readiness (exp backoff) of the endpoint's service in the face of consecutive errors. This probably works similarly to [`Reconnect`](https://github.com/linkerd/linkerd2-proxy/blob/4673e699d901b5e2d81d543b984d7db5db0a9e68/linkerd/reconnect/src/service.rs) but interacts with the response future instead of only service's initial readiness. The point of this being that, if a service is actually configures such that it fails when we send it requests, we don't want to continue retrying forever, so we need something that idles the endpoint so requests to it fail as they should in this case.

There's potentially some cost to doing this, and it seems unnecessary for protocols like HTTP/2 that have active PINGs, but it does seem like a good default for HTTP/1, at least.

This would address issues like #3836

**Comment by mavrick** [comment]
is this in relation to 502 errors like this? `WARN inbound:accept{peer.addr=10.36.4.15:54324}:source{target.addr=10.36.4.26:3000}: linkerd2_app_core::errors: Failed to proxy request: connection error: Connection reset by peer (os error 104)` ? 

```json
{
    "textPayload": "[152362.795965300s]  WARN inbound:accept{peer.addr=10.36.0.16:53746}:source{target.addr=10.36.1.31:3000}: linkerd2_app_core::errors: Failed to proxy request: connection error: Connection reset by peer (os error 104)\n",
    "insertId": "k7nb0ew3cm4sz6p49",
    "resource": {
      "type": "k8s_container",
      "labels": {
        "pod_name": "mp-gallery-website-prod-6987976445-jxp8v",
        "namespace_name": "default",
        "project_id": "textures-1204",
        "container_name": "linkerd-proxy",
        "location": "us-central1",
        "cluster_name": "virgo"
      }
    },
    "timestamp": "2020-06-07T22:06:03.653130698Z",
    "severity": "INFO",
    "labels": {
      "k8s-pod/pod-template-hash": "6987976445",
      "k8s-pod/linkerd_io/proxy-deployment": "mp-gallery-website-prod",
      "k8s-pod/app": "mp-gallery-website-prod",
      "k8s-pod/linkerd_io/control-plane-ns": "linkerd"
    },
    "logName": "projects/textures-1204/logs/stdout",
    "receiveTimestamp": "2020-06-07T22:06:09.767215410Z"
  }
```

**Comment by olix0r** [comment]
@mavrick Probably. When we've seen this before, we've noticed that the server was accidentally configured with idle timeouts, as in https://github.com/linkerd/linkerd2/pull/4350. Changing/removing idle timeouts might be an easy workaround if you are encountering these issues.
