### ISSUE TITLE
2.8 - regression test plan

### ISSUE THREAD

**Issue by admc** [linkerd/linkerd2#4382]
- [x] scale testing
  - deploy emojivoto to 10 namespaces (with identity)
  - deploy books to 10 namespaces (with identity) / or find a way to get to 100+ services
  - scale each deployment to 10 replicas
  - increase total traffic to 1000 rps
- [x] ingress testing
  - inject nginx-ingress controller
  - send 100k bad domains at it
  - send 100 rps traffic back to emojivoto deployment
- [x] functionality testing
  - tracing
  - service profiles (timeouts, retries) for both HTTP and gRPC
  - edges
- [x] cluster version
  - K8s 1.18
- [ ] upgrade testing
  - Upgrade from 2.7 to 2.8
  - Upgrade from 2.7.1 to 2.8
  - Upgrade from Edge 20.5.x to a 2.8.0 tag
  - Monitor error rates and verify that the upgrade notes do not introduce any downtime

**Comment by alpeb** [comment]
Ks 1.18 is passing the integration tests as per #4445, except for the tracing one, but that's caused by the quay.io downtime.

**Comment by zaharidichev** [comment]
Taking the scale testing
