### ISSUE TITLE
Linkerd Add-Ons Test Plan

### ISSUE THREAD

**Issue by Pothulapati** [linkerd/linkerd2#4386]
All the below tests should work both through CLI and Helm

**Specific to Grafana Add-On:**

- [x] Linkerd with Additional Grafana Config
  - Install Linkerd with [additional grafana config](https://github.com/linkerd/linkerd2/tree/master/charts/linkerd2#grafana-add-on)
  - Linkerd Check. (Add-ons tests should be visible)
  - Install emojivoto/books app and test for usual metrics through dashboard and CLI.
  - Perform upgrades with configuration changes of tracing, etc add-ons. (`linkerd-config-addons` cm can be checked to see if the cm is correct consistently.)
  - Upgrade to `--ha`
- [x] Bring your own Grafana
  - Install Linkerd with the below config, pointing to a grafana instance already created from `gcr.io/linkerd-io/grafana`
  - Check if the grafana UI is correctly linkedf from the dashboard, and opens the relevant UI
  - Linkerd Check. ( Grafana add-on tests should not be visible)
  - Install emojivoto/books app and test for usual metrics through dashboard and CLI.
  - Perform upgrades with configuration changes of other add-ons. (`linkerd-config-addons` cm can be checked to see if the cm is correct consistently.)

**Specific to Tracing Add-On:**

- [x] Linkerd with Tracing add-on
  - Install Linkerd with tracing enabled & [additional tracing config](https://github.com/linkerd/linkerd2/tree/master/charts/linkerd2#tracing-add-on)
  - Linkerd Check. (Add-ons tests should be visible)
  - Install emojivoto and enable traces as per https://github.com/linkerd/website/pull/725
  - Check if the dashboard integration works correctly i.e to jump to relevant traces from the web dashboard.
  - Perform upgrades with config changes!

**General Linkerd  Add-On tests:**

- [ ] Normal Linkerd install with multiple add-ons configuration
  - Install Linkerd normally
  - Now upgrade Linkerd with [additional configuration](https://github.com/linkerd/linkerd2/tree/master/charts/linkerd2#add-ons-configuration) (grafana is already enabled, tracing can be enabled.)
  - Linkerd Check. (Add-ons tests should be visible)
  - Perform upgrades with configuration changes of multiple add-ons. (`linkerd-config-addons` cm can be checked to see if the cm is correct consistently.) and even `--ha`
  - Use `-addon-overwrite` to skip `linkerd-config-addons` entirely and use default or `--addon-config` if passed as per https://github.com/linkerd/linkerd2/pull/4377

**Comment by Pothulapati** [comment]
Tagging https://github.com/linkerd/linkerd2/issues/4375, being parent issue!

**Comment by grampelberg** [comment]
@Pothulapati is there anything more we should test around upgrades?

**Comment by Pothulapati** [comment]
Just updated the issue to remove Prometheus tests (as we are not getting it in for 2.8). So, The current work would be to check for grafana and tracing add-ons. 

@grampelberg I can't think of anything specific with regards to upgrades, but I added some stuff around in multiple places as upgrades can be done at any place. It's important to see that the configuration is persisted and used.

@alpeb Do you have any more tests in mind?

**Comment by grampelberg** [comment]
@Pothulapati we should test upgrading from an old version to a new one with addons enabled and between the same version, changing the addons enabled.

**Comment by alpeb** [comment]
I have tested both "Linkerd with Additional Grafana Config"  and "Bring your own Grafana" scenarios successfully.

**Comment by kleimkuhler** [comment]
I was reopening this for completing Prometheus add-on tests, but I will re-close this and create a new issue
