### ISSUE TITLE
service-mirror fails when remote gateway is on a private IP

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#4411]
When service-mirror is configured with a remote gateway on a private (10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16) network, the service-mirror's proxy attempts discovery and the destination service  responds with no identity; and the outbound requests fail because of the `l5d-require-id` header, which requires that the identity is configured (and it is not).

To fix this, I propose the following:
- We create a service for each gateway, e.g. `gateway-multi1`, `gateway-multi2`. This service has two ports (i propose gateway:4180 and healthcheck:4181) and one endpoint for each remote gateway replica.
- The service-mirror calls gateways by their name and not IP.
- The service-mirror manages endpoint readiness according to probes.
- The destination service is able to discover gateway identities (via annotation)?.

wdyt @zaharidichev @grampelberg

**Comment by olix0r** [comment]
Alternatively, we could make the cluster domains configurable (and perhaps restrict the default to only 10/8 -- i took a stab at this in https://github.com/linkerd/linkerd2/pull/new/ver/helm-config-net but there's template hell fallout)

**Comment by grampelberg** [comment]
@olix0r we should probably make that configurable, but it seems like that's a super tough thing to explain to a user. Would it be possible to do something in destination instead?

**Comment by olix0r** [comment]
@grampelberg What about the initial proposal?

**Comment by olix0r** [comment]
@grampelberg 

> we should probably make that configurable, but it seems like that's a super tough thing to explain to a user.

Is it? Cluster operators have to know about pod networks. This is just asking to document the the pod network. It's the same as the cluster domain, basically. 99% of installs can use the defaults, but we need to be able to support customized environments.

> Would it be possible to do something in destination instead?

Anything that the destination service could do would have to be configured or discovered. This just moves the problem.

Note, though, that we don't need to change the default network discovery if we use gateway services, which feels like the most "correct" approach. There's an unwritten rule here: All traffic should target a service unless it is actually pinned to a specific pod (like prometheus/tap).

**Comment by grampelberg** [comment]
> Is it? Cluster operators have to know about pod networks. This is just asking to document the pod network. It's the same as the cluster domain, basically. 99% of installs can use the defaults, but we need to be able to support customized environments.

Only really in context of multicluster. I was just thinking of the failure case that you'd been experiencing.

> Note, though, that we don't need to change the default network discovery if we use gateway services, which feels like the most "correct" approach.

Not sure I understand?

**Comment by olix0r** [comment]
I realized i miswrote the issue at first referring to private api service IP.. the issue is private gateway IP
