### ISSUE TITLE
Adding support for Docker Private Virtual Registries like Jfrog Artifactory for Airgap systems.

### ISSUE THREAD

**Issue by c-n-c** [linkerd/linkerd2#4413]
### What problem are you trying to solve?
Jfrog Artifactory or other private artifact registries for docker container are common in airgap systems, where the Linkerd chart referencing docker images, cannot be downloaded from the default upstream urls ( example: gcr.io/linkerd-io/proxy ).

Also these private registries are configured with authentication, for which the current implementation has no support.

### How should the problem be solved?
By adding `imagePullSecrets: <registry-secret>` parameter in the values.yaml (which is not implemented and therefore needs code change, the airgap systems can smoothly install the chart. 

The implementation should assume the registry secret is already available with the namespace.

User has to configure the value for `imagePullSecrets` in Linkerd Chart's values.yaml, and change the image reference of docker images in the values.yaml to point to their Jfrog Registry so that the charts can directly be deployed. 

### Any alternatives you've considered?
The other way to support such airgap system is to download the chart in zip format, use helm package command to package it after code changes as shared above, and deploy it in Jfrog Artifactory as part of local chart repository. This is a tedious process.

### How would users interact with this feature?
User will supply the `ImagePullSecrets` parameter to configure their artifactory registry, along with changing the reference of docker images in the values.yaml

https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#add-imagepullsecrets-to-a-service-account

**Comment by alpeb** [comment]
Keeping this one open in light of #4882

**Comment by c-n-c** [comment]
@apleb planning to do this today
