### ISSUE TITLE
ci: Test windows cli

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#4431]
A user in slack reported that there was an issue with the latest `linkerd` binary on Windows. AFAIK, we don't have any automated tests for this platform to, for instance, detect filesystem path problems. How hard is it to test the CLI from Windows.

**Comment by alpeb** [comment]
Correct, that isn't currently tested. Github actions supports running jobs in Windows VMs. We could extract the part of the install integration tests that use the command but don't use a cluster in order to sanity-check the CLI.

**Comment by grampelberg** [comment]
I'm kinda doing this over on [the website](https://github.com/linkerd/website/blob/master/.github/workflows/install.yml#L39) right now.
