### ISSUE TITLE
DNS and infinite loop

### ISSUE THREAD

**Issue by ThomWright** [linkerd/linkerd2#4450]
### What is the issue?

We've seen a few symptoms:

- linkerd-proxy will get stuck spinning at 1CPU (its CPU limit)
- context switches on the node will jump from 5k per second to 58k per second
- apparent increased DNS requests
- increased DNS timeouts (but probably a secondary symptom from the other problems)

This is happening in pods which download images from (I guess many different) external URLs/domains.

![image](https://user-images.githubusercontent.com/1884486/82444810-b1187580-9a9b-11ea-9ad3-9ac8dff70c5d.png)

^ What happened after deleting a bunch of linkerd-proxys with the above issue - DNS requests seem to go down.

### How can it be reproduced?

I still haven't figured out a trigger, but I would guess it's something going wrong with DNS resolution.

### Logs, error output, etc

```text
linkerd2_proxy_http::canonicalize failed to refine cottageinthemeadow.plantfans.com: deadline has elapsed; using original name
INFO [ 97821.827536s] linkerd2_proxy_http::upgrade tcp duplex error: Transport endpoint is not connected (os error 107)
```

^ These might be secondary symptoms, but I figured I'd include them anyway.

#### `linkerd check` output

```text
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-identity
----------------
√ certificate config is valid
√ trust roots are using supported crypto algorithm
√ trust roots are within their validity period
√ trust roots are valid for at least 60 days
√ issuer cert is using supported crypto algorithm
√ issuer cert is within its validity period
√ issuer cert is valid for at least 60 days
√ issuer cert is issued by the trust root

linkerd-api
-----------
√ control plane pods are ready
√ control plane self-check
√ [kubernetes] control plane can talk to Kubernetes
√ [prometheus] control plane can talk to Prometheus
√ tap api service is running

linkerd-version
---------------
√ can determine the latest version
‼ cli is up-to-date
    is running version 2.7.0 but the latest stable version is 2.7.1
    see https://linkerd.io/checks/#l5d-version-cli for hints

control-plane-version
---------------------
‼ control plane is up-to-date
    is running version 2.6.1 but the latest stable version is 2.7.1
    see https://linkerd.io/checks/#l5d-version-control for hints
‼ control plane and cli versions match
    control plane running stable-2.6.1 but cli running stable-2.7.0
    see https://linkerd.io/checks/#l5d-version-control for hints

linkerd-ha-checks
-----------------
√ pod injection disabled on kube-system

Status check results are √
```

### Environment

- Kubernetes Version: 1.15.11-gke.3
- Cluster Environment: GKE
- Host OS: Container-Optimized OS from Google
- Linkerd version: 2.6.1

**Comment by grampelberg** [comment]
This is great, thank you for digging in a little bit. Now we'll need to see if we can get it replicated on our side.

**Comment by olix0r** [comment]
@ThomWright I notice that you're running Linkerd 2.6.1. There have been a number of important fixes since then. `stable-2.7.1`is the most recent stable version, and the recent edge-channel releases are release candidates for `stable-2.8.0`.

Can you try upgrading the proxy to the most recent edge on this workload with an annotation like: `config.linkerd.io/proxy-version: edge-20.5.3`? This should be safe to use with the 2.6.1 control plane, and will eliminate a number of known & fixed issues from the set of potential causes.

**Comment by ThomWright** [comment]
Sure thing, we'll see if we can do that later today.

On Slack you also suggested adding the annotation: `config.linkerd.io/proxy-log-level: trust_dns=debug,linkerd=debug,warn` which we could look into (just leaving that here to make it easy for me to refer back to if necessary).

**Comment by grampelberg** [comment]
@ThomWright any progress?

**Comment by ThomWright** [comment]
Since upgrading to 2.7.1, we haven't seen these symptoms again. I'm happy to close this.
