### ISSUE TITLE
cli: Skip mirrored services with export-service

### ISSUE THREAD

**Issue by Pothulapati** [linkerd/linkerd2#4458]
### What is the issue?

`linkerd  cluster export-service` adds export annotations even with mirrored services. 

Example: 
when I run the export command on `west` , which has mirrored svcs from east as backend-one-east . Looks like the export service is applying the mirror annotations even on mirrored services causing `east` to get `backend-one-east-west`

### How can it be reproduced?

Sequence of commands here:
https://gist.githubusercontent.com/Pothulapati/d4cd19b881b8f187be36ba93b180a1be/raw/a24a3a0283b299b1e10d7a410a7c37a84813cb4a/multi.bash

### Logs, error output, etc

(If the output is long, please create a [gist](https://gist.github.com/) and
paste the link here.)

#### `linkerd check` output

```text
your output here ...
```

### Environment

- Kubernetes Version:
- Cluster Environment: (GKE, AKS, kops, ...)
- Host OS:
- Linkerd version:

### Possible solution

By default, skip adding export annotations to mirrored services, but provide a `--force` flag where users would want to do that!

**Comment by psinghal20** [comment]
Hi @Pothulapati, I took a look at this issue. Do you think a check for label `svcmirror.io/mirrored-service` while adding the export annotations? I came to know about this label from this doc: [Service Mirroring Reference Architecture
](https://docs.google.com/document/d/1fWPugswLsFxE89no9EX7-i2x8nJDs20DSuXdoAkN3ps/edit?ts=5e2893db#)

**Comment by Pothulapati** [comment]
Hey @psinghal20, That approach seems right, and thanks for your interest but I think there's already PR raised for the same i.e #4460.
