### ISSUE TITLE
Linkerd2 tap pod CrashLoopBackOff

### ISSUE THREAD

**Issue by Aisuko** [linkerd/linkerd2#4467]
### What is the issue?

```
time="2020-05-22T11:57:44Z" level=info msg="running version stable-2.7.1"
time="2020-05-22T11:57:44Z" level=info msg="Using trust domain: cluster.local"
time="2020-05-22T11:57:44Z" level=fatal msg="failed to load [extension-apiserver-authentication] config: configmaps \"extension-apiserver-authentication\" is forbidden: User \"system:serviceaccount:default:linkerd-tap\" cannot get resource \"configmaps\" in API group \"\" in the namespace \"kube-system\""
```

### How can it be reproduced?

We use `golang` to execute Linkerd command and deploy Linkerd to the cluster

### Logs, error output, etc

(If the output is long, please create a [gist](https://gist.github.com/) and
paste the link here.)

#### `linkerd check` output

```text
version stable-2.7.1
```

### Environment

- Kubernetes Version:
- Cluster Environment: (GKE, AKS, kops, ...)
- Host OS:
- Linkerd version: stable-2.7.1

**Comment by grampelberg** [comment]
Does `extension-apiserver-authentication` exist in your cluster? Take a look at https://discourse.linkerd.io/t/error-no-client-ca-cert-available-for-apiextension-server/947/4 for solutions.
