### ISSUE TITLE
Stop multicluster loops

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#4473]
### What problem are you trying to solve?

It is possible for a user to configure multicluster in a way that the requests loop between two clusters endlessly. While it might be idea to chain clusters (a->b->c), it is not ideal to have (a->b->a) for an identical request.

### How should the problem be solved?

While there are better options, this is a pretty simple update to `nginx.conf` used by the gateway:

```
    events {
    }
    http {
        server {
          listen     {{.Values.incomingPort}};
          proxy_pass http://127.0.0.1:{{.Values.proxyOutboundPort}};
          
          if ($http_l5d_cluster = {{.Values.clusterID}}) {
            return 405;
        }

        add_header l5d-cluster "{{.Values.clusterID}}"
    }
    http {
      server {
          listen     {{.Values.probePort}};
          location {{.Values.probePath}} {
            access_log off;
            return 200 "healthy\n";
          }
      }
      server {
          listen     {{.Values.localProbePort}};
          location {{.Values.localProbePath}} {
            access_log off;
            return 200 "healthy\n";
          }
      }    
    }
```

Note: this is untested and likely to need a little extra love.
Note: cluster ID is the UUID from linkerd-config.

**Comment by grampelberg** [comment]
@zaharidichev do you remember why we did stream instead of http?

**Comment by olix0r** [comment]
https://github.com/linkerd/linkerd2-proxy/pull/545
