### ISSUE TITLE
multicluster: get-credentials doesn't need --remote-cluster-domain

### ISSUE THREAD

**Issue by alpeb** [linkerd/linkerd2#4474]
One must currently provide `--remote-cluster-domain` to `linkerd cluster get-credentials` if different than the default `cluster.local`. But that code is already retrieving the `linkerd-config` configmap which holds the cluster domain set during install. So it can use that and not provide this flag.

**Comment by grampelberg** [comment]
@alpeb we'll still need that as a value in the helm chart though, right?

**Comment by alpeb** [comment]
Ah wait... `--remote-cluster-domain` is actually used in the gateway identity suffix. Like what's passed in `linkerd install --identity-trust-domain`, which is not necessarily the same as what's used in `linkerd install --cluster-domain`.
So what needs to be done here is renaming the flag in `linkerd get-credentials`, to its analogue from `linkerd install`. In Helm it's named `identityTrustDomain` so that's fine.
