### ISSUE TITLE
linkerd check --proxy fails on evicted pods

### ISSUE THREAD

**Issue by siggy** [linkerd/linkerd2#4476]
### What is the issue?

`linkerd check --proxy` fails with `error copying from local connection` errors when checking evicted pods.

### How can it be reproduced?

Run `linkerd check --proxy` on a cluster with injected pods that have been evicted.

#### `linkerd check` output

```bash
$ linkerd check --proxy
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API
...
linkerd-data-plane
------------------
√ data plane namespace exists
E0522 16:14:13.364556   93849 portforward.go:385] error copying from local connection to remote stream: read tcp6 [::1]:53217->[::1]:53219: read: connection reset by peer
| waiting for check to completeE0522 16:14:18.740409   93849 portforward.go:385] error copying from local connection to remote stream: read tcp6 [::1]:53217->[::1]:53230: read:
```

```bash
$ linkerd check --proxy --verbose
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API
...
linkerd-data-plane
------------------
√ data plane namespace exists
DEBU[0003] Making gRPC-over-HTTP call to [http://localhost:53312/api/v1/ListPods] []
DEBU[0004] Response from [http://localhost:53312/api/v1/ListPods] had headers: map[Content-Type:[application/octet-stream] Date:[Fri, 22 May 2020 23:15:25 GMT]]
DEBU[0004] gRPC-over-HTTP call returned status [200 OK] and content length [-1]
DEBU[0004] Retrying on error: The "foo/prometheus-5c7d8554c9-jsl8q" pod is not running
E0522 16:15:25.521699   93927 portforward.go:385] error copying from local connection to remote stream: read tcp6 [::1]:53312->[::1]:53315: read: connection reset by peer
| waiting for check to complete DEBU[0009] Making gRPC-over-HTTP call to [http://localhost:53312/api/v1/ListPods] []
...
× data plane proxies are ready
    The "foo/prometheus-5c7d8554c9-b8vr9" pod is not running
    see https://linkerd.io/checks/#l5d-data-plane-ready for hints

Status check results are ×
```

### Environment

- Kubernetes Version: v1.17.0
- Cluster Environment: AKS
- Host OS: Mac
- Linkerd version: `edge-20.5.4`

### Possible solution

`linkerd check --proxy` should ignore evicted pods.

**Comment by olix0r** [comment]
It would probably be best to turn this into a warning instead of an error?

**Comment by rajatjindal** [comment]
Hi @olix0r 

I started to look at this issue (i hope that is ok).

i wanted to clarify one thing:

in func `validateDataPlanePods`, we return error `if pod.Status != "Running" && pod.Status != "Evicted"`, 

if i understand correctly your suggestion is to print warning in this if condition and continue rather than returning error right? or you want the `check` itself to be `warning` level instead of `error`.

thanks

**Comment by ihcsim** [comment]
@rajatjindal Thanks for your interest in this issue. I believe this is resolved in https://github.com/linkerd/linkerd2/pull/4732. I'm closing this issue.
