### ISSUE TITLE
multicluster checks should show remote cluster names

### ISSUE THREAD

**Issue by Pothulapati** [linkerd/linkerd2#4478]
### What problem are you trying to solve?

Show remote cluster names in Check instead of `√ all remote cluster gateways are alive`

it would be awesome to have the check show clusters names with a tick mark. 

This would be useful, mainly because there isn't any direct way to check what all other clusters this cluster has access to, when there are no services enabled as mirrors(when services are mirrored,  linkerd cluster gateways can be used to see that information.)

### How should the problem be solved?

Show a tick mark with each cluster-name, just like we show warning with remote cluster name when something is wrong.

What do you want to happen? Add any considered drawbacks.

### Any alternatives you've considered?

Is there another way to solve this problem that isn't as good a solution?

### How would users interact with this feature?

If you can, explain how users will be able to use this. Maybe some sample CLI
output?

**Comment by adleong** [comment]
I believe that https://github.com/linkerd/linkerd2/pull/4510 already solves this issue by listing all linked remote clusters in the `mc gateways` output, even if no services have been mirrored.  Is that sufficient?

After some investigation, working this functionality into `linkerd check` is not straightforward.  While many checks will print additional information when they fail, there doesn't exist a mechanism for printing additional information when they succeed.  

One possible solution would be to allow checks to spawn subchecks:

```
√ service mirror controller is running
√ service mirror controller ClusterRoles exist
√ service mirror controller ClusterRoleBindings exist
√ service mirror controller Roles exist
√ service mirror controller RoleBindings exist
√ service mirror controller ServiceAccounts exist
√ service mirror controller has required permissions
× all remote cluster gateways are alive
√ * cluster: [gke-alex-dev], gateway: [linkerd-multicluster/linkerd-gateway] is alive
```
