### ISSUE TITLE
Multicluster Helm Charts

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#4491]
What is the user flow to install the multicluster helm charts without the CLI?

**Comment by alpeb** [comment]
The installation was tested fine with Helm, as @Pothulapati depicted it in linkerd/website#731.

As for the `linkerd multicluster` subcommands to be performed after the installation:
- `linkerd multicluster link`: it requires retrieving the SA token secret, so no way of doing that through Helm
- `linkerd multicluster export-service`: we might provide some kustomize resources to perform that
- `linkerd multicluster allow`: currently this renders the `remote-access-service-mirror-rbac.yaml` template from the multicluster chart. We could extract it into its own chart to allow doing this through `helm install`

**Comment by Pothulapati** [comment]
@alpeb Agree with the first two cases. 

But for `linkerd mc allow`, we could already do ` helm template --generate-name . --set serviceMirror=false --set gateway=false --set remoteMirrorServiceAccountName=<cluster-name>`
