### ISSUE TITLE
`linkerd multicluster gateways` returns empty until services are exported

### ISSUE THREAD

**Issue by alpeb** [linkerd/linkerd2#4495]
Even after having linked two clusters together, `linkerd multicluster gateways` returns empty, until there is at least one service being mirrored. It would be better to be able to see the health of the target cluster, as soon as the probe starts returning results.

**Comment by grampelberg** [comment]
Mind sharing the output between the two @alpeb?

**Comment by zaharidichev** [comment]
Umm.. yes currently gateways are probed actively if there is at least one service that is being mirrored and paired with the gateway in question. Is that something we want to change?

**Comment by alpeb** [comment]
> Mind sharing the output between the two @alpeb?

When there are no mirrored services:
```
$ bin/linkerd mc gateways
CLUSTER  NAMESPACE  NAME  ALIVE    NUM_SVC  LATENCY_P50  LATENCY_P95  LATENCY_P99  
```

After the first services are mirrored:
```
$ bin/linkerd mc gateways
CLUSTER  NAMESPACE             NAME             ALIVE    NUM_SVC  LATENCY_P50  LATENCY_P95  LATENCY_P99  
remote   linkerd-multicluster  linkerd-gateway  True           2        125ms        193ms        199ms
```

**Comment by grampelberg** [comment]
@zaharidichev does the latency come from the liveness checks or from the traffic?

**Comment by adleong** [comment]
This is fixed.  Gateways are now probed even when no services are mirrored.
