### ISSUE TITLE
Disabling the Grafana add-on does not have any effect

### ISSUE THREAD

**Issue by uhthomas** [linkerd/linkerd2#4515]
### What is the issue?

When setting `grafana.enabled: false`, the Grafana manifests should not be generated, but they are.

### How can it be reproduced?

Create a new Linkerd deployment and provide `grafana.enabled: false`. The Grafana deployment will exist, even though it shouldn't.

### Logs, error output, etc

My Helm release can be found [here](https://github.com/uhthomas/k8s/blob/5286b94d0465c46fe072864ce943b13aa1407e46/manifests/linkerd/linkerd2/helm-release.yaml#L32).

Even after deleting them manually and reapplying them, the manifests come back. See
```sh
➜  ~ kubectl -n linkerd get po -l linkerd.io/control-plane-component=grafana
NAME                               READY   STATUS    RESTARTS   AGE
linkerd-grafana-645db54784-lm8cz   2/2     Running   0          48m
```

#### `linkerd check` output

```sh
➜  ~ linkerd check
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-identity
----------------
√ certificate config is valid
√ trust roots are using supported crypto algorithm
√ trust roots are within their validity period
√ trust roots are valid for at least 60 days
√ issuer cert is using supported crypto algorithm
√ issuer cert is within its validity period
‼ issuer cert is valid for at least 60 days
    issuer certificate will expire on 2020-05-30T11:00:28Z
    see https://linkerd.io/checks/#l5d-identity-issuer-cert-not-expiring-soon for hints
√ issuer cert is issued by the trust root

linkerd-api
-----------
\ No running pods for "linkerd-web" ^C
```

`linkerd check` hanged because I have the dashboard disabled... Maybe I should open another issue for that?

### Environment

- Kubernetes Version: v1.17.5
- Cluster Environment: Digital Ocean
- Host OS: Linux
- Linkerd version:
Client version: stable-2.7.1
Server version: stable-2.7.1

### Possible solution

I took a quick glance through the chart and it all seems correct. Not sure what could be wrong. Haven't had this problem with any of the other charts I'm using.

### Additional context

I'm trying to make the cluster more lean, and therefore cut down on unnecessary deployments, of which `linkerd-grafana` is one of them.

**Comment by Pothulapati** [comment]
@uhthomas Thanks for trying this out!

Grafana deployment is moved into the new add-on model from `edge-20.5.2`. I see that you are trying this out in `stable-2.7.1`. Feel free to try the edge release out, and report if there is any problem. :) 

Also, This change will be in `stable-2.8`, which is close! :soon:

**Comment by Pothulapati** [comment]
Closing the issue!
