### ISSUE TITLE
Add support to handle mTLS for pod DNS.

### ISSUE THREAD

**Issue by vijaygos** [linkerd/linkerd2#4517]
### What problem are you trying to solve?
If a connection is made using pod hostnames, linkerd does not provide mTLS for these connections. Also, there are likely challenges around how we can roll out canary and blue|green deployments with flagger (or any other means) in such cases.
### How should the problem be solved?
The crux of the problem appears to be with service discovery. more details [here](https://linkerd.slack.com/archives/C89RTCWJF/p1590725817156700)

When using pod host names to make a connection inside a k8s cluster, linkerd must be able to proxy the connection and provide mTLS for the same.
### Any alternatives you've considered?
No.
Is there another way to solve this problem that isn't as good a solution?
No.
### How would users interact with this feature?
Scenarios where users use pod host names to talk to pods directly (eg: a custom grpc load balancer that decides which destination pod must handle the request) instead of a k8 service should be supported for proxy and mTLS

**Comment by olix0r** [comment]
@vijaygos Can you elaborate on why you've chosen to use Pod DNS?

We use `Service`s because they decouple the logical traffic target from the specific endpoints in the service (and are the underpinning of features like traffic split and multi-cluster routing).

I'm not sure if there's any reason that we can't support pod DNS (aside from added complexity)... but I'm curious if you can work around that with headless services?

**Comment by vijaygos** [comment]
@olix0r , Sorry about missing your question. let me clarify the use case a bit.
We have some queries whose durations are completely dependent on the user input. Some of our requests are long running as in stretching to multiple seconds vs some which are just a few miliseconds. We have custom load balancers that track the requests based on how long they are served at each of these backend pods and requests based on this information. This is something that cannot be done with just headless services.
I would love to contribute for this change if you can provide me some pointers.

**Comment by olix0r** [comment]
@vijaygos Thanks, this is helpful context. As we plan stable-2.9, we're starting to look into making some pretty fundamental changes to how the proxy does service discovery; and I think we can better-support this use case with these changes. I don't know that there's a whole lot we can do incrementally before then, but I'll ping this issue when we have a more concrete proposal.

**Comment by vijaygos** [comment]
Thanks, @olix0r . Do you have a sense of when we can expect the stable-2.9 release?
