### ISSUE TITLE
Polish Multicluster naming

### ISSUE THREAD

**Issue by zaharidichev** [linkerd/linkerd2#4521]
This is an issue to kick off some though around how we do name polishing for the Multicluster work

**Clusters:**
We currently refer to clusters as remote and local. Quite confusing.. We can instead turn that into: 

- target cluster - the cluster from which services are being mirrored
- source cluster - the cluster on which the mirror controller is running

**Labels/Annotations**
We currently have a prefix named `mirror.linkerd.io`. This is no matter what we are annotating. Lets split that into two groups.

gateway.linkerd.io - all labels/annotations that are on a  gateway service
mirror.linkerd.io - all labels/annotation that have to do with the service mirror controller. For example the metadata that indicates that a service should be mirrored OR that a service is a mirror of another service
multicluster.linkerd.io - all labels/annotations that cannot fall into these two categories. 

Alternatively we can split these according to where they live. So for example we can have the labels, annotations be classified based on whether they are present on the  source or the target gateway

Any other ideas are more than welcome.

**Comment by grampelberg** [comment]
Mind giving a couple examples of how it'd look with real data? Part of me wants to just have a common base like `multicluster.linkerd.io`. The source/target naming sounds tempting but I'm having a hard time visualizing what it would actually look like.

**Comment by zaharidichev** [comment]
@grampelberg I will do so. 

@kleimkuhler @olix0r WDYT?

**Comment by Pothulapati** [comment]
IMO, `gateway.linkerd.io` makes sense as the gateway allows communication from meshed applications that are outside the cluster, and it doesn't have to be a *cluster* (maybe for future cases like mesh expansion, etc)

**Comment by adleong** [comment]
Target cluster and source cluster is now the prevailing terminology.

Many labels and annotations have been removed.  `mirror.linkerd.io` is still used as a prefix for things related to service mirroring.
