### ISSUE TITLE
Potential mirroring simplification

### ISSUE THREAD

**Issue by zaharidichev** [linkerd/linkerd2#4535]
So say we have cluster west and cluster east and we want to mirror a service from west to east. 

Cluster west has the following gateway service: 

```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    linkerd.io/created-by: linkerd/cli git-2bf1f4c9
    mirror.linkerd.io/gateway-identity: linkerd-gateway.linkerd-multicluster.serviceaccount.identity.linkerd.west.k3d.example.com
    mirror.linkerd.io/multicluster-gateway: "true"
    mirror.linkerd.io/probe-path: /health
    mirror.linkerd.io/probe-period: "3"
  name: linkerd-gateway
  namespace: linkerd-multicluster
  resourceVersion: "1031"
spec:
  clusterIP: 10.43.227.166
  externalTrafficPolicy: Cluster
  ports:
  - name: incoming-port
    nodePort: 32510
    port: 4143
    protocol: TCP
    targetPort: 4143
  - name: probe-port
    nodePort: 32187
    port: 4181
    protocol: TCP
    targetPort: 4181
  selector:
    app: linkerd-gateway
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 172.19.0.6
```

It also has a service named `emoji-svc` that we want to mirror onto east: 

```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    mirror.linkerd.io/gateway-name: linkerd-gateway
    mirror.linkerd.io/gateway-ns: linkerd-multicluster
  name: emoji-svc
  namespace: emojivoto
  resourceVersion: "1235"
spec:
  clusterIP: 10.43.157.41
  ports:
  - name: grpc
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: prom
    port: 8801
    protocol: TCP
    targetPort: 8801
  selector:
    app: emoji-svc
```

Now in order to mirror that service onto east we need to first create a gateway mirror such as: 
```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    mirror.linkerd.io/mirrored-gateway-probe-path: /health
    mirror.linkerd.io/mirrored-gateway-probe-period: "3"
    mirror.linkerd.io/mirrored-gateway-remote-name: linkerd-gateway
    mirror.linkerd.io/mirrored-gateway-remote-namespace: linkerd-multicluster
    mirror.linkerd.io/remote-gateway-resource-version: "1031"
  labels:
    mirror.linkerd.io/cluster-name: west
    mirror.linkerd.io/mirrored-gateway: "true"
    mirror.linkerd.io/mirrored-service: "true"
  name: linkerd-gateway-west
  namespace: linkerd-multicluster
spec:
  clusterIP: 10.43.96.192
  ports:
  - name: probe-port
    port: 4181
    protocol: TCP
    targetPort: 4181
```
with endpoints that look like: 
```yaml
apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    mirror.linkerd.io/remote-gateway-identity: linkerd-gateway.linkerd-multicluster.serviceaccount.identity.linkerd.west.k3d.example.com
  labels:
    mirror.linkerd.io/cluster-name: west
    mirror.linkerd.io/mirrored-service: "true"
  name: linkerd-gateway-west
  namespace: linkerd-multicluster
subsets:
- addresses:
  - ip: 172.19.0.6
  ports:
  - name: probe-port
    port: 4181
    protocol: TCP
```
So far so good. we will be able to easily probe this remote gateway by hitting the mirrored gateway on port 4181. In order to mirror the service as well we have the following resources: 

```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    mirror.linkerd.io/remote-gateway-resource-version: "1031"
    mirror.linkerd.io/remote-resource-version: "1235"
    mirror.linkerd.io/remote-svc-fq-name: emoji-svc.emojivoto.svc.west.k3d.example.com
  creationTimestamp: "2020-06-02T07:51:21Z"
  labels:
    mirror.linkerd.io/cluster-name: west
    mirror.linkerd.io/mirrored-service: "true"
    mirror.linkerd.io/remote-gateway-name: linkerd-gateway
    mirror.linkerd.io/remote-gateway-ns: linkerd-multicluster
  name: emoji-svc-west
  namespace: emojivoto
spec:
  clusterIP: 10.43.230.149
  ports:
  - name: grpc
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: prom
    port: 8801
    protocol: TCP
    targetPort: 8801
```

```yaml
apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    mirror.linkerd.io/remote-gateway-identity: linkerd-gateway.linkerd-multicluster.serviceaccount.identity.linkerd.west.k3d.example.com
    mirror.linkerd.io/remote-svc-fq-name: emoji-svc.emojivoto.svc.west.k3d.example.com
  creationTimestamp: "2020-06-02T07:51:21Z"
  labels:
    mirror.linkerd.io/cluster-name: west
    mirror.linkerd.io/mirrored-service: "true"
    mirror.linkerd.io/remote-gateway-name: linkerd-gateway
    mirror.linkerd.io/remote-gateway-ns: linkerd-multicluster
  name: emoji-svc-west
  namespace: emojivoto
subsets:
- addresses:
  - ip: 172.19.0.6
  ports:
  - name: prom
    port: 4143
    protocol: TCP
  - name: grpc
    port: 4143
    protocol: TCP
```

This all works fine because of the endpoints that contain the IP of the gateway. The downside of this is that whenever a gateway is updated, we need to gather all service mirrors and update them as well. This is error prone and can lead to problems, especially in the face of failures. And yes, we can use the resourceVersion to try and achieve some level of atomicity, etc but this is all way too complicated. So it might very well happen that we go through the list, update half the services and fail and then try to retry, etc etc. Not to mention that this is costly. Our service mirror controller is issuing updates for all the services that are associated with this gateway of which there might be many.

So what can we do instead? I think that we can make it so the gateway mirror is used for more than simply probing. So instead of what we have above we can have the following:

```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    mirror.linkerd.io/mirrored-gateway-probe-path: /health
    mirror.linkerd.io/mirrored-gateway-probe-period: "3"
    mirror.linkerd.io/mirrored-gateway-remote-name: linkerd-gateway
    mirror.linkerd.io/mirrored-gateway-remote-namespace: linkerd-multicluster
    mirror.linkerd.io/remote-gateway-resource-version: "1031"
  creationTimestamp: "2020-06-02T07:51:21Z"
  labels:
    mirror.linkerd.io/cluster-name: west
    mirror.linkerd.io/mirrored-gateway: "true"
    mirror.linkerd.io/mirrored-service: "true"
  name: linkerd-gateway-west
  namespace: linkerd-multicluster
spec:
  clusterIP: 10.43.96.192
  ports:
  - name: probe-port
    port: 4181
    protocol: TCP
    targetPort: 4181
  - name: incoming-port
    port: 4143
    protocol: TCP
    targetPort: 4143

apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    mirror.linkerd.io/remote-gateway-identity: linkerd-gateway.linkerd-multicluster.serviceaccount.identity.linkerd.west.k3d.example.com
  labels:
    mirror.linkerd.io/cluster-name: west
    mirror.linkerd.io/mirrored-service: "true"
  name: linkerd-gateway-west
  namespace: linkerd-multicluster
subsets:
- addresses:
  - ip: 172.19.0.6
  ports:
  - name: probe-port
    port: 4181
    protocol: TCP
  - name: incoming-port
    port: 4143
    protocol: TCP
```

So the above gives us the gateway mirror with the correct IP and two exposed ports one for probing and one for normal traffic. The definition of the service we want to mirror will be the following then: 

```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    mirror.linkerd.io/remote-resource-version: "1235"
    mirror.linkerd.io/remote-svc-fq-name: emoji-svc.emojivoto.svc.west.k3d.example.com
  labels:
    mirror.linkerd.io/cluster-name: west
    mirror.linkerd.io/mirrored-service: "true"
    mirror.linkerd.io/remote-gateway-name: linkerd-gateway
    mirror.linkerd.io/remote-gateway-ns: linkerd-multicluster
  name: emoji-svc-west
  namespace: emojivoto
spec:
  clusterIP: 10.43.230.149
  ports:
  - name: grpc
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: prom
    port: 8801
    protocol: TCP
    targetPort: 8801
```

In this case we do not create any endpoints for this service. What we do instead is that we modify the destination service to return the endpoints of the associated gateway whenever we do discovery for this service. That should not be too hard because we have all the pieces we need: 

- we know this is a service mirror
- we know the fq name of the service so we can put together an authority override
- we know the gateway identity because it is an annotation on the gateway so we can give this endpoint an identity
- we know the IP of the gateway as it is present in the Endpoints subset of the gateway mirror

This will make things smoother and lighter in the service mirror code because now we would not care about updating endpoints on individual service mirrors. So there is no need of tracking the resourceVersion of the remote gateway for every service mirror, etc. When we receive an update for a gateway we only change the gateway mirror. Similarly the only things that can change for a service that is already mirrored are: 

- transition to not being mirrored anymore
- change the set of exposed ports
- change the gateway it is associated with

I think this is a change that is not very hard but results in: 

- a lot less implementation complexity
- less error prone service mirror controller
- potential performance improvements

To play devil's advocate, this has some magical elements to it as we are creating a service without any endpoints and rely on the proxy to serve some endpoints for it that are attached onto another service. So looking at yaml without really understanding how all of this fits together will net close to zero results to someone who is trying to debug potential problems.

**Comment by zaharidichev** [comment]
@grampelberg @adleong WDYT ?

**Comment by grampelberg** [comment]
One of the reasons I like the current solution is because it works the same way every service in k8s does. We should be able to create the mirror services as `externalName` services to the gateway service though and that'd solve the same issue AFAICT.

**Comment by zaharidichev** [comment]
You are correct, it  will solve the same issue. Also we currently do not support discovery for external services. We can change that ofcourse. But yes the solution is quite similar really. I like the current setup as well but this will result in a lot of simplification. Also.. its not entirely true that this works like every other k8s service. We still do some magical things such as authority and identity rewriting based on metadata on the svc, etc. I guess this is just one step further.

**Comment by adleong** [comment]
I don't think we want to pursue this, at least from the lens of simplification.  There are some other aspects such as support for external services and better support for ingresses which are exposed as a DNS hostname, but we should address those in their own specific issues.
