### ISSUE TITLE
Add checks for misconfigured export services

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#4541]
## What problem are you trying to solve?

When manually changing the annotations on exported services, you can change the gateway name. It is possible that this gateway either doesn't exist or is misconfigured. Currently `check` appears to be healthy, but no traffic is happening.

### How should the problem be solved?

- On the source cluster, there should be a failure if a mirrored service does not have any endpoints.
- On the target cluster, there should be an error if an exported service is referencing a gateway that does not exist.

## Open Questions

- Should we validate the target cluster gateway's configuration as well?
- Should `check` fail mirrored services in the source cluster when the gateway is unreachable or misconfigured? We could improve the help text but I'm not sure it is worth the extra effort.

**Comment by Pothulapati** [comment]
Working on this today!
