### ISSUE TITLE
Add mock timers for timing-dependent tests

### ISSUE THREAD

**Issue by hawkw** [linkerd/linkerd2#455]
- [x] Create a facade that abstracts over timer implementations
- [x] Modify existing code to use the timer facade
- [ ] Create a mock timer that implements the timer facade
- [ ] Rewrite time-dependent tests to use the mock timer instead

Probably depends on #412.

**Comment by hawkw** [comment]
Some progress on this: 01aa4ff906f4d050b484eafad853f39cf327f413.

I've gotten everything ready for injecting mock timers, but there isn't yet a mock timer implementation, and I haven't rewritten the tests to use mock timers yet. Currently hitting a bug in some of the tests that I'm trying to work out.

**Comment by olix0r** [comment]
related: https://github.com/tokio-rs/tokio/pull/368

**Comment by olix0r** [comment]
@hawkw what is the state of this?

**Comment by hawkw** [comment]
@olix0r the required Tokio changes have landed, and I think we should be able to rewrite our tests to use the Tokio mock timer support. I haven't been working on this, however, as it hasn't been prioritized and I'm not sure how big an impact it will have --- most of the flaky tests are flaky because they depend on _ordering_ rather than time.
