### ISSUE TITLE
Better deal with the possibility that the user has overridden the namespace during `conduit install` and/or `conduit inject`

### ISSUE THREAD

**Issue by briansmith** [linkerd/linkerd2#456]
In #365 we modified the `conduit inject` code to recognize when we're injecting the proxy into the `controller.controller` deployment.

@adleong pointed out in https://github.com/runconduit/conduit/pull/448#discussion_r170711755 that we don't know the final value of the namespace at `conduit inject` time. I am guessing that's because the user can use `kubectl -n some-other-namespace` to change the namespace?

If so, then maybe we need to move this logic from `conduit inject` to the conduit proxy: That is, have the proxy substitute "localhost" when it sees that it is injected into "controller.conduit".

Conversely, if/when we implement the mutating webhook, the mutating webhook will know the final namespace name, and we might be able to move such logic out of the proxy and into the webhook.

/cc @deebo91 @adleong

**Comment by adleong** [comment]
I think in this case we always explicitly set the namespace field in the installed components.  So this shouldn't be an issue.
