### ISSUE TITLE
Support grafana.image.version field

### ISSUE THREAD

**Issue by Pothulapati** [linkerd/linkerd2#4572]
### How should the problem be solved?

PR #4571 removes the `grafana.image.version` field, thus restricting using our own image tag. This is caused because of the tight coupling between the linkerd version. This prevents grafana image tag from being upgraded, when grafana.image.version is present in `linkerd-config-addons`
### What problem are you trying to solve?

Ideally there should not be a tight dependency between add-on upgrades and control plane upgrades. 

What do you want to happen? Add any considered drawbacks.

Support image overwriting without running into the upgrade problem

### Any alternatives you've considered?

Is there another way to solve this problem that isn't as good a solution?

### How would users interact with this feature?

If you can, explain how users will be able to use this. Maybe some sample CLI
output?

**Comment by Pothulapati** [comment]
So, I was thinking about this today.

Currently with Add-Ons, we store the default configuration in `values.yaml` and that is also stored directly in `linerd-config-addons` as a configmap. This was done because to have a central place where add-on config is present for things like check to use, and also users to update. 

The problem is now when we perform upgrades, we can't really change those values as the updated default values are overridden by the current values in `linkerd-config-addons` and these could be the older default values

## Possible Solution

Without changing much, this can be solved by making values like `image`, etc which need updates from the project **should not be present in `<add-on>:` in `values.yaml` by default** as they are used directly in cm instead they should be present in the template or another field in value. This prevents the default value from going into the cm, thus making it over-writable. This also allows users to specify `add-on.image.version` which is considered as the one to use when explicitly set.

**Comment by alpeb** [comment]
Sounds like a proper solution to me :+1:

**Comment by alpeb** [comment]
Would be very useful to exercise this kind of overriding in an upgrade integration test (easier if done in the existing one) :wink:

**Comment by Pothulapati** [comment]
We added support for this in #4682
