### ISSUE TITLE
Consider more aggressive reconcilation in service mirror controller

### ISSUE THREAD

**Issue by adleong** [linkerd/linkerd2#4575]
The service mirror controller is event driven.  This means that it reacts to events in the remote cluster such as services being created, updated, or deleted.  This means that if the local state gets out of sync such as if someone manually edits a mirror service endpoints object, that local state will not be repaired until the remote service is updated (a possibly indefinite amount of time).

A more aggressive approach would be do full reconciliation at regular intervals:
* read the full state of gateways and exported services from the remote cluster
* determine the desired local state based on that remote state
* compare the actual local state to the desired local state
* apply any updates necessary

Doing full reconciliation would prevent local state from getting stuck in an invalid state and would also simplify the code since we will no longer need logic to determine which events should trigger updates on which set of resources.  In addition to doing reconciliation at regular intervals, we could also have certain events from the remote cluster trigger reconciliation so that updates propagate quickly.

**Comment by cpretzer** [comment]
+1 on this. I also suggest adding a `sync` sub-sub-command to the `multicluster` subcommand to force reconciliation on demand.

**Comment by zaharidichev** [comment]
>  if someone manually edits a mirror service endpoints object, that local state will not be repaired until the remote service is updated (a possibly indefinite amount of time).

I think in these situations we can rely on the automatic resync period which is configurable and runs every 10 minutes currently. Not sure whether we can actually force that

**Comment by grampelberg** [comment]
I dunno, as someone who violently hates reconciliation getting in the way of my testing ... maybe a happy medium is making it configurable?

**Comment by adleong** [comment]
@grampelberg in that you want to be able to manually edit endpoints and not get clobbered?

**Comment by grampelberg** [comment]
@adleong yeah, I'm not sure it is a strong reason in this instance. I just run into issues with `kube-system` all the time when I want to change something random and it gets reverted.

**Comment by adleong** [comment]
I'm not sure there's sufficient motivation to pursue this.  If we run into problems with the service mirror controller code in the future, we can revisit this.
