### ISSUE TITLE
Transport events when error or close before protocol detection

### ISSUE THREAD

**Issue by seanmonstar** [linkerd/linkerd2#458]
Currently, to detect what protocol a transport is speaking, we wait on all incoming connections for the first `MSG_PEEK` read, and try to guess with those bytes.

If there is a socket error during the peek, or if the connection is closed at that time, we don't have a good way to report this as an event. We have no idea what protocol it may have been, but one is required when first triggered a `TransportOpen` event.

**Comment by olix0r** [comment]
This is probably good to consider in the same context as #425
