### ISSUE TITLE
Manual multicluster gateway configuration

### ISSUE THREAD

**Issue by pnovotnak** [linkerd/linkerd2#4584]
### What problem are you trying to solve?

Currently, multicluster configuration is automagic (the API is queried and `ingress.IP` is discovered). I'm sure this is great for most use cases. However, in some environments there won't be an ingress IP for whatever reason, or the service will be of type NodePort, etc. In these environments it would be great to have a way to manually configure the gateway IPs or hostnames.

### How should the problem be solved?

> What do you want to happen? Add any considered drawbacks.

I'd like to manually configure the endpoint that is used to contact the gateway in a given cluster. To do so, I think another flag should be added to the `multicluster link` command.

#### Possible Approaches

- Annotations on the gateway, an endpoint for each port?
    - Drawbacks
        - Not context aware (think AWS VPCE where each VPC might have a different endpoint)
- Extra flag on the `multicluster link` command
    - Drawbacks
        - More client configuration parameters
        - Need to keep this flag in sync as gateway ports are added / removed

### Any alternatives you've considered?

> Is there another way to solve this problem that isn't as good a solution?

Having the multicluster service sync daemon consider `spec.ExternalIPs` is potentially a good alternative approach, if it can discard ExternalIPs that are not reachable. But this approach doesn't allow remapping ports.

### How would users interact with this feature?

> If you can, explain how users will be able to use this. Maybe some sample CLI
output?

Here is an example of what this would look like in a KinD environment (where  `172.17.0.3` and `172.17.0.4` are containers where `east` and `west` run, respectively)

    $ k get service -n linkerd-multicluster
    NAME                                      TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)                         AGE
    linkerd-gateway                           NodePort       10.96.0.25     <none>        4143:34143/TCP,4181:34181/TCP   17h

    $ linkerd \
        --context=east multicluster link \
            --api-server-address https://172.17.0.4:6443 \
            --gateway-endpoint-{{port type 1}} https://172.17.04:34143 \ 
            --gateway-endpoint-{{port type 2}} https://172.17.0.4:34181 \ 
            --cluster-name east | 
    kubectl --context=west apply -f -

    $ linkerd \
        --context=west multicluster link \
            --api-server-address https://172.17.03:6443 \
            --gateway-endpoint-{{port type 1}} https://172.17.03:34143 \ 
            --gateway-endpoint-{{port type 2}} https://172.17.03:34181 \ 
            --cluster-name west | 
    kubectl --context=east apply -f -

**Comment by adleong** [comment]
It's now possible to manually edit the `Link` custom resource created by `linkerd multicluster link` to override the gateway address.  More detailed docs about this will be added soon.
