### ISSUE TITLE
nginx-ingress proxy connection timeouts on stable-2.8.0

### ISSUE THREAD

**Issue by mmiller1** [linkerd/linkerd2#4585]
## Bug Report
After upgrading to stable-2.8.0 it was observed that requests to nginx-ingress from an assortment of internal clients lacking a proper DNS host name in the host header would result in thousands of connection timeouts being reported by nginx, ultimately until the pods were restarted due to failing liveness probes or OOMKills. Requests were sourced from various locations, most requests were from load balancers that were attempting to do health checks on services running behind the ingress controller, some were web browser initiated requests using the web proxy auto-discovery protocol. 

### How can it be reproduced?
put an nginx ingress controller in the 2.8.0 mesh, and send a request to it using only the controller's IP address. 
```
curl 10.130.150.24/hello -v
```
would result in error messages like this in nginx:
```
2020/06/10 21:32:54 [error] 55#55: *10392 connect() failed (111: Connection refused) while connecting to upstream, client: 10.132.98.133, server: _, request: "GET /hello HTTP/1.1", upstream: "http://10.244.245.159:8080/", host: "10.130.150.24"
```
in this case the client in the log output is the kubernetes node that the pod was running on, and the upstream is a pod from the configured default backend service.

#### `linkerd check` output

```text
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-identity
----------------
√ certificate config is valid
√ trust anchors are using supported crypto algorithm
√ trust anchors are within their validity period
√ trust anchors are valid for at least 60 days
√ issuer cert is using supported crypto algorithm
√ issuer cert is within its validity period
√ issuer cert is valid for at least 60 days
√ issuer cert is issued by the trust anchor

linkerd-api
-----------
√ control plane pods are ready
√ control plane self-check
√ [kubernetes] control plane can talk to Kubernetes
√ [prometheus] control plane can talk to Prometheus
√ tap api service is running

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ control plane is up-to-date
√ control plane and cli versions match

linkerd-addons
--------------
√ 'linkerd-config-addons' config map exists

linkerd-grafana
---------------
√ grafana add-on service account exists
√ grafana add-on config map exists
√ grafana pod is running

Status check results are √
```

### Environment

- Kubernetes Version: 1.15.6
- Cluster Environment: bare-metal, vanilla k8s
- Host OS: ubuntu 18.04
- Linkerd version: stable-2.8.0

### Possible solution
Unsetting the LINKERD2_PROXY_DESTINATION_GET_NETWORKS variable in the proxy container allows things to work

**Comment by mmiller1** [comment]
Rolling back just the proxy injector to 2.7.1 and explicitly setting the proxy versions to 2.8.0 seems to be a suitable workaround for us, the only noticeable difference on the injected pods is the lack of the "INKERD2_PROXY_DESTINATION_GET_NETWORKS env variable, and that the metrics endpoint is being probed for liveness instead of "/live"

**Comment by zaharidichev** [comment]
@mmiller1 So I have a cluster with an nginx controller inside the mesh and when I hit the controller without a hostname, I do not get any timeouts neither I get any suspicious logs in the proxy: 

```
root@blue-866b4d5889-6kkzh:/# curl  http://10.60.1.17 -v
* Rebuilt URL to: http://10.60.1.17/
* Hostname was NOT found in DNS cache
*   Trying 10.60.1.17...
* Connected to 10.60.1.17 (10.60.1.17) port 80 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.38.0
> Host: 10.60.1.17
> Accept: */*
>
< HTTP/1.1 404 Not Found
* Server nginx/1.19.0 is not blacklisted
< server: nginx/1.19.0
< date: Fri, 12 Jun 2020 08:52:08 GMT
< content-type: text/html
< content-length: 153
```

```
root@blue-866b4d5889-6kkzh:/# curl -H "Host: example.com" http://10.60.1.17 -v
* Rebuilt URL to: http://10.60.1.17/
* Hostname was NOT found in DNS cache
*   Trying 10.60.1.17...
* Connected to 10.60.1.17 (10.60.1.17) port 80 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.38.0
> Accept: */*
> Host: example.com
>
< HTTP/1.1 200 OK
* Server nginx/1.19.0 is not blacklisted
< server: nginx/1.19.0
< date: Fri, 12 Jun 2020 08:51:42 GMT
< content-type: text/html
< content-length: 560
```

I tried that from both an unmeshed and meshed pod in the cluster. Am I doing something wrong here so  I cannot see this happening. Can you provide more precise steps for reproducing it?

**Comment by mmiller1** [comment]
Do you have a default backend defined by chance?

**Comment by zaharidichev** [comment]
Hmm maybe my default backend configuration is not quite right but even with default backend configured I do get a 404: 

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web-ingress
  namespace: emojivoto
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/default-backend: "web-svc"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
      grpc_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
spec:
  rules:
  - host: example.com
    http:
      paths:
      - backend:
          serviceName: web-svc
          servicePort: 80
```

**Comment by mmiller1** [comment]
I'm referring to the default backend that nginx can be configured to send the requests to if no ingress rules match: https://kubernetes.github.io/ingress-nginx/user-guide/default-backend/
On my nginx-ingress deployments we have that set with the following flag:
```
--default-backend-service=kube-system/default-backend
```
the pods in that service are also running nginx that mostly serve out 302 responses to other resources.

**Comment by zaharidichev** [comment]
@mmiller1  I see makes sense.  I tried installing with that flag. Same behaviour. Can you provide the exact set of flags we need to install the ingress controller with in order to reproduce  all this. This will certainly make things easier to debug.

**Comment by mmiller1** [comment]
Here is a gist containing the (almost) exact configurations we use. https://gist.github.com/mmiller1/9add70fe196a05e76019fecfd75142e9

I was able to reproduce this on a fresh cluster by doing the following:
```
cat linkerd-4585.yaml| linkerd inject --manual - | kubectl apply -f -
```
wait for the pods to come online...
```
curl http://<any node IP>:$(k get svc -n nginx | awk '/controller/ {print $5}' | awk -F'[:/]' '{print $2}')/whatever
```
Note that no ingress resource needs to be defined to reproduce the issue, as it appears when the request _doesn't_  match any ingress resources.

**Comment by zaharidichev** [comment]
@mmiller1 I think #4608 should give you a way to avoid this situation. Let us know whether that works for you.

**Comment by mmiller1** [comment]
that looks like that will do the trick, thanks!

**Comment by adleong** [comment]
Hi @mmiller1.  After some more investigation, I'm wondering if it's possible for you to create an Ingress resource for your default backend.  This will allow you to configure nginx to properly set the `l5d-dst-override` header that helps Linkerd to correctly route the request and avoid looping.  I've written this up in more detail here: https://github.com/linkerd/linkerd2/issues/4636

Let me know if you think this is feasible and if you're able to give it a try.

**Comment by mmiller1** [comment]
Wow, I didn't realize you could specify an ingress resource without a host or path - I will definitely give this a shot early next week, thanks!
