### ISSUE TITLE
CI: restart count flakiness

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#4595]
We frequently see CI flakiness that manifests as:

```
--- FAIL: TestResourcesPostInstall (46.26s)
    uninstall_test.go:54: Error validating pods for deploy [linkerd-grafana]:
        Container [linkerd-proxy] in pod [linkerd-grafana-65b4cf7cdb-skjnm] in namespace [l5d-integration] has restart count [1]
FAIL
found unexpected warning event: reason: [Failed] Object: [linkerd-grafana-65b4cf7cdb-skjnm] Message: [Error: failed to create containerd task: failed to start io pipe copy: unable to copy pipes: containerd-shim: opening w/o fifo "/run/containerd/io.containerd.grpc.v1.cri/containers/linkerd-proxy/io/643455312/linkerd-proxy-stdout" failed: context deadline exceeded]
FAIL	command-line-arguments	91.725s
FAIL
```

What causes these restarts?

If they are innocuous, should these assertions be removed/relaxed/

**Comment by alpeb** [comment]
It's a containerd bug: containerd/containerd#4068
k8s tests are also experiencing the same flakiness: kubernetes/kubernetes#89064

We can either:
- Wait till that gets fixed upstream and keep on re-running these failed tests
- Only log restarts, and not fail on them till that gets fixed, potentially not catching other reasons for restarts
- If a restart occurs, fetch k8s events and don't fail if there's a match against a known warning like this one

**Comment by mayankshah1607** [comment]
@alpeb @olix0r We're reusing some of the code from the install integration tests for [conformance validation](https://github.com/linkerd/linkerd2-conformance/pull/1) and hence, this issue of restart count seems to persist there as well. It would be great to have this fixed so that users running the conformance tests do not run into any misleading test case failures.

> If a restart occurs, fetch k8s events and don't fail if there's a match against a known warning like this one

sounds like a great option to me, and I'd be more than happy to provide a fix if we do decide to go down this path. 😄

**Comment by olix0r** [comment]
If it's easy (less than a day of work) to do the event detection, let's just do that. If it might take longer, I think I'd prefer that we prevent these errors from causing test failures while we work on a better detection mechanism.

**Comment by alpeb** [comment]
Thanks @mayankshah1607 . It's not a trivial change so in the meantime I'll just push a PR for just logging these failures, to get us going.
