### ISSUE TITLE
Support Gateways in the dashboard

### ISSUE THREAD

**Issue by Pothulapati** [linkerd/linkerd2#4601]
## Feature Request

Currently, There is no way to get gateways information in the Linkerd2 dashboard. As this information is exposed through the `public-api`, It should not be hard to have a `Gateways` tab where we can show the same information from the CLI using a `MetricsTable`

### What problem are you trying to solve?

Remote gateways information in the dashboard

### How should the problem be solved?

Add a `Gateways` Tab into the Linkerd2 dashboard?

### Any alternatives you've considered?

There is the CLI already for this information, but as this info is fetched from public-api, It should be a pretty straight forward PR.

### How would users interact with this feature?

If you can, explain how users will be able to use this. Maybe some sample CLI
output?

**Comment by tharun208** [comment]
I like to work on this @Pothulapati

**Comment by Pothulapati** [comment]
Hey @tharun208, Feel free to take this up.

The expectation is to have a `Gateways` tag below `Control-Plane` and provide the same UI of that of `linkerd mc gateways`. :)
