### ISSUE TITLE
@grpc/grpc-js doesn't include port in authority, leading to routing failures

### ISSUE THREAD

**Issue by seeruk** [linkerd/linkerd2#4605]
### What is the issue?
This seems more like an issue with the `@grpc/grpc-js` node package, but I've been asked to make an issue here too.

I've made an issue in the `@grpc/grpc-js` repository too: https://github.com/grpc/grpc-node/issues/1475

Essentially `@grpc/grpc-js` doesn't include the port in the authority which leads to routing failures, as (understandably) Linkerd then defaults to port 80, and the request fails.

It's the same problem that occurred over here: https://github.com/grpc/grpc-go/issues/1120

### How can it be reproduced?

Create a `@grpc/grpc-js` client application, attempt to make a request to a grpc service, it should fail unless the server is actually running on port 80.

### Logs, error output, etc

For comparison, here's what `$ linkerd tap` looks like for the gRPC client application:

With `grpc`:

```
req id=0:2 proxy=out src=172.30.0.16:48814 dst=172.30.0.18:50051 tls=true :method=POST :authority=client.default.svc.cluster.local:50051 :path=/namespace.Service/Method
rsp id=0:2 proxy=out src=172.30.0.16:48814 dst=172.30.0.18:50051 tls=true :status=200 latency=22078µs
end id=0:2 proxy=out src=172.30.0.16:48814 dst=172.30.0.18:50051 tls=true grpc-status=OK duration=76µs response-length=89B
```

With `@grpc/grpc-js`:

```
req id=0:1 proxy=out src=172.30.7.39:49006 dst=172.30.1.10:80 tls=true :method=POST :authority=client.default.svc.cluster.local :path=/namespace.Service/Method
rsp id=0:1 proxy=out src=172.30.7.39:49006 dst=172.30.1.10:80 tls=true :status=200 latency=37035µs
end id=0:1 proxy=out src=172.30.7.39:49006 dst=172.30.1.10:80 tls=true grpc-status=Unavailable duration=28µs response-length=0B
```

### Environment

- Kubernetes Version: 1.16
- Cluster Environment: GKE
- Linkerd version: 2.8.0

### Possible solution

Seems like this one is up to the grpc/grpc-node maintainers. However, a note could be added to the documentation, similar to the one about `grpc-go` over here: https://linkerd.io/2/features/http-grpc/

**Comment by cpretzer** [comment]
Thanks @seeruk! Interested in contributing a doc [PR](https://github.com/linkerd/website/pulls)?

**Comment by seeruk** [comment]
Sure thing! What I'd suggest for now though is that we wait for the grpc-node issue to be resolved first. It looks like a solution has been found and a PR has been opened, so I'll create docs PR once I know which version the issue has been resolved in.

**Comment by cpretzer** [comment]
Awesome, thank you @seeruk

**Comment by seeruk** [comment]
I think this one might be wrapped up now!
