### ISSUE TITLE
linkerd upgrade multi- stage fails on control plane stage with linkerd-config not found

### ISSUE THREAD

**Issue by devteng** [linkerd/linkerd2#4606]
### What is the issue?
Install Linkerd 2.7.1 with multi-stage install. When trying to upgrade with instruction from here https://linkerd.io/2/reference/cli/upgrade/ it crashes stating that the linkerd-config not found. It looks like during the linkerd config upgrade, the config was pruned.

### How can it be reproduced?
Install Linkerd 2.7.1 multi-stage
Upgrade to Linkerd 2.8.0

### Logs, error output, etc

#linkerd upgrade config | kubectl apply --prune -l linkerd.io/control-plane-ns=linkerd -f -

Don't forget to run `linkerd upgrade control-plane`!

namespace/linkerd unchanged
clusterrole.rbac.authorization.k8s.io/linkerd-linkerd-identity unchanged
clusterrolebinding.rbac.authorization.k8s.io/linkerd-linkerd-identity unchanged
serviceaccount/linkerd-identity unchanged
clusterrole.rbac.authorization.k8s.io/linkerd-linkerd-controller unchanged
clusterrolebinding.rbac.authorization.k8s.io/linkerd-linkerd-controller unchanged
serviceaccount/linkerd-controller unchanged
clusterrole.rbac.authorization.k8s.io/linkerd-linkerd-destination unchanged
clusterrolebinding.rbac.authorization.k8s.io/linkerd-linkerd-destination unchanged
serviceaccount/linkerd-destination unchanged
role.rbac.authorization.k8s.io/linkerd-heartbeat unchanged
rolebinding.rbac.authorization.k8s.io/linkerd-heartbeat unchanged
serviceaccount/linkerd-heartbeat unchanged
role.rbac.authorization.k8s.io/linkerd-web unchanged
rolebinding.rbac.authorization.k8s.io/linkerd-web unchanged
clusterrole.rbac.authorization.k8s.io/linkerd-linkerd-web-check unchanged
clusterrolebinding.rbac.authorization.k8s.io/linkerd-linkerd-web-check unchanged
clusterrolebinding.rbac.authorization.k8s.io/linkerd-linkerd-web-admin unchanged
serviceaccount/linkerd-web unchanged
customresourcedefinition.apiextensions.k8s.io/serviceprofiles.linkerd.io unchanged
customresourcedefinition.apiextensions.k8s.io/trafficsplits.split.smi-spec.io unchanged
clusterrole.rbac.authorization.k8s.io/linkerd-linkerd-prometheus unchanged
clusterrolebinding.rbac.authorization.k8s.io/linkerd-linkerd-prometheus unchanged
serviceaccount/linkerd-prometheus unchanged
clusterrole.rbac.authorization.k8s.io/linkerd-linkerd-proxy-injector unchanged
clusterrolebinding.rbac.authorization.k8s.io/linkerd-linkerd-proxy-injector configured
serviceaccount/linkerd-proxy-injector unchanged
secret/linkerd-proxy-injector-tls unchanged
mutatingwebhookconfiguration.admissionregistration.k8s.io/linkerd-proxy-injector-webhook-config configured
clusterrole.rbac.authorization.k8s.io/linkerd-linkerd-sp-validator unchanged
clusterrolebinding.rbac.authorization.k8s.io/linkerd-linkerd-sp-validator configured
serviceaccount/linkerd-sp-validator unchanged
secret/linkerd-sp-validator-tls unchanged
validatingwebhookconfiguration.admissionregistration.k8s.io/linkerd-sp-validator-webhook-config configured
clusterrole.rbac.authorization.k8s.io/linkerd-linkerd-tap unchanged
clusterrole.rbac.authorization.k8s.io/linkerd-linkerd-tap-admin unchanged
clusterrolebinding.rbac.authorization.k8s.io/linkerd-linkerd-tap unchanged
clusterrolebinding.rbac.authorization.k8s.io/linkerd-linkerd-tap-auth-delegator unchanged
serviceaccount/linkerd-tap unchanged
rolebinding.rbac.authorization.k8s.io/linkerd-linkerd-tap-auth-reader unchanged
secret/linkerd-tap-tls unchanged
apiservice.apiregistration.k8s.io/v1alpha1.tap.linkerd.io unchanged
podsecuritypolicy.policy/linkerd-linkerd-control-plane configured
role.rbac.authorization.k8s.io/linkerd-psp unchanged
rolebinding.rbac.authorization.k8s.io/linkerd-psp unchanged
serviceaccount/linkerd-grafana unchanged
configmap/linkerd-config pruned
configmap/linkerd-grafana-config pruned
configmap/linkerd-prometheus-config pruned
secret/linkerd-identity-issuer pruned
service/linkerd-controller-api pruned
service/linkerd-dst pruned
service/linkerd-grafana pruned
service/linkerd-identity pruned
service/linkerd-prometheus pruned
service/linkerd-proxy-injector pruned
service/linkerd-sp-validator pruned
service/linkerd-tap pruned
service/linkerd-web pruned
cronjob.batch/linkerd-heartbeat pruned
deployment.apps/linkerd-controller pruned
deployment.apps/linkerd-destination pruned
deployment.apps/linkerd-grafana pruned
deployment.apps/linkerd-identity pruned
deployment.apps/linkerd-prometheus pruned
deployment.apps/linkerd-proxy-injector pruned
deployment.apps/linkerd-sp-validator pruned
deployment.apps/linkerd-tap pruned
deployment.apps/linkerd-web pruned

#linkerd upgrade control-plane | kubectl apply --prune -l linkerd.io/control-plane-ns=linkerd -f -

× Failed to build upgrade configuration: could not fetch configs from kubernetes: configmaps "linkerd-config" not found
For troubleshooting help, visit: https://linkerd.io/upgrade/#troubleshooting

#### `linkerd check` output

```text
your output here ...
```

### Environment

- Kubernetes Version: 1.16.9
- Cluster Environment: AKS
- Host OS: Ubuntu 16
- Linkerd version: 2.7.1

### Possible solution
Remove --prune from the config upgrade command?
linkerd upgrade config | kubectl apply -l linkerd.io/control-plane-ns=linkerd -f -

**Comment by cpretzer** [comment]
Thanks for the report @devteng I'll look into this.
