### ISSUE TITLE
proxy: Simplify tap server

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#4611]
The proxy's tap server has a very complicated registry task:

https://github.com/linkerd/linkerd2-proxy/blob/c579f42a4b6f5dd0f73ffce419462052c5045e4a/linkerd/proxy/tap/src/daemon.rs#L63-L156

At the very least, this should become an `async fn`. But, as we do this, we also have an opportunity, I think to eliminate this task entirely. To do this, the tap service would hold something like:

```rust
struct Server {
  taps_tx: Mutex<Registry>,
  taps_rx: watch::Receiver<Vec<Weak<Tap>>>,
   ..
}

struct Registry {
  taps: Vec<Weak<Tap>>,
  tx: watch::Sender<Vec<Weak<Tap>>>,
}
```

Then, each `tap` response is responsible for holding a strong reference to the tap handle until the request is dropped or the number of requested tap events has been satisfied. We'll probably want to instrument some (background task?) way to clear dropped taps from the registry.

Since I have some pretty detailed thoughts about this, we may want to pair on it to short-circuit back and forth in the review, but it would be good to get a handle on what's there (in the linkerd/proxy/tap crate) first.

**Comment by kleimkuhler** [comment]
Closed by linkerd/linkerd2-proxy#582
