### ISSUE TITLE
Support minimal installation footprint

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#4612]
For the Linkerd data plane to function correctly, it only needs (1) the proxy injection admission controller, (2) the identity service, and (3) the destination service.  Other components like the Web UI, Tap, Grafana, Prometheus, etc are purely optional.

I propose the following:

1. These optional components be moved into a "linkerd-viz" extension (analogous to the linkerd-multicluster extension). CRDs, API Extensions, RBAC, etc, that are only required by these components should only be installed when this extension is installed.
2. `linkerd install` should install this extension by default, but should provide a flag to opt-out of installing it. Ideally `linkerd viz install` can be used to install this component post-hoc.
3. CLI commands that interact with services in this extension (tap, stat, etc) should fail gracefully when the extension is not installed.

### Questions:

* How to upgrade from 2.8?

**Comment by Pothulapati** [comment]
On top of my mind, I see that the following changes are required from the exisiting model to make this possible.
- Obviously, The first requirement would be to separate web, tap, Prometheus into individual add-ons.
- Support Individual Install/Uninstall of add-ons. Currently, The add-ons go hand in hand with control-plane install but we want a model like the current multi-cluster model where you can install and uninstall it without effecting the control-plane components. This looks possible with the current model as all these add-ons are sub-charts currently, and if we can populate all the existing `Values` struct but leave the control-plane chart while rendering could make this possible.
- To provide packages like `linkerd-viz`, etc we can have a `viz-values.yaml` which just configures the required components and disables others, and this file can be used by the CLI if the viz component is to be installed. The same can also be used with Helm.
- Currently `linkerd-config-addons` is where all the add-on config goes, and is used by the check command. We can have a similar thing with stat, tap, etc where we first check if the relevant component is installed and try running those commands only then.

The above are the assumptions/thinking based on the current add-on model. But if we need a more better way to do the above stuff, I'm happy to discuss and consider them. :)

**Comment by alpeb** [comment]
I agree we should continue with the add-ons model to achieve this kind of modularity. Currently that approach is not very user-friendly as it requires writing yaml to be passed to the `--addon-config` flag at install/upgrade time. But having a separate subcommand to install these might allow us to surface those config items as separate CLI flags as well, no longer having the `linkerd install` flag explosion fear.

As for upgrading from 2.8, I only see these flag values from `linkerd install` that would get moved into the viz add-ons:
```
- controller-log-level
- controller-replicas
- controller-uid
- prometheus-image
- restrict-dashboard-privileges
```
It's probably enough to just document those changes and not resort to some specific upgrade logic to migrate.

**Comment by olix0r** [comment]
I don't understand enough about the current addons model to comment specifically, but I think we should take some special attention to modularity. Here are a few goals (but not necessarily hard requirements):

* All _viz_ components are installed in a `linkerd-viz` namespace. These components no longer need special-cases for injection, as the injector can be responsible for instantiating these.
* Nothing in the `linkerd` namespace knows anything special `linkerd-viz` namespace.
* The proxy injector obviously needs to know about some features like tracing...
  * Ideally, this could all be expressed as an additive patch provided when viz is installed.
  * Otherwise, we should have a principled way for configuring the proxy injector; and the viz installation configures the proxy injector.

But my impression is that the _addons_ config itself is more of an implementation detail of linkerd-viz and may not actually belong in the linkerd core namespace...

**Comment by alpeb** [comment]
> * All _viz_ components are installed in a `linkerd-viz` namespace. These components no longer need special-cases for injection, as the injector can be responsible for instantiating these.

We're adding the proxy to the control plane components without the injector because of a bootstraping issue. We might avert that issue for the viz components when installed at the same time as the core ones, maybe through some Job to trigger the injection a little afterwards.

> But my impression is that the _addons_ config itself is more of an implementation detail of linkerd-viz and may not actually belong in the linkerd core namespace...

How are we gonna handle viz upgrades? Easiest for users would be through the same `linkerd upgrade`. A centralized addons config would help in this case, to know what to upgrade.

**Comment by olix0r** [comment]
This work is in progress.
