### ISSUE TITLE
Test cleanup does not work on MacOS

### ISSUE THREAD

**Issue by zaharidichev** [linkerd/linkerd2#4621]
### What is the issue?
The test cleanup script does not work on a mac

### How can it be reproduced?
Run bin/test-cleanup

### Logs, error output, etc
```
$bin/test-cleanup
cleaning up control-plane namespaces in k8s-context []
bin/test-cleanup: line 14: local: -n: invalid option
local: usage: local name[=value] ...
```

**Comment by zaharidichev** [comment]
Turns out I am using an ancient version of bash. Upgrading fixes that: 

GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin19)
Copyright (C) 2007 Free Software Foundation, Inc.

Do we have any idea what we want to  support and what not?

**Comment by alpeb** [comment]
Given most people are on Macs I agree we need to support that. Pinging our Bash guru @joakimr-axis :slightly_smiling_face:

**Comment by joakimr-axis** [comment]
> Given most people are on Macs I agree we need to support that. Pinging our Bash guru @joakimr-axis

Oh, that is a title I could not claim with a straight face. But I will do my best to help out! I checked who was the person to blame and realized `git blame` points right back at me. :-)

So what happens there is that a [nameref](https://www.gnu.org/software/bash/manual/html_node/Shell-Parameters.html) is used. Apparently, namerefs were introduce in bash 4.3. Now, I do like macs and Mac OS ("almost as good as Debian Linux", like my brother says) but was not aware bash there was that old. My apologies. Then this would call for another solution—they exist—for the code in `populate_array`. I guess it is more choosing which one of the older techniques to use.

**Comment by joakimr-axis** [comment]
...perhaps a good solution is to copy the code used in kubernetes do achieve this even for legacy bash versions?

https://github.com/kubernetes/kubernetes/blob/868efab6f59632087a47933327e1d7c5b64e3173/hack/lib/util.sh#L755-L770

**Comment by joakimr-axis** [comment]
> I guess it is more choosing which one of the older techniques to use.

I chose the technique used in the Kubernetes utility scripts for my PR.
