### ISSUE TITLE
linkerd multicluster install doesn't work with custom registry

### ISSUE THREAD

**Issue by theoriginalkien** [linkerd/linkerd2#4625]
### What is the issue?

linkerd multicluster install doesn't work with custom registry
the service-mirror image is updated correctly but the linkerd-proxy wasn't

### How can it be reproduced?

```bash
linkerd multicluster install \
    --registry something | \
    kubectl apply -f -
```

### Logs, error output, etc

![image](https://user-images.githubusercontent.com/3182992/84966340-a7deff00-b154-11ea-8220-db3f4bf030e5.png)

### Environment

- Cluster Environment: AKS
- Linkerd version: 2.8.0

### Possible solution

update the docker image registry for the `linker-proxy` to use custom value

**Comment by alpeb** [comment]
Thanks for the report @kienct89 . If you're using a custom registry for the service mirror, I suppose you'll be doing the same for the other components? If so, when you install or upgrade linkerd you can use the `--registry` flag to set up your custom registry and then all the injected proxies, included service mirror's, will use that. Do you mind explaining a bit more your scenario if this doesn't suit you?

**Comment by adleong** [comment]
The `linkerd multicluster install` and `linkerd multicluster link` commands now support the `--registry` flag.
