### ISSUE TITLE
mock-dst: Add support for file-based configuration

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#4633]
The [`mock-dst`](https://github.com/linkerd/linkerd2-mock-dst) allows us to run the proxy ad-hoc (i.e. for [testing/profiling](https://github.com/olix0r/l2-proxy-harness)). Currently, all of its configuration/state is set from the environment/CLI. However, this makes it impractical to drive updates through the system (i.e. because all config is set statically at startup).

We should extend the mock-dst controller to support watching the filesystem for updates. I think a directory structure (as opposed to a single large config object) would be preferable. And it would be ideal to support a simple yaml or json structure for encoding the discovery state (maybe even just the protobuf structures?).

Tactically, it's probably more important to start with the Get (endpoints) API.

This will be useful, as it will allow us to prototype new API features for the proxy without having to make deeper control plane changes.

**Comment by olix0r** [comment]
I don't think there's any requirement that this works outside of Linux (depending on state of file-watching crates...).

At a first glance, it looks like [tokio-inotify](https://github.com/dermesser/tokio-inotify/blob/master/Cargo.toml) may be unmaintained, as it hasn't updated to tokio-0.2. We may want to fork it and figure out the delta (and then submit PRs once we have something working). Though I think we've used it in the past and had some issues with it... @hawkw may recall.

**Comment by hawkw** [comment]
> At a first glance, it looks like [tokio-inotify](https://github.com/dermesser/tokio-inotify/blob/master/Cargo.toml) may be unmaintained, as it hasn't updated to tokio-0.2. We may want to fork it and figure out the delta (and then submit PRs once we have something working). Though I think we've used it in the past and had some issues with it... @hawkw may recall.

I believe the `tokio-inotify` crate is unmaintained because `inotify` itself [has Tokio support built in](https://docs.rs/inotify/0.8.3/inotify/struct.Inotify.html#method.event_stream), which is what we've used in the past. It looks like this has been updated to Tokio 0.2.

**Comment by zaharidichev** [comment]
> We should extend the mock-dst controller to support watching the filesystem for updates. I think a directory structure (as opposed to a single large config object) would be preferable. And it would be ideal to support a simple yaml or json structure for encoding the discovery state (maybe even just the protobuf structures?).

@olix0r So by that, do you mean watching a directory on disk that has a number of files for each name:endpoints pair that would look like, each having content similar to: 

```json
{
    "dst": "http://foo.ns.svc.cluster.local:8080",
     "endpoints":  ["127.0.0.1:1234", "127.0.0.1:1235"]
}
```

And I assume this means we can actually start with static configuration provided to the cli and then drive updates from the file system? Am i getting  that correct?

**Comment by olix0r** [comment]
@zaharidichev 

> And I assume this means we can actually start with static configuration provided to the cli and then drive updates from the file system?

I think at first we should support EITHER a static configuration OR a file-backed configuration.

> So by that, do you mean watching a directory on disk that has a number of files for each name:endpoints pair that would look like, each having content similar to:

Perhaps something like:
* CLI accepts an optional directory for discovery.
* Directory structure like `./endpoints/[authority].[suffix]`, i.e `./endpoints/foo.ns.svc.cluster.local:8080.[json|yml]`

We should never see `http://` schemes in this.

Endpoints should be able to include full metadata (identity config, authority overrides, protocol upgrading, etc). We should seriously consider just using the protobuf structs directly (with a friendlier encoding).

**Comment by zaharidichev** [comment]
Okey, got it. Thanks @olix0r

**Comment by zaharidichev** [comment]
This was solved by https://github.com/linkerd/linkerd2-mock-dst/pull/9
