### ISSUE TITLE
Service profiles should be scoped to ports

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#4639]
Currently, a service profile is assumed to apply for all ports on a service. In order to better-support services that expose multiple interfaces, we should modify service profiles so that they may be scoped to a specific port (even if we must keep the constraint that there is only one service profile per service, we should at least be able to pin it to a specific port).

Then, as the destination service is queried, it will only return profiles for requests that specify the proper service:port.

**Comment by cpackingham** [comment]
Is this a reasonable issue for a new contributor?

**Comment by olix0r** [comment]
@cpackingham I'm a bit skeptical of how useful this issue is in its current form -- I think we may opt to pursue a larger change around the ServiceProfile API after 2.10; so it may not be worth the work needed to make the change, if we're just going to deprecate the current API after it lands. In fact, I'll probably close this issue for now...

I'd recommend looking through issues tagged with [_help wanted_](https://github.com/linkerd/linkerd2/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22) -- these are _generally_ (though not always) more actionable.

Thanks for getting involved, though!
