### ISSUE TITLE
Prometheus unhealthy after installation

### ISSUE THREAD

**Issue by listenerme** [linkerd/linkerd2#4659]
## Bug Report
Old issue mentioned in **https://github.com/linkerd/linkerd2/issues/3819** still exists in new version 2.8.0

### What is the issue?

**Linkerd api is not available after the installation**. Several restart on controller, destination and prometheus required to bring the API up

Sample error:
time="2020-06-23T23:49:14Z" level=error msg="Query(max(process_start_time_seconds{}) by (pod, namespace)) failed with: server_error: server error: 503"

### How can it be reproduced?
Deploy Linkerd version 2.8.0 with linkerd-cni 2.8.0 and cert-manager 0.15.1 in AKS 1.15.11

**"linkerd stat deploy"** fails with error "Error: StatSummary API error: server_error: server error: 503"

**"linkerd check"** fails with error "Error calling Prometheus from the control plane: server_error: server error: 503"

### Logs, error output, etc

$ **kubectl -n linkerd logs -c destination linkerd-destination-65564dd64f-tkgbw**
time="2020-06-23T23:13:15Z" level=info msg="running version stable-2.8.0"
time="2020-06-23T23:13:22Z" level=info msg="waiting for caches to sync"
time="2020-06-23T23:13:22Z" level=info msg="caches synced"
time="2020-06-23T23:13:22Z" level=info msg="starting admin server on :9996"
time="2020-06-23T23:13:22Z" level=info msg="starting gRPC server on :8086"
time="2020-06-24T00:00:12Z" level=warning msg="failed to retrieve job from indexer linkerd/linkerd-heartbeat-1592956800: job.batch \"linkerd-heartbeat-1592956800\" not found"
time="2020-06-24T00:00:12Z" level=warning msg="failed to retrieve job from direct API call linkerd/linkerd-heartbeat-1592956800: jobs.batch \"linkerd-heartbeat-1592956800\" not found"

**$ kubectl -n linkerd logs linkerd-controller-7c954cf6b8-c5829 -c public-api**
time="2020-06-23T23:13:37Z" level=info msg="running version stable-2.8.0"
time="2020-06-23T23:13:38Z" level=info msg="Using cluster domain: cluster.local"
time="2020-06-23T23:13:38Z" level=info msg="waiting for caches to sync"
time="2020-06-23T23:13:38Z" level=info msg="caches synced"
time="2020-06-23T23:13:38Z" level=info msg="starting admin server on :9995"
time="2020-06-23T23:13:38Z" level=info msg="starting HTTP server on :8085"
time="2020-06-23T23:14:57Z" level=error msg="Query(sum(increase(tcp_read_bytes_total{direction=\"inbound\", namespace=\"linkerd\"}[1m])) by (namespace, deployment)) failed with: server_error: server error: 503"
time="2020-06-23T23:14:57Z" level=error msg="queryProm failed with: server_error: server error: 503"
time="2020-06-23T23:14:57Z" level=error msg="Query(histogram_quantile(0.95, sum(irate(response_latency_ms_bucket{direction=\"inbound\", namespace=\"linkerd\"}[1m])) by (le, namespace, deployment))) failed with: server_error: server error: 503"
time="2020-06-23T23:14:57Z" level=error msg="queryProm failed with: server_error: server error: 503"
time="2020-06-23T23:14:57Z" level=error msg="Query(histogram_quantile(0.5, sum(irate(response_latency_ms_bucket{direction=\"inbound\", namespace=\"linkerd\"}[1m])) by (le, namespace, deployment))) failed with: server_error: server error: 503"
time="2020-06-23T23:14:57Z" level=error msg="queryProm failed with: server_error: server error: 503"
time="2020-06-23T23:14:57Z" level=error msg="Query(sum(increase(tcp_write_bytes_total{direction=\"inbound\", namespace=\"linkerd\"}[1m])) by (namespace, deployment)) failed with: server_error: server error: 503"
time="2020-06-23T23:14:57Z" level=error msg="Query(histogram_quantile(0.99, sum(irate(response_latency_ms_bucket{direction=\"inbound\", namespace=\"linkerd\"}[1m])) by (le, namespace, deployment))) failed with: server_error: server error: 503"
time="2020-06-23T23:14:57Z" level=error msg="queryProm failed with: server_error: server error: 503"
time="2020-06-23T23:14:57Z" level=error msg="queryProm failed with: server_error: server error: 503"
time="2020-06-23T23:14:57Z" level=error msg="Query(sum(increase(response_total{direction=\"inbound\", namespace=\"linkerd\"}[1m])) by (namespace, deployment, classification, tls)) failed with: server_error: server error: 503"
time="2020-06-23T23:14:57Z" level=error msg="queryProm failed with: server_error: server error: 503"
time="2020-06-23T23:14:57Z" level=error msg="Query(sum(tcp_open_connections{direction=\"inbound\", namespace=\"linkerd\"}) by (namespace, deployment)) failed with: server_error: server error: 503"
time="2020-06-23T23:14:57Z" level=error msg="queryProm failed with: server_error: server error: 503"
time="2020-06-23T23:15:15Z" level=error msg="Query(max(process_start_time_seconds{}) by (pod, namespace)) failed with: server_error: server error: 503"

#### `linkerd check` output

```
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-cni-plugin
------------------
√ cni plugin ConfigMap exists
√ cni plugin PodSecurityPolicy exists
√ cni plugin ClusterRole exists
√ cni plugin ClusterRoleBinding exists
√ cni plugin Role exists
√ cni plugin RoleBinding exists
√ cni plugin ServiceAccount exists
√ cni plugin DaemonSet exists
√ cni plugin pod is running on all nodes

linkerd-identity
----------------
√ certificate config is valid
√ trust roots are using supported crypto algorithm
√ trust roots are within their validity period
√ trust roots are valid for at least 60 days
√ issuer cert is using supported crypto algorithm
√ issuer cert is within its validity period
‼ issuer cert is valid for at least 60 days
    issuer certificate will expire on 2020-08-02T08:06:54Z
    see https://linkerd.io/checks/#l5d-identity-issuer-cert-not-expiring-soon for hints
√ issuer cert is issued by the trust root

linkerd-api
-----------
√ control plane pods are ready
√ control plane self-check
√ [kubernetes] control plane can talk to Kubernetes
× [prometheus] control plane can talk to Prometheus
    Error calling Prometheus from the control plane: server_error: server error: 503
    see https://linkerd.io/checks/#l5d-api-control-api for hints

Status check results are ×
```

### Environment

- Kubernetes Version: 1.15.11
- Cluster Environment: AKS
- Host OS: Ubuntu
- Linkerd version: 2.8.0

### Possible solution

1) Restarting all linkerd container together helped most of the time. 
2) Sometimes linkerd-controller and linkerd-prometheus helps 
3) But this time with 2.8.0, restarting linkerd-controller and linkerd-prometheus didnt help, but restarting linkerd-destination after that worked.

**Comment by olix0r** [comment]
> Linkerd api is not available after the installation.

Can you share the details of how you installed linkerd? Did you happen to run `linkerd check --pre` beforehand?

Are there any errors emitted by the proxy? Check, for instance, `linkerd logs --control-plane-component prometheus`

Can this be reproduced reliably? Or is this potentially some kind of startup race condition?

**Comment by listenerme** [comment]
I have installed linkerd using helm both non HA and HA, same experience on both of them. I didnt run linkerd check --pre beforehand, but "linkerd check" itself come clean after several restart of the above mentioned components. During HA testing, api went available again, had to just restart linkerd-destination alone to fix the issue, but there was no error in it

Yes, its easily reproducible with helm installation, I would say 5 out of 10 times, this happens. It was the same for 2.7.0, thought it was fixed in 2.8.0

Its a critical issue since linkerd is supposed to heal itself in case of error during reboot, manual intervention is not at all desired.

Following is the logs I have seen in Prometheus initial, restarting Prometheus resolved it, but API was still unavailable 
```
**$ kubectl -n linkerd logs linkerd-prometheus-7987b64d4b-m8tch -c prometheus**
level=info ts=2020-06-23T23:13:16.683Z caller=main.go:330 msg="Starting Prometheus" version="(version=2.15.2, branch=HEAD, revision=d9613e5c466c6e9de548c4dae1b9aabf9aaf7c57)"
level=info ts=2020-06-23T23:13:16.683Z caller=main.go:331 build_context="(go=go1.13.5, user=root@688433cf4ff7, date=20200106-14:50:51)"
level=info ts=2020-06-23T23:13:16.684Z caller=main.go:332 host_details="(Linux 4.15.0-1089-azure #99~16.04.1-Ubuntu SMP Fri Jun 5 15:30:32 UTC 2020 x86_64 linkerd-prometheus-7987b64d4b-m8tch (none))"
level=info ts=2020-06-23T23:13:16.684Z caller=main.go:333 fd_limits="(soft=1048576, hard=1048576)"
level=info ts=2020-06-23T23:13:16.684Z caller=main.go:334 vm_limits="(soft=unlimited, hard=unlimited)"
level=info ts=2020-06-23T23:13:16.686Z caller=main.go:648 msg="Starting TSDB ..."
level=info ts=2020-06-23T23:13:16.686Z caller=web.go:506 component=web msg="Start listening for connections" address=0.0.0.0:9090
level=info ts=2020-06-23T23:13:16.691Z caller=head.go:584 component=tsdb msg="replaying WAL, this may take awhile"
level=info ts=2020-06-23T23:13:16.692Z caller=head.go:632 component=tsdb msg="WAL segment loaded" segment=0 maxSegment=0
level=info ts=2020-06-23T23:13:16.693Z caller=main.go:663 fs_type=EXT4_SUPER_MAGIC
level=info ts=2020-06-23T23:13:16.693Z caller=main.go:664 msg="TSDB started"
level=info ts=2020-06-23T23:13:16.693Z caller=main.go:734 msg="Loading configuration file" filename=/etc/prometheus/prometheus.yml
level=info ts=2020-06-23T23:13:16.695Z caller=kubernetes.go:190 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2020-06-23T23:13:16.696Z caller=kubernetes.go:190 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2020-06-23T23:13:16.699Z caller=kubernetes.go:190 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2020-06-23T23:13:16.700Z caller=main.go:762 msg="Completed loading of configuration file" filename=/etc/prometheus/prometheus.yml
level=info ts=2020-06-23T23:13:16.700Z caller=main.go:617 msg="Server is ready to receive web requests."
level=error ts=2020-06-23T23:13:16.701Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:333: Failed to list *v1.Node: Get https://10.0.0.1:443/api/v1/nodes?limit=500&resourceVersion=0: dial tcp 10.0.0.1:443: connect: connection refused"
level=error ts=2020-06-23T23:13:16.701Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:281: Failed to list *v1.Pod: Get https://10.0.0.1:443/api/v1/pods?limit=500&resourceVersion=0: dial tcp 10.0.0.1:443: connect: connection refused"
level=error ts=2020-06-23T23:13:16.701Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:281: Failed to list *v1.Pod: Get https://10.0.0.1:443/api/v1/namespaces/linkerd/pods?limit=500&resourceVersion=0: dial tcp 10.0.0.1:443: connect: connection refused"
level=error ts=2020-06-23T23:13:18.703Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:333: Failed to list *v1.Node: Get https://10.0.0.1:443/api/v1/nodes?limit=500&resourceVersion=0: EOF"
level=error ts=2020-06-23T23:13:18.704Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:281: Failed to list *v1.Pod: Get https://10.0.0.1:443/api/v1/pods?limit=500&resourceVersion=0: EOF"
level=error ts=2020-06-23T23:13:18.705Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:281: Failed to list *v1.Pod: Get https://10.0.0.1:443/api/v1/namespaces/linkerd/pods?limit=500&resourceVersion=0: EOF"
```

**Comment by kleimkuhler** [comment]
I think we sometimes see this in CI as well. [Here](https://pipelines.actions.githubusercontent.com/p7a3cQoVOfFGt1NRY3JcIVixtulpQevYmOxJelqxEKZRqxlSR3/_apis/pipelines/1/runs/8459/signedlogcontent/22?urlExpires=2020-06-24T19%3A15%3A15.9535349Z&urlSigningMethod=HMACV1&urlSignature=PPRcP9%2BrKHor%2BTa7D45eC00P2Wv4AWK4JH4ZX6kBKy8%3D) is an example that just happened today.

Located at the bottom:

```
..
2020-06-24T19:05:11.9872591Z linkerd-api
2020-06-24T19:05:11.9873140Z -----------
2020-06-24T19:05:37.2442075Z √ control plane pods are ready
2020-06-24T19:05:40.2989082Z √ control plane self-check
2020-06-24T19:05:40.2989894Z √ [kubernetes] control plane can talk to Kubernetes
2020-06-24T19:05:40.2991150Z × [prometheus] control plane can talk to Prometheus
2020-06-24T19:05:40.2991835Z     Error calling Prometheus from the control plane: server_error: server error: 503
2020-06-24T19:05:40.2992799Z     see https://linkerd.io/checks/#l5d-api-control-api for hints
2020-06-24T19:05:40.2993192Z 
2020-06-24T19:05:40.2993832Z Status check results are ×
2020-06-24T19:05:40.3009165Z ##[error]install_version() - linkerd check failed
2020-06-24T19:05:40.3015104Z ##[error]Process completed with exit code 1.
2020-06-24T19:05:40.3082122Z Post job cleanup.
```

**Comment by ihcsim** [comment]
> Failed to list *v1.Node: Get https://10.0.0.1:443/api/v1/nodes?limit=500&resourceVersion=0: dial tcp 10.0.0.1:443: connect: connection refused"

@listenerme I assume 10.0.0.1 is your k8s api-server. How big is your cluster in terms of nodes and VM size? Is everything in the `kube-system` namespace healthy? Try to see if you can retrieve the api-server logs; there are some info on how to do that on the Azure [doc](https://docs.microsoft.com/en-us/azure/aks/view-master-logs).
