### ISSUE TITLE
Allow mTLS and service mesh features for requests to endpoints outside cluster

### ISSUE THREAD

**Issue by plwhite** [linkerd/linkerd2#4667]
### What problem are you trying to solve?

A pod in a cluster wishes to contact an endpoint outside the service mesh, though one that is mTLS capable - perhaps another pod in another cluster, or perhaps a VM. I'd like service mesh to get involved and provide mTLS, metrics, and perhaps other features.

Examples of this use case are:

1. Protocols such as SIP over TCP, where the protocol is fundamentally end point to end point (and the service abstraction and load balancing function does not really apply). I realise that mTLS for TCP is not supported, but it is in road map.

2. High throughput applications, where we want to avoid adding a gateway (because of the high cost of TLS encryption / decryption - one encode and decode is bad enough, many is problematic).

3. Cases where the endpoints are not in Kubernetes, but mTLS capable. For example, this might be a VM with an envoy sidecar or that natively supports mTLS.

### How should the problem be solved?

My ideal would be something like the following.

1. As a prerequisite, the Linkerd service mesh must have a common trust anchor to the remote endpoints. There are some interesting wrinkles in this, but I think it is the same issue as for multi-cluster; both sides must support the other's certificates.

2. Linkerd gets some configuration that says "CIDR X is to be assumed to be TLS capable." Maybe this interacts with Service Profiles, or maybe it is just an annotation. Let's call CIDR X an `external mTLS enabled address`.

3. When the Linkerd proxy on the local (client) side receives a request, it currently checks if the remote IP is a local service or a pod, and if so it applies mTLS and other function (observability, auth, service profiles). I'd like to extend this to include any defined external mTLS enabled address.

4. The remote (server) side must accept the incoming mTLS connection and validate it. This may just work now, or it may require changes - I don't know in enough detail to be sure.

### Any alternatives you've considered?

There are several alternatives.

1. I could put a gateway in the way. That adds CPU cost, but also does not really work if I need to send traffic to a specific endpoint, not any endpoint in the service (for example, SIP).

2. I could just add mTLS support to my application. However, then I have to write that TLS verification code, manage distributing and rotating certificates, and generally do a lot of work that ideally the service mesh would do for me.

**Comment by ihcsim** [comment]
@plwhite To confirm my understanding, you are looking for a way for pods to communicate with each other across clusters, without additional gateways, right? You mentioned on [slack](https://linkerd.slack.com/archives/C89RTCWJF/p1592830231265300) that your current clusters already supports direct pod-to-pod communication, so does that mean cross-cluster service discovery already works on a flat network, without Linkerd?

While there is a case to be made for pod-to-pod traffic, I am not sure if it's just a matter of configuring some CIDR ranges via service profiles. Any thoughts on how the identity of the workloads can be communicated beforehand so both sides can validate each other (like the `m` of mtls)?

**Comment by plwhite** [comment]
@ihcsim answering your questions:

Yes, we have service discovery across clusters. The way this works varies by protocol, but it includes having a service providing that service discovery in the cluster and accessing with HTTP; combined DNS; and in protocol exchanges (SIP in particular involves sending IP addresses around all over the place in protocol messages).

In terms of identity, unsure exactly how this should work. Couple of options occur to me.

- We could just configure the two clusters to share a trust anchor (which I believe is possible and ought to just work, but you can tell me I'm wrong!)

- We could configure some sort of cross-certification. This is more flexible (since it avoids the horrors of certificate expiry and replacement having cross cluster implications). On the other hand, it may not work as is.

That would mean that the two clusters could at least validate each other's certificates etc. We'd want to consider authorization too if possible, by ensuring that the name of each service was something like a SPIFFE ID, i.e. `spiffe://cluster/namespace/serviceaccount` or something similar. To start with I'd be very happy to settle for just validating that the remote endpoint had a validly signed identity, though with auth function being added in future this probably needs some care at this point.

Thanks for engaging with this. All the rapid feedback is much appreciated.

**Comment by adleong** [comment]
Hi @plwhite!  Those three example use-cases you list are each pretty different so I wanted to give some context and ask some additional questions about them individually.

1. Protocols like SIP.  If the workload is running in the Kubernetes cluster as a stateful set then you should be able to just mesh that workload and address individual endpoints using their stable network id.  All of Linkerd's in-mesh mTLS will work.  If the workload is running outside of Kubernetes... see point number 3.

2. You are correct that our mutlicluster traffic goes through an additional gateway hop as compared to local cluster traffic.  However, this extra hop should be very low cost in terms of latency (especially compared to the network latency of going between clusters) and in terms of computation.  Our TLS encrpytion/decryption in particular is highly optimized.  Do you have any benchmarks that show a significant cost to using the gateway?

3. This falls under the category of "mesh expansion": treating things that are outside of Kubernetes as if they are in the mesh.  This is on the Linkerd roadmap, but is farther away than mTLS for TCP.  If you have a specific use-case for mesh expansion (the more specific, the better!) and can describe the protocol, network-architecture, desired mesh functionality, etc. then sharing that can help us prioritize that work.

**Comment by plwhite** [comment]
Addressing each of these in turn.

1. I agree that within the cluster direct mTLS on the TCP connection should just work. The problem comes when you have some pods within a cluster that need to communicate with entities (VMs or pods) outside the cluster using SIP, and are stuck with direct IP to IP communication because SIP is just designed to impose that. We can't change protocol without breaking interop and standards compliance.

2. I don't have good benchmarks for the cost of the extra hop, where I'm mostly concerned about CPU and memory occupancy. It could be that I'm overstating the issue though, so maybe this does not stand up.

3. I don't have enough details on what I'm trying to do here to write anything very clear just yet; might be worth me putting together a document in due course to lay out some of our constraints though. The key issue is that we have solutions that are a mix of third party software (almost entirely VMs), Kubernetes native software, and VMs that are too expensive to port to Kubernetes. Generally these just use unsecured TCP, and we are trying simultaneously to make them more cloud native and to secure all the TCP connections.

**Comment by adleong** [comment]
@plwhite yep, makes total sense.  I think what makes sense is to close this issue for now, and when you have more specific requirements to open a new issue with all of those details.  Does that work for you?

**Comment by plwhite** [comment]
I'm fine with that, thanks.
