### ISSUE TITLE
Eliminate the need to download and build different versions of Rust components

### ISSUE THREAD

**Issue by briansmith** [linkerd/linkerd2#467]
The Rust build system lets us depend on a library that internally uses an incompatible version X than the version Y that another library we depend on uses (or Conduit itself) . This generally works out OK, except it means we have to download and build multiple versions of these libraries to build Conduit. This increases dependency download times, compile times, and the resulting object code size of the proxy. The build time of the proxy is already pretty atrocious, so let's try to eliminate this waste.

For examples of how to do this, see the following PRs in this repo: #465, #451, #450, #445.

In some cases, this requires updating dependencies too; see these for examples:

https://github.com/carllerche/h2/pull/226, https://github.com/danburkert/prost/pull/78, https://github.com/tower-rs/tower/pull/52 for #445. (We still need to update the h2 and power dependencies in this repo to take advantage of those changes.)

The script I'm using to find duplicate dependencies is (Bourne shell experts: don't shoot me):
```sh
cat Cargo.lock | grep "^ \"" | cut -d " " -f 2,3 | sort | uniq | cut -d " " -f 1 | uniq -c | grep -v " 1"
```
Then I look in Cargo.lock to find out which crates need to be updated.

Presently (without #445 and #466 and the related updates for each) the output is:
```
      2 "log
      2 "ordermap
      2 "quote
      2 "rand
      2 "slab
      2 "syn
      2 "unicode-xid
      2 "winapi
```

**Comment by briansmith** [comment]
The case of `ordermap` is special because `ordermap` was renamed to `indexmap`, so any occurance of `ordermap` in Cargo.lock is a bug.

@carllerche @seanmonstar When you can, can you please try to make the underlying libraries (Tokio, Tower, Hyper) are using the latest version of the dependencies explicitly listed in the previous comment (log, indexmap, quote, rand, slab, syn, unicode-xid, winap) at least before cutting the next releases? I filed a bunch of PRs but it is a bit daunting to update every single one.

(I don't actually know how much this will help build times. I'm doing it speculatively.)

**Comment by olix0r** [comment]
> The case of ordermap is special because ordermap was renamed to indexmap, so any occurance of ordermap in Cargo.lock is a bug.

ordermap 0.4.1 was released on Feb 14, so this is an extremely recent change. It's not really a "bug" if we're on a 1-week-old version of a lib, imo.

**Comment by briansmith** [comment]
I filed https://github.com/withoutboats/failure_derive/issues/12 as I don't know how to write a PR for failure_derive to update its `syn` and `quote`.

The remaining one that seems most under our control is `slab`. tokio-core is using 0.4, while tokio-timer and mio are using 0.3. Unfortunately it looks like updating mio to use slab 0.4 is non-trivial.

**Comment by briansmith** [comment]
> ordermap 0.4.1 was released on Feb 14, so this is an extremely recent change. It's not really a "bug" if we're on a 1-week-old version of a lib, imo.

The original issue is that we were already depending on two versions of ordermap that were older than 0.4.1. In order to fix that, we have to update dependencies. In general, my approach is to update dependencies to the latest version of the lib, which in this case meant using indexmap instead of ordermap, due to the renaming.

**Comment by briansmith** [comment]
>       2 "log
>       2 "ordermap

Will be fixed by PR #507 and PR #508.

>       2 "rand

Fixed in https://github.com/runconduit/conduit/pull/495

>       2 "slab

Will be fixed if/when https://github.com/carllerche/mio/pull/824 is merged and we update mio.

>       2 "quote
>       2 "syn
>       2 "unicode-xid

Will be fixed arfter https://github.com/rust-lang-nursery/failure/pull/179 is merged and we update failure_derive accordingly. (withoutboats/failure_derive#12 tracks this.)

>       2 "winapi

winapi 0.3 isn't good enough since the current version of ws2_32-sys uses 0.2 and the next version of ws2_32-sys uses winapi 0.4. This also requires changes to every other crate that depends on winapi to use 0.4, as they are all currently using 0.3 or 0.2. :( So, it will be a while before winapi gets de-dup'd.

**Comment by Eijebong** [comment]
FTR, There is no winapi 0.4 yet, the latest version is still 0.3.4.

**Comment by briansmith** [comment]
> > 2 "quote
> >  2 "syn
>  > 2 "unicode-xid
>
> Will be fixed arfter rust-lang-nursery/failure#179 is merged and we update failure_derive accordingly. (withoutboats/failure_derive#12 tracks this.)

Actually https://github.com/danburkert/prost/pull/87 will fix this by removing the `failure_derive` dependency completely.

**Comment by briansmith** [comment]
> FTR, There is no winapi 0.4 yet, the latest version is still 0.3.4.

Hmm...yeah, I am not sure why I thought that. Maybe winapi 0.3 is good enough? Regardless, we have a lot of dependencies using winapi 0.2 that would need to be updated (as can be seen in Cargo.lock), and each of those updates requires a bunch of tedious, but not difficult, work. I know on Windows, winapi is one of the slowest parts of the build, but I'm not sure that's the case on Linux, since presumably we download it but never actually try to build it.

**Comment by Eijebong** [comment]
Well most of your winapi 0.2 dependencies are there because of mio which has a PR for it but has to be released

**Comment by briansmith** [comment]
> Well most of your winapi 0.2 dependencies are there because of mio which has a PR for it but has to be released

I see that mio has a "0.7" branch that has winapi 0.3 on it, while the master has winapi 0.2. So, the winapi part is blocked on mio 0.7 being released, it seems.

**Comment by carllerche** [comment]
Yes, the winapi crate is included in Mio's public dependencies. This has been fixed in the 0.7 branch.

**Comment by briansmith** [comment]
In the last two weeks, we've eliminated 41 crate dependencies from Conduit and added 1 crate dependency, if my counting is correct.

Now there is only one duplicate version dependency:

```sh
$ cat Cargo.lock | grep "^ \"" | cut -d " " -f 2,3 | sort | uniq | cut -d " " -f 1 | uniq -c | grep -v " 1"
2 "winapi
```

@carllerche When do you estimate mio 0.7 will be released?

The next steps for this issue:
* Stop hiding Cargo.lock in the GitHub PR review interface, so that we can be more conscious of what we're adding (PR #551).
* Add some check to CI to verify that we don't unintentionally add any new duplicate dependencies (TODO).

**Comment by Eijebong** [comment]
@briansmith For the last part you could use  [servo-tidy](https://github.com/servo/servo/tree/master/python/tidy). The config file used in servo is [there](https://github.com/servo/servo/blob/master/servo-tidy.toml).

**Comment by briansmith** [comment]
indexmap 1.0 has been released and we will (as of later today) depend on 1.0 and 0.4.1. We should clean that up eventually.

**Comment by briansmith** [comment]
> Now there is only one duplicate version dependency:
> 
> ```sh
> $ cat Cargo.lock | grep "^ \"" | cut -d " " -f 2,3 | sort | uniq | cut -d " " -f 1 | uniq -c | grep -v " 1"
> 2 "winapi
> ```

The remaining duplicate, winapi, now will be fully resolved when we can update to the newest, not-yet-released versions of these crates: iovec, mio, miow, net2. My understanding is that the necessary mio version is actually on a branch other than the master branch of the mio repo, and is a major version bump.

However, with #593 + #596 + #597 we now already avoid winapi and similar Windows-only crates completely on non-Windows platforms, especially in the container image builds, so the duplicate winapi dependency is truly a minor issue now.

**Comment by briansmith** [comment]
Today:
```
$ cat Cargo.lock | grep "^ \"" | cut -d " " -f 2,3 | sort | uniq | cut -d " " -f 1 | uniq -c | grep -v " 1

      2 "num-traits
      2 "quote
      2 "rand
      2 "syn
      2 "unicode-xid
      2 "winapi
```

**Comment by olix0r** [comment]
@seanmonstar 

> rand:
>   0.4: conduit-proxy, quickcheck, prost-build (via tempdir), tokio-threadpool, tower-balance

FYI, tower-balance uses rand 0.5 on master (and we will depend on this version once #1080 lands)
