### ISSUE TITLE
Unable to have ignoreOutboundPorts in helm chart propagate to injected pods

### ISSUE THREAD

**Issue by lundbird** [linkerd/linkerd2#4679]
### What is the issue?
Using a helm3 install of linkerd with the `values.global.proxyInit.ignoreOutboundPorts` set will not have the values propagated to injected pods.

### How can it be reproduced?

Installing linkerd with several ignoreOutboundPorts set.
```
helm install linkerd2 \                                                                                   
  --set-file global.identityTrustAnchorsPEM=ca.crt \
  --set-file identity.issuer.tls.crtPEM=issuer.crt \
  --set-file identity.issuer.tls.keyPEM=issuer.key \
  --set identity.issuer.crtExpiry=$exp \
--set-string 'global.proxyInit.ignoreOutboundPorts=442\,443\,444\,445' \
linkerd/linkerd2
```
from any of the linkerd control plane pods:
```   
    - --outbound-ports-to-ignore
    - 443,442,443,444,445
```
from linkerd-config configmap:
```
      "ignoreOutboundPorts":[{"port":442},{"port":443},{"port":444},{"port":445}],
```
from any injected pods which are unable to start
```
    - --outbound-ports-to-ignore
    - ',,,'
```

Additionally an installation with one outbound port set:
```
helm install linkerd2 \                                                                                   
  --set-file global.identityTrustAnchorsPEM=ca.crt \
  --set-file identity.issuer.tls.crtPEM=issuer.crt \
  --set-file identity.issuer.tls.keyPEM=issuer.key \
  --set identity.issuer.crtExpiry=$exp \
--set-string 'global.proxyInit.ignoreOutboundPorts=443
linkerd/linkerd2
```
from linkerd-config configmap:
```
      "ignoreOutboundPorts":[{"port":443}]
```

Results in no `--outbound-ports-to-ignore` flag in injected pods.

#### `linkerd check` output
All clean

### Environment
Reproduced by setting up a new cluster in Kind, installing linkerd with the helm command, injecting namespace `default`, creating an nginx deployment in the default namespace, then verifying proxyInit args.

- Kubernetes Version: 1.14.10
- Cluster Environment: (GKE, AKS, kops, ...) Kind
- Host OS: MacOS
- Linkerd version: 2.8.1-stable

### Possible solution
The strings seem to be getting removed before templated with the helm chart, and only on newly injected pods. https://github.com/linkerd/linkerd2/blame/master/charts/partials/templates/_proxy-init.tpl. So possibly an issue with the mutating webhook config?

**Comment by ihcsim** [comment]
Can confirm that this is a bug. This can be easily reproduced with `linkerd inject --manual`:

```
      initContainers:
      - args:
        - --incoming-proxy-port
        - "4143"
        - --outgoing-proxy-port
        - "4140"
        - --proxy-uid
        - "2102"
        - --inbound-ports-to-ignore
        - 4190,4191
        - --outbound-ports-to-ignore
        - ',,,'
```
