### ISSUE TITLE
`linkerd check` will hang on HA installations when pods cannot be scheduled onto a node

### ISSUE THREAD

**Issue by kleimkuhler** [linkerd/linkerd2#4680]
## Bug Report

`linkerd check` hangs on HA installations when there are pods that cannot be
scheduled.

`linkerd stat -n linkerd pods` will fail instantly, pointing to the fact that
there are no nodes available for certain pods.

Should `linkerd check` also instantly fail with the same error, instead of
waiting for these pods to be scheduled?

### How can it be reproduced?

Install a two node KinD cluster.

`test.yaml`:

```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
- role: worker
```

```bash
❯ bin/kind create cluster --config test.yaml
..
❯ linkerd install --ha |kubectl apply -f -
..
```

`linkerd check` will now hang until the third replicas can be scheduled:

```bash
❯ linkerd check
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
/ waiting for check to complete 
```

`linkerd stat -n linkerd pod` will instantly fail:

```
❯ linkerd stat -n linkerd pod
Cannot find Linkerd: linkerd-controller-685dc794ff-r9mbf: 0/3 nodes are available: 1 node(s) had taint {node-role.kubernetes.io/master: }, that the pod didn't tolerate, 2 node(s) didn't match pod affinity/anti-affinity, 2 node(s) didn't satisfy existing pods anti-affinity rules.
    linkerd-destination-68c4c8fb64-mtgzz: 0/3 nodes are available: 1 node(s) had taint {node-role.kubernetes.io/master: }, that the pod didn't tolerate, 2 node(s) didn't match pod affinity/anti-affinity, 2 node(s) didn't satisfy existing pods anti-affinity rules.
    linkerd-identity-55bb549b59-tnc78: 0/3 nodes are available: 1 node(s) had taint {node-role.kubernetes.io/master: }, that the pod didn't tolerate, 2 node(s) didn't match pod affinity/anti-affinity, 2 node(s) didn't satisfy existing pods anti-affinity rules.
    linkerd-proxy-injector-57bf8d46f4-5mpnc: 0/3 nodes are available: 1 node(s) had taint {node-role.kubernetes.io/master: }, that the pod didn't tolerate, 2 node(s) didn't match pod affinity/anti-affinity, 2 node(s) didn't satisfy existing pods anti-affinity rules.
    linkerd-sp-validator-7d98ddd687-pbjzp: 0/3 nodes are available: 1 node(s) had taint {node-role.kubernetes.io/master: }, that the pod didn't tolerate, 2 node(s) didn't match pod affinity/anti-affinity, 2 node(s) didn't satisfy existing pods anti-affinity rules.
    linkerd-tap-7d64cd67c4-lsrfj: 0/3 nodes are available: 1 node(s) had taint {node-role.kubernetes.io/master: }, that the pod didn't tolerate, 2 node(s) didn't match pod affinity/anti-affinity, 2 node(s) didn't satisfy existing pods anti-affinity rules.
Validate the install with: linkerd check
```

**Comment by kleimkuhler** [comment]
This is more of a question about the behavior that we want here, but I find it surprising that `linkerd check` hangs and `linkerd stat` points to the actual issue with my installation.

**Comment by grampelberg** [comment]
We should totally notify if pods are unschedulable, I suspect the reason it is working with `stat` is related to when the command's run.

I'd like for `stat` to only check for its dependencies (eg prometheus and one controller?).

**Comment by kleimkuhler** [comment]
@grampelberg #4675 is already changing `stat` to not fail because of this. Testing that is where I noticed this!

**Comment by ihcsim** [comment]
Feels like `check` hangs because it's waiting for responses from k8s, which itself is waiting for the remaining replicas to be scheduled. By default, `check` has a 5 minute `wait` duration. Maybe we can either introduce an internal timeout to fail sooner, or reduce the default `wait` duration.

**Comment by zaharidichev** [comment]
@ihcsim @kleimkuhler I think what we need here is to have an immediate feedback so it does not look like it is hangind. How about making that check have `surfaceErrorOnRetry: true`. That should at least print information about the problem.. Otherwise the current behaviour seems correct to me...

**Comment by kleimkuhler** [comment]
@zaharidichev Yep I think that would be best. I understand why we don't fail early on the checks today, so it would be helpful to at least communicate that back to the user that a check is being retried for a certain reason.

**Comment by zaharidichev** [comment]
Perfect, I will do that :)

**Comment by ihcsim** [comment]
It looks to me that there is an already internal connection timeout of 30 seconds on the healthcheck client in the [code](https://github.com/linkerd/linkerd2/blob/aea541d6f9bf1b2c2b759918f93b8bf3b3ec5343/pkg/healthcheck/healthcheck.go#L199). Is that not working?

To confirm, with the change in #4683, `check` will still hang until `wait` times out. But at least, it will show the reasons why it's hanigng, right?

**Comment by siggy** [comment]
This may be related, but if not I can file a separate issue, we're seeing similar behavior with `linkerd-check` on evicted pods. It doesn't necessarily hang, but we have many (10s) of evicted pods, and `linkerd check` spends time trying to connect to each one. This is on `stable-2.8.1` with `--ha`:

```bash
$ linkerd check --proxy --verbose
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

...

linkerd-data-plane
------------------
√ data plane namespace exists
DEBU[0090] Making gRPC-over-HTTP call to [http://localhost:55991/api/v1/ListPods] []
DEBU[0090] Response from [http://localhost:55991/api/v1/ListPods] had headers: map[Content-Type:[application/octet-stream] Date:[Mon, 29 Jun 2020 18:45:39 GMT]]
DEBU[0090] gRPC-over-HTTP call returned status [200 OK] and content length [-1]
DEBU[0090] Retrying on error: The "[NS]/pushgateway-54cc9678-pk22j" pod is not running
E0629 11:45:39.538935   23762 portforward.go:385] error copying from local connection to remote stream: read tcp6 [::1]:55991->[::1]:56495: read: connection reset by peer
| waiting for check to complete DEBU[0095] Making gRPC-over-HTTP call to [http://localhost:55991/api/v1/ListPods] []
| waiting for check to complete DEBU[0096] Response from [http://localhost:55991/api/v1/ListPods] had headers: map[Content-Type:[application/octet-stream] Date:[Mon, 29 Jun 2020 18:45:44 GMT]]
DEBU[0096] gRPC-over-HTTP call returned status [200 OK] and content length [-1]
```

**Comment by zaharidichev** [comment]
> It looks to me that there is already an internal connection timeout of 30 seconds on the healthcheck client in the code. Is that not working?

There is no connection timeout happening so I am not sure this should actually kick in. It is just a condition not being met

> To confirm, with the change in #4683, check will still hang until wait times out. But at least, it will show the reasons why it's hanging, right?

@ihcsim That is correct
