### ISSUE TITLE
nodeSelectors not propogated to add-ons

### ISSUE THREAD

**Issue by Pothulapati** [linkerd/linkerd2#4687]
### What is the issue?

Currently we do not propogate `nodeSelectors` to add-ons like `grafana` which are considered to be part of the control-plane. Same with `tolerations` in #4626 . Should we consider them global fields and propagate them to sub-charts? As most times users would expect that all their control-plane components (including extensions) run with the same custom configration.

Currently, `nodeSelectors` can be applied as a `add-on` sub-field with Grafana directly and Linkerd2's `nodeSelectors` are not propogated.

### How can it be reproduced?

`nodeSelectors` are not applied to `linkerd-grafana` when using with Helm.

### Logs, error output, etc

(If the output is long, please create a [gist](https://gist.github.com/) and
paste the link here.)

#### `linkerd check` output

```text
your output here ...
```

### Environment

- Kubernetes Version:
- Cluster Environment: (GKE, AKS, kops, ...)
- Host OS:
- Linkerd version:

### Possible solution

Propogate `nodeSelectors`

**Comment by ihcsim** [comment]
This sounds like a bug to me. The Grafana template includes the `linkerd.node-selector` partial template, but it's not getting set as expected. Whether we want add-ons to inherit the node selectors of the core control plane feels like another legit discussion. I think we should fix this. Any idea how much effort is required to change this Helm variable to a global one? I know it's easy to change the Helm chart, just not sure about the Go code.

**Comment by Pothulapati** [comment]
@ihcsim This actually works with the CLI, as we re-use all the `values.yaml` even with add-ons but does not work with Helm as thats not the case. 

The change should not be a hard one i.e to move `nodeSelectors` to `Global` but that means that we are making it inherit nodeselectors from the core control-plane right?I mean they can always override it by setting their own using add-on fields!

**Comment by ihcsim** [comment]
For now, we should make the Helm experience consistent with the CLI.
