### ISSUE TITLE
Rotating trust anchor with automatic control plane tls didn't work

### ISSUE THREAD

**Issue by andyyaldoo** [linkerd/linkerd2#4711]
### What is the issue?

I was following the steps outlined [here](https://linkerd.io/2/tasks/manually-rotating-control-plane-tls-credentials/) and didn't quite succeed. The `linkerd check` was fine until I do `linkerd upgrade --identity-trust-anchors-file=./bundle.crt | k apply -f -`. I've also replaced the `linkerd-trust-anchor` tls secret with the bundle.crt and regenerate the `linkerd-identitiy-issuer` tls secret

### How can it be reproduced?

1. Install linkerd
1. Generate new trust anchor 
```
step certificate create identity.linkerd.cluster.local ca-new.crt ca-new.key --profile root-ca --no-password --insecure
```
1.. Bundle with the old trust anchor
```
step certificate bundle ca-new.crt original-trust.crt bundle.crt
```
1. Run `linkerd upgrade --identity-trust-anchors-file=./bundle.crt | k apply -f -`
1. Update `linkerd-trust-anchor` tls secret
```
k create secret tls linkerd-trust-anchor --cert=bundle.crt --key=ca-new.key --namespace=linkerd
```
1. Delete `linkerd-identitiy-issuer` secret so that it will be recreated by Certficiate with new trust-anchor
1. `linkerd check`

#### `linkerd check` output

```text
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-identity
----------------
× certificate config is valid
    IdentityContext.TrustAnchorsPem does not match ca.crt in linkerd-identity-issuer
    see https://linkerd.io/checks/#l5d-identity-cert-config-valid for hints

Status check results are ×
```

### Environment

- Kubernetes Version: 1.15
- Cluster Environment: EKS
- Host OS: 
- Linkerd version: 2.8.1

### Additional context

1. I generated my own trust anchor (following [this](https://linkerd.io/2/tasks/automatically-rotating-control-plane-tls-credentials/)) and use cert-manager to manage the intermediate certificate (following [this](https://linkerd.io/2/tasks/automatically-rotating-control-plane-tls-credentials/))
2. Although, the `linkerd check` failed, I've confirmed that within-cluster communications and multi-cluster communications still works

**Comment by ihcsim** [comment]
Can you compare the `data.global.trustAnchorsPem` in the `linkerd-config` configmap and that found in your `linkerd-trust-anchor` secret? `step certificate inspect [--bundle]` will let you see the details of the certs. I wonder if the ordering of the bundled certs is off.
