### ISSUE TITLE
nginx ingress doesn't work

### ISSUE THREAD

**Issue by akamenev** [linkerd/linkerd2#4715]
### What is the issue?
Nginx rules don't work as expected in a multi-cluster setup

### How can it be reproduced?
1. Setup 2 clusters according to the Getting Started guide - https://linkerd.io/2/tasks/multicluster/
2. Create 'tripsinsights' namespaces for the app in both clusters
3. Deploy 3 microservices to 'west' cluster and 2 to 'east' cluster
4. Install nginx-ingress controller with helm
```bash
kubectl create ns ingress

helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
helm install inginx ingress-nginx/ingress-nginx --namespace ingress \
                                                --set controller.podAnnotations."linkerd\.io/inject"=enabled \
                                                --set controller.service.annotations."mirror\.linkerd\.io/gateway-name"=linkerd-gateway \
                                                --set controller.service.annotations."mirror\.linkerd\.io/gateway-ns"=linkerd-multicluster
```
5. Deploy [ingress manifest](https://gist.github.com/akamenev/1b825fa594bcbce9d115ff23ef868bce)

### Logs, error output, etc

Ingress works for services located in the same cluster but doesn't work for services in the second cluster (*-east)
If you look at linkerd-proxy logs in the ingress controller:
```text
...
[  1233.799920560s]  WARN outbound:accept{peer.addr=10.240.0.47:60974}:source{target.addr=55.55.55.55:4143}: linkerd2_app_core::errors: Failed to proxy request: error trying to connect: request timed out
[  1234.38695988s]  WARN outbound:accept{peer.addr=10.240.0.47:33510}:source{target.addr=55.55.55.55:4143}: linkerd2_app_core::errors: Failed to proxy request: error trying to connect: request timed out
[  1234.148158500s]  WARN outbound:accept{peer.addr=10.240.0.47:33522}:source{target.addr=55.55.55.55:4143}: linkerd2_app_core::errors: Failed to proxy request: error trying to connect: request timed out
...
```
At the same time direct call from within ingress-controller works
```bash
kubectl exec -n ingress -it inginx-ingress-nginx-controller-958db7795-ffcdd -- /bin/bash
bash-5.0$ curl http://service-east.namespace.svc.cluster.local
```

All other services that need to connect to service in a different cluster work fine as well. The problem is with ingress only.

#### `linkerd check` output

```text
Status check results are √
```

### Environment

- Kubernetes Version: 1.16.9
- Cluster Environment: AKS
- Host OS: Ubuntu 16.04
- Linkerd version: Client version: stable-2.8.1 Server version: stable-2.8.1

**Comment by ihcsim** [comment]
@zaharidichev Any thoughts on this one?

**Comment by cpretzer** [comment]
@akamenev thanks for trying multicluster out. Did you set up a TrafficSplit resource for the service? I know that seems like a simple step, so that's my first thought.

**Comment by zaharidichev** [comment]
@akamenev I am not sure what you are trying to do. If you want to route traffic from your ingress to an exported service, why are you exporting the ingress service? Why dont you simply. 

1. Export the services you need
2. Mesh the infress controller and configure it to work with Linkerd
3. Setup the rules. 

Again. I have not tried that myself, but in theory it should work.

**Comment by zaharidichev** [comment]
I will try that myself later today and verify

**Comment by zaharidichev** [comment]
@akamenev That looks exactly like https://github.com/kubernetes/ingress-nginx/issues/5198 and I suspect is a bug in the nginx ingress controller. I tried running the dev version and still could not get that resolved. As advised, when there is a hostname in the rules, the problem goes away.  Will comment on the issue

I am stil unclear though why you are exporting the controller? I am not sure this is needed for what you are trying to do.

**Comment by akamenev** [comment]
It looks like the problem might be related to some headers, I am not sure if this is the desired behavior. I've added the 'host' section with a proper domain to the ingress manifest and it works. In the original setting, I was using Public IP directly.

**Comment by ihcsim** [comment]
>  In the original setting, I was using Public IP directly.

@akamenev The `host` field needs to the a FQDN, per the K8s [docs](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#ingressrule-v1beta1-networking-k8s-io).

**Comment by akamenev** [comment]
It is an FQDN, but at the same time, the host field is optional. You can choose to not specify it, and that's what I meant by using Public IP

**Comment by ihcsim** [comment]
In this case, if the host field isn't specified, then you will run into https://github.com/kubernetes/ingress-nginx/issues/5198. Sounds like we can close this issue now?
