### ISSUE TITLE
Confusion between linkerdVersion and controllerImageVersion

### ISSUE THREAD

**Issue by Pothulapati** [linkerd/linkerd2#4720]
## Bug Report

Currently there are two variables i.e `linkerdVersion` and `controllerImageVersion` that are used as control-plane image version tags as `{{default .Values.global.linkerdVersion .Values.global.controllerImageVersion}}`

I don't exactly understand why we would need two of them and I see that `controllerImageVersion` is not set with Helm and we use that for CLI and tests especially.

### What is the issue?

This creates a lot of confusion for add-ons as now we need to add one more image tag vairable where users can set their own image tag.

### Logs, error output, etc

(If the output is long, please create a [gist](https://gist.github.com/) and
paste the link here.)

#### `linkerd check` output

```text
your output here ...
```

### Environment

- Kubernetes Version:
- Cluster Environment: (GKE, AKS, kops, ...)
- Host OS:
- Linkerd version:

### Possible solution

Use one version tag everywhere with images, so that we can clean this up, and make it more simpler?

**Comment by ihcsim** [comment]
Will it make sense to decouple the add-on image version from the control plane image version?

**Comment by olix0r** [comment]
@alpeb Do you recall the history of these values? Is this fallout from supporting the proxy version override?

@Pothulapati I think we should either document what we have or simplify it. But you're probably in the best place to figure out the path forward...

**Comment by alpeb** [comment]
`linkerdVersion` is a placeholder that gets replaced in `values.yaml` at build-time with the real version. It definitely makes sense to use it and get rid of `controllerImageVersion`!

**Comment by Pothulapati** [comment]
Hmm, So, Currently `controllerImageVersion` can be used to override the image tag of all the control-plane components but I don't see it differing from `linkerdVersion` in most cases. and this overriding can only be performed through Helm as there is no relevant cli flag for this.

Are there any use-cases where folks are using image tags that is different from `linkerdVersion`? Even with private registries where they would have a different registry, I don't think users are using a different image tag. If thats the case, then it makes sense to get rid of `controllerImageVersion`

**Comment by ihcsim** [comment]
Sounds like we can get rid of `controllerImageVersion`, and mention this change in the release notes.

**Comment by Pothulapati** [comment]
Okay, So I was able to remove `controllerImageVersion` but that would mean that users **can't choose other image tag for control-plane components without messing up linkerdVersion everywhere** as they would need to use `linkerdVersion` for that then. I think being able to override control-plane image tags without changing `linkerdVersion` everywhere seems like a normal use-case.

For the grafana add-on, I updated the code now to have 3 conditions and choose image tag based on the preference in #4755
