### ISSUE TITLE
destination: Handle IP lookups dynamically

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#4743]
In order to handle the case where a client uses a service IP before it has been made visible to the destination controller, we should support lazily updating IP addresses as the corresponding service address is discovered/lost/etc

**Comment by grampelberg** [comment]
@kleimkuhler is this taken care of, or would we need to do more work?

**Comment by kleimkuhler** [comment]
@grampelberg No this is not done yet. I have not come back to this for a bit, but still on my radar.

**Comment by olix0r** [comment]
For this, I think we need to close the stream when a pod is terminated so that the proxy has to re-resolve the address.
