### ISSUE TITLE
HA: Relaxing webhook failure policy still triggers check warnings

### ISSUE THREAD

**Issue by Abrishges** [linkerd/linkerd2#4754]
## Bug Report
When linkerd is installed in HA mode we have to add  `config.linkerd.io/admission-webhooks=disabled` label in `kube-system `namespace to prevent linkerd to get in the way of system critical workload. However every time I add the label, AKS removes all annotations added in this namespace as AKS team manage the namespace.  The other option  is to change webhook policy in values-ha.yaml file from `fail` to `Ignore`. However After loosing linkerd webhook policy by editing the `linkerd-proxy-injector-webhook-config` mutating webhook configuration, Linkerd check still thinks that the `config.linkerd.io/admission-webhooks =disable `annotation is still needed. 

### What is the issue?
When linkerd is installed in `HA mode` we have to add  `config.linkerd.io/admission-webhooks=disabled` in `kube-system` namespace to prevent linkerd to get in the way of system critical workload.  In HA mode, the admission webhooks use a stricter policy, to ensure uninjected workloads can't enter the cluster. We can also loosen the webhook policy by editing the `linkerd-proxy-injector-webhook-config` mutating webhook configuration, and set the `failurePolicy` to `Ignore`. After change is applied `linkerd check ` still thinks that the `config.linkerd.io/admission-webhooks=disable `annotation is still needed

### How can it be reproduced?
1.	Install linkerd in **HA Mode**
2.	Look for the **MutatingWebookConfiguration** resource in the [value-ha.YAML](https://github.com/linkerd/linkerd2/blob/aea541d6f9bf1b2c2b759918f93b8bf3b3ec5343/charts/linkerd2/values-ha.yaml#L59)  and set it to `ignore`
3.	Apply the change
4.	Run `linkerd check `
After change is applied` linkerd check` still thinks admission webhooks disable annotation is needed
```
‼ pod injection disabled on kube-system
    kube-system namespace needs to have the label config.linkerd.io/admission-webhooks: disabled if HA mode is enabled
    see https://linkerd.io/checks/#l5d-injection-disabled for hints
```
5.	Checked the policy in webhook `**ConfigMap**`, `linkerd-proxy-injector-webhook-config` to make sure, it is set to Ignore

### Logs, error output, etc

```
‼ pod injection disabled on kube-system
    kube-system namespace needs to have the label config.linkerd.io/admission-webhooks: disabled if HA mode is enabled
    see https://linkerd.io/checks/#l5d-injection-disabled for hints
```

#### `linkerd check` output

```text
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-identity
----------------
√ certificate config is valid
√ trust roots are using supported crypto algorithm
√ trust roots are within their validity period
√ trust roots are valid for at least 60 days
√ issuer cert is using supported crypto algorithm
√ issuer cert is within its validity period
√ issuer cert is valid for at least 60 days
√ issuer cert is issued by the trust root

linkerd-api
-----------
√ control plane pods are ready
√ control plane self-check
√ [kubernetes] control plane can talk to Kubernetes
√ [prometheus] control plane can talk to Prometheus
√ tap api service is running

linkerd-version
---------------
√ can determine the latest version
‼ cli is up-to-date
    is running version 2.7.1 but the latest stable version is 2.8.1
    see https://linkerd.io/checks/#l5d-version-cli for hints

control-plane-version
---------------------
‼ control plane is up-to-date
    is running version 2.7.1 but the latest stable version is 2.8.1
    see https://linkerd.io/checks/#l5d-version-control for hints
√ control plane and cli versions match

linkerd-ha-checks
-----------------
‼ pod injection disabled on kube-system
    kube-system namespace needs to have the label config.linkerd.io/admission-webhooks: disabled if HA mode is enabled
    see https://linkerd.io/checks/#l5d-injection-disabled for hints

Status check results are √
```

### Environment

- Kubernetes Version:   **v1.16.9**
- Cluster Environment:  **AKS**
- Host OS:  **Ubuntu 16.04** 
- Linkerd version:  **2.7.1**

### Possible solution
I think ` Linkerd check` code might need to check if either `admission-webhooks` policy is set to Ignore or `kube-system` namespace labeled with `config.linkerd.io/admission-webhooks: disabled`

**Comment by ihcsim** [comment]
We should update `check` to perform the `kube-system` namespace annotation check based on the webhook failure policy, not the HA settings.

**Comment by rajatjindal** [comment]
setting `failurePolicy` to `ignore` will ignore errors (if any) while injecting proxy sidecar (per doc [here](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#failure-policy)), which means the pods in other namespace can come up without proxy sidecar (in case of webhook error) and cause more issues.

the selector on webhook currently is

```
  namespaceSelector:
    matchExpressions:
    - key: config.linkerd.io/admission-webhooks
      operator: NotIn
      values:
      - disabled
```

which means (in this case, where AKS is removing those labels), will still get the sidecar injected (or atleast tried to be injected).

Please correct me if I am wrong. I am very new to Linkerd and so there is a good chance i am missing something here.

**Comment by ihcsim** [comment]
@rajatjindal If AKS removed the `config.linkerd.io/admission-webhooks` label from the namespace, then the workloads will only be injected if they are annotated with the `linkerd.io/inject: enabled` annotation. If the annotations are not present, or set to `linkerd.io/inject: disabled` then auto-injection won't happen.

**Comment by zaharidichev** [comment]
@ihcsim I have submitted a PR for that. However I am not entirely convinced that this is the right approach. Isn't this too much of a coarse grained approach. What are the implications of setting this failure policy to `Ignore` in HA scenarios. I am not a fan of too many knobs, but perhaps we can add a flag to disable this check?

**Comment by ihcsim** [comment]
> What are the implications of setting this failure policy to Ignore in HA scenarios.

Same behaviour as non-HA mode. We have an issue at https://github.com/linkerd/website/issues/772#issuecomment-662732262 to update the HA doc with these details. 

> I am not a fan of too many knobs, but perhaps we can add a flag to disable this check?

IMO a flag is just another knob. Also, it's not just a matter of `linkerd check` failing. In environment with background reconcilers, users have to set the `failurePolicy` to `Ignore`. Otherwise during restarts, the webhook will try to inject the proxies into critical system workloads like those in `kube-system`. And if the webhooks are simultaneously down, then these workloads won't come up.

I am open to other suggestions though.

**Comment by ihcsim** [comment]
>  Otherwise during restarts, the webhook will try to inject the proxies 

Correction: the k8s api-server will try to call the webhooks.
