### ISSUE TITLE
check --multicluster hangs indefinitely

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#4772]
### What is the issue?

If multicluster is not installed, but you run `check --multicluster`, it will hang indefinitely. It should error out saying multicluster is not installed.

### How can it be reproduced?

Run `check --multicluster` when the `linkerd-multicluster` namespace does not exist.

**Comment by adleong** [comment]
This command no longer hangs in this scenario, but the `--multicluster` flag is incorrectly ignored.  https://github.com/linkerd/linkerd2/pull/4817 will fix that.
