### ISSUE TITLE
Debug Sidecar : Unable to chose CPURequest and MemoryRequest 

### ISSUE THREAD

**Issue by BaudouinH** [linkerd/linkerd2#4786]
## Feature Request

Being able to choose the CPURequest and the MemoryRequest for the debug sidecar

### What problem are you trying to solve?

I'm trying to use the debug sidecar on a cluster that requests containers to have these two values to be explicitly written, in order to let the containers be created.

### How should the problem be solved?

Being implementing the possibility of setting these two values with annotations/cli in the spirit of the parameter `config.linkerd.io/proxy-memory-request: [value]`

What do you want to happen? Add any considered drawbacks.

I want to use the debug sidecar running on a container with the CPU and Memory request parameters I chose.

### Any alternatives you've considered?

Disabling the cluster policy of needing these values to be explicitly written.

Is there another way to solve this problem that isn't as good a solution?

Using a third-party debug sidecar

### How would users interact with this feature?

Exactly the same as the feature allowing you to choose the CPURequest and MemoryRequest : By adding annotations to a pod or namespace with `config.linkerd.io/debug-sidecar-memory-request`, or by cli with `linkerd inject --debug-sidecar-memory-request `

If you can, explain how users will be able to use this. Maybe some sample CLI
output?

See `linkerd inject --proxy-memory-request` in cli or the annotation `config.linkerd.io/proxy-memory-request`

**Comment by ihcsim** [comment]
One workaround for this is to use `linkerd inject --manual --enable-debug-sidecar` to inject the proxy and the debug sidecar offline, and then modifyt the YAML accordingly. I assume this is an one-off task.

**Comment by rajatjindal** [comment]
we have policy to be able to provide cpu/memory for all containers as well. and it might make sense to add the annotations as originally suggested.

may be support default for linkerd cluster, with ability to override at namespace and deployment level. what do u think?

**Comment by ihcsim** [comment]
@rajatjindal I see adding debug container as an one-off task. Would one ever want to permanently annotate their workload YAML with debug container resource requests/limits (with or without an actual debug container running)? Any reasons why using `linkerd inject --manual --enable-debug-sidecar` to output and modify the YAML don't work?
