### ISSUE TITLE
smi-metrics in Linkerd

### ISSUE THREAD

**Issue by Pothulapati** [linkerd/linkerd2#4790]
## Bug Report

[smi-metrics](https://github.com/servicemeshinterface/smi-metrics) was included with Linkerd2, to support multi-tenant metrics and was marked as a external feature.

### What is the issue?

There are definitely not many users for this feature, as it was disabled by default. This has not been updated recently, and might have even become stale. Should we continue supporting this or remove it?

### Possible solution

Remove it so that we dont have to keep maintaining the templates

@adleong

**Comment by adleong** [comment]
Thanks for filing this @Pothulapati!

We should remove the SMI metrics resources from the main Linkerd2 chart and CLI as well as remove the experimental metrics commands which consume this API.  We should also add an integration test which installs https://github.com/servicemeshinterface/smi-metrics on top of Linkerd and ensures that it works as intended.  This will help us ensure that the SMI metrics integration will continue to work correctly.
