### ISSUE TITLE
Can proxy metrics add gauge on active requests?

### ISSUE THREAD

**Issue by susanhuhu** [linkerd/linkerd2#4809]
## Feature Request
Per https://linkerd.io/2/reference/proxy-metrics/  we only have counter for request total, but we don't have metrics for current active requests
### What problem are you trying to solve?
We have need to monitor if a deployment is active, if it is not active for some period, we want to scale down it to be 0 replica.  To achieve that, we want to see if the deployment currently is serving any requests.  So if LinkerD proxy metrics can expose such a gauge metrics, it will benefit any deployment that enables LinkerD, instead of each of them having to implement such a metrics.
### How should the problem be solved?
Expose a guage metrics on active request num in proxy metrics

### Any alternatives you've considered?

No, unless each deployment implements this by themselves

### How would users interact with this feature?

We have a zeroscaler service that will keep querying this metrics to check if the related deployment is active.

**Comment by ihcsim** [comment]
You might be able to achieve that already by watching the [`increase`](https://prometheus.io/docs/prometheus/latest/querying/functions/#increase) rate of the `request_total` metrics over a [predefined time window](https://prometheus.io/docs/prometheus/latest/querying/basics/#range-vector-selectors). If the increase rate is zero during that time window, it means the proxy hasn't seen any new requests.

E.g., when there is constant traffic flowing to the `voting` service of the emoji demo app, my request total in the last rolling 1 minute will always be non-zero:

![image](https://user-images.githubusercontent.com/1330522/88856417-4aa18900-d1a9-11ea-9f73-05448a98e676.png)

Once I scale the `vote-bot` load generator down to zero, the value eventually falls to zero:

![image](https://user-images.githubusercontent.com/1330522/88856735-d9aea100-d1a9-11ea-9116-7595f2c51777.png)

**Comment by susanhuhu** [comment]
We do monitor that, but only that is not enough.  Consider the situaiton when there is a long lasting reqeust,  we may not see request_total increase in last 5 minutes,  but the deployment is still active if it is serving a request last longer than 5 minutes.  In our current implementation, we always monitor both metrics,  the increase of request total counter, and the gauge of active requests.

**Comment by ihcsim** [comment]
Even with a new gauge metric, you'd still want to aggregate that over a time window, right? It's better to kill workloads when there hasn't been any active requests in the past X minutes, than to kill them because there are no activities at this very second. 

The other approach is to calculate the `response_total - request_total` over a time window. And if there is strictly for autoscaling purposes, what about the `tcp_open_connections` metric?

**Comment by susanhuhu** [comment]
We aggregate the counter over a time window to see its increase,  we don't aggregate gauge.  gauge tells us if the deployment is serving any request right now.  coutner tells us if there is new request in last x mins.    response_total - request_total have the similar problem, if there is a long running request lasting longer than X mins,  response_total - request_total won't be able to catch it as response_total only increase after the request has finished.  I considered tcp_open_connections  too, but it doesn't have the label for target deployment or service.  So I have no idea what the connection is for

**Comment by ihcsim** [comment]
Thanks for putting some thoughts into other alternatives beforehand. My concern with this new gauge metric is its potential cardinality, particularly, in the worst case scenario where it's equal to the request_total metric. This will double the amount of timeseries data that the proxy generates, right?

Are long-lived requests common in your environment? Say if we aggregate the counter metric over a 10-minute time window, how likely are requests to outlived this time period?

Re `tcp_open_connections`, I can see some namespace and deployment labels in my setup. Do they match what you are looking for?

![image](https://user-images.githubusercontent.com/1330522/89128667-1af5c800-d4ac-11ea-8e8e-8d94f700e47b.png)

> if there is a long running request lasting longer than X mins, response_total - request_total won't be able to catch it as response_total only increase after the request has finished.

I thought in this case we only care about if response_total - request_total (or request_total{direction="inbound"} - response_total{direction="inbound") returns a non-zero value, to indicate that there is still in-progress requests.

**Comment by susanhuhu** [comment]
Thanks for looking at the possible solutions.  It loosk to me that tcp_open_connections or request_total{direction="inbound"} - response_total{direction="inbound"}  may mee the need.   May I know where is the app label's value in tcp_open_connections coming from?  Wondering if we can control that value so we can differenciate what triggered the connection. 
To answer your question,   yes, it is pretty common for us that a request may last long, even for hours.  Some of our services provides speech recognition, which may serve an online meeting and last very long time.

**Comment by ihcsim** [comment]
The app label values come from one of the [label rewrite rules](https://github.com/linkerd/linkerd2/blob/cbcc305b78edb9fe65fc0edee99a5722a949287b/charts/add-ons/prometheus/templates/prometheus.yaml#L123-L126). The labels are added as part of the proxy injection process. 

LMK if we can close this issue. Thanks.

**Comment by susanhuhu** [comment]
thanks. pls feel free to close the issue
