### ISSUE TITLE
proxy: process_cpu_seconds_total should be a float

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#4822]
The proxy's metrics representation works exclusively with u64s currently. This is generally fine for counters, but not for gauges. The cpu_seconds_total metric, for instance, is very coarse when only measured in whole cpu seconds. We should convert the gauge representation to support float values. (For context, prometheus handles all values as floats).

```
# HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
# TYPE process_cpu_seconds_total counter
process_cpu_seconds_total 258
```

**Comment by zaharidichev** [comment]
Seems `process_cpu_seconds_total` is a counter though, not a gauge. Should all be f64 ?

**Comment by hawkw** [comment]
Probably related to #4414, right?

**Comment by olix0r** [comment]
@hawkw yep

**Comment by olix0r** [comment]
This was done in a recent proxy release.
