### ISSUE TITLE
The CNI Plugin does not set iptables rules

### ISSUE THREAD

**Issue by cpretzer** [linkerd/linkerd2#4828]
### What is the issue?
@jvandermark has been helpful in debugging the CNI plugin and provided these gists[[1](https://gist.github.com/jvandemark/ae2a72b203ad25780b68dfb4d993d80d)][[2](https://gist.github.com/jvandemark/3153e0976b416857b1b9de209af4a51b)]

The error was initially discovered on AKS, and I have reproduced it there as well as on KinD. When the CNI plugin runs, this error occurs:

`invalid character 'T' looking for beginning of value`

I believe that the "T" is from the output that is written as a result of [this change](https://github.com/linkerd/linkerd2-proxy-init/commit/a38ea177aa5bd6b4ddfe036cc041193a519aa613#diff-b90cadcd0928c1e490272f4761a52bacR60).

### How can it be reproduced?
Using `edge-20.7.5` run:
`linkerd install-cni | kubectl apply -f -`
`linkerd install --linkerd-cni-enabled | kubectl apply -f -`

### Logs, error output, etc
In the kubelet logs, you will see:
```Aug 01 22:44:27 kind-control-plane kubelet[732]: E0801 22:44:27.405985     732 remote_runtime.go:105] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed to setup network for sandbox "dce453f897022d5c499d8d921f5caf471f713c454284679bb31c147cd27c7617": invalid character 'T' looking for beginning of value```

#### `linkerd check` output

- Linkerd check never finishes

```text
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
| linkerd-controller-6cdc88f55f-xs97t status is ContainerCreating
```

### Environment

- Kubernetes Version:  v1.18.2
- Cluster Environment: KinD
- Host OS: macOS
- Linkerd version: edge-20.7.5

### Possible solution
Revert the change from `fmt.Printf` to `log.Printf` in `iptables.go`

### Additional context

The pods are all stuck in ContainerCreating

```text
NAME                                      READY   STATUS              RESTARTS   AGE
linkerd-controller-6cdc88f55f-xs97t       0/2     ContainerCreating   0          5m20s
linkerd-destination-56cb676998-p5l64      0/2     ContainerCreating   0          5m19s
linkerd-grafana-79b5bb66b7-wc5fc          0/2     ContainerCreating   0          5m18s
linkerd-identity-7cdf75c77-mjd27          0/2     ContainerCreating   0          5m20s
linkerd-prometheus-848bd774c6-d6n6f       0/2     ContainerCreating   0          5m18s
linkerd-proxy-injector-6b6d696568-5nrzl   0/2     ContainerCreating   0          5m19s
linkerd-sp-validator-9fdc59675-k4tjg      0/2     ContainerCreating   0          5m19s
linkerd-tap-867f99fb58-rb4bf              0/2     ContainerCreating   0          5m19s
linkerd-web-5487d94cdd-rt8jz              0/2     ContainerCreating   0          5m19s
```

**Comment by ihcsim** [comment]
@cpretzer Can we close this issue?

**Comment by cpretzer** [comment]
Yep, closing now!

**Comment by cpretzer** [comment]
proxy-init [#24](https://github.com/linkerd/linkerd2-proxy-init/pull/24) PR also addresses this iptables issue
