### ISSUE TITLE
How to scale up workload replicas count based on inbound traffic?

### ISSUE THREAD

**Issue by susanhuhu** [linkerd/linkerd2#4830]
### What problem are you trying to solve?
We have a zeroscaler service, which needs to scale up a service from 0 replica as soon as there is a reqeust coming in.  One way to achieve this is to rely on prometheus metrics to check if there is request coming in, which always has some delay.  We then developed a notification mode in our grpc load balancer solution,  so whenever there is a request coming in, while the dst deployment has 0 replica, the load balancer will send out a notifcation.  Now we are trying to use LinkerD,  wondering if there is an easy way to achieve this notification functionality by writing a proxy plug in.  So when LinkerD tries to find a dst deployment's pod to send request, but get 0 result back, it will send out a notification to a redis pubsub channel ( or other places like event hub).

### How should the problem be solved?
Allowing customized plugin to the proxy, which will trigger notification on request coming in.

### Any alternatives you've considered?

Cannot find an alternative solution with exiting LinkerD.

### How would users interact with this feature?

Our zeroscaler service can consume the notification and trigger corresponding deployment to scale up immediately.

**Comment by grampelberg** [comment]
You can do this pretty trivially with tap, no reason to write a plugin for the proxy.

**Comment by susanhuhu** [comment]
great.  would you share more information about tap and how this can be achieved with it please?

**Comment by susanhuhu** [comment]
I looked at documenation of tap,  I cannot find a way to output its data to a channel. Seems it is designed to debug LinkerD.

**Comment by grampelberg** [comment]
You can either:

- Use the gRPC streaming API directly.
- Consume the CLI as a client library.

I would recommend going the gRPC route first, which would obviously allow you to consume the data with a channel. AFAIK there's no one who's integrated with that API, so you'll want to look through the linkerd codebase, in particular the web service and CLI.

**Comment by viniciusgarcia-hotmart** [comment]
Do you guys have some code sample or even a documentation of this gRPC streaming API?

**Comment by susanhuhu** [comment]
or please at least give a pointer to the source code of this API. :)

**Comment by grampelberg** [comment]
- [Code](https://github.com/linkerd/linkerd2/blob/main/pkg/tap/tap.go)
- [Proto](https://github.com/linkerd/linkerd2-proxy-api/blob/main/proto/tap.proto)

**Comment by viniciusgarcia-hotmart** [comment]
Thanks @grampelberg!

**Comment by ihcsim** [comment]
I'm going to rename the title of this issue. Currently, the Linkerd proxy doesn't support a plugin model. I also don't think a proxy plugin is the right approach - which proxy will be responsible for sending out the notification if the workload replicas count is 0? Are the requests being queued somewhere while the replicas are being scaled up? What if the replicas take longer time to come up?
