### ISSUE TITLE
check command fails on can create non-namespaced resources after installing OSM

### ISSUE THREAD

**Issue by alexellis** [linkerd/linkerd2#4845]
### What is the issue?

The check command fails on can create non-namespaced resources after installing OSM

### How can it be reproduced?

Install the OSM project via https://github.com/openservicemesh/osm#getting-started

Then install linkerd2 and run the pre-flight checks beforehand

### Logs, error output, etc

(If the output is long, please create a [gist](https://gist.github.com/) and
paste the link here.)

```
× can create non-namespaced resources
    cannot create CustomResourceDefinition/trafficsplits.split.smi-spec.io: customresourcedefinitions.apiextensions.k8s.io "trafficsplits.split.smi-spec.io" already exists
    see https://linkerd.io/checks/#pre-k8s-cluster-k8s for hints
```

#### `linkerd check` output

```text
your output here ...
```

### Environment

- Kubernetes Version: KinD 1.18
- Cluster Environment: (GKE, AKS, kops, ...)
- Host OS: Darwin
- Linkerd version: stable-2.8.1

### Possible solution

Less strict checking for this - given there may be > 1 SMI-based mesh on a cluster?

### Additional context

Updating the arkade app for Linkerd to a newer version and adding OSM support to arkade. https://github.com/alexellis/arkade/pull/167

**Comment by adleong** [comment]
Hey @alexellis! OSM uses a different version of the traffic split CRD than we do (v1alpha2 instead of v1alpha1).  Since CRDs are global to the cluster, I think this check error indicates a legitimate incompatibility. We're tracking the upgrade of our trafficsplit CRD version here: https://github.com/linkerd/linkerd2/issues/3962

**Comment by alexellis** [comment]
Thank you @adleong 👍

**Comment by olix0r** [comment]
We'll track this in the referenced issue
