### ISSUE TITLE
External Grafana url does not work with `https://`

### ISSUE THREAD

**Issue by MaT1g3R** [linkerd/linkerd2#4848]
### What is the issue?

We are trying to install linkerd with the helm chart. Setting `global.grafanaUrl` to `https://grafana.example.com` does not work.

### How can it be reproduced?

Set `global.grafanaUrl` to a proper URL including the protocol.

### Logs, error output, etc

```
http: proxy error: dial tcp: lookup https://grafana.example.com: no such host
```

### Possible solution

Seting `global.grafanaUrl` to only include the hostname does work (e.g. `grafana.example.com`)

The documentation should be updated to reflect this, or the config value should be changed to `global.grafanaHostname`

**Comment by ihcsim** [comment]
The proposed fix at https://github.com/linkerd/linkerd2/issues/4838#issuecomment-670509215 might address too. Meanwhile, this variable should be added to the chart README.

**Comment by hetii** [comment]
The same issue here as I try to use grafana included by rancher2 monitoring. 
Now instead `no such host` error I'm able to proxy into grafana but just partial as I see
`If you're seeing this Grafana has failed to load its application files`
This is due the fact that my grafana try to load all additional css etc files without /grafana/ prefix.
Any clue about this issue?
