### ISSUE TITLE
Update bin/build-cli-bin to build binary based off architecture

### ISSUE THREAD

**Issue by kleimkuhler** [linkerd/linkerd2#4868]
## Feature Request

`bin/build-cli-bin` could benefit from the multi-arch builds we are now doing in
CI. Developers on `arm64` for example could expect that running
`bin/build-cli-bin` would produce a binary in `./target/cli/linux-arm64`.

### What problem are you trying to solve?

When using the `bin/linkerd` script, if a binary does not exist in the expected
path then it attempts to build one in `bin/build-cli-bin`. On some
architectures, this will not produce a binary in the correct location.

### How should the problem be solved?

The script should be updated to build the CLI based off the current
architecture.

### Any alternatives you've considered?

--

### How would users interact with this feature?

Users on supported architectures would have a seemless experience using
`bin/linkerd`.

**Comment by kleimkuhler** [comment]
@aliariff Any interest in keeping this issue on your radar? It really only affects Linkerd developers, but it could be helpful in the  future as we have contributors working on different architectures.

**Comment by aliariff** [comment]
@kleimkuhler  yes sure, I will take a look at it. Could you assign this to me?
