### ISSUE TITLE
Move to Helm v3 sdk in CLI

### ISSUE THREAD

**Issue by Pothulapati** [linkerd/linkerd2#4874]
## Feature Request

Currently, we use Helm `v2.16.8`. Helm v2 is moving to its end of lifecycle and wont be supported anymore. Its best to move to Helm v3 internally sdk. Irrespective of #4833, Its best to move the current state of things to Helm v3 so that its lets us experiment with the idea of using Helm in the CLI internally, and also may help clean up the code-base a bit as the Helm Go SDK has been refactored in V3 for cases like us, to be able to perform most of the helm cmd operations.

**Comment by Pothulapati** [comment]
This requires client-go to be updated to `v0.18`

tagging https://github.com/linkerd/linkerd2/issues/4191

**Comment by alpeb** [comment]
Just to know, would the v3 SDK still support v2 charts?

**Comment by Pothulapati** [comment]
@alpeb Yep, I was able to get this working today, especially because we don't use any of the direct `LoadChart()/LoadDir()` funcs which make use of the `requirements.yaml` or `Chart.yaml`. So, Things worked the same as its just replacing types but my hope is that we move into that model (once helmv2 retires) so that we don't have to maintain file paths in code, and let `Load*` functions do their job. WDYT?

**Comment by Pothulapati** [comment]
I was able to skip the client-go `v1.18` dependency by using a `v3.1.3` version of Helm which uses a older version of client-go

**Comment by alpeb** [comment]
> my hope is that we move into that model (once helmv2 retires) so that we don't have to maintain file paths in code, and let `Load*` functions do their job. WDYT?

Agreed. Helm v2 should be EOLd in November, from my understanding.
