### ISSUE TITLE
Add check to linkerd cli to see if pods with inject annotation have sidecar

### ISSUE THREAD

**Issue by secret104278** [linkerd/linkerd2#4875]
### What problem are you trying to solve?
Recently, I try to setup multicluster linkerd follow the document, however it just dont work.
```shell
❯ linkerd --context=west check --multicluster
...
√ service mirror controller can access target clusters
× all target cluster gateways are alive
    Some gateways are not alive:
    * cluster: [east], gateway: [linkerd-multicluster/linkerd-gateway]
    see https://linkerd.io/checks/#l5d-multicluster-target-gateways-alive for hints
√ clusters share trust anchors
√ multicluster daisy chaining is avoided
...

❯ kubectl --context=west -n linkerd-multicluster logs linkerd-service-mirror-7657dc885b-nzfp9 service-mirror
...
time="2020-08-13T10:23:04Z" level=info msg="Updating 2 services due to gateway [linkerd-multicluster/linkerd-gateway] update" apiAddress="https://35.221.211.168" cluster=east
time="2020-08-13T10:23:04Z" level=warning msg="Gateway returned unexpected status 503. Marking as unhealthy" probe-key=linkerd-multicluster-linkerd-gateway-east
time="2020-08-13T10:23:07Z" level=warning msg="Gateway returned unexpected status 503. Marking as unhealthy" probe-key=linkerd-multicluster-linkerd-gateway-east
time="2020-08-13T10:23:11Z" level=warning msg="Gateway returned unexpected status 503. Marking as unhealthy" probe-key=linkerd-multicluster-linkerd-gateway-east
time="2020-08-13T10:23:14Z" level=warning msg="Gateway returned unexpected status 503. Marking as unhealthy" probe-key=linkerd-multicluster-linkerd-gateway-east
...

❯ kubectl --context=east -n linkerd-multicluster logs linkerd-gateway-68545bf968-tj7nx nginx
...
10.10.0.5 - - [13/Aug/2020:10:23:36 +0000] "\x16\x03\x01\x01$\x01\x00\x01 \x03\x03J\xC4\x07\x22\xC2\x9B\xE1Z\x15\xA7\xB6\x1B\x11\x1A\x1C\xC1Z\xD2\x9B\xC4\x91&G\xD2\xF7\x9CX\x07\xAE@\x1F\xF3 -\xAC\xB0\x8EQ\xE0\xB5\x9BR\x90" 400 158 "-" "-"
10.10.0.5 - - [13/Aug/2020:10:23:37 +0000] "\x16\x03\x01\x01$\x01\x00\x01 \x03\x03^\x17a\xDA\xCD\x98vC\xAE\xDE\x1F\x17\x9FW*G\x1E2\xF3\xF0\xF8b\xCC{b\xE3\xD6\xD9\xA2d\xE9\x99 p<H:\x17\xDC\xA2\xF8,\xA4\xBC\xA3X\x9A\xBE\xAAwSz\xD8\xC6\xCAM3\xB7\xA5\xB3\xE3\x1F\x97\xCB\x83\x00\x14\x13\x03\x13\x02\x13\x01\xCC\xA9\xCC\xA8\xC0,\xC0+\xC00\xC0/\x00\xFF\x01\x00\x00\xC3\x00+\x00\x05\x04\x03\x04\x03\x03\x00\x00\x00W\x00U\x00\x00Rlinkerd-gateway.linkerd-multicluster.serviceaccount.identity.linkerd.cluster.local\x00\x0B\x00\x02\x01\x00\x00" 400 158 "-" "-"
10.10.0.7 - - [13/Aug/2020:10:23:37 +0000] "\x16\x03\x01\x01$\x01\x00\x01 \x03\x03\x14\xFC\xFAf\xE5\x85\xDE\xDF\xD0\xD3\xF9\xDC$\x01\xBB\xFB\xDF\x1Dj\xD5\x1B\xB0V\xF8\xF7\x906\xA3\xFC\x84[: -\xAC\xB0\x8EQ\xE0\xB5\x9BR\x90" 400 158 "-" "-"
10.10.0.7 -^CxA8\xC0,\xC0+\xC00\xC0/\x00\xFF\x01\x00\x00\xC3\x00+\x00\x05\x04\x03\x04\x03\x03\x00\x00\x00W\x00U\x00\x00Rlinkerd-gateway.linkerd-multicluster.serviceaccount.identity.linkerd.cluster.local\x00\x0B\x00\x02\x01\x00\x00" 400 158 "-" "-"
10.10.0.7 - - [13/Aug/2020:10:23:38 +0000] "\x16\x03\x01\x01$\x01\x00\x01 \x03\x03h\x9F\x10\x02C\x0E7\x981zG\xE9\x93\x1B]_k\xDAI\x8B\xA5\xA2\x0BVb\x19\x18u\xECB\x95\xED -\xAC\xB0\x8EQ\xE0\xB5\x9BR\x90" 400 158 "-" "-"

...
```

It took me an afternoon to realize that the problem is: 
pod of `linkerd-multicluster/linkerd-gateway` was created before `linkerd/linkerd-proxy-injector` became ready, so `linkerd-multicluster/linkerd-gateway` didn't have the sidecar injected which make it can decrypt the HTTPS from the gateway of another cluster.

This may happens in some cases:
* Someone enters the install command too fast, e.g. `linkerd install && linkerd multicluster install`
* The injector is created too slow
* Someone scales down the cluster size to 0 and scales up again. (This is my case, I scale down clusters after work hour)

### How should the problem be solved?

* Change the mutating webhook to not ignore the error
    * This is quit paradox, we usually set webhook to `Ignore` because we dont want another system critical pod fail due to the webhook. However, if the side can't be inject, then the behaviour of the pod will change.

* Add a condition check in `linkerd check` or `linkerd check --multicluster` to see if all control plane pod with inject annotation have sidecar
    * This will affect user least and easy to implement.

BTW, linkerd is amazing and I really want to contribute to it somehow. So if you have any feedback or decide to implement any solution, I can help.

**Comment by ihcsim** [comment]
Does `linkerd check --proxy` not show any warnings or errors?

**Comment by secret104278** [comment]
Oh yes, it seems like what I was looking for. However, you have to specified namespace like `linkerd --context=east -n linkerd-multicluster check --proxy`

It like we can improve the experience by adding this check command in the document.

**Comment by ihcsim** [comment]
@secret104278 Glad to hear that `linkerd check --proxy` works. I am closing this issue for now, and continue the doc discussion in https://github.com/linkerd/website/pull/798.
