### ISSUE TITLE
proxy: Support profile lookup by IP

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#4877]
Following https://github.com/linkerd/linkerd2/issues/3916, we should modify the proxy's profile client to support discovery on numeric addresses in addition to names. We will have to add an allowed-suffix configuration (as we have done for the destination client).

**Comment by hawkw** [comment]
> We will have to add an allowed-suffix configuration (as we have done for the destination client).

For IP lookups, it seems like might make sense for the allowlist to be able to include CIDR routing prefixes or something, if we want to permit lookups for non-HTTP traffic? I know the service profile configurations are _currently_ http/gRPC-specific, though...

**Comment by olix0r** [comment]
Yeah, that's what I mean:

https://github.com/linkerd/linkerd2-proxy/blob/eee08f995cd8772f45fa3013cd115d4a8621bf25/linkerd/app/src/env.rs#L817-L830

But this is all pretty decoupled from HTTP/etc?

**Comment by hawkw** [comment]
...right, i forgot we were already doing this. Yeah.
