### ISSUE TITLE
destination: Always return dst_overrides for existing services

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#4879]
Currently, the destination service (in GetProfile repsonses) only sets dst_overrides when a traffic split is present. Instead, it should always return at least one dst_override when the service exists. The proxy can then use this response as a hint to indicate whether it should perform a destination.Get: if no dst_overrides are present, it is assumed that the target is not a Service and endpoint resolution will be skipped.

**Comment by kleimkuhler** [comment]
Closed by #4890
