### ISSUE TITLE
Improve the readability of the documentation in doc/ when rendered by GitHub

### ISSUE THREAD

**Issue by briansmith** [linkerd/linkerd2#488]
@klingerf noted that the GitHub rendering of the documentation under doc/ can be improved. See his comments in https://github.com/runconduit/conduit/pull/418.

The main difficulty here is that we have to merge these documents into a larger set of documents for https://conduit.io/ that uses tooling different than what GitHub uses. Already the changes in #418 require some (not yet done!) scripting to handle that merging correctly. This is further complicated by the fact that the sources for all the other documents for https://conduit.io/ aren't open source (yet).

**Comment by klingerf** [comment]
Docs now live in the [linkerd/website](https://github.com/linkerd/website) repo; closing.
