### ISSUE TITLE
Add locales to Linkerd web dashboard

### ISSUE THREAD

**Issue by scottcarol** [linkerd/linkerd2#4886]
### What problem are you trying to solve?

The web dashboard for Linkerd now has `en` and `es` translations. This can be expanded to other languages.

### How should the problem be solved?

To add a new locale, follow the local development instructions in `BUILD.md`. Then, from your command line:

```bash
cd web/app
yarn lingui add-locale [locales...]
```

This will create a `your-new-locale/messages.json` file for new locale(s), that will automatically have all existing keys. Once you have edited that new `messages.json` file, you can run `yarn lingui compile` and view on your web browser in the language of your choice.

**Comment by ihcsim** [comment]
@scottcarol Just want to make sure I understand the scope, is there a list of locales we want to include as part of this issue? Or is this more a doc update? Or do we want to introduce a new script etc.?

**Comment by ihcsim** [comment]
Per conversation with @scottcarol, the purpose of this issue is to promote visibility of the process to add more locales to the Linkerd dashboard, following interests in KubeCon. We agree that this info should be added to the Linkerd doc. I will follow up with a separate doc PR.

**Comment by eugeniaguerrero** [comment]
I am happy to work on the French translation - unless it's better to wait for a locales that are desired / needed, as you've mentioned @ihcsim?

**Comment by ihcsim** [comment]
@eugeniaguerrero That sounds awesome! Please go ahead and submit a PR with your changes. If you need help with getting the build running locally, feel free to drop by the [#contributors](https://linkerd.slack.com/archives/CMS5ZD60Y) channel.

**Comment by ihcsim** [comment]
Closing this issue. See [BUILD.md](https://github.com/linkerd/linkerd2/blob/main/BUILD.md#translations) for steps to add more locales. Feel free to raise any questions in the [#contributors](https://linkerd.slack.com/archives/CMS5ZD60Y) channel.
