### ISSUE TITLE
Update control plane base image

### ISSUE THREAD

**Issue by ihcsim** [linkerd/linkerd2#4888]
Per reported at https://github.com/linkerd/linkerd2/discussions/4884, we need to update our control plane base images before the 2.9 release to address the reported CVEs.

cc @cpretzer @olix0r

**Comment by grampelberg** [comment]
@alpeb could you take a look at this? It'd be great to get updated for ~ this week's edge so that we can test and make sure nothing else breaks!

**Comment by alpeb** [comment]
@grampelberg This got addressed in #4981 by upgrading the Grafana base image, which made it into last weeks edge (edge-20.9.4). As per [this comment](https://github.com/linkerd/linkerd2/discussions/4884#discussioncomment-80098), that addressed two of the CVEs. The remaining one didn't seem to be present in any of our images.
