### ISSUE TITLE
proxy: replace net2 with socket2

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#4891]
The proxy depends on the `net2` crate, which has been deprecated and replaced by `socket2`. We should update our one or two uses:

```
linkerd/app/Cargo.toml
42:net2 = "0.2"

linkerd/app/integration/Cargo.toml
32:net2 = "0.2"

linkerd/app/integration/src/server.rs
205:        let listener = net2::TcpBuilder::new_v4().expect("Tcp::new_v4");

linkerd/app/integration/src/controller.rs
337:    let listener = net2::TcpBuilder::new_v4().expect("Tcp::new_v4");
```

**Comment by hawkw** [comment]
As a side note, this isn't gonna be totally banished from our dependency tree until Tokio migrates from `mio` 0.6 to `mio` 0.7 (https://github.com/tokio-rs/tokio/issues/2677) a breaking change scheduled for Tokio 0.3. But, I imagine that we can remove _our_ uses of it (which all appear to be in the integration tests).

**Comment by hawkw** [comment]
I actually have no idea why the integration tests don't just use `tokio::net::TcpListener::bind`...there is probably _some_ backstory for this...

**Comment by hawkw** [comment]
Ah, the test change from `TcpListener::bind` to `socket2` was in linkerd/linkerd2#952, because we added a test that required introducing a delay between binding and listening on the socket. So, we do still need this, and can probably just switch to `socket2`.
