### ISSUE TITLE
Linkerd-proxy consuming huge memory (~800MB) for a service that creates and maintains a huge number of outbound connections

### ISSUE THREAD

**Issue by ericsuhong** [linkerd/linkerd2#4900]
### What is the issue?

We have noticed that linkerd-proxy is consuming huge memory (~800MB) for a service that creates and maintains a huge number of outbound connections (~30000 sockets per pod):

![image](https://user-images.githubusercontent.com/3857851/90827285-d746ef00-e2f0-11ea-8b92-6aa333f24a9f.png)

For other "normal" services, we do not see such problems, as linkerd-proxy only consumes around 20MB:

![image](https://user-images.githubusercontent.com/3857851/90827388-0198ac80-e2f1-11ea-8c9b-3903db388711.png)

We are running Linkerd stable-2.8.1 version.

Linkerd metrics from a "bad" pod that is consuming 800MB memory:
[linkerd-metrics-bad.txt](https://github.com/linkerd/linkerd2/files/5105686/linkerd-metrics-bad.txt)

Linkerd metrics from a "good" pod that is consuming 20MB memory for comparison:
[linkerd-metrics-good.txt](https://github.com/linkerd/linkerd2/files/5105687/linkerd-metrics-good.txt)

### How can it be reproduced?

Run a service that opens and maintains a huge number of sockets, and mesh it with linkerd.

#### `linkerd check` output

```text
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-identity
----------------
√ certificate config is valid
√ trust anchors are using supported crypto algorithm
√ trust anchors are within their validity period
√ trust anchors are valid for at least 60 days
√ issuer cert is using supported crypto algorithm
√ issuer cert is within its validity period
√ issuer cert is valid for at least 60 days
√ issuer cert is issued by the trust anchor

linkerd-api
-----------
√ control plane pods are ready
√ control plane self-check
√ [kubernetes] control plane can talk to Kubernetes
√ [prometheus] control plane can talk to Prometheus
√ tap api service is running

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ control plane is up-to-date
√ control plane and cli versions match

linkerd-ha-checks
-----------------
‼ pod injection disabled on kube-system
    kube-system namespace needs to have the label config.linkerd.io/admission-webhooks: disabled if HA mode is enabled
    see https://linkerd.io/checks/#l5d-injection-disabled for hints
√ multiple replicas of control plane pods

linkerd-addons
--------------
√ 'linkerd-config-addons' config map exists

linkerd-grafana
---------------
√ grafana add-on service account exists
√ grafana add-on config map exists
√ grafana pod is running

Status check results are √
```

### Environment

- Kubernetes Version: 1.16.9
- Cluster Environment: Azure (aks-engine)
- Host OS: Ubuntu 16.04
- Linkerd version: stable-2.8.1

### Additional context

Our service is using CosmosDB with a huge number partitions, and CosmosDB SDK is (notoriously) maintaining huge # of connections and sockets.

**Comment by olix0r** [comment]
@ericsuhong We've made some changes that should reduce memory usage for busy clients. If you're able to test a recent edge release (or the upcoming stable-2.9.1 release), I would be eager to know if these changes help reduce memory consumption for your use case.
