### ISSUE TITLE
Make proxy controller services headless

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#4912]
Following https://github.com/linkerd/linkerd2-proxy/commit/6962794b1ef3e0d17a6ece16e581bffb1dda4060, the proxy now supports SRV-based controller discovery. In order to take advantage of this, the control plane's services should be exposed as headless services, so that no load balancer IPs are allocated (as implemented in https://github.com/linkerd/linkerd2/commit/17e6490bf09d4848381eff112e3fca495f47ecfe).

Before merging this change, we should test that an upgrade can be performed gracefully. Specifically:

1. If a cluster uses load balancer IP services (i.e. as in the current edge release), `linkerd upgrade` applies cleanly. ISTR that it's not necessarily possible to modify services with LB IPs...
2. Following a `linkerd upgrade` older proxies that do not perform SRV lookups continue to work as expected. I.e., we cannot require a full, lock-step data plane upgrade with this service change.

If we can't meet either of these requirements, we'll need to consider a more staged/incremental upgrade plan (probably introducing _new_ services).

---
Fixes https://github.com/linkerd/linkerd2/issues/4624 https://github.com/linkerd/linkerd2/issues/4674

**Comment by zaharidichev** [comment]
> If a cluster uses load balancer IP services (i.e. as in the current edge release), linkerd upgrade applies cleanly. ISTR that it's not necessarily possible to modify services with LB IPs...

@olix0r Might be missing something but which services are you refering to. And more importantly, why do we need to change them?

**Comment by olix0r** [comment]
@zaharidichev identity and dst, at least (per https://github.com/linkerd/linkerd2/commit/17e6490bf09d4848381eff112e3fca495f47ecfe)... if we don't change them, then we'll continue to see the problems mentioned in #4624 & #4674, correct?

**Comment by zaharidichev** [comment]
@olix0r for some reason I thought you are refering to service type LoadBalancer. Never mind... So I tested that the old proxy code works fine when the services are headless, I will also test the upgrade path. The question is, do we want to turn only the services that are used by the proxy or all control plane services into headless ones?

**Comment by zaharidichev** [comment]
Ahh.... yes just like you thought `.spec.clusterIP` is immutable...

**Comment by olix0r** [comment]
@zaharidichev 

> The question is, do we want to turn only the services that are used by the proxy or all control plane services into headless ones?

Only the services used by the proxy. At least dst and identity. Could go either way on tracing.
