### ISSUE TITLE
multicluster: Support more than one gateway instance

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#4928]
As I understand it, multicluster only supports using a single gateway instance.

https://github.com/linkerd/linkerd2/blob/72aadb540f3e3cb250a178964ffd7f2cff1cb39f/pkg/multicluster/link.go#L41-L43

Should it support more than one gateway instance, i.e., if there isn't a single load balancer VIP on the remote cluster (as may be the case for metalLB configurations)?

**Comment by adleong** [comment]
Good news: this field already supports a comma-separated list of addresses.  The service mirror controller will transform this into an Endpoints resource with one endpoint per address.  Note that all of the gateways must have the expected identity.
