### ISSUE TITLE
Intermitent (random) 502 Bad Gateway hitting a service in the mesh

### ISSUE THREAD

**Issue by dcodix** [linkerd/linkerd2#4934]
## Bug Report

###Notes
I think this is related to: https://github.com/linkerd/linkerd2/issues/3964
And maybe (not sure) related to: https://github.com/linkerd/linkerd2/issues/4870 (??)

### What is the issue?
Slack: https://linkerd.slack.com/archives/C89RTCWJF/p1598486828250400

App1 -> ELB(internal)->nginx (ingress controller)->App2
App1 is in a different VPC

When adding App2 to the mesh we start getting random 502s. When App2 is not in the mesh we don't get them.
Note that nginx is not in the mesh.
This server has around 10k per MINUTE.
We are getting 502 in a very low rate.

(SORRY the traces IPs don't match but I did that different days and IPs had already changed)

I have been tracing this t see what the issue was. Here the trace of a sane request:
<img width="576" alt="Screen Shot 2020-08-26 at 8 11 14 PM" src="https://user-images.githubusercontent.com/1180115/91781160-9f308d80-ebc7-11ea-99bc-df964ac7bb8e.png">

Here the trace of a failed request:
<img width="582" alt="Screen Shot 2020-08-26 at 8 12 01 PM" src="https://user-images.githubusercontent.com/1180115/91781215-b7a0a800-ebc7-11ea-9046-12620d8353bc.png">

Note that after the first succesful request, a second one happens, the 3rd PSH. As that arrives to linkerd-proxy it rejects it with a RST (as I would say expected).

Now, after going deeper to know what was the issue I think I found it. I think something in linkerd sets the headers wrong. As we can see there are 2 HTTP requests in a single stream. The second one is the one that gives 502, the first one succeeds with 200. I noticed 2 things:
1)  In the HTTP response of the first request (200) the headers come back without capital letters. (I know this should have no effect, but it is a clue)
2) In the HTTP response of the first request (200) the `Connection: close` header is missing.

I think this makes nginx to keep the connection open (and that is why the FIN,ACK doesn't happen), and tries to reuse it, anding in a RST.

Here the headers of the HTTP response of the first request (200) whithout 502s:
<img width="412" alt="Screen Shot 2020-08-31 at 8 01 15 PM" src="https://user-images.githubusercontent.com/1180115/91781744-11ee3880-ebc9-11ea-8b4d-7bf97ad4d8a7.png">
The corresponding TCP stream:
<img width="1283" alt="Screen Shot 2020-08-31 at 8 34 05 PM" src="https://user-images.githubusercontent.com/1180115/91781972-c8521d80-ebc9-11ea-93b8-5f15f9b9d03e.png">

Here the headers of the HTTP response of the first request (200) when we get a 502 on the following request (the next POST):
<img width="445" alt="Screen Shot 2020-08-31 at 8 03 25 PM" src="https://user-images.githubusercontent.com/1180115/91781775-2a5e5300-ebc9-11ea-9558-3e1e51dc8521.png">
The corresponding TCP stream:
<img width="1273" alt="Screen Shot 2020-08-31 at 8 34 52 PM" src="https://user-images.githubusercontent.com/1180115/91781983-d1db8580-ebc9-11ea-9caa-e199a2ec3355.png">

I am not sure why this happens. I would be happy to get into the linker-proxy debug mode if that helps, but I would need help with that because I am not sure what I would be looking for in there.

### How can it be reproduced?
Not sure.

#### `linkerd check` output

```kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
× is running the minimum Kubernetes API version
    Kubernetes is on version [1.12.7], but version [1.13.0] or more recent is required
    see https://linkerd.io/checks/#k8s-version for hints
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-identity
----------------
√ certificate config is valid
√ trust roots are using supported crypto algorithm
√ trust roots are within their validity period
√ trust roots are valid for at least 60 days
√ issuer cert is using supported crypto algorithm
√ issuer cert is within its validity period
‼ issuer cert is valid for at least 60 days
    issuer certificate will expire on 2020-09-01T18:41:52Z
    see https://linkerd.io/checks/#l5d-identity-issuer-cert-not-expiring-soon for hints
√ issuer cert is issued by the trust root

linkerd-api
-----------
√ control plane pods are ready
√ control plane self-check
√ [kubernetes] control plane can talk to Kubernetes
√ [prometheus] control plane can talk to Prometheus
√ tap api service is running

linkerd-version
---------------
√ can determine the latest version
‼ cli is up-to-date
    is running version 2.7.1 but the latest stable version is 2.8.1
    see https://linkerd.io/checks/#l5d-version-cli for hints

control-plane-version
---------------------
‼ control plane is up-to-date
    is running version 2.7.1 but the latest stable version is 2.8.1
    see https://linkerd.io/checks/#l5d-version-control for hints
√ control plane and cli versions match

linkerd-ha-checks
-----------------
√ pod injection disabled on kube-system

Status check results are ×
```

### Environment

- Kubernetes Version: 1.12
- Cluster Environment: AWS
- Host OS: Debian 4.9.168-1
- Linkerd version: 2.7.1

**Comment by ihcsim** [comment]
@dcodix Thanks for the detailed issue. Can you post the proxy logs of App2? You can change the proxy log to DEBUG following the doc [here](https://linkerd.io/2/tasks/modifying-proxy-log-level/).

Also for testing repro purposes, does the problem go away if you inject your ingress controller with the Linkerd proxy? (Even if it does, there is still an issue here that we need to investigate.)

For additional context, the issue still exists with Linkerd proxy 2.8.1, per our Slack conversation.

**Comment by dcodix** [comment]
@ihcsim I just tested adding the ingress in the mesh and I keep getting 502s. Also, if I add the ingress to the mesh but I disable the mesh from App2, I still get 502s.

About the debug logs. There are a ton of logs! Not sure I can post all of that here, is there anything in particular I could grep the logs by so I could get some manageable amount of logs?

**Comment by ihcsim** [comment]
Make sure your ingress has the required annotation per documented [here](https://linkerd.io/2/tasks/using-ingress/#nginx). Re debug logs, just post it to a gist and share the link here. It will be helpful if you know and can highlight which section of the logs is relevant to the original 502 errors. Thanks.

**Comment by dcodix** [comment]
Yes, I have the correct headers on the proxy, I think if I didn't I would get many more errors.

Re: Debug logs
Is there any other way I can help you with this? These logs have some sensitive information, as paths and ports, information I would prefer not to publish. Also, it might be too many lines for me to check that I get rid of all sensitive information, from timestamp `2513.703652634s` to `2514.127987769s` it is 3000 log lines...

Checking the logs I do not see anything weird, but then again, I am no expert reading these logs. I am able to locate the request previous to the one that returns a 502, but I am not sure if I should see the 200 response there, I don't find any 200.

**Comment by dcodix** [comment]
Filtering the 3000 lines with `grep -i "warn\|error"` it shows only 36 lines:

```
[  2513.704120109s] DEBUG outbound:accept{peer.addr=100.96.165.46:59198}: hyper::proto::h1::conn: error shutting down IO: Transport endpoint is not connected (os error 107)
[  2513.704155376s] DEBUG outbound:accept{peer.addr=100.96.165.46:59198}: linkerd2_app_core::accept_error: Connection failed error=error shutting down connection: Transport endpoint is not connected (os error 107)
[  2513.773821738s] DEBUG outbound:accept{peer.addr=100.96.165.46:59192}: hyper::proto::h1::conn: error shutting down IO: Transport endpoint is not connected (os error 107)
[  2513.773862897s] DEBUG outbound:accept{peer.addr=100.96.165.46:59192}: linkerd2_app_core::accept_error: Connection failed error=error shutting down connection: Transport endpoint is not connected (os error 107)
[  2513.846864826s] DEBUG outbound:accept{peer.addr=100.96.165.46:59222}: hyper::proto::h1::conn: error shutting down IO: Transport endpoint is not connected (os error 107)
[  2513.846901682s] DEBUG outbound:accept{peer.addr=100.96.165.46:59222}: linkerd2_app_core::accept_error: Connection failed error=error shutting down connection: Transport endpoint is not connected (os error 107)
[  2513.850849599s] DEBUG outbound:accept{peer.addr=100.96.165.46:59208}: hyper::proto::h1::conn: error shutting down IO: Transport endpoint is not connected (os error 107)
[  2513.850884422s] DEBUG outbound:accept{peer.addr=100.96.165.46:59208}: linkerd2_app_core::accept_error: Connection failed error=error shutting down connection: Transport endpoint is not connected (os error 107)
[  2513.853739401s] DEBUG outbound:accept{peer.addr=100.96.165.46:59220}: hyper::proto::h1::conn: error shutting down IO: Transport endpoint is not connected (os error 107)
[  2513.853776161s] DEBUG outbound:accept{peer.addr=100.96.165.46:59220}: linkerd2_app_core::accept_error: Connection failed error=error shutting down connection: Transport endpoint is not connected (os error 107)
[  2513.858409429s] DEBUG outbound:accept{peer.addr=100.96.165.46:59204}: hyper::proto::h1::conn: error shutting down IO: Transport endpoint is not connected (os error 107)
[  2513.858441947s] DEBUG outbound:accept{peer.addr=100.96.165.46:59204}: linkerd2_app_core::accept_error: Connection failed error=error shutting down connection: Transport endpoint is not connected (os error 107)
[  2513.858846575s] DEBUG outbound:accept{peer.addr=100.96.165.46:59202}: hyper::proto::h1::conn: error shutting down IO: Transport endpoint is not connected (os error 107)
[  2513.858876032s] DEBUG outbound:accept{peer.addr=100.96.165.46:59202}: linkerd2_app_core::accept_error: Connection failed error=error shutting down connection: Transport endpoint is not connected (os error 107)
[  2513.859488636s] DEBUG outbound:accept{peer.addr=100.96.165.46:59190}: hyper::proto::h1::conn: error shutting down IO: Transport endpoint is not connected (os error 107)
[  2513.859515744s] DEBUG outbound:accept{peer.addr=100.96.165.46:59190}: linkerd2_app_core::accept_error: Connection failed error=error shutting down connection: Transport endpoint is not connected (os error 107)
[  2513.861222773s] DEBUG outbound:accept{peer.addr=100.96.165.46:59210}: hyper::proto::h1::conn: error shutting down IO: Transport endpoint is not connected (os error 107)
[  2513.861250813s] DEBUG outbound:accept{peer.addr=100.96.165.46:59210}: linkerd2_app_core::accept_error: Connection failed error=error shutting down connection: Transport endpoint is not connected (os error 107)
[  2513.864235777s] DEBUG outbound:accept{peer.addr=100.96.165.46:59206}: hyper::proto::h1::conn: error shutting down IO: Transport endpoint is not connected (os error 107)
[  2513.864273443s] DEBUG outbound:accept{peer.addr=100.96.165.46:59206}: linkerd2_app_core::accept_error: Connection failed error=error shutting down connection: Transport endpoint is not connected (os error 107)
[  2513.869885070s] DEBUG outbound:accept{peer.addr=100.96.165.46:59218}: hyper::proto::h1::conn: error shutting down IO: Transport endpoint is not connected (os error 107)
[  2513.869923319s] DEBUG outbound:accept{peer.addr=100.96.165.46:59218}: linkerd2_app_core::accept_error: Connection failed error=error shutting down connection: Transport endpoint is not connected (os error 107)
[  2513.964976760s] DEBUG outbound:accept{peer.addr=100.96.165.46:59200}: hyper::proto::h1::conn: error shutting down IO: Transport endpoint is not connected (os error 107)
[  2513.965014138s] DEBUG outbound:accept{peer.addr=100.96.165.46:59200}: linkerd2_app_core::accept_error: Connection failed error=error shutting down connection: Transport endpoint is not connected (os error 107)
[  2513.965420175s] DEBUG outbound:accept{peer.addr=100.96.165.46:59212}: hyper::proto::h1::conn: error shutting down IO: Transport endpoint is not connected (os error 107)
[  2513.965447888s] DEBUG outbound:accept{peer.addr=100.96.165.46:59212}: linkerd2_app_core::accept_error: Connection failed error=error shutting down connection: Transport endpoint is not connected (os error 107)
[  2513.965487408s] DEBUG outbound:accept{peer.addr=100.96.165.46:59214}: hyper::proto::h1::conn: error shutting down IO: Transport endpoint is not connected (os error 107)
[  2513.965507360s] DEBUG outbound:accept{peer.addr=100.96.165.46:59214}: linkerd2_app_core::accept_error: Connection failed error=error shutting down connection: Transport endpoint is not connected (os error 107)
[  2514.57450943s] DEBUG outbound:accept{peer.addr=100.96.165.46:59216}: hyper::proto::h1::conn: error shutting down IO: Transport endpoint is not connected (os error 107)
[  2514.57490862s] DEBUG outbound:accept{peer.addr=100.96.165.46:59216}: linkerd2_app_core::accept_error: Connection failed error=error shutting down connection: Transport endpoint is not connected (os error 107)
[  2514.58965384s] DEBUG outbound:accept{peer.addr=100.96.165.46:59232}: hyper::proto::h1::conn: error shutting down IO: Transport endpoint is not connected (os error 107)
[  2514.58995567s] DEBUG outbound:accept{peer.addr=100.96.165.46:59232}: linkerd2_app_core::accept_error: Connection failed error=error shutting down connection: Transport endpoint is not connected (os error 107)
[  2514.65393799s] DEBUG outbound:accept{peer.addr=100.96.165.46:59234}: hyper::proto::h1::conn: error shutting down IO: Transport endpoint is not connected (os error 107)
[  2514.65431425s] DEBUG outbound:accept{peer.addr=100.96.165.46:59234}: linkerd2_app_core::accept_error: Connection failed error=error shutting down connection: Transport endpoint is not connected (os error 107)
[  2514.101488980s] DEBUG outbound:accept{peer.addr=100.96.165.46:59238}: hyper::proto::h1::conn: error shutting down IO: Transport endpoint is not connected (os error 107)
[  2514.101519104s] DEBUG outbound:accept{peer.addr=100.96.165.46:59238}: linkerd2_app_core::accept_error: Connection failed error=error shutting down connection: Transport endpoint is not connected (os error 107)
```

**Comment by dcodix** [comment]
So I had some time and I got back into this a bit. Gonna add some info here, some findings a possible explanation.

So, I think that the issue I am facing is a combination of nginx and linkerd-proxy both under quite a bit of connections.

So I observed that nginx sends `Connection: close` header on the request. When there is no linkerd-proxy in the middle, the response also has that header, and like that it always works, I see no 502s.

Now, when I add linkerd-proxy, nginx keep sending the `Connection: close` in the request headers, but linker-proxy is answering without that header. Now, being all this HTTP1.1, the connection defaults to `Connection: keep-alive`.

An extract of the RFC2616:
```
An HTTP/1.1 server MAY assume that a HTTP/1.1 client intends to maintain a persistent connection unless a Connection header including the connection-token "close" was sent in the request. If the server chooses to close the connection immediately after sending the response, it SHOULD send a Connection header including the connection-token close.

An HTTP/1.1 client MAY expect a connection to remain open, but would decide to keep it open based on whether the response from a server contains a Connection header with the connection-token close. In case the client does not want to maintain a connection for more than that request, it SHOULD send a Connection header including the connection-token close.
```

So, I understand that when linkerd-proxy receives a request with the header `Connection: close` it is instructed to close the connection right after responding. And it does, at TCP level I can see the FIN right after the HTTP response 200. Now, per the RFC, maybe linker-proxy should responde with that header (?) and maybe nginx is expecting it (?). 
Anyway, if nginx did receive the `Connection: close` should inmediatelly close the connection, and that happens when linker-proxy is not in the middle. When it doesn't get that header I am wondering if that is making nginx, from time to time (maybe depending on the puntual amount of requests) to try to reuse the connection, but given that linker-proxy already sent a FIN that connection might be half-closed (?)

Anyway, that theory might be only gibberish, but I found something that solves our issue. If I add to the ingress configmap:
```
  upstream-keepalive-connections: "0"
  upstream-keepalive-requests: "0"
```
I stop getting 502s.
What I intended with those lines is to force nginx to not reuse connections at all, and it seem it is making the trick for now. Altho, I don't like the idea of having to do this, because eventually it can become a different problem if we have too many connections and we can't reuse.

**Comment by ihcsim** [comment]
@dcodix If half-closed connection is the cause, then this sounds related to https://github.com/linkerd/linkerd2/issues/4276, specifically, https://github.com/linkerd/linkerd2/issues/4276#issuecomment-623015297. @adleong added a fix in https://github.com/linkerd/linkerd2/pull/4409, where you can use `linkerd inject --close-wait-timeout` to configure the TCP connection timeout.
