### ISSUE TITLE
Linkerd plugin for Spotify Backstage

### ISSUE THREAD

**Issue by Pothulapati** [linkerd/linkerd2#4955]
## Feature Request

[Backstage]() is an open platform for building developer portals that has a plugin model, allowing all kinds of UI/portals to be built for managing any kind of underlying infra/components/services. It seems to have a [growing ecosystem of plugins](https://backstage.io/plugins) being built.

The idea is to build a plugin for Linkerd on Spotify, allowing users to manage and observe Linkerd primitives and their applications. Currently, As Linkerd does not have a write dashboard (all our dashboards are read-only) and hence this can be a great project to allow that use-case.

**Comment by benjdlambert** [comment]
Hey! Core team from Backstage, and a contributor and long time user of linkerd here 👋 

I created an issue on our repo a while back thinking that this would be a good idea https://github.com/spotify/backstage/issues/633.

Part of Hacktoberfest I have hackweek starting Oct 5th, to work on something and I've love to make this integration happen. It would be awesome to get external contributors onboard to make this happen both from the linkerd and spotify/backstage community, so if you're interested in working together would be super cool to have you onboard!

**Comment by benjdlambert** [comment]
@Pothulapati I got my dates wrong, I'm going to start something on this next week, do you have some time next week?

**Comment by Pothulapati** [comment]
@benjdlambert :wave: I may not be able to spend some allocated time on this plugin but I'm happy to help in getting this started and along with the linkerd API (hoping backstage uses that API to fetch data, and provide UI abstraction). 

Feel free to jump into the [Linkerd slack](https://slack.linkerd.io/) for discussions. WDYT?

**Comment by benjdlambert** [comment]
Sure - I've been on that slack for a while, hiding in the background 👍  yeah, let's continue some of the discussion there, but I'd like to feedback to this or the https://github.com/spotify/backstage/issues/633 issue with progress. :+1:

**Comment by benjdlambert** [comment]
To give an update on this. I've been working on it with our hackdays. Hopefully will have something to show with a few more hours on it. Been waiting for a few other pieces to settle in Backstage first like the `k8s` support 👍
