### ISSUE TITLE
Session Stickiness only works with TLS backends

### ISSUE THREAD

**Issue by dschuldt** [linkerd/linkerd2#4956]
### What is the issue?

We have an linkerd-sidecar injected Ingress Controller (same behaviour with as well nginx as haproxy, linkerd related setup performed s.t. https://linkerd.io/2/tasks/using-ingress/) which terminates HTTPS connections. The connections to some of the upstream services are HTTPS as well, hence we use the annotation "haproxy.com/server-ssl: true" or "nginx.ingress.kubernetes.io/backend-protocol: HTTPS" for these. Since our services are stateful, we also use "haproxy.com/cookie-persistence: route" or "nginx.ingress.kubernetes.io/affinity: cookie" to enable cookie based session stickyness. The problem is, this only works for services with TLS, not for plaintext services. Here the cookie is set, but requests are forwarded to all the running pods.

### How can it be reproduced?

Deployment with replicas > 1; Ingress Controller with Linkerd Sidecars; Ingress with configured session affinity

#### `linkerd check` output

All linkerd checks passed

### Environment

- Kubernetes Version: v1.17.6 and v1.18.6
- Cluster Environment: Rancher RKE created
- Host OS: CentOS 7
- Linkerd version:  edge-20.6.4 and edge-20.9.1

Thanks in advance

**Comment by ihcsim** [comment]
Linkerd doesn't support session stickiness today. You will have to un-inject the Linkerd proxy from your ingress controllers, and let the ingress do their thing. There is an open issue at https://github.com/linkerd/linkerd2/issues/3504. Feel free to +1 that, and we can prioritize accordingly.

**Comment by olix0r** [comment]
I expect that the in-progress discovery changes (planned for stable-2.9) will allow this to work as expected; but we'll need to confirm this once these changes have landed on an edge release.

**Comment by dschuldt** [comment]
So the reason this works in our setup is due to the encrypted traffic (the l5d-dst-override header cannot be read by linkerd)?

I just tried it without the l5d-dst-override header on plaintext traffic. Now session stickiness works as well! Why is the header not necessary even if the documentation states this? (...This creates an infinite loop that can be pretty frustrating!....).

Thank you guys!

**Comment by dschuldt** [comment]
Ok, looks like the trafficsplit is not working without l5d-dst-override header

**Comment by ihcsim** [comment]
With an injected ingress controller, nothing will work if the `l5d-dst-override` header is missing. That's because the Linkerd relies on the `:authority` header to do service discovery. In that case of an ingress, the `:authority` is likely set to your external domain, resulting in the loop (as you observed).

As for why this only works for services with TLS, and not plaintext services, Linkerd can't MITM the encrypted traffic and will simply treat it as TCP, letting your ingress controller do what it wants with the traffic.

**Comment by olix0r** [comment]
This should be fixed in the [edge-20.10.3](https://github.com/linkerd/linkerd2/releases/tag/edge-20.10.3) release. Please let us know if you find any problems!

**Comment by dschuldt** [comment]
@olix0r 
Thanks for all the work on this topic. I can confirm session stickiness works now. 
But Am I missing something, or is traffic splitting just not possible? In #3504 you state 

> if the ingress targets a pod, the proxy will not override the balancer...

How can Traffic Splitting be achived when the service configured in the ingress spec is translated to pod endpoints?
