### ISSUE TITLE
Feature Request - Allow images to be pulled in a single command

### ISSUE THREAD

**Issue by vikas027** [linkerd/linkerd2#4964]
## Feature Request
It makes the deployment fast if the images are pre-cached on the instance.

### What problem are you trying to solve?
I am trying to make the linkerd development quicker on my VMs

### How should the problem be solved?
A command similar to this
```
kubeadm config images pull --kubernetes-version 1.18.8
```

Something like this maybe?
```
linkerd images pull --version 2.8.1
```

What do you want to happen? Add any considered drawbacks.

### Any alternatives you've considered?
A `for` loop :) 
```
for i in web controller proxy grafana; do
  docker pull gcr.io/linkerd-io/${i}:stable-2.8.1
done
docker pull gcr.io/linkerd-io/proxy-init:1.3.3
```

**Comment by cpretzer** [comment]
Hi @vikas027 the [bin](https://github.com/linkerd/linkerd2/tree/main/bin) directory includes several scripts to support developing and building Linkerd. I like the idea of using your `for` loop workaround as a script in the `bin` directory because, it's simple and effective.

Since the use case for this feature is specifically for development, I don't think the `linkerd` CLI is the right tool to pull images.

We'd love a PR, if you're interested in submitting one 😄

**Comment by vikas027** [comment]
Hey @cpretzer,

> Since the use case for this feature is specifically for development

The use case is not for development environment. I am on one of the team members who manage hundreds of AWS accounts for different teams and build AMIs for them. The teams do not have access to pull images from docker.io, so we have to give them AMIs pre-cached with docker images, the process of which is obviously automated.

Now, with every linkerd release, I will have to find out all the dependent docker images manually and then cache them into the AMI. I know the effort is not huge but good to have everything automated :) 

Can I find all the images needed by a linkerd release programmatically? If there is a way, my task is  done.

Thanks,
Vikas

**Comment by cpretzer** [comment]
@vikas027 thanks for clarifying the use case. I only saw the development use case in the OP 😄 

I have just what you're looking for to get the images programmatically:

`linkerd install --ignore-cluster | grep image: | sed -e 's/^ *//' | sort | uniq`

Credit goes to @wmorgan for that one 💥

**Comment by vikas027** [comment]
Cool, yeah that fulfils my need :)
