### ISSUE TITLE
annotation for DISABLE_PROTOCOL_DETECTION

### ISSUE THREAD

**Issue by sbvitok** [linkerd/linkerd2#4976]
Currently we have annotation **config.linkerd.io/skip-outbound-ports** for skip port redirect in init container.
But if I do not want skip port redirect but only DISABLE_PROTOCOL_DETECTION for server-speaks-first protocols on non standard port.
**linkerd2-proxy** have environment variables:
LINKERD2_PROXY_INBOUND_PORTS_DISABLE_PROTOCOL_DETECTION
LINKERD2_PROXY_OUTBOUND_PORTS_DISABLE_PROTOCOL_DETECTION
but proxy-injector have not annotation for setup variables for proxy container.
Even if setup config.linkerd.io/skip-outbound-ports annotation there is no environment variable in proxy container

**Comment by ihcsim** [comment]
@sbvitok This is being worked on under https://github.com/linkerd/linkerd2/issues/4950. Feel free to subscribe to it. Meanwhile, I'm closing this issue.
