### ISSUE TITLE
multicluster: Malformed health checks

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#4984]
While debugging another issue, I noticed that the multicluster healthchecks are malformed:

Cross-cluster checks appear to include a double-slash URI, `//health`:
```
[    13.865634665s] DEBUG ThreadId(13) inbound:http1: linkerd2_proxy_http::client: method=GET uri=http://probe-gateway-west:4181//health version=HTTP/1.1
```

The `health-local` checks are issued as HTTP/1.1 requests but do not include a `Host` header, which is a violation of the RFC.  I've adjusted the proxy to synthesize the host value in the URI from the destination socket, but this shouldn't be necessary. We should set a `Host` header on these requests (or issue HTTP/2 requests?)
```
[    14.484087168s] DEBUG ThreadId(02) inbound:http1: linkerd2_proxy_http::client: method=GET uri=http://10.42.0.32:8888/health-local version=HTTP/1.1
```

**Comment by olix0r** [comment]
Workaround here https://github.com/linkerd/linkerd2-proxy/pull/659

**Comment by zaharidichev** [comment]
> The health-local checks are issued as HTTP/1.1 requests but do not include a Host header, which is a violation of the RFC. I've adjusted the proxy to synthesize the host value in the URI from the destination socket, but this shouldn't be necessary. We should set a Host header on these requests (or issue HTTP/2 requests?)

@olix0r The local checks are issued by kubelet and at the moment we do not explicitly set any headers on readiness/livenes checks. And if I am not mistaken unless we do explicitly, there will be no host header set.

**Comment by olix0r** [comment]
@zaharidichev thanks for investigating! it shouldn't actually cause a problem, just a surprise.
