### ISSUE TITLE
Cannot disable opaque tcp port 3306  for MariaDB in kubernetes

### ISSUE THREAD

**Issue by xkbarkar** [linkerd/linkerd2#4990]
### What is the issue?
I have downloaded and installed linkerd2 
Client version: edge-20.9.3
Server version: edge-20.9.3  
And am trying to enable TLS termination for MARIADB connections on port 3306 , it looks like this port is hardcoded to be excluded from protocol detection as per
https://github.com/linkerd/linkerd2-proxy/blob/main/linkerd/app/src/env.rs#L243  
and I cannot find a way to disable this via configureable parameters 

### How can it be reproduced?
Install linkerd using edge-20.9.3 on a mysql/mariadb pod in kubernetes and try to enable tls on port 3306

### Environment

- Kubernetes Version: 1.15
- Cluster Environment: EKS
- Host OS: Amazon linux 2 
- Linkerd version: edge-20.9.3

**Comment by ihcsim** [comment]
Per conversation on slack, this is currently being worked on in #4938.
