### ISSUE TITLE
Use values from linkerd-config in check and inject

### ISSUE THREAD

**Issue by adleong** [linkerd/linkerd2#5009]
Depends on https://github.com/linkerd/linkerd2/issues/5008

The `linkerd check` and `linkerd inject` commands currently get their configuration by reading the `global`, `install`, or `proxy` files in the `ConfigMap/linkerd-config` resource.  They should read their configuration from the `values` file in this resource instead.  This will simplify the codebase overall and will allow us to remove the `global`, `install`, and `proxy` files.

**Comment by alpeb** [comment]
Done in #5023 (for check)  and #5036 (for inject)
