### ISSUE TITLE
Use linkerd-config-overrides in upgrade

### ISSUE THREAD

**Issue by adleong** [linkerd/linkerd2#5011]
Depends on https://github.com/linkerd/linkerd2/issues/5010

The `linkerd upgrade` command should read the linkerd-config-overrides secret to get the saved configuration of the cluster and preserve it during upgrade.  If this secret does not exist, it should fall back to reading the `global`, `install`, and `proxy` files from the `linkerd-config` ConfigMap.

https://github.com/linkerd/linkerd2/pull/5005 is a draft PR for this feature.

**Comment by alpeb** [comment]
This got finally addressed by #5005
