### ISSUE TITLE
API access to Prometheus URL

### ISSUE THREAD

**Issue by siggy** [linkerd/linkerd2#5030]
### What problem are you trying to solve?

Linkerd supports a custom `prometheusUrl` for the "Bring your own Prometheus" feature. We'd like to be able to retrieve this custom URL from outside Linkerd.

### How should the problem be solved?

We'd like an endpoint, perhaps within the Public API's `Config` endpoint or similar, to retrieve the customer Prometheus URL.

### Any alternatives you've considered?

Though this data is already available in the `linkerd-config` ConfigMap, reading that ConfigMap requires RBAC permissions across namespaces, which we'd like to avoid.

**Comment by adleong** [comment]
Any particular reason why we want to avoid using RBAC here?  In general, I like using RBAC to declare dependencies explicitly.  

We could make this easier by having Linkerd come with a ClusterRole for reading the config.  Any service account that wants to be able to read the config would then only need to create a RoleBinding.

**Comment by siggy** [comment]
We'd like to install our agent with as minimal permissions as possible. Our agent is currently configured with the linkerd namespace, specified by the user (which is how we find `linkerd-prometheus` today).

My understanding is if there were a `ClusterRole` in the `linkerd` namespace, our agent would either need to install a `RoleBinding` in the `linkerd` namespace, or install a `ClusterRoleBinding` in our agent's namespace.

https://kubernetes.io/docs/reference/access-authn-authz/rbac/#rolebinding-and-clusterrolebinding

**Comment by adleong** [comment]
My understanding is that if there is a `ClusterRole` for reading the configmap in the `linkerd` namespace, then your agent should just need a `RoleBinding` in its own namespace to bind to this cluster role.  (per https://medium.com/faun/kubernetes-rbac-use-one-role-in-multiple-namespaces-d1d08bb08286)

But I would need to verify this myself.

**Comment by siggy** [comment]
Interesting! I noticed in that example both the `ServiceAccount` and `ClusterRoleBinding` are in the same (default) namespace. If that's not a requirement, this could work!

**Comment by grampelberg** [comment]
I'm pretty sure the `RoleBinding` needs to end up in the target namespace. You could do a `ClusterRoleBinding` that is restricted by name to *just* that `ConfigMap` but I'm not sure that's an improvement.

Thinking through all the other interactions, having this as an endpoint will end up requiring a `NetworkPolicy` today and a traffic policy something in the future. What's easier for you to include `NetworkPolicy` or some kind of role binding? I suspect you'll need a policy no matter what to connect to the prometheus in question ...

**Comment by adleong** [comment]
Just tested this and indeed, it requires creating a `ClusterRoleBinding` for the agent to grant cross-namespace permissions.

```
➜  test k get clusterrole/linkerd-config -o yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRole","metadata":{"annotations":{},"name":"linkerd-config"},"rules":[{"apiGroups":[""],"resourceNames":["linkerd-config"],"resources":["configmaps"],"verbs":["get"]}]}
  creationTimestamp: "2020-10-01T17:29:56Z"
  name: linkerd-config
  resourceVersion: "94627433"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterroles/linkerd-config
  uid: 3350209e-fd70-4ba2-905a-c181fc5e9bae
rules:
- apiGroups:
  - ""
  resourceNames:
  - linkerd-config
  resources:
  - configmaps
  verbs:
  - get
➜  test k get clusterrolebinding/obama-linkerd-config -o yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRoleBinding","metadata":{"annotations":{},"name":"obama-linkerd-config"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"ClusterRole","name":"linkerd-config"},"subjects":[{"kind":"ServiceAccount","name":"obama","namespace":"alex"}]}
  creationTimestamp: "2020-10-01T17:46:42Z"
  name: obama-linkerd-config
  resourceVersion: "94634263"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterrolebindings/obama-linkerd-config
  uid: 0ea937c0-d580-4af2-ac91-88cca3485b55
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: linkerd-config
subjects:
- kind: ServiceAccount
  name: obama
  namespace: alex
➜  test k --as system:serviceaccount:alex:obama auth can-i get configmaps/linkerd-config
yes
```

**Comment by adleong** [comment]
I don't think we want to provide a wide open HTTP or gRPC api for this.  The values struct in the `linkerd-config` configmap is the canonical source of truth for configuration like this.  Anyone who wishes to read this configuration should be granted the appropriate RBAC to do so.
