### ISSUE TITLE
proxy: Add client_id label to tcp_open_total metric

### ISSUE THREAD

**Issue by alpeb** [linkerd/linkerd2#5031]
In order to have `linkerd edges` return non-empty values for a connection's `CLIENT_ID` in the case of TCP connections, the proxy's `tcp_open_total` metric needs to include the `client_id` label for inbound connections, like the `request_total` one for http connections does.

Ref #4999

**Comment by olix0r** [comment]
Ah yeah, for inbound tcp metrics we only seem to include a boolean.
```
tcp_open_total{peer="src",direction="inbound",tls="true"} 9
```

**Comment by hawkw** [comment]
Okay, I've added `client_id` labels to the `tcp_open_total` metric, but `linkerd edges` is still not showing TCP (MySQL) connections. Is that expected --- does this also require a CLI change to actually consume this data?

**Comment by hawkw** [comment]
(I realize this issue never actually says "adding this label will make TCP connections show up in `linkerd edges`, so I may have misinterpreted it a bit...)

**Comment by alpeb** [comment]
Thanks @hawkw , this still requires a change in the control plane. I can take care of that. Can you push a proxy image I can use with this change?

**Comment by hawkw** [comment]
> Thanks @hawkw , this still requires a change in the control plane. I can take care of that. Can you push a proxy image I can use with this change?

`mycoliza/l2-proxy:dev-3e7430d4-eliza` (on DockerHub)
