### ISSUE TITLE
Linkerd config  refactor test plan

### ISSUE THREAD

**Issue by zaharidichev** [linkerd/linkerd2#5045]
## Clean install (cli)
**Install Linkerd via the CLI and verify that:**
- [x] `check` works from CLI (with some addon custom config like disabling prom)
- [x] `check` works from WEB (with some addon custom config like disabling prom)
- [x] `configmap/linkerd-config` is present and reflects custom config options
- [x] `secret/linkerd-config-overrides` is present and reflects custom config options
- [x] control plane  components take all configuration options as flags

## Clean install (Helm)
**Install Linkerd via Helm and verify that:**

- [x] `check` works from CLI
- [x] `check` works from WEB
- [x] `configmap/linkerd-config` is present and reflects custom config options
- [x] `secret/linkerd-config-overrides` is non present
- [x] control plane  components take all configuration options as flags

## Upgrade (Helm + CLI) 
- [x] 2.7.1 -> main: ensure that the overrides are correctly from the config proto structure and populated
- [x] main install -> upgrade: the upgrade should use the overrides created during install

## Injection (Helm + CLI) 
- [x] automatic injection works (exercise each annotation config option)
- [x] manual injection works (exercise each cmd line config option)
- [x] ensure that inslatt proxy config flags are applied for all injected workfloads unless overriden on any level (namespace, deployment pod template, CLI inject flags)

## Misc
- [x] Match README config options with the code (verify defaults, etc...)

**Comment by zaharidichev** [comment]
cc @Pothulapati @adleong @admc feel free to suggest changes to the approach

**Comment by adleong** [comment]
The proxy injector depends on `configmap/linkerd-config` and will not work correctly if it is removed.  

We should also test upgrading with Helm.

We also have two different upgrade paths that both need to be tested:

* An install -> upgrade which occurs with the code on main
  * The upgrade will use the values override which were created during the install
* stable 2.7.1 -> main
  * The stable 2.7.1 install will not have a values override and we'll need to test that the settings are correctly loaded from the config proto
