### ISSUE TITLE
 2.9 - regression test plan

### ISSUE THREAD

**Issue by Pothulapati** [linkerd/linkerd2#5051]
- [ ] scale testing
  - deploy emojivoto to 10 namespaces (with identity)
  - deploy books to 10 namespaces (with identity) / or find a way to get to 100+ services
  - scale each deployment to 10 replicas
  - increase total traffic to 1000 rps
- [x] HA Testing
  - Perform a HA Install/Upgrade.
  - Scale the cluster Up and Down. _(Especially on the nodes on which control-plane components exist.)_
- [x] ingress testing
  - inject nginx-ingress controller
  - send 100k bad domains at it
  - send 100 rps traffic back to emojivoto deployment
  - Test Ingress with no overridde anotations
- [x] functionality testing
  - tracing
  - service profiles (timeouts, retries) for both HTTP and gRPC
  - edges
- [x] cluster version
  - K8s 1.13, 1.14, 1.15, 1.16, 1.17, 1.18, 1.19
- [x] upgrade testing
  - Upgrade from 2.8 to 2.9
  - Upgrade from 2.8.1 to 2.9
  - Upgrade from Edge 20.10.x to a 2.9 tag
  - Monitor error rates and verify that the upgrade notes do not introduce any downtime

**Comment by Pothulapati** [comment]
Kubernetes Cluster Testing is done by creating the latest kubernetes cluster on Kind with versions ranging from `1.13.x` to `1.19.x` (where x is the latest minor release) and running the deep integration tests on top.

Tthings work smoothely except for `1.19.1` where the SMI-Metrics Integration test fails which is being fixed by https://github.com/servicemeshinterface/smi-metrics/pull/75 (This is a SMI-Metrics bug not that of Linkerds)

**Comment by Pothulapati** [comment]
Ingress Testing is marked as completed by doing the following:
- Nginx Ingress with header overrides
   - Sent 100k requests with correct host header
   - Sent 100k requests with incorrect host header
- Nginx INgress without header overrides _(possible with the new TCP Loadbalancing)_
   - Sent 100k requests with correct host header
   - Sent 100k requests with incorrect host header

Findings:
- Most requests completed succesfully and the proxy never restarted.
- I was able to see around 5k requests being marked as `TLS detection timeout` out of the 100k. My guess is that its because of the limitation of resources. WDYT?

**Comment by adleong** [comment]
Tested HA by installing Linkerd in HA mode on a 3 node cluster, scaling up to 5 nodes, then scaling back to 3.  At all times the control plane components remained on distinct nodes and `linkerd check` continuously passed.

**Comment by kleimkuhler** [comment]
I upgraded to `edge-20.10.4` from `stable-2.8.0`, `stable-2.8.1` and `edge-20.10.3` without issue.

I had Emojivoto installed for each upgrade and noticed no increased error rates or downtime.

**Comment by Pothulapati** [comment]
I meshed multiple demo apps (`emojivoto`, `booksapp`, `booksinfo`, `kuma-demo`) and was able to verify  `edges`, `routes` working as expected.

I verified `ServiceProfiles` with retries and timeouts as [per the doc](https://linkerd.io/2/tasks/books/#service-profiles). We also found that [they do not with Headless services ](https://github.com/BuoyantIO/booksapp/blob/main/k8s/mysql-app.yml) but that is not planned for 2.9
