### ISSUE TITLE
BUILD.md build architecture outdated

### ISSUE THREAD

**Issue by GMarkfjard** [linkerd/linkerd2#5063]
### What problem are you trying to solve?
Looking at the BUILD.md file it seems that the Build Architecture graph is outdated. The graph originates from one single workflow.yml file but in reality several files exists.

### How should the problem be solved?

Update the graph to properly display what happens in the build workflow.

### Any alternatives you've considered?

N/A

### How would users interact with this feature?

Gain knowledge about how the build architecture actually works, helping further development.

**Comment by alpeb** [comment]
It is indeed outdated. @GMarkfjard would you be up for a PR fixing it? There is fame and karma to be gained :slightly_smiling_face:  I can provide some guidance if needed :wink:

**Comment by GMarkfjard** [comment]
@alpeb Absolutely, I've been wandering around those files anyhow. Plus, fame and karma is something you can't have enough of! 🎸

**Comment by alpeb** [comment]
@GMarkfjard Are you still interested in taking care of this one?

**Comment by GMarkfjard** [comment]
> @GMarkfjard Are you still interested in taking care of this one?

I sure am! Just haven't gotten around to it just yet :)
