### ISSUE TITLE
TCP mTLS test plan

### ISSUE THREAD

**Issue by hawkw** [linkerd/linkerd2#5066]
- Inbound stack tests
  - [ ] inbound conns still work when profile resolution is slow
  - [ ] basic "everything works" with an incoming tcp conn
  - [ ] profile lookups are cached per original dest IP
  - [ ] no profile lookups outside of search nets

- Outbound stack tests
  - [ ] tcp traffic splits work
  - [x] tcp load balancing works
  - [x] tls when hinted
  - [x] no tls when not hinted
  - [x] adding/removing tcp endpoints from the lb
  - [x] profile lookups are cached per original dest IP (we have an integration test for this)
  - [x] dst lookups are cached per original dest IP
  - [x] no profile lookups outside of search nets
  - [ ] ~~opaque protocols~~

**Comment by hawkw** [comment]
cc @olix0r --- anything major missing?

**Comment by hawkw** [comment]
AFAIK we don't actually handle `opaque_protocol` hints on profiles in the proxy yet. When that's implemented, it will need tests as well.

**Comment by grampelberg** [comment]
@hawkw is there any more work here before 2.9 ships? It sounds like we're still going to want to do some work here, but it'd be in the 2.10 timeframe.
