### ISSUE TITLE
Proxy-injector up but pods not meshed

### ISSUE THREAD

**Issue by oceaneLonneux** [linkerd/linkerd2#5070]
### What is the issue?
Hello! We are having issues with keeping the pods meshed and sending metrics. As adviced previously, we have put a PriorityClass (Name: high-priority, Value: 1000000) and the pod is QoS : Guaranteed. But we still have to do kubectl rollout restart deploy after each scale down (which we do every night). Thank you for your help!

More details:
We have an annotation in our deployment linkerd.io/inject: enabled. 
The pods are all meshed and sending metrics (we have done kubectl rollout restart), then the cluster scale down at night(from 15 nodes to 1) therefore most pods will not be viable anymore. During that scale down, the linkerd-proxy-injector most of the time dies then get brought back right away. 
In the morning, the scale up happens and all the pods go back (the linkerd proxy injector is still up). However, they are not sending metrics (and we can see on linkerd dashboard 0/2).

### How can it be reproduced?
Add annotation to pods
kubectl rollout restart
scale down the cluster

#### `linkerd check` output
Everything is green except:
```
control-plane-version
---------------------
‼ control plane is up-to-date
    is running version 2.7.0 but the latest stable version is 2.8.1
    see https://linkerd.io/checks/#l5d-version-control for hints
‼ control plane and cli versions match
    control plane running stable-2.7.0 but cli running stable-2.8.1
    see https://linkerd.io/checks/#l5d-version-control for hints

linkerd-addons
--------------
‼ 'linkerd-config-addons' config map exists
    configmaps "linkerd-config-addons" not found

Status check results are √
```

### Environment

- Kubernetes Version: 1.17 
- Cluster Environment: EKS
- Host OS: Linux
- Linkerd version: Server version: stable-2.7.0

### Possible solution
Once the pods are meshed and sending metrics, they continue doing so even if the pods die.

**Comment by Pothulapati** [comment]
@oceaneLonneux It's hard to understand the problem without knowing enough information i.e logs, scale, etc. Also, Why not use the `stable-2.8.1` as it can have some big fixes which might fix this?

It would be awesome to have the proxy-injector logs. Also, If you are running a modelrately scaled cluster, The advice is to install [Linkerd with HA](https://linkerd.io/2/features/ha/)

**Comment by oceaneLonneux** [comment]
Thanks for answering @Pothulapati ! We will try installing that version.

**Comment by Pothulapati** [comment]
@oceaneLonneux Any updates? Will be happy to close the issue, if upgrading to the latest version fixed the issue.

**Comment by Pothulapati** [comment]
Closing this because of the staleness, Feel free to reopen if you are still facing the issue!
