### ISSUE TITLE
Track ReplicaSet stats within a Deployment

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#508]
Deployments manage one or more ReplicaSets.  When a Deployment is [updated](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#updating-a-deployment), for instance, a new ReplicaSet is created and a rolling update is executed.

Currently, we only track Deployments, losing the information about individual rollouts within a deployment.

We should support querying metrics by ReplicaSet, and the UI should list replicasets within a Deployment.

**Comment by siggy** [comment]
Note we may be able to satisfy this requirement via Kubernetes' `pod-template-hash-label`:
https://github.com/runconduit/conduit/pull/605#issuecomment-375772081
