### ISSUE TITLE
linkerd edges for all-namespaces reports less than for specific namespace

### ISSUE THREAD

**Issue by pankajmt** [linkerd/linkerd2#5080]
### What is the issue?
we had 
linkerd edges deployment -o wide -n apps-sim --cni-namespace infra-linkerd-cni --linkerd-namespace infra-linkerd report quite a few entries
but
linkerd edges deployment -o wide -A --cni-namespace infra-linkerd-cni --linkerd-namespace infra-linkerd (and --all-namespaces) not report any

### How can it be reproduced?
was with our setup, but should be easy to reproduce. gke cluster with linkerd-cni and linkerd. can provide more info as needed. 

### Logs, error output, etc

(If the output is long, please create a [gist](https://gist.github.com/) and
paste the link here.)

#### `linkerd check` output

```text
your output here ...
```

### Environment

- Kubernetes Version: v1.16.13-gke.401
- Cluster Environment: (GKE, AKS, kops, ...) GKE
- Host OS: Container OS
- Linkerd version: Stable 2.8.1

**Comment by grampelberg** [comment]
@alpeb you just did a large update of this command. Does it have the same limitations?

**Comment by alpeb** [comment]
Yes, the bug is still there
