### ISSUE TITLE
controllerLogLevel - Chart values incorrectly documenated

### ISSUE THREAD

**Issue by shaikatz** [linkerd/linkerd2#5092]
https://github.com/linkerd/linkerd2/blob/827646a3e107fc1b048dc8a8f830f640270ba7f6/charts/linkerd2/templates/controller.yaml#L79

The chart readme values table shows `controllerLogLevel` while it actually under global at usage.

**Comment by grampelberg** [comment]
@alpeb how does the readme get updated?

**Comment by alpeb** [comment]
It's currently purely manual. #4156 is tracking what's needed to make it automated.
