### ISSUE TITLE
Can't use Helm for installing multicluster access credentials

### ISSUE THREAD

**Issue by alpeb** [linkerd/linkerd2#5098]
[The multicluster installation doc](https://github.com/linkerd/website/pull/782/files#diff-fae783921db4c9259ab03260024736ceb39c4f77feca6a5c46d79e1d7b98930fR343) describes a workflow for installing the RBAC to grant access for a source cluster to access the current (target) cluster through Helm:
```
helm install linkerd2-mc-source linkerd/linkerd2-multicluster --set gateway=false --set remoteMirrorServiceAccountName=source --set installNamespace=false --kube-context target
```
This reuses the same `linkerd2-multicluster` chart that was used for installing the multicluster components, stripping off the gateway. But that command results in the following error:
```
Error: rendered manifests contain a resource that already exists. Unable to continue with install: CustomResourceDefinition "links.multicluster.linkerd.io" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "linkerd2-mc-source": current value is "linkerd2-multicluster"
```
Even after moving the CRD into `templates/crds` and using `--skip-crds` the error persists, because apparently this way of reusing charts to generate different Helm "releases" in the same cluster is not allowed.

One possible way around this would be to separate that RBAC into its own separate chart, to be used directly in this scenario when setting up additional access, and indirectly when installing the multicluster component to provide the default access.

**Comment by alpeb** [comment]
We currently have two charts for multicluster: `linkerd2-multicluster` and `linkerd2-multicluster-link`. Since `linkerd mc link` can't really be replaced with a helm command, separating `linkerd2-multicluster-link` into its own chart probably doesn't make sense. So we could merge that into `linkerd2-multicluster` and then spin off into a separate chart the RBAC stuff.

**Comment by adleong** [comment]
Good catch, @alpeb.  I don't think this workflow of installing potentially several different access credentials is well suited to Helm.  Even if these credentials were in their own Helm chart, does Helm support installing multiple copies of the same chart?

My preference is that people who want to do this workflow should use the `linkerd mc allow` CLI command (potentially saving the output if doing gitops).

A more long term solution for supporting this workflow with Helm would be to allow users to specify a list of service accounts in the Values of the multicluster install chart.

**Comment by alpeb** [comment]
Helm does support installing multiple copies of the same chart as long as you name the releases differently (apparently a problem occurs only when a CRD is in play). Supposing we name this new chart `linkerd2-multicluster-allow` it'd look something like this:
```
$ helm install linkerd2-multicluster-creds-one --set remoteMirrorServiceAccountName=one charts/linkerd2-multicluster-allow
NAME: linkerd2-multicluster-creds-one
LAST DEPLOYED: Tue Oct 20 14:41:51 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None

$ helm install linkerd2-multicluster-creds-two --set remoteMirrorServiceAccountName=two charts/linkerd2-multicluster-allow
NAME: linkerd2-multicluster-creds-two
LAST DEPLOYED: Tue Oct 20 14:42:12 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None

$ helm ls
NAME                            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                                   APP VERSION
linkerd2                        default         1               2020-10-20 14:38:58.174048711 +0000 UTC deployed        linkerd2-0.1.0                          edge-XX.X.X
linkerd2-mc                     default         1               2020-10-20 14:40:10.313387409 +0000 UTC deployed        linkerd2-multicluster-0.1.0             edge-XX.X.X
linkerd2-multicluster-creds-one default         1               2020-10-20 14:50:18.288462076 +0000 UTC deployed        linkerd2-mulicluster-allow-0.1.0        edge-XX.X.X
linkerd2-multicluster-creds-two default         1               2020-10-20 14:50:28.962469612 +0000 UTC deployed        linkerd2-mulicluster-allow-0.1.0        edge-XX.X.X
```
Contrast this with the alternative approach of setting multiple SA in a single variable; in that case we'd do something like `helm get values linkerd2-multicluster-creds` to retrieve the list of those SA :thinking:
