### ISSUE TITLE
Removal of TCP connect timeout

### ISSUE THREAD

**Issue by seanmonstar** [linkerd/linkerd2#511]
We'd like to remove the TCP connect timeout, and allow that to be determined entirely by application rules (when a client gives up on a TCP connect, then we do too). However, there's an [issue we need to solve first](https://github.com/runconduit/conduit/pull/487#issuecomment-370518127), otherwise we can leak connections:

> Due to the way futures work, we'd need to be careful that the steps between receiving a connection and piping on the other side have polled for read (well, HUP, but we can't ask for that directly at the moment), and then notice that the task was woken up because of the HUP. It's, uh, actually a bit tricky.

While we are waiting on the connect event to complete, we need some way of registering with the current task that we also care if the incoming TCP socket hangs up. We can't do that with a read, since don't want to read data yet, and we have nothing to write. We also can't really use a peek, since once the first peek succeeds, it will always be successful, as we aren't taking those bytes out of the buffer.

This perhaps needs some way for us to register that we are interested in a `EPOLLHUP`, and when the future is woken up, a way to ask the socket if it indeed hung up besides a read or write. The current code is generic over `AsyncRead + AsyncWrite`, so we either need to get support from mio and then tokio, **OR** we could plug in plumbing manually, by using our `connection::Connection` type.

cc @carllerche

**Comment by briansmith** [comment]
Let's say we get notified of `EPOLLHUP` on the inbound connection. Then we want to close the outbound connection. But first we need to send all the outstanding data from the inbound connection to the outbound connection. But, we're blocked on `connect()` indefinitely. Won't we still need some timeout? In particular, wouldn't we need to keep the timeout, but start the timer from the time we receive `EPOLLHUP` instead of from the time we called `connect()`?

**Comment by olix0r** [comment]
@briansmith 

> But first we need to send all the outstanding data from the inbound connection to the outbound connection.

What outstanding data? AIUI, we will not read any data from the server connection until the client connection is established.  So if the server connection is lost before the client connection is established, the application should have no expectation that data was read before it closed the connection.

**Comment by seanmonstar** [comment]
Perhaps for fire-and-forget? The application will see they've successfully connected (to the proxy), and could write some data, and then close up, not caring about any response?

**Comment by briansmith** [comment]
> Perhaps for fire-and-forget? The application will see they've successfully connected (to the proxy), and could write some data, and then close up, not caring about any response?

Right.

Ideally we wouldn't `accept()` the incoming connection until `connect()` has completed on the outgoing connection. However, I don't think we can know which IP address to `connect()` to without `accept()`ing the incoming connection and using SO_ORIGINAL_DST, so I don't know how to implement `accept-after-connect` semantics.
