### ISSUE TITLE
2.9 - release documentation

### ISSUE THREAD

**Issue by admc** [linkerd/linkerd2#5112]
In order to get 2.9 out the door, we need to make sure that proper documentation exists for each new, or updated feature are delivered. If it exists, go through it with the latest RC make sure it works as expected, update anything new or changed. If there are bugs, log them!

- [x] Upgrade docs (Alejandro)
- [x]  New Ingress Mode  (Tarun)
- [x] TCP mTLS (Eliza)
    - [x] Update `features/automatic-mtls`
- [x] Multicluster (Alejandro)
    - [x] Helm install/upgrade
- [ ] Bring your own prometheus (Kevin)
- [x] ARM64 (Alex)
- [x] Improved HA (Alex)
- [x] Config overrides (Zahari)
- [ ] Service topologies (Charles)
- [ ] Cert-manager improvements (webhook certificates) (Alex)
- [x] Addons (Tarun)
- [ ] Multithreaded proxy (eliza)

**Comment by adleong** [comment]
Arm documentation addressed here: https://github.com/linkerd/website/pull/830

**Comment by adleong** [comment]
Improved HA (No new documentation needed)

**Comment by alpeb** [comment]
Multicluster docs have been reviewed at linkerd/website#782, that'll get merged when 2.9 is out

**Comment by hawkw** [comment]
Updated the mTLS docs: linkerd/website#836 (could use a review)

**Comment by alpeb** [comment]
Upgrade notes PR: linkerd/website#841

**Comment by Pothulapati** [comment]
Ingress Docs PR: https://github.com/linkerd/website/pull/840

**Comment by Pothulapati** [comment]
Tracking Add-On Docs: https://github.com/linkerd/website/issues/801#issuecomment-717357752

**Comment by kleimkuhler** [comment]
Headless services notes: linkerd/website#842

**Comment by kleimkuhler** [comment]
BYOP docs: linkerd/website#843
