### ISSUE TITLE
Change of reconnection behavior since stable-2.8.1

### ISSUE THREAD

**Issue by alpeb** [linkerd/linkerd2#5124]
### What is the issue?

When the service that some client pod points to gets deleted and then recreated a few seconds later, the client can't connect again to the service (when there's some client connection caching involved as explained in Workarounds below).

### How can it be reproduced?

- Install linkerd and then emojivoto injected
- Tail `vote-bot`'s linkerd-proxy logs
- Delete the `web-svc` service
- You'll see log entries like
```
[     0.199142869s]  INFO ThreadId(06) daemon:identity: linkerd2_app: Certified identity: default.emojivoto.serviceaccount.identity.linkerd.cluster.local
[     0.819620556s]  INFO ThreadId(02) outbound:http{v=1.x}:logical{dst=web-svc.emojivoto.svc.cluster.local:80}:concrete{addr=web-svc.emojivoto.svc.cluster.local:80}: linkerd2_proxy_api_resolve::resolve: No endpoints
[    47.845152380s]  INFO ThreadId(03) outbound:http{v=1.x}:logical{dst=web-svc.emojivoto.svc.cluster.local:80}:concrete{addr=web-svc.emojivoto.svc.cluster.local:80}: linkerd2_proxy_api_resolve::resolve: No endpoints
[    47.848772248s]  INFO ThreadId(04) outbound:http{v=1.x}:logical{dst=web-svc.emojivoto.svc.cluster.local:80}:concrete{addr=web-svc.emojivoto.svc.cluster.local:80}: linkerd2_proxy_api_resolve::resolve: No endpoints
[    51.331380681s]  WARN ThreadId(04) outbound:http{v=1.x}: linkerd2_app_core::errors: Failed to proxy request: Service in fail-fast
[    52.332371659s]  WARN ThreadId(05) outbound:http{v=1.x}: linkerd2_app_core::errors: Failed to proxy request: Service in fail-fast
```
- Wait a few seconds and recreate it
- `vote-bot` won't be able to reconnect and you'll continue seeing the `Service in fail-fast` warnings

The only way to have `vote-bot` connect again is to bounce its pod.

### Environment

- Reproduceable with `edge-20.10.3`, not with `stable-2.8.1`
- Kubernetes Version: 1.18.2
- Cluster Environment: kind

### Workaround

Note this doesn't happen when using a simple client such as `while true; curl http://web-svc.emojivoto.svc.cluster.local/api/list; done`.
In `vote-bot` the [http client is reused](https://github.com/BuoyantIO/emojivoto/blob/main/emojivoto-web/cmd/vote-bot/main.go#L27) and it seems the issue happens because of some kind of connection caching; if I force fast timeouts there through `client = &http.Client{Transport: &ochttp.Transport{}, Timeout: 1 * time.Second}` the connections are reestablished fine.
The odd thing is that this wasn't required in `stable-2.8.1`.

**Comment by adleong** [comment]
Using the `destination-client` to connect directly to the destination service and watch a service, we notice the following behavior when the service is deleted and then re-created:

```
INFO[0000] Add:
INFO[0000] labels: map[namespace:emojivoto service:web-svc]
INFO[0000] - 10.8.2.23:8080
INFO[0000]   - labels: map[control_plane_ns:linkerd deployment:web pod:web-6cbc9fd499-fmwgp pod_template_hash:6cbc9fd499 serviceaccount:web]
INFO[0000]   - protocol hint: H2
INFO[0000]   - identity: dns_like_identity:{name:"web.emojivoto.serviceaccount.identity.linkerd.cluster.local"}
INFO[0000]
INFO[0026] NoEndpoints:
INFO[0026] - exists:false
INFO[0026]
INFO[0026] NoEndpoints:
INFO[0026] - exists:false
INFO[0026]
```

We see the `NoEndpoints` message from when the service is deleted, but no further updates when the service is re-created.  Issuing a new request to the destination controller for that service shows the correct endpoints but the existing resolution stream appears to be stuck and never recovers.

**Comment by olix0r** [comment]
I'd bet there's another bug here, as well: traffic splits changes would not be updated on this recreated service.

We'd need to ensure that, when the profile is discovered by IP and the service is recreated, that the watch does not stall out.

To function correctly, we need one of the following to happen:

1. The watch follows the service instead of the IP. When the service is recreated, we get profile updates for it; or
2. When the service is deleted, the profile stream could fail in a way that signals the proxy should consider the cached service defunct. My recommendation would be to return the `NOT_FOUND` status code (and we'd have to update the proxy to handle this).

I think the latter would be the more robust choice, and it would be suitable in the endpoints lookup case as well. (On older proxy versions, we'll simply retry the watch in this case and pick up new stream updates).

**Comment by adleong** [comment]
Fixed by https://github.com/linkerd/linkerd2/pull/5126
