### ISSUE TITLE
Consider disabling H2 upgrading by default

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#5136]
Benchmarks indicate that our h2 client uses substantially more CPU than a pure HTTP/1 client. Assuming this is confirmed by in-cluster tests, we should consider changing this default for the stable-2.9 release, so that we do not transport HTTP/1 requests over HTTP/2 connections.

Before making this change, though, we should confirm that this works as expected with multicluster configurations. We'd want to confirm that gateways properly handle requests from HTTP/1 proxy connections.

**Comment by alpeb** [comment]
With H2 upgrading is disabled the connections aren't going through. This is what linkerd-proxy on the target gateway is logging:
```
WARN ThreadId(02) inbound:accept{peer.addr=10.36.0.1:54825 target.addr=10.36.0.33:4143}:http{v=1.x}: linkerd2_app_core::errors: Failed to proxy request: no authority
```
