### ISSUE TITLE
Manually Test TCP mTLS

### ISSUE THREAD

**Issue by adleong** [linkerd/linkerd2#5138]
Perform manual testing of an application that uses non-HTTP TCP communication and ensure that, when meshed, this traffic is encrypted with mTLS.

**Comment by olix0r** [comment]
Note that you can probably use the `ghcr.io/olix0r/init-net-test:v6` proxy image for this (from https://github.com/olix0r/init-net-test)

**Comment by adleong** [comment]
After manually testing with the above, everything worked as expected:

* The `linkerd edges po` command showed the edge as secured
* When the server was scaled up, each replica of the server received traffic, as seen by the server's `tcp_write_bytes_total` metric
* When the server was divided into two services and a traffic split was set up between them, traffic was divided between the leaf services as expected, as seen by the server's `tcp_write_bytes_total` metric
