### ISSUE TITLE
Support `install --config -`

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#5156]
The `install --config` flag should accept `-` as a value to indicate that it should read from stdin, similarly to `kubectl apply -f -`

This can be accomplished by passing `--config /dev/stdin`, but `-` has a nicer "feel" ;)

**Comment by cpackingham** [comment]
Hey @olix0r, could I pick this one up?

**Comment by Pothulapati** [comment]
@cpackingham Feel free to take it up! You should probably do something like  https://github.com/linkerd/linkerd2/blob/2b0482c82188ffc48b07abd74cdb18877df41c3a/cli/cmd/inject_util.go#L145 that we already use at inject, upgrade, etc.

**Comment by dominikbraun** [comment]
I'd take this one up if @cpackingham currently isn't working on it.

**Comment by adleong** [comment]
Thanks for your interest, @dominikbraun, but actually I think this is already done.  The `--config` flag has been renamed to `--values` and now correctly supports specifying `-` for stdin.
