### ISSUE TITLE
Validate that cpu-limit actually restricts proxy CPU allocations

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#5165]
Anecdotally (in k3d) I've noticed that when setting a proxy cpu limit of "1", the proxy can still consume many cores worth of resources. The proxy detects its number of available cores via the [`num-cpus`](https://github.com/seanmonstar/num_cpus) crate, which should be cgroups-aware...

We should validate that CPU limits actually limit the proxy's thread allocations, as this could potentially have a deleterious effect on latency, in particular.

**Comment by olix0r** [comment]
@grampelberg suggests that this is actually controlled by cpu _requests_ (and not necessarily limit) -- either way, we should test and validate the behavior as we write docs for it.

**Comment by alpeb** [comment]
From my understanding of the [cpu management docs](https://kubernetes.io/docs/tasks/administer-cluster/cpu-management-policies/) the number of cpus are not surfaced in cgroups unless the pod has a QoS of type "Guaranteed" and the kubelet management policy is `static` (the default being `none`).

```
$ k3d cluster create --k3s-server-arg '--kubelet-arg=kube-reserved=cpu=1' --k3s-server-arg '--kubelet-arg=cpu-manager-policy=static'
...
$ linkerd install | kubectl apply -f -
...
$  kubectl -n linkerd exec -ti linkerd-controller-xxxx -c linkerd-proxy sh
# inside the proxy container (my machine has 12 virtual CPUs)
$ cat /sys/fs/cgroup/cpuset/cpuset.cpus
0,2-5,7-11
$ exit

# now I edit the deployment so that all the containers end up with the same CPU/mem requests/limits, which turns the pod into QoS "Guaranteed"
$ kubectl -n linkerd edit deploy linkerd-controller
...
# I log again into the proxy container and cgroups exposes just one core:
$  kubectl -n linkerd exec -ti linkerd-controller-xxxx -c linkerd-proxy sh
# inside the proxy container (my machine has 12 virtual CPUs)
$ cat /sys/fs/cgroup/cpuset/cpuset.cpus
0
```

**Comment by hawkw** [comment]
Hmm, looking at the docs @alpeb linked, that does appear to be the case. 

This makes me wonder if we want to expose the `LINKERD2_PROXY_CORES` env var @olix0r added in linkerd/linkerd2-proxy#733 as an annotation and/or have the proxy injector set a default value for it when the pod doesn't have proxy CPU requests/limits? Otherwise, when the kubelet isn't configured with `cpu-manager-policy=static`, we might see proxies spawning unexpectedly large pools of worker threads.

**Comment by olix0r** [comment]
Per discussion, the desired behavior is as follows:

* There should be no default CPU limit so that the proxy uses available resources by default. #5169 removes that limit
* When a CPU limit is set, it should be reflected in `LINKERD2_PROXY_CORES` environment. This value may only be a whole number, though; so, when the CPU limit is a fractional CPU value, we should round up to the next whole number.  E.g. a limit of 1400m would set `LINKERD2_PROXY_CORES=2`

**Comment by olix0r** [comment]
#5170 fixed the behavior. Before closing this, though, we should write docs that describe how to apply CPU limits. Note that:
* The `config.linkerd.io/proxy-cpu-limit` annotation enforces limits correctly.
* The install-time flag `--proxy-cpu-limit` enforces limits correctly.
* When using Helm, users must take care to set `global.proxy.cores` in addition to `global.proxy.cpu.limit` iff kubelet is not configured as described [above](h#issuecomment-720761671).

**Comment by hawkw** [comment]
Opened linkerd/website#846 to add docs for this.
