### ISSUE TITLE
Comprehensively handle all HTTP/1.0 and HTTP/1.1 message framing cases

### ISSUE THREAD

**Issue by briansmith** [linkerd/linkerd2#517]
https://tools.ietf.org/html/rfc7230#section-3.3.3 documents ways in which an implementation should parse messages. In particular, it documents various edge cases, e.g. `Transfer-Encoding` where `chunked` isn't the last encoding applied, the combination of `Content-Length` and `Transfer-Encoding`, multiple `Content-Length` header fields, etc. We should have tests that test every single case. PR #457 added a good chunk of these tests already, however not all cases were in scope for #457.

In particular, https://tools.ietf.org/html/rfc7230#section-3.3.3 indicates there are cases where an implementation must refuse to accept a message because the framing is invalid, for example when multiple conflicting Content-Length header fields are present. We should verify that we do the right thing for such messages. We might want to be more lenient than the RFC requires in the name of transparency. I think this is one of the cases where we don't want to be lenient as there are security ramifications to leniency, but it requires more thinking.

/cc @seanmonstar

**Comment by briansmith** [comment]
In #457, we decided that, at least for now, it is OK to add chunked Transfer-Encoding to any HTTP/1.1 message that is missing Content-Length/Transfer-Encoding header fields, instead of implementing the "until EOF" semantics, in part because Hyper cannot generate non-messages without Transfer-Encoding/Content-Length, despite that behavior not being transparent and thus having some likely transparency issues. As part of *this* issue, we should make a final decision about what to do about that case.

**Comment by seanmonstar** [comment]
The good news is that hyper already handles both of those cases: `Transfer-Encoding: weird`, `Content-Length` and `Transfer-Encoding` in the same message, multiple `Content-Length` headers. The fix here is just to add some tests directly in the proxy.

> We might want to be more lenient than the RFC requires in the name of transparency. I think this is one of the cases where we don't want to be lenient as there are security ramifications to leniency, but it requires more thinking.

These are cases specifically pointed out in the RFC that demand no leniency, specifically for security purposes. I don't think we should ignore that.
