### ISSUE TITLE
Setting multi cluster gateway as internal load balancer

### ISSUE THREAD

**Issue by shaikatz** [linkerd/linkerd2#5182]
### What problem are you trying to solve?
I want to be able to reach my gateway load balancer via internal VPC IP.
### How should the problem be solved?
Add option in the multicluster chart to add an annotation to the load balancer service:
For example in AWS we will add this
`service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0`

**Comment by Pothulapati** [comment]
@shaikatz :wave: 

As k8s yaml manifests have a lot of fields that can be conciigured. It's really hard for chart maintainers to provide options for everything in values. We try to be incremental and add as issues (like this) are created. Iam not sure if we can address this for 2.9, @alpeb is a better person to answer that.

In the mean while, folks use [Kustomize](https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/) to perform patches on top of the manifests that Helm emmits.

**Comment by grampelberg** [comment]
I don't see any reason why we can't make the chart take arbitrary labels and annotations. I would have *sworn* that someone was already working on that PR. You'll just need to add it to [https://github.com/linkerd/linkerd2/blob/main/charts/linkerd2-multicluster/templates/gateway.yaml](gateway.yaml). We'd love a PR if you're up for it!
