### ISSUE TITLE
Option to disable automatic cronjob injection at the controller

### ISSUE THREAD

**Issue by shaikatz** [linkerd/linkerd2#5188]
## Feature Request
I would like to be able to configure the injector to prevent injection to cronjob's pods.

### What problem are you trying to solve?
Jobs are not working well with the sidecar injected, they are never ending and requires workarounds to fix that.

### How should the problem be solved?
The injector should be able to ignore pods created by jobs.

### Any alternatives you've considered?
Create a mutation webhook to inject the disable injection annotation to each job template in the cluster.

### How would users interact with this feature?
Config option to the injector.

*Currently, the promise of installing Linkerd on live cluster smoothly is not true, since if you have cronjobs, you will break their behavior.
Going through all the cronjobs manifests in the company which resides in multiple github repositories is not viable.*

**Comment by olix0r** [comment]
Another option would be to extend [`linkerd-await`](https://github.com/olix0r/linkerd-await) to shutdown the proxy after the wrapped process exits. This would also require that the proxy expose a (localhost-only) admin endpoint to support shutdown.

**Comment by shaikatz** [comment]
If I understand correctly it will still require a change in the job manifest to add the linkerd-await container.
I'm looking for a more transparent way to make sure when Linkerd installed on a production cluster it doesn't break anything, including cronjobs.

**Comment by grampelberg** [comment]
I'm pretty against having this by default. Adding things that opt-in *and* opt-out becomes insanely hard to reason about. As it stands today there's a bunch of workarounds seem fine today.

That said, an addon that does the opt-out for specific resource types seems like a nice set of functionality!

>  more transparent way to make sure when Linkerd installed on a production cluster it doesn't break anything

FWIW, the answer to this is to not opt-in entire namespaces. You're going to get breakage almost no matter what if you do that (completely excluding the cronjob issue).

**Comment by shaikatz** [comment]
> That said, an addon that does the opt-out for specific resource types seems like a nice set of functionality!

When you say Addon, what do you mean? creating a mutation webhook controller and add it as [add on for linkerd](https://linkerd.io/2/tasks/enabling-addons/#:~:text=Add%2Dons%20in%20Linkerd%20are,pass%20the%20configuration%20file%20again.) installation?
If this is what you meant I'll be happy to donate such a thing, but I will be happy to know that it'll be pushed upstream and maintained by the community when I'm done.

> FWIW, the answer to this is to not opt-in entire namespaces. You're going to get breakage almost no matter what if you do that (completely excluding the cronjob issue).

I'm rolling out linkerd slowly, but the end goal is to roll it out to all the namespaces, so things like that needs to be sorted out in advance.

**Comment by grampelberg** [comment]
>  creating a mutation webhook controller and add it as add on for linkerd installation?

Yup!

**Comment by shaikatz** [comment]
Sounds good, I'll probably pick that soon.

**Comment by shaikatz** [comment]
That's what we've got so far: https://github.com/Soluto/linkerd-disable-injection-mutation-webhook 
It's in working condition, we currently support only Jobs annotations, because this is the only resource that makes sense to disable injection for the whole cluster.
