### ISSUE TITLE
cli: Remove `logs` subcommand

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#5191]
The `logs` subcommand doesn't really fit within linkerd's core set of responsibilities. In my experience, this subcommand can be a bit buggy... and we're stuck on an old fork of `stern` to support this, and we don't really want to invest in fixing it.

The [kubernetes plugin ecosystem](https://github.com/ishantanu/awesome-kubectl-plugins) offers better, maintained, tools for interacting with pod logs.

I nominate that we remove the `logs` subcommand in favor of proper external tooling. If there's a general desire in the community for `linkerd logs`-like functionality, I'd prefer that it be managed as a _plugin to Linkerd_ that is maintained externally.

**Comment by adleong** [comment]
:+1:
