### ISSUE TITLE
Move sp-validator into the `destination` controller

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#5195]
The destination controller is responsible for Linkerd service discovery concerns. I think, logically, this includes validating the resources it needs to operate correctly. I propose that we move the `sp-validator` to be a container within the `destination` controller so that is a logically cohesive unit.

Are there any technical challenges to doing this?

**Comment by adleong** [comment]
I can't think of any technical challenges to doing this.  

Overall I'm +0 on this change; I could easily go either way.  On one hand, there's something nice about having each component do as little as possible.  On the other, the tasks are logically related and having one fewer deployment will make this appear more tidy.
