### ISSUE TITLE
Document the destination controller's contract

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#5196]
There is an implicit coupling between the multi-cluster extension and the destination controller -- the multi-cluster service-mirror sets attributes/labels that cause the destination controller to set additional discovery metadata that causes the proxy to modify the `:authority` of outbound requests. The destination controller should have no specific knowledge of the multi-cluster component. Instead, the destination controller should provide a public contract, within which the service-mirror operates.

What annotations/labels does the destination controller honor? Document this.

**Comment by adleong** [comment]
For reference, the current state is that the `mirror.linkerd.io/remote-svc-fq-name` annotation is read from the Endpoints or EndpointSlice resource.  The requested port from the destination Get request is appended to that value and returned as the `AuthorityOverride` in the WeightedAddr.

We could rename this annotation to something like `linkerd.io/authority-override` and document this behavior.

**Comment by olix0r** [comment]
@adleong that makes sense. we should probably do a deprecation cycle
