### ISSUE TITLE
Use "distroless" images for linkerd proxy components

### ISSUE THREAD

**Issue by ericsuhong** [linkerd/linkerd2#5198]
### What problem are you trying to solve?

Reduce container image size + Reduce unnecessary security vulnerabiltiies flagged for base debian image.

### How should the problem be solved?

All linkerd controller plane components EXCEPT proxy use distroless images, and I would like to have distroless images for proxy component as well (if possible).

### Any alternatives you've considered?

N/A

**Comment by olix0r** [comment]
I'm generally +1 on this idea, though I believe that it may not currently be possible. In order to build a static binary (i.e. that doesn't need an OS-provided `libc`), we need to build against musl, but this currently fails due to our TLS dependency:

```
:; (cd linkerd2-proxy && cargo build --target=x86_64-unknown-linux-musl)
   Compiling cfg-if v0.1.10
   Compiling lazy_static v1.3.0
   Compiling slab v0.4.2
   Compiling futures-core v0.3.5
   Compiling bytes v0.5.4
   Compiling fnv v1.0.6
   Compiling smallvec v1.2.0
   Compiling futures v0.1.26
   Compiling scopeguard v1.0.0
   Compiling arc-swap v0.4.7
   Compiling pin-project-lite v0.1.4
   Compiling futures-sink v0.3.5
   Compiling futures-io v0.3.5
   Compiling once_cell v1.4.0
   Compiling pin-utils v0.1.0
   Compiling tower-service v0.3.0
   Compiling ppv-lite86 v0.2.6
   Compiling indexmap v1.0.2
   Compiling itoa v0.4.6
   Compiling tower-layer v0.3.0 (https://github.com/tower-rs/tower?rev=ad348d8#ad348d8e)
   Compiling spin v0.5.2
   Compiling untrusted v0.7.0
   Compiling try-lock v0.2.1
   Compiling percent-encoding v2.1.0
   Compiling adler32 v1.0.2
   Compiling base64 v0.11.0
   Compiling base64 v0.12.3
   Compiling matches v0.1.6
   Compiling regex-syntax v0.6.18
   Compiling gimli v0.21.0
   Compiling unicode-normalization v0.1.5
   Compiling match_cfg v0.1.0
   Compiling rustc-demangle v0.1.5
   Compiling object v0.19.0
   Compiling linkerd2-errno v0.1.0 (/home/ver/b/l2-proxy/linkerd/errno)
   Compiling utf8-ranges v1.0.0
   Compiling quick-error v1.2.3
   Compiling linked-hash-map v0.5.3
   Compiling linkerd2-conditional v0.1.0 (/home/ver/b/l2-proxy/linkerd/conditional)
   Compiling utf8-width v0.1.3
   Compiling nom v2.2.1
   Compiling ipnet v2.3.0
   Compiling hex v0.3.2
   Compiling ipnet v1.0.0
   Compiling libc v0.2.76
   Compiling memchr v2.3.3
   Compiling proc-macro-nested v0.1.4
   Compiling log v0.4.6
   Compiling lock_api v0.3.4
   Compiling tracing-core v0.1.17
   Compiling thread_local v1.0.1
   Compiling sharded-slab v0.1.0
   Compiling getrandom v0.1.13
   Compiling futures-channel v0.3.5
   Compiling byteorder v1.3.1
   Compiling futures-task v0.3.5
   Compiling num-traits v0.2.6
   Compiling httparse v1.3.4
   Compiling serde v1.0.104
   Compiling unicode-bidi v0.3.4
   Compiling ryu v1.0.5
   Compiling serde_json v1.0.59
   Compiling http v0.2.1
   Compiling html-escape v0.2.5
   Compiling linkerd2-app-core v0.1.0 (/home/ver/b/l2-proxy/linkerd/app/core)
   Compiling c2-chacha v0.2.3
   Compiling lru-cache v0.1.2
   Compiling want v0.3.0
   Compiling ring v0.16.12
error: failed to run custom build command for `ring v0.16.12`

Caused by:
  process didn't exit successfully: `/home/ver/b/l2-proxy/target/debug/build/ring-577d2b322a8c9caa/build-script-build` (exit code: 101)
 ...
  running "musl-gcc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "include" "-Wall" "-Wextra" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-fstack-protector" "-g3" "-U_FORTIFY_SOURCE" "-DNDEBUG" "-c" "-o/home/ver/b/l2-proxy/target/x86_64-unknown-linux-musl/debug/build/ring-2d3302b00adab5b7/out/aes-x86_64-elf.o" "/home/ver/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.12/pregenerated/aes-x86_64-elf.S"

  --- stderr
  thread 'main' panicked at 'failed to execute ["musl-gcc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "include" "-Wall" "-Wextra" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-fstack-protector" "-g3" "-U_FORTIFY_SOURCE" "-DNDEBUG" "-c" "-o/home/ver/b/l2-proxy/target/x86_64-unknown-linux-musl/debug/build/ring-2d3302b00adab5b7/out/aes-x86_64-elf.o" "/home/ver/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.12/pregenerated/aes-x86_64-elf.S"]: No such file or directory (os error 2)', /home/ver/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.12/build.rs:638:9
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
```

Some folks have expressed interest in building the proxy against alternate TLS implementations, so this may become possible in the future.

**Comment by olix0r** [comment]
Also it seems like there's some progress this in `*ring*` (our current dependency): https://github.com/briansmith/ring/issues/713

**Comment by olix0r** [comment]
Actually, I think that above error is a red herring. I was missing musl-gcc from my host :hurtrealbad:.

It looks like this should be doable. We'll need to vet that this is possible for ARM builds, but seems like a good goal for 2.10!

**Comment by olix0r** [comment]
OK, while it's pretty simple to modify the build to produce static binaries for x86_64, but getting cross-compilation to work for arm builds seems to be substantially more complex. Given the state of the linkerd build/release process, it's not really feasible for us to support a one-off configuration only for x86_64... I'd love help figuring out how to get the ARM builds working with musl, though!

**Comment by briansmith** [comment]
> OK, while it's pretty simple to modify the build to produce static binaries for x86_64, but getting cross-compilation to work for arm builds seems to be substantially more complex. Given the state of the linkerd build/release process, it's not really feasible for us to support a one-off configuration only for x86_64... I'd love help figuring out how to get the ARM builds working with musl, though!

As of https://github.com/briansmith/ring/pull/1118 there is a documented and mostly tested way of cross-compiling for ARM targets in particular. Look at how *ring*'s build system does it, particularly its mk/cargo.sh. It's much better than using musl-gcc because you can install clang once and that one installation will work for all targets.

**Comment by olix0r** [comment]
Thanks for the helpful pointer, @briansmith.

**Comment by olix0r** [comment]
We might be able to just avoid static compilation/musl for now and use https://github.com/GoogleContainerTools/distroless to provide a base image with glib

**Comment by ericsuhong** [comment]
Did we get any traction on this issue? We are being flagged by internal tools for base ubuntu image vulnerability for following three containers: **proxy-init**, **proxy**, and **web**

**Comment by olix0r** [comment]
@ericsuhong This is scheduled for stable-2.11.0. The best way to make this happen quickly is to submit a PR, though :D

**Comment by olix0r** [comment]
Related: https://github.com/linkerd/linkerd2/pull/6165

**Comment by olix0r** [comment]
Recent proxy images use [`distroless`](https://github.com/linkerd/linkerd2/blob/4532f2b7927849aa8fe39b248a9f3956b72a6844/Dockerfile-proxy#L1)
