### ISSUE TITLE
Openfaas function encounters error - linkerd proxy max concurrency exhausted.

### ISSUE THREAD

**Issue by SidGrundfos** [linkerd/linkerd2#5204]
### What is the issue?
We have an openfaas function. we used the following guidelines -
https://github.com/openfaas/openfaas-linkerd-workshop
Everything has been working fine for quite a while. But now only one function throws this error. This function is also running the most and a lot of requests but recently has started to often generate this error. From the documentation https://github.com/openfaas/openfaas-linkerd-workshop, it says the max concurrency is unlimited by default.
Can someone help with the issue here? 

Everything has been 
### Logs, error output, etc

(If the output is long, please create a [gist](https://gist.github.com/) and
paste the link here.)

#### `linkerd check` output

```text
your output here ...
```

### Environment

- Kubernetes Version:
- Cluster Environment: (GKE, AKS, kops, ...)
- Host OS:
- Linkerd version:

**Comment by olix0r** [comment]
@SidGrundfos There is currently a default limit of 10,000 requests in-flight (i.e. requests that have not received a response headers frame). Is it expected for your application to have this many requests without responses? Or might this be a bug?

**Comment by joewilliams** [comment]
https://github.com/linkerd/linkerd2/issues/5183 is reporting a similar problem. I see this error on the client side of a grpc service, something like client -> linkerd -> linkerd -> service. When I delete or restart service pods a few times I get this message with a grpc error code 14 which is [unavailable](https://godoc.org/google.golang.org/grpc/codes), which makes sense. The message in the error like the OP is `proxy max-concurrency exhausted` which seems misleading.

**Comment by olix0r** [comment]
In today's [edge-20.11.5](https://github.com/linkerd/linkerd2/releases/tag/edge-20.11.5), we've made some adjustments to the default proxy configuration to try to avoid this type of error. If you have a staging environment where this issue can be reproduced, we'd love help testing these changes that we plan to include in stable-2.9.1.
