### ISSUE TITLE
Move `check --multicluster` to `multicluster check`

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#5208]
As we modularize linkerd so that the core `install|upgrade|check` is agnostic of extensions (like multicluster & [viz](https://github.com/linkerd/linkerd2/issues/5197)), we should remove the `check --multicluster` flag (which is somewhat difficult to discover) and instead make this command `linkerd multicluster check`.

**Comment by adleong** [comment]
:+1:
