### ISSUE TITLE
Modularize CLI subcommands

### ISSUE THREAD

**Issue by adleong** [linkerd/linkerd2#5210]
Each Linkerd CLI command typically lives in its own file in the `cli/cmd` package.  This package has a flat structure without any subpackages which means that even nested subcommands such as `linkerd multicluster install` live at the top level of `cli/cmd`.  This large flat module structure could benefit from being better organized and having subcommands live in subpackages.

One impediment to this is the use of module private global variables.  Any commands which are moved into submodules would no longer be able to access these variables.  Some amount of refactoring (replacing globals with function arguments, for example) will be needed to accomplish this.

**Comment by mateiidavid** [comment]
Hi, I see nobody has picked this up yet. I'd be interested in working on it over the next week(s) if that's ok?

**Comment by kleimkuhler** [comment]
Hey @mateiidavid you are okay to work on this. I think you'll probably want to wait until #5340 is merged, or at least work on commands that are not part of that change!

**Comment by adleong** [comment]
Actually, this issue is probably going to be fixed automatically as a side effect of the Linkerd extension work that is being done.  For example, all of the viz CLI commands will be moved into the `viz` directory and all of the multicluster commands have been moved into the `multicluster` directory, and so on.

I don't think there are any other Linkerd subcommands other than the ones which are moving to extensions so there might not be anything to do here.

**Comment by mateiidavid** [comment]
Oh! Apologies should have paid a bit more attention.

Thank you for bringing this up @adleong! If for whatever reason circumstances change, let me know :)

**Comment by olix0r** [comment]
This work is done.
