### ISSUE TITLE
cli: support `--set` with install and upgrade

### ISSUE THREAD

**Issue by Pothulapati** [linkerd/linkerd2#5218]
## Feature Request

Now that we have `--config` which allows overriding on top of `Values`, `--set` can also be added. Internally, As the current merge logic already deals with maps, Convering `--set` values into a map and merging them on top should make this possible.

### What problem are you trying to solve?

Make it easy to change configuration through CLI

### How should the problem be solved?

By adding `--set`

**Comment by olix0r** [comment]
Should `--config` be called `--set-file` to matchhelm?

**Comment by Pothulapati** [comment]
@olix0r Don't really have an opinion on `--config` vs `--set-file` :man_shrugging: 

Reg the removal of existing flags, I don't think we should, at least for the first initial release once we add `--config` and maybe plan on removing them later on. This atleast might help us prevent add more flags initially.
I also think we should format the `Values` struct concretely before we make `--set` as the first-class way to configure things.

**Comment by adleong** [comment]
I think `--set-file` is something else (it's like `--set` except it reads the value from a file).  The equivalent flag to `--config` in Helm is `-f`/`--values`.

I wouldn't be opposed to renaming `--config` to `--values`.

**Comment by olix0r** [comment]
This work has been done.
