### ISSUE TITLE
Add linkerd jaeger CLI subcommand

### ISSUE THREAD

**Issue by adleong** [linkerd/linkerd2#5232]
Add a `linkerd jaeger` subcommand to the Linkerd CLI which controls the linkerd-jaeger extension.  It should have the following commands:

* jaeger install
  * renders the jaeger extension chart
  * should support Helm-like flags for configuration (--values and --set)
* jaeger uninstall
  * prints all jaeger extension components so that they can be deleted
* jaeger check
  * ensures that all tracing components exist, are healthy, and have Linkerd proxy sidescars
  * ensures that all data plane pods with a Linkerd sidecar have the tracing variables set
* jaeger dashboard
  * uses port-forwarding to open the jaeger dashboard in a browser

**Comment by adleong** [comment]
note: jaeger dashboard should fail gracefully with a helpful message if the jaeger extension is not installed

**Comment by Pothulapati** [comment]
This seems to be done. @adleong Can you please close this if you think everything is in?

**Comment by adleong** [comment]
Yep!
