### ISSUE TITLE
install: Cannot configure Grafana image name through registry flag

### ISSUE THREAD

**Issue by kleimkuhler** [linkerd/linkerd2#5236]
Passing the `--registry` flag does not affect the Grafana image name which I find a little surprising. This may be the desired behavior with addons, but it's an odd situation for locally built images.

If I build and push images with the tag `git-xyz` and then try to install with `bin/linkerd --registry ghcr.io/kleimkuhler`, the tag used for all images is `git-xyz`. However, the `--registry` flag does not overwrite Grafana's image name, so it tries to pull `ghcr.io/linkerd/grafana:git-xyz`. This of course does not exist and it errors.

## Solutions

The `--registry` could overwrite the Grafana image name like it does for other control plane images.

If it does not, then should it still use the tag from the Linkerd binary? If it does, then you always have to supply a config to `--config` for installs which does not feel very ideal.

Edit: I originally thought there was an issue with changing the name via `--config` flag as well, but that was a user error on my end!

**Comment by Pothulapati** [comment]
@kleimkuhler This was intended as it would multiple if conditions in the template to choose between its local registry flag or the global ones.

But with the model that we are going after, we are totally getting rid of helm dependencies which could make this even harder to do. Wdyt @adleong

**Comment by Pothulapati** [comment]
https://github.com/linkerd/linkerd2/issues/5430 👀

**Comment by kleimkuhler** [comment]
Closing this since it is now a dup of #5430 and the solution is explained in that.
