### ISSUE TITLE
Upgrade base Debian images

### ISSUE THREAD

**Issue by agniveshadhikari** [linkerd/linkerd2#5243]
We just started using linkerd in production and got an alert from our Governance mechanism on the linkerd images:

Raw text from the report below:
```
Refer to Debian security advisory <A HREF="https://lists.debian.org/debian-security-announce/2020/msg00101.html" TARGET="_blank">DSA 4697-1</A> to address this issue and obtain further details.
<P>Patch:<BR>
Following are links for downloading patches to fix the vulnerabilities:
<P> <A HREF="https://lists.debian.org/debian-security-announce/2020/msg00101.html" TARGET="_blank">DSA 4697-1: Debian</A>
```

[The link from above](https://lists.debian.org/debian-security-announce/2020/msg00101.html) has more information. This looks actionable as they claim _"this problem has been fixed in version 3.6.7-4+deb10u4."_

**Comment by olix0r** [comment]
While I understand that this issue triggers automated scanners, no linkerd components actually link against gnutls; so this doesn't actually rise to level of a security issue for the Linkerd project.

That said, we'd happily accept a PR to upgrade the base Debian images ;)
