### ISSUE TITLE
Drop support for IP queries in destination.Get

### ISSUE THREAD

**Issue by adleong** [linkerd/linkerd2#5246]
The Destination controller's `Get` API accepts queries for both fully qualified authorities as well as for IP addresses.  However, as of stable-2.9.0, the Linkerd proxy will never send IP address queries to the `Get` API.  In order to maintain one version of backwards compatibility between the proxy and the control plane, the destination control should continue to support IP address Get queries in stable-2.10.  However, we should drop support for IP address queries to Destination.Get in stable-2.11 which will allow us to simplify the IP watching logic.

In contrast, the `GetProfiles` API must continue to support fully qualified authority queries (used by the inbound proxy) and IP address queries (used by the outbound proxy).

**Comment by olix0r** [comment]
Note that the proxy still does lookups by IP address. so we'll need to make proxy changes for this.

**Comment by Pothulapati** [comment]
I can take this up. I will start with removing the support for `destination.Get` with IP queries and then make the relevant proxy changes (if possible)
