### ISSUE TITLE
Advanced Service Mirroring

### ISSUE THREAD

**Issue by adrianliechti** [linkerd/linkerd2#5247]
Out of the Box Multi-Cluster experience is amazing!

## Feature Request

Controlling the service name and namespace of a mirrored/proxied namespace
Or manually create a proxy to a multicluster service

### What problem are you trying to solve?

We have a setup where individual programs/projects have their own cluster (about 50).

- Now we would like to do an API Catalog, where Program A can expose an API (~service)
- Program B sees exposed APIs of other programs, and can include them in their cluster

=> so basically they can invoke a selective service mirroring; but also choose the namespace and name of this service

### How should the problem be solved?

I could imagine to create a service or service account on the target, and decorate it with some labels (e.g. upstream service name / cluster name)

linkerd would then create/change he mirrored service's endpints

What do you want to happen? Add any considered drawbacks.

Maybe it's an addional feature to "mirror" - and not an extension

### Any alternatives you've considered?

Is there another way to solve this problem that isn't as good a solution?

Of course we could solve our problem with an ingress / and nginx by ourself.
but we would love to leverage the other linkerd features like mTLS

### How would users interact with this feature?

over CRD or annotations

If you can, explain how users will be able to use this. Maybe some sample CLI
output?

**Comment by grampelberg** [comment]
I'm not sure I understand quite what you're asking for? Mind walking through the call tree?

**Comment by adrianliechti** [comment]
thanks a lot for your fast response!

I was easily able to setup a one-way or bidirectional link of two clusters (that's great)
but now, if one sets mirror.linkerd.io/exported=true, it instantly gets mirrored on the other cluster with the name xxx-clustername & in the same namespace

We would love to get more control about the link
so basically that the target cluster can decide which services to mirror, and what will be the name and namespace of it

so if cluster A exposed a service in namespace my-ns with the name "fancy-api-1"
one can define on cluster b a service called "remtote-fancy-api" in namespace e.g. "remote"

so probably I would like to disable the auto mirroring (or do not annotate the service), and create proxied services for myself

I hope I did better in explaining it
thanks a 1000 for reading it

**Comment by grampelberg** [comment]
Why do you want it to be a different namespace/service name in the remote cluster?

**Comment by adrianliechti** [comment]
this might be a special wish - but establish naming conventions over multiple teams/vendors is a tough one. next level of "space vs tabs" :)

I could imagine imagine setups like this:

project A has namespaces like dev1, dev2, prod, stag
project B maybe development, production, staging

so project B might want the prod service "api" of project A in every namespace to access it like "http://ProjectA-API". what would make config handing very easy (fix naming convention)

or that project B might create one namesapce called "xyz" to put instances of that vendor/project
where there then will be services routes like: http://api.xyz, api-dev1.xyz, api-dev2.xyz, ...

if we place the services in the same naming of the original namespace, this might be very confusing...
and some will not like it - because they prefer consistent naming, and have deeper control and not be remotely controlled

**Comment by grampelberg** [comment]
Why not just use traffic splits with a single service?

**Comment by adrianliechti** [comment]
my final goal is to have n:n connections in this constellation
where not every service of cluster b is replicated to a - and vice versa

```
Cluster A:                                                             Cluster B:
http://fancyapi.clusterb (namespace xyz)        => http://backend:80 (namespace dev)
```

if this is possible with the trafficsplit idea, I'm totally open to it

**Comment by grampelberg** [comment]
Should (tm) work! Give it a try and see if that'll do it for you!
