### ISSUE TITLE
Multicluster component shoud support TCP routing to mirrored services

### ISSUE THREAD

**Issue by sonnysideup** [linkerd/linkerd2#5259]
#### Setup

I have two Linkerd clusters (A & B) that have the multicluster component installed with cluster A linked to cluster B.

#### Deployment

Redis is deployed to cluster B with a service that mirrors itself inside cluster A (i.e. `mirror.linkerd.io/exported=true`). The service definition shows up correctly inside cluster A.

#### Results

I am unable to connect to `redis-server` running inside cluster B using `redis-cli` inside cluster A. It appears as though TCP routing is not currently supported.

### How should the problem be solved?

According to a [Slack conversation](https://linkerd.slack.com/archives/C89RTCWJF/p1605824462428900) with @adleong, there are plans to support multicluster TCP routing. I just want to add this issue to track that progress.

Ideally, users should be able to route to any TCP-based application (e.g. RabbitMQ, Redis, PostgreSQL, et al) running inside a linked Linkerd cluster.

**Comment by olix0r** [comment]
Thanks for filing this. This work is in progress and planned for stable-2.10.

Oliver Gould < ver@buoyant.io >

**Comment by sonnysideup** [comment]
@olix0r Is there any way for users to track the progress of the 2.10 release and, by extension, future releases? I'm not seeing anything indicative in the branches/projects/etc...

**Comment by grampelberg** [comment]
@sonnysideup https://github.com/orgs/linkerd/projects/50 is a pretty good place to watch =) Also, I would strongly recommend attending and/or watching the monthly community meetings. There's a section in there about the upcoming release each time.

**Comment by olix0r** [comment]
~final proxy PR is up at https://github.com/linkerd/linkerd2-proxy/pull/909. We need to do more testing, but I expect this to work in the next edge release

**Comment by olix0r** [comment]
This was released in last week's edge. https://github.com/linkerd/linkerd2/issues/5650 tracks supporting `opaque-ports` annotations for mirrored services.

**Comment by sonnysideup** [comment]
Thanks @olix0r, we'll check it out and play with this new feature.

**Comment by olix0r** [comment]
Thanks @sonnysideup.  Over the next week or two we'll be working on docs, etc, for stable-2.10; so please don't hesitate to let us know if you see anything confusing!
