### ISSUE TITLE
mTLS for PHP-FPM causing timeouts and website not being shown

### ISSUE THREAD

**Issue by davi5e** [linkerd/linkerd2#5274]
### What is the issue?

Using Laravel and 2 separate pods for the website (Nginx for the static files and one for all things PHP-FPM) I notice a clear problem with latency if mTLS is enabled between them.

I say latency but some requests never complete (they timeout), others take more than 10 seconds to complete, a minority load as expected (using the network tab of Firefox).

Most of the problems happens in Laravel Nova (an administration panel), since my frontend is mostly static single-page content. Those single pages load fine.

For now, just skipping the PHP-FPM port using annotations (`config.linkerd.io/skip-inbound-ports: 9000` and `config.linkerd.io/skip-outbound-ports: 9000`) works. Perhaps this confirms something is wrong while mTLSing PHP-FPM, but I don't know how to pin point the error not how to provide more information.

### How can it be reproduced?

I guess the easiest way to reproduce is to deploy a [Laravel Nova](https://nova.laravel.com/) website using using some tutorial [like](https://www.youtube.com/watch?v=I980aPL-NRM) this as a guide on how to deploy Laravel.

Not being feasible, my intuition tells me this should not be related to Laravel Nova, it's just that's the part of my website that currently uses PHP (because the frontends are mainly single page javascript). Hence, any code that uses Laravel, Symfony, maybe connects to a database *should* incur in mTLS problems between Nginx and PHP-FPM.

### Logs, error output, etc

I don't even know where to begin, but I can provide some if anyone explains what I need to do and what I need to paste back here.

#### `linkerd check` output

```text
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-cni-plugin
------------------
√ cni plugin ConfigMap exists
√ cni plugin PodSecurityPolicy exists
√ cni plugin ClusterRole exists
√ cni plugin ClusterRoleBinding exists
√ cni plugin Role exists
√ cni plugin RoleBinding exists
√ cni plugin ServiceAccount exists
√ cni plugin DaemonSet exists
√ cni plugin pod is running on all nodes

linkerd-identity
----------------
√ certificate config is valid
√ trust anchors are using supported crypto algorithm
√ trust anchors are within their validity period
√ trust anchors are valid for at least 60 days
√ issuer cert is using supported crypto algorithm
√ issuer cert is within its validity period
‼ issuer cert is valid for at least 60 days
    issuer certificate will expire on 2020-11-24T10:44:52Z
    see https://linkerd.io/checks/#l5d-identity-issuer-cert-not-expiring-soon for hints
√ issuer cert is issued by the trust anchor

linkerd-webhooks-and-apisvc-tls
-------------------------------
√ tap API server has valid cert
√ tap API server cert is valid for at least 60 days
√ proxy-injector webhook has valid cert
√ proxy-injector cert is valid for at least 60 days
√ sp-validator webhook has valid cert
√ sp-validator cert is valid for at least 60 days

linkerd-api
-----------
√ control plane pods are ready
√ control plane self-check
√ [kubernetes] control plane can talk to Kubernetes
√ [prometheus] control plane can talk to Prometheus
√ tap api service is running

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ control plane is up-to-date
√ control plane and cli versions match

linkerd-ha-checks
-----------------
√ multiple replicas of control plane pods

linkerd-prometheus
------------------
√ prometheus add-on service account exists
√ prometheus add-on config map exists
√ prometheus pod is running

linkerd-grafana
---------------
√ grafana add-on service account exists
√ grafana add-on config map exists
√ grafana pod is running

Status check results are √
```

### Environment

- Kubernetes Version: 1.17
- Cluster Environment: GKE
- Host OS: container optimized
- Linkerd version: 2.9.0

### Possible solution

I skipped PHP-FPM between Nginx (outbound port) and PHP-FPM (inbound port). Everything works now.

### Additional context

As I said, I don't know how to help further. It's now "working" because Linkerd is not being used for this particular port, so debugging is not a priority of our company, but I can assists with information if needed albeit maybe taking some hours to respond.

**Comment by grampelberg** [comment]
Have you skipped mysql and/or pgsql?

**Comment by davi5e** [comment]
Yes.

So Nginx skips outbound to 9000.

PHP-FPM skips outbound to 5432 and inbound from 9000.

**Comment by grampelberg** [comment]
Do you have any kind of APM setup? I'd be really interested to see what calls are specifically hanging. An easy test would be to skip everything outbound on php-fpm and see if that fixes it.

**Comment by davi5e** [comment]
We don't have an APM right now because we can't decide which to use (the website is quite recent).

I did find an example of the requests I mentioned (domain redacted to avoid traffic).

![errors](https://user-images.githubusercontent.com/25727609/100000754-cd75d180-2da0-11eb-867e-9f970c3cb12e.png)

> An easy test would be to skip everything outbound on php-fpm and see if that fixes it.

But if we're skipping the FPM inbound port and see the site loading, how would skipping outbound traffic help? Should I delete the `skip-inbound` port? This would bring the pods to their original states, since the only external request are to databases.

**Comment by grampelberg** [comment]
Yeah, remove skip-inbound and only do skip-outbound on php-fpm. The fact that static scripts are loading but pages aren't makes me think it is something outbound again.

**Comment by davi5e** [comment]
I get the need for an APM to figure that out.

Can Linkerd (with debug?) be used to know what would be hanging the PHP pod?

I still think it would end up being the same, but I can spin up a test cluster sometime later this week to test this using a replica of our deployments.
