### ISSUE TITLE
Drill into pod(s) info/view from deployments view

### ISSUE THREAD

**Issue by electrical** [linkerd/linkerd2#5300]
## Feature Request
Under each deployment create a link to the pods view

### What problem are you trying to solve?
At the moment when looking from the deployments view you can only see the overall statistic of that deployment while there could be 1 or more pods behind it.
If you want to drill down into the detailed view of that deployment you have to go to the pods view and find the right pod(s) of that deployment

### How should the problem be solved?

Add a link under the deployment view to go to the pods view

### Any alternatives you've considered?

On the deployment page you do see a table below it with the pod information, but that will link to a specific pod and not to a view that will show all pods related to that deployment

### How would users interact with this feature?

This allows you to quickly see more details of the deployment.

**Comment by cpretzer** [comment]
@electrical thanks for opening this issue. There is some work being done around the Linkerd dashboard and this seems like a good feature.

@adleong WDYT?

**Comment by adleong** [comment]
This already exists
![Uploading Screen Shot 2020-12-17 at 1.47.16 PM.png…]()

**Comment by electrical** [comment]
@adleong unfortunately the screenshot is not showing for some reason.

**Comment by adleong** [comment]
@electrical whoops, sorry about that.  screenshot fixed.
