### ISSUE TITLE
Clarify what 'resources' are missing in Gateway page

### ISSUE THREAD

**Issue by electrical** [linkerd/linkerd2#5310]
## Feature Request

Improve wording on the Gateways page

### What problem are you trying to solve?

The Gateways dashboard page is in most 'simple' deployments empty and 'gateways' is an arbitrary term if you don't understand the relation within Linkered.

### How should the problem be solved?

Clarify what resources are not detected.
Perhaps change the sentence to 'No multi cluster resources detected'

As a side note, it might be useful for people to have links to readme/manuals/howto's etc at the bottom of a page when looking at something specific.
As an example the 'Traffic splits' page for me is empty, but i'm not sure where to look for additional information.

**Comment by adleong** [comment]
This is a great suggestion and is somewhat related to https://github.com/linkerd/linkerd2/issues/5330

@electrical are you interested in contributing a PR to improve these pages?

**Comment by electrical** [comment]
I think we can close this now with the modules introduced in 2.10
If it's not installed it won't show up :-)
