### ISSUE TITLE
Split linkerd-viz components into their own chart

### ISSUE THREAD

**Issue by adleong** [linkerd/linkerd2#5313]
In order to modularize the viz related components into a linkerd-viz extension, we should create a new top-level directory in the Linkerd2 repo called viz, create a linkerd-viz chart there, and move all viz related components to that chart (such as Prometheus, grafana, the metrics-api, tap, the web dashboard, etc.)  This new chart should install these viz components into their own namespace.

The CLI should be updated to find these components in their new namespace.

To preserve the current behavior, the linkerd-viz component templates should remain pre-injected with the proxy and the `linkerd install` command should render both the core chart and the linkerd-viz chart.  In future work once a `linkerd viz install` command is available for installing the linkerd-viz chart separately, the pre-injection can be removed.

**Comment by Pothulapati** [comment]
Working on this, as #5326 is not possible without this first

**Comment by Pothulapati** [comment]
Update: Except for the public-api, every other viz component is now under the new `linkerd-viz` chart,
