### ISSUE TITLE
bin/protoc-diff assumes Debian(-based) system

### ISSUE THREAD

**Issue by joakimr-axis** [linkerd/linkerd2#5337]
### What is the issue?
`bin/protoc-diff` checks if the host is a Linux system. If `unzip` is missing, it calls `apt-get`. This will fail for a non-Debian-based system.

### How can it be reproduced?
```shell
docker run -it --rm -v <path_to_your_linkerd2_dir>:/src/linkerd2 -w /src/linkerd2 fedora
bin/protoc-diff
```

### Logs, error output, etc
```shell
[root@f667739e8564 linkerd2]# bin/protoc-diff 
bin/protoc-diff: line 8: apt-get: command not found
[root@f667739e8564 linkerd2]#
```
#### `linkerd check` output
_Not applicable_

### Environment

- Kubernetes Version: _Not applicable_
- Cluster Environment: _Not applicable_
- Host OS: Debian Linux (bullseye)
- Linkerd version: commit 72a0ca974df2e623a3ffbff2a03abaabaab19322

### Possible solution
1. Should the script really install unzip on its host? If so:
    1. Is it supposed to be run as root? Otherwise it will fail due to permission needed for `apt-get`.
    2. A distinction is needed for the Linux breed. For Debian/Ubuntu etc. apt-get should be used. For Fedora/RedHat etc. yum. For alpine apk. Etc. etc.
2. Could it be simpler just to check for unzip and return an error message to the user if it is missing? And then let the user install it in a suitable way? Then `bin/protoc-diff` can be run as any appropriate non-root user and focus solely on its primary tasks.

### Additional context

Should really `bin/protoc-diff` do the/a `unzip` check/install at all? It does not use `unzip`, but calls `bin/protoc-go.sh` which in its turn calls `bin/protoc`, and `bin/protoc` uses `unzip`. IMO it would be more logical to leave such check/install functionality to `bin/protoc` who is the actual caller of `unzip`.

**Comment by joakimr-axis** [comment]
To make a distinction between different Linux systems, something along these lines could be used:

```shell
#!/bin/sh -eu
[ -f /etc/os-release ] && . /etc/os-release
[ -n "$ID" ] || {
        echo 'Could not find Linux distro info' >&2
        exit 1
}

PKGMGR=
case "$ID" in
        fedora)
                PKGMGR=yum
                ;;
        debian|ubuntu)
                PKGMGR=apt-get
                ;;
        alpine)
                PKGMGR=apk
                ;;
        *)
                echo "No package manager defined for $ID" >&2
                exit 1
                ;;
esac

echo "Will use $PKGMGR for package management!"
```

**Comment by olix0r** [comment]
> Should the script really install unzip on its host?

IMO, no.

> Could it be simpler just to check for unzip and return an error message to the user if it is missing? And then let the user install it in a suitable way?

 Big +1. I think we have other tools that just check for the tools they need and error if not present.  E.g.

https://github.com/linkerd/linkerd2-proxy/blob/c8d3677edad07b8b6b21349a382235330d8adfd2/checksec.sh#L5-L14

**Comment by joakimr-axis** [comment]
Ok, I have made a suggestion PR in #5347 now!
