### ISSUE TITLE
Stop publishing the `linkerd2-multicluster-link` chart

### ISSUE THREAD

**Issue by alpeb** [linkerd/linkerd2#5348]
That chart only serves as a repository of templates used by the `linkerd multicluster link` CLI command and cannot be installed by itself through `helm install` because it doesn't contain the `cluster-credentials` secret nor the `Link` CR that need to be generated dynamically.

This is just a matter of removing one line in `bin/helm-build`

**Comment by yaron-idan** [comment]
Are there any plans to publish a chart that can support these resources? Would it be baked into the multicluster chart or stay outside of the chart responsiblity?

**Comment by alpeb** [comment]
The `cluster-credentials` secret generated as part of `linkerd multicluster link` contains the credentials for the source cluster to connect to the target cluster, so it can watch for the services being exported. That can't be generated solely through Helm templates and thus has to rely on the CLI command.
