### ISSUE TITLE
heartbeat cron should get metrics from linkerd-viz extension when available

### ISSUE THREAD

**Issue by adleong** [linkerd/linkerd2#5352]
The heartbeat cron job currently gets cluster metrics from Prometheus.  However, Prometheus will no longer be available in the core control plane once it moves to the linkerd-viz extension.  To prepare for this, we should add a GetHeartbeatMetrics method to the public-api (which will move to the metrics-api).  This method will fetch the appropriate metrics from Prometheus (either the bundled prometheus or the external prometheus).  The heartbeat process should attempt to discover the linkerd-viz extension using the `linkerd.io/extension: linkerd-viz` namespace selector.  If linkerd-viz is found, it should fetch the cluster metrics from the metrics-api.  Otherwise, it should submit the heartbeat with those metrics omitted.

**Comment by adleong** [comment]
This currently works by having the heartbeat job attempt to query the hardcoded service name of the prometheus instance in the linkerd-viz extension.  If it is not reachable (either because linkerd-viz is not installed or if an external prometheus is configured) then heartbeat will continue, omitting these metrics.

**Comment by olix0r** [comment]
I believe this was addressed?
