### ISSUE TITLE
[prometheus add-on]: alertManagers or alertmanagers ?

### ISSUE THREAD

**Issue by naseemkullah** [linkerd/linkerd2#5371]
https://github.com/linkerd/linkerd2/blob/c19cfd71a12bd0cb033e9a494a3e86a8a3e46c2f/charts/add-ons/prometheus/values.yaml#L31

Noticed after alertmanager integration was not working post 2.9.0 upgrade that it has been camelCased i.e. two words (`alertManagers`), upon porting to add-on. Is this intentional, if not, is it worth changing back to one word (`alertmanagers`) ?

**Comment by kleimkuhler** [comment]
@Pothulapati Do you remember if this was an intentional change when moving to an add-on?

**Comment by Pothulapati** [comment]
[Looks like the configuration is still used in the templates as `alertmanager` only](https://github.com/linkerd/linkerd2/blob/main/charts/add-ons/prometheus/templates/prometheus.yaml#L159). It's only the field name that is wrong in `values.yaml` which was [added incorrectly in the automatic readme generation PR](https://github.com/linkerd/linkerd2/pull/5316/files?file-filters%5B%5D=.golden&file-filters%5B%5D=.gotmpl&file-filters%5B%5D=.md&file-filters%5B%5D=.yaml&file-filters%5B%5D=.yml&file-filters%5B%5D=dotfile#diff-ace0be1cdc6080c8034f3ea2e4445a1b24c42f9262895aef4a18ec007ed2c121R31). 

Using it as `alertmanager` should still work I think?

**Comment by Pothulapati** [comment]
Also, As the `values.yaml` of add-ons are not public facing. This should not effect the users much. These are only used for the generation of readme now, and we can update the readme to reflect the same? 🤔

**Comment by Pothulapati** [comment]
As per the conversation with @alpeb, #5316 did land in the `2.9.*` release branches, So This should not effect any users.

@naseemkullah This means that the alert manager stuff should just work normally without any changes. Can you check if the configuration is correctly being propogated into `linkerd-prometheus-config`? 🤔

**Comment by naseemkullah** [comment]
from 2.8.x to 2.9.0 the flat values moved to nested values, and we remapped our grafana and prometheus values accordingly (nested the flat values).

The one oversight/surprise was that alertManagers was camelCased i.e. two words, while I missed it on my end, it should be known that alertmanager is stylized as one word 

configuring `prometheus.alertmanagers: [my config here]` did not work (well helm did not complain, but our alerting system was broken at that point), changing that to `prometheus.alertManagers: [my config here]` does work, my question is there any plan to correct the make `alertManagers` `alertmanagers` knowing that alertmanager is stylized as one word?

**Comment by Pothulapati** [comment]
@naseemkullah Yep, My bad. Can confirm that `alertManagers` is how that field is used with `2.9.x`. This got changed with the add-ons change and not the docs generation change. Probably because we use camelCase everywhere.

We can update this to reflect how prometheus mentions alertmanager i.e `alertmanager` and not `alertManager` but that won't be for the `2.9.x` release.

**Comment by naseemkullah** [comment]
Thanks @Pothulapati , I can submit a PR, but I'd like to know should we just make the breaking change from `.Values.prometheus.alertManagers` to `.Values.prometheus.alertmanagers` or go through the trouble of supporting both for a period of time? I'm under the impression that this feature is not widely used today (though it should be it is great!), but I do not have numbers to prove this.

**Comment by naseemkullah** [comment]
Thanks @Pothulapati https://github.com/linkerd/linkerd2/pull/5377 opened PTAL 🙏
