### ISSUE TITLE
Service mirror not honoring `requeueLimit`

### ISSUE THREAD

**Issue by alpeb** [linkerd/linkerd2#5374]
### What is the issue?

When a (retryable) error occurs in the service mirror it keeps on getting retrying indefinitely. In theory in should be requeued only up to (by default) 3 times.

### How can it be reproduced?

Run the `multicluster` integration test disabling tearing down the clusters, so we can further work with the clusters after the test finishes, replace the `gatewayAddress` field in the Link CR with an invalid value, and see in the logs how the `repairEndpoints` event keeps on getting fired.

```
# First edit bin/_test-helpers.h commenting out `finish source` and `finish target` in the `start_multicluster_test()` function
# Then trigger the test
$ bin/tests --name multicluster /home/alpeb/src/linkerd2/target/cli/linux-amd64/linkerd

# Wait for it to finish, and switch to the source cluster
$ kubectl config use-context k3d-source

# Edit the Link resource, replacing the IP in `gatewayAddress` with something like `foobar`
$ kubectl edit -n linkerd-multicluster edit links.multicluster.linkerd.io target

# Tail the service-mirror logs
$ kubectl -n linkerd-multicluster logs -f deploy/linkerd-service-mirror-target service-mirror
```

### Logs, error output, etc

Endless repetition of:
```
time="2020-12-11T21:35:32Z" level=error msg="Error processing RepairEndpoints (will retry): Inner errors:\n\tError resolving 'foobar': lookup foobar on 10.43.0.10:53: no such host" apiAddress="https://172.26.0.4:6443" cluster=remote
time="2020-12-11T21:35:32Z" level=info msg="Received: RepairEndpoints" apiAddress="https://172.26.0.4:6443" cluster=remote
```

### Environment

- Kubernetes Version: 1.18
- Cluster Environment: (GKE, AKS, kops, ...): k3d
- Host OS: Linux
- Linkerd version: Edge-20.12.1

### Possible solution

In `cluster_watcher.go` we have checks on `requeueLimit` but apparently we're not incrementing that var when necessary. Also before retrying it might be worth adding some Sleep time. Not worth a fully fledged exponential back-off strategy for now, IMO.

**Comment by piyushsingariya** [comment]
Hi @alpeb, I read the issue and thought to give it a shot and I think this issue is related to [here](https://github.com/linkerd/linkerd2/blob/main/multicluster/service-mirror/cluster_watcher.go#L602)
but I still don't get why this is could be happening as we are already increasing the number of times the event has been queued and checking if it is less than the requeueLimit :thought_balloon:

**Comment by alpeb** [comment]
Right, it seems like we're just not properly using the queue interface. Might be worth adding more debugging logging, checking how the queue grows, etc.
