### ISSUE TITLE
Expose identity certificate validity period in proxy metrics

### ISSUE THREAD

**Issue by cypherfox** [linkerd/linkerd2#5379]
### What problem are you trying to solve?
When the identity certificate of the proxy fails to renew its certificate before the end of its validity period, communication between injected pods will fail. And only a restart of the pod will heal this.

Due to the failure not occurring neither within the application service code, nor the client connecting to the service, this makes it hard to diagnose for application devs.

Also this often indicates a more general problem with *all* the proxies or the l5d control plane, most likely the configuration, rather then a single application pod.

### How should the problem be solved?
By exposing the validity period of the identity certificate through the metrics of the proxy.

This allows cluster wide monitoring and alerting, should the remaining validity fall below an expected value.

### Any alternatives you've considered?

The only alternative would be regularly polling the certificates by opening connection and parsing the certificates sent by the TLS handshake with the proxy. This could then be exposed as it's own metric.

The drawback would be yet another component, requiring more config, more network traffic.

### How would users interact with this feature?

If the user is interested in the information, any existing monitoring and alerting infrastructure could be used to react to the information.

**Comment by adleong** [comment]
Potentially related: https://github.com/linkerd/linkerd2/issues/4459

Another way to address this problem would be for the `linkerd check --proxy` command to connect to each pod and check the certificate.

**Comment by cypherfox** [comment]
> Another way to address this problem would be for the `linkerd check --proxy` command to connect to each pod and check the certificate.

But that would in principle still be an external polling, which I would then pump into prometheus anyway, in order to make it available for alerting.

I do agree that this would be usefull in `linkerd check`. But connecting to each proxy, especially if a lot of them are broken and the connection is failing, would take a very long time. I am not sure if integrating all of that into the `check` subcommand would be good UX.

**Comment by adleong** [comment]
Yup, I just wanted to point out an possible alternative.  But I agree that having this data in the metrics would be useful.  Are you interested in working on this?

**Comment by cypherfox** [comment]
Unfortunately, I cannot, as I don't speak Rust yet. I would like to find the time to finish the things I already started.

**Comment by olix0r** [comment]
@cypherfox What do you imagine that the metric/value would be? A gauge of remaining time? The timestamp of the expiration time?

I've looked through the prometheus docs and I'm not clear on the best practice is for this type of metric.

**Comment by olix0r** [comment]
After some discussion, I'm inclined to represent this as a gauge of remaining time -- it should be easier to monitor that this never hits `0` than to try to compare it to the current time.  Something like:

```
# HELP identity_cert_validity_seconds The number of seconds remaining until the proxy's identity certificate expires.
# TYPE identity_cert_validity_seconds gauge
```

**Comment by cypherfox** [comment]
@olix0r I am afraid it can (and will) have values below 0, as certs run out of validity. But as the value comes to be stuck at 0, you loose the ability to quickly determine the timestamp of the issuance of the cert.

Also reduction of variants: cert-manager uses epoch (which will be good until 2038). 

If I can make a wish, I would prefer l5d to do the same, if only to make writing Grafana dashboards as easy as possible.

**Comment by hawkw** [comment]
Looking at [cert-manager's source code][1], it looks like the metric is `certificate_expiration_timestamp_seconds`. It sounds like @cypherfox would prefer it to be exported in the same format for consistency.

@olix0r what do you think?

[1]: https://github.com/jetstack/cert-manager/blob/cdc53b65cbd344dbef64f0c5c22e6070e79c5b5c/pkg/metrics/metrics.go#L19

**Comment by olix0r** [comment]
@hawkw I think that makes sense. I didn't realize that Prometheus's `time` function existed; so there's still a straightforward way to compare this value for the purposes of alerting.
