### ISSUE TITLE
Remove the use of emptyDir for proxy sidecars

### ISSUE THREAD

**Issue by glitchcrab** [linkerd/linkerd2#5386]
### What problem are you trying to solve?

All clusters we manage have least-privileged PSPs applied, and the clusters all have heavily restricted PSPs in place by default. Currently in order to use Linkerd (with the CNI) we need to modify every PSP to allow emptyDir or the proxy sidecar cannot start.

Discussed briefly with grampelberg here: https://linkerd.slack.com/archives/C89RTCWJF/p1607081073451400

### How should the problem be solved?

Removal of the requirement for an emptyDir.

### Any alternatives you've considered?

Not that I'm aware of - PSPs are pretty limited. If it were possible to have more than one PSP applied to a pod then I could provide one tailored to this purpose, but there's no union of all applicable PSPs to a pod so this point is moot.

### How would users interact with this feature?

Not required

**Comment by adleong** [comment]
Hey @glitchcrab!  To give some context around how the empty dir is used: when the proxy container starts up, a [small Go script](https://github.com/linkerd/linkerd2/tree/main/proxy-identity) runs which generates the private key and certificate signing request (CSR) for the proxy and writes them to that emptyDir for the proxy to read.  

We do this in Go to keep our certificate generation code uniform (the identity controller is also written in Go) and to take advantage of the crypto libraries in Go.  Do you have a specific suggestion for how you'd like to see this done without the use of emptyDir?

**Comment by glitchcrab** [comment]
Thanks for the explanation @adleong! What's the purpose of the use of the emptyDir over just using the container's filesystem? Is it to preserve the certs between pod restarts? Or are the certs generated each time the pod starts?

**Comment by olix0r** [comment]
@glitchcrab the `emptyDir` ensures that the credentials stay in (tmpfs) memory and permits the proxy container to run with a read-only filesystem--something that is also required by many PSPs.

In the rare case where the proxy restarts, the proxy will use the existing credentials; though that use case isn't particularly important. It's mainly intended to have a clear scope for mutable data so the container filesystem can be readonly.

**Comment by glitchcrab** [comment]
OK, I wasn't aware that the proxy's FS was read-only - the requirement for the emptyDir makes more sense now. In that case I can't see a way to remove this requirement (unless someone smarter than me has a bright idea).
