### ISSUE TITLE
Failover controller for trafficsplit objects

### ISSUE THREAD

**Issue by yaron-idan** [linkerd/linkerd2#5387]
## Feature Request
We are using trafficsplit to route local traffic flowing within our cluster to a remote cluster linked using linkerd-multicluster, and would like the weights to be set in a way that will only route traffic to the local cluster, and shift all traffic automatically to the remote cluster in case all endpoints in the local service are unhealthy.

### What problem are you trying to solve?
We'd like all traffic to flow internally within the cluster, and only in case all of the local service endpoints are unhealthy - shift traffic to the remote cluster.

### How should the problem be solved?
A controller should watch changes to the health of endpoints registered to a service. If all endpoints are unhealthy - the controller should shift traffic from the local cluster to the linked cluster. Once a new healthy endpoint joins the service, the traffic should be shifted back to the local cluster.

What do you want to happen? Add any considered drawbacks.
In case of a service with no healthy endpoint - traffic should shift to a secondary, remote cluster.
The main drawback I currently see is that the solution does not support monitoring the health of remote endpoints, making it shift traffic to a remote cluster even if endpoints are unhealthy there as well. 
For the same reason the solution does not extend well to more than 2 clusters.

### Any alternatives you've considered?
Circuit breaking could work as well, but it will require constantly sending some of our traffic to a remote cluster, resulting in increased latency for these requests, as well as no visibility for health of services in the remote cluster.

Is there another way to solve this problem that isn't as good a solution?
Not that I am aware of

### How would users interact with this feature?
Not sure. We're currently developing a controller. It can probably be made available as an addon or a plugin, or added to the serviceprofile object, as suggested in the [circuit breaker RFC](https://github.com/linkerd/rfc/blob/a4858a0da7b9d9b527284d4898b1ae0e95a15696/design/0005-circuit-breaking.md#circuit-breaker).

**Comment by adleong** [comment]
@yaron-idan this is a really cool idea and I think should be well supported by Linkerd's multicluster and trafficsplit functionality.  Even better, it should be possible to build this operator without making any changes to Linkerd itself.  The operator would simply need to monitor prometheus metrics and then make the appropriate changes to the trafficsplit resources.  This is similar to what Flagger does, I believe.

If you decide to build something like this, please let me know!  I'd love to see it!

**Comment by adleong** [comment]
Since this can be built outside of the Linkerd repository, I'm going to close this issue.  However, I highly encourage this project!

**Comment by olix0r** [comment]
https://github.com/linkerd/linkerd-failover
