### ISSUE TITLE
page for collection of production best practices

### ISSUE THREAD

**Issue by electrical** [linkerd/linkerd2#5393]
## Feature Request

It would be great to have a page in the documentation that gives all the best practices ( links to existing articles perhaps ) for a production quality setup.
Since there are different components to linkerd it can be sometimes a bit confusing what would be best for a production ready setup.
Some of them would be the automatic rotation of certificates and the HA installation. I'm sure there are more pages related to it.

Some of the related pages that were mentioned in a discussion on slack for example:

https://linkerd.io/2/tasks/automatically-rotating-control-plane-tls-credentials/
https://linkerd.io/2/tasks/automatically-rotating-webhook-tls-credentials/
https://linkerd.io/2/tasks/generate-certificates/
--ha flag ( couldn't find the page )

**Comment by adleong** [comment]
Sounds useful, though a little bit subjective.  What "production ready" means can vary a lot depending on individual needs.  Are you interested in contributing this page?  I'd recommend opening and issue or PR on the https://github.com/linkerd/website repo.  Alternatively, this might make for a really excellent blog post if you're interested in writing something like that.

**Comment by electrical** [comment]
Although I agree it depends on individual needs, i'm sure there are some basic requirements / advice to run this in a production environment. Like the TLS credentials rotation could be considered best practice. I would guess you guys know this much better than I do ;-)
I will be writing blog posts in the future about all the work I'm doing but no timeline on that. But always happy to contribute!
I'll open a new issue in the website repo.

**Comment by adleong** [comment]
Cool!  I'm going to close this and I'll keep an eye out for the issue in the website repo.
