### ISSUE TITLE
Make service profile generation work offline

### ISSUE THREAD

**Issue by purkhusid** [linkerd/linkerd2#5401]
Currently the service profile generation from proto/swagger requires that you have access to the k8s cluster that has Linkerd running.

The only reason for this is that currently the cluster domain is fetched from the Linkerd installation on the cluster.

I propose that the `profile` command be updated to support the `--ignore-cluster` flag
I also propose that there should be a flag `--cluster-domain` that allows the user to override the cluster domain. 

See discussion here: https://github.com/linkerd/linkerd2/discussions/5287#discussioncomment-187807

**Comment by cpretzer** [comment]
@purkhusid thanks for pointing this out. We'd love your help with this, if you're up for submitting a PR

**Comment by piyushsingariya** [comment]
Hi, I would like to work on this issue!

**Comment by piyushsingariya** [comment]
Hi @cpretzer, I edited the `cli/cmd/profile.go ` where basically I added code to validate `--ignore-cluster`, added a new boolean variable `ignoreCluster` default to be `false` in profileOptions and now we will call a function to create a profile
and I think the step after this is to create a new file in `pkg/profiles` -> ignoreCluster.go where function(creates a profile without checking the access) will be written
this step is a bit challenging for me if you could guide me here, it would be a big help.

**Comment by piyushsingariya** [comment]
Hi, @purkhusid I have started working on this. It would be helpful if you could explain what are the other flags and args which can be passed alongside the flag `--ignore-cluster`

**Comment by wmorgan** [comment]
@piyushsingariya just wanted to say thanks again for fixing this. This was a pet peeve of mine.

**Comment by wmorgan** [comment]
(And thanks @purkhusid for creating the issue, which I never got around to doing!)
