### ISSUE TITLE
Improve Getting Per-Route Metrics docs

### ISSUE THREAD

**Issue by twDuke** [linkerd/linkerd2#5403]
# Thanks for your help improving the project! #

## Getting Help ##

Github issues are for bug reports and feature requests. For questions about
Linkerd, how to use it, or debugging assistance, start by
[asking a question in the forums](https://discourse.linkerd.io/) or join us on
[Slack](https://slack.linkerd.io/).

Full details at [CONTRIBUTING.md](https://github.com/linkerd/linkerd/blob/main/CONTRIBUTING.md).

## Filing a Linkerd issue ##

Issue Type:

- [ ] Bug report
- [x] Feature request

**What happened**:
It's not clear that a service needs to have a clusterip for linkerd to be able to discover it as its based based on the target IP by default. I discovered this when trying to look at Per-Route Metrics and could not get it to work. Eventually i got help from @olix0r resolving it by adding a clusterip to my service. 
**What you expected to happen**:
The troubleshooting section of https://linkerd.io/2/tasks/getting-per-route-metrics/
could have a bullet stating that clusterip is needed. 
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
no
**Environment**:
- linkerd/namerd version, config files:
- Platform, version, and config files (Kubernetes, DC/OS, etc):
- Cloud provider or hardware configuration:

**Comment by cpretzer** [comment]
@twDuke, we'd love your help with this documentation if you're up for submitting a PR in the [linkerd website](https://github.com/linkerd/website) repo
