### ISSUE TITLE
viz: Add Control plane tracing

### ISSUE THREAD

**Issue by Pothulapati** [linkerd/linkerd2#5425]
## Feature Request

#5340 removed those templates from viz extension, and they should be added back.

**Comment by adleong** [comment]
Perhaps I misunderstand, but I thought this issue was about making sure we had the ability to add jaeger tracing to the main Linkerd control plane.  How does #5699 relate to this?

**Comment by adleong** [comment]
@Pothulapati

**Comment by Pothulapati** [comment]
Ah sorry, I marked the wrong issue initially and then changed but this still got closed.
