### ISSUE TITLE
Create update notes for linkerd-viz split

### ISSUE THREAD

**Issue by adleong** [linkerd/linkerd2#5437]
The viz components of Linkerd have been split into a new extension called Linkerd-Viz.  This means that running `linkerd install` is no longer sufficient to get observability; you must run `linkerd viz install` as well.

Write update documentation describing how to upgrade Linkerd from a version that has the viz components bundled in the main control plane to a version that has the linkerd-viz extension.

**Comment by piyushsingariya** [comment]
Hi @adleong, so basically BUILD.md needs to be updated?

**Comment by adleong** [comment]
See https://github.com/linkerd/website/pull/887

**Comment by Pothulapati** [comment]
Also, https://github.com/linkerd/linkerd2/pull/5673 updates the existing multi-stage upgrade to do pruning differently, This was needed to prevent the deletion of unwanted resources. Should we also add those to the docs? 🤔
