### ISSUE TITLE
Typo in check error message 

### ISSUE THREAD

**Issue by adleong** [linkerd/linkerd2#5438]
This check validates that `certOldKeyName` is present in the secret.  However, if it is not, the error message incorrectly refers to the `certKeyName` field.  This error message should be corrected.

https://github.com/linkerd/linkerd2/blob/main/pkg/healthcheck/healthcheck.go#L1734

**Comment by adleong** [comment]
This was first noticed in https://github.com/linkerd/linkerd2/issues/5423

**Comment by pradeepnnv** [comment]
I'd like to work on this issue.

**Comment by alpeb** [comment]
@pradeepnnv go for it! :+1: :partying_face:

**Comment by pradeepnnv** [comment]
Thanks @alpeb . I submitted a PR. Please review.
