### ISSUE TITLE
Update cert-manager docs to create certs with SAN

### ISSUE THREAD

**Issue by adleong** [linkerd/linkerd2#5440]
The documentation for using cert-manager with Linkerd:

https://linkerd.io/2/tasks/automatically-rotating-control-plane-tls-credentials/
https://linkerd.io/2/tasks/automatically-rotating-webhook-tls-credentials/

create Certificate resource which do not include the `dnsNames` field.  In turn, this causes cert-manager to issue leaf certs which do not include the SAN field.  This causes any go processes built with go 1.15+ to fail to validate these certs.  For example, this causes the Linkerd check command to fail if the CLI was built with go 1.15+.  

We should add the `dnsNames` field to the documentation to unblock upgrading to go 1.15 in the CLI.

**Comment by erwbgy** [comment]
Fixed by https://github.com/linkerd/website/pull/882.
