### ISSUE TITLE
test-cleanup should be extension aware

### ISSUE THREAD

**Issue by adleong** [linkerd/linkerd2#5441]
The `bin/test-cleanup` script does not delete linkerd extensions which have been installed on the cluster.  This can cause subsequent test runs to fail when those extensions are installed again.

The script should be updated to full delete all linkerd extensions.  It can use the `linkerd.io/extension` label to locate all resources associated with an extension.  This label may need to be added to extension resources which are missing it.

**Comment by yashvardhan-kukreja** [comment]
@adleong  I guess #5497 addresses this as #5497 leads to deleting the entire namespaces with the label `linkerd.io/is-test-data-plane` and the prior deletions also end up cleaning up the entire cluster of resources created by linkerd.(I tested it)
Still, if there's a strong reason to target deletions with respect to the label `linkerd.io/extension`, then, I think that the following command should suffice for that and I can create a PR addressing that:
```sh
kubectl --context="$k8s_context" delete ns -l linkerd.io/is-test-data-plane
```

**Comment by westford14** [comment]
hey @adleong just popping in here to say that i've opened up a small PR that addresses this issue. (https://github.com/linkerd/linkerd2/pull/7561)

**Comment by kleimkuhler** [comment]
As mentioned already, this should have already been closed by the extension `uninstall` subcommands that were added by #5498.
