### ISSUE TITLE
support external load balancer for multi-cluster link

### ISSUE THREAD

**Issue by kellybirr** [linkerd/linkerd2#5460]
## Feature Request
I am trying to link bare-metal clusters that do not have an integrated "LoadBalancer" provider but have perfectly functional external TCP load balancers.  I need to be able to do one or more of the following:

1. Tell `linkerd multicluster link` get the IP for the service from `spec.loadBalancerIP` or `spec.externalIPs` instead of `status.loadBalancer.ingress.ip`.  Both of these properties can be user defined for use with external load balancers.
2. Be able to provide a command line switch to specify the ip manually

### What problem are you trying to solve?
Use multi-cluster on bare-metal with external load balancers

### Any alternatives you've considered?

I've considered installing MetalLB, but it wont work with my clusters using calico without over-the-top BGP configurations.

### How would users interact with this feature?

Ideally:
`linkerd multicluster install --external-ip 10.4.3.2`

This would set the `spec.externalIPs` and  `spec.loadBalancerIP` on the service, the standard multicluster link command would then see no `status.loadBalancer.ingress.ip` and would fall-back to using the externalIP for the generated YAML.  This would be compatible with any scenario I can imagine.

Alternatively:
`linkerd --context east multicluster link --cluster-name east --ingress-ip 10.4.3.2`
This has the advantage of only a single area of change in the CLI.

### Thanks
If I was halfway decent with Go, I would offer a PR for the CLI.  I'll avoid embarrassing myself though.

**Comment by adleong** [comment]
https://github.com/linkerd/linkerd2/pull/5307 added a `--gateway-addresses` flag which I think addresses this.  However, it seems like this flag got accidentally removed in a recent change.  I've filed https://github.com/linkerd/linkerd2/issues/5471 to restore it.

**Comment by adleong** [comment]
Fixed by https://github.com/linkerd/linkerd2/pull/5473
