### ISSUE TITLE
Fast initialization for local development environment

### ISSUE THREAD

**Issue by jjangga0214** [linkerd/linkerd2#5466]
## Feature Request

Fast initialization for local development environment.

### What problem are you trying to solve?

On local development environment, I use lightweight clusters like [kind](https://kind.sigs.k8s.io/docs/user/quick-start/) or [k3d](https://k3d.io/).
To my experiments (on kind and k3d), Linkerd installation is so slow on such clusters, compared to production-ready clusters, like EKS.
On my machine, `kubectl get pod -n linkerd` shows pods become `READY` between 3 minutes to 4 minutes.

### How should the problem be solved?

I don't know whether it's possible, but if "lightweight mode", which does not support unnecessary advanced features, or lazily loads those feature, can be configured, then Linkerd would be able to provide an option for fast initialization?
(But actually being lightweight itself does not matter, the only important factor in this context is initialization speed, obviously)

For instance, `linkerd install --lightweight`, as like it already provides HA mode by `--ha` option for production.

Thanks!

**Comment by cpretzer** [comment]
@jjangga0214 this is right in line with the work that is going on to separate the control plane from linkerd-viz

I think you'll see what you're looking for over the next few edge releases and possibly the next stable release

**Comment by adleong** [comment]
I'll echo what @cpretzer said: we're currently working to make it possible to install a minimal control plane.
