### ISSUE TITLE
The linkerd install config command has missing flags and creates unneeded files

### ISSUE THREAD

**Issue by erwbgy** [linkerd/linkerd2#5467]
### What is the issue?

The `--identity-external-issuer` and `--disable-heartbeat` options are available when running `linkerd install` but not with `linkerd install config`.

Without `--disable-heartbeat` the `linkerd install config` command incorrectly adds:
```
- kind: ServiceAccount
  name: linkerd-heartbeat
  namespace: linkerd
``` 
and incorrectly creates:
* linkerd-heartbeat Role
* linkerd-heartbeat RoleBinding
* linkerd-heartbeat ServiceAccount

When using `--identity-external-issuer` with either command unused Secret objects are created:
* linkerd-proxy-injector-k8s-tls
* linkerd-sp-validator-k8s-tls
* linkerd-tap-k8s-tls

### How can it be reproduced?
```
$ linkerd install config --disable-heartbeat 2>&1 | grep Error
Error: unknown flag: --disable-heartbeat

$ linkerd install config --identity-external-issuer 2>&1 | grep Error
Error: unknown flag: --identity-external-issuer

$ linkerd install --identity-external-issuer | grep -A3 "kind: Secret"
kind: Secret
apiVersion: v1
metadata:
  name: linkerd-proxy-injector-k8s-tls
kind: Secret
apiVersion: v1
metadata:
  name: linkerd-sp-validator-k8s-tls
kind: Secret
apiVersion: v1
metadata:
  name: linkerd-tap-k8s-tls
```

### Environment

- Kubernetes Version: 1.18.11
- Cluster Environment: kubeadm
- Host OS: RHEL 8.2
- Linkerd version: edge-20.12.4

### Possible solution

Add missing flags to `linkerd install config`.  Do not create unused Secret files when `--identity-external-issuer` is used.

**Comment by cpretzer** [comment]
thanks @erwbgy I'll have a look at this today or tomorrow

**Comment by jimil749** [comment]
So, are we proposing to add the `--disable-heartbeat` and `--identity-external-issuer` flags to `linkerd install config` subcommand to prevent creating the extra files/configurations?

**Comment by kleimkuhler** [comment]
@Pothulapati Do you have any input on this? Is there a plan to move `install` flagsets to the helm way of customization through `set`, `set-string`, `values`, `set-files` flags?

**Comment by Pothulapati** [comment]
@kleimkuhler I dont think we have a plan to remove the current flags and setting them through helm way of things but we definitely want to add the helm flags along side the current flag. I will be working on this.

Irrespective, I would like to first confirm with @adleong, if multi-stage installl is still being supported or not as there have been conversations to remove it.

**Comment by piyushsingariya** [comment]
I think this issue should be closed!!! :thinking:

**Comment by kleimkuhler** [comment]
Yep thanks for noticing @piyushsingariya!
