### ISSUE TITLE
heartbeat: Report ServiceProfile usage

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#5474]
I'd like to begin deprecating the `ServiceProfile` CRD in 2.11 (to replaced by a family of more flexible traffic policy CRDs). We don't really have any insight, though, into how widely the `ServiceProfile` API is used and how impactful this change will be.

In advance of these changes, I propose that:

* The destination controller be instrumented with the total number of (unique) ServiceProfile instances currently in the cluster, e.g. `serviceprofile_instances_count`. This should be a gauge of the current number of service profile instances in the cluster that the controller is observing.
* The heartbeat reporter be updated to query/report this metric (presumably taking the maximum value from all destination controller instances).

**Comment by tharun208** [comment]
@olix0r I will take this up

**Comment by Pothulapati** [comment]
Update: @tharun208 is not working on this issue as it needs some checking on the receiver side. I think @adleong was planning to take this up.

**Comment by olix0r** [comment]
Per discussion, it might be preferable to avoid tracking metrics in prometheus and instead give the heartbeat job RBAC to enumerate service profile directly.
