### ISSUE TITLE
Use linkerd uninstall in test-cleanup script

### ISSUE THREAD

**Issue by kleimkuhler** [linkerd/linkerd2#5497]
The [test-cleanup](https://github.com/linkerd/linkerd2/blob/main/bin/test-cleanup) script used primarily in CI contains a lot of bash script
which is responsible for cleaning up a cluster after running tests.

The history that lead to the state that it is in is there was not always a
`linkerd uninstall` command, so we had to manually clear all the resources out.

We should now be able to use `linkerd uninstall` to remove a lot of of those
resources.

The resources that this will not uninstall are the test namespaces that we
create when running tests, but we should still be able to get rid of the rather
complex `populate_array` function. Running `kubectl --context="$k8s_context"
delete ns -l linkerd.io/is-test-data-plane` should be sufficient.

**Comment by yashvardhan-kukreja** [comment]
Hi @kleimkuhler . I am new to linkerd and lately, was looking forward to contribute to it. This issue seems like a nice place to start. So, I'd like to be assigned to this :)

**Comment by kleimkuhler** [comment]
Sounds good @yashvardhan-kukreja! I'll keep an eye out for the PR. Let me know if you have any questions.

**Comment by adleong** [comment]
@kleimkuhler has this been fixed by https://github.com/linkerd/linkerd2/pull/5494?

**Comment by kleimkuhler** [comment]
@adleong Nope this is about removing all the calls to `populate_array` in `test-cleanup` and using `linkerd uninstall` instead.
