### ISSUE TITLE
linkerd inject command does not work with Ubuntu 20.04

### ISSUE THREAD

**Issue by taiseerkhaled** [linkerd/linkerd2#5500]
### What is the issue?
After upgrading our cluster to Ubuntu 20.04, running linkerd inject command fails with the the error shown below

### How can it be reproduced?
on ubuntu 20.04 machine. 
kubectl get deploy <yourdep> -o yaml | linkerd inject - | kubectl apply -f -
### Logs, error output, etc
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x16c6478]

goroutine 1 [running]:
github.com/linkerd/linkerd2/cli/cmd.getOverrideAnnotations(0xc00010c340, 0xc00010d860, 0xc000646bf0)
        /linkerd-build/cli/cmd/inject.go:446 +0xde8
github.com/linkerd/linkerd2/cli/cmd.newCmdInject.func1(0xc000320840, 0xc0002d89c0, 0x1, 0x1, 0x0, 0x0)
        /linkerd-build/cli/cmd/inject.go:103 +0x1eb
github.com/spf13/cobra.(*Command).execute(0xc000320840, 0xc0002d8970, 0x1, 0x1, 0xc000320840, 0xc0002d8970)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0x2b1f960, 0x0, 0x17d7040, 0xc00007e058)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
        /linkerd-build/cli/main.go:10 +0x2d

(If the output is long, please create a [gist](https://gist.github.com/) and
paste the link here.)

#### `linkerd check` output

```text
linkerd check
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-identity
----------------
√ certificate config is valid
√ trust anchors are using supported crypto algorithm
√ trust anchors are within their validity period
√ trust anchors are valid for at least 60 days
√ issuer cert is using supported crypto algorithm
√ issuer cert is within its validity period
‼ issuer cert is valid for at least 60 days
    issuer certificate will expire on 2021-02-23T10:52:55Z
    see https://linkerd.io/checks/#l5d-identity-issuer-cert-not-expiring-soon for hints
√ issuer cert is issued by the trust anchor

linkerd-webhooks-and-apisvc-tls
-------------------------------
√ tap API server has valid cert
√ tap API server cert is valid for at least 60 days
√ proxy-injector webhook has valid cert
√ proxy-injector cert is valid for at least 60 days
√ sp-validator webhook has valid cert
√ sp-validator cert is valid for at least 60 days

linkerd-api
-----------
√ control plane pods are ready
√ control plane self-check
√ [kubernetes] control plane can talk to Kubernetes
√ [prometheus] control plane can talk to Prometheus
√ tap api service is running

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
‼ control plane is up-to-date
    is running version 2.7.0 but the latest stable version is 2.9.1
    see https://linkerd.io/checks/#l5d-version-control for hints
‼ control plane and cli versions match
    control plane running stable-2.7.0 but cli running stable-2.9.1
    see https://linkerd.io/checks/#l5d-version-control for hints

Status check results are √

```

### Environment

- Kubernetes Version: client: v1.18.5, Server: v1.16.14
- Cluster Environment: (GKE, AKS, kops, ...)  Tanzu
- Host OS: Ubuntu 20.04
- Linkerd version:
Client version: stable-2.9.1
Server version: stable-2.7.0

**Comment by olix0r** [comment]
I suspect that this isn't related to Ubuntu-20.04, but that the 2.9.1 CLI fails to handle metadata from the 2.7.0 control plane metadata properly.

This looks likely caused by our accessing of fields without getter-methods

**Comment by taiseerkhaled** [comment]
> I suspect that this isn't related to Ubuntu-20.04, but that the 2.9.1 CLI fails to handle metadata from the 2.7.0 control plane metadata properly.
> 
> This looks likely caused by our accessing of fields without getter-methods

Hi @olix0r, 
What you are saying makes a lot of sense. Let me check my previous docker image and see what versions of linkerd we are using there.
Please excuse my silly question, but what command shall I use install a specific linkerd cli version?

**Comment by olix0r** [comment]
@taiseerkhaled Generally, we only test sequential neighboring versions for compatibility. So, a 2.8.x CLI should work with a 2.7 control plane; and in order to upgrade from 2.7 to 2.9, we recommend upgrading to 2.8 first, and then to 2.9.

That said, we should fix the underlying segfault.

**Comment by taiseerkhaled** [comment]
> @taiseerkhaled Generally, we only test sequential neighboring versions for compatibility. So, a 2.8.x CLI should work with a 2.7 control plane; and in order to upgrade from 2.7 to 2.9, we recommend upgrading to 2.8 first, and then to 2.9.
> 
> That said, we should fix the underlying segfault.

@olix0r Thanks for your help. I used 2.8.1 for client version and it worked. This bug report can be closed.
