### ISSUE TITLE
Unable To View Success Rate & RPS

### ISSUE THREAD

**Issue by steventranjs** [linkerd/linkerd2#5508]
## Bug Report
We deployed linkerd into our k8s cluster and successfully got default namespace meshed BUT I do not see details like "Success Rate", "RPS" on default namespace. However, these details shows very clear on linkerd namespace.

We tried to deploy your emojivoto  example as in https://linkerd.io/2/getting-started/ and got same results

You can see below screenshot for details.
![image](https://user-images.githubusercontent.com/6488765/104178938-17487300-5446-11eb-9dbb-55c172abbb54.png)

### What is the issue?
We expect statistics like "Success Rate", "RPS" should fully shown

### How can it be reproduced?
- Install k8s using kubeadm
- Follow installation instruction as in https://linkerd.io/2/getting-started/

#### `linkerd check` output

```text
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
W0111 19:46:35.824502   18174 warnings.go:67] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
√ control plane CustomResourceDefinitions exist
W0111 19:46:35.839483   18174 warnings.go:67] admissionregistration.k8s.io/v1beta1 MutatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 MutatingWebhookConfiguration
√ control plane MutatingWebhookConfigurations exist
W0111 19:46:35.848076   18174 warnings.go:67] admissionregistration.k8s.io/v1beta1 ValidatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 ValidatingWebhookConfiguration
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-cni-plugin
------------------
√ cni plugin ConfigMap exists
√ cni plugin PodSecurityPolicy exists
√ cni plugin ClusterRole exists
√ cni plugin ClusterRoleBinding exists
√ cni plugin Role exists
√ cni plugin RoleBinding exists
√ cni plugin ServiceAccount exists
√ cni plugin DaemonSet exists
√ cni plugin pod is running on all nodes

linkerd-identity
----------------
√ certificate config is valid
√ trust anchors are using supported crypto algorithm
√ trust anchors are within their validity period
√ trust anchors are valid for at least 60 days
√ issuer cert is using supported crypto algorithm
√ issuer cert is within its validity period
√ issuer cert is valid for at least 60 days
√ issuer cert is issued by the trust anchor

linkerd-webhooks-and-apisvc-tls
-------------------------------
√ tap API server has valid cert
√ tap API server cert is valid for at least 60 days
W0111 19:46:36.106966   18174 warnings.go:67] admissionregistration.k8s.io/v1beta1 MutatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 MutatingWebhookConfiguration
√ proxy-injector webhook has valid cert
√ proxy-injector cert is valid for at least 60 days
W0111 19:46:36.502199   18174 warnings.go:67] admissionregistration.k8s.io/v1beta1 ValidatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 ValidatingWebhookConfiguration
√ sp-validator webhook has valid cert
√ sp-validator cert is valid for at least 60 days

linkerd-api
-----------
√ control plane pods are ready
√ control plane self-check
√ [kubernetes] control plane can talk to Kubernetes
√ [prometheus] control plane can talk to Prometheus
√ tap api service is running

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ control plane is up-to-date
√ control plane and cli versions match
W0111 19:46:37.890969   18174 warnings.go:67] admissionregistration.k8s.io/v1beta1 MutatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 MutatingWebhookConfiguration

linkerd-prometheus
------------------
√ prometheus add-on service account exists
√ prometheus add-on config map exists
√ prometheus pod is running

linkerd-grafana
---------------
√ grafana add-on service account exists
√ grafana add-on config map exists
√ grafana pod is running

linkerd-tracing
---------------
√ collector service account exists
√ jaeger service account exists
√ collector config map exists
√ collector pod is running
√ jaeger pod is running

Status check results are √
```

### Environment

- Kubernetes Version: 1.20
- Cluster Environment: Kubeadm
- Host OS: Ubuntu
- Linkerd version: latest stable [2.x]

**Comment by adleong** [comment]
Weird!  Check doesn't show any errors so I would expect that stats should be visible.  A few things you can try to dig further in:

* Run `linkerd check  --proxy -n emojivoto` to check the health of the proxies in the emojivoto namespace
* Run `linkerd metrics <pod>` to see if you can get proxy metrics from pods in the emojivoto namespace
* Run `linkerd stat deploy -n emojivoto` to see if you can get stats on the CLI

**Comment by steventranjs** [comment]
@adleong Thanks a lot for ur hint. After I restarted my cluster and try ur command. `emojivoto` namespace started to shows metrics. BUT the default one still empty. Any way I can continue on this? Thanks
![image](https://user-images.githubusercontent.com/6488765/104227257-120a1900-5484-11eb-84bc-83ff5f08ba2b.png)

**Comment by cpretzer** [comment]
@steventranjs You can use the same Linkerd CLI commands on the `default` namespace to inspect the metrics there:

- Run `linkerd check --proxy -n default` to check the health of the proxies in the default namespace
- Run `linkerd metrics <pod>` to see if you can get proxy metrics from pods in the default namespace
- Run `linkerd stat deploy -n default` to see if you can get stats on the CLI

What kind of traffic is used by the services in the default namespace (HTTP, TCP, gRPC, etc.)?

**Comment by adleong** [comment]
@steventranjs are you still experiencing the issue?  have the commands that @cpretzer posted been helpful at all?

**Comment by steventranjs** [comment]
@adleong I will pm details later sorry was not able to recovered yet

**Comment by adleong** [comment]
@steventranjs I'm going to close this due to idleness.  Please feel free to reopen when you are able to send the additional details.  Thanks!
