### ISSUE TITLE
Option to not have linkerd-viz helm chart create namespace

### ISSUE THREAD

**Issue by tustvold** [linkerd/linkerd2#5512]
## Feature Request

Add a `installNamespace` flag to the linkerd-viz helm chart to match the one present in the main linkerd2 helm chart.

### What problem are you trying to solve?

It is beneficial to be able to create namespaces outside of Helm, in part to avoid chicken-and-egg situations with regards to where Helm stores its metadata, but also because namespaces may need to integrate with access control, etc... In my particular case I need to add custom labels as I'm using 

### How would users interact with this feature?

`--set installNamespace=false`

**Comment by pradeepnnv** [comment]
I would like to work on this issue.

**Comment by adleong** [comment]
@pradeepnnv fantastic!

**Comment by pradeepnnv** [comment]
This flag is already added as part of this commit.

https://github.com/linkerd/linkerd2/commit/8eab38d15e211e33889382637845bc15bac3a642

Does this mean this issue is already fixed?

**Comment by adleong** [comment]
Ah, you're right.  It looks like it was fixed by https://github.com/linkerd/linkerd2/pull/5509.  Sorry about that!
