### ISSUE TITLE
CSRF protection - Django rejects incoming request for injected deployment

### ISSUE THREAD

**Issue by ipaleka** [linkerd/linkerd2#5515]
### What is the issue?

Injected deployment of a Django application served by Gunicorn can't pass Django's [Cross Site Request Forgery](https://docs.djangoproject.com/en/3.1/ref/csrf/) protection. If Linkerd is not set or it is uninjected then everything works as expected.

Gunicorn and nginx redirect to my [custom 403_csrf.html template](https://docs.djangoproject.com/en/3.1/ref/settings/#csrf-failure-view) for every template that has got Django's `{% csrf_token %}` tag inside a form. 

If that `{% csrf_token %}` tag is removed from a template then the response is valid 200 (or normal redirect), but that, well, isn't a solution in this case.

### How can it be reproduced?

I've tried to find a suitable minimal Django app in a Kubernetes cluster. Nothing yet to present tho.

### Logs, error output, etc

Nginx/Gunicorn outputs the following message:

`Forbidden (Referer checking failed - no Referer.): /accounts/signup/)`

#### `linkerd check` output

```
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
W0111 21:29:44.371896   90019 warnings.go:67] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
√ control plane CustomResourceDefinitions exist
W0111 21:29:44.382351   90019 warnings.go:67] admissionregistration.k8s.io/v1beta1 MutatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 MutatingWebhookConfiguration
√ control plane MutatingWebhookConfigurations exist
W0111 21:29:44.387045   90019 warnings.go:67] admissionregistration.k8s.io/v1beta1 ValidatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 ValidatingWebhookConfiguration
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-identity
----------------
√ certificate config is valid
√ trust anchors are using supported crypto algorithm
√ trust anchors are within their validity period
√ trust anchors are valid for at least 60 days
√ issuer cert is using supported crypto algorithm
√ issuer cert is within its validity period
√ issuer cert is valid for at least 60 days
√ issuer cert is issued by the trust anchor

linkerd-webhooks-and-apisvc-tls
-------------------------------
√ tap API server has valid cert
√ tap API server cert is valid for at least 60 days
W0111 21:29:44.420982   90019 warnings.go:67] admissionregistration.k8s.io/v1beta1 MutatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 MutatingWebhookConfiguration
√ proxy-injector webhook has valid cert
√ proxy-injector cert is valid for at least 60 days
W0111 21:29:44.788862   90019 warnings.go:67] admissionregistration.k8s.io/v1beta1 ValidatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 ValidatingWebhookConfiguration
√ sp-validator webhook has valid cert
√ sp-validator cert is valid for at least 60 days

linkerd-api
-----------
√ control plane pods are ready
√ control plane self-check
√ [kubernetes] control plane can talk to Kubernetes
√ [prometheus] control plane can talk to Prometheus
√ tap api service is running

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ control plane is up-to-date
√ control plane and cli versions match
W0111 21:29:46.043774   90019 warnings.go:67] admissionregistration.k8s.io/v1beta1 MutatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 MutatingWebhookConfiguration

linkerd-prometheus
------------------
√ prometheus add-on service account exists
√ prometheus add-on config map exists
√ prometheus pod is running

linkerd-grafana
---------------
√ grafana add-on service account exists
√ grafana add-on config map exists
√ grafana pod is running

Status check results are √
```

### Environment

- Kubernetes Version: v1.20.1
- Cluster Environment: one master and two worker nodes in OracleBox VMs on Debian testing host
- Host OS: Ubuntu 20.04 (master and worker nodes)
- Linkerd version: stable-2.9.1

### Additional context

From a pod running Gunicorn:

```
$ python3 --version
Python 3.8.5

$ pip list
...
Django                        3.1.5
django-allauth                0.44.0
gunicorn                      20.0.4
```
[django-allauth](https://github.com/pennersr/django-allauth)

I have Linkerd's Prometheus up and running, so please tell me if anything from there can help. Or from any other log. Also, I'll try to check in a [kind cluster](https://kind.sigs.k8s.io/) too.

**Comment by olix0r** [comment]
Linkerd shouldn't do anything to interfere with a request's headers; but if your CSRF protection is trying to do something to validate the client's IP address, the linkerd proxy will necessarily interfere with this check, because all requests from the proxy to your application will be sent over the localhost network.

I'm afraid that you'll have to use [inbound-skip-ports](https://linkerd.io/2/features/protocol-detection/) to prevent iptables from routing these connections through the proxy or modify your CSRF prevention to be agnostic of the client IP. I don't think we have any ability to preserve the client's IP to your application.

This is all a guess, though. If you're able to provide an example application, we'd be happy to confirm this.

**Comment by olix0r** [comment]
Actually, my assumption may be incorrect. https://docs.djangoproject.com/en/2.2/_modules/django/middleware/csrf/ does not appear to have any references to the client IP; and that error (`Referer checking failed - no Referer.`) does appear to indicate that the request does not have a `Referer` header; but Linkerd shouldn't interfere with `Referer` headers...

Are you able to run your workload with the annotation `config.linkerd.io/proxy-log-level: linkerd=debug,linkerd2_proxy_http=trace,warn`? This should help us to have a deeper understanding of what the proxy is doing in this case.

**Comment by ipaleka** [comment]
I can do that, but your comment has brought me to something else, a html's head c/p from another template that maybe I left. After kind cluster provisioning finishes, I'll first try to check that, and then if it doesn't help I'll set that annotation.

**Comment by ipaleka** [comment]
Well done @olix0r, I've seen/read that message about Referer from Gunicorn/Nginx at least twenty times today, was thinking about [this setting](https://docs.djangoproject.com/en/3.1/ref/settings/#csrf-trusted-origins), but has to be your comment to remind me of silly c/p of `<meta name="referrer" content="no-referrer">` in my Django base template. XD

The most beautiful product you have indeed, I have started to learn about service mesh day before yesterday decided to use Linkerd yesterday and today I have powered functional product that has started help me finding bugs (Django, how the heck this works without Linkerd injection?!) without even powering stat or Prometheus. :)

Please close, best regards!
