### ISSUE TITLE
More helpful error when attempting to `linkerd upgrade` a Helm installation

### ISSUE THREAD

**Issue by adleong** [linkerd/linkerd2#5518]
If Linkerd is installed with Helm, it is not possible to upgrade that installation using `linkerd upgrade`; only Helm can be used to upgrade.  However, attempting to use `linkerd upgrade` on a Helm installation of Linkerd gives a confusing error:

```
bin/linkerd upgrade
Error: failed to validate issuer credentials: failed to read CA: not PEM-encoded
```

I believe this is because it is attempting (and failing) to load the CA from the (non-existent) linkerd-config-overrides secret.  Instead, if `linkerd upgrade` is run on a Helm installation where linkerd-config-overrides does not exist should return an error message that prompts the user to upgrade with Helm instead.

**Comment by pradeepnnv** [comment]
I'd like to work on this issue.

**Comment by cpretzer** [comment]
Great, thanks @pradeepnnv!

Please be sure to join the #contributors channel on [Linkerd Slack](https://slack.linkerd.io) to chat with other contributors and get answers to any questions that come up

**Comment by coderfornow** [comment]
is it available ?

**Comment by kleimkuhler** [comment]
@coderfornow Yep this available if you'd like to work on it!

**Comment by piyushsingariya** [comment]
Hi @adleong, I would like to take this issue. However, I have a small doubt about how do we exactly know that Linkerd has been installed using **Helm**.

**Comment by adleong** [comment]
The simplest heuristic is to look for the `linkerd-config-overrides` secret.  This secret will exist if Linkerd was installed with the CLI but will not exist if it was installed with Helm.

**Comment by adleong** [comment]
Fixed by https://github.com/linkerd/linkerd2/pull/5636
