### ISSUE TITLE
Linkerd Destination crash if endpoint slices enabled

### ISSUE THREAD

**Issue by oleh-ozimok** [linkerd/linkerd2#5521]
### What is the issue?
Linkerd Destination crash if endpoint slices enabled (-enable-endpoint-slices=true)
### How can it be reproduced?
Run Linkerd Destination with -enable-endpoint-slices=true flag
### Logs, error output, etc
`
panic: assignment to entry in nil map
/linkerd-build/controller/api/destination/watcher/endpoints_watcher.go:616 +0x1b4
github.com/linkerd/linkerd2/controller/api/destination/watcher.(*EndpointsWatcher).Subscribe(0xc000342380, 0xc0013f51da, 0x7, 0xc0013f51c0, 0x19, 0x1f90, 0x0, 0x0, 0x1f50e80, 0xc0009ef830, ...)
`

#### `linkerd check` output

```text
your output here ...
```

### Environment

- Kubernetes Version: 1.20.1
- Cluster Environment: (GKE, AKS, kops, ...)
- Host OS: Debian 10
- Linkerd version: edge-21.1.1

### Possible solution

change 

```
func (pp *portPublisher) endpointSliceToAddresses(es *discovery.EndpointSlice) AddressSet {
	addresses := make(map[ID]Address)
	resolvedPort := pp.resolveESTargetPort(es.Ports)
	if resolvedPort == Port(0) {
		return AddressSet{}
	}
```

to 

```
func (pp *portPublisher) endpointSliceToAddresses(es *discovery.EndpointSlice) AddressSet {
	addressSet :=  AddressSet{
	   Addresses: make(map[ID]Address),
	}
	
	resolvedPort := pp.resolveESTargetPort(es.Ports)
	if resolvedPort == Port(0) {
		return addressSet
	}
```

**Comment by olix0r** [comment]
@oleh-ozimok Thanks for the helpful bug report! Do you have time to submit a PR with your suggested fix?
