### ISSUE TITLE
Tap controller should exclude pods with tap disabled

### ISSUE THREAD

**Issue by adleong** [linkerd/linkerd2#5544]
If you run `linkerd viz tap` targeting a workload which has tap disabled or has not been injected by the tap-injector, the tap command simply waits and produces no output.

In some sense, this behavior is correct.  However, it can be unexpected, and users will encounter this situation more frequently now that the tap-injector is no longer part of the default proxy-injector.  

To remedy this, the tap controller can attempt to determine if a target pod is tapable by examining the environment variables of its proxy sidecar.  If a target pod is not tapable, it should be excluded from the list of tap targets.  If the list of tap targets is empty, the tap controller should return a helpful error message to the user informing them that there are no tapable pods in the target workload and to ensure that the pods exist and have been injected by the tap-injector.

Note that with https://github.com/linkerd/linkerd2/issues/5325#issuecomment-760575199 implemented, the `linkerd viz check --proxy` command can be used to diagnose this.

**Comment by olix0r** [comment]
Rather than relying on environment variables, it would be preferable to use workload annotations, if possible. Can/should the tap injector set a disable annotation on pods?
