### ISSUE TITLE
helm: Replace configurable annotation names with include

### ISSUE THREAD

**Issue by adleong** [linkerd/linkerd2#5574]
The Linkerd chart and the extension charts contain values for configuring the name of certain annotations such as `createdByAnnotation`.  In practice, the name of these annotations should never be changed.  These Helm variables are intended to simply be used as constants.

Instead, replace these variables with `include` statements which allows us to define these constants once but also does not expose them as user modifiable.

**Comment by coderfornow** [comment]
can you assign this to me?

**Comment by alpeb** [comment]
Hi @coderfornow , do you need any assistance with this one? :slightly_smiling_face:
