### ISSUE TITLE
Linkerd + Calico + EKS not working

### ISSUE THREAD

**Issue by douglmil** [linkerd/linkerd2#5576]
### What is the issue?
Linkerd pod injection does not work when installed along with Calico in EKS.

### How can it be reproduced?
Deploy Linkerd in an EKS cluster running with a default install of calico cni.

### Logs, error output, etc

linkderd check:  FailedDiscoveryCheck: failing or missing response from https://192.168.200.144:8089/apis/tap.linkerd.io/v1alpha1: Get https://192.168.200.144:8089/apis/tap.linkerd.io/v1alpha1: Address is not allowed

I see the same error is the kubernetes api-server log in eks

#### `linkerd check` output

--------------
âˆš can initialize the client
âˆš can query the Kubernetes API

kubernetes-version
------------------
âˆš is running the minimum Kubernetes API version
âˆš is running the minimum kubectl version

linkerd-existence
-----------------
âˆš 'linkerd-config' config map exists
âˆš heartbeat ServiceAccount exist
âˆš control plane replica sets are ready
âˆš no unschedulable pods
âˆš controller pod is running
âˆš can initialize the client
âˆš can query the control plane API

linkerd-config
--------------
âˆš control plane Namespace exists
âˆš control plane ClusterRoles exist
âˆš control plane ClusterRoleBindings exist
âˆš control plane ServiceAccounts exist
âˆš control plane CustomResourceDefinitions exist
âˆš control plane MutatingWebhookConfigurations exist
âˆš control plane ValidatingWebhookConfigurations exist
âˆš control plane PodSecurityPolicies exist

linkerd-identity
----------------
âˆš certificate config is valid
âˆš trust anchors are using supported crypto algorithm
âˆš trust anchors are within their validity period
âˆš trust anchors are valid for at least 60 days
âˆš issuer cert is using supported crypto algorithm
âˆš issuer cert is within its validity period
âˆš issuer cert is valid for at least 60 days
âˆš issuer cert is issued by the trust anchor

linkerd-webhooks-and-apisvc-tls
-------------------------------
âˆš tap API server has valid cert
âˆš tap API server cert is valid for at least 60 days
âˆš proxy-injector webhook has valid cert
âˆš proxy-injector cert is valid for at least 60 days
âˆš sp-validator webhook has valid cert
âˆš sp-validator cert is valid for at least 60 days

linkerd-api
-----------
âˆš control plane pods are ready
âˆš control plane self-check
âˆš [kubernetes] control plane can talk to Kubernetes
âˆš [prometheus] control plane can talk to Prometheus
â€¼ tap api service is running
    FailedDiscoveryCheck: failing or missing response from https://192.168.200.144:8089/apis/tap.linkerd.io/v1alpha1: Get https://192.168.200.144:8089/apis/tap.linkerd.io/v1alpha1: Address is not allowed
    see https://linkerd.io/checks/#l5d-tap-api for hints

linkerd-version
---------------
âˆš can determine the latest version
â€¼ cli is up-to-date
    is running version 2.9.1 but the latest stable version is 2.9.2
    see https://linkerd.io/checks/#l5d-version-cli for hints

control-plane-version
---------------------
â€¼ control plane is up-to-date
    is running version 2.9.1 but the latest stable version is 2.9.2
    see https://linkerd.io/checks/#l5d-version-control for hints
âˆš control plane and cli versions match

linkerd-prometheus
------------------
âˆš prometheus add-on service account exists
âˆš prometheus add-on config map exists
âˆš prometheus pod is running

linkerd-grafana
---------------
âˆš grafana add-on service account exists
âˆš grafana add-on config map exists
âˆš grafana pod is running

Status check results are âˆš

### Environment

- Kubernetes Version: 1.17
- Cluster Environment: (EKS)
- Host OS: ubuntu
- Linkerd version: 2.9.1

### Possible solution
Need help finding one

### Additional context

I am trying to run linkerd along with calico on an EKS deployment in AWS.  I am not able to get pod injection functioning seemingly due to failed communication with the kubernetes api-server (the linkerd tap pod seems to be the one having the issue).  I understand this is likely due to a disconnect between calico on the worker nodes and the aws cni running on the master node.  The work around for other pods has been the enable host networking to allow api-server communication.  I have not been able to deploy linkerd with hostnetwork=true.  Should this be possible?   If not does anyone no if a way to get EKS + calico + linkerd working?

Note from calico site on need for hostnetwork on eks:
Calico networking cannot currently be installed on the EKS control plane nodes. As a result the control plane nodes will not be able to initiate network connections to Calico pods. (This is a general limitation of EKS’s custom networking support, not specific to Calico.) As a workaround, trusted pods that require control plane nodes to connect to them, such as those implementing admission controller webhooks, can include hostNetwork:true in their pod spec. See the Kuberentes API pod spec definition for more information on this setting.

**Comment by adleong** [comment]
Hi @douglmil. I haven't tried running Linkerd with Calico on EKS but based on the networking restrictions that you describe, it's not too surprising that this doesn't work.  Linkerd relies heavily on webhooks to do things like proxy injection and to serve the tap API.  Linkerd also prohibits running in hostNetwork mode because proxy injection involves modifying the iptables for the pod.

Unfortunately, I don't really see a way around this until that limitation of EKS's custom networking support can be lifted.

**Comment by douglmil** [comment]
hi @adleong,  Do you know if there are other CNI's such as cillium that allow for intergration with linkerd?

**Comment by adleong** [comment]
Any CNI that doesn't impose the networking restriction that prevents the control plane from connecting to pods should work.

**Comment by douglmil** [comment]
@adleong, Any particular recommendations?

**Comment by adleong** [comment]
Sorry, I don't personally have any CNI recommendations.

**Comment by Paragon1970** [comment]
Hitting the same issue sadly. 
https://linkerd.slack.com/archives/C89RTCWJF/p1614097262059300
