### ISSUE TITLE
Refactor BuildResource and BuildResource to remove public-api dependency on viz

### ISSUE THREAD

**Issue by alpeb** [linkerd/linkerd2#5589]
Refactor the `BuildResource` and `BuildResources` functions in `controller/api/util/api_utils.go` that are used by `cli/cmd/metrics` so that instead of returning viz' `pb.Resource` they return an internal struct or something from k8s ' apimachinery. That way we can remove the public-api dependency on viz.

Other places in viz that depend on these functions (`stat`, `edges`, `routes` and `tap` (soon)) would need to convert between `pb.Resource` and that new struct, if needed.

**Comment by kleimkuhler** [comment]
This is worth keeping open so that we can remove this dependency in the docker files.
