### ISSUE TITLE
Linkerd Upgrade process does not preserve "skipped" ports

### ISSUE THREAD

**Issue by dayglojesus** [linkerd/linkerd2#5594]
By default, `linkerd-proxy` will avoid negotiating TLS on certain ports. <~ not sure where these ports are officially documented, but there is a ref to them [here in #5093](https://github.com/linkerd/linkerd2/pull/5093#pullrequestreview-510710583).

During a fresh **install**, if one passes `--skip-outbound-ports`, the `linkerd` binary will append any of the ports specified to this default list. However ...

During an **upgrade**, the skipped ports during the original install are **not preserved**.

I've run into this situation twice now, so some documentation seems appropriate -- see [linkerd2 #4257](https://github.com/linkerd/linkerd2/issues/4257).

**Comment by dayglojesus** [comment]
@adleong ok, you know what ... I have no idea what the behaviour is anymore. I will close this.

**Comment by dayglojesus** [comment]
@adleong Actually, I take that back ... Here's what I am trying to say ...

```
$ ~/bin/linkerd-stable-2.8.1 install --ignore-cluster --skip-outbound-ports 9999 | grep 9999
    {"proxyImage":{"imageName":"gcr.io/linkerd-io/proxy","pullPolicy":"IfNotPresent"},"proxyInitImage":{"imageName":"gcr.io/linkerd-io/proxy-init","pullPolicy":"IfNotPresent"},"controlPort":{"port":4190},"ignoreInboundPorts":[],"ignoreOutboundPorts":[{"portRange":"9999"}],"inboundPort":{"port":4143},"adminPort":{"port":4191},"outboundPort":{"port":4140},"resource":{"requestCpu":"","requestMemory":"","limitCpu":"","limitMemory":""},"proxyUid":"2102","logLevel":{"level":"warn,linkerd=info"},"disableExternalProfiles":true,"proxyVersion":"stable-2.8.1","proxyInitImageVersion":"v1.3.3","debugImage":{"imageName":"gcr.io/linkerd-io/debug","pullPolicy":"IfNotPresent"},"debugImageVersion":"stable-2.8.1","destinationGetNetworks":"10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"}
    {"cliVersion":"stable-2.8.1","flags":[{"name":"skip-outbound-ports","value":"[9999]"}]}
        - 443,9999
        - 443,9999
        - 443,9999
        - 443,9999
        - 443,9999
        - 443,9999
        - 443,9999
        - 443,9999
        - 443,9999
```

VS.

```
$ ~/bin/linkerd-stable-2.9.2 install --ignore-cluster --skip-outbound-ports 9999 | grep 9999
        ignoreOutboundPorts: "9999"
        - "9999"
        - "9999"
        - "9999"
        - "9999"
        - "9999"
        - "9999"
        - "9999"
        - "9999"
        - "9999"
```

So, re-phrase it anyway required the behaviour in the code above is what I am trying to document because it's confusing and difficult to describe.

**Comment by adleong** [comment]
Ah, yes, I see what you mean now.

In 2.8.1 we would append the specified skip ports to the list of defaults while in 2.9.2 we simply use the specified skip ports list as-is.  There are two main reasons why this behavior was changed: 

1. It's simpler: whatever skip ports you pass is are the ones that Linkerd will use.  What you see is what you get.
2. It gives you a mechanism to un-set skip ports from the default list.  Previously if you wanted to remove a skip port from the default list, there was no way to do it.  By expecting that you will pass in the full list, you can include or omit whichever skip ports you decide.

The flag documentation says:

> Ports and/or port ranges (inclusive) that should skip the proxy and send directly to the application

This doesn't talk mention appending to the default list, so I think the documentation is already correct here.

**Comment by dayglojesus** [comment]
Thanks @adleong. What page is that quoted from? I thin it deserves some greater emphasis 😅

**Comment by adleong** [comment]
`linkerd install --help`

or

https://linkerd.io/2/reference/cli/install/
