### ISSUE TITLE
Add 5432 to default skip ports?

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#5595]
We've had a bunch of issues recently referencing port 5432 which is used by Amazon RDS and, I believe Postgres. If we do a stable-2.9.3, should we include this skip port? We'll still need to fold this into https://github.com/linkerd/linkerd2/issues/5571 for stable-2.10...

**Comment by kleimkuhler** [comment]
This was back-ported to `stable-2.9.3` but was not cherry-picked from `main`. Reopening and should be addressed in #5810
