### ISSUE TITLE
linkerd v2.9.2 upgrade Error: failed to validate issuer credentials: failed to read CA: not PEM-encoded

### ISSUE THREAD

**Issue by samstride** [linkerd/linkerd2#5598]
## Bug Report

Linkerd (v 2.x) was originally installed using:

```sh
linkerd install | kubectl apply -f -
```

Been able to upgrade without any issues until v2.9.0.

Running into issue upgrading control plane from v2.9.0 to v2.9.2:

```sh
linkerd upgrade | kubectl apply --prune -l linkerd.io/control-plane-ns=linkerd -f -
```

### What is the issue?

Upgrade fails with following error:

```
Error: failed to validate issuer credentials: failed to read CA: not PEM-encoded
```

#### `linkerd check` output

```text
control-plane-version
---------------------
‼ control plane is up-to-date
    is running version 2.9.0 but the latest stable version is 2.9.2
    see https://linkerd.io/checks/#l5d-version-control for hints
‼ control plane and cli versions match
    control plane running stable-2.9.0 but cli running stable-2.9.2
    see https://linkerd.io/checks/#l5d-version-control for hints
```

### Environment

- Kubernetes Version: Rancher v1.18.4
- Linkerd client version: stable-2.9.2
- Linkerd server version: 2.9.0

**Comment by kleimkuhler** [comment]
@samstride Was the original installation through Helm by chance?

**Comment by adleong** [comment]
Possibly related: https://github.com/linkerd/linkerd2/issues/5518

**Comment by samstride** [comment]
> @samstride Was the original installation through Helm by chance?

Originally installed using:

```sh
linkerd install | kubectl apply -f -
```

**Comment by dragonde** [comment]
Same issue for me:

`linkerd upgrade
Error: failed to validate issuer credentials: failed to read CA: not PEM-encoded`

The funny thing is that I have a very similar cluster and I upgraded it to 2.9.2 some days ago without problem.
 
I also installed it with:
`linkerd install | kubectl apply -f -
`

**Comment by samstride** [comment]
@dragonde , were you going from 2.9.0 -> 2.9.2?

I had another GKE cluster which was on 2.9.1 and I could upgrade that without any issues.

**Comment by adleong** [comment]
Thanks for the information everybody!  I was able to reproduce this by installing Linkerd 2.8.0, upgrading to 2.9.0, and then attempting to upgrade to 2.9.2.  I'll spend some more time digging into this.

**Comment by dragonde** [comment]
> @dragonde , were you going from 2.9.0 -> 2.9.2?
> 
> I had another GKE cluster which was on 2.9.1 and I could upgrade that without any issues.

No, I am trying to upgrade from 2.9.1 -> 2.9.2

**Comment by adleong** [comment]
A quick update: this issue is caused by a bug in stable-2.9.x where the `linkerd-config-overrides` secret is missing a label that it's supposed to have.  This results in that secret getting pruned when performing a Linkerd upgrade with the prune flag which then prevents any further upgrades from taking place.  

We're working on adding some better error messages around this and adding tooling to help recover from this situation (https://github.com/linkerd/linkerd2/pull/5636).  These fixes will be included in stable-2.9.3 which we'll try to get released as soon as possible.

Thanks again for the report and hold tight.

**Comment by samstride** [comment]
@adleong , out of curiosity, is it possible to bake `repair` into `upgrade` for `v2.9.3` for the cli upgrade?

I am assuming there is no harm in performing a repair even if it is not needed.

That way users of affected installations don't raise another issue because they forgot to read the docs?

**Comment by samstride** [comment]
Sweet, upgraded CLI to `2.9.3` and followed the instructions in the upgrade docs.

I can now upgrade from `2.9.1` to `2.9.3`.

Thank you.
