### ISSUE TITLE
Not all Docker image names can be configured using helm chart values

### ISSUE THREAD

**Issue by mroohian** [linkerd/linkerd2#5604]
### What is the issue?

Not all Docker image names can be configured using helm chart values making it impossible for us to use our private registry.

### How can it be reproduced?

Using helm to install Linkerd does not give the possibility to change all docker image names as variables.

### Logs, error output, etc
Using the following command:

```bash
helm --dry-run --debug install linkerd2 \
--set global.imagePullSecrets[0].name=regcred \
--set controllerImage=registry.company.com/linkerd/controller \
--set debugContainer.image.name=registry.company.com/linkerd/debug \
--set global.proxy.image.name=registry.company.com/linkerd/proxy \
--set global.proxyInit.image.name=registry.company.com/linkerd/proxy-init \
--set-file global.identityTrustAnchorsPEM=ca.crt \
--set-file identity.issuer.tls.crtPEM=issuer.crt \
--set-file identity.issuer.tls.keyPEM=issuer.key \
--set identity.issuer.crtExpiry="2022-01-25T14:40:07Z" \
  linkerd/linkerd2 > output.yaml
```

The `output.yaml` file still contains these images:
```text
ghcr.io/linkerd/grafana
ghcr.io/linkerd/grafana:stable-2.9.2
ghcr.io/linkerd/web
ghcr.io/linkerd/web:stable-2.9.2
```

### Environment

- Kubernetes Version: v1.19.6
- Cluster Environment: Rancher
- Host OS: debian
- Linkerd version: stable-2.9.2

### Possible solution

Add these image names as parameters to values file.

### Additional context

N/A

**Comment by olix0r** [comment]
Looking at https://github.com/linkerd/linkerd2/blob/d5e9d56ce431bdf5ec02e51461ec0cf4bfdd783c/charts/linkerd2/values.yaml -- it looks as if there are settings to control these image names as well?

**Comment by mroohian** [comment]
correct! I missed `webImage` and `grafana.image.name`. sorry for the noise.
