### ISSUE TITLE
Linkerd dashboard does not load in versions of Chrome 88+

### ISSUE THREAD

**Issue by dadjeibaah** [linkerd/linkerd2#5612]
### What is the issue?
The Linkerd dashboard does not load and displays the error message below
![Screen Shot 2021-01-26 at 11 36 29 AM](https://user-images.githubusercontent.com/2197104/105890338-d8352880-5fd4-11eb-9ccd-0a7c28f463ec.png)
It looks like this issue occurs in versions of Chrome 88 and higher. Upon further investigation, it looks like material-ui has a bug that that is only present in this version of Chrome. More details here: https://github.com/mui-org/material-ui/issues/24549 

### How can it be reproduced?
- Make sure you are using Chrome version 88 or higher
- Check out the main linkerd2 branch
- Run `bin/web dev`
- navigate to http://localhost:7777
### Logs, error output, etc

Error message is in the screenshot above. 

### Possible solution

Material-UI released https://github.com/mui-org/material-ui/releases/tag/v4.11.3 which directly fixes this issue. Linkerd's dashboard uses material-ui https://github.com/mui-org/material-ui/releases/tag/v4.9.11. We could upgrade to the latest version of Material UI to fix this issue but we should do some UI testing to make sure things work as expected between the minor upgrade.

**Comment by Pothulapati** [comment]
Ran into this today and was unable to view the dashboard. As most users are on the latest browser versions, I think this should be fixed. 🤔

**Comment by dadjeibaah** [comment]
Including some additional info. It looks like the dashboard for stable-2.9.2 is unaffected. However, the latest edge release is affected by this bug.

![Screen Shot 2021-02-02 at 12 07 49 PM](https://user-images.githubusercontent.com/2197104/106643510-75e9a400-654f-11eb-8c2b-0953281f814e.png)
