### ISSUE TITLE
linkerd-viz chart should allow customization of "web" Service

### ISSUE THREAD

**Issue by agaffney** [linkerd/linkerd2#5617]
### What problem are you trying to solve?

I need to add custom annotations to the "web" Service.

Most/all values on this Service are hard-coded, and it generally seems geared toward using it via `linkerd dashboard`. I would like to expose the linkerd dashboard via a custom internal dashboard, which is configured via Service annotations.

### How should the problem be solved?

There should be an additional helm chart value added for custom annotations for the "web" Service.

### Any alternatives you've considered?

I can create an additional Service "manually", but I'd rather not managing anything outside of the helm chart.

### How would users interact with this feature?

Add additional helm values.

**Comment by cpretzer** [comment]
Hi @agaffney have you considered using `kustomize` to add the annotations using a patch?

The [docs](https://linkerd.io/2/tasks/customize-install/) describe how to use `kustomize` with the linkerd charts, and you should be able to do the same with the linkerd-viz charts, as well

**Comment by agaffney** [comment]
I'm deploying the helm chart via Terraform, which does not make it straightforward to apply chart customizations via kustomize, AFAIK. I really don't want to have to add yet another tool to my stack, anyway.

**Comment by adleong** [comment]
@agaffney another possibility would be for you to simply create another Kubernetes service which resolves to the Linkerd dashboard.  This gives you full control over the annotations on that service and you can manage it using whatever tooling you're already using.

**Comment by agaffney** [comment]
That is an option, but I would like to avoid managing extra resources like this outside of the helm chart, because it means I have to manage additional one-off k8s resources with TF. It also complicates things in our use case where I need to deploy a set of helm charts with both TF and a custom orchestration tool for the purpose of local deployments.

The need to customize Service resources is a pretty standard use case in many community helm charts, and it shouldn't take much to support it here. Of course, supporting customizing this particular thing opens up the possibility of doing similar customizations to other resources in the chart.

**Comment by adleong** [comment]
I see where you're coming from and there certainly is precedent in community charts to support this kind of thing.  But I think you hit the nail on the head when you say that this opens the possibility of doing this for each of the (many) resources in the Linkerd charts.  Rather than make the Linkerd chart super configurable, I'd much rather keep it simple and focused.  This keeps the Linkerd configuration surface area smaller while still allowing you to build and manage your own resources however you want (even if this does require pulling in some extra tooling).
