### ISSUE TITLE
`check` should imply --proxy on the relevant namespace

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#5623]
The control plane can't be considered healthy if its proxies are not healthy.  `linkerd check` should check the state of all proxies in the core control plane (e.g. `linkerd check --proxy -n linkerd`). 

Similarly, extension checks should validate the state of the proxies in the extension namespaces.

**Comment by Pothulapati** [comment]
To Confirm, `linkerd check` should also check for control-plane proxies health, without having to specifically do `linkerd check --proxy -n linkerd` (which seems to work currently) ?

**Comment by olix0r** [comment]
@Pothulapati correct; and, similarly `linkerd viz check` should imply `linkerd check --proxy -n linkerd-viz`

This raises an interesting question, though... What does `linkerd check --proxy myns` do with regard to extensions?  Presumably we'll need to support `linkerd viz check --proxy myns`; but that's not the behavior i'm really talking about in this issue.

To summarize:

* Checking the control plane or an extension should always ensure the namespace's proxies are healthy.
* Additionally, each extension's checks will need to support proxy checks (separate issue)

**Comment by Pothulapati** [comment]
> What does linkerd check --proxy myns do with regard to extensions

It does not do anything extra for extensions. It performs the same proxy check when a extension namespace is passed.

>Presumably we'll need to support linkerd viz check --proxy myns; but that's not the behavior i'm really talking about in this issue.

#5602 added `linkerd viz check --proxy` which checks for the tap injection in the proxies and a data-plane Prometheus metrics check.

**Comment by Pothulapati** [comment]
Update, I don't think this is even required with `linkerd check` as we already have `control plane pods are ready` which checks for all the control-plane containers status. https://github.com/linkerd/linkerd2/blob/main/pkg/healthcheck/healthcheck.go#L2420

But currently, This is not under `linkerd-existence` healthcheck Cateogry. So, Hence not ran with all extension checks. Should we move this into that and remove linkerd-api` category?

Also, Is container readiness the same as `healthy` or are we looking for something else?

**Comment by olix0r** [comment]
I don't think these things are equivalent.  `linkerd check --proxy -n linkerd` checks a variety of things -- like the state of the proxy's identity -- that are not checked by 'control plane pods are ready'.

I don't think this is something that is part of "linkerd existence" -- this is about runtime health, not whether linkerd has been installed.

My point is that:
* `linkerd check` should flag any potential configuration issues with the proxy containers in the core control plane
* `linkerd viz check` should flag any potential configuration issues with the proxy containers in the `linkerd-viz` namespace
* etc...

This is more than just the `ready` state. We should actually do data plane checks.

**Comment by Pothulapati** [comment]
That makes sense. Will raise a PR addressing this.

**Comment by olix0r** [comment]
Per discussion: this ends up being a bit more complex than we expected; so taking this out of stable-2.10 so we have more time to think through a proper implementation.
