### ISSUE TITLE
Outbound traffic stopped for the whole cluster when starting 200+ pods

### ISSUE THREAD

**Issue by kforsthoevel** [linkerd/linkerd2#5629]
## Bug Report

We started 200+ pods in a very short time frame (~1min). Outbound traffic stopped for the whole cluster with a lot of fail-fast error messages (`linkerd2_app_core::errors: Failed to proxy request: Service in fail-fast`). During debugging we found a lot of errors in the `destination` log:

```
level=error msg="Failed to get node topology for node ip-172-X-X-X.eu-west-1.compute.internal: context canceled" addr=":8086" component=endpoint-translator remote="127.0.0.1:47822" service="my-service.default.svc.cluster.local:80"
```

and

```
level=error msg="Failed to send address update: rpc error: code = Internal desc = transport: transport: the stream is done or WriteHeader was already called" addr=":8086" component=endpoint-translator remote="127.0.0.1:47822" service="my-servicedefault.svc.cluster.local:80"
```

<img width="997" alt="Screenshot 2021-01-21 at 19 01 52" src="https://user-images.githubusercontent.com/2952012/105392169-3354cd00-5c1b-11eb-9df8-c87c7fa44f46.png">

Each of the 200+ pods make TCP requests against 6 dependent services during startup.

Here are the memory and CPU stats for the `destination` pods during the outage.

<img width="1170" alt="Screenshot 2021-01-21 at 18 57 28" src="https://user-images.githubusercontent.com/2952012/105391605-8f6b2180-5c1a-11eb-9c8c-8b18a7d6cc92.png">

After about 5 minutes everything was fine again and the outbound traffic was ok. 

Let me know if you need further info.

#### `linkerd check` output

```text
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-identity
----------------
√ certificate config is valid
√ trust anchors are using supported crypto algorithm
√ trust anchors are within their validity period
√ trust anchors are valid for at least 60 days
√ issuer cert is using supported crypto algorithm
√ issuer cert is within its validity period
√ issuer cert is valid for at least 60 days
√ issuer cert is issued by the trust anchor

linkerd-webhooks-and-apisvc-tls
-------------------------------
√ tap API server has valid cert
√ tap API server cert is valid for at least 60 days
√ proxy-injector webhook has valid cert
√ proxy-injector cert is valid for at least 60 days
√ sp-validator webhook has valid cert
√ sp-validator cert is valid for at least 60 days

linkerd-api
-----------
√ control plane pods are ready
√ control plane self-check
√ [kubernetes] control plane can talk to Kubernetes
√ [prometheus] control plane can talk to Prometheus
√ tap api service is running

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ control plane is up-to-date
√ control plane and cli versions match

linkerd-ha-checks
-----------------
√ pod injection disabled on kube-system
√ multiple replicas of control plane pods

linkerd-prometheus
------------------
√ prometheus add-on service account exists
√ prometheus add-on config map exists
√ prometheus pod is running

linkerd-grafana
---------------
√ grafana add-on service account exists
√ grafana add-on config map exists
√ grafana pod is running

Status check results are √

```

### Environment

- Kubernetes Version: 1.18.15
- Cluster Environment: (kops
- Host OS: Ubuntu 20.04 LTS
- Linkerd version: Client version: stable-2.9.2, Server version: stable-2.9.2

### Additional context

See #5405

**Comment by kforsthoevel** [comment]
There are four types of log messages from `linkerd-proxy` for the destination during the outage. But only 139 log lines.

a)

```json
{
  "timestamp": "[242094.812456s]",
  "level": "INFO",
  "fields": {
    "message": "Connection closed",
    "error": "connection error: Transport endpoint is not connected (os error 107)"
  },
  "target": "linkerd2_app_core::serve",
  "span": {
    "peer.addr": "100.96.255.12:50692",
    "target.addr": "100.96.16.137:8086",
    "name": "accept"
  },
  "spans": [
    {
      "name": "inbound"
    },
    {
      "peer.addr": "100.96.255.12:50692",
      "target.addr": "100.96.16.137:8086",
      "name": "accept"
    }
  ],
  "threadId": "ThreadId(1)"
}
```

b)

```json
{
  "timestamp": "[242026.532422s]",
  "level": "INFO",
  "fields": {
    "message": "Connection closed",
    "error": "Timed out while reading client stream prefix"
  },
  "target": "linkerd2_app_core::serve",
  "span": {
    "peer.addr": "100.97.24.9:47186",
    "target.addr": "100.96.8.38:8086",
    "name": "accept"
  },
  "spans": [
    {
      "name": "inbound"
    },
    {
      "peer.addr": "100.97.24.9:47186",
      "target.addr": "100.96.8.38:8086",
      "name": "accept"
    }
  ],
  "threadId": "ThreadId(1)"
}
```

c)

```json
{
  "timestamp": "[242007.664132s]",
  "level": "INFO",
  "fields": {
    "message": "Connection closed",
    "error": "TLS detection timeout"
  },
  "target": "linkerd2_app_core::serve",
  "span": {
    "peer.addr": "100.96.239.9:46686",
    "target.addr": "100.96.8.38:8086",
    "name": "accept"
  },
  "spans": [
    {
      "name": "inbound"
    },
    {
      "peer.addr": "100.96.239.9:46686",
      "target.addr": "100.96.8.38:8086",
      "name": "accept"
    }
  ],
  "threadId": "ThreadId(1)"
}
```

d)

```json
{
  "timestamp": "[241404.015655s]",
  "level": "INFO",
  "fields": {
    "message": "Connection closed",
    "error": "connection error: Broken pipe (os error 32)"
  },
  "target": "linkerd2_app_core::serve",
  "span": {
    "peer.addr": "100.96.8.119:58412",
    "target.addr": "100.96.8.38:4191",
    "name": "accept"
  },
  "spans": [
    {
      "name": "daemon"
    },
    {
      "listen.addr": "0.0.0.0:4191",
      "name": "admin"
    },
    {
      "peer.addr": "100.96.8.119:58412",
      "target.addr": "100.96.8.38:4191",
      "name": "accept"
    }
  ],
  "threadId": "ThreadId(2)"
}
```

Let me know if you need further info.

**Comment by adleong** [comment]
Thanks @kforsthoevel.  To me, all of those destination error messages in both the destination container and its sidecar proxy could be explained by the client (i.e. the data plane proxies) cancelling requests.  So the destination service isn't the first place I'd want to look at to diagnose this.

Instead, I'd like to understand exactly why the outbound proxies are putting services in fail-fast.  @olix0r are there specific proxy versions or log settings to get better diagnostics on this?

**Comment by adleong** [comment]
@kforsthoevel what would be super helpful is if you could share more complete proxy logs which contain the fail-fast error itself.  Especially if you can increase the proxy-log-level to `linkerd=debug` and/or if you can upgrade to a recent edge release which has improved the logging for errors like this.

**Comment by kforsthoevel** [comment]
@adleong Every time we scaled one deployment to 200+ pods, the whole traffic within the cluster stops for a couple of minutes. None of our 200 deployments, in multiple namespaces, have been able to connect to any service. It's practically the same as scaling the destination deployment to 0. No more traffic within the cluster.

Why does the scaling of one deployment affects the traffic for all other deployments? 

BTW, we have excluded all deployments with an HPA from the service mesh in order to keep our cluster running.

**Comment by adleong** [comment]
@kforsthoevel scaling one deployment certainly should not affect traffic from other deployments.  we're actively looking into this as well as some other, potentially related issues.

The traffic patterns between the proxy and the destination controller have changed recently, which may help here.  Are you able to test a recent edge release and see if you encounter this issue?

**Comment by kleimkuhler** [comment]
I'd be interested to see if this problem persists when #5722 merges.

**Comment by kforsthoevel** [comment]
Looks like this could solve our problem as well. I will wait till the next edge release.

**Comment by kleimkuhler** [comment]
This did not make it in to `edge-21.2.2` but should be in `edge-21.2.3`.

**Comment by adleong** [comment]
edge-21.2.3 has been released!  @kforsthoevel looking forward to hearing if this resolves the problem for you.

**Comment by kforsthoevel** [comment]
@adleong We have switched to edge-21.2.3 and the first tests look promising, but I would like to do further testing next week before I will closed this.

**Comment by kleimkuhler** [comment]
Good to hear @kforsthoevel thanks for the update!

**Comment by adleong** [comment]
@kforsthoevel just checking in here to see if you've had a chance to do that additional testing yet?

**Comment by kforsthoevel** [comment]
@adleong Sorry for the late response. Everything looks fine now. Thanks for fixing this so quickly.
