### ISSUE TITLE
Upgrade to Go 1.16

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#5630]
Go 1.16 is expected to be released in Feburary 2021. Following this, I propose that we upgrade the Linkerd2 repo to use Go 1.16 (skipping 1.15).

https://tip.golang.org/doc/go1.16

**Comment by Pothulapati** [comment]
Regarding this, Go 1.16 has new embed functionality used to store and retrieve static files. Currently we use https://github.com/shurcooL/vfsgen to store and retrieve the Linkerd chart template files in the binary. We should probably switch over if there is not much obstacle/complexity.

**Comment by dadjeibaah** [comment]
Fixed by PR#5890
