### ISSUE TITLE
jaeger: Is a jaeger-enabled annotation useful?

### ISSUE THREAD

**Issue by kleimkuhler** [linkerd/linkerd2#5632]
Is it valuable to add a `jaeger-enabled` annotation for the Jaeger extension,
similar to the `tap-enabled` annotation for the Viz extension?

#5608 adds the `tap-enabled` annotation primarily so that when the tap server is
tapping a pod, it can look for this annotation and decide whether to tap or
return an error. A side effect of this is that `viz check` can look for this
annotation on pods and commmunicate to a user if the `tap-enabled` annotation is
not on a pod, then the pod cannot be tapped.

An equivalent `jaeger-enabled` annotation could prove useful for the `jaeger
check` command. If a pod does not have this annotation, then the Jaeger
extension's `jaeger-injector` has not injected the pod and we can communicate to
a user that tracing will not work for that workload.

Since right now this would only be used for `jaeger check`, it's not as
important as `tap-enabled` annotation, but it may be worth considering and I'm
interested in any further input.

**Comment by adleong** [comment]
I agree with your assessment: it could be helpful for `jaeger check`.
