### ISSUE TITLE
Multicluster linkerd changes URI to absolute form (linkerd version 2.8.1)

### ISSUE THREAD

**Issue by gitravin** [linkerd/linkerd2#5641]
I have used k3d to setup east, west clusters as described here https://linkerd.io/2/tasks/multicluster/ . Installed using linkerd cli - 2.8.1- stable, kubernetes version 1.16.15

Once the clusters are setup and west cluster starts watching the east cluster, I deployed the app with service mirroring of podinfo service, so I see the service mirrored to the west cluster as 'podinfo-east'. If I do a curl for http://podinfo:9898/ from 'frontend' pod of east cluster, the response is served from the podinfo of the same cluster and I see that the request has no scheme in the request URI (it stays in the relative format) when it reaches the 'podinfo' pod. If I do a curl for http://podinfo-east:9898/ from 'frontend' pod of west cluster, the response is served from podinfo of east cluster (as expected) but this time the request has scheme in the request URI when it reaches the 'podinfo' pod. The request is transformed to absolute format by the linkerd-proxy. I tracked it and it looks like this transformation happens at the linkerd-proxy attached to frontend pod in west cluster.

**Comment by olix0r** [comment]
I think this has always been the case with multicluster... I agree we should stop transforming URLs as part of stable-2.10

**Comment by olix0r** [comment]
Looking into this, it looks like we've already fixed this since 2.8.1. I haven't yet tested this end-to-end, but I'd suggest testing today's edge release, which is nearly feature-complete for stable-2.10 -- so let us know if you see anything awry!

**Comment by olix0r** [comment]
As I mentioned, we believe we've fixed this for the upcoming stable release. I'm closing this issue for now but please let us know if you see anything unexpected on the recent edge releases.
