### ISSUE TITLE
cli: Handle disabled prometheus and grafana use-case.

### ISSUE THREAD

**Issue by Pothulapati** [linkerd/linkerd2#5652]
## Feature Request

Currently, Prometheus and Grafana are optional, but there are some of these rough
edges that need to be handled.
- Make prometheus and Grafana checks more dynamic i.e run them
only when they are enabled.
- Fail `viz install` when `prometheus.enabled=false` and `prometheusUrl=""`
- Use an `ExternalName` service for Prometheus for things like Grafana to use this pointer whose value will be set on the configuration i.e default or external.

**Comment by kleimkuhler** [comment]
So we had some discussion off GitHub where we discussed possibly removing the `prometheus.enabled` configuration. We would only allow specifying the Prometheus URL—meaning it's the default or an external one.

If that's the case, we may not need to handle either of these cases? I assume if we disallow disabling Prometheus, we'd do the same for Grafana.
