### ISSUE TITLE
cli: Remove the --disable-tap flag from inject

### ISSUE THREAD

**Issue by kleimkuhler** [linkerd/linkerd2#5664]
The `inject` command still supports the `--disable-tap` flag which has moved to
the Viz extension. This flag and all remaining mentions of the tap in the core
installation should be removed.

Tap is disabled with the `config.linkerd.io/disable-tap` annotation. This is a
good time to rename this to `viz.linkerd.io/disable-tap` as the naming better
reflects this belongs to the Viz extension.

If users wish to disable tap on workload after the Viz extension has been
installed, they should be annotating resources with the
`viz.linkerd.io/disable-tap` annotation. There will be no `--disable-flag`
equivalent.

**Comment by mayankshah1607** [comment]
Hi! I'd love to work on this issue :)
