### ISSUE TITLE
YAML anchors don't work as expected when overriding flags

### ISSUE THREAD

**Issue by alpeb** [linkerd/linkerd2#5685]
### What is the issue?

We make use of a few YAML anchors in the Helm templates to avoid repetition. It turns out that only works as long as anchors refer to variables in the same document. If one sets a value (via Helm or the CLI) in a document using `-f` or through `--set`, and if that value is referred as an anchor in the main `values.yaml` file, the overridden value will be ignored.

### How can it be reproduced?

```bash
$ linkerd viz install --set defaultLogLevel=debug | ag log-level
        - -log-level=info
        - -log-level=info
        - -log-level=info

$ helm template --set defaultLogLevel=debug linkerd-edge/linkerd-viz | ag log-level
        - -log-level=info
        - -log-level=info
        - -log-level=info
```

### Environment

- Kubernetes Version: 1.19
- Cluster Environment: (GKE, AKS, kops, ...): k3d
- Host OS: Linux
- Linkerd version: edge-21.2.1

### Possible solution

Stop using anchors completely, and instead rely on the `default` function directly in the template files. Instead of using anchors for a value that we wish to reuse, we set leave it to an empty value in `values.yaml`, and then in the template file use the default value (like `defaultLogLevel`) only if the target value hasn't been overridden.

### Additional context

This is the upstream issue describing the problem: helm/helm#2336

**Comment by Pothulapati** [comment]
Working on this.
