### ISSUE TITLE
FTP connections fail

### ISSUE THREAD

**Issue by DGollings** [linkerd/linkerd2#5689]
### What is the issue?
Considering nobody else seems to ever have reported anything FTP related, I guess there's little overlap between users of service meshes and users of ftp servers. :)
Unfortunately I don't have a choice in the matter, need to retrieve some data.
To be clear: FTP, not SFTP
FTP doesn't work without 'disabling' linkerd (`config.linkerd.io/skip-outbound-ports`)

### How can it be reproduced?
Docker image `fauria/vsftpd` is easy enough. Just start it using `--net=host` so you dont need to worry about PASV ports
Then try connecting to it, cli ftp or lftp works
login wont work until you ignore port 20/21, ls wont work until you ignore the port range
edit: on a GKE cluster, microk8s works fine

### Logs, error output, etc
Where could I find relevant logs? Linkerd init/sidecar isn't all that interesting

#### `linkerd check` output
all green

### Environment

- Kubernetes Version:
- Cluster Environment: GKE
- Host OS: Containerd
- Linkerd version: 2.9.2

### Possible solution
Would be nice if the PASV response is parsed and just that port is ignored for the duration of a session instead of having to ignore entire port ranges
Current solution: 
`config.linkerd.io/skip-outbound-ports: "20,21, 41000-4200"
(control port, ftp port and PASV port range, I think)

**Comment by DGollings** [comment]
IIRC: this did work on a Digital Ocean kubernetes cluster, but not GKE.
But that's a different K8s version (1.16 -> 1.17), different Linkerd version (2.6.1 -> 2.9.2) and of course different VM/network

They did both however have 'open outbound' firewalls

**Comment by adleong** [comment]
Hi @DGollings! In passive mode, FTP is essentially a server-speaks-first protocol on the PASV port.  What I would expect to happen is that the client should attempt to connect on the PASV port, the Linkerd proxy should time-out protocol detection (because the client is not sending data), and then should fall back to treating the connection as TCP.  

If you can include proxy logs with the proxy-log-level set to `linkerd=debug` then we can hopefully see the details of what is happening with protocol detection.

I'll also note that recent edge releases include an "opaque ports" feature which allows you to mark certain ports as opaque which will prevent Linkerd from attempting protocol detection on them.  That's probably what you would want to do for FTP, though you'll still have to mark the entire PASV port range as opaque.

**Comment by olix0r** [comment]
Echoing @adleong, I'd expect this to work on recent edge releases, which feature an `opaque-ports` annotation as well as relaxed protocol detection semantics. It would be helpful to confirm that, though.

**Comment by DGollings** [comment]
its not mission critical, but still production (where I have this issue). How stable is the edge release and is it easy to rollback? I'd be willing to beta test :)

**Comment by adleong** [comment]
Rolling back from edge releases is not something that's very well exercised or tested, I'd recommend trying out the edge in a staging or dev environment if possible.

**Comment by DGollings** [comment]
shame, was looking forward to trying out the opaque ports :)

Anyway, I'll try and gather some logs instead. At least in order to figure out why it doesn't work

**Comment by DGollings** [comment]
Sorry, was distracted for a bit, here's some log output:

```
[   132.025829s] DEBUG ThreadId(01) outbound: linkerd2_cache: Caching new service
[   132.025879s] DEBUG ThreadId(01) outbound: linkerd2_cache: services=1 dropped=2
[   132.025913s] DEBUG ThreadId(01) outbound: linkerd2_service_profiles::default: Handling rejected discovery
[   132.025941s] DEBUG ThreadId(01) outbound: linkerd2_proxy_transport::prefix: Buffering prefix capacity=8192
[   135.027824s]  INFO ThreadId(01) outbound:accept{peer.addr=10.104.3.116:47758 target.addr=194.229.60.191:21}: linkerd2_app_core::serve: Connection closed error=Timed out while reading client stream prefix
[   137.573160s] DEBUG ThreadId(02) daemon:admin{listen.addr=0.0.0.0:4191}:accept{peer.addr=10.104.3.1:38304 target.addr=10.104.3.116:4191}: linkerd2_proxy_transport::tls::accept: Peeked bytes from TCP stream sz=120
```
(trimmed similar lines)
lftp reconnect

```
[   162.027504s] DEBUG ThreadId(01) outbound: linkerd2_cache: Caching new service
[   162.028164s] DEBUG ThreadId(01) outbound: linkerd2_cache: services=1 dropped=0
[   162.028621s] DEBUG ThreadId(01) outbound: linkerd2_service_profiles::default: Handling rejected discovery
[   162.029080s] DEBUG ThreadId(01) outbound: linkerd2_proxy_transport::prefix: Buffering prefix capacity=8192
[   165.033430s]  INFO ThreadId(01) outbound:accept{peer.addr=10.104.3.116:48192 target.addr=194.229.60.191:21}: linkerd2_app_core::serve: Connection closed error=Timed out while reading client stream prefix
[   167.575880s] DEBUG ThreadId(02) daemon:admin{listen.addr=0.0.0.0:4191}:accept{peer.addr=10.104.3.1:38780 target.addr=10.104.3.116:4191}: linkerd2_proxy_transport::tls::accept: Peeked bytes from TCP stream sz=120
```
(trimmed)
another reconnect
```
[   207.031176s] DEBUG ThreadId(01) outbound: linkerd2_cache: Caching new service
[   207.032518s] DEBUG ThreadId(01) outbound: linkerd2_cache: services=1 dropped=0
[   207.033373s] DEBUG ThreadId(01) outbound: linkerd2_service_profiles::default: Handling rejected discovery
[   207.034070s] DEBUG ThreadId(01) outbound: linkerd2_proxy_transport::prefix: Buffering prefix capacity=8192
[   207.573912s] DEBUG ThreadId(02) daemon:admin{listen.addr=0.0.0.0:4191}:accept{peer.addr=10.104.3.1:39336 target.addr=10.104.3.116:4191}: linkerd2_proxy_transport::tls::accept: Peeked bytes from TCP stream sz=120
[   207.574420s] DEBUG ThreadId(02) daemon:admin{listen.addr=0.0.0.0:4191}:accept{peer.addr=10.104.3.1:39336 target.addr=10.104.3.116:4191}: linkerd2_app_core::serve: Connection closed
[   207.815883s] DEBUG ThreadId(02) daemon:admin{listen.addr=0.0.0.0:4191}:accept{peer.addr=10.104.3.1:39338 target.addr=10.104.3.116:4191}: linkerd2_proxy_transport::tls::accept: Peeked bytes from TCP stream sz=119
[   207.816489s] DEBUG ThreadId(02) daemon:admin{listen.addr=0.0.0.0:4191}:accept{peer.addr=10.104.3.1:39338 target.addr=10.104.3.116:4191}: linkerd2_app_core::serve: Connection closed
[   210.035820s]  INFO ThreadId(01) outbound:accept{peer.addr=10.104.3.116:48862 target.addr=194.229.60.191:21}: linkerd2_app_core::serve: Connection closed error=Timed out while reading client stream prefix
```

**Comment by adleong** [comment]
Thanks @DGollings!  @olix0r do these logs shed any light on why protocol detection isn't timing out and falling back to TCP for FTP on 2.9.2?  Are there other logs we can ask for that would be more helpful?

**Comment by olix0r** [comment]
@adleong Unfortunately protocol detection timeouts don't fall back to TCP on 2.9. I would, however, expect this to work (with some added connect latency) on recent edge releases.

@DGollings You don't actually have to upgrade the whole control plane to test a recent proxy on your workload. You should be able to set the pod spec annotation `config.linkerd.io/proxy-version: edge-21.2.2` to validate that we permit these connections to succeed after the detection timeout. This won't support the full array of opaque-ports functionality, but I would expect it to fix this specific issue.

**Comment by DGollings** [comment]
Edge works :)

```
   165.922379s] DEBUG ThreadId(01) outbound: linkerd_cache: Caching new service target=Accept { orig_dst: 194.229.60.191:21, protocol: () }
[   165.922483s] DEBUG ThreadId(01) outbound: linkerd_service_profiles::default: Handling rejected discovery
[   175.923369s] DEBUG ThreadId(01) outbound:accept{peer.addr=10.104.3.197:40412 target.addr=194.229.60.191:21}: linkerd_detect: Detection timed out timeout=10s
[   175.923684s] DEBUG ThreadId(01) outbound:accept{peer.addr=10.104.3.197:40412 target.addr=194.229.60.191:21}:tcp:tcp.forward{server.addr=194.229.60.191:21}: linkerd_tls::client: Peer does not support TLS reason=not_provided_by_service_discovery
[   175.923736s] DEBUG ThreadId(01) outbound:accept{peer.addr=10.104.3.197:40412 target.addr=194.229.60.191:21}:tcp:tcp.forward{server.addr=194.229.60.191:21}: linkerd_proxy_transport::connect: Connecting server.addr=194.229.60.191:21
[   175.937901s] DEBUG ThreadId(01) outbound:accept{peer.addr=10.104.3.197:40412 target.addr=194.229.60.191:21}:tcp:tcp.forward{server.addr=194.229.60.191:21}: linkerd_proxy_transport::connect: Connected local.addr=10.104.3.197:40550 keepalive=Some(10s)
[   175.937946s] DEBUG ThreadId(01) outbound:accept{peer.addr=10.104.3.197:40412 target.addr=194.229.60.191:21}:tcp:tcp.forward{server.addr=194.229.60.191:21}: linkerd_proxy_transport::metrics: client connection open
[   176.202413s] DEBUG ThreadId(01) outbound: linkerd_cache: Caching new service target=Accept { orig_dst: 194.229.60.191:41237, protocol: () }
[   176.202589s] DEBUG ThreadId(01) outbound: linkerd_service_profiles::default: Handling rejected discovery
[   181.202632s] DEBUG ThreadId(01) outbound:accept{peer.addr=10.104.3.197:47995 target.addr=194.229.60.191:41237}: linkerd_detect: Detected protocol=None elapsed=4.999982632s
[   181.203243s] DEBUG ThreadId(01) outbound:accept{peer.addr=10.104.3.197:47995 target.addr=194.229.60.191:41237}:tcp:tcp.forward{server.addr=194.229.60.191:41237}: linkerd_tls::client: Peer does not support TLS reason=not_provided_by_service_discovery
[   181.203301s] DEBUG ThreadId(01) outbound:accept{peer.addr=10.104.3.197:47995 target.addr=194.229.60.191:41237}:tcp:tcp.forward{server.addr=194.229.60.191:41237}: linkerd_proxy_transport::connect: Connecting server.addr=194.229.60.191:41237
[   181.216943s] DEBUG ThreadId(01) outbound:accept{peer.addr=10.104.3.197:47995 target.addr=194.229.60.191:41237}:tcp:tcp.forward{server.addr=194.229.60.191:41237}: linkerd_proxy_transport::connect: Connected local.addr=10.104.3.197:39430 keepalive=Some(10s)
[   181.217003s] DEBUG ThreadId(01) outbound:accept{peer.addr=10.104.3.197:47995 target.addr=194.229.60.191:41237}:tcp:tcp.forward{server.addr=194.229.60.191:41237}: linkerd_proxy_transport::metrics: client connection open
[   181.255426s] DEBUG ThreadId(01) outbound:accept{peer.addr=10.104.3.197:47995 target.addr=194.229.60.191:41237}: linkerd_app_core::serve: Connection closed
[   181.255496s] DEBUG ThreadId(01) evict{target=Accept { orig_dst: 194.229.60.191:41237, protocol: () }}: linkerd_cache: Awaiting idleness
[   186.256874s] DEBUG ThreadId(01) evict{target=Accept { orig_dst: 194.229.60.191:41237, protocol: () }}: linkerd_cache: Cache entry dropped
```

So would you say a 2.9.3 hotfix is in the pipeline? Or am I better off waiting for edge to be released to stable?

**Comment by olix0r** [comment]
@DGollings 2.9.3 already went out but it didn't include this change (because it's tied up in larger changes). We're expecting stable-2.10 to be released within the next ~2 weeks, with today's edge release being the first release candidate.

**Comment by DGollings** [comment]
Thanks

Not in that big a rush, workaround is fine for now. I have added a release watch. Shall I close this issue or do you want to use it to track status?

**Comment by olix0r** [comment]
@DGollings I'll close this for now. Let us know if you see anything unexpected, though!
