### ISSUE TITLE
linkerd edge-21.2.1 uninstall broken  

### ISSUE THREAD

**Issue by barkardk** [linkerd/linkerd2#5701]
### What is the issue?
linkerd requires the linkerd and linkerd-viz components to be uninjected before linkerd can be uninstalled

### Logs, error output, etc

```bash
linkerd uninstall |kubectl delete -f -
Please uninject the following pods before uninstalling the control-plane:
	* linkerd-grafana-b7f9bcf6b-md77l
	* linkerd-metrics-api-56b7bd57cf-dmtkn
	* linkerd-prometheus-764d54c5f7-wpnmh
	* linkerd-tap-c655d6d4b-d9p7p
	* linkerd-web-fbb6b6984-898q7
	* tap-injector-5dd7979f75-rk9sh
```
once that is uninjected continued to run the uninstall and ended up with 
```bash
```yaml
 - lastTransitionTime: "2021-02-09T15:49:21Z"
    message: 'Discovery failed for some groups, 1 failing: unable to retrieve the
      complete list of server APIs: tap.linkerd.io/v1alpha1: the server is currently
      unable to handle the request'
    reason: DiscoveryFailed
    status: "True"
    type: NamespaceDeletionDiscoveryFailure
```

TO get rid of the linkerd namespace did the following

```bash
kubectl get ns linkerd -o json  > linkerd.json
// edit out the kubernetes finalizer
kubectl replace --raw "/api/v1/namespaces/linkerd/finalize" -f ./t
```
And then linkerd-viz namespace is still left untouched and has to be manually undeleted in the same way via finalizer override

- Kubernetes Version:
-1.15
- Cluster Environment: (GKE, AKS, kops, ...)
-gke

- Linkerd version:
edge-21.2.1
### Possible solution
linkerd should just delete its own control plane if the uninstall command is run without extra steps

**Comment by kleimkuhler** [comment]
Hi @barkardk I've been unable to reproduce this issue. I did the following:

```
# version check
❯ linkerd version
Client version: edge-21.2.1
Server version: edge-21.2.1

# fails as expected
❯ linkerd uninstall |kubectl delete -f -
Please uninject the following pods before uninstalling the control-plane:
        * linkerd-tap-55b5646fdd-dzwl2
        * linkerd-metrics-api-6c4574b5d9-9tzxh
        * linkerd-web-6d5d75554b-dhx7b
        * linkerd-grafana-c69c8f5cd-tlz9v
        * tap-injector-66dbdf78df-q5kfx
        * linkerd-prometheus-86c4746c46-xd6df
No resources found

# uninstall the viz extension
❯ linkerd viz uninstall |kubectl delete -f -
clusterrole.rbac.authorization.k8s.io "linkerd-linkerd-viz-metrics-api" deleted
...
namespace "linkerd-viz" deleted

# uninstall Linkerd
❯ linkerd uninstall |kubectl delete -f -
clusterrole.rbac.authorization.k8s.io "linkerd-linkerd-identity" deleted
...
namespace "linkerd" deleted
```

Did you do anything differently for uninstalling?

**Comment by barkardk** [comment]
No not at all. 
This was not a fresh cluster though. I had the  linkerd edge 21.1.3 installed on that cluster .  
I first unininstalled that version using linkerd uninstall, and uninstall viz. Verified that the namespaces were gone and no meshed components in any weird states. 

 Then I installed the latest linkerd edge. Ran a few tests and was then going to uninstall it.
Thats when I ran into this issue.

**Comment by adleong** [comment]
You're right that the output is a bit misleading in that it suggests you should uninject the linkerd-viz namespace.  What you should actually do is uninstall the linkerd-viz extension as @kleimkuhler describes above.  Using the `linkerd viz uninstall` command will ensure that all of the appropriate resources get cleaned up, including cluster scoped resources like the apiservice.

I think the right fix here is to update the error message from `linkerd uninstall` to detect any installed extensions and to specifically say that they need to be uninstalled (rather than uninjected).

**Comment by kleimkuhler** [comment]
@barkardk Would the solution to #5712 been more helpful here, or is there still an issue with the actual `uninstall` commands of both `linkerd` and `linkerd viz` that you are experiencing?

**Comment by olix0r** [comment]
We improved the output in https://github.com/linkerd/linkerd2/pull/5723. Please let us know if there are other changes you think we should make!
