### ISSUE TITLE
Set the opaque-port config setting via cmd

### ISSUE THREAD

**Issue by barkardk** [linkerd/linkerd2#5703]
### What problem are you trying to solve?
When injecting linkerd into manifests that use the SSF protocol it would be nice to be able to do so via am cli flag 
just like 
```bash
linkerd inject --skip-inbound-ports=3306 --skip-outbound-ports=3306 -
```

for this setting

### Any alternatives you've considered?

Via pipelines the linkerd properties would be set in the manifests already so this is not crucial  feature
You can always edit the manifest manually also after linkerd inkect and add this 
```yaml
annotations:
  config.linkerd.io/opaque-ports: 3306
```
### How would users interact with this feature?

it would be great to be able to run something similar to  
```bash
linkerd- inject --opaque-ports=3306  -
```

**Comment by adleong** [comment]
This is a great idea!

**Comment by Pothulapati** [comment]
Done via https://github.com/linkerd/linkerd2/pull/5851
