### ISSUE TITLE
linkerd Proxy closing the outbound Connection.

### ISSUE THREAD

**Issue by Neru007** [linkerd/linkerd2#5715]
### What is the issue?
linkerd Proxy closing the outbound connection from one of my service to another service . Few of initial attempts get successful but connection get closed after a while
### How can it be reproduced?
Using Streams of Multiple Calls
### Logs, error output, etc

(If the output is long, please create a [gist](https://gist.github.com/) and
paste the link here
https://gist.github.com/Neru007/31301f1688742bced9ba3b38a43fe711#file-gistfile1-txt.)

#### `linkerd check` output

```text
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-identity
----------------
√ certificate config is valid
√ trust anchors are using supported crypto algorithm
√ trust anchors are within their validity period
√ trust anchors are valid for at least 60 days
√ issuer cert is using supported crypto algorithm
√ issuer cert is within its validity period
√ issuer cert is valid for at least 60 days
√ issuer cert is issued by the trust anchor

linkerd-webhooks-and-apisvc-tls
-------------------------------
√ tap API server has valid cert
√ tap API server cert is valid for at least 60 days
√ proxy-injector webhook has valid cert
√ proxy-injector cert is valid for at least 60 days
√ sp-validator webhook has valid cert
√ sp-validator cert is valid for at least 60 days

linkerd-api
-----------
√ control plane pods are ready
√ control plane self-check
√ [kubernetes] control plane can talk to Kubernetes
√ [prometheus] control plane can talk to Prometheus
√ tap api service is running

linkerd-version
---------------
‼ can determine the latest version
    Get "https://versioncheck.linkerd.io/version.json?version=stable-2.9.2&uuid=e56b00b6-c852-4db6-94ba-c4374e4f010d&source=cli": dial tcp 104.21.70.131:443: connect: connection refused
    see https://linkerd.io/checks/#l5d-version-latest for hints
‼ cli is up-to-date
    unsupported version channel: stable-2.9.2
    see https://linkerd.io/checks/#l5d-version-cli for hints

control-plane-version
---------------------
‼ control plane is up-to-date
    unsupported version channel: stable-2.9.2
    see https://linkerd.io/checks/#l5d-version-control for hints
√ control plane and cli versions match

linkerd-prometheus
------------------
√ prometheus add-on service account exists
√ prometheus add-on config map exists
√ prometheus pod is running

linkerd-grafana
---------------
√ grafana add-on service account exists
√ grafana add-on config map exists
√ grafana pod is running

Status check results are √
```

### Environment

- Kubernetes Version: 1.18.14
- Cluster Environment: AKS
- Host OS: Ubuntu 18.04
- Linkerd version: 2.9.2

### Additional context
Attached Ksniff Packet Dump
[ksniff.zip](https://github.com/linkerd/linkerd2/files/5961318/ksniff.zip)

**Comment by olix0r** [comment]
Are you able to try the most recent edge release? We've addressed similar issues in the past few months and it would be helpful to know whether the issue persists.

**Comment by Neru007** [comment]
Tried the Latest Edge Release edge-21.2.2 and it's blocking the entire http traffic through application so I removed it. However  then I installed stable version 2.9.3 and found that same issue still persist. so currently now I'm on Linkerd version: 2.9.3

**Comment by adleong** [comment]
@Neru007 can you give us more information about edge-21.2.2 blocking all http traffic?  that sounds bad!

**Comment by Neru007** [comment]
@adleong The entire communication between the Pods isn't happening which is working fine with stable release. I'm able to reach the Nginx Pod while stable-2.9.3 proxy is injected whereas it's not working at all when edge-21.2.2 proxy is injected.

**Comment by adleong** [comment]
Hi @Neru007.  Unfortunately, there's very little we can do to help unless you have provide very detailed reproduction instructions or a very detailed description of the behavior that you're seeing.

**Comment by Neru007** [comment]
I believe I've already provided detailed TCP dump along with Linkerd proxy log attached in the ticket itself

**Comment by Neru007** [comment]
I've upgraded it to Linkerd version: 2.9.4 Stable which includes last edge release as well but still issue persist.

**Comment by adleong** [comment]
Hi @Neru007! Unfortunately, we have not had a chance to look at the TCP dump you attached.  Generally speaking, the more work you can do to narrow down the problem, the easier it is for us to investigate.

I'll also note that stable-2.9.4 is a point release on the 2.9 branch and actually does not include recent edge releases.  It would be super helpful if you could test stable-2.10.0 or the latest edge release and see if the issue exists there.

**Comment by adleong** [comment]
Closing this for now.  If you continue to see this behavior in stable-2.10.0 please feel free to re-open or create a new issue.
