### ISSUE TITLE
Rename multicluster mirror label

### ISSUE THREAD

**Issue by kleimkuhler** [linkerd/linkerd2#5725]
Labels and annotations that belong to extensions are prefixed by their extension
name. For example, Viz extension has the `viz.linkerd.io` prefix and Jaeger
extension is `jaeger.linkerd.io`.

When mirroring a service with the multicluster extension, the label is
`mirror.linkerd.io/exported`. To be more consistent, this should be changed to
`multicluster.linkerd.io/exported`

**Comment by alpeb** [comment]
Fixed by #5771
