### ISSUE TITLE
Ensure extension resources are named consistently

### ISSUE THREAD

**Issue by kleimkuhler** [linkerd/linkerd2#5727]
`tap-injector...` -> `linkerd-tap-injector...`

To be more consistent with other pod and deployment names:

```
❯ kubectl get -n linkerd-viz pods
NAME                                   READY   STATUS    RESTARTS   AGE
linkerd-web-6d5d75554b-kqgj4           2/2     Running   0          33m
linkerd-tap-8568895d7d-g6swl           2/2     Running   0          33m
linkerd-grafana-c69c8f5cd-2rnqz        2/2     Running   0          33m
linkerd-metrics-api-776fc757f7-ggk4l   2/2     Running   0          33m
tap-injector-5bf4c78bdc-7jdhn          2/2     Running   0          33m
```

```
❯ kubectl get -n linkerd-viz deploy
NAME                  READY   UP-TO-DATE   AVAILABLE   AGE
linkerd-web           1/1     1            1           34m
linkerd-tap           1/1     1            1           34m
linkerd-grafana       1/1     1            1           34m
linkerd-metrics-api   1/1     1            1           34m
tap-injector          1/1     1            1           34m
```

**Comment by adleong** [comment]
Another possibility to consider would be removing the `linkerd-` prefix from all of the other deployment names, since it's pretty redundant.

**Comment by kleimkuhler** [comment]
I'd be good with that too. The Jaeger extension follows that approach.

**Comment by alpeb** [comment]
Agreed. Only the cluster-level resources should be prepended with `linkerd-`.

**Comment by olix0r** [comment]
Per conversation:

* We need to be sensitive to upgrades for at least the core control plane and multicluster extension
* We should probably make changes to the `viz` and `jaeger` extension.
* We should ALSO do this for extension label values (i.e. `viz` instead `linkerd-viz`)
