### ISSUE TITLE
linkerd-proxy for external traffic `Client network socket disconnected before secure TLS connection was established` error

### ISSUE THREAD

**Issue by mroohian** [linkerd/linkerd2#5730]
Issue Type:

- [x] Bug report
- [ ] Feature request

**What happened**:
Injecting linkerd-proxy in a pod that tries connect(using axios) to external SAP server oauth endpoints causes this error: `Client network socket disconnected before secure TLS connection was established`. However it works fine with `linkerd.io/inject: disabled`. This behavior is a bit random since the first few requests after the pod is created, succeeds. Also the connection is to a non-standard port using HTTPS. Something like `https://[sap-server-host]:50001/path`.

**What you expected to happen**:
As mentioned, the request to external servers should work.

**How to reproduce it (as minimally and precisely as possible)**:
Inject linkerd-proxy into a node.js service that uses axios to connect to external SAP server OAuth using base authentication.

**Anything else we need to know?**:

**Environment**:
- linkerd:
  - Client version: stable-2.9.2
  - Server version: stable-2.9.2
- PlatformKubernetes:
  - Client Version: v1.19.3
  - Server Version: v1.20.1
- Hardware configuration:
  - Bare-metal K8S cluster running on ESXi

**Comment by adleong** [comment]
HI @mroohian!  I think you're encountering this error because your using HTTPS on a nonstandard port.  Consider adding 50001 to your list of outbound skip ports as described here https://linkerd.io/2/features/protocol-detection/ to skip the Linkerd proxy on that port.

**Comment by mroohian** [comment]
Thank you for the prompt response! The solution you've provided solves the error.
