### ISSUE TITLE
Installing linkerd2 with fluxv2 getting error 

### ISSUE THREAD

**Issue by yershalom** [linkerd/linkerd2#5763]
### What is the issue?
I'm trying to install linkerd2 from my fluxv2 repo with HelmRelease resource and I'm getting `Helm install failed: execution error at (linkerd2/charts/prometheus/templates/prometheus.yaml:289:12): Please provide the identity trust anchors` error

### How can it be reproduced?

Try to install linkerd with from here: https://github.com/yershalom/yafyuf-flux.
I provided example config map like I have in my cluster (not the same PEM keys and certs)

### Logs, error output, etc

[gist](https://gist.github.com/yershalom/82a13ccabd12a30fb554df48c756c6c1)

#### `linkerd check` output

```text
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
× 'linkerd-config' config map exists
    failed to load linkerd-config
    see https://linkerd.io/checks/#l5d-existence-linkerd-config for hints

Status check results are ×
```

* I don't have config map with this name linkerd-config.

### Environment

- Kubernetes Version: 1.18.10
- Cluster Environment: AKS
- Host OS: Ubuntu 18.04.5 LTS
- Linkerd version: 2.9.3

**Comment by JasonMorgan** [comment]
Can you add some steps to reproduce? I was about to walk through a similar scenario.

**Comment by adleong** [comment]
Hi @yershalom!  I'm not too familliar with flux.  Do things work for you if you install with Helm directly by following the instructions at https://linkerd.io/2/tasks/install-helm/?  If so, I suspect this is some problem or misconfiguration with how flux is invoking Helm.

**Comment by yershalom** [comment]
Hi @adleong, I see it is working with Helm 3 install.
I'll address the issue to FluxV2.
Thanks
