### ISSUE TITLE
init: Add a check for existing iptables rules

### ISSUE THREAD

**Issue by cpretzer** [linkerd/linkerd2#5786]
### What problem are you trying to solve?
The proxy-init container will fail to start if either of the `PROXY_INIT_OUTPUT` or `PROXY_INIT_REDIRECT` chains already exist in the iptables rules. When the init container fails to start, the pod goes into a CrashLoopBackOff state.

The scenario where this behavior was discovered is an edge case where a process external to Kubernetes removed the `proxy-init` image from the node. k8s has its own garbage collection mechanism for images, so when an image is removed outside of that mechanism, k8s will pull the missing image and restart any containers that use the image.

The underlying cause for this behavior is that the logic in [iptables.go](https://github.com/linkerd/linkerd2-proxy-init/blob/master/iptables/iptables.go#L73) adds the `PROXY_INIT_OUTPUT` and `PROXY_INIT_REDIRECT` chains without checking to see if they exist first.

### How should the problem be solved?
Add logic to iptables.go that captures the output from the `iptables save` command and uses regex to search for the `PROXY_INIT_OUTPUT` and `PROXY_INIT_REDIRECT` rules.

If either of them exist, remove them, then allow the existing code to add the rules back in.

### Any alternatives you've considered?
1. Do the same check outlined above to see if the rules exist, and if they do, then _don't_ remove them or run the `addIncomingTrafficRules` and `addOutgoingTrafficRules` functions. Instead exit 0 and assume that the rules are valid.

The drawback here is that a skipped port could have been added at the namespace level, and those won't be reflected in the iptables rules. I see this being a pretty infrequent or improbable scenario, since updating skipped ports at the namespace level should be followed by restarting the pods.

2. Set `restartPolicy: never` in the proxy-init PodSpec

I don't know the full ramifications of this, so it could be a really bad idea :smile: 

### How would users interact with this feature?

This would be transparent to users and they won't need any interaction

**Comment by propainter** [comment]
I am interested in this. Can i pick it @cpretzer ?

**Comment by 1vanzamarripa** [comment]
@cpretzer I tried this one:

`Set restartPolicy: never in the proxy-init PodSpec`

it didn't work:

`Error from server (Invalid): error when creating "linkerd2-stable-2.9.4.yaml": Deployment.apps "linkerd-prometheus" is invalid: spec.template.spec.restartPolicy: Unsupported value: "Never": supported values: "Always"`

**Comment by kleimkuhler** [comment]
@1vanzamarripa seems this is tracked upstream in kubernetes/kubernetes#24725.

However, I think the first solution provided makes the most sense in this case. The container should be capable of handling the case when the rules already exist instead of erroring out.

**Comment by dadjeibaah** [comment]
Fixed by linkerd/linkerd2-proxy-init#38
