### ISSUE TITLE
Bundled trust anchor will still show as an expiring trust anchor cert

### ISSUE THREAD

**Issue by lagalbra** [linkerd/linkerd2#5800]
# Thanks for your help improving the project! #

## Getting Help ##

Github issues are for bug reports and feature requests. For questions about
Linkerd, how to use it, or debugging assistance, start by
[asking a question in the forums](https://discourse.linkerd.io/) or join us on
[Slack](https://slack.linkerd.io/).

Full details at [CONTRIBUTING.md](https://github.com/linkerd/linkerd/blob/main/CONTRIBUTING.md).

## Filing a Linkerd issue ##

Issue Type:

- [X] Bug report
- [ ] Feature request

**What happened**:
In [the linkerd trust anchor documentation](https://linkerd.io/2/tasks/manually-rotating-control-plane-tls-credentials/#deploying-the-new-bundle-to-linkerd) , under the "Deploying the new bundle to Linkerd" section, it gives example outputs for `linkerd check --proxy` that incorrectly show

```
√ trust roots are within their validity period
√ trust roots are valid for at least 60 days
```

when, if the original trust anchor cert is less than 60 days from expiry, the bundle will still log that:

```
√ trust anchors are within their validity period
‼ trust anchors are valid for at least 60 days
...
```

Note: I do not know what the expected output is when the trust anchor has actually expired, only when it's less than 60 days from expiring.

**What you expected to happen**:
If this is the case for both trust anchor certs-near-expiry and expired-trust-anchor, the docs should be updated to be clear that the warning will not go away until the [removing old trust anchor documentation steps](https://linkerd.io/2/tasks/manually-rotating-control-plane-tls-credentials/#removing-the-old-trust-anchor) are performed.

**How to reproduce it (as minimally and precisely as possible)**:
Perform the trust anchor rotation cert steps up to and including "Deploying the new bundle to Linkerd" and running the last `linkerd check --proxy`

**Anything else we need to know?**:

**Environment**:
- linkerd/namerd version, config files:
    - linkerd 2.9.1
- Platform, version, and config files (Kubernetes, DC/OS, etc):
- Cloud provider or hardware configuration:

**Comment by adleong** [comment]
Thanks @lagalbra!  Are you interested in submitting a PR to https://github.com/linkerd/website to correct this?

**Comment by lagalbra** [comment]
@adleong I would be happy to! Can I simply open a PR with the changes and reference this validated issue?

**Comment by kleimkuhler** [comment]
@lagalbra Yep just open a PR in the [linkerd/website](https://github.com/linkerd/website) repo and reference this issue in the description. Thanks!
