### ISSUE TITLE
Pass in default set of opaque ports to destination server

### ISSUE THREAD

**Issue by kleimkuhler** [linkerd/linkerd2#5817]
After #5810 and and #5814 merge, we'll have two locations that track the default
set of opaque ports—`values.yaml` and `opaqueports/defaults.go`.

Instead of manually keeping these in sync, we should pass in the default set of
opaque ports as a flag to the destination server, and have the server use that
to return the default set of ports in destination profile responses.

**Comment by Pothulapati** [comment]
Working on this.
