### ISSUE TITLE
Huge increase in CPU/Memory in linkerd prometheus after upgrading to 2.9.4 (from 2.8.1)

### ISSUE THREAD

**Issue by ericsuhong** [linkerd/linkerd2#5818]
### What is the issue?

We are seeing a significant increased in CPU/Memory usage in linkerd prometheus container after upgrading to 2.9.4 from 2.8.1:

![image](https://user-images.githubusercontent.com/3857851/109073129-d67d8400-76aa-11eb-920a-3b82fb329414.png)![image](https://user-images.githubusercontent.com/3857851/109073151-dd0bfb80-76aa-11eb-8851-bb40146ffe13.png)

It eventually causes linkerd-prometheus container to keep OOMKilled.

Linkerd prometheus CPU/Memory usage has been pretty much a flat line in 2.8.1.

### How can it be reproduced?
Not sure how it can be reproduced but it is very obvious from our CPU/Memory usage graph.

Nothing changed in our test environment (same traffic volume) except linkerd version.

#### `linkerd check` output

kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-identity
----------------
√ certificate config is valid
√ trust anchors are using supported crypto algorithm
√ trust anchors are within their validity period
√ trust anchors are valid for at least 60 days
√ issuer cert is using supported crypto algorithm
√ issuer cert is within its validity period
√ issuer cert is valid for at least 60 days
√ issuer cert is issued by the trust anchor

linkerd-webhooks-and-apisvc-tls
-------------------------------
√ tap API server has valid cert
√ tap API server cert is valid for at least 60 days
√ proxy-injector webhook has valid cert
√ proxy-injector cert is valid for at least 60 days
√ sp-validator webhook has valid cert
√ sp-validator cert is valid for at least 60 days

linkerd-api
-----------
√ control plane pods are ready
√ control plane self-check
√ [kubernetes] control plane can talk to Kubernetes
| wa× [prometheus] control plane can talk to Prometheus
    Error calling Prometheus from the control plane: server_error: server error: 503
    see https://linkerd.io/checks/#l5d-api-control-api for hints

### Environment

- Kubernetes Version: 1.16.9
- Cluster Environment: Azure, self-hosted Kubernets clusters
- Host OS: Ubuntu
- Linkerd version: 2.9.4

**Comment by ericsuhong** [comment]
Here are sample metrics output from 2.8.1 and 2.9.4
[prom_output_2.8.1.txt](https://github.com/linkerd/linkerd2/files/6039270/prom_output_2.8.1.txt)
[prom_output_2.9.4.txt](https://github.com/linkerd/linkerd2/files/6039271/prom_output_2.9.4.txt)

**Comment by ericsuhong** [comment]
Here is "Highest Cardinality Metric Names" from prometheus dashboard:

2.8.1:
![image](https://user-images.githubusercontent.com/3857851/109083978-c1f5b780-76bb-11eb-8ef7-4a8f6eac845a.png)

2.9.4:
![image](https://user-images.githubusercontent.com/3857851/109083962-bacea980-76bb-11eb-9e74-18c29a870bf1.png)

It seems to be very clear that tcp_* metrics are just too many for regular linkerd prometheus to handle... Is there a way to disable these metrics (or go back to old way of metrics?)

**Comment by dadjeibaah** [comment]
Hey @ericsuhong, wanted to note that the proxy has been modified to stop sending `tcp_connection_duration_ms` metrics in linkerd/linkerd2-proxy#930. Hopefully this reduces cpu and memory pressure on Prometheus since this metric had the highest cardinality.

 There are other tcp_* metrics that are still useful and are used by the CLI `stat` and `edges` command. We also use these metrics to display TCP info in the web dashboard. The metrics used are as follows:

- `tcp_open_connections`
-  `tcp_read_bytes_total`
-  `tcp_write_bytes_total`
-  `tcp_close_total`
-  `tcp_open_total`

**Comment by ericsuhong** [comment]
I still have a concern that remaining tcp_ metrics would still increase memory usage a lot compared to previous release (based on numbers attached on above screenshot).

**Comment by olix0r** [comment]
@ericsuhong The proxy now reports TCP client metrics for each endpoint a proxy communicates with. Given that there are many more TCP metrics in your cluster than HTTP metrics, it sounds like your application connects to many more non-HTTP TCP endpoints than it does HTTP endpoints and I assume your application connects to many unique IP:PORT pairs.

In the short-term, you might consider modifying the prometheus scrape config to drop these metrics from pods that connect to many unique tcp endpoints. These metrics are relied on, however, for `edges` and `stat` commands, so you may lose some functionality there.

More generally, though: what would you like Linkerd to do in this situation? How would you like TCP client metrics to reported for this application?

**Comment by ericsuhong** [comment]
@olix0r We do not rely on TCP client metrics, so we were surprised by this issue. This is a regression only specific to high-load scenario such as ours, so a flag to turn off these tcp-related metrics would have been nice.

**Comment by adleong** [comment]
Hi @ericsuhong!  As of [edge-21.2.4](https://github.com/linkerd/linkerd2/releases/tag/edge-21.2.4) and later, the `tcp_connection_duration_ms` metric has been removed.  Hopefully this should resolve the prometheus memory issue.
