### ISSUE TITLE
Cert Rotation not clearly described in the Documents

### ISSUE THREAD

**Issue by S93rastogi** [linkerd/linkerd2#5824]
Hi Team,

I have started working with LinkerD recently and trying to set it up on the cluster. 
The issue I am facing is with the cert rotation. **The LinkerD documentation does not elaborate completely on the process of how the issuer cert is used to generate the CSR for the Proxy request and also it does not mention how Cert Manager could be used to store the issuer cert.**
If I am not missing something could you please point me to the documentation that completely elaborates the same.

Also I want to clarify if we just generate the root cert and intermediate cert, later inject it using **--identity-trust-anchors-file** and 
**--identity-issuer-certificate-file** will that work or we need to find specifically how to rotate the certs.
I may be posting on the wrong channel but the lack of documentation caused me to ask the above questions.
Thanks in advance.

**Comment by olix0r** [comment]
Cert-manger configuration is discussed here: https://linkerd.io/2/tasks/automatically-rotating-control-plane-tls-credentials/#cert-manager

And an overview of the steps required to rotate the trust anchor is provided here: https://linkerd.io/2/tasks/manually-rotating-control-plane-tls-credentials/#rotating-the-trust-anchor

> Also I want to clarify if we just generate the root cert and intermediate cert, later inject it using --identity-trust-anchors-file and --identity-issuer-certificate-file will that work or we need to find specifically how to rotate the certs.

You should try to avoid rotating the trust *anchor* (though, it's expected and encouraged for you to rotate the issuer credentials as frequently as you'd like). As described in the above document, rotating the anchor is an invasive process that requires restarting all of your workloads multiple times. This is by-design, as it should not be possible to change a proxy's trust anchors at runtime. We generally expect a trust anchor to live as long as your Kubernetes cluster.

Let us know if you have questions about these docs or ideas about how they could be clearer.

**Comment by S93rastogi** [comment]
Thanks a lot, @olix0r . I will go through the documentation and try the things mentioned above. Will come back to you with the improvements as required to the documents if any.
There may be follow-up questions so I will be thankful if you could bear up with me.

**Comment by adleong** [comment]
Thanks @S93rastogi! Feel free to open issues or ask in slack if you find specific things that can be improved.  PRs are also more than welcome!
