### ISSUE TITLE
[FEATURE] DeepSource Integration

### ISSUE THREAD

**Issue by withshubh** [linkerd/linkerd2#5828]
I ran DeepSource analysis on my fork of this repository and found some code quality issues. Have a look at the issues caught in this repository by DeepSource [here](https://deepsource.io/gh/withshubh/linkerd2/issues/?category=recommended).

[DeepSource](https://deepsource.io/) is a code review automation tool that detects code quality issues and helps you to automatically fix some of them. You can use DeepSource to track test coverage, Detect problems in Dockerfiles, etc. in addition to detecting issues in code. 

PR #5827 fixed some of the issues caught by DeepSource.

All the features of the DeepSource are mentioned [here](https://deepsource.io/features/).
I'd suggest you integrate DeepSource since it is free for Open Source projects forever.

Integrating DeepSource to continuously analyze your repository:
- Install DeepSource on your repository [here](https://deepsource.io/signup).
- Create a `.deepsource.toml` configuration specific to this repo or use the configuration mentioned below which I used to run the analysis on the fork of this repo.
- Activate analysis [here](https://deepsource.io/gh/linkerd/linkerd2/).

----

- [x] I can submit a new PR with the [configuration file](https://github.com/withshubh/linkerd2/blob/deepsource/.deepsource.toml) which I used to run the analysis on the forked copy of this repo.

**Comment by olix0r** [comment]
We're pretty conservative about adding dependencies to CI, especially when these checks can't easily be run locally as part of our normal development flow.

So far, we've been pretty happy with our Go linting and haven't found much value in the changes suggested by DeepSource. They're not _bad_, they're just not particularly high-impact enough to add to our CI.

Thanks for the suggestion, though! Things may change in the future.

**Comment by withshubh** [comment]
@olix0r  No problem! thanks for having a look :sparkles:
