### ISSUE TITLE
Dashboard "linkerd check" results missing identity section

### ISSUE THREAD

**Issue by diversario** [linkerd/linkerd2#5830]
## Bug Report

Results reported by `linkerd check` command ran locally are different from the results shown in the dashboard when using "Run linkerd check" button.

### What is the issue?

Dashboard "linkerd check" report does not include `linkerd-identity` section. Compare:

`linkerd check` command ran locally:

![image](https://user-images.githubusercontent.com/355800/109164749-114eed00-777b-11eb-8b72-4fe2649f2ad0.png)

"Run linkerd check" dashboard output:
![image](https://user-images.githubusercontent.com/355800/109164809-21ff6300-777b-11eb-94f6-8483e2e521e7.png)

Crucially, dashboard does not surface broken trust anchors.

### How can it be reproduced?

Run `linkerd check` locally. Run "Run linkerd check" in the dashboard, in the "Control Plane" view. Compare output.

### Logs, error output, etc

n/a

#### `linkerd check` output

```text
➜ linkerd check
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-identity
----------------
√ certificate config is valid
× trust anchors are using supported crypto algorithm
    Invalid trustAnchors:
        * 161447036489339868606905408684435501653 Sub CA 3 Service Mesh Testing must be signed by an ECDSA P-256 key, instead SHA256-RSA was used
        * 161447036489339868606905408684435501650 Root CA must use ECDSA for public key algorithm, instead RSA was used
    see https://linkerd.io/checks/#l5d-identity-trustAnchors-use-supported-crypto for hints

Status check results are ×
```

### Environment

- Kubernetes Version: 1.17.17
- Cluster Environment: `kops`
- Host OS: local - macOS 10.15.7, k8s - Ubuntu 20.04
- Linkerd version: 2.9.4

**Comment by alpeb** [comment]
That's a good catch :+1:  I'll get that synced up.

**Comment by alpeb** [comment]
Ok if I enabled such check, we'd see something like:
![image](https://user-images.githubusercontent.com/554287/109176064-6cb9b480-7754-11eb-9637-78eb9959eeca.png)
Which means we need to grant secrets read access to the useraccount underlying the dashboard. The dashboard being accessible to a broader public than the CLI, it's understandable why it would have less privileges. Thoughts?

**Comment by diversario** [comment]
Dashboard isn't exposed by default, and access to the dashboard depends on access to the `linkerd` namespace (so one could `port-forward` to the dashboard service), so there's an effort in exposing it to unprivileged users.

But it makes sense to not grant permissions like this if it can be avoided. I think a way to do this safely would be to delegate this validation to another linkerd component (e.g. `linkerd-identity` service itself), and dashboard could call an endpoint on it to get validation results. Then there would be no need for direct secrets access.

**Comment by adleong** [comment]
We definitely want to restrict access to the `linkerd-identity-anchor` secret as much as possible.  I'd recommend running `linkerd check` from the CLI if you want to check identity cert health.

**Comment by diversario** [comment]
> We definitely want to restrict access to the `linkerd-identity-anchor` secret as much as possible. I'd recommend running `linkerd check` from the CLI if you want to check identity cert health.

If the in-dashboard identity check is not possible/practical, it should at least warn the user that it does not perform that check. Right now, it _looks_ like it's the same as the CLI check, so it's not intuitive that one should bother rerunning the check from the CLI.

**Comment by adleong** [comment]
@diversario that's a great point.  I think it would be a great idea for the dashboard check to have such a warning.  Are you interested in contributing a PR adding this to the dashboard?

**Comment by diversario** [comment]
> @diversario that's a great point. I think it would be a great idea for the dashboard check to have such a warning. Are you interested in contributing a PR adding this to the dashboard?

I'm interested! Will try to do that ASAP.
