### ISSUE TITLE
cli: Show spinner in extension checks when invoked from core check

### ISSUE THREAD

**Issue by kleimkuhler** [linkerd/linkerd2#5837]
We should so a spinner for extension checks that are invoked by the core `check`
command.

For example, immediately after installing the viz extension, running `linkerd
viz check` results in spinners for each component:

```
❯ linkerd viz check
linkerd-viz
-----------
√ linkerd-viz Namespace exists
√ linkerd-viz ClusterRoles exist
√ linkerd-viz ClusterRoleBindings exist
√ tap API server has valid cert
√ tap API server cert is valid for at least 60 days
| waiting for check to complete 
```

However, if invoked by the core `check` command, it appears to hang:

```
...
√ control plane and cli versions match

Status check results are √

Linkerd extensions checks
=========================


```

I would expect the above output to be:

```
...
√ control plane and cli versions match

Status check results are √

Linkerd extensions checks
=========================

linkerd-viz
-----------
√ linkerd-viz Namespace exists
√ linkerd-viz ClusterRoles exist
√ linkerd-viz ClusterRoleBindings exist
√ tap API server has valid cert
√ tap API server cert is valid for at least 60 days
| waiting for check to complete
```

**Comment by adleong** [comment]
Note that since we invoke extension checks with the json output flag, we get the entire json response at once.  This means we can't display a spinner for individual check items in extension checks.  We could, however, display 1 spinner for the entire extension check while waiting for the extension check output.
