### ISSUE TITLE
linkerd destination service keeps stopping watching profiles and endpoints , causing whole traffic gets down between pods

### ISSUE THREAD

**Issue by gokcesurenkok** [linkerd/linkerd2#5852]
## Bug Report
linkerd destination service stops watching profiles and endpoints, causing whole traffic to get down between pods
### What is the issue?
It happened to us the second time in a while, it seems destination service stops responding to proxies .and whole traffic stops.
### How can it be reproduced?
it happened to us 2 unrelated time. last time it happened in the middle of night when there is really low traffic coming to cluster. I checked the kubernetes cluster events , there were no node unready event , or none of the linkerd controller pods were restarted.
### Logs, error output, etc
i am attaching the destination pod logs
https://gist.github.com/gokcesurenkok/1c89e4d41b3731a27e2cbfb9a86f30e3

and injected linkerd proxies throwing 

Failed to proxy request: HTTP Balancer service in fail-fast
 this log.

(If the output is long, please create a [gist](https://gist.github.com/) and
paste the link here.)

#### `linkerd check` output

```
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-identity
----------------
√ certificate config is valid
√ trust anchors are using supported crypto algorithm
√ trust anchors are within their validity period
√ trust anchors are valid for at least 60 days
√ issuer cert is using supported crypto algorithm
√ issuer cert is within its validity period
√ issuer cert is valid for at least 60 days
√ issuer cert is issued by the trust anchor

linkerd-webhooks-and-apisvc-tls
-------------------------------
√ proxy-injector webhook has valid cert
√ proxy-injector cert is valid for at least 60 days
√ sp-validator webhook has valid cert
√ sp-validator cert is valid for at least 60 days

linkerd-api
-----------
√ control plane pods are ready

linkerd-version
---------------
√ can determine the latest version
‼ cli is up-to-date
    is running version 21.2.3 but the latest edge version is 21.2.4
    see https://linkerd.io/checks/#l5d-version-cli for hints

control-plane-version
---------------------
‼ control plane is up-to-date
    is running version 21.2.3 but the latest edge version is 21.2.4
    see https://linkerd.io/checks/#l5d-version-control for hints
√ control plane and cli versions match

Status check results are √
```

### Environment

- Kubernetes Version: 1.19.7
- Cluster Environment: on prem
- Host OS: centos 7
- Linkerd version: edge-21.2.3

**Comment by gokcesurenkok** [comment]
and i uninstalled it , and reinstalled it with the latest edge release, and now it fails totally , i think the problem might be this 
`linkerd_app_core::control: Failed to resolve control-plane component error=no record found for name: linkerd-dst-headless.linkerd.svc.cluster.local. type: SRV class: IN`
it is a log line from identity pod linkerd proxy container.

**Comment by gokcesurenkok** [comment]
second note :  after i applied linkerd uninstall , it is not removing clusterrolebindings, clusterroles, or crds , so i had to remove namespace , and apply linkerd install | kubectl delete -f - , that deleted the residues.

now it works , but proxies stop loadbalancing randomly , that issue remains.

**Comment by kleimkuhler** [comment]
@gokcesurenkok So all the `Stopping watch on ...` logs in the destination server mean that a client of the server is closing its connection. That means the server can stop sending updates to that specific client; it's not necessarily stopping all watches.

I know you mentioned there are no linkerd pod restarts, but are there any application pod restarts? It's possible if one of these restarts, then this could result in the logs you attached.

As a side note (and feel free to open in a separate issue if you'd like), I haven't been able to reproduce the uninstall behavior you mention. Are you by chance doing an upgrade between the two versions and seeing this? If so, the upgrade command was [recently updated](https://linkerd.io/2/tasks/upgrade/#with-linkerd-cli) to prune cluster scoped resources. I would try using that.

**Comment by gokcesurenkok** [comment]
hey @kleimkuhler , yeah I have realized it later, sorry for the misunderstanding that part. However, when this thing happens, we have to uninject , otherwise, traffic stops, and it is repeating again when you reinject. I have restarted the controller pods of linkerd and injected them again. linkerd proxy was still rejecting the traffic. 
and it is not only one applications sidecar, all of the applications sidecar proxies were failing.
In the end, I had to remove the whole linkerd setup. it is really weird and happened to us the second time. right now we consider moving something else for service mesh sadly..

**Comment by mboutet** [comment]
I've got the same problem. In my case, this happens when the system is under moderate load. All traffic suddenly stops. You can see the dramatic drop [here](https://user-images.githubusercontent.com/52334444/110035009-1e368800-7d09-11eb-8152-9ea655ecd026.png). This is the ingress RPS going from ~180 RPS of 200 HTTP codes to ~10 RPS of 503 HTTP codes. Also on 1.19.7 and 2.9.4-stable and using AKS. The CPU usage of `linkerd-destination` is nowhere the request of `200m`.

Should I open a separate issue? It seems to me that the problem might be the same.

**Comment by gokcesurenkok** [comment]
it happened once again, 3 incidents in a row, we have decided to uninject linkerd proxy from all of our applications till it is resolved. 
I am attaching the linkerd proxy logs of 3 controller components if it helps.
controller,destination ,and identitys

https://gist.github.com/gokcesurenkok/016acf2408b29a02cd4bd1dbb8f63e2c

**Comment by olix0r** [comment]
Alternately, in #5881 we think this may be a bug in the way we handle lookups for host-network pods. Are you using host networking or connecting to node IPs?

**Comment by kleimkuhler** [comment]
@gokcesurenkok This will likely be fixed by #5904 if you are dealing with any pods that have a host IP. @mboutet The same goes for you.

I'll update this issue when we get an edge release out with those changes, but just wanted to let you both know we are still looking into this issue and hope to have a fix in for it soon.

**Comment by kleimkuhler** [comment]
The fix for this is available in the current edge `edge-21.3.3`. If anyone on this thread would like to confirm that would be helpful! I'll keep it open for a little while longer for any follow-up debugging if needed.

**Comment by DaspawnW** [comment]
We detected this issue a week ago in 2.9.0, afterwards we performed an upgrade to 2.10.2, which should include the edge-21.3.3 fix for it. At some point in time the destination service stops watching profiles and endpoints and then the whole traffic within the mesh stops to work.

![destination stop watching](https://user-images.githubusercontent.com/2182549/125078865-43764100-e0c3-11eb-8a92-891555efcb54.png)

Afterwards the proxy nodes run into the exception "could not fetch profile":
![linkerd-proxy could not fetch profile](https://user-images.githubusercontent.com/2182549/125079005-6e609500-e0c3-11eb-8518-64d2e1984812.png)

What we see in our monitoring system is, that at this point in time a really immensive number of traffic goes through the linkerd-proxy running infront of the destination service:
![grafana-destination](https://user-images.githubusercontent.com/2182549/125079301-bb446b80-e0c3-11eb-9d44-04d8c64f4f4b.png)

After restarting the destination servers again the cluster is healthy.

For now we increased the memory limit of destination from 256MB to 512 and removed the cpu limitation which were applied before.

Our cluster currently has around 720 pods with linkerd, so maybe the system was simply a bit too heavy under use, but on the other side it simply occured at some point in time and before the system was healthy and with near to no usage.

**Comment by kleimkuhler** [comment]
@gokcesurenkok Thanks for the details here. It would be helpful to figure out why there was such a large increase in traffic to the destination service.

Around the time that this occurred, were there any other meshed pod restarts going on in the cluster? Is it possible that after a large number of restarts or the introduction of newly meshed pods, that there was just a lot more traffic to the destination service?

If there were no other events going on within the cluster then this spike in traffic is definitely questionable. Increased logs should be helpful if this happens again so I'll keep an eye out for any more updates from you.

**Comment by DaspawnW** [comment]
Sorry for spamming a bit, after the upgrade of memory to 512MB for destination service it currently seems that we are stable again. I'll continue to monitor it but I have fingers crossed that its gone ;-)

Restarts of linkerd destination service:
![restarts](https://user-images.githubusercontent.com/2182549/125578322-a1b19a45-924e-457c-97c4-fba741f825b0.png)

**Comment by adleong** [comment]
Sounds like things have been stable.  Please feel free to re-open or file a new issue if you encounter any problems.
