### ISSUE TITLE
Issue with the command to export service in multi-cluster setup

### ISSUE THREAD

**Issue by sagarpatil23192** [linkerd/linkerd2#5854]
### No logs are found in service-mirror

(If the output is long, please create a [gist](https://gist.github.com/) and
paste the link here.)

#### `linkerd check` output

```text
your output here ...
```

### Environment

- Kubernetes Version:1.18.12-gke.1210
- Cluster Environment: GKE
- Host OS: 
- Linkerd version:
Client version: stable-2.8.1
Server version: stable-2.8.1

**Comment by kleimkuhler** [comment]
@sagarpatil23192 The issue you are running into here is the docs are updated for the current stable version: `stable-2.9.4`. If you still using `stable-2.8.1` there may be commands and sub-commands (such as `export-service`) that have been removed.

I'd recommend using a more current version of Linkerd if you are following the doc tutorials. If you still run into issues, please feel free to continue discussion on this issue and I can open it back up!
