### ISSUE TITLE
Infrequent connectivity issues on stable-2.9.4 with "Stopping watch on profile" messages

### ISSUE THREAD

**Issue by tyzbit** [linkerd/linkerd2#5865]
### What is the issue?
Occasionally, there appears to be connectivity issues between two containers with linkerd injected.  In my case, NextCloud is unable to talk to Redis for a short period of time.

### How can it be reproduced?
Create two deployments + services, have one deployment call the other service via internal Kubernetes DNS

### Logs, error output, etc

[gist](https://gist.github.com/tyzbit/71cfbf4bdba0a9411daa3f4acdeaf7de)

#### `linkerd check` output

<details><summary>Click to expand</summary>
<pre>
~|⇒ (⎈ |takeout:default) linkerd check                                                                                                                                          [16m16s] [2021/03/03|20:21]
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
W0303 20:21:53.542031   18816 warnings.go:67] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
√ control plane CustomResourceDefinitions exist
W0303 20:21:53.554185   18816 warnings.go:67] admissionregistration.k8s.io/v1beta1 MutatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 MutatingWebhookConfiguration
√ control plane MutatingWebhookConfigurations exist
W0303 20:21:53.563962   18816 warnings.go:67] admissionregistration.k8s.io/v1beta1 ValidatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 ValidatingWebhookConfiguration
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-identity
----------------
√ certificate config is valid
√ trust anchors are using supported crypto algorithm
√ trust anchors are within their validity period
√ trust anchors are valid for at least 60 days
√ issuer cert is using supported crypto algorithm
√ issuer cert is within its validity period
√ issuer cert is valid for at least 60 days
√ issuer cert is issued by the trust anchor

linkerd-webhooks-and-apisvc-tls
-------------------------------
√ tap API server has valid cert
√ tap API server cert is valid for at least 60 days
W0303 20:21:53.633315   18816 warnings.go:67] admissionregistration.k8s.io/v1beta1 MutatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 MutatingWebhookConfiguration
√ proxy-injector webhook has valid cert
√ proxy-injector cert is valid for at least 60 days
W0303 20:21:53.741607   18816 warnings.go:67] admissionregistration.k8s.io/v1beta1 ValidatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 ValidatingWebhookConfiguration
√ sp-validator webhook has valid cert
√ sp-validator cert is valid for at least 60 days

linkerd-api
-----------
√ control plane pods are ready
√ control plane self-check
√ [kubernetes] control plane can talk to Kubernetes
√ [prometheus] control plane can talk to Prometheus
√ tap api service is running

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ control plane is up-to-date
√ control plane and cli versions match
W0303 20:21:54.790601   18816 warnings.go:67] admissionregistration.k8s.io/v1beta1 MutatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 MutatingWebhookConfiguration

linkerd-prometheus
------------------
√ prometheus add-on service account exists
√ prometheus add-on config map exists
√ prometheus pod is running

linkerd-grafana
---------------
√ grafana add-on service account exists
√ grafana add-on config map exists
√ grafana pod is running

Status check results are √
</pre>
</details>

### Environment

- Kubernetes Version: v1.19.7
- Cluster Environment: (GKE, AKS, kops, ...): baremetal, provisioned with kubeadm
- Host OS: Ubuntu 20.04.1 LTS
- Linkerd version:
        Client version: stable-2.9.4
        Server version: stable-2.9.4

### Possible solution
I suspect the `Stopping watch on profile default/nextcloud-cache.default.svc.cluster.local` type messages are related to the cause.  If the watch is stopped, does this mean connectivity is interrupted?  I see these messages in my logs constantly.

### Additional context
I do have Weave Scope installed in the cluster as well; I don't know if that's interfering at all.  I installed that before linkerd and only noticed issues after adding linkerd.

**Comment by mboutet** [comment]
Might be related to https://github.com/linkerd/linkerd2/issues/5852?

**Comment by tyzbit** [comment]
Yes, I'm not positive but this might be a duplicate.  I don't have the `Failed to resolve control-plane component` message in my logs though.

**Comment by kleimkuhler** [comment]
@tyzbit Thanks for opening up a report on this. We're currently trying to figure out if this is related to #5852. Is there any chance you would be able to try the current edge `edge-21.3.1`? As that is a release candidate for `stable-2.10.0` it would be good to know if in all the proxy changes that have occurred, this is the same or different than #5852.

Additionally, the logs provided in the last comment https://github.com/linkerd/linkerd2/issues/5852#issuecomment-791175920 are helpful, but it would be good have the proxy on debug log level as well.

If you are able to try this out with the edge, installing with `--proxy-log-level=debug` (or set the `config.linkerd.io/proxy-log-level: debug` that would really be appreciated. Thanks again!

**Comment by kleimkuhler** [comment]
@mboutet I saw you commented on #5852 as well that you are running into this with the current stable.

So far we have not been able to reproduce this, so the same request goes for you. If there is any chance you could try using the current edge with the proxy on debug log level, that would really help us out.

If you are not able to try out the current edge, providing information about anything unique to your cluster creation, linkerd installation, or type/amount of application traffic would be helpful.

Also, did you see any restarts in the linkerd pods when this occurred? If not, were there any other significant events on the cluster around the time it occurred?

**Comment by tyzbit** [comment]
@kleimkuhler Applying edge-21.3.1 with debug logging immediately killed connectivity to and between all of the services on my cluster, so I had to remove linkerd from everything.  Hopefully someone else can test.

**Comment by kleimkuhler** [comment]
@tyzbit Sorry to hear you ran into a different issue when trying to upgrade; that is certainly not good to hear. If you're interested in helping us figure out what that upgrade issue could have been, we'd definitely appreciate a new issue where you can just briefly describe what you did before all the connectivity issues.

Including what commands you used for upgrading and any logs from the pods would be great.

We'd like to make the upgrade process from `stable-2.9.4` to `stable-2.10.0` seamless, so if an issue occurs in certain scenarios it'd be good to get those figured out before we tag the new stable.

**Comment by adleong** [comment]
@kleimkuhler @tyzbit I see that #5879 has been closed.  Is there anything further to do on this issue or should we close this one as well?

**Comment by tyzbit** [comment]
I think this is close enough to being a duplicate of #5852 that it can be closed.
