### ISSUE TITLE
Docs run-through for release 2.10

### ISSUE THREAD

**Issue by Pothulapati** [linkerd/linkerd2#5867]
This is a parent issue to track and check if the docs are updated and work as expected.

- [x] [Adding Your Services to Linkerd](https://linkerd.io/2/tasks/adding-your-service/)
- [ ] [Automated Canary Releases](https://linkerd.io/2/tasks/canary-release/)
This does not work currently because [Flagger has a static dependency on the old prometheus endpoint](https://github.com/fluxcd/flagger/blob/main/kustomize/linkerd/patch.yaml)
https://github.com/fluxcd/flagger/pull/845
- [x] [Automatically Rotating Control Plane TLS Credentials](https://linkerd.io/2/tasks/automatically-rotating-control-plane-tls-credentials/)
No effect
- [x] [Automatically Rotating Webhook TLS Credentials](https://linkerd.io/2/tasks/automatically-rotating-webhook-tls-credentials/)
- [x] [Bringing your own Prometheus](https://linkerd.io/2/tasks/external-prometheus/)
- [x] [Configuring Proxy Concurrency](https://linkerd.io/2/tasks/configuring-proxy-concurrency/)
No effect
- [x] [Configuring Retries](https://linkerd.io/2/tasks/configuring-retries/)
- [x] [Configuring Timeouts](https://linkerd.io/2/tasks/configuring-timeouts/)
No effect
- [x] [Control Plane Debug Endpoints](https://linkerd.io/2/tasks/using-debug-endpoints/)
No effect
- [x] [Customizing Linkerd](https://linkerd.io/2/tasks/customize-install/)
- [x] [Debugging 502s](https://linkerd.io/2/tasks/debugging-502s/)
No effect
- [x] [Debugging gRPC applications with request tracing](https://linkerd.io/2/tasks/debugging-your-service/)
- [x] [Debugging HTTP applications with per-route metrics](https://linkerd.io/2/tasks/books/)
- [x] [Distributed tracing with Linkerd](https://linkerd.io/2/tasks/distributed-tracing/)
- [x] [Exporting Metrics](https://linkerd.io/2/tasks/exporting-metrics/)
https://github.com/linkerd/website/pull/979
- [x] [Exposing the Dashboard](https://linkerd.io/2/tasks/exposing-dashboard/)
- [x] [Generating your own mTLS root certificates](https://linkerd.io/2/tasks/generate-certificates/)
No effect
- [x] [Getting Per-Route Metrics](https://linkerd.io/2/tasks/getting-per-route-metrics/)
- [x] [Graceful Pod Shutdown](https://linkerd.io/2/tasks/graceful-shutdown/)
No effect
- [x] [Ingress traffic](https://linkerd.io/2/tasks/using-ingress/)
No effect
- [x] [Injecting Faults](https://linkerd.io/2/tasks/fault-injection/)
- [x] [Installing Linkerd](https://linkerd.io/2/tasks/install/)
- [x] [Installing Linkerd with Helm](https://linkerd.io/2/tasks/install-helm/)
- [x] [Installing Multi-cluster Components](https://linkerd.io/2/tasks/installing-multicluster/)
- [x] [Linkerd and Pod Security Policies (PSP)](https://linkerd.io/2/tasks/using-psp/)
- [x] [Manually Rotating Control Plane TLS Credentials](https://linkerd.io/2/tasks/manually-rotating-control-plane-tls-credentials/)
- [x] [Modifying the Proxy Log Level](https://linkerd.io/2/tasks/modifying-proxy-log-level/)
- [x] [Multi-cluster communication](https://linkerd.io/2/tasks/multicluster/)
- [x] [Replacing expired certificates](https://linkerd.io/2/tasks/replacing_expired_certificates/)
No effect
- [x] [Rotating webhooks certificates](https://linkerd.io/2/tasks/rotating_webhooks_certificates/)
- [x] [Securing Your Application with mTLS](https://linkerd.io/2/tasks/securing-your-service/)
- [x] [Securing Your Cluster](https://linkerd.io/2/tasks/securing-your-cluster/)
https://github.com/linkerd/website/pull/972
- [x] [Setting Up Service Profiles](https://linkerd.io/2/tasks/setting-up-service-profiles/)
- [x] [Troubleshooting](https://linkerd.io/2/tasks/troubleshooting/)
https://github.com/linkerd/website/pull/947
- [x] [Uninstalling Linkerd](https://linkerd.io/2/tasks/uninstall/)
https://github.com/linkerd/website/pull/971
- [x] [Uninstalling Multicluster](https://linkerd.io/2/tasks/uninstall-multicluster/)
- [x] [Upgrading Linkerd](https://linkerd.io/2/tasks/upgrade/)
- [x] [Upgrading Multicluster in Linkerd 2.9](https://linkerd.io/2/tasks/upgrade-multicluster/)
- [x] [Using a Custom Cluster Domain](https://linkerd.io/2/tasks/using-custom-domain/)
https://github.com/linkerd/website/pull/969
- [ ] [Using A Private Docker Repository](https://linkerd.io/2/tasks/using-a-private-docker-repository/)
- [ ] [Using GitOps with Linkerd with Argo CD](https://linkerd.io/2/tasks/gitops/)
- [x] [Using the Debug Sidecar](https://linkerd.io/2/tasks/using-the-debug-container/)

**Comment by Pothulapati** [comment]
[Architecture Diagram and Doc](https://linkerd.io/2/reference/architecture/) should also be updated

**Comment by adleong** [comment]
@Pothulapati now that 2.10.0 has been released, should we close this issue or are there outstanding doc items here that we should take care of?

**Comment by Pothulapati** [comment]
@adleong There are a couple of doc updates still in flight i.e
- Flagger Canary
- ArgoCD

Both of the above require changes in external repos, and I am tracking them. Will close this once they are fixed.

**Comment by adleong** [comment]
@Pothulapati any update on these?  since these changes are already tracked externally, should we close this tracking issue?
