### ISSUE TITLE
Applying edge-21.3.1 on top of stable-2.9.4 causes loss of connectivity

### ISSUE THREAD

**Issue by tyzbit** [linkerd/linkerd2#5879]
## Bug Report
While running stable-2.9.4, I applied edge-21.3.1 and lost connectivity between all pods with linkerd injected.  In order to restore connectivity, I removed linkerd from the cluster and respun all of the pods.  I did use `--ignore-cluster`.

### What is the issue?
Upgrading to a new version of linkerd should not cause loss of connectivity

### How can it be reproduced?
1. Install stable-2.9.4 by using version 2.9.4 of `linkerd install | kubectl apply -f -` to generate and apply the Kubernetes manifest
2. Launch pods with injected linkerd
3. Install edge-21.3.1 with version edge-21.3.1 of `linkerd install --ignore-cluster | kubectl apply -f -`

### Logs, error output, etc
None were collected

#### `linkerd check` output

```
~|⇒ (⎈ |takeout:monitoring) linkerd check                                                                                                                                        [270ms] [2021/03/09|00:16]
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
× 'linkerd-config' config map exists
    failed to load linkerd-config
    see https://linkerd.io/checks/#l5d-existence-linkerd-config for hints

Status check results are ×
```

### Environment

- Kubernetes Version: v1.19.7
- Cluster Environment: (GKE, AKS, kops, ...): baremetal, provisioned with kubeadm
- Host OS: Ubuntu 20.04.1 LTS
- Linkerd version:
   Client version: stable-2.9.4
   Server version: stable-2.9.4

### Possible solution
Perhaps `--ignore-cluster` should not have been used.

### Additional context
Opened from https://github.com/linkerd/linkerd2/issues/5865

**Comment by kleimkuhler** [comment]
Thanks for opening a separate issue @tyzbit. You'll want to use the `upgrade` command when upgrading the linkerd installation on your cluster. This should solve the issue you're seeing.

For upgrading to the latest edge you'll want to do the following:

```
# Upgrade the control plane
linkerd upgrade | kubectl apply --prune -l linkerd.io/control-plane-ns=linkerd -f -
# Prune cluster-scoped resources
linkerd upgrade | kubectl apply --prune -l linkerd.io/control-plane-ns=linkerd \
  --prune-whitelist=rbac.authorization.k8s.io/v1/clusterrole \
  --prune-whitelist=rbac.authorization.k8s.io/v1/clusterrolebinding \
  --prune-whitelist=apiregistration.k8s.io/v1/apiservice -f -
```

The edge releases have removed certain default components from the core installation such as Prometheus and Grafana. To install those and be able to run commands such as `linkerd stat` and `linkerd dashboard`, you'll want to install the Viz extension:

```
# Install the Linkerd-Viz extension to restore viz functionality.
linkerd viz install | kubectl apply -f -
```

**Comment by kleimkuhler** [comment]
@tyzbit I'm closing this for now but let us know if you run into the same issues when using the `upgrade` command!
