### ISSUE TITLE
version 2.10.0 is not backwards compatible

### ISSUE THREAD

**Issue by kevjin** [linkerd/linkerd2#5892]
## Bug Report

minor versions should be backwards compatible, but version 2.10.0 broke our terraform config.

### What is the issue?
the chart field `global.identityTrustAnchorsPEM` has been updated to just `identityTrustAnchorsPEM` and it results in the following error when trying to set up linkerd:

```
Error: execution error at (linkerd2/templates/sp-validator.yaml:129:12): Please provide the identity trust anchors
```

### How can it be reproduced?

try to use the chart field `global.identityTrustAnchorsPEM` instead of `identityTrustAnchorsPEM`

**Comment by adleong** [comment]
Hi @kevjin!  Linkerd2 does not strictly follow semver.  To the degree that it does, the second number should be considered the major version.  Thus 2.9.0 to 2.10.0 should be considered a major version upgrade.

The specific backwards incompatible changes and instructions for safely upgrading are documented here: https://linkerd.io/2.10/tasks/upgrade/#upgrade-notice-stable-2-10-0
