### ISSUE TITLE
idea: `linkerd check --short`

### ISSUE THREAD

**Issue by wmorgan** [linkerd/linkerd2#5909]
We often ask people to give us the output of `linkerd check` while helping them figure out an issue they're having with Linkerd. The full output of this command is very verbose. Add a `--short` flag that just gives the overall status plus the error(s) encountered, in a compact format that can be pasted into e.g. Slack.

Maybe embed the CLI and CP versions in the output as well.

**Comment by yashvardhan-kukreja** [comment]
Hi @wmorgan , I'd like to pick this issue up :)

**Comment by wmorgan** [comment]
@yashvardhan-kukreja fine by me, but I'd wait to see whether one of the maintainers thinks this is a good idea first. 😅

**Comment by yashvardhan-kukreja** [comment]
> @yashvardhan-kukreja fine by me, but I'd wait to see whether one of the maintainers thinks this is a good idea first. 😅

Sure :)

**Comment by olix0r** [comment]
I think ideally a `--short` (or something) CLI output would _only_ include warnings/errors and a final summary line displaying the number of OK/WARN/ERROR checks.

@yashvardhan-kukreja We'd love help here :D

**Comment by dadjeibaah** [comment]
Fixed by #6038
