### ISSUE TITLE
Linkerd Init:ImagePullBackOff  issue

### ISSUE THREAD

**Issue by prydeep** [linkerd/linkerd2#5914]
I am trying to deploy linkerd on AKS cluster and control plane pods are throwing Init:ImagePullBackOff  

linkerd-controller-6d597b5648-8t8wk       0/2     Init:ImagePullBackOff   0          106m
linkerd-destination-7cfcd9469d-9rvd8      0/2     Init:ImagePullBackOff   0          106m
linkerd-heartbeat-1615975500-msslg        0/1     ImagePullBackOff        0          97m
linkerd-identity-54dd6d54dd-vbgdm         0/2     Init:ImagePullBackOff   0          106m
linkerd-proxy-injector-6948bf98cd-qn2jg   0/2     Init:ImagePullBackOff   0          106m
linkerd-sp-validator-67bccf8448-cq6qk     0/2     Init:ImagePullBackOff   0          105m

linked version stable-2.10.0

Can anyone help?

**Comment by alpeb** [comment]
Can you check the events on those pods to double check the right image+tag is getting pulled?

**Comment by prydeep** [comment]
Thank you alpeb.

Events:
  Type     Reason   Age                      From     Message
  ----     ------   ----                     ----     -------
  Normal   Pulling  49m (x39 over 3h44m)     kubelet  Pulling image "cr.l5d.io/linkerd/proxy-init:v1.3.9"
  Normal   BackOff  9m19s (x949 over 3h44m)  kubelet  Back-off pulling image "cr.l5d.io/linkerd/proxy-init:v1.3.9"
  Warning  Failed   4m33s (x970 over 3h44m)  kubelet  Error: ImagePullBackOff

**Comment by alpeb** [comment]
Would it be possible for you to run something like `dig cr.l5d.io` in your cluster to see if that domain is being properly resolved?

**Comment by prydeep** [comment]
bash-5.0# dig cr.l5d.io

; <<>> DiG 9.16.6 <<>> cr.l5d.io
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 39185
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;cr.l5d.io.			IN	A

;; ANSWER SECTION:
cr.l5d.io.		30	IN	CNAME	linkerd.docker.scarf.sh.
linkerd.docker.scarf.sh. 30	IN	CNAME	a36404dad14aa491dbe069f66b6a4046-0d60751c84101ad0.elb.us-west-2.amazonaws.com.
a36404dad14aa491dbe069f66b6a4046-0d60751c84101ad0.elb.us-west-2.amazonaws.com. 30 IN A 44.233.125.190
a36404dad14aa491dbe069f66b6a4046-0d60751c84101ad0.elb.us-west-2.amazonaws.com. 30 IN A 35.155.47.48

;; Query time: 44 msec
;; SERVER: 10.0.32.10#53(10.0.32.10)
;; WHEN: Wed Mar 17 14:20:48 UTC 2021
;; MSG SIZE  rcvd: 384

**Comment by alpeb** [comment]
Still having issues? Sounds like something particular to your cluster given we haven't had similar reports. Any way to access cluster logs (docker's in particular)? Or perhaps you can also check general events in the cluster that might surface things like disk pressure or docker GC failing, etc.

**Comment by prydeep** [comment]
Tried to pull images and push them to ACR repo, linkerd namespace I am able to resolve but linkerd-viz I am still seeing issues
for example web pod in linkerd-viz has events
Warning  Failed   12m (x1451 over 5h42m)    kubelet  Error: ImagePullBackOff
  Normal   BackOff  2m43s (x1493 over 5h42m)  kubelet  Back-off pulling image "cr.l5d.io/linkerd/proxy-init:v1.3.9"

I have already pulled the images and pushed to our local ACR, I am not sure from where it is trying to pull image cr.l5d.io/linkerd/proxy-init:v1.3.9

**Comment by prydeep** [comment]
Hi alpeb,

Is linkerd-viz compulsory, my main usecase is to use only mTLS?

**Comment by prydeep** [comment]
I pushed images to our ACR but when I inject, I still see it pointing to linkerd repo, any changes that I should do particularly?

**Comment by kleimkuhler** [comment]
> Is linkerd-viz compulsory, my main usecase is to use only mTLS?

No the viz extension only provides only metrics and visibility features; the core install is responsible for mTLS.

> I pushed images to our ACR but when I inject, I still see it pointing to linkerd repo, any changes that I should do particularly?

The `inject` command provides a `--registry` flag that you may find useful for changing the registry it is pulled from. Additionally, on install I think you should be able to use the `--set proxy.image.name="..."` flag to set your proxy registry for all injected apps. If you look at `values.yaml` you'll see that configurable field.

**Comment by prydeep** [comment]
Thank you Kevin, will try this and will get back to you if I see any issues

**Comment by prydeep** [comment]
Kevin, can we also pass imagepullsecret while injecting using --registry flag?

**Comment by prydeep** [comment]
Can I also deploy viz using --registry flag? I pushed viz images too to ACR but still I am seeing image pull back (pointing to linkerd registry images)

**Comment by kleimkuhler** [comment]
@prydeep Yes similar to the `--set` flag above, you'll want to do the same here for the viz extension: `linkerd viz install --set defaultRegistry="..."`. Does that help out?

**Comment by prydeep** [comment]
@kleimkuhler I tried that but still seeing Failed to pull image "cr.l5d.io/linkerd/proxy-init:v1.3.9": rpc error: code = Unknown desc = Error response from daemon: Get https://cr.l5d.io/v2/: proxyconnect tcp: dial tcp: lookup proxy.conexus.svc.local: Temporary failure in name resolution

**Comment by prydeep** [comment]
I have given command like this

linkerd viz install --set proxy.image.name="xxxx.azurecr.io/proxy-init:v1.3.9" --set defaultRegistry="xxxx.azurecr.io"| kubectl apply -f -

**Comment by kleimkuhler** [comment]
@prydeep These should be separate commands. Installing the viz extension is separate from the core installation. Additionally, if all the images are in your own registry, you'll need to set those accordingly. I'd encourage you to take a look at the [values.yaml](https://github.com/linkerd/linkerd2/blob/main/charts/linkerd2/values.yaml) to see where I'm getting these from.

So for your case I would expect the following to work:

```
# install core linkerd with a custom proxy registry
$ linkerd install --set proxyInit.image.name="...",proxy.image.name="...",controllerImage="..." |kubectl apply -f -

# install the viz extension with a custom registry
$ linkerd viz install --set defaultRegistry="xxxx.azurecr.io" |kubectl apply -f -
```

Also I see you have `proxy.image.name="xxxx.azurecr.io/proxy-init:v1.3.9"`. `proxy.image.name` is for the proxy, not the proxyInit image—they are separate from each other. I'd make sure in your own registry you have the required images.

**Comment by prydeep** [comment]
Thank You @kleimkuhler, checking this

**Comment by prydeep** [comment]
@kleimkuhler I was able to fix this thank you, one question do I need to inject linkerd to Ingress Controller too?
 I have added annotation to my ingress though, but I am not sure if I have to add to my ingress controller too.

**Comment by kleimkuhler** [comment]
In order to get mTLS and additional service mesh features from the ingress it will be need to be injected. There are some [docs](https://linkerd.io/2.10/tasks/using-ingress/) explaining if you'd like to annotate with `linkerd.io/inject: enabled` or `ingress`.
