### ISSUE TITLE
Error calling Prometheus from the control plane: server_error: server error: 503:linkerd-viz

### ISSUE THREAD

**Issue by praveenpattisapu** [linkerd/linkerd2#5947]
## Bug Report
Cannot connect to Linkerd Viz: Error calling Prometheus from the control plane: server_error: server error: 503
Validate the install with: linkerd viz check

### What is the issue?
We recently upgraded to linkerd2.10.1 as we have some DNS issues with stable 2.9.2, when ever we execute the below command,
linkerd2 viz stat deploy -n dev-nsj, getting the below error and the only way to resolve this is by restarting the promethues application in linkerd-viz name space.

Cannot connect to Linkerd Viz: Error calling Prometheus from the control plane: server_error: server error: 503
Validate the install with: linkerd viz check

### How can it be reproduced?
Very easy and this is a constant issue

### Logs, error output, etc
Cannot connect to Linkerd Viz: Error calling Prometheus from the control plane: server_error: server error: 503
Validate the install with: linkerd viz check

Prometheus logs from linkerd-viz name space:

```
021-03-24T09:31:27.258630089Z level=error ts=2021-03-24T09:31:27.258Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:385: Failed to list *v1.Pod: Get \"https://192.168.0.1:443/api/v1/pods?limit=500&resourceVersion=0\": dial tcp 192.168.0.1:443: connect: connection refused"
2021-03-24T09:31:27.258941989Z level=error ts=2021-03-24T09:31:27.258Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:385: Failed to list *v1.Pod: Get \"https://192.168.0.1:443/api/v1/namespaces/linkerd-viz/pods?limit=500&resourceVersion=0\": dial tcp 192.168.0.1:443: connect: connection refused"
2021-03-24T09:31:27.259097389Z level=error ts=2021-03-24T09:31:27.259Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:385: Failed to list *v1.Pod: Get \"https://192.168.0.1:443/api/v1/namespaces/linkerd/pods?limit=500&resourceVersion=0\": dial tcp 192.168.0.1:443: connect: connection refused"
2021-03-24T09:31:27.259247290Z level=error ts=2021-03-24T09:31:27.259Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:449: Failed to list *v1.Node: Get \"https://192.168.0.1:443/api/v1/nodes?limit=500&resourceVersion=0\": dial tcp 192.168.0.1:443: connect: connection refused"
2021-03-24T09:31:27.265899792Z level=error ts=2021-03-24T09:31:27.265Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:385: Failed to list *v1.Pod: Get \"https://192.168.0.1:443/api/v1/namespaces/linkerd-viz/pods?limit=500&resourceVersion=0\": dial tcp 192.168.0.1:443: connect: connection refused"
```

#### `linkerd check` output

It is successful:
Status check results are √
```

### Environment

- Kubernetes Version:1.16.15
- Cluster Environment: (GKE, AKS, kops, ...)AKS
- Host OS:Linux
- Linkerd version:2.10.0

### Possible solution
Dont know

### Additional context

**Comment by adleong** [comment]
Hi @praveenpattisapu, linkerd 2.10.1 has not been released, did you mean 2.10.0?

Looking at the logs, it appears that Prometheus is trying to connect to the Kubernetes API at `192.168.0.1` which seems pretty weird.  I'm not sure why it would do that.  Can you provide specific steps for reproducing this?  e.g. exactly which commands to run at which versions to get into this state?

**Comment by praveenpattisapu** [comment]
@adleong yes, the version is 2.10.0.
yes it is very easy to replicate the issue as this issue is happening almost everyday and all i have to do is restart the prometheus pod and that will establish the connection again to dashboard etc but we cannot go live "as is" until this issue is fixed.

How to Re-Produce:

1.Install a K8 Cluster in AKS
2.Deploy some applications
3.Install latest stable linkerd version using helm
4.Install Linkerd-Viz extension as well using helm
5.Make sure all applications are injected with linkerd
6.Connect to AKS cluster and install linkerd-cli on your laptop.
7.execute the below command,
linkerd viz stat deploy -n <namespace>

initially it will show but after some time, when you execute the same command, you will get the below error

Cannot connect to Linkerd Viz: Error calling Prometheus from the control plane: server_error: server error: 503
Validate the install with: linkerd viz check

Please let me know if you need any info, happy to join a meeting and share my screen if that's helpful

**Comment by akowald** [comment]
I am getting a similar error just trying to complete the [Getting Started](https://linkerd.io/2.10/getting-started/) tutorial. The `linkerd check` after `linkerd viz install | kubectl apply -f -` just stalls out with the same error `Error calling Prometheus from the control plane: server_error: server error: 503`. Same logs from Prometheus as the OP. I did notice the linkerd-heartbeat pod failing over and over:

```
time="2021-03-26T18:05:36Z" level=error msg="Prometheus query failed: Post \"http://prometheus.linkerd-viz.svc.cluster.local:9090/api/v1/query\": dial tcp 104.196.0.225:9090: i/o timeout"
time="2021-03-26T18:06:06Z" level=error msg="Prometheus query failed: Post \"http://prometheus.linkerd-viz.svc.cluster.local:9090/api/v1/query\": dial tcp 104.196.0.225:9090: i/o timeout"
time="2021-03-26T18:06:06Z" level=info msg="Sending heartbeat: https://versioncheck.linkerd.io/version.json?ext-viz=1&install-time=1616781119&k8s-version=v1.20.2&service-profile-count=0&source=heartbeat&uuid=7a1ec34f-e1f0-4697-b062-7b7cd4fc43c9&version=stable-2.10.0"
time="2021-03-26T18:06:06Z" level=fatal msg="Failed to send heartbeat: Check URL [https://versioncheck.linkerd.io/version.json?ext-viz=1&install-time=1616781119&k8s-version=v1.20.2&service-profile-count=0&source=heartbeat&uuid=7a1ec34f-e1f0-4697-b062-7b7cd4fc43c9&version=stable-2.10.0] request failed with: Get \"https://versioncheck.linkerd.io/version.json?ext-viz=1&install-time=1616781119&k8s-version=v1.20.2&service-profile-count=0&source=heartbeat&uuid=7a1ec34f-e1f0-4697-b062-7b7cd4fc43c9&version=stable-2.10.0\": x509: certificate is valid for *.wpengine.com, wpengine.com, not versioncheck.linkerd.io"

# prometheus pod
level=error ts=2021-03-26T17:55:49.676Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:385: Failed to list *v1.Pod: Get \"https://10.96.0.1:443/api/v1/pods?limit=500&resourceVersion=0\": dial tcp 10.96.0.1:443: connect: connection refused"
level=error ts=2021-03-26T17:55:49.676Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:385: Failed to list *v1.Pod: Get \"https://10.96.0.1:443/api/v1/namespaces/linkerd-viz/pods?limit=500&resourceVersion=0\": dial tcp 10.96.0.1:443: connect: connection refused"
level=error ts=2021-03-26T17:55:49.676Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:449: Failed to list *v1.Node: Get \"https://10.96.0.1:443/api/v1/nodes?limit=500&resourceVersion=0\": dial tcp 10.96.0.1:443: connect: connection refused"
level=error ts=2021-03-26T17:55:49.676Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:385: Failed to list *v1.Pod: Get \"https://10.96.0.1:443/api/v1/namespaces/linkerd/pods?limit=500&resourceVersion=0\": dial tcp 10.96.0.1:443: connect: connection refused"
level=error ts=2021-03-26T17:55:49.676Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:385: Failed to list *v1.Pod: Get \"https://10.96.0.1:443/api/v1/namespaces/linkerd-viz/pods?limit=500&resourceVersion=0\": dial tcp 10.96.0.1:443: connect: connection refused"
```

I've tried using kubectl on a kind and minikube cluster so far, same result. Using Ubuntu 20.04.2, docker 20.10.5, linkerd 2.10.0, kubectl v1.20.5.

**Comment by dadjeibaah** [comment]
@praveenpattisapu are you able to determine how long it takes for the Prometheus pod to get into this state on a fresh install? It looks like Prometheus isn't able to reach the K8s API. Are you able to manually exec into a different pod and try reaching the K8s API on that same IP?

**Comment by praveenpattisapu** [comment]
@dadjeibaah it takes 20 mins for the promotheus pod to come into this state and i am now testing the connectivity from the pod to k8 API server

**Comment by praveenpattisapu** [comment]
@dadjeibaah yes, i am able to curl to k8 api server from a diff pod, do we need a network policy in place as they are in 2 different name spaces?

**Comment by praveenpattisapu** [comment]
C:\Users\praveen>linkerd21 viz stat deploy -n dev-nsj --verbose
time="2021-04-06T14:40:53+01:00" level=debug msg="Starting port forward to https://aks-xxx-xxxxxx.northeurope.azmk8s.io:443/api/v1/namespaces/linkerd-viz/pods/metrics-api-75dfd8c75-vc7mb/portforward?timeout=30s 51750:8085"
time="2021-04-06T14:40:53+01:00" level=debug msg="Port forward initialised"
time="2021-04-06T14:40:53+01:00" level=debug msg="Expecting API to be served over [http://localhost:51750/api/v1/]"
time="2021-04-06T14:40:53+01:00" level=debug msg="Making gRPC-over-HTTP call to [http://localhost:51750/api/v1/SelfCheck] []"
time="2021-04-06T14:40:57+01:00" level=debug msg="Response from [http://localhost:51750/api/v1/SelfCheck] had headers: map[Content-Length:[189] Content-Type:[application/octet-stream] Date:[Tue, 06 Apr 2021 13:40:57 GMT]]"
time="2021-04-06T14:40:57+01:00" level=debug msg="gRPC-over-HTTP call returned status [200 OK] and content length [189]"
Cannot connect to Linkerd Viz: Error calling Prometheus from the control plane: server_error: server error: 503
Validate the install with: linkerd viz check

**Comment by praveenpattisapu** [comment]
PS C:\Users\> curl http://localhost:49470/api/v1/SelfCheck

 StatusCode        : 200
StatusDescription : OK
Content           : {15, 0, 0, 0...}
RawContent        : HTTP/1.1 200 OK
                    Linkerd-Error: Internal Server Error
                    Content-Length: 19
                    Content-Type: application/octet-stream
                    Date: Tue, 06 Apr 2021 13:21:58 GMT

 

                    ....
                    POST required
Headers           : {[Linkerd-Error, Internal Server Error], [Content-Length, 19], [Content-Type,
                    application/octet-stream], [Date, Tue, 06 Apr 2021 13:21:58 GMT]}
RawContentLength  : 19

**Comment by praveenpattisapu** [comment]
After restarting the prometheus pod, it all works and this is the result again,pls see the diff when it works and when it does'nt

C:\Users\praveen.pattisapu>linkerd21 viz stat deploy -n dev-nsj --verbose
time="2021-04-06T16:21:05+01:00" level=debug msg="Starting port forward to https://aks-xxx-xxxxxx.azmk8s.io:443/api/v1/namespaces/linkerd-viz/pods/metrics-api-75dfd8c75-vc7mb/portforward?timeout=30s 54624:8085"
time="2021-04-06T16:21:05+01:00" level=debug msg="Port forward initialised"
time="2021-04-06T16:21:05+01:00" level=debug msg="Expecting API to be served over [http://localhost:54624/api/v1/]"
time="2021-04-06T16:21:05+01:00" level=debug msg="Making gRPC-over-HTTP call to [http://localhost:54624/api/v1/SelfCheck] []"
time="2021-04-06T16:21:11+01:00" level=debug msg="Response from [http://localhost:54624/api/v1/SelfCheck] had headers: map[Content-Length:[104] Content-Type:[application/octet-stream] Date:[Tue, 06 Apr 2021 15:21:11 GMT]]"
time="2021-04-06T16:21:11+01:00" level=debug msg="gRPC-over-HTTP call returned status [200 OK] and content length [104]"
time="2021-04-06T16:21:11+01:00" level=debug msg="Making gRPC-over-HTTP call to [http://localhost:54624/api/v1/StatSummary] [selector:{resource:{namespace:\"dev-nsj\"  type:\"deployment\"}}  time_window:\"1m\"  tcp_stats:true]"
time="2021-04-06T16:21:13+01:00" level=debug msg="Response from [http://localhost:54624/api/v1/StatSummary] had headers: map[Content-Type:[application/octet-stream] Date:[Tue, 06 Apr 2021 15:21:13 GMT]]"
time="2021-04-06T16:21:13+01:00" level=debug msg="gRPC-over-HTTP call returned status [200 OK] and content length [-1]"
NAME                               MESHED   SUCCESS      RPS   LATENCY_P50   LATENCY_P95   LATENCY_P99   TCP_CONN
api-mocks-dev-nsj                     1/1   100.00%   1.2rps           1ms           1ms           8ms          3
ms-address-api-dev-nsj                2/2         -        -             -             -             -          -
ms-appointment-api-dev-nsj            1/2   100.00%   0.9rps           1ms           2ms          17ms          3
ms-content-api-dev-nsj                2/2         -        -             -             -             -          -
ms-credit-check-api-dev-nsj           1/2         -        -             -             -             -          -
ms-customer-api-dev-nsj               1/2         -        -             -             -             -          -

**Comment by shousper** [comment]
Same issue here today on v2.10.2 in an EKS cluster (v1.18.9-eks-d1db3c). Restarting the `prometheus` pod caused `linkerd viz check` to start passing, but the same 4 errors are still reported on startup:

```
prometheus-6d8cc8b7b9-mxr5s prometheus level=error ts=2021-05-20T04:52:18.623Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:385: Failed to list *v1.Pod: Get \"https://172.20.0.1:443/api/v1/namespaces/linkerd-viz/pods?limit=500&resourceVersion=0\": dial tcp 172.20.0.1:443: connect: connection refused"
prometheus-6d8cc8b7b9-mxr5s prometheus level=error ts=2021-05-20T04:52:18.623Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:385: Failed to list *v1.Pod: Get \"https://172.20.0.1:443/api/v1/pods?limit=500&resourceVersion=0\": dial tcp 172.20.0.1:443: connect: connection refused"
prometheus-6d8cc8b7b9-mxr5s prometheus level=error ts=2021-05-20T04:52:18.623Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:449: Failed to list *v1.Node: Get \"https://172.20.0.1:443/api/v1/nodes?limit=500&resourceVersion=0\": dial tcp 172.20.0.1:443: connect: connection refused"
prometheus-6d8cc8b7b9-mxr5s prometheus level=error ts=2021-05-20T04:52:18.623Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:385: Failed to list *v1.Pod: Get \"https://172.20.0.1:443/api/v1/namespaces/linkerd/pods?limit=500&resourceVersion=0\": dial tcp 172.20.0.1:443: connect: connection refused"
```

The log output otherwise appears identical to the previous broken pod.

**Comment by olix0r** [comment]
Is it possible that your clusters have some sort of `NetworkPolicy` enabled that is preventing these connections?

**Comment by shousper** [comment]
@olix0r Checked that this morning, can confirm I have no `NetworkPolicy` resources.

**Comment by worldwideward** [comment]
Followed the getting started guide today using Minikube and ran into the exact same issue. Fresh cluster, no network policies.
