### ISSUE TITLE
Linkerd 2.10 and Traefik ingress requires setting port 8443 as opaque 

### ISSUE THREAD

**Issue by rio** [linkerd/linkerd2#5948]
A while ago I made this PR https://github.com/linkerd/website/pull/995 documenting a case where when traefik's default helm chart is used along with linkerd 2.10 the websecure port 8443 should be added to the opaque ports otherwise timeout's will occur. I find this a bit confusing because I was under the impression that client initiated TLS would just work, but if that was the case why is port 443 still added to the default opaque ports?

Eithe rway in the PR it was noted that it should be solved in edge-21.3.3 which I didn't find to be the case. So to reproduce this locally I've made a script. It will basically start k3d or kind and install linkerd, traefik and emojivoto. Then executes a curl request that will fail because of the missing opaque port. It will add the annotation an reexecute the test which will then pass. It can be run with other linkerd binaries by setting `LINKERD_CLI` at the top of the script.

I hope we can figure this out.

```bash
set -euxo pipefail

# Set the linkerd binary to use.
LINKERD_CLI=linkerd

# create the local k8s cluster. Either k3d or kind can be used.
# k3d cluster create --k3s-server-arg "--disable=servicelb,traefik"
kind create cluster

# install linkerd and wait for it to report ready
$LINKERD_CLI install | kubectl apply -f -
$LINKERD_CLI check

# install traefik
helm install traefik traefik \
	--create-namespace \
	--namespace=traefik-system \
	--repo=https://helm.traefik.io/traefik \
        --wait \
	--set=deployment.podAnnotations."linkerd\.io/inject=enabled" \
        --set=service.type=NodePort

# install emojivoto
curl -sL https://run.linkerd.io/emojivoto.yml | $LINKERD_CLI inject - | kubectl apply -f -

# create an ingress for the web-svc with tls enabled through traefik
kubectl --namespace emojivoto apply -f - <<EOF
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web
  namespace: emojivoto
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web-svc
            port:
              number: 80
EOF

# wait for all pods to report ready. Timeout is for 10 minutes for slower connections
kubectl wait --for=condition=Ready --all pods --all-namespaces --timeout 10m

# fetch both the first node's ip address and the node port on which TLS is being served
NODE_ADDRESS=$(kubectl get nodes -o jsonpath='{.items[0].status.addresses[0].address}')
HTTPS_PORT=$(kubectl --namespace traefik-system get svc traefik -o jsonpath='{.spec.ports[?(@.name == "websecure")].nodePort}')

# sleep a bit to give k8s and traefik a chance to process the ingress
sleep 2

# use the address and port to test if it get's routed to web-svc. This will time out after 15 seconds.
curl -vk --max-time 15 https://${NODE_ADDRESS}:${HTTPS_PORT} || true

# patch the traefik deployment to set port 8443 as an opaque port.
kubectl patch --namespace traefik-system deployments.apps traefik --patch '{"spec": {"template": {"metadata": {"annotations": {"config.linkerd.io/opaque-ports":"8443"}}}}}'

# wait for the rollout to complete
kubectl --namespace traefik-system rollout status deployment traefik

# sleep a bit to give k8s a chance to switch endpoints
sleep 2

# this time it will work.
curl -vk --max-time 15 https://${NODE_ADDRESS}:${HTTPS_PORT}
```

**Comment by alpeb** [comment]
Thanks a lot @rio for the effort on creating a reproducible case :+1: 

Port 443 would still work if it wasn't marked as an opaque port, but in that case we're certain that the outcome is for the proxy to just let through those connections, so we just mark it as opaque by default. The same case could be made for port 8443, but I don't know how "official" that port is to be for TLS.

I will give a try at your script in a moment, but the first thing I realize is the ingress resource is lacking the `ingress.kubernetes.io/custom-request-headers` annotation, which could explain why it doesn't work without marking the port as opaque.

**Comment by alpeb** [comment]
For the life of me, I couldn't make this work again with the latest edge :man_shrugging: 

@ver would you mind taking a look? To summarize, I'm trying to have an injected Traefik ingress receive TLS connections in its port 8443, without having to set that port to opaque.
I've modified the script above in [this gist](https://gist.github.com/alpeb/08ef54ce1e8b240cc7fdeae03659b716) with these changes:
- fixed the k3d command
- enabled TLS in Traefik
- added the `ingress.kubernetes.io/custom-request-headers` annotation to the ingress resource
- used curl with `--resource` to force SNI

With that, the curl request hangs at `Client Hello`:
```console
$ curl -vk --max-time 15 --resolve example.com:30974:192.168.48.2 https://example.com:30974
* Added example.com:30974:192.168.48.2 to DNS cache
* Hostname example.com was found in DNS cache
*   Trying 192.168.48.2:30974...
* TCP_NODELAY set
* Connected to example.com (192.168.48.2) port 30974 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* Operation timed out after 15001 milliseconds with 0 out of 0 bytes received
* Closing connection 0
curl: (28) Operation timed out after 15001 milliseconds with 0 out of 0 bytes received
```

with the ingress proxy logging a timeout:
```console
INFO ThreadId(01) server{port=8443}: linkerd_detect: Continuing after timeout: linkerd_proxy_http::version::Version protocol detection timed out after 10s
```
grepping 8443 in the logs with tracing, we get this:
```console
[    77.083926s] DEBUG ThreadId(01) inbound:accept{client.addr=10.42.0.1:43171}:server{port=8443}:proxy: linkerd_tls::server: Peeked bytes from TCP stream sz=512
[    77.083963s] TRACE ThreadId(01) inbound:accept{client.addr=10.42.0.1:43171}:server{port=8443}:proxy: linkerd_tls::server::client_hello: parse_sni: needs more input
[    77.083974s] DEBUG ThreadId(01) inbound:accept{client.addr=10.42.0.1:43171}:server{port=8443}:proxy: linkerd_tls::server: Attempting to buffer TLS ClientHello after incomplete peek
[    77.083980s] DEBUG ThreadId(01) inbound:accept{client.addr=10.42.0.1:43171}:server{port=8443}:proxy: linkerd_tls::server: Reading bytes from TCP stream buf.capacity=8192
[    77.083991s] DEBUG ThreadId(01) inbound:accept{client.addr=10.42.0.1:43171}:server{port=8443}:proxy: linkerd_tls::server: Read bytes from TCP stream buf.len=517
[    77.083998s] TRACE ThreadId(01) inbound:accept{client.addr=10.42.0.1:43171}:server{port=8443}:proxy: linkerd_tls::server::client_hello: parse_sni: parsed correctly up to SNI sni=Some(ServerId("example.com"))
[    77.084008s] TRACE ThreadId(01) inbound:accept{client.addr=10.42.0.1:43171}:server{port=8443}:proxy: linkerd_tls::server: Identified non-matching SNI via peek sni=example.com
[    77.084023s] DEBUG ThreadId(01) inbound:accept{client.addr=10.42.0.1:43171}:server{port=8443}:proxy: linkerd_app_inbound::require_identity: port=8443 tls=Some(Passthru { sni: ServerId("example.com") }) id_required=false
[    77.084046s] TRACE ThreadId(01) inbound:accept{client.addr=10.42.0.1:43171}:server{port=8443}:proxy: linkerd_detect: Starting protocol detection
[    77.084056s] TRACE ThreadId(01) inbound:accept{client.addr=10.42.0.1:43171}:server{port=8443}:proxy: linkerd_proxy_http::detect: Reading capacity=1024
```
```

**Comment by alpeb** [comment]
I did try using  `Middleware` and `IngressRoute` as detailed in the [docs](https://linkerd.io/2.10/tasks/using-ingress/#traefik) with exactly the same results unfortunately.

**Comment by olix0r** [comment]
@rio thank you for the detailed repro! This made this issue much easier to track down.

I've got a fix up here https://github.com/linkerd/linkerd2-proxy/pull/958 that we'll include in next week's edge release as well as the upcoming stable-2.10.1 release.

If you'd like to confirm this in the meantime, I've published a proxy image with the fix that can be used by setting the annotations:
```
        config.linkerd.io/proxy-image: ghcr.io/olix0r/l2-proxy
        config.linkerd.io/proxy-version: tls-detect.2a698b9a
```

**Comment by rio** [comment]
@olix0r, Yes I can confirm it for the test setup I've made! I love (almost) one-line fixes ;) To test it on the system I originally encountered it I'd have to rebuild the image for arm64. I'll probably not be able to do that this weekend. Thanks for the fix though!

**Comment by olix0r** [comment]
I've built `ghcr.io/olix0r/l2-proxy:tls-detect.dd75b4c5` for multiarch (amd64 and arm64) in case that helps. But I agree we should keep this open until we've got the fix more generally available.

**Comment by rio** [comment]
Thanks, this one works. Looking forward to the next point release.

**Comment by rio** [comment]
Just verified 2.10.1 works for my installation. Thanks for the fix! Closing.
