### ISSUE TITLE
Support Multi-Cluster Routing for North/South communication.

### ISSUE THREAD

**Issue by hanoisteve** [linkerd/linkerd2#5965]
## Feature Request
Allow routing across multiple clusters.

### What problem are you trying to solve?
Currently an Ingress only supports routing within a single cluster.  But with multi-cluster it will be useful to route across the clusters.

### How should the problem be solved?

What do you want to happen? Add any considered drawbacks.
Support routing across clusters for north/south traffic.

### Any alternatives you've considered?

Is there another way to solve this problem that isn't as good a solution?
This could be moved into a load balancer but its really an L7 type load balancing so that's not optimal.

Its possible Kubernetes will have a gateway to support this feature at some point but I don't any details or know if its on the roadmap..

### How would users interact with this feature?

If you can, explain how users will be able to use this. Maybe some sample CLI
output?
Ideally they could configure routes as standard Kubernetes resources and these routes could go to any cluster within the multi-cluster setup.

**Comment by adleong** [comment]
Hi @hanoisteve.  In order for this to be actionable, you'll need to provide a lot more details about exactly the behavior that you're looking for and how you would like it to work.

Notably, Linkerd does not include an ingress controller: https://linkerd.io/2.10/features/ingress/

One potential solution would be to configure your ingress to route to a mirror service created by Linkerd's multicluster extension: https://linkerd.io/2.10/features/multicluster/  Have you investigated this?

**Comment by hanoisteve** [comment]
Well I think its good that Linkerd does not provide a separate Ingress controller as the inbuilt one is quite stable and we like to use it where possible.   I will look into service mirroring.  where could I find out more about the gateway component? I want to know what it can do out of the box and also how it can be customized.

**Comment by adleong** [comment]
Reading through the multicluster guide: https://linkerd.io/2.10/tasks/multicluster/ and the multicluster helm chart: https://github.com/linkerd/linkerd2/tree/main/multicluster/charts/linkerd-multicluster are probably the best places to start.  If you have further questions, don't hesitate to ask in the Linkerd slack!
