### ISSUE TITLE
external prometheus gets "certificate signed by unknown authority" error

### ISSUE THREAD

**Issue by danoshi** [linkerd/linkerd2#5966]
### What is the issue?
Hi we are using linkerd version stable-2.9.2 and trying to use our own prometheus. We set the "prometheusUrl" parameter correctly but every time when we access the dashboard we get "https://prometheus......./api/v1/query\": x509: certificate signed by unknown authority"

Is there a way or parameter where we can tell the linkerd where the certificate are stored or should we import them into our repo? Any guideline how to do it would be appreciated. 
### How can it be reproduced?
Use the prometheusUrl parameter with an external prometheus over https. (using not per default trusted public certificate)

### Environment

- Kubernetes Version: 1.18
- Cluster Environment: aws eks
- Host OS:  amazon Linux 
- Linkerd version: 2.9.2

**Comment by danoshi** [comment]
Hello, 

unfortunately this does not solve our issue. We are using CA certificate on our external Prometheus that is signed by a private certificate authority. We would need the possibility to define our own cacerts or k8s certificate secret. It should be configurable like for other linkerd-viz components, and in the end we should be able to set it via the values file for helm

**Comment by adleong** [comment]
Ah, you're right that we don't have any mechanism to configure the CA certs that the viz extension uses to talk to an external prometheus.  If you need to provide your own CA certs, I think your best bet to create your own Docker image for the metrics-api container which adds your CA certificates in a layer on top of the base Docker image.  See https://github.com/linkerd/linkerd2/blob/main/viz/metrics-api/Dockerfile#L27 for an example of how we copy in the default CA certs.  You will then need to set the `metricsAPI.image` Helm value to point to your custom metrics-api image.

**Comment by danoshi** [comment]
That would mean we would have to maintain the metrics-api container and I don't know if this would be worth the effort.
Is there any plans from your side to give the possibility to define our own cacerts or k8s certificate secret?

**Comment by adleong** [comment]
@danoshi no current plans, but PRs welcome!
