### ISSUE TITLE
[Question] Link to roadmap

### ISSUE THREAD

**Issue by leecalcote** [linkerd/linkerd2#6009]
## Question

Is there a link to the roadmap? I've seen links to the Linkerd2 roadmap pointing to  https://github.com/linkerd/linkerd2/blob/main/ROADMAP.md. I also see the following in Linkerd's docs regarding roadmap:

> What's on the Linkerd roadmap?
> 
>   As a community project, there is no formal roadmap, but a glance at the active GitHub issues will give you a sense of what is in store for the future.

Will you confirm whether there is a published project roadmap outside of the list of active GitHub issues?

**Comment by wmorgan** [comment]
Thanks for pointing this out. https://github.com/linkerd/linkerd2/blob/main/ROADMAP.md now contains the roadmap. Update to that FAQ entry is up for review.

**Comment by leecalcote** [comment]
Thank you, sir.
