### ISSUE TITLE
helm install fails for linkerd-viz

### ISSUE THREAD

**Issue by openJT** [linkerd/linkerd2#6036]
### What is the issue?
helm install fails for linkerd-viz

### How can it be reproduced?
the linkerd-viz namespace does not exist prior to running this command

helm install linkerd-viz linkerd/linkerd-viz --namespace linkerd-viz --create-namespace
### Logs, error output, etc
Error: namespaces "linkerd-viz" already exists

 helm -n linkerd-viz status linkerd-viz     ->

NAME: linkerd-viz
LAST DEPLOYED: Thu Apr 15 14:28:03 2021
NAMESPACE: linkerd-viz
STATUS: failed
REVISION: 1
TEST SUITE: None
NOTES:
The Linkerd Viz extension was successfully installed 🎉

To make sure everything works as expected, run the following:

  linkerd viz check ->

linkerd-viz
-----------
× linkerd-viz Namespace exists
    could not find the viz extension
    see https://linkerd.io/checks/#l5d-viz-ns-exists for hints

Status check results are ×

To view the linkerd dashboard, run the following:

  linkerd viz dashboard

(did not install, hence thie issue)
Cannot connect to Linkerd Viz: could not find the viz extension
Validate the install with: linkerd viz check

(If the output is long, please create a [gist](https://gist.github.com/) and
paste the link here.)

#### `linkerd check` output

kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-identity
----------------
√ certificate config is valid
√ trust anchors are using supported crypto algorithm
√ trust anchors are within their validity period
√ trust anchors are valid for at least 60 days
√ issuer cert is using supported crypto algorithm
√ issuer cert is within its validity period
√ issuer cert is valid for at least 60 days
√ issuer cert is issued by the trust anchor

linkerd-webhooks-and-apisvc-tls
-------------------------------
√ proxy-injector webhook has valid cert
√ proxy-injector cert is valid for at least 60 days
√ sp-validator webhook has valid cert
√ sp-validator cert is valid for at least 60 days

linkerd-api
-----------
√ control plane pods are ready
√ can initialize the client
√ can query the control plane API

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ control plane is up-to-date
√ control plane and cli versions match

### Environment

- Kubernetes Version: 1.20.5
- Cluster Environment: AWS -> kubeadm
- Host OS: Ubuntu 20.04
- Linkerd version:
Client version: stable-2.10.1
Server version: stable-2.10.1

### Additional context

I am able to install it using the cli but I need to change enforcedHostRegexp

Had the same result with the stable and edge repo

**Comment by alpeb** [comment]
The recommended helm install procedure is to not use `--create-namespace` so that the namespace template included in the chart is used, given it contains required labels and annotations.
If needed, you can create the namespace beforehand, making sure it contains the required metadata (see the [tempate](https://github.com/linkerd/linkerd2/blob/main/viz/charts/linkerd-viz/templates/namespace.yaml)). And then install with helm setting `installNamespace=false`:
```
helm install linkerd-viz --namespace linkerd-viz --set installNamespace=false linkerd/linkerd-viz
```

**Comment by openJT** [comment]
Ok thanks, that helped. I had previously tried to install it without using the --create-namespace, but I was using the --namespace linkerd-viz flag, and I was getting a namespace  does not exist error, creating it manually before hand was also not working.  

I thought I tried helm install linkerd-viz linkerd/linkerd-viz but apparently I had not.

helm install linkerd-viz linkerd/linkerd-viz worked.

Thanks again, you can close the issue.
