### ISSUE TITLE
Allow specification of sidecar image for each Jaeger collector pod

### ISSUE THREAD

**Issue by SiegfredRodriguez** [linkerd/linkerd2#6040]
Allow specification of sidecar image for each Jaeger collector pod.

The problem is that it seems to be difficult to register a Jaeger collector pod to a service registry.

The common solution is to use the side car pattern, and use something like Spring Cloud Netflix Sidecar to do the registration in behalf of the collector.

Current usage in mind is:

linkerd jaeger install --set sidecar.image="mysidecar/spring-sc:latest"

But open to better approach.

**Comment by adleong** [comment]
Hi @SiegfredRodriguez!  I don't think I understand what problem you're solving here with a registration sidecar.  The collector is discoverable by a kubernetes service: `collector.linkerd-jaeger`.  Can you elaborate on why further registration is necessary?

**Comment by SiegfredRodriguez** [comment]
Hello @adleong,

I understand linkerd's jaeger collector can be discovered by kubernetes DNS, however i am thinking of the scenario where the service fleet is using client side load balancing services registries like Eureka, and Zookeeper. Though I honestly don't know if Kubernetes service load balancing would be enough for collector purposes.

**Comment by adleong** [comment]
It's unlikely that we'll support this for the Jaeger which is bundled in the Viz extension.  However, it is easy to run your own Jaeger collector with any configuration or sidecars that you like and have the Viz extension use that.  See the docs: https://linkerd.io/2.10/tasks/distributed-tracing/#bring-your-own-jaeger

**Comment by olix0r** [comment]
Closing this for now. Please let us know if there's anything we can do to clarify the docs for this.
