### ISSUE TITLE
Centralized Grafana is not supporting Dashboards

### ISSUE THREAD

**Issue by jijeesh** [linkerd/linkerd2#6043]
### What is the issue?
Grafana dashboard is currently supporting into hardcoded data source name prometheus only. It will not work directly in external Grafana and Prometheus

### How can it be reproduced?
 Most of the Grafana default datasource will be Prometheus (Please note Capital letter begin with). So we need to duplicate datasource with small letter names like prometheus to work with external Prometheus and Grafana. But this will not help when we are using centralized Grafana to get metrics from multiple Kubernetes environments

### Logs, error output, etc

(If the output is long, please create a [gist](https://gist.github.com/) and
paste the link here.)

#### `linkerd check` output

```text
your output here ...
```

### Environment

- Kubernetes Version: Any
- Cluster Environment:  AKS
- Host OS: ubuntu
- Linkerd version: Any

### Possible solution
Add a Datasource as variable

**Comment by Pothulapati** [comment]
@jijeesh Thanks for raising the question.

Ignore my lack of knowledge with Grafana.

> Add a Datasource as variable
variable in Helm? 

I was hoping users could change the datasource variable value to their prometheus URL. Is that not possible? 🤔 

Feel free to raise a PR if you are interested to fix this.

**Comment by jijeesh** [comment]
> @jijeesh Thanks for raising the question.
> 
> Ignore my lack of knowledge with Grafana.
> 
> > Add a Datasource as variable
> > variable in Helm?
> 
> I was hoping users could change the data source variable value to their Prometheus URL. Is that not possible? 🤔
> 
> Feel free to raise a PR if you are interested to fix this.

it will help to solve in a single cluster when we change the data source variable value.
but we could not able to select which data source want to select  if we are creating a Grafana with multiple Prometheus servers  as data source
I will try to make pr. but I have changed all the dashboard JSON files like below example

![image](https://user-images.githubusercontent.com/8288856/115364493-11022980-a1e1-11eb-9d11-4a401f2d4670.png)

![image](https://user-images.githubusercontent.com/8288856/115364605-2d9e6180-a1e1-11eb-8b16-433c4349e6c0.png)

**Comment by jijeesh** [comment]
I have sent a PR [6044](https://github.com/linkerd/linkerd2/pull/6044)

**Comment by olix0r** [comment]
The PR includes further discussion about this, but the summary is that this is out of scope for Linkerd's Grafana instance.
