### ISSUE TITLE
Adapt to Grafana's new licensing

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#6045]
Grafana is now going to be distributed under the AGPLv3 https://grafana.com/blog/2021/04/20/grafana-loki-tempo-relicensing-to-agplv3/

I'm not lawyerly enough to articulate the implications of this on Linkerd's use of Grafana in the viz extension but, before upgrading Grafana, we'll need to understand this more fully so that those who are adopting or distributing Linkerd--an Apache v2 licensed project--can make informed decisions about the use AGPLv3 code.

As a starting point, we may want to entirely separate a `linkerd-grafana` extension so that `linkerd-viz` can be installed without having to worry about these licensing restrictions.

**Comment by olix0r** [comment]
As I understand it, as long as we're distributing an unmodified Grafana image, that shouldn't impact the rest of Linkerd's licensing. My main questions are:

* If we extend Grafana base images with our configurations, is that considered modification?
* Does (hyper-)linking to Grafana from the Linkerd CLI or Web UI constitute "linking" in the same sense as it would for library code?

**Comment by stefanprodan** [comment]
I see you are relicensing with Apache here https://github.com/linkerd/linkerd2/blob/main/grafana/Dockerfile#L3, maybe that's an issue? @olix0r have you opened a ticket in CNCF Servicedesk around this? We also distribute Grafana as part of Flux monitoring task but we don't build our own container yet, once our dashboards will hit the ectd limit we'll have to do same thing as you.

**Comment by stefanprodan** [comment]
@olix0r looks like we need to stop updating Grafana and stick to the last version released under Apache, see https://twitter.com/cra/status/1384859663615864833?s=20

This is a sad day for most CNCF projects....

**Comment by coderanger** [comment]
Not a lawyer but I was sent this thread from someone with questions so an attempt to bring things back to reality a bit:

> If we extend Grafana base images with our configurations, is that considered modification?

It wouldn't be a modification as you are not modifying any Grafana source code. However it miiiiight be a derived work. The FSF's position is that dynamic linking does activate virality and Docker layering is kind of like dynamic linking if you squint really hard. However the FSF's position is not reflected in US case law which holds the opposite view, that a combined work involving both sides does not in and of itself create a derived work relationship. This is an area that actual lawyers should weigh in on but I wouldn't assume it would be a problem and as a specific case we can potential request Grafana put their Dockerfiles back under Apache2 as they have for the JS libraries and related code.

> Does (hyper-)linking to Grafana from the Linkerd CLI or Web UI constitute "linking" in the same sense as it would for library code?

No, flatly and clearly. What it does do is activate the AGPL's code sharing provisions meaning if a user of Linkerd asks for the source code of Grafana, give them a link to https://github.com/grafana/grafana and you're in compliance with the license.

**Comment by kriswill** [comment]
> Please be aware that this is highly unlikely to be granted, and that the Governing Board has (at the time of this writing) not previously granted any exceptions for components that are under AGPL-3.0.

From: https://github.com/cncf/foundation/blob/master/agpl-recommendations.md#seek-an-exception-from-the-governing-board
