### ISSUE TITLE
linkerd viz uninstall missing role/rolebinding output for full cleanup

### ISSUE THREAD

**Issue by hollowimage** [linkerd/linkerd2#6062]
### What is the issue?

when you install viz via `linkerd viz install | kubectl apply -f -`  it creates resources, including a role and a rolebinding named web; but i think using `linkerd viz uninstall | kubectl delete -f -`  does not delete those, so when i tried to install viz with helm, it threw a managed conflict.

using linkerd viz install | kubectl delete -f - instead of linkerd viz uninstall | kubectl delete -f - cleaned up the role and rolebinding correctly

### How can it be reproduced?
install with `linkerd viz install | kubectl apply -f -`
delete with `linkerd viz uninstall | kubectl delete -f -`

try install with helm `helm install linkerd-viz linkerd/linkerd-viz`

get error
`
Error: rendered manifests contain a resource that already exists. Unable to continue with install: Role "web" in namespace "linkerd" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "linkerd-viz"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "default"
`

### Logs, error output, etc
quick and dirty grep for resources named `web` in uninstall manifest generator:

```
[12:49:50][~/k8s/linkerd/1 ]➭ linkerd viz uninstall | grep web
  name: linkerd-linkerd-viz-web-api
  name: linkerd-linkerd-viz-web-check
  name: linkerd-linkerd-viz-web-admin
  name: linkerd-linkerd-viz-web-api
  name: linkerd-linkerd-viz-web-check
  name: linkerd-tap-injector-webhook-config
[12:52:14][~/k8s/linkerd/1 ]➭ linkerd viz install | grep web
  name: web
    component: web
  name: web
    component: web
  name: web
  name: web
  name: linkerd-linkerd-viz-web-check
    component: web
  resources: ["mutatingwebhookconfigurations", "validatingwebhookconfigurations"]
  name: linkerd-linkerd-viz-web-check
    component: web
  name: linkerd-linkerd-viz-web-check
  name: web
  name: linkerd-linkerd-viz-web-admin
    component: web
  name: web
  name: linkerd-linkerd-viz-web-api
    component: web
  name: linkerd-linkerd-viz-web-api
    component: web
  name: linkerd-linkerd-viz-web-api
  name: web
  name: web
    component: web
  name: web
  name: linkerd-tap-injector-webhook-config
webhooks:
  name: web
    component: web
    component: web
    app.kubernetes.io/name: web
    component: web
  name: web
      component: web
        component: web
        - -enforced-host=^(localhost|127\.0\.0\.1|web\.linkerd-viz\.svc\.cluster\.local|web\.linkerd-viz\.svc|\[::1\])(:\d+)?$
        image: cr.l5d.io/linkerd/web:stable-2.10.1
        name: web
      serviceAccountName: web
```
### Environment

- Kubernetes Version: 1.19.8
- Cluster Environment: EKS
- Host OS:
- Linkerd version: 

```
Client version: stable-2.10.1
Server version: stable-2.10.1
```

### Possible solution
add stubs for 

```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: web

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: web

```

into `linkerd uninstall` template

**Comment by miguescri** [comment]
Is this fixed now with that MR?

**Comment by olix0r** [comment]
@miguescri Yeah, this should be closed. Thanks.
