### ISSUE TITLE
diagnostics proxy-metrics --obfuscate

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#6073]
The `proxy-metrics` diagnostics include potentially private information (service names, pod names, etc).

It would be helpful if this command could support an `--obfuscate` flag that mangles metric label values like

- `authority`
- `dst_service`
- `dst_namespace`
- `target_addr`
- `server_id`
- `client_id`

Each of these values should be hashed so that values can be correlated but should be obscured so that the metrics can be shared publicly.

**Comment by PavloGl** [comment]
Hi!
Could I be assigned to this issue?

**Comment by olix0r** [comment]
@PavloGl We'd love help with this!

**Comment by sannimichaelse** [comment]
Hi @PavloGl, are you still working on this?

**Comment by PavloGl** [comment]
Hi @sannimichaelse, yes, i've just opened PR

**Comment by ahmedalhulaibi** [comment]
Seeing as it has been a few months since the last comment on this issue and PR, I will pick this one up

**Comment by kleimkuhler** [comment]
thanks @ahmedalhulaibi!

**Comment by ahmedalhulaibi** [comment]
Happy to help! 😁
