### ISSUE TITLE
Service Profiles for core cp and extensions

### ISSUE THREAD

**Issue by Pothulapati** [linkerd/linkerd2#6084]
Currently, There are [service profile resources available](https://github.com/linkerd/linkerd2/blob/main/cli/installsp/template.go#L4) for the core
control-plane in the `diagnostics install-sp` command through which they can be
installed on-demand.

These are currently out-dated, and may not work as expected with all the recent
changes that the control-plane components went through.

One of the reason for having these (I think) into a separate `install-sp` cmd instead of
`linkerd install` is that having both the `ServicProfile` definiation and instances
in the same manifest could cause problem with the install, and there are long standing
issues around this in Helm, etc.

With the recent addition of extensions, This won't be the problem as CRD is part of
the core install, while extension components can get Service Profiles instances as
part of their install.

## Proposed Changes

With the above infromation in mind, I propose the following changes:

- Clean up `diagnostics install-sp` with the latest core cp changes.
- All extension components should have their service profile definiations
  as part of their install. (atleast first party extensions i.e viz, multi-cluster, etc)
  (Should they be enabled by default, or manually enabled is a point to be discussed)
- Optionally, Extensions should also get their own `install-sp` cmd to install
  service profile definations later on.
  (Implementation wise, Both the above points can be simplified, by having good code re-use)

@olix0r

**Comment by olix0r** [comment]
> All extension components should have their service profile definiations
as part of their install. (atleast first party extensions i.e viz, multi-cluster, etc)
> (Should they be enabled by default, or manually enabled is a point to be discussed)
> Optionally, Extensions should also get their own install-sp cmd to install
service profile definations later on.
> (Implementation wise, Both the above points can be simplified, by having good code re-use)

I think extensions should provide these resources by default without any additional configuration/install commands.
