### ISSUE TITLE
Multicluster's Helm chart doesn't expose `gateway-addresses`

### ISSUE THREAD

**Issue by alpeb** [linkerd/linkerd2#6098]
Followup to #6059 

Add support for a `--gateway-addresses` equivalent value in the multicluster Helm chart. This is necessary when installing with a gateway of service type NodePort.

Also add Helm-level validation (like we have for ensuring the certs are defined) that ensures that's set when serviceType is NodePort.

**Comment by psmit** [comment]
Hi @alpeb ! The code I have added earlier regarding specifying node ports works great. However, I'm still having a usability issue and I think it is related to this issue.

On the `linkerd mc link` command, there is also no option to set the gateway-port and gateway-probe-port, in a similar fashion as setting the gateway-adresses. My link command looks now like:

```
./linkerd2-cli-edge-21.5.2-linux-amd64 --context=east mc link --cluster-name east --service-account-name west --gateway-addresses 1.2.3.4 | sed s/30181/4181/g | sed s/30143/4143/g | kubectl --context=west apply -f -
```

**Comment by alpeb** [comment]
Hi @psmit :wave:
Yes, that makes sense for the gateway port, would you please create an issue for that? As for the gateway probe port, you can set it via `--set gateway.probe.port=4143` on the command line.
OTOH, I'm gonna close this issue because there's really no Helm-equivalent for `linkerd mc link` given there's some logic performed on the CLI that can't be replicated through sheer templates.
