### ISSUE TITLE
Warn about expiring root certificate on getting started page

### ISSUE THREAD

**Issue by iamargopelter** [linkerd/linkerd2#6099]
The getting started page at https://linkerd.io/2.10/getting-started/ ends with 'Congratulations, you’re now a Linkerd user!', but doesn't warn that the control plane certificate will expire. As everything else seems automated, this has led to some unwelcome surprises.

A mention / link to the [rotation procedure](https://linkerd.io/2.10/tasks/manually-rotating-control-plane-tls-credentials/) and/or [how to set up automation ](https://linkerd.io/2.10/tasks/automatically-rotating-control-plane-tls-credentials/) in the 'next steps' segment would save headaches for new (and returning) users.

**Comment by mateiidavid** [comment]
Hey @iamargopelter seems like a good suggestion to me! Would you be willing to submit a PR in [linkerd2/website](https://github.com/linkerd/website) with the proposed changes?

**Comment by iamargopelter** [comment]
Hey @mateiidavid, certainly. Submitted a PR.
