### ISSUE TITLE
Failed to read SO_ORIGINAL_DST: Os { code: 2, kind: NotFound, message: "No such file or directory" }

### ISSUE THREAD

**Issue by pdefreitas** [linkerd/linkerd2#6105]
### What is the issue?

Under a certain conditions, communication between linkerd proxies of injected workloads will fail.

### How can it be reproduced?

Right after a cluster is scaled up to allocate a new deployment, linkerd-proxy shows errors and the communication to this proxy is reset.
This situation does not happen with **linkerd-cni** disabled, which may be related with problems reported in #5916.

### Logs, error output, etc

**Linkerd proxy log of automatically injected workload (repeats forever):**
```
[  1385.864911s]  WARN ThreadId(01) inbound: linkerd_proxy_transport::orig_dst::linux: failed to read SO_ORIGINAL_DST: Os { code: 2, kind: NotFound, message: "No such file or directory" }
[  1385.864984s]  WARN ThreadId(01) inbound: linkerd_app_core::serve: Server failed to accept connection error=No such file or directory (os error 2)
```

**Linkerd-CNI log:**
```
Wrote linkerd CNI binaries to /host/opt/cni/bin
Using CNI config template from CNI_NETWORK_CONFIG environment variable.
      "k8s_api_root": "https://__KUBERNETES_SERVICE_HOST__:__KUBERNETES_SERVICE_PORT__",
      "k8s_api_root": "https://10.0.0.1:__KUBERNETES_SERVICE_PORT__",
CNI config: {
  "name": "linkerd-cni",
  "type": "linkerd-cni",
  "log_level": "info",
  "policy": {
      "type": "k8s",
      "k8s_api_root": "https://10.0.0.1:443",
      "k8s_auth_token": "__SERVICEACCOUNT_TOKEN__"
  },
  "kubernetes": {
      "kubeconfig": "/etc/cni/net.d/ZZZ-linkerd-cni-kubeconfig"
  },
  "linkerd": {
    "incoming-proxy-port": 4143,
    "outgoing-proxy-port": 4140,
    "proxy-uid": 2102,
    "ports-to-redirect": [],
    "simulate": false,
    "use-wait-flag": false
  }
}
Created CNI config /host/etc/cni/net.d/10-azure.conflist
Done configuring CNI. Sleep=true
```

**`linkerd check --proxy`** output

```
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-cni-plugin
------------------
√ cni plugin ConfigMap exists
√ cni plugin PodSecurityPolicy exists
√ cni plugin ClusterRole exists
√ cni plugin ClusterRoleBinding exists
√ cni plugin Role exists
√ cni plugin RoleBinding exists
√ cni plugin ServiceAccount exists
√ cni plugin DaemonSet exists
√ cni plugin pod is running on all nodes

linkerd-identity
----------------
√ certificate config is valid
√ trust anchors are using supported crypto algorithm
√ trust anchors are within their validity period
√ trust anchors are valid for at least 60 days
√ issuer cert is using supported crypto algorithm
√ issuer cert is within its validity period
‼ issuer cert is valid for at least 60 days
    issuer certificate will expire on 2021-05-11T14:53:07Z
    see https://linkerd.io/checks/#l5d-identity-issuer-cert-not-expiring-soon for hints
√ issuer cert is issued by the trust anchor

linkerd-webhooks-and-apisvc-tls
-------------------------------
√ proxy-injector webhook has valid cert
√ proxy-injector cert is valid for at least 60 days
√ sp-validator webhook has valid cert
√ sp-validator cert is valid for at least 60 days

linkerd-identity-data-plane
---------------------------
√ data plane proxies certificate match CA

linkerd-api
-----------
√ control plane pods are ready
√ can initialize the client
√ can query the control plane API

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

linkerd-data-plane
------------------
√ data plane namespace exists
√ data plane proxies are ready
√ data plane is up-to-date
√ data plane and cli versions match

linkerd-ha-checks
-----------------
‼ pod injection disabled on kube-system
    kube-system namespace needs to have the label config.linkerd.io/admission-webhooks: disabled if injector webhook failure policy is Fail
    see https://linkerd.io/checks/#l5d-injection-disabled for hints

Status check results are √
```

### Environment

- Kubernetes Version: 1.20.5
- Cluster Environment: AKS with **Azure CNI**
- Host OS: Ubuntu 18.04.5 LTS - 5.4.0-1043-azure
- Linkerd version: 2.10.1

### Possible solution
This situation does not happen with **linkerd-cni** disabled (using init container with NET_ADMIN and NET_RAW capabilities). It is not ideal for scenarios where we don't want to give away these permissions.

### Additional context
N/A

**Comment by olix0r** [comment]
> This situation does not happen with linkerd-cni disabled

Fascinating! As far as I know, the code used in both cases is essentially identical, so this sounds likely to be some unexpected interaction with Azure's CNI.

For reference, we're hitting this code in the proxy: https://github.com/linkerd/linkerd2-proxy/blob/251fa8bf049b0b69154beb088f73332f2e3fda4c/linkerd/proxy/transport/src/orig_dst.rs#L107-L118

The code for the CNI is [here](https://github.com/linkerd/linkerd2/blob/6ea497fdb0c352f7a17f348b98cee285a51dc0e6/cni-plugin/main.go) -- it pulls in logic from `proxy-init` as a library dependency.

**Comment by pdefreitas** [comment]
> Fascinating! As far as I know, the code used in both cases is essentially identical, so this sounds likely to be some unexpected interaction with Azure's CNI.

I'm not familiar with Azure CNI implementation but it seems like the situation only occurs in new instances that are turning on during a scale up.

I'm not sure if this behavior happens on different AKS versions since we've only detected this situation recently.

We've disabled _cniEnabled_ in Linkerd configuration and instead rely solely on the init container to inject workloads into the service mesh.

**Comment by pdefreitas** [comment]
Some updates. I will be closing this issue since I wasn't able to reproduce it anymore on AKS with the following setup:
**Kubernetes:** 1.21.2
**OS Image:** Ubuntu 18.04.6 LTS
**Cluster Environment:** AKS with Azure CNI
**Kernel versions:** 5.4.0-1056-azure, 5.4.0-1061-azure and 5.4.0-1064-azure
**Containerd runtime:** 1.4.8+azure and 1.4.9+azure
**Linkerd version:** 2.11.1

If anything changes I will report back. Thanks for the help.
