### ISSUE TITLE
linkerd `check --proxy` appears to fail on Completed Job Pods

### ISSUE THREAD

**Issue by jkirkham-ratehub** [linkerd/linkerd2#6128]
### What is the issue?
I've successfully got kubernetes CronJobs to work with linkerd-proxy injection by using the linkerd-away wrapper, however if I check the proxy status in the target namespace `linkerd check --proxy -n <namespace>` the linkerd CLI will never exit.  It appears to be stuck checking the proxy container in the "Completed" Pod that is no longer running.

Using `--verbose` mode does not yield any more information.
Output continues to be `         | waiting for check to complete` until linkerd-cli is kill (ctrl-C).

### How can it be reproduced?
 - Run a "Batch" Pod (CronJob or Job) with the linkerd-await so it exits properly.
 - run linkerd-cli to check the proxy status: `linkerd check --proxy -n <target namespace>`
 - wait and nothing happens until you either delete all Completed Pods or manually terminate linkerd CLI.

### Environment

- Kubernetes Version:  v1.19.6 (DigitalOcean) / v1.19.9 (GCP)
- Cluster Environment: DOKS (DigitalOcean) / GCP
- Host OS: Debian GNU/Linux 10 (buster) - DigitalOcean / Container-Optimized OS from Google
- Linkerd version: 2.10.1  (install via Helm)

### Possible solution
Delete all completed Job Pods before running `linker check --proxy`

### Expected Behaviour
linkerd check should detect that a Pod is no longer running and skip the proxy check on that pod.

**Comment by adleong** [comment]
Nice find, @jkirkham-ratehub!  `linker check --proxy` probably needs to be more intelligent about skipping pods in the `completed` status.
