### ISSUE TITLE
Add Redis to default list of Opaque ports

### ISSUE THREAD

**Issue by JasonMorgan** [linkerd/linkerd2#6132]
Redis is pretty common. We should add it to the list of default skip ports.

https://github.com/linkerd/linkerd2/blob/da588130544154fdb94afb64147fa745ce852fc4/charts/linkerd2/values.yaml#L110

**Comment by alpeb** [comment]
Also please add elasticsearch' port to `opaquePorts`, and Galeras' ports to both `ignoreInboundPorts` and `ignoreOutboundPOrts`, basically bringing the [doc](https://linkerd.io/2.10/features/protocol-detection/) in sync with our config.
