### ISSUE TITLE
podAnnotations fail with linkerd-viz helm chart

### ISSUE THREAD

**Issue by johnmckenna** [linkerd/linkerd2#6148]
### What is the issue?
helm install linkerd-viz linkerd/linkerd-viz --version 2.10.2 --values values.yaml

produces the following error:

Error: template: linkerd-viz/templates/prometheus.yaml:227:50: executing "linkerd-viz/templates/prometheus.yaml" at <trim>: wrong type for value; expected string; got map[string]interface {}

### How can it be reproduced?

values.yaml has the following configuration:

podAnnotations:
  apparmor.security.beta.kubernetes.io/pod: runtime/default

### Logs, error output, etc
Error: template: linkerd-viz/templates/prometheus.yaml:227:50: executing "linkerd-viz/templates/prometheus.yaml" at <trim>: wrong type for value; expected string; got map[string]interface {}

(If the output is long, please create a [gist](https://gist.github.com/) and
paste the link here.)

#### `linkerd check` output

```text
your output here ...
```

### Environment

- Kubernetes Version: 1.19.9
- Cluster Environment:  AKS
- Host OS: Ubuntu-20.04
- Linkerd version: 2.10.2

**Comment by kleimkuhler** [comment]
Thanks for the report @johnmckenna we'll get this fix out soon.
