### ISSUE TITLE
Use opentelemetry collector instead of opencensus

### ISSUE THREAD

**Issue by aatarasoff** [linkerd/linkerd2#6159]
## Feature Request

Use [opentelemetry-collector](https://github.com/open-telemetry/opentelemetry-collector) instead of opencensus

### What problem are you trying to solve?

**Opencensus collector is deprecated** and has much less features for span modifications.

For example we can rewrite service name, span name and attributes to make tracing clearer:
<img width="526" alt="Screenshot 2021-05-21 at 12 07 22" src="https://user-images.githubusercontent.com/3737657/119112934-42af2000-ba2d-11eb-8a2c-a89ef5069427.png">

On the screenshot `nginx-ingress` and `website-primary` are processed Linkerd spans.

### How should the problem be solved?

Extend Helm chart with `use_opentelemetry` property. If it is enabled then opentelemetry collector configuration is used. In other case opencensus use as usual.

### Any alternatives you've considered?

Think that we should care about backward compatibility, so we should support both collectors for some time. So, no other alternatives.

### How would users interact with this feature?

Just turn on property and fill specific configuration in `values.yml` and update release on their environment.

**Comment by olix0r** [comment]
Thanks @aatarasoff.

I'm curious if we really need to continue supporting OpenCensus collectors. We should probably ask around on Slack and the users list to get a sense of how important this is.  I get the sense that the `linkerd-jaeger` extension isn't _that_ widely deployed; so we may be able to just change APIs without real impact...

**Comment by aatarasoff** [comment]
@olix0r sometimes we have a lot of unexpected work because of breaking changes in Helm charts (especially when you need to update something fast), so I vote to keep backward compatibility as long as possible.

OpenTelemetry and OpenCensus collectors have not compatible configurations, and I think there is not much work to support both templates for a while under a toggle.

Anyway I am ready to make a PR because we've done it for our installation already.

**Comment by olix0r** [comment]
@aatarasoff My main concern is having to support wiring configuration through the injector and proxy. It's not a deal-breaker, but generally we prefer to minimize the configuration surface area. Does the OT collector _just work_ with the open census gRPC API? or are we going to have to support both formats in the proxy?

**Comment by aatarasoff** [comment]
@olix0r hmm, I see that this problem is a little bit more complex than I thought 🤔 

These two issues are linked but could be implemented and delivered separately. On the one hand, the proxy could use OC protocol with OT collector for a long time. On the other hand, adopters could use OLTP protocol in the proxy (if it supports) with a separated OT collector.

Just as a variant, we could use the following steps:
1. Server-side first. OT collector comes first under a toggle (turn off by default) and could be used by early adopters (who see value from the new collector). Proxy using OC protocol because both collectors support it.
2. Variant A: OT collector comes as default, but there is an option to use OC collector (revert the toggle default value). 
    Variant B: Proxy comes with OLTP protocol under a toggle (turn off by default). 
    We could implement both variants in any order or skip variant B and go to the next step.
3. OT collector remains the only option (can support OC and OLTP protocols via configuration).
4. Someday, OLTP protocol in proxy becomes the only option.

Just for me, a collector is more beneficial than a protocol because in practical cases (for example, with nginx-ingress opentracing option), any collector (OC or OT) should have at least two receivers (Zipkin or Jaeger for Nginx and OpenCensus for Linkerd). And my opinion is OT collector will support all of these receivers for a very long time (maybe till the next standard comes 😃).

**Comment by Pothulapati** [comment]
Hey @aatarasoff,

That approach seems right for me too i.e starting with replacing the OC collector with OT collector (with OC protocol) and then figure out a plan specifically for the proxy! I'm also fairly confident that OC protocol will be supported for a while with OT.

 I'm not sure how well tested OT collector is, and when would be the right time to make the switch though! WDYT? @olix0r

**Comment by adleong** [comment]
Replacing the OC collector with the OT collector seems like a natural first step if the OT collector supports the OC API.  Are there any drawbacks to doing so?

**Comment by aatarasoff** [comment]
@adleong yep, it supports OC API. I tried to explain some details in this comment: https://github.com/linkerd/linkerd2/pull/6167#discussion_r638024625

**Comment by olix0r** [comment]
#6188 has been merged
