### ISSUE TITLE
Linkerd2 (2.8.1) returns 502 when a request with a large header is received

### ISSUE THREAD

**Issue by ericsuhong** [linkerd/linkerd2#6164]
### What is the issue?

Linkerd-proxy containers return 502 errors when a request with a larger header is received.

### How can it be reproduced?

Simply send a request with a large header value (i.e. I attached the header value I used to reproduce this issue), and linkerd-proxy container will return 502.

### Logs, error output, etc

linkerd-proxy container shows this error message:
````
linkerd2_app_core::errors: Failed to proxy request: http2 error: user error: header too big
````

#### `linkerd check` output
N/A
[largeheader.txt](https://github.com/linkerd/linkerd2/files/6525597/largeheader.txt)

### Environment
Linkerd2 2.8.1-stable

### Possible solution
Linkerd2 needs to return 4xx error codes in this case, not 5xx errors

**Comment by hawkw** [comment]
This error is returned by the `h2` library and wrapped by `hyper`.

Skimming the docs, it looks like [`h2`'s error type](https://docs.rs/h2/0.3.3/h2/struct.Error.html) doesn't currently expose a way to programmatically determine the cause of an error beyond determining whether it was a protocol error, an IO error, or a "user error". The only way we could detect this _specific_ error currently is through string matching, which is kind of sad.

Potentially, distinguishing between protocol, IO, and user errors sufficient if all the errors that are considered "user errors" by `h2` should produce 4xx responses, but I'm not sure if this is the case; some of them may represent internal bugs.  Alternatively, we might need to make a change in `h2` to expose additional error information programmatically?

I also opened a related issue against `hyper`: https://github.com/hyperium/hyper/issues/2564
