### ISSUE TITLE
How to verify whether load balancing really happens for the pods inside my cluster using linkerd service mesh.

### ISSUE THREAD

**Issue by balazzii** [linkerd/linkerd2#6198]
Background before installing linkerd:
k8s provider: AKS
Version: 1.19.7
Ingress controller: nginx ingress
Application protocol: gRPC
TLS termination happens at ingress.

I read from the below official k8s document that load balancing does not happen efficiently for gRPC applications, hence it is better to use linkerd service mesh.
https://kubernetes.io/blog/2018/11/07/grpc-load-balancing-on-kubernetes-without-tears/

I installed linkerd in my k8s cluster using the below document:
https://linkerd.io/2.10/getting-started/

I injected linkerd using the below command:
`kubectl get -n <NAMESPACE NAME> deploy -o yaml \
  | linkerd inject - \
  | kubectl apply -f -`

I checked the dashboard and application pods in the namespace were meshed but I could not see any metrics.
![image](https://user-images.githubusercontent.com/53429199/120158654-53327800-c22f-11eb-8469-1b012dbb113e.png)

I followed the steps mentioned in the below documents to use linkerd along with nginx-ingress controller.
https://linkerd.io/2.10/tasks/using-ingress/#
https://linkerd.io/2.10/tasks/using-ingress/#nginx

But despite of doing that I could not see any metrics(HTTP/TCP).

The following is mentioned in the above document but I still could not see any TCP metric.
![image](https://user-images.githubusercontent.com/53429199/120159002-b1f7f180-c22f-11eb-85a4-e7dc20bb5cc2.png)

It would be great if someone could help me out with troubleshooting this problem.

**Comment by alpeb** [comment]
Can you please post the results of  both `linkerd check` and `linkerd check --proxy -n trading`? Also, it seems you have an extra pod in the linkerd namespace, any chance that might be interfering?

**Comment by balazzii** [comment]
@alpeb 
Thank you for your reply.

Results of `linkerd check`:

`kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-identity
----------------
√ certificate config is valid
√ trust anchors are using supported crypto algorithm
√ trust anchors are within their validity period
√ trust anchors are valid for at least 60 days
√ issuer cert is using supported crypto algorithm
√ issuer cert is within its validity period
√ issuer cert is valid for at least 60 days
√ issuer cert is issued by the trust anchor

linkerd-webhooks-and-apisvc-tls
-------------------------------
√ proxy-injector webhook has valid cert
√ proxy-injector cert is valid for at least 60 days
√ sp-validator webhook has valid cert
√ sp-validator cert is valid for at least 60 days

linkerd-api
-----------
√ control plane pods are ready
√ can initialize the client
√ can query the control plane API

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ control plane is up-to-date
√ control plane and cli versions match

Status check results are √

Linkerd extensions checks
=========================

                              linkerd-viz
-----------
√ linkerd-viz Namespace exists
√ linkerd-viz ClusterRoles exist
√ linkerd-viz ClusterRoleBindings exist
√ tap API server has valid cert
√ tap API server cert is valid for at least 60 days
√ tap API service is running
√ linkerd-viz pods are injected
√ viz extension pods are running
√ prometheus is installed and configured correctly
√ can initialize the client
√ viz extension self-check

Status check results are √`


Results of `linkerd check --proxy -n trading`:

`kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-identity
----------------
√ certificate config is valid
√ trust anchors are using supported crypto algorithm
√ trust anchors are within their validity period
√ trust anchors are valid for at least 60 days
√ issuer cert is using supported crypto algorithm
√ issuer cert is within its validity period
√ issuer cert is valid for at least 60 days
√ issuer cert is issued by the trust anchor

linkerd-webhooks-and-apisvc-tls
-------------------------------
√ proxy-injector webhook has valid cert
√ proxy-injector cert is valid for at least 60 days
√ sp-validator webhook has valid cert
√ sp-validator cert is valid for at least 60 days

linkerd-identity-data-plane
---------------------------
√ data plane proxies certificate match CA

linkerd-api
-----------
√ control plane pods are ready
√ can initialize the client
√ can query the control plane API

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

linkerd-data-plane
------------------
√ data plane namespace exists
√ data plane proxies are ready
√ data plane is up-to-date
√ data plane and cli versions match

Status check results are √

Linkerd extensions checks
=========================

                              linkerd-viz
-----------
√ linkerd-viz Namespace exists
√ linkerd-viz ClusterRoles exist
√ linkerd-viz ClusterRoleBindings exist
√ tap API server has valid cert
√ tap API server cert is valid for at least 60 days
√ tap API service is running
√ linkerd-viz pods are injected
√ viz extension pods are running
√ prometheus is installed and configured correctly
√ can initialize the client
√ viz extension self-check

linkerd-viz-data-plane
----------------------
√ data plane namespace exists
‼ data plane proxy metrics are present in Prometheus
    Data plane metrics not found for trading/trading-6b985cb845-7vg2l, trading/trading-6b985cb845-l2ldv.
    see https://linkerd.io/2.10/checks/#l5d-data-plane-prom for hints

Status check results are √`

>Also, it seems you have an extra pod in the linkerd namespace, any chance that might be interfering?
The extra pod is that of flagger that I had installed.
Even if I uninstall it, it doesn't help.

**Comment by alpeb** [comment]
> ‼ data plane proxy metrics are present in Prometheus
>     Data plane metrics not found for trading/trading-6b985cb845-7vg2l, trading/trading-6b985cb845-l2ldv.
>     see https://linkerd.io/2.10/checks/#l5d-data-plane-prom for hints

This means Prometheus isn't able to reach your trading pod. Do you have in place a NetworkPolicy or some other restriction that is forbidding this to happen?

> Does that mean that load balancing happens at nginx ingress controller's load balancer and I can only get request splits at ingress controller pods and not at application pods?

Requests are indeed load-balanced at the Ingress pod. I didn't understand though what you meant by having requests split at application pods. Is there another pod sitting in between the trading pods and the ingress pod?

**Comment by balazzii** [comment]
>This means Prometheus isn't able to reach your trading pod. Do you have in place a NetworkPolicy or some other restriction that is forbidding this to happen?

Yes I have a network policy in place. 

NetworkPolicy:

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  annotations:
    meta.helm.sh/release-name: trading
    meta.helm.sh/release-namespace: trading
  creationTimestamp: "2021-06-01T11:54:17Z"
  generation: 1
  labels:
    app.kubernetes.io/managed-by: Helm
  name: api-allow-ports
  namespace: trading
  resourceVersion: "9058883"
  selfLink: /apis/networking.k8s.io/v1/namespaces/trading/networkpolicies/api-allow-ports
  uid: f13fbbb1-d06d-47c8-863b-fcbc215c6e25
spec:
  ingress:
  - ports:
    - port: 80
      protocol: TCP
    - port: 443
      protocol: TCP
    - port: 9500
      protocol: TCP
    - port: 8080
      protocol: TCP
  podSelector: {}
  policyTypes:
  - Ingress
```

> I didn't understand though what you meant by having requests split at application pods. Is there another pod sitting in between the trading pods and the ingress pod?

No I do not have any other pods between them but I do have a trading service between trading application pod & ingress.

**Comment by alpeb** [comment]
Ok, you'll have to add an ingress rule in your NetworkPolicy to allow traffic from Prometheus on port 4191, protocol TCP. This will allow for metrics to be collected and surfaced in the linkerd dashboard.

**Comment by balazzii** [comment]
>Ok, you'll have to add an ingress rule in your NetworkPolicy to allow traffic from Prometheus on port 4191, protocol TCP. This will allow for metrics to be collected and surfaced in the linkerd dashboard.

Thank you. This worked.

Question:
As a general practice, should I inject linkerd proxy in Application pod or Ingress-Controller pod or both?

**Comment by alpeb** [comment]
Glad it worked out! :+1: 

> As a general practice, should I inject linkerd proxy in Application pod or Ingress-Controller pod or both?

If you inject it in both you'll have more complete metrics about the traffic flowing out of the ingress and into the application pod :wink:

**Comment by balazzii** [comment]
>If you inject it in both you'll have more complete metrics about the traffic flowing out of the ingress and into the application pod

Got it!!
Thank you.
