### ISSUE TITLE
Connection closed error=TCP Server service in fail-fast

### ISSUE THREAD

**Issue by davi5e** [linkerd/linkerd2#6200]
### What is the issue?

We were using Linkerd2 for months, going from `2.8.0` until `2.10.1` without a single issue. Then a couple of weeks ago we upgraded to `2.10.2` while also upgrading GKE and a bunch of errors started appearing in all Linkerd pods's logs, shown later on.

The communication from any pod to Linkerd started having a lot of issues and if we try to `rollback restart` the Deployments no single Linkerd Pod passes its probes since they never get Certified by `linkerd-identity`... This is a real problem since we had the bad idea to just delete old pods only to have them all in a state of "not ready" at which point no communication flowed in our workloads and the Kubernetes cluster came to stand still (solved by deleting `validatingwebhookconfigurations/linkerd-sp-validator-webhook-config` since there was no pod to handle the webhook and then restarting every single workload so it would come up without the sidecar container).

Our cluster have a lot of security build in because we use PodSecurityPolicies and NetworkPolicies (both configurations worked forever). We use `cert-manager` to handle the issuer, also without a single problem until some weeks ago. Using GKE, we obviously disabled Istio to install Linekrd. We also deploy `linkerd-cni`.

After recovering from the incurred downtime, we tried to delete Linkerd `2.10.2` and install `2.10.1` to **no avail**. By now we started to wonder if the problem was with GKE's image `1.18.17-gke.1900` and waited for the next one. Last Saturday, we upgraded to `1.18.18-gke.1100` and gave another shot at Linkerd `2.10.2`. Today those errors started to pop up again and we decided to post this problem to get some help debugging it.

Keep in mind this is our production cluster and the workloads that currently have Linkerd enabled _seem_ to be working albeit a lot of error messages. If we were to issue `kubectl rollback -n linkerd restart deploy` we would get back to `linkerd-identity` not certifying pods, meaning we can't make tests quickly because we'd need to first remove linkerd from these workloads and this would always be done late at night to avoid downtime.

### How can it be reproduced?

Not sure, all was fine for months using `2.10.1` up until GKE `1.18.17-gke.1200` (both worked!).

We upgraded Linkerd to `2.10.2` with GKE `1.18.17-gke.1900` (currently `1.18.18-gke.1100`) and started noticing the errors. Do not seem to be Linkerd since `2.10.1` yield the same erros if downgraded.

### Logs, error output, etc

The messages below happen in most Linkerd pods beside those of `linkerd-identity`. Here is an example of **linkerd-controller** (before trying to rollback):

```text
public-api time="2021-05-30T18:21:01Z" level=info msg="running version stable-2.10.2"
public-api time="2021-05-30T18:21:01Z" level=info msg="Using cluster domain: cluster.local"
public-api time="2021-05-30T18:21:01Z" level=info msg="waiting for caches to sync"
public-api time="2021-05-30T18:21:02Z" level=info msg="caches synced"
public-api time="2021-05-30T18:21:02Z" level=info msg="starting admin server on :9995"
public-api time="2021-05-30T18:21:02Z" level=info msg="starting HTTP server on :8085"
linkerd-proxy time="2021-05-30T18:21:00Z" level=info msg="running version stable-2.10.2"
linkerd-proxy [     0.002234s[]  INFO ThreadId(01) linkerd2_proxy::rt: Using single-threaded proxy runtime
linkerd-proxy [     0.002955s[]  INFO ThreadId(01) linkerd2_proxy: Admin interface on 0.0.0.0:4191
linkerd-proxy [     0.002970s[]  INFO ThreadId(01) linkerd2_proxy: Inbound interface on 0.0.0.0:4143
linkerd-proxy [     0.002974s[]  INFO ThreadId(01) linkerd2_proxy: Outbound interface on 127.0.0.1:4140
linkerd-proxy [     0.002977s[]  INFO ThreadId(01) linkerd2_proxy: Tap DISABLED
linkerd-proxy [     0.002980s[]  INFO ThreadId(01) linkerd2_proxy: Local identity is linkerd-controller.linkerd.serviceaccount.identity.linkerd.cluster.local
linkerd-proxy [     0.002984s[]  INFO ThreadId(01) linkerd2_proxy: Identity verified via linkerd-identity-headless.linkerd.svc.cluster.local:8080 (linkerd-identity.linkerd.serviceaccount.identity.linkerd.cluster.local)
linkerd-proxy [     0.002988s[]  INFO ThreadId(01) linkerd2_proxy: Destinations resolved via linkerd-dst-headless.linkerd.svc.cluster.local:8086 (linkerd-destination.linkerd.serviceaccount.identity.linkerd.cluster.local)
linkerd-proxy [     0.408784s[]  INFO ThreadId(02) daemon:identity: linkerd_app: Certified identity: linkerd-controller.linkerd.serviceaccount.identity.linkerd.cluster.local
linkerd-proxy [     1.029928s[]  INFO ThreadId(02) linkerd_app_core::serve: Connection closed error=non-HTTP connection from 127.0.0.1:42724
linkerd-proxy [     1.114028s[]  WARN ThreadId(01) server{orig_dst=10.0.25.127:8086}: linkerd_app_core::control: Failed to resolve control-plane component error=no record found for name: linkerd-dst-headless.linkerd.svc.cluster.local. type: SRV class: IN
linkerd-proxy [     1.115734s[]  WARN ThreadId(01) server{orig_dst=10.0.25.127:8086}: linkerd_app_core::control: Failed to resolve control-plane component error=no record found for name: linkerd-dst-headless.linkerd.svc.cluster.local. type: SRV class: IN
linkerd-proxy [     4.113758s[]  WARN ThreadId(01) server{orig_dst=10.0.25.127:8086}: linkerd_timeout::failfast: TCP Server entering failfast after 3s
linkerd-proxy [     4.113916s[]  INFO ThreadId(01) linkerd_app_core::serve: Connection closed error=TCP Server service in fail-fast
linkerd-proxy [     5.121474s[]  INFO ThreadId(01) linkerd_app_core::serve: Connection closed error=TCP Server service in fail-fast
linkerd-proxy [     6.688163s[]  INFO ThreadId(01) linkerd_app_core::serve: Connection closed error=TCP Server service in fail-fast
linkerd-proxy [     9.591757s[]  INFO ThreadId(01) linkerd_app_core::serve: Connection closed error=TCP Server service in fail-fast
linkerd-proxy [    14.071013s[]  INFO ThreadId(01) linkerd_app_core::serve: Connection closed error=TCP Server service in fail-fast
linkerd-proxy [    23.060995s[]  WARN ThreadId(01) server{orig_dst=10.0.25.127:8086}: linkerd_timeout::failfast: TCP Server entering failfast after 3s
linkerd-proxy [    23.061181s[]  INFO ThreadId(01) linkerd_app_core::serve: Connection closed error=TCP Server service in fail-fast
linkerd-proxy [    38.607955s[]  WARN ThreadId(01) server{orig_dst=10.0.25.127:8086}: linkerd_timeout::failfast: TCP Server entering failfast after 3s
linkerd-proxy [    38.608059s[]  INFO ThreadId(01) linkerd_app_core::serve: Connection closed error=TCP Server service in fail-fast
linkerd-proxy [    61.075060s[]  WARN ThreadId(01) server{orig_dst=10.0.25.127:8086}: linkerd_timeout::failfast: TCP Server entering failfast after 3s
linkerd-proxy [    61.075279s[]  INFO ThreadId(01) linkerd_app_core::serve: Connection closed error=TCP Server service in fail-fast
```

#### `linkerd check` output

```text
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-cni-plugin
------------------
√ cni plugin ConfigMap exists
√ cni plugin PodSecurityPolicy exists
√ cni plugin ClusterRole exists
√ cni plugin ClusterRoleBinding exists
√ cni plugin Role exists
√ cni plugin RoleBinding exists
√ cni plugin ServiceAccount exists
√ cni plugin DaemonSet exists
√ cni plugin pod is running on all nodes

linkerd-identity
----------------
√ certificate config is valid
√ trust anchors are using supported crypto algorithm
√ trust anchors are within their validity period
√ trust anchors are valid for at least 60 days
√ issuer cert is using supported crypto algorithm
√ issuer cert is within its validity period
‼ issuer cert is valid for at least 60 days
    issuer certificate will expire on 2021-06-01T18:13:19Z
    see https://linkerd.io/2.10/checks/#l5d-identity-issuer-cert-not-expiring-soon for hints
√ issuer cert is issued by the trust anchor

linkerd-webhooks-and-apisvc-tls
-------------------------------
√ proxy-injector webhook has valid cert
√ proxy-injector cert is valid for at least 60 days
√ sp-validator webhook has valid cert
√ sp-validator cert is valid for at least 60 days

linkerd-api
-----------
√ control plane pods are ready
√ can initialize the client
√ can query the control plane API

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ control plane is up-to-date
√ control plane and cli versions match

linkerd-ha-checks
-----------------
√ pod injection disabled on kube-system
√ multiple replicas of control plane pods

Status check results are √
```

### Environment

- Kubernetes Version: 1.18
- Cluster Environment: GKE
- Host OS: container optimized
- Linkerd version: 2.9.2

### Possible solution

No idea... We are currently using the annotation `linkerd.io/inject: disabled` in all workloads to avoid any downtime to our applications...

### Additional context

None.

EDIT: I originally made some typing errors where I mentioned version `2.9` instead of `2.10`.

**Comment by mateiidavid** [comment]
Hey @davi5e 👋🏻  thanks for submitting the issue! Sorry to hear this happened unexpectedly.

First, I'd like to confirm a few things if that's ok. I'm a bit confused when looking at the logs because you mentioned you upgraded to `2.9.2` but the logs show `2.10.2`:
```
public-api time="2021-05-30T18:21:01Z" level=info msg="running version stable-2.10.2"
linkerd-proxy time="2021-05-30T18:21:00Z" level=info msg="running version stable-2.10.2"
```

Second, I wonder if `linkerd-identity` doesn't certify the pods because of the cert expiry date. Have you tried rotating your certs? Does the problem still persist?

There could be other issues here; a bit more verbosity in logs might make it a bit easier to pinpoint the exact problem. To start, would you mind posting some logs from the proxy with the log level set to something a bit more verbose? Something like `linkerd=debug,warn` might do the trick. Lines such as:
```
linkerd-proxy [    61.075060s[]  WARN ThreadId(01) server{orig_dst=10.0.25.127:8086}: linkerd_timeout::failfast: TCP Server entering failfast after 3s
linkerd-proxy [    61.075279s[]  INFO ThreadId(01) linkerd_app_core::serve: Connection closed error=TCP Server service in fail-fast
```

mean that the proxy cannot connect to the underlying server for some reason. It'd be useful to know if this happens because of a TLS detection timeout or something else. You can [modify the log level](https://linkerd.io/2.10/tasks/modifying-proxy-log-level/#) without having to restart the pod.

**Comment by davi5e** [comment]
Sorry, all the versions I've mention should be `2.10`, I'll edit the OP.

We used cert-manager tool to rotate the certificates, we've check the event telling it happened and the problem persists.

I'll get the logs later on today and post them back as soon as I can.

**Comment by davi5e** [comment]
By the way, back when the problem happened, we tried Linkerd without cert-manger so it'd use its own certificate. Also did not help.

I personally believe this is somehow related to the underlying VM provided by GKE since all was fine for so many months and downgrading back to `2.10.1` had no effect in "solving" the issue.

**Comment by davi5e** [comment]
Well, I'm not sure it's "good news" but the log I previously posted appears to have been a one time thing.

Now that I can make some tests in the production cluster I could restart all deployments and they all came back online without problems. There is one and only `linkerd-destination-57df7f4bc-tvnq2 linkerd-proxy [    60.727567s]  INFO ThreadId(01) linkerd_app_core::serve: Connection closed error=TLS detection timed out` that may not be related to the issues we were facing.

Overall, somehow Linkerd `2.10.2` is back to the old boring behavior of just working. Maybe it was GKE's `1.18.17-gke.1900` image, but at least I myself will never know.

I don't see the point to keep this issue opened, but not having any idea why `linkerd-identity` failed 2 weeks ago or what `Connection closed error=TCP Server service in fail-fast` means is not very comforting.

**Comment by mateiidavid** [comment]
@davi5e glad it fixed itself! It would have been good to know for sure but at least your production environment is back to normal. 

> what Connection closed error=TCP Server service in fail-fast means is not very comforting.

This is easier to tackle -- when you see these errors it typically means the proxy cannot connect to the service it is trying to reach so it fails fast. It's not very descriptive, I agree. Generally it signals a connection problem, bumping up the log level is what I usually do to learn more about the problem. 

I'm not sure either why the identity service would fail. My assumption was we'd see a lot of `TLS detection timeout` logs. If it happens again, feel free to ping me to re-open this or just create a new issue; we'll probably want to fix it asap.

Thanks again for raising this and following-up!
