### ISSUE TITLE
Add company/org affiliation to MAINTAINERS

### ISSUE THREAD

**Issue by caniszczyk** [linkerd/linkerd2#6205]
This is great https://github.com/linkerd/linkerd2/blob/main/MAINTAINERS.md

It would be great if each member had their organization affiliation

**Comment by caniszczyk** [comment]
Also consider having an "Emeritus" section highlighting previous maintainers

**Comment by caniszczyk** [comment]
cc: @wmorgan

**Comment by wmorgan** [comment]
We've got emeriti in there already, but org affiliation would be easy to add.

**Comment by adleong** [comment]
Each of the current maintainers is listed with an email address from their employer's domain.  Is that sufficient or should we express their affiliation more explicitly?

**Comment by caniszczyk** [comment]
I guess that's good enough, my main issue was with the SC which has no affiliations https://github.com/linkerd/linkerd2/blob/main/MAINTAINERS.md#steering-committee
