### ISSUE TITLE
Instructions for integrating with Contour incomplete

### ISSUE THREAD

**Issue by jroper** [linkerd/linkerd2#6237]
With the current instructions for integrating with Contour, Contour fails to start, because linkerd blocks traffic from the Contour envoy proxy to the Contour controller manager (an xDS server, uses gRPC with mTLS to communicate) because linkerd only allows HTTP traffic (but the xDS server traffic is TLS) when in ingress mode, the following error is output in the linkerd logs:

```
[   484.169131s]  INFO ThreadId(01) linkerd_app_core::serve: Connection closed error=ingress-mode routing is HTTP-only
```

To fix this, communication with the xDS server must be excluded from going through the linkerd proxy, by adding the following annotation:

```
config.linkerd.io/skip-outbound-ports: 8001
```

**Comment by adleong** [comment]
Great catch, thanks @jroper!  Are you interested in submitting a fix for this as a PR in the linkerd/website repo?
