### ISSUE TITLE
Linkerd proxy container showing "Failed to proxy request: error trying to connect: Connection refused (os error 111)"

### ISSUE THREAD

**Issue by shahriak** [linkerd/linkerd2#6248]
### What is the issue?
I have deployed my application on a cluster with Linkerd sidecar injected. However, I am seeing errors in the sidecar pod. 

### How can it be reproduced?
Deploy linkerd 2.10.0 with Nginx Ingress (LoadBalancer) on a cluster and then deploy your service and enable linkerd injection.

### Logs, error output, etc
Linkerd-proxy Container logs:

time="2021-06-11T00:27:46Z" level=info msg="running version stable-2.10.0"
[     0.002007s]  INFO ThreadId(01) linkerd2_proxy::rt: Using single-threaded proxy runtime
[     0.002570s]  INFO ThreadId(01) linkerd2_proxy: Admin interface on 0.0.0.0:4191
[     0.002583s]  INFO ThreadId(01) linkerd2_proxy: Inbound interface on 0.0.0.0:4143
[     0.002585s]  INFO ThreadId(01) linkerd2_proxy: Outbound interface on 127.0.0.1:4140
[     0.002587s]  INFO ThreadId(01) linkerd2_proxy: Tap interface on 0.0.0.0:4190
[     0.002589s]  INFO ThreadId(01) linkerd2_proxy: Local identity is default.ccpgls.serviceaccount.identity.linkerd.cluster.local
[     0.002591s]  INFO ThreadId(01) linkerd2_proxy: Identity verified via linkerd-identity-headless.linkerd.svc.cluster.local:8080 (linkerd-identity.linkerd.serviceaccount.identity.linkerd.cluster.local)
[     0.002594s]  INFO ThreadId(01) linkerd2_proxy: Destinations resolved via linkerd-dst-headless.linkerd.svc.cluster.local:8086 (linkerd-destination.linkerd.serviceaccount.identity.linkerd.cluster.local)
[     0.031768s]  INFO ThreadId(02) daemon:identity: linkerd_app: Certified identity: default.ccpgls.serviceaccount.identity.linkerd.cluster.local
[     2.149397s]  WARN ThreadId(01) inbound:accept{client.addr=10.240.7.196:38430 target.addr=10.240.7.200:80}: linkerd_app_core::errors: Failed to proxy request: error trying to connect: Connection refused (os error 111)

(If the output is long, please create a [gist](https://gist.github.com/) and
paste the link here.)
App logs with no proxy injected: https://gist.github.com/shahriak/29fb2ddf598b445dff8b575820640b7f
App logs with proxy: https://gist.github.com/shahriak/a5763d8e5cedc997d083929114081d64

#### `linkerd check` output

```text
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-identity
----------------
√ certificate config is valid
√ trust anchors are using supported crypto algorithm
√ trust anchors are within their validity period
√ trust anchors are valid for at least 60 days
√ issuer cert is using supported crypto algorithm
√ issuer cert is within its validity period
√ issuer cert is valid for at least 60 days
√ issuer cert is issued by the trust anchor

linkerd-webhooks-and-apisvc-tls
-------------------------------
√ proxy-injector webhook has valid cert
√ proxy-injector cert is valid for at least 60 days
√ sp-validator webhook has valid cert
√ sp-validator cert is valid for at least 60 days

linkerd-api
-----------
√ control plane pods are ready
√ can initialize the client
√ can query the control plane API

linkerd-version
---------------
√ can determine the latest version
‼ cli is up-to-date
    is running version 2.10.0 but the latest stable version is 2.10.2
    see https://linkerd.io/checks/#l5d-version-cli for hints

control-plane-version
---------------------
‼ control plane is up-to-date
    is running version 2.10.0 but the latest stable version is 2.10.2
    see https://linkerd.io/checks/#l5d-version-control for hints
√ control plane and cli versions match

linkerd-ha-checks
-----------------
‼ pod injection disabled on kube-system
    kube-system namespace needs to have the label config.linkerd.io/admission-webhooks: disabled if injector webhook failure policy is Fail
    see https://linkerd.io/checks/#l5d-injection-disabled for hints

Status check results are √

Linkerd extensions checks
=========================

linkerd-viz
-----------
√ linkerd-viz Namespace exists
√ linkerd-viz ClusterRoles exist
√ linkerd-viz ClusterRoleBindings exist
√ tap API server has valid cert
√ tap API server cert is valid for at least 60 days
√ tap API service is running
√ linkerd-viz pods are injected
√ viz extension pods are running
√ prometheus is installed and configured correctly
√ can initialize the client
√ viz extension self-check

Status check results are √
```

### Environment

- Kubernetes Version: Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.17", GitCommit:"5871d3360e3612052babed0c1e2f0da18389cdaa", GitTreeState:"clean", BuildDate:"2021-05-19T22:23:29Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
- Cluster Environment: (GKE, AKS, kops, ...) AKS
- Host OS: Linux
- Linkerd version: 2.10.0

**Comment by shahriak** [comment]
I ran the linkerd check --pre command before installing linkerd and found the following output. Could the lack of NET_ADMIN capabilities be causing this issue?

kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

pre-kubernetes-setup
--------------------
√ control plane namespace does not already exist
√ can create non-namespaced resources
√ can create ServiceAccounts
√ can create Services
√ can create Deployments
√ can create CronJobs
√ can create ConfigMaps
√ can create Secrets
√ can read Secrets
√ can read extension-apiserver-authentication configmap
‼ no clock skew detected
    clock skew detected for node(s): aks-linkerd-32106900-vmss00000e, aks-linkerd-32106900-vmss00000m, aks-linkerd-32106900-vmss00000p, aks-workload-32106900-vmss000001, aks-workload-32106900-vmss000002, aks-workload-32106900-vmss000004, aks-workload-32106900-vmss000006, aks-workload-32106900-vmss000007, aks-workload-32106900-vmss000009, aks-workload-32106900-vmss00000b, aks-workload-32106900-vmss00000c, aks-workload-32106900-vmss00000d, aks-workload-32106900-vmss00000g, aks-workload-32106900-vmss00000h, aks-workload-32106900-vmss00000i, aks-workload-32106900-vmss00000j, aks-workload-32106900-vmss00000l, aks-workload-32106900-vmss00000m, aks-workload-32106900-vmss00000p, aks-workload-32106900-vmss00000q, aks-workload-32106900-vmss00000r, aks-workload-32106900-vmss00000s, aks-workload-32106900-vmss00000t, aks-workload-32106900-vmss00000u, aks-workload-32106900-vmss00000w, aks-workload-32106900-vmss00000y, aks-workload-32106900-vmss000012
    see https://linkerd.io/2.10/checks/#pre-k8s-clock-skew for hints

pre-kubernetes-capability
-------------------------
‼ has NET_ADMIN capability
    found 4 PodSecurityPolicies, but none provide NET_ADMIN, proxy injection will fail if the PSP admission controller is running
    see https://linkerd.io/2.10/checks/#pre-k8s-cluster-net-admin for hints
‼ has NET_RAW capability
    found 4 PodSecurityPolicies, but none provide NET_RAW, proxy injection will fail if the PSP admission controller is running
    see https://linkerd.io/2.10/checks/#pre-k8s-cluster-net-raw for hints

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

Status check results are √

**Comment by mateiidavid** [comment]
Hey @shahriak thanks for raising this!

Let me address `NET_ADMIN` capabilities first. We generally use `NET_ADMIN` (and `NET_RAW`) to rewrite iptable rules using the initContainer. This allows the proxy to forward traffic to and from your application. With that said, `NET_ADMIN` is not a necessity if you're using a CNI. This would be my first question: are you using a CNI? Does Linkerd work well with your other services? You can read more about this here: https://linkerd.io/2.10/tasks/troubleshooting/#pre-k8s-cluster-net-admin.

The logs themselves don't tell us much, however, it might be that traffic cannot be proxied because of the (lack of) `NET_ADMIN` capabilities; it's possible the iptable rules were not set up properly? It would be helpful to bump up the log level for your proxy so we can see a few more details as to why this is failing. I think `linkerd=debug,warn` would be enough for this purpose.  You can change the log level without restarting your pod, [this doc outlines how](https://linkerd.io/2.10/tasks/modifying-proxy-log-level/#). 

Let me know what you think, after we have a bit more information it might be easier to get to the bottom of this : )

**Comment by olix0r** [comment]
Can you share any information about the target pod? The error you're seeing is a client proxy indicating that the server at `10.240.7.200:80` is not listening. Is that a pod in Kubernetes? Is it listening on port 80? Is that pod injected with Linkerd? If so, can you share proxy logs from this pod?

**Comment by shahriak** [comment]
> Hey @shahriak thanks for raising this!
> 
> Let me address `NET_ADMIN` capabilities first. We generally use `NET_ADMIN` (and `NET_RAW`) to rewrite iptable rules using the initContainer. This allows the proxy to forward traffic to and from your application. With that said, `NET_ADMIN` is not a necessity if you're using a CNI. This would be my first question: are you using a CNI? Does Linkerd work well with your other services? You can read more about this here: https://linkerd.io/2.10/tasks/troubleshooting/#pre-k8s-cluster-net-admin.
> 
> The logs themselves don't tell us much, however, it might be that traffic cannot be proxied because of the (lack of) `NET_ADMIN` capabilities; it's possible the iptable rules were not set up properly? It would be helpful to bump up the log level for your proxy so we can see a few more details as to why this is failing. I think `linkerd=debug,warn` would be enough for this purpose. You can change the log level without restarting your pod, [this doc outlines how](https://linkerd.io/2.10/tasks/modifying-proxy-log-level/#).
> 
> Let me know what you think, after we have a bit more information it might be easier to get to the bottom of this : )

yes, I am using CNI plugin. Here's logs with debug,warn turned on: https://gist.github.com/shahriak/2fb49ebf43dfdf571639881912bc1183

**Comment by adleong** [comment]
Hi @shahriak!  It seems that the gists in the original description are no longer available: https://gist.github.com/shahriak/a5763d8e5cedc997d083929114081d64

**Comment by shahriak** [comment]
I am not able to repro the issue. closing!
