### ISSUE TITLE
Regression in proxy between edge-21.5.1 and edge-21.5.3

### ISSUE THREAD

**Issue by jroper** [linkerd/linkerd2#6249]
During performance tests (10000req/s shared across two nodes, http/2), when running in `ingress-mode` but not setting the `l5d-dst-override` header, the outbound proxy fairly quickly starts outputting a dozen or so errors like this:

```
[   213.771212s]  INFO ThreadId(01) linkerd_app_core::serve: Connection closed error=connection closed before message completed
```

And then becomes completely unresponsive and never recovers. If I set `l5d-dst-override`, the problem goes away. The problem doesn't happen in `edge-21.5.1`, but does happen in `edge-21.5.3`. I can't tell you about `edge-21.5.2` because it made the `l5d-dst-override` header compulsory (which was backed out in `edge-21.5.3`), making it impossible to reproduce the error. This was in fact how I found out that I wasn't setting the header, I was bisecting between `stable-2.10.0` and `edge-21.6.2`, and when I tried `edge-21.5.2`, I got the no header error, realised I wasn't setting it, fixed it, and then the problem went away for all versions.

Since discovering that I wasn't setting the header correctly, and now that I've set it and the problem has gone away, this bug doesn't impact me, but I thought it was worth raising.

**Comment by olix0r** [comment]
Thanks for the report @jroper!
