### ISSUE TITLE
linkerd-proxy traffic splitter metrics missing in prometheus  

### ISSUE THREAD

**Issue by Abrishges** [linkerd/linkerd2#6261]
## Feature Request
Linkerd prometheus doesn't show traffic splitter weight information during traffic splitting/canary deployment. The only information available about traffic splitter in Prometheus is `trafficsplit_subscribers `and `trafficsplit_updates`.   Linkerd dashboard shows traffic splitter weight information and it will be great if this information is also available in Prometheus 

linkerd dashboard ts weight information 
![image](https://user-images.githubusercontent.com/10562495/121947086-80405980-cd0a-11eb-8f75-9c6561f9a6fa.png)

### How should the problem be solved?
The problem can be solving by adding traffic splitter weight metrics and progress information available in Prometheus, the same way we have it in linkerd dashboard, as shown above

**Comment by olix0r** [comment]
The linkerd dashboard is displaying this information by looking up the traffic split resources in the Kubernetes API. So I think you're looking for some kind of controller that watches all traffic splits in a cluster and exports prometheus gauges reflecting the cluster's state? This is probably something that belongs in the https://github.com/linkerd/linkerd-smi extension.
