### ISSUE TITLE
injector: Set LINKERD2_PROXY_INBOUND_PORTS

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#6267]
The injector should configure the proxy with a list of (non-proxy) ports exposed by the pod spec. Specifically:

- Extract all port numbers from all non-proxy containers in a workload spec;
- Add a variable to the proxy's environment, `LINKERD2_PROXY_INBOUND_PORTS`, with a list of port numbers exposed by the workload;
- The injector _should_ probably handle the case where other web hooks may add containers that expose ports; so we may need to support being reinvoked to detect this situation.

This will support inbound policy discovery by proxies.

**Comment by alpeb** [comment]
xref #3750 for another use case where reinvocation would be desirable
