### ISSUE TITLE
Specify ports inclusively (not with --skip-ports)

### ISSUE THREAD

**Issue by elig-salt** [linkerd/linkerd2#6322]
## Feature Request
We would like to ask for a an option to specify which ports to go through specifically with a flag such as:
`linkerd inject --include-ports XXX`

### What problem are you trying to solve?
We have a lot of outgoing traffic to databases, logs, metrics - destinations we're not interested in TCP metrics for.
Since we have only 1 or 2 ports open for HTTP traffic - we want to ignore all the rest.
This could be a bit tedious to configure for many services.

We would also like to avoid a situation - where some developer adds a feature to the deployment (some outgoing request somewhere) - and connections would drop because we forgot to skip those.

Providing a whitelist of ports would make things much easier,
and we also think this can speed up onboarding to Linkerd :)

**Comment by adleong** [comment]
While it's not particularly ergonomic, I think you can accomplish this with `--skip-ports` and port ranges.  For example, to include only port 8888 you could specify `--skip-ports 1-8887,8889-65535`

**Comment by elig-salt** [comment]
> While it's not particularly ergonomic, I think you can accomplish this with `--skip-ports` and port ranges. For example, to include only port 8888 you could specify `--skip-ports 1-8887,8889-65535`

Thought possible, it does feel a bit hacky :)
Plus - if we have ports `8081`, `3000`, `50004` and `50005`
It's hard to see it by looking at:
`1-2999,3001-8080,8082-50003,50006-65535`

I feel like this use case is strong enough to have a proper flag

**Comment by adleong** [comment]
Yup, it's awkward for sure.  However, it's a priority to keep Linkerd's configuration as simple as possible.  Having both `--skip-ports` and `--include-ports` would incur some complexity in how these configurations are stored and how to resolve interactions between the two.

**Comment by elig-salt** [comment]
I see, we'll use --skip and try to produce the same result on our end. Thanks !
