### ISSUE TITLE
Emit events from the identity controller

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#6324]
There's relatively little audit trail around certificates issued by the identity controller. To fix this, we should update the identity controller to emit Kubernetes events--like the proxy-injector does--as certificates are issued.

- Events should include at least the identity string, a digest of the certificate, and the certificate expiration.
- Ideally, these events should be associated with specific pods. Does the identity controller have enough information to know the source IP? This may warrant proxy changes to support this (via the `Forwarded` header perhaps?). This shouldn't be a blocker but is worth investigating as we implement the initial version of this.
- I'm not sure if there are any concerns about adding load to the system, though I suppose these events should be fairly rare.

**Comment by wmorgan** [comment]
Is there any value to having similar events emitted by the proxies, in such a way that they could be reconciled?

**Comment by olix0r** [comment]
@wmorgan the proxy doesn't talk to the Kubernetes API (and it shouldn't imo). The identity service is a fine source of truth for this information.

**Comment by adleong** [comment]
Fixed by https://github.com/linkerd/linkerd2/pull/6364
