### ISSUE TITLE
Expose client-go cache metrics in control plane components

### ISSUE THREAD

**Issue by alpeb** [linkerd/linkerd2#6354]
Control plane components such as `linkerd-proxy-injector` and `linkerd-destination` create multiple client-go informers whose caches can potentially grow a lot in big clusters that keep track of lots of workloads and resources. In order to verify that assumption we need to expose informer metrics.
It appears there's some instrumentation in place as shown in `reflector_metrics.go`(https://github.com/kubernetes/client-go/blob/v0.21.2/tools/cache/reflector_metrics.go) that we could wire-in.

**Comment by akshitgrover** [comment]
@alpeb 
Can I take a shot at this
I might need some help along the way

**Comment by alpeb** [comment]
Awesome, thanks @akshitgrover !
I'm not familiar myself with that mechanism either, so some experimentation will be required. You can start by looking into `controller/proxy-injector/webhook.go`, how it wires up prometheus metrics, and see how that can be extended to include client-go metrics.

**Comment by akshitgrover** [comment]
Even I have not tried exposing prometheus metrics as such.
This would be a great learning experience
Will be working on this on the weekend
I hope the timeline on this PR is not too tight

`controller/proxy-injector/webhook.go`
Also, I saw this `[controller/k8s/api.go](https://github.com/linkerd/linkerd2/blob/main/controller/k8s/api.go)` This can be our hook point for the metrics, As from the high level investigation it looks like this where all other packages use this to get informers.

**Comment by akshitgrover** [comment]
Sorry for the delay on this
I have been stuck with some other tasks for quite a while
An update on this
I came across this controller-runtime repo
It implements reflector metrics, I am digging into this to find out a hook point
https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/metrics/client_go_adapter.go#L184
