### ISSUE TITLE
Unable to install linkerd viz on DigitalOcean due to missing node's podCIDR 

### ISSUE THREAD

**Issue by WoLfulus** [linkerd/linkerd2#6398]
### What is the issue?

I can't install linkerd viz due to a failing check. The problem seems to occur here because podCIDR is "missing" from spec:

https://github.com/linkerd/linkerd2/blob/ebbb3182a9a09467eac1204b3b517a3caa864027/pkg/healthcheck/healthcheck.go#L1901-L1905

For some reason DigitalOcean nodes doesn't seem to return podCIDR in its spec. I'm not sure if this is a permission issue or not (#6288 ). I couldn't find anything related to this anywhere and I'm not even sure if this is a problem with linkerd itself since DigitalOcean provides linkerd as a 1-click app - I imagine it should be compatible? 

### How can it be reproduced?

I think trying to install linkerd in any DigitalOcean kubernetes cluster would do since I tried recycling the nodes and recreating the cluster, and the same behavior continues. The only field present in spec is `providerID`. 

### Logs, error output, etc

> kubectl get nodes -o yaml | grep spec -C 5

```
    ...
  spec:
    providerID: digitalocean://...
  status:
    ...
---
    ...
  spec:
    providerID: digitalocean://...
  status:
    ...
```

#### `linkerd check` output

```text
× cluster networks contains all node podCIDRs
    invalid CIDR address: 
    see https://linkerd.io/2/checks/#l5d-cluster-networks-cidr for hints
```

### Environment

- Kubernetes Version: 1.20.7-do.0
- Cluster Environment: DigitalOcean
- Host OS: ??
- Linkerd version: 

```
Client version: edge-21.6.5
Server version: edge-21.6.5
```

### Possible solution

Unsure.

**Comment by alpeb** [comment]
Thanks @WoLfulus , I was able to reproduce that problem in DO as well. I'll issue a PR to get around that.

**Comment by alpeb** [comment]
It's a consistency check only, but I can see that check is also blocking the installation of the viz extension. Everything else should be ok as long as those default CIDRs are respected, which seems to be the case. We'll try to get that fix in this week's edge, so please keep an eye open for that one so you can give it another try :wink:

**Comment by WoLfulus** [comment]
I already built a version locally to get around that one ;)

Thanks!
