### ISSUE TITLE
Confusing error while installing linkerd cli

### ISSUE THREAD

**Issue by rdileep13** [linkerd/linkerd2#6423]
## Bug Report
When installing linkerd cli with  'curl -sL https://run.linkerd.io/install | sh' displays below error
```
Failed to create the file linkerd2-cli-stable-2.10.2-linux-amd64:
Warning: Permission denied
...
curl: (23) Failure writing output to destination
```

### What is the issue?
There was no space in /tmp where installation script was trying to create a directory to copy the file. Fails while copying the file (directory is created)

### How can it be reproduced?
Run 'curl -sL https://run.linkerd.io/install | sh' on any box without enough storage

### Logs, error output, etc
Copied above

#### `linkerd check` output

```text
Not applicable
```

### Environment

- Kubernetes Version: kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}

- Cluster Environment: (GKE, AKS, kops, ...) Minikube on Local
- Host OS: Ubuntu 21.X on Virtual Box
- Linkerd version: N/A

### Possible solution
Option 1:
Modify script to check for space and return right error

Option 2: Add an entry in troubleshooting section for this specific issue with logs

### Additional context
I was able to workaround this with below steps:

1. download script from above location to a local file
2. edit the file and set $tmpdir to /var
3. chmod +x file
4. run it

Once it downloaded cli binary to /var, it installed successfully

**Comment by rdileep13** [comment]
An additional option could be to ask the user for installation location (directory)

**Comment by adleong** [comment]
Hi @rdileep13!  If the https://run.linkerd.io/install script doesn't work for you, you can also download and install the Linkerd CLI binary directly from the releases page: https://github.com/linkerd/linkerd2/releases

**Comment by rdileep13** [comment]
That's right. We can manually download it. However, the instructions for that are absent or incomplete. For example, if I go into releases, it shows all releases (edge and cli). I had to scroll to the right page to get cli.
Secondly, once I download the cli, further steps are not documented (ie copying that in /usr/local/bin, chmod and symlink).

As part of this bug, I was wondering if it is possible to check disk size or if first approach fails, have user specify download directory. In the worst case, we could enhance documentation and add notes in troubleshooting section for this.

Please let me know your thoughts.

**Comment by kleimkuhler** [comment]
@rdileep13 We'll happily take documentation contributions that would have been helpful for the situation you encountered!

I'm not inclined to add additional error handling into the install script though; it's meant to be a convenience for installing the CLI. Since each situation and machine is different, there is the potential for a lot of additional complexity to handle all possible errors that a user could encounter.
