### ISSUE TITLE
Bad Certificate Issue with Linkerd 2.95 installation -'Sending fatal alert BadCertificate'

### ISSUE THREAD

**Issue by tejeshwari** [linkerd/linkerd2#6427]
Bug Report
Bad Certificate Issue with Linkerd 2.9.5 installation -'Sending fatal alert BadCertificate'

What is the issue?

We have tried to install Linkerd 2.9.5 stable version with our certificates . Certificates were generated from Step Tool. As we had  few issues with certs and switched to install 2.9.5 manually with the default certificates that were generated with the command  **linkerd install --ha  --ignore-cluster > linkerd.yaml** .Post installation, the pods seems running but with an error in **linkerd-controller** and **linkerd-identity**

### Logs, error output, etc
**Linkerd-controller logs**

WARN ThreadId(01) dst: rustls::session: Sending fatal alert BadCertificate
 WARN ThreadId(01) dst: rustls::session: Sending fatal alert BadCertificate
ERROR ThreadId(02) daemon:identity: linkerd2_proxy_identity::certify: Received invalid ceritficate: invalid certificate: CertNotValidYet
 ERROR ThreadId(02) daemon:identity: linkerd2_proxy_identity::certify: Received invalid ceritficate: invalid certificate: CertNotValidYet
 ERROR ThreadId(02) daemon:identity: linkerd2_proxy_identity::certify: Received invalid ceritficate: invalid certificate: CertNotValidYet
 ERROR ThreadId(02) daemon:identity: linkerd2_proxy_identity::certify: Received invalid ceritficate: invalid certificate: CertNotValidYet
ERROR ThreadId(02) daemon:identity: linkerd2_proxy_identity::certify: Received invalid ceritficate: invalid certificate: CertNotValidYet

**Linkerd-Identity logs** 

 ERROR ThreadId(01) inbound:accept{peer.addr=XX.XX.XX.XX:37498 target.addr=XX.XX.XX.XX:8080}: rustls::session: TLS alert received: Message {
    typ: Alert,
    version: TLSv1_2,
    payload: Alert(
        AlertMessagePayload {
            level: Fatal,
            description: BadCertificate,
        },
    ),

#### `linkerd check` output

kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version
linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running
√ can initialize the client
√ can query the control plane API
linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist
linkerd-identity
----------------
√ certificate config is valid
√ trust anchors are using supported crypto algorithm
√ trust anchors are within their validity period
√ trust anchors are valid for at least 60 days
√ issuer cert is using supported crypto algorithm
√ issuer cert is within its validity period
√ issuer cert is valid for at least 60 days
√ issuer cert is issued by the trust anchor
linkerd-webhooks-and-apisvc-tls
-------------------------------
√ tap API server has valid cert
√ tap API server cert is valid for at least 60 days
√ proxy-injector webhook has valid cert
√ proxy-injector cert is valid for at least 60 days
√ sp-validator webhook has valid cert
√ sp-validator cert is valid for at least 60 days

linkerd-api
-----------
/ pod/linkerd-sp-validator-776588dbff-zl485 container linkerd-proxy is not ready
### Environment

- Linkerd version: 2.9.5

**Comment by rdileep13** [comment]
I'm a novice trying to come up to speed with linkerd.

I am assuming this is the command to reproduce the issue - linkerd install --ha --ignore-cluster > linkerd.yaml , ie observing logs after that. Let me know if anything else is required.

That apart, based on the past experience CertNotValidYet implies clock skew on your instances. Let's say certificate was issued to be valid from tomorrow and you try to use it today, then you would see this issue.
This implies that the target instance is running ahead of current clock.

Can you please check that?

Again, I could be wrong. Please check for 'linkerd official' response on this bug.

**Comment by adleong** [comment]
Hello @tejeshwari and @rdileep13 

Are you following these instructions for generating certs and installing Linkerd? https://linkerd.io/2.10/tasks/generate-certificates/

Can you share the exact command you used to generate the certificates using `step`?

Note that in order for Linkerd to use the certificates you generated, you'll need to pass the `--identity-issuer-key-file`, `--identity-issuer-certificate-file`, and `--identity-trust-anchors-file` flags.  See the above tutorial for more details.

**Comment by adleong** [comment]
Closed due to inactivity.
