### ISSUE TITLE
Add metrics data to ReplicaSets

### ISSUE THREAD

**Issue by JasonMorgan** [linkerd/linkerd2#6429]
## Feature Request

I'd like to see Linkerd metrics for ReplicaSets

### What problem are you trying to solve?

If you look at issue #5189 you can't get data from a rollout because we don't handle that object type. It does however create a replicaSet which would be just as good as watching a rollout.

### How should the problem be solved?

After talking with @alpeb it sounds like there are 2 main fixes:

- Populate metrics for replicaSets that don't have parent objects in Linkerd
- Populate metrics for all replicaSets

### Any alternatives you've considered?

Do nothing

### How would users interact with this feature?

Via the Linkerd dashboard or `linkerd viz stat replicaset`

**Comment by aryan9600** [comment]
I might be wrong here, but isn't this already supported via `linkerd viz stat rs`?

**Comment by alpeb** [comment]
@aryan9600 You'll see calling that will return empty stats. The problem starts in [GetOwnerKindAndName](https://github.com/linkerd/linkerd2/blob/30a50e7d430b8bcc85efddd5393d8c272a415ba5/controller/k8s/api.go#L469): when injecting the pod, if the parent is a ReplicaSet then the ReplicaSet's parent is fetched and returned as the pod's owner, which in this case is the Rollout workload. This is then used in [parse](https://github.com/linkerd/linkerd2/blob/30a50e7d430b8bcc85efddd5393d8c272a415ba5/pkg/inject/inject.go#L431) to set a label pointing to that owner workload, but Rollout types are not considered there, so the label is not set.

**Comment by olix0r** [comment]
The "correct" solution is to make our metrics labeling generic enough to support arbitrary resource hierarchies without special-casing deployments. An interim fix might be to fallback replica sets when a deployment cannot be discovered.
