### ISSUE TITLE
Latency when linkerD enabled to Azure MySQL

### ISSUE THREAD

**Issue by ctienshi** [linkerd/linkerd2#6449]
### What is the issue?
When linkerD is injected to a pod running in AKS, the initial connection to the MySQL takes around 100 seconds. But when the linkerD injection is disabled it takes around 2 seconds.

### How can it be reproduced?
Run a pod with linkerD injected and connect to a Azure MySQL server from the pod. The latency would be around 100 seconds

### Logs, error output, etc
N/A

### Environment

- Kubernetes Version: 1.19.11
- Cluster Environment: AKS
- Host OS: Linux
- Linkerd version: 2.10.0

### Possible solution
N/A

### Additional context
N/A

**Comment by olix0r** [comment]
You're likely hitting protocol detection timeouts. You likely need to configure outbound skip ports as described here https://linkerd.io/2.10/features/protocol-detection/#skipping-the-proxy

**Comment by ctienshi** [comment]
Thanks @olix0r . We will check on this
