### ISSUE TITLE
Check cert provided by external issuers is indeed an intermediate cert

### ISSUE THREAD

**Issue by alpeb** [linkerd/linkerd2#6453]
When the issuer certificate is dynamically loaded [here](https://github.com/linkerd/linkerd2/blob/136edffaa4b63a6321f78b71600848bd791f3a90/pkg/identity/service.go#L113), add to the list of validations that it is indeed an intermediate certificate and not a leaf.
One example where this problem was found was #6428, where Cert-manager was configured with Vault as an issuer, but a misconfig had Vault issue a leaf cert despite the `isCA: true` field in the `Certificate` resource for the linkerd issuer.

**Comment by importhuman** [comment]
I'd like to take this up!

**Comment by alpeb** [comment]
@importhuman I believe @rumanzo is already looking into it, so let's leave him some time to tackle it. I can guide you in the #contributors slack channel selecting a first issue if you're so inclined :slightly_smiling_face:

**Comment by rumanzo** [comment]
> @importhuman I believe @rumanzo is already looking into it, so let's leave him some time to tackle it. I can guide you in the #contributors slack channel selecting a first issue if you're so inclined 🙂

Yes, I actually wrote a code and checked it. Will make PR later
