### ISSUE TITLE
Published Helm Charts depends on local file based unpublished chart

### ISSUE THREAD

**Issue by darkn3rd** [linkerd/linkerd2#6462]
There are a few helm charts that are published that have a dependency on the partials  chart from a file based reference.  The user is required to download the source code to be able to have access to the unpublished chart.

### Steps

Observe the dependency and note that this cannot be resolved.

This is what I found with a brief scan:

* https://artifacthub.io/packages/helm/linkerd2-edge/jaeger
* https://artifacthub.io/packages/helm/linkerd2/linkerd2
* https://artifacthub.io/packages/helm/linkerd2/linkerd-viz
* https://artifacthub.io/packages/helm/linkerd2/linkerd2-cni
* https://artifacthub.io/packages/helm/linkerd2/linkerd-multicluster
* https://artifacthub.io/packages/helm/linkerd2-edge/linkerd-jaeger
* https://artifacthub.io/packages/helm/linkerd2-edge/jaeger
* https://artifacthub.io/packages/helm/linkerd2-edge/linkerd2
* https://artifacthub.io/packages/helm/linkerd2-edge/linkerd2-cni
* https://artifacthub.io/packages/helm/linkerd2-edge/linkerd-multicluster
* https://artifacthub.io/packages/helm/linkerd2-edge/linkerd-viz

### Actual Results

The charts will nave a non-resolvable unpublished chart, for example:

```
dependencies:
- name: partials
  version: 0.1.0
  repository:  file://../../../charts/partials
```

This was found in these locations:

* https://github.com/linkerd/linkerd2/blob/main/viz/charts/linkerd-viz/requirements.yaml
* https://github.com/linkerd/linkerd2/blob/main/multicluster/charts/linkerd-multicluster/requirements.yaml
* https://github.com/linkerd/linkerd2/blob/main/jaeger/charts/linkerd-jaeger/requirements.yaml
* https://github.com/linkerd/linkerd2/blob/main/charts/linkerd2/requirements.yaml
* https://github.com/linkerd/linkerd2/blob/main/charts/linkerd2-cni/requirements.yaml

### Expected Results

Any dependencies in published charts would be to published charts.

**Comment by Pothulapati** [comment]
Hey @darkn3rd,

>  The user is required to download the source code to be able to have access to the unpublished chart.

I don't think that is the case. Currently, The main charts i.e `linkerd` and the extensions that are published, have the dep chart i.e `partials` (which hosts common templating functions) inside their `./charts` folder where dependencies are rendered into. Hence,

```bash
on ⛵ kind-kind  linkerd-smi on 🌱 taru [📦📝🤷‍] via 🐼 v1.16.5 via  
 ➜ helm repo add linkerd2-edge https://helm.linkerd.io/edge  

on ⛵ kind-kind  linkerd-smi on 🌱 taru [📦📝🤷‍] via 🐼 v1.16.5 via  
 ➜ helm pull linkerd-edge/linkerd-viz --untar                    ~/work/linkerd-smi

on ⛵ kind-kind  linkerd-smi on 🌱 taru [📦📝🤷‍] via 🐼 v1.16.5 via  
➜ ls linkerd-viz/charts                                         ~/work/linkerd-smi
partials

on ⛵ kind-kind  linkerd-smi on 🌱 taru [📦📝🤷‍] via 🐼 v1.16.5 via  
➜ ls linkerd-viz/charts/partials                                ~/work/linkerd-smi
Chart.yaml  README.md  README.md.gotmpl  templates  values.yaml
```

This is done because users would never interact with `partials` directly, and hence we didn't find a need to version and publish it separately!

Why do you think it has to be published? 🤔
