### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by tejeshwari** [linkerd/linkerd2#6488]
### What is the issue?

We have tried to install Linkerd 2.9.5 stable version with our certificates .

### How can it be reproduced?
linkerd check 

### Logs, error output, etc
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x38 pc=0x1379e1b]

#### `linkerd check` output
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

```console
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x38 pc=0x1379e1b]

goroutine 1 [running]:
github.com/linkerd/linkerd2/pkg/healthcheck.(*HealthChecker).checkCertificatesConfig(0xc0004829c0, 0xc000084098, 0xc00080f908, 0x4305a6, 0x0, 0xc00077e0f0, 0xc000239b00)
        /linkerd-build/pkg/healthcheck/healthcheck.go:1359 +0x8b
github.com/linkerd/linkerd2/pkg/healthcheck.(*HealthChecker).allCategories.func47(0x1a92ea0, 0xc000239b00, 0x6fc23ac00, 0x1a92ea0)
        /linkerd-build/pkg/healthcheck/healthcheck.go:874 +0x3a
github.com/linkerd/linkerd2/pkg/healthcheck.(*HealthChecker).runCheck(0xc0004829c0, 0x1833c7c, 0x10, 0xc00080faa8, 0xc00080fbe0, 0xc00078c000)
        /linkerd-build/pkg/healthcheck/healthcheck.go:1247 +0x14e
github.com/linkerd/linkerd2/pkg/healthcheck.(*HealthChecker).RunChecks(0xc0004829c0, 0xc00080fbe0, 0x4)
        /linkerd-build/pkg/healthcheck/healthcheck.go:1216 +0x29f
github.com/linkerd/linkerd2/cli/cmd.runChecksTable(0x1a50cc0, 0xc0000c80f0, 0xc0004829c0, 0x0)
        /linkerd-build/cli/cmd/check.go:265 +0x132
github.com/linkerd/linkerd2/cli/cmd.runChecks(0x1a50cc0, 0xc0000c80f0, 0x1a50cc0, 0xc0000c8140, 0xc0004829c0, 0x1825b76, 0x5, 0xc)
        /linkerd-build/cli/cmd/check.go:219 +0x62
github.com/linkerd/linkerd2/cli/cmd.configureAndRunChecks(0x1a50cc0, 0xc0000c80f0, 0x1a50cc0, 0xc0000c8140, 0x0, 0x0, 0xc0002784e0, 0x0, 0x0)
        /linkerd-build/cli/cmd/check.go:206 +0x553
github.com/linkerd/linkerd2/cli/cmd.newCmdCheck.func1(0xc00033a780, 0xc000776050, 0x0, 0x1, 0x0, 0x0)
        /linkerd-build/cli/cmd/check.go:132 +0x69
github.com/spf13/cobra.(*Command).execute(0xc00033a780, 0xc000776030, 0x1, 0x1, 0xc00033a780, 0xc000776030)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x467
github.com/spf13/cobra.(*Command).ExecuteC(0x2645ea0, 0x0, 0x157bac0, 0xc000076058)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x302
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
```

- Kubernetes Version: 1.18.14
- Linkerd version: 2.10.0

**Comment by alpeb** [comment]
This might be caused by an invalid `linkerd-config` ConfigMap. Could you please share the contents of that resource?

**Comment by tejeshwari** [comment]
@alpeb here is the ConfigMap

kind: ConfigMap
apiVersion: v1
metadata:
  name: linkerd-config
  namespace: linkerd
  labels:
    linkerd.io/control-plane-component: controller
    linkerd.io/control-plane-ns: linkerd
  annotations:
    linkerd.io/created-by: linkerd/cli stable-2.10.0
data:
  
  values: |
    controllerImage: cr.l5d.io/linkerd/controller
    controllerReplicas: 3
    controllerUID: 2103
    dashboard:
      replicas: 1
    debugContainer:
      image:
        name: cr.l5d.io/linkerd/debug
        pullPolicy: IfNotPresent
        version: stable-2.10.0
    destinationProxyResources: null
    destinationResources:
      cpu:
        limit: ""
        request: 100m
      memory:
        limit: 250Mi
        request: 50Mi
    disableHeartBeat: false
    enableH2Upgrade: true
    enablePodAntiAffinity: true
    global:
      cliVersion: linkerd/cli stable-2.10.0
      clusterDomain: cluster.local
      clusterNetworks: 10.0.0.0/8,100.64.0.0/10,172.16.0.0/12,192.168.0.0/16
      cniEnabled: false
      controlPlaneTracing: false
      controllerComponentLabel: linkerd.io/control-plane-component
      controllerImageVersion: stable-2.10.0
      controllerLogLevel: info
      controllerNamespaceLabel: linkerd.io/control-plane-ns
      createdByAnnotation: linkerd.io/created-by
      enableEndpointSlices: false
      grafanaUrl: ""
      highAvailability: true
      identityTrustAnchorsPEM: |
        -----BEGIN CERTIFICATE-----
        MIIBgzCCASmgAwIBAgIBATAKBggqhkjOPQQDAjApMScwJQYDVQQDEx5pZGVudGl0
        eS5saW5rZXJkLmNsdXN0ZXIubG9jYWwwHhcNMjEwNzE0MDYwNTQ3WhcNMjIwNzE0
        MDYwNjA3WjApMScwJQYDVQQDEx5pZGVudGl0eS5saW5rZXJkLmNsdXN0ZXIubG9j
        YWwwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQ9/+QrL9PFvBSP/kl7BksTpjKN
        w+NFJHFD7MjaOpH1ATqKSwGeJbe5xa+R5Td7tbajRBCOwNgo1+MqKKjIB3ypo0Iw
        QDAOBgNVHQ8BAf8EBAMCAQYwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMC
        MA8GA1UdEwEB/wQFMAMBAf8wCgYIKoZIzj0EAwIDSAAwRQIhAJRnPB9vwU9z4Go9
        nVHuNMkRhjo9LG9ac86kYMEJYWOXAiB5qfOg3xgz8yRZBRUBOayyNCSylNDIR+52
        YTZnt3br+g==
        -----END CERTIFICATE-----
      identityTrustDomain: cluster.local
      imagePullPolicy: IfNotPresent
      imagePullSecrets: null
      linkerdNamespaceLabel: linkerd.io/is-control-plane
      linkerdVersion: stable-2.10.0
      namespace: linkerd
      podAnnotations: {}
      podLabels: {}
      prometheusUrl: ""
      proxy:
        capabilities: null
        disableIdentity: false
        disableTap: false
        enableExternalProfiles: false
        image:
          name: cr.l5d.io/linkerd/proxy
          pullPolicy: IfNotPresent
          version: stable-2.10.0
        inboundConnectTimeout: 100ms
        isGateway: false
        isIngress: false
        logFormat: plain
        logLevel: warn,linkerd=info
        opaquePorts: ""
        outboundConnectTimeout: 1000ms
        ports:
          admin: 4191
          control: 4190
          inbound: 4143
          outbound: 4140
        requireIdentityOnInboundPorts: ""
        resources:
          cpu:
            limit: ""
            request: 100m
          memory:
            limit: 250Mi
            request: 20Mi
        saMountPath: null
        trace:
          collectorSvcAccount: default
          collectorSvcAddr: ""
        uid: 2102
        waitBeforeExitSeconds: 0
      proxyContainerName: linkerd-proxy
      proxyInit:
        capabilities: null
        closeWaitTimeoutSecs: 0
        ignoreInboundPorts: 25,443,587,3306,11211,5432
        ignoreOutboundPorts: 25,443,587,3306,11211,5432
        image:
          name: cr.l5d.io/linkerd/proxy-init
          pullPolicy: IfNotPresent
          version: v1.3.9
        resources:
          cpu:
            limit: 100m
            request: 10m
          memory:
            limit: 50Mi
            request: 10Mi
        saMountPath: null
        xtMountPath:
          mountPath: /run
          name: linkerd-proxy-init-xtables-lock
          readOnly: false
      proxyInjectAnnotation: linkerd.io/inject
      proxyInjectDisabled: disabled
      workloadNamespaceLabel: linkerd.io/workload-ns
    grafana:
      enabled: true
      resources:
        cpu:
          limit: ""
          request: 100m
        memory:
          limit: 1024Mi
          request: 50Mi
    heartbeatResources:
      cpu:
        limit: ""
        request: 100m
      memory:
        limit: 250Mi
        request: 50Mi
    heartbeatSchedule: 0 0 * * *
    identity:
      issuer:
        clockSkewAllowance: 20s
        crtExpiry: "2022-07-14T06:06:07Z"
        crtExpiryAnnotation: linkerd.io/identity-issuer-expiry
        issuanceLifetime: 24h0m0s
        scheme: linkerd.io/tls
        tls:
          crtPEM: |
            -----BEGIN CERTIFICATE-----
            MIIBgzCCASmgAwIBAgIBATAKBggqhkjOPQQDAjApMScwJQYDVQQDEx5pZGVudGl0
            eS5saW5rZXJkLmNsdXN0ZXIubG9jYWwwHhcNMjEwNzE0MDYwNTQ3WhcNMjIwNzE0
            MDYwNjA3WjApMScwJQYDVQQDEx5pZGVudGl0eS5saW5rZXJkLmNsdXN0ZXIubG9j
            YWwwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQ9/+QrL9PFvBSP/kl7BksTpjKN
            w+NFJHFD7MjaOpH1ATqKSwGeJbe5xa+R5Td7tbajRBCOwNgo1+MqKKjIB3ypo0Iw
            QDAOBgNVHQ8BAf8EBAMCAQYwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMC
            MA8GA1UdEwEB/wQFMAMBAf8wCgYIKoZIzj0EAwIDSAAwRQIhAJRnPB9vwU9z4Go9
            nVHuNMkRhjo9LG9ac86kYMEJYWOXAiB5qfOg3xgz8yRZBRUBOayyNCSylNDIR+52
            YTZnt3br+g==
            -----END CERTIFICATE-----
    identityProxyResources: null
    identityResources:
      cpu:
        limit: ""
        request: 100m
      memory:
        limit: 250Mi
        request: 10Mi
    installNamespace: true
    nodeSelector:
      beta.kubernetes.io/os: linux
    omitWebhookSideEffects: false
    profileValidator:
      caBundle: ""
      crtPEM: ""
      externalSecret: false
      namespaceSelector:
        matchExpressions:
        - key: config.linkerd.io/admission-webhooks
          operator: NotIn
          values:
          - disabled
    prometheus:
      enabled: true
      resources:
        cpu:
          limit: ""
          request: 300m
        memory:
          limit: 8192Mi
          request: 300Mi
    proxyInjector:
      caBundle: ""
      crtPEM: ""
      externalSecret: false
      namespaceSelector:
        matchExpressions:
        - key: config.linkerd.io/admission-webhooks
          operator: NotIn
          values:
          - disabled
    proxyInjectorProxyResources: null
    proxyInjectorResources:
      cpu:
        limit: ""
        request: 100m
      memory:
        limit: 250Mi
        request: 50Mi
    publicAPIProxyResources: null
    publicAPIResources:
      cpu:
        limit: ""
        request: 100m
      memory:
        limit: 250Mi
        request: 50Mi
    restrictDashboardPrivileges: false
    spValidatorProxyResources: null
    spValidatorResources:
      cpu:
        limit: ""
        request: 100m
      memory:
        limit: 250Mi
        request: 50Mi
    tap:
      caBundle: ""
      crtPEM: ""
      externalSecret: false
    tapProxyResources: null
    tapResources:
      cpu:
        limit: ""
        request: 100m
      memory:
        limit: 250Mi
        request: 50Mi
    tolerations: null
    tracing:
      enabled: false
    webImage: cr.l5d.io/linkerd/web
    webProxyResources: null
    webResources:
      cpu:
        limit: ""
        request: 100m
      memory:
        limit: 250Mi
        request: 50Mi
    webhookFailurePolicy: Fail

**Comment by alpeb** [comment]
You mentioned you were trying to install v2.9.5 but apparently you have already installed v2.10.0. Are you trying to downgrade?

**Comment by tejeshwari** [comment]
Oh My bad. I am installing 2.9.5. I have installed multiple versions was confused.

Here is the one that I have currently .

kind: ConfigMap
apiVersion: v1
metadata:
  name: linkerd-config
  namespace: linkerd
  labels:
    linkerd.io/control-plane-component: controller
    linkerd.io/control-plane-ns: linkerd
  annotations:
    linkerd.io/created-by: linkerd/cli stable-2.9.5
data:
  values: |
    controllerImage: cr.l5d.io/linkerd/controller
    controllerReplicas: 3
    controllerUID: 2103
    dashboard:
      replicas: 1
    debugContainer:
      image:
        name: cr.l5d.io/linkerd/debug
        pullPolicy: IfNotPresent
        version: stable-2.9.5
    destinationProxyResources: null
    destinationResources:
      cpu:
        limit: ""
        request: 100m
      memory:
        limit: 250Mi
        request: 50Mi
    disableHeartBeat: false
    enableH2Upgrade: true
    enablePodAntiAffinity: true
    global:
      cliVersion: linkerd/cli stable-2.9.5
      clusterDomain: cluster.local
      clusterNetworks: 10.0.0.0/8,100.64.0.0/10,172.16.0.0/12,192.168.0.0/16
      cniEnabled: false
      controlPlaneTracing: false
      controllerComponentLabel: linkerd.io/control-plane-component
      controllerImageVersion: stable-2.9.5
      controllerLogLevel: info
      controllerNamespaceLabel: linkerd.io/control-plane-ns
      createdByAnnotation: linkerd.io/created-by
      enableEndpointSlices: false
      grafanaUrl: ""
      highAvailability: true
      identityTrustAnchorsPEM: |
        -----BEGIN CERTIFICATE-----
        MIIBgzCCASmgAwIBAgIBATAKBggqhkjOPQQDAjApMScwJQYDVQQDEx5pZGVudGl0
        eS5saW5rZXJkLmNsdXN0ZXIubG9jYWwwHhcNMjEwNzE0MDYwNTQ3WhcNMjIwNzE0
        MDYwNjA3WjApMScwJQYDVQQDEx5pZGVudGl0eS5saW5rZXJkLmNsdXN0ZXIubG9j
        YWwwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQ9/+QrL9PFvBSP/kl7BksTpjKN
        w+NFJHFD7MjaOpH1ATqKSwGeJbe5xa+R5Td7tbajRBCOwNgo1+MqKKjIB3ypo0Iw
        QDAOBgNVHQ8BAf8EBAMCAQYwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMC
        MA8GA1UdEwEB/wQFMAMBAf8wCgYIKoZIzj0EAwIDSAAwRQIhAJRnPB9vwU9z4Go9
        nVHuNMkRhjo9LG9ac86kYMEJYWOXAiB5qfOg3xgz8yRZBRUBOayyNCSylNDIR+52
        YTZnt3br+g==
        -----END CERTIFICATE-----
      identityTrustDomain: cluster.local
      imagePullPolicy: IfNotPresent
      imagePullSecrets: null
      linkerdNamespaceLabel: linkerd.io/is-control-plane
      linkerdVersion: stable-2.9.5
      namespace: linkerd
      podAnnotations: {}
      podLabels: {}
      prometheusUrl: ""
      proxy:
        capabilities: null
        disableIdentity: false
        disableTap: false
        enableExternalProfiles: false
        image:
          name: cr.l5d.io/linkerd/proxy
          pullPolicy: IfNotPresent
          version: stable-2.9.5
        inboundConnectTimeout: 100ms
        isGateway: false
        isIngress: false
        logFormat: plain
        logLevel: warn,linkerd=info
        opaquePorts: ""
        outboundConnectTimeout: 1000ms
        ports:
          admin: 4191
          control: 4190
          inbound: 4143
          outbound: 4140
        requireIdentityOnInboundPorts: ""
        resources:
          cpu:
            limit: ""
            request: 100m
          memory:
            limit: 250Mi
            request: 20Mi
        saMountPath: null
        trace:
          collectorSvcAccount: default
          collectorSvcAddr: ""
        uid: 2102
        waitBeforeExitSeconds: 0
      proxyContainerName: linkerd-proxy
      proxyInit:
        capabilities: null
        closeWaitTimeoutSecs: 0
        ignoreInboundPorts: 25,443,587,3306,11211,5432
        ignoreOutboundPorts: 25,443,587,3306,11211,5432
        image:
          name: cr.l5d.io/linkerd/proxy-init
          pullPolicy: IfNotPresent
          version: v1.3.9
        resources:
          cpu:
            limit: 100m
            request: 10m
          memory:
            limit: 50Mi
            request: 10Mi
        saMountPath: null
        xtMountPath:
          mountPath: /run
          name: linkerd-proxy-init-xtables-lock
          readOnly: false
      proxyInjectAnnotation: linkerd.io/inject
      proxyInjectDisabled: disabled
      workloadNamespaceLabel: linkerd.io/workload-ns
    grafana:
      enabled: true
      resources:
        cpu:
          limit: ""
          request: 100m
        memory:
          limit: 1024Mi
          request: 50Mi
    heartbeatResources:
      cpu:
        limit: ""
        request: 100m
      memory:
        limit: 250Mi
        request: 50Mi
    heartbeatSchedule: 0 0 * * *
    identity:
      issuer:
        clockSkewAllowance: 20s
        crtExpiry: "2022-07-14T06:06:07Z"
        crtExpiryAnnotation: linkerd.io/identity-issuer-expiry
        issuanceLifetime: 24h0m0s
        scheme: linkerd.io/tls
        tls:
          crtPEM: |
            -----BEGIN CERTIFICATE-----
            MIIBgzCCASmgAwIBAgIBATAKBggqhkjOPQQDAjApMScwJQYDVQQDEx5pZGVudGl0
            eS5saW5rZXJkLmNsdXN0ZXIubG9jYWwwHhcNMjEwNzE0MDYwNTQ3WhcNMjIwNzE0
            MDYwNjA3WjApMScwJQYDVQQDEx5pZGVudGl0eS5saW5rZXJkLmNsdXN0ZXIubG9j
            YWwwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQ9/+QrL9PFvBSP/kl7BksTpjKN
            w+NFJHFD7MjaOpH1ATqKSwGeJbe5xa+R5Td7tbajRBCOwNgo1+MqKKjIB3ypo0Iw
            QDAOBgNVHQ8BAf8EBAMCAQYwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMC
            MA8GA1UdEwEB/wQFMAMBAf8wCgYIKoZIzj0EAwIDSAAwRQIhAJRnPB9vwU9z4Go9
            nVHuNMkRhjo9LG9ac86kYMEJYWOXAiB5qfOg3xgz8yRZBRUBOayyNCSylNDIR+52
            YTZnt3br+g==
            -----END CERTIFICATE-----
    identityProxyResources: null
    identityResources:
      cpu:
        limit: ""
        request: 100m
      memory:
        limit: 250Mi
        request: 10Mi
    installNamespace: true
    nodeSelector:
      beta.kubernetes.io/os: linux
    omitWebhookSideEffects: false
    profileValidator:
      caBundle: ""
      crtPEM: ""
      externalSecret: false
      namespaceSelector:
        matchExpressions:
        - key: config.linkerd.io/admission-webhooks
          operator: NotIn
          values:
          - disabled
    prometheus:
      enabled: true
      resources:
        cpu:
          limit: ""
          request: 300m
        memory:
          limit: 8192Mi
          request: 300Mi
    proxyInjector:
      caBundle: ""
      crtPEM: ""
      externalSecret: false
      namespaceSelector:
        matchExpressions:
        - key: config.linkerd.io/admission-webhooks
          operator: NotIn
          values:
          - disabled
    proxyInjectorProxyResources: null
    proxyInjectorResources:
      cpu:
        limit: ""
        request: 100m
      memory:
        limit: 250Mi
        request: 50Mi
    publicAPIProxyResources: null
    publicAPIResources:
      cpu:
        limit: ""
        request: 100m
      memory:
        limit: 250Mi
        request: 50Mi
    restrictDashboardPrivileges: false
    spValidatorProxyResources: null
    spValidatorResources:
      cpu:
        limit: ""
        request: 100m
      memory:
        limit: 250Mi
        request: 50Mi
    tap:
      caBundle: ""
      crtPEM: ""
      externalSecret: false
    tapProxyResources: null
    tapResources:
      cpu:
        limit: ""
        request: 100m
      memory:
        limit: 250Mi
        request: 50Mi
    tolerations: null
    tracing:
      enabled: false
    webImage: cr.l5d.io/linkerd/web
    webProxyResources: null
    webResources:
      cpu:
        limit: ""
        request: 100m
      memory:
        limit: 250Mi
        request: 50Mi
    webhookFailurePolicy: Fail

**Comment by alpeb** [comment]
The config looks fine, so this is kinda surprising... The source code lines reported in the panic stack trace don't make sense either. Can you check your server and client versions and let me know what you get with `linkerd version`?

**Comment by tejeshwari** [comment]
Linkerd versions 
Client version: stable-2.7.1
Server version: stable-2.9.5

**Comment by alpeb** [comment]
That is likely the problem. Please upgrade the linkerd CLI you have installed in your local machine, for it to match the version on the server side.

**Comment by tejeshwari** [comment]
Awesome!
The problem is with Version mismatch. It's working now.

Thank you :) :)
