### ISSUE TITLE
Intermittent termination of outbound TLS connections before they're established

### ISSUE THREAD

**Issue by jameschoa** [linkerd/linkerd2#6513]
### What is the issue?
Outbound TLS connections from services inside the linkerd service mesh will occasionally terminate before the TLS session is established. Issue has been observed in Linkerd versions 2.7.1, 2.8.1 and 2.10.2.

### How can it be reproduced?

Have a service (maybe in NodeJS) that makes outbound https calls to servers outside the cluster periodically and wait for the error to show up (it's intermittent).

### Logs, error output, etc
We have a lot of services running in NodeJS and every now and then, some of them will throw this error on occasion.
```
Client network socket disconnected before secure TLS connection was established
```

### Environment

- Kubernetes Version: v1.17.17
- Cluster Environment: AWS EKS
- Host OS: Amazon Linux 2
- Linkerd version: 2.7.1, 2.8.1, 2.10.2

### Possible solution

Workaround: Add port 443 to the `skip-outbound-port` pod annotation.

### Additional context

* Issue has been observed in clusters with both high and low traffic
* We're not sure if this is a NodeJS specific issue since majority of our services use that.

**Comment by adleong** [comment]
Hi @jameschoa!  To help us diagnose this, can your provide detailed instructions for reproducing the issue?  For example, k8s manifests for a demo NodeJS app which exhibits the behavior (even if it only exhibits it intermittently as you say).  If that's not possible, setting the linkerd-proxy's log level to debug and looking at the proxy logs during one of the incidents might provide some more clues as to what is happening.

**Comment by jameschoa** [comment]
I enabled debug logging and attached a snippet of the logs around the time when an error happened. The endpoint is LogDNS with IP of `147.75.39.99`. 
[linkerd.log](https://github.com/linkerd/linkerd2/files/6852649/linkerd.log)

**Comment by jameschoa** [comment]
Chiming in again, we've been adding the `skip-outbound-port` annotation to our deployments for the past few weeks and so far the impact has been very positive. One of our services had 236 errors over the course of a week without the annotation. With the annotation, the error has dropped to a total of 1 over 7 days and it was likely due to some other issue.

**Comment by adleong** [comment]
It sounds like with the addition of the `skip-outbound-port` annotation, things are working as expected.
