### ISSUE TITLE
client-initiated TLS connection is failing when proxied to a destination outside the cluster

### ISSUE THREAD

**Issue by dkulchinsky** [linkerd/linkerd2#6548]
### What is the issue?

Our setup includes the following components:

```
|-------- K8s cluster --------------|
<Golang app> --> <haproxy:port 3306> --> <proxysql:port 6033> --> <mysql:port 3306>
```

Note: for simplicity, there's just one `proxysql` server, but the goal is to load balance across a cluster of `proxysql` machines, there's also one app pod and one haproxy pod.

The `app` connects to the Database (the address is `haproxy:3306`) using TLS (`DB_USE_TLS: "true"`), both the `app` and `haproxy` are meshed, the `haproxy` service and deployment also have `config.linkerd.io/opaque-ports: "3306"` annotation (though it shouldn't matter, since port 3306 is skipped by default and we also tried without it).

With this setup the `app` can't establish a connection to the `proxysql` (i.e. DB).

If we disable proxy injection to the `haproxy` pod - everything works fine (also adding port 6033 to the skip-outbound-ports works).

### How can it be reproduced?

1. `proxysql` + `mysql` outside the K8s cluster, `proxysql` configured to use TLS (I guess the same will happen when connecting to `mysql` directly, but we can't test that because of the specifics of how our systems are designed)
2. a meshed `app` pod deployed that connects to haproxy service and uses TLS (I'm afraid I can't provide the app code as that's proprietary, but I suspect any Golang application that connects to a MySQL database with TLS would work).
3. a meshed `haproxy` pod deployed (we use the upstream `haproxy:2.3.10-alpine` image and the haproxy configuration is:
```
    global
      log stdout format raw local0 
      user haproxy
      group haproxy
    defaults
      log global
      option tcplog
      option logasap
      retries 2
      timeout connect 8s
      timeout server 1200s
      timeout client 1200s
    frontend stats
      mode http
      bind :::8404 v4v6
      stats enable
      stats uri /stats
      stats refresh 10s
    listen mysql-cluster
      bind :::3306 v4v6
      mode tcp
      option mysql-check
      server <proxysql name> <proxysql ip>:<proxysql port> check
```

### Logs, error output, etc

```
[  2091.091976s] DEBUG ThreadId(01) outbound:accept{client.addr=10.233.118.26:44764}:server{orig_dst=<proxysql ip>:6033}: linkerd_proxy_http::detect: Could not detect protocol read=0
[  2091.092023s] DEBUG ThreadId(01) outbound:accept{client.addr=10.233.118.26:44764}:server{orig_dst=<proxysql ip>:6033}: linkerd_detect: DetectResult protocol=None elapsed=2.00082772s
[  2091.092048s] DEBUG ThreadId(01) outbound:accept{client.addr=10.233.118.26:44764}:server{orig_dst=<proxysql ip>:6033}:tcp: linkerd_app_outbound::target: Target is unresolveable reason=not_provided_by_service_discovery orig_dst=<proxysql ip>:6033
[  2091.092115s] DEBUG ThreadId(01) outbound:accept{client.addr=10.233.118.26:44764}:server{orig_dst=<proxysql ip>:6033}:tcp:tcp.forward{server.addr=<proxysql ip>:6033}: linkerd_tls::client: Peer does not support TLS reason=not_provided_by_service_discovery
[  2091.092136s] DEBUG ThreadId(01) outbound:accept{client.addr=10.233.118.26:44764}:server{orig_dst=<proxysql ip>:6033}:tcp:tcp.forward{server.addr=<proxysql ip>:6033}: linkerd_proxy_transport::connect: Connecting server.addr=<proxysql ip>:6033
[  2091.093074s] DEBUG ThreadId(01) outbound:accept{client.addr=10.233.118.26:44764}:server{orig_dst=<proxysql ip>:6033}:tcp:tcp.forward{server.addr=<proxysql ip>:6033}: linkerd_proxy_transport::connect: Connected local.addr=10.233.118.26:44790 keepalive=Some(10s)
[  2091.093131s] DEBUG ThreadId(01) outbound:accept{client.addr=10.233.118.26:44764}:server{orig_dst=<proxysql ip>:6033}:tcp:tcp.forward{server.addr=<proxysql ip>:6033}: linkerd_proxy_transport::metrics: client connection open
[  2091.093813s] DEBUG ThreadId(01) outbound:accept{client.addr=10.233.118.26:44764}: linkerd_app_core::serve: Connection closed reason=server: Transport endpoint is not connected (os error 107)
```

`<proxysql ip>` is redacted, but it is an address outside of the CIDRs defined in `clusterNetworks`

#### `linkerd check` output

```text
❯ linkerd check
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-identity
----------------
√ certificate config is valid
√ trust anchors are using supported crypto algorithm
√ trust anchors are within their validity period
√ trust anchors are valid for at least 60 days
√ issuer cert is using supported crypto algorithm
√ issuer cert is within its validity period
√ issuer cert is valid for at least 60 days
√ issuer cert is issued by the trust anchor

linkerd-webhooks-and-apisvc-tls
-------------------------------
√ proxy-injector webhook has valid cert
√ proxy-injector cert is valid for at least 60 days
√ sp-validator webhook has valid cert
√ sp-validator cert is valid for at least 60 days

linkerd-api
-----------
√ control plane pods are ready
√ can initialize the client
√ can query the control plane API

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ control plane is up-to-date
√ control plane and cli versions match

linkerd-ha-checks
-----------------
√ pod injection disabled on kube-system

Status check results are √

Linkerd extensions checks
=========================

linkerd-viz
-----------
√ linkerd-viz Namespace exists
√ linkerd-viz ClusterRoles exist
√ linkerd-viz ClusterRoleBindings exist
√ tap API server has valid cert
√ tap API server cert is valid for at least 60 days
√ tap API service is running
√ linkerd-viz pods are injected
√ viz extension pods are running
√ prometheus is installed and configured correctly
√ can initialize the client
√ viz extension self-check

Status check results are √
```

### Environment

- Kubernetes Version: v1.19.9
- Cluster Environment: GKE
- Host OS: COS
- Linkerd version: 2.10.2

### Possible solution

Not really a solution, but the following two workaround seem to work:

1. add port 6033 to the skip-outbound-ports on the `haproxy` deployment, this is feasible but the problem with this annotation is that our users have to also append the ports defined on the control plane level (setting this on the control plane level is not possible, because different teams utilize same port numbers for different purposes)

2. remove `haproxy` pod from the mesh

### Additional context

happy to provide additional information if needed.

**Comment by mateiidavid** [comment]
Hey @dkulchinsky apologies for being a bit late with a response here.

Thank you for the detailed message! I think we spoke about this briefly over Slack. To me, it looks a bit odd that the external connection (`haproxy` <----> `proxysql`) is immediately torn down. Here's my understanding of the situation:
  * Go app establishes a TLS'd connection to `haproxy`, since haproxy is marked as opaque, we won't do any protocol 
    detection. Based on your message, this part of the stack seems to work well.
  * `haproxy` tries to establish a connection to `proxysql` but that quickly fails. Skipping the outbound port works well but 
      that's not a viable solution. You can also unmesh the pod and that also works out fine. It seems removing the proxy from 
      the equation fixes your issue, but I'd like to understand why that's the case.

As I mentioned on Slack, the proxy forwards connections to external services on the outbound side without a problem. Looking at the logs you have posted from `haproxy`, everything seems to be in order. 

```
[  2091.091976s] DEBUG ThreadId(01) outbound:accept{client.addr=10.233.118.26:44764}:server{orig_dst=<proxysql ip>:6033}: linkerd_proxy_http::detect: Could not detect protocol read=0
[  2091.092023s] DEBUG ThreadId(01) outbound:accept{client.addr=10.233.118.26:44764}:server{orig_dst=<proxysql ip>:6033}: linkerd_detect: DetectResult protocol=None elapsed=2.00082772s
[  2091.092048s] DEBUG ThreadId(01) outbound:accept{client.addr=10.233.118.26:44764}:server{orig_dst=<proxysql ip>:6033}:tcp: linkerd_app_outbound::target: Target is unresolveable reason=not_provided_by_service_discovery orig_dst=<proxysql ip>:6033
```

The stream is encrypted since the Go app does client TLS, we can't do any protocol detection here as a result. This is fine, since the protocol is set to `None`, the proxy will simply establish a TCP connection to the target. When doing service discovery on the target, we find that the target is unresolveable, this is again fine, since our target is not part of the defined `clusterNetworks`, like you pointed out.

```
[  2091.092115s] DEBUG ThreadId(01) outbound:accept{client.addr=10.233.118.26:44764}:server{orig_dst=<proxysql ip>:6033}:tcp:tcp.forward{server.addr=<proxysql ip>:6033}: linkerd_tls::client: Peer does not support TLS reason=not_provided_by_service_discovery
[  2091.092136s] DEBUG ThreadId(01) outbound:accept{client.addr=10.233.118.26:44764}:server{orig_dst=<proxysql ip>:6033}:tcp:tcp.forward{server.addr=<proxysql ip>:6033}: linkerd_proxy_transport::connect: Connecting server.addr=<proxysql ip>:6033
[  2091.093074s] DEBUG ThreadId(01) outbound:accept{client.addr=10.233.118.26:44764}:server{orig_dst=<proxysql ip>:6033}:tcp:tcp.forward{server.addr=<proxysql ip>:6033}: linkerd_proxy_transport::connect: Connected local.addr=10.233.118.26:44790 keepalive=Some(10s)
[  2091.093131s] DEBUG ThreadId(01) outbound:accept{client.addr=10.233.118.26:44764}:server{orig_dst=<proxysql ip>:6033}:tcp:tcp.forward{server.addr=<proxysql ip>:6033}: linkerd_proxy_transport::metrics: client connection open
```

The next set of log lines take us through TCP forwarding. Linkerd won't do any TLS here, we also know the target is unresolveable and we don't have a protocol, so the proxy will simply forward the TCP stream from the client to the target.

```
[  2091.093813s] DEBUG ThreadId(01) outbound:accept{client.addr=10.233.118.26:44764}: linkerd_app_core::serve: Connection closed reason=server: Transport endpoint is not connected (os error 107)
```

This is where it gets a bit confusing; before this line, the proxy was doing what it had to do, there were no indications of a failure. For some reason though, the server doesn't seem to want to talk to us. Our logs don't have any obvious sign of misbehaviour here. I think our best bet would be to look at the server logs (`proxysql`) and see why it refused the connection. I'm not familiar with `proxysql`, if you'd have access to such logs, it would probably help us paint a better picture of what's going on.

The fault might be with the proxy and I'm not discounting that, as far as it is concerned it does what it is supposed to, but it might do something bad so the server doesn't want to accept the connection. Hope it'd be easy to pull some logs from `proxysql`. It might also be good to increase the verbosity in the client, maybe `linkerd=trace,warn`.

Let me know if this makes sense so far or if you've uncovered anything new in the past week : )

**Comment by dkulchinsky** [comment]
Hey @mateiidavid 👋🏼 

>  I think our best bet would be to look at the server logs (`proxysql`) and see why it refused the connection. I'm not familiar with `proxysql`, if you'd have access to such logs, it would probably help us paint a better picture of what's going on.

I could try, I'll need to coordinate this with the relevant team to add the proxy back to the `haproxy` pod and capture any logs on proxysql that may be relevant.

>  It might also be good to increase the verbosity in the client, maybe `linkerd=trace,warn`.

Sure, we can do that at the same time as we're testing the above.

> Let me know if this makes sense so far or if you've uncovered anything new in the past week : )

Nothing new to report on, we had to disable proxy injection on the haproxy pod which fixed the issue and since it's a staging environment, I didn't try anything else, one thing we know for sure os that this is failing when haproxy is injected with the proxy and works just fine when disabling proxy injection, so we're confident that it's the only thing that changes.

**Comment by mateiidavid** [comment]
@dkulchinsky any updates? Have you managed to capture more logs?

**Comment by mateiidavid** [comment]
Closing for now due to lack of activity. 

@dkulchinsky if you have any updates or if you want to re-open this issue, either comment or ping me. Thanks!

**Comment by dkulchinsky** [comment]
@mateiidavid sorry for the lack of communication on my end, was on PTO for a while and things side-tracked, I'll try to get the issue reproduced and collect the logs you've requested, will report back once I have them.
