### ISSUE TITLE
Add option to inject to set resource limits

### ISSUE THREAD

**Issue by jobinjosem1** [linkerd/linkerd2#6557]
Currently there is option to add cpu and memory requests and limits while generating manifests using linkerd install. We can add flag like `--proxy-cpu-request` or `--proxy-cpu-limit `but this only applies to proxy container. It would be nice if you can add additional flags to limit resources for all other containers part of the linkerd ecosystem.

Currently we have to generate the manifests and manually edit the yaml to set resource limits and requests for other containers.

**Comment by alpeb** [comment]
We have decided to limit the amount of flags directly exposed in the CLI to avoid bloating it. Instead, still from the CLI, you can "indirectly" access all the manifests configs as if you were installing through Helm, using the `--set` flags. The configs are listed [here](https://github.com/linkerd/linkerd2/blob/main/charts/linkerd2/values.yaml). For example to set CPU and memory limits to the `linkerd-destination` main container, you'd install with something like:
```console
linkerd install --set destinationResources.cpu.limit=500m --set destinationResources.memory.limit=250Mi
```
Let me know if that works out for you :slightly_smiling_face:

**Comment by jobinjosem1** [comment]
Unfortunately we are not sing helm. The non-helm method https://linkerd.io/2.10/tasks/install/ doesn't work with these options.

**Comment by alpeb** [comment]
You just need to use the command I posted above. It's not using Helm. That should work since version 2.10. What CLI version are you on?

**Comment by jobinjosem1** [comment]
Thanks @alpeb It seems to be working with 2.10 even though I get a warning. 
Now when I try to add the same for controller it is not working. I run the below command to generate manifests.

linkerd install --set identityResources.cpu.limit=512m --set identityResources.memory.limit=512Mi --set identityResources.cpu.request=100m --set identityResources.memory.request=128Mi --proxy-cpu-limit 50m --proxy-cpu-request 20m --proxy-memory-limit 64Mi --proxy-memory-request 32Mi --set destinationResources.cpu.limit=512m --set destinationResources.memory.limit=512Mi --set destinationResources.cpu.request=100m --set destinationResources.memory.request=128Mi --set public-apiResources.cpu.limit=510m --set public-apirResources.memory.limit=510Mi --set public-apiResources.cpu.request=100m --set public-apiResources.memory.request=128Mi

2021/08/04 11:23:43 warning: skipped value for destinationResources: Not a table.
2021/08/04 11:23:43 warning: skipped value for identityResources: Not a table.

Could you please help to inject the values in to controller, proxy-injector and sp-validator as well?

**Comment by alpeb** [comment]
For the controller, the flags are `publicAPIResources....` . For the injector, `proxyInjectorResources...`. And for the sp-validor, `spValidatorResources...`.

As for the warnings, you can ignore them. They're no longer present in the latest edge releases.
