### ISSUE TITLE
Feature Request - Allow use of existing certs in the helm installation

### ISSUE THREAD

**Issue by vikas027** [linkerd/linkerd2#6561]
## Issue
I use [ArgoCD](https://argo-cd.readthedocs.io/en/stable/) to automatically install/upgrade helm charts on the kubernetes clusters. This allows me to store the helm chart values in a git repository.
I'd like to do the same thing in the linkerd  helm [values](https://github.com/linkerd/linkerd2/blob/main/charts/linkerd2/values.yaml) as well but as of the values in the helm chart takes `ca.crt`, `issuer.crt`, and `issuer.key` directly in the yaml file. I don't want to store these, especially the key in a git repo :) 

## Probable Solution
It would be great if you allow use of existing kubernetes secrets in the yaml file so that one can just specify the secret names in the `values.yaml`

## References
- [Slack thread](https://linkerd.slack.com/archives/C89RTCWJF/p1627207362488000)

**Comment by alpeb** [comment]
This is already possible with the following setup.

You can pass your `ca.crt` contents in the `identityTrustAnchorsPEM` setting, and store it in git given it's a public cert.

The secret `linkerd-identity-issuer` stores the issuer cert and key. If you want to provide it yourself, set `identity.issuer.scheme: kubernetes.io/tls`. That secret should also have the root certificate. For example you could create it with
```console
kubectl create secret tls linkerd-identity-issuer --cert=issuer.crt --key=issuer.key --namespace=linkerd
```
And to add the root cert you need to edit its yaml and include the `ca.crt` field with the contents of that file encoded in base64.

Let me know if that does the trick!

**Comment by vikas027** [comment]
Thanks, @alpeb . I will try this out soon. I think it would be a good idea to add this info to the [values.yaml](https://github.com/linkerd/linkerd2/blob/main/charts/linkerd2/values.yaml#L189-L209) file.
