### ISSUE TITLE
Connection closed error=Unexpected TLS connection

### ISSUE THREAD

**Issue by emcay** [linkerd/linkerd2#6567]
### What is the issue?
Confusing INFO level error messages. What do these mean? They are generating at a very rapid rate.
### How can it be reproduced?
Unknown, impacting only one of several clusters with identical configuration.
### Logs, error output, etc
'339753.344528s]  INFO ThreadId(02) linkerd_app_core::serve: Connection closed error=Unexpected TLS connection to service-account-name.namespace-name.serviceaccount.identity.linkerd.cluster.local from x.x.x.x:(ephemeral port numbers)'

#### `linkerd check` output

```kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-identity
----------------
√ certificate config is valid
√ trust anchors are using supported crypto algorithm
√ trust anchors are within their validity period
√ trust anchors are valid for at least 60 days
√ issuer cert is using supported crypto algorithm
√ issuer cert is within its validity period
√ issuer cert is valid for at least 60 days
√ issuer cert is issued by the trust anchor

linkerd-webhooks-and-apisvc-tls
-------------------------------
√ proxy-injector webhook has valid cert
√ proxy-injector cert is valid for at least 60 days
√ sp-validator webhook has valid cert
√ sp-validator cert is valid for at least 60 days

linkerd-api
-----------
√ control plane pods are ready
√ can initialize the client
√ can query the control plane API

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ control plane is up-to-date
√ control plane and cli versions match

Status check results are √

Linkerd extensions checks
=========================

linkerd-viz
-----------
√ linkerd-viz Namespace exists
√ linkerd-viz ClusterRoles exist
√ linkerd-viz ClusterRoleBindings exist
√ tap API server has valid cert
√ tap API server cert is valid for at least 60 days
√ tap API service is running
√ linkerd-viz pods are injected
√ viz extension pods are running
√ prometheus is installed and configured correctly
√ can initialize the client
√ viz extension self-check

Status check results are √
```

### Environment

- Kubernetes Version:
   v1.19.8-eks-96780e
- Cluster Environment: (GKE, AKS, kops, ...)
   EKS
- Host OS:
   Amazon linux
- Linkerd version:
   2.10.2

### Possible solution
Unknown
### Additional context
Can't determine why these occur. And for some known reason suddenly stopped? They traverse the ephemeral port range, and a various service account names in the errors.

**Comment by olix0r** [comment]
I assume that the service emitting these logs does not match the service account described in the log message? Can you share any details about the pod at the client IP? Is it an ingress? How does the client target the server -- is it using a clusterIP service or is it targeting individual pod IPs?

**Comment by emcay** [comment]
Oops forgot to mention they were coming from the sidecar containers.

Additionally, I actually think this is a cni issue im gonna close it.
