### ISSUE TITLE
Cannot use newer grafana versions

### ISSUE THREAD

**Issue by rmgpinto** [linkerd/linkerd2#6579]
## Bug Report
On newer grafana versions (> 7.1.5), the url specified here: https://github.com/linkerd/linkerd2/blob/main/web/app/js/components/GrafanaLink.jsx#L7 does not work.

Instead of `/grafana/dashboard/db/linkerd-${resource}?var-${resource}=${name}` it's now `/grafana/d/linkerd-${resource}?var-${resource}=${name}`

Can you make this a variable?

**Comment by kleimkuhler** [comment]
The bundled Grafana version is now 7.1.5 so instead of making it a variable it may make sense to just change the URL.

**Comment by kleimkuhler** [comment]
@rmgpinto That'd be great!
