### ISSUE TITLE
Remove the namespace resource from the Helm charts

### ISSUE THREAD

**Issue by alpeb** [linkerd/linkerd2#6584]
It is considered bad practice to have the charts create their namespace, specially since Helm v3. A few reasons for this:
- Just like you would do with `kubectl --namespace xxx apply`, it's more flexible to leave `helm install` instruct in a flag the namespace it'd like the resources to be deployed into.
- Now that Tiller is gone, the chart config is no longer stored in Tiller's namespace, but in the namespace passed to `helm install --namespace`. If nothing was passed, the config secret is stored in the `default` namespace regardless of the namespace used in the chart's templates. That secret can contain private data, so that's not secure.

Removing the namespace from the templates requires to take these points into account.
- Have the CLI to manually generate the yaml for the namespace.
- The namespace can no longer have this specific linkerd metadata:
  - The `linkerd.io/inject: disabled` annotation. No big deal, we'll just have to add that to each control plane workload.
  - The `config.linkerd.io/admission-webhooks: disabled` label. Without this the injector will get called for control plane pod restarts, but it shouldn't mutate the pod given the presence of the `linkerd.io/inject: disabled` annotation.
  - The `linkerd.io/is-control-plane: "true"` label. From what I could tell this is not relied on.
  - The `linkerd.io/control-plane-ns` label. Used for identifying all the resources belonging to linkerd, and used for `kubectl apply --prune`. Since the namespace isn't touched during upgrades, it seems this doesn't matter. Integrations tests though will need to manually remove namespaces for cleanup.
  - Linkerd extensions rely on the `linkerd.io/extension` label. If we can't find an easy workaround for this, we could add a simple post-install hook for just adding that label.
- For folks having installed without using `helm install --namespace`, a simple upgrade to this new way won't likely be possible. Will have to figure if it's possible to do it without downtime, and document the procedure. Maybe we can consider still leaving the namespace template in the chart, but disabled by default, and just instruct to enable it in the upgrade docs for folks not wanting to migrate to the new way.

Ref #6463 #3211

**Comment by kleimkuhler** [comment]
I don't think we need to worry about the `linkerd.io/inject: disabled` annotation on control plane workloads. When the webhook checks if workloads are injectable [here](https://github.com/linkerd/linkerd2/blob/ca1077bb08c5790317345377a92c3303034b4d40/controller/proxy-injector/webhook.go#L89), the function will see that it already has a sidecar [here](https://github.com/linkerd/linkerd2/blob/a11012819c366574e07fadbbdf4e4a341d0cae54/pkg/inject/report.go#L125-L127).

That should be enough for injection to be skipped.
