### ISSUE TITLE
Add `--cluster-domain` for `linkerd vis install`?

### ISSUE THREAD

**Issue by Hongbo-Miao** [linkerd/linkerd2#6602]
### What problem are you trying to solve?

The problem detail is at https://github.com/linkerd/linkerd2/discussions/6601

### How should the problem be solved?

`linkerd install` has a parameter `--cluster-domain`.
However, `linkerd vis install` does not have. I think it should also have 

### Any alternatives you've considered?

I don't have any alternative solution currently.

### How would users interact with this feature?

N/A.

**Comment by Pothulapati** [comment]
Hey @Hongbo-Miao, With all the new extensions these explicit flags are not added to decrease the code complexity.

You can always use the `--set` flags to do the same, as shown below

```bash
on ⛵ kind-kind  linkerd2 on 🌱 taru [📦📝🤷‍🏎💨] via 🐼 v1.16.6 via 
➜ linkerd viz install --set clusterDomain="google.com" | grep google ~/work/linkerd2
        - -cluster-domain=google.com
        - -prometheus-url=http://prometheus.linkerd-viz.svc.google.com:9090
      url: http://prometheus.linkerd-viz.svc.google.com:9090
        - -identity-trust-domain=google.com
        - -linkerd-metrics-api-addr=metrics-api.linkerd-viz.svc.google.com:8085
        - -cluster-domain=google.com
        - -grafana-addr=grafana.linkerd-viz.svc.google.com:3000
        - -enforced-host=^(localhost|127\.0\.0\.1|web\.linkerd-viz\.svc\.google\.com|web\.linkerd-viz\.svc|\[::1\])(:\d+)?$
  name: metrics-api.linkerd-viz.svc.google.com
  name: prometheus.linkerd-viz.svc.google.com
  name: grafana.linkerd-viz.svc.google.com

```

These flags are the same as that of the [ones present in Helm](https://helm.sh/docs/helm/helm_install/#synopsis)

Closing this issue, as the answer was straightforward. Feel free to reopen if this doesn't answer your question.

**Comment by Hongbo-Miao** [comment]
Thanks @Pothulapati ! Will try it out!

**Comment by Hongbo-Miao** [comment]
Thanks @Pothulapati ! It works now!
