### ISSUE TITLE
Split core Helm charts

### ISSUE THREAD

**Issue by alpeb** [linkerd/linkerd2#6620]
## Background

It's not possible to have CRD definitions and instances in the same chart under the `templates` directory, because it takes time for the new CRD APIs to become available, and attempting to persist instances prematurely will result in an error.

## The options

Helm v3 [documents two methods](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/) for handling CRDs:
1) Putting CRDs definitions under the `templates/crds` directory. Helm will first persist what's in there and wait for its availability before processing the other resources under `templates/`.
2) Use separate charts. A first one containing the CRD definitions, a second one their instances.

The first option is a no-go because it implies CRDs will get installed and Helm won't ever touch them again. `helm upgrade` nor `helm delete` will touch them, so the anytime these require changes, instructions would need to be provided for the user to do that manually. Helm's reasons are documented [here](https://github.com/helm/community/blob/e5cd91bbfe93f0e538c0890d5f970c7b6149d4a9/hips/hip-0011.md).

## Our strategy

So we'd go with the second option. Similar to the staged installs available for the CLI, we'd have one first chart ("linkerd-base" or "linkerd-root"?) containing all the CRD definitions along with all the other cluster-level resources, and a second chart ("linkerd-core"?) with the rest.

Like with the staged CLI install, a nice additional benefit is that the first chart could be handed to admin-level folks and the former to operators with only namespace-level access. Note though that, from what I've seen, the staged CLI hasn't seen much adoption. Given the Helm method is more prod oriented, maybe it'd be more relevant in that case?

## Are the motivations strong enough?

In order of importance, these are the motivations:

- Allow us to define instances for the new auth CRDs, for the control plane pods. #6606 added support setting default policies declaratively in the injected proxy manifest. So do we really need auth CRD instances at install-time, or do we just want to leave the door open for adding that in the future?
- #6584 proposes to remove namespaces from the charts, which is a breaking change; users will need to uninstall the control plane and reinstall it using the new chart version. This proposal is also breaking. So club them together and call it a day?
- Very minor point: We'll be able to add a ServiceProfile instance for Destination, which was dropped a couple of releases ago.

**Comment by kleimkuhler** [comment]
Closed by #6691
