### ISSUE TITLE
Override glog's default for the -logtostderr flag

### ISSUE THREAD

**Issue by klingerf** [linkerd/linkerd2#664]
In #524 we started setting the `-logtostderr=true` flag on all of the controller components in the kubernetes configs that are output by the `conduit install` command. This fixed the issue described in #522, but it would be better to fix this in a way that didn't require modifying every command line invocation of every controller component.

We should be able to call `flag.Set` in our code to accomplish this, per: https://twitter.com/fatih/status/980918398417817600

**Comment by briansmith** [comment]
In case the Tweet gets deleted, it's just putting this into the main module and removing the CLI arguments:

```go
func init() {
    flag.Set("logtostderr", "true")
}
```

**Comment by klingerf** [comment]
We should enable glog logging to stderr if `-log-level=debug`, otherwise we should suppress glog logs.

**Comment by klingerf** [comment]
I took some time to read the glog source, and unfortunately it appears that it's not possible for us to disable glog logs on a readonly filesystem. This relates to kubernetes/kubernetes#61006. Glog writes it logs to either stderr or to a directory on disk, and we have to write to stderr since our processes are running inside scratch containers and can't write to disk.

I'll still use this issue to track overriding glog's default settings to log to stderr automatically, which will allow us to remove the `-logtostderr` flags from our install config.
