### ISSUE TITLE
Deprecate default SMI support in Linkerd

### ISSUE THREAD

**Issue by Pothulapati** [linkerd/linkerd2#6647]
SMI support in the Linkerd control-plane is being planned to be removed in favor of the [new SMI extension.](https://github.com/linkerd/linkerd-smi/) which supports the usage of SMI resources(that are currently supported) with Linkerd. [CLI Support](https://github.com/linkerd/linkerd2/pull/6514) has also been added through which users can get the stat metrics on a `TrafficSplit` resource applied with SMI extension installed.

Because Linkerd follows a deprecation policy of 1 release version, We have to intimate users about the removal in `2.11`, So that we can actually remove it in `2.12`.

I propose the following changes for this process:

### Before `2.11`

- [x] Update `linkerd check` to warn the usage of `TrafficSplit` resources without the [SMI extension](https://www.github.com/linkerd/linkerd-smi)
- [x] Deprecate `linkerd viz stat ts` and warn on its usage.

### After `2.11`
- [x] Remove `TrafficSplit` CRD from the control-plane, along with the the removal of watches and reads from the controller, CLI and dashboard.

**Comment by kleimkuhler** [comment]
Being addressed by #7334.

**Comment by adleong** [comment]
@Pothulapati can we close this?

**Comment by Pothulapati** [comment]
Yep, This is completed! Users who want SMI support should be using the [linkerd-smi extension](https://github.com/linkerd/linkerd-smi/) on the latest release.
