### ISSUE TITLE
Dashboard support for `stat` on services

### ISSUE THREAD

**Issue by Pothulapati** [linkerd/linkerd2#6648]
## Feature Request

See https://github.com/linkerd/linkerd2/issues/2967, 

With #6514, `stat` on services now works with the use of client side metrics and `authority` label. This means that the dashboard can also be made to do the same with a new `Services` button on the side bar. Most of the changes should be straight forward and should be very similar to the existing code paths but stat on services differs in the following ways:

- The `StatsSummary` response might include `weights` when a `ServiceProfile` exists. In which case, a different table format has to be used for rendering.
- Add an additional note describing how stat on a `service` differs. See #6646

**Comment by Pothulapati** [comment]
@tharun208 Awesome, Going ahead and assigning you this. 

Feel free to ask questions here, or in a draft PR (with any changes that you tried) and we can go from there!

**Comment by Pothulapati** [comment]
Unassigned @tharun208 as there hasn't been much activity on this.

**Comment by krzysztofdrys** [comment]
I would like to work on this ticket. I hope to give some update within a week from now.

My plan is the following:
1. Display services using `ResourceDetails` and `ResourceList` view,
2. Make adjustment to properly render weights.

I have looked into this a little and I have two questions:
1. Could someone provide me with an icon for services? 🙏🏻
2. What do I need to do to get weight? Will it be enough to add service profiles to setup from https://github.com/linkerd/linkerd2/blob/main/BUILD.md#comprehensive ?

**Comment by krzysztofdrys** [comment]
Hi @Pothulapati ! I have created a draft PR. Could you help me get it merged?
