### ISSUE TITLE
Remove unused `config` protobuf file and references

### ISSUE THREAD

**Issue by mateiidavid** [linkerd/linkerd2#6666]
## What

With [linkerd2#5008](https://github.com/linkerd/linkerd2/issues/5008) and associated PRs, we changed the way configuration is handled by storing a helm values struct inside of the configmap. This replaced the old `config` pb API. In PR #6651 we removed some of the functions that were previously responsible for fetching pb configuration from the configmap.

Since these functions were no longer used and have been cleaned up, it might also be useful to remove the pb file itself and any lingering functions and references. This would also require small refactors in certain places (that'll highlight below). The only impediment to this so far is the usage of the pb API in `cli/cmd/upgrade_legacy.go`: https://github.com/linkerd/linkerd2/blob/741fde679b726dd8548765deaf14e7a8c2d2c706/cli/cmd/upgrade_legacy.go#L91-L112

This was used to (afaik) upgrade from `stable-2.8.x` to `stable-2.9.0`. We generally enforce that consecutive versions have a sound upgrade path; from `stable-2.8.x` to `stable-2.11` this wouldn't be a strict necessity however, and provided we still have a documented upgrade path, should be feasible to do.

## How

To clean-up, we would have to delete the protobuf file itself, change the proto compilation script and also remove obsolete references. This is what I uncovered so far:

- [ ] Remove [`proto/config/config.proto`](https://github.com/linkerd/linkerd2/blob/main/proto/config/config.proto)
- [ ] Change [`bin/protoc-go.sh`](https://github.com/linkerd/linkerd2/blob/main/bin/protoc-go.sh) to not include `config.proto`
- [ ] Change [`FetchLinkerdConfigMap()`](https://github.com/linkerd/linkerd2/blob/741fde679b726dd8548765deaf14e7a8c2d2c706/pkg/healthcheck/healthcheck.go#L1768) in `healthcheck.go` to return only the configmap, with the pb type.
- [ ] Change [`FetchCurrentConfiguration()`](https://github.com/linkerd/linkerd2/blob/741fde679b726dd8548765deaf14e7a8c2d2c706/pkg/healthcheck/healthcheck.go#L1647) only unmarshal and use helm value struct from configmap (as a follow-up to the todo above; note that there's already a todo here to refactor the function once value struct is the default, which has already happened)
- [ ] Remove (or change) [`upgrade_legacy.go`](https://github.com/linkerd/linkerd2/blob/main/cli/cmd/upgrade_legacy.go)
- [ ] Test upgrade paths

Of course, the list is not exhaustive and more things might come up, but from my initial search these seem to be the places where we still make use of the deprecated `config pb`. I found most of these by grepping for the pb API message or functions, i.e
```sh
# in linkerd root
$ grep 'pb.All'
```

**Comment by mateiidavid** [comment]
> /accept

Thanks a lot @xichengliudui! Let us know if you have any questions or if we can help out in any way.

**Comment by adleong** [comment]
@xichengliudui I suspect that this will be a fairly involved change because our config and upgrade code is somewhat complex.  As a starting point, I suggest reading `cli/cmd/upgrade.go`, `cli/cmd/upgrade_legacy.go`, and `pkg/config/config.go` to see how things currently work.  Ideally, as a result of this change, we will be able to get rid of `upgrade_legacy.go` altogether.

We're here to help, so as @mateiidavid said, please reach out if you have any questions at all.

**Comment by mateiidavid** [comment]
Hi @xichengliudui, just checking in to see if you've had any trouble so far with this issue. I know the change is not that straightforward, more than happy to answer questions.

One of our colleagues was also hoping to get in touch with some exciting news regarding the contributions you have made to the project so far. Do you have a preferred communication channel where we can reach you privately? Alternatively, if you wouldn't mind, you can e-mail me at matei@buoyant.io, or find me on the Linkerd, Kubernetes and CNCF Slack at @Matei (David). I can forward you to the person in question, would be great to get a conversation started. Hope to hear from you soon :)

**Comment by krzysztofdrys** [comment]
@mateiidavid @adleong if this issue is available, I would like to take it.

**Comment by alpeb** [comment]
@krzysztofdrys Please go ahead! :muscle:

**Comment by krzysztofdrys** [comment]
I started looking at this. Very nice to have such a detailed TODO list and thorough description.

I have a couple of questions, just to be sure I got everything right. :-) 

> We generally enforce that consecutive versions have a sound upgrade path; from stable-2.8.x to stable-2.11 this wouldn't be a strict necessity however, and provided we still have a documented upgrade path, should be feasible to do.

Is there anything specific which I should do about testing the upgrade path? Or is it enough to look at the status of the integration tests?

> Change FetchLinkerdConfigMap() in healthcheck.go to return only the configmap, with the pb type.

Did you mean "with not pb type"? We would like something like this, right? 
```
func FetchLinkerdConfigMap(ctx context.Context, k kubernetes.Interface, controlPlaneNamespace string) (*corev1.ConfigMap, error)
```
I am just trying to understand if I got this right.

**Comment by krzysztofdrys** [comment]
One more question. Should `FetchCurrentConfiguration` return an error if `configMap.Data["values"]` is empty? Seems like a lot of callers expect that if there is no error returned, values are there.

**Comment by krzysztofdrys** [comment]
@alpeb @mateiidavid  
I created the PR. This is a draft, since there is still some work to do. But if you could take a look and see if I am going in the right direction, it would be very nice.
