### ISSUE TITLE
Create new integration test for `linkerd multicluster allow`

### ISSUE THREAD

**Issue by alpeb** [linkerd/linkerd2#6693]
`linkerd multicluster allow` outputs credentials resources (ClusterRole, ServiceAccount and a ClusterRoleBinding to link them) besides the default ones returned by `linkerd multicluster install`, to give additional access to a target cluster. 

Turns out this command has been broken for a few releases:
```console
$ linkerd mc allow --service-account-name foobar
Error: template: linkerd-multicluster/templates/remote-access-service-mirror-rbac.yaml:16:7: executing "linkerd-multicluster/templates/remote-access-service-mirror-rbac.yaml" at <include "partials.annotations.created-by" $>: error calling include: template: no template "partials.annotations.created-by" associated with template "gotpl"
```
but has already been fixed by #6665

It would be nice though to have it tested in the integration tests, somewhere under `test/integration/multicluster`. A simple call to the command using the context of the target cluster, and comparing its output to a golden file should do the trick.

**Comment by girish332** [comment]
Can I work on this ?

**Comment by alpeb** [comment]
> Can I work on this ?

Sure! Let me know if you have any questions :slightly_smiling_face:

**Comment by jaskeerat789** [comment]
@alpeb is this resolved ?

**Comment by alpeb** [comment]
> @alpeb is this resolved ?

Nope, wanna give it a try? :wink:

**Comment by jaskeerat789** [comment]
> > @alpeb is this resolved ?
> 
> Nope, wanna give it a try? :wink:

Ya sure...

**Comment by pratikkumar-mohite** [comment]
@alpeb would like work on it, is it still open?

**Comment by alpeb** [comment]
> @alpeb would like work on it, is it still open?

Yep, still open :+1:
