### ISSUE TITLE
WaitBeforeExitSeconds doesn't work due to missing /bin/bash inside proxy image

### ISSUE THREAD

**Issue by mkrutik** [linkerd/linkerd2#6723]
### What is the issue?
After swithicng to distroless base image for proxy (it was done in this [PR](https://github.com/linkerd/linkerd2/pull/6228)) `proxy.waitBeforeExitSeconds` functionality stoped working as image doesn't contain `/bin/bash` anymore.

### How can it be reproduced?
Configure `waitBeforeExitSeconds` to non zero value, and delete/update deployment and now it should be visible inside pod description or K8S node logs that pre stop hook failed due to missing `/bin/bash`.
```
I0823 10:28:58.312316    2346 handlers.go:67] Exec lifecycle hook ([/bin/bash -c sleep 25]) for Container "linkerd-proxy" in Pod "service-cos-5fd5469db9-l5zqr_default(17d0ac4f-4b1b-41cf-a8cd-9199226f2801)" failed - error: command '/bin/bash -c sleep 25' exited with 126: , message: "OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec: \"/bin/bash\": stat /bin/bash: no such file or directory: unknown\r\n"
```
### Environment
- Linkerd version: linkerd-edge-21.8.1

**Comment by alpeb** [comment]
Thanks for the report, I could confirm this is an issue. To fix, we'll have to bring an external binary performing the sleep without relying on the shell, or perhaps include that functionality into `linkerd-await` itself... In the meantime, I'm afraid you'll have to build your own proxy image using a RUNTIME_IMAGE base from a less minimal image like Alpine.
