### ISSUE TITLE
AWS EKS Fargate backed cluster does not accept control plane deployment

### ISSUE THREAD

**Issue by tyler-bixal** [linkerd/linkerd2#6728]
### What is the issue?

When using a 100% Fargate backed EKS cluster, deployments time out while progressing.

### How can it be reproduced?

1. Create an EKS Fargate backed cluster and associated Fargate profile for the linkerd namespace. 
1. Follow the multi-step linkerd installation guide [here](https://linkerd.io/2.10/tasks/install/#multi-stage-install).
1. See that both `kubectl get pods -n linkerd` and `linkerd check` show that the controller pod is "Pending" after a period of time that the pods should have started.

### Logs, error output, etc

Fargate workload for the `linkerd/linkerd-controller` deployment (and all of the other deployments) has the following conditions:

```text
Available | False | Deployment does not have minimum availability.

Progressing | False | ReplicaSet "linkerd-controller-6f9ff448f" has timed out progressing.
```

There are no events for any of the pods, they are all stuck in a "Pending" status.

#### `linkerd check` output

```text
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
× controller pod is running
    linkerd-controller-6f9ff448f-6r6hj status is Pending
    see https://linkerd.io/2.10/checks/#l5d-existence-controller for hints

Status check results are ×
```

### Environment

- Kubernetes Version: v1.21.2-eks-0389ca3
- Cluster Environment: (EKS)
- Host OS: Linux
- Linkerd version: stable-2.10.2

### Possible solution

Whatever it is, it is specific to Fargate backed EKS and the deployment manifests not being compatible. It is doubtful that the issue is specific to this particular Fargate cluster but it is possible. This cluster works for the existing workload running on it, without issue.

### Additional context

1. I have verified that I can create pods in this namespace and also that the `cr.l5d.io` repository is available and I can pull images from it into my cluster and this namespace.
2. I have verified that, with an EC2 backed EKS cluster, linkerd installs without issue using the exact same yaml manifest applied in the exact same order. I output all of the linkerd commands from the multi-step install into files and applied them so there is no difference in install method.

**Comment by alpeb** [comment]
Can you share the Fargate profile selectors you used that point to the linkerd pods?

**Comment by tyler-bixal** [comment]
> Can you share the Fargate profile selectors you used that point to the linkerd pods?

I have the Fargate profile selector based on namespace so any pod created in a namespace, gets a Fargate profile. There are no finer selectors applied to this particular Fargate profile. So I just have a profile for the 'linkerd' namespace.

**Comment by alpeb** [comment]
Oh reading through [Fargate docs](https://docs.aws.amazon.com/eks/latest/userguide/fargate.html) I found that privileged containers aren't supported. The init-container that linkerd injects (both into your app and into the linkerd control plane itself) requires `NET_ADMIN` and `NET_RAW` capabilities in order to run `iptables` and configure the proxy rerouting, so this won't work in Fargate. An alternate linkerd config is to use our [CNI plugin](https://linkerd.io/2.10/features/cni/)  that doesn't use an init-container, relying instead in a DaemonSet, but alas, I also see in those docs that Fargate doesn't support DaemonSets! So I'm afraid that leaves us out of options :man_shrugging:

**Comment by tyler-bixal** [comment]
Thank you for confirming @alpeb. Is it possible to reconfigure the CNI plugin to run as a sidecar instead? That is the general guidance for turning a DaemonSet into something compatible with Fargate.

**Comment by wmorgan** [comment]
See https://github.com/aws/containers-roadmap/issues/682 for more. Today, Fargate does not support any service mesh except for App Mesh.

**Comment by tyler-bixal** [comment]
> See [aws/containers-roadmap#682](https://github.com/aws/containers-roadmap/issues/682) for more. Today, Fargate does not support any service mesh except for App Mesh.

Appreciate the link!
