### ISSUE TITLE
remove unused reference env variables in `_proxy.tpl`

### ISSUE THREAD

**Issue by Pothulapati** [linkerd/linkerd2#6740]
#6711 removes the usage of `_l5d_namespace` and `_l5d_trustDomain` but doesn't actually
remove them because it causes the `linkerd-viz` upgrades to fail because
the older `tap-injector` still injects `LINKERD2_PROXY_TAP_SVC_NAME` with the usage of them
as the new version of `tap-injector` isn't ready yet which causes the proxy to fail with the following
error.

```bash
on ⛵ kind-kind  linkerd2 on 🌱 taru [📦📝🤷‍] via 🐼 v1.16.7 via 
❯ k -n linkerd-viz logs tap-7bf584f5d8-nscj8 linkerd-proxy                                        ~/work/linkerd2
time="2021-08-25T06:24:25Z" level=info msg="Found pre-existing key: /var/run/linkerd/identity/end-entity/key.p8"
time="2021-08-25T06:24:25Z" level=info msg="Found pre-existing CSR: /var/run/linkerd/identity/end-entity/csr.der"
[     0.001010s] ERROR ThreadId(01) linkerd_app::env: Not a valid identity name: tap.linkerd-viz.serviceaccount.identity.$(_l5d_ns).$(_l5d_trustdomain)
Invalid configuration: invalid environment variable
[     0.001039s] ERROR ThreadId(01) linkerd_app::env: LINKERD2_PROXY_TAP_SVC_NAME="tap.linkerd-viz.serviceaccount.identity.$(_l5d_ns).$(_l5d_trustdomain)" is not valid: NameError
[     0.001074s]  WARN ThreadId(01) linkerd_app::env: LINKERD2_PROXY_INBOUND_DEFAULT_POLICY was not set; using `all-unauthenticated`
```

This can be fixed by doing a `rollout restart` on the failing pods but it adds another unnecessary manual step. Hence,
These variables will be instead removed in a future release which should prevent this.

**Comment by alpeb** [comment]
So this will actually cause downtime in the control plane during upgrades? `linkerd upgrade | kubectl apply -f -` will restart the control-plane pods, which will get tap-injected by the not-yet-upgraded tap injector, causing the issue you pointed out, till viz gets updated and then the control-plane gets rolled out, correct?

**Comment by Pothulapati** [comment]
@alpeb If the upgrade is from `2.11` then it should work right? as this removal is being planned from `2.12` and in `2.11`the tap-injector (which is considered old then) will not be using those variables as per the change in #6711

**Comment by alpeb** [comment]
Gotcha, makes sense! :sweat_smile:

**Comment by adleong** [comment]
@Pothulapati is this fixed by https://github.com/linkerd/linkerd2/pull/6711

**Comment by Pothulapati** [comment]
@adleong This issue tracks the removal of these reference variables definitions which we did not remove because of the race conditions that happens during upgrade i.e
> it causes the linkerd-viz upgrades to fail because
the older tap-injector still injects LINKERD2_PROXY_TAP_SVC_NAME with the usage of them
as the new version of tap-injector isn't ready yet which causes the proxy to fail with the following
error.

#6711 removes their usage *only*. so that the race condition won't happen when remove their definitions in a future release

**Comment by olix0r** [comment]
@Pothulapati This can happen in 2.12, right?

**Comment by Pothulapati** [comment]
@olix0r Yep, Totally. Will raise a PR shortly
