### ISSUE TITLE
 add `default-inbound-policy` to proxy injection flags

### ISSUE THREAD

**Issue by kleimkuhler** [linkerd/linkerd2#6754]
#6750 adds the `config.linkerd.io/default-inbound-policy` annotation for setting the default inbound policy for an injected proxy. As this affects how the proxy is configured, we should support this flag in `makeProxyFlags` so that it can be set with the `linkerd inject` command.

**Comment by ahmedalhulaibi** [comment]
Hey all, I can work on adding this flag
