### ISSUE TITLE
docker-in-docker(dind): dind containers lost external connectivity 

### ISSUE THREAD

**Issue by michaellzc** [linkerd/linkerd2#6758]
### What is the issue?

Same as https://github.com/linkerd/linkerd2/issues/3107, I only added the instruction to reproduce the issue and some workaround.

Docker-in-docker container lost external network connectivity.

### How can it be reproduced?

Spin up a K8S cluster and install linkerd `2.10.2` stable release (no `cni`, just the regular stuff)

```bash
kubectl -n default apply -f <the yaml below.yaml>
```

```yaml
kind: Pod
apiVersion: v1
metadata:
  name: debug-linkerd-dind
  annotations:
    config.linkerd.io/skip-outbound-ports: 1-65535
    linkerd.io/inject: enabled
    kubectl.kubernetes.io/default-container: docker
spec:
  containers:
    - name: docker
      image: docker:19.03.5-dind
      imagePullPolicy: IfNotPresent
      securityContext:
        privileged: true
        runAsUser: 0
        allowPrivilegeEscalation: true
```

Upon pod is ready, exec into the container. 

```bash
kubectl -n default exec -ti debug-linkerd-dind -- sh
```

In side the container, run and you should see some `502` error. Or just build a Docker image per the original issue.

```bash
docker run  --rm curlimages/curl:7.78.0 -L -vv http://curl.haxx.se
```

### Logs, error output, etc

`linker-proxy` container

```
[   683.593971s]  WARN ThreadId(01) server{port=80}: linkerd_app_core::errors: Failed to proxy request: error trying to connect: Connection refused (os error 111) client.addr=172.17.0.2:34320
```

#### `linkerd check` output

Controlplane is healthy.

```text
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-identity
----------------
√ certificate config is valid
√ trust anchors are using supported crypto algorithm
√ trust anchors are within their validity period
√ trust anchors are valid for at least 60 days
√ issuer cert is using supported crypto algorithm
√ issuer cert is within its validity period
‼ issuer cert is valid for at least 60 days
    issuer certificate will expire on 2021-08-28T08:39:27Z
    see https://linkerd.io/2.10/checks/#l5d-identity-issuer-cert-not-expiring-soon for hints
√ issuer cert is issued by the trust anchor

linkerd-webhooks-and-apisvc-tls
-------------------------------
√ proxy-injector webhook has valid cert
‼ proxy-injector cert is valid for at least 60 days
    certificate will expire on 2021-08-27T08:39:28Z
    see https://linkerd.io/2.10/checks/#l5d-proxy-injector-webhook-cert-not-expiring-soon for hints
√ sp-validator webhook has valid cert
‼ sp-validator cert is valid for at least 60 days
    certificate will expire on 2021-08-27T08:39:27Z
    see https://linkerd.io/2.10/checks/#l5d-sp-validator-webhook-cert-not-expiring-soon for hints

linkerd-api
-----------
√ control plane pods are ready
√ can initialize the client
√ can query the control plane API

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ control plane is up-to-date
√ control plane and cli versions match

linkerd-ha-checks
-----------------
√ pod injection disabled on kube-system

Status check results are √
```

### Environment

- Kubernetes Version: `1.18`
- Cluster Environment: IBM Cloud Kubernetes Service (IKS), should be able to reproduce it with `kind` or `k3s`, but I never try.
- Host OS: Ubuntu `1.8`
- Linkerd version: `2.10.2`

### Possible solution

Below is the iptables rules configured by `linkerd-init`.

```bash
iptables -t nat --list --line-numbers
```

```
Chain PROXY_INIT_REDIRECT (2 references)
num  target     prot opt source               destination         
1    RETURN     tcp  --  anywhere             anywhere             multiport dports 4190,4191 /* proxy-init/ignore-port-4190,4191/1630027032 */
2    REDIRECT   tcp  --  anywhere             anywhere             /* proxy-init/redirect-all-incoming-to-proxy-port/1630027032 */ redir ports 4143
```

In our use case, we don't want linkerd to proxy any outbound traffic fro our `dind` container anyway (hence the `config.linkerd.io/skip-outbound-ports: 1-65535`), so we can just tell iptables to not redirect when the source is coming from the `172.17.0.0/16` (the default docker subnet).

In a container with `NET_ADMIN` capabilities, run the following

```bash
iptables -t nat -R PROXY_INIT_REDIRECT 2 -p tcp -m comment --comment "proxy-init/redirect-all-incoming-to-proxy-port/workaround" -j REDIRECT --to-ports 4143 ! -s 172.17.0.0/16
```

I am not an iptables or linkerd expert, and this is just a hakcy workaround. I am expecting linkerd to have a better support for the `dind` use case out of the box.

Should `linkerd-init` somehow detects whether `dind` is used and add the negation rule automagically? Or introduce an option in `linkerd-init` to ignore a specific subnet?

### References

- [how linkerd-init works](https://linkerd.io/2.10/reference/architecture/#linkerd-init)

**Comment by michaellzc** [comment]
Hey, just checking in. What is linkerd team's thought on supporting `dind`?

**Comment by mateiidavid** [comment]
Hey @michaellzc, sorry for the delay in answering. I haven't managed to properly look into this yet. As far as we are concerned, we would love to support `dind`. 

I'll make some time to look into this properly, I think for now this will not be scoped for our `stable-2.11.0` release. The proposed solution looks fine, but I would like to see what alternatives we have here. If you have more thoughts you'd like to share, we can have a discussion here.

**Comment by michaellzc** [comment]
> Hey @michaellzc, sorry for the delay in answering. I haven't managed to properly look into this yet. As far as we are concerned, we would love to support `dind`.
> 
> I'll make some time to look into this properly, I think for now this will not be scoped for our `stable-2.11.0` release. The proposed solution looks fine, but I would like to see what alternatives we have here. If you have more thoughts you'd like to share, we can have a discussion here.

Hey, thanks for the reply. I totally understand that you guys are probably busy with the new stable release and other stuff.

To be frank, I am not a fan of my approach where we just ignore all traffic from the inner container, even though it works for this particular use case (ignore all outbound traffic). Is there any way we can write the iptables rule such that linkerd can also manage outbound traffic for the inner container? Sorry not a iptables power user, and I wish I wouldn't have to become one 😂

**Comment by adleong** [comment]
This seems like a fairly reasonable approach to me.

**Comment by mateiidavid** [comment]
Hey @michaellzc, thanks for being so patient with this. I've been on annual leave for the past two weeks so I hadn't had a chance to check out your answer. You've been very thorough, here's what I think:

> This may not necessarily work for us since we have a lot of workload running dind and they are all provisioned programmatically. I am hoping the service mesh layer can be transparent to the underlying application code where we don't have to adjust the way how workload is provisioned. However, we could write our own admission controller to override the behaviour of proxy-injector to customize the --subnet argument.

That makes sense. I think writing an admission controller just for this purpose would be a bit overkill. Ideally, if we're going to add a new `--subnet` option, it would be great if the solution would fix similar problems for other people in the community; asking everyone to implement their own admission controllers in case they have many workloads running dind is not very feasible. Also, I think admission web hooks are not always guaranteed to run in order? An admission controller here would have to depend on the proxy-injector running first but afaik there isn't really a way to enforce ordering here.

> Is it something like adding a new global configuration to the linkerd-config configmap where all pods will ignore the docker subnet? I feel like the subnet bypass config should be something a pod can opt-in with.

Yeah, I think you're right here.

> I understand introducing yet another annotation could make things more complicated, but there doesn't seem to be a more elegant solution.

We generally prefer not to introduce new annotations, but I think in this case (based on the work you've done researching this) it would make sense. We already have `--skip-inbound-ports` (and its outbound counterpart) as an annotation, we could follow the same model here and introduce a `--skip-subnets` option. An annotation would be a good fit, like you pointed out, we'd have to change the init container to support the option. Additionally, we'd have to change the proxy-injector to wire up the option through annotations, and it would probably be a good idea to also support this at install time, so we'd have to change the helm charts slightly. 

All of this would work in a similar fashion to how `--skip-inbound-ports` and `--skip-outbound-ports` work as options. If you'd be willing to contribute this, I'd be more than happy to help you along the way and provide examples on how to do it.

Let me know what you think.

**Comment by michaellzc** [comment]
Hey, the approach sounds good to me. I plan to work on the initial implementation in the next week or so. Will definitely reach out if I need any help.

**Comment by michaellzc** [comment]
- [ ] Update `linkerd-init` to support skipping subnets https://github.com/linkerd/linkerd2-proxy-init/pull/53
- [ ] Update `linkerd2` proxy injector to support `config.linkerd.io/skip-subnets` annotation

**Comment by mateiidavid** [comment]
@michaellzc thanks for the proxy-init PR! I released a new version of the init container. I think the only thing left to do now is to wire it all up in the proxy-injector, right?

**Comment by michaellzc** [comment]
> @michaellzc thanks for the proxy-init PR! I released a new version of the init container. I think the only thing left to do now is to wire it all up in the proxy-injector, right?

Hey @mateiidavid,

Yes, I plan to pick it up some time next week.

**Comment by michaellzc** [comment]
Hey @mateiidavid @alpeb, sorry for the radio silence in the past months. Things change quite a lot over the holiday career-wise. That said, I figured it's better to finish whatever I started and not to leave things hanging out there 😬. 

Anyhow, the PR to add the required annotation to configure the skip subnets flag in `proxy-init` is ready for review https://github.com/linkerd/linkerd2/pull/7631

**Comment by michaellzc** [comment]
cc @reevejd

Maybe you can monitor this thread? When this gets merged and a new stable version is out, consider upgrading linkerd and utilizing the new `config.linkerd.io/skip-subnets` annotation to get dind working with linked for good.

**Comment by mateiidavid** [comment]
@michaellzc no worries! Thanks for reaching out, and most of all, thanks for following through with a PR. I'm excited to have this brought across the finish line 🚀
