### ISSUE TITLE
Linkerd auto-injection breaks QoS Guaranteed

### ISSUE THREAD

**Issue by dcodix** [linkerd/linkerd2#6786]
### What is the issue?
Linkerd auto-inject breaks any Guaranteed QoS pod.
Both linkerd-proxy and linkerd-init don't have cpu and memory requests == limits so, any pod auto-injected cannot be Guaranteed QoS.
It is easy to solve for the linkerd-proxy container as we can use annotations for seting the req/lim, but we do not have such annotations for linkerd-init, making it imposible to have QoS Guaranteed.

### How can it be reproduced?
Launch a pod, Guaranteed QoS, meaning seting limits and requests for all containers for both cpu and memory being request==limit.
Let linkerd auto inject.
This pod is not Guaranteed anymore.

### Environment

It is the same on any environment.

### Possible solution
- Create annotations to be able to configure the linkerd-init resources
- Make some default that will not break the QoS Guaranteed, menaing req==lim

### Additional context
https://linkerd.slack.com/archives/C89RTCWJF/p1630403909121900

**Comment by mateiidavid** [comment]
Hi @dcodix,

First of all apologies, I was a bit shortsighted on slack and didn't properly look through our supported helm values. We _do in fact_ support custom values for resource limits and requests on the `linkerd-init` container, these have to be supplied at install time. 

You can find these values along with their respective defaults here: https://github.com/linkerd/linkerd2/blob/3e4f1369f507ba7be62de18b27cd44536017d17f/charts/linkerd2/values.yaml#L167-L177

If you'd like to install Linkerd and make sure the init container doesn't mark the pod as burstable (or anything other than guaranteed) then you'd have to just supply these through `--set` flags or your own values file (depending on how you want to install Linkerd). [You can find a guide for helm install here](https://linkerd.io/2.10/tasks/install-helm/), for the CLI something like the snippet below would work:
```sh
# Set memory and cpu limits to be the same as their request counterparts
# will ensure pod is guaranteed qos
# 
$ linkerd install \
    --set "proxyInit.resources.cpu.limit=10m,proxyInit.resources.memory.limit=10Mi" \
    | kubectl apply -f - 
```

This should fix your issue. :)

**Comment by mateiidavid** [comment]
I'll be closing this issue now since resource requests and limits can be overridden -- users can specify their own overrides to ensure pods are guaranteed.
