### ISSUE TITLE
Add `kubectl get`-style resource parsing to `conduit stat` CLI command

### ISSUE THREAD

**Issue by rmars** [linkerd/linkerd2#683]
The queries proposed in #627 require more sophisticated parsing than the stat summary endpoints currently do. (Current implementation in #671 just takes a singular resource and name).

Add parsing to the CLI to take queries such as the following and generate a series of `StatSummaryRequests`.

```
  # Stat all replication controllers and services together.
  conduit stat rc,services

  # Stat one or more resources by their type and names.
  conduit stat rc/web service/frontend pods/web-pod-13je7
```

**Comment by klingerf** [comment]
As part of this change, we should also enable kubectl-style resource parsing for the `--to*` and `--from*` flags.

For example, as it's currently implemented, if you wanted to query all of the namespaces that send traffic to the "foo" deployment in the default namespace, you'd use:

```
conduit stat ns --to foo --to-resource deployment --to-namespace default
```

But we should make the `--to` flag resource-aware, such that you can instead run:

```
conduit stat ns --to deploy/foo --to-namespace default
```

**Comment by siggy** [comment]
Moving this into 0.5.0 milestone. This task is mostly complete. What remains is handing comma-separated lists of resource strings.
