### ISSUE TITLE
Proxy trying to connect to stale endpoint IP address

### ISSUE THREAD

**Issue by mkrutik** [linkerd/linkerd2#6842]
## Bug Report
From time to time we run into connection problems, when we enabled the debug logs, we noticed that the proxy was trying to connect to outdated IP addresses.

### What is the issue?
The proxy is trying to connect to the stale IP address of the endpoint.

### How can it be reproduced?
We are still trying to reproduce it, but so far with no success. **One thing we've observed that could be a potential trigger for this problem is fast/huge scaling down the target PODs from ~10 instances to 2.**

### Logs, error output, etc
**`10.208.6.184`** destination SVC IP

[Logs](https://gist.github.com/mkrutik/05c2a36af6766b7d0109ad2d8493319d ) related to this svc IP - unfortunately they are in JSON format since I exported them from GCP.
I also have all the logs with TRACE and DEBUG for ~20 minutes after the problem occurred (~60K entries). I can share them too if you need them!

#### `linkerd check` output

```text
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-identity
----------------
√ certificate config is valid
√ trust anchors are using supported crypto algorithm
√ trust anchors are within their validity period
√ trust anchors are valid for at least 60 days
√ issuer cert is using supported crypto algorithm
√ issuer cert is within its validity period
√ issuer cert is valid for at least 60 days
√ issuer cert is issued by the trust anchor

linkerd-webhooks-and-apisvc-tls
-------------------------------
√ proxy-injector webhook has valid cert
√ proxy-injector cert is valid for at least 60 days
√ sp-validator webhook has valid cert
√ sp-validator cert is valid for at least 60 days

linkerd-api
-----------
√ control plane pods are ready
√ can initialize the client
√ can query the control plane API

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ control plane is up-to-date
√ control plane and cli versions match

Status check results are √

Linkerd extensions checks
=========================

linkerd-viz
-----------
√ linkerd-viz Namespace exists
√ linkerd-viz ClusterRoles exist
√ linkerd-viz ClusterRoleBindings exist
√ tap API server has valid cert
√ tap API server cert is valid for at least 60 days
√ tap API service is running
√ linkerd-viz pods are injected
√ viz extension pods are running
√ can initialize the client
√ viz extension self-check

Status check results are √
```

### Environment

- Kubernetes Version: `v1.20.8-gke.2100`
- Cluster Environment: `GKE` with `kube-proxy` 
- Linkerd version: `stable-2.10.2`

### Additional context 
⚠️ This happened several times a month for different PODs.

**Comment by kleimkuhler** [comment]
Thanks for the report @mkrutik. This may already be fixed by linkerd/linkerd2-proxy#1180 which has been included in the last several edge releases. If you are able to try a recent edge release, it would be helpful to know if it fixes it for you.

I'm not sure we ever got solid confirmation that that change was enough to fix this issue about stale endpoint IP addresses, so that would be good to know.

**Comment by mkrutik** [comment]
@kleimkuhler  thanks for so quick support 👍 I already thought about trying the `edge` version, but the problem is that we are only able to use the `stable` version for our production cluster (due to our internal requirements).
We are already using the latest `edge` version for our DEV / STAGE clusters, and this issue has not been encountered there yet (possibly due to less load and pod scaling).

Do you know when the new stable version will be released?

**Comment by kleimkuhler** [comment]
@mkrutik That's good to hears that you haven't encountered this issue in your dev/stage clusters.

We're close to a release candidate for `stable-2.11.0`—probably this week or next. If nothing major comes up in testing, we should have it released within September.

**Comment by olix0r** [comment]
@kleimkuhler I'm not confident that the issue you reference will address this -- that's specific to cases when the serverside proxy encounters errors, ensuring that the client side proxy can act on those errors. But based on the description and logs we see a different case entirely: the client is communicating with a service ClusterIP and it continues to reconnect to endpoints (but these connection attempts fail). To dig more deeply into this, we'd need to understand the state of the service's endpoints in this situation--i.e, `k get endpoints -n $ns $svc`. Assuming the target pod IPs are no longer in the service's endpoints, we'd want to look into the client's service discovery state. The command `linkerd diagnostics endpoints $svc.$ns.svc.cluster.local:$port` can help dump the controller's view of the service. If the endpoint IP isn't returned by the controller,  we'll want to get a better understanding of whether the proxy has been notified of the removal or not--we can probably help craft a narrower logging configuration to reduce the noise.

**Comment by mkrutik** [comment]
@olix0r thanks for explaining this. I will collect and attach that `diagnostics` information next time this problem will occur again.

**Comment by tobiaszheller** [comment]
@olix0r so linkerd can "serve stale endpoints" if some notification is lost? Have you thought about doing cyclic request for all endpoints just to cover case when notification is lost?
Looking from my perspective "self healing" mechanism is quite important so would be good to understand the approach here. 

Thanks for making that clear to me and thanks for making great product!

**Comment by jakub-koban** [comment]
@olix0r the problem occurred again. I'm including the diagnostic logs.
``` bash
> linkerd diagnostics endpoints carrier-depost.default.svc.cluster.local:9090
NAMESPACE   IP           PORT   POD                               SERVICE
default     10.16.5.67   9090   carrier-depost-5cbf7db9f9-zpz9h   carrier-depost.default
default     10.16.2.42   9090   carrier-depost-5cbf7db9f9-qbgtn   carrier-depost.default
```
``` shell
❯ k get endpoints carrier-depost -o json | jq ".subsets[0].addresses[] | .ip"
"10.16.2.42"
"10.16.5.67"
```
```
{"timestamp":"[185179.532834s]","level":"WARN","fields":{"message":"Failed to proxy request: HTTP Balancer service in fail-fast","client.addr":"10.16.2.42:35896"},"target":"linkerd_app_core::errors","spans":[{"orig_dst":"10.208.6.184:9090","name":"se │
│ rver"}],"threadId":"ThreadId(1)"}
```
```
❯ k get service | grep 10.208.6.184
service-sites                                 ClusterIP      10.208.6.184    <none>           6060/TCP,9090/TCP                              3y6d
```
```
❯ linkerd diagnostics endpoints service-sites.default.svc.cluster.local:9090
NAMESPACE   IP            PORT   POD                              SERVICE
default     10.16.4.80    9090   service-sites-69c65bc459-sdk7r   service-sites.default
default     10.16.6.86    9090   service-sites-69c65bc459-9td6m   service-sites.default
default     10.16.2.49    9090   service-sites-69c65bc459-9n2r6   service-sites.default
default     10.16.3.245   9090   service-sites-69c65bc459-mbp77   service-sites.default
```
```
❯ k get endpoints service-sites -o json | jq ".subsets[0].addresses | .[] | .ip"
"10.16.2.49"
"10.16.3.245"
"10.16.4.80"
"10.16.6.86"
```

**Comment by olix0r** [comment]
We've fixed a problem that sounds potentially related: if an HTTP load balancer had healthy endpoints, defunct endpoints are not necessarily eagerly removed until the balancer processes more requests. In this state, we would continually attempt to reconnect on these defunct endpoints. We've updated the proxy to avoid eagerly reconnecting in this case so the balancer has a chance to process service discovery updates before we attempt to reconnect.

To be clear: when we were in this state, the proxy should have been able to process requests without issue. We just generated a lot of log spam reporting that the endpoint was unreachable; but as soon as the balancer tried to process requests it would drop the defunct endpoint. We would never try to route requests to these endpoints.

This fix should be available in tomorrow's edge release, which is a release candidate for stable-2.11.0.

@jakub-koban your last post seems like it might describe a different issue? Your initial logs have lots of _failed to connect_ errors but nothing with _failed to proxy request_. I'd expect we've fixed the first issue but I don't have enough information to understand if these errors are related.

@tobiaszheller

> So linkerd can "serve stale endpoints" if some notification is lost?

 Based on the information we have, we were never actually sending traffic to stale endpoints.

The issue in this case--at least the one we fixed--is that, while the proxy had received the proper service discovery updates from the control plane, the balancer's state is only updated as it processes requests. This is generally fine and good--we don't spend CPU cycles maintaining state for unused resources. But in this case, it meant that we were not terminating the busy work of reconnecting to old endpoints. With the fix, these old endpoints will remain in the load balancer until a request is processed; but they won't continually try to reconnect.

**Comment by mkrutik** [comment]
UPD: a few weeks ago we updated Linkerd to the latest stable version - 2.11, and it looks like the problem is solved in this version 🕺 

@olix0r  @kleimkuhler thanks guys for your support 🙏
