### ISSUE TITLE
Honor `server.proxyProtocol=opaque` in client discovery

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#6857]
Server resources have a `proxyProtocol` field that can be set to _opaque_. This setting can eliminate the need to configure the annotation `config.linkerd.io/opaque-ports`. We should update the destination controller to use a pod:port's server configuration when possible.

Naively, we might have to update the destination controller to replicate the indexing logic in the policy controller; but, instead, we can probably have the destination controller establish a watch (via grpc over localhost for each pod and port). Note that we really only need to establish a watch for each pod-port that is actually resolved--most pods are only resolved through their `service` IP, where the destination controller uses the _service's_ opaque annotation. `Server` resources are only used when a client resolves a pod IP directly. Alternatively, we could add new bulk API endpoints to the controller API; but this may be overkill for now.

**Comment by mateiidavid** [comment]
Closed through #7184
