### ISSUE TITLE
Enable Linkerd proxy injection to work without "automountServiceAccountToken" set to true

### ISSUE THREAD

**Issue by HighWatersDev** [linkerd/linkerd2#6862]
## Feature Request

Enable Linkerd to inject proxy without needing `automountServiceAccountToken` set to `true` for mTLS. 

### What problem are you trying to solve?

By default `automountServiceAccountToken` is set to `false`. This is also recommended setting in certain environments.

### How should the problem be solved?

One of the proposed solutions is to use token volume projection [ref](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#service-account-token-volume-projection).

The other possible solution is to use admission controller as implemented by some other mesh services.

What do you want to happen? Add any considered drawbacks.

Alternative method of injecting proxy sidecar for mTLS without using service account token automount option.

Previously discussed in this issue: [#4651](https://github.com/linkerd/linkerd2/issues/4651)

**Comment by snoord** [comment]
I think this is resolved by #7117

**Comment by olix0r** [comment]
@snoord I think you're correct. It would be good to add a test that checks that a pod with `automountServiceAccounToken: false` becomes ready
