### ISSUE TITLE
Investigate success rate calculations in CLI stat summary

### ISSUE THREAD

**Issue by rmars** [linkerd/linkerd2#687]
As mentioned by @siggy in https://github.com/runconduit/conduit/pull/671#discussion_r179333611, prometheus can be used for success rate calculations.

```
sum(irate(response_total{direction = "inbound", classification="success"}[1m])) by (deployment)
/
sum(irate(response_total{direction = "inbound"}[1m])) by (deployment)
```

One thing to consider is that we can get request rate and success rate in one prometheus query in the current implementation (by slicing the query by `classification` and using `total_requests = success + fail` and `success_rate = success / total_requests`). If we use prometheus to calculate success rate, we'll be issuing an additional query.

**Comment by bourquep** [comment]
I am also observing >100% success rate in the "Top Line" grafana dashboard (v18.8.2):

<img width="1798" alt="image" src="https://user-images.githubusercontent.com/65096/44805811-373bac80-ab93-11e8-82c3-1dae28173f3b.png">
