### ISSUE TITLE
Support json log format in linkerd-viz

### ISSUE THREAD

**Issue by jcogilvie** [linkerd/linkerd2#6871]
### What problem are you trying to solve?
Unifying all my logs in json format, including linkerd-viz.

### How should the problem be solved?
There is precedent in `linkerd2`:

The main helm chart for linkerd supports log formats (plain and json) for the controller (`controllerLogFormat`) and the proxy (`proxy.logFormat`).  

What do you want to happen? Add any considered drawbacks.
Add support for the same json logging functionality into linkerd-viz as well as its helm chart.

### Any alternatives you've considered?

Is there another way to solve this problem that isn't as good a solution?

### How would users interact with this feature?
Setting the new log format field in linkerd-viz helm chart to `json`.

If you can, explain how users will be able to use this. Maybe some sample CLI
output?

**Comment by gusfcarvalho** [comment]
Hi guys, can I take this one?

**Comment by alpeb** [comment]
@gusfcarvalho Please go ahead! Happy to help answering any questions you might have :slightly_smiling_face:
