### ISSUE TITLE
Support json log format in linkerd-proxy-init

### ISSUE THREAD

**Issue by jcogilvie** [linkerd/linkerd2#6881]
### What problem are you trying to solve?
Unifying all my logs in json format, including linkerd-proxy-init.

### How should the problem be solved?
There is precedent in `linkerd2`:

The main helm chart for linkerd supports log formats (plain and json) for the controller (`controllerLogFormat`) and the proxy (`proxy.logFormat`).  Either `proxyInit.logFormat` should be added, or proxy-init should obey `proxy.logFormat`.

What do you want to happen? Add any considered drawbacks.
Add support for the same json logging functionality into linkerd-proxy-init as well as the linkerd helm chart.

### Any alternatives you've considered?

Is there another way to solve this problem that isn't as good a solution?

### How would users interact with this feature?
Setting the new log format field in linkerd helm chart to `json`.  Or, possibly, through the existing `proxy.logFormat` helm chart field.

If you can, explain how users will be able to use this. Maybe some sample CLI
output?

**Comment by jcogilvie** [comment]
Relates to #6871.

**Comment by gusfcarvalho** [comment]
Hi guys! Can I take this one as well?

**Comment by alpeb** [comment]
@gusfcarvalho of course! :slightly_smiling_face:
