### ISSUE TITLE
Change logging level of Destination pods 'Establishing watch' and 'Stopping watch' to debug

### ISSUE THREAD

**Issue by bartpeeters** [linkerd/linkerd2#6894]
Based on discussion https://github.com/linkerd/linkerd2/discussions/6877.

The Linkerd destination pods generate a lot of logs 'Establishing watch' and 'Stopping watch' for the Kubernetes services:
```
time="2021-09-14T10:22:54Z" level=info msg="Establishing watch on profile default/some-service.default.svc.cluster.local" addr=":8086" component=profile-watcher
time="2021-09-14T10:23:14Z" level=info msg="Stopping watch on profile default/some-service.default.svc.cluster.local" addr=":8086" component=profile-watche
```

These logs really add up if you have a lot of services in your K8 cluster.

Maybe we could change this log level from info to debug? Or do they have some use?

I think I'll be able to make a PR for this if nobody thinks this is a bad idea.

**Comment by olix0r** [comment]
@bartpeeters I think changing them to debug would be fine. A PR would be great!

**Comment by bartpeeters** [comment]
PR: https://github.com/linkerd/linkerd2/pull/6917

**Comment by olix0r** [comment]
Thanks @bartpeeters!
