### ISSUE TITLE
Update doc for distributed tracing

### ISSUE THREAD

**Issue by jadedevin13** [linkerd/linkerd2#6941]
## Bug Report
The doc still uses open census. https://linkerd.io/2.10/tasks/distributed-tracing/

### What is the issue?
I want to use the open telemetry now and java instrumentation but I'm not sure to set it up with linkerd.

**Comment by adleong** [comment]
Hi @jadedevin13 

The Linkerd proxy exports spans using the Open Census API.  The doc you linked gives a good overview of the architecture and how different backends can be swapped out.  The Open Census collector can also be configured to receive spans in a wide variety of formats.
