### ISSUE TITLE
tcp_connection_duration_ms metric is missing 

### ISSUE THREAD

**Issue by arempter** [linkerd/linkerd2#6958]
Hi, 

I have installed latest version of linkerd:
```
Client version: stable-2.10.2
Server version: stable-2.10.2
```

and when I check tcp connection metrics I do not get tcp_connection_duration_ms. I only have those
```
# HELP tcp_close_total Total count of closed connections
# HELP tcp_open_connections Number of currently-open connections
# HELP tcp_open_total Total count of opened connections
# HELP tcp_read_bytes_total Total count of bytes read from peers
# HELP tcp_write_bytes_total Total count of bytes written to peers
```

According to docs: 

The following labels are added only to metrics which are updated when a connection closes (tcp_close_total and tcp_connection_duration_ms):

classification: success if the connection terminated cleanly, failure if the connection closed due to a connection failure.

I can see that tcp_close_total is recording connection metrics:
```
tcp_close_total{direction="outbound",peer="dst",authority="kubernetes.default.svc.cluster.local:443",target_addr="192.168.64.4:8443",tls="no_identity",no_tls_reason="not_provided_by_service_discovery",dst_namespace="default",dst_service="kubernetes",errno=""} 1
tcp_close_total{direction="outbound",peer="src",target_addr="10.96.0.1:443",tls="no_identity",no_tls_reason="loopback",errno=""} 1
tcp_close_total{direction="inbound",peer="src",target_addr="0.0.0.0:4191",tls="no_identity",no_tls_reason="no_tls_from_remote",errno=""} 133
```

Are we missing something in the configuration? 

Thanks

#### `linkerd check` output

all green

### Environment

Client version: stable-2.10.2
Server version: stable-2.10.2
this is test minikube version: v1.19.0, but we have the same situation for pods on GCP k8s cluster

**Comment by arempter** [comment]
as an update I did downgrade to 2.9

```
Client version: stable-2.9.5
Server version: stable-2.9.5
```

and I can see that metric:

```
...
tcp_connection_duration_ms_sum{peer="dst",authority="server-service.default.svc.cluster.local:8090",direction="outbound",dst_control_plane_ns="linkerd",dst_deployment="server",dst_namespace="default",dst_pod="server-747745f764-85wh8",dst_pod_template_hash="747745f764",dst_service="server-service",dst_serviceaccount="default",tls="true",server_id="default.default.serviceaccount.identity.linkerd.cluster.local",errno=""} 140305
...
```

**Comment by adleong** [comment]
Hi @arempter!  You are correct that the tcp_connection_duration_ms_sum metric has been removed.  We found that storing this metric was consuming a lot of resources and not providing a lot of value.  Connections are typically long lived and the majority of connections end up in the largest histrogram bucket.  If you have a use-case for this metric, I'd love to chat more.

**Comment by arempter** [comment]
ok, thanks for response. I guess confusion came from docs, which still state that metric is generated.
We will find another one for your use case...

Thanks!
