### ISSUE TITLE
It needs to export linkerd CLI to my path everytime I open ubuntu, even if I have done it before.

### ISSUE THREAD

**Issue by NikhilSharmaWe** [linkerd/linkerd2#6971]
## Bug Report
![Screenshot (467)](https://user-images.githubusercontent.com/77074571/134883223-ca2a4fd5-9444-4d27-9537-fccbc0329392.png)

### What is the issue?
Every time I open ubuntu and I write "linkerd" it says command not found. It works when I export it in my Path and it happens repeatedly.
### Logs, error output, etc

(If the output is long, please create a [gist](https://gist.github.com/) and
paste the link here.)

#### `linkerd check` output

```text
your output here ...
```

### Environment

- Kubernetes Version:
- Cluster Environment: (GKE, AKS, kops, ...)
- Host OS:
- Linkerd version:

**Comment by Pothulapati** [comment]
@NikhilSharmaWe This isn't a linkerd issue. Please make sure that the linkerd binary's path is part of your `PATH` environment variable as per https://linuxize.com/post/how-to-add-directory-to-path-in-linux/

Once you do that, you should be able to execute the binary, without adding the path every time.

**Comment by NikhilSharmaWe** [comment]
Yes it's true, it works in my case too but when I try to run linkerd command again after closing the terminal it works only after I export linkerd CLI again. Is it a problem in my case only or it should behave like this.

**Comment by mateiidavid** [comment]
@NikhilSharmaWe this might be a problem in your case. You should make sure the path is persisted across sessions. Like @Pothulapati mentioned, this is related to your shell and operating system. Perhaps check that you're setting this in your `.bashrc` (or any equivalent that applies to your shell).
