### ISSUE TITLE
Failed to pull proxy image

### ISSUE THREAD

**Issue by adleong** [linkerd/linkerd2#7012]
Same problem over here, I just tried to install Linkerd and pods are not coming up, this is the last error:

```
Failed to pull image "cr.l5d.io/linkerd/proxy:stable-2.11.0": rpc error: code = Unknown desc = failed to pull and unpack image "cr.l5d.io/linkerd/proxy:stable-2.11.0": failed to resolve reference "cr.l5d.io/linkerd/proxy:stable-2.11.0": failed to do request: Head "https://cr.l5d.io/v2/linkerd/proxy/manifests/stable-2.11.0": dial tcp 54.70.21.136:443: i/o timeout
```

Going to the URL https://cr.l5d.io/v2/linkerd/proxy/manifests/stable-2.11.0 I get:

```
{
  "errors": [
    {
      "code": "MANIFEST_INVALID",
      "message": "manifest invalid",
      "detail": {}
    }
  ]
}
```

_Originally posted by @daviddesmet in https://github.com/linkerd/linkerd2/issues/7011#issuecomment-932645205_

**Comment by adleong** [comment]
@daviddesmet I have deleted your original comment and moved it to its own issue here.

**Comment by adleong** [comment]
@daviddesmet is this in AKS?  Is this a duplicate of https://github.com/linkerd/linkerd2/issues/6700?

**Comment by daviddesmet** [comment]
Yes it is, didn't notice the issue you are referring to. Please close this one.
