### ISSUE TITLE
Upgrade integration test is flaky

### ISSUE THREAD

**Issue by adleong** [linkerd/linkerd2#7026]
It seems the upgrade integration tests can sometime fail if the previous version pods have not shutdown by the time check is run.  

e.g. https://github.com/linkerd/linkerd2/pull/7005/checks?check_run_id=3797610098#step:7:501

**Comment by alpeb** [comment]
That was a failure of `TestCheckHelmStableBeforeUpgrade`, so before the upgrade is attempted. The problem got fixed by #7014. Now that test is being flaky in the latest run for another reason 🙃
