### ISSUE TITLE
check: stray newline

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#7031]
When running `linkerd check -o short`, there are two empty lines between the first header and status check:

```text
Linkerd core checks
===================


Status check results are √

Linkerd extensions checks
=========================

linkerd-viz
-----------

Status check results are √
```

Ideally, though, it would be preferable if we didn't print _any_ headers unless there was something to report in that section. It would be much preferable to simply have the output simply be:
```text
Status check results are √
```
when all checks pass.

The headers only make sense when they contextualize some other error output

**Comment by amitech** [comment]
I would like to work on it. Please assign it to me. 🙂
