### ISSUE TITLE
CLI check extension output in JSON broken

### ISSUE THREAD

**Issue by sterlingbates** [linkerd/linkerd2#7037]
### What is the issue?
`linkerd check -o json` will produce an initial core check in JSON format, but all extensions will thereafter ignore the `json` setting and dump in table format. If an extension is invoked on its own, it produces JSON format as expected.

### How can it be reproduced?
1. Install viz or multicluster (in my case both).
2. Run `linkerd check -o json` or `linkerd check --output=json`
3. Observe an initial JSON object, followed by standard table output.

```
user@host# ./linkerd check -o json
{
  "success": true,
  "categories": [
    {
      "categoryName": "kubernetes-api",
      "checks": [
        {
          "description": "can initialize the client",
          "result": "success"
        },
  ...
        }
      ]
    }
  ]
}

linkerd-multicluster
--------------------
√ Link CRD exists
√ Link resources are valid
	* data
√ remote cluster access credentials are valid
...

Status check results are √

linkerd-viz
-----------
√ linkerd-viz Namespace exists
√ linkerd-viz ClusterRoles exist
√ linkerd-viz ClusterRoleBindings exist
...
```

### Environment

- Kubernetes Version: 1.21.0
- Cluster Environment: Bare metal
- Host OS: Ubuntu
- Linkerd version: 2.11.0 stable

### Possible solution

If I had to guess, [PR 6038 modified the `output` param to the RunChecks call](https://github.com/linkerd/linkerd2/commit/8055a074fbc53d3371e25503a9cbdca559098e3e#diff-ad49e1a26f2606d0393d9088f4eccf5abbf7f62d8a3b58fa96fc9129e30a163dR142), from the earlier [simple value](https://github.com/linkerd/linkerd2/commit/8055a074fbc53d3371e25503a9cbdca559098e3e#diff-251191d61bca9248a9edd7b5f6d0029c2c15870638a916839a94802c35a218bfL326). I don't see any other substantive changes.

[edit: clarified link at the end]

**Comment by PremnishaTW** [comment]
I would like to try this, can I ?
