### ISSUE TITLE
Grafana: non-deployment centric dashboards

### ISSUE THREAD

**Issue by siggy** [linkerd/linkerd2#706]
`deployment.json` provides a deployment-centric Grafana dashboard. We should add new dashboards centering on other objects, some set of:
- [x] #788 `pod`
- [x] #843 `replication_controller`
- [ ] `namespace`
- [ ] `daemon_set`
- [ ] `k8s_job`
- [ ] `replica_set`
- [ ] `pod_template_hash`

Part of #420

**Comment by siggy** [comment]
Consider `namespace` only for `0.4.0` release.

**Comment by olix0r** [comment]
@siggy Can you update this issue with the current state of things?

**Comment by siggy** [comment]
@olix0r updated. pod and replication-controller are done.
