### ISSUE TITLE
Simulate-proxy: support other owner and dst types

### ISSUE THREAD

**Issue by siggy** [linkerd/linkerd2#707]
`simulate-proxy` exports metrics with `deployment` and `dst_deployment` labels. We should generalize this to export metrics with other k8s types, specifically:
- `daemon_set` / `dst_daemon_set`
- `k8s_job` / `dst_k8s_job`
- `replication_controller` / `dst_replication_controller`
- `replica_set` / `dst_replica_set`

Relevant TODO:
https://github.com/runconduit/conduit/blob/28d5007cdf0dbd93d50e20aea3e60689ab830a31/controller/script/simulate-proxy/main.go#L276-L294

**Comment by olix0r** [comment]
@siggy has this been done yet?

**Comment by siggy** [comment]
@olix0r it has not, the TODO in the code referenced above is still there.

**Comment by siggy** [comment]
simulate-proxy was removed in #1294, closing.
