### ISSUE TITLE
`tcp_open_connections` metric having stale policy label data

### ISSUE THREAD

**Issue by Pothulapati** [linkerd/linkerd2#7071]
## Bug Report

Currently, When a connection is being allowed and policy resources are created that also
allow that connection, the `tcp_open_connections` metric would still show the `saz`, and
`server` label values that were present when the connection was first created.

This meant that on dashboards like bcloud, you end up getting two workloads
with the same client and port, one with the `RPS` (as http response metric labels
are updated correctly), while another with the older policy but with TCP connections.

![image](https://user-images.githubusercontent.com/7892868/136788393-6ed22231-7184-4b1e-87e8-0d1920b90b29.png)

I think, We should also be updating the policy labels on connection metrics
even when the connection is allowed with newer policy resources.

@olix0r

**Comment by Pothulapati** [comment]
@olix0r Yep, you are right. I debugged further and realized the proxy is rendering the metrics correctly. I will debug further and update this if we think there is anything.

One other question, If a port is marked as `unauthenticated: true`, then the proxy stops adding the `client` metadata into the metrics right like `client_id`?

**Comment by zaharidichev** [comment]
@olix0r I think @Pothulapati's question is really around the `srv_name` label. And if we really forget any UI and what it does with the metrics the real question is this: Is there a situation where the `srv_name` label would have a different value for `tcp_open_connections` and `response_total` metrics that are measuring the same traffic. (on the same port, from the same client, etc).  I might be wrong but what I am seeing in the raw metrics output from the proxy is exactly this: 

**TCP_OPEN_CONNECTIONS**

```promql
sum (
    tcp_open_connections{
        deployment="ingress-nginx-controller-api",
        client_id="dive-viz.dive-viz.serviceaccount.identity.linkerd.cluster.local",target_port="10254"
        }
    ) by (
        deployment,
        target_port,
        srv_name,
        client_id
    )
```

```json
{
  "status": "success",
  "data": {
    "resultType": "vector",
    "result": [
      {
        "metric": {
          "client_id": "dive-viz.dive-viz.serviceaccount.identity.linkerd.cluster.local",
          "deployment": "ingress-nginx-controller-api",
          "srv_name": "default:all-unauthenticated",
          "target_port": "10254"
        },
        "value": [
          1634024218.133,
          "3"
        ]
      }
    ]
  }
}
```

**RPS**

```promql
sum(
    rate(
        response_total{
            direction="inbound",
            deployment="ingress-nginx-controller-api",
            client_id="dive-viz.dive-viz.serviceaccount.identity.linkerd.cluster.local",
            target_port="10254"}[1m]
            )
    )
    by (
        deployment,
        target_port,
        srv_name,
        client_id
    )
```

```json
{
  "status": "success",
  "data": {
    "resultType": "vector",
    "result": [
      {
        "metric": {
          "client_id": "dive-viz.dive-viz.serviceaccount.identity.linkerd.cluster.local",
          "deployment": "ingress-nginx-controller-api",
          "srv_name": "admin",
          "target_port": "10254"
        },
        "value": [
          1634024671.793,
          "0.30000000000000004"
        ]
      }
    ]
  }
}

```

We can see here two metrics with labels presumably describing traffic coming from the same client. Why are the `srv_name` labels different here? Furthermore, is `default:all-unauthenticated` a valid value at a time when there is another Server that captures this particular port?  Is it the case that this connection was established before the `admin` Server was created and this is why it still has `default:all-unauthenticated` value for `srv_name`. If that is the case, shouldn't this metric get updated?

**Comment by olix0r** [comment]
TCP server information is bound to the connection as it's established (and won't change dynamically).

HTTP request information is dynamic and may be updated for each request.

>  If that is the case, shouldn't this metric get updated (ie: the connections gauge decremented for this label, incremented with the correct srv_name label)?

Maybe. But it's complicated. And a bit of an edge case. What would we do for tcp_open_total and tcp_close_total, for instance? The TCP connection was opened with one server and closed with another?

If anything, we should probably just remove the srv_name label from TCP metrics to avoid this ambiguity.
