### ISSUE TITLE
Health check fails due to "connection closed before message completed" errors

### ISSUE THREAD

**Issue by oocx** [linkerd/linkerd2#7079]
### What is the issue?

For many of our services, requests fail sporadically with "connection closed before message completed" errors in the linkerd proxy logs.

In the application log, I can see that the health check completed successfully, but the linkerd proxy fails with the error.

It seems like the problem appears more often for services with higher traffic (not "high" in absolute numbers, just compared to the services which see the problem less often. In our case "high" is something like maybe 5-8 rps).

I think we may have had the issue for a while, but did not notice it until we deployed a new service that gets more traffic than the previous services.

The problem happens independent of the technology used by the service (we had the problem with .net / kestrel servers and with python based services).

### How can it be reproduced?

We have not figured that out yet.

#### `linkerd check` output

```text
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-identity
----------------
√ certificate config is valid
√ trust anchors are using supported crypto algorithm
√ trust anchors are within their validity period
√ trust anchors are valid for at least 60 days
√ issuer cert is using supported crypto algorithm
√ issuer cert is within its validity period
√ issuer cert is valid for at least 60 days
√ issuer cert is issued by the trust anchor

linkerd-webhooks-and-apisvc-tls
-------------------------------
√ proxy-injector webhook has valid cert
√ proxy-injector cert is valid for at least 60 days
√ sp-validator webhook has valid cert
√ sp-validator cert is valid for at least 60 days

linkerd-api
-----------
√ control plane pods are ready
√ can initialize the client
√ can query the control plane API

linkerd-version
---------------
√ can determine the latest version
‼ cli is up-to-date
    is running version 2.10.2 but the latest stable version is 2.11.0
    see https://linkerd.io/2.10/checks/#l5d-version-cli for hints

control-plane-version
---------------------
‼ control plane is up-to-date
    is running version 2.10.2 but the latest stable version is 2.11.0
    see https://linkerd.io/2.10/checks/#l5d-version-control for hints
√ control plane and cli versions match

Status check results are √

Linkerd extensions checks
=========================

linkerd-viz
-----------
√ linkerd-viz Namespace exists
√ linkerd-viz ClusterRoles exist
√ linkerd-viz ClusterRoleBindings exist
√ tap API server has valid cert
√ tap API server cert is valid for at least 60 days
√ tap API service is running
√ linkerd-viz pods are injected
√ viz extension pods are running
√ prometheus is installed and configured correctly
√ can initialize the client
√ viz extension self-check

Status check results are √

```

#### example linkerd log output from one of our services:

```text
[343825.616231s]  INFO ThreadId(01) linkerd_app_core::serve: Connection closed error=connection closed before message completed
[343827.493008s]  INFO ThreadId(01) linkerd_app_core::serve: Connection closed error=connection closed before message completed
[343830.353377s]  INFO ThreadId(01) linkerd_app_core::serve: Connection closed error=connection closed before message completed
[343832.272533s]  INFO ThreadId(01) linkerd_app_core::serve: Connection closed error=connection closed before message completed
```

### Environment

- Kubernetes Version: 1.19.4
- Cluster Environment: Rancher 2.5.6 (own installation on virtual machines in the Open Telekom Cloud)
- Host OS:
- Linkerd version: stable-2.10.2

### Additional context

I know this is not much context yet. I can try to provide more data if you can tell me what to collect and how.

(note: renamed the issue from "health checks fail" to "requests fail" because we see the bug for all kinds of requests)

**Comment by adleong** [comment]
Hey @oocx!

I'd recommend the following things in order to get more information:

* try the latest Linkerd release (stable-2.11.1)
* try increasing the proxy log level (https://linkerd.io/2.11/tasks/modifying-proxy-log-level/).  a log level of "linkerd=debug" might be a good place to start

**Comment by oocx** [comment]
@adleong Thanks, we will try that.

We currently think that we see most of these error messages when our application runs out of free thread pool threads, though I don't know why this would close existing connections as the message suggests.

**Comment by aleksanyan** [comment]
Am getting the same thing on 2.11.1
```
[ 17699.051244s]  INFO ThreadId(01) inbound: linkerd_app_core::serve: Connection closed error=connection closed before message completed
[ 21616.225989s]  INFO ThreadId(01) outbound: linkerd_app_core::serve: Connection closed error=connection closed before message completed
[ 21631.077684s]  INFO ThreadId(01) inbound: linkerd_app_core::serve: Connection closed error=connection closed before message completed
[ 23173.226149s]  INFO ThreadId(01) outbound: linkerd_app_core::serve: Connection closed error=connection closed before message completed
[ 23188.032115s]  INFO ThreadId(01) inbound: linkerd_app_core::serve: Connection closed error=connection closed before message completed
[ 23232.992413s]  INFO ThreadId(01) outbound: linkerd_app_core::serve: Connection closed error=connection closed before message completed
[ 23247.809867s]  INFO ThreadId(01) inbound: linkerd_app_core::serve: Connection closed error=connection closed before message completed
```

**Comment by adleong** [comment]
@aleksanyan I'd recommend increasing the log level (see above) to get some more information on what's happening here.

**Comment by aleksanyan** [comment]
@adleong thanks for the reply. 
I managed to somehow solve my problem a day ago. I'll try to describe some details hoping it helps for further investigation.
I mainly needed linkerd to evenly distribute the traffic on `grpc` service (https://github.com/tensorflow/serving) coming from another service in k8s.

Linkerd was injected on 2 Deployments (one sending requests to another). Second one (tensorflow serving) exposes 2 ports (8501 - grpc, 8500 - http rest api).
The `grpc` port was working fine and I clearly see the even load distribution, however `http` rest api port (used for health check) was causing the above INFO logs and giving time outs. After digging the docs I tried adding following into service object (of tensorflow serving) in kube, which solved the problem.

```
annotations:
    config.linkerd.io/opaque-ports: "8501"
```
It's a bit weird to me cause from the docs, as far as I understand it's not needed for a regular http server since it should detect the protocol automatically.

Linkerd version: `stable-2.11.1`
K8s version:  `v1.21.6`.
Hope this helps someone.

**Comment by adleong** [comment]
@aleksanyan glad to hear you got this working!  you're correct that regular http traffic should not require an opaque-ports setting so there's definitely SOMETHING fishy going on.  But since this is working for you now, I'm going to close the issue.  If you experience more problems in the future and want to dig back in, please feel free to file another issue.
