### ISSUE TITLE
Add PodDisruptionBudgets for multicluster components

### ISSUE THREAD

**Issue by Crevil** [linkerd/linkerd2#7082]
### What problem are you trying to solve?

When rolling the nodes of the cluster and/or scaling in it is possible for all the multicluster pods to be terminated.

### How should the problem be solved?

The helm chart should provision `PodDisruptionBudgets` for the multicluster components same as implemented in #5406 (discussed in #5398)

What do you want to happen? Add any considered drawbacks.

### Any alternatives you've considered?

Modyfing the output of the helm chart manually to add these features.

### How would users interact with this feature?

They wouldn't as it should be a default for keeping the setup safe.

**Comment by Crevil** [comment]
When starting to look into this I noticed there wasn't any tests (I could find at least) for the multicluster install command so I kicked this off with #7111 to get a baseline before changing any behaviour.

**Comment by kleimkuhler** [comment]
Hey @Crevil it looks like to wrap this up we need to add high availability mode and a PDB to the service mirror. Any interest in wrapping this up? No problem if not—just thought I'd check first!

**Comment by Crevil** [comment]
Thanks for picking this up @kleimkuhler 🎉
