### ISSUE TITLE
linkerd caching api requests responses

### ISSUE THREAD

**Issue by saba-bakhshi** [linkerd/linkerd2#7093]
Our health checker pod (which has linkerd enabled) is supposed to flag the service down if any of the depending pods is down (by making rest api requests). Currently, we're seeing this odd behaviour where If we bring down any pods, we see the rest apis are returning success. We suspect that it might be due to Linkerd caching the result. Is there a workaround for this?

**Comment by olix0r** [comment]
Linkerd doesn't cache responses. We'll need more specific details to understand what behavior you're seeing.

**Comment by saba-bakhshi** [comment]
I'm not able to share the exact logs due to security reasons but a detailed description of what we're seeing in our health checker pod with  linkerd being disabled is that let's say pod named A is down, then we get failure in Readiness check of service related to the down pod (connection refused). However, when the health pod has linkerd enabled , we get success on readiness checks for scaled down pods, which shouldn't be the case.

**Comment by adleong** [comment]
Hi @saba-bakhshi.  Without steps for reproducing this, there's not much help we can offer.  As @olix0r mentioned, Linkerd does not do any caching of responses.

**Comment by olix0r** [comment]
> we get failure in Readiness check of service related to the down pod (connection refused) 

If your health checks rely on the connection being refused, you'll need to avoid proxying these connections -- the linkerd proxy accepts requests before attempting to initiate a connection to the application. if the application isn't listening on the port, i'd expect these connections to fail with a 502 status code -- so an alternative might be to update the health check to consider non-200 responses as failures.

But I'm guessing here. We don't have a whole lot of information about the specific behavior you're seeing. If you can't share diagnostic information in Github, you'll have to diagnose these issues more fully on your own or engage a [support provider](https://linkerd.io/support-training/).

**Comment by saba-bakhshi** [comment]
thanks @olix0r. The solution you provided to consider non-200 responses as failures seems to be working.
