### ISSUE TITLE
Unused service discovery watches aren't reaped

### ISSUE THREAD

**Issue by briansmith** [linkerd/linkerd2#710]
Once we initiate service discovery for a name, we never cancel the polling for that name. When the Destination service is being used then this consumes resources on both the Controller side and the proxy side. In the case DNS is being used, DNS will be polled *forever*.

The DNS case is problematic, especially when running in minikube on a laptop, since it will cause network traffic every 5 seconds currently. This might increase significantly if/when we start honoring TTLs that could be as low as 1ms.

@olix0r I suggest we fix this in 0.5.

**Comment by olix0r** [comment]
I think that this relates closely to https://github.com/runconduit/conduit/issues/404 -- in order to have a sense of an "unused" discovery request, we need to be able to consider certain routes as idle. I agree that we should address these in 0.5

**Comment by olix0r** [comment]
Our primary case is addressed by #956. There is still some work to be done to finish this, described in #964

**Comment by hawkw** [comment]
I'm unsure if this is still the case. Currently, we drop any inactive `DestinationSet`s on every iteration of `poll_rpc`:
https://github.com/linkerd/linkerd2-proxy/blob/56f72dc5f18c92a54a7f2de471ab61c3175c77f6/src/control/destination/background/mod.rs#L172

We also now try to drop idle `DestinationSet`s any time a resolve request comes in and capacity isn't available for additional Destination service queries:
https://github.com/linkerd/linkerd2-proxy/blob/56f72dc5f18c92a54a7f2de471ab61c3175c77f6/src/control/destination/background/mod.rs#L214-L221
(although we do that to release Destination service query capacity, it also has the side effect of reaping any inactive DNS queries)

**Comment by olix0r** [comment]
@hawkw As described in #964, because these drops don't notify the poll_rpc task; and, since we have no guarantees about regular notification of this task, this is theoretically leaky.

In practice, I expect this isn't a high-priority concern.
