### ISSUE TITLE
smi trafficsplit v1alpha4 support?

### ISSUE THREAD

**Issue by hawk-liu** [linkerd/linkerd2#7155]
## Feature Request
smi trafficsplit v1alpha4 support in linkerd or linkerd-smi. 
v1alpha4/v1alpha3 support the trafficsplit based on http header/cookie.

### What problem are you trying to solve?
we are trying linkerd in our app, but we want serviceA-canary->serviceB-canary->serviceC-canary。NOT serviceA-canary->serviceB-pro->serviceC-canary.
because linkerd do not support sourcelabe like istio, we want to using trafficesplit based on HTTP header to solve this problem. 
But linkerd/linkerd-smi now only support smi v1alpha2, which only support weight based trafficsplit.

**Comment by ontehfritz** [comment]
This is something we really need as well to be able to traffic split by header! Would help us out a lot :)

**Comment by ezemegwara** [comment]
guys, any update if Linkerd now supports http based routing with smi v1alpha3/v1alpha4 ?

**Comment by Pothulapati** [comment]
Hey @ontehfritz @ezemegwara 

Some context here,
Currently, Linkerd is in the process of moving the support of SMI APIs into a separate extension in the [linkerd-smi](github.com/linkerd/linkerd-smi) repo. This means that the Linkerd components will not be listening for the SMI
APIs directly, and rely on the extension to do the conversion. The `linkerd-smi` will surface whatever functionality Linkerd
supports through the SMI APIs. The `linkerd-smi` project is up-to-date with the current functionality present.

Now coming to the question, Header based routing functionality is being worked on currently for the `2.12` release.
It's still in the early designs as it compasses routing in general i.e across protocols and across client, server. Once
we get a design doc up, We will make sure to provide a link here. This will have a different set of APIs specific to
Linkerd.

Once the functionality is up, I think it should be straight forward to add support for `v1alpha3` in the `linkerd-smi`
extension.

Thanks. Feel free to reply if you have any more questions!

**Comment by lucasarrudatrustly** [comment]
Any news about this issue?
the SMI spec is at v1alpha4 and linkerd is still on v1alpha2

**Comment by tao12345666333** [comment]
OSM is about to be archived, and I am not sure about the future development direction of SMI specifications. Do we still need to continue supporting it?

https://openservicemesh.io/blog/osm-project-update/

**Comment by wmorgan** [comment]
In [Linkerd 2.13, we introduced "dynamic request routing"](https://buoyant.io/blog/announcing-linkerd-2-13-circuit-breaking-dynamic-request-routing-fips) which covers this use case and more. That implementation was based on the Gateway API rather than SMI.

In future releasees, we will continue to invest in the Gateway API rather than SMI.

I am going to close this issue as wontfix, since it's about a specific SMI implementation, even though the original functionality requested is now present in Linkerd, just in a different form.
