### ISSUE TITLE
Multiple configs kubctl config files not supported

### ISSUE THREAD

**Issue by jerger** [linkerd/linkerd2#7161]
### What is the issue?
I'm working with multiple clusters and organized my kubectl to use multiple configuration files. My KUBECONFIG looks like:
`KUBECONFIG="/home/jem/.kube/custom-contexts/such-prod.yml:/home/jem/.kube/custom-contexts/such-dev.yml:/home/jem/.kube/config"`

linkerd does not respect this setting

```
linkerd check
Linkerd core checks
===================

kubernetes-api
--------------
√ can initialize the client
× can query the Kubernetes API
    the server has asked for the client to provide credentials
    see https://linkerd.io/2.11/checks/#k8s-api for hints

Status check results are ×
failed to run extensions checks: Unauthorized

```
while this works

```
linkerd --context dev --kubeconfig ~/.kube/custom-contexts/such-dev.yml check
Linkerd core checks
===================

kubernetes-api
--------------
√ can initialize the client
...
```

### How can it be reproduced?
see above.

### Logs, error output, etc
if I `strace linkerd check` I get:

```
...
newfstatat(AT_FDCWD, "/home/jem/.kube/config", {st_mode=S_IFREG|0660, st_size=4136, ...}, 0) = 0
openat(AT_FDCWD, "/home/jem/.kube/custom-contexts/such-prod.yml", O_RDONLY|O_CLOEXEC) = 3
epoll_ctl(4, EPOLL_CTL_ADD, 3, {EPOLLIN|EPOLLOUT|EPOLLRDHUP|EPOLLET, {u32=4219614936, u64=140333686077144}}) = -1 EPERM (Vorgang nicht zulässig)
epoll_ctl(4, EPOLL_CTL_DEL, 3, 0xc00098ef6c) = -1 EPERM (Vorgang nicht zulässig)
fstat(3, {st_mode=S_IFREG|0660, st_size=3961, ...}) = 0
read(3, "apiVersion: v1\nclusters:\n- clust"..., 3962) = 3961
read(3, "", 1)                          = 0
close(3)                                = 0
openat(AT_FDCWD, "/home/jem/.kube/custom-contexts/such-dev.yml", O_RDONLY|O_CLOEXEC) = 3
epoll_ctl(4, EPOLL_CTL_ADD, 3, {EPOLLIN|EPOLLOUT|EPOLLRDHUP|EPOLLET, {u32=4219614936, u64=140333686077144}}) = -1 EPERM (Vorgang nicht zulässig)
epoll_ctl(4, EPOLL_CTL_DEL, 3, 0xc00098ef6c) = -1 EPERM (Vorgang nicht zulässig)
fstat(3, {st_mode=S_IFREG|0660, st_size=2376, ...}) = 0
read(3, "apiVersion: v1\nclusters:\n- clust"..., 2377) = 2376
read(3, "", 1)                          = 0
close(3)                                = 0
openat(AT_FDCWD, "/home/jem/.kube/config", O_RDONLY|O_CLOEXEC) = 3
epoll_ctl(4, EPOLL_CTL_ADD, 3, {EPOLLIN|EPOLLOUT|EPOLLRDHUP|EPOLLET, {u32=4219614936, u64=140333686077144}}) = -1 EPERM (Vorgang nicht zulässig)
epoll_ctl(4, EPOLL_CTL_DEL, 3, 0xc00098ef6c) = -1 EPERM (Vorgang nicht zulässig)
fstat(3, {st_mode=S_IFREG|0660, st_size=4136, ...}) = 0
epoll_pwait(4, [], 128, 0, NULL, 1)     = 0
futex(0xc00041e550, FUTEX_WAKE_PRIVATE, 1) = 1
read(3, "apiVersion: v1\nclusters:\n- clust"..., 4137) = 4136
read(3, "", 1)                          = 0
close(3)                                = 0
...
```

### Environment

- Kubernetes Version: v1.19.13
- Cluster Environment: aws eks
- Host OS: ubuntu20.04
- Linkerd version: stable-2.11.0

**Comment by adleong** [comment]
@jerger as far as I can tell, this is not a Linkerd issue.  I'm not sure about the specifics of the permissions necessary to open the kubeconfig file.

**Comment by jerger** [comment]
As I can find no valid permission setting (have tested the most relaxing option already) and have no problem with other tools (kubectl, helmX) with my setup I do not agree to your rating.

**Comment by olix0r** [comment]
@jerger I hear you, but there's very little the linkerd developers can do about this if we can't reproduce the issue in some way. If you're up for it, you could try looking more closely at the code to understand what's going on. I believe all of the CLI's configuration is loaded via this function:

https://github.com/linkerd/linkerd2/blob/ff90f37e0171ae06d4876cd4885ac431fb663af7/pkg/k8s/k8s.go#L123-L132

As you can see, this code uses `k8s.io/client-go/tools/clientcmd` directly -- Linkerd doesn't actually implement its own logic for config file processing.
