### ISSUE TITLE
multicluster issues with EKS and GKE

### ISSUE THREAD

**Issue by ezemegwara** [linkerd/linkerd2#7197]
### What is the issue?
GKE cluster can't access services on EKS cluster. I don't know if this is related to the fact that Linkerd-gateway on EKS don't have IP address rather a DNS name. 
I have read https://github.com/linkerd/linkerd2/pull/4588 and https://github.com/linkerd/linkerd2/issues/4582 but I can't seem to get the solution 
 

### How can it be reproduced?

I installed Linkerd  and the Multi-cluster Components on both GKE and EKS clusters following the official documentation.
I linked both clusters, deployed the apps, ingress and mirrored the services.
all deployment and ingress pods was injected with Linkerd-proxy

The frontend service was deployed on GKE and mirrored to EKS. then the fronend app calls an app (currency service) located in EKS.

the good news is that I can hit the frontend from both clusters but the next call to the service (currency service) that's resides in EKS is not working and I get  this error

### rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp: lookup currencyservice on  10.3.240.10:53: no such host
could not retrieve currencies "

this means I think, EKS can reach GKE, but not vice versa.

I had similar issues when I installed Istio on both GKE and EKS running the same application. I resolved it by editing the Istio Gateway service on EKS with spec.externalIPs to use the IP address of EKS ELB. this didn't work with Linkerd, that's why I am suspecting Linkerd-gateway on EKS .

### Logs, error output, etc

(If the output is long, please create a [gist](https://gist.github.com/) and
paste the link here.)

#### `linkerd check` output

```text
Checking cluster: gke_thesis12345_europe-west3-a_gke-cluster .........

Linkerd core checks
===================

kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ control plane pods are ready
√ cluster networks contains all node podCIDRs

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist

linkerd-identity
----------------
√ certificate config is valid
√ trust anchors are using supported crypto algorithm
√ trust anchors are within their validity period
√ trust anchors are valid for at least 60 days
√ issuer cert is using supported crypto algorithm
√ issuer cert is within its validity period
√ issuer cert is valid for at least 60 days
√ issuer cert is issued by the trust anchor

linkerd-webhooks-and-apisvc-tls
-------------------------------
√ proxy-injector webhook has valid cert
√ proxy-injector cert is valid for at least 60 days
√ sp-validator webhook has valid cert
√ sp-validator cert is valid for at least 60 days
√ policy-validator webhook has valid cert
√ policy-validator cert is valid for at least 60 days

linkerd-version
---------------
√ can determine the latest version
‼ cli is up-to-date
    is running version 2.11.0 but the latest stable version is 2.11.1
    see https://linkerd.io/2.11/checks/#l5d-version-cli for hints

control-plane-version
---------------------
√ can retrieve the control plane version
‼ control plane is up-to-date
    is running version 2.11.0 but the latest stable version is 2.11.1
    see https://linkerd.io/2.11/checks/#l5d-version-control for hints
√ control plane and cli versions match

linkerd-control-plane-proxy
---------------------------
√ control plane proxies are healthy
‼ control plane proxies are up-to-date
    some proxies are not running the current version:
        * linkerd-destination-5c884cf786-nt25w (stable-2.11.0)
        * linkerd-identity-5d48f446db-95rgn (stable-2.11.0)
        * linkerd-proxy-injector-789f4f55fb-2448p (stable-2.11.0)
    see https://linkerd.io/2.11/checks/#l5d-cp-proxy-version for hints
√ control plane proxies and cli versions match

Status check results are √
-------------

Checking cluster: arn:aws:eks:eu-central-1:991114884934:cluster/eks-cluster .........

Linkerd core checks
===================

kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ control plane pods are ready

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist

linkerd-identity
----------------
√ certificate config is valid
√ trust anchors are using supported crypto algorithm
√ trust anchors are within their validity period
√ trust anchors are valid for at least 60 days
√ issuer cert is using supported crypto algorithm
√ issuer cert is within its validity period
√ issuer cert is valid for at least 60 days
√ issuer cert is issued by the trust anchor

linkerd-webhooks-and-apisvc-tls
-------------------------------
√ proxy-injector webhook has valid cert
√ proxy-injector cert is valid for at least 60 days
√ sp-validator webhook has valid cert
√ sp-validator cert is valid for at least 60 days
√ policy-validator webhook has valid cert
√ policy-validator cert is valid for at least 60 days

linkerd-version
---------------
√ can determine the latest version
‼ cli is up-to-date
    is running version 2.11.0 but the latest stable version is 2.11.1
    see https://linkerd.io/2.11/checks/#l5d-version-cli for hints

control-plane-version
---------------------
√ can retrieve the control plane version
‼ control plane is up-to-date
    is running version 2.11.0 but the latest stable version is 2.11.1
    see https://linkerd.io/2.11/checks/#l5d-version-control for hints
√ control plane and cli versions match

linkerd-control-plane-proxy
---------------------------
√ control plane proxies are healthy
‼ control plane proxies are up-to-date
    some proxies are not running the current version:
        * linkerd-destination-658d57c49b-n2drx (stable-2.11.0)
        * linkerd-identity-749d4b55c4-j5hdm (stable-2.11.0)
        * linkerd-proxy-injector-6f98987496-g5fn7 (stable-2.11.0)
    see https://linkerd.io/2.11/checks/#l5d-cp-proxy-version for hints
√ control plane proxies and cli versions match

Status check results are √
-------------
```

#### `linkerd multicluster check output for GKE
```

√ Link CRD exists
√ Link resources are valid
        * eks-cluster
√ remote cluster access credentials are valid
        * eks-cluster
√ clusters share trust anchors
        * eks-cluster
√ service mirror controller has required permissions
        * eks-cluster
√ service mirror controllers are running
        * eks-cluster
√ multicluster extension proxies are healthy
‼ multicluster extension proxies are up-to-date
    some proxies are not running the current version:
        * linkerd-gateway-7dc59f865f-94gfv (stable-2.11.0)
        * linkerd-service-mirror-eks-cluster-6574d77dff-x55p2 (stable-2.11.0)
    see https://linkerd.io/2.11/checks/#l5d-multicluster-proxy-cp-version for hints
√ multicluster extension proxies and cli versions match

Status check results are √


```

#### `linkerd multicluster check output for EKS
```
linkerd-multicluster
--------------------
√ Link CRD exists
√ Link resources are valid
        * gke-cluster
√ remote cluster access credentials are valid
        * gke-cluster
√ clusters share trust anchors
        * gke-cluster
√ service mirror controller has required permissions
        * gke-cluster
√ service mirror controllers are running
        * gke-cluster
√ multicluster extension proxies are healthy
‼ multicluster extension proxies are up-to-date
    some proxies are not running the current version:
        * linkerd-gateway-7dc59f865f-vv6vf (stable-2.11.0)
        * linkerd-service-mirror-gke-cluster-5bf4cc77f9-k2g27 (stable-2.11.0)
    see https://linkerd.io/2.11/checks/#l5d-multicluster-proxy-cp-version for hints
√ multicluster extension proxies and cli versions match

Status check results are √

```

#### Endpoint check for the service mirrored by EKS
```
kubectl --context=$gke -n online-shop get endpoints currencyservice-eks-cluster \
  -o 'custom-columns=ENDPOINT_IP:.subsets[*].addresses[*].ip'
kubectl --context=$eks -n linkerd-multicluster get svc linkerd-gateway \
  -o "custom-columns=GATEWAY_IP:.status.loadBalancer.ingress[*].ip"
ENDPOINT_IP
35.156.189.72
GATEWAY_IP
<none>

```
### Environment

- Kubernetes Version: 1.20 on GKE and 1.21 on EKS
- Cluster Environment: (GKE, AKS, kops, ...)
- Host OS:
- Linkerd version: Client version: stable-2.11.0

Please guys, any thought ?

**Comment by adleong** [comment]
Hi @ezemegwara!  I'm not super clear on the details of your environment, but it sounds like you may need to set the `--gateway-addresses` flag when running the `linkerd multicluster link` command to override the gateway address of the EKS cluster to the address of the ELB.

**Comment by ezemegwara** [comment]
I did try it also with this command and it didn't work 

linkerd --context=$eks multicluster link --cluster-name eks-cluster --gateway-addresses  x.x.x.x |
  kubectl --context=$gke apply -f –

**Comment by ezemegwara** [comment]
Hi @adleong come to think of it, I looked at Linkerd documentation on using the  --gateway-addresses  flag. it says

If specified overwrites gateway addresses **when gateway service is not type LoadBalancer** (comma separated list)

I am not an English native speaker but it sounds like it won't overwrite it because the Linkerd-gateway (ELB) is obviously of type**type LoadBalancer**

**Comment by ezemegwara** [comment]
So I can say that for now the gateway in EKS is not my problem. I recreated all the deployment and Linkerd multi cluster in two GKE clusters and still have the issues. the application here  [https://cloud.google.com/architecture/building-a-multi-cluster-service-mesh-on-gke-using-replicated-control-plane-architecture#installing_istio](url) is what I used for my Istio and tried recreating it with Linkerd.

All the Linkerd gateways are up, I can see all endpoints as expected. I went back to this Linkerd documentation [https://linkerd.io/2020/02/25/multicluster-kubernetes-with-service-mirroring/](url) about configuring ingress controllers (not ingress resources) to support wildcard and been able to rewrite the request header to the correct service name in the target cluster, since Linkerd multi cluster doesn't include ingress controllers.

Also there is another post that Linkerd can be an ingress controller. [https://linkerd.io/2017/04/06/a-service-mesh-for-kubernetes-part-viii-linkerd-as-an-ingress-controller/](url)

I am so confused, please guys I really need your help

**Comment by adleong** [comment]
@ezemegwara I looked into this and you are correct, if the gateway service is a LoadBalancer service with an external IP, the `multicluster link` command will prefer that over the `--gateway-addresses` flag.  To truly override the gateway address, I think you'll need to edit the `link` custom resource in the source cluster (GKE).  You'll notice that the `link` resource has a field in it's spec called `gatewayAddress: `.  You can edit this to change the address that GKE will use to send multicluster requests to EKS.  It sounds like you probably want to change that to the address of the ELB.

**Comment by ezemegwara** [comment]
> @ezemegwara I looked into this and you are correct, if the gateway service is a LoadBalancer service with an external IP, the `multicluster link` command will prefer that over the `--gateway-addresses` flag. To truly override the gateway address, I think you'll need to edit the `link` custom resource in the source cluster (GKE). You'll notice that the `link` resource has a field in it's spec called `gatewayAddress: `. You can edit this to change the address that GKE will use to send multicluster requests to EKS. It sounds like you probably want to change that to the address of the ELB.

**Comment by ezemegwara** [comment]
@adleong please any thought to my other comment. the issue is beyond EKS now as I tried to deploy it on 2 GKE clusters and still have the same issues

**Comment by adleong** [comment]
@ezemegwara regardless of the cloud provider, I recommend taking a look at the `Link` resources and ensuring that the `gatewayAddress` fields are set to the proper addresses.
