### ISSUE TITLE
Installation script not working on fedora

### ISSUE THREAD

**Issue by Bakrog** [linkerd/linkerd2#7202]
### What is the issue?
I’m trying the installation script in another virtual machine that I have and I found a problem with the checksum function.

### How can it be reproduced?
Have a machine or virtual machine running Fedora 34. Then install using the following command:
```shell
curl -fsL https://run.linkerd.io/install | sh
```

### Logs, error output, etc

It is downloading linkerd2-cli-stable-2.11.0-linux-amd64 and linkerd2-cli-stable-2.11.0-linux-amd64.sha256 but shasum generate the following result:

```shell
❯ /usr/bin/shasum -a256 $PWD/linkerd2-cli-stable-2.11.0-linux-amd64
f2ffddbd7339b3b402c8094cbc1d114105a5fe74309fc589cb4b6a7febf2f07d  /tmp/linkerd2.zxamqX/linkerd2-cli-stable-2.11.0-linux-amd64
```

Problem is that in the script you’re removing the first string so checksum fails:

```shell
❯ /usr/bin/shasum -a256 $PWD/linkerd2-cli-stable-2.11.0-linux-amd64 | sed -e 's/^.* //'
/tmp/linkerd2.zxamqX/linkerd2-cli-stable-2.11.0-linux-amd64
````

### Environment

- Host OS: Fedora 34
- Linkerd version: Latest

### Possible solution

correct command should be

```shell
❯ /usr/bin/shasum -a256 $PWD/linkerd2-cli-stable-2.11.0-linux-amd64 | sed -e 's/ .*$//'
f2ffddbd7339b3b402c8094cbc1d114105a5fe74309fc589cb4b6a7febf2f07d
```

### Additional context

Idk if this is only on this setup (Fedora 34) but I didn’t had problems with rocky linux (I think it was using openssl).

**Comment by alpeb** [comment]
That's a great catch, thanks! Would you like to issue a PR fixing it? It would be in the linkerd/website repo, in the `run.linkerd.io/public/install` and `run.linkerd.io/public/install-edge` files :slightly_smiling_face:

**Comment by Bakrog** [comment]
Sure, I'll do it today.
