### ISSUE TITLE
Linkerd2 is not compatible with Tencent Cloud managed service k8s

### ISSUE THREAD

**Issue by netcmcc** [linkerd/linkerd2#7217]
### What is the issue?

Linkerd2 is not compatible with Tencent Cloud managed service k8s. After installation, the policy container restarts repeatedly, and the log file is as follows:

How to make more logs for analysis, please give me a hint, if necessary, I can provide the environment kubeconfig to diagnose the problem.

### How can it be reproduced?

- Create new cluster on Tencent Cloud
- linkerd check --pre
- linkerd install | kubectl apply -f -
- kubectl get po -n linkerd

### Logs, error output, etc

```test
NAME                                      READY   STATUS    RESTARTS   AGE
linkerd-destination-549f568447-mlbfb      3/4     Running   1          64s
linkerd-identity-55b7f77dc-r6hns          2/2     Running   0          78s
linkerd-proxy-injector-7f74f96bf9-xhs7x   1/2     Running   0          57s


chenming@mingchen-mbp .kube % k logs linkerd-destination-549f568447-mlbfb policy
2021-11-04T05:51:38.191602Z  INFO linkerd_policy_controller: Admission controller server listening addr=0.0.0.0:9443
2021-11-04T05:51:38.192177Z  INFO serve{addr=0.0.0.0:9990}: linkerd_policy_controller::admin: HTTP admin server listening addr=0.0.0.0:9990
2021-11-04T05:51:38.192831Z  INFO grpc{addr=0.0.0.0:8090 cluster_networks=[10.0.0.0/8, 100.64.0.0/10, 172.16.0.0/12, 192.168.0.0/16]}: linkerd_policy_controller: gRPC server listening addr=0.0.0.0:8090
2021-11-04T05:51:38.201214Z  WARN servers: rustls::session: Sending fatal alert DecodeError
2021-11-04T05:51:38.201272Z ERROR servers: kube::client: failed with error error trying to connect: invalid certificate: BadDER
2021-11-04T05:51:38.201284Z  INFO servers: linkerd_policy_controller_k8s_api::watch: Failed error=failed to perform initial object list: HyperError: error trying to connect: invalid certificate: BadDER
2021-11-04T05:51:38.201387Z  WARN serverauthorizations: rustls::session: Sending fatal alert DecodeError
2021-11-04T05:51:38.201436Z ERROR serverauthorizations: kube::client: failed with error error trying to connect: invalid certificate: BadDER
2021-11-04T05:51:38.201452Z  INFO serverauthorizations: linkerd_policy_controller_k8s_api::watch: Failed error=failed to perform initial object list: HyperError: error trying to connect: invalid certificate: BadDER
2021-11-04T05:51:38.202124Z  WARN pods: rustls::session: Sending fatal alert DecodeError
2021-11-04T05:51:38.202184Z ERROR pods: kube::client: failed with error error trying to connect: invalid certificate: BadDER
2021-11-04T05:51:38.202194Z  INFO pods: linkerd_policy_controller_k8s_api::watch: Failed error=failed to perform initial object list: HyperError: error trying to connect: invalid certificate: BadDER
2021-11-04T05:51:39.202667Z  INFO serverauthorizations: linkerd_policy_controller_k8s_api::watch: Restarting
2021-11-04T05:51:39.202714Z  INFO servers: linkerd_policy_controller_k8s_api::watch: Restarting
2021-11-04T05:51:39.203709Z  INFO pods: linkerd_policy_controller_k8s_api::watch: Restarting
```

(If the output is long, please create a [gist](https://gist.github.com/) and
paste the link here.)

#### `linkerd check` output

```text
chenming@mingchen-mbp .kube % linkerd check --pre
Linkerd core checks
===================

kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

pre-kubernetes-setup
--------------------
√ control plane namespace does not already exist
√ can create non-namespaced resources
√ can create ServiceAccounts
√ can create Services
√ can create Deployments
√ can create CronJobs
√ can create ConfigMaps
√ can create Secrets
√ can read Secrets
√ can read extension-apiserver-authentication configmap
√ no clock skew detected

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

Status check results are √

=========================
chenming@mingchen-mbp .kube % linkerd check
Linkerd core checks
===================

kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
\ pod/linkerd-destination-549f568447-mlbfb container policy is not ready
```

### Environment

- Kubernetes Version: v1.18.4-tke.14
- Cluster Environment: Tencent Cloud Elastic Kubernetes Service

- Host OS: Tencent Linux 2.4   4.14.105-19-0020.1
- Linkerd version: stable-2.11.1

**Comment by olix0r** [comment]
Can you share the output of:

```
:; kubectl get secret $(kubectl get sa default -o json |jq  -r '.secrets[0].name') -o json |jq -r '.data["ca.crt"] | @base64d'    
```

We don't have access to a Tencent cluster, so I can't try this myself, but it would be helpful to see how the CA certificates are issued so we can figure out the best path forward. There is no security risk to sharing the CA certificate :)

**Comment by netcmcc** [comment]
-----BEGIN CERTIFICATE-----
MIICyDCCAbCgAwIBAgIBADANBgkqhkiG9w0BAQsFADAVMRMwEQYDVQQDEwprdWJl
cm5ldGVzMB4XDTIxMTEwNDAzMDk1OVoXDTMxMTEwMjAzMDk1OVowFTETMBEGA1UE
AxMKa3ViZXJuZXRlczCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMn0
O0qkLKNHewDpRkCj5Mvc+TX1Ngwnkds3uTRJPCxN7oPG2MYXxUNsRHkSUWfZqHv3
asoTEYyQnJyB2bXUya6D3Bslqss8gL3uNBzETqAW4RGxpQCq6t0bKqFqgGJSdeiT
ezkwKF9QAJn0g3rhsW0D29KCM017QJNvojL+dBPCFkouWUK+f09sYYuTDqHxKXRj
vO/5bj7hr8CaRqIUksZ+8oqxUxfnL+esWYVx9ruLMkTihoPd5WUmi6OKnRN+LOrE
5aYoVqBA3WymDZnvkNxb4GAwJiS7lAvAmj6zXMvz6kLGyY6WnHe4Q5xXAmqzOLnd
VFHqaZkL+zY/zuoVXMkCAwEAAaMjMCEwDgYDVR0PAQH/BAQDAgKUMA8GA1UdEwEB
/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBAKb3EzOG1HHYMc9ZW+te1D15bYet
4sACwn2l1LZpRQGNVyQhpYUyxb66I18p5kAdwDNAgIMwCsQAPuSfEdI2oKSGTp3B
VrKvR0DRx24Ur8xw1okggjm8/z0MZot7GVaQLCJLQCosnSDpRkwtQXxnnRQ/R5vq
p3ld+xRm7Yi7uheXDkKQX1s88F//AMNI0oTSXXZwltZdc2kNYNSc6Buc+K+dTFff
FeQLkWlaS8beZrbvl/V+IhM8we0tOMs2G7KaI5jYA5/+pDzgP8+1i8Yf4Q1TZCMm
xhW4R8D/YxLM3h6eWqXa2PvbjdNsyY4ZG1e+klViTEZvt21g8G6wh3s5vAQ=
-----END CERTIFICATE-----

**Comment by netcmcc** [comment]
> Can you share the output of:
> 
> ```
> :; kubectl get secret $(kubectl get sa default -o json |jq  -r '.secrets[0].name') -o json |jq -r '.data["ca.crt"] | @base64d'    
> ```
> 
> We don't have access to a Tencent cluster, so I can't try this myself, but it would be helpful to see how the CA certificates are issued so we can figure out the best path forward. There is no security risk to sharing the CA certificate :)

-----BEGIN CERTIFICATE-----
MIICyDCCAbCgAwIBAgIBADANBgkqhkiG9w0BAQsFADAVMRMwEQYDVQQDEwprdWJl
cm5ldGVzMB4XDTIxMTEwNDAzMDk1OVoXDTMxMTEwMjAzMDk1OVowFTETMBEGA1UE
AxMKa3ViZXJuZXRlczCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMn0
O0qkLKNHewDpRkCj5Mvc+TX1Ngwnkds3uTRJPCxN7oPG2MYXxUNsRHkSUWfZqHv3
asoTEYyQnJyB2bXUya6D3Bslqss8gL3uNBzETqAW4RGxpQCq6t0bKqFqgGJSdeiT
ezkwKF9QAJn0g3rhsW0D29KCM017QJNvojL+dBPCFkouWUK+f09sYYuTDqHxKXRj
vO/5bj7hr8CaRqIUksZ+8oqxUxfnL+esWYVx9ruLMkTihoPd5WUmi6OKnRN+LOrE
5aYoVqBA3WymDZnvkNxb4GAwJiS7lAvAmj6zXMvz6kLGyY6WnHe4Q5xXAmqzOLnd
VFHqaZkL+zY/zuoVXMkCAwEAAaMjMCEwDgYDVR0PAQH/BAQDAgKUMA8GA1UdEwEB
/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBAKb3EzOG1HHYMc9ZW+te1D15bYet
4sACwn2l1LZpRQGNVyQhpYUyxb66I18p5kAdwDNAgIMwCsQAPuSfEdI2oKSGTp3B
VrKvR0DRx24Ur8xw1okggjm8/z0MZot7GVaQLCJLQCosnSDpRkwtQXxnnRQ/R5vq
p3ld+xRm7Yi7uheXDkKQX1s88F//AMNI0oTSXXZwltZdc2kNYNSc6Buc+K+dTFff
FeQLkWlaS8beZrbvl/V+IhM8we0tOMs2G7KaI5jYA5/+pDzgP8+1i8Yf4Q1TZCMm
xhW4R8D/YxLM3h6eWqXa2PvbjdNsyY4ZG1e+klViTEZvt21g8G6wh3s5vAQ=
-----END CERTIFICATE-----

**Comment by olix0r** [comment]
Can you try installing with
```
--set policyController.image.name=ghcr.io/olix0r/policy-controller
--set policyController.image.version=nativetls.40ab223a
```

I've built a version of the policy controller that replaces `rustls` with `openssl` (from 40ab223a865b547d8fe010bf3f19b5ef2759c674).

**Comment by netcmcc** [comment]
> Can you try installing with
> 
> ```
> --set policyController.image.name=ghcr.io/olix0r/policy-controller
> --set policyController.image.version=nativetls.40ab223a
> ```
> 
> I've built a version of the policy controller that replaces `rustls` with `openssl` (from [40ab223](https://github.com/linkerd/linkerd2/commit/40ab223a865b547d8fe010bf3f19b5ef2759c674)).

it works!.

**Comment by olix0r** [comment]
@netcmcc Thanks for confirming!

We'll include this change in this week's edge release and this is probably worth including in a stable-2.10.2 patch release.
