### ISSUE TITLE
CNI fails when config is of version 0.4.0 or later

### ISSUE THREAD

**Issue by chdxD1** [linkerd/linkerd2#7247]
### What is the issue?
New pods fail to start because linkerd2-cni can't work with CNIs newer than 0.3.1.

### How can it be reproduced?
1. Create CNI config with version 0.4.0 or later
2. Install linkerd-cni
3. Try to create new pod

### Logs, error output, etc
```
Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "b7a96202d9b7e255e38810d9334f18c03d5a5e9a64669d0d12756e8cdb5af00c": incompatible CNI versions; config is "0.4.0", plugin supports ["0.1.0" "0.2.0" "0.3.0" "0.3.1"]
```

### Environment

- Kubernetes Version: v1.20.11
- Cluster Environment: kubeadm on Baremetal
- Host OS: Ubuntu 20.04
- Linkerd version: 2.11.1

### Possible solution
Update https://github.com/containernetworking/cni to a newer version (currently it's from 2018!) in https://github.com/linkerd/linkerd2/blob/814d7edd6efd357208138cda4e572f3934dc9d23/go.mod#L9

### Additional context
Changes in CNI v0.4 are described here: https://github.com/containernetworking/cni/blob/v1.0.1/Documentation/spec-upgrades.md#changes-in-cni-v04

**Comment by alpeb** [comment]
Thanks for the report @chdxD1. I've just pushed #7270 addressing this. I couldn't get ahold of a CNI implementation recent enough to test that (the latest calico config provided for k3d is still pinned to `0.3.1` and attempting any higher version breaks it), so I'd appreciate if you could give this a test. Should be included in next week's edge :wink:

**Comment by chdxD1** [comment]
@alpeb Thanks for the update, will test this in one of our clusters and report back :)

**Comment by alpeb** [comment]
Hi @chdxD1 , any news about your testing? :grimacing:
