### ISSUE TITLE
proxy: Add a `/logs.json` admin endpoint

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#7250]
It can be cumbersome (and expensive!) to get detailed proxy logs while the proxy is running. It would be better if we could stream logs with a custom log level from an admin endpoint, especially when gathering information for a bug report. Doing so should **not** alter the log level of logging emitted to stdout.

It's probably best to emit JSON-structured logs so that it's possible to inspect them programatically.

Questions:

* Should we use `POST /logs.json` to indicate that we're _creating_ a subscription? Or is this exposing an implementation detail? Is this effectively a `GET`?
* How should the tracing spec be encoded? If we're POSTing a log spec, we could use a JSON object to more explicitly express the logging spec. Or we could use the `EnvFilter` format that the proxy already accepts. The latter is probably
* We need to take care to ensure that writing response data does not cause more data to be logged! If, for instance, we tried to stream logs with `hyper=trace`, we could get into a situation where writing the logs response causes us to log more, which requires writing more logs in the response, etc... Ideally we would make it impossible for the logging endpoint to generate logs in this case.
* We'll need to think about how to authorize requests to this endpoint.

**Comment by hawkw** [comment]
Some questions that it would be good to answer:
 - How many concurrent log streaming requests do we expect to be in flight to a given proxy at a time?
 - Does each log streaming request have a separate filter, or do they all share the same filter?
 - Relatedly, are setting a filter and streaming logs separate endpoints, or a single endpoint?

I think that the implementation is _significantly_ simpler if there is a single filter for all log streaming requests (which can be separate from the stdout log filter), and there might be additional overhead from allowing separate filters per-request. However, if we think that's important for this, it is certainly possible to implement that.

**Comment by olix0r** [comment]
> How many concurrent log streaming requests do we expect to be in flight to a given proxy at a time?

Ultimately, an arbitrary number of concurrent requests. We could start by supporting a small/finite number of requests and failing with a 418 or something if we get additional requests.

> Does each log streaming request have a separate filter, or do they all share the same filter?
>
> Relatedly, are setting a filter and streaming logs separate endpoints, or a single endpoint?

I think each request would set its own filter.
