### ISSUE TITLE
linkerd blocks external smtp services like aws ses

### ISSUE THREAD

**Issue by runningman84** [linkerd/linkerd2#7280]
## Bug Report
If you enable linkerd in your pod access to an external email service like aws ses is blocked. I could solve it using outbound-ports-to-ignore 587

### What is the issue?
From my point of view linkerd should not touch any connection which is going outside of the cluster like an external email service.

### How can it be reproduced?
* Install linkerd
* Install an application which talks to an external email service like aws ses

### Logs, error output, etc

(If the output is long, please create a [gist](https://gist.github.com/) and
paste the link here.)

#### `linkerd check` output

```text
➜  ~ linkerd check
Linkerd core checks
===================

kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ control plane pods are ready
√ cluster networks contains all node podCIDRs

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist

linkerd-identity
----------------
√ certificate config is valid
√ trust anchors are using supported crypto algorithm
√ trust anchors are within their validity period
√ trust anchors are valid for at least 60 days
√ issuer cert is using supported crypto algorithm
√ issuer cert is within its validity period
√ issuer cert is valid for at least 60 days
√ issuer cert is issued by the trust anchor

linkerd-webhooks-and-apisvc-tls
-------------------------------
√ proxy-injector webhook has valid cert
√ proxy-injector cert is valid for at least 60 days
√ sp-validator webhook has valid cert
√ sp-validator cert is valid for at least 60 days
√ policy-validator webhook has valid cert
√ policy-validator cert is valid for at least 60 days

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ can retrieve the control plane version
√ control plane is up-to-date
√ control plane and cli versions match

linkerd-control-plane-proxy
---------------------------
√ control plane proxies are healthy
√ control plane proxies are up-to-date
√ control plane proxies and cli versions match

Status check results are √

Linkerd extensions checks
=========================

linkerd-viz
-----------
√ linkerd-viz Namespace exists
√ linkerd-viz ClusterRoles exist
√ linkerd-viz ClusterRoleBindings exist
√ tap API server has valid cert
√ tap API server cert is valid for at least 60 days
√ tap API service is running
‼ linkerd-viz pods are injected
    could not find proxy container for metrics-api-849c9c575f-5r4xx pod
    see https://linkerd.io/2.11/checks/#l5d-viz-pods-injection for hints
√ viz extension pods are running
× viz extension proxies are healthy
    No "linkerd-proxy" containers found in the "linkerd" namespace
    see https://linkerd.io/2.11/checks/#l5d-viz-proxy-healthy for hints

Status check results are ×

```

### Environment

- Kubernetes Version: 1.22
- Cluster Environment: (GKE, AKS, kops, ...) k3s
- Host OS: ubuntu
- Linkerd version: 2.11

**Comment by kleimkuhler** [comment]
@runningman84 Are you seeing the traffic being completely blocked or just a protocol timeout? SMTP is a server-speaks-first protocol, so I'd _expect_ traffic to be going through but it would be experiencing a 10 second protocol-detecton timeout.

Marking services as opaque is a server-side annotation in Linkerd, so if the service is not in your cluster then ignoring it is the only option right now. I don't think we have an issue open for marking outbound ports as opaque on the _client_, but that could possibly be useful here.

**Comment by runningman84** [comment]
I am using home-assistant which just talks to the aws ses service, this is the corresponding source code:
https://github.com/home-assistant/core/blob/dev/homeassistant/components/smtp/notify.py
It looks like if the connection takes longer than 5 seconds (maybe 10s because it tries twice) is is marked broken.

**Comment by kleimkuhler** [comment]
@runningman84 Okay yes if the app client is marking the connection as broken after 5 seconds, then the 10 second detection timeout could be the issue here.

As you mention in the description

> From my point of view linkerd should not touch any connection which is going outside of the cluster like an external email service

I think this is also your best path forward and is what we recommend in our documentation about server-speaks-first protocols outside of the cluster. I would add `587` to `skip-outbound-ports` configuration and that should fix your issue. Linkerd will not touch any connections on that port.
