### ISSUE TITLE
linkerd proxy exposing application ports listening on localhost

### ISSUE THREAD

**Issue by pankajmt** [linkerd/linkerd2#7289]
### What is the issue?

Even if the application has ports open just on the localhost interface, linkerd proxy forwards traffic to it. My colleague witnessed this recently with the nginx ingress controller, logs for which showed lots of unintended traffic on port 10247 it opens for configuration reloads within the pod. Istio had a similar bug until recently - https://istio.io/latest/blog/2021/upcoming-networking-changes/. Are there plans to fix this in linkerd anytime soon?

**Comment by cpretzer** [comment]
hi @pankajmt I think this is addressed in 2.11: https://github.com/linkerd/linkerd2/issues/6495

Does that look like the behavior that you expect?

**Comment by pankajmt** [comment]
Yeah, what would be the annotation to use it?

**Comment by kleimkuhler** [comment]
@pankajmt Correct this is actually fixed in the _current_ stable release 2.11.

**Comment by pankajmt** [comment]
Great. thanks!

**Comment by pankajmt** [comment]
Sorry I missed the version in the original comment from @cpretzer. Saw it now!
