### ISSUE TITLE
Export service without cluster name

### ISSUE THREAD

**Issue by ezemegwara** [linkerd/linkerd2#7291]
### What is the issue?
I want to maintain the service name after exporting it.
### How can it be reproduced?
I have a west and east multicluster in GKE and after exporting services, as expected: in the west cluster I get the exported service as `example-east`. as the app in west was programmed to send request to `example` service not `example-east` , is it possible to export a service without appending the cluster name to it?

### Environment

- Kubernetes Version: 1.20
- Cluster Environment: (GKE,)
- Host OS:
- Linkerd version:  Client version: stable-2.11.0

**Comment by adleong** [comment]
Hi @ezemegwara!

The cluster name will always be appended to mirror services created by the mutlicluster extension.

As a work-around for you app not being able to send requests to the `example-east` service, you could create an empty `example` service and a traffic split with only `example-east` as the backend.  This essentially forms a redirect from `example` to `example-east`.

**Comment by ezemegwara** [comment]
Thanks
