### ISSUE TITLE
tap api service is running -- FailedDiscoveryCheck in Tencent Cloud k8s service(TKE)

### ISSUE THREAD

**Issue by littleboy-j** [linkerd/linkerd2#7301]
### What is the issue?
install viz and then run linkerd viz check： 
‼ tap API service is running
    FailedDiscoveryCheck: failing or missing response from https://172.19.0.87:8089/apis/tap.linkerd.io/v1alpha1: Get "https://172.19.0.87:8089/apis/tap.linkerd.io/v1alpha1": read tcp 169.254.128.90:40336->172.19.0.87:8089: read: connection reset by peer
    see https://linkerd.io/2.11/checks/#l5d-tap-api for hints

   （ 172.19.0.87 is tap's pod ip ）

### How can it be reproduced?
1. Create new cluster on Tencent Cloud
2. linkerd install （fix error according to https://github.com/linkerd/linkerd2/issues/7217）
3. linkerd viz install
4. linkerd viz check

### Logs, error output, etc
- tap:tap
2021-11-17T16:41:24.35445613+08:00 time="2021-11-17T08:41:24Z" level=info msg="running version dev-undefined"
2021-11-17T16:41:24.37059226+08:00 time="2021-11-17T08:41:24Z" level=info msg="Using trust domain: cluster.local"
2021-11-17T16:41:24.381049354+08:00 time="2021-11-17T08:41:24Z" level=info msg="waiting for caches to sync"
2021-11-17T16:41:24.481204656+08:00 time="2021-11-17T08:41:24Z" level=info msg="caches synced"
2021-11-17T16:41:24.481272202+08:00 time="2021-11-17T08:41:24Z" level=info msg="starting admin server on :9998"
2021-11-17T16:41:24.481279207+08:00 time="2021-11-17T08:41:24Z" level=info msg="starting tap API server on :8089" addr=":8089" component=tap

- tap:linkerd-proxy
2021-11-17T18:50:55.67749838+08:00 [  7771.621026s]  INFO ThreadId(01) inbound:server{port=8089}: linkerd_app_inbound::policy::authorize::tcp: Connection denied server=tap-api tls=None(NoClientHello) client=169.254.128.90:38662
2021-11-17T18:50:55.677542795+08:00 [  7771.621042s]  INFO ThreadId(01) inbound: linkerd_app_core::serve: Connection closed error=unauthorized connection on server tap-api

#### `linkerd check` output

```text
Linkerd core checks
===================

kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ control plane pods are ready
√ cluster networks contains all node podCIDRs

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist

linkerd-identity
----------------
√ certificate config is valid
√ trust anchors are using supported crypto algorithm
√ trust anchors are within their validity period
√ trust anchors are valid for at least 60 days
√ issuer cert is using supported crypto algorithm
√ issuer cert is within its validity period
√ issuer cert is valid for at least 60 days
√ issuer cert is issued by the trust anchor

linkerd-webhooks-and-apisvc-tls
-------------------------------
√ proxy-injector webhook has valid cert
√ proxy-injector cert is valid for at least 60 days
√ sp-validator webhook has valid cert
√ sp-validator cert is valid for at least 60 days
√ policy-validator webhook has valid cert
√ policy-validator cert is valid for at least 60 days

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ can retrieve the control plane version
√ control plane is up-to-date
√ control plane and cli versions match

linkerd-control-plane-proxy
---------------------------
√ control plane proxies are healthy
√ control plane proxies are up-to-date
√ control plane proxies and cli versions match

Status check results are √

Linkerd extensions checks
=========================

linkerd-viz
-----------
√ linkerd-viz Namespace exists
√ linkerd-viz ClusterRoles exist
√ linkerd-viz ClusterRoleBindings exist
√ tap API server has valid cert
√ tap API server cert is valid for at least 60 days
‼ tap API service is running
    FailedDiscoveryCheck: failing or missing response from https://172.19.0.87:8089/apis/tap.linkerd.io/v1alpha1: Get "https://172.19.0.87:8089/apis/tap.linkerd.io/v1alpha1": read tcp 169.254.128.90:45688->172.19.0.87:8089: read: connection reset by peer
    see https://linkerd.io/2.11/checks/#l5d-tap-api for hints
√ linkerd-viz pods are injected
√ viz extension pods are running
√ viz extension proxies are healthy
√ viz extension proxies are up-to-date
√ viz extension proxies and cli versions match
√ prometheus is installed and configured correctly
√ can initialize the client
√ viz extension self-check

Status check results are √
```

### Environment

- Kubernetes Version: v1.18.4-tke.14
- Cluster Environment: Tencent Cloud Elastic Kubernetes Service
- Host OS: Tencent Linux 2.4（based on CentOS 7）
- Linkerd version: stable-2.11.1

**Comment by littleboy-j** [comment]
Who can help to solve this problem

**Comment by adleong** [comment]
As the health check says, I recommend taking a look at https://linkerd.io/2.11/checks/#l5d-tap-api

There are some conditions that must be met by your kubernetes cluster: namely that the tap server must be reachable by the kube apiserver and that the aggregation layer must be enabled.  Please verify that these are true for TKE.

**Comment by littleboy-j** [comment]
It's hard to check。

According to https://github.com/linkerd/linkerd2/issues/7233, I add below section to solve this problem temporarily, thanks.

networks:
      - cidr: 0.0.0.0/0
