### ISSUE TITLE
Bring your own Jaeger not work

### ISSUE THREAD

**Issue by serg-bs** [linkerd/linkerd2#7322]
### How can it be reproduced?

0. minikube start
1. linkerd install | kubectl apply -f -
2. linkerd jaeger install | kubectl apply -f -
3. wget https://raw.githubusercontent.com/diazjf/meow-micro/main/jaeger/jaeger-all-in-one.yaml
4. k apply -f jaeger-all-in-one.yaml
5. linkerd jaeger install --set collector.jaegerAddr='http://jaeger-collector.default.svc.cluster.local:14268/api/traces' | kubectl apply -f -

linkerd jaeger install --set collector.jaegerAddr='http://jaeger-collector.default.svc.cluster.local:14268/api/traces' >1.yaml
inkerd jaeger install >2.yaml

1.yaml and 2.yaml  have no difference in jaegerAddr

If I made changes in yaml file and apply it. It's still not work.
Is this functionality is depricated? 
Is it tested with jaeger operator?

**Comment by olix0r** [comment]
This probably depends on what version of Linkerd you are using, but `collector.jaegerAddr` isn't currently a valid setting in the [linkerd-jaeger template](https://github.com/linkerd/linkerd2/tree/1bf0da4f69c2a010b80ebf608754b5796375ee83/jaeger/charts/linkerd-jaeger). Perhaps you want to use `webhook.collectorSvcAddr`?

**Comment by Pothulapati** [comment]
Hey @serg-bs, 

The proxies always send the traces to the OTLP collector right now which is inject. So, To use a different jaeger, you can just update the `collector-config` ConfigMap that is created to use the different jaeger endpoint.

You can also choose not to use the OTLP collector in the jaeger extension in which case, you have to set the `webhook.collectorSvcAddr` and `webhook.collectorSvcAccount` values to the external Collector Srvc URL and Svc account name respectively.

Hope this answers your question. Feel free to re-open the issue if it doesn't.
