### ISSUE TITLE
ci: Proposal for integration test requirements

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#7328]
The integration test suite is currently pretty heavyweight (#7246). Until we find a way to speed it up, I propose the following:

* We remove the branch requirement for integration tests. As a convention, we should only merge changes if they've all passed.
* We skip the integration test workflow when a special `xxx/no-integration` label is set on the PR.
* We can then use this, for instance, when adding release notes or other trivial changes.
* We add this label automatically on npm dependency updates.

Thoughts? Objections?

**Comment by alpeb** [comment]
Sounds good to me :+1:

**Comment by mateiidavid** [comment]
Don't have any objections to it, sounds good!
