### ISSUE TITLE
Failure on "control plane pods are ready"

### ISSUE THREAD

**Issue by formichunter** [linkerd/linkerd2#7350]
### What is the issue?
Green field installation of linkerd fails at 'control plane pods are ready' stage in 'linkerd check' command

### How can it be reproduced?
linkerd check --pre passes all tests
curl -sL run.linkerd.io/install | sh
linkerd install | kubectl apply -f -
linkerd check

### Logs, error output, etc
```
@lfs258:~$ kc -n linkerd logs linkerd-proxy-injector-8457d99c9b-mjx46 -c linkerd-proxy -f
[     0.158330s]  INFO ThreadId(01) linkerd2_proxy::rt: Using single-threaded proxy runtime
[     0.409284s]  INFO ThreadId(01) linkerd2_proxy: Admin interface on 0.0.0.0:4191
[     0.410337s]  INFO ThreadId(01) linkerd2_proxy: Inbound interface on 0.0.0.0:4143
[     0.410340s]  INFO ThreadId(01) linkerd2_proxy: Outbound interface on 127.0.0.1:4140
[     0.410342s]  INFO ThreadId(01) linkerd2_proxy: Tap DISABLED
[     0.410344s]  INFO ThreadId(01) linkerd2_proxy: Local identity is linkerd-proxy-injector.linkerd.serviceaccount.identity.linkerd.cluster.local
[     0.410346s]  INFO ThreadId(01) linkerd2_proxy: Identity verified via linkerd-identity-headless.linkerd.svc.cluster.local:8080 (linkerd-identity.linkerd.serviceaccount.identity.linkerd.cluster.local)
[     0.410348s]  INFO ThreadId(01) linkerd2_proxy: Destinations resolved via linkerd-dst-headless.linkerd.svc.cluster.local:8086 (linkerd-destination.linkerd.serviceaccount.identity.linkerd.cluster.local)
[     2.873134s]  INFO ThreadId(02) daemon:admin{listen.addr=0.0.0.0:4191}: linkerd_app_core::serve: Connection closed error=TLS detection timed out
[     4.875903s]  INFO ThreadId(02) daemon:admin{listen.addr=0.0.0.0:4191}: linkerd_app_core::serve: Connection closed error=TLS detection timed out
[    15.442355s]  WARN ThreadId(01) linkerd_app: Waiting for identity to be initialized...
[    18.491072s]  WARN ThreadId(01) policy:watch{port=8443}:controller{addr=linkerd-policy.linkerd.svc.cluster.local:8090}: linkerd_app_core::control: Failed to resolve control-plane component error=no record found for name: linkerd-policy.linkerd.svc.cluster.local. type: SRV class: IN
[    18.492815s]  WARN ThreadId(01) policy:watch{port=8443}:controller{addr=linkerd-policy.linkerd.svc.cluster.local:8090}: linkerd_app_core::control: Failed to resolve control-plane component error=no record found for name: linkerd-policy.linkerd.svc.cluster.local. type: SRV class: IN
[    20.454611s]  WARN ThreadId(01) trust_dns_proto::xfer: error notifying wait, possible future leak: TrySendError { kind: Disconnected }
[    20.973865s]  INFO ThreadId(02) daemon:identity: linkerd_app: Certified identity: linkerd-proxy-injector.linkerd.serviceaccount.identity.linkerd.cluster.local
[    22.273778s]  WARN ThreadId(01) outbound:server{orig_dst=10.96.0.1:443}:controller{addr=linkerd-dst-headless.linkerd.svc.cluster.local:8086}: linkerd_app_core::control: Failed to resolve control-plane component error=no record found for name: linkerd-dst-headless.linkerd.svc.cluster.local. type: SRV class: IN
[    22.275113s]  WARN ThreadId(01) outbound:server{orig_dst=10.96.0.1:443}:controller{addr=linkerd-dst-headless.linkerd.svc.cluster.local:8086}: linkerd_app_core::control: Failed to resolve control-plane component error=no record found for name: linkerd-dst-headless.linkerd.svc.cluster.local. type: SRV class: IN
[    23.109655s]  INFO ThreadId(01) inbound:server{port=9995}:rescue{client.addr=192.168.1.175:32984}: linkerd_app_core::errors::respond: Request failed error=error trying to connect: Connection refused (os error 111)
[    24.122766s]  INFO ThreadId(01) inbound:server{port=9995}:rescue{client.addr=192.168.1.175:32992}: linkerd_app_core::errors::respond: Request failed error=error trying to connect: Connection refused (os error 111)
[    25.129739s]  INFO ThreadId(01) inbound:server{port=9995}:rescue{client.addr=192.168.1.175:33000}: linkerd_app_core::errors::respond: Request failed error=error trying to connect: Connection refused (os error 111)
[    25.274046s]  WARN ThreadId(01) outbound:server{orig_dst=10.96.0.1:443}: linkerd_stack::failfast: TCP Server entering failfast after 3s
[    25.274195s]  INFO ThreadId(01) outbound: linkerd_app_core::serve: Connection closed error=TCP Server service in fail-fast
[    25.274210s]  INFO ThreadId(01) outbound: linkerd_app_core::serve: Connection closed error=TCP Server service in fail-fast
[    25.274214s]  INFO ThreadId(01) outbound: linkerd_app_core::serve: Connection closed error=TCP Server service in fail-fast
[    25.274217s]  INFO ThreadId(01) outbound: linkerd_app_core::serve: Connection closed error=TCP Server service in fail-fast
[    25.274220s]  INFO ThreadId(01) outbound: linkerd_app_core::serve: Connection closed error=TCP Server service in fail-fast

@lfs258:~$ kc get all -n linkerd
NAME                                          READY   STATUS             RESTARTS          AGE
pod/linkerd-destination-675cfbb667-6hvql      2/4     CrashLoopBackOff   831 (46s ago)     23h
pod/linkerd-identity-6b78ff444f-8m265         2/2     Running            2 (16m ago)       23h
pod/linkerd-proxy-injector-8457d99c9b-mjx46   1/2     CrashLoopBackOff   396 (4m45s ago)   23h
```

#### `linkerd check` output

@lfs258:~$ linkerd check
Linkerd core checks
===================

kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
× control plane pods are ready
    pod/linkerd-destination-675cfbb667-6hvql container policy is not ready
    see https://linkerd.io/2.11/checks/#l5d-api-control-ready for hints

### Environment

- Kubernetes Version: ~$ kc version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:45:37Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:39:34Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
- Cluster Environment: VMware VM 2 node setup (controller/worker and worker)
- Host OS: @lfs258:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic
@lfs258:~$
- Linkerd version: $ linkerd version
Client version: stable-2.11.1
Server version: stable-2.11.1

### Additional context
~$ kc exec -it nettool -- nslookup linkerd-identity-headless.linkerd.svc.cluster.local
Server:         10.96.0.10
Address:        10.96.0.10#53

Name:   linkerd-identity-headless.linkerd.svc.cluster.local
Address: 192.168.136.130

$ kc get ep -n linkerd
NAME                        ENDPOINTS              AGE
linkerd-dst                                        23h
linkerd-dst-headless                               23h
linkerd-identity            192.168.136.130:8080   23h
linkerd-identity-headless   192.168.136.130:8080   23h
linkerd-policy                                     23h
linkerd-policy-validator                           23h
linkerd-proxy-injector                             23h
linkerd-sp-validator                               23h

~$ kc config view
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://k8scp:6443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: kubernetes-admin
  name: kubernetes-admin@kubernetes
current-context: kubernetes-admin@kubernetes
kind: Config
preferences: {}
users:
- name: kubernetes-admin
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED

**Comment by formichunter** [comment]
https://linkerd.io/2.11/tasks/troubleshooting/#l5d-existence-controller

Why does your documentation reference the controller pods when I don't see any existence of them during deployment?  Should there be controller pods?

twizod@lfs258:~$ kubectl -n linkerd get po --selector linkerd.io/control-plane-component=controller
No resources found in linkerd namespace.
twizod@lfs258:~$ linkerd version
Client version: stable-2.11.1
Server version: stable-2.11.1
twizod@lfs258:~$

**Comment by adleong** [comment]
hi @formichunter!  looks like the example in the docs there is slightly out of date, the controller deployment no longer exists.  

As for why the control plane isn't coming up, it looks like the destination controller is in CrashLoopBackoff.  I'd recommend looking at the logs of the containers in the linkerd-destination pod to see why it's crashing.

**Comment by formichunter** [comment]
Yes, I got 10.96.0.1 dns timeouts and I noticed that my podCIDR was the same as my host network, 192.168.1.0/24.  I decided that the only reason it was having timeouts could be b/c of this and destroyed my k8s cluster and rebuilt it with PodCIDR on the 172.16.0.0/16 network while keeping host network the same.  I redeployed linkerd after rebuilding the k8s cluster and it worked fine.
