### ISSUE TITLE
ci: replace blocking `time.Sleep` calls with retries for transient errors in tests

### ISSUE THREAD

**Issue by mateiidavid** [linkerd/linkerd2#7372]
To address slow tests in the `deep` suite (see #7246), I had a look at what can be improved in individual tests to cut down on the execution time. I noticed in quite a few tests, we're susceptible to transient errors. These errors generally have to do with pods being in an unready state; either the containers have not been marked as ready, or the application has not started sending and receiving traffic.

In a few tests, we seem to mitigate this with `TestHelper.RetryFor(timeout, func())`. A particular function is retried for as long as the specified timeout. For example, we do this in [`localhost_test`](https://github.com/linkerd/linkerd2/blob/f92e77f7f0080544f62e1567c5c997d4be25637c/test/integration/localhost/localhost_test.go#L66-#L73).

In other tests, we seem to be blocking the execution with `time.Sleep(duration)` to mitigate the same class of transient errors: the client (or server) not being ready to send or receive traffic. Our values are arbitrary and put there as a "good measure", but can end up adding a bit of overhead. I think we could shave some time off the tests if we swap out `time.Sleep()` with `RetryFor()`. 

Currently, we use `time.Sleep()` in the following tests:

```sh
:; rg 'time.Sleep'
install_test.go
178:    time.Sleep(10 * time.Second)

skipports/skip_ports_test.go
63:             time.Sleep(30 * time.Second)

externalissuer/external_issuer_test.go
160:    time.Sleep(20 * time.Second)

opaqueports/opaque_ports_test.go
95:     time.Sleep(20 * time.Second)

multicluster/target-statefulset/target_statefulset_test.go
67:     time.Sleep(30 * time.Second)

```

It is worth pointing out, only `skip_ports`, `opaque_ports` and `target_statefulset_test` use `time.Sleep()` to "warm-up" pods.

I focused on `opaqueports` and `skip_ports` first. Locally, it took 30.745s and 51.532s respectively to run.

```
ok      github.com/linkerd/linkerd2/test/integration/opaqueports        30.745s
Test script: [policy] Params: []
Test script: [skipports] Params: []
ok      github.com/linkerd/linkerd2/test/integration/skipports  51.532s
```

After changing the logic to use `RetryFor`:

```
ok      github.com/linkerd/linkerd2/test/integration/opaqueports        21.089s
Test script: [policy] Params: []
Test script: [skipports] Params: []
ok      github.com/linkerd/linkerd2/test/integration/skipports  31.494s
```

-20s for `skip_ports` and -9s for `opaqueports` (although I haven't checked for consistency with many subsequent runs).

Thoughts on going ahead with this change? Seems a micro optimisation at this point but I suppose it wouldn't hurt to cut down the times?

**Comment by olix0r** [comment]
This seems like a good change to me! I wonder if there's any way to flag `time.Sleep` (as a lint) so that we have to explicitly document why we are using it.

**Comment by kleimkuhler** [comment]
Yep replacing the usage of `time.Sleep()` where we can is a good change!
