### ISSUE TITLE
Optionally configure linkerd-cni DaemonSet with privileged securityContext

### ISSUE THREAD

**Issue by ron1** [linkerd/linkerd2#7391]
### What is the issue?
linkerd-cni DaemonSet Pods have status CrashLoopBackOff

### How can it be reproduced?
Install linkerd-cni via linkerd client into the Kubernetes environment described below

### Logs, error output, etc
linkerd-cni Pod logs report:
```
/host/opt/cni/bin is non-writeable, failure
Removing linkerd-cni artifacts.
Removing linkerd-cni config: /host/etc/cni/net.d/10-calico.conflist
/linkerd/install-cni.sh: 69: /linkerd/install-cni.sh: cannot create /host/etc/cni/net.d/10-calico.conflist: Permission denied
```

#### `linkerd check` output

```text
your output here ...
```

### Environment

- Kubernetes Version: 1.21.5+rke2r1
- Cluster Environment: (GKE, AKS, kops, ...) Rancher RKE2 w/Calico CNI
- Host OS: CentOS 7.9 w/selinux enforcing
- Linkerd version: 2.11.1

### Possible solution
Modify linkerd-cni DaemonSet to include property securityContext.privileged: true. Maybe this could be made configurable in linkerd-cni Helm Chart and command-line installer.

Note that the calico-node DaemonSet in this environment is also configured with securityContext.privileged: true.

**Comment by olix0r** [comment]
@ron1 have you confirmed that this setting resolves your problem? if so, are you willing to submit a PR to make the helm chart configurable in this way? :)

**Comment by ron1** [comment]
Yes, this setting resolved my problem.
