### ISSUE TITLE
Switching to externalSecret from existing internal secret fails helm release

### ISSUE THREAD

**Issue by jcogilvie** [linkerd/linkerd2#7394]
### What is the issue?
We're trying to follow this:
https://linkerd.io/2.11/tasks/automatically-rotating-webhook-tls-credentials/#issuing-certificates-and-writing-them-to-secrets

We're using helm to install.  the problem is, when we set `externalSecrets` to true in the various fields that require it, the new pods never become healthy.  helm fails to deploy because the pods don't come alive because the secrets no longer exist, because it just deleted them... even if the new cert-manager config is already deployed.

That is:  in our current state, secrets exist and are managed by linkerd+helm.  in our desired state, the secrets are managed by cert-manager.  but in order to go from current to desired, we must first remove the secrets that linkerd has created... helm does this, and then the deployment fails because the new pods can't come up because the secrets are gone.  But cert-manager can't create new secrets in place with the same names because they already exist.

I think this is a kind of circular dependency issue.

### How can it be reproduced?
Deploy linkerd using helm with externalSecrets=false.  Enable externalSecrets=true and redeploy.  Note that helm removes the existing secrets.  There is no room in the process for us to add the secrets by another mechanism, since the existing ones are helm-managed, and required for operation.  

### Logs, error output, etc

Helm release fails due to missing secret `linkerd-policy-validator-k8s-tls`

### Environment

- Kubernetes Version: 1.21
- Cluster Environment: AWS EKS
- Host OS:
- Linkerd version: 2.10.2

### Possible solution
Allow configuration of the secret names that are expected.  Then, I can do this:

1.  deploy with internal secrets; default secrets are created.
2.  create new go-forward secrets with different names
3.  enable external secrets and change names to point to (2)
4.  deployment deletes secrets from (1), and starts to look for (2) instead, and new pods start successfully

Alternately, create and document some way of handing over secret control to cert-manager so that helm does not try to delete the secrets during the deployment that sets `externalSecrets` to true.  As-is, cert-manager will try to reuse existing secrets if we deploy the `Certificate` that references the secret, but then the secret is destroyed by helm.  Maybe just a separate flag that says not to delete the secret if it exists?  Or a doc step to manually remove the "managed by helm" labels on the default secrets?

**Comment by olix0r** [comment]
If I'm reading this correctly, it sounds like this is only a problem when starting with a cluster that does not use cert-manager and upgrading it to use cert-manager. Is this correct? I.e., if you install the control plane initially using cert-manager, everything works as expected?

**Comment by jcogilvie** [comment]
I am upgrading to certs managed by cert-manager, yes.  So I can confirm that it is indeed a problem for this case.  

I can neither confirm nor deny how it works in the other case, but your logic seems reasonable.
