### ISSUE TITLE
Set and standardize pod ownership and destination labels

### ISSUE THREAD

**Issue by siggy** [linkerd/linkerd2#741]
# Background

Telemetry label information comes from several disparate sources. The goal of this ticket is to identify, complete, and standardize the set of labels used by our telemetry system.

# Current State

Pod telemetry labels are derived at 3 different points in a pod's lifecycle, all via disparate data sources:
1. Inject time via Kubernetes yaml
2. Destination lookup via Kubernetes/Conduit labels
3. Prometheus collection

More information on the current state may be found at:
https://github.com/runconduit/conduit/blob/e1e1b6b599f99ce05221c4680e9ed890eda3fa2e/doc/proxy-metrics.md#labels

## Inject time via Kubernetes yaml

At `conduit inject` time, the controller examines the Kubernetes object being injected into, and sets a `conduit.io/proxy-*` label on the pod. A couple examples:
- `conduit.io/proxy-deployment: vote-bot`
- `conduit.io/proxy-k8s-job: vote-job`

At Prometheus collection time, these labels are converted to pod source information:

Kubernetes label:
```yaml
labels:
  conduit.io/proxy-deployment: vote-bot
```

Prometheus label:
```
request_total{
  deployment="vote-bot",
}
```

## Destination lookup via Kubernetes/Conduit labels

Destination labels are derived from injected source labels, at destination lookup time.

In #731, we modified the Destination service to convert `conduit.io/proxy-deployment` (and similar) Kubernetes labels to `deployment`-style destination labels, to send to the proxy, enabling metrics on destination information.

```
destination lookup from proxy ->
  "conduit.io/proxy-deployment: foo" ->

    destination service sends response to proxy->
      "deployment: foo" ->

        conduit-proxy receives response from destination service ->
          "dst_deployment: foo" ->

            prometheus collection
```

### Source labels derived at Prometheus collection time

Full description of labels derived at Prometheus collection time are at:
https://github.com/runconduit/conduit/blob/e1e1b6b599f99ce05221c4680e9ed890eda3fa2e/doc/proxy-metrics.md#prometheus-collector-labels

# Current Issues

1. ReplicaSet information is not possible. This information is not known at inject time, not retrieved at Destination lookup time, and not available at Prometheus collection time.
2. The code paths for injected labels are very different from labels retrieved via destination lookup. Injected labels are derived by looking at yaml at `conduit inject` time, the proxy has no knowledge of them, and are then read and modified by Prometheus at collection time. Destination labels are derived at Destination lookup time, the proxy exposes them through its metrics endpoint, and Prometheus collects them unmodified.

# Proposal

The [kube-state-metrics](https://github.com/kubernetes/kube-state-metrics) project exists to provide Kubernetes state information to Prometheus. Conduit can join proxy metrics with `kube-state-metrics` to provide telemetry information equivalent to what the telemetry pipeline provides today.

A simple example demonstrating this approach (some labels omitted for clarity):

### `kube-state-metrics`

```
kube_pod_owner{
  namespace="emojivoto",
  pod="web-7f84fbc5f4-l5vx7"
  owner_kind="ReplicaSet",
  owner_name="web-7f84fbc5f4",
}
```

### `proxy-metrics`

```
request_total{
  namespace="emojivoto",
  pod="web-7f84fbc5f4-l5vx7",
  direction="inbound",
}
```

### Joined metrics

```
request_total_ex{
  namespace="emojivoto",
  pod="web-7f84fbc5f4-l5vx7",
  direction="inbound",

  owner_kind="ReplicaSet",
  owner_name="web-7f84fbc5f4",
}
```

Some advantates of integrating with `kube-state-metrics`:

- Conduit is already doing much of the work that `kube-state-metrics` was specifically designed for.
- Joining between these two data sets would ensure our data was normalized, allowing more flexible query patterns.
- Adding new Kubernetes objects becomes easier, as we get them for free from `kube-state-metrics`. Currently in Conduit, plumbing through a new object type (ReplicaSet, etc) requires changes to all components of the Telemetry pipeline.

Some concerns around this approach:

- Kubernetes API state at collection time will not always match API state at proxy request time. By deferring the join of Kubernetes API state and proxy requests until collection time, it's possible some proxy request counters will not match against anything currently in the Kubernetes API. This may be particularly problematic if the proxy is failing due to being out of sync with Kubernetes service discovery information. The counters directly exposed by the proxy will have less information, and may require special processing in the pipeline to determine the endpoints they are trying to reach.
- Normalization of Prometheus data means more complex join queries are required to get the same information. This may be particularly problematic when performing adhoc queries. This can be somewhat alleviated by performing the joins in Recording Rules, and storing denormalized metrics.

As an example `kube-state-metrics` integration, #958 demonstrates the following:
- Identifies source and destination labels for ReplicaSet and Deployment and encodes them via Recording Rules
- Adds a ReplicaSet Grafana dashboard

More details about `kube-state-metrics` in the [kube-state-metrics Documentation](https://github.com/kubernetes/kube-state-metrics/tree/master/Documentation)

Here is a complex Recording Rule, based on #958, demonstrating adding ReplicaSet and Deployment information:

```yaml
# copy pod/namespace/owner_kind/owner_name labels to dst_* equivalents for easier matching in subsequent recording rules
- record: kube_pod_owner_ex
  expr: |
    label_replace(
      label_replace(
        label_replace(
          label_replace(
            kube_pod_owner,
            "dst_pod", "$1", "pod", "(.*)"
          ),
          "dst_namespace", "$1", "namespace", "(.*)"
        ),
        "dst_owner_kind", "$1", "owner_kind", "(.*)"
      ),
      "dst_owner_name", "$1", "owner_name", "(.*)"
    )

# temporary metric to introduce dst_owner_kind, dst_owner_name, and dst_deployment labels to request_total
- record: request_total_tmp
  expr: |
    # if this dst_owner_kind = "ReplicaSet", we can infer dst_deployment
    label_replace(
      # only match on direction = "outbound" as we're concerned with dst_* labels
      request_total{direction="outbound"}
      # join request_total (from the proxy) with kube_pod_owner_ex (from kube-state-metrics), match on dst_namespace and dst_pod labels
      # add dst_owner_kind and dst_owner_name labels to request_total_tmp
      * on(dst_namespace, dst_pod) group_left(dst_owner_kind, dst_owner_name)
      kube_pod_owner_ex{dst_owner_kind="ReplicaSet"},
      # perform a regex on the ReplicaSet name to infer dst_deployment
      "dst_deployment", "$1", "dst_owner_name", "(.*)-.*"
    )
    # dst_owner_kind != "ReplicaSet", do not set dst_deployment
    or on (dst_namespace, dst_pod)(
      request_total{direction="outbound"}
      * on(dst_namespace, dst_pod) group_left(dst_owner_kind, dst_owner_name)
      kube_pod_owner_ex
    )
    # catch-all for other metrics (direction = "inbound")
    or request_total{direction="inbound"}

# introduce owner_kind, owner_name, and deployment labels to request_total
- record: request_total_ex
  expr: |
    label_replace(
      request_total_tmp
      * on(namespace, pod) group_left(owner_kind, owner_name)
      kube_pod_owner{owner_kind="ReplicaSet"},
      "deployment", "$1", "owner_name", "(.*)-.*"
    )
    or on (namespace, pod)(
      request_total_tmp
      * on(namespace, pod) group_left(owner_kind, owner_name)
      kube_pod_owner
    )
```

---

# Alternative approaches

## Self-identifying endpoint in proxy-api, augment Destination service

- Add a new endpoint to the proxy-api / controller, allowing `conduit-proxy` to retrieve self-identifying information, to be added to its `/metrics` endpoint. This would make the metrics exported via the proxy more self-contained, no longer requiring Prometheus to have knowledge of and modify `conduit.io/proxy-` Kubernetes labels.
- Augment the existing destination endpoint to derive pod ownership information from the Kubernetes API, rather than from `conduit.io/proxy-` labels. This would provide more complete ownership information, from a Pod to a ReplicaSet to a Deployment.

Self-identifying information would be very similar to destination information, basically a proxy requesting destination information about itself:

```proto
service PodInfo {
  rpc Get(common.TcpAddress) returns (PodLabels) {}
}

message PodLabels {
  map<string, string> pod_labels = 1;
}
```

## Prometheus collection changes

It's possible that all source information could be set at Prometheus collection time. Today, Prometheus makes things like `__meta_kubernetes_namespace` and `__meta_kubernetes_pod_name` information available, via this config:

```yaml
kubernetes_sd_configs:
- role: pod
```

We could consider modifying Prometheus to make additional Kubernetes properties available. More details:
https://prometheus.io/docs/prometheus/latest/configuration/configuration/#pod

## CONDUIT_PROMETHEUS_LABELS

We can revive #624, use `conduit inject` to set source labels via  `CONDUIT_PROMETHEUS_LABELS` environment variable, and the proxy may report information about itself via `/metrics`. This would make source labels more consistent with destination labels, and avoid requiring Prometheus to understand and modify source labels at collection time. This approach is limited by information available at inject time, specifically ReplicaSet.

## Downward API

Kubernetes Downward API provides some information at startup time, but it's a subset of what we need (ReplicaSet not available):
https://kubernetes.io/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/#capabilities-of-the-downward-api

# Misc

This ticket is a follow up from a change in the Destination service where ownership information is derived from the `conduit.io/proxy-*` kubernetes labels injected by the controller:
https://github.com/runconduit/conduit/pull/731#discussion_r180835499

**Comment by olix0r** [comment]
@siggy Is this still the most up-to-date plan we have?

**Comment by siggy** [comment]
@olix0r The `Current State` section of this issue is still valid. We should revisit the `Proposal` as there may be a better way to gather self-identifying pod information, via kube-state-metrics, mentioned here: https://github.com/runconduit/conduit/issues/426#issuecomment-368501827

**Comment by brancz** [comment]
The biggest plus of the de-normalized approach is that you do not have breaking time-series, as if you were to change the labels at runtime ("Self-identifying endpoint in proxy-api, augment Destination service") then Prometheus views them as entirely different and you will end up seeing separate lines on a graph even though the data came from the same target.

Beyond that it allows you to do changes to queries after the fact, and people can still view their historical metrics.

I would keep things done at inject time to a minimum, as it's hard to undo after objects have been applied against a cluster and changes are done to the inject logic (same in the other direction, what used to be compatible is no longer backward compatible).

My take on these situations is, guide a user through these metrics by using meaningful dashboards, including drill down and up on all dimensions, so users don't feel restricted to what they can do. That way you can ship dashboards with arbitrarily complex queries and recording rules as you need. This approach actually works really well with the container metrics from cAdvisor which are normalized in the same fashion, as in that we at collection time only have namespace + pod available as labels.
