### ISSUE TITLE
`linkerd check --pre`: change container runtime check to warning

### ISSUE THREAD

**Issue by kleimkuhler** [linkerd/linkerd2#7457]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What problem are you trying to solve?

When `linkerd check --pre` is run on the docker container runtime, the check is emitted as an error resulting in failure:

```bash
$ linkerd check --pre
...
× proxy-init container runs as root user if docker container runtime is used
...

Status check results are ×
```

Unlike other `--pre` checks, there isn't really anything the user can do to fix this. We are using this to communicate to the user that _when_ they install Linkerd, they should pass the ` --set proxyInit.runAsRoot=true` flag.

### How should the problem be solved?

I think this should change to `warning: true` in the check. This would result in `linkerd check --pre` still passing but still passing on the warning to the user

```bash
$ linkerd check --pre
...
‼ proxy-init container runs as root user if docker container runtime is used
    There are nodes using the docker container runtime and proxy-init container must run as root user.
        Try installing linkerd via --set proxyInit.runAsRoot=true
    see https://linkerd.io/2/checks/#l5d-proxy-init-run-as-root for hints

Status check results are √
```

### Any alternatives you've considered?

We could keep this as is, but it feels like it's worth the discussion.

**Comment by olix0r** [comment]
sgtm

**Comment by kleimkuhler** [comment]
Alternatively, it may make sense to make this a `linkerd install` error rather than communicating it to the user via error/warning as part of `linkerd check --pre`.

That way, a user cannot miss passing the flag when needed, and we'll still have it as part of the config check post `linkerd install`.
