### ISSUE TITLE
Linkerd does not show http custom methods on top feature

### ISSUE THREAD

**Issue by majidghs** [linkerd/linkerd2#7461]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### What is the issue?

My application uses HTTP custom methods. The issue with linkerd is that when I try to use the top feature to listen to a traffic stream, every custom method shows as GET method.
Is there any way to fix this?

### How can it be reproduced?

You can reproduce it by creating a web server that uses HTTP custom methods.

### Logs, error output, etc

`curl 'http://<URL>/apiv1/'   -X 'PATCH'`

`linkerd viz top deploy`
```
(press a/LeftArrowKey to scroll left, d/RightArrowKey to scroll right)

Source                           Destination                                        Method      Path                Count    Best   Worst    Last  Success Rate

192.168.1.90                     dolphin-backend-f4554cf9c-6dgz7                    GET         /apiv1/                 1   203ms   203ms   203ms       100.00%
```

### output of `linkerd check -o short`

```
Linkerd core checks
===================


Status check results are √

Linkerd extensions checks
=========================


Status check results are √
```

### Environment

- Kubernetes version: 1.21
- Cluster environment: Rancher RKE2
- Host OS: Ubuntu20.04.2
- Linkerd version: stable-2.11.1

**Comment by Pothulapati** [comment]
Hey, 

Thanks for raising the issue. Seems to a valid feature request. But, I think this can be separated into the following two requests:

- `PATCH` which seems to be [a official request method in HTTP,](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/PATCH) does not seem to be recognized by default by Linkerd (like other request methods) from the following top output where I tried requests with all HTTP methods.

```
Source      Destination  Method      Path   Count    Best   Worst    Last  Success Rate
10.244.0.1  poddd        GET         /          4   602µs   716µs   602µs       100.00%
10.244.0.1  poddd        PUT         /          1   537µs   537µs   537µs       100.00%
10.244.0.1  poddd        POST        /          1   537µs   537µs   537µs       100.00%
10.244.0.1  poddd        OPTIONS     /          1   936µs   936µs   936µs       100.00%
10.244.0.1  poddd        TRACE       /          1     1ms     1ms     1ms       100.00%
10.244.0.1  poddd        DELETE      /          1   399µs   399µs   399µs       100.00%
```
- Custom method http requests are marked as `GET` by default.

Working on fixing both the above issues currently!

**Comment by majidghs** [comment]
> Hey,
> 
> Thanks for raising the issue. Seems to a valid feature request. But, I think this can be separated into the following two requests:
> 
> * `PATCH` which seems to be [a official request method in HTTP,](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/PATCH) does not seem to be recognized by default by Linkerd (like other request methods) from the following top output where I tried requests with all HTTP methods.
> 
> ```
> Source      Destination  Method      Path   Count    Best   Worst    Last  Success Rate
> 10.244.0.1  poddd        GET         /          4   602µs   716µs   602µs       100.00%
> 10.244.0.1  poddd        PUT         /          1   537µs   537µs   537µs       100.00%
> 10.244.0.1  poddd        POST        /          1   537µs   537µs   537µs       100.00%
> 10.244.0.1  poddd        OPTIONS     /          1   936µs   936µs   936µs       100.00%
> 10.244.0.1  poddd        TRACE       /          1     1ms     1ms     1ms       100.00%
> 10.244.0.1  poddd        DELETE      /          1   399µs   399µs   399µs       100.00%
> ```
> 
> * Custom method http requests are marked as `GET` by default.
> 
> Working on fixing both the above issues currently!

Glad to hear this.
