### ISSUE TITLE
Introducing the class E range in the cluster Network

### ISSUE THREAD

**Issue by venkyvikram** [linkerd/linkerd2#7482]
### What problem are you trying to solve?

As part of the setup, we use class E ranges for the cluster secondary CIDR's - pod and secondary. Currently the values.yaml support the ranges for  Class A, B and C private ranges which includes - 10.0.0.0/8,100.64.0.0/10,172.16.0.0/12,192.168.0.0/16 these ranges
I want to request for the addition of Class E range 240.0.0.0/4

Since this is not part of the initial generation, i need to append these ranges everytime by updating the yaml file, once it generates through the linkerd CLI.

### How should the problem be solved?

I hope the changes need to be made here to accomodate the new range. 
https://github.com/linkerd/linkerd2/blob/main/charts/linkerd-control-plane/values.yaml#L13

### Any alternatives you've considered?

As of now, i am using atlernative  yaml tooling to update the pod and service CIDR per cluster during the linkerd installation.

### How would users interact with this feature?

Recently it's becoming common in enterprises to use class E ranges for the clusters CIDR within the network space of the cluster.
It would be helpful for the teams/users when they use linkerd setup with class E ranges, and they don't need to manipulate using certain set of tools to update these CIDR's during run time. 

### Would you like to work on this feature?

yes

**Comment by kleimkuhler** [comment]
@venkyvikram You can configure the default cluster networks at install time with `linkerd install --set clusterNetworks='...'`. Let me know if you have any more questions!

**Comment by olix0r** [comment]
@venkyvikram As @kleimkuhler, you can set environment-specific overrides via the CLI, or maintain a Helm-style `values.yaml` file with overrides specific to your environment. The defaults include private networks used by major cloud providers. We're probably unlikely to update the defaults to include other IP ranges unless we find that this is applicable to a broad set of users.

**Comment by venkyvikram** [comment]
Hi @kleimkuhler & @olix0r  - Thanks for the update. Sure, i am currently overriding as part of the installation through CLI, eventually, the yaml gets updated with the IP ranges required by the cluster network. 
And since i thought, we can update these as part of defaults, except windows systems, these IP ranges can be used internally within the network.
https://cloud.google.com/vpc/docs/vpc#valid-ranges
But i also agree, we can take this as per the need arises in future. Thanks again for taking your time for responding. 
Wish you both great year ahead.
