### ISSUE TITLE
Linkerd does not let set default container

### ISSUE THREAD

**Issue by hamidaria70** [linkerd/linkerd2#7497]
### What is the issue?

Linkerd changes the default container to linkerd-proxy when the side-car is injected into deployment for any `kubectl` command and its subcommands.

### How can it be reproduced?

Install the deployment below:

```bash
cat <<EOF | kubectl apply -f -
apiVersion: apps/v1
kind: Deployment
metadata:
 name: counter
 labels:
   app: counter
spec:
  selector:
    matchLabels:
      app: counter
  replicas: 1
  template:
    metadata:
      labels:
        app: counter
    spec:
      containers:
      - name: counter
        image: busybox
        args: [/bin/sh, -c,
                'i=0; while true; do echo "$i: $(date)"; i=$((i+1)); sleep 1; done']
EOF
```
The result will be something like `deployment.apps/counter created`.

Checking the pods `kubectl get pods` :

```bash
NAME                                                READY   STATUS        RESTARTS   AGE
counter-6f94c74886-7wp6k                          1/1     Running       0          15s
```

Check the logs of the pod by `kubectl logs -f <counter-*>` and the logs should be:

```bash
.
.
.
131: Sat Dec 18 12:55:57 UTC 2021
132: Sat Dec 18 12:55:58 UTC 2021
133: Sat Dec 18 12:55:59 UTC 2021
134: Sat Dec 18 12:56:00 UTC 2021
135: Sat Dec 18 12:56:01 UTC 2021
.
.
.
```

Now inject the linked side-car:

```bash
kubectl get deployment counter -o yaml | linked inject -f | kubectl apply -f -
```

results are `deployment "counter" injected` and `deployment.apps/counter configured`.

Checking the pods and side-car:

```bash
NAME                                                READY   STATUS        RESTARTS   AGE
counter-5d88475f5c-gmhgq               2/2        Running             0               15s
```

### Logs, error output, etc

Now, check the counter pod logs:

```bash
kubectl logs -f counter-5d88475f5c-gmhgq
```

And the result is:

```bash
error: a container name must be specified for pod counter-5d88475f5c-gmhgq, choose one of: [linkerd-proxy counter] or one of the init containers: [linkerd-init]
```

But I need run the `kubectl logs` and see logs of `counter` container by default...not the `linkerd-proxy`.

### output of `linkerd check -o short`

Linkerd core checks
===================

Status check results are √

Linkerd extensions checks
=========================

Status check results are √

Status check results are √

### Environment

Kubernetes version: 1.21
Cluster environment: Rancher RKE2
Host OS: Ubuntu20.04.2
Linkerd version: stable-2.11.1

**Comment by mateiidavid** [comment]
@hamidaria70 you can still get the logs, using your example:

```
# kubectl logs -f <pod> <container>
:; kubectl logs -f counter-5d88475f5c-gmhgq counter
```

When you have more than one container you need to specify its name when you want the pod's logs.

**Comment by hamidaria70** [comment]
Thank you @mateiidavid 
But if you `inject` the linked-proxy with the `--manual` option and then check the deployment of `counter`, you'll see that in `.spec.container` the order of containers will be changed and the proxy is the first container...default container in Kubernetes is the first container which is defined under `.spec.container`.

**Comment by hamidaria70** [comment]
> @hamidaria70 you can still get the logs, using your example:
> 
> ```
> # kubectl logs -f <pod> <container>
> :; kubectl logs -f counter-5d88475f5c-gmhgq counter
> ```
> 
> When you have more than one container you need to specify its name when you want the pod's logs. I'm a bit confused by what you mean with seeing the `counter` container's logs by default and not the proxy; the following error line is from Kubernetes, not the proxy.
> 
> ```
> error: a container name must be specified for pod counter-5d88475f5c-gmhgq, choose one of: [linkerd-proxy counter] or one of the init containers: [linkerd-init]
> ```

**Comment by hamidaria70** [comment]
> @hamidaria70 you can still get the logs, using your example:
> 
> ```
> # kubectl logs -f <pod> <container>
> :; kubectl logs -f counter-5d88475f5c-gmhgq counter
> ```
> 
> When you have more than one container you need to specify its name when you want the pod's logs. I'm a bit confused by what you mean with seeing the `counter` container's logs by default and not the proxy; the following error line is from Kubernetes, not the proxy.
> 
> ```
> error: a container name must be specified for pod counter-5d88475f5c-gmhgq, choose one of: [linkerd-proxy counter] or one of the init containers: [linkerd-init]
> ```

Thank you @mateiidavid
But if you inject the linked-proxy with the --manual option and then check the deployment of counter, you'll see that in .spec.container the order of containers will be changed and the proxy is the first container...default container in Kubernetes is the first container which is defined under .spec.container.

**Comment by kleimkuhler** [comment]
@hamidaria70 I previously explained the reason for this [here](https://github.com/linkerd/linkerd2/issues/7122#issuecomment-947195722).

> In order to fix container startup ordering issues, we use the fact that containers are created in the order that they appear in the manifest. When linkerd-proxy is first, we can block the application container from becoming ready before the proxy. This allows the application container to startup and immediately start sending/receiving requests.

If you have other applications that depend on container ordering that you cannot change, the feature can be disabled with the `config.linkerd.io/proxy-await: "disabled"` annotation. Keep in mind this may introduce startup issues.

We don't currently have docs that explain this clearly so we'll get that updated.

**Comment by hamidaria70** [comment]
> @hamidaria70 I previously explained the reason for this [here](https://github.com/linkerd/linkerd2/issues/7122#issuecomment-947195722).
> 
> > In order to fix container startup ordering issues, we use the fact that containers are created in the order that they appear in the manifest. When linkerd-proxy is first, we can block the application container from becoming ready before the proxy. This allows the application container to startup and immediately start sending/receiving requests.
> 
> If you have other applications that depend on container ordering that you cannot change, the feature can be disabled with the `config.linkerd.io/proxy-await: "disabled"` annotation. Keep in mind this may introduce startup issues.
> 
> We don't currently have docs that explain this clearly so we'll get that updated.

Thanks

Yeah, I searched about that and checked issue #7122 and [linkerd-await](https://github.com/linkerd/linkerd-await) but I couldn't add `config.linkerd.io/proxy-await: "disabled"` annotation.

I'll be glad if my problem gets solved.

**Comment by adleong** [comment]
Hi @hamidaria70.  I'm going to close this issue because I don't think there's much we can do to reasonably do here.  If at all possible, I would recommend avoiding relying on Kubernetes' notion of a default container and instead specifying the container that you want explicitly whenever you can.
