### ISSUE TITLE
Using external grafana/prometheus, all `linkerd viz check` shows green, but no metrics are shows

### ISSUE THREAD

**Issue by presidenten** [linkerd/linkerd2#7510]
## Summary

Im trying to use the rancher cluster monitoring prometheus and grafana with linkerd-viz. Everything starts, both `linkerd check` and `linkerd viz check` shows green, but linkerd-viz shows no metrics, and the grafana link from linkerd-viz do not work.

## Environment

- Kubernetes 1.21.1 running in Kind 0.11.1
- Rancher 2.6.2
- Rancher-monitoring 100.0.0+up16.6.0
- Linkerd 2.11.1
- Linkerd-viz 2.11.1
- Docker Desktop for mac 4.2.0, docker engine 20.10.10, setup with 6 cpu and 16 gb ram

## How to recreate

I have setup a repo here: https://github.com/presidenten/rancher-in-kind

Prerequisites:
- kind
- linkerd cli
- helm 3
- kubectl

Clone the repo and run `./rkind.sh create` to get everything setup. It takes a few min for everything to get up and running.

Rancher is available at https://localhost:4443 with password admin/admin.
Grafana password is also set to admin/admin.

Then check linkerd-viz at http://localhost:30000. 
Note that no metrics are available, and the grafana link dont work, but all is green in `linkerd check` and `linkerd viz check` during setup.

#### Changes to Rancher monitoring
- Extra dependencies (loki + promtail): https://github.com/presidenten/rancher-in-kind/blob/master/charts/monitoring/Chart.yaml#L8-L16
- Value overrides: https://github.com/presidenten/rancher-in-kind/blob/master/charts/monitoring/values.yaml

#### Changes to linkerd-viz
- Helm value overrides: https://github.com/presidenten/rancher-in-kind/blob/master/charts/linkerd-viz/values.yaml
- Extra nodeport service: https://github.com/presidenten/rancher-in-kind/blob/master/charts/linkerd-viz/templates/services/linkerd-viz-nodeport.yaml

The rest of the settings are default

**Comment by adleong** [comment]
Hi @presidenten!

I tested out your repo and as far as I can tell, the external prometheus has not been configured with the necessary scrape config to scrape metrics from the Linkerd proxies.  See https://linkerd.io/2.10/tasks/external-prometheus/#prometheus-scrape-configuration for details.

**Comment by presidenten** [comment]
@adleong 
Thanks! I will have a look tomorrow, as my schedule is full today.

Any ideas on the config needed to get the grafana links to work as well?

**Comment by adleong** [comment]
See https://github.com/linkerd/linkerd2/issues/7429

**Comment by presidenten** [comment]
So I managed to get it working by installing linkerd-viz version 30.0.3-edge and using `externalUrl` and extracing extra adding scrape config jobs from default linkerd-viz rollout (with prometheus) by checking configmap `kubectl -n linkerd-viz  get configmap prometheus-config -o yaml`

**Comment by presidenten** [comment]
@adleong Thanks for you input! ...and sorry for being so slow to verify :-)
