### ISSUE TITLE
Set Nominal Resource Requests on Proxy

### ISSUE THREAD

**Issue by steve-gray** [linkerd/linkerd2#7537]
### What problem are you trying to solve?

The Kubernetes horizontal pod autoscaler will not consider a workload for scaling if any container of the pods within the deployment/replicaset or other unit of work does not have a resource request set. Workloads where any container has a resource request missing will show as "Unknown" status and not scale.

### How should the problem be solved?

Always set a nominal resource request for the injected proxy that reflects the lowest possible, unless a user has expressly requested a different/explicit request. The proxy always inherently consumes some resources, so it should be possible to set a nominal soft-request anyway, and probably best practices to do so anyway.

### Any alternatives you've considered?

- Manually editing every deployment to manually add pointlessly small annotations. However a lot of users will be surprised when HPA's suddenly silently break if they have them when adding Linkerd, as the default proxy settings will cause the above behaviour and it's not something that leaps off the screen as the causative element.

- Convince a Kubernetes SIG to change their ways. 

### How would users interact with this feature?

Winds willing, they wouldn't. If they want to customise this request, they can do it via the existing workload annotations.

### Would you like to work on this feature?

maybe

**Comment by olix0r** [comment]
Unfortunately, this tends to cause support issues when people try to use Linkerd on small (local) clusters. When linkerd is installed with e.g. `linkerd install --ha`, however, proxies are configured with requests/limits defaults. Furthermore, you can use a values.yaml file at install-time to set defaults for a cluster. In general, if you're using something like an HPA, I'd recommend using the --ha mode, which is supposed to be configured with production defaults (unlike the basic install).

**Comment by steve-gray** [comment]
I am running in HA mode @olix0r. I suspect the request defaults aren't working/broken.

1. Screenshot of Linkerd Controlplane Status
![image](https://user-images.githubusercontent.com/14563775/147506662-96d1f7b6-e15c-44d8-90b5-447ce80ea057.png)

2. HPA for Workload showing Invalid Status
![image](https://user-images.githubusercontent.com/14563775/147506705-b52b1d88-8217-4396-be58-97231d9518ca.png)

3. Linkerd Version
```
steve@rover ~ % linkerd version
Client version: stable-2.11.1
Server version: stable-2.11.1
```

4. The workload does definitely have the pod injected
![image](https://user-images.githubusercontent.com/14563775/147506810-cafe22b9-7167-43c5-9b00-97e39281b390.png)

**Comment by steve-gray** [comment]
If I manually add this to my helm charts for deployments though, the HPA springs back to life:

```
  config.linkerd.io/proxy-cpu-request: "0.5"    # Required for HPA
```

**Comment by steve-gray** [comment]
I'm not quite sure how I've ended up __without__ these annotations, but the rest of the controlplane in HA state - but I'll re-apply/set cluster level defaults and see how I go. Sorry for burning your time @olix0r.

**Comment by olix0r** [comment]
@steve-gray no worries :)

For what it's worth, I just tested a fresh `--ha` install and I see

```
:; linkerd install --ha | k apply -f -
...
:; curl -L https://run.linkerd.io/emojivoto.yml |linkerd inject - | k apply -f -
...
:; k describe -n emojivoto po -l app=emoji-svc 
...
Containers:
  linkerd-proxy:
    Container ID:   containerd://7c9661df8d253b1ff36cecc15c6ec63acfa573389d6455e290660e25e7dd4b3c
    Image:          cr.l5d.io/linkerd/proxy:stable-2.11.1
    Image ID:       cr.l5d.io/linkerd/proxy@sha256:91b53d4b39e4c058e5fc63b72dd7ab6fe7f7051869ec5251dc9c0d8287b2771f
    Ports:          4143/TCP, 4191/TCP
    Host Ports:     0/TCP, 0/TCP
    State:          Running
      Started:      Mon, 27 Dec 2021 21:06:51 +0000
    Ready:          True
    Restart Count:  0
    Limits:
      memory:  250Mi
    Requests:
      cpu:      100m
      memory:   20Mi
```

Let us know if you see any problems or if you have any suggestions for documentation improvements.
