### ISSUE TITLE
rt_route is not in linkerd tap!!

### ISSUE THREAD

**Issue by hamidaria70** [linkerd/linkerd2#7557]
### What is the issue?

I have a web application and I wanted to test `retry` when I call an API, using curl, from pods `retry` works and I will get `rt_route` at the end of the `linkerd tap` command bud when calling the same API from the browser or host terminal, it doesn't show up and retry will not work. (ingress Nginx controller also meshed).

### How can it be reproduced?

Create a service profile and set `pathRegex: /.*` to route everything, Make a simple python app with an API for example `version` then run it on a pod and inject it and also create a service for it...from another pod call the API...Check the tap and you will see the `rt_route`. if you scale up the pod to 3 or 4 pods, you will notice that the retry works.

Create an ingress with an example domain, add it into `/etc/hosts` and again call the API from your host...if you check the tap there is no `rt_route` and retry won't work.

### Logs, error output, etc

Service profile:
```bash
apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  creationTimestamp: "2022-01-03T06:12:53Z"
  generation: 14
  name: app-backend.default.svc.cluster.local
  namespace: default
  resourceVersion: "12747568"
  uid: 35f9af28-1efe-41f3-b50e-110add86f897
spec:
  routes:
  - condition:
      method: GET
      pathRegex: /.*
    isRetryable: true
    name: GET /apiv1
```

Calling API from a meshed pod:

```bash
user@app2-backend-6b74c8d75f-2kpt2:/app2$ curl app-backend:8080/apiv1/version
{
    "version":"0.176.0a109"
}
```

Tap command:

```bash
linkerd viz tap deploy/app-backend -o wide | grep req
```

Tap Output:

```bash
req id=1:37 proxy=in  src=10.42.0.217:40266 dst=10.42.0.206:8080 tls=true :method=GET :authority=app-backend:8080 :path=/apiv1/version src_res=deploy/app2-backend src_ns=default dst_res=deploy/app-backend dst_ns=default rt_route=GET /apiv1/
```

Calling API from my host:

```bash
curl app-test.com/apiv1/version

{
    "version":"0.176.0a109"
}
```

Tap Output:

```bash
req id=1:92 proxy=in  src=192.168.1.90:43884 dst=10.42.0.206:8080 tls=no_tls_from_remote :method=GET :authority=app-test.com :path=/apiv1/version dst_res=deploy/app-backend dst_ns=default
```

### output of `linkerd check -o short`

```test
Linkerd core checks
===================


Status check results are √

Linkerd extensions checks
=========================


Status check results are √


Status check results are √
```

### Environment

Kubernetes version: 1.21
Cluster environment: Rancher RKE2
Host OS: Ubuntu20.04.2
Linkerd version: stable-2.11.1

**Comment by adleong** [comment]
Hi @hamidaria70!

It looks like nginx is forwarding requests to your backend using the original authority (app-test.com) instead of setting the proper headers for your backend.  Can you tell me more about how nginx is configured?  We recommend using the "service-upstream" feature as described here: https://linkerd.io/2.10/tasks/using-ingress/#nginx

**Comment by hamidaria70** [comment]
> Hi @hamidaria70!
> 
> It looks like nginx is forwarding requests to your backend using the original authority (app-test.com) instead of setting the proper headers for your backend. Can you tell me more about how nginx is configured? We recommend using the "service-upstream" feature as described here: https://linkerd.io/2.10/tasks/using-ingress/#nginx

Yes, I checked it ...that's right...

This is the ingress config:
```bash
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    meta.helm.sh/release-name: app
    meta.helm.sh/release-namespace: default
    nginx.ingress.kubernetes.io/cors-allow-headers: Content-Type, Authorization, Cache-Control
    nginx.ingress.kubernetes.io/cors-allow-methods: GET, POST, OPTIONS, PUT, LIST,
      OBTAIN, PATCH, SUBSCRIBE, UNSUBSCRIBE, CREATE, DELETE, UPDATE, METADATA, DEFINE,
      FINALIZE, RELATE, ADD, REMOVE, KICK, HIDE, SHOW, APPEND, HEAD, ASSIGN, MENTIONED,
      MOVE, SEARCH, SENT, UNASSIGN, UNRELATE, SCHEDULE, ACCOMPLISH, APPROVE, EXTEND,
      DENY, GRANT, ATTACH, LOGOUT, REVOKE, CHECK, CLAIM, REGISTER, INVITE, JOIN, CHANGE,
      RESET, BIND, ASK, INVALIDATE, EDIT, REQUEST, SEND, REPLY, SEE, MENTION, PREFLIGHT,
      DECLINE, COMPLETE, RESCHEDULE, JOIN, LEAVE
    nginx.ingress.kubernetes.io/cors-allow-origin: http://app-test.com
    nginx.ingress.kubernetes.io/cors-expose-headers: X-Pagination-Take, X-Pagination-Skip,
      X-Identity, X-New-JWT-Token, X-Pagination-Count
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 5m
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/service-upstream: "true"
    nginx.ingress.kubernetes.io/websocket-services: jaguar-websocket
    nginx.org/websocket-services: jaguar-websocket
  creationTimestamp: "2021-12-28T09:35:31Z"
  generation: 1
  labels:
    app.kubernetes.io/managed-by: Helm
  name: maestro-backend-ingress
  namespace: default
  resourceVersion: "12910985"
  uid: 8ba6aa21-6b9a-4996-8e4a-61ece8962da7
spec:
  rules:
  - host: app-test.com
    http:
      paths:
      - backend:
          service:
            name: app-backend
            port:
              number: 8080
        path: /app(/|$)(.*)
        pathType: ImplementationSpecific
```

**Comment by adleong** [comment]
Hi @hamidaria70, I've just tried this using ingress-nginx and I am getting the rt_route data as expected.

Here are the steps I used to test:

1. install Linkerd 2.11.1, the Viz extension, and ingress-nginx from the Helm chart (https://kubernetes.github.io/ingress-nginx/deploy/)
2. `k annotate ns/ingress-nginx linkerd.io/inject=enabled` and restart ingress controller deployment
2. install emojivoto `linkerd inject https://run.linkerd.io/emojivoto.yml | k apply -f -`
3. delete vote-bot deployment so that we won't get any in-cluster traffic
3. add simple service profile:
```
apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  name: web-svc.emojivoto.svc.cluster.local
  namespace: emojivoto
spec:
  routes:
  - name: 'all'
    condition:
      pathRegex: '/.*'
```
5. use curl to send requests to ingress-nginx-controller external-ip
6. 
```console
> linkerd viz tap -o wide -n emojivoto deploy/web
req id=4:0 proxy=in  src=XXX dst=XXX tls=true :method=GET :authority=XXX :path=/ src_res=deploy/ingress-nginx-controller src_ns=ingress-nginx dst_res=deploy/web dst_ns=emojivoto rt_route=all
```

In particular, using `linkerd viz tap -o json` or [linkerd tapshark](https://github.com/adleong/tapshark/) shows that the request header `l5d-dst-canonical: web-svc.emojivoto.svc.cluster.local:80` has been set.  When nginx sends traffic to the web-svc service, it's linkerd-proxy sets that header on the outbound side which tells the backend's linkerd-proxy to use that name when looking up service profiles.

I'm not sure why you're seeing different behavior, but I'd recommend looking at these steps and seeing if your setup differs in any significant way.  I'd especially ensure that your nginx ingress controller is injected with `linkerd.io/inject: enabled` and not `linkerd.io/inject: ingress`.

**Comment by hamidaria70** [comment]
> Hi @hamidaria70, I've just tried this using ingress-nginx and I am getting the rt_route data as expected.
> 
> Here are the steps I used to test:
> 
> 1. install Linkerd 2.11.1, the Viz extension, and ingress-nginx from the Helm chart (https://kubernetes.github.io/ingress-nginx/deploy/)
> 2. `k annotate ns/ingress-nginx linkerd.io/inject=enabled` and restart ingress controller deployment
> 3. install emojivoto `linkerd inject https://run.linkerd.io/emojivoto.yml | k apply -f -`
> 4. delete vote-bot deployment so that we won't get any in-cluster traffic
> 5. add simple service profile:
> 
> ```
> apiVersion: linkerd.io/v1alpha2
> kind: ServiceProfile
> metadata:
>   name: web-svc.emojivoto.svc.cluster.local
>   namespace: emojivoto
> spec:
>   routes:
>   - name: 'all'
>     condition:
>       pathRegex: '/.*'
> ```
> 
> 5. use curl to send requests to ingress-nginx-controller external-ip
> 
> ```
> > linkerd viz tap -o wide -n emojivoto deploy/web
> req id=4:0 proxy=in  src=XXX dst=XXX tls=true :method=GET :authority=XXX :path=/ src_res=deploy/ingress-nginx-controller src_ns=ingress-nginx dst_res=deploy/web dst_ns=emojivoto rt_route=all
> ```
> 
> In particular, using `linkerd viz tap -o json` or [linkerd tapshark](https://github.com/adleong/tapshark/) shows that the request header `l5d-dst-canonical: web-svc.emojivoto.svc.cluster.local:80` has been set. When nginx sends traffic to the web-svc service, it's linkerd-proxy sets that header on the outbound side which tells the backend's linkerd-proxy to use that name when looking up service profiles.
> 
> I'm not sure why you're seeing different behavior, but I'd recommend looking at these steps and seeing if your setup differs in any significant way. I'd especially ensure that your nginx ingress controller is injected with `linkerd.io/inject: enabled` and not `linkerd.io/inject: ingress`.

I tried your solution but the problem is still the same!!!

**Comment by adleong** [comment]
See also https://github.com/linkerd/linkerd2/issues/7363 which seems like it might be related.

**Comment by adleong** [comment]
@hamidaria70 do you have any additional information that could help us reproduce this issue?  otherwise, without a reproduction, there's not much we can do to help.
