### ISSUE TITLE
Optionally disable versioncheck in heartbeat CronJob and linkerd cli

### ISSUE THREAD

**Issue by ron1** [linkerd/linkerd2#7588]
### What problem are you trying to solve?

The linkerd versioncheck url is not accessible for some linkerd deployments. This breaks the heartbeat CronJob and triggers warnings in the linkerd cli check commands.

### How should the problem be solved?

Consider introducing an environment variable and potentially a cli flag to disable the linkerd versioncheck functionality.

### Any alternatives you've considered?

An unsatisfactory work-around is to disable the heartbeat functionality entirely.

**Comment by cpretzer** [comment]
@ron1 the way to disable the heartbeat is to use the `--disable-heartbeat` flag for the CLI or the `disableHeartbeat` value for helm. 

The endpoint at https://versioncheck.linkerd.io/version.json is used to collect anonymous details about the Linkerd deployment and disabling the request to that URL will cause the heartbeat controller to collect the details without sending them. 

[Here](https://github.com/linkerd/linkerd2/blob/edge-22.1.1/controller/cmd/heartbeat/main.go#L59) is the code for the heartbeat.

**Comment by ron1** [comment]
So the only purpose of the heartbeat CronJob is to send telemetry data? If that is true, then I will go ahead and close this issue.
