### ISSUE TITLE
policy test is flakey

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#7590]
The cni-calico-deep test failed on an unrelated change with:

```
Test script: [policy] Params: [--cni]
Error: TestPolicy - timed-out checking stats (3m0s)
--- FAIL: TestPolicy (497.00s)
    --- FAIL: TestPolicy/linkerd_viz_stat_srv_-n_linkerd-stat-authz-test (180.72s)
        policy_test.go:146: Unexpected success rate for [emoji-grpc], got [-]
```

It looks like the test ran for up to 3 minutes before failing.

Can this test be decoupled from viz/prometheus perhaps?

**Comment by mateiidavid** [comment]
Ugh, cni-calico-deep will doom me. I think the policy test is focused more on checking the output of the viz stat command (`linkerd viz authz`). 

We can definitely decouple it from viz and prometheus. My suggestion would be to:

* Keep this test as is, make it part of the viz suite in the upcoming ci change; it'll only be run once and it'll still check our viz commands work properly.
* Create a new test for the deep suite that will check the diagnostics of the pod and make assertions based on response codes (i.e unauthorized, success and so on). 

We could also turn the current policy integration test into a unit test and then have a new integration test that will check the diagnostics of the pod. Either way, I think the best way to go about it would be to use `linkerd diagnostics` in the test if we want to remove the dependency on viz.

**Comment by olix0r** [comment]
I've see this failure _a lot_ recently (most recently in the _external-prometheus-deep_ test)l
