### ISSUE TITLE
No "linkerd-proxy" containers found 

### ISSUE THREAD

**Issue by choupijiang** [linkerd/linkerd2#7592]
### What is the issue?

linkerd check is Ok:

```
...
Status check results are √
```
But when checked after  i inject linkerd proxy to my deploy . 
It is stucked at `waiting for check to complete ` and after looong  time, it failed with 
```
× data plane proxies are ready
    No "linkerd-proxy" containers found in the "emojivoto" namespace
    see https://linkerd.io/checks/#l5d-data-plane-ready for hints
``` 

### How can it be reproduced?

just use demo https://linkerd.io/2.9/getting-started/

### Logs, error output, etc

```text 
linkerd-data-plane
------------------
√ data plane namespace exists
× data plane proxies are ready
    No "linkerd-proxy" containers found in the "emojivoto" namespace
    see https://linkerd.io/checks/#l5d-data-plane-ready for hints

Status check results are ×


```

### output of `linkerd check -o short`

```text
...
linkerd-grafana
---------------
√ grafana add-on service account exists
√ grafana add-on config map exists
√ grafana pod is running

Status check results are √


```

### Environment

Env: 
K8s: Server Version: v1.14.1, CLient version V1.22.0 

linkerd version: 
> linkerd version 
Client version: stable-2.9.1
Server version: stable-2.9.1

**Comment by Pothulapati** [comment]
Hey @choupijiang, This is weird, as the control-plane checks seem to pass. Can you post logs for the `proxy-injector` and also events in the namespace?

You seem to run a bit older version of Linkerd i.e `stable-2.9.1`. Any particular reason for this? Just that it makes a bit harder for us to debug and help.

**Comment by choupijiang** [comment]
@Pothulapati I used it 2.9.x because my k8s version is lower. 

when i upgrade linkerd from 2.9.1 to 2.9.4 , it reproduce the same issue . 

but when i inject first it report
```shell 
> kubectl get -n grpc-lb deploy -o yaml  | linkerd inject -  | kubectl apply -f -

deployment "greeter-client-no-lb" injected
deployment "greeter-server" injected

Warning: resource deployments/greeter-client-no-lb is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
deployment.extensions/greeter-client-no-lb configured
Warning: resource deployments/greeter-server is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
deployment.extensions/greeter-server configured
```
the above warn i  also find when I used the demo .

but when inject it again it will ok 
```shell
kubectl get -n grpc-lb deploy -o yaml  | linkerd inject -  | kubectl apply -f -

deployment "greeter-client-no-lb" injected
deployment "greeter-server" injected

Warning: resource deployments/greeter-client-no-lb is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
deployment.extensions/greeter-client-no-lb configured
Warning: resource deployments/greeter-server is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
deployment.extensions/greeter-server configured
```

**Comment by Pothulapati** [comment]
@choupijiang That seems weird but it seems to be a warning from `kubectl` and not `linkerd`

> Warning: resource deployments/greeter-client-no-lb is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.

Could be that you have k8s compatibility issues btw the cluster version i.e `1.14.1` and client `1.22` as there is a huge version gap?

Thanks,
Tarun

**Comment by choupijiang** [comment]
@Pothulapati thx for your kindly remind. 
But I dont think its is a problem,  even warning reported. Because others all works. 
I still degrade my kubectl to v1.14.1 ,but not works either. 
```text
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}

```

**Comment by Pothulapati** [comment]
Hey @choupijiang, Deployments are not injected. Its the pods that are injected. This is done to make the injector logic simpler as pods are the final application resources irrespective of the grouping layer i.e deployments, statefulsets, etc. And as per the events of the deployment, The pods of the deployment should be injected as you would expect. Can you confirm that?

**Comment by choupijiang** [comment]
@Pothulapati  
no text matched return when 
` kubectl describe pod greeter-server-6f49554494-b8qk7 -n grpc-lb | grep -i linkerd `.

there are no linkerd inject message found in pod description.

**Comment by Pothulapati** [comment]
@choupijiang Can you check if there is information in the injector logs on whats happening? 🤔

**Comment by choupijiang** [comment]
@Pothulapati I found the pod not restart and the describe logs as follow
```text
> kubectl describe pod  greeter-server-6f49554494-b8qk7 -n grpc-lb 
Name:               greeter-server-6f49554494-b8qk7
Namespace:          grpc-lb
Priority:           0
PriorityClassName:  <none>
Node:               host-XXX
Start Time:         Tue, 18 Jan 2022 10:32:50 +0800
Labels:             app=greeter-server
                    pod-template-hash=6f49554494
Annotations:        kubernetes.io/psp: default
                    seccomp.security.alpha.kubernetes.io/pod: docker/default
Status:             Running
IP:                 XXXXXX
Controlled By:      ReplicaSet/greeter-server-6f49554494
Containers:
  greeter-server:
    Container ID:   docker://0a367f198036fed262c5fc10310b6a1fdafd49d04abb5cc38b0eaee97d68abe2
    Image:         XXXXX/greeter_server:latest
    Image ID:      XXXXX@sha256:1b390967fc549486769a76260e97ca624a86850acc6dc79687f5e47f54f50909
    Port:           8000/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Tue, 18 Jan 2022 10:32:52 +0800
    Ready:          True
    Restart Count:  0
    Environment:
      GRPC_VERBOSITY:  debug
      MY_POD_IP:        (v1:status.podIP)
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-XXX (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  default-token-XXX:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-XXX
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:          <none>

```
Plz tell me if you know how to check , thx.

**Comment by Pothulapati** [comment]
Hey @choupijiang 

To get the proxy injector logs, You should be able to do 

```
kubectl -n linkerd logs deploy/linkerd-proxy-injector proxy-injector
```

**Comment by stardustman** [comment]
same problem，linkerd version 2.11

**Comment by mateiidavid** [comment]
@xgenvn and @stardustman do either of you use a private GKE cluster? Have you followed the docs on how to open up the firewall so the pods can talk to the apiserver? It's important for the injector otherwise the admission requests won't come through:

https://linkerd.io/2.11/reference/cluster-configuration/

**Comment by xgenvn** [comment]
@mateiidavid thank you for the response. I'm using GKE cluster, I will check the reference.

**Comment by xgenvn** [comment]
@mateiidavid After updating the firewall, everything is working as expected. Thank you again for the reference.
