### ISSUE TITLE
Using Ambassador as MultiCluster Gateway does not work

### ISSUE THREAD

**Issue by RicardoNalesAmato** [linkerd/linkerd2#7612]
### What is the issue?

Using Ambassador as the multicluster gateway as described [here](https://linkerd.io/2.11/tasks/installing-multicluster/#leverage-ambassador) does not currently work. Ambassador constantly returns 400 the error specifically being `envoy missing_host_header`.

### How can it be reproduced?

Following the steps in https://linkerd.io/2.11/tasks/installing-multicluster/#leverage-ambassador with :

- Ambassador 1.14.2
- Linkerd 2.11.1

### Logs, error output, etc

service-mirror constantly returns:
```
time="2022-01-14T20:54:39Z" level=warning msg="Gateway returned unexpected status 400. Marking as unhealthy" probe-key=west
```
```
linkerd-multicluster
--------------------
√ Link CRD exists
√ Link resources are valid
	* sandbox-eks
√ remote cluster access credentials are valid
	* sandbox-eks
√ clusters share trust anchors
	* sandbox-eks
√ service mirror controller has required permissions
	* sandbox-eks
√ service mirror controllers are running
	* sandbox-eks
× all gateway mirrors are healthy
        liveness checks failed for sandbox-eks
    see https://linkerd.io/2.11/checks/#l5d-multicluster-gateways-endpoints for hints
√ multicluster extension proxies are healthy
√ multicluster extension proxies are up-to-date
√ multicluster extension proxies and cli versions match

Status check results are ×
```

### output of `linkerd check -o short`

```
Linkerd core checks
===================

kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ control plane pods are ready
√ cluster networks contains all node podCIDRs

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist

linkerd-identity
----------------
√ certificate config is valid
√ trust anchors are using supported crypto algorithm
√ trust anchors are within their validity period
√ trust anchors are valid for at least 60 days
√ issuer cert is using supported crypto algorithm
√ issuer cert is within its validity period
‼ issuer cert is valid for at least 60 days
    issuer certificate will expire on 2022-02-08T18:33:19Z
    see https://linkerd.io/2.11/checks/#l5d-identity-issuer-cert-not-expiring-soon for hints
√ issuer cert is issued by the trust anchor

linkerd-webhooks-and-apisvc-tls
-------------------------------
√ proxy-injector webhook has valid cert
√ proxy-injector cert is valid for at least 60 days
√ sp-validator webhook has valid cert
√ sp-validator cert is valid for at least 60 days
√ policy-validator webhook has valid cert
√ policy-validator cert is valid for at least 60 days

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ can retrieve the control plane version
√ control plane is up-to-date
√ control plane and cli versions match

linkerd-control-plane-proxy
---------------------------
√ control plane proxies are healthy
√ control plane proxies are up-to-date
√ control plane proxies and cli versions match

Status check results are √
```

### Environment

- Kubernetes version: 1.20
- Cluster Environment: EKS
- Host OS: Amazon Linux
- Linkerd Version: 2.11.1

### Possible solution

I had added the GatewayAddress [in this PR](https://github.com/linkerd/linkerd2/pull/7611) which fixes the issue though I am not sure if the approach is correct or if `localGatewayName` should still be used and would love to hear what you think. There are some other issues mentioned in https://github.com/linkerd/linkerd2/pull/7611 that prevent me from testing this entirely.

### Would you like to work on fixing this bug?

yes

**Comment by adleong** [comment]
I followed these instructions to install ambassador: https://buoyant.io/2021/05/24/emissary-and-linkerd-the-best-of-both-worlds/

followed by these instructions for linking the clusters https://linkerd.io/2.11/tasks/installing-multicluster/#leverage-ambassador

I was able to make cross-cluster requests successfully and was not able to reproduce the errors listed above.

**Comment by RicardoNalesAmato** [comment]
> I followed these instructions to install ambassador: https://buoyant.io/2021/05/24/emissary-and-linkerd-the-best-of-both-worlds/
> 
> followed by these instructions for linking the clusters https://linkerd.io/2.11/tasks/installing-multicluster/#leverage-ambassador
> 
> I was able to make cross-cluster requests successfully and was not able to reproduce the errors listed above.

I'll give it another try now that the other issue is fixed. One question though is this line in the tutorial correct:
```
 --require-identity-on-inbound-ports 4183
 ```
 Or should it be:
 ```
  --require-identity-on-inbound-ports 4143
  ```

**Comment by adleong** [comment]
Yes, I think you're right.  It should be set to the gateway port which is 4143.
