### ISSUE TITLE
Flag RUSTSEC issues in the proxy repo

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#7632]
90f7391de53f31818f8adabb35536d1521dcf5e9 added a new action to this repo that flags security issues in the controller's Rust code. We should replicate this behavior in the proxy repo.

The major obstacle to this, though, is that the proxy repo does not permit issues to be created. The audit action does not, as far as I know, support creating issues in a different repo; so we'll either have to fix that or change the proxy repo to accept issues.

If we change the proxy repo to accept issues, we'll want to automatically move issues from `linkerd2-proxy` repo into the `linkerd2` repo. We may be able to use https://github.com/lando/transfer-issue-action for this.

**Comment by olix0r** [comment]
We should do the same for the `linkerd-await` repo

**Comment by Pothulapati** [comment]
@olix0r Instead of allowing to accept issues across repos, and then having a action that transfers issues, How about we include checking out all the rust repos under `linkerd` org, and running it in the same `linkerd2` cronjob, and thus raising issues here?

This seems possible, as[ we can specify what repo to checkout](https://github.com/actions/checkout#usage) in the checkout action 🤔

**Comment by olix0r** [comment]
@Pothulapati Yeah that sounds great. We could probably just add a matrix to the existing workflow. Ideally, we'd want to set the `area/proxy` label when appropriate, too.

**Comment by Pothulapati** [comment]
The cronjob [seems to work as expected across repos](https://github.com/linkerd/linkerd2/actions/runs/1720912233), Now I have some questions:

- So, The action somehow seems to know and not create duplicate issues in the same repo. Does it also not raise duplicate issues even when we have the same vulnerability across repos? 🤔 
- Find a way to label issues based on the repo that the vulnerability was found in.

**Comment by olix0r** [comment]
I just noticed that this action failed last night with:

> `Error: You have exceeded a secondary rate limit. Please wait a few minutes before you try again.`

I manually reran the action to get it to proceed. I _believe_ these API responses include a `Retry-After` header that can be used to gracefully backoff in this case, but presumably the audit-check action doesn't honor this.

This got me looking at the audit-check repo... It looks like the action hasn't been touched since May 2020 (nearly 2 years). There are currently 26 open PRs. Most are simple dependency updates. HALF of them are marked as security-related https://github.com/actions-rs/audit-check/pulls?q=is%3Apr+is%3Aopen+label%3Asecurity.

While very convenient, this project doesn't appear to be actively maintained.

**Comment by olix0r** [comment]
I've created a new action that we could potentially use for this https://github.com/olix0r/rustsecbot -- it needs more testing/polish, but this may be an option to replace audit-check.
