### ISSUE TITLE
linkerd-viz chart cannot be installed (without significant and incorrect actions)

### ISSUE THREAD

**Issue by mikebell90** [linkerd/linkerd2#7650]
### What is the issue?

the chart will not work. The details are below. Basically on a clean cluster I installed the main linkerd helm chart, worked fine, linkerd-viz will not install

### How can it be reproduced?

1. kind create cluster
2. Follow the instructions to generate anchor
3. helm install linkerd2 \
  --set-file identityTrustAnchorsPEM=ca.crt \
  --set-file identity.issuer.tls.crtPEM=issuer.crt \
  --set-file identity.issuer.tls.keyPEM=issuer.key \
  --set identity.issuer.crtExpiry=$exp \
  linkerd/linkerd2
4. helm install linkerd-viz -n linkerd-viz --create-namespace linkerd/linkerd-viz

FAILS with Error: INSTALLATION FAILED: namespaces "linkerd-viz" already exists

### Logs, error output, etc

https://gist.github.com/mikebell90/28f0f47a4c16f5d5c4644e72be57079e

### output of `linkerd check -o short`

Not relevant

### Environment

kubernetes 1.21
kind
helm 3.7.0
on a mac

### Possible solution

There's a hack described, but it's terrible helm form

```
 kubectl create ns linkerd-viz
 kubectl annotate ns linkerd-viz app.kubernetes.io/managed-by=Helm
 kubectl label ns linkerd-viz app.kubernetes.io/managed-by=Helm
 kubectl annotate ns linkerd-viz meta.helm.sh/release-namespace=linkerd-viz
 kubectl label ns linkerd-viz meta.helm.sh/release-namespace=linkerd-viz
 kubectl annotate ns linkerd-viz meta.helm.sh/release-name=linkerd-viz
 helm install linkerd-viz -n linkerd-viz linkerd/linkerd-viz

```

Note the manual label/annotation hack and the helm install without --create-namespace

### Would you like to work on fixing this bug?

maybe

**Comment by mikebell90** [comment]
After a lovely slack discussion with the very helpful @mateiidavid we agreed that handling ones own namespace in helm is a bad idea. I believe edge already has a chart without this.

The following will work

```
kubectl create ns linkerd-viz
helm install linkerd-viz -n linkerd-viz linkerd/linkerd-viz  --set "installNamespace=false"
```

I'm guessing @mateiidavid this will be required for all linkerd namespace in the future, and that folks will have to (ugh) reinstall, because otherwise I believe they have to edit the helm secrets to get helm to relinquish control of the ns object

**Comment by mikebell90** [comment]
Feel free to close this @mateiidavid . I'm only leaving it open for now in case we come up with some other fruitful thoughts.

**Comment by mateiidavid** [comment]
Cool, glad I could help, and glad we got this sorted @mikebell90. I'm going to go ahead and close the issue.

If you want this re-opened, you can just mention me in a comment.
