### ISSUE TITLE
test: Unsafe usage of `env::set_var`

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#7651]
In the proxy's test initialization code, we use [`std::env::set_var`](https://github.com/linkerd/linkerd2-proxy/blob/af72a6960d965117f30872b9979579ee8576d347/linkerd/tracing/src/test.rs#L10-L20) to configure a log format:

```rust
pub fn trace_subscriber(default: impl ToString) -> (Dispatch, Handle) {
    let log_level = env::var("LINKERD2_PROXY_LOG")
        .or_else(|_| env::var("RUST_LOG"))
        .unwrap_or_else(|_| default.to_string());
    let log_format = env::var("LINKERD2_PROXY_LOG_FORMAT").unwrap_or_else(|_| "PLAIN".to_string());
    env::set_var("LINKERD2_PROXY_LOG_FORMAT", &log_format);
    // This may fail, since the global log compat layer may have been
    // initialized by another test.
    let _ = init_log_compat();
    Settings::for_test(log_level, log_format).build()
}
```

My understanding is that this is unsafe, per https://github.com/rust-lang/rust/issues/90308, because our tests run in multiple threads. It would be great if we could avoid environment mutation in our codebase.

Can we remove this? Do we actually care about JSON formatting in our tests?

Are there [tools](https://blog.trailofbits.com/2021/11/09/write-rust-lints-without-forking-clippy/) we could use to, for instance, make clippy fail on new uses of `set_var`/`remove_var`?

**Comment by hawkw** [comment]
In this case, we can just remove the `set_var` calls. I never understood why they were there to begin with --- I think this is an artifact of back before we were able to use the same logging configuration for the test driver thread and the test proxy?
