### ISSUE TITLE
linkerd cli requires api server access for trivial operations

### ISSUE THREAD

**Issue by mikebell90** [linkerd/linkerd2#7654]
### What is the issue?

Obviously linkerd needs access for things like checks for example. But it should probably lazy initialize its k8s client library because things like

* linkerd inject
* linkerd profile importing of swagger

I dont think actually they need the api server, my guess is the client gets eagerly initialized earlier.

Why is this "bad"? honestly, it's minor tbh, but I can imagine some "off network" automation being blocked by this.

### How can it be reproduced?

disconnect from any kubectl context
pipe something to linkerd inject

### Logs, error output, etc

Cannot connect to Kubernetes: error configuring Kubernetes API client: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable

### output of `linkerd check -o short`

not relevant but probably ghastly ;)

### Environment

not terribly relevant, but a mac running the linkerd 2.11 cli

### Possible solution

Lazy initialize the k8s client?

**Comment by olix0r** [comment]
@mikebell90 Yeah, I agree it would be good to remove unnecessary client initialization. In the meantime, the `--ignore-cluster` flag should work in many cases to skip this loading. I know that it was missing in a few places recently fixed by https://github.com/linkerd/linkerd2/pull/7564, though, so ymmv.

**Comment by adleong** [comment]
Both `linkerd inject` and `linkerd profile` load configuration from the installed linkerd configmap.  Both commands support a `--ignore-cluster` flag which allows them to operate using default configuration rather than loading it from the cluster.

E.g. try

```
KUBECONFIG="invalid" linkerd inject --ignore-cluster https://run.linkerd.io/emojivoto.yml
```

**Comment by mikebell90** [comment]
interesting. That makes sense, and I'll close the ticket. But it seems like that could be clearer?
