### ISSUE TITLE
Please update docs fot "Gitops"

### ISSUE THREAD

**Issue by exocode** [linkerd/linkerd2#7665]
### What problem are you trying to solve?

I followed that tutorial "Using GitOps with Linkerd with Argo CD" (https://linkerd.hacker-linner.com/2.9/tasks/gitops/)

I struggled the point where `identityTrustAnchorsPEM` are not deployed correctly. 

I had errors like `LINKERD2_PROXY_IDENTITY_TRUST_ANCHORS must be set` or `linkerd-identity-trust-roots empty`

### How should the problem be solved?

Simply updating the docs by adapting to 2.11.x

remove `global.` from `global.identityTrustAnchorsPEM` beginning at that point on in the docs: https://linkerd.hacker-linner.com/2.9/tasks/gitops/#deploy-linkerd

### Any alternatives you've considered?

there are no alternatives :-) 

### How would users interact with this feature?

Users now can follow the tutorial without errors. 

### Would you like to work on this feature?

maybe

**Comment by alpeb** [comment]
Thanks for the report @exocode. There's an upgrade to that doc scheduled for the 2.12 release here:
https://github.com/linkerd/website/pull/1244/files#diff-f00f9317897d66fd46e8b66d3c8efcdb55c8be7f6423f76da16526fdac0bb047
I'll back-port the changes to version 2.11 anyways :+1:

**Comment by alpeb** [comment]
The gitops docs update should be live now (#1287)
