### ISSUE TITLE
Use the OpenTelemetry protocol in the proxy

### ISSUE THREAD

**Issue by seblaz** [linkerd/linkerd2#7672]
### What problem are you trying to solve?

Use the OpenTelemetry protocol, but the proxy doesn't support it yet

### How should the problem be solved?

Make the proxy implement the OpenTelemetry protocol

### Any alternatives you've considered?

Using the OpenCensus protocol for now

### Would you like to work on this feature?

no

**Comment by seblaz** [comment]
This would be a continuation of #6159 with the proxy implementation, is this something that would be worked in?

**Comment by olix0r** [comment]
@seblaz We're not opposed to this in general. But it's probably not a high priority issue for us unless there's a functional difference or problem this solves.

**Comment by seblaz** [comment]
I think that without the proxy implementation if the open telemetry protocol is used then the two differences I can find are:
 - The proxy spans are not included
 - The tag `linkerd.io/workload-ns=<namespace>` and the service name are not added to the traces
Is that a functional difference?

**Comment by olix0r** [comment]
> ### What problem are you trying to solve?
> Use the OpenTelemetry protocol, but the proxy doesn't support it yet

> if the open telemetry protocol is used then the two differences I can find are:
>
> * The proxy spans are not included
> * The tag linkerd.io/workload-ns=<namespace> and the service name are not added to the traces

Are you suggesting that Linkerd traces sent over the opencensus protocol are incompatible with an application's traces sent over the opentelemtry protocol?

I'm under the impression that collectors can accept traces over either protocol and UIs like jaeger should be able to render these spans together.

**Comment by seblaz** [comment]
Yes, you are right. I was under the impression that they were incompatible but the collectors handle the traces correctly, thanks!
