### ISSUE TITLE
Additional validation for CLI stat command inputs

### ISSUE THREAD

**Issue by klingerf** [linkerd/linkerd2#776]
The new stat command introduces some new flags that are highly configurable. We should validate that any given configuration of flags is valid before attempting to retrieve stats. This issue contains a list of invalid configurations that I've come across that aren't properly handled.

1. The `--from*` and `--to*` flags are mutually exclusive, and the CLI should return an error if both are specified as part of the same command. In its current implementation, the CLI silently discards the `--to*` flags, and uses the `--from*` flags instead.

---

2. The `--to-namespace` and `--from-namespace` flags aren't valid for "namespace" resource types. For instance, we should consider these commands to be invalid:
```
# this should be written as: conduit stat ns --from ns/default
conduit stat ns --from-namespace default

# this should be written as: conduit stat ns --to ns/default
conduit stat ns --to-namespace default
```

---

3. Similarly, when targeting a namespace with `--from*` or `--to*` flags, one should use `--from-namespace` or `--to-namespace`, instead of using the `--from` and `--to` flags with `--from-resource=namespace` and `--to-resource=namespace`. For instance:
```
# this should be written as: conduit stat deploy --to-namespace default
conduit stat deploy --to default --to-resource namespace

# this is be written as: conduit stat deploy --from-namespace default
conduit stat deploy --from default --from-resource namespace
```

---

For 2 and 3 above, I think it would also be ok if we coerced the request to be the correct format, instead of returning a validation error. But since we don't do any coercion or validation at present, the command completes successfully, but the stats that we return are wrong. I think validation is probably easier to implement, but coercion is perhaps more user friendly.

**Comment by klingerf** [comment]
4. The `--namespace` flag should be supported for "namespace" type resources. By default `conduit stat ns` returns all namespaces. `conduit stat ns -n default` should return only the default namespace, but right now it is ignored.

Compare:

```
$ conduit stat ns
NAME          MESHED   SUCCESS      RPS   LATENCY_P50   LATENCY_P95   LATENCY_P99
conduit          4/4   100.00%   0.5rps           2ms           3ms           3ms
default          0/0         -        -             -             -             -
emojivoto        4/4    92.67%   5.0rps           1ms           5ms           8ms
kube-public      0/0         -        -             -             -             -
kube-system      0/6         -        -             -             -             -
```

To:

```
$ conduit stat ns -n default
NAME          MESHED   SUCCESS      RPS   LATENCY_P50   LATENCY_P95   LATENCY_P99
conduit          4/4   100.00%   0.6rps           2ms           9ms          10ms
default          0/0         -        -             -             -             -
emojivoto        4/4    92.67%   5.0rps           1ms           5ms           7ms
kube-public      0/0         -        -             -             -             -
kube-system      0/6         -        -             -             -             -
```

I'd expect the latter to be equivalent to:

```
$ conduit stat ns default
NAME      MESHED   SUCCESS   RPS   LATENCY_P50   LATENCY_P95   LATENCY_P99
default      0/0         -     -             -             -             -
```

**Comment by hawkw** [comment]
For the cases where we should coerce the requests to be in the proper format, should we also emit a warning?

**Comment by klingerf** [comment]
@hawkw Good question. On reflection I'm not sure it's worth it to coerce any of these -- let's just reject them and make people type the stat commands correctly.

Note that this issue is _slightly_ out of date. The `--from-resource` and `--to-resource` flags are no more. So a few of the validation issues that I mentioned in the description might be moot at this point.
