### ISSUE TITLE
`clusterNetworks` check did not report missing CIDRs

### ISSUE THREAD

**Issue by mateiidavid** [linkerd/linkerd2#7761]
### What is the issue?

It has been reported in our [community chat](https://linkerd.slack.com/archives/C89RTCWJF/p1643729888860299?thread_ts=1643724358.747309&cid=C89RTCWJF) (link may expire) that `linkerd check` did not correctly report a CIDR that wasn't included in the control plane's `clusterNetworks` by default.

Pod CIDR value on Node:

```
spec:
  podCIDR: 10.100.11.0/24
  podCIDRs:
  - 10.100.11.0/2
```

We should check if our assertion logic is sound:

https://github.com/linkerd/linkerd2/blob/f9ba4eb1ead68d6a9fe9daa85ee9b3ce7d617626/pkg/healthcheck/healthcheck.go#L1893-L1902

I think we're covered with unit tests for the check itself, but if we find cases that would be good to test, it might be worth creating some unit tests to guard against this type of stuff in the future.

### How can it be reproduced?

I'd spin up a k3d environment and see if the node CIDRs can be (re)assigned to something not included in the default list. I'd try with the values posted above.

If `linkerd check` does not report an error, we should check why that is.

### Logs, error output, etc

N/A

### output of `linkerd check -o short`

N/A

### Environment

Linkerd version: `stable-2.11.1`

**Comment by isurusiri** [comment]
Hey everyone, I'd like to give this a go if this is still relevant.

**Comment by mateiidavid** [comment]
@isurusiri sure is! :) I think we'd just like to first check where the logic holds up correctly and then try to get some unit tests in to have a bit more confidence in the check. The issue description should set you up nicely (you can check the conversation that started all of this in slack).

Let us know if you have any questions.

**Comment by isurusiri** [comment]
Thanks @mateiidavid   for the heads up. I'll start working on this and keep y'all posted in here.

**Comment by adleong** [comment]
Reading back over the slack conversation, it seems the targeted IP for which discovery was skipped was `198.18.226.92` which is not in the default cluster networks.  However, the user only mentions `10.100.11.0/24` as podCIDRs specified on the nodes.  This means that there's no way for Linkerd to know that `198.18.226.92` is supposed to be part of the cluster network.  

As far as I can tell, there isn't any error in the CIDR checking logic.  Please re-open this issue if this is incorrect.
