### ISSUE TITLE
Linkerd Jaeger image versions don't support arm

### ISSUE THREAD

**Issue by BobyMCbobs** [linkerd/linkerd2#7793]
### What is the issue?

The images provided by `linkerd jaeger install` 
- `docker.io/otel/opentelemetry-collector:0.27.0@sha256:f6ac448b9de543830af942e1691e75fc082c709754bf9ac690e8c216cbb43a25`
- `docker.io/jaegertracing/all-in-one:1.19.2@sha256:f4855ebc1a915ea92782292f5696b22ac61ac834fecaced1004d652b10f5d245`

### How can it be reproduced?

Bring up an arm cluster

Install Linkerd+Jaeger
```
linkerd install | kubectl apply -f -

linkerd jaeger install | kubectl apply -f -
```

### Logs, error output, etc

`standard_init_linux.go:228: exec user process caused: exec format error`

### output of `linkerd check -o short`

```
Linkerd extensions checks
=========================

linkerd-jaeger
--------------
‼ jaeger injector pods are running
    pod "collector-68cfd6b9f7-gp8zc" status is Running
    see https://linkerd.io/2/checks/#l5d-jaeger-pods-running for hints
‼ jaeger extension proxies are healthy
    pod "collector-68cfd6b9f7-gp8zc" status is Running
    see https://linkerd.io/2/checks/#l5d-jaeger-proxy-healthy for hints
‼ jaeger extension proxies are up-to-date
    some proxies are not running the current version:
	* jaeger-5c69f55dc9-d6ckp (edge-22.1.3)
	* jaeger-injector-64f75c9d79-8ctlw (edge-22.1.3)
    see https://linkerd.io/2/checks/#l5d-jaeger-proxy-cp-version for hints
‼ jaeger extension proxies and cli versions match
    collector-68cfd6b9f7-gp8zc running edge-22.1.3 but cli running edge-22.2.1
    see https://linkerd.io/2/checks/#l5d-jaeger-proxy-cli-version for hints

Linkerd extensions checks
=========================

linkerd-viz
-----------
‼ viz extension proxies are up-to-date
    some proxies are not running the current version:
	* metrics-api-68d5cd894c-xgnbx (edge-22.1.3)
	* prometheus-69b97787fc-btvqb (edge-22.1.3)
	* web-67fc66dbb-wm8hs (edge-22.1.3)
    see https://linkerd.io/2/checks/#l5d-viz-proxy-cp-version for hints
‼ viz extension proxies and cli versions match
    metrics-api-68d5cd894c-xgnbx running edge-22.1.3 but cli running edge-22.2.1
    see https://linkerd.io/2/checks/#l5d-viz-proxy-cli-version for hints

Status check results are √
```

### Environment

- Kubernetes version: v1.23.1
- Cluster Environment: Metal (Raspberry Pis)
- Host OS: Talos
- Linkerd version: edge-22.2.1

### Possible solution

Use Jaeger newer versions

### Additional context

The latest images are 
- `docker.io/otel/opentelemetry-collector:0.43.0@sha256:ba3b0346d8b6ec4ec564b78daec0af5ef7fd664ec33ead7bcbb283e3ae32525e`
- `docker.io/jaegertracing/all-in-one:1.31.1@sha256:04d224a9999bbf9583e75d27af335bf7bcd870d2573f37218c9c0b1c9e38f3a0`

however, `collector` has issues on this version with the default configuration 
```
Error: failed to get config: cannot unmarshal the configuration: error reading exporters configuration for "jaeger": 1 error(s) decoding:

* '' has invalid keys: insecure
2022/02/05 04:53:15 collector server run finished with error: failed to get config: cannot unmarshal the configuration: error reading exporters configuration for "jaeger": 1 error(s) decoding:

* '' has invalid keys: insecure
```

**Comment by si-hyeon-ee** [comment]
I am using linkerd on k3s. Upstream supports arm (it has recently been supported), but if you upgrade collector image version, an error occurs in the collector.

In my case, I solved it by executing `kubectl edit -n linkerd-jaeger deloyments.app jaeger` and then deploying to amd node by specifying `kubernetes.io/arch:amd` in node-selector.
