### ISSUE TITLE
Investigate Destination service sending address updates without labels

### ISSUE THREAD

**Issue by siggy** [linkerd/linkerd2#783]
If the Destination service receives an address update, and fails to find an associated pod, it still sends an update message to the Proxy:
https://github.com/runconduit/conduit/blob/e1e1b6b599f99ce05221c4680e9ed890eda3fa2e/controller/destination/listener.go#L81-L86

We should determine if this is advisable behavior, and also confirm whether this can ever actually happen. A first step could be to add a metric counter that increments any time this happens, in addition to logging an error.

source: https://github.com/runconduit/conduit/pull/781#discussion_r182215953

**Comment by klingerf** [comment]
Fwiw, @olix0r ran into this issue this morning, and I think it's a result of the Kubernetes API cache not being populated before serving requests from the proxies. We should fix this issue by completing the fix described in #1013.

**Comment by klingerf** [comment]
I think this was fixed in #1168 but I don't have a great way to verify it unfortunately. I'll leave it open for now, to see if we get any more reports of it.
