### ISSUE TITLE
batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+; use batch/v1 CronJob

### ISSUE THREAD

**Issue by prahlad141992** [linkerd/linkerd2#7852]
### What is the issue?

Recent k8s made changes cronJob apiVersion for new version. Request you to take a look and fix.
Error:
batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+; use batch/v1 CronJob 

### How can it be reproduced?

Run the helm install in k8s version 1.21+ or later version.

### Logs, error output, etc

Release "linkerd2" does not exist. Installing it now.
W0209 00:14:25.802326     428 warnings.go:70] batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+; use batch/v1 CronJob
W0209 00:19:26.804378     428 warnings.go:70] batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+; use batch/v1 CronJob
Error: release linkerd2 failed, and has been uninstalled due to atomic being set: timed out waiting for the condition
##[error]W0209 00:14:16.561306     428 warnings.go:70] batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+; use batch/v1 CronJob
W0209 00:14:25.802326     428 warnings.go:70] batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+; use batch/v1 CronJob
W0209 00:19:26.804378     428 warnings.go:70] batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+; use batch/v1 CronJob
Error: release linkerd2 failed, and has been uninstalled due to atomic being set: timed out waiting for the condition

### output of `linkerd check -o short`

Release "linkerd2" does not exist. Installing it now.
W0209 00:14:25.802326     428 warnings.go:70] batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+; use batch/v1 CronJob
W0209 00:19:26.804378     428 warnings.go:70] batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+; use batch/v1 CronJob
Error: release linkerd2 failed, and has been uninstalled due to atomic being set: timed out waiting for the condition
##[error]W0209 00:14:16.561306     428 warnings.go:70] batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+; use batch/v1 CronJob
W0209 00:14:25.802326     428 warnings.go:70] batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+; use batch/v1 CronJob
W0209 00:19:26.804378     428 warnings.go:70] batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+; use batch/v1 CronJob
Error: release linkerd2 failed, and has been uninstalled due to atomic being set: timed out waiting for the condition

### Environment

 k8s version 1.21

**Comment by olix0r** [comment]
We can't update the api version until Kubernetes v1.21 is our minimum-supported Kubernetes version. In theory, the maintenance window for v1.20 ends on 2022/02/28, so we can consider updating the MSKV in March.
