### ISSUE TITLE
linkerd-cni and calico syncage

### ISSUE THREAD

**Issue by jack1902** [linkerd/linkerd2#7855]
### What problem are you trying to solve?

relates to: https://github.com/linkerd/linkerd2/issues/4789#issuecomment-723714946

Currently, when deploying `linkerd-cni` onto my cluster which has `calico` enabled I use the `wait` flag on linkerd-cni to fix a race condition between calico and linkerd-cni starting up on the node, this works great.

However, if the `calico` pod restarts or the node restarts then an issue arises whereby the `linkerd-cni` snippet within the `CNI` yaml `10-calico.conflist` no longer exists and no automation to fix this exists "out of the box". This then means that any pods that come up on the node aren't aware of linkerd at all 😭 

Slack thread: https://linkerd.slack.com/archives/C89RTCWJF/p1644266941323399

### How should the problem be solved?

A mechanism should exist so that, if `linkerd`' snippets are no longer within the relevant `*.conflist` in question (I'm being selfish on the `calico` front but this is surely a similar issue with azure/aws/other) that the following holds true:

- linkerd-cni and linkerd snippets are injected back into the relevant configuration
- Any pod that comes up has a check carried out to ensure that it has a proxy within its object (similar to: https://github.com/istio/istio/issues/14327#issuecomment-585959879)

Whatever the solution is, I would like it to still work with the lesser privileges of using the `linked-cni` in the first place since I would prefer to lock down my pods as much as possible and the `linkerd-cni` in its current form provides that but has this critical bug (whether linkerd or other plugins are at fault shouldn't matter, the problem exists and would be quicker to fix on the linkerd side)

### Any alternatives you've considered?

1. Abandon `linkerd-cni` approach entirely but this means my pods will need more privileges to run due to the `initContainer` altering the IPTables
2. Use Istio instead (the jump in latency is the real turn off here and linkerd is so much simpler)
3. I've looked at a weird roundabout approach whereby I ensure that the config that is written out by `calico` has `linkerd` in it upfront thereby ensuring that if `calico` restarts that linkerd is never removed. This sounds great on the face of it but makes it difficult to automate since:
    - knowledge of the linkerd `serviceAccount` token must be known upfront but I wouldn't know this until I deployed `linkerd` in the first place.
    - This feels retrospective to deploy `calico` then `linkerd` and then loop back round to `calico` so it has `linkerd` within. I'd prefer to configure things upfront as much as possible.

### How would users interact with this feature?

This feature would become the default behaviour for the `linkerd-cni` to avoid issues that exist today when using the `linkerd-cni` alongside `calico` (potentially other plugins aswell)

### Would you like to work on this feature?

maybe

**Comment by jack1902** [comment]
potentially relates to: https://github.com/linkerd/linkerd2/issues/2219 but that doesn't seem to have had much love in recent months

**Comment by mateiidavid** [comment]
Hey @jack1902 , thanks for bringing this up. It's been on my radar for a while, I just haven't really had the bandwidth to properly look into it. Like you've noted already https://github.com/linkerd/linkerd2/issues/2219 is the original issue that was filed, and there's also https://github.com/linkerd/linkerd2/issues/4049. 

Copied from the latter:

```
A potential solution is to always assume that the CNI plugin is installed in scenarios where there is another plugin to chain with. We can then make the script wait until this other plugin's config is present and chain itself into it. This will introduce another problem. It could be the case that the Linkerd pods start up before our CNI plugin had the chance to install itself. This will break Linkerd as there will be no iptables rules on our pods. One way to fix that is to introduce an Init container that waits until the desired iptables config is present. That should ensure that we achieve some sort of synchronisation between all of these steps and eliminate the racy scenarios.
```

We have added the ability to add an `initContainer` to the cni plugin, so this _could_ be a solution. I'm very eager to fix this, and I know a lot of people would love to finally have an end to the racey behaviour (cc: @electrical since we talked about it on slack a few times). I wouldn't necessarily favour this approach since it'll require `NET_ADMIN` to check for iptables. 

Let's figure out what the best solution would be. I'm interested to see as a CNI user what would be your preferred way of doing this. 

 > I've put maybe on the would i like to work on this purely because I haven't written rust before and I am currently strapped for time, but I can interact with a potential solution to this problem via this issue

Ah, I have great news. Our cni plugin is in Go. It's unlikely we'll need to write any Rust code for this :D

**Comment by ron1** [comment]
As mentioned here: https://github.com/istio/istio/issues/14327#issuecomment-585959879, it appears that Istio solved this same CNI race problem a couple of years ago. Furthermore, Istio CNI users seem to happy with the solution that was implemented. Hopefully, the Istio solution can inspire a comparable solution for linkerd. The current race issues with linkerd-cni are production blockers as far as I am concerned.

**Comment by pdefreitas** [comment]
We've been using linkerd-cni on our AKS cluster and it is noticeable some race conditions (even with the extraInitCointainer in place to test -f .conf files for Azure). This is something I've originally reported on #6105, which initially we thought it was fixed for newer AKS versions, but few months later after multiple node restarts, it's noticeable again, the exact same issue. The only thing that seems to work is restarting the workloads post CNI installation (after noticing the problem). We're not using calico but Azure CNI instead. With this limitation is not feasible to use linkerd-cni in a production system.

**Comment by jack1902** [comment]
Not stale

**Comment by mateiidavid** [comment]
@jack1902 thanks for raising this. Will be closing it for now, I posted a comment in https://github.com/linkerd/linkerd2/issues/8120 explaining the reasoning. For your (and anyone else's) convenience, I've quoted the respective comment below. Hope this is satisfactory, for any concerns, you know where to reach us :) 

> A final update. We're on track to release `stable-2.13.0`. In my previous update, I mentioned that we've introduced two new mechanisms to deal with race conditions for CNI plugins:
> 
> * a file watcher (to ensure linkerd's cni plugin can be installed successfully when other plugins exist in the cluster)
> * a network validator (to ensure iptables has been set-up correctly in a network namespace).
> 
> For now, these two mechanisms should be enough to significantly reduce any race conditions that arise when nodes are rebooted or restarted. While the network validator will not restart pods, it will block any misconfigured pod from running; moving the failure point at a different layer will allow operators or engineers to diagnose issues better and to take manual intervention when required.
> 
> While restarting misconfigured pods through a controller was part of the original scope of this issue, it won't be part of the stable release. A new controller needs a bit more thought and design before being introduced. We'll likely open up a separate issue to discuss the approach and design.
> 
> I will be closing this issue for now. As of `stable-2.13.0` the handling of race conditions will be improved. After we trial out the network validator and get more feedback, we'll figure out where the automation fits in. Hopefully by then the Kubernetes community will have also figured out a better way to bootstrap CNIs before node provisioning.
> 
> Any questions, concerns, or feedback, feel free to open up a new issue or ping me in an existing one. Thanks.
