### ISSUE TITLE
GitHub Container Registry hosted images

### ISSUE THREAD

**Issue by cpressland** [linkerd/linkerd2#7926]
### What problem are you trying to solve?

We're still unable to pull Linkerd images from `cr.l5d.io`, on average the four main images take between 20 minutes and 45 minutes to successfully pull when we provision a new cluster. We don't see this behaviour from other container registries. We have raised support tickets with Microsoft over this as the issue appears to be specific to the use of Azure Firewall, but they have been unwilling to assist us further on troubleshooting this.

Our cluster bootstrap cookbook executes a `linkerd check` immediately after the `linkerd install` command has finished, this retries 10 times waiting 60 seconds between each retry, but usually results in a cookbook failure until the next full retry 60 minutes later.

### How should the problem be solved?

We'd like to see the linkerd2 images hosted somewhere else in addition to `cr.l5d.io`, ideally the GitHub Container Registry as this has been proven for us to be incredibly fast, and is free for Open Source Projects. Given the core linkerd projects already use GitHub Actions, this would be a trivial thing to add as part of the docker build and push process.

### Any alternatives you've considered?

I have pulled the images locally to my laptop with the `--platform=linux/amd64` flag and re-tagged and pushed them to:

* ghcr.io/binkhq/linkerd/proxy:stable-2.11.1
* ghcr.io/binkhq/linkerd/controller:stable-2.11.1
* ghcr.io/binkhq/linkerd/proxy-init:v1.4.0
* ghcr.io/binkhq/linkerd/policy-controller:stable-2.11.1

We've then changed our Kubernetes Cluster bootstrap cookbook to execute `linkerd install` with the `--registry ghcr.io/binkhq/linkerd` arg. This results in a linkerd installation finishing in about 30 seconds instead of ~30 minutes.

If we're breaching any rules by re-hosting these images, please let me know and I'll remove these images and find another solution.

### How would users interact with this feature?

Operators could optionally pass the `--registry ghcr.io/linkerd` arg during cluster installation.

### Would you like to work on this feature?

maybe

**Comment by olix0r** [comment]
The Linkerd container images are already published to ghcr.io/linkerd :) cr.l5d.io is simply a redirect that allows us to move them in the future, should that become necessary. You should be able to change the registry as you suggest.

**Comment by cpressland** [comment]
Thanks @olix0r - how on earth did I miss that! Ha. I’ll give it a test this weekend and set that as the default if that’s the case.

I’ll close this off.
