### ISSUE TITLE
Could not install linkerd-smi by helm after install linkerd using helm

### ISSUE THREAD

**Issue by jingb** [linkerd/linkerd2#7937]
### What is the issue?

Could not install linkerd-smi by helm after install linkerd using helm.
The command I use to install linkerd

### How can it be reproduced?

helm install linkerd2 \
  --set-file identityTrustAnchorsPEM=./stepCertificate/ca.crt \
  --set-file identity.issuer.tls.crtPEM=./stepCertificate/issuer.crt \
  --set-file identity.issuer.tls.keyPEM=./stepCertificate/issuer.key \
  --set policyController.image.name=ghcr.io/olix0r/policy-controller \
  --set policyController.image.version=nativetls.40ab223a \
  --set identity.issuer.crtExpiry=$exp \
  --set proxyInit.runAsRoot=true \
  linkerd/linkerd2

helm install l5d-smi/linkerd-smi --generate-name

### Logs, error output, etc

helm install l5d-smi/linkerd-smi --generate-name
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /root/.kube/config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /root/.kube/config
Error: rendered manifests contain a resource that already exists. Unable to continue with install: CustomResourceDefinition "trafficsplits.split.smi-spec.io" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "linkerd-smi-1645512254": current value is "linkerd2"

### output of `linkerd check -o short`

linkerd check -o short
Linkerd core checks
===================

linkerd-version
---------------
‼ cli is up-to-date
    is running version 22.1.3 but the latest edge version is 22.2.3
    see https://linkerd.io/2/checks/#l5d-version-cli for hints

control-plane-version
---------------------
‼ control plane and cli versions match
    control plane running stable-2.11.1 but cli running edge-22.1.3
    see https://linkerd.io/2/checks/#l5d-version-control for hints

linkerd-control-plane-proxy
---------------------------
‼ control plane proxies and cli versions match
    linkerd-destination-59ccb6d975-p6khf running stable-2.11.1 but cli running edge-22.1.3
    see https://linkerd.io/2/checks/#l5d-cp-proxy-cli-version for hints

Status check results are √

### Environment

kubectl version --short
Client Version: v1.21.0
Server Version: v1.21.0

linkerd version
Client version: edge-22.1.3
Server version: stable-2.11.1

### Possible solution

kubectl delete crd trafficsplits.split.smi-spec.io
and re-execute helm install l5d-smi/linkerd-smi --generate-name

**Comment by alpeb** [comment]
The linkerd chart stopped installing the `trafficsplits.split.smi-spec.io` CRD a few releases ago, but it appears you still have it installed in your server, or it was installed by another project. If you don't have any `TrafficSplit` resources installed in your cluster, you can just delete that CRD and let linkerd-smi install it again. Let me know if that addresses your issue :-)

**Comment by jingb** [comment]
> The linkerd chart stopped installing the `trafficsplits.split.smi-spec.io` CRD a few releases ago, but it appears you still have it installed in your server, or it was installed by another project. If you don't have any `TrafficSplit` resources installed in your cluster, you can just delete that CRD and let linkerd-smi install it again. Let me know if that addresses your issue :-)

ok, thanks
