### ISSUE TITLE
cli: remove `--proxy-version` flag

### ISSUE THREAD

**Issue by mateiidavid** [linkerd/linkerd2#7939]
### What problem are you trying to solve?

The CLI should behave similarily to Helm. Currently, there are two ways to set the proxy version explictly: 

* through `--proxy-version`
* and through the `--set` flag (`--set proxy.image.version`).

This issue is similar to https://github.com/linkerd/linkerd2/issues/7859. Note: the cli flag seems to mess up the overidden values since they get a default value associated to them. For example, we can override all images in the manifest with `linkerdVersionValue`, but the proxy image won't use this by default, since its proxy-version variable is always initialized when using the CLI. 

More information about the problem and the conversations we had on the topic can be found in the PR for 7859 ( PR https://github.com/linkerd/linkerd2/pull/7883 )

### How should the problem be solved?

Deprecate the flag. We can set the version in the unit tests by using the helm template flag instead.

### Any alternatives you've considered?

N/A

**Comment by importhuman** [comment]
Hi, can I pick this up? Does this include a part I'm not understanding or it's only removing the flag?

**Comment by kleimkuhler** [comment]
This should be a fairly straightforward change. To clarify the wording, we want to deprecate (`MarkDeprecated`) the flag and not fully remove it. From there you'll have to make sure the tests still configure it properly without the flag but as stated we can use Helm's `--set` flag still.
