### ISSUE TITLE
Linkerd CRD types are not compatible with controller-tools library

### ISSUE THREAD

**Issue by aw185176** [linkerd/linkerd2#7947]
### What problem are you trying to solve?

We need to manage L5d in a hands-off, pull-based approach.  This has led us to build a service mesh controller that handles the installation of Linkerd and centralizes service injection configuration rolling workloads, and other things.  We use Flux to sync all of our manifests to each cluster.  Because our controller installs Linkerd, the CRDs wouldn't normally be present until our controller is applied and a `Linkerd` object is scheduled.  This is fine, except for our workloads are going to include `Server` / `ServerAuthorization` objects which will fail to be scheduled because those CRDs don't yet exist.  To resolve this, we would like to statically bundle the Linkerd CRDs alongside of our controller.

Typically we will generate CRDs from our open source dependencies using controller-gen (github.com/kubernetes-sigs/controller-tools) so that we can easily vendor test fixtures and install manifests without involving Helm in each of these workflows.

When trying to do this for the Linkerd types, errors are thrown regarding using non-string map keys and no version being marked for storage.  

You can recreate this problem by running the `controller-gen` binary against `github.com/linkerd/linkerd2/gen/...`

### How should the problem be solved?

Either by making the CRD types compatible with `controller-gen`, or by making the CRDs available outside of the Helm Chart.  

### Any alternatives you've considered?

We dumped the total install manifests from the `linkerd` CLI and then manually picked the CRDs out, but it is a bit tedious and updates over time will be a pain.

### How would users interact with this feature?

With love.

### Would you like to work on this feature?

no

**Comment by alpeb** [comment]
I'm not very familiar with the kubebuilder ecosystem, but extracting things separately doesn't generate errors:
```bash
controller-gen crd paths=./controller/gen/apis/server/v1beta1/...
controller-gen crd paths=./controller/gen/apis/serverauthorization/v1beta1/...
```
Running things wholesale through `controller-gen crd paths=./controller/gen/apis/..`, shows some errors even though the resources are generated, but with some weird things like duplicated sections...

Still, it seems those go types are a bit outdated, so I'll look into that. OTOH, for the upcoming linkerd 2.12 we have separated the CRDs into their own chart `linkerd-crds`, available currently in the https://helm.linkerd.io/edge  repo. Could that address your use case, perhaps extracting those resources via `helm template`? (although note that the charts in the edge won't necessarily be compatible with linkerd stable).
