### ISSUE TITLE
High latency between 2 meshed services 

### ISSUE THREAD

**Issue by haim-ari** [linkerd/linkerd2#7950]
### What is the issue?

When 2 services are communicating by linkerd proxies, latency is higher in ~20ms comparing to communicating without linkerd.

### How can it be reproduced?

* Setting up Linkerd 2.11
* Injecting both apps with Linkerd

### Logs, error output, etc

<img width="1404" alt="LinkerD" src="https://user-images.githubusercontent.com/4179195/155382031-2782b461-16b3-4645-82c8-7ff3c9c9a2e1.png">

### output of `linkerd check -o short`

```
linkerd check -o short
Linkerd core checks
===================


Status check results are √

Linkerd extensions checks
=========================


Status check results are √


Status check results are √


Status check results are √
```

### Environment

Tested in production ENV + in local cluster

## Production
RKE (Rancher 2.5.9)
k8s v1.20.8
Ingress Helm Chart version: 3.12.0
Linkerd 2.11

Local k3d 
k8s v1.20.8
Ingress Helm Chart version: 3.12.0
Linkerd 2.11

**Comment by cpretzer** [comment]
@haim-ari what is the protocol for the traffic where you are seeing that increased latency?

**Comment by haim-ari** [comment]
@cpretzer HTTP
