### ISSUE TITLE
Grafana "outbound" latency chart is incomplete

### ISSUE THREAD

**Issue by bourquep** [linkerd/linkerd2#800]
* Conduit v0.4.0
* Proxy injected into deployments A and B
* Deployment A calls deployment B

When looking at the Grafana dashboard for deployment A, the _Outbound Traffic Latency_ chart is missing a lot of timespans even though I have a steady RPS:

<img width="1056" alt="image" src="https://user-images.githubusercontent.com/65096/38967769-8bd865bc-4356-11e8-95f8-57c83bbbabc8.png">

* I am observing this with other deployments as well
* I am observing this in both the "global outbound traffic" chart and the expanded "outbound traffic to a specific deployment" chart.
* In some cases the outbound traffic latency chart is completely empty.

**Comment by siggy** [comment]
That graph runs the following Prometheus query:
```
histogram_quantile(0.95, sum(rate(response_latency_ms_bucket{namespace="$namespace", deployment="$deployment", direction="outbound"}[20s])) by (le, dst_deployment))
```
... where are the `$foo` vars are templated from Grafana. Can you substitute those vars for your current selection in the dashboard, and then run that query against Prometheus:

```bash
$ kubectl -n conduit port-forward $(kubectl --namespace=conduit get po --selector=conduit.io/control-plane-component=prometheus -o jsonpath='{.items[*].metadata.name}') 9090:9090 &
$ open localhost:9090
```

**Comment by bourquep** [comment]
Running the query against Prometheus to get a "now" snapshot returns `NaN` for certain outbound deployments:

<img width="139" alt="image" src="https://user-images.githubusercontent.com/65096/39380308-1bcd3496-4a2c-11e8-86a2-59ca280901f0.png">

Which is to be expected I guess, because my observed deployment isn't calling into all outbound deployments at all times. This would imply that when I see holes in the latency chart, it means that none of the outbound deployments were involved in the blank time range. It feels wrong, but it might very well be true.

I see the holes in the Prometheus graph as well:

<img width="1873" alt="image" src="https://user-images.githubusercontent.com/65096/39380425-83cd7e16-4a2c-11e8-9fe4-56788d31b61d.png">

**Comment by klingerf** [comment]
@bourquep I just wanted to check in to see if you're still seeing this issue. I can't reproduce it with conduit 0.5.0. It is the case that the latency graph is incomplete if one of my deployments didn't receive any traffic in a 10-second collection window:

![image](https://user-images.githubusercontent.com/9226/42791064-1fd4913e-8923-11e8-9873-fb05fa626e89.png)

But as long as at least one pod in the deployment receives at least one request per collection window, then there are no gaps in the graphs. So as far as I can tell, not all pods need to receive traffic in each window in order for us to successfully draw the latency graph. Would you mind checking your dashboards to see if that's consistent with what you're seeing?

**Comment by bourquep** [comment]
@klingerf Unfortunately, I haven't had time to test any Conduit releases post 0.3. I think you can close this issue now, I'll reopen if I ever see it again once I deploy the latest Conduit version.

**Comment by klingerf** [comment]
@bourquep Thanks for the feedback -- definitely let us know if you see it again going forward.
