### ISSUE TITLE
Make Linkerd healthcheck package less tightly coupled to the `linkerd` CLI

### ISSUE THREAD

**Issue by aw185176** [linkerd/linkerd2#8000]
### What problem are you trying to solve?

We have built a L5d controller to manage our mesh installation and implement many of the pieces that aren't available in L5d out of the box (eg https://github.com/linkerd/linkerd2/issues/4015) and to avoid install churn.  We would like to surface a more sophisticated status on whether or not the mesh is healthy, and the `healthcheck` package that already exists seemed quite promising.  The issue is that its tightly coupled to the `linkerd` CLI, even assuming that the result / output will be printed to stdout (instead of returning values to some component which can decide to log them and in what format).

### How should the problem be solved?

If the checks could be pulled into their own package so that they are more easily usable from non-CLI contexts, it would be very helpful.

### Any alternatives you've considered?

Scheduling a `linkerd check` CronJob and watching the results.

### How would users interact with this feature?

Via Go code.

### Would you like to work on this feature?

no

**Comment by olix0r** [comment]
One workaround would be to fork `linkerd check -o json` to at least get parseable output you can read programmatically. We haven't really designed any of Linkerd's internals to be consumed as a library, don't do semantic versioning on these components, etc. Furthermore, some Linkerd extensions CLIs aren't even implemented in Go, but adhere to the `linkerd <ext> check -o json` contract.

I think we're open to PRs that extract useful helpers, but I don't think we're likely to publish a stable library interface for this functionality in the short-term. The JSON-formatted CLI output is probably the best we can offer as far as a stable API.

**Comment by aw185176** [comment]
I figured that would be the case, but wanted to ask anyway.  Thanks for the response, feel free to close as `wontfix`.
