### ISSUE TITLE
Capture target application port in outbound cross-cluster request metrics

### ISSUE THREAD

**Issue by klingerf** [linkerd/linkerd2#8003]
### What problem are you trying to solve?

When linkerd makes a cross-cluster request, the request flows from the source application pod running in cluster A, through the multicluster gateway pod running in cluster B, to the destination application pod running in cluster B. Each of these three pods is injected with a linkerd proxy, and I'd like to be able to join the metrics from the source application pod in cluster A to the destination application pod in cluster B, but it's difficult to do this with the currently available set of metric labels.

By way of example, I have a multicluster setup with the "hello" deployment in cluster "east" sending traffic to the "world" deployment in cluster "west". For the cross-cluster request, the linkerd proxy in the "hello" pod in the "east" cluster emits the following outbound metric:

```
response_total{
  app="hello"
  authority="world-west.default.svc.east.k3d.example.com:7778"
  classification="success"
  control_plane_ns="linkerd"
  deployment="hello"
  direction="outbound"
  dst_namespace="default"
  dst_service="world-west"
  dst_target_cluster="west"
  dst_target_service="world"
  dst_target_service_namespace="default"
  instance="10.42.0.56:4191"
  job="linkerd-proxy"
  namespace="default"
  pod="hello-66d8664884-wzds2"
  pod_template_hash="66d8664884"
  server_id="linkerd-gateway.linkerd-multicluster.serviceaccount.identity.linkerd.west.k3d.example.com"
  status_code="200"
  target_addr="172.20.0.4:4143"
  target_ip="172.20.0.4"
  target_port="4143"
  tls="true"
  workload_ns="default"
}
```

The linkerd proxy in the "linkerd-gateway" pod in the "west" cluster emits the following outbound metric:

```
response_total{
  app="linkerd-gateway"
  authority="world.default.svc.west.k3d.example.com:7778"
  classification="success"
  control_plane_ns="linkerd"
  deployment="linkerd-gateway"
  direction="outbound"
  dst_control_plane_ns="linkerd"
  dst_deployment="world"
  dst_namespace="default"
  dst_pod="world-56fc48db7d-bhhkx"
  dst_pod_template_hash="56fc48db7d"
  dst_service="world"
  dst_serviceaccount="default"
  instance="10.42.0.48:4191"
  job="linkerd-proxy"
  namespace="linkerd-multicluster"
  pod="linkerd-gateway-6b9c9df95f-z5zqj"
  pod_template_hash="6b9c9df95f"
  server_id="default.default.serviceaccount.identity.linkerd.west.k3d.example.com"
  status_code="200"
  target_addr="10.42.0.51:7778"
  target_ip="10.42.0.51"
  target_port="7778"
  tls="true"
  workload_ns="linkerd-multicluster"
}
```

And the linkerd proxy in the "world" pod in the "west" cluster emits the following inbound metric:

```
response_total{
  app="world"
  authority="world.default.svc.west.k3d.example.com:7778"
  classification="success"
  client_id="linkerd-gateway.linkerd-multicluster.serviceaccount.identity.linkerd.west.k3d.example.com"
  control_plane_ns="linkerd"
  deployment="world"
  direction="inbound"
  instance="10.42.0.51:4191"
  job="linkerd-proxy"
  namespace="default"
  pod="world-56fc48db7d-bhhkx"
  pod_template_hash="56fc48db7d"
  saz_name="default:all-unauthenticated"
  srv_name="default:all-unauthenticated"
  status_code="200"
  target_addr="10.42.0.51:7778"
  target_ip="10.42.0.51"
  target_port="7778"
  tls="true"
  workload_ns="default"
}
```

You can see that the `target_port` label in the second and third metric is set to 7778, which is the application port. The `target_port` label in the first metric is set to 4193, however, which is a proxy port. There's no real way to see from the first metric that the request is destined for port 7778 on the other side. 7778 does appear in the `authority` label, but that feels brittle. We shouldn't need to parse out the port portion of the authority header to know to which application port the request is heading.

### How should the problem be solved?

It seems like there are two options. For the first metric, we could update the `target_addr` / `target_id` / `target_port` labels to reflect the IP and port of the destination pod in the remote cluster. That way these labels would match in all 3 metrics, but I'm not sure this is really possible. Alternatively we could add a new label (`dst_target_target_port`?) that holds the target application port.

### Any alternatives you've considered?

Just use the port from the `authority` label.

**Comment by adleong** [comment]
Adding a `dst_target_port` metric doesn't seem unreasonable to me.
