### ISSUE TITLE
Split high availability configuration from the podAntiAffinity value flag in the helm chart

### ISSUE THREAD

**Issue by evan-hines-firebolt** [linkerd/linkerd2#8062]
### What problem are you trying to solve?

We cannot use podAntiAffinity in our cluster due to constraints imposed by our autoscaler. Instead, we must use topologySpreadConstraints added via mutating webhooks. However, the .Values.podAntiAffinity flag is currently overloaded to control PDB generation and rollingUpdate configuration in addition to setting the podAntiAffinity constraints.

### How should the problem be solved?

I would like to propose a new flag `highAvailability` or `ha` that controls general high availability settings, such as PDB and rollingUpdate configurations, while not affecting the podAntiAffinity constraints. The existing podAntiAffinity value would then manage only the podAntiAffinity configuration. For backwards compatibility, we could keep the same behavior if podAntiAffinity: true but also allow PDB and rolling update to be controlled by the highAvailability flag if podAntiAffinity: false. The default for highAvailability would be false to maintain current behavior.

### Any alternatives you've considered?

Our current workaround is to set podAntiAffinity: true in the values file and use a mutating webhook to set podAntiAffinity to an empty dict. This isn't ideal but it does work.

### Would you like to work on this feature?

yes

**Comment by evan-hines-firebolt** [comment]
If this is something that would be accepted, I would be happy to make the change.

**Comment by kleimkuhler** [comment]
@evan-hines-firebolt This sounds reasonable! I'm thinking this would involve add something like `enableHA: true` to `values-ha.yaml`. We'd use that to generate PDBs and rolling update configurations. Then, users could still pass `--set enablePodAntiAffinity=false` to disable pod anti-affinity constraints.

As you mentioned this is backwards compatible so this all sounds good to me.

**Comment by evan-hines-firebolt** [comment]
Will get to work on this tonight. The last two times I tried to post, github happened to be down. Hopefully third times a charm.

**Comment by evan-hines-firebolt** [comment]
If that change looks good, I can also look into adding topologySpreadConstraints instead of podAntiAffinity when enableHA is true. It doesn't matter on our side since we have a global webhook for it but may be useful to community.

If that is something that interests you, I can make another issue.
