### ISSUE TITLE
Watch CNI plugin conf files for changes

### ISSUE THREAD

**Issue by mateiidavid** [linkerd/linkerd2#8070]
### What problem are you trying to solve?

Our CNI plugin has two race conditions:

* if used together with another plugin (running in `"chained mode"`), if the cluster restarts or node reboots, there is no guarantee our plugin will run **after** the plugin it is supposed to append to. It's common to see this scenario with Calico/Cilium; our plugin may run first in which case we end up with two different configuration files, one for the other CNI plugin and one for ours.
* if a cluster restarts or a node reboots, pods may start up without any iptables rules if they run **after** our CNI plugin.

These issues have both been documented in other places, such as:

* #7855
* #2219
* #4049
* #4789

This issue focuses on the first condition described above.

### How should the problem be solved?

The end goal is to ensure that configuration files can be reconciled, regardless of which pod created them. It would be ideal to not have to refactor too much code and keep the changes minimal so they are easier to review (and work with in the future). Writing these configuration files can introduce quite a bit of complexity, I think the current bash script form is well suited to the task so I am apprehensive to re-write it in another language. With this in mind, I propose the following:

1. Introduce a new `chainedMode` value in the CNI chart. Our CNI plugin currently tries to do a bit too much, e.g deciding whether to create a standalone plugin file or chain to a different plugin.

https://github.com/linkerd/linkerd2/blob/518af12c7d8d321550517f7435421b87cf3652c8/cni-plugin/deployment/scripts/install-cni.sh#L55-L60

We can simplify this through a `chainedMode` condition. If our plugin needs to chain to another configuration file, we can either wait until a file is present before carrying on with the rest of our operations, or exist gracefully from the script (prompting the DaemonSet to spin another pod until we find a file to append to).

2. Introduce a file watch to react to any config changes. If the configuration will change, we should re-run our configuration templating and append to the file again. This may happen for a variety of reasons, including but not limited to:

 - CNI plugin configuration changes
 - Race conditions with other plugins (suppose three plugins should be chained together and a third plugin chains to file while linkerd-cni is doing operations; we'd end up with a messy config, we should re-install everything)

Unfortunately, we can't rely on any platform specific fs event tools (such as `inotify`) because we cannot guarantee such utils are installed on the host. We can, however, use `stat` to check modification timestamps and attempt to re-install if we spot a diff between the last and current observed times. We'd have to busy loop, check, and sleep but I don't anticipate this being a problem; we are currently endlessly sleeping in the container anyway so the kubelet doesn't kill it.

### Any alternatives you've considered?

.

### Would you like to work on this feature?

yes

**Comment by mateiidavid** [comment]
Quick update. Instead of relying on `stat` we can probably pull in `inotify` in the container since this doesn't need to run on the host.

**Comment by adleong** [comment]
It's a bit frustrating that there's no wider guidance on how multiple CNI plugins are supposed to be managed and get along and that other common CNI plugins don't chain onto Linkerd's configuration the way we chain onto theirs.  Ok, I'm done complaining now.

If we implement step 2 in the above description, do we actually need to do step 1 at all?  If we run a reconciliation loop that ensures the config is valid and contains the Linkerd configuration, we shouldn't need to terminate and be restarted, right?

I would imagine that the reconciliation logic would be something like:

```
if a non-linkerd CNI config file exists:
    delete the linkerd CNI config file if it exists;
    if the CNI config file does not contain the Linkerd configuration:
        append Linkerd configuraiton to CNI config file
    end
else
    create Linkerd CNI config file
end
```

Pulling in `inotify` sounds promising.  If that doesn't work out, I think having a sleep-loop should be perfectly fine.

**Comment by mateiidavid** [comment]
> It's a bit frustrating that there's no wider guidance on how multiple CNI plugins are supposed to be managed and get along and that other common CNI plugins don't chain onto Linkerd's configuration the way we chain onto theirs. Ok, I'm done complaining now.

Hear, hear :( 

Yeah, we can absolutely skip the first step. I added it in because I thought it would help simplify the bash logic, but we can definitely react to the filesystem itself and infer whether an existing CNI config file exists or if we should create our own.
