### ISSUE TITLE
Unable to communicate between two processes using TCP (not HTTP) using linkerd with mTLS

### ISSUE THREAD

**Issue by mikematbhmi** [linkerd/linkerd2#8081]
### What is the issue?

I have a pair of python scripts, one that acts as a server and one that acts as a client.  The client connects to the server, sends 100000 bytes, then posts a recv for 100,000 bytes.  When it receives the complete response, it disconnects, and then repeats the cycle.  The server accepts a connection, reads for 100,000 bytes, then sends the 100,000 bytes back to the client, and disconnects.  This works fine in Kubernetes, but when I add them to a cluster that has linkerd installed, the behavior I see is:
 
1.	The client connects, sends 100000 bytes, and then posts a recv for 100000 bytes from the server.
2.	The server listens for a connection, ….. and never gets it.

I turned on the linkerd trace for both the client and server, and have attached gists for the logs.  As best I can tell from the logs, (and I am not a linkerd expert) linkerd seems to be accumulating the request data, but never sends it.   Any help would be appreciated.  (Note: this is a test case to see if our app can use linkerd.  This works with Kubernetes without a service mesh, and with Istio.  We would prefer to use linkerd due to its simplicity and performance, but we need to figure this out first.)

Any help would be greatly appreciated!  Thanks!

### How can it be reproduced?

I have included in the gist the two python scripts and two Dockerfiles to create the client and server images.  Also included are the Kubernetes yaml files.  The server yaml file should be run first, followed by the client yam file.

### Logs, error output, etc

Here is the gist with:

- linkerd proxy logs for client and server
- kubernetes yaml files for client and server
- python source for client and server
- Dockerfiles for client and server

https://gist.github.com/mikematbhmi/97ad6bbad670d1ace8bc4c02f1327a3e

### output of `linkerd check -o short`

[test@mtest7 smtclnt]$ linkerd check -o short
Linkerd core checks
===================

Status check results are √

Linkerd extensions checks
=========================

Status check results are √

### Environment

-Kubernetes server version: 1.21.5
-Cluster environment: Rancher RKE
-Host OS:  Oracle Enterprise Linux 8
-Linkerd version: 2.11.1

**Comment by olix0r** [comment]
@mikematbhmi Excellent! I'm going to close this issue out, but please let us know if you hit other issues as you get started with Linkerd!
