### ISSUE TITLE
Content-Security-Policy header violation reports

### ISSUE THREAD

**Issue by tspearconquest** [linkerd/linkerd2#8179]
### What is the issue?

Linkerd is using some unsafe inline `<style>` tags in the Dashboard.

### How can it be reproduced?

We have a WAF which adds Content-Security-Policy-Report-Only headers (CSP v2) to all HTTP responses from the cluster, and we have Linkerd's dashboard exposed from the cluster through the WAF.

So after configuring the CSP policy on the WAF to allow safe directives only from the trusted external sources linkerd requires that a client have access to, we find the below error message in our web console

### Logs, error output, etc

```
[Report Only] Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self' https://fonts.googleapis.com". Either the 'unsafe-inline' keyword, a hash ('sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='), or a nonce ('nonce-...') is required to enable inline execution.
```

### output of `linkerd check -o short`

N/A

### Environment

- Kubernetes Version: 1.18.x and 1.19.x
- Cluster Environment: AKS
- Host OS: Ubuntu 18.04
- Linkerd version: stable-2.11.1

### Possible solution

Add nonce values for all required unsafe inline elements that can't be moved out of the HTML

### Additional context

Our CSP header for the linkerd dashboard endpoint in the WAF is configured as follows (slightly modified for public consumption):

```
    add_header Content-Security-Policy-Report-Only "default-src 'none'; base-uri 'self'; connect-src 'self' https://linkerd.io https://versioncheck.linkerd.io; font-src 'self' https://fonts.gstatic.com; form-action 'self'; frame-ancestors 'self'; frame-src 'self'; img-src 'self'; object-src 'none'; script-src 'self'; style-src 'self' https://fonts.googleapis.com;" always;
```

**Comment by yuchieh8968** [comment]
@tspearconquest  Hello, have you found a solution for this problem? Facing the exact same problem with similar setup. Any suggestions would be greatly appreciated!

**Comment by tspearconquest** [comment]
My team moved on without solving it; for sites we can't fix, we leave the CSP header in reporting only mode so that the dashboard continues to work but in violation of the CSP header.

**Comment by yuchieh8968** [comment]
I see. Thank you for your response! Really appreciate it
