### ISSUE TITLE
Proxy improperly records some counts and latencies

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#818]
Currently, the proxy records the following metrics:

| metric | meaning |
|-------|----|
| `request_total` | number of request **trailers** sent |
| `request_duration` | time spent sending a request payload |
| `response_latency` | the time between the request headers being sent and the response **trailers** being received |
| `response_total` | number of complete responses sent |

1. I think it's preferable to measure latency as the time between the request headers being sent and the time being the response **headers** being received. This avoids treating large payloads and sparse streams as "slow" in terms of latency. This is how our load balancer will measure latency.
2. I think we should increment `request_total` at the time of request **headers** being sent. Otherwise, there is no way to account for this pending work in the system.

(1) poses a small challenge: we cannot properly include classification labels on latencies, because classification may require letting the response stream complete (or fail).

I propose the following changes:
1. we move request_total counting to the head-of-request
2. we _record_ the latency as the time between request head and response head, but we _report_ the latency only when the response has completed and the stream is properly classified.

---

Note that when I refer to _trailers_, I don't necessarily mean literal http trailers -- I mean end-of-unidirection-stream, as opposed to headers at the start of such a stream.

**Comment by olix0r** [comment]
I think we should address this before pursuing latency-aware load balancing.  My loose plan of attack is the following:

1. Restructure event-processing logic so that we can start by measuring latency between request and response. This is a necessary first step, since we currently are _only_ able to record a latency value after we've classified the whole stream as a success for failure; and we currently separate success and failure latencies.
2. Introduce a new telemetry event type that is emitted either on all data reads or only the first read.
3. Change the reported latency to use this new measurement.

**Comment by hawkw** [comment]
I'd also be happy to work on some of these changes, if you like.
