### ISSUE TITLE
Call proxy shutdown endpoint to fix namespace-metadata helm jobs not completing

### ISSUE THREAD

**Issue by Foltik** [linkerd/linkerd2#8194]
### What problem are you trying to solve?

The helm charts for the jaeger, viz, and multicluster extensions create a `namespace-metadata` job which never completes. The pods that the jobs create get stuck in a `NotReady` state because their sidecar container never exits (see #1869).

I'm using Flux to deploy these helm charts, which interprets this non-completion as failure to finish the installation and requires a workaround.

### How should the problem be solved?

Using the `/shutdown` endpoint added in linkerd/linkerd2-proxy#811, the jobs' main containers could be updated to manually terminate the proxy when finished, allowing the pod to terminate and the job to complete (see https://github.com/Foltik/linkerd2/commit/398c2c53a5c21f4199721817567fe4bea3ddc13e).

### Any alternatives you've considered?

It looks like the official solution to this issue in the future will be to use the Keystone containers feature from kubernetes/enhancements/issues/2872.

### Would you like to work on this feature?

yes

**Comment by olix0r** [comment]
It may be simpler to configure these jobs to not be injected. The proxy probably is not adding any real value for this workload.

**Comment by Foltik** [comment]
Ah, looks like the jobs were auto injected because of a namespace annotation. If they don't need the proxy then this issue can be closed.

**Comment by olix0r** [comment]
@Foltik Ah, okay. Yeah, the control plane/extension namespaces do not need the inject annotation and, instead, workloads are injected individually.
