### ISSUE TITLE
Linkerd/Linkerd-viz fails after node eviction

### ISSUE THREAD

**Issue by yuriy-filatov** [linkerd/linkerd2#8228]
### What is the issue?

Clean deploy onto EC2-based dedicated cluster with kops + k8s 1.22.8 which is using spot instances for worker nodes.
Linkerd is installed successfully, all check are fine.

After the node eviction Linkerd failed to "start" properly:
```
√ tap API service is running
‼ linkerd-viz pods are injected
    could not find proxy container for grafana-8d54d5f6d-6n56v pod
    see https://linkerd.io/2.11/checks/#l5d-viz-pods-injection for hints
√ viz extension pods are running
× viz extension proxies are healthy
    No "linkerd-proxy" containers found in the "linkerd" namespace
    see https://linkerd.io/2.11/checks/#l5d-viz-proxy-healthy for hints

Status check results are ×
```
Restart of all pods in linkerd namespace and restart of all linkerd-viz pods helps with the issue, linkerd check is OK after this.

But we also need to bounce all deployments to pick up sidecar linkerd-proxy container -- and that's a potentially unwanted thing.

### How can it be reproduced?

Launch whole linkerd-related deployment on a spot instance and wait for eviction (or launch a single worker node cluster and terminate the worker node).

### Logs, error output, etc
Initial after eviction:
```
√ tap API service is running
‼ linkerd-viz pods are injected
    could not find proxy container for grafana-8d54d5f6d-6n56v pod
    see https://linkerd.io/2.11/checks/#l5d-viz-pods-injection for hints
√ viz extension pods are running
× viz extension proxies are healthy
    No "linkerd-proxy" containers found in the "linkerd" namespace
    see https://linkerd.io/2.11/checks/#l5d-viz-proxy-healthy for hints

Status check results are ×
```
restarted Linkerd pods and grafana pod in linkerd-viz:
```
√ linkerd-viz Namespace exists
√ linkerd-viz ClusterRoles exist
√ linkerd-viz ClusterRoleBindings exist
√ tap API server has valid cert
√ tap API server cert is valid for at least 60 days
√ tap API service is running
‼ linkerd-viz pods are injected
    could not find proxy container for metrics-api-6c59967bf4-p59mh pod
    see https://linkerd.io/2.11/checks/#l5d-viz-pods-injection for hints
√ viz extension pods are running
√ viz extension proxies are healthy
√ viz extension proxies are up-to-date
‼ viz extension proxies and cli versions match
    metrics-api-6c59967bf4-p59mh running  but cli running stable-2.11.1
    see https://linkerd.io/2.11/checks/#l5d-viz-proxy-cli-version for hints
√ prometheus is installed and configured correctly
√ can initialize the client
√ viz extension self-check
```
Restarted metrics-api:

```
√ linkerd-viz Namespace exists
√ linkerd-viz ClusterRoles exist
√ linkerd-viz ClusterRoleBindings exist
√ tap API server has valid cert
√ tap API server cert is valid for at least 60 days
√ tap API service is running
‼ linkerd-viz pods are injected
    could not find proxy container for prometheus-7bbc4d8c5b-rh65z pod
    see https://linkerd.io/2.11/checks/#l5d-viz-pods-injection for hints
√ viz extension pods are running
√ viz extension proxies are healthy
√ viz extension proxies are up-to-date
‼ viz extension proxies and cli versions match
    prometheus-7bbc4d8c5b-rh65z running  but cli running stable-2.11.1
    see https://linkerd.io/2.11/checks/#l5d-viz-proxy-cli-version for hints
√ prometheus is installed and configured correctly
√ can initialize the client
√ viz extension self-check
```
etc.

linkerd-proxy pod in linkerd namespace throws tons of connection errors.

### output of `linkerd check -o short`

Before the restart (sorry, not short one)
```
√ tap API service is running
‼ linkerd-viz pods are injected
    could not find proxy container for grafana-8d54d5f6d-6n56v pod
    see https://linkerd.io/2.11/checks/#l5d-viz-pods-injection for hints
√ viz extension pods are running
× viz extension proxies are healthy
    No "linkerd-proxy" containers found in the "linkerd" namespace
    see https://linkerd.io/2.11/checks/#l5d-viz-proxy-healthy for hints

Status check results are ×
```

After the step-by-step restart
```
Linkerd core checks
===================


Status check results are √

Linkerd extensions checks

Status check results are √

```

### Environment

- Kubernetes version: 1.22.8
- Cluster env: AWS EC2, spot m4.2xlarge workers, kops 1.23.0 
- Ubuntu 18.04.6
- Linkerd stable-2.11.1 (both client and erver)

### Possible solution

Restart in a proper order?

**Comment by olix0r** [comment]
Unfortunately, there's nothing we can do in Linkerd to dictate the order in which Kubernetes restarts pods. We recommend running Linkerd with a configuration that ensures at least one replica of the core control plane components are running. There are a variety of knobs kubernetes exposes to support this, like pod anti-affinity, that are enabled via the default HA configuration https://github.com/linkerd/linkerd2/blob/fbf9cc13929fad0cd6fd527e65875bc75eccb6ad/charts/linkerd-control-plane/values-ha.yaml.

**Comment by yuriy-filatov** [comment]
thanks @olix0r.
Is there a way to upgrade existing installation to HA or we need to start from scratch?

**Comment by yuriy-filatov** [comment]
thank you @olix0r
