### ISSUE TITLE
Grafana: fix deployment count inconsistencies

### ISSUE THREAD

**Issue by siggy** [linkerd/linkerd2#823]
The `Inbound Deployments` top-line metric does not match the actual list of Inbound Deployments shown in the dashboard.

In the example detailed here, top-line shows 10, the dashboard shows 9.

## Top-Line

`Inbound Deployments` runs this query:

```
count(count(request_total{dst_namespace="strest-102b82ec", dst_deployment="strest", direction="outbound"}) by (namespace, deployment))
```

...and yields 10 deployments:

![screen shot 2018-04-20 at 11 54 21 am](https://user-images.githubusercontent.com/236915/39068584-9b43f99e-4491-11e8-9f46-28464414b46f.png)

Digging into Prometheus, we see 10 deployments:

```
count(request_total{dst_namespace="strest-102b82ec", dst_deployment="strest", direction="outbound"}) by (namespace, deployment)
```

...which yields:

![screen shot 2018-04-20 at 11 53 48 am](https://user-images.githubusercontent.com/236915/39068550-826415f8-4491-11e8-86d8-25a04f466260.png)

## Dashboard

The dashboard uses a Grafana template variable `$inbound`, based on this query:

```
label_values(request_total{dst_namespace="$namespace", dst_deployment="$deployment"}, deployment)
```

... which yields 9 deployments:

![screen shot 2018-04-20 at 11 58 50 am](https://user-images.githubusercontent.com/236915/39068772-4a60ebe4-4492-11e8-8504-f11e557995df.png)

## Root cause

Two of the deployments have the same name but different namespaces:

```
{deployment="strest",namespace="strest-30f5c29e"}
{deployment="strest",namespace="strest-102b82ec"}
```

The `$inbound` variable loses this information, as it ignores the namespace, and only counts unique deployment names.

We need a way to make `$inbound` template variable (and similar) unique by namespace + deployment name. Possibly by modifying the template variable query, or limiting variables like `$inbound` to one namespace at a time.

**Comment by rmars** [comment]
Looking at `top-line.json` I can see that this field is now "Deployments Monitored" rather than "Inbound Deployments" and that the query is now:
```
"expr": "count(count(request_total{namespace=~\"$namespace\"}) by (namespace, deployment))",
```
This query does take into account the namespace/deployment combination and should return the correct count, so the "Deployments Monitored" field we now show in the `Conduit Top Line` dashboard should be correct even if two deployments have the same name.

**Comment by bourquep** [comment]
FYI, with v18.8.2, the _Deployments Monitored_ number in my Top-Line grafana dashboard keeps oscillating between 13 and 15, although the deployments on this cluster are stable (we aren't creating/updating/deleting any deployments).
