### ISSUE TITLE
Create an internal library for matching prometheus metrics

### ISSUE THREAD

**Issue by krzysztofdrys** [linkerd/linkerd2#8250]
### What problem are you trying to solve?

In a few places, tests assert on metrics emitted by linkerd proxy. Usually these tests are done using regex. For example here: https://github.com/linkerd/linkerd2/blob/main/test/integration/deep/skipports/skip_ports_test.go#L20

This approach surely works. However, for some people (for example: me), regular expressions can be a little hard to read. Because of this it is often not obvious, what we are exactly trying to test. 

### How should the problem be solved?

Introduce a library for matching prometheus metrics. Internally it would use [github.com/prometheus/common/expfmt](https://github.com/prometheus/common/tree/main/expfmt). 

Assuming this library would be called `prommatch`, we could change this:
```
	httpResponseTotalMetricRE = regexp.MustCompile(
		`route_response_total\{direction="outbound",dst=".*\.skip-ports-test\.svc\.cluster\.local:7002",classification="failure".*`,
	)
```
to this
```
 httpResponseTotalMetric = prommatch.Counter{
    Name: "route_response_total",
    Labels: prommatch.Labels{ 
          "direction": prommatch.Equals("outbound"),
          "dst": prommatch.Matches(".*.skip-ports-test.svc.cluster.local:7002"),
          "classification": prommatch.Equals("failure"),
     }
}
```
While this is much more verbose, IMO it is easier to read and maintain. Of course, package name and exact syntax are up for debate. 

### Any alternatives you've considered?

An obvious alternative is to do nothing and keep things how they are. :-) 

### How would users interact with this feature?

They wouldn't. We could even make this an internal package to make sure it cannot be used "outside". 

### Would you like to work on this feature?

yes

**Comment by mateiidavid** [comment]
@krzysztofdrys sounds good, we'd love to have this in. Using `expfmt` to parse the metrics is what we think would be best here too.

We can have this as part of `testutil`, I don't have a strong opinion on where the code should reside. As to the implementation, I'm pretty certain we can create a reader from a string through `strings.NewReader`. I imagine we'd create a decoder with the reader and then process whatever metrics we're interested in. We can start with some helper functions and change opaque ports test to use it, the rest of the tests can be tackled in different PRs. Wdyt?

Leaving some links down here for reference, in case anyone else is curious.

* [Go docs expfmt](https://pkg.go.dev/github.com/prometheus/common@v0.33.0/expfmt)
* [Exposition formats](https://github.com/prometheus/docs/blob/main/content/docs/instrumenting/exposition_formats.md)
