### ISSUE TITLE
when control plane is down, meshed pods are not working

### ISSUE THREAD

**Issue by munger1985** [linkerd/linkerd2#8274]
### What is the issue?

when we scale the control plane to 0
kubectl get deploy -n linkerd |grep -v NAME|awk '{print $1}'|xargs -I ARG kubectl scale deploy ARG -n linkerd  --replicas=0 

used booksapp app,  from authors pod to ping books pod, failed.
k -n booksapp exec -it authors-5fdcc84c89-66srd -c linkerd-debug  --   curl   http://books.booksapp:7002/books.json
connection reset by peer

we can see the proxy is still there, but not ok to ping each other, we guessed there is some connection tracking, if control is down, connection is broken with iptables in pods. 

when we bring up control plane, it is working again. so this is not making sense

### How can it be reproduced?

booksapp 

### Logs, error output, etc

 k -n booksapp exec -it authors-5fdcc84c89-66srd -c linkerd-debug  --   curl   http://books.booksapp:7002/books.json
connection reset by peer

### output of `linkerd check -o short`

k -n booksapp exec -it authors-5fdcc84c89-66srd -c linkerd-debug  --   curl   http://books.booksapp:7002/books.json
connection reset by peer

### Environment

k8s
linkerd edge

### Possible solution

linkerd-proxy might have added some iptables to the pod

**Comment by olix0r** [comment]
Linkerd proxies need the control plane to resolve connection information, especially whether TLS should be used. Proxies cache this information for actively used connections/endpoints, but if the control plane is down--especially the destination controller--proxies will be unable to build new clients.

We recommend running enough destination controller replicas to ensure that your cluster can withstand losing nodes without impacting mesh availability.

**Comment by munger1985** [comment]
dear dude， not affecting the new clients, affected old pod,  https://www.youtube.com/watch?v=ayskWYigqEE

**Comment by munger1985** [comment]
> Linkerd proxies need the control plane to resolve connection information, especially whether TLS should be used. Proxies cache this information for actively used connections/endpoints, but if the control plane is down--especially the destination controller--proxies will be unable to build new clients. The destination controllers function like your DNS servers. If you shutdown all of the clusters's DNS servers, you would end up in a similar state.
> 
> We recommend running enough destination controller replicas to ensure that your cluster can withstand losing nodes without impacting mesh availability.

can u check this video i made

**Comment by olix0r** [comment]
@munger1985 Thanks. It's a little difficult for me to replicate your test based on a video, so let me document a test I just ran to confirm that the behavior works as I'd expect. I'm using linkerd 2.11.2 on the client and server.

1. The control plane is installed and running:
```text
:; linkerd version
Client version: stable-2.11.2
Server version: stable-2.11.2
:; linkerd check -o short
Status check results are √
:; k get po -n linkerd
NAME                                      READY   STATUS    RESTARTS   AGE
linkerd-identity-847445f99d-n8v5q         2/2     Running   0          3m39s
linkerd-destination-6c84cb54d8-h842v      4/4     Running   0          3m39s
linkerd-proxy-injector-555cd7c685-kz8dk   2/2     Running   0          3m39s
```
2. I deploy the _emojivoto_ example app:
```text
:; linkerd inject https://run.linkerd.io/emojivoto.yml | k apply -f -

namespace "emojivoto" skipped
serviceaccount "emoji" skipped
serviceaccount "voting" skipped
serviceaccount "web" skipped
service "emoji-svc" skipped
service "voting-svc" skipped
service "web-svc" skipped
deployment "emoji" injected
deployment "vote-bot" injected
deployment "voting" injected
deployment "web" injected

namespace/emojivoto created
serviceaccount/emoji created
serviceaccount/voting created
serviceaccount/web created
service/emoji-svc created
service/voting-svc created
service/web-svc created
deployment.apps/emoji created
deployment.apps/vote-bot created
deployment.apps/voting created
deployment.apps/web created
:; linkerd check -o short --proxy -n emojivoto                       
Status check results are √
:; k get po -n emojivoto 
NAME                        READY   STATUS    RESTARTS   AGE
emoji-696d9d8f95-qllpj      2/2     Running   0          2m23s
vote-bot-6d7677bb68-ngtmz   2/2     Running   0          2m23s
voting-ff4c54b8d-mjvb5      2/2     Running   0          2m23s
web-5f86686c4d-b26t6        2/2     Running   0          2m23s
```
3. In a  new terminal, I start monitoring the logs of the `vote-bot` client (which drives traffic to the web pod, which depends on both the emoji and voting pods):
```text:; k logs -n emojivoto deploy/vote-bot -c vote-bot -f --tail=0
✔ Voting for :rabbit:
✔ Voting for :steam_locomotive:
✔ Voting for :flushed:
...
```
4. I then scale down the linkerd deployments:
```text
:; k scale -n linkerd deploy --replicas=0 --all
deployment.apps/linkerd-identity scaled
deployment.apps/linkerd-destination scaled
deployment.apps/linkerd-proxy-injector scaled
:; k get po -n linkerd                        
No resources found in linkerd namespace.
```
5. I confirm that the vote-bot continues to log messages indicating its working properly. If I had prometheus setup, I would see that traffic is flowing successfully. This confirms that the data plane continues to use cached clients without issue.
