### ISSUE TITLE
Introduce `-o json` flag for `linkerd multicluster gateways`

### ISSUE THREAD

**Issue by kleimkuhler** [linkerd/linkerd2#8285]
### What problem are you trying to solve?

Having JSON output options for commands helps with programatic use of the CLI. The main driver behind this feature request though is for use in tests so that we can eliminate the manual parsing that we currently have to do in the integration tests as noted [here](https://github.com/linkerd/linkerd2/pull/8139#discussion_r840698514).

### How should the problem be solved?

We can look at other `-o json` flag implementations (for example `linkerd multicluster check`) as it should be similar.

### Any alternatives you've considered?

No

### How would users interact with this feature?

`linkerd multicluster gateways -o json`

**Comment by Santosh1176** [comment]
Hey @kleimkuhler @adleong I would like to work on this, if it's still open.

**Comment by kleimkuhler** [comment]
That'd be great @Santosh1176! Let us know if you need any help.

**Comment by Santosh1176** [comment]
@kleimkuhler Thank you! I surely will reach out, if I hit a roadblock.

**Comment by Santosh1176** [comment]
Hey @kleimkuhler I was on the job and do not have the multicluster setup ready. Is there a way to test if the command works without a Multicluster setup? This is where I am currently:


![linkerd-gateways](https://user-images.githubusercontent.com/91916466/181593712-e6566b79-b63b-4132-a186-c4ec3e5753a1.png)
struck.

**Comment by kleimkuhler** [comment]
You're going to need multicluster setup to test this properly. The `gateways` command will only have stats when the current cluster is linked to another. You may be able to use https://github.com/olix0r/l2-k3d-multi/ to try setting up two clusters (this required k3d).

If you local environment is not setup at all for k3d and testing multiple clusters, you are also welcome to open a draft PR with the changes and I can take a look myself.

**Comment by pratikkumar-mohite** [comment]
@kleimkuhler is this issue still open, I would like to work on it

**Comment by Santosh1176** [comment]
@kleimkuhler apologies for the inordinate delay on this issue. With all the help, I could not set up a multicluster env to reproduce the results, and I am stuck [here](https://github.com/linkerd/linkerd2/issues/8285#issuecomment-1198395394). If, @pratikkumar-mohite can move this ahead, please unassign me and assign them. Thank you for all the help.

**Comment by adleong** [comment]
@Santosh1176 no problem, thanks for your interest!

@pratikkumar-mohite this issue is still open and available to be worked on.

**Comment by saurabhsadhale** [comment]
@adleong @kleimkuhler  If this is still open I would be interested to work on it.

**Comment by kleimkuhler** [comment]
@saurabhsadhale sure let us know if you have any questions!

**Comment by saurabhsadhale** [comment]
@kleimkuhler  thank you.  I will start working on this by this week. I will update here if I face any issues.

**Comment by hiteshwani29** [comment]
@saurabhsadhale are you still working on the issue?
 If not I can start working on this Issue.

**Comment by hiteshwani29** [comment]
Thanks, @saurabhsadhale started working on the issue.
