### ISSUE TITLE
Pods get stuck at ContainerCreating state

### ISSUE THREAD

**Issue by tspearconquest** [linkerd/linkerd2#8323]
### What is the issue?

I'm not 100% certain what causes this issue, so the steps to reproduce are a little bit fuzzy.

On 2 separate occasions when I was doing cluster maintenance on our Azure AKS workers, I have seen an issue where the linkerd destination and proxy injector pods in the control plane don't start up, and throw DNS errors similar to the ones shown in #5932

### How can it be reproduced?

We are running linkerd stable-2.11.1 on Azure AKS.

In todays instance of this issue, I was working on migrating pods to a new nodepool.
A few weeks ago when this happened previously, I was creating new nodes in the existing nodepool on a different cluster in a different region.

Today's steps:
- I created a nodepool, cordoned the old nodepool and drained nodes one at a time using `kubectl drain`
  - The first few nodes went smoothly. Linkerd had not been evicted from the old nodepool yet, and everything looked well.
- I drained the node where both linkerd-destination and linkerd-proxy-injector were scheduled.
  - Side note: we are planning to setup HA linkerd, which is expected to prevent this issue due to the pod anti affinity defined in the HA linkerd manifest.
- The linkerd destination and linkerd proxy injector pods did not start up properly.

I tried a few different things at this point, with different effects.
Deleting linkerd-proxy-injector's deployment allowed linkerd-destination to start up, but then pods weren't getting proxies injected. So I tried to redeploy, but then the pods wouldn't start up again. I recalled that a few weeks ago I was able to solve this by deleting the linkerd-viz pods, so I did that, and then redeployed linkerd's control plane. This time, the pods spun up, and allowed other pods to spin up and receive their proxy sidecars.

Later on, while migrating back to the default nodepool, I deleted the linkerd control plane pods one at a time from the temporary nodepool and watched them start up on on the default nodepool properly rather than letting the node drain process handle it. Then I went to drain one of the nodes from the temporary nodepool, and I saw all of the containers get stuck in ContainerCreating status again.

So, in this instance, the linkerd-viz pods were not deployed, and so I simply deleted and redeployed the control plane and everything then started up properly including the stuck containers.

The really interesting part is that I can reliably reproduce the linkerd-destination and linkerd-proxy-injector pods getting stuck if linkerd-viz components are deployed. And if they are not deployed, then the other containers get stuck until I redeploy linkerd.

I am not 100% certain that the linkerd-viz components actually play a role, to be clear, but not having deployments running in that namespace definitely seems to have helped get everything up and running again.

### Logs, error output, etc

`linkerd_app_core::control: Failed to resolve control-plane component error=no record found for name: linkerd-dst-headless.linkerd.svc.cluster.local. type: SRV class: IN`

### output of `linkerd check -o short`

n/a as I didn't capture this before I fixed the issue either time

### Environment

This happened once on Kubernetes 1.19.13 a few weeks ago and again today on Kubernetes 1.22.6
Azure AKS
Ubuntu 18.04
Linkerd stable-2.11.1

**Comment by tspearconquest** [comment]
I forgot to mention one of the other things I tried before deleting the linkerd-viz namespace deployments was deleting the replicaset for linkerd-destination and linkerd-proxy-injector, so that the deployment would recreate the replicaset.

This did not help anything. After that, I deleted the linkerd-viz namespace deployments, and tried to delete the replicasets again for linkerd-destination and linkerd-proxy-injector. That also didn't fix anything.

Only once I deleted the deployments and redeployed those, with linkerd-viz namespace deployments NOT deployed, did everything finally start up.

**Comment by magec** [comment]
I think this is related to https://github.com/linkerd/linkerd2/issues/8296

**Comment by alpeb** [comment]
@tspearconquest The issue Azure/AKS#2750 also describes a problem with linkerd pods getting stuck because of a problem in AKS when using Azure CNI with Calico. Is that your setup? If not, can you please try the repro described in that issue and let us know what happens?

**Comment by tspearconquest** [comment]
Hi @alpeb we are not running Calico, only Azure CNI and Linkerd. We do have Linkerd's CNI installed, and I will say we did not see this issue prior to installing Linkerd-CNI, so there may be something to this despite us not having the exact same setup.

**Comment by tspearconquest** [comment]
Apologies, I misread the first time, do you want to know what happens if I run curl in the postStart lifecycle hook?

I haven't tried this, but I can confirm that the behavior is similar to what is described on that issue. Even this part

> The pod remains in the ContainerCreating status as expected [snip]. This status forbids us from checking the pod's logs through kubectl logs, but we can get them by getting into the node through kubectl debug:

I didn't use `kubectl debug` but rather `kubectl attach`. I could not see output through `kubectl logs`, and so I had to attach to get any info.

**Comment by alpeb** [comment]
Yes, please try deploying the Pod described in that issue and get ahold of the logs. That will allow us to know if it's exactly that issue or something else.

**Comment by olix0r** [comment]
We've merged the fix for #8296. I've pushed a proxy image (which will be included in this week's edge release) that can be used for testing: `ghcr.io/olix0r/l2-proxy:main.c7b9c6565`.

**Comment by tspearconquest** [comment]
Hello again,

I ended up coming back to this today, as I was able to secure a new dedicated nodepool for some critical pods like linkerd, so I wanted to add node affinity rules via kustomize and I ended up watching something happen in real time that I suspect may help in reproducing the issue.

What I found is that our pipeline is deploying linkerd viz components too quickly after we deploy linkerd. It's still in the middle of restarting the linkerd components when the linkerd viz components start trying to come up.

I'm planning to separate the viz deployment into a separate stage in the pipeline in order to resolve this.

One question, next time I need to do a linkerd version upgrade, will there be any errors from linkerd check if I run it at the end of deploying linkerd, before I deploy linkerd viz? I've seen issues in our pipelines sometimes when running linkerd check because of the viz component checks, so I'd like to find a way to disable the viz checks when I don't need them. Is this something we can do currently? I have not seen it mentioned anywhere. If not, could I feature request it in a different issue?

**Comment by alpeb** [comment]
> One question, next time I need to do a linkerd version upgrade, will there be any errors from linkerd check if I run it at the end of deploying linkerd, before I deploy linkerd viz? I've seen issues in our pipelines sometimes when running linkerd check because of the viz component checks, so I'd like to find a way to disable the viz checks when I don't need them. Is this something we can do currently? I have not seen it mentioned anywhere. If not, could I feature request it in a different issue?

Right after installing linkerd you can run `linkerd check`, which will block for a bit till the control plane becomes ready. As long as you haven't yet created the `linkerd-viz` namespace, `linkerd check` shouldn't trigger the viz checks.

**Comment by ayushiaks** [comment]
@alpeb will the fix be released in the stable version sometime soon?

**Comment by tspearconquest** [comment]
> Right after installing linkerd you can run linkerd check, which will block for a bit till the control plane becomes ready. As long as you haven't yet created the linkerd-viz namespace, linkerd check shouldn't trigger the viz checks.

In our setup, we perform rolling updates of linkerd so the namespace always exists and the viz namespace is always available. Is there a way to avoid the viz checks when the namespace is present?
