### ISSUE TITLE
Container image mirror

### ISSUE THREAD

**Issue by jack1902** [linkerd/linkerd2#8335]
### What problem are you trying to solve?

Currently, all images produced for linkerd live in one registry, if this goes down (as is the case currently) it is not easy to upgrade from one version to the next as it isn't possible to pull newer images (I already mirror current versions internally but I can't upgrade until the upstream registry is happy)

![image](https://user-images.githubusercontent.com/39212456/165074697-c66831fd-6658-45a2-b5de-60e3889cc26e.png)

### How should the problem be solved?

Provide an alternative mirror registry hosted by a different provider to ensure a single point of failure doesn't exist (for those wishing to upgrade and mirror images themselves into their own registries)

### Any alternatives you've considered?

Build the versions from source via `bin/docker-build` and then push to my own registry

### How would users interact with this feature?

Users would have a choice of what image-registry to use, should an upstream registry be offline they can switch the install / charts to an alternative.

### Would you like to work on this feature?

no

**Comment by AgrimPrasad** [comment]
We are facing this issue too currently.

**Comment by mateiidavid** [comment]
@jack1902 @AgrimPrasad thank you both for raising awareness to this. We'll give it due consideration, but in the mean time, I have managed to pull the latest stable proxy image. It seems GH engineers have made quick work of the outage.

You might still notice degraded performance until everything is fully fixed, you can keep up with GH's updates [here](https://www.githubstatus.com). For now, you should be able to pull images though.

**Comment by yyhpys** [comment]
Looks like google cloud's container registry images are outdated. It would be grateful to have an alternative mirror repository for recent versions in case of outage of github.

**Comment by AgrimPrasad** [comment]
> Looks like google cloud's container registry images are outdated. It would be grateful to have an alternative mirror repository other than github for recent versions in case of outage of github.

Yes, specifically these docs are outdated: https://linkerd.io/2.11/tasks/using-a-private-docker-repository/

Would be nice to have docker images mirrored to GCR again which is quite stable in our experience.

**Comment by olix0r** [comment]
GHCR is a free service. Google's is not.

If you are relying on free container registries for your production environments, you are setting yourself up for failure. There is no SLA. We strongly recommend the images be replicated  to your private registries for production use cases.

**Comment by jack1902** [comment]
> GHCR is a free service. Google's is not.
> 
> If you are relying on free container registries for your production environments, you are setting yourself up for failure. There is no SLA. We strongly recommend the images be replicated  to your private registries for production use cases.

As mentioned in this issue, I hang my production off of my own registry, but wanted to pull the newer version of linkerd, which I couldn't do due to the only source of images being down at the time of raising the issue (it's fixed now, but still leaves linkerd users without an alternative if the only source for fetching updates is offline)

If a secondary registry existed (dockerhub for example, as the project is opensource) it would enable people to use multiple sources to get updates. If people hang their environments off of these registries I see that as a different issue entirely.

**Comment by olix0r** [comment]
@jack1902 I hear you, but we're probably unlikely to spend time on this in the near future.

So much of what we do depends on GitHub: ranging from the source code to the CLI artifacts to the linkerd.io website (including the install script and the versioncheck endpoints, etc), as well as the docker container images. The specific use case of obtaining new images to upgrade is fairly narrow and isn't particularly time-sensitive; and GHCR outages have been pretty rare in the scheme of things. And there's a reasonable fallback option, as you mentioned, which is to build the containers from the repo.

If GitHub's availability becomes a larger concern, however, we'll probably be more motivated to diversify or move off of GitHub completely.

**Comment by olix0r** [comment]
I'm going to close this for now. If GHCR reliability becomes a larger problem, we will revisit it.
