### ISSUE TITLE
Pod failed to start with Linkerd, C

### ISSUE THREAD

**Issue by ericfuxealth** [linkerd/linkerd2#8378]
### What is the issue?

We have an EKS cluster on AWS with the following:
- Pod Security Group
- Cilium with AWS CNI
- Linkerd
The pod works fine with any 2 of the above but stops working when all 3 all enforced.
The problem is illustrated in this https://github.com/ericfuxealth/test-linkerd

### How can it be reproduced?

This repro https://github.com/ericfuxealth/test-linkerd provides the setup to reproduce this issue.

### Logs, error output, etc

Readiness probe failed: Get "http://10.10.37.71:4191/ready": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

### output of `linkerd check -o short`

```
$ linkerd check -o short
Linkerd core checks
===================

linkerd-existence
-----------------
‼ cluster networks can be verified
    the following nodes do not expose a podCIDR:
        ip-10-10-39-100.us-west-2.compute.internal
    see https://linkerd.io/2.11/checks/#l5d-cluster-networks-verified for hints

Status check results are √
```

### Environment

Kubernetes version: 
1.21

Cluster environment: 
EKS

Host OS:
Amazon Linux 2

Linkerd version:
- Client version: stable-2.11.2
- Server version: stable-2.11.2

**Comment by olix0r** [comment]
We're waiting on access to an EKS cluster https://github.com/cncf/credits/issues/8

**Comment by ericfuxealth** [comment]
Setting POD_SECURITY_GROUP_ENFORCING_MODE to standard seems to fix the problem. 
See
https://docs.aws.amazon.com/eks/latest/userguide/security-groups-for-pods.html 
Note that it says this needs to be set for Calico
