### ISSUE TITLE
Support GKE Autopilot Clusters

### ISSUE THREAD

**Issue by DanielZuerrer** [linkerd/linkerd2#8422]
### What problem are you trying to solve?

Due to limitations of GKE Autopilot clusters for [host options](https://cloud.google.com/kubernetes-engine/docs/concepts/autopilot-overview#host_options_restrictions) and [Linux capabilities](https://cloud.google.com/kubernetes-engine/docs/concepts/autopilot-overview#linux_workload_limitations) it is currently not possible to install linkerd in a GKE Autppilot Cluster.

While using the proxy init container approach needs the `NET_ADMIN` capability, installing the CNI plugin requires enabling hostNetwork and accessing hostPath volume cni-net-dir in container install-cni in write mode. All three requirements are disallowed in GKE Autopilot clusters.

### How should the problem be solved?

Remove the requirement for either the  `NET_ADMIN` capability or for enabling hostNetwork and accessing a hostPath volume. Otherwise, provide an alternative approach for installing and running linkerd on GKE Autopilot clusters.

### Any alternatives you've considered?

Unfortunately we have not found any alternatives for installing linkerd.

### Would you like to work on this feature?

no

**Comment by olix0r** [comment]
> there's no way to run service meshes other than Istio.

Correction: there's no way to run service meshes other than [**Anthos**](https://cloud.google.com/service-mesh/docs/overview). You couldn't even run vanilla Istio on these clusters.

**Comment by DanielZuerrer** [comment]
Thank you @olix0r and @wmorgan for the responses. I was afraid that might be the case. I will contact google and see if there is anything they can do on their end.

**Comment by DanielZuerrer** [comment]
I have received an update from Google and unfortunately, they have no plans to allow service meshes (other than Anthos) on GKE Autopilot. 

> Specifically with regards to Linkerd as service mesh - this is not supported for GKE Autopilot and there is currently also no roadmap or ETA for supporting this AFAIK. From my point of view and understanding, this is also due to a focus on Google Cloud "opinionated" solutions that aim to simplify operations, but come at a certain price of choosing specific components etc..

and

> So the short answer is sort of stay with GKE standard and Linkerd or leverage GKE Autopilot in conjunction with ASM -- a combination of GKE Autopilot with Linkered is currently not possible.

**Comment by wmorgan** [comment]
Bummer @DanielZuerrer, but not unexpected. Does this block you from using Linkerd or can you use non-autopilot clusters?

**Comment by wmorgan** [comment]
It may now be possible to deploy Linkerd on GKE Autopilot clusters. Per https://cloud.google.com/kubernetes-engine/docs/release-notes-new-features#June_22_2023 :

> GKE Autopilot now supports the ability to deploy your own service mesh. Many service meshes, such as Istio or LinkerD, require CAP_NET_ADMIN Linux capability to function, which is disabled on Autopilot clusters by default to reduce the size of the security attack surface. You can now optionally enable NET_ADMIN on your Autopilot clusters if you need this capability for your service meshes or other opt-in use cases. See [Autopilot Security](https://cloud.google.com/kubernetes-engine/docs/concepts/autopilot-security#linux_workload_limitations) for more information for how to enable NET_ADMIN.

Thanks to @revero-doug for pointing this out in #11087!
