### ISSUE TITLE
Multicluster headless service mirror isn't removed when removing exported label on target

### ISSUE THREAD

**Issue by alpeb** [linkerd/linkerd2#8475]
### What is the issue?

After successfully having mirrored a headless service by labeling it with `mirror.linkerd.io/exported=true` on target, removing that label does remove the mirrored service, but it gets created again immediately.

### How can it be reproduced?

Run the mc integration test without cleanup:
```
bin/tests --name multicluster --skip-cluster-delete `pwd`/target/cli/linux-amd64/linkerd
```
On the target cluster, remove the label on the exported headless service:
```
k -n linkerd-multicluster-statefulset label svc nginx-statefulset-svc mirror.linkerd.io/exported-
```
Then see that the mirrored services got recreated:
```
$ k --context k3d-source -n linkerd-multicluster-statefulset get svc
NAME                           TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)   AGE
nginx-statefulset-svc-target   ClusterIP   None            <none>        80/TCP    6s
nginx-statefulset-0-target     ClusterIP   10.43.201.254   <none>        80/TCP    6s
```

### Logs, error output, etc

NA

### output of `linkerd check -o short`

NA

### Environment

linkerd edge-22.5.1, but this also applies to 2.11.x

### Possible solution

Have `createOrUpdateHeadlessEndpoints()` in `cluster_watcher_headless.go` handle the case when the exported label is not there.

### Would you like to work on fixing this bug?

maybe

**Comment by NeckBeardPrince** [comment]
@alpeb I also noticed that after a few hours the endpoints of the mirrored service go unhealthy and never recover. I have to delete a pod or do something to force an endpoint change to get it to go healthy again. Is there a chance this issue could be related?

**Comment by alpeb** [comment]
I haven't noticed that. Could you provide logs from the service-mirror container to see what could be going on?

**Comment by NeckBeardPrince** [comment]
> I haven't noticed that. Could you provide logs from the service-mirror container to see what could be going on?

@alpeb  Unfortunately, nothing shows up in the logs (I have debug enabled).

When I have `-enable-headless-services` enabled -

1. In one terminal pane, I'm running `watch -n10 --differences=cumulative -t 'kubectl describe endpoints rockwell-es-ingest -n observability'` which shows the two IP addresses for each pod I have running under my headless StatefulSet service. In another pane, I'm running `watch -n5 --differences -t 'dig rockwell-es-ingest-rockwell-development.observability.svc.cluster.local +short'`. This is also showing the two IP addresses under my headless service. If I restart or delete the service-mirror pod, of course the IP addresses disappear when running the `dig` command against the FQDN. But they never recover or come back, I can see the endpoint for the service is still returning the two IP addresses. If I make a change to a label or delete a pod under my service, the service-mirror seems to pick it up and everything comes back.

2. Same as everything above, except I don't delete or restart the service-mirror pod, I just leave everything running for a while. All of a sudden, the `dig` command starts to show nothing when running against the `dig rockwell-es-ingest-rockwell-development.observability.svc.cluster.local` FQDN. When this happens, the IP addresses under the endpoint are now gone, the addresses' field is blank. Like before, if I change a label or delete a pod under service, everything comes back up for some time.

None of these things happen when I have `-enable-headless-services` disabled.
