### ISSUE TITLE
Add metrics for admission control webhook success in proxy injector

### ISSUE THREAD

**Issue by MarcelMue** [linkerd/linkerd2#8510]
### What problem are you trying to solve?

It can be hard to detect if the mutating webhook served by the proxy injector is processing actions in an HA setup. 

### How should the problem be solved?

A metric could be added which reflects the amount of admission requests handled by the proxy injector.

### Any alternatives you've considered?

(I could not find if such a metric or something which serves the same usecase already exists, if yes, then this can be closed.)

### How would users interact with this feature?

Metrics would be ingested by Prometheus and processed there.

### Would you like to work on this feature?

maybe

**Comment by MarcelMue** [comment]
cc @mateiidavid as we discussed this at Kubecon and weren't certain if it already exists. I tried to find available metrics but failed to find something that fits this usecase.

**Comment by olix0r** [comment]
I'm going to close this for now, since we expose these metrics. But please let us know if these aren't sufficient for some reason!
