### ISSUE TITLE
Suggestion: don't use helm v3 `crds` dir for CRDs

### ISSUE THREAD

**Issue by m1o1** [linkerd/linkerd2#8523]
### What problem are you trying to solve?

When upgrading, helm does not upgrade CRDs on newer chart versions.
It [doesn't even add new ones](https://github.com/helm/helm/issues/6581).
This will make upgrades for linkerd difficult as upgrading the crd chart will not add new CRDs / versions of existing CRDs.

### How should the problem be solved?

In my opinion there are two good options for handling CRDs:
* Having a pre-install+pre-upgrade+pre-rollback(?) helm hook job that does `kubectl apply --server-side` for the CRDs
* Leaving it out of the chart and having users manually before upgrading do `kubectl apply` on CRDs like [kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack) does.

### Any alternatives you've considered?

In our pipelines, I'm just pulling the CRDs out of the linkerd-crds chart, extracting the yaml out and doing `kubectl apply --server-side` on them before installing/upgrading the linkerd-control-plane chart. 

### Would you like to work on this feature?

maybe

**Comment by adleong** [comment]
Hi @m1o1!  I believe the Helm issue you refer to applies to the `crds/` directory of a Helm chart.  It's for this reason that we don't use a `crds/` directory in our charts and instead have a dedicated `linkerd-crds` chart.  Upgrading this chart should add or upgrade any CRDs in the chart.

**Comment by m1o1** [comment]
Oh I was in the CRDs chart and for some reason thought there was a crds dir. Thanks for the info!
