### ISSUE TITLE
Linkerd viz shows deprecated commands?

### ISSUE THREAD

**Issue by figaw** [linkerd/linkerd2#8525]
### What is the issue?

Browsing linkerd viz, you'll sometimes come across "Current Tap query" or similar, but when I copy the command and run it in the terminal it says,

```shell
Command "tap" is deprecated, use instead 'linkerd viz tap [flags] (RESOURCE)'
```

### How can it be reproduced?

Troubleshooting the "getting started" emoji voto app, suggests on the Tap-site for the `/api/vote`-endpoint that the current query is

```
linkerd tap deployment/vote-bot --namespace emojivoto --to deployment/web --to-namespace emojivoto --path /api/vote
```

### Logs, error output, etc

```
Command "tap" is deprecated, use instead 'linkerd viz tap [flags] (RESOURCE)'
```

### output of `linkerd check -o short`

```text
Linkerd core checks
===================

linkerd-existence
-----------------
‼ cluster networks can be verified
    the following nodes do not expose a podCIDR:
        docker-desktop
    see https://linkerd.io/2.11/checks/#l5d-cluster-networks-verified for hints

Status check results are √
```

### Environment

- Kubernetes Version: `Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:32:32Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}`
- Cluster Environment: Docker for Desktop
- Host OS: Win 11
- Linkerd version: `Client version: stable-2.11.2, Server version: stable-2.11.2`

### Possible solution

It's probably just a UI thing, but I guess it should include the `viz`-part if it's deprecated?

### Would you like to work on fixing this bug?

maybe

**Comment by philnichol** [comment]
Hey 👋 looks like this should have been addressed here? https://github.com/linkerd/linkerd2/pull/7230
Might just need to upgrade the version of linkerd-viz?
