### ISSUE TITLE
Relax `Server` `proxyProtocol` validation

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#8564]
The `Server` CRD currently enumerates all possible `proxyProtocol` values:

https://github.com/linkerd/linkerd2/blob/7303846417df063279f845fbebec96b162951dc4/charts/linkerd-crds/templates/policy/server.yaml#L131-L137

Instead of hardcoding this list in an `enum` in the CRD, we should probably treat this as a general string and let the controller decide what values are acceptable.

I think we can make this change in the CRD without impacting the api version, since it's not making validation any more restrictive...

**Comment by mateiidavid** [comment]
Sounds good to me, but just a quick question on the UX around this. I think getting rid of the enum will make it easier to write `Server` resources but perhaps the failure won't be as obvious to people? 

Suppose someone puts in a string that the policy-controller won't consider a valid `proxyProtocol` value. In this case my assumption is that we'd log the failure and continue to do protocol detection; would this result in behaviour that a user wouldn't expect though? I wouldn't expect an invalid value to stop things from working, just result in silent failures that users might not be aware of. In contrast, an invalid value would stop the resource from being created in the cluster from the get-go which might mitigate this (thought at the cost of more descriptive CRDs).

Does this make sense as a concern?

**Comment by olix0r** [comment]
@mateiidavid it's worth writing a test for this, but my expectation is that the admission controller will still reject the resource if it can't read the value. This approach means that we can, for instance, ignore the case of the value or do other processing on it.
