### ISSUE TITLE
policy: `ClusterNetworkAuthentication`

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#8566]
We currently have a `NetworkAuthentication` type that is namespace-scoped. But, for the majority of network-based authentication policies, the networks are actually cluster-scoped. For instance, if we wanted to define the pod networks or networks of other clusters or kubelet IPs--all of those concerns are likely to apply across all namespaces.

We can in theory store `NetworkAuthentication` resources in the linkerd namespace and reference those from other namespaces, but I think it may be more ergonomic to have a cluster-scoped resource for these authentications.

Thoughts?

**Comment by adleong** [comment]
Is there any meaningful relationship between networks and namespaces?  Would it make sense to have `NetworkAuthenticaiton` be cluster-scoped? (or deprecate it in favor of ClusterNetworkAuthentication).  Is there a situation where a `NetworkAuthenticaion` makes sense to belong to a specific namespace?

**Comment by alpeb** [comment]
I think it still makes sense to keep `NetworkAuthentication` namespaced, for multi-tenant clusters where users wouldn't necessary have permissions to create cluster-level resources.

> We can in theory store NetworkAuthentication resources in the linkerd namespace and reference those from other namespaces

That sounds simpler to me than to have to deal with an extra cluster-level CRD :man_shrugging:
