### ISSUE TITLE
Registry flag for linkerd viz install

### ISSUE THREAD

**Issue by vikas027** [linkerd/linkerd2#8584]
### What problem are you trying to solve?

It will be great to have a `--registry` flag for command `linkerd viz install` just like we have for `linkerd install`

### How should the problem be solved?

It helps in environments where we cannot pull a public image

### Any alternatives you've considered?

Probably do some `sed` logic to prefix the images with a custom registry

### How would users interact with this feature?

```bash
linkerd viz install --registry <custom_registry>
```

### Would you like to work on this feature?

maybe

**Comment by mateiidavid** [comment]
Hey @vikas027, I think for `viz` you can make use of the Helm template flags to use whatever docker registry you want. I looked through `viz`'s values file and found:
https://github.com/linkerd/linkerd2/blob/123a152d2bad899b10f15843b6ceba3e7a0c5346/viz/charts/linkerd-viz/values.yaml#L16

If you're using the CLI, you can overwrite that value like so:

```
:; linkerd viz install --set 'defaultRegistry=dockerhub.com' | rg 'image'
        image: dockerhub.com/metrics-api:stable-2.11.2
        imagePullPolicy: IfNotPresent
        image: dockerhub.com/grafana:stable-2.11.2
        imagePullPolicy: IfNotPresent
        image: prom/prometheus:v2.19.3
        imagePullPolicy: IfNotPresent
```

Would this suffice?

**Comment by vikas027** [comment]
Yep, that's perfect 👌
