### ISSUE TITLE
Remove `Gateways` API from linkerd-viz

### ISSUE THREAD

**Issue by kleimkuhler** [linkerd/linkerd2#8630]
### What problem are you trying to solve?

The `Gateways` API was deprecated as part of 2.12 (#8600) and should be fully removed in 2.13.

### How should the problem be solved?

The API implementation should be removed.

### Any alternatives you've considered?

N/A

**Comment by alpeb** [comment]
From what I understand, the usage of this API was removed from the CLI, but it's still being used by the web component to display the Gateways section of the dashboard...
