### ISSUE TITLE
Add option to linkerd cli tool to add PSP code for K8s clusters that require NET_* capabilities

### ISSUE THREAD

**Issue by spstarr** [linkerd/linkerd2#8635]
### What problem are you trying to solve?

If you use the linkerd cli in https://linkerd.io/2.11/getting-started/, one would expect you to be able to install linkerd fully.

However, depending on whoever setup your Kubernetes cluster, you may need additional checks,

`linkerd check --pre` should have failed when NET_* capabilities we not detected.

Unable to install linkerd fully.

### How should the problem be solved?

Improve documentation, on PodSecurityPolicy (even if its deprecated its still in use...)

The helm chart you provide has enablePSP option, when I attempt to look at troubleshooting you refer to https://linkerd.io/2.11/tasks/using-psp/

but the CRD for this is for the *demo* and doesn't help me with the actual setup of linkerd itself.

### Any alternatives you've considered?

Maybe if I installed via helm chart directly not via cli?

### How would users interact with this feature?

Better check for PSP and error if it is not configured.

**Comment by adleong** [comment]
You can use the `linkerd upgrade --set enablePSP=true` option to install Linkerd control plane with PSP.

**Comment by spstarr** [comment]
That does solve it, so closing
