### ISSUE TITLE
Viz dashboard main script 404

### ISSUE THREAD

**Issue by marcusthelin** [linkerd/linkerd2#8718]
### What is the issue?

When on the dashboard homepage, the main.*.js script is loaded from `dist/main.98a8aa16917edbcb5993.js`. But when I navigate to any other page and **refresh** the page, it tries to fetch the script from `/namespaces/default/dist/main.98a8aa16917edbcb5993.js`. It, in other words, add the /namespace/* path. This results in the request responding with a 404 and the page gets blank.

### How can it be reproduced?

1. Start viz dashboard
2. Navigate to any other resource, e.g. a deployment.
3. Refresh page.

### Logs, error output, etc

/namespaces

![CleanShot 2022-06-21 at 16 04 12](https://user-images.githubusercontent.com/22647302/174819195-8983dd31-42b2-4032-9056-0a0de1d38c83.png)

/namespaces/default
![CleanShot 2022-06-21 at 16 04 49](https://user-images.githubusercontent.com/22647302/174819364-0442cf85-0390-44e2-98ed-e485ab5b1546.png)

### output of `linkerd check -o short`

```text
Linkerd core checks
===================

linkerd-existence
-----------------
‼ cluster networks can be verified
    the following nodes do not expose a podCIDR:
	ip-10-0-1-153.eu-north-1.compute.internal
	ip-10-0-2-128.eu-north-1.compute.internal
	ip-10-0-2-143.eu-north-1.compute.internal
	ip-10-0-2-160.eu-north-1.compute.internal
	ip-10-0-2-36.eu-north-1.compute.internal
	ip-10-0-3-152.eu-north-1.compute.internal
	ip-10-0-3-86.eu-north-1.compute.internal
    see https://linkerd.io/2.11/checks/#l5d-cluster-networks-verified for hints

Status check results are √

```

### Environment

- Kuberentes version: 1.21
- Environment: AWS EKS

### Would you like to work on fixing this bug?

maybe

**Comment by adleong** [comment]
Hi @marcusthelin, can you confirm what version of Linkerd this occurs on?

**Comment by alpeb** [comment]
@marcusthelin I couldn't reproduce the issue in the latest stables 2.11.1 and 2.11.2. This looks like a browser issue, although nobody else has reported this. Chrome 102 had some issues, although probably unrelated. Can you give it a try with a newer browser?
