### ISSUE TITLE
Allow disabling `lifecycle.postStart` hooks for control plane pods

### ISSUE THREAD

**Issue by lamebear** [linkerd/linkerd2#8738]
### What problem are you trying to solve?

In some circumstances, the `lifecycle.postStart` hook can cause the `linkerd-proxy` container to get stuck waiting for identity verification. After the `linkerd-await` timeout, the container is restarted and the proxy starts without further incident. This causes pod startup to be > 2 minutes. From testing, the `linkerd-proxy` can start correctly the first time without the `lifecycle.postStart` hook. The `linkerd-control-plane` chart currently has a way to disable the `lifecycle.postStart` hook for injected proxies, but no way to do so for control plane pods.

This behavior is noticed on EKS v1.21/22 with up to date `aws-vpc-cni` and `linkerd-cni`.

### How should the problem be solved?

The `linkerd-control-plane` chart can be updated to allow disabling the `lifecycle.postStart` hook for control plane proxies. This should only be used when the `linkerd-proxy` containers do not start correctly without being restarted after the `linkerd-await` timeout. This can be accomplished by adding a new value, `proxy.controlPlaneAwait`, that would disable the `lifecycle.postStart` hook on the destination and proxy-injector pods. The existing value of `proxy.await` could also be used, but that would change existing behavior and end-user's current use of the value.

### Any alternatives you've considered?

Deployments can be patched after being applied, but those deployments would need to be patched anytime the released `linkerd-control-plane` is redeployed to their environment.

### How would users interact with this feature?

Users would simply set the `proxy.controlPlaneAwait=false` if they desire to disable the `lifecycle.postStart` hook on destination and proxy-injector pods:

```
helm install linkerd/linkerd2 --set proxy.controlPlaneAwait=false ...
```

### Would you like to work on this feature?

yes

**Comment by danibaeyens** [comment]
It looks related to:
https://github.com/linkerd/linkerd2/discussions/8458

In case it is, there is a workaround working for other projects which might be interesting to adopt while upstream is fixed. It's just adding a no-op initContainer to make sure the pod sandbox receives an IP before the postStart hook.
https://github.com/openshift/cluster-network-operator/commit/cbacf6d169fef042b04d9580f37dce877cd18c96#diff-95566c5e08594ee74004728f0a4910304a230cd024f4fd102f16396c693b88ea
