### ISSUE TITLE
linkerd authz command is too slow

### ISSUE THREAD

**Issue by aatarasoff** [linkerd/linkerd2#8792]
### What problem are you trying to solve?

We have 200+ ServerAuthorizations and 250+ Server resources in the test environment.

The command below runs for more than 5 mins and looks slightly useless:

```
linkerd authz -n mynamespace deployments/my-deployment
```

### How should the problem be solved?

The reason is that there is a loop over SA, Servers, and Pods that does real calls to a K8s server.

I propose to cache resources to minimize network calls to speed the command.

### Any alternatives you've considered?

If `authz` command should work as real selector commands then I can implement it in the extension: https://github.com/aatarasoff/linkerd-easyauth

### Would you like to work on this feature?

yes

**Comment by aatarasoff** [comment]
fixed now

**Comment by wmorgan** [comment]
Nice work @aatarasoff! Thank you!
