### ISSUE TITLE
linkerd2 helm chart does not remove policyValidator.keyPEM field from configmap

### ISSUE THREAD

**Issue by ericsuhong** [linkerd/linkerd2#8823]
### What is the issue?

Linkerd2 helm chart currently has a logic to remove keyPEM fields from configmap: https://github.com/linkerd/linkerd2/blob/main/charts/linkerd-control-plane/templates/config.yaml

However, this is missing removing keyPEM field from policyValidator, which makes it visible when you specify a custom TLS cert for policy Validator.

### How can it be reproduced?

Deploy linkerd using helm chart with custom keyPEM fields:

````
step certificate create linkerd-proxy-injector.linkerd.svc linkerd-proxy-injector.crt linkerd-proxy-injector.key \
      --profile self-signed --not-after $linkerdCertExpiration --no-password --insecure --subtle --kty=RSA

step certificate create linkerd-policy-validator.linkerd.svc linkerd-policy-validator.crt linkerd-policy-validator.key \
      --profile self-signed --not-after $linkerdCertExpiration --no-password --insecure --subtle --kty=RSA 

helm upgrade --install --atomic --wait --timeout 90m linkerd2 linkerd/linkerd2 \
      --set-file proxyInjector.crtPEM=linkerd-proxy-injector.crt \
      --set-file proxyInjector.keyPEM=linkerd-proxy-injector.key \
      --set-file policyValidator.crtPEM=linkerd-policy-validator.crt \
      --set-file policyValidator.keyPEM=linkerd-policy-validator.key

kubectl get configmap linkerd-config -n linkerd -o yaml

=> keyPEM is removed for proxyInjector, but still visible for policyValidator.
````

### Logs, error output, etc

Sample configMap:
````
policyValidator:
      ....
      keyPEM: "SECRET VISIBLE"
      ....
````

### output of `linkerd check -o short`

N/A

### Environment

linkerd 2.11.2

### Possible solution

Add this section
````
{{- if kindIs "map" $values.policyValidator-}}
    {{- $_ := unset $values.policyValidator "keyPEM"}}
  {{- end -}}
````
into config.yaml in helm chart here: https://github.com/linkerd/linkerd2/blob/main/charts/linkerd-control-plane/templates/config.yaml

**Comment by ericsuhong** [comment]
@kleimkuhler @adleong Since this bug is a security-related issue, can we get a new minor linkerd release that includes this fix as soon as possible? It will block us from upgrading linkerd version.

**Comment by kleimkuhler** [comment]
Yes we'll be releasing 2.11.4 to patch this within the next few days.
