### ISSUE TITLE
multicluster: Provide High Availability mode for service-mirror component

### ISSUE THREAD

**Issue by kleimkuhler** [linkerd/linkerd2#8848]
### What problem are you trying to solve?

#7186 added HA mode for linkerd-multicluster's gateway component. We should investigate what is required for the service-mirror to also operate in HA mode.

### How should the problem be solved?

The service-mirror was not designed to handle multiple service-mirror's watching the same cluster and keeping the local one mirrored correctly. Rather than just increasing the `replicas` configuration, we should look into leader election and see if they work well together.

### Any alternatives you've considered?

Not right now but this should be part of the consideration.

**Comment by knutgoetz** [comment]
Hey there, looks like most of the work was done by @mateiidavid in https://github.com/linkerd/linkerd2/pull/11047 or am I mistaken? Maybe this can be closed? Anyway let me know if I can help. And thx @mateiidavid!

**Comment by mateiidavid** [comment]
Thanks @knutgoetz! Seems that I forgot to link it against the PR. It can be closed! :)
