### ISSUE TITLE
Proxy Timeout configuration doesn't work with nginx ingress controller

### ISSUE THREAD

**Issue by pppizarro** [linkerd/linkerd2#8867]
### What is the issue?

Hi there! I'm currently having issues with proxy timeouts. We have a service that receives a lot of data and the request can last for a bit longer than 20s. However, the default value appears to be 10s and there's no straightforward way to set that incoming connections timeout without managing service profiles.

We're using nginx ingress, and the controller has been meshed with the annotation "[linkerd.io/inject](http://linkerd.io/inject): enabled", both our service and the ingress controller are injected properly. We tried manually creating a service profile but there were no matches in the tap output as there were no rt_route field, so we tried the service profile auto generation approach from tap. Even though the service profile was generated by linkerd from the incoming traffic read from tap, it's still unable to match the routes, hence unable to set the timeouts accordingly.
I also searched in this slack for the keyword "route" and it seems to be a common issue, however I tried several of the proposed solutions to previous posters without success.

We are using the ingress annotation: 

- [nginx.ingress.kubernetes.io/service-upstream](http://nginx.ingress.kubernetes.io/service-upstream): "true"

We also tried running linkerd check --proxy and everything seems to be fine.

### How can it be reproduced?

I created a simple meshed pod with curl in it, to perform a request against my service.
The service profile for our service:
```
apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  name: cost-api.cost-management.svc.cluster.local
  namespace: cost-management
spec:
  routes:
  - condition:
      method: GET
      pathRegex: /actuator
    name: GET /actuator
  - condition:
      method: GET
      pathRegex: /actuator/health
    name: GET /actuator/health
```

### Logs, error output, etc

Tap output
`req id=5:3 proxy=in  src=10.203.32.39:40702 dst=10.203.32.38:8080 tls=true :method=GET :authority=cost-api.cost-management.svc.cluster.local :path=/actuator`
Curl request

- curl [http://cost-api.cost-management.svc.cluster.local:80/actuator](http://cost-api.cost-management.svc.cluster.local/actuator)

### output of `linkerd check -o short`

Linkerd core checks
===================

linkerd-webhooks-and-apisvc-tls
-------------------------------
‼ proxy-injector cert is valid for at least 60 days
    certificate will expire on 2022-07-14T04:14:25Z
    see https://linkerd.io/2.11/checks/#l5d-proxy-injector-webhook-cert-not-expiring-soon for hints
‼ sp-validator cert is valid for at least 60 days
    certificate will expire on 2022-07-14T04:14:25Z
    see https://linkerd.io/2.11/checks/#l5d-sp-validator-webhook-cert-not-expiring-soon for hints
‼ policy-validator cert is valid for at least 60 days
    certificate will expire on 2022-07-14T04:14:25Z
    see https://linkerd.io/2.11/checks/#l5d-policy-validator-webhook-cert-not-expiring-soon for hints

control-plane-version
---------------------
‼ control plane is up-to-date
    is running version 2.11.2 but the latest stable version is 2.11.3
    see https://linkerd.io/2.11/checks/#l5d-version-control for hints
‼ control plane and cli versions match
    control plane running stable-2.11.2 but cli running stable-2.11.3
    see https://linkerd.io/2.11/checks/#l5d-version-control for hints

linkerd-control-plane-proxy
---------------------------
‼ control plane proxies are up-to-date
    some proxies are not running the current version:
	* linkerd-destination-6cc85dd6bf-x56fr (stable-2.11.2)
	* linkerd-identity-5cbdcf64db-kbwzv (stable-2.11.2)
	* linkerd-proxy-injector-74b7f64cb8-ft472 (stable-2.11.2)
    see https://linkerd.io/2.11/checks/#l5d-cp-proxy-version for hints
‼ control plane proxies and cli versions match
    linkerd-destination-6cc85dd6bf-x56fr running stable-2.11.2 but cli running stable-2.11.3
    see https://linkerd.io/2.11/checks/#l5d-cp-proxy-cli-version for hints

Linkerd extensions checks
=========================

linkerd-viz
-----------
‼ tap API server cert is valid for at least 60 days
    certificate will expire on 2022-07-14T04:14:26Z
    see https://linkerd.io/2.11/checks/#l5d-tap-cert-not-expiring-soon for hints
‼ viz extension proxies are up-to-date
    some proxies are not running the current version:
	* grafana-6c76bcfdb6-k6sfx (stable-2.11.2)
	* metrics-api-74f4d6f76b-mkdc9 (stable-2.11.2)
	* prometheus-6976585447-q6rd7 (stable-2.11.2)
	* tap-59b5c7ff4b-ptz89 (stable-2.11.2)
	* tap-injector-689c67b6d5-sc4gf (stable-2.11.2)
	* web-665c567599-spphc (stable-2.11.2)
    see https://linkerd.io/2.11/checks/#l5d-viz-proxy-cp-version for hints
‼ viz extension proxies and cli versions match
    grafana-6c76bcfdb6-k6sfx running stable-2.11.2 but cli running stable-2.11.3
    see https://linkerd.io/2.11/checks/#l5d-viz-proxy-cli-version for hints

Status check results are √

### Environment

- Kubernetes Version: v1.21.12-gke.1500
- Cluster Environment: GKE
- Host OS: linux/amd64 - Container-Optimized OS with Docker (cos)
- Linkerd Version: stable-2.11.2

Another relevant info
- Nginx Version: nginx/1.19.9

### Additional context

Found another thread where Matei David (Linkerd Slack) helped someone else by asking them to set the origin's proxy log level to debug,warn and dump the output after doing grep by the service's ip:

1. [  1465.900930s] DEBUG ThreadId(01) accept{client.addr=10.203.32.39:55852}:server{orig_dst=10.203.2.24:80}: linkerd_cache: Caching new service target=Accept { orig_dst: OrigDstAddr(10.203.2.24:80), protocol: () }
2. [  1465.901054s] DEBUG ThreadId(01) accept{client.addr=10.203.32.39:55852}:server{orig_dst=10.203.2.24:80}:profile: linkerd_app_outbound::discover: Allowing profile lookup
3. [  1465.901101s] DEBUG ThreadId(01) accept{client.addr=10.203.32.39:55852}:server{orig_dst=10.203.2.24:80}: linkerd_stack::failfast: TCP Server service has become unavailable
4. [  1465.907435s] DEBUG ThreadId(01) accept{client.addr=10.203.32.39:55852}:server{orig_dst=10.203.2.24:80}:profile: linkerd_service_profiles::client: Resolved profile
5. [  1465.907464s] DEBUG ThreadId(01) accept{client.addr=10.203.32.39:55852}:server{orig_dst=10.203.2.24:80}:profile: linkerd_app_outbound::switch_logical: Profile describes a logical service
6. [  1465.907470s] DEBUG ThreadId(01) accept{client.addr=10.203.32.39:55852}:server{orig_dst=10.203.2.24:80}:profile: linkerd_app_outbound::http::detect: Attempting HTTP protocol detection
7. [  1465.907918s] DEBUG ThreadId(01) accept{client.addr=10.203.32.39:55852}:server{orig_dst=10.203.2.24:80}:profile: linkerd_detect: DetectResult protocol=Some(Http1) elapsed=16.913µs
8. [  1465.907954s] DEBUG ThreadId(01) accept{client.addr=10.203.32.39:55852}:server{orig_dst=10.203.2.24:80}:profile:http{v=1.x}: linkerd_proxy_http::server: Creating HTTP service version=Http1
9. [  1465.907974s] DEBUG ThreadId(01) accept{client.addr=10.203.32.39:55852}:server{orig_dst=10.203.2.24:80}:profile:http{v=1.x}:logical{dst=cost-api.cost-management.svc.cluster.local:80}: linkerd_cache: Caching new service target=Logical { protocol: Http1, profile: .., logical_addr: LogicalAddr(cost-api.cost-management.svc.cluster.local:80) }
10. [  1465.908021s] DEBUG ThreadId(01) accept{client.addr=10.203.32.39:55852}:server{orig_dst=10.203.2.24:80}:profile:http{v=1.x}: linkerd_proxy_http::server: Handling as HTTP version=Http1
11. [  1465.908109s] DEBUG ThreadId(01) accept{client.addr=10.203.32.39:55852}:server{orig_dst=10.203.2.24:80}:profile:http{v=1.x}:logical{dst=cost-api.cost-management.svc.cluster.local:80}: linkerd_service_profiles::http::service: Updating HTTP routes routes=3
12. [  1465.908310s] DEBUG ThreadId(01) accept{client.addr=10.203.32.39:55852}:server{orig_dst=10.203.2.24:80}:profile:http{v=1.x}:logical{dst=cost-api.cost-management.svc.cluster.local:80}: linkerd_service_profiles::split: Updating targets=[Target { addr: cost-api-primary.cost-management.svc.cluster.local:80, weight: 1000000 }]
13. [  1465.908340s] DEBUG ThreadId(01) accept{client.addr=10.203.32.39:55852}:server{orig_dst=10.203.2.24:80}:profile:http{v=1.x}:logical{dst=cost-api.cost-management.svc.cluster.local:80}:concrete{addr=cost-api-primary.cost-management.svc.cluster.local:80}: linkerd_proxy_api_resolve::resolve: Resolving dst=cost-api-primary.cost-management.svc.cluster.local:80 context={"ns":"nginx", "nodeName":"gke-k8s-fal-corp-mrc-np-k8s-fal-corp--d14c18be-5noc"}
14. [  1465.908393s] DEBUG ThreadId(01) accept{client.addr=10.203.32.39:55852}:server{orig_dst=10.203.2.24:80}:profile:http{v=1.x}:logical{dst=cost-api.cost-management.svc.cluster.local:80}: linkerd_stack::failfast: HTTP Logical service has become unavailable
15. [  1465.913362s] DEBUG ThreadId(01) accept{client.addr=10.203.32.39:55852}:server{orig_dst=10.203.2.24:80}:profile:http{v=1.x}:logical{dst=cost-api.cost-management.svc.cluster.local:80}:concrete{addr=cost-api-primary.cost-management.svc.cluster.local:80}: linkerd_stack::failfast: HTTP Balancer service has become unavailable
16. [  1465.913433s] DEBUG ThreadId(01) accept{client.addr=10.203.32.39:55852}:server{orig_dst=10.203.2.24:80}:profile:http{v=1.x}:logical{dst=cost-api.cost-management.svc.cluster.local:80}:concrete{addr=cost-api-primary.cost-management.svc.cluster.local:80}: linkerd_proxy_api_resolve::resolve: Add endpoints=2
17. [  1465.913449s] DEBUG ThreadId(01) accept{client.addr=10.203.32.39:55852}:server{orig_dst=10.203.2.24:80}:profile:http{v=1.x}:logical{dst=cost-api.cost-management.svc.cluster.local:80}:concrete{addr=cost-api-primary.cost-management.svc.cluster.local:80}: linkerd_proxy_discover::from_resolve: Changed change=Insert(10.203.37.35:8080, Endpoint { addr: Remote(ServerAddr(10.203.37.35:8080)), tls: Some(ClientTls { server_id: ServerId(Name("cm-workload-identity.cost-management.serviceaccount.identity.linkerd.cluster.local")), alpn: None }), metadata: Metadata { labels: {"control_plane_ns": "linkerd", "deployment": "cost-api-primary", "namespace": "cost-management", "pod": "cost-api-primary-7bb4cd86fb-l5cx8", "pod_template_hash": "7bb4cd86fb", "service": "cost-api-primary", "serviceaccount": "cm-workload-identity"}, protocol_hint: Http2, opaque_transport_port: None, identity: Some(ServerId(Name("cm-workload-identity.cost-management.serviceaccount.identity.linkerd.cluster.local"))), authority_override: None }, logical_addr: Some(LogicalAddr(cost-api.cost-management.svc.cluster.local:80)), protocol: Http1, opaque_protocol: false })
18. [  1465.913510s] DEBUG ThreadId(01) accept{client.addr=10.203.32.39:55852}:server{orig_dst=10.203.2.24:80}:profile:http{v=1.x}:logical{dst=cost-api.cost-management.svc.cluster.local:80}:concrete{addr=cost-api-primary.cost-management.svc.cluster.local:80}: linkerd_proxy_discover::from_resolve: Changed change=Insert(10.203.32.38:8080, Endpoint { addr: Remote(ServerAddr(10.203.32.38:8080)), tls: Some(ClientTls { server_id: ServerId(Name("cm-workload-identity.cost-management.serviceaccount.identity.linkerd.cluster.local")), alpn: None }), metadata: Metadata { labels: {"control_plane_ns": "linkerd", "deployment": "cost-api-primary", "namespace": "cost-management", "pod": "cost-api-primary-7bb4cd86fb-2vpkc", "pod_template_hash": "7bb4cd86fb", "service": "cost-api-primary", "serviceaccount": "cm-workload-identity"}, protocol_hint: Http2, opaque_transport_port: None, identity: Some(ServerId(Name("cm-workload-identity.cost-management.serviceaccount.identity.linkerd.cluster.local"))), authority_override: None }, logical_addr: Some(LogicalAddr(cost-api.cost-management.svc.cluster.local:80)), protocol: Http1, opaque_protocol: false })
19. [  1465.913559s] DEBUG ThreadId(01) accept{client.addr=10.203.32.39:55852}:server{orig_dst=10.203.2.24:80}:profile:http{v=1.x}:logical{dst=cost-api.cost-management.svc.cluster.local:80}:concrete{addr=cost-api-primary.cost-management.svc.cluster.local:80}:endpoint{server.addr=10.203.37.35:8080}: linkerd_reconnect: Disconnected backoff=false
20. [  1465.913566s] DEBUG ThreadId(01) accept{client.addr=10.203.32.39:55852}:server{orig_dst=10.203.2.24:80}:profile:http{v=1.x}:logical{dst=cost-api.cost-management.svc.cluster.local:80}:concrete{addr=cost-api-primary.cost-management.svc.cluster.local:80}:endpoint{server.addr=10.203.37.35:8080}: linkerd_reconnect: Creating service backoff=false
21. [  1465.913573s] DEBUG ThreadId(01) accept{client.addr=10.203.32.39:55852}:server{orig_dst=10.203.2.24:80}:profile:http{v=1.x}:logical{dst=cost-api.cost-management.svc.cluster.local:80}:concrete{addr=cost-api-primary.cost-management.svc.cluster.local:80}:endpoint{server.addr=10.203.37.35:8080}: linkerd_proxy_http::client: Building HTTP client settings=OrigProtoUpgrade
22. [  1465.913588s] DEBUG ThreadId(01) accept{client.addr=10.203.32.39:55852}:server{orig_dst=10.203.2.24:80}:profile:http{v=1.x}:logical{dst=cost-api.cost-management.svc.cluster.local:80}:concrete{addr=cost-api-primary.cost-management.svc.cluster.local:80}:endpoint{server.addr=10.203.37.35:8080}: linkerd_tls::client: Initiating TLS connection server.id=cm-workload-identity.cost-management.serviceaccount.identity.linkerd.cluster.local
23. [  1465.913596s] DEBUG ThreadId(01) accept{client.addr=10.203.32.39:55852}:server{orig_dst=10.203.2.24:80}:profile:http{v=1.x}:logical{dst=cost-api.cost-management.svc.cluster.local:80}:concrete{addr=cost-api-primary.cost-management.svc.cluster.local:80}:endpoint{server.addr=10.203.37.35:8080}: linkerd_proxy_transport::connect: Connecting server.addr=10.203.37.35:8080
24. [  1465.913748s] DEBUG ThreadId(01) accept{client.addr=10.203.32.39:55852}:server{orig_dst=10.203.2.24:80}:profile:http{v=1.x}:logical{dst=cost-api.cost-management.svc.cluster.local:80}:concrete{addr=cost-api-primary.cost-management.svc.cluster.local:80}:endpoint{server.addr=10.203.32.38:8080}: linkerd_reconnect: Disconnected backoff=false
25. [  1465.913760s] DEBUG ThreadId(01) accept{client.addr=10.203.32.39:55852}:server{orig_dst=10.203.2.24:80}:profile:http{v=1.x}:logical{dst=cost-api.cost-management.svc.cluster.local:80}:concrete{addr=cost-api-primary.cost-management.svc.cluster.local:80}:endpoint{server.addr=10.203.32.38:8080}: linkerd_reconnect: Creating service backoff=false
26. [  1465.913767s] DEBUG ThreadId(01) accept{client.addr=10.203.32.39:55852}:server{orig_dst=10.203.2.24:80}:profile:http{v=1.x}:logical{dst=cost-api.cost-management.svc.cluster.local:80}:concrete{addr=cost-api-primary.cost-management.svc.cluster.local:80}:endpoint{server.addr=10.203.32.38:8080}: linkerd_proxy_http::client: Building HTTP client settings=OrigProtoUpgrade
27. [  1465.913783s] DEBUG ThreadId(01) accept{client.addr=10.203.32.39:55852}:server{orig_dst=10.203.2.24:80}:profile:http{v=1.x}:logical{dst=cost-api.cost-management.svc.cluster.local:80}:concrete{addr=cost-api-primary.cost-management.svc.cluster.local:80}:endpoint{server.addr=10.203.32.38:8080}: linkerd_tls::client: Initiating TLS connection server.id=cm-workload-identity.cost-management.serviceaccount.identity.linkerd.cluster.local
28. [  1465.913789s] DEBUG ThreadId(01) accept{client.addr=10.203.32.39:55852}:server{orig_dst=10.203.2.24:80}:profile:http{v=1.x}:logical{dst=cost-api.cost-management.svc.cluster.local:80}:concrete{addr=cost-api-primary.cost-management.svc.cluster.local:80}:endpoint{server.addr=10.203.32.38:8080}: linkerd_proxy_transport::connect: Connecting server.addr=10.203.32.38:8080
29. [  1465.915301s] DEBUG ThreadId(01) accept{client.addr=10.203.32.39:55852}:server{orig_dst=10.203.2.24:80}:profile:http{v=1.x}:logical{dst=cost-api.cost-management.svc.cluster.local:80}:concrete{addr=cost-api-primary.cost-management.svc.cluster.local:80}:endpoint{server.addr=10.203.32.38:8080}:h2: linkerd_proxy_transport::connect: Connected local.addr=10.203.32.39:50458 keepalive=Some(10s)
30. [  1465.915519s] DEBUG ThreadId(01) accept{client.addr=10.203.32.39:55852}:server{orig_dst=10.203.2.24:80}:profile:http{v=1.x}:logical{dst=cost-api.cost-management.svc.cluster.local:80}:concrete{addr=cost-api-primary.cost-management.svc.cluster.local:80}:endpoint{server.addr=10.203.37.35:8080}:h2: linkerd_proxy_transport::connect: Connected local.addr=10.203.32.39:32948 keepalive=Some(10s)
31. [  1465.917809s] DEBUG ThreadId(01) accept{client.addr=10.203.32.39:55852}:server{orig_dst=10.203.2.24:80}:profile:http{v=1.x}:logical{dst=cost-api.cost-management.svc.cluster.local:80}:concrete{addr=cost-api-primary.cost-management.svc.cluster.local:80}:endpoint{server.addr=10.203.32.38:8080}:h2: linkerd_transport_metrics::client: client connection open
32. [  1465.919060s] DEBUG ThreadId(01) accept{client.addr=10.203.32.39:55852}:server{orig_dst=10.203.2.24:80}:profile:http{v=1.x}:logical{dst=cost-api.cost-management.svc.cluster.local:80}:concrete{addr=cost-api-primary.cost-management.svc.cluster.local:80}:endpoint{server.addr=10.203.37.35:8080}:h2: linkerd_transport_metrics::client: client connection open
33. [  1465.919206s] DEBUG ThreadId(01) accept{client.addr=10.203.32.39:55852}:server{orig_dst=10.203.2.24:80}:profile:http{v=1.x}:logical{dst=cost-api.cost-management.svc.cluster.local:80}:concrete{addr=cost-api-primary.cost-management.svc.cluster.local:80}:endpoint{server.addr=10.203.32.38:8080}: linkerd_reconnect: Connected
34. [  1465.919234s] DEBUG ThreadId(01) accept{client.addr=10.203.32.39:55852}:server{orig_dst=10.203.2.24:80}:profile:http{v=1.x}:logical{dst=cost-api.cost-management.svc.cluster.local:80}:concrete{addr=cost-api-primary.cost-management.svc.cluster.local:80}:endpoint{server.addr=10.203.37.35:8080}: linkerd_reconnect: Connected

**Comment by adleong** [comment]
Hi @pppizarro!  Linkerd does not enforce any default timeout if there is not a service profile configured for a service.  Here's an example of traffic between two mesh pods where the service is configured with a 15s delay:

```console
/ # time curl bb:9090
{"requestUID":"in:http-sid:terminus-grpc:-1-h1:9090-683026315","payload":"BANANA"}
real  0m 15.02s
user    0m 0.00s
sys     0m 0.00s
```

Can you provide more details about exactly what you're seeing and why you think it's a proxy timeout?

**Comment by pppizarro** [comment]
Hi @adleong and thanks for your answer!
Sorry but we were the problem all this time. We are using a GCP HTTP Load Balancer with a 10s timeout.
We tried to bypass that LB using port-forward and that worked, so we checked our LB configuration and we found it.

Hopefully this help someone in the future

Thank you so much @adleong !
