### ISSUE TITLE
policy: Ensure routes have a deterministic order

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#8946]
When there are multiple equivalent routes (e.g., two routes with the same match), the proxy will use the first route in the returned list. We need to ensure that the policy controller returns routes in a deterministic order--and the Gateway API defines such an order:

> If ties still exist across multiple Routes, matching precedence MUST be
> determined in order of the following criteria, continuing on ties:
>
> * The oldest Route based on creation timestamp.
> * The Route appearing first in alphabetical order by
>   "{namespace}/{name}".

The policy controller should order route resources in API responses so that they are ordered to satisfy this constraint.

**Comment by hawkw** [comment]
I have this mostly done, need to write some tests before I open a PR for it, though.
