### ISSUE TITLE
error: a container name must be specified for pod 7bcdd7ccb6-s8tm4, choose one of: [linkerd-proxy ] or one of the init containers: [linkerd-init]

### ISSUE THREAD

**Issue by manhtd98** [linkerd/linkerd2#9001]
### What is the issue?

I cannot create load balancer grpc protocols on K8S

### How can it be reproduced?

I use linkerd to load balancer GRPC protocols
```
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
```

### Logs, error output, etc

error: a container name must be specified for pod triton-triton-inference-server-7bcdd7ccb6-s8tm4, choose one of: [linkerd-proxy triton-inference-server] or one of the init containers: [linkerd-init]

### output of `linkerd check -o short`

Linkerd core checks
===================

linkerd-existence
-----------------
‼ cluster networks can be verified
    the following nodes do not expose a podCIDR:
        ip-192-168-165-255.ap-southeast-1.compute.internal
        ip-192-168-175-189.ap-southeast-1.compute.internal
        ip-192-168-201-96.ap-southeast-1.compute.internal
        ip-192-168-205-238.ap-southeast-1.compute.internal
    see https://linkerd.io/2.11/checks/#l5d-cluster-networks-verified for hints

Status check results are √

### Environment

K8S
Amazon Linux 2

**Comment by mateiidavid** [comment]
@manhtd98 I don't understand the problem here, do you mind expanding?

**Comment by manhtd98** [comment]
i deploy my container and add linkerd as load balancer 
i got error:
```
error: a container name must be specified for pod triton-triton-inference-server-7bcdd7ccb6-s8tm4, choose one of: [linkerd-proxy triton-inference-server] or one of the init containers: [linkerd-init]
```

**Comment by mateiidavid** [comment]
That doesn't seem to be a Kubernetes error. I'm not sure what you're trying to do there, but the error message indicates whatever tool you're using (presumably `kubectl`) requires you to specify the container name. This is not a Linkerd thing, it's a Kubernetes thing. Once a pod has more than one container, you need to specify which container you want to interact with.

```
$ kubectl logs triton-triton-inference-server-7bcdd7ccb6-s8tm4 triton-inference-server
$ kubectl exec triton-triton-inference-server-7bcdd7ccb6-s8tm4 -c linkerd-proxy
```

**Comment by mateiidavid** [comment]
@manhtd98 I'm going to go ahead and close this issue for now :) If you run into any more problems, feel free to raise another issue or to open a discussion. Thanks!
