### ISSUE TITLE
Use client-go types in `pkg/charts/linkerd2/values.go`

### ISSUE THREAD

**Issue by mateiidavid** [linkerd/linkerd2#9006]
Linkerd CLI uses untyped values for certain fields, such as `nodeAffinity`, `deploymentStrategy` and `tolerations`. 

https://github.com/linkerd/linkerd2/blob/main/pkg/charts/linkerd2/values.go#L28

For extra type safety, we could leverage upstream (Kubernetes) types. This has the advantage of surfacing type errors early on when rendering manifests, and reduces the risk of deserialization errors in the injector as noticed in https://github.com/linkerd/linkerd2/pull/8992. 

For an example of upstream types, see [DeploymentStrategy](https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/pkg/apis/apps/types.go#L365-L377) and [Toleration](https://github.com/kubernetes/api/blob/v0.24.3/core/v1/types.go#L3007). To contrast, the CLI uses untyped values for both of these (usually `interface{}`).

@adleong's thoughtful [comment](https://github.com/linkerd/linkerd2/pull/8992#discussion_r930326944) in PR#8992 expresses some of the tradeoffs of making this change.

**Comment by olix0r** [comment]
I'm open to this, but we have to be sensitive to MSKV--probably pinning our client-go versions. Honestly, we probably need to do that anyway...
