### ISSUE TITLE
Vulnerabilities reported for linkerD images at ECR scan

### ISSUE THREAD

**Issue by Vamsi0473** [linkerd/linkerd2#9017]
### What is the issue?

We are trying to uprade linkerD from 2.9.5 to 2.11.2 version in this process we have downloaded following images and pushed to AWS ECR repo
cr.l5d.io/linkerd/policy-controller:stable-2.11.2
cr.l5d.io/linkerd/controller:stable-2.11.2
cr.l5d.io/linkerd/proxy:stable-2.11.2
cr.l5d.io/linkerd/proxy-init:v1.5.3
 Unfortunately we encountered following critical and high vulnerabilities upon scanning the images at AWS ECR repo
For proxy-init:v1.5.3
<img width="771" alt="linkerd-proxy-init-vulnerabilities" src="https://user-images.githubusercontent.com/46375277/181310825-1b59caea-dae0-445a-9a6b-66c2986df347.PNG">
For proxy-stable-2.11.2
![image](https://user-images.githubusercontent.com/46375277/181311024-8c64fe80-65a3-4b98-89fd-275cb0a7acb2.png)
For proxy-controller-stable-2.11.2
![image](https://user-images.githubusercontent.com/46375277/181311129-2bf47d5a-6e43-4acb-b9df-c03d80d84c9d.png)
This is blocking us from getting required approvals from our corporate security team and unable to uprade linkerD

### How can it be reproduced?

Download the images and push to ECR for scan

### Logs, error output, etc

Attached the vulnerabilities

### output of `linkerd check -o short`

trying to update linkerD

### Environment

Dev

**Comment by olix0r** [comment]
I recommend trying the most recent Linkerd stable release, 2.11.4

**Comment by Vamsi0473** [comment]
@olix0r  thank you for your reply I tried 2.11.4 and I see no vulnerabilities in initial scan but still I can see vulnerabilities for proxy-init:v1.6.2 as below 
![image](https://user-images.githubusercontent.com/46375277/181785378-55f5f9e0-b83c-417d-9c7e-625cd708f91d.png)

**Comment by Vamsi0473** [comment]
Hi,
Can someone please help in resolving these vulnerabilities that I have mentioned above with respect to linkerd proxy-init:v1.6.2 image

**Comment by olix0r** [comment]
@Vamsi0473 we'll do another proxy-init release as we prepare for the upcoming stable-2.12 release, or you're welcome to build your own image from https://github.com/linkerd/linkerd2-proxy-init/blob/main/Dockerfile if it's urgent.

We generally don't consider base image vulnerabilities to be urgent unless the impacted dependencies are actively used in Linkerd. In this case, the proxy-init containers are not impacted by these issues.

**Comment by olix0r** [comment]
Fixed by https://github.com/linkerd/linkerd2/pull/9179
