### ISSUE TITLE
Mesh view of namespace not allways showing

### ISSUE THREAD

**Issue by FellowFellow** [linkerd/linkerd2#9127]
### What is the issue?

The Mesh-view when accessing the namespaces is not showing for all of my custom namespaces. 

This view is not shoing for my namespace. All of the pods in the namespace are connected to linkerd just the view is missing
![linkerd-mesh](https://user-images.githubusercontent.com/74979180/183914777-436d5af0-41e9-40dc-85eb-b2ea824b5573.png)

My namespace
![linkerd](https://user-images.githubusercontent.com/74979180/183915005-766c2c4c-2673-47ae-ba96-ecfc81637ec8.png)

### How can it be reproduced?

Create a custom namespace and add some pods, it seems to vary by the namespace. Sometimes it shows sometimes it doesn't

### Logs, error output, etc

Not sure if these are relevant but these poped up in the web container after some time 

```
web time="2022-08-10T13:37:25Z" level=error msg="Post \"http://metrics-api.linkerd-viz.svc.cluster.local:8085/api/v1/StatSummary\": context canceled"
linkerd-proxy [525856.427435s]  INFO ThreadId(01) inbound: linkerd_app_core::serve: Connection closed error=connection closed before message completed client.addr=10.244.0.165:50030
linkerd-proxy [525856.427868s]  INFO ThreadId(01) outbound: linkerd_app_core::serve: Connection closed error=connection closed before message completed client.addr=10.244.0.101:41610
web time="2022-08-10T13:37:25Z" level=error msg="Post \"http://metrics-api.linkerd-viz.svc.cluster.local:8085/api/v1/StatSummary\": context canceled"
web time="2022-08-10T13:37:25Z" level=error msg="Get \"https://10.245.0.1:443/api/v1/namespaces?labelSelector=linkerd.io%2Fextension\": context canceled"
linkerd-proxy [525856.649520s]  INFO ThreadId(01) inbound: linkerd_app_core::serve: Connection closed error=connection closed before message completed client.addr=10.244.0.165:50028
linkerd-proxy [525856.649679s]  INFO ThreadId(01) inbound: linkerd_app_core::serve: Connection closed error=connection closed before message completed client.addr=10.244.0.165:42710
linkerd-proxy [525856.650261s]  INFO ThreadId(01) outbound: linkerd_app_core::serve: Connection closed error=connection closed before message completed client.addr=10.244.0.101:53190
```

### output of `linkerd check -o short`
```
Linkerd core checks
===================

linkerd-existence
-----------------
‼ cluster networks can be verified
    the following nodes do not expose a podCIDR:
        default-c9gpf
        dev-c9gpo
        dev-c9gpx
        dev-c9gpy
        stage-73pnc
    see https://linkerd.io/2.11/checks/#l5d-cluster-networks-verified for hints

Status check results are √
```

### Environment

- k8s Version: Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.9", GitCommit:"c1de2d70269039fe55efb98e737d9a29f9155246", GitTreeState:"clean", BuildDate:"2022-07-13T14:19:57Z", GoVersion:"go1.17.11", Compiler:"gc", Platform:"linux/amd64"}
- linkerd Version: stable-2.11.4
- cluster hoster: DigitalOcean

### Would you like to work on fixing this bug?

maybe

**Comment by olix0r** [comment]
The screenshot you share shows the workloads having <1RPS, which I'm assuming is healthchecks/probes. I would expect that the graph views are dependent on there being recent inter-pod communication.

**Comment by aatarasoff** [comment]
@olix0r looking at the errors like this:
```
web time="2022-08-10T13:37:25Z" level=error msg="Post \"http://metrics-api.linkerd-viz.svc.cluster.local:8085/api/v1/StatSummary\": context canceled"
```
I bet that the issue is that the Prometheus backend cannot process requests before timeout comes.

We see similar behavior if a namespace has a lot of PODs. Also, we've migrated to Victoria Metrics and reduced the cardinality of some metrics to improve the speed and stability of viz.
