### ISSUE TITLE
linkerd-destination - context deadline exceeded

### ISSUE THREAD

**Issue by VladoPortos** [linkerd/linkerd2#9128]
### What is the issue?

Hello,

I have installed Linkerd + Linkerd Viz on my kubernetes k3s cluster, made out of 7x Rpi4. Everything went smooth, no issues. But recently I get notification from monitoring like this:

```
Liveness probe failed: Get "http://10.42.2.122:9997/ping": context deadline exceeded (Client.Timeout exceeded while awaiting headers

or

Readiness probe failed: Get "http://10.42.2.122:9990/ready": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

From `linkerd-destination` not sure how to deal with it. Maybe it's just slowness of the rpis ? Its kind of annoying getting these messages 5 to 10times a day.

### How can it be reproduced?

Not sure, it just come up at random times.

### Logs, error output, etc

No logs that i can see ( looking in Argo CD into the 3 containers, linkerd-proxy-injector, linkerd-destination, linkerd-identity)

### output of `linkerd check -o short`

```text
root@control01:~# linkerd check -o short
Status check results are √
root@control01:~# 
```

### Environment

- Kubernetes: v1.23.6+k3s1
- k3s
- Host: DietPi
- Linkerd: stable-2.11.4

### Possible solution

Perhaps extend the probe time ? Not sure.

**Comment by olix0r** [comment]
Linkerd doesn't configure a probe timeout, so you're hitting the kubelet's default timeout of 1s. This should be more than enough time for node-local communication in most environments, but it's possible you're hitting CPU contention on a small RPI cluster... Normally I'd recommend using CPU requests to ensure that Linkerd components have enough resources to operate correctly, but this may make the control plane unschedulable for you. If you really need the probe timeout to be configurable, we may accept a pull request to support this, but I would expect that you're likely to hit other problems if the system is so constrained that probe requests take >1s.

**Comment by VladoPortos** [comment]
Thanks @olix0r I checked the nodes where the pods are running, CPU is normal hardly over 10% usage. However, I noticed `Undervoltage detected!` in dmesg, this very well might be the issue. I will add more juice to the nodes and see if that helps.
