### ISSUE TITLE
Investigate the `TokenRequest` API for multicluster

### ISSUE THREAD

**Issue by mateiidavid** [linkerd/linkerd2#9142]
### Background

In #9033 we looked at an issue with running the multicluster extension on the latest stable version of Kubernetes `v1.24`. Users were unable to install multicluster due to a missing ServiceAccount token, necessary to establish remote k8s clientsets when linking clusters together. As of Kubernetes `v1.24`, ServiceAccount tokens are __no longer automatically generated__. 

Our short-term approach is to create a Secret of the `service account token` type. When this Secret is associated to our ServiceAccount (through a Kubernetes specific annotation), the token controller __will__ generate a token. The token can be used successfully, however, this has the downside of creating a redundant secret in older versions. Any Kubernetes version <= `v1.24` will have two tokens created:

* One created by us;
* One created automatically.

A much better approach would be to use the [`TokenRequest` API](https://kubernetes.io/docs/reference/kubernetes-api/authentication-resources/token-request-v1/#create-create-token-of-a-serviceaccount). This would allow us to request a token directly from the API server.

To move forward with the `TokenRequest` API, we should probably first understand:

* What this implies for Kubernetes compatibility: [according to these docs](https://kubernetes.io/docs/concepts/configuration/secret/#service-account-token-secrets) `TokenRequest` API has been introduced in Kubernetes `v1.22`. It is unclear though if it is considered stable, or if it requires a special feature flag. If we move on with using `TokenRequest`, what would the minimum supported Kubernetes version be?
* Generated tokens will have a default lifetime of ~ 10m. This token will be embedded in a kubeconfig and used to create remote Kubernetes clients (i.e informers, core REST client, and so on). Can these tokens be rotated without having to re-link clusters? Are tokens easy to rotate? What lifetime should we provide to ensure we do not run into problems.

### Further reading

1. [Token Account Volume Projection KEP](https://github.com/mikedanese/community/blob/2bf41bd80a9a50b544731c74c7d956c041ec71eb/contributors/design-proposals/storage/svcacct-token-volume-source.md)
2. [ServiceAccount Token Projection docs](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#service-account-token-volume-projection)
3. [Bound ServiceAccount Tokens KEP](https://github.com/kubernetes/enhancements/blob/af83259700f816c593637f95fdc301aab4445a8f/keps/sig-auth/1205-bound-service-account-tokens/README.md)
4. [Docs on ServiceAccount token secrets](https://kubernetes.io/docs/concepts/configuration/secret/#service-account-token-secrets)

**Comment by jeremychase** [comment]
Should we update the priority on this for 2.13?
