### ISSUE TITLE
Show default servers in linkerd viz authz output

### ISSUE THREAD

**Issue by adleong** [linkerd/linkerd2#9149]
### What problem are you trying to solve?

The `linkerd viz authz` command lists metrics for all Servers of the given resource.  However, the default Server (which is used when no Server resource has been created) is not shown.  This leaves us with a blind spot when trying to reason about traffic for which there is no explicit server and can hide denials caused by the default policy.

### How should the problem be solved?

The `linkerd viz authz` command should list the default Server for each resource in addition to the Server resources.

### Any alternatives you've considered?

N/A

**Comment by jeremychase** [comment]
Likely to be resolved as part of #9144
