### ISSUE TITLE
chore: Move the cni-plugin sources to the proxy-init repo

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#9165]
As discussed in https://github.com/linkerd/linkerd2-proxy-init/pull/96, the cni-plugin is tightly coupled with the proxy-init codebase. We should move these sources into the same repo so that they can change in sync.

We should also consider unifying the binaries (perhaps as subcommands?) or otherwise unifying the release artifact to a single docker image.

**Comment by jeremychase** [comment]
This should be done in two steps. First we want to move the cni-plugin sources to the proxy-init repo. Second we want to remove them from the linkerd2 repo.

**Comment by stevej** [comment]
oh yeah, we did this!
