### ISSUE TITLE
rfc: Network Graph Visualization

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#924]
Leverage stat to create a high level visual overview of everything inside (and outside) of the mesh.

An example of what this could look like:

![foo](https://user-images.githubusercontent.com/47992/39830528-54f38036-5387-11e8-9248-4d874bf0386c.png)

# Dashboard

## User Stories

- As a developer, I would like to explore the network graph associated with my service, so that I can debug a current issue.
- As an operator, I would like to narrow down external traffic to a specific service that is failing, so that I can contact the service's owner to get it fixed.
- As someone looking to adopt conduit, I would like to visually show some of the observability features, so that others can understand the benefit of adoption.

## Features

- Add a new tab (`Network`)
- Provide a dropdown to select namespace.
- Render the high level resource types (deployments) with directed arrows showing traffic both *to* and *from*. This would show external traffic coming into a node.
- Clicking on a node will dive into a "detail" view for that resource, showing every pod and the traffic going to these.
- Show basic stats next to each edge (success rate, latency) with color coding.

# Open Questions

- How should multiple resource types be handled?
- Should there be an extreme detail view that shows everything we've got for specific resource types, as a card?
- How valuable is the grafana and/or dashboard integration?
- Should the grafana integration be more integrated in the existing dashboards?
- Is the CLI/Grafana work work the cost?

**Comment by hawkw** [comment]
It occurs to me that on terminals where Unicode is supported (i.e. a vast majority of them these days, we could even use Unicode box-drawing characters as well, for extra fanciness.

**Comment by grampelberg** [comment]
# Minimum Effort

My hypothesis is that the first deliverable (sorted by effort) would be in the grafana dashboards. Any ideas on where best to add the graph?

# CLI

I think you're right about the CLI. I wonder if we could be better served by doing an update to stat's output.

```
NAME       MESHED   TO    FROM    SUCCESS      RPS   LATENCY_P50   LATENCY_P95   LATENCY_P99
emoji         1/1    -       -    100.00%   2.0rps           1ms           1ms           2ms
                           web     90.68%   1.0rps           1ms           1ms           2ms    
vote-bot      1/1    -       -          -        -             -             -             -
                    web      -     90.68%   1.0rps           1ms           1ms           2ms
voting        1/1    -       -     79.66%   1.0rps           1ms           1ms           1ms
                           web     90.68%   1.0rps           1ms           1ms           2ms
web           1/1    -       -     90.68%   2.0rps           3ms           4ms           4ms
                          vote-bot 90.68%   1.0rps           1ms           1ms           2ms
                   emoji     -     90.68%   1.0rps           1ms           1ms           2ms
                  voting     -     90.68%   1.0rps           1ms           1ms           2ms  
```

**Comment by wmorgan** [comment]
That's not a bad idea for the CLI, especially if triggered by a --deps or something argument.

As for Grafana, I think this makes most sense as a separate page, since it potentially spans namespaces and acts as a top-level view of the cluster.

**Comment by grampelberg** [comment]
Okay, updates:

- Removing the CLI integration. There are some potentials for a better experience via. tables or something else.
- The existing grafana plugin doesn't let you define the diagram dynamically. It is more for coloring nodes and edges via. metric values.

So, this is reduced to just integration with the conduit dashboard for now.

**Comment by grampelberg** [comment]
# Historical --------------------------------

# Grafana

## User Stories

- As an operator, I would like to have a high level view of the health of my services, so that I can feel good about everything working as it should.

## Features

- New network graph dashboard
- Graphviz plugin for rendering the entire state
- Namespace dropdown

# CLI

## User Stories

- As a developer, I would like to see an overview of the connections to my service, so that I can understand if the changes I made were successful.

## Features

`conduit graph`

```
Display network graph for one or many resources.

This command will hide resources that have completed, such as pods that are in the Succeeded or Failed phases.

Examples:
  # Output graph for default namespace
  conduit graph

  # Graph the incoming/outgoing traffic for the web deployment
  conduit graph deploy/web

  # Graph everything in the walrus namespace
  conduit -n walrus graph

Options:
      --all-namespaces=false: If present, list the requested object(s) across all namespaces. Namespace in current context is ignored even if specified with --namespace.
  -E, --end-time='': If present, sets the end of the measured window to the specified time.
      --no-headers=false: When using the default or custom-column output format, don't print headers (default print headers).
  -l, --selector='': Selector (label query) to filter on, supports '=', '==', and '!='. (e.g. -l key1=value1,key2=value2)
  -w, --window='10s': Time period over which stats are measured.

Usage:
  conduit graph (TYPE [NAME | -l label] | TYPE/NAME ...) [flags] [options]

Use "conduit options" for a list of global command-line options (applies to all commands).
```

Example output:

```
    vote-bot
     1ms|93%
        |
        v
       web
        +
 100%   |     86%
emoji<--+-->voting
 1ms          1ms
```

**Comment by grampelberg** [comment]
Apparently graph layout is a tough problem. There's a library that has implemented the same algorithm as GraphViz (and it works with d3!):

https://github.com/dagrejs/dagre-d3
