### ISSUE TITLE
getting Error initializing k8s API client: error configuring Kubernetes API clientset: exec plugin: invalid apiVersion "client.authentication.k8s.io/v1alpha1"

### ISSUE THREAD

**Issue by srinath-panda** [linkerd/linkerd2#9255]
### What is the issue?

linkerd check throwing Error initializing k8s API client: error configuring Kubernetes API clientset: exec plugin: invalid apiVersion "client.authentication.k8s.io/v1alpha1"

linkerd version stable 2.12

### How can it be reproduced?

install linkerd 2.12
linkerd check

### Logs, error output, etc

Error initializing k8s API client: error configuring Kubernetes API clientset: exec plugin: invalid apiVersion "client.authentication.k8s.io/v1alpha1"

### output of `linkerd check -o short`

Error initializing k8s API client: error configuring Kubernetes API clientset: exec plugin: invalid apiVersion "client.authentication.k8s.io/v1alpha1"

### Environment

linkerd version 2.12
kubernetes 1.21

### Would you like to work on fixing this bug?

maybe

**Comment by srinath-panda** [comment]
my bad. sorry for the spam

**Comment by chriskolenko** [comment]
@srinath-panda how did you fix it?

**Comment by srinath-panda** [comment]
@chriskolenko  you have to regenerate the kubeconfig, in my case its eks , so update aws cli and recreate the kubeconfig
