### ISSUE TITLE
Support k8s 1.25 and update client-go to 0.25.0

### ISSUE THREAD

**Issue by kleimkuhler** [linkerd/linkerd2#9271]
### What problem are you trying to solve?

k8s 1.25 and client-go 0.25.0 have recently been released. #9263 updates the Go dependencies, but we should keep those in sync with the maximum k8s version as well.

### How should the problem be solved?

When we update the client-go dependencies we should also make sure k8s 1.25 is supported as well. The minimum version ([1.21.0](https://github.com/linkerd/linkerd2/blob/4b5ab072d6c4de5263ca6538f230e83adcfb3424/charts/linkerd-control-plane/Chart.yaml#L11)) is specified in the `linkerd-control-plane` `Chart.yaml`, but we test for the maximum in the [integration tests](https://github.com/linkerd/linkerd2/blob/e46e8738f4d259fb1b43c14e845cc310522a4446/.github/workflows/integration.yml#L172-L174).

### Any alternatives you've considered?

We could update these separately, but it seems like a good idea to keep them coupled.

**Comment by kleimkuhler** [comment]
Similar to what we do with the Rust side of things, we may want to consider downgrading `client-go` to the minimum supported k8s version instead.

**Comment by adleong** [comment]
Current client-go version is 0.25.5: `https://github.com/linkerd/linkerd2/blob/main/go.mod#L45`
