### ISSUE TITLE
Viz - blank page on loading any of the tools

### ISSUE THREAD

**Issue by dwilliams782** [linkerd/linkerd2#9306]
### What is the issue?

If I select any of the Tap / Top / Routes options from the Viz dashboard, I get a blank white page:

![image](https://user-images.githubusercontent.com/42545485/187716198-212b851c-71c4-4a13-bb6a-5ab35bb3673d.png)

Another user on Slack confirmed they also have this issue **[here](https://linkerd.slack.com/archives/C89RTCWJF/p1661339757008719).**

### How can it be reproduced?

Try to use any of the "tools" from the viz dashboard on 2.12.0

### Logs, error output, etc

```
main.82c8da3a2c82d46049d2.js:2 TypeError: Cannot read properties of undefined (reading 'search')
    at main.82c8da3a2c82d46049d2.js:2:788239
    at n (main.82c8da3a2c82d46049d2.js:2:789521)
    at Ko (main.82c8da3a2c82d46049d2.js:2:245602)
    at xs (main.82c8da3a2c82d46049d2.js:2:291507)
    at pl (main.82c8da3a2c82d46049d2.js:2:284283)
    at dl (main.82c8da3a2c82d46049d2.js:2:284208)
    at rl (main.82c8da3a2c82d46049d2.js:2:281238)
    at main.82c8da3a2c82d46049d2.js:2:233011
    at t.unstable_runWithPriority (main.82c8da3a2c82d46049d2.js:2:321171)
    at Va (main.82c8da3a2c82d46049d2.js:2:232720)
ns @ main.82c8da3a2c82d46049d2.js:2
n.callback @ main.82c8da3a2c82d46049d2.js:2
mo @ main.82c8da3a2c82d46049d2.js:2
ss @ main.82c8da3a2c82d46049d2.js:2
vl @ main.82c8da3a2c82d46049d2.js:2
t.unstable_runWithPriority @ main.82c8da3a2c82d46049d2.js:2
Va @ main.82c8da3a2c82d46049d2.js:2
gl @ main.82c8da3a2c82d46049d2.js:2
rl @ main.82c8da3a2c82d46049d2.js:2
(anonymous) @ main.82c8da3a2c82d46049d2.js:2
t.unstable_runWithPriority @ main.82c8da3a2c82d46049d2.js:2
Va @ main.82c8da3a2c82d46049d2.js:2
Ga @ main.82c8da3a2c82d46049d2.js:2
Ua @ main.82c8da3a2c82d46049d2.js:2
M @ main.82c8da3a2c82d46049d2.js:2
Gt @ main.82c8da3a2c82d46049d2.js:2
main.82c8da3a2c82d46049d2.js:2 Uncaught TypeError: Cannot read properties of undefined (reading 'search')
    at main.82c8da3a2c82d46049d2.js:2:788239
    at n (main.82c8da3a2c82d46049d2.js:2:789521)
    at Ko (main.82c8da3a2c82d46049d2.js:2:245602)
    at xs (main.82c8da3a2c82d46049d2.js:2:291507)
    at pl (main.82c8da3a2c82d46049d2.js:2:284283)
    at dl (main.82c8da3a2c82d46049d2.js:2:284208)
    at rl (main.82c8da3a2c82d46049d2.js:2:281238)
    at main.82c8da3a2c82d46049d2.js:2:233011
    at t.unstable_runWithPriority (main.82c8da3a2c82d46049d2.js:2:321171)
    at Va (main.82c8da3a2c82d46049d2.js:2:232720)
```

This is from the console in the browser. There are no logs or errors in the viz pods.

### output of `linkerd check -o short`

```
Status check results are √
```

### Environment

GKE Version: v1.22.8-gke.202
Linkerd version: 2.12.0

**Comment by calvinbui** [comment]
similar to https://github.com/linkerd/linkerd2/issues/9147

having the same issue. it was working on 2.11

**Comment by Tolsto** [comment]
I'm facing the same problem with 2.12.0. I see errors in the Prometheus logs though when clicking on `Tap` in the dashboard.

```
INFO ThreadId(01) inbound:server{port=9090}: linkerd_app_inbound::policy::tcp: Connection denied server.group=policy.linkerd.io server.kind=server server.name=admin tls=Some(Established { client_id: Some(ClientId(Name("metrics-api.linkerd-viz.serviceaccount.identity.linkerd.cluster.local"))), negotiated_protocol: None }) client=10.20.232.121:58878
INFO ThreadId(01) inbound: linkerd_app_core::serve: Connection closed error=unauthorized connection on server/admin client.addr=10.20.232.121:58878  
```

Creating a tap via the CLI works.

**Comment by uGiFarukh** [comment]
Having the same issue. Any update on this? Will this be fixed with 2.12.1? any eta?

**Comment by migg24** [comment]
Is a downgrade from 2.12.0 to 2.11.4 safe? Or will data plane break?

**Comment by alvis** [comment]
I can also confirm that it's an issue even with brand new installation

**Comment by jaohurtas** [comment]
Same here, brand new installation.

**Comment by rahul-citymall** [comment]
any update on ETA for above issue ?

**Comment by iamhritik** [comment]
any update on new release @jeremychase

**Comment by deusxanima** [comment]
@iamhritik , 2.12.2 is out and you should be able to test and confirm the fix.

**Comment by iamhritik** [comment]
checked and now it's working fine. Thanks

**Comment by liad-haber** [comment]
I still see the same issue, both on CLI and linkerd viz dashboard. 
Fresh install on on OKE cluster running k8s v1.24.1 and using flannel CNI. 
![image](https://user-images.githubusercontent.com/94528796/203639108-ce954de2-adbf-4a70-a6ad-058c13831068.png)
![image](https://user-images.githubusercontent.com/94528796/203639160-a92ebaee-223d-493e-8313-b2c03073fe51.png)
![image](https://user-images.githubusercontent.com/94528796/203639253-1dc5b81a-9e7c-4bb8-b09c-a8c0c3470371.png)
![image](https://user-images.githubusercontent.com/94528796/203639391-1c414343-dc9a-4fe3-9e11-a2e34825ce23.png)
