### ISSUE TITLE
Make it possible to set securityContext readOnlyRootFilesystem in the linkerd-viz Helm chart

### ISSUE THREAD

**Issue by Danielkem** [linkerd/linkerd2#9309]
### What problem are you trying to solve?

We are already able to set `readOnlyRootFilesystem` for the control plane but the option to do so for the linkerd-viz chart does not exist. This request is similar to https://github.com/linkerd/linkerd2/pull/6469 which fixed the issue for the cni-plugin helm chart.

### How should the problem be solved?

We should be able to set `readOnlyRootFilesystem` for the linkerd-viz helm chart.

### Any alternatives you've considered?

No, but maybe this issue will spark some discussion about whether this is something desirable or not for this specific application.

**Comment by adleong** [comment]
Can you give me a bit more context on what the motivation is for setting `readOnlyRootFilesystem`?  As far as I know, linkerd-viz's metrics-api controller doesn't write anything to the local filesystem, but I'm not sure I want to rely or commit to that behavior.
