### ISSUE TITLE
Investigate which extensions need policy resources for probes

### ISSUE THREAD

**Issue by kleimkuhler** [linkerd/linkerd2#9364]
### What problem are you trying to solve?

#6846 introduced policy resources for authorization probes in Linkerd extensions. As of #9008, probes are authorized by default when no other Server selects that workload.

We should investigate which extensions still need explicit probe authorizations (because another Server already should exist for that workload) and which ones can be removed.

### How should the problem be solved?

Unnecessary policy resources can be removed from the templates.

### Any alternatives you've considered?

NA

**Comment by jeremychase** [comment]
Merge it! https://github.com/linkerd/linkerd2/pull/10073
