### ISSUE TITLE
404 - l5d-proxy-error: no route found for request

### ISSUE THREAD

**Issue by dwilliams782** [linkerd/linkerd2#9387]
### What is the issue?

I've observed two of our clusterIP services returning 404s since upgrading to 2.12.0:

```
HTTP/1.1 404 Not Found
l5d-proxy-error: no route found for request
```

Both applications had the opaque port annotation set, and removing it restored functionality. We do not use HTTPRoute objects or Servers etc for these services. I can't find any reference to this error in the docs. Is this a bug or intentional?

### How can it be reproduced?

I think just having a deployment with an opaque port set is all that happened to trigger it in our dev cluster.

### Logs, error output, etc

```
DEBUG ThreadId(01) inbound:server{port=4143}:http{v=h2}: linkerd_app_core::errors::respond: Handling error on HTTP connection status=404 Not Found version=HTTP/2.0 close=false

INFO ThreadId(01) inbound:server{port=4143}:http{v=h2}:rescue{client.addr=10.123.35.8:60168}: linkerd_app_core::errors::respond: Request failed error=no route found for request

DEBUG ThreadId(01) inbound:server{port=4143}:http{v=h2}: linkerd_proxy_http::orig_proto: translating HTTP2 to orig-proto: "HTTP/1.1"
```

### output of `linkerd check -o short`

Status check results are √

### Environment

```
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.11-gke.400", GitCommit:"b4e1ab06be827438def8aee0021791b413a0961d", GitTreeState:"clean", BuildDate:"2022-06-24T09:27:38Z", GoVersion:"go1.16.15b7", Compiler:"gc", Platform:"linux/amd64"}
```

Linkerd: 2.12.0

**Comment by adleong** [comment]
Hi @dwilliams782!  If you have at least one `HTTPRoute` defined for a `Server` then any requests to that `Server` which do not match any `HTTPRoute` will result in a 404.  I recommend either defining `HTTPRoute`s for all of routes your application accepts, or adding a "catch-all" `HTTPRoute`.

**Comment by dwilliams782** [comment]
Hey @adleong, thanks for coming back to me. We do not use either of those resources:

```
> k get HttpRoute -A
No resources found

>k get Server -A 
NAMESPACE     NAME                   PORT            PROTOCOL
linkerd-viz   admin                  admin-http      HTTP/1
linkerd-viz   metrics-api            http            HTTP/1
linkerd-viz   proxy-admin            linkerd-admin   HTTP/1
linkerd-viz   tap-api                apiserver       TLS
linkerd-viz   tap-injector-webhook   tap-injector    TLS

```

If we had set HTTPRoutes then I believe setting/unsetting the opaque annotation wouldn't have made a difference, but in this case, removing opaque fixed two services that do not have servers / routes defined. Cheers!

**Comment by adleong** [comment]
Now that you have removed opaque from those two services, is everything working as desired?  I can't say I really understand what's going on here, but if it's working for you then there's no need to dig in any further.

**Comment by dwilliams782** [comment]
Didn't follow up here - we've just had another service show up the no route found log, which also had opaque ports set and works once the annotation is removed. This shouldn't be happening without a server defined, but I haven't had a chance to repro exactly what is going on.

**Comment by adleong** [comment]
@dwilliams782 Definitely let us know if you can get repro steps for this, we'd love to dig in and understand this better.

**Comment by rarora-21** [comment]
The similar issue is reproducible at my end in dev cluster where if annotation for opaque port is set, I am getting 404 not found even though there is no HttpRoute or Server resource in that namespace.

I am using latest stable version: 2.12.2

**Comment by adleong** [comment]
Hi @rarora-21.  Would you mind opening a new issue with detailed steps for how to reproduce this behavior so that we can investigate?

**Comment by rarora-21** [comment]
Thanks @adleong , I have raised another ticket: https://github.com/linkerd/linkerd2/issues/9811

**Comment by adleong** [comment]
I think is now captured in https://github.com/linkerd/linkerd2/issues/9888.  Please re-open this if that is not the case.

**Comment by dwilliams782** [comment]
Thanks @adleong, I haven't had a chance to get back to find a repro on this yet, glad it's been pushed forward.
