### ISSUE TITLE
Warning during helm HA control-plane installation - PodDisruptionBudget

### ISSUE THREAD

**Issue by HummingMind** [linkerd/linkerd2#9408]
### What is the issue?

Hello,
I was installing the latest control-plane in HA mode and received a bunch of these warnings:

![image](https://user-images.githubusercontent.com/87399963/190841537-679024b1-3ddf-40b2-987f-b6c1370c3931.png)

I am still on k8s 1.24.3, but 1.25.0 is GA, so will be upgrading soon. Sounds like linkerd 2.12.0 HA would break on k8s 1.25?

Thank you!

### How can it be reproduced?

Run the HA install using helm on k8s 1.24.x

### Logs, error output, etc

Warning: policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget

### output of `linkerd check -o short`

not available
Don't have the CLI installed.

### Environment

k8s: 1.24.3
AKS
Linux
2.12.0

**Comment by mikutas** [comment]
It seems to be already resolved in #9305

**Comment by HummingMind** [comment]
Great! Thank you!
