### ISSUE TITLE
Linkerd stable-2.12.0 viz stat is not working

### ISSUE THREAD

**Issue by AleksandrAksenov** [linkerd/linkerd2#9416]
### What is the issue?

After installing Linkerd 2.12 `linkerd viz stat` is not working.

### How can it be reproduced?

```
helm repo add linkerd https://helm.linkerd.io/stable
kubectl create namespace linkerd
step certificate create root.linkerd.cluster.local ca.crt ca.key --profile root-ca --no-password --insecure
kubectl create secret tls linkerd-trust-anchor --cert=ca.crt --key=ca.key --namespace=linkerd

cat <<EOF | kubectl apply -f -
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: linkerd-trust-anchor
  namespace: linkerd
spec:
  ca:
    secretName: linkerd-trust-anchor
EOF

cat <<EOF | kubectl apply -f -
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-identity-issuer
  namespace: linkerd
spec:
  secretName: linkerd-identity-issuer
  duration: 744h
  renewBefore: 48h
  issuerRef:
    name: linkerd-trust-anchor
    kind: Issuer
  commonName: identity.linkerd.cluster.local
  dnsNames:
  - identity.linkerd.cluster.local
  isCA: true
  privateKey:
    algorithm: ECDSA
  usages:
  - cert sign
  - crl sign
  - server auth
  - client auth
EOF

helm install linkerd-crds linkerd/linkerd-crds -n linkerd
helm upgrade --install linkerd-control-plane \
  --set-file identityTrustAnchorsPEM=ca.crt \
  --set identity.issuer.scheme=kubernetes.io/tls \
  --set installNamespace=false \
  linkerd/linkerd-control-plane \
  -n linkerd

helm upgrade --install linkerd-viz  --namespace linkerd-viz --create-namespace linkerd/linkerd-viz
```

### Logs, error output, etc

```
$linkerd viz stat ns/NAMESPACE --verbose
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x48 pc=0x103cb0de0]

goroutine 114 [running]:
github.com/linkerd/linkerd2/viz/cmd.requestStatsFromAPI({0x0?, 0x0?}, 0x6220414320656874?)
	/private/tmp/linkerd-20220823-37628-9yusbn/viz/cmd/stat.go:299 +0x20
github.com/linkerd/linkerd2/viz/cmd.NewCmdStat.func2.1(0x0, 0x6f74206465646461?)
	/private/tmp/linkerd-20220823-37628-9yusbn/viz/cmd/stat.go:245 +0x3c
created by github.com/linkerd/linkerd2/viz/cmd.NewCmdStat.func2
	/private/tmp/linkerd-20220823-37628-9yusbn/viz/cmd/stat.go:244 +0x20c
```

### output of `linkerd check -o short`

```
$ linkerd check -o short
Linkerd core checks
===================

linkerd-identity
----------------
‼ issuer cert is valid for at least 60 days
    issuer certificate will expire on 2022-10-05T13:50:01Z
    see https://linkerd.io/2.12/checks/#l5d-identity-issuer-cert-not-expiring-soon for hints

Linkerd extensions checks
=========================

linkerd-viz
-----------
‼ linkerd-viz ClusterRoles exist
    missing ClusterRoles: linkerd-default-metrics-api, linkerd-default-tap, linkerd-default-tap-admin
    see https://linkerd.io/2.12/checks/#l5d-viz-cr-exists for hints

Linkerd extensions checks
=========================

linkerd-viz
-----------
‼ linkerd-viz ClusterRoles exist
    missing ClusterRoles: linkerd-default-metrics-api, linkerd-default-tap, linkerd-default-tap-admin
    see https://linkerd.io/2.12/checks/#l5d-viz-cr-exists for hints

Status check results are √
```

```
$ kubectl get clusterroles | grep linkerd-viz
linkerd-linkerd-viz-metrics-api                                        2022-09-19T07:11:42Z
linkerd-linkerd-viz-prometheus                                         2022-09-19T07:11:42Z
linkerd-linkerd-viz-tap                                                2022-09-19T07:11:42Z
linkerd-linkerd-viz-tap-admin                                          2022-09-19T07:11:42Z
linkerd-linkerd-viz-web-api                                            2022-09-19T07:11:42Z
linkerd-linkerd-viz-web-check                                          2022-09-19T07:11:42Z
```

```
kubectl get pods -n linkerd-viz
NAME                            READY   STATUS    RESTARTS   AGE
metrics-api-55ff74779c-9ldr6    2/2     Running   0          100m
prometheus-56cc56585f-rs28l     2/2     Running   0          100m
tap-6bbd4cd674-n9gc4            2/2     Running   0          100m
tap-injector-6d955f6dcd-45w9v   2/2     Running   0          100m
web-dd996f84d-qbwnl             2/2     Running   0          100m
```

### Environment

- Kubernetes version: 1.23
- Cluster environment: EKS
- Host OS: ami-eks
- Linkerd version: stable-2.12.0

### Possible solution

No solution

**Comment by Chakki1301** [comment]
Yes I guess linkerd is broken. 2.11 was fine. Upgrading to 2.12 broke it. Fresh install of 2.12 is not working as well in EKS 1.22 and 1.23. I just now tried upgrading to 2.12.1 still the pods won't even recycle, health check fails.

`NAME                                         READY   STATUS    RESTARTS   AGE
pod/linkerd-destination-54854b6475-pbxft     4/4     Running   0          25d
pod/linkerd-destination-5c8865f587-n65h9     0/4     Pending   0          5m50s
pod/linkerd-heartbeat-27731509-tllzg         0/1     Pending   0          11m
pod/linkerd-identity-6879dd4c6f-hzpq5        0/2     Pending   0          5m51s
pod/linkerd-identity-6d9446f8f8-478g4        2/2     Running   0          25d
pod/linkerd-proxy-injector-b4df984b8-762qp   2/2     Running   0          25d
pod/linkerd-proxy-injector-d96749d5f-2k2kk   0/2     Pending   0          5m50s

NAME                                TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
service/linkerd-dst                 ClusterIP   172.20.119.79    <none>        8086/TCP   65d
service/linkerd-dst-headless        ClusterIP   None             <none>        8086/TCP   65d
service/linkerd-identity            ClusterIP   172.20.134.36    <none>        8080/TCP   65d
service/linkerd-identity-headless   ClusterIP   None             <none>        8080/TCP   65d
service/linkerd-policy              ClusterIP   None             <none>        8090/TCP   65d
service/linkerd-policy-validator    ClusterIP   172.20.112.176   <none>        443/TCP    65d
service/linkerd-proxy-injector      ClusterIP   172.20.169.180   <none>        443/TCP    65d
service/linkerd-sp-validator        ClusterIP   172.20.96.175    <none>        443/TCP    65d

NAME                                     READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/linkerd-destination      1/1     1            1           65d
deployment.apps/linkerd-identity         1/1     1            1           65d
deployment.apps/linkerd-proxy-injector   1/1     1            1           65d
`
`LAST SEEN   TYPE      REASON              OBJECT                                        MESSAGE
45m         Warning   Unhealthy           pod/linkerd-destination-54854b6475-pbxft      Readiness probe failed: Get "http://10.13.103.195:9990/ready": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
14s         Warning   FailedScheduling    pod/linkerd-destination-5c8865f587-n65h9      0/2 nodes are available: 2 Too many pods.
6m27s       Normal    SuccessfulCreate    replicaset/linkerd-destination-5c8865f587     Created pod: linkerd-destination-5c8865f587-n65h9
7m14s       Warning   FailedScheduling    pod/linkerd-destination-7d4fc994fd-7h4l9      0/2 nodes are available: 2 Too many pods.
6m27s       Warning   FailedScheduling    pod/linkerd-destination-7d4fc994fd-7h4l9      skip schedule deleting pod: linkerd/linkerd-destination-7d4fc994fd-7h4l9
21m         Normal    SuccessfulCreate    replicaset/linkerd-destination-7d4fc994fd     Created pod: linkerd-destination-7d4fc994fd-7h4l9
6m27s       Normal    SuccessfulDelete    replicaset/linkerd-destination-7d4fc994fd     Deleted pod: linkerd-destination-7d4fc994fd-7h4l9
21m         Normal    ScalingReplicaSet   deployment/linkerd-destination                Scaled up replica set linkerd-destination-7d4fc994fd to 1
6m27s       Normal    ScalingReplicaSet   deployment/linkerd-destination                Scaled down replica set linkerd-destination-7d4fc994fd to 0
6m27s       Normal    ScalingReplicaSet   deployment/linkerd-destination                Scaled up replica set linkerd-destination-5c8865f587 to 1
12m         Warning   FailedScheduling    pod/linkerd-heartbeat-27731498-z9cxn          0/2 nodes are available: 2 Too many pods.
12m         Warning   FailedScheduling    pod/linkerd-heartbeat-27731498-z9cxn          skip schedule deleting pod: linkerd/linkerd-heartbeat-27731498-z9cxn
23m         Normal    SuccessfulCreate    job/linkerd-heartbeat-27731498                Created pod: linkerd-heartbeat-27731498-z9cxn
44s         Warning   FailedScheduling    pod/linkerd-heartbeat-27731509-tllzg          0/2 nodes are available: 2 Too many pods.
12m         Normal    SuccessfulCreate    job/linkerd-heartbeat-27731509                Created pod: linkerd-heartbeat-27731509-tllzg
23m         Normal    SuccessfulCreate    cronjob/linkerd-heartbeat                     Created job linkerd-heartbeat-27731498
12m         Normal    SuccessfulDelete    cronjob/linkerd-heartbeat                     Deleted job linkerd-heartbeat-27731498
12m         Normal    SuccessfulCreate    cronjob/linkerd-heartbeat                     Created job linkerd-heartbeat-27731509
44s         Warning   FailedScheduling    pod/linkerd-identity-6879dd4c6f-hzpq5         0/2 nodes are available: 2 Too many pods.
6m28s       Normal    SuccessfulCreate    replicaset/linkerd-identity-6879dd4c6f        Created pod: linkerd-identity-6879dd4c6f-hzpq5
6m44s       Warning   FailedScheduling    pod/linkerd-identity-8459fc4594-tq24l         0/2 nodes are available: 2 Too many pods.
6m28s       Warning   FailedScheduling    pod/linkerd-identity-8459fc4594-tq24l         skip schedule deleting pod: linkerd/linkerd-identity-8459fc4594-tq24l
21m         Normal    SuccessfulCreate    replicaset/linkerd-identity-8459fc4594        Created pod: linkerd-identity-8459fc4594-tq24l
6m28s       Normal    SuccessfulDelete    replicaset/linkerd-identity-8459fc4594        Deleted pod: linkerd-identity-8459fc4594-tq24l
21m         Normal    ScalingReplicaSet   deployment/linkerd-identity                   Scaled up replica set linkerd-identity-8459fc4594 to 1
6m28s       Normal    ScalingReplicaSet   deployment/linkerd-identity                   Scaled down replica set linkerd-identity-8459fc4594 to 0
6m28s       Normal    ScalingReplicaSet   deployment/linkerd-identity                   Scaled up replica set linkerd-identity-6879dd4c6f to 1
7m14s       Warning   FailedScheduling    pod/linkerd-proxy-injector-6f97d78c8-h8zjf    0/2 nodes are available: 2 Too many pods.
6m27s       Warning   FailedScheduling    pod/linkerd-proxy-injector-6f97d78c8-h8zjf    skip schedule deleting pod: linkerd/linkerd-proxy-injector-6f97d78c8-h8zjf
21m         Normal    SuccessfulCreate    replicaset/linkerd-proxy-injector-6f97d78c8   Created pod: linkerd-proxy-injector-6f97d78c8-h8zjf
6m27s       Normal    SuccessfulDelete    replicaset/linkerd-proxy-injector-6f97d78c8   Deleted pod: linkerd-proxy-injector-6f97d78c8-h8zjf
14s         Warning   FailedScheduling    pod/linkerd-proxy-injector-d96749d5f-2k2kk    0/2 nodes are available: 2 Too many pods.
6m27s       Normal    SuccessfulCreate    replicaset/linkerd-proxy-injector-d96749d5f   Created pod: linkerd-proxy-injector-d96749d5f-2k2kk
21m         Normal    ScalingReplicaSet   deployment/linkerd-proxy-injector             Scaled up replica set linkerd-proxy-injector-6f97d78c8 to 1
6m27s       Normal    ScalingReplicaSet   deployment/linkerd-proxy-injector             Scaled down replica set linkerd-proxy-injector-6f97d78c8 to 0
6m27s       Normal    ScalingReplicaSet   deployment/linkerd-proxy-injector             Scaled up replica set linkerd-proxy-injector-d96749d5f to 1
`

**Comment by winterhalder** [comment]
Not sure if it is related, but I had a problem installing the linkerd-viz 2.12 helm chart directly - the default ServerAuthorization settings weren't letting anything talk to the metrics-api pod (and others I guess).

Doing a manual `linkerd viz install` worked though - so I guess it's the helm chart itself that is broken?

**Comment by adleong** [comment]
@AleksandrAksenov Based on the output that you provided, it looks like maybe you have the `linkerd.io/extension=viz` label on the default namespace.  This can definitely cause problems because Linkerd uses this label to locate the extension.  That label should be set on the namespace where the viz extension is installed (`linkerd-viz` by default) only.  I recommend deleting that label off of the default namespace and seeing if things start working again.

With all that said, the panic is not great.  I'm working on a fix now to have the CLI handle this error more gracefully.

**Comment by adleong** [comment]
@Chakki1301 @winterhalder Unless you also have the `linkerd.io/extension=viz` label set on the incorrect namespace, I suspect you may be experiencing a different problem.  Please open a new issue with as many details as possible so that we can dig in.

**Comment by AleksandrAksenov** [comment]
@adleong 
Dear Alex - you are the best.
The issue can be closed - the problem is precisely in the label on the default namespace. As soon as I removed it - everything started working perfectly.
