### ISSUE TITLE
Set securityContext on namespace-metadata job container

### ISSUE THREAD

**Issue by akorp** [linkerd/linkerd2#9445]
### What problem are you trying to solve?

Additional security. It is a best practice in security to run container with a minimum required `securityContext`. Many kubernetes users, including us, have constraints in cluster prohibiting high privileges. 

### How should the problem be solved?

Add `securityContext` for the [namespace-metadata](https://github.com/linkerd/linkerd2/blob/main/viz/charts/linkerd-viz/templates/namespace-metadata.yaml) job.
 >       privileged: false
 >       allowPrivilegeEscalation: false
 >       runAsNonRoot: true
 >       readOnlyRootFilesystem: true

As described at https://github.com/linkerd/linkerd2/pull/6638, image might change in the future, but any image unlikely to require high privileges for its taks described in PR.

### Any alternatives you've considered?

Could not find other alternatives for the described solution.

**Comment by alpeb** [comment]
Note that this is being addressed indirectly by #9719

**Comment by alpeb** [comment]
Addressed in #9719
