### ISSUE TITLE
Possibility to add additional labels on all resources for linkerd-control-plane helm chart

### ISSUE THREAD

**Issue by bastienbosser** [linkerd/linkerd2#9510]
### What problem are you trying to solve?

Currently it is not possible to add additional labels on all resources deployed by the helm chart linkerd-control-plane. 

### How should the problem be solved?

Add a labels variable in the values.yml file that allows to add additional labels on all helm chart resources.

### Any alternatives you've considered?

Nothing to report

### How would users interact with this feature?

The user will be able to add labels to all resources deployed by the helm charts in the same way as he can already do for pods.

### Would you like to work on this feature?

yes

**Comment by olix0r** [comment]
> What problem are you trying to solve?
>
> Currently it is not possible to add additional labels on all resources deployed by the helm chart linkerd-control-plane.

Can you help us understand some of the specific situations where this may be necessary?

**Comment by bastienbosser** [comment]
Hello @olix0r,

As you know, labels can be used to organize and to select subsets of objects. In my case of use it allows me to group the applications by category and to check by a simple command the status of it.

As examples, for all security applications, I put a label "my-cluster-name/application_group: security". Then I just have to make the command "kubectl get all -A -l my-cluster-name/application_group=security" to know the status of all applications that provide security.

Let me know if you have more questions.

Regards,

**Comment by olix0r** [comment]
@bastienbosser Thanks. This makes sense.

As an example of another project doing this, [cert-manager](https://github.com/cert-manager/cert-manager/blob/52c6723de522a63a66ef8ea8d99117f6b8a79b5b/deploy/charts/cert-manager/values.yaml) includes various configurations for labels and annotations of managed resources.

**Comment by bastienbosser** [comment]
@olix0r Thanks.

I did a PR on this. If you could review it to make sure the form is right for you. Maybe I can do the same for all the helm charts in the repository.
