### ISSUE TITLE
Linkerd Helm Chart fails to install on K8S 1.25+ due to use of batch/v1beta1 CronJob

### ISSUE THREAD

**Issue by dacjames** [linkerd/linkerd2#9523]
### What is the issue?

The linkerd helm chart does not work with Kubernetes version 1.25.

This appears to be caused by the use of "CronJob" resource with "batch/v1beta1", which has now been removed.

### How can it be reproduced?

- Run a K8S cluster with version 1.25+ (i used minikube)
- Deploy linkerd with the stable helmchart (I used terraform to do this)

### Logs, error output, etc

Here is the log of the error when using the helm chart through terraform.

```
│ Error: unable to build kubernetes objects from release manifest: resource mapping not found for name: "linkerd-heartbeat" namespace: "linkerd" from "": no matches for kind "CronJob" in version "batch/v1beta1"
│ ensure CRDs are installed first
│ 
│   with module.linkerd.helm_release.linkerd2,
│   on ../../modules/linkerd/main.tf line 8, in resource "helm_release" "linkerd2":
│    8: resource "helm_release" "linkerd2" {
```

### output of `linkerd check -o short`

N/A. Occurs pre-install.

### Environment

- Kubernetes Version: 1.25
- Cluster Environment: minikube

### Possible solution

The problem seems simple enough, but I'm not well versed in K8S versioning to recommend the proper solution.

### Would you like to work on fixing this bug?

maybe

**Comment by adleong** [comment]
Hi @dacjames.  What version of the Linkerd chart are you trying to install? Can you show us where in the chart the invalid CronJob api version is?

Linkerd stable-2.12.0 upgraded this resource to version `batch/v1` and `batch/v1beta1` should no longer be present anywhere in the chart.

**Comment by dacjames** [comment]
Ah, thanks @adleong, I was using the `linkerd2` chart, not the `linkerd2-crds` / `linkerd2-control-plane` charts that I see in the latest docs.
