### ISSUE TITLE
Feature to disable certain checks in linkerd check command

### ISSUE THREAD

**Issue by lieberlois** [linkerd/linkerd2#9529]
### What problem are you trying to solve?

In our cloud native setup, we are trying to implement smoketests for our infrastructure. One of the tests is a call to the `linkerd check` command. However, since we are running one windows node, we get the problem that "proxy-init container runs as root user if docker container runtime is used". We don't want to change the whole K8s setup just to match the `linkerd check` command.

### How should the problem be solved?

Add a flag to the `linkerd check` command that allows the user to disable certain checks by name/id.

### Any alternatives you've considered?

Right now, we are using bash (grep + wc) to check whether the linkerd check was successful manually. This is a bad solution though.

### How would users interact with this feature?

Example call:

```sh
linkerd check --disable-check linkerd-identity.proxy-init-run-as-root
```

### Would you like to work on this feature?

maybe

**Comment by adleong** [comment]
Hi @lieberlois 

I would recommend using the `-o json` flag to get the check output in json format which is more suitable for post-processing.

**Comment by lieberlois** [comment]
Hi @adleong ,

thanks for the advice, Ill probably change this 👍 still, the functionality of disabling certain checks would be nice

**Comment by adleong** [comment]
Sounds good.  Since this use case can be satisfied with json output, we're unlikely to add the ability to disable checks in the near-term.
