### ISSUE TITLE
Issue with linkerd version 2.12 installation using helm

### ISSUE THREAD

**Issue by Priyaboliset** [linkerd/linkerd2#9551]
### What is the issue?

I tried to install the linkerd using helm with linkerd 2.12 version
After installing verified tried to verify with

### How can it be reproduced?

linkerd check command should produce the output as expected 
Following this documentation https://linkerd.io/2.12/tasks/install-helm/

### Logs, error output, etc

$helm search repo linkerd
NAME                                    CHART VERSION   APP VERSION     DESCRIPTION                                       
linkerd/linkerd-control-plane           1.9.3           stable-2.12.1   Linkerd gives you observability, reliability, a...
linkerd/linkerd-crds                    1.4.0                           Linkerd gives you observability, reliability, a...
linkerd/linkerd-failover                0.1.0           0.1.0                                                             
linkerd/linkerd-jaeger                  30.4.3          stable-2.12.1   The Linkerd-Jaeger extension adds distributed t...
linkerd/linkerd-multicluster            30.2.3          stable-2.12.1   The Linkerd-Multicluster extension contains res...
linkerd/linkerd-viz                     30.3.3          stable-2.12.1   The Linkerd-Viz extension contains observabilit...
linkerd/linkerd2                        2.11.5          stable-2.11.5   DEPRECATED: Use linkerd-crds and linkerd-contro...
linkerd/linkerd2-cni                    30.3.3          stable-2.12.1   Linkerd is a *service mesh*, designed to give p...
linkerd/linkerd2-multicluster           2.9.6           stable-2.9.5    DEPRECATED: Use linkerd-multicluster instead - ...
linkerd/linkerd2-multicluster-link      2.9.6           stable-2.9.5    DEPRECATED: A helm chart containing the resourc...

### output of `linkerd check -o short`

Linkerd core checks
===================

kubernetes-api
--------------
× can initialize the client
    error configuring Kubernetes API clientset: exec plugin: invalid apiVersion "client.authentication.k8s.io/v1alpha1"
    see https://linkerd.io/2.12/checks/#k8s-api for hints

Failed to run extensions checks: error configuring Kubernetes API clientset: exec plugin: invalid apiVersion "client.authentication.k8s.io/v1alpha1"
When i checked the pod logs, getting like below
$kubectl logs linkerd-destination-585c8b9fd6-m7vhw -n linkerd -c linkerd-init
time="2022-10-06T07:45:19Z" level=info msg="/sbin/iptables-save -t nat"
time="2022-10-06T07:45:19Z" level=info msg="iptables-save v1.8.8 (legacy): Cannot initialize: Permission denied (you must be root)\n\n"
time="2022-10-06T07:45:19Z" level=error msg="aborting firewall configuration"
Error: exit status 1

### Environment

Kubernetes Version: 1.21
Cluster Environment: EKS
Linkerd version: 2.12
OS: Centos

**Comment by joscabmar** [comment]
Yes, I ran into these issues. EKS in 1.21 uses Docker runtime by default. So you must change it in your chart values to use root:
```
proxyInit:
  iptablesMode: legacy
  runAsRoot: true
```
