### ISSUE TITLE
Dashboard's TrafficSplit section is producing an error

### ISSUE THREAD

**Issue by alpeb** [linkerd/linkerd2#9554]
![image](https://user-images.githubusercontent.com/554287/193929700-ae01895a-19c8-4e0a-b199-be59a73ab5d9.png)

This is happening since `stable-2.12.0`, even after having installed the `linkerd-smi` extension which creates the TrafficSplit CRD.

The issue stems from #7334 where all TrafficSplit functionality was removed from the `web` service. As described there, it seems the splitting information is being surfaced under the Services section. So it might make sense to just remove the TrafficSplit section altogether from the dashboard.

**Comment by hungran** [comment]
I have exactly same issue
```
linkerd v2.12.2
k8s version 1.23.5
linux (amd64)
Ubuntu 18.04.6 LTS
```
we used gitops approach with argocd application and used helm to install control plane, viz, smi, crds
then now when open the Traffic Splits  tab from web browser it appeared exactly same error above

`cannot find Kubernetes canonical name from friendly name [trafficsplit]`

**Comment by mdimarino** [comment]
Try to execute a

**Comment by hungran** [comment]
> Try to execute a

? what do you mean?

**Comment by eddie-huhu** [comment]
@mdimarino Try  what?

**Comment by adleong** [comment]
I agree with @alpeb's assessment that the best course of action is to remove the trafficsplits section entirely.

**Comment by adleong** [comment]
More specifically, I think we should remove the TrafficSplitDetail page, the Traffic Splits navigation item from the left sidebar, and the "Configuration" section from the left sidebar (since Traffic Splits was the only item in it).

**Comment by mdimarino** [comment]
The more functionalities you remove from Linkerd Dashboard the more Kiali with Istio will prove to help users.

**Comment by kong62** [comment]
remove from Linkerd Dashboard , but, command also failed: 
```
# linkerd viz stat ts/my-split
Error: error creating metrics request while making stats request: cannot find Kubernetes canonical name from friendly name [ts]
Usage:
  linkerd viz stat [flags] (RESOURCES)
```

**Comment by adleong** [comment]
Hi @mdimarino!  To give some context here, this is part of ongoing work in Linkerd to move away from having SMI baked into Linkerd and instead be able to express much richer client policy (including traffic splits) using the gateway API.  You can read more about our motivation for that here https://buoyant.io/blog/linkerd-and-the-gateway-api

In the short term, that means removing dependencies on SMI such as the traffic split page.

I'll also note that even though SMI is no longer part of Linkerd core, it is still possible to use SMI traffic splits with Linkerd by using the linkerd-smi extension: https://github.com/linkerd/linkerd-smi

**Comment by adleong** [comment]
Hi @kong62! The `viz stat` command no longer supports querying traffic split resources directly (for reasons outlined in my above comment).  Instead, you can use `viz stat` on, for example, deployments or pods directly to see how much traffic they are receiving.  You can also use `--to` or `--from` flags to further isolate the type of traffic you want to look at.

**Comment by PaarthAgarwal** [comment]
I saw this along with #7865 and #9243 on the Lfx mentorship page, and they caught my interest. I want to work on them this spring term. Other than the tech stack mentioned, are there any other prerequisites for applying?

**Comment by amr-aly-careem** [comment]
I'm on latest version, having `viz` and `smi` extensions installed through helm, still facing this issue.
