### ISSUE TITLE
Unable to push new proxy-init release

### ISSUE THREAD

**Issue by stevej** [linkerd/linkerd2#9572]
### What is the issue?

The release process for proxy-init (in the linkerd2-proxy-init repo) is to create a git tag which results in github action making the release. Unfortunately it's failing due an underlying git issue. This only affects the arm7 release artifact.

### How can it be reproduced?

`git tag -v$YOUR_VERSION` and watch the log output for the github action.

### Logs, error output, etc

This is the relevant section from the job output: https://github.com/linkerd/linkerd2-proxy-init/actions/runs/3198984982/jobs/5224206312

```#36 [linux/arm/v7 rust 5/6] RUN --mount=type=cache,target=target    --mount=type=cache,from=docker.io/library/rust:1.63.0-slim,source=/usr/local/cargo,target=/usr/local/cargo    cargo fetch
#36 1.593     Updating crates.io index
#36 2.061 warning: spurious network error (2 tries remaining): could not read directory '/usr/local/cargo/registry/index/github.com-1285ae84e5963aae/.git/refs': Value too large for defined data type; class=Os (2)
#36 2.326 warning: spurious network error (1 tries remaining): could not read directory '/usr/local/cargo/registry/index/github.com-1285ae84e5963aae/.git/refs': Value too large for defined data type; class=Os (2)
#36 2.592 error: Unable to update registry `crates-io`
#36 2.598 
#36 2.598 Caused by:
#36 2.599   failed to fetch `https://github.com/rust-lang/crates.io-index`
#36 2.600 
#36 2.600 Caused by:
#36 2.601   could not read directory '/usr/local/cargo/registry/index/github.com-1285ae84e5963aae/.git/refs': Value too large for defined data type; class=Os (2)
#36 ERROR: process "/bin/sh -c cargo fetch" did not complete successfully: exit code: 101
```

### output of `linkerd check -o short`

not relevant here.

### Environment

equinix host

### Possible solution

I've found a few relevant issues from other people having the same issue.

https://github.com/rust-lang/cargo/issues/8719
https://github.com/docker/buildx/issues/395

### Would you like to work on fixing this bug?

yes

**Comment by adleong** [comment]
Closed by https://github.com/linkerd/linkerd2-proxy-init/pull/115
