### ISSUE TITLE
Default multi-cluster installation blocks non-http traffic from flowing

### ISSUE THREAD

**Issue by psmit** [linkerd/linkerd2#9574]
### What is the issue?

In a default multicluster install, the Server object for the linkerd-gateway allows only HTTP/1 traffic. This means, that any traffic not-conforming, such as TLS traffic is blocked as unauthorized.

### How can it be reproduced?

Install multicluster. Launch a mirrored TLS service in east, and try to connect from west. Result: unauthorized.

### Logs, error output, etc

```text
[ 1040.864233s] DEBUG ThreadId(01) inbound:accept{client.addr=172.16.28.3:8203}:server{port=4143}:direct: linkerd_transport_header::server: Read transport header header=TransportHeader { port: 9443, name: Some(Name("minio-console.minio.svc.cluster.local")), protocol: None }
[ 1040.864265s] INFO ThreadId(01) inbound:accept{client.addr=172.16.28.3:8203}:server{port=4143}:direct:gateway{dst=minio-console.minio.svc.cluster.local:9443}: linkerd_app_inbound::policy::tcp: Connection denied server.group=policy.linkerd.io server.kind=server server.name=linkerd-gateway tls=Some(Established { client_id: Some(ClientId(Name("ingress-nginx.ingress-nginx.serviceaccount.identity.linkerd.cluster.local"))), negotiated_protocol: Some("transport.l5d.io/v1") }) client=172.16.28.3:8203
[ 1040.864390s] INFO ThreadId(01) inbound:accept{client.addr=172.16.28.3:8203}: linkerd_app_core::serve: Connection closed error=unauthorized connection on server/linkerd-gateway client.addr=172.16.28.3:8203
```

### output of `linkerd check -o short`

```text
Linkerd core checks
===================

Status check results are √
```

### Environment

Kubernetes 1.23 (west), 1.25 east.

Linkerd 2.12.1, latest multicluster version.

### Possible solution

Update the default template for linkerd multicluster to have `proxyProtocol: unknown` instead of `proxyProtocol: HTTP/1`.

### Would you like to work on fixing this bug?

yes

**Comment by olix0r** [comment]
This is a good catch. I'm not sure that your change actually fixes the issue, though. Have you confirmed that it does?

> ```
> [ 1040.864390s] INFO ThreadId(01) inbound:accept{client.addr=172.16.28.3:8203}: linkerd_app_core::serve: Connection closed error=unauthorized connection on server/linkerd-gateway client.addr=172.16.28.3:8203
> ```

This is an authorization error. The server's proxyProtocol shouldn't have any bearing on whether the connection is authorized or not. If your change does fix the issue, we probably want to figure out how to improve the logging in this situation.

**Comment by psmit** [comment]
You are correct, we are still having issues with some connections. Just when the critical ones did start again (after the fix in the PR) I didn't look in depth at all other connections.

I'll investigate more this week and give an update.
