### ISSUE TITLE
Allow Linkerd Viz dashboard Helm Chart to add Service annotations

### ISSUE THREAD

**Issue by sgrzemski** [linkerd/linkerd2#9580]
### What problem are you trying to solve?

I would like to expose Linkerd Viz Dashboard as an internal Ingress in GCP. To do so, I need to add some annotations to the Service object. I am deploying this using Flux/Kustomize pair, so I cannot patch the objects directly and I cannot make it work. 

### How should the problem be solved?

Modify the Helm Chart to allow set annotations for `web` Service.

### Any alternatives you've considered?

N/A

### How would users interact with this feature?

Set values and forget.

### Would you like to work on this feature?

yes

**Comment by kleimkuhler** [comment]
This is being worked on in #9581.
