### ISSUE TITLE
Integration Linkerd To External Pormetheus 

### ISSUE THREAD

**Issue by roombiotank** [linkerd/linkerd2#9594]
### What is the issue?

I have linkerd running on kubernetes cluster and I want to get metric use Prometheus External and I have a Problem Linkerd Controller can the integration but Linkerd Proxy and linkerd-service-mirror has status dropped all prometheus externalscrapconfig. 

### How can it be reproduced?

values.yaml
#extascrapconfig 

    - job_name: 'linkerd-controller'
      kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
          - '{{.Values.linkerdNamespace}}'
          - '{{.Values.namespace}}'
      relabel_configs:
      - source_labels:
        - __meta_kubernetes_pod_container_port_name
        action: keep
        regex: admin-http
      - source_labels: [__meta_kubernetes_pod_container_name]
        action: replace
        target_label: component

    - job_name: 'linkerd-service-mirror'
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - source_labels:
        - __meta_kubernetes_pod_label_linkerd_io_control_plane_component
        - __meta_kubernetes_pod_container_port_name
        action: keep
        regex: linkerd-service-mirror;admin-http$
      - source_labels: [__meta_kubernetes_pod_container_name]
        action: replace
        target_label: component

    - job_name: 'linkerd-proxy'
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - source_labels:
        - __meta_kubernetes_pod_container_name
        - __meta_kubernetes_pod_container_port_name
        - __meta_kubernetes_pod_label_linkerd_io_control_plane_ns
        action: keep
        regex: ^{{default .Values.proxyContainerName "linkerd-proxy" .Values.proxyContainerName}};linkerd-admin;{{.Values.linkerdNamespace}}$
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: namespace
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: pod
      # special case k8s' "job" label, to not interfere with prometheus' "job"
      # label
      # __meta_kubernetes_pod_label_linkerd_io_proxy_job=foo =>
      # k8s_job=foo
      - source_labels: [__meta_kubernetes_pod_label_linkerd_io_proxy_job]
        action: replace
        target_label: k8s_job
      # drop __meta_kubernetes_pod_label_linkerd_io_proxy_job
      - action: labeldrop
        regex: __meta_kubernetes_pod_label_linkerd_io_proxy_job
      # __meta_kubernetes_pod_label_linkerd_io_proxy_deployment=foo =>
      # deployment=foo
      - action: labelmap
        regex: __meta_kubernetes_pod_label_linkerd_io_proxy_(.+)
      # drop all labels that we just made copies of in the previous labelmap
      - action: labeldrop
        regex: __meta_kubernetes_pod_label_linkerd_io_proxy_(.+)
      # __meta_kubernetes_pod_label_linkerd_io_foo=bar =>
      # foo=bar
      - action: labelmap
        regex: __meta_kubernetes_pod_label_linkerd_io_(.+)
      # Copy all pod labels to tmp labels
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
        replacement: __tmp_pod_label_$1
      # Take `linkerd_io_` prefixed labels and copy them without the prefix
      - action: labelmap
        regex: __tmp_pod_label_linkerd_io_(.+)
        replacement:  __tmp_pod_label_$1
      # Drop the `linkerd_io_` originals
      - action: labeldrop
        regex: __tmp_pod_label_linkerd_io_(.+)
      # Copy tmp labels into real labels
      - action: labelmap
        regex: __tmp_pod_label_(.+)

### Logs, error output, etc

Target Up Linkerd-Controller
![image](https://user-images.githubusercontent.com/63233249/194990772-1b7c0a37-55fa-4cb1-8a21-f08b4a64e989.png)

Dropped Linkerd-Proxy
<img width="1627" alt="image" src="https://user-images.githubusercontent.com/63233249/194991137-cdac4c8d-b539-4543-a162-f9106fa8cf21.png">

Dropped Linkerd-service-mirror
![Uploading image.png…]()

### output of `linkerd check -o short`

Linkerd core checks
===================

W1011 10:36:32.421447    3893 gcp.go:120] WARNING: the gcp auth plugin is deprecated in v1.22+, unavailable in v1.25+; use gcloud instead.
To learn more, consult https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ control plane pods are ready
√ cluster networks contains all node podCIDRs
√ cluster networks contains all pods

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ proxy-init container runs as root user if docker container runtime is used

linkerd-identity
----------------
√ certificate config is valid
√ trust anchors are using supported crypto algorithm
√ trust anchors are within their validity period
√ trust anchors are valid for at least 60 days
√ issuer cert is using supported crypto algorithm
√ issuer cert is within its validity period
√ issuer cert is valid for at least 60 days
√ issuer cert is issued by the trust anchor

linkerd-webhooks-and-apisvc-tls
-------------------------------
√ proxy-injector webhook has valid cert
√ proxy-injector cert is valid for at least 60 days
√ sp-validator webhook has valid cert
√ sp-validator cert is valid for at least 60 days
√ policy-validator webhook has valid cert
√ policy-validator cert is valid for at least 60 days

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ can retrieve the control plane version
√  control plane is up-to-date
    is running version 2.12.0 but the latest stable version is 2.12.1
    see https://linkerd.io/2.12/checks/#l5d-version-control for hints
√ control plane and cli versions match
    control plane running stable-2.12.0 but cli running stable-2.12.1
    see https://linkerd.io/2.12/checks/#l5d-version-control for hints

linkerd-control-plane-proxy
---------------------------
√ control plane proxies are healthy
√ control plane proxies are up-to-date
    some proxies are not running the current version:
	* linkerd-destination-58b97c96c-dxffw (stable-2.12.0)
	* linkerd-identity-6f458497df-t4ljj (stable-2.12.0)
	* linkerd-proxy-injector-69c84895f7-5x5pq (stable-2.12.0)
    see https://linkerd.io/2.12/checks/#l5d-cp-proxy-version for hints
√ control plane proxies and cli versions match
    linkerd-destination-58b97c96c-dxffw running stable-2.12.0 but cli running stable-2.12.1
    see https://linkerd.io/2.12/checks/#l5d-cp-proxy-cli-version for hints

Linkerd extensions checks
=========================

linkerd-viz
-----------
√ linkerd-viz Namespace exists
√ linkerd-viz ClusterRoles exist
√ linkerd-viz ClusterRoleBindings exist
√ tap API server has valid cert
√ tap API server cert is valid for at least 60 days
√ tap API service is running
√ linkerd-viz pods are injected
√ viz extension pods are running
√ viz extension proxies are healthy
√ viz extension proxies are up-to-date
    some proxies are not running the current version:
	* metrics-api-848b5556d9-p7p9s (stable-2.12.0)
	* prometheus-5897c87d4f-pjtdv (stable-2.12.0)
	* tap-679c979b8c-6k6g2 (stable-2.12.0)
	* tap-injector-76d68b465d-r874z (stable-2.12.0)
	* web-77c7ff79cb-hn25f (stable-2.12.0)
    see https://linkerd.io/2.12/checks/#l5d-viz-proxy-cp-version for hints
√ viz extension proxies and cli versions match
    metrics-api-848b5556d9-p7p9s running stable-2.12.0 but cli running stable-2.12.1
    see https://linkerd.io/2.12/checks/#l5d-viz-proxy-cli-version for hints
√ can initialize the client
√ viz extension self-check

Status check results are √

### Environment

- kubernetes v.1.22 
-  GKE
-  Linux
-  Linkerd v.2.12.0

### Would you like to work on fixing this bug?

no

**Comment by adleong** [comment]
Hi @roombiotank 

Unfortunately, I don't think I understand what the problem is that you're reporting.  Can you state specifically what you're trying to do and what isn't working as expected?

I also recommend running data plane checks as well:

```
linkerd check --proxy
linkerd viz check --proxy
```
