### ISSUE TITLE
Remove kubectl version check from linkerd check

### ISSUE THREAD

**Issue by jeremychase** [linkerd/linkerd2#9616]
The `linkerd check` command [verifies that kubectl meets the version found](https://github.com/linkerd/linkerd2/blob/c492bdb290359b6ffb665a813dc1503c45c9ad5d/pkg/healthcheck/healthcheck.go#L542-L549) in [pkg/k8s/api.go](https://github.com/linkerd/linkerd2/blob/c492bdb290359b6ffb665a813dc1503c45c9ad5d/pkg/k8s/api.go#L30). This check is no longer necessary because the CLI no longer exec's `kubectl`.

We want to remove the check and any dead code that results.

Related to Website issue [#1510](https://github.com/linkerd/website/issues/1510)

**Comment by ziollek** [comment]
@jeremychase pls verify my [PR](https://github.com/linkerd/linkerd2/pull/9623).
