### ISSUE TITLE
Enabling LinkerD on a large service causes outages

### ISSUE THREAD

**Issue by MarkSRobinson** [linkerd/linkerd2#9652]
### What is the issue?

If I have a large service (100+ pods, 200-500 RPS per pod) and turn on Linkerd you will get immediate outages.

What happens is that the first pod to come online with linkerd will cause 100% of the traffic to be sent to that single pod.  This will cause either the pod itself or the linkerd sidecar to immediately fail.  As other pods come online, they will immediately get huge surges of load and crash.  Eventually the service will stabilize (maybe) but you are looking at a considerable outage until enough pods can come online without crashing.

### How can it be reproduced?

1. Setup a service without linkerd
2. Generate a huge amount of traffic to the service such that a single pod can't handle the load (1k-10k+ RPS).  
3. Change the deployment spec to enable LinkerD injection
4. BOOM - your new pods will start blowing out due to the high load 

### Logs, error output, etc

This happened a while ago and I don't have the logs.

One key effect is the memory consumption of the sidecar proxy spikes very high.

### output of `linkerd check -o short`

```
Linkerd core checks
===================

linkerd-version
---------------
‼ cli is up-to-date
    is running version 2.11.1 but the latest stable version is 2.12.2
    see https://linkerd.io/2.11/checks/#l5d-version-cli for hints

control-plane-version
---------------------
‼ control plane is up-to-date
    is running version 2.10.2 but the latest stable version is 2.12.2
    see https://linkerd.io/2.11/checks/#l5d-version-control for hints
‼ control plane and cli versions match
    control plane running stable-2.10.2 but cli running stable-2.11.1
    see https://linkerd.io/2.11/checks/#l5d-version-control for hints

linkerd-control-plane-proxy
---------------------------
‼ control plane proxies are up-to-date
    some proxies are not running the current version:
	* linkerd-controller-774b6ccd8f-bgw4x (stable-2.10.2)
	* linkerd-controller-774b6ccd8f-cv64j (stable-2.10.2)
	* linkerd-controller-774b6ccd8f-p6f8r (stable-2.10.2)
	* linkerd-destination-5bd97ffbf9-7vt89 (stable-2.10.2)
	* linkerd-destination-5bd97ffbf9-88vvz (stable-2.10.2)
	* linkerd-destination-5bd97ffbf9-pjxnp (stable-2.10.2)
	* linkerd-identity-774c86b48c-66wht (stable-2.10.2)
	* linkerd-identity-774c86b48c-f59tn (stable-2.10.2)
	* linkerd-identity-774c86b48c-h5z8g (stable-2.10.2)
	* linkerd-proxy-injector-74fcd7c577-5zdv2 (stable-2.10.2)
	* linkerd-proxy-injector-74fcd7c577-xbn2q (stable-2.10.2)
	* linkerd-proxy-injector-74fcd7c577-zqcv9 (stable-2.10.2)
	* linkerd-sp-validator-77c69687cb-4jzwx (stable-2.10.2)
	* linkerd-sp-validator-77c69687cb-dknvb (stable-2.10.2)
	* linkerd-sp-validator-77c69687cb-hlfvx (stable-2.10.2)
    see https://linkerd.io/2.11/checks/#l5d-cp-proxy-version for hints
‼ control plane proxies and cli versions match
    linkerd-controller-774b6ccd8f-bgw4x running stable-2.10.2 but cli running stable-2.11.1
    see https://linkerd.io/2.11/checks/#l5d-cp-proxy-cli-version for hints

Status check results are √

Linkerd extensions checks
=========================

linkerd-viz
-----------
‼ viz extension proxies are up-to-date
    some proxies are not running the current version:
	* metrics-api-6765f74fb9-zmg2c (stable-2.10.2)
	* tap-595d8c9cbb-b5qk4 (stable-2.10.2)
	* tap-595d8c9cbb-s2vvs (stable-2.10.2)
	* tap-595d8c9cbb-wbbmd (stable-2.10.2)
	* tap-injector-64cdd794fd-bpzxt (stable-2.10.2)
	* web-5d8888c958-dw4xx (stable-2.10.2)
    see https://linkerd.io/2.11/checks/#l5d-viz-proxy-cp-version for hints
‼ viz extension proxies and cli versions match
    metrics-api-6765f74fb9-zmg2c running stable-2.10.2 but cli running stable-2.11.1
    see https://linkerd.io/2.11/checks/#l5d-viz-proxy-cli-version for hints

Status check results are √
```

### Environment

- Kubernetes 1.17-1.20
- Linkerd 2.10, 2.11
- Cilium CNI
- Golang services, serving gRPC requests

### Possible solution

To work around this we wrote a tool to duplicate services.

We created a secondary ingress service (on a separate ELB), and then copy the service objects (ingress, deployment, service) as 'duplicates' with a weighted DNS set to 0 weight.  We then spin up pods such that we have the original service serving traffic, and duplicate service (duplicate in everything) but serving zero traffic.  We then adjust the DNS weighting to go the other ingress.  Eventually all the traffic is on the duplicate service.

At this point, we upgrade the service to linkerd and swap out the pods.  So the original service now has linkerd injected but no traffic.  We then gradually shift the traffic back to the original service, and tear down the duplicate.

The whole process takes several hours and is about as fun as it sounds. 

LinkerD needs some sort of start-up mode where it doesn't immediately pull in all traffic so that it can be ramped up gracefully.

### Additional context

I spoke with Flynn at Bouyant about this a few days ago and he asked me to open a ticket for this.

### Would you like to work on fixing this bug?

no

**Comment by mateiidavid** [comment]
Hey @MarkSRobinson, I think it'd be helpful to have some logs from some of your services to see exactly what the proxy's doing in this scenario. 

> What happens is that the first pod to come online with linkerd will cause 100% of the traffic to be sent to that single pod. This will cause either the pod itself or the linkerd sidecar to immediately fail

Just to start with the obvious, have you looked at what destination the packets have after leaving the client pod(s)? If you look through the client pod proxy logs (`linkerd=debug,warn` is a good log verbosity levels), is the target always the same pod? Is it the service (ClusterIP)?

> Environment
Cilium CNI

Are you running Cilium in eBPF mode? AFAIK, in some scenarios Cilium will re-write your destination IP to forward traffic directly to an endpoint. It implements transparent proxying itself (i.e it acts as a [kube-proxy replacement](https://docs.cilium.io/en/v1.10/gettingstarted/kubeproxy-free/)) and makes the decision before Linkerd actually has a chance to look at the traffic. If this is the case, Linkerd's simply forwarding traffic to the IP address on the client packet -- if Cilium intervenes, that will be a single endpoint -- under normal conditions this should be a ClusterIP service, which gets translated by Linkerd into the actual endpoints it needs to forward to.

**Comment by MarkSRobinson** [comment]
@migueleliasweb That's exactly what I do.  I wrote a simple tool to duplicate the service, then I can adjust the DNS weight on the ingress to move to the traffic to the new service.  It's a huge pain and requires special handling outside of the regular workflow of deploying an application.
