### ISSUE TITLE
linkerd viz  dashboard show no metrics data when upgrade to 2.12.2

### ISSUE THREAD

**Issue by aries1998** [linkerd/linkerd2#9660]
### What is the issue?

when upgrade linkerd, linkerd-viz from 2.12.1 to 2.12.2 with helm, the viz dashboard show no metric data.

linkerd check and linkerd viz check ok

tap works fine 

the external prometheus can pull the linkerd/linkerd-viz related metrics

can query linkerd proxy data from  prometheus like "http_client_requests_total"

### How can it be reproduced?

using helm upgrade linkerd, linkerd viz from 2.12.1 to 2.12.2

```
helm upgrade --reset-values --atomic linkerd-crds linkerd/linkerd-crds -n linkerd
helm upgrade --reset-values --atomic --set-file identityTrustAnchorsPEM=ca.crt --set-file identity.issuer.tls.crtPEM=issuer.crt --set-file identity.issuer.tls.keyPEM=issuer.key linkerd-control-plane linkerd/linkerd-control-plane -n linkerd
helm upgrade --reset-values --atomic -f values_linkerd_viz.yaml linkerd-viz linkerd/linkerd-viz -n linkerd-viz
```

```
root@k8s-master:~/.../workspace/k8s/linkerd# cat values_linkerd_viz.yaml
prometheus:
  enabled: false
prometheusUrl: http://prometheus-stack-kube-prom-prometheus.monitor.svc.cluster.local:9090
```

### Logs, error output, etc

linkerd check , linkerd viz check both ok
```
root@k8s-master:~/.../workspace/k8s/linkerd# linkerd check -o short
Status check results are √
root@k8s-master:~/.../workspace/k8s/linkerd# linkerd viz  check -o short
Status check results are √
```
use linkerd cli is the same , no metrics
```
root@k8s-master:~/.../workspace/k8s/linkerd# linkerd viz list -A
Pods with tap enabled:
        * emojivoto/emoji-699d77c79-bdhns
        * emojivoto/vote-bot-b57689ffb-v7982
        * emojivoto/voting-55d76f4bcb-ldm9r
        * emojivoto/web-6c54d9554d-z44bk
        * linkerd-viz/metrics-api-5b9cf77bb-m7zgx
        * linkerd-viz/tap-79c7b9b6c7-nx9bm
        * linkerd-viz/tap-injector-c8d9cd5b6-2nplw
        * linkerd-viz/web-7f7bbbcdfd-vmh2w
        * linkerd/linkerd-destination-58f749c4b7-qnpnz
        * linkerd/linkerd-identity-7d85cbc9fb-n295q
        * linkerd/linkerd-proxy-injector-7675675d99-kbd9k
root@k8s-master:~/.../workspace/k8s/linkerd# linkerd viz stat ns/emojivoto
NAME        MESHED   SUCCESS   RPS   LATENCY_P50   LATENCY_P95   LATENCY_P99   TCP_CONN
emojivoto      4/4         -     -             -             -             -          -
```

### output of `linkerd check -o short`

linkerd check , linkerd viz check both ok
```
root@k8s-master:~/.../workspace/k8s/linkerd# linkerd check -o short
Status check results are √
root@k8s-master:~/.../workspace/k8s/linkerd# linkerd viz  check -o short
Status check results are √
```

### Environment

k8s: 1.24.6
linkerd/linkerd-viz: 2.12.2

**Comment by aries1998** [comment]
and in viz dashboard , there's no metrics of http data only , the tcp data seems ok

**Comment by mdimarino** [comment]
also, follow the documentation example for traffic split at https://linkerd.io/2.12/tasks/linkerd-smi/

when it tries to show stats for the `ts` using command line an error happens:

`Error: error creating metrics request while making stats request: cannot find Kubernetes canonical name from friendly name [ts]`

**Comment by subbufrom** [comment]
Even i am facing the same issue, can some one help on this

**Comment by subbufrom** [comment]
@olix0r , @jeremychase !! , can you guys help on this ?

**Comment by realhuseyn** [comment]
I have this problem, too

**Comment by subbufrom** [comment]
I got this working, by changing the global scrape interval of prometheus from 1m to 10s.

global:
    ## How frequently to scrape targets by default
    ##
    scrape_interval: 10s
    ## How long until a scrape request times out
    ##
    scrape_timeout: 10s
    ## How frequently to evaluate rules
    ##
    evaluation_interval: 10s

**Comment by subbufrom** [comment]
It would be great if linkerd-viz provides changing window value from the default value for all its apis to display metrics on dashboard,

**Comment by adleong** [comment]
Nice find, @subbufrom!

We should definitely add an item to our external Prometheus docs describing how short the scrape interval needs to be for the dashboard to work: 
https://linkerd.io/2.12/tasks/external-prometheus/
https://github.com/linkerd/website/blob/main/linkerd.io/content/2.12/tasks/external-prometheus.md

I believe that the query window used by the dashboard is 1m.  Therefore I'd probably recommend a scrape interval of <30s.

Are you interested in contributing this to the docs?

**Comment by realhuseyn** [comment]
@subbufrom thank you very much, man! Finally, I can see metrics after changing intervals of Prometheus scraping
