### ISSUE TITLE
GRPC load balancing doesn't work with Calico

### ISSUE THREAD

**Issue by kandeshvari** [linkerd/linkerd2#9674]
### What is the issue?

When I use Calico CNI all GRPC requests go to one pod instead of balancing between all pods behind a `Service`

I see this line in the logs in broken setup:
```
[     0.204913s] DEBUG ThreadId(01) outbound:accept{client.addr=172.25.229.60:42842}:proxy{addr=172.25.240.43:50051}: linkerd_cache: Caching new value key=Accept { orig_dst: OrigDstAddr(172.25.240.43:50051), protocol: () }
```

And this line in correctly working setup:
```
[     0.184450s] DEBUG ThreadId(01) outbound:accept{client.addr=172.27.102.88:44572}:proxy{addr=10.106.182.82:50051}: linkerd_cache: Caching new value key=Accept { orig_dst: OrigDstAddr(10.106.182.82:50051), protocol: () }
```

In the first line linkerd-proxy uses `Pod` address (172.25.240.43:50051). In the second line linkerd-proxy uses `Service` address (10.106.182.82:50051).

### How can it be reproduced?

Install linkerd in Calico and try to send grpc requests to a grpc service behind a kubernetes `Service`.

### Logs, error output, etc

first appearance of the pod address in the client's linkerd-proxy log:

```
[     0.204913s] DEBUG ThreadId(01) outbound:accept{client.addr=172.25.229.60:42842}:proxy{addr=172.25.240.43:50051}: linkerd_cache: Caching new value key=Accept { orig_dst: OrigDstAddr(172.25.240.43:50051), protocol: () }
```

### output of `linkerd check -o short`

```
Linkerd core checks
===================

linkerd-version
---------------
‼ cli is up-to-date
    is running version 2.12.1 but the latest stable version is 2.12.2
    see https://linkerd.io/2.12/checks/#l5d-version-cli for hints

control-plane-version
---------------------
‼ control plane is up-to-date
    is running version 2.12.1 but the latest stable version is 2.12.2
    see https://linkerd.io/2.12/checks/#l5d-version-control for hints

linkerd-control-plane-proxy
---------------------------
‼ control plane proxies are up-to-date
    some proxies are not running the current version:
	* linkerd-destination-788d67674-nx9r9 (stable-2.12.1)
	* linkerd-identity-7d54bd547-lkvrw (stable-2.12.1)
	* linkerd-proxy-injector-7cf8cf457c-hjht5 (stable-2.12.1)
    see https://linkerd.io/2.12/checks/#l5d-cp-proxy-version for hints

Linkerd extensions checks
=========================

linkerd-viz
-----------
‼ viz extension proxies are up-to-date
    some proxies are not running the current version:
	* metrics-api-cbb5cdd44-tljc9 (stable-2.12.1)
	* prometheus-796c56d568-tp58f (stable-2.12.1)
	* tap-775d89cc78-spp5k (stable-2.12.1)
	* tap-injector-599fdd646b-b84wp (stable-2.12.1)
	* web-7666f68d74-qbfjs (stable-2.12.1)
    see https://linkerd.io/2.12/checks/#l5d-viz-proxy-cp-version for hints

Status check results are √
```

### Environment

- kubernetes v1.22.2
- on-prem installation
- OS Debian Linux 10
- linkerd: stable-2.12.1

**Comment by mateiidavid** [comment]
@kandeshvari thanks for raising this. Can you give us a bit more information about your set-up? Specifically, you seem to have a "working" scenario, what's different there? Is it a non-gRPC workload?

Linkerd reacts and forwards traffic by analysing the packet. It uses the `SO_ORIGINAL_DST` socket option to get the (original) destination. If your packet is going to a pod, Linkerd will forward traffic to a pod. If it's a `Service` IP, it will send traffic to all of the service's endpoints. In other words, Linkerd does not handle any DNS, and it doesn't do any target re-writes.

If we want to debug this further, it would be helpful to get logs in a more verbose output (`linkerd=debug,warn` for your "client" proxy). It would also be helpful to run a tcpdump/tshark in your network namespace to try and pick up the target on the packets that leave your main process. For the logs, you'll get a lot of output, I'd be interested first to see what "profile" the proxy resolves the IP address to (try to `grep profile`).

Finally, we can do a quick troubleshoot by looking at your Calico configuration. Are you running Calico in [eBPF mode](https://projectcalico.docs.tigera.io/maintenance/ebpf/install)? Is it replacing `kube-proxy`? Chances are it might be re-writing your packet headers without you knowing, in which case, the proxy's doing what it is supposed to do.

Unfortunately, with these issues there's not much we can do without a concrete repro. I can help you troubleshoot further; the steps above should give us a good foundation to pin down the problem.

**Comment by kandeshvari** [comment]
@mateiidavid thank you for the fast answer!

Yes, I ran calico in eBPF mode, and it replaced the `kube-proxy`.

I have two clusters of the same version 1.22.2. One with calico eBPF and simple `bridge-cni` on another.

Here are logs for calico and bridge-cni clusters:

```
$ cat calico-client-proxy.log | grep profile
[     0.173181s] DEBUG ThreadId(01) outbound:accept{client.addr=172.25.229.67:40260}:proxy{addr=172.25.229.37:50051}: linkerd_app_outbound::discover: Allowing profile lookup
[     0.177387s] DEBUG ThreadId(01) outbound:accept{client.addr=172.25.229.67:40260}:proxy{addr=172.25.229.37:50051}: linkerd_service_profiles::client: Resolved profile


$ cat no-calico-client-proxy.log | grep profile
[     0.184605s] DEBUG ThreadId(01) outbound:accept{client.addr=172.27.102.88:44572}:proxy{addr=10.106.182.82:50051}: linkerd_app_outbound::discover: Allowing profile lookup
[     1.296941s] DEBUG ThreadId(01) outbound:accept{client.addr=172.27.102.88:44572}:proxy{addr=10.106.182.82:50051}: linkerd_service_profiles::client: Resolved profile
[     1.297073s] DEBUG ThreadId(01) outbound:accept{client.addr=172.27.102.88:44572}:proxy{addr=10.106.182.82:50051}:http{v=h2}:logical{dst=grpc-server.grpc-test.svc.cluster.local:50051}: linkerd_cache: Caching new value key=Logical { protocol: H2, profile: .., logical_addr: LogicalAddr(grpc-server.grpc-test.svc.cluster.local:50051) }
[     1.297379s] DEBUG ThreadId(01) evict{key=Logical { protocol: H2, profile: .., logical_addr: LogicalAddr(grpc-server.grpc-test.svc.cluster.local:50051) }}: linkerd_cache: Awaiting idleness
[     2.084205s] DEBUG ThreadId(01) outbound:accept{client.addr=172.27.102.88:44596}:proxy{addr=10.106.182.82:50051}:http{v=h2}:logical{dst=grpc-server.grpc-test.svc.cluster.local:50051}: linkerd_service_profiles::http::service: Updating HTTP routes routes=1
[     2.084255s] DEBUG ThreadId(01) outbound:accept{client.addr=172.27.102.88:44596}:proxy{addr=10.106.182.82:50051}:http{v=h2}:logical{dst=grpc-server.grpc-test.svc.cluster.local:50051}: linkerd_service_profiles::split: Updating targets=[Target { addr: grpc-server.grpc-test.svc.cluster.local:50051, weight: 1000000 }]
```

Is there a chance to run linked alongside calico eBPF? Maybe I can tweak calico somehow?

**Comment by mateiidavid** [comment]
@kandeshvari we're going to be looking into this a little bit. Off the top of my head, you should be able to skip socket load balancing when in a pod's network namespace. I'm not sure if Calico surfaces this as a configuration option. You can have a look at how that's achieved in Cilium:  https://github.com/cilium/cilium/pull/17154.

Another option would be to _not_ use Calico's kube-proxy replacement. Until we have a better idea of the path forward here, I can't really offer any other suggestions. I'm not that knowledgeable in Calico's configuration options. As far as requirements and correctness goes, Linkerd is doing (what it thinks is) the correct thing, it just forwards to the IP address on the packet.

We'll spend a bit of time looking at what we can do to make them work better together even in the face of weird configuration options :)

**Comment by mateiidavid** [comment]
@kandeshvari going to close this out now. We have an issue in the backlog to emit a warning when Cilium / Calico use eBPF mode. Both work differently so until we find a consistent way to advertise this to users, you'll just have to check on your own. Unfortunately neither of them provides an easy way to programatically check for the option.

There isn't much else we can do here; to let Linkerd route, we need to skip load balancing at the socket/tc level. Thanks for raising this though :D
