### ISSUE TITLE
endpoint_pods metric showing an incorrect count

### ISSUE THREAD

**Issue by dwilliams782** [linkerd/linkerd2#9707]
### What is the issue?

Following the issue we had in https://github.com/linkerd/linkerd2/issues/8956 where we had incorrect endpoints, we set up an alert that relies on the controller metric endpoint_pods to ensure the destination pods have the correct number of endpoints.

This alert has just fired for one service in particular (for the first time, we recently upgraded to 2.12.2, may or may not be a coincidence).

The service currently has 8 pods running:

```
>k get pods -n frontend | grep sunrise | wc -l
8
```

The controller metrics (we have three replicas) shows 9 pods for this service on each destination replica:

```
>linkerd diagnostics controller-metrics | grep 'endpoints_pods{hostname="",namespace="frontend",port="3000",service="sunrise"}'

endpoints_pods{hostname="",namespace="frontend",port="3000",service="sunrise"} 9
endpoints_pods{hostname="",namespace="frontend",port="3000",service="sunrise"} 9
endpoints_pods{hostname="",namespace="frontend",port="3000",service="sunrise"} 9
```

However, if I query each destination pod for endpoints directly, we get the correct count:

```
>linkerd diagnostics endpoints sunrise.frontend.svc.cluster.local --destination-pod linkerd-destination-54768476cf-srhf9 | grep sunrise | wc -l
8
>linkerd diagnostics endpoints sunrise.frontend.svc.cluster.local --destination-pod linkerd-destination-54768476cf-nsfs8 | grep sunrise | wc -l
8
>linkerd diagnostics endpoints sunrise.frontend.svc.cluster.local --destination-pod linkerd-destination-54768476cf-pwhwx | grep sunrise | wc -l
8
```

The following graph shows the replica count vs endpoint metric, it diverged at ~ 11:16

![image](https://user-images.githubusercontent.com/42545485/198013174-364acff2-0003-4d40-8e21-4dc0a6c159cf.png)

The destination logs contain the following:

```
2022-10-26 11:15:48 | linkerd-destination-54768476cf-nsfs8 time="2022-10-26T10:15:48Z" level=error msg="Unable to create new address:unable to fetch pod frontend/sunrise-7944c9c95b-6hrfs: pod \"sunrise-7944c9c95b-6hrfs\" not found" addr=":8086" component=service-publisher ns=frontend port=3000 svc=sunrise

2022-10-26 11:15:48 | linkerd-destination-54768476cf-pwhwx time="2022-10-26T10:15:48Z" level=error msg="Unable to create new address:unable to fetch pod frontend/sunrise-7944c9c95b-6hrfs: pod \"sunrise-7944c9c95b-6hrfs\" not found" addr=":8086" component=service-publisher ns=frontend port=3000 svc=sunrise

2022-10-26 11:15:48 | linkerd-destination-54768476cf-srhf9 time="2022-10-26T10:15:48Z" level=error msg="Unable to create new address:unable to fetch pod frontend/sunrise-7944c9c95b-6hrfs: pod \"sunrise-7944c9c95b-6hrfs\" not found" addr=":8086" component=service-publisher ns=frontend port=3000 svc=sunrise
```

### How can it be reproduced?

Unknown

### Logs, error output, etc

```
2022-10-26 11:15:48 | linkerd-destination-54768476cf-nsfs8 time="2022-10-26T10:15:48Z" level=error msg="Unable to create new address:unable to fetch pod frontend/sunrise-7944c9c95b-6hrfs: pod \"sunrise-7944c9c95b-6hrfs\" not found" addr=":8086" component=service-publisher ns=frontend port=3000 svc=sunrise

2022-10-26 11:15:48 | linkerd-destination-54768476cf-pwhwx time="2022-10-26T10:15:48Z" level=error msg="Unable to create new address:unable to fetch pod frontend/sunrise-7944c9c95b-6hrfs: pod \"sunrise-7944c9c95b-6hrfs\" not found" addr=":8086" component=service-publisher ns=frontend port=3000 svc=sunrise

2022-10-26 11:15:48 | linkerd-destination-54768476cf-srhf9 time="2022-10-26T10:15:48Z" level=error msg="Unable to create new address:unable to fetch pod frontend/sunrise-7944c9c95b-6hrfs: pod \"sunrise-7944c9c95b-6hrfs\" not found" addr=":8086" component=service-publisher ns=frontend port=3000 svc=sunrise
```

### output of `linkerd check -o short`

```
Status check results are √
```

### Environment

- Linkerd version: 2.12.2
- Kubernetes version: v1.22.12-gke.1200

**Comment by kleimkuhler** [comment]
So in #8956 we could only reproduce this issue with the otel-agent DaemonSet. I have a few questions to dig into this further.

1. Is this "frontend" different than the original otel-agent? Is it a DaemonSet, or does it just have multiple replicas on the same Node? 
2. Was a Node deleted, similar to before, or were Pods just spinning up and down?
3. Now that you're on 2.12.2, are you changing anything about enabling EndpointSlices? It defaults to `true` in this version so I want to make sure that it _is_ still enabled.
4. Does "frontend" have multiple ports? It was [mentioned](https://github.com/linkerd/linkerd2/issues/8956#issuecomment-1213072403) that multiple ports were exposed on the workload causing these issues before.

I'd love to help debug this more, but similar to my [comment](https://github.com/linkerd/linkerd2/issues/8956#issuecomment-1212427347) before using nginx, I couldn't get any sort of reproduction—and that is still the case. Are you able to provide manifests for deploying "frontend" or something else that I could reproduce locally?

Sorry you're running into this again and hopefully we can make progress on it.

**Comment by dwilliams782** [comment]
Hey @kleimkuhler,

This issue differs from #8956 in that, each destination pod has the correct number of pods, but the metric `endpoints_pods` reports incorrect. In #8956 the destination pods were actually showing incorrect pods.

We do have endpointSlices enabled as per default now. Only one port on the service I mentioned in this report. There appears to be no correlation between pods restarting / nodes restarting and this happening but I will dig further when I get some time ASAP.

The metric showing the incorrect count is happening very sporadically and we wouldn't know about it if we weren't alerting on it via Prometheus / Alertmanager. If you have access to a Prom / AM set up (we remote write linkerd metrics to our prom set up) in a busy cluster, you might be able to run into this too. Following is the alertmanager rule:

```
        - alert: DestinationEndpointsIncorrect
          annotations:
            summary: Destination pod {{ $labels.pod }}  has an incorrect pod count for {{ $labels.namespace }}/{{ $labels.endpoint }} for more than 30m
            description: When a destination pod shows a different count to the amount of pods for a service for a prolonged period, it indicates stale IPs and the destination pod should be restarted.
          expr: |
            sum(label_replace(label_replace(linkerd_endpoints_pods, "endpoint", "$1", "service", "(.+)"), "namespace", "$1", "exported_namespace", "(.+)")) by (pod, namespace, endpoint) - ignoring (pod) group_left() (kube_endpoint_address_available / on (namespace, endpoint) sum(kube_endpoint_ports) by (namespace, endpoint)) != 0
          for: 30m
          labels:
            team: platform-infrastructure
```

Looks messy but essentially we're checking the value of `endpoints_pods` from Linkerd metrics against the actual number of endpoints on `kube_endpoint_address_available`.

Once I've grabbed some time to sift through kube logs and see if anything else is going on, I'll report back. Just wanted to clarify that it's not the same as #8956 in that we're not actually having incorrect endpoints, just the metric is wrong.

**Comment by kleimkuhler** [comment]
Thanks for the clarification. I'll keep an eye out for any updates on this. The code does overlap a little with this metric and a destination controller showing incorrect data, but we'll keep treating them as separate issues until we have a little more information. Also good to know that this doesn't seem related to Node or Pod churn right now.

**Comment by olix0r** [comment]
Was this fixed by https://github.com/linkerd/linkerd2/commit/768e04dd7e148583d5c8e0ea7caa324afdafdae9?

**Comment by kleimkuhler** [comment]
It should have been, yes. It'd be nice if it could be confirmed with the recent edge release that contains it (`edge-23.1.1`), but the tests we added as part of it feel relevant enough that we could close this.

**Comment by dwilliams782** [comment]
Hi both, these were too sporadic to have any confidence if it was fixed but it is the same log warning/error that has been fixed recently so I'm happy for this to be closed. Thanks!
