### ISSUE TITLE
Ensure consistency for client.addr in proxy logs

### ISSUE THREAD

**Issue by dwilliams782** [linkerd/linkerd2#9722]
### What problem are you trying to solve?

I've noticed that where logs contain a `client.addr=<ip:port>`, sometimes this is the local Pod IP, and other times it can be the remote IP. 

For example, the IP shown for these logs map to the source pod IP.:

```
inbound: linkerd_app_core::serve: Connection closed error=connection closed before message completed client.addr=<ip:port>

inbound: linkerd_app_core::serve: Connection closed error=invalid URI client.addr=<ip:port>
```

However this log, the IP reflects the IP of the pod that produced the log.

```
outbound: linkerd_app_core::serve: Connection closed error=connect timed out after 1s client.addr=<ip:port>
```

I assume this is because on the outbound, the local proxy/pod is considered the client, but it would be more useful IMO to always show the IP we are either trying to connect to or receiving requests from. For the timed out after 1s log, it would be useful to know what it is trying to connect to.

### How should the problem be solved?

Either always show the source / destination IP, always show the local IP, or update the docs to understand why this is the behaviour.

**Comment by jeremychase** [comment]
We put this into 2.14 with a P1 priority because we feel this change will improve debug-ability for 2.14 work.
