### ISSUE TITLE
Missing labels for response_latency_ms_bucket

### ISSUE THREAD

**Issue by bjor-joh** [linkerd/linkerd2#9737]
### What is the issue?

Is the response_latency_ms_bucket proxy metric suppose to have grpc_status as a label? Or is that only present on response_total ?
According to the [documentation](https://linkerd.io/2.12/reference/proxy-metrics/#response-labels) all `response_*` metrics  should have `status_code, grpc_status_code and classification`, 

But I can only se `status_code`. `grpc_status` and `classification` is missing. 

If I look at the same service but at the `response_total` metric the labels are populated correctly. 

It's a bit problematic because then I can filter on response time for successful requests separately. Is it a bug or is the documentation not up to date?

I have tried with both grpc and rest services and both display a similar behaviour. 

### How can it be reproduced?

Scrape metric from any linkerd-proxy. `response_latency_ms_bucket` entries are missing classification and grpc_status label. 

### Logs, error output, etc

Here's an example from the `/metrics` endpoint for one of our services that uses grpc

```
response_latency_ms_bucket{direction="inbound",authority="AUTHORITY",target_addr="IP:50051",target_ip="IP",target_port="50051",tls="true",client_id="CLIENT_ID",srv_name="default:all-unauthenticated",saz_name="default:all-unauthenticated",status_code="200",le="1"} 31
response_latency_ms_bucket{direction="inbound",authority="AUTHORITY",target_addr="IP:50051",target_ip="IP",target_port="50051",tls="true",client_id="CLIENT_ID",srv_name="default:all-unauthenticated",saz_name="default:all-unauthenticated",status_code="200",le="2"} 7824
response_latency_ms_bucket{direction="inbound",authority="AUTHORITY",target_addr="IP:50051",target_ip="IP",target_port="50051",tls="true",client_id="CLIENT_ID",srv_name="default:all-unauthenticated",saz_name="default:all-unauthenticated",status_code="200",le="3"} 13366
response_latency_ms_bucket{direction="inbound",authority="AUTHORITY",target_addr="IP:50051",target_ip="IP",target_port="50051",tls="true",client_id="CLIENT_ID",srv_name="default:all-unauthenticated",saz_name="default:all-unauthenticated",status_code="200",le="4"} 17149
response_latency_ms_bucket{direction="inbound",authority="AUTHORITY",target_addr="IP:50051",target_ip="IP",target_port="50051",tls="true",client_id="CLIENT_ID",srv_name="default:all-unauthenticated",saz_name="default:all-unauthenticated",status_code="200",le="5"} 21215
response_latency_ms_bucket{direction="inbound",authority="AUTHORITY",target_addr="IP:50051",target_ip="IP",target_port="50051",tls="true",client_id="CLIENT_ID",srv_name="default:all-unauthenticated",saz_name="default:all-unauthenticated",status_code="200",le="10"} 37810
response_latency_ms_bucket{direction="inbound",authority="AUTHORITY",target_addr="IP:50051",target_ip="IP",target_port="50051",tls="true",client_id="CLIENT_ID",srv_name="default:all-unauthenticated",saz_name="default:all-unauthenticated",status_code="200",le="20"} 53747
response_latency_ms_bucket{direction="inbound",authority="AUTHORITY",target_addr="IP:50051",target_ip="IP",target_port="50051",tls="true",client_id="CLIENT_ID",srv_name="default:all-unauthenticated",saz_name="default:all-unauthenticated",status_code="200",le="30"} 65601
response_latency_ms_bucket{direction="inbound",authority="AUTHORITY",target_addr="IP:50051",target_ip="IP",target_port="50051",tls="true",client_id="CLIENT_ID",srv_name="default:all-unauthenticated",saz_name="default:all-unauthenticated",status_code="200",le="40"} 75666
response_latency_ms_bucket{direction="inbound",authority="AUTHORITY",target_addr="IP:50051",target_ip="IP",target_port="50051",tls="true",client_id="CLIENT_ID",srv_name="default:all-unauthenticated",saz_name="default:all-unauthenticated",status_code="200",le="50"} 81597
response_latency_ms_bucket{direction="inbound",authority="AUTHORITY",target_addr="IP:50051",target_ip="IP",target_port="50051",tls="true",client_id="CLIENT_ID",srv_name="default:all-unauthenticated",saz_name="default:all-unauthenticated",status_code="200",le="100"} 96465
response_latency_ms_bucket{direction="inbound",authority="AUTHORITY",target_addr="IP:50051",target_ip="IP",target_port="50051",tls="true",client_id="CLIENT_ID",srv_name="default:all-unauthenticated",saz_name="default:all-unauthenticated",status_code="200",le="200"} 103953
response_latency_ms_bucket{direction="inbound",authority="AUTHORITY",target_addr="IP:50051",target_ip="IP",target_port="50051",tls="true",client_id="CLIENT_ID",srv_name="default:all-unauthenticated",saz_name="default:all-unauthenticated",status_code="200",le="300"} 105672
response_latency_ms_bucket{direction="inbound",authority="AUTHORITY",target_addr="IP:50051",target_ip="IP",target_port="50051",tls="true",client_id="CLIENT_ID",srv_name="default:all-unauthenticated",saz_name="default:all-unauthenticated",status_code="200",le="400"} 106304
response_latency_ms_bucket{direction="inbound",authority="AUTHORITY",target_addr="IP:50051",target_ip="IP",target_port="50051",tls="true",client_id="CLIENT_ID",srv_name="default:all-unauthenticated",saz_name="default:all-unauthenticated",status_code="200",le="500"} 106619
response_latency_ms_bucket{direction="inbound",authority="AUTHORITY",target_addr="IP:50051",target_ip="IP",target_port="50051",tls="true",client_id="CLIENT_ID",srv_name="default:all-unauthenticated",saz_name="default:all-unauthenticated",status_code="200",le="1000"} 107155
response_latency_ms_bucket{direction="inbound",authority="AUTHORITY",target_addr="IP:50051",target_ip="IP",target_port="50051",tls="true",client_id="CLIENT_ID",srv_name="default:all-unauthenticated",saz_name="default:all-unauthenticated",status_code="200",le="2000"} 107454
response_latency_ms_bucket{direction="inbound",authority="AUTHORITY",target_addr="IP:50051",target_ip="IP",target_port="50051",tls="true",client_id="CLIENT_ID",srv_name="default:all-unauthenticated",saz_name="default:all-unauthenticated",status_code="200",le="3000"} 107459
response_latency_ms_bucket{direction="inbound",authority="AUTHORITY",target_addr="IP:50051",target_ip="IP",target_port="50051",tls="true",client_id="CLIENT_ID",srv_name="default:all-unauthenticated",saz_name="default:all-unauthenticated",status_code="200",le="4000"} 107459
response_latency_ms_bucket{direction="inbound",authority="AUTHORITY",target_addr="IP:50051",target_ip="IP",target_port="50051",tls="true",client_id="CLIENT_ID",srv_name="default:all-unauthenticated",saz_name="default:all-unauthenticated",status_code="200",le="5000"} 107459
response_latency_ms_bucket{direction="inbound",authority="AUTHORITY",target_addr="IP:50051",target_ip="IP",target_port="50051",tls="true",client_id="CLIENT_ID",srv_name="default:all-unauthenticated",saz_name="default:all-unauthenticated",status_code="200",le="10000"} 107459
response_latency_ms_bucket{direction="inbound",authority="AUTHORITY",target_addr="IP:50051",target_ip="IP",target_port="50051",tls="true",client_id="CLIENT_ID",srv_name="default:all-unauthenticated",saz_name="default:all-unauthenticated",status_code="200",le="20000"} 107459
response_latency_ms_bucket{direction="inbound",authority="AUTHORITY",target_addr="IP:50051",target_ip="IP",target_port="50051",tls="true",client_id="CLIENT_ID",srv_name="default:all-unauthenticated",saz_name="default:all-unauthenticated",status_code="200",le="30000"} 107459
response_latency_ms_bucket{direction="inbound",authority="AUTHORITY",target_addr="IP:50051",target_ip="IP",target_port="50051",tls="true",client_id="CLIENT_ID",srv_name="default:all-unauthenticated",saz_name="default:all-unauthenticated",status_code="200",le="40000"} 107459
response_latency_ms_bucket{direction="inbound",authority="AUTHORITY",target_addr="IP:50051",target_ip="IP",target_port="50051",tls="true",client_id="CLIENT_ID",srv_name="default:all-unauthenticated",saz_name="default:all-unauthenticated",status_code="200",le="50000"} 107459
response_latency_ms_bucket{direction="inbound",authority="AUTHORITY",target_addr="IP:50051",target_ip="IP",target_port="50051",tls="true",client_id="CLIENT_ID",srv_name="default:all-unauthenticated",saz_name="default:all-unauthenticated",status_code="200",le="+Inf"} 107459
```

I would expect these entries to have a `classification` and `grpc_status_code` label

### output of `linkerd check -o short`

Linkerd core checks
===================

linkerd-version
---------------
‼ cli is up-to-date
    is running version 2.11.2 but the latest stable version is 2.12.2
    see https://linkerd.io/2.11/checks/#l5d-version-cli for hints

control-plane-version
---------------------
‼ control plane is up-to-date
    is running version 2.11.2 but the latest stable version is 2.12.2
    see https://linkerd.io/2.11/checks/#l5d-version-control for hints

linkerd-control-plane-proxy
---------------------------
‼ control plane proxies are up-to-date
    some proxies are not running the current version:
	* linkerd-destination-8644f98dbc-644js (stable-2.11.2)
	* linkerd-destination-8644f98dbc-dm9ff (stable-2.11.2)
	* linkerd-destination-8644f98dbc-gz5tp (stable-2.11.2)
	* linkerd-identity-6c55548666-cz9ws (stable-2.11.4)
	* linkerd-identity-6c55548666-n5brv (stable-2.11.4)
	* linkerd-identity-6c55548666-nspns (stable-2.11.4)
	* linkerd-proxy-injector-557789764f-59ztm (stable-2.11.4)
	* linkerd-proxy-injector-557789764f-bfnst (stable-2.11.4)
	* linkerd-proxy-injector-557789764f-gpjrk (stable-2.11.4)
    see https://linkerd.io/2.11/checks/#l5d-cp-proxy-version for hints
‼ control plane proxies and cli versions match
    linkerd-identity-6c55548666-cz9ws running stable-2.11.4 but cli running stable-2.11.2
    see https://linkerd.io/2.11/checks/#l5d-cp-proxy-cli-version for hints

Linkerd extensions checks
=========================

linkerd-multicluster
--------------------
× all gateway mirrors are healthy
        wrong number of (0) gateway metrics entries for probe-gateway-test.linkerd-multicluster
    see https://linkerd.io/2.11/checks/#l5d-multicluster-gateways-endpoints for hints
‼ multicluster extension proxies are up-to-date
    some proxies are not running the current version:
	* linkerd-gateway-549cd6c5b-77frp (stable-2.11.4)
	* linkerd-gateway-549cd6c5b-8jftb (stable-2.11.2)
	* linkerd-gateway-549cd6c5b-9kgwv (stable-2.11.4)
	* linkerd-service-mirror-test-54bcb596f5-t75hm (stable-2.11.4)
    see https://linkerd.io/2.11/checks/#l5d-multicluster-proxy-cp-version for hints
‼ multicluster extension proxies and cli versions match
    linkerd-gateway-549cd6c5b-77frp running stable-2.11.4 but cli running stable-2.11.2
    see https://linkerd.io/2.11/checks/#l5d-multicluster-proxy-cli-version for hints

Linkerd extensions checks
=========================

linkerd-viz
-----------
‼ viz extension proxies are up-to-date
    some proxies are not running the current version:
	* grafana-57b8b967c7-br6g2 (stable-2.11.4)
	* metrics-api-5b694b9cbd-z7f4q (stable-2.11.4)
	* tap-5577884466-mf57r (stable-2.11.4)
	* tap-injector-7767778f4d-xpxtz (stable-2.11.4)
	* web-6fdb44954-qndm9 (stable-2.11.2)
    see https://linkerd.io/2.11/checks/#l5d-viz-proxy-cp-version for hints
‼ viz extension proxies and cli versions match
    grafana-57b8b967c7-br6g2 running stable-2.11.4 but cli running stable-2.11.2
    see https://linkerd.io/2.11/checks/#l5d-viz-proxy-cli-version for hints

Status check results are ×

### Environment

- kubernetes_version 1.22
- cluster_env: GKE
- linkerd_version: 2.11.4

### Additional context

We have it on our todo to upgrade to latest version. If this is a known issues fixed in 2.12 please let me know. 

We are not using the service mirrors at the moment, that's why it's scaled down to 0.

We are using external prometheus and grafana instances.

**Comment by bjor-joh** [comment]
@olix0r 
Any updates on this?

**Comment by adleong** [comment]
This is reproducible with emojivoto:

```
> linkerd install --crds | kubectl apply -f -
> linkerd install | kubectl apply -f -
> linkerd inject https://run.linkerd.io/emojivoto.yml | kubectl apply -f -
> linkerd diagnotics proxy-metrics -n emojivoto po/<emoji pod name>
```

These metrics include the gRPC type labels for the `response_total` metric, indicating that the protocol is being detected as gRPC:

```
response_total{direction="inbound",authority="emoji-svc.emojivoto.svc.cluster.local:8080",target_addr="10.244.125.146:8080",target_ip="10.244.125.146",target_port="8080",tls="true",client_id="web.emojivoto.serviceaccount.identity.linkerd.cluster.local",srv_group="",srv_kind="default",srv_name="all-unauthenticated",route_group="",route_kind="default",route_name="default",authz_group="",authz_kind="default",authz_name="all-unauthenticated",status_code="200",classification="success",grpc_status="0"} 74
```

However, the `classification` and `grpc_status` labels are not present on the corresponding `response_latency_ms_bucket` metrics, for example:

```
response_latency_ms_bucket{direction="inbound",authority="emoji-svc.emojivoto.svc.cluster.local:8080",target_addr="10.244.125.146:8080",target_ip="10.244.125.146",target_port="8080",tls="true",client_id="web.emojivoto.serviceaccount.identity.linkerd.cluster.local",srv_group="",srv_kind="default",srv_name="all-unauthenticated",route_group="",route_kind="default",route_name="default",authz_group="",authz_kind="default",authz_name="all-unauthenticated",status_code="200",le="1"} 73
```

**Comment by hawkw** [comment]
linkerd/linkerd2-proxy#2167 should fix this. :)

**Comment by hawkw** [comment]
Unfortunately, after further discussion, it turns out that we can't move forwards with the simple solution in linkerd-linkerd2-proxy#2167, since it would prevent latencies from being recorded in a timely manner for long-running streaming requests (see https://github.com/linkerd/linkerd2-proxy/pull/2167#issuecomment-1397733190).

The proxy measures latency based on time to first byte, so response latencies are currently recorded as soon as the first `DATA` frame in an HTTP/2 body stream is received. However, because `grpc-status` is sent in a `TRAILERS` frame that terminates the body stream, we cannot classify the response as a success or failure until the stream ends or a `TRAILERS` frame is received. In the case of a long-running streaming gRPC request, the stream may not end for a very long time after the first data is received, so a simple change to only record latencies once the response is classified would prevent latencies for streaming responses from being recorded for much longer than they are currently. 

A potential solution that would allow labeling response latencies with response classifications would be to change how response classification works so that non-gRPC HTTP responses are classified based on the status code without waiting for trailers, allowing the classification to be recorded on the latency metrics. However, this is a much larger change to how the proxy records response metrics.

For now, we should update the docs to not make the misleading statement that classification labels are present on all `response_` metrics.
