### ISSUE TITLE
Make `linkerd check` smarter about webhook certificate expiration warnings

### ISSUE THREAD

**Issue by philomory** [linkerd/linkerd2#9747]
### What problem are you trying to solve?

Currently, `linkerd check` issues a warning if your webhook certificates will expire in 60 days or less, which I feel is perhaps overzealous in the face of certificates whose total lifespan between `notBefore` and `notAfter` is only 24 hours.

### How should the problem be solved?

When checking webhook certificate lifespan, `linkerd check` should consider the total lifespan implied by `notBefore` and `notAfter`, in addition to the amount of time remaining between the present moment and `notAfter`. A warning could be issued if the remaining period of validity is less than (for example), 60 days or 30% of the total lifespan of the certificate, whichever is less (I suggest 30% because it would line up well with the default `renewBefore` value in `cert-manager`, but anything in the range of 15-40% would probably be fine).

### Any alternatives you've considered?

Currently we've set our webhook certificates to have a lifespan of 62 days, and get renewed when they have 61 days remaining. This is our attempt to webhook certificates renewed automatically on a daily basis, but not get warnings due to having fewer than 60 days remaining.

### How would users interact with this feature?

By default they shouldn't have to, although as an optional bonus feature `linkerd check` could take a command line flag indicating the minimum acceptable remaining certificate lifespan, in which case the user could interact with the feature by running e.g. `linkerd check --min-cert-life-remaining 30d` or `linkerd check --min-cert-life-remaining 10%`, or similar. If such a flag were added, the default behavior when the flag is not supplied could be as described above, or it could be left as the current behavior.

### Would you like to work on this feature?

maybe

**Comment by jeremychase** [comment]
Related to #9612

**Comment by philomory** [comment]
I'll not that while this is related to #9612, the solution/workaround from #9612 doesn't work here, because this is about warnings presented to a human user, not warnings you need to get a CI system to ignore; while a human user _can_ of course be told to ignore certain specific warnings (even easier than teaching a CI system to do so), ignoring warnings is a dangerous habit to get into, and it's much preferable to be able to suppress specific warnings (or have them intelligently suppressed by default) rather than getting into a bad habit which may result in ignoring other, still-relevant warnings down the road.
