### ISSUE TITLE
Fix ARM testing

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#9752]
At the very least, we need to re-provision our ARM testing host. But our ARM test host can be a source of flakiness in releases. Can we move it into actions? Or is there a better way to manage this environment?

**Comment by olix0r** [comment]
This may very likely end up being more trouble than it's worth, so we should timebox investigation.

I think the best solution would be to setup a [self-hosted runner](https://docs.github.com/en/actions/hosting-your-own-runners), but I'm not sure how much work that is in practice.

**Comment by alpeb** [comment]
Fixed by #9830
