### ISSUE TITLE
Add port `6443` to the default list of skipped ports for control plane components

### ISSUE THREAD

**Issue by mateiidavid** [linkerd/linkerd2#9817]
It is possible for the control plane to get stuck when installing Linkerd, if the environment makes use of a CNI plugin that replaces `kube-proxy` with ebpf based solutions (e.g #8591).

Cilium (and other ebpf-based CNIs) can do socket-level load balancing, which has the downside of changing the target from the `ClusterIP` to the actual backend during the tcp `connect` syscall.

> sockets are assigned to service backends directly, e.g. at TCP connect time [[1]](https://docs.cilium.io/en/v1.9/gettingstarted/kubeproxy-free/#maglev-consistent-hashing-beta)

By default, the Kubernetes api server listens on `6443`, this can be changed by users when clusters are rolled out, but should be pretty consistent across managed distributions. The default is documented in the [official reference](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/). 

```
--secure-port int     Default: 6443
  | The port on which to serve HTTPS with authentication and authorization. It cannot be switched off with 0.
```

**The implication for Linkerd's control plane**: containers (e.g identity, destination) will talk directly to _6443_, instead of 443, which is not skipped by default. This requires manual patching as the control plane is not injected automatically. We should include `6443` in the list of default skipped ports. This would require us to change the CNI plugin source code (which hardcodes 443 as a skipped port for control plane components), and the helm charts.

**Comment by adleong** [comment]
Would it make sense to get this value from the kubernetes API by looking at the endpoints of the kubernetes service?

```
> lkubectl get ep/kubernetes -o jsonpath='{.subsets[*].ports[*].port}'
6443
```

**Comment by mateiidavid** [comment]
Yes and no. Looking at the port programatically would work well when the cni plugin is used because the control plane passes through the cni chain at pod creation time, but it wouldn't work when we use the init container since we'd expect to have the skipped port in the manifest.

* On the cni plugin side, we look at the `linkerd.io/control-plane-component` annotation, and if it is set, we skip port 443. We could definitely look at the endpoints and also skip whatever port the apiserver actually listens on.
* On the init container side, we could potentially do that through the cli and patch the template. But the helm installation wouldn't support it.

Using the `downwardAPI` was an option. There is no environment variable that exposes the port of the backend though, so there's no way to wire it through the API.

@alpeb tagging you here in case you might know of a way to get this port using a Helm hook or special function.

**Comment by alpeb** [comment]
- The `lookup` function allows to query the k8s api to extract any object and then we can extract that port, all that during `helm install`. However I've become wary about that kind of magic because it doesn't work with `helm template` which apparently some tools depend on (like ArgoCD).
- Hooks are executed after the templates are rendered, so there's no way to modify a values.yaml entry or affect a resource template through that mechanism.

:-(

**Comment by adleong** [comment]
However, `linkerd install` could use the k8s api to determine this port and add it as value when rendering the templates.  This doesn't help for Helm installs, but we could default it to 6443 and document that it needs to be configured if a port other than 6443 is used.
