### ISSUE TITLE
proxy: call to getsockopt causes Linux kernel versions between 4.14.22 and 4.14.40 to deadlock

### ISSUE THREAD

**Issue by hawkw** [linkerd/linkerd2#982]
In Linux kernel versions between 4.14.22 and 4.14.40, there appears to be a bug that can cause the kernel to deadlock on calls to the `getsockopt` syscall with certain options. These options include `SO_ORIGINAL_DST`, which Conduit relies on.

I did a bit of digging, and I'm fairly sure this bug was introduced into the kernel in torvalds/linux@516c855cf51462678eb50ec52da845c10734d0bf and fixed in torvalds/linux@485595768d89f53581a7527285acf97880fc65a6.

As far as I know, there's nothing that can be done to resolve this issue (as it was already fixed in the kernel) beyond avoiding the affected versions.

**Comment by briansmith** [comment]
> As far as I know, there's nothing that can be done to resolve this issue (as it was already fixed in the kernel) beyond avoiding the affected versions.

There is an alternative mechanism to `SO_ORIGINAL_DST` called TPROXY which is described in https://blog.cloudflare.com/mmproxy-creative-way-of-preserving-client-ips-in-spectrum/ that I believe we could and probably should switch to at some point.

**Comment by missnebun** [comment]
Is this affecting CentOS 7.5 The kernel is  3.10.0-862.el7.x86_64

**Comment by briansmith** [comment]
According to https://github.com/istio/istio/issues/5723#issuecomment-396491765:
> GKE 1.10.4-gke.0 is rolling out this week, and it contains the fix of this issue.

**Comment by ihcsim** [comment]
I just tested this with 1.10.5-gke.0 running CoS; seems to be working.
```
$ conduit version
Client version: v0.5.0
Server version: v0.5.0
$ kubectl version --short
Client Version: v1.10.1
Server Version: v1.10.5-gke.0
$ conduit check
kubernetes-api: can initialize the client..................................[ok]
kubernetes-api: can query the Kubernetes API...............................[ok]
kubernetes-api: is running the minimum Kubernetes API version..............[ok]
conduit-api: can query the Conduit API.....................................[ok]
conduit-api[kubernetes]: control plane can talk to Kubernetes..............[ok]
conduit-api[prometheus]: control plane can talk to Prometheus..............[ok]
conduit-version: cli is up-to-date.........................................[ok]
conduit-version: control plane is up-to-date...............................[ok]

Status check results are [ok]
```

It's still using the 4.14.22 kernel, but someone fixed something somewhere...
```
gke-main-default-pool-fe70e08a-v9xq ~ $ uname -a
Linux gke-main-default-pool-fe70e08a-v9xq 4.14.22+ #1 SMP Wed May 30 13:49:27 PDT 2018 x86_64 Intel(R) Xeon(R) CPU @ 2.20GHz GenuineIntel GNU/Linux
```
