### ISSUE TITLE
Inbound requests to a pod(meshed with Linkerd proxy) at a network attachment IP (other than the PodIP) is rejected by Linkerd.

### ISSUE THREAD

**Issue by pranab19sah99** [linkerd/linkerd2#9840]
### What is the issue?

I'm facing an issue that Linkerd is only allowing inbound connections at the PodIP of the meshed service/Pod. But I have one network interface also in the Pod and I want to send request at that IP. When I send request at the interface IP without the Linkerd mesh, I'm able to get the response.

Scenario:-
I've a serviceA and a serviceB. We've attached one additional network interface to the services (I'll paste the Pod config below for reference). 
The serviceA sends request to serviceB at the interface IP. 

Call flow:-
`serviceA -> serviceB -> serviceA`

pod config:-
```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/podIP: 10.233.112.144/32
    cni.projectcalico.org/podIPs: 10.233.112.144/32
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "",
          "ips": [
              "10.233.112.144"
          ],
          "default": true,
          "dns": {}
      },{
          "name": "system/network1",
          "interface": "eth1",
          "ips": [
              "10.2.28.14"
          ],
          "mac": "00:50:56:a3:68:01",
          "dns": {}
      }]
    k8s.v1.cni.cncf.io/networks: '[{"name": "network1","interface":
      "eth1","ips": ["10.2.28.14/24"]}]'
```
Pasting a log line from the Linkerd proxy container of serviceB, that says linkerd is blocking inbound connections.
```[   141.961188s] DEBUG ThreadId(01) inbound:accept{client.addr=10.2.28.13:24329}:server{port=8046}:      linkerd_app_core::transport::allow_ips: Target IP address not permitted addr=10.2.28.14:8046 allowed     ={10.233.112.144}```
Here `10.2.28.14` is the network attachment IP
and `10.233.112.144` is the PodIP.

I think I found the config due to which this is happening. There's an environment variable in linkerd charts which is pointing to PodIPs. Please refer the code snippet below.
```
- name: LINKERD2_PROXY_INBOUND_IPS
  valueFrom:
    fieldRef:
      fieldPath: status.podIPs
```

Is there any workaround for this? to allow inbound connections at the network attachment IP also?

Pod Status:- `kubectl describe pod <pod-name> -n <namespace>`
```
Status:       Running
IP:           10.233.112.144
IPs:
  IP:           10.233.112.144
```
It would not be a problem if Linkerd would be allowing inbound connections at all the IPs available to the pod. Or if Kubernetes (k8s) would be listing all the interface IPs of the pod under the `status.podIPs` field, although k8s is not blocking the connections as without linkerd my call flow was successful.

I'm not sure if there's a config in k8s to update/add the interface IP to PodIPs nor we could find a config in linkerd to change/add the linkerd proxy inbound IPs

If any more information can help, I'll be happy to post here.

### How can it be reproduced?

1. Deploy Linkerd on a k8s cluster.
2. Deploy an application with 2 services at least. Add an additional network interface should be added to the services/Pods. So that other pods can communicate with the pod at both the IPs (PodIP assigned by k8s and the interface IP).
Note: Replica for my services is one only.
3. Mesh the serviceA and serviceB with linkerd-proxy.
4. Send request from serviceA to serviceB at the network attachment IP.

We should be able to observe that the connections are getting refused by the serviceB linkerd proxy container.

### Logs, error output, etc

Logs from linkerd proxy container of serviceA:-
```
[ 27004.540653s]  INFO ThreadId(01) outbound:server{orig_dst=10.2.28.14:8046}: linkerd_app_outbound::http::proxy_connection_close: Received unmeshed response with l5d-proxy-connection set
[ 27064.533036s]  INFO ThreadId(01) outbound:server{orig_dst=10.2.28.14:8046}:rescue{client.addr=10.2.28.12:42353}: linkerd_app_core::errors::respond: Request failed error=connection error: client: Connection reset by peer (os error 104)
```
Debug log from linkerd proxy container of serviceB:
`[   141.961188s] DEBUG ThreadId(01) inbound:accept{client.addr=10.2.28.13:24329}:server{port=8046}:      linkerd_app_core::transport::allow_ips: Target IP address not permitted addr=10.2.28.14:8046 allowed     ={10.233.112.144}`
here `10.2.28.14` is the network attachment IP
and `10.233.112.144` is the PodIP.

pod config:-
```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/podIP: 10.233.112.144/32
    cni.projectcalico.org/podIPs: 10.233.112.144/32
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "",
          "ips": [
              "10.233.112.144"
          ],
          "default": true,
          "dns": {}
      },{
          "name": "system/network1",
          "interface": "eth1",
          "ips": [
              "10.2.28.14"
          ],
          "mac": "00:50:56:a3:68:01",
          "dns": {}
      }]
    k8s.v1.cni.cncf.io/networks: '[{"name": "network1","interface":
      "eth1","ips": ["10.2.28.14/24"]}]'
```
Linkerd proxy environment variable from the Liknerd templates:-
```
- name: LINKERD2_PROXY_INBOUND_IPS
  valueFrom:
    fieldRef:
      fieldPath: status.podIPs
```

### output of `linkerd check -o short`

I haven't installed linkerd CLI. I'm deploying the Linkerd using helm charts.

### Environment

- Kubernetes version: v1.19.2
- Linkerd version: stable-2.11.4

### Possible solution

Expected solution:-
Linkerd should allow inbound requests at all the IPs available in the Pod.

**Comment by mateiidavid** [comment]
Hey @pranab19sah99, Linkerd uses the [downward API](https://kubernetes.io/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/) to inject the pod's IP in the `LINKERD2_PROXY_INBOUND_IPS` environment variable. Traffic is only allowed when the target IP corresponds to that of the pod.

In your case, it seems that [multus-cni](https://github.com/k8snetworkplumbingwg/multus-cni/blob/master/README.md) (which I assume you're using to create your other network interface) provisions a network interface but it never updates the pod's status. As far as the k8s API Server is concerned, the pod only has one IP that it is reachable at.

It makes sense that other connections work when the pod is unmeshed. Since the network interface is created by (presumably) multus, routing works; at a higher level though, it is impossible for pods to be aware of the fact that they have more than one IP address. 

```json
  k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "",
          "ips": [
              "10.233.112.144"
          ],
          "default": true,
          "dns": {}
      },{
          "name": "system/network1",
          "interface": "eth1",
          "ips": [
              "10.2.28.14"
          ],
          "mac": "00:50:56:a3:68:01",
          "dns": {}
      }]
    k8s.v1.cni.cncf.io/networks: '[{"name": "network1","interface":
      "eth1","ips": ["10.2.28.14/24"]}]'
```

Is there anything in the above configuration that you can modify to make the podStatus include both IP addresses? For your possible solution you say that Linkerd should allow all requests to IPs available in the pod, but like I mentioned, Linkerd gets the IP addresses off the pod's status.

**Comment by pranab19sah99** [comment]
Workaround:-
We can use an External IP for the service and make request at the External IP. This way the k8s will handle the request to send at the pod IP. And the pod IP is known to the Linkerd hence it allows inbound connections.

Although, there should be a solution for multiple IPs of a pod. Linkerd should allow inbound connections at all IPs of the Pod or there could be option to configure the pod IP(s) that Linkerd will allow inbound connections to.

**Comment by pranab19sah99** [comment]
As there's a work around for this and it's not really a blocker, I'll close the issues.
