### ISSUE TITLE
Provide debuginfos for linkerd2-proxy

### ISSUE THREAD

**Issue by brancz** [linkerd/linkerd2#9894]
### What problem are you trying to solve?

I'm trying to profile the linkerd2-proxy, among everything else in my infrastructure, to understand where on a global level all CPU resources are being spent. The linkerd2-proxy, while efficient is meant to be deployed in practically every pod in a Kubernetes, cluster so while an individual container may not use a lot of resources, it would be great to understand what that looks like globally.

### How should the problem be solved?

To do this, debuginfos need to be available somehow. This could be in a variety of different ways. My preference would be to produce debuginfos as part of the build process of the linkerd2-proxy, when creating the release tarball. Using the recently stabilized [`split-debuginfo`](https://doc.rust-lang.org/cargo/reference/profiles.html#split-debuginfo) configuration option, the production binary would be created and in a separate file the debuginfos would be written. These debuginfos can then be separately distributed, ideally through a [`debuginfod`](https://sourceware.org/elfutils/Debuginfod.html) server, from where profilers and debuggers can automatically find the debuginfos using the binary's BuildID (which are identical in the "production" binary and the debuginfo file, that's how they're linked).

I think distributing the binary and the debuginfos this way it the best as there is only ever a single binary being produced per release, removing the possibility that the debug build it in any way different from a non-debug build.

### Any alternatives you've considered?

There could be other ways, just like having a container images that contains a binary that has the debuginfos included. This would work as well, but it would require a user to explicitly change the infrastructure to make it debuggable, which is not ideal.

### How would users interact with this feature?

Users would primarily interact with it indirectly, as it enables profilers such as [Parca](https://www.parca.dev/) to discover the debuginfos automatically without the user having to do anything. Same goes for regular Linux `perf` as well as debuggers such as `gdb` or `delve`.

### Would you like to work on this feature?

maybe

**Comment by brancz** [comment]
I want to clarify why I selected "maybe" on whether I'd like to work on this. I'd be happy to be a supporting function, but since this is primarily build pipeline work and I very rarely interact with the rust ecosystem, I find it hard to believe that I'd be of much use. I'd be more than happy to do anything I can though!

**Comment by brancz** [comment]
Also for reference, I have tried to build a container image with the `debug=1` flag (which includes sufficient debuginfos to get the above things working), and here are some stats:

#### Builing from v2.188.0 release with zero modifications
```
[+] Building 332.9s (21/21) FINISHED
localhost/linkerd/proxy   HEAD.4e172043     a57cf56c46e4   4 minutes ago    92.7MB
```
#### Building from v2.188.0 release with `debug=1`
```
[+] Building 377.6s (21/21) FINISHED
localhost/linkerd/proxy   HEAD.4e172043     8566dec1a8f5   20 minutes ago   978MB
```
#### Change
This means there is approximately a ~13% increase in build time and about 10-11x artifact size.

**Comment by brancz** [comment]
cc @stevej @olix0r @siggy

**Comment by alpeb** [comment]
As pointed out in https://github.com/linkerd/linkerd2/issues/10227#issuecomment-1419875006 debug-info is already being produced by the proxy build, so closing this one out.

**Comment by brancz** [comment]
🥳 🎉
