### ISSUE TITLE
ServiceProfile spec document does not describe "dstOverrides" field.

### ISSUE THREAD

**Issue by luucaocuong** [linkerd/linkerd2#9915]
### What is the issue?

Linkerd uses the "dstOverrides" of the ServiceProfile resource to define the traffic split, however, the spec document does not describe the "dstOverrides" field.
Document link: https://linkerd.io/2.12/reference/service-profiles/

### How can it be reproduced?

Check the document: 
- Document link: https://linkerd.io/2.12/reference/service-profiles/

### Logs, error output, etc

Now it only describes "routes" and "retryBudget"

### output of `linkerd check -o short`

 https://linkerd.io/2.12/reference/service-profiles/

### Environment

- Linkerd  2.12

### Possible solution

Add document for dstOverrides

**Comment by alpeb** [comment]
Note that this is being replaced by the new HTTPRoute functionality coming out in 2.13, for which new docs will be provided.
