### ISSUE TITLE
Add `--set` flag for `linkerd-cni`

### ISSUE THREAD

**Issue by mateiidavid** [linkerd/linkerd2#9917]
The CNI plugin can be installed either through Helm or the CLI (`linkerd install-cni`). The CNI plugin CLI install command should support the same templating of helm values as the normal linkerd CLI install. 

For example, https://github.com/linkerd/linkerd2/pull/9874 adds support for resources in the CNI plugin's helm chart. At the moment, this is not usable with the CLI since there is no support for `--set`.

**Comment by amit-62** [comment]
Hello @mateiidavid I would like to work on this issue. But it is going to be first issue here. How should I proceed.

**Comment by alpeb** [comment]
That's awesome @amit-62 :+1: 
The Jaeger extension is the simpler one we have, so I think you can study its `cmd` package as an example to see how to wire that up for `linkerd-cni`.

`linkerd jaeger install` is driven by [install.go](jaeger/cmd/install.go), and the handling of the `--set` flag is managed via [this call](https://github.com/linkerd/linkerd2/blob/main/jaeger/cmd/install.go#L85). You can jump into our [Slack's](https://slack.linkerd.io/) #contributors channel and we'll be glad to provide more pointers if needed.

**Comment by amit-62** [comment]
I will try to solve this issue.

**Comment by amit-62** [comment]
Hello @alpeb currently we are setting each value in [values.yaml](https://github.com/linkerd/linkerd2/blob/main/charts/linkerd2-cni/values.yaml) individually from [install-cni-plugin.go](https://github.com/linkerd/linkerd2/blob/main/cli/cmd/install-cni-plugin.go) if we add support for `--set` flag then we can set each value using `--set` flag. Or we can directly add a new sub-command for `resources`. Am I going in right direction? Please suggest how should I prcceed.

**Comment by alpeb** [comment]
> currently we are setting each value in [values.yaml](https://github.com/linkerd/linkerd2/blob/main/charts/linkerd2-cni/values.yaml) individually from [install-cni-plugin.go](https://github.com/linkerd/linkerd2/blob/main/cli/cmd/install-cni-plugin.go) if we add support for `--set` flag then we can set each value using `--set` flag.

That's correct, this is the intention of the current issue.

> Or we can directly add a new sub-command for `resources`. Am I going in right direction?

Why adding a sub-command? This should be supported as flags directly into the `linkerd install-cni` command. My recommendation is to first get familiar with how the CLI code deals with flags, for example looking at the jaeger extension, and then you can expand the functionality in `install-cni-plugin.go` to account for the family of `--set` flags.

**Comment by amit-62** [comment]
Thank you @alpeb I will do as suggested.

**Comment by amit-62** [comment]
Hello @alpeb please review my PR [#10353](https://github.com/linkerd/linkerd2/pull/10353) and suggest improvement.
