### ISSUE TITLE
Label linkerd deployments with `app.kubernetes.io/name`

### ISSUE THREAD

**Issue by NissesSenap** [linkerd/linkerd2#9932]
### What problem are you trying to solve?

I'm currently want to visualize my linkerd traffic using cilium hubble but the UI reports the linkerd endpoints as `Unknown App`.
This is due to the missing of `app.kubernetes.io/name` as a pod label.

+ it's best practice to use `app.kubernetes.io/name` as one of your labels

### How should the problem be solved?

Add the label `app.kubernetes.io/name` to all linkerd deployments

### Any alternatives you've considered?

N/A

### How would users interact with this feature?

They will be able to use use label selectors that matches `app.kubernetes.io/name`

### Would you like to work on this feature?

yes

**Comment by mateiidavid** [comment]
You might be able to apply them yourself in recent edge releases (`edge-22.11.1+`) through `commonLabels`.

https://github.com/linkerd/linkerd2/tree/main/charts/linkerd-control-plane#values
https://github.com/linkerd/linkerd2/blob/main/charts/linkerd-control-plane/values.yaml#L55-L56

**Comment by NissesSenap** [comment]
Yeah it sounds like a possible workaround.
I guess I would argue that it would be reasonable that linkerd would follow the "standard" kubernetes labeling.
So instead of having an empty commonLabels it should contain some defaults.

I didn't look if all helm charts got the new `cmmonLabels` but if they didn't that should probably be done as well.
What do you think @mateiidavid ?
