### ISSUE TITLE
FailedPostStartHook for ProxyInjector and Destination pods during Helm Chart Install

### ISSUE THREAD

**Issue by coffee-time-design** [linkerd/linkerd2#9958]
### What is the issue?

I am running K3S with Calico.
When installing the helm chart I run the CNI Plugin Chart, then the CRDs chart then finally the Control Plane chart.
VERSION=edge-22.12.1
CHARTVERSION=1.9.4
But issue exists with other versions I have tried.

Without fail, every time I run the install, the identity and CNI pods come up but the destination and proxy injectors fail with: FailedPostStartHook.

### How can it be reproduced?

Install k3s, cert-manager, create certificates for Linkerd with cert-manager, then install the three charts for Linkerd.

### Logs, error output, etc

Exec lifecycle hook ([/usr/lib/linkerd/linkerd-await --timeout=2m]) for Container "linkerd-proxy"

### output of `linkerd check -o short`

Status check results are √

### Environment

v1.24.6+k3s1
Hosts are Ubuntu 22.04

### Possible solution

kubectl delete --all pods --namespace=linkerd after kubectl rollout status -w --timeout=300s daemonset/linkerd-cni -n linkerd-cni is true.
Fixes the issue every time, which leads me to believe that the issue is something to do with the order in which the pods start.

### Would you like to work on fixing this bug?

no

**Comment by kleimkuhler** [comment]
Could you please provide `linkerd-proxy` logs for the components failing to come up? It's possible they are failing to come up for some reason—lets say something with CertManager—and then the PostStart hook is unable to complete because the proxy never becomes ready.

**Comment by coffee-time-design** [comment]
The log is filled with:
`linkerd-identity-75dffd4468-qb7tg linkerd-proxy 2023-02-06T13:10:36.638589257+10:00 [   192.021517s]  WARN ThreadId(01) policy:watch{port=4191}:controller{addr=linkerd-policy.linkerd.svc.cluster.local:8090}: linkerd_app_core::control: Failed to resolve control-plane component error=failed SRV and A record lookups: failed to resolve SRV record: no record found for Query { name: Name("linkerd-policy.linkerd.svc.cluster.local."), query_type: SRV, query_class: IN }; failed to resolve A record: no record found for Query { name: Name("linkerd-policy.linkerd.svc.cluster.local."), query_type: AAAA, query_class: IN } error.sources=[failed to resolve A record: no record found for Query { name: Name("linkerd-policy.linkerd.svc.cluster.local."), query_type: AAAA, query_class: IN }, no record found for Query { name: Name("linkerd-policy.linkerd.svc.cluster.local."), query_type: AAAA, query_class: IN }]`
