### ISSUE TITLE
Doc contains misleading note regarding automountServiceAccountToken feature

### ISSUE THREAD

**Issue by kozart** [linkerd/linkerd2#9970]
### What problem are you trying to solve?

There is a note on this page https://linkerd.io/2.12/tasks/validating-your-traffic/ that says: `Linkerd uses Kubernetes ServiceAccounts to define service identity. This requires that the automountServiceAccountToken feature (on by default) has not been disabled on the pod`
In the sane time starting from `edge-21.11.1` release `injection also works on pods with automountServiceAccountToken set to
false` https://github.com/linkerd/linkerd2/releases/tag/edge-21.11.1

### How should the problem be solved?

Misleading note should be removed

### Any alternatives you've considered?

Misleading note should be restated to reflect actual information

### Would you like to work on this feature?

None

**Comment by alpeb** [comment]
Good catch, thanks @kozart :+1: 
I've pushed linkerd/website#1547 addressing this.
