### ISSUE TITLE
Linkerd init containers are running with privilege escalation even turned off through helm chart

### ISSUE THREAD

**Issue by Vamsi0473** [linkerd/linkerd2#9998]
### What is the issue?

Hi all, we have OPA rules configured in our cluster which blocks any container that runs with allowPrivilegeEscalation: true, so I have set all the allowPrivilegeEscalation references to false in helm charts with linkerd 2.12.2 version i.e linkerd-control-plane and linkerd-crds  charts and installed in our cluster. After which when I try to inject linkerd to one of our application pod I am ended OPA gatekeeper blocking with following error message: 'admission webhook "validation.gatekeeper.sh" denied the request: [psp-allow-privilege-escalation-container] Privilege escalation container is not allowed: linkerd-init'. Can someone please help me in understanding why this behavior is being observed I have modified the charts to set allowPrivilegeEscalation to false as below
![image](https://user-images.githubusercontent.com/46375277/207134802-96eb6b6e-a927-4f36-87ff-34a964e37ced.png)

and deployed linkerd crds and linkerd control plane but I am ending up with same issue. I did also check the security contexts after deploying where I can see allowPrivilegeEscalation to be false

### How can it be reproduced?

Try to install linkerd crds and linkerd control plane through Helm charts of version 2.12.2 by modifying allowPrivilegeEscalation: false. Then try to inject linkerd using annotation in deployment then if in the environment you have OPA rules which blocks pod initialization containers having privilege escalation then your deployment fails with that error since linkerd proxy injector is trying to inject linkerd-init container with privilege escalation

### Logs, error output, etc

message: 'admission webhook "validation.gatekeeper.sh" denied the request: [psp-allow-privilege-escalation-container]
      Privilege escalation container is not allowed: linkerd-init'

### output of `linkerd check -o short`

we can't install linkerd cli in our machine

### Environment

Kubernetes Version - 1.22
Cluster Environment - EKS
Host OS - Linux
Linkerd verison - 2.12.2

### Possible solution

Linkerd init container should run without privilege escalation container privileges

### Would you like to work on fixing this bug?

None

**Comment by alpeb** [comment]
I'm not able to replicate this issue. How do your custom values.yaml entries look like, in particular for `proxyInit`? How are you consuming your modied version of  the `linkerd-control-plane` chart? Also, note linkerd stable-2.12.3 now includes a setting `proxyInit.privileged` that allows you to control that entry more directly.

**Comment by Vamsi0473** [comment]
Thanks @alpeb  after moving to stable-2.12.3 we are not facing this issue
